<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13885>Orc Pawn Pick</a><li><a href=http://phobos/eq/item.php?id=12272>Bag of Cutthroat Rings</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17975>Bag for Cutthroat Rings</a><li><a href=http://phobos/eq/item.php?id=12273>Militia Armory Token</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a><li><a href=http://phobos/eq/faction.php?id=48>Coalition of Tradefolk Underground</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a><li><a href=http://phobos/eq/faction.php?id=258>Priests of Marr</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Guard Valon says </b>'Greetings, traveler! If you wish to walk upon the road to Freeport, you will pay the toll of two silver pieces. And you should. It is not safe to stray from the pathway. There are many [dangers in the Commonlands].'
<p><b>You say, </b>'dangers in the commonlands'
<br><b>Guard Valon says </b>'The orcs have been a nuisance of late. Many travelers have perished at the hands of the orc pawns. Would you like to [assist the Freeport Militia] in ridding the lands of the orcs?'
<p><b>You say, </b>'assist the freeport militia'
<br><b>Guard Valon says </b>'Sir Lucan would be proud!! Patrol the Commonlands and watch for any orc pawns. Should you find any orc pawn picks on them, I will pay you for every four you return to me. Be off, then! For the glory of Freeport!!'
<p><b>You say, </b>'hunt dervish cutthroats'
<br><b>Guard Valon says </b>'You will make a fine reserve!! Take this bag and fill it with Dervish Cutthroat Insignia Rings. When they are combined and returned to me you shall be accepted into the Reserve Freeport Militia!!'
<br><b>Guard Valon gives you : </b><a href=http://phobos/eq/item.php?id=17975>Bag for Cutthroat Rings</a>
<p><b>You give Guard Valon : </b><a href=http://phobos/eq/item.php?id=13885>Orc Pawn Pick</a> x4
<br><b>Guard Valon says </b>'You have done well. Keep up the good work and we may trust you to [hunt dervish cutthroats] which in turn will allow you to join the Reserve Freeport Militia.'
<br><b>You receive </b> 1gp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=48>Coalition of Tradefolk Underground</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=258>Priests of Marr</a> has gotten worse.</font>
<p><b>You give Guard Valon : </b><a href=http://phobos/eq/item.php?id=12272>Bag of Cutthroat Rings</a>
<br><b>Guard Valon says </b>'Excellent work, [Your Name]!! You are quite formidable. Maybe soon you shall aid in our efforts to rid the Northern part of Freeport of the paladins!! Until then keep up the good work. Take this Armory Token to the Militia Armorer
in the Militia House in Freeport to receive your tunic. He may not be there, but I assure you he will show up at some time. On the second floor. Hail Sir Lucan!!'
<br><b>Guard Valon gives you : </b><a href=http://phobos/eq/item.php?id=12273>Militia Armory Token</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=48>Coalition of Tradefolk Underground</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=258>Priests of Marr</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>