<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28035>Token of Mastery</a><li><a href=http://phobos/eq/item.php?id=28000>Torn Page of Magi`kot pg. 1</a><li><a href=http://phobos/eq/item.php?id=28001>Torn Page of Magi`kot pg. 2</a><li><a href=http://phobos/eq/item.php?id=28002>Torn Page of Magi`kot pg. 3</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28003>Words of Magi`kot</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Jahsohn Aksot says </b>'Greetings, [Your Name].'
<p><b>You say, </b>'rykas gave it to me'
<br><b>Jahsohn Aksot says </b>'I have not heard of anyone speaking that name out loud in years. Rykas once shared a tale with me, though I have lived with fear in my mind ever since. He told me afterwards that I did not have the balance I thought I had. Have you come for the Words of Magi'kot?'
<p><b>You say, </b>'words'
<br><b>Jahsohn Aksot says </b>'The Words of Magi'kot can only be shared with those elementalists whose minds are of balance. The Words were separated into three pieces by a high council of Magi who feared that the story would bring an end to elementalists throughout Norrath. If you feel you wish to read from the sacred Power of the Orb then an elementalist of such power should easily accomplish this task.'
<p><b>You say, </b>'what task'
<br><b>Jahsohn Aksot says </b>'Bring me the torn pages of Magi'kot. The first section can be found in the depths of a tainted forest, warded by an angry lupine. It is also rumored that one section is found in the haunted estate of a murderer, on a many armed creature. The last may be found in the belly of an amphibian who thirsts for blood.'
<p><b>You give Jahsohn Aksot : </b><a href=http://phobos/eq/item.php?id=28035>Token of Mastery</a>
<br><b>Jahsohn Aksot says </b>'What is this? I cannot believe you found it! Where did you get this?'
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Jahsohn Aksot : </b><a href=http://phobos/eq/item.php?id=28000>Torn Page of Magi`kot pg. 1</a>, <a href=http://phobos/eq/item.php?id=28001>Torn Page of Magi`kot pg. 2</a>, <a href=http://phobos/eq/item.php?id=28002>Torn Page of Magi`kot pg. 3</a>
<br><b>Jahsohn Aksot says </b>'Rykas may have been right about you, [Your Name]. Now, go find Walnan. Walnan was apprenticed to a very powerful Mage. After her apprenticeship was complete, she wished to begin teaching other beings of Norrath. Even those who knew nothing of the art! I do not believe she was successful, though. Seek her out to further your tale. Good luck in your journeys, [Your Name]!'
<br><b>Jahsohn Aksot gives you : </b><a href=http://phobos/eq/item.php?id=28003>Words of Magi`kot</a>
<br><b>Jahsohn Aksot says </b>'I do not need these.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>