<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18891>A Tattered Cloth Note</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Kizdean Gix says </b>'If you have business then out with it!! If not, then please be gone. I have little time to waste on chitchat!'
<p><b>You say, </b>'Utalk Adarev Otcin'
<br><b>Kizdean Gix says </b>'You speak the words of the Dead. You must be the assistance Loveal was to send. You must work quickly! Inside Befallen are the three pieces to the [Thex Mallet] which are to be returned to Loveal. Find Hubard L'rodd. He was my assistant. Give him this note and he should have information.'
<br><b>Kizdean Gix gives you : </b><a href=http://phobos/eq/item.php?id=18891>A Tattered Cloth Note</a>
</td></tr></table>