<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=17931>A 'Sparkle' Purse</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12352>A Tiny Key</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Noresa Sparkle says </b>'He.. Hello. Wou.. would you like to buy something? Be quick or [Kizdean] will return!'
<p><b>You say, </b>'Kizdean'
<br><b>Noresa Sparkle says </b>'Sshhh..Please..save me. Get..rid..of..him.'
<p><b>You give Noresa Sparkle : </b><a href=http://phobos/eq/item.php?id=17931>A 'Sparkle' Purse</a>
<br><b>Noresa Sparkle says </b>'Oh!!! Thank you. You are my hero. I have been held captive by that horrid dark elf for weeks. Please take this. It was the key to a gem case which was stolen from me by an unseen rogue. If you find the gem case you can take it and the key to the original craftsman. He can open it with only two keys.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Noresa Sparkle gives you : </b><a href=http://phobos/eq/item.php?id=12352>A Tiny Key</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>