<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=6708>A Gem Encrusted Casket</a><li><a href=http://phobos/eq/item.php?id=6709>Revenant Ash</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15693>Spell: Divine Might</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=258>Priests of Marr</a><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Simon Aldicott says </b>'Hail and well met. I am Simon Aldicott, a cleric in the service of Mithaniel Marr. I've been sent here to prepare a funeral service for one of our lost to join Marr in his kingdom.'
<p><b>You say, </b>'funeral service'
<br><b>Simon Aldicott says </b>'Are you the brave knight whom Valeron sent to meet me here? If so please place the remains in the coffin and seal it. Then hand me the coffin so that we may bless it in the waters of this lake.'
<p><b>You give Simon Aldicott : </b><a href=http://phobos/eq/item.php?id=6708>A Gem Encrusted Casket</a>
<br><font color=green><b>Simon Aldicott </b>places the coffin in the water and begins to pray. 'Lord of Valor high above, take this knight, your loyal child, into thy kingdom and all that is holy! What is that thing!'</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=21031>a_Tortured_Revenant</a></b> spawns (259.7,2901,-51).</font>
<p><b>You give Simon Aldicott : </b><a href=http://phobos/eq/item.php?id=6709>Revenant Ash</a>
<br><b>Simon Aldicott says </b>'Thank you, Knight. With this task accomplished, I shall reward you with this scroll. It is an ancient spell that only the holiest of knights may cast. Remember your duty!'
<br><b>Simon Aldicott gives you : </b><a href=http://phobos/eq/item.php?id=15693>Spell: Divine Might</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=258>Priests of Marr</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>