<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Wallin Slyfoot says </b>'Hello [Your Name].  I'm a bit busy right now, no time to chat.'
<p><b>You say, </b>'assist'
<br><b>Wallin Slyfoot says </b>'Hello [Your Name].  I'm a bit busy right now, no time to chat.'
<br><b>Wallin Slyfoot says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>