<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When #Emperor Ssraeshza  spawns </b>
<hr><b>When #Emperor Ssraeshza  is killed </b>
<br><font color=green><b>#Emperor Ssraeshza  </b>'s corpse says 'How...did...ugh...'</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=162210>A_shissar_wraith</a></b> spawns (-332,953,403.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=162210>A_shissar_wraith</a></b> spawns (-324,953,403.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=162210>A_shissar_wraith</a></b> spawns (-316,953,403.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=162210>A_shissar_wraith</a></b> spawns (-332,937,403.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=162210>A_shissar_wraith</a></b> spawns (-324,937,403.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=162210>A_shissar_wraith</a></b> spawns (-316,937,403.1).</font>
</td></tr></table>