<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When #Vyzh-dra the Cursed spawns </b>
<hr><b>When #Vyzh-dra the Cursed is killed </b>
<br><font color=red><b>#Vyzh-dra the Cursed shouts </b>'I cannot die! I am the only true god!'</font>
<br><font color=green><b>#Vyzh-dra the Cursed </b>crashes to the ground. A horrific sound fills the room, but vanishes as quickly as it came.</font>
</td></tr></table>