<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13464>Bixie Crunchies</a><li><a href=http://phobos/eq/item.php?id=29853>Sealed Note to Bregun</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=29852>Bixie Charm</a><li><a href=http://phobos/eq/item.php?id=29854>Bregun's Directions</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>#Bregun Dorey says </b>'Trog trog trog trog?'
<p><b>You say, </b>'trog'
<br><b>#Bregun Dorey says </b>'Ha! What are you talking about?! Strange thing you are. Wait a minute, come closer. Are you from Norrath?'
<p><b>You say, </b>'i am from norrath'
<br><b>#Bregun Dorey says </b>'I thought so, your armor looks to be made from things found not here. Have you heard of Rivervale?'
<p><b>You say, </b>'I have heard of Rivervale'
<br><b>#Bregun Dorey says </b>'Good.'
<p><b>You say, </b>'good'
<br><b>#Bregun Dorey says </b>'Yeah good! Trog trog trog trog! Hahaha! These Troglodytes don't know of Rivervale. They just run around the cave all day doing Troglodyte things. Hahaha! Trog trog trog. So what was I speaking of.. Oh Bixies! So, are there bixies around Rivervale?'
<p><b>You say, </b>'bixes.*rivervale'
<br><b>#Bregun Dorey says </b>'There are Bixies! THERE ARE BIXIES! This is great. You should hunt some Bixies, and get some Bixie parts. Then you can make me some Bixie Crunchies! Ooooh, Crunchies. I want to try the Crunchies. I think you should bring me four Crunchies!'
<p><b>You give #Bregun Dorey : </b><a href=http://phobos/eq/item.php?id=13464>Bixie Crunchies</a> x4
<br><b>#Bregun Dorey says </b>'Ah hum!'
<br><b>#Bregun Dorey gives you : </b><a href=http://phobos/eq/item.php?id=29852>Bixie Charm</a>
<br><b>#Bregun Dorey says </b>'Give this charm to Torsten as a present from his old friend.'
<p><b>You give #Bregun Dorey : </b><a href=http://phobos/eq/item.php?id=29853>Sealed Note to Bregun</a>
<br><b>#Bregun Dorey says </b>'Hahaha! Silly Torsten. Always snooping over my shoulder. Well I have nothing to lose... take this to him, it's directions on how to find the Journal I kept. I hid it where no one would look! Haha! Trog trog trog!'
<br><b>#Bregun Dorey gives you : </b><a href=http://phobos/eq/item.php?id=29854>Bregun's Directions</a>
<br><b>#Bregun Dorey disappears.</b>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>