<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=29851>Dawnshroud Cider</a></ul></td><td><p><b>You say, </b>'Where is Bregun Dorey'
<br><b>#Legionnaire Dalini says </b>'Yeah maybe I know Bregun. You know, I sure am thirsty with all this guard work I am doing. I know what I want, some Dawnshroud Cider! Yeah, go fetch me a cider and we will see if I remember anything when you get back.'
<p><b>You give #Legionnaire Dalini : </b><a href=http://phobos/eq/item.php?id=29851>Dawnshroud Cider</a>
<br><b>#Legionnaire Dalini says </b>'Dorey usually roams in the troglodyte caves, you might find him there.'
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=161077>#Bregun_Dorey</a></b> spawns (240,-400,-3).</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>