<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=5982>Unsigned Agreement</a><li><a href=http://phobos/eq/item.php?id=5983>Signed Agreement</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=5982>Unsigned Agreement</a><li><a href=http://phobos/eq/item.php?id=5983>Signed Agreement</a><li><a href=http://phobos/eq/item.php?id=5984>Jasper Kundan Earring</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'Ahh. hello there [Your Name].  I am a trader from Sanctus Seru trying to make my way to Shadowhaven for some dealings.  I have come this far with the aid of guards from Sanctus Seru. but they have turn back and left me to go on my own.  I hear there are many terrible [creatures] here lurking in the shadows. leave it to the guards of the Hand to leave me unprotected.'
<p><b>You say, </b>'what creatures'
<br><b>Not Found says </b>'What I was told is that this pass is filled with small horrible creatures with no eyes.  Perhaps you could [help by providing safe passage] to the other side?'
<p><b>You say, </b>'i will help by providing safe passage'
<br><b>Not Found says </b>'Great!  If I can get safely to the other side I will give you a small trinket that I was going to sell.  Getting safe passage for the rest of my goods is worth more than the item in itself.  Surely you know a good deal when you hear one.  Take this note. if you agree to the conditions that I get across safely before you get payment return it to me and we will be on our way.'
<br><b>Not Found gives you : </b><a href=http://phobos/eq/item.php?id=5982>Unsigned Agreement</a>
<p><b>You give Not Found : </b><a href=http://phobos/eq/item.php?id=5982>Unsigned Agreement</a>
<br><b>Not Found says </b>'Let us go then. please be alert throughout the cavern.  Once we get to the other side safely give me the signed agreement and you will have your payment.'
<br><b>Not Found gives you : </b><a href=http://phobos/eq/item.php?id=5983>Signed Agreement</a>
<p><b>You give Not Found : </b><a href=http://phobos/eq/item.php?id=5983>Signed Agreement</a>
<br><b>Not Found says </b>'Thank you so much for your help!  As I promised here is a small token of my appreciation.'
<br><b>Not Found gives you : </b><a href=http://phobos/eq/item.php?id=5984>Jasper Kundan Earring</a>
</td></tr></table>