<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28700>Small Bottle of Blargrot</a><li><a href=http://phobos/eq/item.php?id=28701>Jug of Blargrot</a><li><a href=http://phobos/eq/item.php?id=28702>Huge Keg of Blargrot</a><li><a href=http://phobos/eq/item.php?id=28705>East Caller Contract</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28705>East Caller Contract</a></ul></td><td><hr><b>When #Caller Torgal spawns </b>
<hr><b>When #Caller Torgal is killed </b>
<p><b>You give #Caller Torgal : </b><a href=http://phobos/eq/item.php?id=28700>Small Bottle of Blargrot</a>
<br><b>#Caller Torgal says </b>'Aieee! Beastie huntin' fer us! Le's go! You give me back da contract when you had nuff beasties, yub. Me quit then, an' call no more beasties. I wait a minute so you make ready. Then ya follow me, and I take ya to da cave where we find beasties..'
<br><b>#Caller Torgal gives you : </b><a href=http://phobos/eq/item.php?id=28705>East Caller Contract</a>
<p><b>You give #Caller Torgal : </b><a href=http://phobos/eq/item.php?id=28701>Jug of Blargrot</a>
<br><b>#Caller Torgal says </b>'Aieee! Beastie huntin' fer us! Le's go! You give me back da contract when you had nuff beasties, yub. Me quit then, an' call no more beasties. I wait a minute so you make ready. Then ya follow me, and I take ya to da cave where we find beasties..'
<br><b>#Caller Torgal gives you : </b><a href=http://phobos/eq/item.php?id=28705>East Caller Contract</a>
<p><b>You give #Caller Torgal : </b><a href=http://phobos/eq/item.php?id=28702>Huge Keg of Blargrot</a>
<br><b>#Caller Torgal says </b>'Aieee! Beastie huntin' fer us! Le's go! You give me back da contract when you had nuff beasties, yub. Me quit then, an' call no more beasties. I wait a minute so you make ready. Then ya follow me, and I take ya to da cave where we find beasties..'
<br><b>#Caller Torgal gives you : </b><a href=http://phobos/eq/item.php?id=28705>East Caller Contract</a>
<p><b>You give #Caller Torgal : </b><a href=http://phobos/eq/item.php?id=28705>East Caller Contract</a>
<br><b>#Caller Torgal disappears.</b>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>