<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=26057>Book of Sales Secrets</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=26058>Thars Sales Report</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a><li><a href=http://phobos/eq/faction.php?id=152>House of Fordel</a><li><a href=http://phobos/eq/faction.php?id=153>House of Midst</a><li><a href=http://phobos/eq/faction.php?id=154>House of Stout</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Thar Anton says </b>'Hello there traveler. I have many wares for sale so please take a look at what I have. If you think all my goods are junk and wish to buy from someone else though I'll understand.'
<p><b>You give Thar Anton : </b><a href=http://phobos/eq/item.php?id=26057>Book of Sales Secrets</a>
<br><b>Thar Anton says </b>''I see you have brought a book from the Commissioner. Well I'm not much for reading but I will surely try anything that may increase my sales. Anyways I'm sure you arent that interested in how bad my sales are and would like to be on your way so here you go.'
<br><font color=green><b>Thar Anton </b>gives you a Sales Report.</font>
<br><b>Thar Anton gives you : </b><a href=http://phobos/eq/item.php?id=26058>Thars Sales Report</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=152>House of Fordel</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=153>House of Midst</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=154>House of Stout</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Thar Anton says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>