<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17092>Grotesque Mortar and Pestle</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>a mortician </b>stares at you with hollow eye sockets. As he opens his jaw to speak, you are overcome by the foul smell of a thousand rotted corpses. 'What is your desire, master?'</font>
<p><b>You say, </b>'mortar and pestle'
<br><font color=green><b>a mortician </b>moves with a mixture of creaks and clicks and produces a grotesque looking mortar and pestle set. He places the items in your hands and motions indicating you dismissal. You can feel the vile power of your god moving throughout the material that makes up the two items.</font>
<br><b>a mortician gives you : </b><a href=http://phobos/eq/item.php?id=17092>Grotesque Mortar and Pestle</a>
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>a mortician says </b>'I've no use for that.'
</td></tr></table>