<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12886>Barbed Scaled Whip</a><li><a href=http://phobos/eq/item.php?id=4266>Sorcerer Skullcap</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17195>A Flaxen Hilt</a><li><a href=http://phobos/eq/item.php?id=4267>Necromancer Skullcap</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a><li><a href=http://phobos/eq/faction.php?id=24>Brood of Kotiz</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>an Iksar hermit says </b>'I am looking for a [great sorcerer]. Are you such a person?'
<p><b>You say, </b>'great sorcerer'
<p><b>an Iksar hermit checks to see if you have <a href=http://phobos/eq/item.php?id=4266>Sorcerer Skullcap</a></b><br>
<br><b>an Iksar hermit says </b>'Are we now? Well then take this. See if you can finish this project that I started so many years ago. It still requires a [whip], a [tassel], and a [lock]. Go and find these items and return to me with what you have already learned and I shall reward you.'
<br><b>an Iksar hermit gives you : </b><a href=http://phobos/eq/item.php?id=17195>A Flaxen Hilt</a>
<p><b>You say, </b>'great sorcerer'
<p><b>an Iksar hermit checks to see if you have <a href=http://phobos/eq/item.php?id=4266>Sorcerer Skullcap</a></b><br>
<br><b>an Iksar hermit says </b>'Are we now? Well then take this. See if you can finish this project that I started so many years ago. It still requires a [whip], a [tassel], and a [lock]. Go and find these items and return to me with what you have already learned and I shall reward you.'
<br><b>an Iksar hermit gives you : </b><a href=http://phobos/eq/item.php?id=17195>A Flaxen Hilt</a>
<p><b>You say, </b>'whip'
<br><b>an Iksar hermit says </b>'Many years ago in Dreadlans a drovarg came and ravaged my camp and stole a whip that was given to me by my master. With the loss of the whip I became an outcast to the dark arts.'
<p><b>You say, </b>'tassel'
<br><b>an Iksar hermit says </b>'You should find a large ghostly tassel, I was on my way to Kaesora to learn about this tassel but my age has hindered this adventure. You should go there and see what you can find.'
<p><b>You say, </b>'lock'
<br><b>an Iksar hermit says </b>'Only a goblins hair is strong enough to hold this together. Go and slay them till you find a lock of hair strong enough for this.'
<p><b>You give an Iksar hermit : </b><a href=http://phobos/eq/item.php?id=12886>Barbed Scaled Whip</a>, <a href=http://phobos/eq/item.php?id=4266>Sorcerer Skullcap</a>
<br><font color=green><b>an Iksar hermit </b>takes the flail and vanishes with a brilliant flash!! Within your hands appears a skullcap. You hear a voice echo through the cave. Well done. You are a formidable necromancer. We thank you.</font>
<br><b>an Iksar hermit disappears.</b>
<br><b>an Iksar hermit gives you : </b><a href=http://phobos/eq/item.php?id=4267>Necromancer Skullcap</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=24>Brood of Kotiz</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>an Iksar hermit says </b>'All is not complete. A cap and the rest, which was asked for, is required.'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>an Iksar hermit says </b>'All is not complete. A cap and the rest, which was asked for, is required.'
</td></tr></table>