<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18204>Guild Summons</a><li><a href=http://phobos/eq/item.php?id=12874>Sceptre of Emperor Vekin</a><li><a href=http://phobos/eq/item.php?id=4265>Revenant Skullcap</a><li><a href=http://phobos/eq/item.php?id=48037>A Rogue Marauder's Head</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12873>Unfinished Sceptre</a><li><a href=http://phobos/eq/item.php?id=12407>Drape of the Brood</a><li><a href=http://phobos/eq/item.php?id=4266>Sorcerer Skullcap</a><li><a href=http://phobos/eq/item.php?id=48039>Glosk's Sack</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a><li><a href=http://phobos/eq/faction.php?id=24>Brood of Kotiz</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Harbinger Glosk </b>halts his chanting.</font>
<br><b>Harbinger Glosk says </b>'You dare to interrupt me? You had best have a good reason. I care not for small talk.'
<p><b>You say, </b>'new revenant'
<br><b>Harbinger Glosk says </b>'Yes. You are. You shall do as I command. Take this. It is incomplete and must be ready for the emperor within the half season. You must find the [Four Missing Gems]. When you have them, then you will have to Quest for the [Grand Forge of Dalnir]. Within it's fire, all shall combine. Return the Sceptre to me with your Revenant Skullcap. Go. '
<br><b>Harbinger Glosk gives you : </b><a href=http://phobos/eq/item.php?id=12873>Unfinished Sceptre</a>
<p><b>You say, </b>'forge of dalnir'
<br><font color=green><b>Harbinger Glosk </b>scratches his chin.</font>
<br><b>Harbinger Glosk says </b>'I know little of it other than that it once belonged to the ancient Haggle Baron, Dalnir. From what I have read, its fires require no skill, but will melt any common forge hammer used. Dalnir was said to have called upon the ancients for a hammer which could tolerate the magickal flames.'
<p><b>You say, </b>'gem of reflection'
<br><b>Harbinger Glosk says </b>'I have not been asked that in ages but I can recall the last person that asked me. If you are in league with that scoundrel Ixpacan, I will slay you where you stand! But if you are not, you will not mind ridding your kin of a [menace] as of late.'
<p><b>You say, </b>'menace'
<br><b>Harbinger Glosk says </b>'It seems as though a rogue marauder in a jungle near here has attacked several of our trade suppliers. If you can bring me back his head I will gladly share the information you have asked for.'
<p><b>You give Harbinger Glosk : </b><a href=http://phobos/eq/item.php?id=18204>Guild Summons</a>
<br><b>Harbinger Glosk says </b>'Another apprentice has reached rebirth. You now have become one with the Brood of Kotiz. We study the ancient writing of Kotiz. Through his writing we have found the power of the dark circles. Listen well to the scholars within this tower and seek the [Keepers Grotto] for knowledge of our spells. This drape shall be the sign to all Iksar that you walk with the Brood. Now go speak with Xydoz.'
<br><b>Harbinger Glosk gives you : </b><a href=http://phobos/eq/item.php?id=12407>Drape of the Brood</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Harbinger Glosk : </b><a href=http://phobos/eq/item.php?id=12874>Sceptre of Emperor Vekin</a>, <a href=http://phobos/eq/item.php?id=4265>Revenant Skullcap</a>
<br><font color=green><b>Harbinger Glosk </b>presents to you a glowing skullcap.</font>
<br><b>Harbinger Glosk says </b>'This is the treasured cap of the sorcerers of this tower. Let all gaze upon you in awe. You are what others aspire to be. I look forward to reading of your adventures, Sorceror [Your Name].'
<br><b>Harbinger Glosk gives you : </b><a href=http://phobos/eq/item.php?id=4266>Sorcerer Skullcap</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=24>Brood of Kotiz</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 2pp
<p><b>You give Harbinger Glosk : </b><a href=http://phobos/eq/item.php?id=48037>A Rogue Marauder's Head</a>
<br><b>Harbinger Glosk says </b>'You have done well in doing what I have asked. To make a gem of reflection you will need some Mt Death mineral salts, a green goblin skin, spiroc bone dust, essence of rathe, blue slumber fungus, and a vial of pure essence. Combine all of these in this container and you will have what it is you seek.'
<br><b>Harbinger Glosk gives you : </b><a href=http://phobos/eq/item.php?id=48039>Glosk's Sack</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>