<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19423>Spell: Convergence</a><li><a href=http://phobos/eq/item.php?id=19296>Spell: Defoliation</a><li><a href=http://phobos/eq/item.php?id=19294>Spell: Splurt</a><li><a href=http://phobos/eq/item.php?id=19299>Spell: Thrall of Bones</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19421>Spell: Sacrifice</a><li><a href=http://phobos/eq/item.php?id=19409>Spell: Shadowbond</a><li><a href=http://phobos/eq/item.php?id=19408>Spell: Scent of Terris</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Izarod Fristan says </b>'Hail there. [Your Name]. So you are ready to learn more about our ways? Do you wish to try and expand your knowledge of our arcane arts? Then venture far from here to the darkest depths of our once great empire and seek the minions that inhabit the ruins. The arcane powers will come in the form of [scrolls].'
<p><b>You say, </b>'what scrolls?'
<br><b>Izarod Fristan says </b>'Besides all the ones you will find. there are some that are only in my possession. To show that you have been successful on your journey. return one of splurt. defoliation. convergence. or thrall of bones. You then will be rewarded with one of my scrolls.'
<p><b>You give Izarod Fristan : </b><a href=http://phobos/eq/item.php?id=19423>Spell: Convergence</a>
<br><b>Izarod Fristan says </b>'Here is the scroll that I promised. We have both gained much today. I hope to do business with you again soon. Farewell.'
<br><b>Izarod Fristan gives you : </b><a href=http://phobos/eq/item.php?id=19421>Spell: Sacrifice</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Izarod Fristan : </b><a href=http://phobos/eq/item.php?id=19296>Spell: Defoliation</a>
<br><b>Izarod Fristan says </b>'Here is the scroll that I promised. We have both gained much today. I hope to do business with you again soon. Farewell.'
<br><b>Izarod Fristan gives you : </b><a href=http://phobos/eq/item.php?id=19421>Spell: Sacrifice</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Izarod Fristan : </b><a href=http://phobos/eq/item.php?id=19294>Spell: Splurt</a>
<br><b>Izarod Fristan says </b>'Here is the scroll that I promised. We have both gained much today. I hope to do business with you again soon. Farewell.'
<br><b>Izarod Fristan gives you : </b><a href=http://phobos/eq/item.php?id=19409>Spell: Shadowbond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Izarod Fristan : </b><a href=http://phobos/eq/item.php?id=19299>Spell: Thrall of Bones</a>
<br><b>Izarod Fristan says </b>'Here is the scroll that I promised. We have both gained much today. I hope to do business with you again soon. Farewell.'
<br><b>Izarod Fristan gives you : </b><a href=http://phobos/eq/item.php?id=19408>Spell: Scent of Terris</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>