<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12442>Bone Granite Powder</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17025>Fern Flower Pouch</a><li><a href=http://phobos/eq/item.php?id=12443>Kromdul Toothpick</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Jondin says </b>'Greetings. friend.  I have many fine herbs for sale.  My prices are reasonable for I am not governed by the [Haggle Baron].  If you fancy yourself an adventurer. I would like to hire you for a [simple mission].'
<p><b>You say, </b>'haggle baron'
<br><b>Jondin says </b>'Haggle Baron Klok Dun Ree is the current Haggle Baron. It is written in the law that all services shall be governed by the Haggle Baron. To do business outside of the law is forbidden, but the merchants of the Tower of Death are exempt from this rule. Klok will not test the temper of the Harbinger and Baron Eator will not upset his most powerful ally.'
<p><b>You say, </b>'simple mission'
<br><b>Jondin says </b>'I actually have a few items I am presently low on.  I would appreciate some assistance to [collect fern flowers] or maybe you are an alchemist who can [gather bone chips].'
<p><b>You say, </b>'fern flowers'
<br><b>Jondin says </b>'I have run low on fern flowers and must have more of them.  Take this [flower pouch].  Outside the city can be found carnivorous plants and a strain of them buds the flower in question.  Collect enough of these flowers to fill and combine the pouch and I shall reward you.'
<br><b>Jondin gives you : </b><a href=http://phobos/eq/item.php?id=17025>Fern Flower Pouch</a>
<p><b>You say, </b>'bone chips'
<br><b>Jondin says </b>'I should tell you. I do not need the bone chips.  I need bone granite powder.  In order to get it. you must find some granite pebbles and then three piles of bone chips from decaying skeletons.  After you gather the items you will have to use your skill in alchemy to combine the items and create bone granite powder.  The powder is what I need.'
<p><b>You give Jondin : </b><a href=http://phobos/eq/item.php?id=12442>Bone Granite Powder</a>
<br><b>Jondin says </b>'You have done well. Here is your reward.'
<br><b>Jondin gives you : </b><a href=http://phobos/eq/item.php?id=12443>Kromdul Toothpick</a>
</td></tr></table>