<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12869>Wand of Pain</a><li><a href=http://phobos/eq/item.php?id=12885>Full Component Chest</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17041>Component Chest</a><li><a href=http://phobos/eq/item.php?id=15444>Spell: Renew Bones</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=24>Brood of Kotiz</a><li><a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Keeper Pain </b>raises his gaze from his tomes to greet you. 'Ahh!! Welcome, seeker of knowledge! Come to fill your brains, have you? Look closer, adventurer. I have scribed some very powerful spells.</font>
<p><b>You say, </b>'wand of pain'
<br><font color=green><b>Keeper Pain </b>drops his tome and monocle and looks at you sharply. 'What?!! Have you seen Revenant Vytrix? I let him borrow my wand for a quest. That was half a season ago!! I fear he is dust and my precious wand is lost.</font>
<p><b>You give Keeper Pain : </b><a href=http://phobos/eq/item.php?id=12869>Wand of Pain</a>
<br><font color=green><b>Keeper Pain </b>begins jumping for joy. 'Yoohoo!! My wand!! Thank you. You must be some powerful adventurer. You can help me collect a few components. Fill this chest with a frost cystal, a cockatrice egg, a giant hornet egg and a plains pebble. Return the full chest to me and I shall offer you a spell I recently researched.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 4gp
<br><b>Keeper Pain gives you : </b><a href=http://phobos/eq/item.php?id=17041>Component Chest</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=24>Brood of Kotiz</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<p><b>You give Keeper Pain : </b><a href=http://phobos/eq/item.php?id=12885>Full Component Chest</a>
<br><b>Keeper Pain says </b>'Yes this is exactly what i wanted. Here is your spell.'
<br><b>Keeper Pain gives you : </b><a href=http://phobos/eq/item.php?id=15444>Spell: Renew Bones</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=24>Brood of Kotiz</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>