<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12854>An Illegible Note</a><li><a href=http://phobos/eq/item.php?id=12855>An Illegible Note</a><li><a href=http://phobos/eq/item.php?id=12856>An Illegible Note</a><li><a href=http://phobos/eq/item.php?id=12857>An Illegible Note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=16426>Spell: Intensify Death</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=24>Brood of Kotiz</a><li><a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Keeper Rott </b>bows before you. His eyes are kept wide by the pins which distort his eyelids.</font>
<br><b>Keeper Rott says </b>'Greetings! You have stumbled upon the cave of the Keepers. We record the arcane secrets of the Brood of Kotiz. We have scribed many spells and make them available to all those who are deserving. Please, have a look.'
<p><b>You say, </b>'chosen occultist'
<br><font color=green><b>Keeper Rott </b>kneels before you abjectly.</font>
<br><b>Keeper Rott says </b>'Oh, great occultist! I am glad you have arrived, but I do not have the artifacts Kyvix seeks. You will have to seek out the sarnak revenants who still hold the precious stem and base. Get them and take them with your occultist skullcap back to Master Kyvix. Since you are headed in the general direction, I also have an [additional mission], if you do not mind.'
<p><b>You say, </b>'additional mission'
<br><font color=green><b>Keeper Rott </b>grabs a fist full of scribbled notes and throws them into the air in a rage.</font>
<br><b>Keeper Rott says </b>'All these notes are useless to me without the first four note pages! While I ventured through the fields of the drixies, I was assaulted by a band of gobs. They were shamans. I heard them calling spirits. They took the first two pages before I escaped. Then I lost the [second two pages] the next day!! Blast!!'
<p><b>You say, </b>'second two pages'
<br><font color=green><b>Keeper Rott </b>begins to curse. Luckily, you do not understand the language, but you feel a bit of spittle strike your face.</font>
<br><b>Keeper Rott says </b>'...and then there I was, almost home and the legion expedition leader decided we should explore a bit more near the lake. Then I find myself up against the same type of gobs from the fields. I just ran for the exit an never looked back, but they still managed to swipe pages 3 and 4!!'
<p><b>You give Keeper Rott : </b><a href=http://phobos/eq/item.php?id=12854>An Illegible Note</a>, <a href=http://phobos/eq/item.php?id=12855>An Illegible Note</a>, <a href=http://phobos/eq/item.php?id=12856>An Illegible Note</a>, <a href=http://phobos/eq/item.php?id=12857>An Illegible Note</a>
<br><b>Keeper Rott says </b>'Oh, great necromancer, how can I repay you?!! I know. Here is a spell I recently researched. It should help you increase the strength of a summoned pet. Learn it well.'
<br><b>Keeper Rott gives you : </b><a href=http://phobos/eq/item.php?id=16426>Spell: Intensify Death</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=24>Brood of Kotiz</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Keeper Rott says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>