<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12739>Brittle Iksar Skull</a><li><a href=http://phobos/eq/item.php?id=12659>Large Scorpion Pincer</a><li><a href=http://phobos/eq/item.php?id=12426>Sabertooth Cub Canine</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15347>Spell: Numb the Dead</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Keeper Bile says </b>'Greetings [Your Name]. Lately the creatures of Lake of Ill Omen have be causing problems for us. Are you [interested] in helping me reduce the threat from this creatures?'
<p><b>You say, </b>'interested'
<br><b>Keeper Bile says </b>'Good. Bring me a Brittle Iksar Skull, a Sabertooth Cub Canine, and a Large Scorpion Pincer. And i shall reward you with a spell.'
<p><b>You give Keeper Bile : </b><a href=http://phobos/eq/item.php?id=12739>Brittle Iksar Skull</a>, <a href=http://phobos/eq/item.php?id=12659>Large Scorpion Pincer</a>, <a href=http://phobos/eq/item.php?id=12426>Sabertooth Cub Canine</a>
<br><b>Keeper Bile says </b>'Good Work [Your Name]. This will surely hold back those vile creatures for some time. Here is your spell.'
<br><b>Keeper Bile gives you : </b><a href=http://phobos/eq/item.php?id=15347>Spell: Numb the Dead</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>