<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12853>Stem of Candlestick</a><li><a href=http://phobos/eq/item.php?id=12852>Foot of Candlestick</a><li><a href=http://phobos/eq/item.php?id=4264>Occultist Skullcap</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17024>Brood Sack</a><li><a href=http://phobos/eq/item.php?id=12848>A Spectacle</a><li><a href=http://phobos/eq/item.php?id=4265>Revenant Skullcap</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a><li><a href=http://phobos/eq/faction.php?id=24>Brood of Kotiz</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Master Kyvix says </b>'Quite busy!! Quite busy!! Things must be done. [New components] to be collected!!'
<p><b>You say, </b>'hail'
<br><b>Master Kyvix says </b>'Quite busy!! Quite busy!! Things must be done. [New components] to be collected!!'
<p><b>You say, </b>'New components'
<br><b>Master Kyvix says </b>'Yes, yes!! I will need components from beyond the gates. I must find an [apprentice of the third rank].'
<p><b>You say, </b>'apprentice of the third rank'
<br><b>Master Kyvix says </b>'If you truly be an apprentice of the third circle, then there is a Dark Binder skullcap to be earned. Take this sack and fill it with a creeper cabbage, a heartsting telson with venom, brutling choppers and a scalebone femur. When they are combined within the sack, you may return it to me with your third rank skullcap and and we shall bid farewell to the title, 'apprentice.'
<br><b>Master Kyvix gives you : </b><a href=http://phobos/eq/item.php?id=17024>Brood Sack</a>
<p><b>You say, </b>'true mission'
<br><b>Master Kyvix says </b>'I have been waiting for a Nihilist to return. His name was Ryx and I fear his love of ale and the high seas has kept him from his mission. All I want you to do is find him. He should be disguised as a worker and he will give you a tome to bring to me. Return it with your Dark Binder Cap. I am sure that is simple enough for one as simple as you. Be sure to give him this.'
<br><b>Master Kyvix gives you : </b><a href=http://phobos/eq/item.php?id=12848>A Spectacle</a>
<p><b>You say, </b>'Kor Sha Candlestick'
<br><b>Master Kyvix says </b>'I need the foot and stem of my candlestick. The Stem comes from Sarnaks. The foot has been stolen by Gripe, in East Cabilis.'
<p><b>You give Master Kyvix : </b>
<p><b>You give Master Kyvix : </b>
<p><b>You give Master Kyvix : </b><a href=http://phobos/eq/item.php?id=12853>Stem of Candlestick</a>, <a href=http://phobos/eq/item.php?id=12852>Foot of Candlestick</a>, <a href=http://phobos/eq/item.php?id=4264>Occultist Skullcap</a>
<br><font color=green><b>Master Kyvix </b>grabs the candle parts and puts them in an odd pouch, then takes your cap which disintegrates in his palm. He hands you another cap.</font>
<br><b>Master Kyvix says </b>'Welcome, Revenant ______. You have done well. The Harbinger awaits you. He seeks a [new revenant].'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=24>Brood of Kotiz</a> has gotten better.</font>
<br><b>Master Kyvix gives you : </b><a href=http://phobos/eq/item.php?id=4265>Revenant Skullcap</a>
<br><b>You receive </b> 6gp
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>