<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12411>Preserved Sarnak Brain</a><li><a href=http://phobos/eq/item.php?id=4261>Apprentice Skullcap - 2nd Rank</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17023>Brood Canopic</a><li><a href=http://phobos/eq/item.php?id=4262>Apprentice Skullcap - 3rd Rank</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a><li><a href=http://phobos/eq/faction.php?id=24>Brood of Kotiz</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Master Rixiz says </b>'You are on the grounds of the Brood of Kotiz. If you do not belong, you must leave at once. There shall be no [third rank skullcap] for you.'
<p><b>You say, </b>'third rank skullcap'
<br><b>Master Rixiz says </b>'I offer the third rank apprentice skullcap to those who wear the second. If that is you, then you will do the [bidding of the tower].'
<p><b>You say, </b>'bidding of the tower'
<br><b>Master Rixiz says </b>'Take this glass canopic. Within it you shall place a brain for me. The brain I seek is that of a sarnak crypt raider. Any shall do. The ones we seek should be near the Lake of Ill Omen. When you obtain the brain, you must quickly put it into the glass canopic with [embalming fluid]. When these are combined, the canopic shall seal and if you return it to me with your second rank skullcap, I shall hand you the next and final skullcap.'
<br><b>Master Rixiz gives you : </b><a href=http://phobos/eq/item.php?id=17023>Brood Canopic</a>
<br><b>Master Rixiz says </b>'You shall get no skullcap until I have the preserved raider brain and your second circle apprentice skullcap.'
<p><b>You say, </b>'embalming fluid'
<br><b>Master Rixiz says </b>'Embalming fluid is created through brewing, but do not drink it!! You can learn about the process of brewing on our grounds.'
<p><b>You give Master Rixiz : </b><a href=http://phobos/eq/item.php?id=12411>Preserved Sarnak Brain</a>, <a href=http://phobos/eq/item.php?id=4261>Apprentice Skullcap - 2nd Rank</a>
<br><b>Master Rixiz says </b>'You have done well. Here is your final apprentice skullcap.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=24>Brood of Kotiz</a> has gotten better.</font>
<br><b>Master Rixiz gives you : </b><a href=http://phobos/eq/item.php?id=4262>Apprentice Skullcap - 3rd Rank</a>
<br><b>You receive </b> 10gp
</td></tr></table>