<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12408>Sarnak Hatchling Brain</a><li><a href=http://phobos/eq/item.php?id=4260>Apprentice Skullcap - 1st Rank</a><li><a href=http://phobos/eq/item.php?id=18208>Mended Tapestry</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=4260>Apprentice Skullcap - 1st Rank</a><li><a href=http://phobos/eq/item.php?id=4261>Apprentice Skullcap - 2nd Rank</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a><li><a href=http://phobos/eq/faction.php?id=24>Brood of Kotiz</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Master Xydoz says </b>'What is it you seek within the tower ? Could it be that you are a new apprentice ? If so, you are required to don the [apprentice skullcap]'
<p><b>You say, </b>'apprentice'
<br><b>Master Xydoz says </b>'All new members of the Brood of Kotiz are required to don the [apprentice skullcap]. To earn one, a new apprentice is required to fetch four brains for further experiments. Not just any four brains, mind you, but the brains of [sarnak] hatchlings.'
<p><b>You say, </b>'sarnak'
<br><b>Master Xydoz says </b>'Sarnak ? Do not speak loudly, that name. If you seek information on the sarnak, read the tome of this tower. The tower librarian should be found within.'
<p><b>You say, </b>'second rank skullcap'
<br><b>Master Xydoz says </b>'Looking for the second rank skullcap ? Look no further, but be prepared to earn it. I seek a [faded tapestry]. Now, too, so do you.'
<p><b>You say, </b>'faded tapestry'
<br><b>Master Xydoz says </b>'I have heard reports of such a thing found upon Sarnak hatchlings. They must have scampered from the safety of their dwelling with their master's property. I would like to see this tapestry, but only when it has been mended. I need find a necromancer who is [adept at tailoring].'
<p><b>You say, </b>'adept at tailoring'
<br><b>Master Xydoz says </b>'If you are a member of the Brood and wish to assist you may seek out this tapestry. Find the Torn and Ripped pieces and take them both to a sewing kit. Return with the mended tapestry and your first rank skullcap and I shall see that you are rewarded with coin and a second rank skullcap'
<p><b>You give Master Xydoz : </b><a href=http://phobos/eq/item.php?id=12408>Sarnak Hatchling Brain</a> (x4)
<br><b>Master Xydoz says </b>'Good work, my young apprentice. You will make a fine addition to our ranks. Here is your first apprentice skullcap. Wear it as a sign of our circle. Do not lose it. Someday you shall wear a necromancer skullcap, but next shall come the [second rank skullcap].'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=24>Brood of Kotiz</a> has gotten better.</font>
<br><b>Master Xydoz gives you : </b><a href=http://phobos/eq/item.php?id=4260>Apprentice Skullcap - 1st Rank</a>
<p><b>You give Master Xydoz : </b><a href=http://phobos/eq/item.php?id=4260>Apprentice Skullcap - 1st Rank</a>, <a href=http://phobos/eq/item.php?id=18208>Mended Tapestry</a>
<br><b>Master Xydoz says </b>'A job well done, apprentice. Your fine service shall earn you the second circle apprentice skullcap. I would advise you to forget this tapestry, it is nothing more than an ancient rug of no importance.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=24>Brood of Kotiz</a> has gotten better.</font>
<br><b>Master Xydoz gives you : </b><a href=http://phobos/eq/item.php?id=4261>Apprentice Skullcap - 2nd Rank</a>
</td></tr></table>