<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18272>Rites of Exoneration</a><li><a href=http://phobos/eq/item.php?id=24770>Filled Penance Bag</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18271>A Ragged Book</a><li><a href=http://phobos/eq/item.php?id=12407>Drape of the Brood</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Nihilist Zeegarn says </b>'Mind yourself within Cabilis. We will not tolerate any mischief. If you don't heed my warnings, you may be sentenced to the pit of the Crusaders of Greenmist. You don't want that! Also, you should always wear your robe when entering these walls. You do have your Drape of the Brood, correct?'
<p><b>You say, </b>'yes'
<br><b>Nihilist Zeegarn says </b>'Very good. Please keep it on and bow before the will of the Cazic-Thule when entering these walls. Be off.'
<p><b>You say, </b>'no'
<br><b>Nihilist Zeegarn says </b>'What is this?' the Nihilist barks in disbelief. 'You have lost your drape? This is unacceptable! Take this note and report to the Toilmaster at once. Read it on the way and praise Cazic-Thule for any mercy that you may be granted!'
<br><b>Nihilist Zeegarn gives you : </b><a href=http://phobos/eq/item.php?id=18271>A Ragged Book</a>
<p><b>You give Nihilist Zeegarn : </b><a href=http://phobos/eq/item.php?id=18272>Rites of Exoneration</a>, <a href=http://phobos/eq/item.php?id=24770>Filled Penance Bag</a>
<br><font color=green><b>Nihilist Zeegarn </b>takes the bag and tome from you and in return gives you the item that you have been thinking of all of this time.</font>
<br><b>Nihilist Zeegarn says </b>'Lucky you. You have earned a second chance. Praise Cazic-Thule!'
<br><b>Nihilist Zeegarn gives you : </b><a href=http://phobos/eq/item.php?id=12407>Drape of the Brood</a>
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Nihilist Zeegarn says </b>'This isn't what I asked for.'
</td></tr></table>