<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=24860>Bag of Crushed Herbs</a><li><a href=http://phobos/eq/item.php?id=24861>Bag of Sulfur</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=22855>Pile of Rubble</a></ul></td><td><p><b>You give a bag of suies.pl : </b><a href=http://phobos/eq/item.php?id=24860>Bag of Crushed Herbs</a>, <a href=http://phobos/eq/item.php?id=24861>Bag of Sulfur</a>
<br><b>a bag of suies.pl gives you : </b><a href=http://phobos/eq/item.php?id=22855>Pile of Rubble</a>
<br><font color=brown><b>a bag of suies.pl casts a spell : </b><a href=http://phobos/eq/spell.php?id=1644>Pillar of Flame</a>.</font>
<br><b>a bag of suies.pl disappears.</b>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>