<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=30081>Coldain Head</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=188>Kromrif</a><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a><li><a href=http://phobos/eq/faction.php?id=49>Coldain</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>a kromrif recruiter says </b>'Greetings, little thing. You have entered into the great city of Kael Drakkel, home of the Kromzek as well as a few of my kind, the Kromrif. If you are to walk among my people as a peer you must prove yourself as a friend, not a foe.'
<p><b>You say, </b>'prove myself'
<br><b>a kromrif recruiter says </b>'Leave this place then and return when you have waged war upon the Coldain. Remove their heads from their bodies and return them to me. I will spread the word of your deeds amongst my people if you do so, [Your Name].'
<p><b>You say, </b>'coldain'
<br><b>a kromrif recruiter says </b>'The Coldain are the ice dwarves who dwell in the city of Thurgadin. They are a blight upon the land known as Velious, speaking the word of their god, Brell.'
<p><b>You give a kromrif recruiter : </b><a href=http://phobos/eq/item.php?id=30081>Coldain Head</a>
<br><b>a kromrif recruiter says </b>'Very good, [Your Name]. Slay more of the beasts and your name will be known by all of the Kromrif!'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=49>Coldain</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>