<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=30081>Coldain Head</a><li><a href=http://phobos/eq/item.php?id=25301>Icepaw Kobold's Paw</a><li><a href=http://phobos/eq/item.php?id=1718>Wurmscale Scroll</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=25084>Antlered Mask</a><li><a href=http://phobos/eq/item.php?id=25024>Mask of War</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=188>Kromrif</a><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a><li><a href=http://phobos/eq/faction.php?id=179>King Tormax</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Captain Bvellos says </b>'Greetings, [Your Name]. I am the captain of the Kael militia. I will be watching those of your kind who have come to Kael Drakkel as mercenaries and bounty hunters. You may have come here to serve king Tormax but Kael is my home and I intend to keep it a safe place for the Kromzek. Keep yourself out of trouble or you will end up in a world of pain.'
<p><b>You say, </b>'work'
<br><b>Captain Bvellos says </b>'Are you looking for work, Feninie? I may have a use for one of your kind. I believe that several nobles in this fine city are not all they appear to be. I have suspicions about that filthy Wenglawks. He will do whatever it takes to amass his own wealth. My sources tell me that he may very well be trading with the Coldain, or worse yet, the dragons. If you could find me proof of his underhanded dealings, I would be most pleased.'
<p><b>You say, </b>'proof'
<br><b>Captain Bvellos says </b>'The more convincing the proof is, the better. There must be a record of his actions somewhere.'
<p><b>You say, </b>'keep safe'
<br><b>Captain Bvellos says </b>'With the influx of mercenaries into Kael Drakkel, I have seen minor crimes increase. I have had to increase my militia patrols. A majority of my militia work longer hours than they did before. There was a time when we only had to watch for the dragons from the sky and the Coldain from the outside. Now we must watch within'
<p><b>You say, </b>'mercenaries'
<br><b>Captain Bvellos says </b>'I have several bounties open if you are interested. Bring me the head of a Coldain and I will reward you with a small sum of money and spread the word of your good work. There is also a bounty upon the nefarious Icepaw kobolds who serve the outcast Velketor. I require four of the paws of those little beasts.'
<p><b>You give Captain Bvellos : </b><a href=http://phobos/eq/item.php?id=30081>Coldain Head</a>
<br><b>Captain Bvellos says </b>'Excellent, [Your Name]. Here is the bounty as promised.'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 10pp 5gp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=179>King Tormax</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten worse.</font>
<p><b>You give Captain Bvellos : </b><a href=http://phobos/eq/item.php?id=25301>Icepaw Kobold's Paw</a> x4
<br><b>Captain Bvellos says </b>'Excellent, [Your Name]. Here is the bounty as promised.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Captain Bvellos gives you : </b><a href=http://phobos/eq/item.php?id=25084>Antlered Mask</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=179>King Tormax</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten worse.</font>
<p><b>You give Captain Bvellos : </b><a href=http://phobos/eq/item.php?id=1718>Wurmscale Scroll</a>
<br><b>Captain Bvellos says </b>'This indeed points to Wenglawks being a traitor. If only there were more proof I could take this to the king. Thank you, [Your Name], you have done a great service for Kael. Take this mask as a reward for your service to this city.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Captain Bvellos gives you : </b><a href=http://phobos/eq/item.php?id=25024>Mask of War</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=179>King Tormax</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>