<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=25119>Great Dragon's Head</a><li><a href=http://phobos/eq/item.php?id=25118>Greater Dragon's Head</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=25023>Cloak of the Maelstrom</a><li><a href=http://phobos/eq/item.php?id=25022>Frostbringer</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=179>King Tormax</a><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=362>Yelinak</a><li><a href=http://phobos/eq/faction.php?id=67>Dain Frostreaver IV</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Dlammaz Stormslayer says </b>'Welcome to the castle of King Tormax. It is quite an accomplishment for one of your kind to have lived this long in the service of our great King Tormax. You must be powerful indeed. My power is like a storm - I may rage and destroy my foes with great fury.'
<p><b>You say, </b>'foes'
<br><b>Dlammaz Stormslayer says </b>'The dragons are the greatest threat to Kael Drakkel. For some reason they believe that this land we inhabit is holy and should not be tread upon. I cannot count the number of wurms I have beaten back from the gates of Kael Drakkel in the past. We giants will live on, though, for each year their numbers thin and ours only grow. With the help of mercenaries such as yourself we may be able to eradicate them from the face of Velious.'
<p><b>You say, </b>'eradicate'
<br><b>Dlammaz Stormslayer says </b>'I dream of the day when the only dragons in Velious are the ones whose skins line my boots. Some day my dream will come true. Until the day I can gather a force powerful enough to assault their homes, I will slay whatever foul beasts tread near Kael Drakkel.'
<p><b>You say, </b>'assault'
<br><b>Dlammaz Stormslayer says </b>'That is an aspiration of King Tormax. One day, it may be possible for us to do so. Encountering so many dragons at once may very well be suicide though. Enough of my banter about dragons. What is it that brings you to Dragon Death Keep? Do you seek more challenging tasks?'
<p><b>You say, </b>'challenging tasks'
<br><b>Dlammaz Stormslayer says </b>'If you are as mighty as I believe you to be, travel out from this city and fight off the draconian menace. For the head of an elder dragon you will be handsomely rewarded.'
<p><b>You say, </b>'reward'
<br><font color=green><b>Dlammaz Stormslayer </b>pats the huge axe at his side and drapes his shimmering cloak over his shoulders.</font>
<p><b>You say, </b>'axe'
<br><b>Dlammaz Stormslayer says </b>'My axe is named Frostbringer. It was given to me by the great King Tormax for my service to him. Serving the king can be quite advantageous.'
<p><b>You say, </b>'cloak'
<br><b>Dlammaz Stormslayer says </b>'The cloak of the Maelstrom allows me to rage like a great storm. It is but a simple possession - the head of an elder dragon would be worth far more to my kind.'
<p><b>You give Dlammaz Stormslayer : </b><a href=http://phobos/eq/item.php?id=25119>Great Dragon's Head</a>
<br><b>Dlammaz Stormslayer says </b>'The bards will sing of your greatness, [Your Name]. Rage on like the Maelstrom when you wear this cloak. You have done a great service for the city of Kael Drakkel, and we Kromzek do not soon forget great deeds.'
<br><b>Dlammaz Stormslayer gives you : </b><a href=http://phobos/eq/item.php?id=25023>Cloak of the Maelstrom</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=179>King Tormax</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=362>Yelinak</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=67>Dain Frostreaver IV</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Dlammaz Stormslayer : </b><a href=http://phobos/eq/item.php?id=25118>Greater Dragon's Head</a>
<br><b>Dlammaz Stormslayer says </b>'We shall hang this head from the halls of Dragondeath Keep and sing your praises, [Your Name]. Take my axe as a reward for your great deeds. You are a true hero for Kael Drakkel!'
<br><b>Dlammaz Stormslayer gives you : </b><a href=http://phobos/eq/item.php?id=25022>Frostbringer</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=179>King Tormax</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=362>Yelinak</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=67>Dain Frostreaver IV</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Dlammaz Stormslayer says </b>'I have no use for this, [Your Name].'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>