<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1717>Sealed Letter</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=25030>Frozen Shard</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a><li><a href=http://phobos/eq/faction.php?id=179>King Tormax</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=67>Dain Frostreaver IV</a><li><a href=http://phobos/eq/faction.php?id=362>Yelinak</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Fjokar Frozenshard says </b>'Today is a good day in Kael Drakkel. Don't you think?'
<p><b>You say, </b>'Wenglawks'
<br><b>Fjokar Frozenshard says </b>'Wenglawks masquerades as a noble. As family lines go, his is even more diluted than those two Iceshard brothers. He is a petty merchant and traitor. One day I will find my proof of this.'
<p><b>You say, </b>'Iceshard Brothers'
<br><b>Fjokar Frozenshard says </b>'Klaggan and Vorken, those two ruffians who somehow have managed to become the lords of the Kromrif manor. They were nothing but a pair of thugs no less than twenty years ago. I remember watching them kill and maim the innocent among the Kromrif tribes. If it were not for King Tormax's protection, I would slay them.'
<p><b>You say, </b>'Kromrif'
<br><b>Fjokar Frozenshard says </b>'The Frost giants are a proud race, but they are not nearly as powerful and blessed as we Kromzek. Our cousins may be strong, but the might of an enraged storm giant is something to behold.'
<p><b>You say, </b>'courier'
<br><b>Fjokar Frozenshard says </b>'Those Kromzek deserve to die. They know very well what he is up to. I will hunt them for sport, moving silently through the streets of Kael Drakkel, and invisibly through the outside world. Wenglawks has some sort of underhanded deals going on with the dragons. I have yet to find anything which will persuade King Tormax to allow me to slay him, unfortunately.'
<p><b>You give Fjokar Frozenshard : </b><a href=http://phobos/eq/item.php?id=1717>Sealed Letter</a>
<br><b>Fjokar Frozenshard says </b>'You have found what I was unable to. King Tormax's protection of Wenglawks will end soon. His death will be so very delightful to invoke.'
<br><font color=green><b>Fjokar Frozenshard </b>rushes out of the room, dropping his spear as he does.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=179>King Tormax</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=67>Dain Frostreaver IV</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=362>Yelinak</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Fjokar Frozenshard gives you : </b><a href=http://phobos/eq/item.php?id=25030>Frozen Shard</a>
<br><b>Fjokar Frozenshard says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>