<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=24987>Brell's Divine Strategy</a><li><a href=http://phobos/eq/item.php?id=24988>War Tactics of the Frostreavers</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=25039>Gauntlets of Iron Tactics</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=188>Kromrif</a><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a><li><a href=http://phobos/eq/faction.php?id=179>King Tormax</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Gkrean Prophet of Tallon says </b>'You have entered the sacred temple of Tallon Zek. This is the Temple of Tactics, where we teach what must be done to achieve goals in the most efficient manner.'
<p><b>You say, </b>'teach me'
<br><b>Gkrean Prophet of Tallon says </b>'I cannot teach one of your kind the arts of war. I must teach the other Kromzek at this time. If you were to serve the Temple of Tactics I might consider giving you a few words of wisdom.'
<p><b>You say, </b>'serve the temple'
<br><b>Gkrean Prophet of Tallon says </b>'The great father of war, Rallos Zek, wishes the destruction of the inferior race known as the Coldain. As the high priest of Tallon Zek, I see that they use great tactics to evade destruction. Find the ones who teach these tactics to the other Coldain and bring back the books that contain the ancient
Coldain tactics and strategies. Do not waste my time without a scroll or book that those tiny beasts hold'
<p><b>You give Gkrean Prophet of Tallon : </b><a href=http://phobos/eq/item.php?id=24987>Brell's Divine Strategy</a>, <a href=http://phobos/eq/item.php?id=24988>War Tactics of the Frostreavers</a>
<br><b>Gkrean Prophet of Tallon says </b>'You are a brave little beast to gain this tome. Let me impart a bit of wisdom to you. Tactics must change - if you do not ever adapt to new surroundings, environments and rules, you will surely perish.'
<br><b>Gkrean Prophet of Tallon gives you : </b><a href=http://phobos/eq/item.php?id=25039>Gauntlets of Iron Tactics</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=179>King Tormax</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten worse.</font>
<br><b>Gkrean Prophet of Tallon says </b>'You are a brave little beast to gain this tome. Let me impart a bit of wisdom to you. Tactics must change - if you do not ever adapt to new surroundings, environments and rules, you will surely perish.'
<br><b>Gkrean Prophet of Tallon gives you : </b><a href=http://phobos/eq/item.php?id=25039>Gauntlets of Iron Tactics</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=179>King Tormax</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten worse.</font>
</td></tr></table>