<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=25137>Vluudeen's Tail</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=25033>Bow of the Huntsman</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=188>Kromrif</a><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a><li><a href=http://phobos/eq/faction.php?id=49>Coldain</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Gleed Dragonhunter </b>sighs as he looks down at you. 'I grow tired of this city. I so long for the tundra and lands of the wild.'</font>
<p><b>You say, </b>'lands of the wild'
<br><b>Gleed Dragonhunter says </b>'I enjoy training these animals, don't get me wrong, but the open wastes, where the great animals and dragons roam free are what I crave. Before I came to serve King Tormax, I wandered those wastes, hunting young dragons and elder wurms. The whistle of an arrow from my bow was like sweet music - each slash of my sword a sweet song.'
<p><b>You say, </b>'young dragons'
<br><b>Gleed Dragonhunter says </b>'Yes, I hunted true dragons. The younger ones, at least. With my bow I could shoot them from such a distance they would never see what was coming.'
<p><b>You say, </b>'bow'
<br><font color=green><b>Gleed Dragonhunter </b>unslings an intricately carved bow from his back and shows it to you. 'I crafted this bow myself. It was to be a great slayer of wurms and dragons and it was, for a time. Now it goes to waste in the city, far from the beasts I long to slay. Far from the hunt and the excitement.'</font>
<p><b>You say, </b>'waste'
<br><b>Gleed Dragonhunter says </b>'It is such a shame, this bow deserves to be used. If only there were someone who would use it to hunt the beasts - someone to slay them and skin them like they should be.'
<p><b>You say, </b>'hunt the beasts'
<br><b>Gleed Dragonhunter says </b>'You will, little one? One such as yourself is a hunter? I did not know your kind had any skill in such things. In fact, I do not believe your kind could hunt a wurm, not without my wonderful bow. I will not simply hand it to a foolish . Hunt down some big game before you bother talking to me again. Perhaps if you bring me the tail of the elusive Vluudeen.'
<p><b>You give Gleed Dragonhunter : </b><a href=http://phobos/eq/item.php?id=25137>Vluudeen's Tail</a>
<br><b>Gleed Dragonhunter says </b>'My, you do have a hunters spirit! If you could track down Vluudeen and slay him without the aid of my bow, you must be worthy. Take the bow, huntsman. Use it to slay others of Vluudeen's kind.'
<br><b>Gleed Dragonhunter gives you : </b><a href=http://phobos/eq/item.php?id=25033>Bow of the Huntsman</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=49>Coldain</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>