<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=25279>Voucher for Toolset</a><li><a href=http://phobos/eq/item.php?id=25280>Voucher for Spear</a><li><a href=http://phobos/eq/item.php?id=25281>Voucher for Mechanical Net</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=25104>Coldain Toolset</a><li><a href=http://phobos/eq/item.php?id=25106>Bekerak's New Spear</a><li><a href=http://phobos/eq/item.php?id=25107>Mechanical Net</a></ul></td><td><p><b>You give Kellek Felhammer : </b><a href=http://phobos/eq/item.php?id=25279>Voucher for Toolset</a>
<br><b>Kellek Felhammer says </b>'Here you go [Your Name]. I dunno why master Wenglawks trusts you with this but take it anyways and don't mess up.'
<br><font color=green><b>Kellek Felhammer </b>smacks his fists together as he looks at you.</font>
<br><b>Kellek Felhammer gives you : </b><a href=http://phobos/eq/item.php?id=25104>Coldain Toolset</a>
<p><b>You give Kellek Felhammer : </b><a href=http://phobos/eq/item.php?id=25280>Voucher for Spear</a>
<br><b>Kellek Felhammer says </b>'Another delivery eh? Be careful with this spear, if you break it I'll break you.'
<br><b>Kellek Felhammer gives you : </b><a href=http://phobos/eq/item.php?id=25106>Bekerak's New Spear</a>
<p><b>You give Kellek Felhammer : </b><a href=http://phobos/eq/item.php?id=25281>Voucher for Mechanical Net</a>
<br><b>Kellek Felhammer says </b>'It's hard to belive a  like you is going to make a trip like this. I don't envy you little fool.'
<br><b>Kellek Felhammer gives you : </b><a href=http://phobos/eq/item.php?id=25107>Mechanical Net</a>
</td></tr></table>