<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=30501>Dain Frostreaver's Head</a><li><a href=http://phobos/eq/item.php?id=24984>Yelinak's Head</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>King Tormax says </b>'Greetings, . You know who I am, but I only vaguely know of you. My purpose is simple, I will rule these lands like my father, and my grandfather before him. All tasks but two are inconsequential to me.'
<p><b>You say, </b>'tasks'
<br><b>King Tormax says </b>'The tasks are simple, . I wish the death of the other 'powers' of this frozen waste land. If you are able to destroy either of my mortal foes, bring me proof of your exploits and you will be known as the hero of Kael Drakkel.'
<p><b>You say, </b>'powers'
<br><font color=green><b>King Tormax </b>laughs deeply. 'I speak of the foolish old dragon Yelinak and that pitiful Dain Frostreaver.'</font>
<p><b>You give King Tormax : </b><a href=http://phobos/eq/item.php?id=30501>Dain Frostreaver's Head</a>
<br><b>King Tormax says </b>'I do not know you well enough to entrust you with such an item, yet.'
<p><b>You give King Tormax : </b><a href=http://phobos/eq/item.php?id=24984>Yelinak's Head</a>
<br><b>King Tormax says </b>'I do not know you well enough to entrust you with such an item, yet.'
<br><b>King Tormax says </b>'I do not know you well enough to entrust you with such an item, yet.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>