<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=25119>Great Dragon's Head</a><li><a href=http://phobos/eq/item.php?id=25118>Greater Dragon's Head</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=25029>Barbed Dragonscale Boots</a><li><a href=http://phobos/eq/item.php?id=25028>Barbed Dragonscale Pauldrons</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a><li><a href=http://phobos/eq/faction.php?id=188>Kromrif</a><li><a href=http://phobos/eq/faction.php?id=179>King Tormax</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Kyenka says </b>'My, it is the great [Your Name] who stands before me! Rumors of your greatness have spread even to the court of King Tormax. I am Kyenka, Duke of Kael Drakkel. I advise King Tormax on matters concerning the nefarious dragons.'
<p><b>You say, </b>'dragons'
<br><b>Kyenka says </b>'The living dragons of this realm are the bane of Kael Drakkel and its people. Eventually they will be gone and only we Kromzek will remain. We will purge this land of their menace.'
<p><b>You say, </b>'purge'
<br><b>Kyenka says </b>'The beasts must be slain. They only bring strife to this world. You are a powerful mercenary, and are sympathetic to my cause, I would assume. You could become rich beyond your wildest dreams by assisting King Tormax and me.'
<p><b>You say, </b>'assist'
<br><b>Kyenka says </b>'Rally together a band of adventurers and track down and slay the elder dragons of this continent. For each head you return to me I will impart a gift to you.'
<p><b>You give Kyenka : </b><a href=http://phobos/eq/item.php?id=25119>Great Dragon's Head</a>
<br><b>Kyenka says </b>'This beast must have taken quite a force to slay. These boots have been crafted to reward your kind for such great efforts. Take them and wear them with pride. They will be a warning to other dragons that you are a great slayer of their kind.'
<br><b>Kyenka gives you : </b><a href=http://phobos/eq/item.php?id=25029>Barbed Dragonscale Boots</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=179>King Tormax</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Kyenka : </b><a href=http://phobos/eq/item.php?id=25118>Greater Dragon's Head</a>
<br><b>Kyenka says </b>'You serve the crown well, [Your Name]. This is one less beast to ruin our lands. Take these pauldrons which I have fashioned from the first dragon scales brought to King Tormax's court.'
<br><b>Kyenka gives you : </b><a href=http://phobos/eq/item.php?id=25028>Barbed Dragonscale Pauldrons</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=179>King Tormax</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Kyenka says </b>'I have no use for this, [Your Name].'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>