<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1724>Field Supplies</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Noble Helssen says </b>'You obviously have no idea where you have trespassed so I will generously allow you to live. I suggest you leave immediately before my generosity runs out however......Unless, you're looking for work.'
<p><b>You say, </b>'looking for work'
<br><b>Noble Helssen says </b>'Well, you might do. Out in the deepest scar, known as the Wakening Land we have deployed several mercenaries to harass the local annoying population. They are in need of constant supplies so we hire those we can trust to deliver those supplies to the mercenaries wandering out in the field. Are you interested, ?'
<p><b>You say, </b>'i am interested'
<br><b>Noble Helssen says </b>'Very well. Take this pack of supplies to any of the Mercenaries you come across in the field. They will pay you upon delivery. Return here for more supplies to deliver when you are ready.'
<br><b>Noble Helssen gives you : </b><a href=http://phobos/eq/item.php?id=1724>Field Supplies</a>
</td></tr></table>