<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=25117>Bllizent's Fang</a></ul></td><td><p><b>You say, </b>'hail'
<p><b>You say, </b>'purpose'
<p><b>You say, </b>'battlerager'
<p><b>You say, </b>'rallos zek'
<p><b>You say, </b>'plan'
<p><b>You say, </b>'blizzent'
<p><b>You give Reivaj the Battlerager : </b><a href=http://phobos/eq/item.php?id=25117>Bllizent's Fang</a>
</td></tr></table>