<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=24986>Golden Tablet of Draconic Strategy</a><li><a href=http://phobos/eq/item.php?id=24985>Scroll of Scaled Tactics</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=25034>Circlet of Vallon</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=188>Kromrif</a><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a><li><a href=http://phobos/eq/faction.php?id=179>King Tormax</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Semkak Prophet of Vallon says </b>'You have entered the sacred temple of Vallon Zek. This is the Temple of Strategy. We teach what must be done to be a great leader. Forethought is a powerful tool.'
<p><b>You say, </b>'teach'
<br><b>Semkak Prophet of Vallon says </b>'I cannot teach one of your kind the arts of war at this time. I must teach the other Kromzek and Kromrif that proper strategy will allow us to win the war against the dragons. If you were to serve the temple of Vallon, I might consider giving you a few words of advice about strategy.'
<p><b>You say, </b>'serve'
<br><b>Semkak Prophet of Vallon says </b>'The dragons of Velious are ancient and wise beyond belief. They have ageless strategies to destroy their foes. The Temple of Strategy must gain the knowledge they hold. I have heard rumors of a great dragon burial ground. If this tomb indeed exists, find it and seek out the knowledge of the dragons who are now dead. Bring whatever you believe will teach us their strategies and tactics of the past.'
<p><b>You give Semkak Prophet of Vallon : </b><a href=http://phobos/eq/item.php?id=24986>Golden Tablet of Draconic Strategy</a>
<br><b>Semkak Prophet of Vallon says </b>'These scrolls are ancient beyond belief. They describe the maneuvers dragons use to avoid being injured by mighty warriors. This will aid the cause of King Tormax greatly. Take this gift from the temple of Vallon and know that you are wise indeed.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=179>King Tormax</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Semkak Prophet of Vallon gives you : </b><a href=http://phobos/eq/item.php?id=25034>Circlet of Vallon</a>
<p><b>You give Semkak Prophet of Vallon : </b><a href=http://phobos/eq/item.php?id=24985>Scroll of Scaled Tactics</a>
<br><b>Semkak Prophet of Vallon says </b>'These scrolls are ancient beyond belief. They describe the maneuvers dragons use to avoid being injured by mighty warriors. This will aid the cause of King Tormax greatly. Take this gift from the temple of Vallon and know that you are wise indeed.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=179>King Tormax</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Semkak Prophet of Vallon gives you : </b><a href=http://phobos/eq/item.php?id=25034>Circlet of Vallon</a>
<br><b>Semkak Prophet of Vallon says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>