<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=30081>Coldain Head</a><li><a href=http://phobos/eq/item.php?id=25100>Shard Wurm Fang</a><li><a href=http://phobos/eq/item.php?id=25101>Ice Wyvern Stinger</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=25017>Giant Scalemail Gauntlets</a><li><a href=http://phobos/eq/item.php?id=25071>Cerulean Greaves</a><li><a href=http://phobos/eq/item.php?id=25070>Cerulean Vambraces</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=188>Kromrif</a><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=49>Coldain</a><li><a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Slaggak the Trainer says </b>'Hello there, . I am Slaggak, the trainer. The Kromrif here will soon be ready to serve the great and honorable King Tormax.'
<p><b>You say, </b>'serve'
<br><b>Slaggak the Trainer says </b>'So you say, little one. Why are you here, then? You should be out slaying those pestering little Coldain or maybe those damnable shard wurms and wyverns.'
<p><b>You say, </b>'coldain'
<br><b>Slaggak the Trainer says </b>'The Coldain are the ice dwarves. They have defiled our lands for long enough. Thinking of them makes my blood run hot. With my new position as trainer, I am not allowed to roam the lands and slaughter their kind as I once did.' Slaggak sighs. 'I long for the days when I could fashion necklaces from their skulls.'
<p><b>You say, </b>'skulls'
<br><b>Slaggak the Trainer says </b>'Go from here and seek out the Coldain, slay them, and return to me with their heads. I wish to fashion four skull talismans as I once did. If you can do this for me, I will surely let King Tormax know of your deeds and reward you with a piece of armor from the Militia armory.'
<p><b>You say, </b>'shard wurm'
<br><b>Slaggak the Trainer says </b>'You must have seen the shard wurms by now! The lizards that roam the lands eating whatever they can find? They can grow to be quite ferocious! Not nearly as ferocious as their ancient cousins, the dragons, but a nuisance nonetheless. We have a bounty on those beasts here in Kael Drakkel.'
<p><b>You say, </b>'bounty'
<br><b>Slaggak the Trainer says </b>'If you think you have what it takes to slay the shard wurms or their relatives, the wyverns, bring back proof of your exploits. For every four shard wurm fang you bring me, I am authorized to reward you with a pair of cerulean greaves. Every fourth ice wyvern stinger will grant you a pair of vambraces.'
<p><b>You give Slaggak the Trainer : </b><a href=http://phobos/eq/item.php?id=30081>Coldain Head</a>
<br><b>Slaggak the Trainer gives you : </b><a href=http://phobos/eq/item.php?id=25017>Giant Scalemail Gauntlets</a>
<br><b>Slaggak the Trainer says </b>'You are truly a worthy little . I hope this armor serves you well. If it does not, I am sure a mercenary such as yourself could find a buyer.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=49>Coldain</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Slaggak the Trainer : </b><a href=http://phobos/eq/item.php?id=25100>Shard Wurm Fang</a> x4
<br><b>Slaggak the Trainer gives you : </b><a href=http://phobos/eq/item.php?id=25071>Cerulean Greaves</a>
<br><b>Slaggak the Trainer says </b>'You are truly a worthy little . I hope this armor serves you well. If it does not, I am sure a mercenary such as yourself could find a buyer.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=49>Coldain</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Slaggak the Trainer : </b><a href=http://phobos/eq/item.php?id=25101>Ice Wyvern Stinger</a> x4
<br><b>Slaggak the Trainer gives you : </b><a href=http://phobos/eq/item.php?id=25070>Cerulean Vambraces</a>
<br><b>Slaggak the Trainer says </b>'You are truly a worthy little . I hope this armor serves you well. If it does not, I am sure a mercenary such as yourself could find a buyer.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=49>Coldain</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Slaggak the Trainer says </b>'I have no use for this, [Your Name].'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>