<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28600>Message to Wenglawks</a><li><a href=http://phobos/eq/item.php?id=20474>Receipt</a><li><a href=http://phobos/eq/item.php?id=25130>Giant Icewurm Talisman</a><li><a href=http://phobos/eq/item.php?id=25110>Giant Siren Scale Cloak</a><li><a href=http://phobos/eq/item.php?id=29068>Note to Wenglawks</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=25279>Voucher for Toolset</a><li><a href=http://phobos/eq/item.php?id=25280>Voucher for Spear</a><li><a href=http://phobos/eq/item.php?id=25281>Voucher for Mechanical Net</a><li><a href=http://phobos/eq/item.php?id=25062>Engraved Bone Pauldrons</a><li><a href=http://phobos/eq/item.php?id=25061>Bracer of Midnight</a><li><a href=http://phobos/eq/item.php?id=17049>Wenglawks Manly Purse</a><li><a href=http://phobos/eq/item.php?id=29626>Dispelling device</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Wenglawks Kkeak says </b>'Greetings, [Your Name], I have heard of you. My name is Wenglawks Kkeak. Welcome to my humble home. My sources tell me you are a [mercenary]. Is this true?'
<p><b>You say, </b>'mercenary'
<br><b>Wenglawks Kkeak says </b>'Well then, I suppose you might be [looking] for work. Are you?'
<p><b>You say, </b>'looking'
<br><b>Wenglawks Kkeak says </b>'I have been looking for a few good people to deliver goods for me. I have several [deliveries] to clients which must be made soon. My last delivery person ended up dead, unfortunately.'
<p><b>You say, </b>'deliveries'
<br><b>Wenglawks Kkeak says </b>'I have three clients whose orders must be taken care of. These will not be simple deliveries. I want you not only to deliver the items but to assist them if they need help using their packages. Do you wish to hear of the first task I have for you?'
<p><b>You say, </b>'first task'
<br><b>Wenglawks Kkeak says </b>'One of my clients lives on the shores of the Iceclad Ocean. His name is Sojan. Supposedly he is some kind of pirate from the other lands. However, I could not care less what he calls himself. He paid me well to acquire him a set of Coldain tools and they were not easy to come by. Are you willing to take this [package] to Sonjan?'
<p><b>You say, </b>'package'
<br><b>Wenglawks Kkeak says </b>'Wonderful, [Your Name]. Take this note to Kellek and he will give you the tools.'
<br><b>Wenglawks Kkeak gives you : </b><a href=http://phobos/eq/item.php?id=25279>Voucher for Toolset</a>
<p><b>You say, </b>'undertake'
<br><b>Wenglawks Kkeak says </b>'In the great divide there is a small outpost of kromrif. In that outpost you will find Bekerak, my client. I have acquired this new hunting spear for him and he may wish to test it out. Because of one simple mistake, once in my past, he thinks all of my wares are shoddy. I need the payment for the transaction still so don't let him get away without giving it to you. Take this voucher to Kellek and he will give you the spear.'
<br><b>Wenglawks Kkeak gives you : </b><a href=http://phobos/eq/item.php?id=25280>Voucher for Spear</a>
<p><b>You say, </b>'third client'
<br><b>Wenglawks Kkeak says </b>'Are you sure you will be up to this journey? It will take a hardened person to survive the trip. Let alone find my client. Do you really [want to go] out into the dangerous lands in the west?'
<p><b>You say, </b>'want to go'
<br><b>Wenglawks Kkeak says </b>'I'm not sure if I can [trust] you with this. If you die on the trip, I will be losing profit! The other deliveries were much simpler, I remind you. Can I really [trust] you as far as I can throw you? Wait, that's a bad example - I could probably throw you quite far.'
<p><b>You say, </b>'trust'
<br><b>Wenglawks Kkeak says </b>'I will curse your immortal soul if you fail, [Your Name]. In the depths of the icy waters of the cobalt scar lives an outcast siren who preys upon her own kind. We have a deal, I will provide her with an excellent hunting net and she will provide me with a giant cloak made of the scales of her kind. Take this voucher to Kellek and deliver the net. Do whatever it takes to get my cloak.'
<br><b>Wenglawks Kkeak gives you : </b><a href=http://phobos/eq/item.php?id=25281>Voucher for Mechanical Net</a>
<p><b>You give Wenglawks Kkeak : </b><a href=http://phobos/eq/item.php?id=28600>Message to Wenglawks</a>
<br><b>Wenglawks Kkeak says </b>'I have no need for this item [Your Name], you can have it back.'
<p><b>You give Wenglawks Kkeak : </b><a href=http://phobos/eq/item.php?id=20474>Receipt</a>
<br><b>Wenglawks Kkeak says </b>'I assume the delivery went well? You can have these as payment. One of my customers just decided he does not wish to buy them. They are rather sturdy! I do have another task available if you wish to [undertake] it.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Wenglawks Kkeak gives you : </b><a href=http://phobos/eq/item.php?id=25062>Engraved Bone Pauldrons</a>
<p><b>You give Wenglawks Kkeak : </b><a href=http://phobos/eq/item.php?id=25130>Giant Icewurm Talisman</a>
<br><b>Wenglawks Kkeak says </b>'He has reconsidered the offer, you say? This is most excellent! I hope this will be acceptable payment for your troubles, [Your Name]. My cash situation is not the best at this point in time. I do have a [third client] who needs delivery...'
<br><font color=yellow>You gain experience!!</font>
<br><b>Wenglawks Kkeak gives you : </b><a href=http://phobos/eq/item.php?id=25061>Bracer of Midnight</a>
<p><b>You give Wenglawks Kkeak : </b><a href=http://phobos/eq/item.php?id=25110>Giant Siren Scale Cloak</a>
<br><b>Wenglawks Kkeak says </b>'It is truly a sight to behold. This is the most fashionable cloak I have yet to see. Even King Tormax will be green with envy. This old bag has served me well, I hope you find it to your liking.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Wenglawks Kkeak gives you : </b><a href=http://phobos/eq/item.php?id=17049>Wenglawks Manly Purse</a>
<p><b>You give Wenglawks Kkeak : </b><a href=http://phobos/eq/item.php?id=29068>Note to Wenglawks</a>
<br><b>Wenglawks Kkeak says </b>'Here is the information your employer requested. Now be gone. I have more business to take care of.'
<br><b>Wenglawks Kkeak gives you : </b><a href=http://phobos/eq/item.php?id=29626>Dispelling device</a>
<br><b>Wenglawks Kkeak says </b>'I have no need for this item [Your Name], you can have it back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>