<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=25122>Head of the Huntsman</a><li><a href=http://phobos/eq/item.php?id=25123>Head of the Royal Scribe</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=25027>Coldain Skin Boots</a><li><a href=http://phobos/eq/item.php?id=25026>Coldain Skin Gloves</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=188>Kromrif</a><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a><li><a href=http://phobos/eq/faction.php?id=179>King Tormax</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Yetarr says </b>'[Your Name], your name has reached my ears more than a few times. Rumors fly that your kind will be the downfall of both the dragons and the Coldain.'
<p><b>You say, </b>'dragons'
<br><b>Yetarr says </b>'The dragons are not my primary concern, Kyenka has a greater hatred for them. I leave matters regarding to them in his capable hands. My worries are of the Coldain.'
<p><b>You say, </b>'Coldain'
<br><b>Yetarr says </b>'I do not fully trust the Kromrif to keep Kael Drakkel protected from the menace of the tiny savages. The Kromrif do not actively seek to kill them. If the Coldain are left to breed they will one day swarm over Kael and no number of Kromzek warriors will be able to save us.'
<p><b>You say, </b>'Kromrif'
<br><b>Yetarr says </b>'The Frost giants who call Kael their home have grown far too lax. So few of them train daily and actively seek out the Coldain to slay. I have advised King Tormax to send Kromzek raiding parties to raze Thurgadin, however, each time he reminds me that our strongest warriors must stay to guard against the dragon menace. What I need is a band of mercenaries to seek out and assassinate key Coldain leaders. We must destroy their ability to make war.'
<p><b>You say, </b>'assassinate'
<br><b>Yetarr says </b>'Perhaps assassinate is not the best word. I simply wish the death of some of the more compitent (sic) advisors of that foolish Dain. Within the halls of Icewell keep dwells a huntsman that has stood by the Dains side since he was a mere child. The court scribe is also more then he appears to be. Bring me their heads, I will reward you for each one. That is the only proof I will take of their deaths.'
<p><b>You give Yetarr : </b><a href=http://phobos/eq/item.php?id=25122>Head of the Huntsman</a>
<br><b>Yetarr says </b>'The death of this one must be causing great strife amoung the Coldain. Your work is greatly appreciated. I wish I could reward you with more, but these boots are among the few things I have to give.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=179>King Tormax</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Yetarr gives you : </b><a href=http://phobos/eq/item.php?id=25027>Coldain Skin Boots</a>
<p><b>You give Yetarr : </b><a href=http://phobos/eq/item.php?id=25123>Head of the Royal Scribe</a>
<br><b>Yetarr says </b>'The death of this one must be causing great strife amoung the Coldain. Your work is greatly appreciated. I wish I could reward you with more, but these gloves are among the few things I have to give.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=179>King Tormax</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Yetarr gives you : </b><a href=http://phobos/eq/item.php?id=25026>Coldain Skin Gloves</a>
<br><b>Yetarr says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>