<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4764>A List of Potion Components</a><li><a href=http://phobos/eq/item.php?id=2693>Vampyre Blood</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=154>House of Stout</a><li><a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a></ul></td><td><hr><b>When Daksins spawns </b>
<p><b>You say, </b>'hail'
<br><b>Daksins says </b>'Hello traveller, what brings you to these cursed mountains? If I were you I would turn back now, all that really lies ahead of you is certain death. The vampires that inhabitant these mountains are some of the fiercest and most skilled.'
<p><b>You say, </b>'return the extract'
<p><b>You give Daksins : </b><a href=http://phobos/eq/item.php?id=4764>A List of Potion Components</a>
<br><b>Daksins says </b>'I see you were sent by my friends from back home. I understand that they are very worried about me but they must understand that I am doing this to help my sister and anyone else infected by this horrible beasts. If only I could receive some help in collecting a vampyre blood extract sample I could return it home along with the other components that Zimloro decribes in this letter.'
<p><b>You give Daksins : </b><a href=http://phobos/eq/item.php?id=2693>Vampyre Blood</a>
<br><b>Daksins says </b>'The blood of one of the cursed! You have done it, [Your Name]. You must be a very skilled fighter to have bested one of these vile creatures. All that needs to be done now is to return this extract along with the other antidote supplies that I have prepared to Zimloro. Will you return this extract?'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=154>House of Stout</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>