<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10799>Skin of Akheva Blood</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17096>Empty Blood Skin</a><li><a href=http://phobos/eq/item.php?id=7778>Coterie Mask of the Dead</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=55>Coterie of the Eternal Night</a><li><a href=http://phobos/eq/faction.php?id=349>Valdanov Zevfeer</a><li><a href=http://phobos/eq/faction.php?id=350>Validus Custodus</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=228>Nathyn Illuminious</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Renaldok Masric says </b>'Greetings mortal. The aura of death that surrounds you is the only reason you are not already a feast for my minions. Have you come to me as a sacrifice or are you offering your [services] to the Coterie of the Eternal Night?'
<p><b>You say, </b>'services'
<br><b>Renaldok Masric says </b>'If you are powerful enough to be of use to me you will journey to the Twilight regions on the south side of Luclin and fill this wineskin with the blood of Akheva. Failure is final death, either at the hands of the Akheva or the hands of the Coterie.'
<br><b>Renaldok Masric gives you : </b><a href=http://phobos/eq/item.php?id=17096>Empty Blood Skin</a>
<p><b>You give Renaldok Masric : </b><a href=http://phobos/eq/item.php?id=10799>Skin of Akheva Blood</a>
<br><b>Renaldok Masric says </b>'Well done, for a mortal you have served us well'
<br><b>Renaldok Masric gives you : </b><a href=http://phobos/eq/item.php?id=7778>Coterie Mask of the Dead</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=55>Coterie of the Eternal Night</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=349>Valdanov Zevfeer</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=228>Nathyn Illuminious</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=350>Validus Custodus</a> has gotten better.</font>
<br><b>Renaldok Masric says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>