<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=31748>Damaged Custodus Legionnaire Helm</a><li><a href=http://phobos/eq/item.php?id=31749>Damaged Custodus Centurion Helm</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=31750>Blood Dipped Dart</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=55>Coterie of the Eternal Night</a><li><a href=http://phobos/eq/faction.php?id=349>Valdanov Zevfeer</a><li><a href=http://phobos/eq/faction.php?id=350>Validus Custodus</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=228>Nathyn Illuminious</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Tymoz says </b>'So , you dare to stand before the mighty Tymoz?  I am the Governor of this village of the Coterie of the Eternal Night.  Do you wish to assist the Coterie, or will you better serve us as sustenance for our eternal lives?'
<p><b>You say, </b>'assist the Coterie'
<br><b>Tymoz says </b>'You have made an intelligent decision my friend.  Our primary foe is the meddling Validus Custodus, the militia of Katta Castellum.  I will reward you for every two damaged custodus legionnaire helms or two damaged custodus centurion helms that you present to me as proof that you have slain members of our enemies ranks.'
<p><b>You give Tymoz : </b><a href=http://phobos/eq/item.php?id=31748>Damaged Custodus Legionnaire Helm</a> x2, <a href=http://phobos/eq/item.php?id=31749>Damaged Custodus Centurion Helm</a> x2
<br><b>Tymoz says </b>'Excellent! Two less of thos self righteous Validus Custodus goons to worry about!'
<br><b>Tymoz gives you : </b><a href=http://phobos/eq/item.php?id=31750>Blood Dipped Dart</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=55>Coterie of the Eternal Night</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=349>Valdanov Zevfeer</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=228>Nathyn Illuminious</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=350>Validus Custodus</a> has gotten better.</font>
<br><b>Tymoz says </b>'Excellent! Two less of thos self righteous Validus Custodus goons to worry about!'
<br><b>Tymoz gives you : </b><a href=http://phobos/eq/item.php?id=31750>Blood Dipped Dart</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=55>Coterie of the Eternal Night</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=349>Valdanov Zevfeer</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=228>Nathyn Illuminious</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=350>Validus Custodus</a> has gotten better.</font>
</td></tr></table>