<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10295>Summoned: Firefly Globe</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Venril Sathirs remains says </b>'The living fire. I seek the fires of life. Bring them.'
<p><b>You give Venril Sathirs remains : </b><a href=http://phobos/eq/item.php?id=10295>Summoned: Firefly Globe</a>
<br><font color=green><b>Venril Sathirs remains </b>grasps the glowing sphere of fireflies from your hands. Tendrils of mystical energy begin to flow forth from the swarm of glowing insects like tiny fingers. The glowing tendrils begin to reach into the ribcage of the rotting remains of Venril Sathir, coalescing into the form of an iksar ghost.</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=102123>Spirit_of_Venril_Sathir</a></b> spawns.</font>
<br><b>Venril Sathirs remains disappears.</b>
</td></tr></table>