<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=item1></a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18844>A Sealed Letter</a><li><a href=http://phobos/eq/item.php?id=13581>Old Black Tunic*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Eolorn J-Axx says </b>'It is good to see new blood in our halls. I am the leader of this house. If you are looking for guidance, seek out the masters within. I rarely appoint tasks to new recruits, unless I need to retrieve the [foreign take].'
<p><b>You say, </b>'take'
<br><b>Eolorn J-Axx says </b>'We have rogues operating in a few great cities. We send young rogues to retrieve the monthly take. We have been awaiting the Freeport delivery. The last youth I sent must have been killed along the way. I will need a new runner to [retrieve the chest].'
<p><b>You say, </b>'chest'
<br><b>Eolorn J-Axx says </b>'You seem able enough. Here. Take this note to Freeport. Go through the Commonlands and be careful not to encounter any Freeport guards. There is a network of aqueducts accessible through hidden passages. Search the outside walls of Freeport. Take the note to Giz. She will meet you at night, on an island in the harbor. Good luck.'
<br><b>Eolorn J-Axx gives you : </b><a href=http://phobos/eq/item.php?id=18844>A Sealed Letter</a>
<p><b>You give Eolorn J-Axx : </b><a href=http://phobos/eq/item.php?id=18752>A tattered note</a>
<br><b>Eolorn J-Axx says </b>'Thanks.'
<br><b>Eolorn J-Axx gives you : </b><a href=http://phobos/eq/item.php?id=13581>Old Black Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>