<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13071>Rat Whiskers</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=87>Dreadguard Inner</a><li><a href=http://phobos/eq/faction.php?id=69>Dark Bargainers</a><li><a href=http://phobos/eq/faction.php?id=155>Indigo Brotherhood</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=260>Primordial Malice</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Exterminator Gilea says </b>'Hello, [Your Name]. I was hired to eradicate all these pesky rodents running around the city, but there are too many of them. If you could help me by bringing back four of their whiskers I should have a few spare coins for you.'
<p><b>You give Exterminator Gilea : </b><a href=http://phobos/eq/item.php?id=13071>Rat Whiskers</a> x4
<br><b>Exterminator Gilea says </b>'Well there are still many rodents around, but I will honor my deal. Here are your coins. Now I must get back to work.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=87>Dreadguard Inner</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=69>Dark Bargainers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=155>Indigo Brotherhood</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=260>Primordial Malice</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 1gp 1sp 1cp
</td></tr></table>