<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13889>Bag of Snake Parts</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12258>Dark Shield of Ebon</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=111>Fungus Man</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Hekzin G-Zule says </b>'How's it going. scrub? Correct me if I'm wrong. but you appear to be a rogue. If you're a [new rogue]. it's my job to test your skill.  If you are not. then by speaking with me. I see you show interest in [joining this house of rogues].'
<p><b>You say, </b>'i am a new rogue'
<br><b>Hekzin G-Zule says </b>'We of the Ebon Mask must first be sure you are skilled with a blade. At the same time. we are attempting to create a new type of armor for our rogues. So it is the test of each young rogue to take this bag into Nektulos and fill it with three moss snake skins and three snake fangs. then combine them. We get the bag and you earn a little respect as well as the [Dark Shield of Ebon].'
<p><b>You say, </b>'what dark shield of ebon'
<br><b>Hekzin G-Zule says </b>'The Dark Shield of Ebon was made for the use of this house by the finest craftsmen of Neriak.  It can be carried in the hand as well as slung upon one's back.  Besides this advantage. it is much lighter than most other shields.'
<p><b>You say, </b>'i am joining this house of rogues'
<br><b>Hekzin G-Zule says </b>'We of the Ebon Mask must first be sure you are skilled with a blade. At the same time. we are attempting to create a new type of armor for our rogues. So it is the test of each young rogue to take this bag into Nektulos and fill it with three moss snake skins and three snake fangs. then combine them. We get the bag and you earn a little respect as well as the [Dark Shield of Ebon].'
<p><b>You give Hekzin G-Zule : </b><a href=http://phobos/eq/item.php?id=13889>Bag of Snake Parts</a>
<br><b>Hekzin G-Zule says </b>'Fine work for a scrub. Maybe one day you will be able to test this new snakescale armor out. For the moment you shall take the [Dark Shield of Ebon] if you do not own one already.'
<br><b>Hekzin G-Zule gives you : </b><a href=http://phobos/eq/item.php?id=12258>Dark Shield of Ebon</a>
<br><b>You receive </b> 4sp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=111>Fungus Man</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>