<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=22617>A Tattered Journal pg 1</a><li><a href=http://phobos/eq/item.php?id=22618>A Tattered Journal pg 2</a><li><a href=http://phobos/eq/item.php?id=22619>A Tattered Journal pg 3</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=22698>Mace of the Darkpriest</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>High Priestess Alexandria says </b>'Greetings child, what business do you have here? I'm sorry but I will only deal with Clerics that are willing to prove their loyalty to Innoruuk. I cannot deal with every single heathen that feels it is necessary to bid me a good day. If you are a [Cleric of Innoruuk] I might be able to aid you in your training.'
<p><b>You say, </b>'Cleric of Innoruuk'
<p><b>You say, </b>'interested in proving myself'
<p><b>You say, </b>'magical relic'
<p><b>You say, </b>'important items'
<p><b>You say, </b>'armor recipes'
<p><b>You say, </b>'Armguards'
<p><b>You say, </b>'Boots'
<p><b>You say, </b>'Bracer'
<p><b>You say, </b>'Breastplate'
<p><b>You say, </b>'Gauntlets'
<p><b>You say, </b>'Greaves'
<p><b>You say, </b>'Helm'
<p><b>You say, </b>'final test'
<p><b>You give High Priestess Alexandria : </b><a href=http://phobos/eq/item.php?id=22617>A Tattered Journal pg 1</a>, <a href=http://phobos/eq/item.php?id=22618>A Tattered Journal pg 2</a>, <a href=http://phobos/eq/item.php?id=22619>A Tattered Journal pg 3</a>
<br><b>High Priestess Alexandria says </b>'Your prowess both in the classroom and on the battlefield has certainly amazed me. Please take this relic that is only presented to the most dedicated initiates and carry it with pride. You have made your house very proud on this day.'
<br><b>High Priestess Alexandria gives you : </b><a href=http://phobos/eq/item.php?id=22698>Mace of the Darkpriest</a>
<br><b>High Priestess Alexandria says </b>'[Your Name], I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>