<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=2416>Note to Kanthuk</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17124>Mail Assembly Kit</a><li><a href=http://phobos/eq/item.php?id=19561>Tattered Boot Pattern</a><li><a href=http://phobos/eq/item.php?id=19558>Tattered Wristband Pattern</a><li><a href=http://phobos/eq/item.php?id=19555>Tattered Cap Pattern</a><li><a href=http://phobos/eq/item.php?id=19559>Tattered Glove Pattern</a><li><a href=http://phobos/eq/item.php?id=19560>Tattered Pant Pattern</a><li><a href=http://phobos/eq/item.php?id=19557>Tattered Sleeve Pattern</a><li><a href=http://phobos/eq/item.php?id=19556>Tattered Tunic Pattern</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Kanthu M-Rekkor says </b>'Greetings, [Your Name]. So you are one of Selzar's new recruits. You are to assist in the construction of the armor you will don as a new Rogue of the House of the Ebon Mask. I have assembled a kit that is used in the crafting of Ashen Bone Mail. You must travel beyond Neriak into the Nektulos Forest for the [materials] that compose the armor. '
<p><b>You say, </b>'materials'
<br><b>Kanthu M-Rekkor says </b>'Many species of dangerous creatures, the restless dead, and halfling invaders from Rivervale inhabit the Nektulos Forest. You must defeat these creatures and halflings in order to obtain the materials. The materials you seek depend on the piece of armor you desire. Do you desire to craft [gloves], [boots], a [bracer], a [coif], [leggings], [sleeves], or a [tunic]? '
<br><b>Kanthu M-Rekkor gives you : </b><a href=http://phobos/eq/item.php?id=17124>Mail Assembly Kit</a>
<p><b>You say, </b>'boots'
<br><b>Kanthu M-Rekkor says </b>'To craft Ashen Bone Mail Boots you require two [silk thread], two ruined ash drakeling scales, and two halfling foot bones. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Boot Pattern. '
<br><b>Kanthu M-Rekkor gives you : </b><a href=http://phobos/eq/item.php?id=19561>Tattered Boot Pattern</a>
<p><b>You say, </b>'bracer'
<br><b>Kanthu M-Rekkor says </b>'To craft an Ashen Bone Mail Bracer you require a [silk thread], a ruined ash drakeling scales, and a halfling ulna bone. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Bracer Pattern. '
<br><b>Kanthu M-Rekkor gives you : </b><a href=http://phobos/eq/item.php?id=19558>Tattered Wristband Pattern</a>
<p><b>You say, </b>'coif'
<br><b>Kanthu M-Rekkor says </b>'To craft a Ashen Bone Mail Coif you require two [silk thread], a ruined ash drakeling scales, and a halfling skull. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Cap Pattern. '
<br><b>Kanthu M-Rekkor gives you : </b><a href=http://phobos/eq/item.php?id=19555>Tattered Cap Pattern</a>
<p><b>You say, </b>'gloves'
<br><b>Kanthu M-Rekkor says </b>'To craft Ashen Bone Mail Gloves you require two [silk thread], a ruined ash drakeling scales, and two halfling finger bones. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Glove Pattern. '
<br><b>Kanthu M-Rekkor gives you : </b><a href=http://phobos/eq/item.php?id=19559>Tattered Glove Pattern</a>
<p><b>You say, </b>'leggings'
<br><b>Kanthu M-Rekkor says </b>'To craft Ashen Bone Mail Leggings you require three [silk thread], ash drakeling scales, two halfling tibia, and a halfling pelvis bone. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Leggings Pattern.'
<br><b>Kanthu M-Rekkor gives you : </b><a href=http://phobos/eq/item.php?id=19560>Tattered Pant Pattern</a>
<p><b>You say, </b>'sleeve'
<br><b>Kanthu M-Rekkor says </b>'To craft Ashen Bone Mail Sleeves you require two [silk thread], ash drakeling scales, and two halfling humerus bones. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Sleeves Pattern. '
<br><b>Kanthu M-Rekkor gives you : </b><a href=http://phobos/eq/item.php?id=19557>Tattered Sleeve Pattern</a>
<p><b>You say, </b>'tunic'
<br><b>Kanthu M-Rekkor says </b>'To craft an Ashen Bone Mail Tunic you require four [silk thread], pristine ash drakeling scales, a halfling sternum, and a halfling ribcage. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Tunic Pattern. '
<br><b>Kanthu M-Rekkor gives you : </b><a href=http://phobos/eq/item.php?id=19556>Tattered Tunic Pattern</a>
<p><b>You give Kanthu M-Rekkor : </b><a href=http://phobos/eq/item.php?id=2416>Note to Kanthuk</a>
<br><b>Kanthu M-Rekkor says </b>'Greetings, [Your Name]. So you are one of Selzar's new recruits. You are to assist in the construction of the armor you will don as a new Rogue of the House of the Ebon Mask. I have assembled a kit that is used in the crafting of Ashen Bone Mail. You must travel beyond Neriak into the Nektulos Forest for the [materials] that compose the armor. '
</td></tr></table>