<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13030>Red Wine</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=87>Dreadguard Inner</a><li><a href=http://phobos/eq/faction.php?id=88>Dreadguard Outer</a><li><a href=http://phobos/eq/faction.php?id=69>Dark Bargainers</a></ul></td><td><p><b>You say, </b>'scribe of Dal'
<br><b>Lokar To-Biath says </b>'The Scribes of Dal? All of them are long since [dead].. or at least most would say that.'
<p><b>You say, </b>'dead'
<br><b>Lokar To-Biath says </b>'Perhaps, perhaps not. I cannot remember, but perhaps Innoruuk would help me remember should you tithe him a bottle of red wine from the Blind Fish.'
<p><b>You say, </b>'vow'
<br><b>Lokar To-Biath says </b>'Break the vow? She might. Were you to tithe 70 gold to your god, Innoruuk, he might aid you.'
<p><b>You give Lokar To-Biath : </b><a href=http://phobos/eq/item.php?id=13030>Red Wine</a>
<br><b>Lokar To-Biath says </b>'Ah, yes, let me pray to our god.. Yes, Innoruuk has given me wisdom. A Scribe of Dal still exists, disguised as a barkeep in the Blind Fish. This information will not help you though, for she has sworn a [vow] of silence and will not speak of the Dal.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=87>Dreadguard Inner</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=88>Dreadguard Outer</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=69>Dark Bargainers</a> has gotten better.</font>
<br><b>Lokar To-Biath says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>