<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18828>Testimony</a><li><a href=http://phobos/eq/item.php?id=13390>Thex Mallet</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2317>Cloak of the Undead Eye</a><li><a href=http://phobos/eq/item.php?id=5374>Reaper of the Dead</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=322>The Dead</a><li><a href=http://phobos/eq/faction.php?id=268>Queen Cristanos Thex</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=177>King Naythox Thex</a><li><a href=http://phobos/eq/faction.php?id=170>Keepers of the Art</a><li><a href=http://phobos/eq/faction.php?id=91>Eldritch Collective</a><li><a href=http://phobos/eq/faction.php?id=260>Primordial Malice</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Loveal S-Nez says </b>'What is this I see before me? A would-be hero of the Dead? You reek of false bravado. I have seen others much stronger than you meet their fate at the end of a blade. I see no reason to continue our conversation. How can one such as you assist with my [delegated duties]?'
<p><b>You say, </b>'delegated duties'
<br><b>Loveal S-Nez says </b>'Why do you ask? I know why. Glory has captured your affections. Those who seek glory find death. Still, you may be of some use. Before I assign you a task, I must be assured of your power. I require you to [perform a test].'
<p><b>You say, </b>'perform a test'
<br><b>Loveal S-Nez says </b>'In the Lavastorm Mountain Range there have been sightings of a paladin, one Sir Lindeal. He has compromised our routes between.. well, that is none of your concern. All you need to know is that this paladin of the Temple of Marr must be sent to his everlasting life. Do so and prove your worth to us. I await your proof. Use no assistance. If you are truly his equal then I shall know. I know all.'
<p><b>You say, </b>'appointed tasks'
<br><b>Loveal S-Nez says </b>'Very well. You have gained the appropriate power. I require you to journey to the Commonlands and seek out Kizdean Gix. He is a member of a very important force. Tell him 'Utalk Adarev Otcin'. Remember this password.'
<p><b>You say, </b>'Thex Mallet'
<br><b>Loveal S-Nez says </b>'All you can know is that the Thex Mallet is desired by our Queen. If we are not successful in its retrieval, it will be our heads which adorn her trophy room. We have learned its location and believe it to be broken into three separate pieces.'
<p><b>You say, </b>'Queen Cristanos Thex'
<br><b>Loveal S-Nez says </b>'The Queen of the Teir'Dal is the most powerful of all. It is she who should sit on the throne and not King Naythox. The Dead are her humble servants. We await the day when she shall finally take her rightful position as ruler of Neriak.'
<p><b>You say, </b>'King Naythox Thex'
<br><b>Loveal S-Nez says </b>'A competent and powerful warrior, but a warrior nonetheless. He has suppressed the true glory of the Teir'Dal. Perhaps it is time for a new ruler of Neriak.'
<p><b>You give Loveal S-Nez : </b><a href=http://phobos/eq/item.php?id=18828>Testimony</a>
<br><b>Loveal S-Nez says </b>'So you have succeeded where others have failed. You show promise. Take this then. You shall be a valuable asset to the Dead and soon this shall be of value to one so great. This will help you on your way. Are you still interested in my [appointed tasks]?'
<br><b>Loveal S-Nez gives you : </b><a href=http://phobos/eq/item.php?id=2317>Cloak of the Undead Eye</a>
<br><b>You receive </b> 14sp
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=322>The Dead</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=268>Queen Cristanos Thex</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=177>King Naythox Thex</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=170>Keepers of the Art</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=91>Eldritch Collective</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=260>Primordial Malice</a> has gotten worse.</font>
<p><b>You give Loveal S-Nez : </b><a href=http://phobos/eq/item.php?id=13390>Thex Mallet</a>
<br><b>Loveal S-Nez says </b>'Oh how grand it is!! Look at it!! I feel the power trembling within. Who would have thought such an item would be abandoned? You have performed supremely. Queen Cristanos shall reward me greatly and I shall reward you greatly. Here is my weapon from years past.. the Reaper of the Dead. I believe it has one soul still trapped within.'
<br><b>Loveal S-Nez gives you : </b><a href=http://phobos/eq/item.php?id=5374>Reaper of the Dead</a>
<br><b>You receive </b> 14sp
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=322>The Dead</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=268>Queen Cristanos Thex</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=177>King Naythox Thex</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=170>Keepers of the Art</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=91>Eldritch Collective</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=260>Primordial Malice</a> has gotten worse.</font>
<br><b>Loveal S-Nez says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>