<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Mare X-Lottl says </b>'Hello there. sweetie!!  How about letting me dance for you?  Two gold and I will do a little dance for you.'
<p><b>You say, </b>'Tayla'
<br><b>Mare X-Lottl says </b>'Why do you seek that little scamp when you have Mare right here? If you really want to know where she is, it will cost you. Did I ever tell you that my heart belongs to Jasper?'
</td></tr></table>