<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=16170>Basilisk Hatchling Hide</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19610>Scaled Femur Shield</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=69>Dark Bargainers</a><li><a href=http://phobos/eq/faction.php?id=87>Dreadguard Inner</a><li><a href=http://phobos/eq/faction.php?id=88>Dreadguard Outer</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Medron Y-Lask says </b>'Welcome to the Furrier Royale. Here you will find the finest skins from a variety of Norraths lesser creatures.'
<p><b>You give Medron Y-Lask : </b><a href=http://phobos/eq/item.php?id=16170>Basilisk Hatchling Hide</a> x2
<br><font color=green><b>Medron Y-Lask </b>Medron Y`Lask stretches and fastened the basilisk skins across the shield frame and attaches a leather strap and grip to the back of the shield. Here is your new shield young Shadowknight. I have been paid in advance by the Lodge of the Dead for the shields assembly. May Innoruuk strengthen you in your service to Her Majesty Queen Cristanos.</font>
<br><b>Medron Y-Lask gives you : </b><a href=http://phobos/eq/item.php?id=19610>Scaled Femur Shield</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=69>Dark Bargainers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=87>Dreadguard Inner</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=88>Dreadguard Outer</a> has gotten better.</font>
</td></tr></table>