<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10791>Glowing Coin of Tash</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10792>Gleaming Coin of Tash</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=442>Temple Of Sol Ro</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=291>Shadowed Men</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Mizr N-Mar says </b>'Have you come to buy a scroll from me?'
<p><b>You say, </b>'coin'
<br><b>Mizr N-Mar says </b>'So, you want a coin do you?'
<p><b>You give Mizr N-Mar : </b><a href=http://phobos/eq/item.php?id=10791>Glowing Coin of Tash</a>
<br><b>Mizr N-Mar says </b>'Ah - the Coin of Tash - and already enchanted by.. ? Tarn? Very good! I have enchanted it further - you must now take the coin to Raine Beteria in the Library of Erudin to get the final enchantment.'
<br><b>Mizr N-Mar gives you : </b><a href=http://phobos/eq/item.php?id=10792>Gleaming Coin of Tash</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=442>Temple Of Sol Ro</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=291>Shadowed Men</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>