<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13389>Box of Beetle Eyes</a><li><a href=http://phobos/eq/item.php?id=10124>Mammoth Tusks</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17930>Empty Box</a><li><a href=http://phobos/eq/item.php?id=13022>Rotgrub Rye</a><li><a href=http://phobos/eq/item.php?id=15362>Spell: Convoke Shadow</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=322>The Dead</a><li><a href=http://phobos/eq/faction.php?id=268>Queen Cristanos Thex</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=177>King Naythox Thex</a><li><a href=http://phobos/eq/faction.php?id=170>Keepers of the Art</a><li><a href=http://phobos/eq/faction.php?id=91>Eldritch Collective</a><li><a href=http://phobos/eq/faction.php?id=260>Primordial Malice</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Noxhil V-Sek says </b>'Greetings, [Your Name]!  We of the Dead are proud to have you among us.  Your lineage is well known.  Still, you must learn to claw your way to the upper echelon.  There are many [menial tasks] to be performed before you can truly be inducted as a member.'
<p><b>You say, </b>'menial tasks'
<br><b>Noxhil V-Sek says </b>'You cannot avoid the toil of peons. We have all spent our time in the lower ranks. There are duties such as [collecting beetle eyes].'
<p><b>You say, </b>'collecting beetle eyes'
<br><b>Noxhil V-Sek says </b>'Take this chest.  It has been fitted with a mold designed to hold ten beetle eyes.  We require them for further experiments.  Do not return until you fill the chest.'
<br><b>Noxhil V-Sek gives you : </b><a href=http://phobos/eq/item.php?id=17930>Empty Box</a>
<p><b>You say, </b>'other components'
<br><b>Noxhil V-Sek says </b>'The other components that are required are two Bull Elephant tusks.  Mammoth tusks would do as well.'
<p><b>You give Noxhil V-Sek : </b><a href=http://phobos/eq/item.php?id=13389>Box of Beetle Eyes</a>
<br><b>Noxhil V-Sek says </b>'Fantastic work, my child! We shall store these for further experiments. Take this as extra payment for a fine job. You have done so well I believe you can assist in obtaining two [other components].'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=322>The Dead</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=268>Queen Cristanos Thex</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=177>King Naythox Thex</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=170>Keepers of the Art</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=91>Eldritch Collective</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=260>Primordial Malice</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 16sp
<br><b>Noxhil V-Sek gives you : </b><a href=http://phobos/eq/item.php?id=13022>Rotgrub Rye</a>
<p><b>You give Noxhil V-Sek : </b><a href=http://phobos/eq/item.php?id=10124>Mammoth Tusks</a> x2
<br><b>Noxhil V-Sek says </b>'These will do.  Thank you, child.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=322>The Dead</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=268>Queen Cristanos Thex</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=177>King Naythox Thex</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=170>Keepers of the Art</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=91>Eldritch Collective</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=260>Primordial Malice</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Noxhil V-Sek gives you : </b><a href=http://phobos/eq/item.php?id=15362>Spell: Convoke Shadow</a>
<br><b>Noxhil V-Sek says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>