<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=7041>Burning Rapier</a><li><a href=http://phobos/eq/item.php?id=9438>Lon's Head</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=24095>Vein Rot Sketch</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Pazin Punox says </b>'Welcome to the Hall of the Ebon Mask. You had best be a rogue or you have no business here. We have nothing to say to outsiders.'
<p><b>You say, </b>'dark assassin'
<p><b>You say, </b>'vexing you'
<p><b>You give Pazin Punox : </b><a href=http://phobos/eq/item.php?id=7041>Burning Rapier</a>, <a href=http://phobos/eq/item.php?id=9438>Lon's Head</a>
<br><font color=green><b>Pazin Punox </b>laughs. 'Here, take this then!'</font>
<br><b>Pazin Punox gives you : </b><a href=http://phobos/eq/item.php?id=24095>Vein Rot Sketch</a>
<br><b>Pazin Punox says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>