<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=14550>Woven Grass Amulet</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1369>Initiate Symbol of Innoruuk</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=177>King Naythox Thex</a><li><a href=http://phobos/eq/faction.php?id=256>Priests of Innoruuk</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=43>Clerics of Tunare</a><li><a href=http://phobos/eq/faction.php?id=257>Priests of Life</a><li><a href=http://phobos/eq/faction.php?id=258>Priests of Marr</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Perrir Zexus says </b>'Salutations, [Your Name]! Your devotion to our Lord Innoruuk is evident in your actions and on your soul. As a member of the Spires of Innoruuk, you are required to obtain and wear the symbol of your station among the clergy. I can award you the [hematite symbol of Innoruuk] worn by the initiates of the Spires.'
<p><b>You say, </b>'hematite symbol of Innoruuk'
<br><b>Perrir Zexus says </b>'The forest beyond the gates of our grand city has been shaped by the magic of our Lord Innoruuk to be more hospitable to our kind. There are halfling druids in the service of Karana who have set up shrines there in hopes of restoring the forest to its former state. They could never succeed in their task with their feeble powers granted by their insignificant god, yet still, they are a nuisance. Bring me four of the holy symbols worn by the druids and I shall grant you the initiate symbol of Innoruuk.'
<p><b>You give Perrir Zexus : </b><a href=http://phobos/eq/item.php?id=14550>Woven Grass Amulet</a> x4
<br><font color=green><b>Perrir Zexus </b>laughs. 'Here, take this then!  You are now and initiate of Innoruuk.  Speak with Ithvol K`Jasn for further advancement.'</font>
<br><b>Perrir Zexus gives you : </b><a href=http://phobos/eq/item.php?id=1369>Initiate Symbol of Innoruuk</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=177>King Naythox Thex</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=256>Priests of Innoruuk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=43>Clerics of Tunare</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=257>Priests of Life</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=258>Priests of Marr</a> has gotten worse.</font>
<br><b>Perrir Zexus says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>