<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19578>Halfling Clavicle</a><li><a href=http://phobos/eq/item.php?id=19577>Halfling Fibula</a><li><a href=http://phobos/eq/item.php?id=13060>Large Snake Skin</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2416>Note to Kanthuk</a><li><a href=http://phobos/eq/item.php?id=19608>Scaled Bone Rapier</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Selzar L-Crit says </b>'What have we here? Another hopeful member of the House of the Ebon Mask? You've got much to learn before you will be of much use to our House or the secret operations that support both the thrones of our King and Queen. First you need to outfit yourself in a suit of [armor], [Your Name]. '
<p><b>You say, </b>'armor'
<br><b>Selzar L-Crit says </b>'Seek Kanthu M'Rekkor and give him this request parchment. When you have outfitted yourself in a suit of armor return to the House of the Ebon Mask and I will grant you [another task]. '
<br><b>Selzar L-Crit gives you : </b><a href=http://phobos/eq/item.php?id=2416>Note to Kanthuk</a>
<p><b>You say, </b>'other task'
<br><b>Selzar L-Crit says </b>'Ah, you are eager to advance further within the House of the Ebon Mask. Although it is my duty to aid your training, do not allow your arrogance to blind you to your lowly position in our House. I can see that you have not yet learned to temper the use of your tongue. Your next task is to assist the construction of a [weapon] and [bow] worthy of being wielded by a Rogue of the House of the Ebon Mask. '
<p><b>You say, </b>'bow'
<br><b>Selzar L-Crit says </b>'The Halfling Druids from Rivervale that frequent the ancient druid ruins in the Nektulos Forest are guarded by Leatherfoot Warriors. The peck druids perform the rituals that they hope will prevent Innoruuks corruption from spreading deeper into the Forest and the lands beyond. Should you slay the peck warriors guarding the druids and obtain a Leatherfoot Short Bow, take the bow, a Black Mamba Skin, and a Lock of Zombie Hair to Andara C'Luzz at The Bleek Fletcher in the Neriak Commons near the headquarters of the Indigo Brotherhood. '
<p><b>You say, </b>'weapon'
<br><b>Selzar L-Crit says </b>'Beyond the mouth of Neriak lies the Nektulos Forest. There the Halflings of Rivervale have set up camps at ancient druid holy sites in an attempt to cleanse Innoruuks corruption that is spreading through the Nektulos Forest. Slay these trespassers and bring me a Large Snake Skin, a Halfling Fibula bone, and a Halfling Clavicle bone. '
<p><b>You give Selzar L-Crit : </b><a href=http://phobos/eq/item.php?id=13060>Large Snake Skin</a>, <a href=http://phobos/eq/item.php?id=19577>Halfling Fibula</a>, <a href=http://phobos/eq/item.php?id=19578>Halfling Clavicle</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Selzar L-Crit gives you : </b><a href=http://phobos/eq/item.php?id=19608>Scaled Bone Rapier</a>
<br><b>Selzar L-Crit says </b>'You have slain enemies of our order.  Carry your weapon with pride.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>