<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=77522></a><li><a href=http://phobos/eq/item.php?id=26662>Swirling Banshee Essence</a><li><a href=http://phobos/eq/item.php?id=29921>Arachnae Fangs</a><li><a href=http://phobos/eq/item.php?id=26640>A Wrulon Claw</a><li><a href=http://phobos/eq/item.php?id=26632>A Blood Raven Tailfeather</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18651>Note to the Troll</a><li><a href=http://phobos/eq/item.php?id=12212>Kaglari Mana Doll</a><li><a href=http://phobos/eq/item.php?id=28740>Troll Receipt</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Bregna says </b>'Me says hi to you. What you want from me? Oh!! Me shaman trainer. You must be shaman. Are you [shaman Darkone]?'
<p><b>You say, </b>'shaman darkone'
<br><b>Bregna says </b>'You choose rite if you bes a shaman. We's da best. You remember ta not get in Kaglari way. She get mad berry easy. She gets berry mad at Bregna if she finds out me make [big mistake].'
<p><b>You say, </b>'big mistake'
<br><b>Bregna says </b>'Kaglari make me do the tasks for her. She tolds me to take crate of speshal poshuns to sumwun in Nektoolos forust. But I make mistake. I fall asleep under da trees becuz I was so tired. I wake up and poshuns are gone! Sumwun take the poshuns frum me. Dey leave dis note wit me. Me tinks dey play trick on me. Me tinks it be da stinkin' Halflings. Me needs ta gets dem back before Kaglari find out. I need sumwun to help me find da poshuns.'
<br><b>Bregna gives you : </b><a href=http://phobos/eq/item.php?id=18651>Note to the Troll</a>
<p><b>You give Bregna : </b><a href=http://phobos/eq/item.php?id=77522></a>
<br><b>Bregna says </b>'Phew!  Me are safe from Kaglari's beating.  Dank yoo, [Your Name].  Take dis.'
<br><b>Bregna gives you : </b><a href=http://phobos/eq/item.php?id=12212>Kaglari Mana Doll</a>
<p><b>You give Bregna : </b><a href=http://phobos/eq/item.php?id=26662>Swirling Banshee Essence</a>, <a href=http://phobos/eq/item.php?id=29921>Arachnae Fangs</a>, <a href=http://phobos/eq/item.php?id=26640>A Wrulon Claw</a>, <a href=http://phobos/eq/item.php?id=26632>A Blood Raven Tailfeather</a>
<br><b>Bregna says </b>'Me been waitin for doze. Dank yoo, [Your Name].  Take dis.'
<br><b>Bregna gives you : </b><a href=http://phobos/eq/item.php?id=28740>Troll Receipt</a>
</td></tr></table>