<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12073>Steel Boning</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19030>Crate of Teir`Dal Provisions</a></ul></td><td><p><b>You say, </b>'Ithvol sent me'
<br><b>Dran -Slug- Rembor says </b>'Did he?  Good, bring me two steel bonings to complete this crate of provisions and be swift!'
<p><b>You give Dran -Slug- Rembor : </b><a href=http://phobos/eq/item.php?id=12073>Steel Boning</a> x2
<br><b>Dran -Slug- Rembor says </b>'Here's the crate of provisions. Take this to Dragoon Szorn in the Lesser Faydark immediately!'
<br><b>Dran -Slug- Rembor gives you : </b><a href=http://phobos/eq/item.php?id=19030>Crate of Teir`Dal Provisions</a>
<p><b>You give Dran -Slug- Rembor : </b>
<br><b>Dran -Slug- Rembor says </b>'I don't need this.'
<br><b>Dran -Slug- Rembor says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>