<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>Smaka says </b>'You want stuff? Or mebby you looks for a cure?'
<p><b>You say, </b>'cough elixir'
<br><b>Smaka says </b>'Ahh, you want me cure?! It cost lots of money, big big secret it is. Only us ogres know how to make. You wants? Only 1000 platinum! Make you feels bedder in no times!'
</td></tr></table>