<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10627>Head of a Prince</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10608>Chalice of Kings</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Joren Nobleheart says </b>'I hope you have been sent by the King. There is an urgent matter at hand.'
<p><b>You say, </b>'i have been sent by the king'
<br><b>Joren Nobleheart says </b>'Our sources at the outpost have learned that the Chardokian royal family had a part in the disappearance of Firiona Vie. I have been ordered by King Tearis Thex to locate individuals familiar with the new lands and to order them to the gates of Chardok Mountain. Do you accept the king's order?'
<p><b>You say, </b>'i accept'
<br><b>Joren Nobleheart says </b>'Gather your forces and march on the gates of Chardok. You are to strike deep into the home of Overking Bathezid. Your goal is not the overking himself, but his only living heir. His son's head will be the price to pay for their involvement in this kidnapping.'
<p><b>You give Joren Nobleheart : </b><a href=http://phobos/eq/item.php?id=10627>Head of a Prince</a>
<br><b>Joren Nobleheart says </b>'Vengeance has been fufilled! However, the King still has a heavy heart. Not until Firiona has been returned can this sadness be lifted. But in appreciation of your efforts, I am honored to present to you the King's Chalice.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Joren Nobleheart gives you : </b><a href=http://phobos/eq/item.php?id=10608>Chalice of Kings</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>