<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18778>An Enrollment Letter</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13593>Torn Training Robe*</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=170>Keepers of the Art</a><li><a href=http://phobos/eq/faction.php?id=178>King Tearis Thex</a><li><a href=http://phobos/eq/faction.php?id=99>Faydark's Champions</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=322>The Dead</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Kinool Goldsinger says </b>'Hail and welcome.  I am sure you have much to do, but could I ask a [favor] of you?'
<p><b>You say, </b>'What favor'
<br><b>Kinool Goldsinger says </b>'Oh, um, on second thought, never mind.  I should really just do it myself.  Thank you anyway.'
<p><b>You give Kinool Goldsinger : </b><a href=http://phobos/eq/item.php?id=18778>An Enrollment Letter</a>
<br><b>Kinool Goldsinger says </b>'Greetings and welcome aboard!  My name's Kinool. Master Enchanter of the Keepers of the Art.  Here is your guild tunic. Make us proud, young pupil!'
<br><b>Kinool Goldsinger gives you : </b><a href=http://phobos/eq/item.php?id=13593>Torn Training Robe*</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=170>Keepers of the Art</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=178>King Tearis Thex</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=99>Faydark's Champions</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=322>The Dead</a> has gotten worse.</font>
</td></tr></table>