<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13068>Bat Wing</a><li><a href=http://phobos/eq/item.php?id=18777>An Enrollment Letter</a><li><a href=http://phobos/eq/item.php?id=18902>A Torn Drawing</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15332>Spell: Shield of Fire</a><li><a href=http://phobos/eq/item.php?id=13592>Faded Training Robe*</a><li><a href=http://phobos/eq/item.php?id=1307>Gossamer Robe</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=170>Keepers of the Art</a><li><a href=http://phobos/eq/faction.php?id=178>King Tearis Thex</a><li><a href=http://phobos/eq/faction.php?id=99>Faydark's Champions</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=322>The Dead</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Niola Impholder says </b>'Greetings, [Your Name] . Welcome to the home of the Keepers of the Art. I am in need of spell components. Would you be willing to [fetch] some for me?'
<p><b>You say, </b>'fetch'
<br><b>Niola Impholder says </b>'What I need are some bat wings for a spell I am researching. If you bring me back four bat wings, I would be willing to reward you with a scroll.'
<p><b>You give Niola Impholder : </b><a href=http://phobos/eq/item.php?id=13068>Bat Wing</a> x4
<br><b>Niola Impholder says </b>'Ah yes.  These are exactly what I need.  Thank you very much.'
<br><b>Niola Impholder gives you : </b><a href=http://phobos/eq/item.php?id=15332>Spell: Shield of Fire</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=170>Keepers of the Art</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=178>King Tearis Thex</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=99>Faydark's Champions</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=322>The Dead</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Niola Impholder : </b><a href=http://phobos/eq/item.php?id=18777>An Enrollment Letter</a>
<br><b>Niola Impholder says </b>'Welcome. I am Niola Impholder. Master Magician of the Keepers of the Art. Here is our guild robe. You have much to learn. so let's get started.'
<br><b>Niola Impholder gives you : </b><a href=http://phobos/eq/item.php?id=13592>Faded Training Robe*</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Niola Impholder : </b><a href=http://phobos/eq/item.php?id=18902>A Torn Drawing</a>
<br><b>Niola Impholder says </b>'She is still alive? OH, thank you for this news.'
<br><b>Niola Impholder gives you : </b><a href=http://phobos/eq/item.php?id=1307>Gossamer Robe</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>