<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13758>Black Wolf Skin</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=58094>Simple Copper Ring</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=170>Keepers of the Art</a><li><a href=http://phobos/eq/faction.php?id=178>King Tearis Thex</a><li><a href=http://phobos/eq/faction.php?id=99>Faydark's Champions</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=322>The Dead</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Tarker Blazetoss says </b>'Hail and well met. [Your Name]!  Have you come to study. or can you [perform a task] for me this day?'
<p><b>You say, </b>'i can perform a task'
<br><b>Tarker Blazetoss says </b>'That is the spirit.  There are many black wolves wandering Faydark these days.  One of my brethren needs a black wolf skin as a component for his magic.  Bring me a black wolf skin. and I shall reward you for your efforts.'
<p><b>You give Tarker Blazetoss : </b><a href=http://phobos/eq/item.php?id=13758>Black Wolf Skin</a>
<br><b>Tarker Blazetoss says </b>'Ah yes.  This is exactly what I need.  Thank you very much.'
<br><b>Tarker Blazetoss gives you : </b><a href=http://phobos/eq/item.php?id=58094>Simple Copper Ring</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=170>Keepers of the Art</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=178>King Tearis Thex</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=99>Faydark's Champions</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=322>The Dead</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>