<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Anson McBale </b>looks at you suspiciously. 'Yeah? Whacha want?'</font>
<p><b>You say, </b>'i need to see stanos'
<br><b>Anson McBale says </b>'Go away! We don't have time for the likes of you.'
<br><font color=green><b>Anson McBale </b>will not accept this item.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>