<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Barn Bloodstone says </b>'You seem a little out of place here. You should go back to the nice little village you came from. This place will eat you alive. The [Golden Rooster] is no place for you.'
<p><b>You say, </b>'what Blackburrow Stout'
<br><b>Barn Bloodstone says </b>'Blackburrow Stout is the finest drink available. It is the nectar of the gods. Well.. nectar of the gnolls at least. I can't wait until they hold another drink special in the Rooster. When I hear that. I am there!'
<p><b>You say, </b>'what Golden rooster'
<br><b>Barn Bloodstone says </b>'The Golden Rooster only happens to be the finest gambling house in Highpass. It is also the only place in these parts that serves [Blackburrow Stout].'
</td></tr></table>