<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12366>never stop chopping</a><li><a href=http://phobos/eq/item.php?id=12365>Case of Spirits</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17984>Bottle Crate</a><li><a href=http://phobos/eq/item.php?id=12348>Gem of Stamina</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=48>Coalition of Tradefolk Underground</a><li><a href=http://phobos/eq/faction.php?id=47>Coalition of Trade Folk</a><li><a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a><li><a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Bryan McGee says </b>'I do not know what you are doing up here, but I am a busy man. Please return to the bar downstairs and enjoy the atmosphere.'
<p><b>You say, </b>'oblong bottle'
<br><b>Bryan McGee says </b>'The oblong bottle is a legend. They say one drink and you're off to oblivion, but just before that you feel the best you've ever felt and relive all your finest memories in the blink of an eye. The last I heard, some guy by the name of Turgin Swillfod turned up in Freeport spouting that he had found it. He was never heard from again.'
<p><b>You say, </b>'never stop chopping'
<br><b>Bryan McGee says </b>'Hey!! You must be the one I traded my axe to. Funny, I thought you were much shorter. If you have my axe then I will return my your gem to you.
Well, let's have it.'
<p><b>You give Bryan McGee : </b><a href=http://phobos/eq/item.php?id=12366>never stop chopping</a>
<br><b>Bryan McGee says </b>'On second thought.. You can do a little favor for me first. An associate of mine has asked me to acquire a case of spirits for him. Take this box and seek out what is needed to fill it. Inside you will combine the spirits of Lendel's Grand Lager, Gator Gulp Ale, Blackburrow Swig, Tunare's Finest, Underfoot Triple Bock, Frozen Toe Rum, Blood Spirit, Vasty Deep Ale, Clockwork Oil Stout and the legendary..[Oblong Bottle].'
<br><b>Bryan McGee gives you : </b><a href=http://phobos/eq/item.php?id=17984>Bottle Crate</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=48>Coalition of Tradefolk Underground</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=47>Coalition of Trade Folk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<p><b>You give Bryan McGee : </b><a href=http://phobos/eq/item.php?id=12365>Case of Spirits</a>
<br><b>Bryan McGee says </b>'I cannot believe you actually acquired all those drinks!! You do good work, kid. Here is the gem as I promised. And a few plat for good measure. Don't let it be said that the Axe doesn't treat his friends right.'
<br><b>You receive </b> 7pp
<br><b>Bryan McGee gives you : </b><a href=http://phobos/eq/item.php?id=12348>Gem of Stamina</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=48>Coalition of Tradefolk Underground</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=47>Coalition of Trade Folk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>