<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13791>Orc Scalp</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a><li><a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a><li><a href=http://phobos/eq/faction.php?id=214>Merchants of Highpass</a><li><a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Captain Ashlan says </b>'Greetings, traveler! I am Captain Ashlan of the Highpass Guards. I keep watch over my men and the [volunteers] here at the East Gate. It's been a busy [job] here lately, with the [orc raids] and all.'
<p><b>You say, </b>'what job'
<br><b>Captain Ashlan says </b>'We're short-handed around here, as usual. Would you like to help us out with the [Volunteer Watch]?'
<p><b>You say, </b>'what volunteer'
<br><b>Captain Ashlan says </b>'The Volunteer Watch guards the entry gates of Highpass. Since the [orc raids] are becoming more and more frequent, it's a busy job. But it can pay well, depending on how many [orcs] you slay.'
<p><b>You say, </b>'what orc'
<br><b>Captain Ashlan says </b>'One of the orc clans of Kithicor Woods has been trying to expand their territory. Small orc raiding parties are frequently rushing the East Gate. Without the [Volunteer Watch] helping us out, Highpass would probably be overrun by those vile beasts.'
<p><b>You give Captain Ashlan : </b><a href=http://phobos/eq/item.php?id=13791>Orc Scalp</a> x4
<br><b>Captain Ashlan says </b>'Great work! Maybe you can help us out again sometime?'
<br><b>You receive </b> 3gp 4sp 8cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=214>Merchants of Highpass</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Captain Ashlan says </b>'Great work! Maybe you can help us out again sometime?'
<br><b>You receive </b> 2gp 5sp 9cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=214>Merchants of Highpass</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Captain Ashlan says </b>'Great work! Maybe you can help us out again sometime?'
<br><b>You receive </b> 1pp 2gp 4sp 5cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=214>Merchants of Highpass</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Captain Ashlan says </b>'Great work! Maybe you can help us out again sometime?'
<br><b>You receive </b> 1pp 2sp 5cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=214>Merchants of Highpass</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Captain Ashlan : </b><a href=http://phobos/eq/item.php?id=13791>Orc Scalp</a> x3
<br><b>Captain Ashlan says </b>'Great work! Maybe you can help us out again sometime?'
<br><b>You receive </b> 5sp 7cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=214>Merchants of Highpass</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Captain Ashlan says </b>'Great work! Maybe you can help us out again sometime?'
<br><b>You receive </b> 3gp 1sp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=214>Merchants of Highpass</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Captain Ashlan says </b>'Great work! Maybe you can help us out again sometime?'
<br><b>You receive </b> 1pp 3gp 1cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=214>Merchants of Highpass</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Captain Ashlan : </b><a href=http://phobos/eq/item.php?id=13791>Orc Scalp</a> x2
<br><b>Captain Ashlan says </b>'Great work! Maybe you can help us out again sometime?'
<br><b>You receive </b> 8cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=214>Merchants of Highpass</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Captain Ashlan says </b>'Great work! Maybe you can help us out again sometime?'
<br><b>You receive </b> 1pp 3sp 7cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=214>Merchants of Highpass</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Captain Ashlan : </b><a href=http://phobos/eq/item.php?id=13791>Orc Scalp</a>
<br><b>Captain Ashlan says </b>'Great work! Maybe you can help us out again sometime?'
<br><b>You receive </b> 1pp 1gp 5sp 8cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=214>Merchants of Highpass</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>