<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13792>Gnoll Scalp</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a><li><a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a><li><a href=http://phobos/eq/faction.php?id=214>Merchants of Highpass</a><li><a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Captain Orben says </b>'Greetings, traveler! I am Captain Orben of the Highpass Guards. I keep watch over my men and the [volunteers] here at the West Gate. It's been a busy [job] here lately, with the [gnoll raids] and all.'
<p><b>You say, </b>'what job'
<br><b>Captain Orben says </b>'We're short-handed around here, as usual. Would you like to help us out with the [Volunteer Watch]?'
<p><b>You say, </b>'what volunteer'
<br><b>Captain Orben says </b>'The Volunteer Watch guards the entry gates of Highpass. Since the [gnoll raids] are becoming more and more frequent, it's a busy job. But it can pay well, depending on how many [gnolls] you slay.'
<p><b>You say, </b>'what orc'
<br><b>Captain Orben says </b>'The Mucktail Gnolls of the Karanas have been trying to expand their territory. Small gnoll raiding parties are frequently rushing the West Gate. Without the [Volunteer Watch] helping us out, Highpass would probably be overrun by those vile beasts.'
<p><b>You give Captain Orben : </b><a href=http://phobos/eq/item.php?id=13792>Gnoll Scalp</a> x4
<br><b>Captain Orben says </b>'Great work! Maybe you can help us out again sometime?'
<br><b>You receive </b> 1pp 2gp 1sp 2cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=214>Merchants of Highpass</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Captain Orben says </b>'Great work! Maybe you can help us out again sometime?'
<br><b>You receive </b> 1pp 2gp 4sp 2cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=214>Merchants of Highpass</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Captain Orben says </b>'Great work! Maybe you can help us out again sometime?'
<br><b>You receive </b> 1pp 1gp 6sp 7cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=214>Merchants of Highpass</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Captain Orben says </b>'Great work! Maybe you can help us out again sometime?'
<br><b>You receive </b> 1gp 2sp 5cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=214>Merchants of Highpass</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Captain Orben : </b><a href=http://phobos/eq/item.php?id=13792>Gnoll Scalp</a> x3
<br><b>Captain Orben says </b>'Great work! Maybe you can help us out again sometime?'
<br><b>You receive </b> 1pp 1gp 3sp 9cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=214>Merchants of Highpass</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Captain Orben says </b>'Great work! Maybe you can help us out again sometime?'
<br><b>You receive </b> 2gp 6sp 9cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=214>Merchants of Highpass</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Captain Orben says </b>'Great work! Maybe you can help us out again sometime?'
<br><b>You receive </b> 1pp 3gp 4sp 8cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=214>Merchants of Highpass</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Captain Orben : </b><a href=http://phobos/eq/item.php?id=13792>Gnoll Scalp</a> x2
<br><b>Captain Orben says </b>'Great work! Maybe you can help us out again sometime?'
<br><b>You receive </b> 1sp 1cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=214>Merchants of Highpass</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Captain Orben says </b>'Great work! Maybe you can help us out again sometime?'
<br><b>You receive </b> 1pp 2gp 1sp 2cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=214>Merchants of Highpass</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Captain Orben : </b><a href=http://phobos/eq/item.php?id=13792>Gnoll Scalp</a>
<br><b>Captain Orben says </b>'Great work! Maybe you can help us out again sometime?'
<br><b>You receive </b> 1pp 2gp 1sp 6cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=214>Merchants of Highpass</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>