<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Falyn Farreach says </b>'Welcome to Top of the World, the newest shop in the pass!'
<p><b>You say, </b>'never stop chopping'
<br><b>Falyn Farreach says </b>''Never stop chopping?!!' Hey! I engraved that on a special order for a fellow Highpass citizen. I can't remember his name. He gave me not only some rare gems for it, but also a case of something called 'Lumberjack Pale Ale.' Great stuff!!'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>