<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12114>Tumpy Tonic</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19006>Icon of the Fervent</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Jovan says </b>'Not so loud! My head is spinning so! What I wouldn't give for a Tumpy's Tonic right now! They were always just the thing for the hair of the gnoll that bit me.'
<p><b>You give Jovan : </b><a href=http://phobos/eq/item.php?id=12114>Tumpy Tonic</a>
<br><b>Jovan says </b>'<SLURP!!>  Ahh thhhhat'thh betterr. Take thithhh. <BURP!>'
<br><b>Jovan gives you : </b><a href=http://phobos/eq/item.php?id=19006>Icon of the Fervent</a>
<br><b>Jovan disappears.</b>
</td></tr></table>