<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>#Hero Goxnok </b>sighs slowly, seeing the confusion on your face. He says, 'Yes, [Your Name], I am the traitor. What I can gain by giving up this tome outweighs any patriotic obligations I may have once had. That city is dead, it is now time for us to grasp at our own destinies. I now give you two choices, . You can walk away and never speak of this to anyone......or you can die. What will it be?'</font>
<hr><b>When #Hero Goxnok is killed </b>
<br><b>#Hero Goxnok says </b>'You shall now be a wanted man.. The Union of Vie shall punish you.'
</td></tr></table>