<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12828>Full Kwinn Pack</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17038>Empty Pack from Kwinn</a><li><a href=http://phobos/eq/item.php?id=12822>A Mechanical Iksar Tail</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>#Kwinn the Outlander says </b>'Hail, adventurer! Kwinn's the name. Hunting is my game. I have been all over this continent. Seen many things and found [odd trinkets]. I have no quarrel with any race. I judge a person or critter by their actions. Heck, my best friend is a troll!!'
<p><b>You say, </b>'odd trinkets'
<br><b>#Kwinn the Outlander says </b>'Blast!! I found some strange thingamajigs!! Most of it I toss or sell to vendors and crazy sages. I am on my way to sell this [iron tail] to a tinkerer.'
<p><b>You say, </b>'iron tail'
<br><b>#Kwinn the Outlander says </b>'Found the thing washed up on the shore in Timorous Deep. Looks like a metal lizardman tail. It is all rusted and covered with barnacles. Probably can't get much for it, but I'll try. Why do you ask? Are you looking to [trade for the mechanical thing]?'
<p><b>You say, </b>'trade for the mechanical thing'
<br><font color=green><b>#Kwinn the Outlander </b>takes out an extra pack. 'Thought you might be interested. I don't want to take a loss and I only trade for things I am hunting, so here!! Inside this pack you need to combine the following items; a sabertooth tiger mane, a pair of pygmy brute choppers, a lime plume and a war bone fist. Return the full sack to me and the tail is yours.'</font>
<br><b>#Kwinn the Outlander gives you : </b><a href=http://phobos/eq/item.php?id=17038>Empty Pack from Kwinn</a>
<p><b>You give #Kwinn the Outlander : </b><a href=http://phobos/eq/item.php?id=12828>Full Kwinn Pack</a>
<br><b>#Kwinn the Outlander says </b>'Kackling Quellious!! This will bring a fortune on the black market!! Well, a deal is a deal. Here is the tail.'
<br><font color=yellow>You gain experience!!</font>
<br><b>#Kwinn the Outlander gives you : </b><a href=http://phobos/eq/item.php?id=12822>A Mechanical Iksar Tail</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>