<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19269>Spell: Cripple</a><li><a href=http://phobos/eq/item.php?id=19238>Spell: Spirit of Scale</a><li><a href=http://phobos/eq/item.php?id=19264>Spell: Talisman of Jasinth</a><li><a href=http://phobos/eq/item.php?id=19272>Spell: Cannibalize III</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19274>Spell: Torrent of Poison</a><li><a href=http://phobos/eq/item.php?id=19266>Spell: Insidious Decay</a><li><a href=http://phobos/eq/item.php?id=19271>Spell: Shroud of the Spirits</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Alex McDarnin says </b>'Hail! Do you by chance bring news from the North? I sure do miss the cold. It is just a bit too warm for me down here. Well, I wish you the best of luck in your travels. Tomorrow is a new day and I am off in search of [new writings] to take back to the Tribunal.'
<p><b>You say, </b>'new writings'
<br><b>Alex McDarnin says </b>'There have been tales of new writings being found in some of the ancient ruins that abound outside of this outpost. These writings will be very valuable to my church. The sooner I can return with the writings, the sooner the Tribunal can put the teachings to work. I am always in need of aides so if [you want to help], just say so.'
<p><b>You say, </b>'I want to help'
<br><b>Alex McDarnin says </b>'We won't be traveling together, but here is what I need. There are four writings that still elude me. Return one of these and I'll spare one of the four extra writings I have. I am looking for the writings called Talisman of Jasinth, Spirit of Scale, Cripple, and Cannibalize III. Be off, and may your travels be safe!'
<p><b>You give Alex McDarnin : </b><a href=http://phobos/eq/item.php?id=19269>Spell: Cripple</a>
<br><b>Alex McDarnin says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Alex McDarnin gives you : </b><a href=http://phobos/eq/item.php?id=19274>Spell: Torrent of Poison</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Alex McDarnin : </b><a href=http://phobos/eq/item.php?id=19238>Spell: Spirit of Scale</a>
<br><b>Alex McDarnin says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Alex McDarnin gives you : </b><a href=http://phobos/eq/item.php?id=19266>Spell: Insidious Decay</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Alex McDarnin : </b><a href=http://phobos/eq/item.php?id=19264>Spell: Talisman of Jasinth</a>
<br><b>Alex McDarnin says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Alex McDarnin gives you : </b><a href=http://phobos/eq/item.php?id=19271>Spell: Shroud of the Spirits</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Alex McDarnin : </b><a href=http://phobos/eq/item.php?id=19272>Spell: Cannibalize III</a>
<br><b>Alex McDarnin says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Alex McDarnin gives you : </b><a href=http://phobos/eq/item.php?id=19271>Spell: Shroud of the Spirits</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>