<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10059>Star of Odus</a><li><a href=http://phobos/eq/item.php?id=12829>A Tin Box</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17045>Tin Box</a><li><a href=http://phobos/eq/item.php?id=12940>Nostrolo Tambourine</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Assistant Buford says </b>'Well hello there. I am new to the bank. I am helping the Fargins out since it is so busy lately. Mr. Fargin doesn't even have time for his [hobby] these days.'
<p><b>You say, </b>'hobby'
<br><b>Assistant Buford says </b>''Mr. Fargin used to collect rare coins and gems. He came to Firiona Vie to do just that, but now he never has the time to [collect rare coins] since he is always working here. That is why I came to help him out.'
<p><b>You say, </b>'collect rare coins'
<br><b>Assistant Buford says </b>'If you want to help, you can begin by replacing Mr. Fargin's prized Star of Odus which was taken from his vault when he stepped out to dine one night. Do so, and I may trust you to collect coins. I will also reward you with an item a composer left here. With Mr. Fargin's approval of course.'
<p><b>You give Assistant Buford : </b><a href=http://phobos/eq/item.php?id=10059>Star of Odus</a>
<br><b>Assistant Buford says </b>'Thank you!! I never could have gone to Odus to replace this. Perhaps now you can collect some rare coins.'
<br><b>Assistant Buford gives you : </b><a href=http://phobos/eq/item.php?id=17045>Tin Box</a>
<p><b>You give Assistant Buford : </b><a href=http://phobos/eq/item.php?id=12829>A Tin Box</a>
<br><b>Assistant Buford gives you : </b><a href=http://phobos/eq/item.php?id=12940>Nostrolo Tambourine</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>