<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19315>Spell: Atol`s Spectral Shackles</a><li><a href=http://phobos/eq/item.php?id=19322>Spell: Inferno of Al`Kabor</a><li><a href=http://phobos/eq/item.php?id=19318>Spell: Pillar of Frost</a><li><a href=http://phobos/eq/item.php?id=19319>Spell: Tears of Druzzil</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19324>Spell: Thunderbold</a><li><a href=http://phobos/eq/item.php?id=19317>Spell: Tishan`s Discord</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Barnal Flamehand says </b>'And a fine day to you, too, [Your Name]! What is it that brings you here? Fortune? Adventure? In either case. it will be more fun than the duty I have. I am to acquire what scrolls I can for the High Council of Erudin. And you're also in luck, as I seek the services of a mighty adventurer like yourself. Do you wish to [aid me in my duty]?'
<p><b>You say, </b>'aid you in your duty'
<br><b>Barnal Flamehand says </b>'Then you will do this for me. Venture beyond this outpost to the most distant lands and the darkest dungeons. Within them. the creatures with the greatest power will have scrolls. The residents here will be able to give you general locations of the most dangerous places. I wish to obtain the scrolls of Atol's Spectral Shackles, Tears of Druzzil, Inferno of Al'Kabor, and lastly, Pillar of Frost. Make haste, as the High Council cannot be kept waiting! Fear not. I shall [reward] you well.'
<p><b>You say, </b>'reward'
<br><b>Barnal Flamehand says </b>'I am not empty-handed. I have already located some of the most rare scrolls. I'll part with one of my four for what you return to me. Fare thee well!'
<p><b>You give Barnal Flamehand : </b><a href=http://phobos/eq/item.php?id=19315>Spell: Atol`s Spectral Shackles</a>
<br><b>Barnal Flamehand says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Barnal Flamehand gives you : </b><a href=http://phobos/eq/item.php?id=19324>Spell: Thunderbold</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Barnal Flamehand : </b><a href=http://phobos/eq/item.php?id=19322>Spell: Inferno of Al`Kabor</a>
<br><b>Barnal Flamehand says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Barnal Flamehand gives you : </b><a href=http://phobos/eq/item.php?id=19317>Spell: Tishan`s Discord</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Barnal Flamehand : </b><a href=http://phobos/eq/item.php?id=19318>Spell: Pillar of Frost</a>
<br><b>Barnal Flamehand says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Barnal Flamehand gives you : </b><a href=http://phobos/eq/item.php?id=19317>Spell: Tishan`s Discord</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Barnal Flamehand : </b><a href=http://phobos/eq/item.php?id=19319>Spell: Tears of Druzzil</a>
<br><b>Barnal Flamehand says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Barnal Flamehand gives you : </b><a href=http://phobos/eq/item.php?id=19324>Spell: Thunderbold</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>