<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12977>A Canine</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13155>Elven Trail Mix</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=320>Temple of Solusek Ro</a><li><a href=http://phobos/eq/faction.php?id=10401></a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=11501></a><li><a href=http://phobos/eq/faction.php?id=403>Cursed Drakes</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Captain Nealith says </b>'Hail. adventurer!!  Stand tall and fight for the forest folk and all good races of Norrath. 
We shall claim this land for the kingdom of Thex!  My warriors shall not fail.  Already we patrol deep
in the wilds of Kunark.  We welcome all mercenaries and urge adventurers to [join the defense of the
outpost].'
<p><b>You say, </b>'join the defense'
<br><b>Captain Nealith says </b>'I salute you!!  Join the hunt.  Reports from the front line indicate a rise in the drolvarg
population.  Abandon your fear and slay these beasts for the greater good.  Already. they have taken far
too many lives. even my sibling's!!  I shall pay you your wages upon the return of four drolvarg
teeth.'
<p><b>You give Captain Nealith : </b><a href=http://phobos/eq/item.php?id=12977>A Canine</a> (x4)
<br><font color=green><b>Captain Nealith </b>Captain Nealith tosses the teeth into a very large cask full of similar teeth.</font>
<br><b>Captain Nealith says </b>'Fine work, [Your Name]. I wish all my own troops showed the same tenacity. I salute you. This will
keep you well fed during your long patrols. Use your wages to better equip yourself. Continue the
fight!! The General is pleased.'
<br><b>Captain Nealith gives you : </b><a href=http://phobos/eq/item.php?id=13155>Elven Trail Mix</a>
<br><b>You receive </b> 3gp 12sp 7cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=320>Temple of Solusek Ro</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10401></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=11501></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=403>Cursed Drakes</a> has gotten worse.</font>
<br><font color=green><b>Captain Nealith </b>Captain Nealith holds the canine in his palm.</font>
<br><b>Captain Nealith says </b>'Good work, but you will have to slay more than this to earn your wages.'
</td></tr></table>