<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10033>Fire Emerald</a><li><a href=http://phobos/eq/item.php?id=10013>A Special Fire Emerald</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10013>A Special Fire Emerald</a></ul></td><td><p><b>You give Drake Mountainstorm : </b><a href=http://phobos/eq/item.php?id=10033>Fire Emerald</a>
<br><font color=green><b>Drake Mountainstorm </b>examines the fire emerald, reaches into his pouch and hands you another. 'There you go, it doesn't look special but it is. If you don't believe me I'll take another look at it. Just remember this special fire emerald only has one purpose!'</font>
<br><b>Drake Mountainstorm gives you : </b><a href=http://phobos/eq/item.php?id=10013>A Special Fire Emerald</a>
<p><b>You give Drake Mountainstorm : </b><a href=http://phobos/eq/item.php?id=10013>A Special Fire Emerald</a>
<br><b>Drake Mountainstorm says </b>'There you go, it doesn't look special, but it is.'
<br><b>Drake Mountainstorm gives you : </b><a href=http://phobos/eq/item.php?id=10013>A Special Fire Emerald</a>
</td></tr></table>