<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19203>Spell: Death Pact</a><li><a href=http://phobos/eq/item.php?id=19205>Spell: Upheaval</a><li><a href=http://phobos/eq/item.php?id=19209>Spell: Yaulp IV</a><li><a href=http://phobos/eq/item.php?id=19212>Spell: Reckoning</a><li><a href=http://phobos/eq/item.php?id=19233>Spell: Upheaval</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19420>Spell: Sunskin</a><li><a href=http://phobos/eq/item.php?id=19206>Spell: Word of Vigor</a><li><a href=http://phobos/eq/item.php?id=19224>Spell: Heroic Bond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Frist Furtun says </b>'Hail to thee, adventurer! I have been sent to this new land by the Clerics of Tunare in search of the new arcane magiks said to exist beyond this outpost. I myself once searched the nearby Outlands, but to go any further would lead to my certain death. Lately, the dangers have proven to be too much for adventurers and ones like myself. Have you also ventured to this land in search of these [new magiks?]'
<p><b>You say, </b>'new magiks'
<br><b>Frist Furtun says </b>'Ahh, wonderful! The more souls who search for these scrolls, the sooner I'll be able to return home and share this knowledge. The magiks are in the form of scrolls held by the strongest creatures of the Outlands. You will probably have the best luck searching in the darkest depths of the dungeons beyond this outpost. You might want to talk to the residents of this outpost for locations of these dreadful places. If you should happen to [have] any duplicate scrolls], please come speak to me. I might be interested in working out a trade for a scroll you do not yet have.'
<p><b>You say, </b>'I have duplicate scrolls'
<br><b>Frist Furtun says </b>'Great! The scrolls I am interested in are those of Death Pact, Upheaval, Yaulp IV, and Reckoning. If you bring me any one of these scrolls, I'll let you reach into my bag and pull out one of the four very rare scrolls that have come into my possession.'
<p><b>You give Frist Furtun : </b><a href=http://phobos/eq/item.php?id=19203>Spell: Death Pact</a>
<br><b>Frist Furtun says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Frist Furtun gives you : </b><a href=http://phobos/eq/item.php?id=19420>Spell: Sunskin</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Frist Furtun : </b><a href=http://phobos/eq/item.php?id=19205>Spell: Upheaval</a>
<br><b>Frist Furtun says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Frist Furtun gives you : </b><a href=http://phobos/eq/item.php?id=19206>Spell: Word of Vigor</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Frist Furtun : </b><a href=http://phobos/eq/item.php?id=19209>Spell: Yaulp IV</a>
<br><b>Frist Furtun says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Frist Furtun gives you : </b><a href=http://phobos/eq/item.php?id=19420>Spell: Sunskin</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Frist Furtun : </b><a href=http://phobos/eq/item.php?id=19212>Spell: Reckoning</a>
<br><b>Frist Furtun says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Frist Furtun gives you : </b><a href=http://phobos/eq/item.php?id=19224>Spell: Heroic Bond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Frist Furtun : </b><a href=http://phobos/eq/item.php?id=19233>Spell: Upheaval</a>
<br><b>Frist Furtun says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Frist Furtun gives you : </b><a href=http://phobos/eq/item.php?id=19224>Spell: Heroic Bond</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>