<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=62093>Earring of King Dronan</a><li><a href=http://phobos/eq/item.php?id=62092>Sash of the Cave Lord</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=62202>Copper Medal of Rapture</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Gillia Brissok says </b>'Greetings friend, it is good to be freed from the clutches of those evil creatures. Tell me are you willing to help me bring some [justice] to them?'
<p><b>You say, </b>'justice'
<br><b>Gillia Brissok says </b>'For justice to be brought to them you will need to strike at some of the most powerful goblins found there. Seek out the goblin cave lords deep within the Temple of Droga and bring me back three Sashes of the Cave Lords. Also I will need the Earring of King Dronan. Do this and you will be well rewarded.'
<p><b>You give Gillia Brissok : </b><a href=http://phobos/eq/item.php?id=62093>Earring of King Dronan</a>, <a href=http://phobos/eq/item.php?id=62092>Sash of the Cave Lord</a> x3
<br><b>Gillia Brissok gives you : </b><a href=http://phobos/eq/item.php?id=62202>Copper Medal of Rapture</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>