<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19378>Spell: Color Slant</a><li><a href=http://phobos/eq/item.php?id=19269>Spell: Cripple</a><li><a href=http://phobos/eq/item.php?id=19384>Spell: Dementia</a><li><a href=http://phobos/eq/item.php?id=19374>Spell: Theft of Thought</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19381>Spell: Recant Magic</a><li><a href=http://phobos/eq/item.php?id=19379>Spell: Clarity II</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Gracie F-Liler says </b>'It's so good to see new faces. not to mention more adventurers in this area. On some nights. the sounds that come from the nearby hills will scare even the hardiest of travelers. I volunteered in the name of the Keepers of the Art to help locate any [new spell scrolls] that might surface. Maybe you will have a successful journey and find some of these scrolls yourself.'
<p><b>You say, </b>'what new spell scrolls'
<br><b>Gracie F-Liler says </b>'I have recently come into possession of some of these scrolls. They seem to be very promising in adding to the strengths of our occupation. Some more good news is that I have a few extra of these scrolls. Perhaps you might have or find an extra of your own and be willing to trade? In case you are interested. I am looking for the scrolls Theft of Thought. Color Slant. Cripple. and lastly Dementia. Bring me one of these and I'll make an even trade.'
<p><b>You give Gracie F-Liler : </b><a href=http://phobos/eq/item.php?id=19378>Spell: Color Slant</a>
<br><b>Gracie F-Liler says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Gracie F-Liler gives you : </b><a href=http://phobos/eq/item.php?id=19381>Spell: Recant Magic</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Gracie F-Liler : </b><a href=http://phobos/eq/item.php?id=19269>Spell: Cripple</a>
<br><b>Gracie F-Liler says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Gracie F-Liler gives you : </b><a href=http://phobos/eq/item.php?id=19379>Spell: Clarity II</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Gracie F-Liler : </b><a href=http://phobos/eq/item.php?id=19384>Spell: Dementia</a>
<br><b>Gracie F-Liler says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Gracie F-Liler gives you : </b><a href=http://phobos/eq/item.php?id=19381>Spell: Recant Magic</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Gracie F-Liler : </b><a href=http://phobos/eq/item.php?id=19374>Spell: Theft of Thought</a>
<br><b>Gracie F-Liler says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Gracie F-Liler gives you : </b><a href=http://phobos/eq/item.php?id=19379>Spell: Clarity II</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>