<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Guard Ivak says </b>'Blast!!  Hundreds of goblins to slay and [great treasure] to be had and I am stuck at my post!'
<p><b>You say, </b>'what great treasure?'
<br><b>Guard Ivak says </b>'A fellow paladin who was a member of an expedition into the jungles of Kunark returned with a jade green broadsword.  He said he came across it while they were fighting their way out of some ancient city filled with golems.  They lost many strong troops on that expedition.'
</td></tr></table>