<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19351>Spell: Bristlebane`s Bundle</a><li><a href=http://phobos/eq/item.php?id=19347>Spell: Gift of Xev</a><li><a href=http://phobos/eq/item.php?id=19354>Spell: Quiver of Marr</a><li><a href=http://phobos/eq/item.php?id=19358>Spell: Scars of Sigil</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19346>Spell: Scintillation</a><li><a href=http://phobos/eq/item.php?id=19355>Spell: Vocarate: Fire</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Hiptal Frizzleboth says </b>'Bah!! It's not been a good day! Reports from the Outlands are even worse than I was led to believe. Many would-be adventurers have turned up missing of late. One of them was one of my messenger. He was out collecting some of the various new and [interesting scrolls] that have been surfacing in the farthest reaches of this land. I fear for his safety and that of the others searching for the lost travelers. I wish there was more I could do.'
<p><b>You say, </b>'interesting scrolls'
<br><font color=green><b>Hiptal Frizzleboth </b>reaches into his pouch. 'Well, let's see what I have in here. Ah, yes. The scrolls are definitely worth finding. Possibly even dangerous if they should fall into the wrong hands. But that is why the Collective sent me here. To procure all of the scrolls so that they may be studied at the Library of Mechanimagica. Bah!! But my messenger is missing! I can't fail them. Would you be willing to [help locate] some of the scrolls I am missing?</font>
<p><b>You say, </b>'help locate'
<br><b>Hiptal Frizzleboth says </b>'You would do that for me? Of course you would, you realize how important my work is here. Your task is quite simple, really. I'll part with one of my rare scrolls if you bring me one of the common ones from the surrounding areas. To be more precise, I am looking for the scrolls Gift of Xev and Bristlebane's Bundle. Oh, my nephew is going to love these! I can't wait to get my hands on them! I'm also looking for the scrolls Quiver of Marr and Scars of Sigil. Bring them back to me as soon as you find one.'
<p><b>You give Hiptal Frizzleboth : </b><a href=http://phobos/eq/item.php?id=19351>Spell: Bristlebane`s Bundle</a>
<br><b>Hiptal Frizzleboth says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Hiptal Frizzleboth gives you : </b><a href=http://phobos/eq/item.php?id=19346>Spell: Scintillation</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Hiptal Frizzleboth : </b><a href=http://phobos/eq/item.php?id=19347>Spell: Gift of Xev</a>
<br><b>Hiptal Frizzleboth says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Hiptal Frizzleboth gives you : </b><a href=http://phobos/eq/item.php?id=19355>Spell: Vocarate: Fire</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Hiptal Frizzleboth : </b><a href=http://phobos/eq/item.php?id=19354>Spell: Quiver of Marr</a>
<br><b>Hiptal Frizzleboth says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Hiptal Frizzleboth gives you : </b><a href=http://phobos/eq/item.php?id=19346>Spell: Scintillation</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Hiptal Frizzleboth : </b><a href=http://phobos/eq/item.php?id=19358>Spell: Scars of Sigil</a>
<br><b>Hiptal Frizzleboth says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Hiptal Frizzleboth gives you : </b><a href=http://phobos/eq/item.php?id=19346>Spell: Scintillation</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>