<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12948>Nok Shaman Powder</a><li><a href=http://phobos/eq/item.php?id=12834>Heart of Ice</a><li><a href=http://phobos/eq/item.php?id=12744>Ton Warrior Totem</a><li><a href=http://phobos/eq/item.php?id=12824>Sabertooth Tiger Mane</a><li><a href=http://phobos/eq/item.php?id=12743>Ton Warrior Totem</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12949>Vision of Sebilite</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=418>Inhabitants of Firiona Vie</a><li><a href=http://phobos/eq/faction.php?id=92>Emerald Warriors</a><li><a href=http://phobos/eq/faction.php?id=314>Storm Guard</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a><li><a href=http://phobos/eq/faction.php?id=250>Pirates of Gunthak</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Luminare Pasinia </b>wave's her hand's as if to cast a spell.</font>
<br><b>Luminare Pasinia says </b>'Greeting's!! I am the Luminare of Firiona. By decree of his royal highness, King Thex, I am here to research spell's and artifact's. I have much to do. I welcome any enchanter who offer's to [assist] the great Luminare.'
<p><b>You say, </b>'assist'
<br><b>Luminare Pasinia says </b>'And great I am, indeed!! Alas, not great enough to be everywhere at once. I would gladly reward you if you would [collect] components for me.'
<p><b>You say, </b>'collect'
<br><b>Luminare Pasinia says </b>'Then go into the wilds beyond the outpost and upon your return, you shall give me one Nok Shaman Powder, one Heart of Ice, one Ton Warrior Totem, and one Sabertooth Tiger Mane. This shall earn you knowledge of an enchanter spell I recently scribed.'
<p><b>You give Luminare Pasinia : </b><a href=http://phobos/eq/item.php?id=12948>Nok Shaman Powder</a>, <a href=http://phobos/eq/item.php?id=12834>Heart of Ice</a>, <a href=http://phobos/eq/item.php?id=12744>Ton Warrior Totem</a>, <a href=http://phobos/eq/item.php?id=12824>Sabertooth Tiger Mane</a>, <a href=http://phobos/eq/item.php?id=12948>Nok Shaman Powder</a>, <a href=http://phobos/eq/item.php?id=12834>Heart of Ice</a>, <a href=http://phobos/eq/item.php?id=12743>Ton Warrior Totem</a>, <a href=http://phobos/eq/item.php?id=12824>Sabertooth Tiger Mane</a>
<br><font color=green><b>Luminare Pasinia </b>place's the items into a sack and removes a scroll from her robe.</font>
<br><b>Luminare Pasinia says </b>'This is your's. A spell I discovered and translated for one with less intelligence than the great Luminare of Firiona Vie. You may kiss my feet now.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=418>Inhabitants of Firiona Vie</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=92>Emerald Warriors</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=314>Storm Guard</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=250>Pirates of Gunthak</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Luminare Pasinia gives you : </b><a href=http://phobos/eq/item.php?id=12949>Vision of Sebilite</a>
<br><b>Luminare Pasinia says </b>'I have no need for this item, [Your Name]. You can have it back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>