<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12942>Strange Ochre Clay</a><li><a href=http://phobos/eq/item.php?id=12945>Crushed Diamonds</a><li><a href=http://phobos/eq/item.php?id=12944>Yun Shaman Powder</a><li><a href=http://phobos/eq/item.php?id=12943>Greyish Bone Chips</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12941>Spell: Cannibalize II</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Marlyn McMerin says </b>'Greetings hearty adventurer. Searching for the components necessary for fine shaman spells are we? I have come to Kunark in search of [rare alchemy components], but I have found the dangers of Kunark are far too great for me.'
<p><b>You say, </b>'rare alchemy components'
<br><b>Marlyn McMerin says </b>'Grand!! I have heard word of [four rare components]. Collect them for me and I will share with you a rare scroll of [McMerin's Feast].'
<p><b>You say, </b>'McMerins Feast'
<br><b>Marlyn McMerin says </b>'Clan McMerin are wise shamans from the North. The secret of McMerin's Feast won't be understandable unless you're a shaman, but you can always pass it on to one.'
<p><b>You say, </b>'McMerin's Feast'
<br><b>Marlyn McMerin says </b>'Clan McMerin are wise shamans from the North. The secret of McMerin's Feast won't be understandable unless you're a shaman, but you can always pass it on to one.'
<p><b>You say, </b>'four rare components'
<br><b>Marlyn McMerin says </b>'From the lands of Kunark we require some clay of Ghiosk, crushed dread diamond and some powder of a Yun shaman. The rarest component is the bones of one who touched the Bath of Obulus. Find these things, return them to me and the secret of [McMerin's Feast] is yours.'
<p><b>You give Marlyn McMerin : </b><a href=http://phobos/eq/item.php?id=12942>Strange Ochre Clay</a>, <a href=http://phobos/eq/item.php?id=12945>Crushed Diamonds</a>, <a href=http://phobos/eq/item.php?id=12944>Yun Shaman Powder</a>, <a href=http://phobos/eq/item.php?id=12943>Greyish Bone Chips</a>
<br><b>Marlyn McMerin says </b>'What's this? This is amazing - you collected them all! To think, the power that these items hold if properly used. Never mind that now, here, take the scroll. You've certainly earned it.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Marlyn McMerin gives you : </b><a href=http://phobos/eq/item.php?id=12941>Spell: Cannibalize II</a>
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Marlyn McMerin says </b>'Whats this? I don't want this, have it back.'
</td></tr></table>