<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10604>Jeb's Seal</a><li><a href=http://phobos/eq/item.php?id=10637>A Sack For Nadia</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10631>Dull Diamond</a><li><a href=http://phobos/eq/item.php?id=10632>Dull Sapphire</a><li><a href=http://phobos/eq/item.php?id=10633>Dull Ruby</a><li><a href=http://phobos/eq/item.php?id=10634>Dull Emerald</a><li><a href=http://phobos/eq/item.php?id=10604>Jeb's Seal</a><li><a href=http://phobos/eq/item.php?id=17861>An Enchanters Sack</a><li><a href=http://phobos/eq/item.php?id=10612>3rd Piece of Staff</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=342>True Spirit</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Nadia Starfeast says </b>'Hello my dear. I am quite pleased to make your acquaintance. Perhaps even charmed!'
<p><b>You say, </b>'gems'
<br><b>Nadia Starfeast says </b>'I have prepared some gems that you will need to trap the essence. You will need to force a diamond, sapphire, ruby and emerald onto special creatures to obtain their essence.'
<p><b>You say, </b>'diamond'
<br><b>Nadia Starfeast says </b>'Here is the diamond that I have prepared for you. Its only purpose is to trap the essence of a particular book worm. If you should fail in your first attempt, do not worry. I will provide you with another.'
<br><b>Nadia Starfeast gives you : </b><a href=http://phobos/eq/item.php?id=10631>Dull Diamond</a>
<p><b>You say, </b>'sapphire'
<br><b>Nadia Starfeast says </b>'Here is the sapphire that I have prepared for you. Take it and give it to the one referred to as the Golden Faerie.'
<br><b>Nadia Starfeast gives you : </b><a href=http://phobos/eq/item.php?id=10632>Dull Sapphire</a>
<p><b>You say, </b>'ruby'
<br><b>Nadia Starfeast says </b>'Blood red is the ruby that I have given you. The city that you must travel to has no sun, but still a day and night. And at night, the mist could suffocate one. Tis the fate of poor Jaxion.'
<br><b>Nadia Starfeast gives you : </b><a href=http://phobos/eq/item.php?id=10633>Dull Ruby</a>
<p><b>You say, </b>'emerald'
<br><font color=green><b>Nadia Starfeast </b>jumps.</font>
<br><b>Nadia Starfeast says </b>'Eeekk... a scorpion. I thought they rid this area of these critters. Those things give me the creepers. Take this emerald and be on your way.'
<br><b>Nadia Starfeast gives you : </b><a href=http://phobos/eq/item.php?id=10634>Dull Emerald</a>
<p><b>You give Nadia Starfeast : </b><a href=http://phobos/eq/item.php?id=10604>Jeb's Seal</a>
<br><b>Nadia Starfeast says </b>'Oh it must be time to reveal the staff! The piece I will help you craft is encrusted with magical gems. These gems contain the essence of various creatures. Alone they have very little power. Combined together they are much more powerful. They must be combined in a sack. Just ask if you don't have one.'
<br><b>Nadia Starfeast gives you : </b><a href=http://phobos/eq/item.php?id=10604>Jeb's Seal</a>
<br><b>Nadia Starfeast gives you : </b><a href=http://phobos/eq/item.php?id=17861>An Enchanters Sack</a>
<p><b>You give Nadia Starfeast : </b><a href=http://phobos/eq/item.php?id=10637>A Sack For Nadia</a>
<br><b>Nadia Starfeast says </b>'Lovely! You are indeed quite the charmer. Here, take the third part, and seek out the last master. The time draws near.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=342>True Spirit</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Nadia Starfeast gives you : </b><a href=http://phobos/eq/item.php?id=10612>3rd Piece of Staff</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>