<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=6067>Bound Research Notes</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=6069>Packaged Research Notes</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Noilgin Mindtune says </b>'Hello there, [Your Name]! I hope you are enjoying your visit to the outpost. I know I sure am.'
<p><b>You give Noilgin Mindtune : </b><a href=http://phobos/eq/item.php?id=6067>Bound Research Notes</a>
<br><b>Noilgin Mindtune says </b>'Oh no! I have been tracked down. Can't I have a moment's peace? I'm sorry you went through all the trouble to get this to me, but I'm not delivering mail right now. I'm trying to take a vacation. You'll have to deliver it to Lanivon Baxer in the Toxxulia Forest yourself. Here, take it back. I have packaged it up nicely for the journey.'
<br><b>Noilgin Mindtune gives you : </b><a href=http://phobos/eq/item.php?id=6069>Packaged Research Notes</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>