<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19238>Spell: Spirit of Scale</a><li><a href=http://phobos/eq/item.php?id=19244>Spell: Form of the Howler</a><li><a href=http://phobos/eq/item.php?id=19232>Spell: Circle of Winter</a><li><a href=http://phobos/eq/item.php?id=19234>Spell: Circle of Summer</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19233>Spell: Upheaval</a><li><a href=http://phobos/eq/item.php?id=19240>Spell: Glamour of Tunare</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Samitha Lightheart says </b>'And a good day to you, too! I have traveled here in the name of the Jaggedpine Treefolk to search out any new and [wonderful powers] that would aid us in preserving the wildlife back home. I have not been able to venture far from this outpost as the inhabitants of the nearby woods pose a great danger. I have decided to wait for more of my Treefolk to arrive before adventuring further.  There's safety in numbers, they always say.'
<p><b>You say, </b>'wonderful powers'
<br><b>Samitha Lightheart says </b>'From what I have gathered from the residents of this outpost and from others like myself, there are a fair number of scrolls to be found in the outlying areas.  These scrolls are said to contain new and powerful magic. I myself have found a few of these scrolls. But the problem is, I don't believe I have a complete collection. If you would care to [help] me, I'd be willing to trade some of the extra ones I have for some of the extras you may run across.'
<p><b>You say, </b>'help'
<br><b>Samitha Lightheart says </b>'I am still looking for four scrolls that I have not been able to locate. They are the scrolls of Circle of Winter, Circle of Summer, Spirit of Scale, and Form of the Howler. If you bring any of these back, I'll give you one of four very rare scrolls in my possession.'
<p><b>You give Samitha Lightheart : </b><a href=http://phobos/eq/item.php?id=19238>Spell: Spirit of Scale</a>
<br><b>Samitha Lightheart says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Samitha Lightheart gives you : </b><a href=http://phobos/eq/item.php?id=19233>Spell: Upheaval</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Samitha Lightheart : </b><a href=http://phobos/eq/item.php?id=19244>Spell: Form of the Howler</a>
<br><b>Samitha Lightheart says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Samitha Lightheart gives you : </b><a href=http://phobos/eq/item.php?id=19233>Spell: Upheaval</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Samitha Lightheart : </b><a href=http://phobos/eq/item.php?id=19232>Spell: Circle of Winter</a>
<br><b>Samitha Lightheart says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Samitha Lightheart gives you : </b><a href=http://phobos/eq/item.php?id=19240>Spell: Glamour of Tunare</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Samitha Lightheart : </b><a href=http://phobos/eq/item.php?id=19234>Spell: Circle of Summer</a>
<br><b>Samitha Lightheart says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Samitha Lightheart gives you : </b><a href=http://phobos/eq/item.php?id=19233>Spell: Upheaval</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>