<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'what hobby'
<br><b>Wellford Fargin says </b>'I used to collect rare coins and gems.  I came to Firiona Vie to do just that. but I never have the time to [collect rare coins] when I am always here working.'
<p><b>You say, </b>'I will collect rare coins'
<br><b>Wellford Fargin says </b>'If you want to help. you can begin by replacing my prized Star of Odus which was taken from my vault when I stepped out to dine.  Do so. and I may trust you to collect coins. I will also reward you with an item a composer left here.'
</td></tr></table>