<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>#Translocator Deela says </b>'Hello there. We have most the ships working again. If you need to [travel to Butcherblock] or want to know more about [travel to Overthere],  [travel to Oasis] or [travel to Firiona] I can help you with this.'
<p><b>You say, </b>'travel to butcherblock'
<br><font color=white><b>The Player moves to zone 68 at 3168.92,851.92,11.66</b></font>
<p><b>You say, </b>'travel to overthere'
<br><b>#Translocator Deela says </b>'The bloated Belly docks at the ogre camp'
<p><b>You say, </b>'travel to oasis'
<br><b>#Translocator Deela says </b>'Take the raft north of the ogre camp'
<p><b>You say, </b>'travel to firiona'
<br><b>#Translocator Deela says </b>'Take the shuttle to Firiona Vie'
</td></tr></table>