<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17037>hand with one only a thumb</a></ul></td><td><p><b>You say, </b>'gomoz'
<br><font color=green><b>a dancing skeleton </b>stops in suprise.</font>
<br><b>a dancing skeleton says </b>'Gomoz!! Why, that is me! I was heading off to be with the elements when I was captured by this smelly ogre. Actually, he is not as smelly as most.'
<p><b>You say, </b>'talon southpaw'
<br><b>a dancing skeleton says </b>'Master Talon Southpaw!! He was my master. Dead, he became. Off to the elements. I keep his special hand with me. Perhaps I should have it returned. Maybe I shall find a young adventurer to [return the hand to Cabilis].'
<p><b>You say, </b>'return the hand to cabilis'
<br><b>a dancing skeleton says </b>'Yes!! Return the hand. Here it is. Missing four it is. Within the tower of past pain and torture is where the four lie. Taken by bones similar to myself.'
<br><b>a dancing skeleton gives you : </b><a href=http://phobos/eq/item.php?id=17037>hand with one only a thumb</a>
</td></tr></table>