<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20474>Receipt</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20457>Crushed Pot</a><li><a href=http://phobos/eq/item.php?id=18960>Ancient Pattern</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Alrik Farsight says </b>'Ah. Hello there, adventurer. Come to search for ancient artifacts with Fizzlebik and myself?'
<p><b>You say, </b>'ancient artifacts'
<br><b>Alrik Farsight says </b>'Oh. All types of things. This area is great. So many artifacts and remains of things all over. It's starting to fall into the pattern of things.'
<p><b>You say, </b>'ancient bowl'
<br><font color=green><b>Alrik Farsight </b>rummages through his tattered bag and throws aside a towel. 'Too many towels. Oh well, someone told me they were good to have once. Here it is, a bowl pattern. Interesting bowl. Looks almost like a magical bowl but I'm no potter. You need it, you say? Well, it is interesting. Part of my research here is for the wizard guild in Felwithe. I'm sure they'd put a high price on this one, the enchanters guild being so interested in trading for magical paraphernalia and all. Of course if you helped me out on a chore I have, I'd be happy to give it to you. I need to deliver an artifact to the guild and I'd much rather stay here exploring. If you wish, you can take the artifact and return with the receipt and I'll give you the pattern.'</font>
<p><b>You say, </b>'take the artifact'
<br><b>Alrik Farsight says </b>'Hah! Okay, then. Here take this to Farios Elianos in Felwithe. He will give you the receipt.'
<br><b>Alrik Farsight gives you : </b><a href=http://phobos/eq/item.php?id=20457>Crushed Pot</a>
<p><b>You give Alrik Farsight : </b><a href=http://phobos/eq/item.php?id=20474>Receipt</a>
<br><font color=green><b>Alrik Farsight </b>grins happily. 'Excellent! Was he pleased with the artifact? Oh, that's not even worth answering. I'm sure he was. He's always happy with the things I send him. That's why he honored me with this position of esteem, searching for useful and powerful items in this newly discovered land.'</font>
<br><b>Alrik Farsight gives you : </b><a href=http://phobos/eq/item.php?id=18960>Ancient Pattern</a>
</td></tr></table>