<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28023>Orb of the Triumvirate</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=5532>Water Sprinkler of Nem Ankh</a></ul></td><td><p><b>You give Avatar of Water : </b><a href=http://phobos/eq/item.php?id=28023>Orb of the Triumvirate</a>
<br><b>Avatar of Water gives you : </b><a href=http://phobos/eq/item.php?id=5532>Water Sprinkler of Nem Ankh</a>
<br><b>Avatar of Water disappears.</b>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>