<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20696>Froglok Essence</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20696>Froglok Essence</a></ul></td><td><p><b>You give Dolgin Codslayer : </b><a href=http://phobos/eq/item.php?id=20696>Froglok Essence</a>
<br><b>Dolgin Codslayer says </b>'What's this? Egads! It's perfect.  Now all we gotta do is hope he bites.' Dolgin takes a little of the essence and smears it on a piece of bread. He places the bait into the water and watches intently.'
<br><b>Dolgin Codslayer gives you : </b><a href=http://phobos/eq/item.php?id=20696>Froglok Essence</a>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=96073>#Faydedar</a></b> spawns (-11745,-2178,-0.63).</font>
<br><b>Dolgin Codslayer disappears.</b>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>