<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>Drendico Metalbones says </b>'The hills ears keep spinning the wonders of wells. Twisting twisting fly in water scar hot horses. Teach me! Bring floating water islands of doom!'
<br><font color=green><b>Drendico Metalbones </b>will not accept this item.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>