<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12970>Robe of the Whistling Fists</a><li><a href=http://phobos/eq/item.php?id=1682>Danl's Reference</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1683>Celestial Fists</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Lheao </b>jumps at your voice and begins laughing at his skittishness.</font>
<br><b>Lheao says </b>'Ahh, hello there. Not many people know of this place, so visitors are quite rare. Hehehe. Its a very beautiful place indeed, so.. ummm, dont go telling everyone you know about it. Heheh. Thanks, Friend.'
<p><b>You say, </b>'i have found the book of immortals'
<br><font color=green><b>Lheao </b>looks up at you, eyes wide in astonishment.</font>
<br><b>Lheao says </b>'My god, you found Immortals?! Where did you find it? Nevermind, that is unimportant. I have in my possession a book that explains more of these individuals. Its value is unimaginable as well as the impact it is capable of. As you can see, I grow old. I need an individual to watch over this book and make sure it is protected. Would you be willing to take this [responsibility]?'
<p><b>You say, </b>'responsibility'
<br><b>Lheao says </b>'Im sorry, [Your Name], but I could only give this book to a true master, such as a member of the Whistling Fists Order. And unless you can give me proof that you are one, in addition to Danls reference, which is very unlikely, there is no way I'll let you take charge of the [Celestial Fists].'
<p><b>You say, </b>'celestial fists'
<br><b>Lheao says </b>'The Celestial Fists is the title of a book written by an unknown author. His writing is sub par but the legend is interesting from a biographical standpoint alone. Its rarity commands top dollar in the scholarly community but the secrets revealed in the book are what truely makes it dangerous. I hope Im able to find someone to watch over it soon.'
<p><b>You give Lheao : </b><a href=http://phobos/eq/item.php?id=12970>Robe of the Whistling Fists</a>, <a href=http://phobos/eq/item.php?id=1682>Danl's Reference</a>
<br><b>Lheao says </b>'Astonishing! To think that you are a master of an order thought to be lost in our world. Forgive my earlier doubts. I believe you are indeed worthy to be given the responsibility of watching over this book. Take great care that it does not fall into the wrong hands as it would be truly disatrous.'
<br><b>Lheao gives you : </b><a href=http://phobos/eq/item.php?id=1683>Celestial Fists</a>
<br><b>Lheao says </b>'I have no need for this item [Your Name], you can have it back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>