<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12942>Strange Ochre Clay</a><li><a href=http://phobos/eq/item.php?id=12945>Crushed Diamonds</a><li><a href=http://phobos/eq/item.php?id=12944>Yun Shaman Powder</a><li><a href=http://phobos/eq/item.php?id=12943>Greyish Bone Chips</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12941>Spell: Cannibalize II</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>The Great Oowomp </b>gestures as if casting a powerful spell...</font>
<br><b>The Great Oowomp says </b>'Come forward, adventurer! Come and [see the dancing skeleton]. I shall cast a powerfull spell and bring forth this operatic, clattering jumble of bones and he shall do a fine dance for you. From the nether regions and planes beyond, I call forth this bardic, magical, rhyming, tap-dancing hunk of undead!! I am Oowomp the Great!!'
<p><b>You say, </b>'see the dancing skeleton'
<br><b>The Great Oowomp says </b>'Oh!!  You wish to see the great Oowomp perform his magic!! I have studied with the grand mages and wise [McMerin clan] of Norrath. as my speech implies. I can call forth the skeleton with but a twinkling of my power and five of your gold.'
<p><b>You say, </b>'McMerin clan'
<br><b>The Great Oowomp says </b>'Clan McMerin were wise shamans from the North. They allowed me to study with them. I learned many spells while I communed with them.  From them, I sto.., I mean, I learned the secret of McMerin's Feast. If you want to know the secret, you could [help gather components] for future rituals.'
<p><b>You say, </b>'help gather components'
<br><b>The Great Oowomp says </b>'Actually... Not so much help as do - ALL - of the gathering. In the lands of Kunark are clay of Ghiosk, crushed dread diamond and powder of Yun. A rare find would be the bones of one who touched the Bath of Obulus. Find and return these to me and the shaman secret of McMerin's Feast is yours.'
<p><b>You give The Great Oowomp : </b><a href=http://phobos/eq/item.php?id=12942>Strange Ochre Clay</a>, <a href=http://phobos/eq/item.php?id=12945>Crushed Diamonds</a>, <a href=http://phobos/eq/item.php?id=12944>Yun Shaman Powder</a>, <a href=http://phobos/eq/item.php?id=12943>Greyish Bone Chips</a>
<br><b>The Great Oowomp says </b>'Ahh, you've gathered all the ritual components. Very good, as promised, a cop...I mean, priceless scroll of McMerin's Feast for you!'
<br><b>The Great Oowomp gives you : </b><a href=http://phobos/eq/item.php?id=12941>Spell: Cannibalize II</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>The Great Oowomp says </b>'Whats this? I don't want this, have it back.'
</td></tr></table>