<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=59041>A cracked Zraxthril amulet</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=59008>Spell: Icewind</a></ul></td><td><hr><b>When #A Tempest Spirit spawns </b>
<p><b>You give #A Tempest Spirit : </b><a href=http://phobos/eq/item.php?id=59041>A cracked Zraxthril amulet</a>
<br><font color=green><b>#A Tempest Spirit </b>takes the amulet from you and holds it in its watery hand. The wind around you rises and the sea begins to swell. The spirit melts into a swirling pool at your feet. You gaze down into the pool and notice it begin to shrink in circumference. It continues to shrink and spin until finally there is nothing left but a small blue amulet on the ground. You reach to pick it up and hear an echo from the sea. 'Call us and we will aid you.'</font>
<br><b>#A Tempest Spirit gives you : </b><a href=http://phobos/eq/item.php?id=59008>Spell: Icewind</a>
<br><b>#A Tempest Spirit disappears.</b>
<br><b>#A Tempest Spirit says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>