<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=59030>Alina's emblem</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=59011>Spell: Temperance</a></ul></td><td><p><b>You give 1 an erudite spirit : </b><a href=http://phobos/eq/item.php?id=59030>Alina's emblem</a>
<br><font color=green><b>1 an erudite spirit </b>is surrounded by a warm glow as the ring touches her ethereal form. Her lips curl into a smile as she begins to fade away into the mist. You hear something fall to the ground. You notice a wet scroll half buried in the sand. You reach down and pick it up</font>
<br><b>1 an erudite spirit gives you : </b><a href=http://phobos/eq/item.php?id=59011>Spell: Temperance</a>
<br><font color=grey><i>A global variable is unset at this point.</font></i>
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<br><b>1 an erudite spirit disappears.</b>
<hr><b>When 1 an erudite spirit is killed </b>
<br><font color=grey><i>A global variable is unset at this point.</font></i>
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
</td></tr></table>