<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=59027>A black skull necklace</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=59003>Spell: Ethereal Cleansing</a><li><a href=http://phobos/eq/item.php?id=59028>A glowing black skull necklace</a></ul></td><td><p><b>You give 2 an erudite spirit : </b><a href=http://phobos/eq/item.php?id=59027>A black skull necklace</a>
<br><b>2 an erudite spirit gives you : </b><a href=http://phobos/eq/item.php?id=59003>Spell: Ethereal Cleansing</a>
<br><b>2 an erudite spirit gives you : </b><a href=http://phobos/eq/item.php?id=59028>A glowing black skull necklace</a>
<br><b>2 an erudite spirit disappears.</b>
</td></tr></table>