<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=55007>A note of safe passage</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>a shipwrecked hatestorm sailor says </b>'Wot do you want?  I be tired after [big trouble].'  This Troll's speech gives you the impression that he is not the smartest being you have ever dealt with'
<p><b>You say, </b>'big trouble'
<br><b>a shipwrecked hatestorm sailor says </b>'Me's and me crew come to dock here but a big storm come and smash our ship. I thinks me the only one alive now. Da ship and all [loots] are now gone.'
<p><b>You say, </b>'loots'
<br><b>a shipwrecked hatestorm sailor says </b>'Da loots from da other ship dat we attacked. Dat ship gone now too becuz of da big storm. ' An almost sly look seems to grow across the troll's scarred face. 'Yous wants da loots? Mebbe me can helps you if you can [help] me?'
<p><b>You say, </b>'help'
<br><b>a shipwrecked hatestorm sailor says </b>'Now dat I have no ship, methinks dat I will have ta work in da mines agin. Me not want that. Dere be no ale in dere and me luvs da ale. You gets me da [safe passage] to da maynland and mebbe me can tell you more about da loots.'
<p><b>You say, </b>'safe passage'
<br><b>a shipwrecked hatestorm sailor says </b>'I dunno. Mebbe you can gets me a note dat says me can ride on a ship to da maynland or sumthing.'
<p><b>You give a shipwrecked hatestorm sailor : </b><a href=http://phobos/eq/item.php?id=55007>A note of safe passage</a>
<br><b>a shipwrecked hatestorm sailor says </b>'Dis be gud. Better not trick me, becuz I get angry and it not good when me get angry. Me saw a lot of da loots come up to da beach. Da troll zombee mens come to da loots and take all. I not fights dem. Date be truble dere.'
<br><b>You receive </b> 6cp
<br><b>a shipwrecked hatestorm sailor says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>