<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=58007>Luggald Heart</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=58008>Fragment of Dark Ice</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Aliaka Songscale </b>flinches as you initially approach, but appears more at ease when she realizes you are not an immediate threat. 'Ah, thank Prexus you are not one of them. Not that this guarantees that you are any less dangerous, so please state your intentions clearly. We have suffered much [abuse] at the hands of other races, and in particular I do not appreciate the pain that the sea trolls inflict upon my sisters.'</font>
<p><b>You say, </b>'abuse'
<br><font color=green><b>Aliaka Songscale </b>speaks, her visage one of sadness and despair, 'This shore has forever been the home of my people, but we are practically driven into hiding now, forced to flee and scatter when the Luggalds come near. At their whim, the fiendish beasts lance us with their icy spears. The cold chill bites and the pain is horrible. In fact, there are still fragments of the dark ice embedded in my scales from their last attack. I believe they only mean to torment and not kill us, as so far there have been few deaths. Now that you understand our plight, what is it you want from me?'</font>
<p><b>You say, </b>'fragments of the dark ice'
<br><font color=green><b>Aliaka Songscale </b>smirks, 'Forgive my hesitance in trusting a stranger, but the frozen shards are quite painful, and removing them would be even more so. Perhaps we can trade services? I will give you some willingly if you would complete a [task] first.'</font>
<p><b>You say, </b>'task'
<br><b>Aliaka Songscale says </b>'As a sign of loyalty, and to avenge the innocent blood that was spilt by the Luggalds, I would like you to cut down some of the fiends and bring proof of their demise. Use whatever means necessary. Grant them no quarter and expect none in return. For each of their dark hearts, I will trade pieces of the ice that you seem so interested in. I will accept nothing else.'
<p><b>You give Aliaka Songscale : </b><a href=http://phobos/eq/item.php?id=58007>Luggald Heart</a>
<br><b>Aliaka Songscale says </b>'Yes!  For this I will gladly give you a fragment of the dark ice!'
<br><b>Aliaka Songscale gives you : </b><a href=http://phobos/eq/item.php?id=58008>Fragment of Dark Ice</a>
<br><b>Aliaka Songscale says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>