<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=58010>Empty Flask</a><li><a href=http://phobos/eq/item.php?id=58013>A Large Rock</a><li><a href=http://phobos/eq/item.php?id=58014>Small Piece of Flotsam</a><li><a href=http://phobos/eq/item.php?id=58015>Small Piece of Jetsam</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=58013>A Large Rock</a><li><a href=http://phobos/eq/item.php?id=59013>Spell: Stoicism</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>an impassive sea spirit </b>sways back and forth, rocking with the gentle motions of the tide. You are nearly mesmerized by its periodic fluctuation, when it suddenly speaks,</font>
<br><b>an impassive sea spirit says </b>'I watch you as you watch me, and I wonder. Do you realize how to become empty of wishes, of dreams, of hope and sorrow? What do you know, strange one, about the virtue of null emotion? Do you understand how to be as unwavering as the ocean itself? Can you envision yourself as the pebble in the river? Can you mute feeling? Do you [dare to learn]?'
<p><b>You say, </b>'dare to learn'
<br><b>an impassive sea spirit says </b>'We will see, Dreamhunter, we will see. If you are a willing pupil then demonstrate that you have begun to comprehend. Bring me something empty that previously numbed feeling and therefore brought emptiness to its possessor. You should not have to travel far.'
<p><b>You say, </b>'impassive as the sea'
<br><font color=green><b>an impassive sea spirit </b>removes his gaze from the ocean and looks at you.</font>
<br><b>an impassive sea spirit says </b>'Perhaps you can be, but I require proof. If you can defeat the smallest elements of the ocean I shall reward you. Hand me their essences and I shall know you have completed the task. When you are ready to challenge them hand me back that rock.'
<p><b>You give an impassive sea spirit : </b><a href=http://phobos/eq/item.php?id=58010>Empty Flask</a>
<br><b>an impassive sea spirit says </b>'Well done, strange one. Your perception is admirable.' The spirit hands you an incredibly heavy rock. 'Can you, Dreamhunter, be as [impassive as the sea]?'
<br><font color=yellow>You gain experience!!</font>
<br><b>an impassive sea spirit gives you : </b><a href=http://phobos/eq/item.php?id=58013>A Large Rock</a>
<p><b>You give an impassive sea spirit : </b><a href=http://phobos/eq/item.php?id=58013>A Large Rock</a>
<br><font color=green><b>an impassive sea spirit </b>melds with the murky ocean water, and two elements of the sea appear.</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=224345>Flotsam</a></b> spawns (650,-284.48,-148.25).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=224346>Jetsam</a></b> spawns (665.95,-267.1,-148.25).</font>
<p><b>You give an impassive sea spirit : </b><a href=http://phobos/eq/item.php?id=58014>Small Piece of Flotsam</a>, <a href=http://phobos/eq/item.php?id=58015>Small Piece of Jetsam</a>
<br><b>an impassive sea spirit says </b>'Now you comprehend. This is the way things are, and the way they have always been. Your acceptance of these truths proves your worthiness.'
<br><b>an impassive sea spirit gives you : </b><a href=http://phobos/eq/item.php?id=59013>Spell: Stoicism</a>
</td></tr></table>