<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When Assistant Vagli spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Assistant Vagli says </b>'Greetings, friend. If you have come to study under the great Alvarik you have come to the right place! I help by carrying his research tomes for him. If there is one you would like to buy, feel free to browse through what we have. If you're looking for something to do, I may have a [task] available for you to get started on. Alvarik has much he needs done and I can't do it all myself!'
</td></tr></table>