<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=62002>Worn Trinket</a><li><a href=http://phobos/eq/item.php?id=62001>Ruined Trinket</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Bremmus Mopfoot </b>Greetings friend. To see one brave the dangers of this forsaken island is suprising. You must be a treasure seeker. Tell me, do you seek [treasure]?</font>
<p><b>You say, </b>'treasure'
<br><font color=green><b>Bremmus Mopfoot </b>Oh that's no good! More competition means less treasure for me. Say, tell you what: If you bring me any trinkets you find, I will reward you depending on their condition.</font>
<p><b>You give Bremmus Mopfoot : </b><a href=http://phobos/eq/item.php?id=62002>Worn Trinket</a>
<br><b>Bremmus Mopfoot says </b>'Ah! This is most excellent. I was looking for this piece. Here, take this for your troubles.'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 14pp
<p><b>You give Bremmus Mopfoot : </b><a href=http://phobos/eq/item.php?id=62001>Ruined Trinket</a>
<br><b>Bremmus Mopfoot says </b>'Ah! This is most excellent. I was looking for this piece. Here, take this for your troubles.'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 7pp
<br><b>Bremmus Mopfoot says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>