<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=59033>A glowing collar</a><li><a href=http://phobos/eq/item.php?id=59034>A strange dark powder</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=59032>A stone emblem</a><li><a href=http://phobos/eq/item.php?id=59010>Spell: Bond of the Wild</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Craegin Coldtongue </b>shivers quietly.  You have a hard time believing that a barbarian of his stature could possibly think this climate to be cold.  He stares into your eyes for a moment and then shuffles away.</font>
<p><b>You say, </b>'Beastlord'
<br><font color=green><b>Craegin Coldtongue </b>nods quickly and begins to draw again in the sand. He points at the humanoid figure and then at himself. Apparently he has drawn himself. He looks up at you and you nod back in understanding. He points to the wolf and then points out onto the island. He grabs a handful of dust and blows it across the wolf's picture. Perhaps his [warder] is sick and lost on the island somewhere. He looks as if he might want to [draw] more.</font>
<p><b>You say, </b>'draw more about your warder'
<br><font color=green><b>Craegin Coldtongue </b>nods furiously. He begins drawing again in the sand. you see some sort of spear being thrown at the wolf. He then draws a collar of some sort and then draws an arrow to the wolf. Apparently his warder has been injured and captured somehow by something on the island. You can see the pain in the barbarian's eyes as he looks at you hopefully. He hands you a small emblem of some kind and points towards the island.</font>
<br><b>Craegin Coldtongue gives you : </b><a href=http://phobos/eq/item.php?id=59032>A stone emblem</a>
<p><b>You say, </b>'draw for me'
<p><b>You say, </b>'cave system'
<p><b>You give Craegin Coldtongue : </b><a href=http://phobos/eq/item.php?id=59033>A glowing collar</a>
<br><font color=green><b>Craegin Coldtongue </b>looks at you in amazement as you hand the glowing collar to him. He looks as if he might weep for joy at any moment. He holds the collar firmly by the clasp and brings it down to his side. He mumbles some words and the wolf immediately appears beside him. He reaches into his bags and grabs a small stone similar to the one fit into the collar. You reach forward and take it from him. He points at the dirt once more as if he wishes to [draw] something for you.</font>
<br><b>Craegin Coldtongue gives you : </b><a href=http://phobos/eq/item.php?id=59010>Spell: Bond of the Wild</a>
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<p><b>You give Craegin Coldtongue : </b><a href=http://phobos/eq/item.php?id=59034>A strange dark powder</a>
<br><b>Craegin Coldtongue says </b>'I don't need this.'
<br><b>Craegin Coldtongue says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>