<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=59053>A glowing black potion</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Grennik Neltrin says </b>'Hello, [Your Name]. Nice weather isn't it?  Well considering our location I mean.  I somehow doubt that the sun ever shines on this cursed rock.'
<p><b>You give Grennik Neltrin : </b><a href=http://phobos/eq/item.php?id=59053>A glowing black potion</a>
<br><font color=green><b>Grennik Neltrin </b>holds the vial carefully between her fingers as she spins it slowly in the light. 'Yes I believe the potion is complete now. Of course we can never be certain until one of us drinks it. Since you prepared it would stand to reason for you to try it.'</font>
<br><font color=green><b>Grennik Neltrin </b>lifts the dark potion towards [Your Name] and [Your Name] reaches out and takes it from her. [Your Name] takes a deep breath and brings the potion to  lips. The smell nearly makes  faint, but  regains  composure and swallows it in one giant gulp.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grennik Neltrin says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>