<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=59022>A faded, watermarked book</a><li><a href=http://phobos/eq/item.php?id=59024>A transcribed songbook</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=59023>A faded songbook</a><li><a href=http://phobos/eq/item.php?id=59002>Song: Aria of Asceticism</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Kardin Nillic </b>lifts his gaze from the whitened corpse lying on the bed in front of him. He holds the pale fingers tightly in his hands. As he opens his mouth to speak you shiver as what you thought was a corpse makes a soft moaning sound on the bed next to him. 'What business do you have here? Death grows near for him, what comfort can you hope to bring him in this [plagued] place?</font>
<p><b>You say, </b>'plagued'
<br><b>Kardin Nillic says </b>'The plague of Innoruuk has infested this island. We now know that many of the fish that can be caught here are diseased and should not be eaten. Of course this knowledge does little to abate the fevers of those already stricken. The Broken Skull pirates seem to be mysteriously [immune] to this plague.'
<p><b>You say, </b>'immune'
<br><b>Kardin Nillic says </b>'Somehow the pirates are able to avoid becoming ill from eating the fish here. We know they're eating the same manner of fish that we are, but something else must be protecting or perhaps curing them of the toxins in the fish. In fact, they seem to always be in good spirits with the boisterous racket of [singing] and fighting that echoes over the island every fortnight.'
<p><b>You say, </b>'singing'
<br><font color=green><b>Kardin Nillic </b>snickers softly. 'The pirates apparently enjoy songs at meal time. A group of bards seem to have joined them. They sound as if they were trained at the Wind Spirit's Song, but the faded song pages I've seen of theirs read like students of Marsheart's. All the pages I've seen have been faded and largely illegible or I would know for sure.</font>
<p><b>You give Kardin Nillic : </b><a href=http://phobos/eq/item.php?id=59022>A faded, watermarked book</a>
<br><b>Kardin Nillic says </b>'I can't read all of it, Take the rest to Jusean Evanesque of South Qeynos, he will understand.'
<br><b>Kardin Nillic gives you : </b><a href=http://phobos/eq/item.php?id=59023>A faded songbook</a>
<p><b>You give Kardin Nillic : </b><a href=http://phobos/eq/item.php?id=59024>A transcribed songbook</a>
<br><b>Kardin Nillic says </b>'You have done well [Your Name], my friend will now be saved, let me share my song with you.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Kardin Nillic gives you : </b><a href=http://phobos/eq/item.php?id=59002>Song: Aria of Asceticism</a>
</td></tr></table>