<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=58009>Pouch of Dark Ice</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17194>Small Pouch</a><li><a href=http://phobos/eq/item.php?id=59021>Spell: Frozen Harpoon</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Lairyn Debeian </b>stares at you directly in the eyes. 'Greetings, [Your Name].  I suppose you're here like everyone else in search of fame and fortune.  Good luck to you, and good day.  I have many things to attend to.'</font>
<p><b>You say, </b>'new power'
<br><b>Lairyn Debeian says </b>'The strange beasts known as Luggalds that reside on Broken Skull Rock have an amazing power over the dark waters of the deep. They are able to conjure it up in the form of an immense spear of ice. I have seen them do so with my own eyes, though I was watching from afar, of course. I would not dare venture close enough to anger the foul beasts. Their grasp of this magic is simply breathtaking, and from my observations alone, I am very close to unlocking their methods. Unfortunately, I have run into an obstacle, as I cannot complete my research without something more tangible. If only I were brave enough to get closer, or foolish enough. As you can see, I am more intellectual than adventurer.'
<br><font color=green><b>Lairyn Debeian </b>chuckles and his spectacles slip a little further down his nose.</font>
<p><b>You say, </b>'brave enough'
<br><font color=green><b>Lairyn Debeian </b>gasps in apparent surprise, 'What? Are you certain you wish to put yourself in such a perilous position? Well I certainly can't turn down good help, so I'll tell you what I know. The Luggalds often utilize their spells against creatures in the waters of the harbor. Whether this is for practice, or for sport, or to ward off attackers I am not sure. I would suggest investigating the harbor for further evidence. Take this bag and bring me whatever you can find.'</font>
<br><b>Lairyn Debeian gives you : </b><a href=http://phobos/eq/item.php?id=17194>Small Pouch</a>
<p><b>You give Lairyn Debeian : </b><a href=http://phobos/eq/item.php?id=58009>Pouch of Dark Ice</a>
<br><font color=green><b>Lairyn Debeian </b>looks at you in amazement as you hand the pouch of dark ice him.</font>
<br><b>Lairyn Debeian says </b>'Well then, let's have a look then.  Yes, yes, I see now.'
<br><font color=green><b>Lairyn Debeian </b>scribles on a piece of parchment and thrusts it at you.</font>
<br><b>Lairyn Debeian says </b>'This should serve you well'
<br><b>Lairyn Debeian gives you : </b><a href=http://phobos/eq/item.php?id=59021>Spell: Frozen Harpoon</a>
<br><b>Lairyn Debeian says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>