<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=54005>A Blue Lotus Petal</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=54004>Shiny Mermaid Scale</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Latiza Trelune </b>eyes you coolly, taking particular interest in the shining pieces of your array. 'Yes, [Your Name]? Is there something in particular that you were looking for?</font>
<br><font color=green><b>Latiza Trelune </b>chuckles. 'Do not be taken aback that I know your name. People of my kind have always been a bit more observant than yours.'</font>
<p><b>You give Latiza Trelune : </b><a href=http://phobos/eq/item.php?id=54005>A Blue Lotus Petal</a>
<br><font color=green><b>Latiza Trelune </b>looks delighted and tucks the petal into a lock of her hair. 'How lovely! Here then, a scale you shall have. Do not be surprised if nothing comes of it, but I do thank you for the gift. Best of luck to you, dear mortal.'</font>
<br><b>Latiza Trelune gives you : </b><a href=http://phobos/eq/item.php?id=54004>Shiny Mermaid Scale</a>
<br><b>Latiza Trelune says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>