<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=59054>Gnomish spectacles</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=59020>Spell: Vision Shift</a></ul></td><td><hr><b>When Redlin Hullnic spawns </b>
<p><b>You say, </b>'hail'
<br><b>Redlin Hullnic says </b>'Eh, who's there? Yender is that you? No you're far too tall to be Yender. You must be one o' them [pirates]!' Redlin then begins to beat furiously on your ankle with his staff. Furiously might be a slightly strong word, as he doesn't seem to be doing any real damage.'
<p><b>You say, </b>'not a pirate'
<br><b>Redlin Hullnic says </b>'Not a pirate, aye? Well lucky thing for you, I would have given you a real thrashing with my stick if you were! I don't suppose you know where I could get a good pair of gnomish glasses around here do ya? Mine broke on the boat ride over and I can't see a thing without 'em.'
<p><b>You give Redlin Hullnic : </b><a href=http://phobos/eq/item.php?id=59054>Gnomish spectacles</a>
<br><font color=green><b>Redlin Hullnic </b>takes the spectacles from your hands and puts them up to his eyes and blinks several times.</font>
<br><b>Redlin Hullnic says </b>'Many thanks, [Your Name]! I don't know what I would have done without you. Probably stagger around the island half blind for the rest of my life! At any rate I can repay you with a little trick I picked up along the way. If you ever get in a jam, hopefully you won't be as forgetful as I was!' He hands you a scroll with several runes scrawled across it.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Redlin Hullnic gives you : </b><a href=http://phobos/eq/item.php?id=59020>Spell: Vision Shift</a>
</td></tr></table>