<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12848>A Spectacle</a><li><a href=http://phobos/eq/item.php?id=12850>Forsaken Pariah Mask</a><li><a href=http://phobos/eq/item.php?id=12851>Evergreen Ivy Ringband</a><li><a href=http://phobos/eq/item.php?id=12610>Green Death Rum</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12848>A Spectacle</a></ul></td><td><p><b>You give 93182 : </b><a href=http://phobos/eq/item.php?id=12848>A Spectacle</a>
<br><font color=green><b>93182 </b>a skeleton worker stops working and begins to open his creaking jaw.</font>
<br><b>93182 says </b>'I live to study and quench my thirst. I live to Bash the Faces of Pariah and entangle myself in the ivy of evergreen. I live. I want to remember.'
<br><b>93182 gives you : </b><a href=http://phobos/eq/item.php?id=12848>A Spectacle</a>
<p><b>You give 93182 : </b><a href=http://phobos/eq/item.php?id=12848>A Spectacle</a>, <a href=http://phobos/eq/item.php?id=12851>Evergreen Ivy Ringband</a>, <a href=http://phobos/eq/item.php?id=12610>Green Death Rum</a>, <a href=http://phobos/eq/item.php?id=12850>Forsaken Pariah Mask</a>
<br><font color=green><b>93182 </b>a skeleton worker stops working and begins to open his creaking jaw.</font>
<br><b>93182 says </b>'I live to study and quench my thirst. I live to Bash the Faces of Pariah and entangle myself in the ivy of evergreen. I live. I want to remember.'
<br><b>93182 gives you : </b><a href=http://phobos/eq/item.php?id=12848>A Spectacle</a>
<br><b>93182 says </b>'You will have to be more skilled to complete that quest.'
</td></tr></table>