<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10023>Jade</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>an undead foreman </b>an undead foreman turns to face you. You can see a faint green glow emanating from his vacant eye sockets.</font>
<br><b>an undead foreman says </b>'Are you a [new worker]? Huh? Speak or go!!'
<p><b>You say, </b>'new worker'
<br><b>an undead foreman says </b>'Hmmph!! Too much flesh!! If you want to work, you must first fill my eye sockets with my favorite gem. This shall be your payment for your sledgehammer.'
<p><b>You give an undead foreman : </b><a href=http://phobos/eq/item.php?id=10023>Jade</a>
<br><b>an undead foreman says </b>'I do not know you well enough to entrust such an item to you, yet.'
<br><b>an undead foreman says </b>'I do not know you well enough to entrust such an item to you, yet.'
</td></tr></table>