<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1686>Trunt's Head</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1687>Eye of Kaiaren</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Astral Projection </b>ignores you.</font>
<p><b>You say, </b>'yes'
<br><b>Astral Projection says </b>'I assume you have read about us and spoken with the old man, Kaiaren. Since that time, I have grown in power and influence to a point unseen by any mortal. Unfortunately, I will have to demonstrate a small amount of my skill when I destroy you. This is bad. I must decide whether you are worthy to see the techniques I wield, even though you will die shortly thereafter. Tell me, [Your Name], who are you?'
<p><b>You say, </b>'i am the one'
<br><font color=green><b>Astral Projection </b>chuckles.</font>
<br><b>Astral Projection says </b>'Thats quite a boast, [Your Name]. All beings strive for nothingness at the most basic level of sentience. However, almost none ever achieve this. Not even I have discarded my ego yet and you stand here and tell me you have? Perhaps you will be a worthy opponent. I shall be waiting in the great lake near here. Take that token as proof of things to come for you. If you still wish to throw your life away so needlessly, return it to my image there. I await your decision.'
<br><b>Astral Projection disappears.</b>
<p><b>You give Astral Projection : </b><a href=http://phobos/eq/item.php?id=1686>Trunt's Head</a>
<br><font color=green><b>Astral Projection </b>looks up and down.</font>
<br><b>Astral Projection gives you : </b><a href=http://phobos/eq/item.php?id=1687>Eye of Kaiaren</a>
<br><b>Astral Projection says </b>'Hmmm, I was hoping for something more impressive. This is just a small token of the last person who tried to interfere with my plans. He failed as shall you. But tell me truly, are you the one who has so rudely removed my students?'
</td></tr></table>