<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19203>Spell: Death Pact</a><li><a href=http://phobos/eq/item.php?id=19205>Spell: Upheaval</a><li><a href=http://phobos/eq/item.php?id=19209>Spell: Yaulp IV</a><li><a href=http://phobos/eq/item.php?id=19212>Spell: Reckoning</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19206>Spell: Word of Vigor</a><li><a href=http://phobos/eq/item.php?id=19224>Spell: Heroic Bond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Brinaa Darkpact says </b>'Hello, [Your Name]. It's nice to see more able bodies around this part of the outland. We came here in search of the magical powers that are supposed to exist in the ruins and dungeons of this area. We need you to bring back evidence of this power in the form of scrolls. I can't offer much coin in payment, but I do have some rare scrolls I already brought back that may interest you, if you wish to [help in the search].'
<p><b>You say, </b>'help in the search'
<br><b>Brinaa Darkpact says </b>'Excellent! Here is what we are still seeking. The scrolls of Death Pact. Upheaval. Yaulp IV. and Reckoning. If you return one of these to me. I'll release one of my rare scrolls to you.'
<p><b>You give Brinaa Darkpact : </b><a href=http://phobos/eq/item.php?id=19203>Spell: Death Pact</a>
<br><b>Brinaa Darkpact says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Brinaa Darkpact gives you : </b><a href=http://phobos/eq/item.php?id=19206>Spell: Word of Vigor</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Brinaa Darkpact : </b><a href=http://phobos/eq/item.php?id=19205>Spell: Upheaval</a>
<br><b>Brinaa Darkpact says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Brinaa Darkpact gives you : </b><a href=http://phobos/eq/item.php?id=19206>Spell: Word of Vigor</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Brinaa Darkpact : </b><a href=http://phobos/eq/item.php?id=19209>Spell: Yaulp IV</a>
<br><b>Brinaa Darkpact says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Brinaa Darkpact gives you : </b><a href=http://phobos/eq/item.php?id=19224>Spell: Heroic Bond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Brinaa Darkpact : </b><a href=http://phobos/eq/item.php?id=19212>Spell: Reckoning</a>
<br><b>Brinaa Darkpact says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Brinaa Darkpact gives you : </b><a href=http://phobos/eq/item.php?id=19224>Spell: Heroic Bond</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>