<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Bukuku Wolffeetz says </b>'Har har har! Yu funy lukking. Oooo.. do u hav doze smarty writin's? Me like. me like [smarty writin's.]'
<p><b>You say, </b>'what smarty writins'
<br><b>Bukuku Wolffeetz says </b>'Me not know what dem ar for shure. Dem only hav dees names. Umm.. let me see if I can member dem. Taaalisman de umm.. Jasinth. Dat's one of dem. Spirited of Scaley?? OH!! Dis my favorite. Kripple. Den the last is the painful one. Canaabaalize canaabaalize canaabaalize. Yep, dat super duper one. Bring me bak one of dem me trade.'
<p><b>You give Bukuku Wolffeetz : </b>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>