<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12982>A Sarnak War Braid</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12981>Guard of the Marines</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=353>Venril Sathir</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Captain Rottgrime </b>Captain Rottgrime has numerous cracks and holes in his skull from many battles.</font>
<br><b>Captain Rottgrime says </b>'Attention marine!! You will go into battle and fear nothing. You shall prevail and then you shall be sent back into battle. We [shall not allow those sarnak to overtake the Danak Shipyards]. Is that clear marine?!!'
<p><b>You say, </b>'shall not allow those sarnak to overtake the danak shipyards'
<br><b>Captain Rottgrime says </b>'Stand up straight!! That is correct marine!! You shall not allow the sarnak to overtake the shipyards!! Head out to the frontlines marine. Kill the berzerkers and return their war braids to me. For every four, you shall earn your wages. Now get to the front marine!! Move it!! Move it!!'
<p><b>You give Captain Rottgrime : </b><a href=http://phobos/eq/item.php?id=12982>A Sarnak War Braid</a> x4
<br><b>Captain Rottgrime says </b>'Great job marine!! Word of your heroics shall be passed on to the Admiral. If you don't have a shield then take one, if you do then get back to the frontlines. There is no time for R n R!! Move it marine!! Or you'll be pushing Danak till the cockatrice crow!!'
<br><b>Captain Rottgrime gives you : </b><a href=http://phobos/eq/item.php?id=12981>Guard of the Marines</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=353>Venril Sathir</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 1gp
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>