<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10033>Fire Emerald</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18068>Before Green</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Dom K-Perl says </b>'Welcome to my little refuge of the mind. Here you may find passage to the grand worlds within a fine book. I have few books for sale, but any good book is rare in the realm of Norrath. On occasion, I even have [rare finds]. Be sure to use good lighting when reading. Strain the brain, not the eye, I always say.'
<p><b>You say, </b>'rare finds'
<br><font color=green><b>Dom K-Perl </b>starts rummaging through a pile of books and scrolls.</font>
<br><b>Dom K-Perl says </b>'Oh yes, yes, yes. Rare books occasionally make their way to me. Ahhh!! I have one title, Before Green. Sounds like a bit of fiction. What would you like to [purchase]?'
<p><b>You say, </b>'purchase'
<br><font color=green><b>Dom K-Perl </b>puts on a monocle and begins to look over the book.</font>
<br><b>Dom K-Perl says </b>'Hmmmm, Looks fairly valuable. In honor of the book's title, I shall allow you to trade for it with a fire emerald. What a bargain!'
<p><b>You give Dom K-Perl : </b><a href=http://phobos/eq/item.php?id=10033>Fire Emerald</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Dom K-Perl gives you : </b><a href=http://phobos/eq/item.php?id=18068>Before Green</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>