<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'what realm of heroes'
<br><b>Gogu the Smasher says </b>'Me dund 'xactly know wat dat is. but me kno' me part o'it. Me hero 'cause [Cazic] sed so.  Der many heroes from Norrath in it.  Me not as smart as [Kizrak the Tyrant] but me jus' as strong.  Me 'pose to find heroes like me dat like to bash dorfs an' dund like gud things.'
<p><b>You say, </b>'who cazic'
<br><b>Gogu the Smasher says </b>'Cazic-Thule is da Faceless.  He is Lord of Fear an' nobody kin mess wit him.  He liked da way I SMASH things.  He made me a hero an' told me to find others dat SMASH as gud as me. Me was a basher for Oggok befoor dat.'
<p><b>You say, </b>'who kizrak the tyrant'
<br><b>Gogu the Smasher says </b>'Kisrak the Tyrant is 'nother hero from da Realm.  Kisrak is reel smart an' stuff. but he like to smash tuu.  He in Oggok right now lookin' fer heroes.'
</td></tr></table>