<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10634>Dull Emerald</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10621>Enchanted Emerald</a></ul></td><td><p><b>You give Impaler Tzilug : </b><a href=http://phobos/eq/item.php?id=10634>Dull Emerald</a>
<br><b>Impaler Tzilug says </b>'Your bidding has been done, now leave this land and never return.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Impaler Tzilug gives you : </b><a href=http://phobos/eq/item.php?id=10621>Enchanted Emerald</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>