<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4267>Necromancer Skullcap</a><li><a href=http://phobos/eq/item.php?id=48042>Ixpacan's Tome</a><li><a href=http://phobos/eq/item.php?id=48044>Child of Charasis Remains</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=4267>Necromancer Skullcap</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Ixpacan says </b>'Hmm. . .is there something I can help you with? I am far too [busy] to listen to your problems though so I take that back.'
<p><b>You say, </b>'busy'
<br><b>Ixpacan says </b>'It is none of your concern unless you are truly gifted in the dark   art of necromancy. If so, you will have some form of proof to show me.'
<p><b>You say, </b>'wish to hear'
<p><b>You say, </b>'sages of cabilis'
<p><b>You say, </b>'collect these items'
<p><b>You give Ixpacan : </b><a href=http://phobos/eq/item.php?id=4267>Necromancer Skullcap</a>
<br><b>Ixpacan gives you : </b><a href=http://phobos/eq/item.php?id=4267>Necromancer Skullcap</a>
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<br><b>Ixpacan says </b>'Oh, I see you are truly gifted in the dark arts. Well I will explain my dilemma to you now if you [wish to hear].'
<p><b>You give Ixpacan : </b><a href=http://phobos/eq/item.php?id=48042>Ixpacan's Tome</a>
<br><b>Ixpacan says </b>'Wonderful! You have brought all of the items I have asked for. Your future seems very bright with the rest of the Sages. Step back now as I conjure the child of Charasis.'
<br><font color=green><b>Ixpacan </b>As Ixpacan starts his incantations, you can see an image begin to appear from the shadows.</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=93189>child_of_Charasis</a></b> spawns.</font>
<br><b>Ixpacan says </b>'It's out of my control! Defeat it before it destroys us both!'
<p><b>You give Ixpacan : </b><a href=http://phobos/eq/item.php?id=48044>Child of Charasis Remains</a>, <a href=http://phobos/eq/item.php?id=4267>Necromancer Skullcap</a>
<br><b>Ixpacan gives you : </b><a href=http://phobos/eq/item.php?id=4267>Necromancer Skullcap</a>
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<br><b>Ixpacan says </b>'Oh, I see you are truly gifted in the dark arts. Well I will explain my dilemma to you now if you [wish to hear].'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>