<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10604>Jeb's Seal</a><li><a href=http://phobos/eq/item.php?id=10635>A Sack For Modani</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10604>Jeb's Seal</a><li><a href=http://phobos/eq/item.php?id=17861>An Enchanters Sack</a><li><a href=http://phobos/eq/item.php?id=10610>1st Piece of Staff</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=342>True Spirit</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Modani Qu-Loni says </b>'The hidden self inside a myriad of magic is one that walks quite softly. Yes, that is what you must seek.'
<p><b>You say, </b>'ready'
<br><b>Modani Qu-Loni says </b>'Scattered throughout the world are various items. To prove your worth, go collect these and return them to me. The Xolion Rod, Innoruuk's Word, Chalice of Kings, and snow blossoms.'
<p><b>You say, </b>'chalice of kings'
<br><b>Modani Qu-Loni says </b>'The Chalice of Kings is the chalice of elven kings. Previously thought to be lost to the ages, it was recently discovered. I need its magical powers to create a magical liquid.'
<p><b>You say, </b>'xolion rod'
<br><b>Modani Qu-Loni says </b>'This is the rod of an ancient civilization found on this continent. Nothing is known of it other than that the scaled ones discovered it years ago.'
<p><b>You say, </b>'snow blossoms'
<br><b>Modani Qu-Loni says </b>'These are flowers that are also used in the creation process. They were once widespread, but now I am told they only grow in select places.'
<p><b>You say, </b>'innoruuks word'
<br><b>Modani Qu-Loni says </b>'The strict doctrine of the priests of Innoruuk is used as a material component in the crafting. The power of their hate must not be underestimated.'
<p><b>You give Modani Qu-Loni : </b><a href=http://phobos/eq/item.php?id=10604>Jeb's Seal</a>
<br><b>Modani Qu-Loni says </b>'Ah yes, Jeb's seal. The time to craft a Serpent must have come. I will need components collected to craft the first of the pieces. I will also provide you with a sack in which you must combine the items. Are you ready to collect them?'
<br><b>Modani Qu-Loni gives you : </b><a href=http://phobos/eq/item.php?id=10604>Jeb's Seal</a>
<br><b>Modani Qu-Loni gives you : </b><a href=http://phobos/eq/item.php?id=17861>An Enchanters Sack</a>
<p><b>You give Modani Qu-Loni : </b><a href=http://phobos/eq/item.php?id=10635>A Sack For Modani</a>
<br><b>Modani Qu-Loni says </b>'Excellent, you have done well. Here is the first piece of the staff. Now you must go seek out the second master; he will clear the path for you.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=342>True Spirit</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Modani Qu-Loni gives you : </b><a href=http://phobos/eq/item.php?id=10610>1st Piece of Staff</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>