<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19374>Spell: Theft of Thought</a><li><a href=http://phobos/eq/item.php?id=19378>Spell: Color Slant</a><li><a href=http://phobos/eq/item.php?id=19269>Spell: Cripple</a><li><a href=http://phobos/eq/item.php?id=19384>Spell: Dementia</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19379>Spell: Clarity II</a><li><a href=http://phobos/eq/item.php?id=19381>Spell: Recant Magic</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Siladdarae N-Riese says </b>'Hello, [Your Name]. This place is quite a formidable outpost, but it lacks the comforts of home. Once I have finished collecting some of my [missing scrolls], I'll be able to leave this place and all its hidden dangers.'
<p><b>You say, </b>'missing scrolls'
<br><b>Siladdarae N-Riese says </b>'Travelers have been bringing back numerous scrolls from the depths of darkness in the Outlands. They contain arcane knowledge specific to our classes. Only four are left that I seek. Keep a wary out for Theft of Thoughts, Color Slant, Cripple, and Dementia. Return any one of these to me and your reward shall be a scroll that can be found nowhere else.'
<p><b>You give Siladdarae N-Riese : </b><a href=http://phobos/eq/item.php?id=19374>Spell: Theft of Thought</a>
<br><b>Siladdarae N-Riese says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Siladdarae N-Riese gives you : </b><a href=http://phobos/eq/item.php?id=19379>Spell: Clarity II</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Siladdarae N-Riese : </b><a href=http://phobos/eq/item.php?id=19378>Spell: Color Slant</a>
<br><b>Siladdarae N-Riese says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Siladdarae N-Riese gives you : </b><a href=http://phobos/eq/item.php?id=19379>Spell: Clarity II</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Siladdarae N-Riese : </b><a href=http://phobos/eq/item.php?id=19269>Spell: Cripple</a>
<br><b>Siladdarae N-Riese says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Siladdarae N-Riese gives you : </b><a href=http://phobos/eq/item.php?id=19379>Spell: Clarity II</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Siladdarae N-Riese : </b><a href=http://phobos/eq/item.php?id=19384>Spell: Dementia</a>
<br><b>Siladdarae N-Riese says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Siladdarae N-Riese gives you : </b><a href=http://phobos/eq/item.php?id=19381>Spell: Recant Magic</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>