<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19351>Spell: Bristlebane`s Bundle</a><li><a href=http://phobos/eq/item.php?id=19347>Spell: Gift of Xev</a><li><a href=http://phobos/eq/item.php?id=19354>Spell: Quiver of Marr</a><li><a href=http://phobos/eq/item.php?id=19358>Spell: Scars of Sigil</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19346>Spell: Scintillation</a><li><a href=http://phobos/eq/item.php?id=19357>Spell: Vocarate: Air</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Slicia J-Singe says </b>'Why is it that you have come to this place? If you are coming here to search for [magical scrolls], just get back on that so-called ship you came here on and forget everything you thought you heard.'
<p><b>You say, </b>'magical scrolls'
<br><b>Slicia J-Singe says </b>'Is your hearing failing you!? Unless you [have something I need]. be gone!'
<p><b>You say, </b>'i have something you need'
<br><b>Slicia J-Singe says </b>'I must have the scrolls of Gift of Xev. Bristlebane's Bundle. Quiver of Marr. and the Scars of Sigil. If you don't have one of these. leave my sight!  If you do. I think we can work up a fair trade.'
<p><b>You give Slicia J-Singe : </b><a href=http://phobos/eq/item.php?id=19351>Spell: Bristlebane`s Bundle</a>
<br><b>Slicia J-Singe says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Slicia J-Singe gives you : </b><a href=http://phobos/eq/item.php?id=19346>Spell: Scintillation</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Slicia J-Singe : </b><a href=http://phobos/eq/item.php?id=19347>Spell: Gift of Xev</a>
<br><b>Slicia J-Singe says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Slicia J-Singe gives you : </b><a href=http://phobos/eq/item.php?id=19357>Spell: Vocarate: Air</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Slicia J-Singe : </b><a href=http://phobos/eq/item.php?id=19354>Spell: Quiver of Marr</a>
<br><b>Slicia J-Singe says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Slicia J-Singe gives you : </b><a href=http://phobos/eq/item.php?id=19346>Spell: Scintillation</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Slicia J-Singe : </b><a href=http://phobos/eq/item.php?id=19358>Spell: Scars of Sigil</a>
<br><b>Slicia J-Singe says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Slicia J-Singe gives you : </b><a href=http://phobos/eq/item.php?id=19357>Spell: Vocarate: Air</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>