<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12849>A Metal Key</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=14382>Dusty Tome</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Tin Banker Assistant says </b>'Insert Metal Key *whirrrr*.'
<p><b>You give Tin Banker Assistant : </b><a href=http://phobos/eq/item.php?id=12849>A Metal Key</a>
<br><b>Tin Banker Assistant says </b>'*Whirrrr*'
<br><b>Tin Banker Assistant gives you : </b><a href=http://phobos/eq/item.php?id=14382>Dusty Tome</a>
</td></tr></table>