<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19315>Spell: Atol`s Spectral Shackles</a><li><a href=http://phobos/eq/item.php?id=19322>Spell: Inferno of Al`Kabor</a><li><a href=http://phobos/eq/item.php?id=19318>Spell: Pillar of Frost</a><li><a href=http://phobos/eq/item.php?id=19319>Spell: Tears of Druzzil</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19324>Spell: Thunderbold</a><li><a href=http://phobos/eq/item.php?id=19317>Spell: Tishan`s Discord</a><li><a href=http://phobos/eq/item.php?id=19320>Spell: Abscond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Utandar Rizndown says </b>' It is good to see our numbers growing on this land.
Welcome! May your travels be as prosperous as mine have.
There are many [new powers] to be gained from this land.'
<p><b>You say, </b>'new powers'
<br><b>Utandar Rizndown says </b>' The new powers are scrolls that give us access to new and powerful spells.
My collection is almost complete. I am simply [lacking] four more and then I will return back to the homeland.'
<p><b>You say, </b>'lacking'
<br><b>Utandar Rizndown says </b>' I am missing the scroll Atol's Spectral Shackles, Tears of Druzzil, Inferno of Al'kabor, and Pillar of Frost. Should you run into one, bring it to me and I'll perform an exchange for another scroll.'
<p><b>You give Utandar Rizndown : </b><a href=http://phobos/eq/item.php?id=19315>Spell: Atol`s Spectral Shackles</a>
<br><b>Utandar Rizndown says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Utandar Rizndown gives you : </b><a href=http://phobos/eq/item.php?id=19324>Spell: Thunderbold</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Utandar Rizndown : </b><a href=http://phobos/eq/item.php?id=19322>Spell: Inferno of Al`Kabor</a>
<br><b>Utandar Rizndown says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Utandar Rizndown gives you : </b><a href=http://phobos/eq/item.php?id=19317>Spell: Tishan`s Discord</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Utandar Rizndown : </b><a href=http://phobos/eq/item.php?id=19318>Spell: Pillar of Frost</a>
<br><b>Utandar Rizndown says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Utandar Rizndown gives you : </b><a href=http://phobos/eq/item.php?id=19324>Spell: Thunderbold</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Utandar Rizndown : </b><a href=http://phobos/eq/item.php?id=19319>Spell: Tears of Druzzil</a>
<br><b>Utandar Rizndown says </b>'Here is the scroll that I promised. We have both gained much knowledge today. I hope to do business with you again soon. Farewell!'
<br><b>Utandar Rizndown gives you : </b><a href=http://phobos/eq/item.php?id=19320>Spell: Abscond</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>