<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=3457>Boiled Rockhopper Egg</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=3459>Acrylia Flakes</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Sergeant Tylah says </b>'Good day to you [Your Name], would you happen to have any boiled rockhopper eggs for sale? I'm so very hungry and they're my favorite food.'
<p><b>You give Sergeant Tylah : </b><a href=http://phobos/eq/item.php?id=3457>Boiled Rockhopper Egg</a> (x4)
<br><font color=green><b>Sergeant Tylah </b>Sergeant Tylah devours all four of the eggs in the blink of an eye, 'Delicious! May the spirits bless you [Your Name]! Here are a few acrylia flakes for your trouble. I'll be happy to pay for more should you find yourself with any extra!</font>
<br><b>Sergeant Tylah gives you : </b><a href=http://phobos/eq/item.php?id=3459>Acrylia Flakes</a>
</td></tr></table>