<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When Tolah Rakknak spawns </b>
<br><font color=grey><i>A global variable is unset at this point.</font></i>
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<br><font color=grey><i>A global variable is unset at this point.</font></i>
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<br><font color=grey><i>A global variable is unset at this point.</font></i>
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<br><font color=grey><i>A global variable is unset at this point.</font></i>
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<br><font color=grey><i>A global variable is unset at this point.</font></i>
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<br><font color=grey><i>A global variable is unset at this point.</font></i>
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<p><b>You say, </b>'Hail'
<br><b>Tolah Rakknak says </b>'Hello. [Your Name]. you may call me Tolah. Please feel free to peruse my wares. I think you'll find my prices very fair considering the risk I am taking to bring them here. If not. you can always go all the way to town to do your shopping.'
</td></tr></table>