<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20536>Mystical Lute Body</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20536>Mystical Lute Body</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>An Undead Bard says </b>'Hail, [Your Name]. Are you perchance a minstrel?'
<p><b>You say, </b>'i am a minstrel'
<br><b>An Undead Bard says </b>'I, too, am a bard, or was rather. I have been cursed by that blasted pile of bones who calls itself, Trakanon.'
<p><b>You say, </b>'who is trakanon'
<br><b>An Undead Bard says </b>'He is the undead dragon who rules this realm. I came on a quest seeking strings for my new instrument.'
<p><b>You say, </b>'what new instrument'
<br><b>An Undead Bard says </b>'I sought to create a Magical Lute.'
<p><b>You say, </b>'what magical lute'
<br><b>An Undead Bard says </b>'One that would make me the greatest bard in all the lands! Are you on a similar quest?'
<p><b>You say, </b>'i am on a similar quest'
<br><b>An Undead Bard says </b>'Excellent. I have stayed here far too long and I wish to go to my eternal slumber. But before I do so, I ask for one last request.'
<p><b>You say, </b>'what last request'
<br><b>An Undead Bard says </b>'Well then, I would ask you a favor for one in return. If I bring that cursed dragon here, will you kill it for me?'
<p><b>You say, </b>'i will kill it for you'
<br><b>An Undead Bard says </b>'Give me the Mystical Lute Body you have. I will return it, don't worry. I only wish to hold an instrument one last time before I leave.'
<hr><b>When An Undead Bard is killed </b>
<p><b>You give An Undead Bard : </b><a href=http://phobos/eq/item.php?id=20536>Mystical Lute Body</a>
<br><b>An Undead Bard says </b>'I feel so powerful once again...a strange feeling is overcoming me!'
<br><b>An Undead Bard gives you : </b><a href=http://phobos/eq/item.php?id=20536>Mystical Lute Body</a>
</td></tr></table>