<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=2692>Vampyre Ashes</a><li><a href=http://phobos/eq/item.php?id=2693>Vampyre Blood</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10015>Malachite</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=206>Magus Conlegium</a><li><a href=http://phobos/eq/faction.php?id=168>Katta Castellum Citizens</a><li><a href=http://phobos/eq/faction.php?id=350>Validus Custodus</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=284>Seru</a><li><a href=http://phobos/eq/faction.php?id=139>Hand of Seru</a><li><a href=http://phobos/eq/faction.php?id=96>Eye of Seru</a><li><a href=http://phobos/eq/faction.php?id=138>Hand Legionnaries</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Avir Sterbla says </b>'Greetings [Your Name]. I am Avir Sterbla, Governor of Magician Studies here at the Magus Conlegium of Katta Castellum. I am currently in the middle of researching more effective magical methods of combating the [vampyres] of the Coterie of the Eternal Night. Governor Drenic Garrison has been assisting me with the scientific side of the research, that having to do with physical materials that have detrimental effects on the vampyres while my research is more with magical elements.'
<p><b>You say, </b>'vampyres'
<br><b>Avir Sterbla says </b>'The vampyres are becoming a larger threat to the safety of our citizens and it is the responsibility of the Magus Conlegium to find magical ways of stifling this threat while the Validus Custodus fight them with physical means. However, I am running short on research components. I will trade for every four samples of vampyre blood or every four piles of vampyre ashes.'
<p><b>You give Avir Sterbla : </b><a href=http://phobos/eq/item.php?id=2692>Vampyre Ashes</a> x4
<br><b>Avir Sterbla says </b>'Thank you [Your Name]! These samples will be put to good use I assure you. The Coterie will not stand much longer against the forces of Katta Castellum.'
<br><b>Avir Sterbla gives you : </b><a href=http://phobos/eq/item.php?id=10015>Malachite</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=206>Magus Conlegium</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=168>Katta Castellum Citizens</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=350>Validus Custodus</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=284>Seru</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=139>Hand of Seru</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=96>Eye of Seru</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=138>Hand Legionnaries</a> has gotten worse.</font>
<p><b>You give Avir Sterbla : </b><a href=http://phobos/eq/item.php?id=2693>Vampyre Blood</a> x4
<br><b>Avir Sterbla says </b>'Thank you [Your Name]! These samples will be put to good use I assure you. The Coterie will not stand much longer against the forces of Katta Castellum.'
<br><b>Avir Sterbla gives you : </b><a href=http://phobos/eq/item.php?id=10015>Malachite</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=206>Magus Conlegium</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=168>Katta Castellum Citizens</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=350>Validus Custodus</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=284>Seru</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=139>Hand of Seru</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=96>Eye of Seru</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=138>Hand Legionnaries</a> has gotten worse.</font>
<br><b>Avir Sterbla says </b>'I can do nothing with these items, [Your Name].'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>