<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4769>Seal of Beriol</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=4770>Book of Ancient Scribings</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=153>House of Midst</a><li><a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Dersino says </b>'Hello stranger. Im very busy with my work, is there something specific you need to speak to me about?'
<p><b>You give Dersino : </b><a href=http://phobos/eq/item.php?id=4769>Seal of Beriol</a>
<br><b>Dersino says </b>'Ah, of course, my teacher Beriol needs some of these books for his research, here they are. It is a shame my studies have taken me so far from my roots. Hopefully I can return home soon and Visit my family and friends. In the mean time It was very nice to meet you and I wish you the best of luck. Please also return of you wish to deliver more books to my friend Beriol.'
<br><b>Dersino gives you : </b><a href=http://phobos/eq/item.php?id=4770>Book of Ancient Scribings</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=153>House of Midst</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>