<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19841>Note to Jarin</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=141>Haven Smugglers</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Jarin Lorean says </b>'Can't you see I'm, eh, busy here? Leave me be.'
<p><b>You say, </b>'i will deliver the goods'
<p><b>You give Jarin Lorean : </b><a href=http://phobos/eq/item.php?id=19841>Note to Jarin</a>
<br><font color=green><b>Jarin Lorean </b>glances nervously about, 'So you're here on 'official' business eh? Well, there's not much I can do right now. I have the goods but someone caught scent of what I've been doing and there are too many people watching me to leave right now. You can tell our mutual friend that he needs to wait for things to calm down or send someone else to bring back the goods.'</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=141>Haven Smugglers</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>