<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=7000>Lcea's Jewel Box</a><li><a href=http://phobos/eq/item.php?id=29860>Signet Earring of Veracity</a><li><a href=http://phobos/eq/item.php?id=7810>Head of the Inquisitor</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=29861>Sigil Earring of Veracity</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=52>Concillium Universus</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=284>Seru</a><li><a href=http://phobos/eq/faction.php?id=142>Heart of Seru</a></ul></td><td><p><b>You say, </b>'arx key'
<p><b>You give Lcea Katta : </b><a href=http://phobos/eq/item.php?id=7000>Lcea's Jewel Box</a>
<p><b>You give Lcea Katta : </b><a href=http://phobos/eq/item.php?id=29860>Signet Earring of Veracity</a>, <a href=http://phobos/eq/item.php?id=7810>Head of the Inquisitor</a>
<br><b>Lcea Katta says </b>'This is astounding, I find myself at a loss for words. You have done Katta a great justice, Sanctus Seru will never be the same now that the truth is known. Their leader has fallen.'
<br><b>Lcea Katta gives you : </b><a href=http://phobos/eq/item.php?id=29861>Sigil Earring of Veracity</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=52>Concillium Universus</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=284>Seru</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=142>Heart of Seru</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>