<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=3881>A Vial of Thick Liquid</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=3883>An Empty Poison Vial</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=350>Validus Custodus</a><li><a href=http://phobos/eq/faction.php?id=168>Katta Castellum Citizens</a><li><a href=http://phobos/eq/faction.php?id=206>Magus Conlegium</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=228>Nathyn Illuminious</a><li><a href=http://phobos/eq/faction.php?id=55>Coterie of the Eternal Night</a><li><a href=http://phobos/eq/faction.php?id=284>Seru</a><li><a href=http://phobos/eq/faction.php?id=139>Hand of Seru</a><li><a href=http://phobos/eq/faction.php?id=96>Eye of Seru</a><li><a href=http://phobos/eq/faction.php?id=138>Hand Legionnaries</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Legionnaire Erallic says </b>'Well met friend. I am sorry but I musn't converse while I am on duty.'
<p><b>You give Legionnaire Erallic : </b><a href=http://phobos/eq/item.php?id=3881>A Vial of Thick Liquid</a>
<br><b>Legionnaire Erallic says </b>'gasps silently for air and the falls completely still! No one seems to have heard you.'
<br><b>Legionnaire Erallic gives you : </b><a href=http://phobos/eq/item.php?id=3883>An Empty Poison Vial</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=350>Validus Custodus</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=168>Katta Castellum Citizens</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=206>Magus Conlegium</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=228>Nathyn Illuminious</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=55>Coterie of the Eternal Night</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=284>Seru</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=139>Hand of Seru</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=96>Eye of Seru</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=138>Hand Legionnaries</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>