<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Shara Aristos says </b>'Greetings good [Your Name]! I am Shara Aristos. Governess of History and Lore. I aid the scholars and Magistrate Salic in keeping accurate and detailed records of the history of Katta Castellum and the Combine Empire as well as organize and record lore on an abundance of topics.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>