<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4754>A Jarbled Note</a></ul></td><td><hr><b>When Terasol spawns </b>
<p><b>You say, </b>'hail'
<br><b>Terasol says </b>'Nice to meet you, [Your Name]. I have usually the finest mining supplies one can find. However, I am waiting for a shipment so please check back later.'
<p><b>You say, </b>'take the mining picks'
<p><b>You give Terasol : </b><a href=http://phobos/eq/item.php?id=4754>A Jarbled Note</a>
<br><b>Terasol says </b>'Ah, of course, you must be sent to pick up the supplies that Daesorak has been needing for his mining operation. I was wondering when that crazy Dwarf was going to come and pick these up. I imagine then that you will [take the mining picks] to Daesorak?'
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>