<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=31779>Full Fertilizer Bag</a><li><a href=http://phobos/eq/item.php?id=14936>Twilight Orchid</a><li><a href=http://phobos/eq/item.php?id=14931>Dawnflower Seeds</a><li><a href=http://phobos/eq/item.php?id=14952>Red Sands Cactus</a><li><a href=http://phobos/eq/item.php?id=14953>Letalis Zenith Vine</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17870>Empty Fertilizer Bag</a><li><a href=http://phobos/eq/item.php?id=12809>Midnight Tangelo</a><li><a href=http://phobos/eq/item.php?id=10695>Foraging Machette</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=52>Concillium Universus</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=142>Heart of Seru</a><li><a href=http://phobos/eq/faction.php?id=284>Seru</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Tobala Honeyjar says </b>'Hello, [Your Name]! I am Governess Tobala Honeyjar of Katta Castellum. Overseeing the maintenance of the [Nocturnal Gardens] is just one of my duties as the governess of agriculture and ecology.'
<p><b>You say, </b>'nocturnal gardens'
<br><b>Tobala Honeyjar says </b>'These are the Nocturnal Gardens in which we now stand. It is a collection of flora from various regions of the dark side of Luclin. It is a shame that we are not capable of supplying the nutrients necessary to maintain flora from the light side of Luclin. If you wish to assist in the maintenance of the garden I have some [tasks] you may be helpful in completing.'
<p><b>You say, </b>'tasks'
<br><b>Tobala Honeyjar says </b>'I am in need of ingredients to create more [fertilizer] and in need of a competent forager to gather some [rare plants] for me.'
<p><b>You say, </b>'fertilizer'
<br><b>Tobala Honeyjar says </b>'How humble of you to assist me with my mundane tasks! Take this bag and fill it with Three piles of Owlbear Dung, Three Piles of Fungus Compost, and Two Piles of Netherbian Nitrate.'
<br><b>Tobala Honeyjar gives you : </b><a href=http://phobos/eq/item.php?id=17870>Empty Fertilizer Bag</a>
<p><b>You say, </b>'rare plants'
<br><b>Tobala Honeyjar says </b>'I am seeking seeds and plants that I may extract the seeds from that are native to the light side of Luclin so that I am prepared should the Illuminarium Industria succeed in constructing a lantern that will provide the plants with the nutrients they need to survive here on the dark side. It would be a tremendous help if you could bring me a Twilight Orchid, Dawnflower Seeds, a Red Sands Cactus, and a Letalis Zenith Vine.'
<p><b>You give Tobala Honeyjar : </b><a href=http://phobos/eq/item.php?id=31779>Full Fertilizer Bag</a>
<br><b>Tobala Honeyjar gives you : </b><a href=http://phobos/eq/item.php?id=12809>Midnight Tangelo</a>
<br><b>Tobala Honeyjar says </b>'Oh! Thank you so much! You have saved much time and trouble! Now if only those tinkerers in the Illuminarium Industria could figure out how to get that artificial light working!'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=52>Concillium Universus</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=142>Heart of Seru</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=284>Seru</a> has gotten worse.</font>
<p><b>You give Tobala Honeyjar : </b><a href=http://phobos/eq/item.php?id=14936>Twilight Orchid</a>, <a href=http://phobos/eq/item.php?id=14931>Dawnflower Seeds</a>, <a href=http://phobos/eq/item.php?id=14952>Red Sands Cactus</a>, <a href=http://phobos/eq/item.php?id=14953>Letalis Zenith Vine</a>
<br><b>Tobala Honeyjar gives you : </b><a href=http://phobos/eq/item.php?id=10695>Foraging Machette</a>
<br><b>Tobala Honeyjar says </b>'Oh! Thank you so much! You have saved much time and trouble! Now if only those tinkerers in the Illuminarium Industria could figure out how to get that artificial light working!'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=52>Concillium Universus</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=142>Heart of Seru</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=284>Seru</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>