<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10690>Acrylian Phosphate</a><li><a href=http://phobos/eq/item.php?id=10691>Zelniak Oil</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2596>Phosphorous Torch</a><li><a href=http://phobos/eq/item.php?id=10694>Combine Fire Flasks</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=206>Magus Conlegium</a><li><a href=http://phobos/eq/faction.php?id=168>Katta Castellum Citizens</a><li><a href=http://phobos/eq/faction.php?id=350>Validus Custodus</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=37>Citizens of Seru</a><li><a href=http://phobos/eq/faction.php?id=284>Seru</a><li><a href=http://phobos/eq/faction.php?id=298>Shoulders of Seru</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Triblix Tikbok says </b>'Pleasure to meet ya! Have you come to the Illuminarium Industria to gaggle about or have you come looking for [some work]?'
<p><b>You say, </b>'some work'
<br><b>Triblix Tikbok says </b>'Well in that case I sure could use the assistance of a powerful  such as yourself. You see my job here is to construct the lighting for Katta Castellum and Im always in need of more supplies. I need a fresh supply of [zelniak oil] for the standard city street lanterns and a fresh supply of [acrylian phosphate] to construct more phosporous lanterns and torches.'
<p><b>You say, </b>'acrylian phosphate'
<br><b>Triblix Tikbok says </b>'Acrylian phosphate is an uncommon mineral deposit containing the same mineral compound that provides acrylia ore with its self luminescence. The acrylian phosphate also burns very well and at extremely high temperatures for very long periods of time. I will trade with you for every four piles of acrylian phosphate you can supply me.'
<p><b>You say, </b>'zelniak oil'
<br><b>Triblix Tikbok says </b>'Zelniaks are strange creatures that live on the light side of Luclin. Their fat can be boiled in a brew barrel with a flask of water and poured into an empty bottle to produce an oil that is an excellent fuel for lanterns. I will trade for every four bottles of zelniak oil you produce for me.'
<p><b>You give Triblix Tikbok : </b><a href=http://phobos/eq/item.php?id=10690>Acrylian Phosphate</a> x4
<br><b>Triblix Tikbok gives you : </b><a href=http://phobos/eq/item.php?id=2596>Phosphorous Torch</a>
<p><b>You give Triblix Tikbok : </b><a href=http://phobos/eq/item.php?id=10691>Zelniak Oil</a> x4
<br><b>Triblix Tikbok says </b>'Thank you [Your Name]! It would be pretty hard to see around here if we didnt keep the fires burning, it never being daytime and all.'
<br><b>Triblix Tikbok gives you : </b><a href=http://phobos/eq/item.php?id=10694>Combine Fire Flasks</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=206>Magus Conlegium</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=168>Katta Castellum Citizens</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=350>Validus Custodus</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=37>Citizens of Seru</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=284>Seru</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=298>Shoulders of Seru</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 1gp
</td></tr></table>