<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4762>Gemmed Sword Hilt</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=4762>Gemmed Sword Hilt</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Yaeorat says </b>'Ah, hello there stranger. I do not often receive visitors in my workshop, what brings you here today.'
<p><b>You give Yaeorat : </b><a href=http://phobos/eq/item.php?id=4762>Gemmed Sword Hilt</a>
<br><b>Yaeorat says </b>'Ah, a Gemmed sword hilt attached with a note from my old friend Daloran. It is a shame that I have not seen him for such a long time. Being so busy with my work has prevented me from seeing and of my family or friends, really. Alas, this hilt has a positive energy eminating from it and not destructive as Daloran feared. Please take this back to him as Im sure he awaits it.'
<br><b>Yaeorat gives you : </b><a href=http://phobos/eq/item.php?id=4762>Gemmed Sword Hilt</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>