<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10603>Copy of Notes</a><li><a href=http://phobos/eq/item.php?id=10639>A Bundle of Staves</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10604>Jeb's Seal</a><li><a href=http://phobos/eq/item.php?id=10650>Staff of the Serpent</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=342>True Spirit</a></ul></td><td><p><b>You say, </b>'are you jeb lumsed'
<br><b>a sarnak imitator says </b>'Yes, I am. Use your most enlightened magic to seek the truth of what is around you. When that is done, you will know what you seek.'
<p><b>You say, </b>'the serpent'
<br><b>a sarnak imitator says </b>'The first truly powerful enchanter, Krilan Pedin, crafted the Serpent years ago. He trained his students to carry on the trade in a five-step process. Each student then became a master and chose one of their own students to pass the legacy on to. Four others and I, myself, are current practitioners of the crafting.'
<p><b>You say, </b>'masters of enchantment'
<br><b>a sarnak imitator says </b>'The masters are enchanters who have reached the plateau of understanding. Their names are Modani Qu'Loni, Mizzle Gepple, Nadia Starfeast, and Polzin Mrid. All are master crafters in their own right.'
<p><b>You say, </b>'modani'
<br><b>a sarnak imitator says </b>'Modani is a master of illusions. You should seek him out first. Keep a careful eye out for him - he is never in his true form. The last time I spoke to him, he seemed very excited about his voyage to the elven outpost. You may or may not find more clues about his location there.'
<p><b>You say, </b>'mizzle'
<br><b>a sarnak imitator says </b>'Mizzle is a gnome who has mastered the use of enlightened magic. Go to him once you have spoken to Modani. Mizzle is not one to travel, so you should not have to look far from his home to find him.'
<p><b>You say, </b>'nadia'
<br><b>a sarnak imitator says </b>'The mistress of charm, Nadia is very beautiful. She, too, traveled with her relatives to the new land. I just recently received a letter from her. She says more and more pilgrims and explorers are arriving every day, and that the outpost is well defended now.'
<p><b>You say, </b>'polzin'
<br><b>a sarnak imitator says </b>'Master of the Phantasms - he is the last one you will seek out. Hmm...Polzin is native to Erudin, however, after the incident near Paineel, no one has heard from him. I hope that he is well.'
<p><b>You give a sarnak imitator : </b><a href=http://phobos/eq/item.php?id=10603>Copy of Notes</a>
<br><b>a sarnak imitator says </b>'I see that you have what I was waiting for. Stofo does do excellent work. It seems that you are to start on a long journey. Take this seal and it will guide you on your next step. Seek out the masters of enchantment. In time we will craft the Serpent for you. When you have collected the four parts of the staff, you must combine them in a bundle for me.'
<br><b>a sarnak imitator gives you : </b><a href=http://phobos/eq/item.php?id=10604>Jeb's Seal</a>
<p><b>You give a sarnak imitator : </b><a href=http://phobos/eq/item.php?id=10639>A Bundle of Staves</a>
<br><b>a sarnak imitator says </b>'The path you trod was long and hard. Now you are worthy to bear the Serpent. Use it well.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=342>True Spirit</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>a sarnak imitator gives you : </b><a href=http://phobos/eq/item.php?id=10650>Staff of the Serpent</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>