<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20481>Refined Ancient Sword</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20487>Swiftwind</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Faelin Bloodbriar says </b>'Didn't think I was gone for good, did you? We're that much closer to finishing this trial of our strength, thanks to you.'
<p><b>You give Faelin Bloodbriar : </b><a href=http://phobos/eq/item.php?id=20481>Refined Ancient Sword</a>
<br><font color=green><b>Faelin Bloodbriar </b>smiles at you, then closes her eyes as she sets the gem 'Nature's Balance' into the crossguard and begins to channel her spirit into the sword. The ground rumbles loudly as she casts. She collapses in exhaustion after a short time. 'Take the blade, and perhaps you can finish this. You must strike at the heart of Innoruuk's lair. Bring a shattered gem and the mithril blade to Xanuusus. Only by weakening Innoruuk's grip over his realm can the balance of the land once again be restored. If we do not meet again, [Your Name], remember you always have my eternal thanks.'</font>
<br><b>Faelin Bloodbriar gives you : </b><a href=http://phobos/eq/item.php?id=20487>Swiftwind</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Faelin Bloodbriar disappears.</b>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>