<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28056>Ornate Sea Shell</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28052>Message to Natasha</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Naxot Deepwater says </b>'Beware these woods! The sarnak claim this land as their own and wicked creatures walk beneath the burning foliage.'
<p><b>You give Naxot Deepwater : </b><a href=http://phobos/eq/item.php?id=28056>Ornate Sea Shell</a>
<br><b>Naxot Deepwater says </b>'Praise the Triumvirate! Natasha sent you just in time! Those twisted sarnak summoners are summoning Ixiblat Fer as we speak! We must stop Ixiblat Fer while he is still weak or all of Norrath may be set aflame! Please do me one more favor, should I perish to this beast of fire. Give this note to Natasha when you next see her, and if you should perish and I survive, I will make sure the waters never forget your reflections of your deeds this day.'
<br><b>Naxot Deepwater gives you : </b><a href=http://phobos/eq/item.php?id=28052>Message to Natasha</a>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=87151>Ixiblat_Fer</a></b> spawns (-2000,1500,-300).</font>
<br><b>Naxot Deepwater disappears.</b>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>