<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19956>Piece of a medallion</a><li><a href=http://phobos/eq/item.php?id=19957>Piece of a medallion</a><li><a href=http://phobos/eq/item.php?id=19958>Piece of a medallion</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19953>Medallion of the Obulus</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Slixin Klex says </b>'So long ago... The burning of our land?'
<p><b>You say, </b>'burning'
<br><b>Slixin Klex says </b>'Fiery death from the sky. Rock and fire burning our lands. Death and destruction splintering our tribe. Once, strong we were, but the fiery rocks from the sky crushed our proud cities and weakened our tribe.'
<p><b>You say, </b>'tribe'
<br><b>Slixin Klex says </b>'Obulus was our people. The hills and trees were our lands. We tamed the dark and wilds and bent the forests to our needs. But all is gone, all our people, all our works, even the medallion that was the symbol of our power.'
<p><b>You say, </b>'medallion'
<br><b>Slixin Klex says </b>'Medallion of the Obulus. Symbol of our proud people. Broken into pieces long lost to the dark forests now. I know where they are now but I am no longer flesh. If I were, I would find them and bring them back together.'
<p><b>You say, </b>'pieces'
<br><b>Slixin Klex says </b>'Hhhhh. Three pieces there are. One sits in the hands of Sselot though he knows its purpose not. Another sits upon an iksar ghost in Trakanons. The last is held by a long rotted iksar skeleton in the Dreadlands. Bring them all here and I may be able to unite them again. Perhaps this will even free me from my torment... or not.'
<p><b>You give Slixin Klex : </b><a href=http://phobos/eq/item.php?id=19957>Piece of a medallion</a>, <a href=http://phobos/eq/item.php?id=19956>Piece of a medallion</a>, <a href=http://phobos/eq/item.php?id=19958>Piece of a medallion</a>
<br><b>Slixin Klex says </b>'Ssssss. I thought I would never see these. I never thought the symbol of our people would be made whole again. I feel no rest for my sssoul though. My torment still flows as freely as when my peoples first suffered fiery death. I need this not. It is useless to me. Here, you take it. Maybe you can find some good to do with it.'
<br><b>Slixin Klex gives you : </b><a href=http://phobos/eq/item.php?id=19953>Medallion of the Obulus</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>