<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20447>Dark Metal Coin</a><li><a href=http://phobos/eq/item.php?id=20468>Warmly Glowing Stone</a><li><a href=http://phobos/eq/item.php?id=20481>Refined Ancient Sword</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20448>Worn Dark Metal Coin</a><li><a href=http://phobos/eq/item.php?id=20477>Ancient Longsword</a><li><a href=http://phobos/eq/item.php?id=20481>Refined Ancient Sword</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Telin Darkforest </b>looks at you serenely. 'Hello, wanderer.'</font>
<p><b>You say, </b>'what are you doing'
<br><b>Telin Darkforest says </b>'Mighty this place must have been, once. Now scarred by hatred and suffering. I have been sent here seeking answers to problems not yet understood.'
<p><b>You say, </b>'answers'
<br><font color=green><b>Telin Darkforest </b>considers you for a few moments before speaking. 'A great evil walks across the land. The hand of some demon we don't yet know is twisting and polluting forests.'</font>
<p><b>You say, </b>'evil'
<br><b>Telin Darkforest says </b>'If I knew that, I wouldn't be here looking for answers. I would be elsewhere, looking for solutions. For now, I suspect much but know little.'
<p><b>You say, </b>'suspect'
<br><font color=green><b>Telin Darkforest </b>looks at you and sighs. 'The lands are changing. Beasts, large and small, have turned upon those who watched over them. Druids and rangers, worshippers of both Karana and Tunare, have reported a feeling of hatred throughout their once peaceful lands.'</font>
<p><b>You say, </b>'innoruuk'
<br><font color=green><b>Telin Darkforest </b>raises his eyebrow slightly and a subtle look of surprise creeps across his face. 'Innoruuk? Perhaps. Aye. It must be. Perhaps I knew and didn't want to consider the possibility. It must be this though, and some action will have to be taken.'</font>
<p><b>You say, </b>'action'
<br><b>Telin Darkforest says </b>'You are not yet powerful enough to complete this task. Return when you have gained more experience.'
<p><b>You give Telin Darkforest : </b><a href=http://phobos/eq/item.php?id=20447>Dark Metal Coin</a>
<br><font color=green><b>Telin Darkforest </b>scratches the coin as he looks at it. 'Faelin sent you to Giz? Surprising. This coin speaks to the outcome of your talk. He would hardly give this bit of metal to a stranger, but that's a story for a different time. So, you say Giz did confirm Innoruuk's involvement, and something about undead minions? Here, take this coin back. Find Arch Druid Althele in the Karanas and show her that. Tell her what we have discussed. She will look kindly on an ally in this matter.'</font>
<br><b>Telin Darkforest gives you : </b><a href=http://phobos/eq/item.php?id=20448>Worn Dark Metal Coin</a>
<p><b>You give Telin Darkforest : </b><a href=http://phobos/eq/item.php?id=20468>Warmly Glowing Stone</a>
<br><font color=green><b>Telin Darkforest </b>nods as he unbuckles his sword and hands it to you. 'The storm callers are working on containing and fighting against the corruption but they can not hold back the inevitable for long. It is up to us to strike against Innoruuk directly. If we were warriors or paladins we would have a fancy ceremony and plenty of feasting but we're just rangers, without time for pleasantries. The sword you hold in your hands is one of the oldest blades known, even to the eldest. To strike at the darkest heart of evil requires a weapon beyond this, or even ones you may carry at your side. The first task, the first preparation you must make, is the smithing of that blade. Its edge sharpened, its balance made perfect. When you have finished, bring me this sword again.'</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Telin Darkforest gives you : </b><a href=http://phobos/eq/item.php?id=20477>Ancient Longsword</a>
<p><b>You give Telin Darkforest : </b><a href=http://phobos/eq/item.php?id=20481>Refined Ancient Sword</a>
<br><font color=green><b>Telin Darkforest </b>smiles slowly. 'Now that's fine work, [Your Name]. Just a moment, we have a friend here who can enchant one of the blades. Give her the blade that the ancient smithed.'</font>
<br><b>Telin Darkforest gives you : </b><a href=http://phobos/eq/item.php?id=20481>Refined Ancient Sword</a>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=54237>Faelin_Bloodbriar</a></b> spawns (3239,2852,-155).</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>