<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12196>Bunker Cell #1</a><li><a href=http://phobos/eq/item.php?id=16581>Bog Juice</a><li><a href=http://phobos/eq/item.php?id=13498>Edible Goo</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12143>H. K.  102</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>a prisoner says </b>'Aaaarghhh!!.. Buggl n gump.. Figgle and fump..'
<p><b>You say, </b>'Are you Ariska Zimel'
<br><font color=green><b>a prisoner </b>stares deeply into your eyes.. Very eerie!!</font>
<p><b>You give a prisoner : </b><a href=http://phobos/eq/item.php?id=12196>Bunker Cell #1</a>, <a href=http://phobos/eq/item.php?id=16581>Bog Juice</a>, <a href=http://phobos/eq/item.php?id=13498>Edible Goo</a>
<br><b>a prisoner says </b>'Bog n Goo.. Blanket too!!'
<br><b>a prisoner says </b>'Bog n Goo.. Blanket too!!'
<br><b>a prisoner says </b>'Hide, hide, safe, cee.. lerk has the clue.. Must travel.. Travel.. Travel.. Tunaria's corridor..'
<br><b>a prisoner gives you : </b><a href=http://phobos/eq/item.php?id=12143>H. K.  102</a>
</td></tr></table>