<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=9919>Pristine Giant Scarab Leg</a><li><a href=http://phobos/eq/item.php?id=9918>Greater Cat Paw</a><li><a href=http://phobos/eq/item.php?id=9923>Vial of Smoke</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Arinna Trueblade says </b>'Well met, [Your Name]. I am Arianna Trueblade, Warlord of the Steel Warriors. I am personally in charge of all the training that our young warriors receive. I take pride in knowing that my teaching can help make the foundation of a Freeport Champion. If you are a [warrior] then we might just have something to talk about.'
<p><b>You say, </b>'warrior'
<p><b>You say, </b>'ready to begin'
<p><b>You say, </b>'helm'
<p><b>You say, </b>'bracers'
<p><b>You say, </b>'armguards'
<p><b>You say, </b>'boots'
<p><b>You say, </b>'greaves'
<p><b>You say, </b>'gauntlets'
<p><b>You say, </b>'breastplates'
<p><b>You say, </b>'final task'
<p><b>You give Arinna Trueblade : </b><a href=http://phobos/eq/item.php?id=9919>Pristine Giant Scarab Leg</a>, <a href=http://phobos/eq/item.php?id=9918>Greater Cat Paw</a>, <a href=http://phobos/eq/item.php?id=9923>Vial of Smoke</a>
<br><b>Arinna Trueblade says </b>'Only members of the guild may do these quests.'
<br><b>Arinna Trueblade says </b>'Only members of the guild may do these quests.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>