<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12273>Militia Armory Token</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=3097>Reserve Militia Tunic</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a><li><a href=http://phobos/eq/faction.php?id=48>Coalition of Tradefolk Underground</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a><li><a href=http://phobos/eq/faction.php?id=258>Priests of Marr</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Armorer Dellin says </b>'Hail!! If you be a new reserve member then show me your Militia Armory Token. If you are not yet initiated then I suggest you head to the Toll Gate in the Commonlands and speak with Guard Valon.'
<p><b>You give Armorer Dellin : </b><a href=http://phobos/eq/item.php?id=12273>Militia Armory Token</a>
<br><b>Armorer Dellin says </b>'Welcome to the Freeport Militia. As a reserve member we require you to wear this tunic and fight when, who and wherever Sir Lucan commands, no questions asked!! There is no turning back!! Remember to keep clear of North Freeport. You have made a wise decision. Hail Sir Lucan!!'
<br><b>Armorer Dellin gives you : </b><a href=http://phobos/eq/item.php?id=3097>Reserve Militia Tunic</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=48>Coalition of Tradefolk Underground</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=258>Priests of Marr</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>