<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13916>Deathfist Slashed Belt</a><li><a href=http://phobos/eq/item.php?id=18742>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13572>Dirty Training Tunic*</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Cain Darkmoore says </b>'Hail. [Your Name]!  We are the Steel Warriors of Freeport.  Our training disciplines have created some of the finest warriors ever to walk upon Norrath.  Perhaps the bards shall sing songs of you one day.  Let your first mission be the extermination of [Clan Deathfist].'
<p><b>You say, </b>'Clan Deathfist'
<br><b>Cain Darkmoore says </b>'The orcs of the Commonlands call themselves Clan Deathfist.  They have committed many vile acts upon the residents of the Commonlands as well as persons traveling to and from Freeport.  They must be destroyed.  Go forth to slay them.  I shall pay a bounty for every two Deathfist belts.  If you are a true warrior of the bunker. perhaps you can begin with [the green and blue].'
<p><b>You say, </b>'the green and blue'
<br><b>Cain Darkmoore says </b>'The green and blue was a test for all skilled warriors. All one needed do was return to me four orc legionnaire shoulderpads. Two from the loathsome green skinned Deathfist Clan and two from the vile blue skinned Crushbone Clan. But we have no more bunker battle blades to spare. We must prepare for war!!'
<p><b>You say, </b>'bigger problem'
<br><b>Cain Darkmoore says </b>'The bigger problem is the Freeport Militia. Go to the Hall of Truth and speak with the Knights of Truth about that. They have already started their campaign to rid the city of the militia. The so-called Freeport Militia is not to be trusted.'
<p><b>You give Cain Darkmoore : </b><a href=http://phobos/eq/item.php?id=13916>Deathfist Slashed Belt</a> x2
<br><b>Cain Darkmoore says </b>'Very fine work [Your Name] . With your help, we shall soon rid the commonlands of the orcs. Then we can move on to a [bigger problem].'
<br><b>You receive </b> 8gp
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<p><b>You give Cain Darkmoore : </b><a href=http://phobos/eq/item.php?id=18742>A tattered note</a>
<br><b>Cain Darkmoore says </b>'Welcome to the Steel Warriors. young warrior.  It is time to prove your mettle.  Look to the outskirts of Freeport and join the fray.  Show Clan Deathfist what a warrior of the bunker can do.'
<br><b>Cain Darkmoore gives you : </b><a href=http://phobos/eq/item.php?id=13572>Dirty Training Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>