<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13916>Deathfist Slashed Belt</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Captain Hazran says </b>'Hail. [Your Name]!  We are the Militia of Freeport.  Our training disciplines have created some of the finest guards ever to walk upon Norrath.  To prove your loyalty and ability your first mission is to be the extermination of [Clan Deathfist].'
<p><b>You say, </b>'Clan Deathfist'
<br><b>Captain Hazran says </b>'The orcs of the Commonlands call themselves Clan Deathfist.  They have committed many vile acts upon the residents of the Commonlands as well as persons traveling to and from Freeport.  They must be destroyed.  Go forth to slay them.  I shall pay a bounty for every two Deathfist belts.'
<p><b>You say, </b>'bigger problem'
<br><b>Captain Hazran says </b>'The bigger problem is the Knights of Truth. We have already started our campaign to rid the city of the Knights. The so-called Knights of Truth are not to be trusted.'
<p><b>You give Captain Hazran : </b><a href=http://phobos/eq/item.php?id=13916>Deathfist Slashed Belt</a> x2
<br><b>Captain Hazran says </b>'Very fine work [Your Name] . With your help, we shall soon rid the commonlands of the orcs. Then we can move on to a [bigger problem].'
<br><b>You receive </b> 8gp
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>