<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Dooly Jonkers says </b>'Greetings. [Your Name]!  Welcome to the Academy of Arcane Science.  Nowhere on Norrath can you find a greater learning center.'
<p><b>You say, </b>'Retlon Brenclog'
<br><b>Dooly Jonkers says </b>'I'm very sorry to report that Retlon was kidnapped by some vile orcs from Crushbone. And I haven't seen him since.'
</td></tr></table>