<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1797>Reagent pouch</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=21>Bloodsabers</a><li><a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a><li><a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a><li><a href=http://phobos/eq/faction.php?id=257>Priests of Life</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Driana Poxsbourne says </b>'Hail! [Your Name], You best not be associating yourself with the likes of Najena.'
<p><b>You say, </b>'reagent'
<br><b>Driana Poxsbourne says </b>'The infamous Mage, Najena employs several apprentices. These apprentices are most likely well equiped with just the reagents I need. Perhaps you can relieve them of their burden for me? Bring me 3 pouches of reagents from the Mages and you'll have the substance.'
<p><b>You give Driana Poxsbourne : </b><a href=http://phobos/eq/item.php?id=1797>Reagent pouch</a> (x3)
<br><b>Driana Poxsbourne says </b>'Ahh wonderful work [Your Name] Here is the substance....don't spill it HAHAHAaahhahehehe...yes......you don't want to spill that heheh.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=21>Bloodsabers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=257>Priests of Life</a> has gotten worse.</font>
</td></tr></table>