<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13071>Rat Whiskers</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=48>Coalition of Tradefolk Underground</a><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a><li><a href=http://phobos/eq/faction.php?id=258>Priests of Marr</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Exterminator Qalantir says </b>'Pleased to meet you! If you are a newcomer to Freeport then you can clearly see we are having quite the rat problem. If you are interested, the militia has granted me some coin to reward those that bring me four rat whiskers.'
<p><b>You give Exterminator Qalantir : </b><a href=http://phobos/eq/item.php?id=13071>Rat Whiskers</a> x4
<br><b>Exterminator Qalantir says </b>'This is good work! I know this isn't much, but it is all I can offer you. Thanks for your help!'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=48>Coalition of Tradefolk Underground</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=258>Priests of Marr</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 1gp 1sp 1cp
</td></tr></table>