<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18013>A Note</a><li><a href=http://phobos/eq/item.php?id=14585>Odd Cold Iron Necklace</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=14585>Odd Cold Iron Necklace</a><li><a href=http://phobos/eq/item.php?id=18013>A Note</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Glyssa Sonshaw says </b>'Hail! [Your Name], welcome to the Academy of Arcane Science.'
<p><b>You give Glyssa Sonshaw : </b><a href=http://phobos/eq/item.php?id=14585>Odd Cold Iron Necklace</a>, <a href=http://phobos/eq/item.php?id=18013>A Note</a>
<br><b>Glyssa Sonshaw says </b>'You must seek out a friendly kobold in Ak'anon, Nnamed Drigaz Grumblegrowl. Give hime these and you shall be well on your way to honoring Quellious.'
<br><b>Glyssa Sonshaw gives you : </b><a href=http://phobos/eq/item.php?id=14585>Odd Cold Iron Necklace</a>
<br><b>Glyssa Sonshaw gives you : </b><a href=http://phobos/eq/item.php?id=18013>A Note</a>
</td></tr></table>