<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18817>A Sealed Letter</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18818>A tattered flier</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a><li><a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Guard Alayle says </b>'Greetings. citizen!  You should not be in the Militia House.  These are restricted grounds.  Please leave at once unless you have business here.'
<p><b>You say, </b>'truth is good'
<br><b>Guard Alayle says </b>'Ssshhh!! Pipe down. The others might hear you. You must have something for me. Kalatrina must have given you something if you serve the Hall of Truth. If you have nothing please leave. You will blow my cover.'
<p><b>You give Guard Alayle : </b><a href=http://phobos/eq/item.php?id=18817>A Sealed Letter</a>
<br><b>Guard Alayle says </b>'This is not good news. I must leave immediately. Here. Take this to Kala.. I mean my father. I found it on the floor of Sir Lucan DLeres quarters. Thanks again, messenger. I got this just in time.'
<br><b>Guard Alayle gives you : </b><a href=http://phobos/eq/item.php?id=18818>A tattered flier</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
</td></tr></table>