<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13863>A Locked Book</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=11>Arcane Scientists</a><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Hemia Skemner says </b>'How are you? Welcome to the Academy of Arcane Science. Please feel free to roam. May knowledge be your goal. Be you a [fellow scientist] or visitor, I am sure you will find whatever you seek.'
<p><b>You say, </b>'fellow scientist'
<br><b>Hemia Skemner says </b>'That is good. I hope you can handle the knowledge of arcane science. Some have gone mad conducting research. Such a person is [Lydl Mastat].'
<p><b>You say, </b>'Lydl Mastat'
<br><b>Hemia Skemner says </b>'Lydl Mastat is nothing more than a young apprentice of mine. He went mad working on a formula for deep water breathing. He now roams the outskirts of Freeport boasting of power he does not have. Someone should [teach Lydl a lesson].'
<p><b>You say, </b>'teach Lydl a lesson'
<br><b>Hemia Skemner says </b>'Then go. He appears near the gates of Freeport from time to time. He is not powerful, but he has a secret. Nothing save magic can harm him. This was the result of an experimental potion he drank. Slay him and return his locked spellbook to me.'
<p><b>You give Hemia Skemner : </b><a href=http://phobos/eq/item.php?id=13863>A Locked Book</a>
<br><b>Hemia Skemner says </b>'You have done the world of magic a great justice, [Your Name].'
<br><b>You receive </b> 9gp 9sp 9cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=11>Arcane Scientists</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten worse.</font>
</td></tr></table>