<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18201>A Note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18200>A Note</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Janam Rekish says </b>'Ah. hello there. friend!  Me an' Rebby here. we're a just couple o' regular merchants.  Though we've got nothin' to sell right now. we'd gladly take any donations.  Them's the breaks. I suppose.'
<p><b>You give Janam Rekish : </b><a href=http://phobos/eq/item.php?id=18201>A Note</a>
<br><font color=green><b>Janam Rekish </b> scribbles out a note and says </font>
<br><b>Janam Rekish gives you : </b><a href=http://phobos/eq/item.php?id=18200>A Note</a>
<br><b>Janam Rekish says </b>'Please make sure that Harkin Duskfoot gets this right away...
if you lose it . it could mean both of our heads. '
<br><b>Janam Rekish says </b>'Thanks for the donations [Your Name].'
</td></tr></table>