<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=29008>bucket of water</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=29009>bucket of pure water</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Joshua says </b>'Welcome to freeport [Your Name].'
<p><b>You give Joshua : </b><a href=http://phobos/eq/item.php?id=29008>bucket of water</a>
<br><font color=green><b>Joshua </b>Joshua dips his emaciated hand into the bucket and brings the water to his mouth. As he does, you hear a soft thump from outside and notice that through the window his sister has collapsed. A glimmer enfolds her body, and you notice the water in Joshua's hand gleam a pure, bright light for a moment. 'Thank you, sir. I hope my sister returns soon. I feel better for some reason.</font>
<br><b>Joshua gives you : </b><a href=http://phobos/eq/item.php?id=29009>bucket of pure water</a>
</td></tr></table>