<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Jyle Windshot says </b>'Greeting friend!! Nice to meet you. I see you enjoy barging into other peoples rooms. No problem. I enjoy the company. What are you looking for?'
<p><b>You say, </b>'treant wood'
<br><b>Jyle Windshot says </b>'You are a new courier from the Faydarks. I am sorry I did not stay closer to the docks. I hear that part of Freeport is dangerous and is filled with many rogues. I shall require a new Small Lantern in trade for the Treant Wood.'
<br><b>Jyle Windshot says </b>'You have no business giving me this junk.'
</td></tr></table>