<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When Krazen Loosh spawns </b>
<br><b>Krazen Loosh says </b>'Hello, Alayle. We just got a message from Qeynos. I think you should come with me.'
<br><b>Krazen Loosh says </b>'As you try to open penetrate the stone wall it is clearly being held in place by a powerful force.'
<p><b>You say, </b>'Hail'
<br><b>Krazen Loosh says </b>'The towering wall of stone is clearly unmovable at this point, being held in place by collection of magical energies.'
</td></tr></table>