<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12241>Raw Short Sword 1</a><li><a href=http://phobos/eq/item.php?id=12242>Raw Short Sword 2</a><li><a href=http://phobos/eq/item.php?id=12243>Raw Short Sword 3</a><li><a href=http://phobos/eq/item.php?id=12244>Raw Short Sword 4</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1717>Sealed Letter</a><li><a href=http://phobos/eq/item.php?id=5418>Groflah's Stoutbite</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Larn Brugal says </b>'Good day to you [Your Name] ! I hope you yearn to become a Steel Warrior as we all are here in the Bunker. We are in need of more recruits to continue the [war].'
<p><b>You say, </b>'war'
<br><b>Larn Brugal says </b>'The war I speak of is the one we Steel Warriors have sworn to wage agianst [Clan Deathfist] in the Commonlands. We are doing a fine job but we require more weapons. We are expecting a shipment of blades from Groflahs Forge. We require a warrior of the bunker to [get our shipment]. Maybe you.'
<p><b>You say, </b>'Clan Deathfist'
<br><b>Larn Brugal says </b>'If you do not know of Clan Deathfist go ask Cain who they are. He will not only tell you he will sign you up to help fight our war!'
<p><b>You say, </b>'get our shipment'
<br><b>Larn Brugal says </b>'We would be most thankful for your service. Please take this voucher over to Groflah at Groflahs Forge in North Freeport. He will give you the shipment of weapons.'
<br><b>Larn Brugal gives you : </b><a href=http://phobos/eq/item.php?id=1717>Sealed Letter</a>
<p><b>You give Larn Brugal : </b><a href=http://phobos/eq/item.php?id=12241>Raw Short Sword 1</a>, <a href=http://phobos/eq/item.php?id=12242>Raw Short Sword 2</a>, <a href=http://phobos/eq/item.php?id=12243>Raw Short Sword 3</a>, <a href=http://phobos/eq/item.php?id=12244>Raw Short Sword 4</a>
<br><b>Larn Brugal says </b>'I heard you were on your way back. Here then. Let us sharpen that blade for you. There you are. That should be much better in a fray now.'
<br><b>Larn Brugal gives you : </b><a href=http://phobos/eq/item.php?id=5418>Groflah's Stoutbite</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>