<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Lorme Tredore says </b>'Hello [Your Name]. If you are new here you might have a note for me.'
<br><font color=green><b>Lorme Tredore </b> mumbles under his breath - Now where did I lose that Fleshy Orb.</font>
<br><b>Lorme Tredore says </b>'Only Casters may earn the rewards of the Academy!'
</td></tr></table>