<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13860>A Strongbox</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=11>Arcane Scientists</a><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Nusk Treton says </b>'Freeport!!  Great trade city of Norrath!!  What a wondrous place!  How do you do?  You are an [arcane scientist]. are you not?'
<p><b>You say, </b>'arcane scientist'
<br><b>Nusk Treton says </b>'Grand!! I remember my younger days within this great academy. I have spent many years of research here in Freeport. I compiled a [locked journal] of my research. Alas, I still am awaiting it's return.'
<p><b>You say, </b>'locked journal'
<br><b>Nusk Treton says </b>'I lent it to an old colleague of mine in Ak'Anon. He was to send it back aboard a private vessel. A Lenka Stoutheart was to return it to me. It has been one month and counting. I wish there was a young wizard who could [seek out Lenka]. '
<p><b>You say, </b>'seek out Lenka'
<br><b>Nusk Treton says </b>'What luck!! I would be most appreciative if you could find Lenka Stoutheart in Freeport and inquire where the Journal Strongbox would be. I do so look forward to it's return.'
<p><b>You give Nusk Treton : </b><a href=http://phobos/eq/item.php?id=13860>A Strongbox</a>
<br><b>Nusk Treton says </b>'Grand and fantastic!! You have made my day complete. Here is what little I can offer. Most of my money goes into my research. Thank you. '
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=11>Arcane Scientists</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten worse.</font>
<br><b>You receive </b> 10sp 2cp
</td></tr></table>