<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Palon Deskeb says </b>'Pleased to meet you. [Your Name]. Have you seen how clear the water is underneath the Academy? All sorts of life could flourish there. What a shame there are no [Marr Minnows] there.'
<p><b>You say, </b>'What Marr Minnows?'
<br><b>Palon Deskeb says </b>'The Marr Minnow swims in the pond near the Temple of Marr. I wish I had one. Not a dead one. A live one. I need someone to [get the minnow].'
<p><b>You say, </b>'get the minnow'
<br><b>Palon Deskeb says </b>''Please try. Here you are. Take this jar. Offer the jar to the minnows. Maybe they will swim into it.'
</td></tr></table>