<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=29008>bucket of water</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>peasant woman </b>grunts as she tries to fill two buckets of [water]. Her frail arms strain at her work and pain fills her eyes with tears.</font>
<p><b>You say, </b>'Water'
<br><b>peasant woman says </b>'Aye, water, m'lord. For my brother. He is very sick. He's needin' drink. He's burnin' up. I am sick myself but still able to move, a little. I must [take this water to him] before he gets worse.'
<p><b>You say, </b>'take this water to him'
<br><b>peasant woman says </b>'Aye, water, m'lord. For my brother. He is very sick. He's needin' drink. He's burnin' up. I am sick myself but still able to move, a little. I must [take this water to him] before he gets worse.'
<br><b>peasant woman says </b>'Surely you are a pure soul. If you would take this bucket of water to my brother, I would be forever grateful. I am just so tired, I need to rest... She slumps to the floor and begins to breathe shallowly, in short, harsh gasps.'
<br><b>peasant woman gives you : </b><a href=http://phobos/eq/item.php?id=29008>bucket of water</a>
</td></tr></table>