<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=MISSING></a><li><a href=http://phobos/eq/item.php?id=12337>A Tattered Toupee</a><li><a href=http://phobos/eq/item.php?id=6710>Full Gem Bag</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17512>Empty Gem Bag</a><li><a href=http://phobos/eq/item.php?id=17080>Gem Encrusted Casket</a></ul></td><td><p><b>You say, </b>'coffin'
<br><b>Ping Fuzzlecutter says </b>'You're looking for a craftsman, are you? Well look no further! For I, Ping Fizzlecutter, am the best in all the lands! Or at lest this side of Freeport. So you're the one that Valeron was talking about, eh? Well, while you were off traipsing around the lands he and I discussed the details of the coffin. I require nothing less than these [components]. Get me them and I will gladly make you a coffin any king would be proud to be buried in!'
<p><b>You say, </b>'components'
<br><b>Ping Fuzzlecutter says </b>'I require a diamond, a star ruby, a pearl, a [special fire emerald], a sapphire, a fire opal, and two enchanted platinum bars. Take this bag and combine the items once you have them all and bring it back to me.'
<br><b>Ping Fuzzlecutter gives you : </b><a href=http://phobos/eq/item.php?id=17512>Empty Gem Bag</a>
<p><b>You say, </b>'special fire emerald'
<br><b>Ping Fuzzlecutter says </b>'Now the fire emerald I want is not the normal one you receive from most jewelers. There is one jeweler I know who has the special one I want. Last time I heard, she had traveled to the elven outpost. Just ask her about special fire emeralds.'
<p><b>You say, </b>'You can repair the toupee'
<br><b>Ping Fuzzlecutter says </b>'Ah!! You have a toupee to repair. It must be the [Mane Attraction]. I gave a one out and it seems to always fall to pieces. Seeing as it has a 100 season warranty and I only created it 5 seasons ago, I suppose I can do it. Do you want me to [make the Mane Attraction].'
<p><b>You say, </b>'Mane Attraction'
<br><b>Ping Fuzzlecutter says </b>'The Mane Attraction is a special toupee I created for a Gnome junker. He wasn't getting much attention at the taverns till I created the eye catching toupee. He became one Charismatic Gnome after that. Unfortunately, it seems to fall to pieces to easy and since it has a warranty, I have to fix it for him every time at no charge!! I will never make another. '
<p><b>You say, </b>'make the Mane Attraction'
<br><b>Ping Fuzzlecutter says </b>'The Mane Attraction is a special toupee I created for a Gnome junker. He wasn't getting much attention at the taverns till I created the eye catching toupee. He became one Charismatic Gnome after that. Unfortunately, it seems to fall to pieces to easy and since it has a warranty, I have to fix it for him every time at no charge!! I will never make another. '
<br><b>Ping Fuzzlecutter says </b>'If you have the original tattered toupee then I can do it. Before you give it to me I will also need three other items. I require two clumps of hair from a Hulking Gorilla and a strand of hair from a [certain mermaid].'
<p><b>You say, </b>'certain mermaid'
<br><b>Ping Fuzzlecutter says </b>'I encountered a particular mermaid with beautiful hair!! She had beautiful golden tresses. I used a lock of her hair to create the Mane Attraction. That was a while back when I was in Faydwer.'
<p><b>You give Ping Fuzzlecutter : </b><a href=http://phobos/eq/item.php?id=12337>A Tattered Toupee</a>, <a href=http://phobos/eq/item.php?id=MISSING></a>
<p><b>You give Ping Fuzzlecutter : </b><a href=http://phobos/eq/item.php?id=6710>Full Gem Bag</a>
<br><font color=green><b>Ping Fuzzlecutter </b>smiles broadly as he rifles through the bag, then looks up at you and says, 'Bout time! Here is the coffin as promised.'</font>
<br><b>Ping Fuzzlecutter gives you : </b><a href=http://phobos/eq/item.php?id=17080>Gem Encrusted Casket</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>