<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=26644>A Sealed Letter</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=26644>A Sealed Letter</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Plagus Ladeson says </b>'Greetings [Your Name], and welcome to the Bunker. Are you a [new warrior] or [veteran]?'
<p><b>You say, </b>'new warrior'
<br><b>Plagus Ladeson says </b>'Good to know you chose the Bunker to train you. It is the home of The Steel Warriors. We find our inner strengths grow through battles and deeds to further our growth. Do you [seek deeds] or [crave battle] ?'
<p><b>You say, </b>'seek deeds'
<br><b>Plagus Ladeson says </b>'It may not be a fray, but who said all we Steel Warriors are nothing more than brawn. There has been recent reports of frequent visits by Dark Elves to the Hog Caller's Inn, here in Freeport. Go speak with Lady Shae. Tell her, the [Steel Warriors sent you]. We cannot rely on the Freeport Militia to look into such matters. They are probably involved. Bring me any clues.'
<p><b>You say, </b>'I am veteran'
<br><b>Plagus Ladeson says </b>'I apologize for not knowing. I am new to the Bunker. I was a trainer at the Hall of Steel in Qeynos before this.I left Qeynos in search of [Milea] and instead found myself joining the Bunker's weapons masters.'
<p><b>You say, </b>'Milea'
<br><b>Plagus Ladeson says </b>'Milea Clothspinner. She was my one true love. She is a Steel Warrior also. When she left Qeynos to find adventure my heart left also. I never saw her again, but I decided to transfer my skills to Freeport. It is probably best I did not find her. She was in love with adventure. Sigh !! The women I am attracted to are always in love with another. Just like [Toala].'
<p><b>You say, </b>'Toala'
<br><b>Plagus Ladeson says </b>'Toala is supreme when it comes to the blade, but in the art of passion she chooses to sway towards Cain Darkmoore. I do not get it. She is a very beautiful and strong hearted warrior. That Cain does not like her is a mystery to me. Why does she waste her time when she could have me. After all, we men of Qeynos are known as the most romantic in all of Norrath.'
<p><b>You say, </b>'Milea is in East Karana'
<br><b>Plagus Ladeson says </b>'Milea Clothspinner. She was my one true love. She is a Steel Warrior also. When she left Qeynos to find adventure my heart left also. I never saw her again, but I decided to transfer my skills to Freeport. It is probably best I did not find her. She was in love with adventure. Sigh !! The women I am attracted to are always in love with another. Just like [Toala].'
<br><b>Plagus Ladeson says </b>'You have seen Milea Clothspinner!! This is great news. I wish I could travel to see her, but Cain will not allow me to do so at this time. You must take her a note for me. Here. Take this to her. I as a master in this order command you to do so immediately. Go!!'
<p><b>You give Plagus Ladeson : </b><a href=http://phobos/eq/item.php?id=26644>A Sealed Letter</a>
<br><b>Plagus Ladeson says </b>'Oh my! Opal? She is providing these agents of Neriak with information regarding the Acedemy's secrets. I can not tell Cain about this. He will be furious. Show this to Toala. She will know what to do. '
<br><b>Plagus Ladeson gives you : </b><a href=http://phobos/eq/item.php?id=26644>A Sealed Letter</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>