<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18746>A tattered note</a><li><a href=http://phobos/eq/item.php?id=28055>Tattered Parchment</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12369>Puab's Token</a><li><a href=http://phobos/eq/item.php?id=13507>Torn Cloth Tunic*</a><li><a href=http://phobos/eq/item.php?id=12344>Treant Fists</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=12>Ashen Order</a><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a><li><a href=http://phobos/eq/faction.php?id=300>Silent Fist Clan</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Puab Closk says </b>'Greetings. I am Puab Closk, Master of the Ashen Order.  Our home is your home, friend. Feel free to stay as long as you like.  Learn our ways as many have done in the past.  To fight like the tiger and strike like the cobra are your goals. Cough- [treant fist] -Cough!'
<p><b>You say, </b>'treant fist'
<br><b>Puab Closk says </b>'I have these items, and will gift them to any [monk of great skill]'
<p><b>You say, </b>'monk of great skill'
<br><b>Puab Closk says </b>'Then you shall aid our family. My former pupil [Clawfist] has been banished by his people. You will go to him and hand him this token as proof of your origin. He shall be expecting you.'
<br><b>Puab Closk gives you : </b><a href=http://phobos/eq/item.php?id=12369>Puab's Token</a>
<p><b>You say, </b>'Clawfist'
<br><b>Puab Closk says </b>'Clawfist is a Kerran, a catman. He braved the dangers of Norrath to reach the Ashen Order. He sought knowledge of our disiples. He learned well.'
<p><b>You say, </b>'Where is Clawfist'
<br><b>Puab Closk says </b>'Clawfist is a Kerran, a catman. He braved the dangers of Norrath to reach the Ashen Order. He sought knowledge of our disiples. He learned well.'
<br><b>Puab Closk says </b>'Clawfist has been banished by the Kerrans of Odus. Where they have sent him I am unsure'
<p><b>You give Puab Closk : </b><a href=http://phobos/eq/item.php?id=18746>A tattered note</a>
<br><b>Puab Closk says </b>'Welcome to the Order'
<br><b>Puab Closk gives you : </b><a href=http://phobos/eq/item.php?id=13507>Torn Cloth Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Puab Closk : </b><a href=http://phobos/eq/item.php?id=28055>Tattered Parchment</a>
<br><b>Puab Closk says </b>'You have performed a great service to one who is your brother. Your loyalty shines brightly, as does your skill. Take the treant fists. They are yours now.'
<br><b>Puab Closk gives you : </b><a href=http://phobos/eq/item.php?id=12344>Treant Fists</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=12>Ashen Order</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=300>Silent Fist Clan</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>