<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18923>Message to Rebby</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13158>Rebby's Rat Whiskers</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Rebby Willend says </b>'Hey friend. nice wallet ya got there.  Bet it's fulla money. huh?  Why don't ya let me take a quick look. huh?'
<p><b>You give Rebby Willend : </b><a href=http://phobos/eq/item.php?id=18923>Message to Rebby</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Rebby Willend gives you : </b><a href=http://phobos/eq/item.php?id=13158>Rebby's Rat Whiskers</a>
</td></tr></table>