<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18741>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13560>Old Violet Robe*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Romiak Jusathorn says </b>'Squawk! Er.. I mean - Hello!'
<p><b>You give Romiak Jusathorn : </b><a href=http://phobos/eq/item.php?id=18741>A tattered note</a>
<br><b>Romiak Jusathorn says </b>'Thanks.'
<br><b>Romiak Jusathorn gives you : </b><a href=http://phobos/eq/item.php?id=13560>Old Violet Robe*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>