<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Shintl Lowbrew says </b>'Hail. mighty one! What are you doing in the city?  You should be out slaying beasts. There is nothing to find here in the city.'
<p><b>You say, </b>'Who is Hollish'
<br><b>Shintl Lowbrew says </b>'I have never heard of this Hollish character you speak of. You must be mistaking me for someone else.'
<p><b>You say, </b>'Who is Opal'
<br><b>Shintl Lowbrew says </b>'Opal is just a friend I have here in Freeport. She works at the Academy of Arcane Science.'
<hr><b>When Shintl Lowbrew is killed </b>
<br><b>Shintl Lowbrew says </b>'You have no idea what a big mistake you made. Either my fellow rogues shall find you or the Freeport Mi.. Unnnghh'
</td></tr></table>