<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Sir Lucan D-Lere says </b>'Hail. citizen!  I am very busy. I do not have time to speak with you.  If you have any complaints. please direct them to City Hall.  Unless. of course. you have some personal business in which I might be interested.'
<hr><b>When Sir Lucan D-Lere is killed </b>
<br><b>Sir Lucan D-Lere says </b>'You shall never get my testimony. I shall fight you from the grave!! Ha Ha Ha!! You cannot stop the undead!! Foolish mortal!! Your foul deeds have earned my contempt. '
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=9147>Sir_Lucan_DLere</a></b> spawns.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>