<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12147>Hog Key # 2</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=26644>A Sealed Letter</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=47>Coalition of Trade Folk</a><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a><li><a href=http://phobos/eq/faction.php?id=217>Merchants of Qeynos</a><li><a href=http://phobos/eq/faction.php?id=369>Coalition of TradeFolk III</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Swin Blackeye says </b>'Greetings, friend! Welcome to the Hog Caller's Inn! Don't let the name fool you.  We are the finest establishment in Freeport. Please feel free to relax in our lounge. There is usually music to soothe your blues away.'
<p><b>You say, </b>'need the mail for room two'
<br><b>Swin Blackeye says </b>'Hmmph !! If you're here to get the mail for room two you first need to show me the room key.'
<p><b>You give Swin Blackeye : </b><a href=http://phobos/eq/item.php?id=12147>Hog Key # 2</a>
<br><b>Swin Blackeye says </b>'Here you go then.'
<br><b>Swin Blackeye gives you : </b><a href=http://phobos/eq/item.php?id=26644>A Sealed Letter</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=47>Coalition of Trade Folk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=217>Merchants of Qeynos</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=369>Coalition of TradeFolk III</a> has gotten better.</font>
</td></tr></table>