<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13845>Illegible Cantrip</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=11>Arcane Scientists</a><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Tara Neklene says </b>'It is always a pleasure to meet a new face. We have many who travel far and wide to visit our great academy. Many who brave the long trip by boat. Many who dare to cross the territory of the [Deathfist orcs].'
<p><b>You say, </b>'deathfist orcs'
<br><b>Tara Neklene says </b>'The Deathfist are a clan of orcs. They are not very powerful. yet I hear they dabble in the circles of magic. Their skills in the ways of magic are limited. It is my duty to study them.  I shall pay for your services. Will you [assist with the research]?'
<p><b>You say, </b>'assist with the research'
<br><b>Tara Neklene says </b>'Yes. You will do. Go into the lands which surround Freeport. There you shall encounter Deathfist apprentices. They are as young as yourself and each should carry an orc cantrip. Return one for further studies.  Do so and you will earn your pay as well as our respect.'
<p><b>You say, </b>'test the might of the orc oracles'
<br><b>Tara Neklene says </b>'The word of mouth in the Academy of Arcane Science is that you are no foe, but you have yet to prove your worth to us. Perform more tasks for the great Tara Neklene.'
<p><b>You give Tara Neklene : </b><a href=http://phobos/eq/item.php?id=13845>Illegible Cantrip</a>
<br><b>Tara Neklene says </b>'Very fine work, my young apprentice. This shall be very useful in understanding their ways. I have heard rumors of a scribe who can decipher these scrolls. He is said to frequent the local taverns. Bah!! If I cannot decipher them, no one can!! Continue with your work. Soon you shall advance enough to [test the might of the orc oracles].'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 12sp 3cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=11>Arcane Scientists</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten worse.</font>
</td></tr></table>