<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17590>Warded Satchel</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Taxonomist Darwin Grisk says </b>'Have you come to [help]? If not, be gone! I will not have my time wasted.'
<p><b>You say, </b>'Help'
<br><b>Taxonomist Darwin Grisk says </b>'Recently rumors have surfaced that a new race, the Luggalds, walks the land. I suspect that some evil force is involved in their appearance. Are you [willing] to risk unknown dangers to help me find out?'
<p><b>You say, </b>'willing'
<br><b>Taxonomist Darwin Grisk says </b>'Good. I have not been able to confirm the existence of these beings. I will need definite proof if the rest of the members of the Academy are to believe me. Take this Warded Satchel and retrieve three examples of Luggald Flesh.'
<br><b>Taxonomist Darwin Grisk gives you : </b><a href=http://phobos/eq/item.php?id=17590>Warded Satchel</a>
</td></tr></table>