<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13814>L.S. Pouch</a><li><a href=http://phobos/eq/item.php?id=26644>A Sealed Letter</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13923>Moggok's Right Eye</a><li><a href=http://phobos/eq/item.php?id=17971>Toala's Box for heads</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=361>Wolves of the North</a><li><a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a><li><a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a><li><a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=275>Rogues of the White Rose</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Toala Nehron says </b>'I am Toala Nehron. You must be A another Young warrior aspiring to join the ranks of the Steel Warriors. We welcome all who should try. When you [have time] there is A friend of mine I would like you to check on.'
<p><b>You say, </b>'have time'
<br><b>Toala Nehron says </b>'I have A friend by the name of [Lenka Stoutheart]. She reported to me that her ship was broken into and someone stold A pouch of hers. Could you go look into it for me. Just tell her Toala sent you . Oh... And pay No mind to the walking mountain by her. That will only be Bronto her navigator. Thanks friend.'
<p><b>You say, </b>'Lenka Stoutheart'
<br><b>Toala Nehron says </b>'Lenka Stoutheart is an old friend of mine. I trained with her in my younger days when the Steel Warriors sent me to train in the ways of the Wolves of the North, the barbarian warriors of Halas. She is now an adventurer of great sorts. She travels from continent to continent aboard the Blue Beast, her ship. The Last time I had heard from her she was docked in East Karana.'
<p><b>You give Toala Nehron : </b><a href=http://phobos/eq/item.php?id=13814>L.S. Pouch</a>
<br><b>Toala Nehron says </b>'You found my pouch! Thanks kid. Let me buy you A drink and this is for the good work. Hmmmm. It looks as though they took my voucher. Darn it! Hey... It looks like they were using my bag to hold items they were stealing. Here you go. You can have it. It looks like junk. '
<br><font color=yellow>You gain experience!!</font>
<br><b>Toala Nehron gives you : </b><a href=http://phobos/eq/item.php?id=13923>Moggok's Right Eye</a>
<br><b>You receive </b> 2sp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=361>Wolves of the North</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=275>Rogues of the White Rose</a> has gotten worse.</font>
<p><b>You give Toala Nehron : </b><a href=http://phobos/eq/item.php?id=26644>A Sealed Letter</a>
<br><b>Toala Nehron says </b>'Why, that little trollop! What is she up to? Cain will never believe this! She must be in league with some faction of the dark elves, but why? Neither the Academy of Arcane Science nor Cain will believe this note. I will see what I can do. As for you, I command you to kill this Shintl and her dark elf courier Hollish!! Put their heads into this box and combine them. We shall cut the link. Bring me thier heads.'
<br><b>Toala Nehron gives you : </b><a href=http://phobos/eq/item.php?id=17971>Toala's Box for heads</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>