<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=14017>A Snake Venom Sac</a><li><a href=http://phobos/eq/item.php?id=12353>A Sparkling Sapphire</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12351>A Tiny Key</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Toxdil says </b>'Correct. Toxdil is my name. No last name. I swear allegiance to no house nor guild. What brings you down here? Perhaps you seek my [deadly liquid], perhaps not. Whatever your reasons, I warn you to keep an eye out for the militia. They have begun to patrol the sewers.'
<p><b>You say, </b>'deadly liquid'
<p><b>You say, </b>'gems'
<p><b>You say, </b>'gem case'
<p><b>You give Toxdil : </b><a href=http://phobos/eq/item.php?id=14017>A Snake Venom Sac</a> (x2)
<p><b>You give Toxdil : </b><a href=http://phobos/eq/item.php?id=12353>A Sparkling Sapphire</a>
<br><b>Toxdil says </b>'The gem!! I would notice it's sparkle anywhere!! I cannot believe you are handing it back to me!! What a fool. Here you are fool. You can have this worthless key now.'
<br><b>Toxdil gives you : </b><a href=http://phobos/eq/item.php?id=12351>A Tiny Key</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>