<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=29803>A Shield Repair Order</a><li><a href=http://phobos/eq/item.php?id=29808>Jasir's Immaculate Shield</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=29807>Jasir's Dented Shield</a><li><a href=http://phobos/eq/item.php?id=29809>Jasir's work order</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>#Khala Dun Jasir says </b>'Welcome to North Gate side of the Merchant's Corridor.'
<p><b>You give #Khala Dun Jasir : </b><a href=http://phobos/eq/item.php?id=29803>A Shield Repair Order</a>
<br><b>#Khala Dun Jasir says </b>'Well it's about time Barkhem got around to us, and he couldn't even be bothered to come himself. Please get this back to me as soon as you can... you do know that we are here to guard the city, right?'
<br><b>#Khala Dun Jasir gives you : </b><a href=http://phobos/eq/item.php?id=29807>Jasir's Dented Shield</a>
<p><b>You give #Khala Dun Jasir : </b><a href=http://phobos/eq/item.php?id=29808>Jasir's Immaculate Shield</a>
<br><b>#Khala Dun Jasir says </b>'Thank you very much [Your Name], and I must apologize for the way I spoke to you earlier. We just got word of some [poachers] out in the Thicket, they really get me angry. In any case, you have done a fine job, worthy of Barkhem himself.'
<br><b>#Khala Dun Jasir gives you : </b><a href=http://phobos/eq/item.php?id=29809>Jasir's work order</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>