<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=29803>A Shield Repair Order</a><li><a href=http://phobos/eq/item.php?id=29805>Koby's Immaculate Shield</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=29804>Koby's Dented Shield</a><li><a href=http://phobos/eq/item.php?id=29806>Koby's work order</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>#Khala Dun Koby says </b>'And hello to you traveler. Beyond this gate lies the Shadeweavers Thicket. You had best go armed. for the [Claw Beasts] have been attacking merchants regularly.'
<p><b>You say, </b>'what claw beasts?'
<br><b>#Khala Dun Koby says </b>'A true horror. they are mindless predators and quite large to boot. These beasts have massive razor sharp teeth that can rip your arm off cleanly.'
<p><b>You give #Khala Dun Koby : </b><a href=http://phobos/eq/item.php?id=29803>A Shield Repair Order</a>
<br><b>#Khala Dun Koby says </b>'Oh this old shield does fine, but I guess if Barkhem needs to break in a new apprentice, it does have some dings in it. Thank you, my friend.'
<br><b>#Khala Dun Koby gives you : </b><a href=http://phobos/eq/item.php?id=29804>Koby's Dented Shield</a>
<p><b>You give #Khala Dun Koby : </b><a href=http://phobos/eq/item.php?id=29805>Koby's Immaculate Shield</a>
<br><b>#Khala Dun Koby says </b>'Tip-top work! Barkhem has done well by himself choosing you for an apprentice.'
<br><b>#Khala Dun Koby gives you : </b><a href=http://phobos/eq/item.php?id=29806>Koby's work order</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>