<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10390>Worm Meat</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=30580>Wooden Practice Dagger</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Cook Yalkiin says </b>'Welcome to our kitchen! As you can tell we stay pretty busy in here.  There are a lot of people to feed and a vast number of delicious meals to feed them.  I'm in charge of preparing stews. broth. and vegetables.  If you ever have any questions about those areas. please let me know.'
<p><b>You give Cook Yalkiin : </b><a href=http://phobos/eq/item.php?id=10390>Worm Meat</a> (x4)
<br><b>Cook Yalkiin gives you : </b><a href=http://phobos/eq/item.php?id=30580>Wooden Practice Dagger</a>
<br><b>You receive </b> 2sp 3cp
</td></tr></table>