<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Dharr Nadim says </b>'Step up. step up! Please take a moment to purchase some supplies from me.  Times are hard and my [luck] has been bad.'
<p><b>You say, </b>'what luck'
<br><b>Dharr Nadim says </b>'I have just come from Hollowshade Moor a few weeks ago.  My fishing days have been very unprosperous. The lures that I have now are made of low quality Acrylia and scare the fish away rather than attract them.  I want to make a new lure. and on my way in I noticed the dull color of the [scorpions].  I would have moved closer to them but unfortunately  I am deathly allergic to the poisons found in scorpion venom.'
<p><b>You say, </b>'what scorpions'
<br><b>Dharr Nadim says </b>'The scorpions are at the bottom of the canyon surrounding the city.  If you can bring me four shells to make a few lures. I will give you my old lure.  Be careful making your way down the ledges. as there are many steep drops.'
</td></tr></table>