<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Dronqam Runghi says </b>'Good day friend! I'm glad you've stopped by. I am in need of some assistance. Please direct anyone seeking work to me.'
<p><b>You say, </b>'i seek work'
<br><b>Dronqam Runghi says </b>'Excellent! I practice the art of alchemy and I am currently working on some new recipes. I require a few special ingredients. Fortunately they grow in the crater just outside our city walls. Bring me a  redcapped mushroom. a pinch of scarlet moss and a bluecapped mushroom. I'll be most grateful.'
</td></tr></table>