<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18554>A Taruun Guild Summons</a><li><a href=http://phobos/eq/item.php?id=2897>Notarized Application</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2873>Application for Citizenship</a><li><a href=http://phobos/eq/item.php?id=2878>Initiate's Cloak of Shar Vahl</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Elder Scout Kyth Lar says </b>'Well met. Friend.  May I be of assistance?'
<p><b>You give Elder Scout Kyth Lar : </b><a href=http://phobos/eq/item.php?id=18554>A Taruun Guild Summons</a>
<br><b>Elder Scout Kyth Lar gives you : </b><a href=http://phobos/eq/item.php?id=2873>Application for Citizenship</a>
<p><b>You give Elder Scout Kyth Lar : </b><a href=http://phobos/eq/item.php?id=2897>Notarized Application</a>
<br><b>Elder Scout Kyth Lar says </b>'Allow me to be the first to welcome you. Accept this cloak, young initiate. It is a symbol of your loyalty to our noble people. May it serve you as you serve us all. Present your acrylia slate to Harbin Gernawl and he will give you instruction. May the spirits of the beasts guide you and keep you safe.''
<br><b>Elder Scout Kyth Lar gives you : </b><a href=http://phobos/eq/item.php?id=2878>Initiate's Cloak of Shar Vahl</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>