<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=9061>Collection of Spirit Lore</a></ul></td><td><p><b>You say, </b>'spirits'
<p><b>You give Elder Animist Dumul : </b><a href=http://phobos/eq/item.php?id=9061>Collection of Spirit Lore</a>
<br><b>Elder Animist Dumul says </b>'Thank you, young courier. I will not need anything more from you at this time. We have a great deal of research to do and absolutely no time to complete said studies. Did the Historian tell you anything? Matters are bad enough without rumors floating about in the shadows. Speak up... did you hear anything about our situation?'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>