<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=29803>A Shield Repair Order</a><li><a href=http://phobos/eq/item.php?id=29811>Aihjin's Immaculate Shield</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=29810>Aihjin's Dented Shield</a><li><a href=http://phobos/eq/item.php?id=29812>Aihjin's work order</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Khala Dun Aihjin says </b>'Hello there. [Your Name].  Careful around some of the rougher pubs late at night. wouldn't want to see you caught up in a fight like the last one I broke up.  Did you hear about it?'
<p><b>You give Khala Dun Aihjin : </b><a href=http://phobos/eq/item.php?id=29803>A Shield Repair Order</a>
<br><b>Khala Dun Aihjin says </b>'Well it's about time Barkhem got around to us, and he couldn't even be bothered to come himself. Please get this back to me as soon as you can... you do know that we are here to guard the city, right?'
<br><b>Khala Dun Aihjin gives you : </b><a href=http://phobos/eq/item.php?id=29810>Aihjin's Dented Shield</a>
<p><b>You give Khala Dun Aihjin : </b><a href=http://phobos/eq/item.php?id=29811>Aihjin's Immaculate Shield</a>
<br><b>Khala Dun Aihjin says </b>'Well done, I sure will be ready for next time something tries to cause a disturbance in our city. My thanks to you [Your Name].'
<br><b>Khala Dun Aihjin gives you : </b><a href=http://phobos/eq/item.php?id=29812>Aihjin's work order</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>