<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=14587>Rhino Beetle Eye</a><li><a href=http://phobos/eq/item.php?id=29803>A Shield Repair Order</a><li><a href=http://phobos/eq/item.php?id=29814>Bokh's Immaculate Shield</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=29813>Bokh's Dented Shield</a><li><a href=http://phobos/eq/item.php?id=29815>Bokh's work order</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Khala Dun Bokh says </b>'Greetings traveler. if you are headed through these gates you should be aware that there are many [dangers] you may encounter.'
<p><b>You say, </b>'what dangers?'
<br><b>Khala Dun Bokh says </b>'Recently there have been numerous [brigand] encounters. the [Shak Dratha] have also taken arms against our people.'
<p><b>You say, </b>'what shak dratha?'
<br><b>Khala Dun Bokh says </b>'Very little is known about the Shak Dratha. They appeared shortly after the explosion heard in the thicket. Although they are not really our enemies. they have been known to attack when those unknown to them approach.'
<p><b>You say, </b>'who are the shak dratha'
<br><b>Khala Dun Bokh says </b>'The Khala Dun are the king's warriors. They are charged with defending the city of Shar Vahl and commanding any offensives necessary. They are named after Khala Dun who was King Vah Kerrath's protec'
<p><b>You say, </b>'what brigand'
<br><b>Khala Dun Bokh says </b>'The brigands arrived shortly after the disappearance [Loda Kai.] Although it shames me to say it. I believe he may in some way be involved with these attacks. I can not bear to think about such an atrocity. Nevertheless there is a bounty on the brigands.'
<p><b>You say, </b>'who is loda kai'
<br><b>Khala Dun Bokh says </b>'[Loda Kai] was a strong member of the Taruun. he was off to investigate the spirit deaths in shadeweavers thicket when a strong explosion was felt throughout the thickets. He has not been seen since. It was around the time of his disappearance that the brigands began to raid our trade route to shadow haven.'
<p><b>You say, </b>'what is loda kai'
<br><b>Khala Dun Bokh says </b>'[Loda Kai] was a strong member of the Taruun. he was off to investigate the spirit deaths in shadeweavers thicket when a strong explosion was felt throughout the thickets. He has not been seen since. It was around the time of his disappearance that the brigands began to raid our trade route to shadow haven.'
<p><b>You say, </b>'assigned'
<br><b>Khala Dun Bokh says </b>'Thank you for coming to assist. We are always looking for hungry new soldiers. Young soldiers get old much too fast these days. Just look at me.' He smiles at this comment. 'Do this old 
soldier a favor and go down there and gather up a handful of rhino beetle eyes', he says and looks at the mass of crawling creatures that wait below. 'Beetle eyes not only taste good... they keep your fur shiny as well.'
<p><b>You give Khala Dun Bokh : </b><a href=http://phobos/eq/item.php?id=14587>Rhino Beetle Eye</a> x4
<br><font color=green><b>Khala Dun Bokh </b>tosses the beetle eyes into his mouth & attempts to say something to the effect of 'here is your payment.' The sound of crunching gristle & popping eyeballs prevents him from saying it 
properly.</font>
<br><b>You receive </b> 3sp 3cp
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Khala Dun Bokh : </b><a href=http://phobos/eq/item.php?id=29803>A Shield Repair Order</a>
<br><b>Khala Dun Bokh says </b>'Outstanding! Nothing like a sharp-looking shield to scare off the undesirables. And if you bring it back full of food I wouldn't complain either,'
<br><font color=green><b>Khala Dun Bokh </b>laughs, flashing a mischievous grin your way.</font>
<br><b>Khala Dun Bokh says </b>'Just kidding! You have much to do and Barkhem would have my hide if I kept you from your studies.'
<br><b>Khala Dun Bokh gives you : </b><a href=http://phobos/eq/item.php?id=29813>Bokh's Dented Shield</a>
<p><b>You give Khala Dun Bokh : </b><a href=http://phobos/eq/item.php?id=29814>Bokh's Immaculate Shield</a>
<br><b>Khala Dun Bokh says </b>'Well done, shiny enough to eat off of. My compliments to you [Your Name], Barkhem would be most pleased.'
<br><b>Khala Dun Bokh gives you : </b><a href=http://phobos/eq/item.php?id=29815>Bokh's work order</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>