<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18299>Note to King Raja</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18304>Note from King Raja</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>King Raja Kerrath says </b>'Greetings citizen... you are very brave to approach me in this manner.  That sort of bravery warrants my respect.  How may I help you?'
<p><b>You give King Raja Kerrath : </b><a href=http://phobos/eq/item.php?id=18299>Note to King Raja</a>
<br><b>King Raja Kerrath says </b>'Your humility and willingness to serve shall not be wasted. There is much to be done. [Your Name]. and our people thank you in advance for your selfless service.'
<br><b>King Raja Kerrath gives you : </b><a href=http://phobos/eq/item.php?id=18304>Note from King Raja</a>
</td></tr></table>