<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2876>Acrylia Slate</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Mignah Cahru says </b>'Hello. [Your Name]. I am Mignah. a humble acrylia specialist. If you have a form of acrylia that merchants will not buy please hand it to me and I will pay you whatever it may be worth.'
<p><b>You say, </b>'what about an acrylia slate'
<br><font color=green><b>Mignah Cahru </b>pulls a smoldering piece of forged acrylia from a nearby oven and, before you can react, presses your hand into the still soft metal.</font>
<br><b>Mignah Cahru says </b>'This may hurt a bit, but it'll heal.'
<br><font color=green><b>Mignah Cahru </b>etches your name and the date into the slate and plunges it into a bucket of water before placing it into your stinging palm. </font>
<br><b>Mignah Cahru gives you : </b><a href=http://phobos/eq/item.php?id=2876>Acrylia Slate</a>
</td></tr></table>