<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=2877>Acrylia Slate of Shar Vahl</a><li><a href=http://phobos/eq/item.php?id=3461>Rytan's sealed bag</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2877>Acrylia Slate of Shar Vahl</a><li><a href=http://phobos/eq/item.php?id=3463>Xakra tooth dart</a><li><a href=http://phobos/eq/item.php?id=3464>Seal of Rytan</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Rytan says </b>'Hello [Your Name], I trust all is well with you today. Come in and have a look around, just let me know if you see anything you like. By the way, I am in need of the assistance of an official Shar Vahl citizen. If you know of any please send them my way.'
<p><b>You say, </b>'citizen'
<br><b>Rytan says </b>'Wonderful! Please, show me your acrylia slate and I'll disclose my errand.'
<p><b>You give Rytan : </b><a href=http://phobos/eq/item.php?id=2877>Acrylia Slate of Shar Vahl</a>
<br><b>Rytan gives you : </b><a href=http://phobos/eq/item.php?id=2877>Acrylia Slate of Shar Vahl</a>
<br><b>Rytan says </b>'Here's my dilemma, I am low on darts to sell and I need to replenish my supply. I simply cannot break away from the store so I require your help. Fill this bag with xakra teeth and return the sealed bag to me. With those teeth I can make six darts and I'll give you three.'
<p><b>You give Rytan : </b><a href=http://phobos/eq/item.php?id=3461>Rytan's sealed bag</a>
<br><b>Rytan gives you : </b><a href=http://phobos/eq/item.php?id=3463>Xakra tooth dart</a>
<br><b>Rytan gives you : </b><a href=http://phobos/eq/item.php?id=3464>Seal of Rytan</a>
<br><b>Rytan says </b>'Here are the three darts I promised you and a seal of mine. I need more darts desperately, so show me your acrylia slate to take another bag and fill it as you are able. Collect four of my seals and show them to me. I will reward you by revealing my method of dart construction.'
</td></tr></table>