<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=2874>Certificate of Taxability</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2875>Stamped Certificate of Taxability</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Tax Collector Khugra says </b>'Well met. Friend.  May I be of assistance?'
<p><b>You give Tax Collector Khugra : </b><a href=http://phobos/eq/item.php?id=2874>Certificate of Taxability</a>
<br><font color=green><b>Tax Collector Khugra </b>places his seal on the certificate before returning it to you.</font>
<br><b>Tax Collector Khugra says </b>'Ahh, a new taxpayer, wonderful! You must always remember that it is a distinct privilege to contribute to the upkeep of our noble society and not merely a duty or a burden. I look forward to collecting your honorable taxes in the future. May the spirits prosper you, [Your Name].''
<br><b>Tax Collector Khugra gives you : </b><a href=http://phobos/eq/item.php?id=2875>Stamped Certificate of Taxability</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>