<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Weapons Master Rahoul says </b>'Hail friend, are you a new recruit or have you been at it for a bit?'
<p><b>You say, </b>'i am a new recruit'
<br><b>Weapons Master Rahoul says </b>'Well... perhaps you should head to the combat training grounds and pick up a few pointers.  Walk west along the ledge that runs just outside of the city's walls and you shouldn't be able to miss it.'
<p><b>You say, </b>'i have been at it for a bit'
<br><b>Weapons Master Rahoul says </b>'Good good... keep at it!  We need all of the strong willed thick headed Khala Dun we can muster!  Now, get back to the fight!'
</td></tr></table>