<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When   Thelin Poxbourne spawns </b>
<p><b>You say, </b>'Hail'
<br><b>  Thelin Poxbourne says </b>'She lied! She said she would release me if I found my way through the maze! Please, you must defeat her. It is the only way I will ever be free..'
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
</td></tr></table>