<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=9258>Dagger Blade Shard</a></ul></td><td><hr><b>When Thelin Poxbourne spawns </b>
<p><b>You give Thelin Poxbourne : </b><a href=http://phobos/eq/item.php?id=9258>Dagger Blade Shard</a>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=204065>#Terris_Thule</a></b> spawns (5018,-4554,5).</font>
<br><b>Thelin Poxbourne disappears.</b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=204067>__Thelin_Poxbourne</a></b> spawns.</font>
</td></tr></table>