<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10953>Large Shipment of High Quality Ore</a><li><a href=http://phobos/eq/item.php?id=10952>Small Shipment of High Quality Ore</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17814>Empty Ore Crate</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=157>Inhabitants of Tanaan</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>#Yeril Imsin says </b>'Good day to you, [Your Name]. New Tanaan holds a wealth of knowledge and opportunities to further yourself in more ways than mere talent of the mind. If you are a craftsman of steel and armor and seek to further progress your trade, then you have come to the right place. My inventory is quite plentiful and holds the necessary elements for any blacksmith's trade. I am also willing to pay those [willing to help] me restock my supply of high quality ore.'
<p><b>You say, </b>'willing to help'
<br><b>#Yeril Imsin says </b>'Excellent! Simply fill this crate with either four large bricks or four small bricks of unrefined ore from Norrath and return it to me. I will provide you with coin and refine the ore for sale to the smiths of New Tanaan.'
<br><b>#Yeril Imsin gives you : </b><a href=http://phobos/eq/item.php?id=17814>Empty Ore Crate</a>
<p><b>You give #Yeril Imsin : </b><a href=http://phobos/eq/item.php?id=10953>Large Shipment of High Quality Ore</a>
<br><b>#Yeril Imsin says </b>'Thank you [Your Name]! I will prepare the ore for sale and be open for business again momentarily. Here is your payment for your services.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=157>Inhabitants of Tanaan</a> has gotten better.</font>
<br><b>You receive </b> 44pp
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=202068>Yeril_Imsin</a></b> spawns.</font>
<br><b>#Yeril Imsin disappears.</b>
<br><b>#Yeril Imsin says </b>'I don't need this.'
<p><b>You give #Yeril Imsin : </b><a href=http://phobos/eq/item.php?id=10952>Small Shipment of High Quality Ore</a>
<br><b>#Yeril Imsin says </b>'Thank you [Your Name]! I will prepare the ore for sale and be open for business again momentarily. Here is your payment for your services.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=157>Inhabitants of Tanaan</a> has gotten better.</font>
<br><b>You receive </b> 14pp
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=202068>Yeril_Imsin</a></b> spawns.</font>
<br><b>#Yeril Imsin disappears.</b>
<br><b>#Yeril Imsin says </b>'I don't need this.'
<br><b>#Yeril Imsin says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>