<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28188>History of Evils: The Age of Scale</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28084>Note to Caden</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Agrakath Theric </b>regards you indifferently.  'You appear to be new around here, as I have not seen your face walking these streets before.  If you have come seeking knowledge, the library of Myrist will be a most excellent resource for you.  If you have come for any other reason, I'm afraid your quest will not go very far with me, as I do not have much time to hear of your escapades.  Good day.'</font>
<p><b>You say, </b>'erase the debt'
<br><font color=green><b>Agrakath Theric </b>grins and says, 'So, that weasel Caden has sent you to settle his debt? And you actually agreed to this endeavor? Ha ha, very well! I shall transfer the responsibility of what Caden owes me to your shoulders. I have a simple job for you. Somewhere in the library there lies a book I have been searching for, but it has eluded me for quite some time. I believe it can be found somewhere in the upper levels. You are to venture into Myrist and seek out a tome titled History of Evils: The Age of Scale, and bring it to me. Do this one task for me and your debt shall be relinquished.'</font>
<p><b>You give Agrakath Theric : </b><a href=http://phobos/eq/item.php?id=28188>History of Evils: The Age of Scale</a>
<br><font color=green><b>Agrakath Theric </b>eyes go wide with surprise as you hand over the book. 'Very impressive for one of your abilities. Here, take this note to Caden. He is absolved of his debt to me at this time.'</font>
<br><b>Agrakath Theric gives you : </b><a href=http://phobos/eq/item.php?id=28084>Note to Caden</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Agrakath Theric says </b>'I don't need this.'
<br><b>Agrakath Theric says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>