<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28740>Troll Receipt</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Aid Garuuk says </b>'Hullo traveler, an' welcum ta New Tanaan. Have ya been sittin' in da library very long? Da pages contained whif'in dese walls hold many inturestin' bits uv knowledge. As aides ta da council, our job is ta help assist our represenuhtives wif da task uv cullectin' more an' more knowledge fer da library. Right now I'm busy researchin' artifacts uv power fer Srethix but I'm missin' sum books I need. An' worse den dat, all dis werk has made me late in deliverin' sum supplies ta Grobb. Do ya think you could [give me a hand] whif dat?'
<br><b>Aid Garuuk says </b>'Umm, on secund thought, maybe you shudn't help me after all. Da trolls where I come frum aren't as kind an' undurstandin' as I am.'
<p><b>You say, </b>'I will give you a hand'
<br><b>Aid Garuuk says </b>'Umm, on secund thought, maybe you shudn't help me after all. Da trolls where I come frum aren't as kind an' undurstandin' as I am.'
<p><b>You give Aid Garuuk : </b><a href=http://phobos/eq/item.php?id=28740>Troll Receipt</a>
<br><b>Aid Garuuk says </b>'I don't need this.'
<p><b>You give Aid Garuuk : </b><a href=http://phobos/eq/item.php?id=28740>Troll Receipt</a>
<br><b>Aid Garuuk says </b>'I don't need this.'
<br><b>Aid Garuuk says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>