<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28078></a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28240>Fine Antique Locket</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Alexis Dubbani says </b>'Why hello there. [Your Name].  I'm so glad you could take the time to see my exhibit.  I am a collector of [books]. and I seek many more volumes of strange and wonderful texts.  Perhaps I could hire your services to help me find some more?'
<p><b>You say, </b>'books'
<br><b>Alexis Dubbani says </b>'I am still looking for the following. Please locate a Black Tome with Silver Runes, Tome of the Eternal, Codex of the Warrior, and a Book of Inspiration. Please store them inside a Collector's Box you can get from [Merri] for safekeeping. After you find all the books, be sure to close the box and return it to me. I appreciate your help.'
<p><b>You say, </b>'merri'
<br><b>Alexis Dubbani says </b>'Curator Merri is the founder of the museum in the Selia district of New Tanaan. She is a true visionary and a wonderful person as well. It is her dream to turn life's love into something truly grand. She also carries with her the Collector's Boxes. If you need one, be sure to ask her for it.'
<p><b>You give Alexis Dubbani : </b><a href=http://phobos/eq/item.php?id=28078></a>
<br><b>Alexis Dubbani says </b>'These will do. Please accept this as a show of my appreciation. Now if you'll excuse me I have much work left to do.'
<br><b>Alexis Dubbani gives you : </b><a href=http://phobos/eq/item.php?id=28240>Fine Antique Locket</a>
</td></tr></table>