<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1239>Apothic Crown</a><li><a href=http://phobos/eq/item.php?id=1240>Apothic Robe</a><li><a href=http://phobos/eq/item.php?id=1241>Apothic Sleeves</a><li><a href=http://phobos/eq/item.php?id=1242>Apothic Warband</a><li><a href=http://phobos/eq/item.php?id=1243>Apothic Gloves</a><li><a href=http://phobos/eq/item.php?id=1244>Apothic Kilt</a><li><a href=http://phobos/eq/item.php?id=1245>Apothic Boots</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Arch Mage Olera </b>gives an almost unearthly graceful gesture in warm welcoming of [Your Name]. 'May the light of honor, valor, and untainted passion guide you through the dark turmoil of this dreaded era. I am very pleased to see you before us, friend, for the children of the light must all come together in this dark hour of Norrath and the universe's fate. If you have need of guidance in the ways of the elements, then what humble knowledge I have is at your disposal, my friend.'</font>
<p><b>You give Arch Mage Olera : </b><a href=http://phobos/eq/item.php?id=1239>Apothic Crown</a>
<br><b>Arch Mage Olera says </b>'Thank you, [Your Name].'
<br><b>Arch Mage Olera gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Arch Mage Olera says </b>'I don't need this.'
<p><b>You give Arch Mage Olera : </b><a href=http://phobos/eq/item.php?id=1240>Apothic Robe</a>
<br><b>Arch Mage Olera says </b>'Thank you, [Your Name].'
<br><b>Arch Mage Olera gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Arch Mage Olera says </b>'I don't need this.'
<p><b>You give Arch Mage Olera : </b><a href=http://phobos/eq/item.php?id=1241>Apothic Sleeves</a>
<br><b>Arch Mage Olera says </b>'Thank you, [Your Name].'
<br><b>Arch Mage Olera gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Arch Mage Olera says </b>'I don't need this.'
<p><b>You give Arch Mage Olera : </b><a href=http://phobos/eq/item.php?id=1242>Apothic Warband</a>
<br><b>Arch Mage Olera says </b>'Thank you, [Your Name].'
<br><b>Arch Mage Olera gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Arch Mage Olera says </b>'I don't need this.'
<p><b>You give Arch Mage Olera : </b><a href=http://phobos/eq/item.php?id=1243>Apothic Gloves</a>
<br><b>Arch Mage Olera says </b>'Thank you, [Your Name].'
<br><b>Arch Mage Olera gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Arch Mage Olera says </b>'I don't need this.'
<p><b>You give Arch Mage Olera : </b><a href=http://phobos/eq/item.php?id=1244>Apothic Kilt</a>
<br><b>Arch Mage Olera says </b>'Thank you, [Your Name].'
<br><b>Arch Mage Olera gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Arch Mage Olera says </b>'I don't need this.'
<p><b>You give Arch Mage Olera : </b><a href=http://phobos/eq/item.php?id=1245>Apothic Boots</a>
<br><b>Arch Mage Olera says </b>'Thank you, [Your Name].'
<br><b>Arch Mage Olera gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Arch Mage Olera says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Arch Mage Olera says </b>'I don't need this.'
</td></tr></table>