<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1239>Apothic Crown</a><li><a href=http://phobos/eq/item.php?id=1240>Apothic Robe</a><li><a href=http://phobos/eq/item.php?id=1241>Apothic Sleeves</a><li><a href=http://phobos/eq/item.php?id=1242>Apothic Warband</a><li><a href=http://phobos/eq/item.php?id=1243>Apothic Gloves</a><li><a href=http://phobos/eq/item.php?id=1244>Apothic Kilt</a><li><a href=http://phobos/eq/item.php?id=1245>Apothic Boots</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Arch Mage Deidus </b>gives a loathsome, unwavering stare upon [Your Name]. His features are steely and cold in their disdain. 'Kartis is the place of shadow - the cornerstone of the seed of corruption in this universe. You have no place here as you are. Return to Selia. for you will find nothing of use to you here. If you intend to decipher the purpose of the shadow or interrupt the training of our disciples, then you are grievously mistaken in your cause. We will share nothing with the likes of you in the ways of knowledge. Though slowly, if you choose to remain, we shall corrupt and contort you to our will. Even through mere acts of training, you will be fueling the shadow and will become a part of it unwittingly or no.'</font>
<p><b>You give Arch Mage Deidus : </b><a href=http://phobos/eq/item.php?id=1239>Apothic Crown</a>
<br><b>Arch Mage Deidus says </b>'Thank you, [Your Name].'
<br><b>Arch Mage Deidus gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Arch Mage Deidus says </b>'I don't need this.'
<p><b>You give Arch Mage Deidus : </b><a href=http://phobos/eq/item.php?id=1240>Apothic Robe</a>
<br><b>Arch Mage Deidus says </b>'Thank you, [Your Name].'
<br><b>Arch Mage Deidus gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Arch Mage Deidus says </b>'I don't need this.'
<p><b>You give Arch Mage Deidus : </b><a href=http://phobos/eq/item.php?id=1241>Apothic Sleeves</a>
<br><b>Arch Mage Deidus says </b>'Thank you, [Your Name].'
<br><b>Arch Mage Deidus gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Arch Mage Deidus says </b>'I don't need this.'
<p><b>You give Arch Mage Deidus : </b><a href=http://phobos/eq/item.php?id=1242>Apothic Warband</a>
<br><b>Arch Mage Deidus says </b>'Thank you, [Your Name].'
<br><b>Arch Mage Deidus gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Arch Mage Deidus says </b>'I don't need this.'
<p><b>You give Arch Mage Deidus : </b><a href=http://phobos/eq/item.php?id=1243>Apothic Gloves</a>
<br><b>Arch Mage Deidus says </b>'Thank you, [Your Name].'
<br><b>Arch Mage Deidus gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Arch Mage Deidus says </b>'I don't need this.'
<p><b>You give Arch Mage Deidus : </b><a href=http://phobos/eq/item.php?id=1244>Apothic Kilt</a>
<br><b>Arch Mage Deidus says </b>'Thank you, [Your Name].'
<br><b>Arch Mage Deidus gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Arch Mage Deidus says </b>'I don't need this.'
<p><b>You give Arch Mage Deidus : </b><a href=http://phobos/eq/item.php?id=1245>Apothic Boots</a>
<br><b>Arch Mage Deidus says </b>'Thank you, [Your Name].'
<br><b>Arch Mage Deidus gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Arch Mage Deidus says </b>'I don't need this.'
<br><b>Arch Mage Deidus says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>