<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4901>Woven Shadow Helm</a><li><a href=http://phobos/eq/item.php?id=4902>Woven Shadow Chestplate</a><li><a href=http://phobos/eq/item.php?id=4903>Woven Shadow Vambraces</a><li><a href=http://phobos/eq/item.php?id=4904>Woven Shadow Bracer</a><li><a href=http://phobos/eq/item.php?id=4905>Woven Shadow Gauntlets</a><li><a href=http://phobos/eq/item.php?id=4906>Woven Shadow Greaves</a><li><a href=http://phobos/eq/item.php?id=4907>Woven Shadow Boots</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Assassin Mirot </b>gives a sharply raised brow and cruelly wicked smirk, his comely features contorted in a sinister mask of disgust and amusement. 'Well, how charming of you to find it within your heart to visit Kartis, my dear pathetic [Your Name]. Do not think that you will be received in the manner you had hoped, for we are in the city of knowledge where tolerance for all beings to one extent or another is mandatory. Aaaah, yes, we will tolerate your existence among us, but only for the amusement of watching you squirm uncomfortably when presented with the truth of our purpose. Even further the amusement would stretch is if you would have the audacity to train from one of our adepts -- who are, I assure you, most eager to lend their dark arts to you, for it only fuels the shadow, despite your intent on learning from us.'</font>
<p><b>You give Assassin Mirot : </b><a href=http://phobos/eq/item.php?id=4901>Woven Shadow Helm</a>
<br><b>Assassin Mirot says </b>'Thank you, [Your Name].'
<br><b>Assassin Mirot gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Assassin Mirot says </b>'I don't need this.'
<p><b>You give Assassin Mirot : </b><a href=http://phobos/eq/item.php?id=4902>Woven Shadow Chestplate</a>
<br><b>Assassin Mirot says </b>'Thank you, [Your Name].'
<br><b>Assassin Mirot gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Assassin Mirot says </b>'I don't need this.'
<p><b>You give Assassin Mirot : </b><a href=http://phobos/eq/item.php?id=4903>Woven Shadow Vambraces</a>
<br><b>Assassin Mirot says </b>'Thank you, [Your Name].'
<br><b>Assassin Mirot gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Assassin Mirot says </b>'I don't need this.'
<p><b>You give Assassin Mirot : </b><a href=http://phobos/eq/item.php?id=4904>Woven Shadow Bracer</a>
<br><b>Assassin Mirot says </b>'Thank you, [Your Name].'
<br><b>Assassin Mirot gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Assassin Mirot says </b>'I don't need this.'
<p><b>You give Assassin Mirot : </b><a href=http://phobos/eq/item.php?id=4905>Woven Shadow Gauntlets</a>
<br><b>Assassin Mirot says </b>'Thank you, [Your Name].'
<br><b>Assassin Mirot gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Assassin Mirot says </b>'I don't need this.'
<p><b>You give Assassin Mirot : </b><a href=http://phobos/eq/item.php?id=4906>Woven Shadow Greaves</a>
<br><b>Assassin Mirot says </b>'Thank you, [Your Name].'
<br><b>Assassin Mirot gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Assassin Mirot says </b>'I don't need this.'
<p><b>You give Assassin Mirot : </b><a href=http://phobos/eq/item.php?id=4907>Woven Shadow Boots</a>
<br><b>Assassin Mirot says </b>'Thank you, [Your Name].'
<br><b>Assassin Mirot gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Assassin Mirot says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Assassin Mirot says </b>'I don't need this.'
</td></tr></table>