<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4901>Woven Shadow Helm</a><li><a href=http://phobos/eq/item.php?id=4902>Woven Shadow Chestplate</a><li><a href=http://phobos/eq/item.php?id=4903>Woven Shadow Vambraces</a><li><a href=http://phobos/eq/item.php?id=4904>Woven Shadow Bracer</a><li><a href=http://phobos/eq/item.php?id=4905>Woven Shadow Gauntlets</a><li><a href=http://phobos/eq/item.php?id=4906>Woven Shadow Greaves</a><li><a href=http://phobos/eq/item.php?id=4907>Woven Shadow Boots</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Assassin Daran </b>grins wildly at [Your Name]. An uncomfortable presence washes over you in a split moment as you catch the halfling's narrowed eyes searching every inch of your person. 'Hail, greetings, and well met, friend! I am Daran, rogue extraordinaire! Rather, I am -the- rogue, I should say. A'course I dinnae boast, my friend! Aww. . . dinnae be offended or feel inferior, but be honored that ye stand in my presence. Well, enough of the introductions then, yes? Hrm. . . what have we here? Perhaps ye be a rogue, hrm? Ye seek my infinite and unsurpassed cunning and prowess perhaps to teach ye? Well then, if it is a master of the shadows that you wish to be, then I be the man who will most assuredly make a proper rogue out of you yet.'</font>
<p><b>You give Assassin Daran : </b><a href=http://phobos/eq/item.php?id=4901>Woven Shadow Helm</a>
<br><b>Assassin Daran says </b>'Thank you, [Your Name].'
<br><b>Assassin Daran gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Assassin Daran says </b>'I don't need this.'
<p><b>You give Assassin Daran : </b><a href=http://phobos/eq/item.php?id=4902>Woven Shadow Chestplate</a>
<br><b>Assassin Daran says </b>'Thank you, [Your Name].'
<br><b>Assassin Daran gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Assassin Daran says </b>'I don't need this.'
<p><b>You give Assassin Daran : </b><a href=http://phobos/eq/item.php?id=4903>Woven Shadow Vambraces</a>
<br><b>Assassin Daran says </b>'Thank you, [Your Name].'
<br><b>Assassin Daran gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Assassin Daran says </b>'I don't need this.'
<p><b>You give Assassin Daran : </b><a href=http://phobos/eq/item.php?id=4904>Woven Shadow Bracer</a>
<br><b>Assassin Daran says </b>'Thank you, [Your Name].'
<br><b>Assassin Daran gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Assassin Daran says </b>'I don't need this.'
<p><b>You give Assassin Daran : </b><a href=http://phobos/eq/item.php?id=4905>Woven Shadow Gauntlets</a>
<br><b>Assassin Daran says </b>'Thank you, [Your Name].'
<br><b>Assassin Daran gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Assassin Daran says </b>'I don't need this.'
<p><b>You give Assassin Daran : </b><a href=http://phobos/eq/item.php?id=4906>Woven Shadow Greaves</a>
<br><b>Assassin Daran says </b>'Thank you, [Your Name].'
<br><b>Assassin Daran gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Assassin Daran says </b>'I don't need this.'
<p><b>You give Assassin Daran : </b><a href=http://phobos/eq/item.php?id=4907>Woven Shadow Boots</a>
<br><b>Assassin Daran says </b>'Thank you, [Your Name].'
<br><b>Assassin Daran gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Assassin Daran says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Assassin Daran says </b>'I don't need this.'
</td></tr></table>