<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=59997>Burning Crystal Shard</a><li><a href=http://phobos/eq/item.php?id=59996>Frozen Crystal Shard</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=59996>Frozen Crystal Shard</a><li><a href=http://phobos/eq/item.php?id=59997>Burning Crystal Shard</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Bertrand Bibblesworth says </b>'Yes, hello to you as well. I have recently come here in search of some more curious [crystals].'
<p><b>You say, </b>'crystals'
<br><b>Bertrand Bibblesworth says </b>'These are no ordinary crystals. They are known as frozen crystal shards and burning crystal shards. I believe they are made by the gelidrans and pyrilens, chaotic elemental creatures composed of fire and ice. I encountered a couple of these fierce creatures in the Realm of Discord and managed to, um, procure quite a collection of crystals. Hey, if you would like to [trade], I might be interested.'
<p><b>You say, </b>'trade'
<br><b>Bertrand Bibblesworth says </b>'I can trade you a frozen crystal for a burning crystal or vice versa. Just hand one to me if you are interested!'
<p><b>You give Bertrand Bibblesworth : </b><a href=http://phobos/eq/item.php?id=59997>Burning Crystal Shard</a>
<br><font color=green><b>Bertrand Bibblesworth </b>Here you go, [Your Name]!</font>
<br><b>Bertrand Bibblesworth gives you : </b><a href=http://phobos/eq/item.php?id=59996>Frozen Crystal Shard</a>
<br><b>Bertrand Bibblesworth says </b>'I don't need this.'
<p><b>You give Bertrand Bibblesworth : </b><a href=http://phobos/eq/item.php?id=59996>Frozen Crystal Shard</a>
<br><font color=green><b>Bertrand Bibblesworth </b>Here you go, [Your Name]!</font>
<br><b>Bertrand Bibblesworth gives you : </b><a href=http://phobos/eq/item.php?id=59997>Burning Crystal Shard</a>
<br><b>Bertrand Bibblesworth says </b>'I don't need this.'
<br><b>Bertrand Bibblesworth says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>