<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28085>Boiron's Standard</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28086>Letter to Elisha</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Boiron Ston says </b>'Welcome to New Tanaan. traveler.  The practice of smithing is a time-honored tradition for my people.  My particular specialty is craftsmanship of plate armor for the larger races of Norrath.  Feel free to search my stock for anything you might need to help aid your pursuit of this skill.'
<p><b>You say, </b>'like elisha dirtyshoes'
<br><b>Boiron Ston says </b>'Aye, she's a pretty lass. And I am aware of her feelings toward me. I haven't had the courage to approach her though. My family standard has recently disappeared, and no dwarf is the same when their standard is in jeopardy. Seek out Caden Zharik and demand my standard back, I believe he may have lifted it from me.'
<p><b>You give Boiron Ston : </b><a href=http://phobos/eq/item.php?id=28085>Boiron's Standard</a>
<br><font color=green><b>Boiron Ston </b>seems to perk up. 'Ah, 'tis a beauty, is it not? I thank you for its safe return. Perhaps I shall go and visit Elisha after all. Please take this letter to her, so she may be ready for me when I arrive.'</font>
<br><b>Boiron Ston gives you : </b><a href=http://phobos/eq/item.php?id=28086>Letter to Elisha</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Boiron Ston says </b>'I don't need this.'
<br><b>Boiron Ston says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>