<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28091>Curative Potion</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28092>New Sewing Needles</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Bolcen Tendag </b>coughs and says. 'Hello traveler.  Allow me to introduce myself. I am Bolcen. If you are looking for my master Xelrin. you may find him upstairs.  Careful should you stand too close to me however. I have become ill.'  He coughs again.</font>
<p><b>You say, </b>'needles'
<br><b>Bolcen Tendag says </b>'I feel just terrible that I haven't been to see Willamina yet. Due to my illness I barely have the energy to stand. If you could aid me in some way, I would greatly appreciate it. Mirao Frostpouch might have an elixir that would help me feel better. Please seek him out and ask for it.'
<p><b>You give Bolcen Tendag : </b><a href=http://phobos/eq/item.php?id=28091>Curative Potion</a>
<br><b>Bolcen Tendag says </b>'Oh thank you so much.' He drinks from the bottle, then reaches in his pocket and produces a set of needles. 'I believe this is what Willamina is in need of. Please take these to her and give her my best.'
<br><b>Bolcen Tendag gives you : </b><a href=http://phobos/eq/item.php?id=28092>New Sewing Needles</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Bolcen Tendag says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>