<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Borik Darkanvil says </b>'Greetings. Borik Darkanvil. at your service.  I was once a planar traveler like you.  Those days are behind me. now I am content to earn my keep as a blacksmith. and to experiment with some of the [special recipes] that I have picked up in these outer planes.'
</td></tr></table>