<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28084>Note to Caden</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28085>Boiron's Standard</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Caden Zharik says </b>'What?  Oh, sorry.  You appear to be harmless enough.  Never can be too careful these days, you know.  Say. as long as you're here, would you care to have a look at my stock of supplies and see if there's anything you might need?  I worked really hard to scrounge this together, won't you just like to have a look?'
<p><b>You say, </b>'standard'
<br><font color=green><b>Caden Zharik </b>turns white with fear. 'Ah, so he sent you to rough me up, did he? Fine, but you should know you couldn't hurt me any worse than Agrakath Theric would! I'm in a bit of trouble you see, I owe Agrakath some money I haven't got. So I stole the standard to pay him off. If you could please find him and have him somehow erase my debt, I would gladly give the standard back.'</font>
<p><b>You give Caden Zharik : </b><a href=http://phobos/eq/item.php?id=28084>Note to Caden</a>
<br><font color=green><b>Caden Zharik </b>eyes go wide with relief. 'Oh thank you thank you! Here, take the standard. And do apologize to Boiron for me. It shall never happen again. Again, thank you!'</font>
<br><b>Caden Zharik gives you : </b><a href=http://phobos/eq/item.php?id=28085>Boiron's Standard</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Caden Zharik says </b>'I don't need this.'
<br><b>Caden Zharik says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>