<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<p><b>Cadelawin Browan checks to see if you have <a href=http://phobos/eq/item.php?id=1057>Mystic Cloak</a></b><br>
<br><b>Cadelawin Browan says </b>'Wow, you have a Mystic Cloak! I was just reading a book about cloaks with similar enchantments. I'm studying to try and learn how to make magical and enchanted armor. I'm pretty sure I have figured out a way to [recharge] a Mystic Cloak.'
<p><b>You say, </b>'recharge'
<br><b>Cadelawin Browan says </b>'Well, in the case of the Mystic Cloak at least, the true enchantment is in the brooch that you use to clip the cloak around your shoulders. The cloak itself cannot run out of magic, the brooch, however, can. When it no longer has the ability to cast spells you should be able to attach a [new brooch] and regain the magic the cloak once possessed.'
<p><b>You say, </b>'new brooch'
<br><b>Cadelawin Browan says </b>''I figured that would be your next question. Each enchanted cloak has its own brooch, and you need to know the specifics of the brooch for your cloak in order to replace it. You happen to be in luck today as I happen to know the specifications for the cloak associated with the Mystic Cloak. First you will need talisman made from Chrysoberyl. That talisman will need to be affixed inside a Planar Jeweler's kit by a skilled jewelcrafter to an enchanted platinum bar with a magic scroll of steelskin and a vial of distilled mana. Once you have the brooch simply attach it to your cloak in one of the looms you can find in Jeral, it shouldn't be terribly difficult.'
<br><b>Cadelawin Browan says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>