<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=16266>Power of the Planes</a><li><a href=http://phobos/eq/item.php?id=32106>Jade Hoop of Speed</a><li><a href=http://phobos/eq/item.php?id=17209>Frizznik's Endless Coin Purse</a><li><a href=http://phobos/eq/item.php?id=32107>Cord of Invigoration</a><li><a href=http://phobos/eq/item.php?id=32108>Mace of the Ancients</a><li><a href=http://phobos/eq/item.php?id=32109>Ring of Farsight</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=32106>Jade Hoop of Speed</a><li><a href=http://phobos/eq/item.php?id=17209>Frizznik's Endless Coin Purse</a><li><a href=http://phobos/eq/item.php?id=32107>Cord of Invigoration</a><li><a href=http://phobos/eq/item.php?id=32108>Mace of the Ancients</a><li><a href=http://phobos/eq/item.php?id=32109>Ring of Farsight</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Councilwoman Kerasha says </b>'Greetings [Your Name].  I am Councilwoman Kerasha. representative of the Selia district.  I provide the voice of nature to the Council of Tanaan.  Woe is the city in any realm that forgets to heed Mother Tunare.  For where else could one draw strength from but the land?'
<p><b>You say, </b>'aid'
<p><b>You say, </b>'essences of power'
<p><b>You say, </b>'Hail'
<br><b>Councilwoman Kerasha says </b>'Greetings [Your Name].  I am Councilwoman Kerasha. representative of the Selia district.  I provide the voice of nature to the Council of Tanaan.  Woe is the city in any realm that forgets to heed Mother Tunare.  For where else could one draw strength from but the land?'
<p><b>You give Councilwoman Kerasha : </b><a href=http://phobos/eq/item.php?id=16266>Power of the Planes</a>
<br><font color=green><b>Councilwoman Kerasha </b>takes the Power from you and hands it to Aid Eino. 'Thank you [Your Name]. The energy I must expend to perform such a task is days in the gathering. The city of Tanaan is forever in your debt. Take this, it is but a small token of the gratitude of the city. If it does not suit you, return it to me and I shall give you another reward.'</font>
<br><b>Councilwoman Kerasha gives you : </b><a href=http://phobos/eq/item.php?id=32106>Jade Hoop of Speed</a>
<br><b>Councilwoman Kerasha says </b>'I don't need this.'
<p><b>You give Councilwoman Kerasha : </b><a href=http://phobos/eq/item.php?id=32106>Jade Hoop of Speed</a>
<br><b>Councilwoman Kerasha says </b>'I understand.  Take this, may it serve you well, [Your Name].'
<br><b>Councilwoman Kerasha gives you : </b><a href=http://phobos/eq/item.php?id=17209>Frizznik's Endless Coin Purse</a>
<br><b>Councilwoman Kerasha says </b>'I don't need this.'
<p><b>You give Councilwoman Kerasha : </b><a href=http://phobos/eq/item.php?id=17209>Frizznik's Endless Coin Purse</a>
<br><b>Councilwoman Kerasha says </b>'I understand.  Take this, may it serve you well, [Your Name].'
<br><b>Councilwoman Kerasha gives you : </b><a href=http://phobos/eq/item.php?id=32107>Cord of Invigoration</a>
<br><b>Councilwoman Kerasha says </b>'I don't need this.'
<p><b>You give Councilwoman Kerasha : </b><a href=http://phobos/eq/item.php?id=32107>Cord of Invigoration</a>
<br><b>Councilwoman Kerasha says </b>'I understand.  Take this, may it serve you well, [Your Name].'
<br><b>Councilwoman Kerasha gives you : </b><a href=http://phobos/eq/item.php?id=32108>Mace of the Ancients</a>
<br><b>Councilwoman Kerasha says </b>'I don't need this.'
<p><b>You give Councilwoman Kerasha : </b><a href=http://phobos/eq/item.php?id=32108>Mace of the Ancients</a>
<br><b>Councilwoman Kerasha says </b>'I understand.  Take this, may it serve you well, [Your Name].'
<br><b>Councilwoman Kerasha gives you : </b><a href=http://phobos/eq/item.php?id=32109>Ring of Farsight</a>
<br><b>Councilwoman Kerasha says </b>'I don't need this.'
<p><b>You give Councilwoman Kerasha : </b><a href=http://phobos/eq/item.php?id=32109>Ring of Farsight</a>
<br><b>Councilwoman Kerasha says </b>'I understand.  Take this, may it serve you well, [Your Name].'
<br><b>Councilwoman Kerasha gives you : </b><a href=http://phobos/eq/item.php?id=32106>Jade Hoop of Speed</a>
<br><b>Councilwoman Kerasha says </b>'I don't need this.'
<br><b>Councilwoman Kerasha says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>