<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4851>Valorium Helmet</a><li><a href=http://phobos/eq/item.php?id=4852>Valorium Chestplate</a><li><a href=http://phobos/eq/item.php?id=4853>Valorium Vambraces</a><li><a href=http://phobos/eq/item.php?id=4854>Valorium Bracers</a><li><a href=http://phobos/eq/item.php?id=4855>Valorium Gauntlets</a><li><a href=http://phobos/eq/item.php?id=4856>Valorium Greaves</a><li><a href=http://phobos/eq/item.php?id=4857>Valorium Boots</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Crusader Difur </b>kneels before [Your Name] in humble recognition. The clang of his spotless, dwarven crafted armor against the stone floor briefly chimes through the hall. The song of steel and marble is echoed by his gruff, iron voice. 'I am Difur, Crusader of Brell Serillis and master of the paladins in the district of Tanaan. If ye seek knowledge and wisdom of the justly knights of Norrath than I, most humbly, am at yer service, traveler.'</font>
<p><b>You give Crusader Difur : </b><a href=http://phobos/eq/item.php?id=4851>Valorium Helmet</a>
<br><b>Crusader Difur says </b>'Thank you, [Your Name].'
<br><b>Crusader Difur gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Crusader Difur says </b>'I don't need this.'
<p><b>You give Crusader Difur : </b><a href=http://phobos/eq/item.php?id=4852>Valorium Chestplate</a>
<br><b>Crusader Difur says </b>'Thank you, [Your Name].'
<br><b>Crusader Difur gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Crusader Difur says </b>'I don't need this.'
<p><b>You give Crusader Difur : </b><a href=http://phobos/eq/item.php?id=4853>Valorium Vambraces</a>
<br><b>Crusader Difur says </b>'Thank you, [Your Name].'
<br><b>Crusader Difur gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Crusader Difur says </b>'I don't need this.'
<p><b>You give Crusader Difur : </b><a href=http://phobos/eq/item.php?id=4854>Valorium Bracers</a>
<br><b>Crusader Difur says </b>'Thank you, [Your Name].'
<br><b>Crusader Difur gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Crusader Difur says </b>'I don't need this.'
<p><b>You give Crusader Difur : </b><a href=http://phobos/eq/item.php?id=4855>Valorium Gauntlets</a>
<br><b>Crusader Difur says </b>'Thank you, [Your Name].'
<br><b>Crusader Difur gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Crusader Difur says </b>'I don't need this.'
<p><b>You give Crusader Difur : </b><a href=http://phobos/eq/item.php?id=4856>Valorium Greaves</a>
<br><b>Crusader Difur says </b>'Thank you, [Your Name].'
<br><b>Crusader Difur gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Crusader Difur says </b>'I don't need this.'
<p><b>You give Crusader Difur : </b><a href=http://phobos/eq/item.php?id=4857>Valorium Boots</a>
<br><b>Crusader Difur says </b>'Thank you, [Your Name].'
<br><b>Crusader Difur gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Crusader Difur says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Crusader Difur says </b>'I don't need this.'
</td></tr></table>