<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4851>Valorium Helmet</a><li><a href=http://phobos/eq/item.php?id=4852>Valorium Chestplate</a><li><a href=http://phobos/eq/item.php?id=4853>Valorium Vambraces</a><li><a href=http://phobos/eq/item.php?id=4854>Valorium Bracers</a><li><a href=http://phobos/eq/item.php?id=4855>Valorium Gauntlets</a><li><a href=http://phobos/eq/item.php?id=4856>Valorium Greaves</a><li><a href=http://phobos/eq/item.php?id=4857>Valorium Boots</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Crusader Gimil says </b>'kneels low before [Your Name], offering a humble gesture of respect and greetings. 'The light of Selia embraces thee, my friend. If you reside in our midst in searching for knowledge and guidance, then know that we are your servants in that quest. Should you be a paladin, and your object of faith is of no consequence in this matter, then my services are humbly at your disposal should you need or wish them.''
<p><b>You give Crusader Gimil : </b><a href=http://phobos/eq/item.php?id=4851>Valorium Helmet</a>
<br><b>Crusader Gimil says </b>'Thank you, [Your Name].'
<br><b>Crusader Gimil gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Crusader Gimil says </b>'I don't need this.'
<p><b>You give Crusader Gimil : </b><a href=http://phobos/eq/item.php?id=4852>Valorium Chestplate</a>
<br><b>Crusader Gimil says </b>'Thank you, [Your Name].'
<br><b>Crusader Gimil gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Crusader Gimil says </b>'I don't need this.'
<p><b>You give Crusader Gimil : </b><a href=http://phobos/eq/item.php?id=4853>Valorium Vambraces</a>
<br><b>Crusader Gimil says </b>'Thank you, [Your Name].'
<br><b>Crusader Gimil gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Crusader Gimil says </b>'I don't need this.'
<p><b>You give Crusader Gimil : </b><a href=http://phobos/eq/item.php?id=4854>Valorium Bracers</a>
<br><b>Crusader Gimil says </b>'Thank you, [Your Name].'
<br><b>Crusader Gimil gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Crusader Gimil says </b>'I don't need this.'
<p><b>You give Crusader Gimil : </b><a href=http://phobos/eq/item.php?id=4855>Valorium Gauntlets</a>
<br><b>Crusader Gimil says </b>'Thank you, [Your Name].'
<br><b>Crusader Gimil gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Crusader Gimil says </b>'I don't need this.'
<p><b>You give Crusader Gimil : </b><a href=http://phobos/eq/item.php?id=4856>Valorium Greaves</a>
<br><b>Crusader Gimil says </b>'Thank you, [Your Name].'
<br><b>Crusader Gimil gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Crusader Gimil says </b>'I don't need this.'
<p><b>You give Crusader Gimil : </b><a href=http://phobos/eq/item.php?id=4857>Valorium Boots</a>
<br><b>Crusader Gimil says </b>'Thank you, [Your Name].'
<br><b>Crusader Gimil gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Crusader Gimil says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Crusader Gimil says </b>'I don't need this.'
</td></tr></table>