<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28082>Collection of Idols</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28241>Fine Antique Velvet Rose</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Curator Merri </b>beams a smile as you approach. 'Welcome [Your Name]. This building will be the site of New Tanaan's greatest museum ever. I realize it looks a bit empty now, but just imagine how beautiful it will look after we fill it with rare and exotic treasures from all over. It's a very exciting time, no? Of course, we still need to obtain a few more [artifacts].'</font>
<p><b>You say, </b>'artifacts'
<br><b>Curator Merri says </b>'Each of the people you see working here has their own exhibit to build and maintain. If you speak to them, they can tell you about which items they are looking for to add to their collection. Any items you collect will need to be placed inside one of my storage containers. If you [need a Collector's Box] at any time, just ask me. Also know I could use some help in retrieving some [special items] for my own exhibit.'
<p><b>You say, </b>'special items'
<br><b>Curator Merri says </b>'My display will showcase the many interesting religious idols and artifacts from Norrath's history. Most of my gallery is complete, but I still need a few more items. I am looking for a Forlorn Totem of Rolfron Zek, Idol of Woven Grass, Coldain Fetish, and a Petrified Totem. Once you have these holy artifacts, close them up inside a Collector's Box and return it to me. Good luck.'
<p><b>You say, </b>'need a Collector\'s Box'
<p><b>You give Curator Merri : </b><a href=http://phobos/eq/item.php?id=28082>Collection of Idols</a>
<br><b>Curator Merri says </b>'Thank you very much [Your Name]!  Here, please accept this as a reward for the fine work you've done.'
<br><b>Curator Merri gives you : </b><a href=http://phobos/eq/item.php?id=28241>Fine Antique Velvet Rose</a>
<br><b>Curator Merri says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>