<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When Darius Gandril spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Darius Gandril says </b>'Good day to you. traveler. The trails of the outer planes and Norrath alike take their tolls upon any adventurer. The need for supplies is great to maintain strength. agility. awareness. and focus and thus. I provide that which may quench your common desires. Search my stock as you wish and purchase what catches your eye. My prices are most fair. I assure you.'
</td></tr></table>