<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>Dieffer Wolfhugger says </b>'Hello [Your Name], I can buff you with [Spirt of the Wolf], [Pure Blood] and my friend, Nomaad, over there has 'chanter buffs. Also, if you are in need of Cleric Buffs, Qadar has those.'
<br><font color=green><b>Dieffer Wolfhugger </b>waves at Nomaad</font>
<p><b>You say, </b>'hail'
<br><b>Dieffer Wolfhugger says </b>'Hello [Your Name], I can buff you with [Spirt of the Wolf], [Pure Blood] and my friend, Nomaad, over there has 'chanter buffs. Also, if you are in need of Cleric Buffs, Qadar has those.'
<br><font color=green><b>Dieffer Wolfhugger </b>waves at Nomaad</font>
<p><b>You say, </b>'Wolf'
<br><font color=brown><b>Dieffer Wolfhugger casts a spell : </b><a href=http://phobos/eq/spell.php?id=3692>Temperance</a>.</font>
<br><b>Dieffer Wolfhugger says </b>'Casting Spirit of the Wolf, Good hunting!'
<p><b>You say, </b>'Eagle'
<br><font color=brown><b>Dieffer Wolfhugger casts a spell on you : </b><a href=http://phobos/eq/spell.php?id=></a>.</font>
<br><b>Dieffer Wolfhugger says </b>'Casting Spirit of the Eagle, Good hunting!'
<p><b>You say, </b>'Pure Blood'
<br><font color=brown><b>Dieffer Wolfhugger casts a spell on you : </b><a href=http://phobos/eq/spell.php?id=></a>.</font>
<br><b>Dieffer Wolfhugger says </b>'Casting Pure Blood, Be Well!'
</td></tr></table>