<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28077>Collection of Gems</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28242>Fine Antique Veil</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Drelynn Beaufax says </b>'A fine day to you, [Your Name]. The exhibit you will see here soon will likely be the most valuable of them all. My display will house some of the most precious and rare gemstones you will ever find. It is too sad there are still spaces missing in my display box, if I could only find a few more [gems] to fill them out.'
<p><b>You say, </b>'gems'
<br><b>Drelynn Beaufax says </b>'To make the exhibit truly stand out, I would need to add a Blackened Sapphire, Greenscale Emerald, Shimmering Velium Ruby, and a Hope Diamond. Could I perhaps procure these from you? Visit [Merri] and get a Collector's Box from her. Carefully place the gems inside and close it up. Once you return this to me, I can pay you for your services.'
<p><b>You say, </b>'merri'
<br><b>Drelynn Beaufax says </b>'Curator Merri is the founder of the museum in the Selia district of New Tanaan. She is a true visionary and a wonderful person as well. It is her dream to turn life's love into something truly grand. She also carries with her the Collector's Boxes. If you need one, be sure to ask her for it.'
<p><b>You give Drelynn Beaufax : </b><a href=http://phobos/eq/item.php?id=28077>Collection of Gems</a>
<br><font color=green><b>Drelynn Beaufax </b>inspects each gem carefully. 'These are in much better condition then I thought I would get them in. Adding these to my exhibit pleases me greatly. As promised, here is something for you.'</font>
<br><b>Drelynn Beaufax gives you : </b><a href=http://phobos/eq/item.php?id=28242>Fine Antique Veil</a>
<br><b>Drelynn Beaufax says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>