<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=29112>Ethereal Parchment</a><li><a href=http://phobos/eq/item.php?id=29131>Spectral Parchment</a><li><a href=http://phobos/eq/item.php?id=29132>Glyphed Rune Word</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28440>Spell: Elemental Barrier</a><li><a href=http://phobos/eq/item.php?id=29363>Spell: Maelstrom of Ro</a><li><a href=http://phobos/eq/item.php?id=28436>Spell: Sun Vortex</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Elementalist Somat says </b>''
<p><b>You give Elementalist Somat : </b><a href=http://phobos/eq/item.php?id=29112>Ethereal Parchment</a>
<br><font color=green><b>Elementalist Somat </b></font>
<br><b>Elementalist Somat gives you : </b><a href=http://phobos/eq/item.php?id=28440>Spell: Elemental Barrier</a>
<br><b>Elementalist Somat says </b>'I don't need this.'
<p><b>You give Elementalist Somat : </b><a href=http://phobos/eq/item.php?id=29131>Spectral Parchment</a>
<br><font color=green><b>Elementalist Somat </b></font>
<br><b>Elementalist Somat gives you : </b><a href=http://phobos/eq/item.php?id=29363>Spell: Maelstrom of Ro</a>
<br><b>Elementalist Somat says </b>'I don't need this.'
<p><b>You give Elementalist Somat : </b><a href=http://phobos/eq/item.php?id=29132>Glyphed Rune Word</a>
<br><font color=green><b>Elementalist Somat </b></font>
<br><b>Elementalist Somat gives you : </b><a href=http://phobos/eq/item.php?id=28436>Spell: Sun Vortex</a>
<br><b>Elementalist Somat says </b>'I don't need this.'
<br><b>Elementalist Somat says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>