<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28086>Letter to Elisha</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28087>Narik's Ring</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Elisha Dirtyshoes says </b>'Well, good day to you, good traveler. I am Elisha Dirtyshoes, a humble citizen of New Tanaan. Though I have never braved the dangers of an adventurer's life, I make a suitable and humble life here in this beautiful city. If you are a potter, then perhaps my wares might interest you?'
<p><b>You say, </b>'ring'
<br><font color=green><b>Elisha Dirtyshoes </b>sighs and says, 'Tis a painful memory, for sure. My love for Narik fell once I met Onirelin, but my love for him was not reciprocated. Now I am left with no one to share my life, with only this ring as a reminder. Narik may have it back if he desires it, but then I shall be left truly alone. Boiron Ston once held a door open for me, such a handsome dwarf he is. If he could only find more time to spend with me, giving up this ring would be no problem at all. Do you think he likes me? Could you ask him and find out?'</font>
<p><b>You give Elisha Dirtyshoes : </b><a href=http://phobos/eq/item.php?id=28086>Letter to Elisha</a>
<br><font color=green><b>Elisha Dirtyshoes </b>reads the letter and says, 'Oh happy day! Boiron will be visiting me soon. You may take Narik's ring back to him now. If you'll excuse me, I have some cleaning up to do.'</font>
<br><b>Elisha Dirtyshoes gives you : </b><a href=http://phobos/eq/item.php?id=28087>Narik's Ring</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Elisha Dirtyshoes says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>