<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28079></a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28243>Fine Antique Poniard</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Gammle Hecht says </b>'Good day [Your Name].  I don't mean to be curt but I have much work to do to be ready for my museum display, and there is not much time left. I expect many young warriors to be visiting here, but it is unfortunate that I do not have the final pieces I am [missing]. They would add to the collection greatly.'
<p><b>You say, </b>'missing'
<br><b>Gammle Hecht says </b>'If you would be willing to help me, I can make it worth your while. I need you to find a Minotaur Battle Axe, Goblin Two-Handed Sword, Chill Dagger, and an Ancient Sensate Shield. When you get these items, put them in a Collector's Box that you can get from [Merri], close it up and bring it to me.'
<p><b>You say, </b>'merri'
<br><b>Gammle Hecht says </b>'Curator Merri is the founder of the museum in the Selia district of New Tanaan. She is a true visionary and a wonderful person as well. It is her dream to turn life's love into something truly grand. She also carries with her the Collector's Boxes. If you need one, be sure to ask her for it.'
<p><b>You give Gammle Hecht : </b><a href=http://phobos/eq/item.php?id=28079></a>
<br><b>Gammle Hecht says </b>'These will do. Please accept this as a show of my appreciation. Now if you'll excuse me I have much work left to do.'
<br><b>Gammle Hecht gives you : </b><a href=http://phobos/eq/item.php?id=28243>Fine Antique Poniard</a>
</td></tr></table>