<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1201>Shiverback-hide Jerkin</a><li><a href=http://phobos/eq/item.php?id=1202>Shiverback-hide Armbands</a><li><a href=http://phobos/eq/item.php?id=1203>Shiverback-hide Wristbands</a><li><a href=http://phobos/eq/item.php?id=1204>Shiverback-hide Gloves</a><li><a href=http://phobos/eq/item.php?id=1205>Shiverback-hide Leggings</a><li><a href=http://phobos/eq/item.php?id=1206>Shiverback-hide Boots</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Grandmaster Vohar </b>sneers coldly, his face contorting into a wretched, gruesome stare of hate. His eyes fill with an untamed, feral bloodlust as his low, hissing voice begins to seep from his throat. 'You stand within the district of Kartis -- the cradle of the seed of corruption in the universe. How strange it is that we find a child of the goodly mortal virtues willingly engaging in conversation with those they have sworn to destroy. I see that perhaps you feel yourself immune to the corruption, or that you will cast down your blade and use wit and the power of your 'pure' soul to overcome the shadow at its core. How amusing -- pathetically naive and vain, but amusing nonetheless. Learn from our adepts -- convince yourself it is a means to learn our secrets, if you will, but learn from us. You will serve us most efficiently without even a conscious awareness of your deeds.'</font>
<p><b>You give Grandmaster Vohar : </b><a href=http://phobos/eq/item.php?id=1201>Shiverback-hide Jerkin</a>
<br><b>Grandmaster Vohar says </b>'Thank you, [Your Name].'
<br><b>Grandmaster Vohar gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grandmaster Vohar says </b>'I don't need this.'
<p><b>You give Grandmaster Vohar : </b><a href=http://phobos/eq/item.php?id=1202>Shiverback-hide Armbands</a>
<br><b>Grandmaster Vohar says </b>'Thank you, [Your Name].'
<br><b>Grandmaster Vohar gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grandmaster Vohar says </b>'I don't need this.'
<p><b>You give Grandmaster Vohar : </b><a href=http://phobos/eq/item.php?id=1203>Shiverback-hide Wristbands</a>
<br><b>Grandmaster Vohar says </b>'Thank you, [Your Name].'
<br><b>Grandmaster Vohar gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grandmaster Vohar says </b>'I don't need this.'
<p><b>You give Grandmaster Vohar : </b><a href=http://phobos/eq/item.php?id=1204>Shiverback-hide Gloves</a>
<br><b>Grandmaster Vohar says </b>'Thank you, [Your Name].'
<br><b>Grandmaster Vohar gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grandmaster Vohar says </b>'I don't need this.'
<p><b>You give Grandmaster Vohar : </b><a href=http://phobos/eq/item.php?id=1205>Shiverback-hide Leggings</a>
<br><b>Grandmaster Vohar says </b>'Thank you, [Your Name].'
<br><b>Grandmaster Vohar gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grandmaster Vohar says </b>'I don't need this.'
<p><b>You give Grandmaster Vohar : </b><a href=http://phobos/eq/item.php?id=1206>Shiverback-hide Boots</a>
<br><b>Grandmaster Vohar says </b>'Thank you, [Your Name].'
<br><b>Grandmaster Vohar gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grandmaster Vohar says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Grandmaster Vohar says </b>'I don't need this.'
</td></tr></table>