<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1201>Shiverback-hide Jerkin</a><li><a href=http://phobos/eq/item.php?id=1202>Shiverback-hide Armbands</a><li><a href=http://phobos/eq/item.php?id=1203>Shiverback-hide Wristbands</a><li><a href=http://phobos/eq/item.php?id=1204>Shiverback-hide Gloves</a><li><a href=http://phobos/eq/item.php?id=1205>Shiverback-hide Leggings</a><li><a href=http://phobos/eq/item.php?id=1206>Shiverback-hide Boots</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Grandmaster Limsa </b>closes his eyes and gives a deep-seated bow before [Your Name]. 'Greetings, traveler. I am Grand Master Limsa, master of the tranquil order of the Tanaan district of the Plane of Knowledge. Monks of both Norrathian orders may approach me for guidance and knowledge through the long path of self-mastery and discipline.'</font>
<p><b>You give Grandmaster Limsa : </b><a href=http://phobos/eq/item.php?id=1201>Shiverback-hide Jerkin</a>
<br><b>Grandmaster Limsa says </b>'Thank you, [Your Name].'
<br><b>Grandmaster Limsa gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grandmaster Limsa says </b>'I don't need this.'
<p><b>You give Grandmaster Limsa : </b><a href=http://phobos/eq/item.php?id=1202>Shiverback-hide Armbands</a>
<br><b>Grandmaster Limsa says </b>'Thank you, [Your Name].'
<br><b>Grandmaster Limsa gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grandmaster Limsa says </b>'I don't need this.'
<p><b>You give Grandmaster Limsa : </b><a href=http://phobos/eq/item.php?id=1203>Shiverback-hide Wristbands</a>
<br><b>Grandmaster Limsa says </b>'Thank you, [Your Name].'
<br><b>Grandmaster Limsa gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grandmaster Limsa says </b>'I don't need this.'
<p><b>You give Grandmaster Limsa : </b><a href=http://phobos/eq/item.php?id=1204>Shiverback-hide Gloves</a>
<br><b>Grandmaster Limsa says </b>'Thank you, [Your Name].'
<br><b>Grandmaster Limsa gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grandmaster Limsa says </b>'I don't need this.'
<p><b>You give Grandmaster Limsa : </b><a href=http://phobos/eq/item.php?id=1205>Shiverback-hide Leggings</a>
<br><b>Grandmaster Limsa says </b>'Thank you, [Your Name].'
<br><b>Grandmaster Limsa gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grandmaster Limsa says </b>'I don't need this.'
<p><b>You give Grandmaster Limsa : </b><a href=http://phobos/eq/item.php?id=1206>Shiverback-hide Boots</a>
<br><b>Grandmaster Limsa says </b>'Thank you, [Your Name].'
<br><b>Grandmaster Limsa gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grandmaster Limsa says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Grandmaster Limsa says </b>'I don't need this.'
</td></tr></table>