<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1201>Shiverback-hide Jerkin</a><li><a href=http://phobos/eq/item.php?id=1202>Shiverback-hide Armbands</a><li><a href=http://phobos/eq/item.php?id=1203>Shiverback-hide Wristbands</a><li><a href=http://phobos/eq/item.php?id=1204>Shiverback-hide Gloves</a><li><a href=http://phobos/eq/item.php?id=1205>Shiverback-hide Leggings</a><li><a href=http://phobos/eq/item.php?id=1206>Shiverback-hide Boots</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Grandmaster Chendra </b>gives a deep-seated bow of respect and humble greetings. Her voice is gentle and calm, like the soothing melody of a grandmother with the youth of a newborn wind. 'Greetings, my friend, and may the light watch over your path. The district of Selia is one of light and upholds its virtues fervently, though we do not seek to impose upon others in our humble plane. You will find many whom, upon your world, are enemies but here, though they look upon you with disdain, are ultimately your equals in the quest for knowledge and enlightenment. If you are a student of the disciplines of the monk, then I shall lend my knowledge to you whenever you are in need of lessons in the martial skills of our order.'</font>
<p><b>You give Grandmaster Chendra : </b><a href=http://phobos/eq/item.php?id=1201>Shiverback-hide Jerkin</a>
<br><b>Grandmaster Chendra says </b>'Thank you, [Your Name].'
<br><b>Grandmaster Chendra gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grandmaster Chendra says </b>'I don't need this.'
<p><b>You give Grandmaster Chendra : </b><a href=http://phobos/eq/item.php?id=1202>Shiverback-hide Armbands</a>
<br><b>Grandmaster Chendra says </b>'Thank you, [Your Name].'
<br><b>Grandmaster Chendra gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grandmaster Chendra says </b>'I don't need this.'
<p><b>You give Grandmaster Chendra : </b><a href=http://phobos/eq/item.php?id=1203>Shiverback-hide Wristbands</a>
<br><b>Grandmaster Chendra says </b>'Thank you, [Your Name].'
<br><b>Grandmaster Chendra gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grandmaster Chendra says </b>'I don't need this.'
<p><b>You give Grandmaster Chendra : </b><a href=http://phobos/eq/item.php?id=1204>Shiverback-hide Gloves</a>
<br><b>Grandmaster Chendra says </b>'Thank you, [Your Name].'
<br><b>Grandmaster Chendra gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grandmaster Chendra says </b>'I don't need this.'
<p><b>You give Grandmaster Chendra : </b><a href=http://phobos/eq/item.php?id=1205>Shiverback-hide Leggings</a>
<br><b>Grandmaster Chendra says </b>'Thank you, [Your Name].'
<br><b>Grandmaster Chendra gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grandmaster Chendra says </b>'I don't need this.'
<p><b>You give Grandmaster Chendra : </b><a href=http://phobos/eq/item.php?id=1206>Shiverback-hide Boots</a>
<br><b>Grandmaster Chendra says </b>'Thank you, [Your Name].'
<br><b>Grandmaster Chendra gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grandmaster Chendra says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Grandmaster Chendra says </b>'I don't need this.'
</td></tr></table>