<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4841>Umbral Platemail Helm</a><li><a href=http://phobos/eq/item.php?id=4842>Umbral Platemail Breastplate</a><li><a href=http://phobos/eq/item.php?id=4843>Umbral Platemail Vambraces</a><li><a href=http://phobos/eq/item.php?id=4844>Umbral Platemail Bracer</a><li><a href=http://phobos/eq/item.php?id=4845>Umbral Platemail Gauntlets</a><li><a href=http://phobos/eq/item.php?id=4846>Umbral Platemail Greaves</a><li><a href=http://phobos/eq/item.php?id=4847>Umbral Platemail Boots</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Grave Lord Dreavud </b>peels back the upper right portion of his thin lips, giving a dark sneer of his gruesome features and horrific maw. 'You do not belong here! Return to Selia, where the light thrives. The shadow would embrace you, should you let it, but you are here for some righteous cause - one to destroy the shadow or learn of its secrets. You will find no success here, you pathetic little light crawler. Remain here and ignore my warning, and you will condemn yourself to consumption by the shadow should you further pursue its interests.'</font>
<p><b>You give Grave Lord Dreavud : </b><a href=http://phobos/eq/item.php?id=4841>Umbral Platemail Helm</a>
<br><b>Grave Lord Dreavud says </b>'Thank you, [Your Name].'
<br><b>Grave Lord Dreavud gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grave Lord Dreavud says </b>'I don't need this.'
<p><b>You give Grave Lord Dreavud : </b><a href=http://phobos/eq/item.php?id=4842>Umbral Platemail Breastplate</a>
<br><b>Grave Lord Dreavud says </b>'Thank you, [Your Name].'
<br><b>Grave Lord Dreavud gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grave Lord Dreavud says </b>'I don't need this.'
<p><b>You give Grave Lord Dreavud : </b><a href=http://phobos/eq/item.php?id=4843>Umbral Platemail Vambraces</a>
<br><b>Grave Lord Dreavud says </b>'Thank you, [Your Name].'
<br><b>Grave Lord Dreavud gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grave Lord Dreavud says </b>'I don't need this.'
<p><b>You give Grave Lord Dreavud : </b><a href=http://phobos/eq/item.php?id=4844>Umbral Platemail Bracer</a>
<br><b>Grave Lord Dreavud says </b>'Thank you, [Your Name].'
<br><b>Grave Lord Dreavud gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grave Lord Dreavud says </b>'I don't need this.'
<p><b>You give Grave Lord Dreavud : </b><a href=http://phobos/eq/item.php?id=4845>Umbral Platemail Gauntlets</a>
<br><b>Grave Lord Dreavud says </b>'Thank you, [Your Name].'
<br><b>Grave Lord Dreavud gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grave Lord Dreavud says </b>'I don't need this.'
<p><b>You give Grave Lord Dreavud : </b><a href=http://phobos/eq/item.php?id=4846>Umbral Platemail Greaves</a>
<br><b>Grave Lord Dreavud says </b>'Thank you, [Your Name].'
<br><b>Grave Lord Dreavud gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grave Lord Dreavud says </b>'I don't need this.'
<p><b>You give Grave Lord Dreavud : </b><a href=http://phobos/eq/item.php?id=4847>Umbral Platemail Boots</a>
<br><b>Grave Lord Dreavud says </b>'Thank you, [Your Name].'
<br><b>Grave Lord Dreavud gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grave Lord Dreavud says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Grave Lord Dreavud says </b>'I don't need this.'
</td></tr></table>