<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=5166>Greenmist Helm</a><li><a href=http://phobos/eq/item.php?id=5167>Greenmist Breastplate</a><li><a href=http://phobos/eq/item.php?id=5168>Greenmist Vambraces</a><li><a href=http://phobos/eq/item.php?id=5169>Greenmist Bracer</a><li><a href=http://phobos/eq/item.php?id=5171>Greenmist Greaves</a><li><a href=http://phobos/eq/item.php?id=5172>Greenmist Boots</a><li><a href=http://phobos/eq/item.php?id=5173>Greenmist Mask</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Grave Lord Vizurik </b>peels back the upper right portion of his thin lips, giving a dark sneer of his gruesome features and horrific maw. 'You do not belong here! Return to Selia, where the light thrives. The shadow would embrace you, should you let it, but you are here for some righteous cause - one to destroy the shadow or learn of its secrets. You will find no success here, you pathetic little light crawler. Remain here and ignore my warning, and you will condemn yourself to consumption by the shadow should you further pursue its interests.'</font>
<p><b>You give Grave Lord Vizurik : </b><a href=http://phobos/eq/item.php?id=5166>Greenmist Helm</a>
<br><b>Grave Lord Vizurik says </b>'Thank you, [Your Name].'
<br><b>Grave Lord Vizurik gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grave Lord Vizurik says </b>'I don't need this.'
<p><b>You give Grave Lord Vizurik : </b><a href=http://phobos/eq/item.php?id=5167>Greenmist Breastplate</a>
<br><b>Grave Lord Vizurik says </b>'Thank you, [Your Name].'
<br><b>Grave Lord Vizurik gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grave Lord Vizurik says </b>'I don't need this.'
<p><b>You give Grave Lord Vizurik : </b><a href=http://phobos/eq/item.php?id=5168>Greenmist Vambraces</a>
<br><b>Grave Lord Vizurik says </b>'Thank you, [Your Name].'
<br><b>Grave Lord Vizurik gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grave Lord Vizurik says </b>'I don't need this.'
<p><b>You give Grave Lord Vizurik : </b><a href=http://phobos/eq/item.php?id=5169>Greenmist Bracer</a>
<br><b>Grave Lord Vizurik says </b>'Thank you, [Your Name].'
<br><b>Grave Lord Vizurik gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grave Lord Vizurik says </b>'I don't need this.'
<p><b>You give Grave Lord Vizurik : </b><a href=http://phobos/eq/item.php?id=5171>Greenmist Greaves</a>
<br><b>Grave Lord Vizurik says </b>'Thank you, [Your Name].'
<br><b>Grave Lord Vizurik gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grave Lord Vizurik says </b>'I don't need this.'
<p><b>You give Grave Lord Vizurik : </b><a href=http://phobos/eq/item.php?id=5172>Greenmist Boots</a>
<br><b>Grave Lord Vizurik says </b>'Thank you, [Your Name].'
<br><b>Grave Lord Vizurik gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grave Lord Vizurik says </b>'I don't need this.'
<p><b>You give Grave Lord Vizurik : </b><a href=http://phobos/eq/item.php?id=5173>Greenmist Mask</a>
<br><b>Grave Lord Vizurik says </b>'Thank you, [Your Name].'
<br><b>Grave Lord Vizurik gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Grave Lord Vizurik says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Grave Lord Vizurik says </b>'I don't need this.'
</td></tr></table>