<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=3801>Vermiculated Crown</a><li><a href=http://phobos/eq/item.php?id=3802>Vermiculated Tunic</a><li><a href=http://phobos/eq/item.php?id=3803>Vermiculated Armplates</a><li><a href=http://phobos/eq/item.php?id=3804>Vermiculated Bracelet</a><li><a href=http://phobos/eq/item.php?id=3805>Vermiculated Gloves</a><li><a href=http://phobos/eq/item.php?id=3806>Vermiculated Leggings</a><li><a href=http://phobos/eq/item.php?id=3807>Vermiculated Boots</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Hierophant Trilawyth </b>gives a gentle bow of his head in respect toward [Your Name]. 'The district of Tanaan welcomes you, traveler. The adepts of the city have come together collectively and as individuals in hopes of aiding our visitors as we are able. In my time upon Norrath, I served as a child of nature dedicated to Tunare, the Mother of All. Though my faith has not wavered and my philosophies of nature have only grown in this astral city, I am able to train any druid who is in need of gaining a better grasp upon their skills. Mind you, however, that I am not a preacher and will not guide you through the instruction of faith or spell, for it is these things you must acquire and perfect through your own trials.'</font>
<p><b>You give Hierophant Trilawyth : </b><a href=http://phobos/eq/item.php?id=3801>Vermiculated Crown</a>
<br><b>Hierophant Trilawyth says </b>'Thank you, [Your Name].'
<br><b>Hierophant Trilawyth gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Hierophant Trilawyth says </b>'I don't need this.'
<p><b>You give Hierophant Trilawyth : </b><a href=http://phobos/eq/item.php?id=3802>Vermiculated Tunic</a>
<br><b>Hierophant Trilawyth says </b>'Thank you, [Your Name].'
<br><b>Hierophant Trilawyth gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Hierophant Trilawyth says </b>'I don't need this.'
<p><b>You give Hierophant Trilawyth : </b><a href=http://phobos/eq/item.php?id=3803>Vermiculated Armplates</a>
<br><b>Hierophant Trilawyth says </b>'Thank you, [Your Name].'
<br><b>Hierophant Trilawyth gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Hierophant Trilawyth says </b>'I don't need this.'
<p><b>You give Hierophant Trilawyth : </b><a href=http://phobos/eq/item.php?id=3804>Vermiculated Bracelet</a>
<br><b>Hierophant Trilawyth says </b>'Thank you, [Your Name].'
<br><b>Hierophant Trilawyth gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Hierophant Trilawyth says </b>'I don't need this.'
<p><b>You give Hierophant Trilawyth : </b><a href=http://phobos/eq/item.php?id=3805>Vermiculated Gloves</a>
<br><b>Hierophant Trilawyth says </b>'Thank you, [Your Name].'
<br><b>Hierophant Trilawyth gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Hierophant Trilawyth says </b>'I don't need this.'
<p><b>You give Hierophant Trilawyth : </b><a href=http://phobos/eq/item.php?id=3806>Vermiculated Leggings</a>
<br><b>Hierophant Trilawyth says </b>'Thank you, [Your Name].'
<br><b>Hierophant Trilawyth gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Hierophant Trilawyth says </b>'I don't need this.'
<p><b>You give Hierophant Trilawyth : </b><a href=http://phobos/eq/item.php?id=3807>Vermiculated Boots</a>
<br><b>Hierophant Trilawyth says </b>'Thank you, [Your Name].'
<br><b>Hierophant Trilawyth gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Hierophant Trilawyth says </b>'I don't need this.'
<br><b>Hierophant Trilawyth says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>