<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4881>Ethereal Mist Helm</a><li><a href=http://phobos/eq/item.php?id=4882>Ethereal Mist Chestplate</a><li><a href=http://phobos/eq/item.php?id=4883>Ethereal Mist Vambraces</a><li><a href=http://phobos/eq/item.php?id=4884>Ethereal Mist Bracers</a><li><a href=http://phobos/eq/item.php?id=4885>Ethereal Mist Gauntlets</a><li><a href=http://phobos/eq/item.php?id=4886>Ethereal Mist Greaves</a><li><a href=http://phobos/eq/item.php?id=4887>Ethereal Mist Boots</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>High Priest Vasil </b>closes his eyes and gives a deep, formal bow before [Your Name]. 'Welcome to Jeral, friend. I am Vasil, High Priest of Brell Serillis and resident master of the clerical arts in the district of Tanaan. If you have come in search of a mentor to guide you through the skills of your priesthood, then do not be discouraged by my own declaration of faith should it differ from yours. I cannot teach you how to know and be close to your deity in life, for only you may know that individually, but I can impart to you the fundamental basics that every priest, despite the object of their undying faith and devotion, wields in their life of service.'</font>
<p><b>You give High Priest Vasil : </b><a href=http://phobos/eq/item.php?id=4881>Ethereal Mist Helm</a>
<br><b>High Priest Vasil says </b>'Thank you, [Your Name].'
<br><b>High Priest Vasil gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give High Priest Vasil : </b><a href=http://phobos/eq/item.php?id=4882>Ethereal Mist Chestplate</a>
<br><b>High Priest Vasil says </b>'Thank you, [Your Name].'
<br><b>High Priest Vasil gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give High Priest Vasil : </b><a href=http://phobos/eq/item.php?id=4883>Ethereal Mist Vambraces</a>
<br><b>High Priest Vasil says </b>'Thank you, [Your Name].'
<br><b>High Priest Vasil gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give High Priest Vasil : </b><a href=http://phobos/eq/item.php?id=4884>Ethereal Mist Bracers</a>
<br><b>High Priest Vasil says </b>'Thank you, [Your Name].'
<br><b>High Priest Vasil gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give High Priest Vasil : </b><a href=http://phobos/eq/item.php?id=4885>Ethereal Mist Gauntlets</a>
<br><b>High Priest Vasil says </b>'Thank you, [Your Name].'
<br><b>High Priest Vasil gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give High Priest Vasil : </b><a href=http://phobos/eq/item.php?id=4886>Ethereal Mist Greaves</a>
<br><b>High Priest Vasil says </b>'Thank you, [Your Name].'
<br><b>High Priest Vasil gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give High Priest Vasil : </b><a href=http://phobos/eq/item.php?id=4887>Ethereal Mist Boots</a>
<br><b>High Priest Vasil says </b>'Thank you, [Your Name].'
<br><b>High Priest Vasil gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>High Priest Vasil says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>