<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28076>Collection of Taxidermy</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28237>Fine Antique Ring</a></ul></td><td><hr><b>When Holly Longtail spawns </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=202020>Strat</a></b> spawns (,-10,).</font>
<p><b>You say, </b>'Hail'
<br><b>Holly Longtail says </b>'Hello, [Your Name]. The preservation of ancestors is a time-honored tradition. It's a task one must handle with painstaking care and precision. Please do not fret for the lives of these specimens. They live in the eternal realm of beauty now. I have quite a large collection of stuffed animals ready to go, but many of them have sustained injuries in their capture. In fact, I wouldn't mind some help to collect some [replacement parts] from creatures around the world.'
<p><b>You say, </b>'replacement parts'
<br><b>Holly Longtail says </b>'Grab a Collector's Box from [Merri] before you go. You need to recover an Undead Froglok Tongue, Cockatrice Beak, High Quality Cougarskin, and a Tiny Rockhopper Eye. Seal the box tightly and return it to me. If the contents are in sufficient and usable condition, I may have a reward for you.'
<p><b>You say, </b>'Merri'
<br><b>Holly Longtail says </b>'Curator Merri is the founder of the museum in the Selia district of New Tanaan. She is a true visionary and a wonderful person as well. It is her dream to turn life's love into something truly grand. She also carries with her the Collector's Boxes. If you need one, be sure to ask her for it.'
<p><b>You give Holly Longtail : </b><a href=http://phobos/eq/item.php?id=28076>Collection of Taxidermy</a>
<br><font color=green><b>Holly Longtail </b>opens the box and carefully inspects its contents. 'These will do. Please accept this as a show of my appreciation. Now if you'll excuse me I have much work left to do.</font>
<br><b>Holly Longtail gives you : </b><a href=http://phobos/eq/item.php?id=28237>Fine Antique Ring</a>
<br><b>Holly Longtail says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>