<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=29112>Ethereal Parchment</a><li><a href=http://phobos/eq/item.php?id=29131>Spectral Parchment</a><li><a href=http://phobos/eq/item.php?id=29132>Glyphed Rune Word</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=21639>Spell: Aeldorb's Animation</a><li><a href=http://phobos/eq/item.php?id=28461>Spell: Uproar</a><li><a href=http://phobos/eq/item.php?id=21664>Spell: Vallon's Quickening</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Illusionist Jerup says </b>'Greetings traveler and welcome to the Plane of Knowledge! I am so pleased to see so many eager minds among us -- for it has been so long since I have had the meaningful presence of a pupil. If by chance you practice the art of Enchantments. then I might be of service to you. I have penned many spells from memory as a wandering enchanter and scholar of Norrath's history and though these spells are nothing unique or rare unto your world. they may provide some aid to you while you are here. Also. if you happen upon a seemingly meaningless item of arcane nature -- you will recognize these specific items I speak of by their corporeal state of existence -- then do not hesitate to take them up and return them to me. I know a thing or two regarding planar magic and can turn these seemingly mundane items into enchantments of great power.'
<p><b>You give Illusionist Jerup : </b><a href=http://phobos/eq/item.php?id=29112>Ethereal Parchment</a>
<br><font color=green><b>Illusionist Jerup </b></font>
<br><b>Illusionist Jerup gives you : </b><a href=http://phobos/eq/item.php?id=21639>Spell: Aeldorb's Animation</a>
<br><b>Illusionist Jerup says </b>'I don't need this.'
<p><b>You give Illusionist Jerup : </b><a href=http://phobos/eq/item.php?id=29131>Spectral Parchment</a>
<br><font color=green><b>Illusionist Jerup </b></font>
<br><b>Illusionist Jerup gives you : </b><a href=http://phobos/eq/item.php?id=28461>Spell: Uproar</a>
<br><b>Illusionist Jerup says </b>'I don't need this.'
<p><b>You give Illusionist Jerup : </b><a href=http://phobos/eq/item.php?id=29132>Glyphed Rune Word</a>
<br><font color=green><b>Illusionist Jerup </b></font>
<br><b>Illusionist Jerup gives you : </b><a href=http://phobos/eq/item.php?id=21664>Spell: Vallon's Quickening</a>
<br><b>Illusionist Jerup says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>