<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28792>Beginner Stealth Manual</a><li><a href=http://phobos/eq/item.php?id=29133>Rattican's Head</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28793>Intermediate Stealth Manual</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Leramas Feston says </b>'I see by the beginner manual you carry that you are on the right track. Let us continue your lessons, shall we? Bring me the Head of Rattican, who resides in the Plane of Disease.  Return this along with your Beginner Stealth Manual.'
<p><b>You say, </b>'Hail'
<br><b>Leramas Feston says </b>'I see by the beginner manual you carry that you are on the right track. Let us continue your lessons, shall we? Bring me the Head of Rattican, who resides in the Plane of Disease.  Return this along with your Beginner Stealth Manual.'
<p><b>You give Leramas Feston : </b><a href=http://phobos/eq/item.php?id=28792>Beginner Stealth Manual</a>, <a href=http://phobos/eq/item.php?id=29133>Rattican's Head</a>
<br><b>Leramas Feston says </b>'Very impressive, [Your Name]. This proves you have clearly graduated to the next phase of training we have to offer. Keep this book by your side and speak to Ethoach Trokith when you are ready for your next lesson.'
<br><b>Leramas Feston gives you : </b><a href=http://phobos/eq/item.php?id=28793>Intermediate Stealth Manual</a>
<br><b>Leramas Feston says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>