<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28080>Collection of Instruments</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28239>Fine Antique Amice</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Lohie Cantare says </b>'Greetings, [Your Name]. Have you come to see my exhibit? I am honored but also sad to say it is incomplete. Mine will be the finest presentation of musical history you will find, once I finish assembling my display. If you have some free time, perhaps you could help me collect some still missing [pieces]?'
<p><b>You say, </b>'pieces'
<br><b>Lohie Cantare says </b>''I need you to bring me a Minotaur Horn, Tambourine of Rituals, Orcish Lute of Singing, and a Stretched Skin Drum. If you could find these for me, I would be most overjoyed. You will need to get a Collector's Box from [Merri] to keep them in. Close the box up tightly and return it to me once you have placed the instruments inside. Hurry back and we shall have a grand festival!'
<p><b>You say, </b>'merri'
<br><b>Lohie Cantare says </b>'Curator Merri is the founder of the museum in the Selia district of New Tanaan. She is a true visionary and a wonderful person as well. It is her dream to turn life's love into something truly grand. She also carries with her the Collector's Boxes. If you need one, be sure to ask her for it.'
<p><b>You give Lohie Cantare : </b><a href=http://phobos/eq/item.php?id=28080>Collection of Instruments</a>
<br><font color=green><b>Lohie Cantare </b>inspects each instrument carefully. 'These are in much better condition then I thought I would get them in. Adding these to my exhibit pleases me greatly. As promised, here is something for you.'</font>
<br><b>Lohie Cantare gives you : </b><a href=http://phobos/eq/item.php?id=28239>Fine Antique Amice</a>
<br><b>Lohie Cantare says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>