<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=29112>Ethereal Parchment</a><li><a href=http://phobos/eq/item.php?id=29131>Spectral Parchment</a><li><a href=http://phobos/eq/item.php?id=29132>Glyphed Rune Word</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28475>Song: Melody of Mischief</a><li><a href=http://phobos/eq/item.php?id=28479>Song: Dreams of Terris</a><li><a href=http://phobos/eq/item.php?id=28486>Song: Lullaby of Morell</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Minstrel Eoweril says </b>'Hail and well met, my friend. New Tanaan greets you most warmly and is grateful to have you in our midst. All residents of this great Plane of Knowledge have come together in recent times with the unexpected, though warmly embraced presence of Norrathian visitors. We hope that we might be able to aid you in lending our wisdom and timeless knowledge wherever possible to your cause. I wish I could do more, my friend, but I am but a humble bard and my services may only benefit those of like profession. However, if you believe that my services could be of use, then do not hesitate to peruse my inventory and purchase what you will. If by chance you come across a curious parchment or other arcane item of seemingly unidentifiable purpose, then do not hesitate to bring it to me. Besides having composed many a song in my day, I do know a thing or two regarding mysteries of the planes' magics.'
<p><b>You give Minstrel Eoweril : </b><a href=http://phobos/eq/item.php?id=29112>Ethereal Parchment</a>
<br><font color=green><b>Minstrel Eoweril </b></font>
<br><b>Minstrel Eoweril gives you : </b><a href=http://phobos/eq/item.php?id=28475>Song: Melody of Mischief</a>
<br><b>Minstrel Eoweril says </b>'I don't need this.'
<p><b>You give Minstrel Eoweril : </b><a href=http://phobos/eq/item.php?id=29131>Spectral Parchment</a>
<br><font color=green><b>Minstrel Eoweril </b></font>
<br><b>Minstrel Eoweril gives you : </b><a href=http://phobos/eq/item.php?id=28479>Song: Dreams of Terris</a>
<br><b>Minstrel Eoweril says </b>'I don't need this.'
<p><b>You give Minstrel Eoweril : </b><a href=http://phobos/eq/item.php?id=29132>Glyphed Rune Word</a>
<br><font color=green><b>Minstrel Eoweril </b></font>
<br><b>Minstrel Eoweril gives you : </b><a href=http://phobos/eq/item.php?id=28486>Song: Lullaby of Morell</a>
<br><b>Minstrel Eoweril says </b>'I don't need this.'
<br><b>Minstrel Eoweril says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>