<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28088>Onirelin's Jewel</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28089>Cador's Artifact</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Onirelin Gali </b>peers you over carefully, studying you.  'Welcome and come in, stranger.  Are you here to simply look around or have you come to speak to my superior, Gunyth?  If so, you may find him upstairs. Watch your step, now.'</font>
<p><b>You say, </b>'artifact'
<br><font color=green><b>Onirelin Gali </b>pauses for a moment and continues, 'I am aware of that which Cador desires. Be wary of his ways for they are not always as they appear. Nevertheless, if he thinks this artifact will bring him greater peace, he may have it for a price. Certainly I have no use for it but what do I get in return? I'll tell you. Narik and I used to be good friends, until he became jealous of my relationship with his former companion Elisha. During our fight, he marched off with one of my finest jewels, and I believe still has it. Find him and ask for my jewel back. If you bring it to me, Cador may get want he wants as well.'</font>
<p><b>You give Onirelin Gali : </b><a href=http://phobos/eq/item.php?id=28088>Onirelin's Jewel</a>
<br><b>Onirelin Gali says </b>'How did you get this away from Narik? Oh never mind, I'm just happy to have it back. I shall give you what Cador desires now, keep it secure and deliver it to him.'
<br><b>Onirelin Gali gives you : </b><a href=http://phobos/eq/item.php?id=28089>Cador's Artifact</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Onirelin Gali says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>