<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4871>Rune Etched Helm</a><li><a href=http://phobos/eq/item.php?id=4872>Rune Etched Chestplate</a><li><a href=http://phobos/eq/item.php?id=4873>Rune Etched Vambraces</a><li><a href=http://phobos/eq/item.php?id=4884>Ethereal Mist Bracers</a><li><a href=http://phobos/eq/item.php?id=4874>Rune Etched Bracer</a><li><a href=http://phobos/eq/item.php?id=4875>Rune Etched Gauntlets</a><li><a href=http://phobos/eq/item.php?id=4876>Rune Etched Greaves</a><li><a href=http://phobos/eq/item.php?id=4877>Rune Etched Boots</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Oracle Maeth </b>makes a sweeping motion with his arms in an almost ritualistic fashion of greetings known only to those of the shamanistic world. 'We welcome you, friend, to the Tanaan district of the Plane of Knowledge. Beyond a seemingly endless fount of tangible supplies, the adepts of Jeral have come together and offered to retake our former duties as guildmasters and mentors to those of our art. In my life before New Tanaan's embrace of me, I served as one of many shamans of the Northmen, before Halas' walls were secured in the turmoil of the frozen north. As the years passed and years fell way to decades, I ascended to hold the seat of guild master of my order and have mentored countless shamans in my day. If you are in need of such knowledge, then please, do not hesitate in acquiring my aid.'</font>
<p><b>You give Oracle Maeth : </b><a href=http://phobos/eq/item.php?id=4871>Rune Etched Helm</a>
<br><b>Oracle Maeth says </b>'Thank you, [Your Name].'
<br><b>Oracle Maeth gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Oracle Maeth : </b><a href=http://phobos/eq/item.php?id=4872>Rune Etched Chestplate</a>
<br><b>Oracle Maeth says </b>'Thank you, [Your Name].'
<br><b>Oracle Maeth gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Oracle Maeth : </b><a href=http://phobos/eq/item.php?id=4873>Rune Etched Vambraces</a>
<br><b>Oracle Maeth says </b>'Thank you, [Your Name].'
<br><b>Oracle Maeth gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Oracle Maeth : </b><a href=http://phobos/eq/item.php?id=4884>Ethereal Mist Bracers</a>
<br><b>Oracle Maeth says </b>'Thank you, [Your Name].'
<br><b>Oracle Maeth gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Oracle Maeth : </b><a href=http://phobos/eq/item.php?id=4874>Rune Etched Bracer</a>
<br><b>Oracle Maeth says </b>'Thank you, [Your Name].'
<br><b>Oracle Maeth gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Oracle Maeth : </b><a href=http://phobos/eq/item.php?id=4875>Rune Etched Gauntlets</a>
<br><b>Oracle Maeth says </b>'Thank you, [Your Name].'
<br><b>Oracle Maeth gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Oracle Maeth : </b><a href=http://phobos/eq/item.php?id=4876>Rune Etched Greaves</a>
<br><b>Oracle Maeth says </b>'Thank you, [Your Name].'
<br><b>Oracle Maeth gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Oracle Maeth : </b><a href=http://phobos/eq/item.php?id=4877>Rune Etched Boots</a>
<br><b>Oracle Maeth says </b>'Thank you, [Your Name].'
<br><b>Oracle Maeth gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Oracle Maeth says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>