<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4871>Rune Etched Helm</a><li><a href=http://phobos/eq/item.php?id=4872>Rune Etched Chestplate</a><li><a href=http://phobos/eq/item.php?id=4873>Rune Etched Vambraces</a><li><a href=http://phobos/eq/item.php?id=4884>Ethereal Mist Bracers</a><li><a href=http://phobos/eq/item.php?id=4874>Rune Etched Bracer</a><li><a href=http://phobos/eq/item.php?id=4875>Rune Etched Gauntlets</a><li><a href=http://phobos/eq/item.php?id=4876>Rune Etched Greaves</a><li><a href=http://phobos/eq/item.php?id=4877>Rune Etched Boots</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Oracle Guwan </b>curls back his thin, reptilian-like lips, baring a two rows of jagged, unkempt teeth in a sinister sneer of hate. 'Little worm speaks? How quaint and disgusting you are, worm, and how pathetic. Begone from Kartis, little worm, you do not belong among the shadows. Your ears will melt when the shadow speaks the secrets of its mind and infinite memory. But. . . hehehe. . . but. yes. maybe you little worms think yourselves beyond the shadow's venomous tongue. . . maybe you are. . . heheheh. . . maybe you should stay, worm, and learn from Guwan. He knows much of the shadow's words, the shadow that taints and subdues the world of spirits to its will. Yes, stay worm, and learn from the shadow. . . see how. . . hehehehe. . . see how brave you truly are.'</font>
<p><b>You give Oracle Guwan : </b><a href=http://phobos/eq/item.php?id=4871>Rune Etched Helm</a>
<br><b>Oracle Guwan says </b>'Thank you, [Your Name].'
<br><b>Oracle Guwan gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Oracle Guwan : </b><a href=http://phobos/eq/item.php?id=4872>Rune Etched Chestplate</a>
<br><b>Oracle Guwan says </b>'Thank you, [Your Name].'
<br><b>Oracle Guwan gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Oracle Guwan : </b><a href=http://phobos/eq/item.php?id=4873>Rune Etched Vambraces</a>
<br><b>Oracle Guwan says </b>'Thank you, [Your Name].'
<br><b>Oracle Guwan gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Oracle Guwan : </b><a href=http://phobos/eq/item.php?id=4884>Ethereal Mist Bracers</a>
<br><b>Oracle Guwan says </b>'Thank you, [Your Name].'
<br><b>Oracle Guwan gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Oracle Guwan : </b><a href=http://phobos/eq/item.php?id=4874>Rune Etched Bracer</a>
<br><b>Oracle Guwan says </b>'Thank you, [Your Name].'
<br><b>Oracle Guwan gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Oracle Guwan : </b><a href=http://phobos/eq/item.php?id=4875>Rune Etched Gauntlets</a>
<br><b>Oracle Guwan says </b>'Thank you, [Your Name].'
<br><b>Oracle Guwan gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Oracle Guwan : </b><a href=http://phobos/eq/item.php?id=4876>Rune Etched Greaves</a>
<br><b>Oracle Guwan says </b>'Thank you, [Your Name].'
<br><b>Oracle Guwan gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Oracle Guwan : </b><a href=http://phobos/eq/item.php?id=4877>Rune Etched Boots</a>
<br><b>Oracle Guwan says </b>'Thank you, [Your Name].'
<br><b>Oracle Guwan gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Oracle Guwan says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>