<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1246>Insidious Halo</a><li><a href=http://phobos/eq/item.php?id=1247>Insidious Robe</a><li><a href=http://phobos/eq/item.php?id=1248>Insidious Sleeves</a><li><a href=http://phobos/eq/item.php?id=1249>Insidious Manacle</a><li><a href=http://phobos/eq/item.php?id=1250>Insidious Gloves</a><li><a href=http://phobos/eq/item.php?id=1251>Insidious Pantaloons</a><li><a href=http://phobos/eq/item.php?id=1252>Insidious Slippers</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Phantasmist Tairon </b>bows deeply in respect to [Your Name]. 'Good day to you and welcome to the Tanaan district of the Plane of Knowledge. The citizens of Tanaan are beings of neutrality and we strive to uphold our ways without the interference of the zealous. Do not take offense to this, my friend, for we view the same toward all sides of the coin who are extreme - those of extreme light and darkness alike are viewed warily. If you feel that our ways are not suitable for your cause in this city, then seek the district of Selia where the zealots of the light dwell respectfully without the interference of the other city’s districts. However, if you are able to yield your heart to our wishes only temporarily while in our midst, then we embrace you most warmly. The knowledge and supplies created by our adepts and craftsmen are at your disposal should you have a need of them.'</font>
<p><b>You give Phantasmist Tairon : </b><a href=http://phobos/eq/item.php?id=1246>Insidious Halo</a>
<br><b>Phantasmist Tairon says </b>'Thank you, [Your Name].'
<br><b>Phantasmist Tairon gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Phantasmist Tairon : </b><a href=http://phobos/eq/item.php?id=1247>Insidious Robe</a>
<br><b>Phantasmist Tairon says </b>'Thank you, [Your Name].'
<br><b>Phantasmist Tairon gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Phantasmist Tairon : </b><a href=http://phobos/eq/item.php?id=1248>Insidious Sleeves</a>
<br><b>Phantasmist Tairon says </b>'Thank you, [Your Name].'
<br><b>Phantasmist Tairon gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Phantasmist Tairon : </b><a href=http://phobos/eq/item.php?id=1249>Insidious Manacle</a>
<br><b>Phantasmist Tairon says </b>'Thank you, [Your Name].'
<br><b>Phantasmist Tairon gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Phantasmist Tairon : </b><a href=http://phobos/eq/item.php?id=1250>Insidious Gloves</a>
<br><b>Phantasmist Tairon says </b>'Thank you, [Your Name].'
<br><b>Phantasmist Tairon gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Phantasmist Tairon : </b><a href=http://phobos/eq/item.php?id=1251>Insidious Pantaloons</a>
<br><b>Phantasmist Tairon says </b>'Thank you, [Your Name].'
<br><b>Phantasmist Tairon gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Phantasmist Tairon : </b><a href=http://phobos/eq/item.php?id=1252>Insidious Slippers</a>
<br><b>Phantasmist Tairon says </b>'Thank you, [Your Name].'
<br><b>Phantasmist Tairon gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Phantasmist Tairon says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>