<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1246>Insidious Halo</a><li><a href=http://phobos/eq/item.php?id=1247>Insidious Robe</a><li><a href=http://phobos/eq/item.php?id=1248>Insidious Sleeves</a><li><a href=http://phobos/eq/item.php?id=1249>Insidious Manacle</a><li><a href=http://phobos/eq/item.php?id=1250>Insidious Gloves</a><li><a href=http://phobos/eq/item.php?id=1251>Insidious Pantaloons</a><li><a href=http://phobos/eq/item.php?id=1252>Insidious Slippers</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Phantasmist Abaur </b>closes his eyes and in a graceful motion, gives a low, sweeping bow. 'Greetings to you, friend, and welcome to the district of Selia. We are the beacon of light and justice, of all that is good and kind. As Tanaan is the cornerstone of neutrality, we are the shining jewel of righteousness, valor, and honor. I am Phantasmist Abaur and in my years upon Norrath, served as an enchanter within the arcane council of Freeport. Then, the city was in a fledgling state of being -- the Temple of Truth was still in the primordial beginnings of its construction and the city served mostly as a port rather than the functioning metropolis I'm told it has come to be today. If you practice the same art and require aid in learning the fundamental basic skills, then I will be more than pleased to oblige that necessity.'</font>
<p><b>You give Phantasmist Abaur : </b><a href=http://phobos/eq/item.php?id=1246>Insidious Halo</a>
<br><b>Phantasmist Abaur says </b>'Thank you, [Your Name].'
<br><b>Phantasmist Abaur gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Phantasmist Abaur : </b><a href=http://phobos/eq/item.php?id=1247>Insidious Robe</a>
<br><b>Phantasmist Abaur says </b>'Thank you, [Your Name].'
<br><b>Phantasmist Abaur gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Phantasmist Abaur : </b><a href=http://phobos/eq/item.php?id=1248>Insidious Sleeves</a>
<br><b>Phantasmist Abaur says </b>'Thank you, [Your Name].'
<br><b>Phantasmist Abaur gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Phantasmist Abaur : </b><a href=http://phobos/eq/item.php?id=1249>Insidious Manacle</a>
<br><b>Phantasmist Abaur says </b>'Thank you, [Your Name].'
<br><b>Phantasmist Abaur gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Phantasmist Abaur : </b><a href=http://phobos/eq/item.php?id=1250>Insidious Gloves</a>
<br><b>Phantasmist Abaur says </b>'Thank you, [Your Name].'
<br><b>Phantasmist Abaur gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Phantasmist Abaur : </b><a href=http://phobos/eq/item.php?id=1251>Insidious Pantaloons</a>
<br><b>Phantasmist Abaur says </b>'Thank you, [Your Name].'
<br><b>Phantasmist Abaur gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Phantasmist Abaur : </b><a href=http://phobos/eq/item.php?id=1252>Insidious Slippers</a>
<br><b>Phantasmist Abaur says </b>'Thank you, [Your Name].'
<br><b>Phantasmist Abaur gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Phantasmist Abaur says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>