<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1246>Insidious Halo</a><li><a href=http://phobos/eq/item.php?id=1247>Insidious Robe</a><li><a href=http://phobos/eq/item.php?id=1248>Insidious Sleeves</a><li><a href=http://phobos/eq/item.php?id=1249>Insidious Manacle</a><li><a href=http://phobos/eq/item.php?id=1250>Insidious Gloves</a><li><a href=http://phobos/eq/item.php?id=1251>Insidious Pantaloons</a><li><a href=http://phobos/eq/item.php?id=1252>Insidious Slippers</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Phantasmist Salkith </b>tilts his head back, a sneer crossing his features in unmasked disgust toward [Your Name]. 'What exactly are you doing here, [Your Name]? Don't you know that this is the district of Kartis -- the center of the shaded voice of mortal power in the known universe? Perhaps you stumbled into the darkness by accident -- but then, why would not your deity of pure light, justice, valor, and honor deter you from this place? Perhaps they have abandoned you, or perhaps you have been subject to the true face value of their illusion.'</font>
<br><font color=green><b>Phantasmist Salkith </b>ponders a moment, then continues. 'Yes, [Your Name], your god does not exist -- not as you think of them, for none of them care of you either way. Serve them with your life and go to the same place that all mortals go when they perish, despite their dogmatic affiliations. Indeed, I stand here on my own accord -- my faith is in myself and in my power and thus is how I fuel the shadow.  Perhaps this is a life more suited for you -- for it is a shame to see all that conviction and head-strong will go to waste, now isn't it?'</font>
<p><b>You give Phantasmist Salkith : </b><a href=http://phobos/eq/item.php?id=1246>Insidious Halo</a>
<br><b>Phantasmist Salkith says </b>'Thank you, [Your Name].'
<br><b>Phantasmist Salkith gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Phantasmist Salkith : </b><a href=http://phobos/eq/item.php?id=1247>Insidious Robe</a>
<br><b>Phantasmist Salkith says </b>'Thank you, [Your Name].'
<br><b>Phantasmist Salkith gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Phantasmist Salkith : </b><a href=http://phobos/eq/item.php?id=1248>Insidious Sleeves</a>
<br><b>Phantasmist Salkith says </b>'Thank you, [Your Name].'
<br><b>Phantasmist Salkith gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Phantasmist Salkith : </b><a href=http://phobos/eq/item.php?id=1249>Insidious Manacle</a>
<br><b>Phantasmist Salkith says </b>'Thank you, [Your Name].'
<br><b>Phantasmist Salkith gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Phantasmist Salkith : </b><a href=http://phobos/eq/item.php?id=1250>Insidious Gloves</a>
<br><b>Phantasmist Salkith says </b>'Thank you, [Your Name].'
<br><b>Phantasmist Salkith gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Phantasmist Salkith : </b><a href=http://phobos/eq/item.php?id=1251>Insidious Pantaloons</a>
<br><b>Phantasmist Salkith says </b>'Thank you, [Your Name].'
<br><b>Phantasmist Salkith gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Phantasmist Salkith : </b><a href=http://phobos/eq/item.php?id=1252>Insidious Slippers</a>
<br><b>Phantasmist Salkith says </b>'Thank you, [Your Name].'
<br><b>Phantasmist Salkith gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Phantasmist Salkith says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>