<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=29112>Ethereal Parchment</a><li><a href=http://phobos/eq/item.php?id=29131>Spectral Parchment</a><li><a href=http://phobos/eq/item.php?id=29132>Glyphed Rune Word</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28548>Spell: Spirit of Arag</a><li><a href=http://phobos/eq/item.php?id=21630>Spell: Frost Spear</a><li><a href=http://phobos/eq/item.php?id=28554>Spell: Ferocity</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Primalist Saosith says </b>'Welcome, traveler, to New Tanaan. All citizens of New Tanaan have come together in welcoming Norrath's curious travelers who crave knowledge and a path to better themselves individually. What little help I alone can offer is extended to the Beastlords of Norrath, for as I was once one of them in a time long since past. If you are a Beastlord, then perhaps what spells that I have penned, though neither unique nor rare to your world, would be of use. If through your endeavors upon the planes you happen to come across fledgling manuscripts -- similar to those upon which a spell or song is scribed -- then you may return them to me if you wish. I am quite versed in the ways of planar magics relating to the Beastlord's focus.'
<p><b>You give Primalist Saosith : </b><a href=http://phobos/eq/item.php?id=29112>Ethereal Parchment</a>
<br><font color=green><b>Primalist Saosith </b></font>
<br><b>Primalist Saosith gives you : </b><a href=http://phobos/eq/item.php?id=28548>Spell: Spirit of Arag</a>
<br><b>Primalist Saosith says </b>'I don't need this.'
<p><b>You give Primalist Saosith : </b><a href=http://phobos/eq/item.php?id=29131>Spectral Parchment</a>
<br><font color=green><b>Primalist Saosith </b></font>
<br><b>Primalist Saosith gives you : </b><a href=http://phobos/eq/item.php?id=21630>Spell: Frost Spear</a>
<br><b>Primalist Saosith says </b>'I don't need this.'
<p><b>You give Primalist Saosith : </b><a href=http://phobos/eq/item.php?id=29132>Glyphed Rune Word</a>
<br><font color=green><b>Primalist Saosith </b></font>
<br><b>Primalist Saosith gives you : </b><a href=http://phobos/eq/item.php?id=28554>Spell: Ferocity</a>
<br><b>Primalist Saosith says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>