<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=29173>Vallorian Discus Bones</a><li><a href=http://phobos/eq/item.php?id=29171>Nightmare Cichlid Bones</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=29175>Fisherman's Companion</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Ramos Jerwan says </b>'Good day traveler... perhaps you have come to help me with my studies?'
<p><b>You say, </b>'studies'
<br><b>Ramos Jerwan says </b>'It's quite simple really. I'm interested in studying some aquatic specimens from around the planes... will you take up your pole and give me a hand?'
<p><b>You say, </b>'hand'
<br><b>Ramos Jerwan says </b>'There are some particularly interesting cichlid swimming about in the Plane of Nightmare. I also hear the discus in the Plane of Valor are quite plentiful. I need you to bring me two sets of bones from each for study. You do know how to extract them, yes? If not, I believe the lovely Peras Glickon may have something that can instruct you. Best of luck lad.'
<p><b>You give Ramos Jerwan : </b><a href=http://phobos/eq/item.php?id=29173>Vallorian Discus Bones</a> x2, <a href=http://phobos/eq/item.php?id=29171>Nightmare Cichlid Bones</a> x2
<br><b>Ramos Jerwan says </b>'Ah, you've done quite well. Take this, it's a special gift I recovered from a recent adventure, and I can think of no greater person to keep it than you. Remember if you're in need of fishing supplies, come see us any time.'
<br><b>Ramos Jerwan gives you : </b><a href=http://phobos/eq/item.php?id=29175>Fisherman's Companion</a>
<br><b>Ramos Jerwan says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>