<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28083>Collection of Plants</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28238>Fine Antique Corset</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Randi Ellan says </b>'And a good morning to you as well, [Your Name]. I can see by the gleam in your eye you are interested in learning more about the flowers of Norrath. Sadly my exhibit is not much to speak of. I require new [specimens] to help build my collection.'
<p><b>You say, </b>'specimens'
<br><b>Randi Ellan says </b>'If you could find some for me, I would be ever so grateful. I need a Black Root, Maneater Bud, Yew Leaf, and a Twilight Orchid. If you should come across them, handle them with care. Be sure to get a Collector's Box from [Merri] to keep them in. Close the box and return it to me.'
<p><b>You say, </b>'Merri'
<br><b>Randi Ellan says </b>'Curator Merri is the founder of the museum in the Selia district of New Tanaan. She is a true visionary and a wonderful person as well. It is her dream to turn life's love into something truly grand. She also carries with her the Collector's Boxes. If you need one, be sure to ask her for it.'
<p><b>You give Randi Ellan : </b><a href=http://phobos/eq/item.php?id=28083>Collection of Plants</a>
<br><b>Randi Ellan says </b>'Plants and flowers are a special treasure I keep close to my heart. Did you ever stop to marvel at how beautiful these specimens are? I thank you greatly for them. Here, take this in return.'
<br><b>Randi Ellan gives you : </b><a href=http://phobos/eq/item.php?id=28238>Fine Antique Corset</a>
<br><b>Randi Ellan says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>