<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28077>Collection of Gems</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28235>Fine Antique Pelisse</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Renni Stone says </b>'Har har, [Your Name]! I see yer curious mind has brought ye to what will be the most fabulous and fascinating museum display of them all, the geological exhibit. Behold the [rocks] of Norrath! I'd be most delighted to show them to ye, eh, but I'm afraid it's not quite ready yet, you see. Some pieces of my collection have gone missing and I haven't gone to get replacements yet.'
<p><b>You say, </b>'rocks'
<br><b>Renni Stone says </b>'Eh, let's see. I'm missing a Whirling Crystal, A Scarlet Stone, Icy Geoduck, and A Pulsating Rock. Might ye have these on ye? If ye do, go and get a Collector's Box from [Merri], and put them inside. Close the box and bring it to me. The display will be most grand if ye do!'
<p><b>You say, </b>'Merri'
<br><b>Renni Stone says </b>'Curator Merri is the founder of the museum in the Selia district of New Tanaan. She is a true visionary and a wonderful person as well. It is her dream to turn life's love into something truly grand. She also carries with her the Collector's Boxes. If you need one, be sure to ask her for it.'
<p><b>You give Renni Stone : </b><a href=http://phobos/eq/item.php?id=28077>Collection of Gems</a>
<br><font color=green><b>Renni Stone </b>opens the box carefully and inspects the contents.  'These will do.  Thank ye.  Take this as a reward.'</font>
<br><b>Renni Stone gives you : </b><a href=http://phobos/eq/item.php?id=28235>Fine Antique Pelisse</a>
<br><b>Renni Stone says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>