<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=7817>Anthemion Wristguard</a><li><a href=http://phobos/eq/item.php?id=7818>Anthemion Boots</a><li><a href=http://phobos/eq/item.php?id=7819>Anthemion Leggings</a><li><a href=http://phobos/eq/item.php?id=7832>Anthemion Gloves</a><li><a href=http://phobos/eq/item.php?id=7833>Anthemion Jerkin</a><li><a href=http://phobos/eq/item.php?id=7834>Anthemion Armbands</a><li><a href=http://phobos/eq/item.php?id=7835>Anthemion Skullcap</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Savage Lord Etherat </b>performs an ancient, graceful gesture that is seemingly arcane in nature, though no energy can be felt entering or dispersing in the room. 'Tanaan welcomes you to its midst, traveler, There is much to be found in the whole of New Tanaan and specifically, the great library of Myrist. However, there is only so much that the tangible world can teach you. friend. for true, infinite knowledge lies eternally beyond the confines of material and astral domains. Within yourself. your very spirit and the spirits that surround you lays the key to true enlightenment and self-progress. Should you follow the path of the Beastlords. then I may be of aid in guiding your further toward the realization of your potential and the true elements surrounding you.'</font>
<p><b>You give Savage Lord Etherat : </b><a href=http://phobos/eq/item.php?id=7817>Anthemion Wristguard</a>
<br><b>Savage Lord Etherat says </b>'Thank you, [Your Name].'
<br><b>Savage Lord Etherat gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Savage Lord Etherat says </b>'I don't need this.'
<p><b>You give Savage Lord Etherat : </b><a href=http://phobos/eq/item.php?id=7818>Anthemion Boots</a>
<br><b>Savage Lord Etherat says </b>'Thank you, [Your Name].'
<br><b>Savage Lord Etherat gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Savage Lord Etherat says </b>'I don't need this.'
<p><b>You give Savage Lord Etherat : </b><a href=http://phobos/eq/item.php?id=7819>Anthemion Leggings</a>
<br><b>Savage Lord Etherat says </b>'Thank you, [Your Name].'
<br><b>Savage Lord Etherat gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Savage Lord Etherat says </b>'I don't need this.'
<p><b>You give Savage Lord Etherat : </b><a href=http://phobos/eq/item.php?id=7832>Anthemion Gloves</a>
<br><b>Savage Lord Etherat says </b>'Thank you, [Your Name].'
<br><b>Savage Lord Etherat gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Savage Lord Etherat says </b>'I don't need this.'
<p><b>You give Savage Lord Etherat : </b><a href=http://phobos/eq/item.php?id=7833>Anthemion Jerkin</a>
<br><b>Savage Lord Etherat says </b>'Thank you, [Your Name].'
<br><b>Savage Lord Etherat gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Savage Lord Etherat says </b>'I don't need this.'
<p><b>You give Savage Lord Etherat : </b><a href=http://phobos/eq/item.php?id=7834>Anthemion Armbands</a>
<br><b>Savage Lord Etherat says </b>'Thank you, [Your Name].'
<br><b>Savage Lord Etherat gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Savage Lord Etherat says </b>'I don't need this.'
<p><b>You give Savage Lord Etherat : </b><a href=http://phobos/eq/item.php?id=7835>Anthemion Skullcap</a>
<br><b>Savage Lord Etherat says </b>'Thank you, [Your Name].'
<br><b>Savage Lord Etherat gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Savage Lord Etherat says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Savage Lord Etherat says </b>'I don't need this.'
</td></tr></table>