<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=7817>Anthemion Wristguard</a><li><a href=http://phobos/eq/item.php?id=7818>Anthemion Boots</a><li><a href=http://phobos/eq/item.php?id=7819>Anthemion Leggings</a><li><a href=http://phobos/eq/item.php?id=7832>Anthemion Gloves</a><li><a href=http://phobos/eq/item.php?id=7833>Anthemion Jerkin</a><li><a href=http://phobos/eq/item.php?id=7834>Anthemion Armbands</a><li><a href=http://phobos/eq/item.php?id=7835>Anthemion Skullcap</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Savage Lord Cedrean </b>in an almost arcane motion, gives a mystic gesture of ancient greetings. 'The light of Selia shines upon you most brightly, [Your Name]. Be at ease, and know that all answers you seek will be delivered in time. The library of Myrist, though lacking the purity of the virtues we hold most dear to our selves in valiant memory of our mortal endeavors, is truly an unrivaled source of infinite knowledge. However, if you seek the comfort of your own light and goodly virtues, then Selia shall provide whatever it can to accommodate your needs while in our midst. Unfortunately, the ruling of the council has limited each individual citizen of the city to one particular specialty so that each have their equal opportunity to share their unique knowledge. In my former life, I was a master of the beasts and crusader of Mithaniel Marr. If you share the same profession as I and are in need of training, then I am more than pleased to oblige you.'</font>
<p><b>You give Savage Lord Cedrean : </b><a href=http://phobos/eq/item.php?id=7817>Anthemion Wristguard</a>
<br><b>Savage Lord Cedrean says </b>'Thank you, [Your Name].'
<br><b>Savage Lord Cedrean gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Savage Lord Cedrean says </b>'I don't need this.'
<p><b>You give Savage Lord Cedrean : </b><a href=http://phobos/eq/item.php?id=7818>Anthemion Boots</a>
<br><b>Savage Lord Cedrean says </b>'Thank you, [Your Name].'
<br><b>Savage Lord Cedrean gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Savage Lord Cedrean says </b>'I don't need this.'
<p><b>You give Savage Lord Cedrean : </b><a href=http://phobos/eq/item.php?id=7819>Anthemion Leggings</a>
<br><b>Savage Lord Cedrean says </b>'Thank you, [Your Name].'
<br><b>Savage Lord Cedrean gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Savage Lord Cedrean says </b>'I don't need this.'
<p><b>You give Savage Lord Cedrean : </b><a href=http://phobos/eq/item.php?id=7832>Anthemion Gloves</a>
<br><b>Savage Lord Cedrean says </b>'Thank you, [Your Name].'
<br><b>Savage Lord Cedrean gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Savage Lord Cedrean says </b>'I don't need this.'
<p><b>You give Savage Lord Cedrean : </b><a href=http://phobos/eq/item.php?id=7833>Anthemion Jerkin</a>
<br><b>Savage Lord Cedrean says </b>'Thank you, [Your Name].'
<br><b>Savage Lord Cedrean gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Savage Lord Cedrean says </b>'I don't need this.'
<p><b>You give Savage Lord Cedrean : </b><a href=http://phobos/eq/item.php?id=7834>Anthemion Armbands</a>
<br><b>Savage Lord Cedrean says </b>'Thank you, [Your Name].'
<br><b>Savage Lord Cedrean gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Savage Lord Cedrean says </b>'I don't need this.'
<p><b>You give Savage Lord Cedrean : </b><a href=http://phobos/eq/item.php?id=7835>Anthemion Skullcap</a>
<br><b>Savage Lord Cedrean says </b>'Thank you, [Your Name].'
<br><b>Savage Lord Cedrean gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Savage Lord Cedrean says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Savage Lord Cedrean says </b>'I don't need this.'
</td></tr></table>