<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=7817>Anthemion Wristguard</a><li><a href=http://phobos/eq/item.php?id=7818>Anthemion Boots</a><li><a href=http://phobos/eq/item.php?id=7819>Anthemion Leggings</a><li><a href=http://phobos/eq/item.php?id=7832>Anthemion Gloves</a><li><a href=http://phobos/eq/item.php?id=7833>Anthemion Jerkin</a><li><a href=http://phobos/eq/item.php?id=7834>Anthemion Armbands</a><li><a href=http://phobos/eq/item.php?id=7835>Anthemion Skullcap</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Savage Lord Dwev </b>growls lowly, the rumble from the depths of his throat akin to that of a starved tiger prepared to pounce upon its first prey. 'Yoo worm! Yoo worm stupidly come to shadow, and now shadow wants worm to be its slave. Worm shood stay and be shadow's slave, be Dwev's slave. Dwev teech worm how to rip spirits frum spirit world and make beasts worm's slaves, like worm be to Dwev! HAHA! Yes. Dwev smart! Dwev serve shadow faith. . . faithful. . . gud with new worm slave.'</font>
<p><b>You give Savage Lord Dwev : </b><a href=http://phobos/eq/item.php?id=7817>Anthemion Wristguard</a>
<br><b>Savage Lord Dwev says </b>'Thank you, [Your Name].'
<br><b>Savage Lord Dwev gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Savage Lord Dwev says </b>'I don't need this.'
<p><b>You give Savage Lord Dwev : </b><a href=http://phobos/eq/item.php?id=7818>Anthemion Boots</a>
<br><b>Savage Lord Dwev says </b>'Thank you, [Your Name].'
<br><b>Savage Lord Dwev gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Savage Lord Dwev says </b>'I don't need this.'
<p><b>You give Savage Lord Dwev : </b><a href=http://phobos/eq/item.php?id=7819>Anthemion Leggings</a>
<br><b>Savage Lord Dwev says </b>'Thank you, [Your Name].'
<br><b>Savage Lord Dwev gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Savage Lord Dwev says </b>'I don't need this.'
<p><b>You give Savage Lord Dwev : </b><a href=http://phobos/eq/item.php?id=7832>Anthemion Gloves</a>
<br><b>Savage Lord Dwev says </b>'Thank you, [Your Name].'
<br><b>Savage Lord Dwev gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Savage Lord Dwev says </b>'I don't need this.'
<p><b>You give Savage Lord Dwev : </b><a href=http://phobos/eq/item.php?id=7833>Anthemion Jerkin</a>
<br><b>Savage Lord Dwev says </b>'Thank you, [Your Name].'
<br><b>Savage Lord Dwev gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Savage Lord Dwev says </b>'I don't need this.'
<p><b>You give Savage Lord Dwev : </b><a href=http://phobos/eq/item.php?id=7834>Anthemion Armbands</a>
<br><b>Savage Lord Dwev says </b>'Thank you, [Your Name].'
<br><b>Savage Lord Dwev gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Savage Lord Dwev says </b>'I don't need this.'
<p><b>You give Savage Lord Dwev : </b><a href=http://phobos/eq/item.php?id=7835>Anthemion Skullcap</a>
<br><b>Savage Lord Dwev says </b>'Thank you, [Your Name].'
<br><b>Savage Lord Dwev gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Savage Lord Dwev says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Savage Lord Dwev says </b>'I don't need this.'
</td></tr></table>