<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1225>Carmine Turban</a><li><a href=http://phobos/eq/item.php?id=1226>Carmine Robe</a><li><a href=http://phobos/eq/item.php?id=1227>Carmine Sleeves</a><li><a href=http://phobos/eq/item.php?id=1228>Carmine Trinket</a><li><a href=http://phobos/eq/item.php?id=1229>Carmine Gloves</a><li><a href=http://phobos/eq/item.php?id=1230>Carmine Pants</a><li><a href=http://phobos/eq/item.php?id=1231>Carmine Boots</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Sorcerer Dogan </b>sneers darkly, revealing a row of unmanaged teeth beneath his grim visage. 'You travel too leniently, child of the light. Return to Selia, for you will find no welcoming here -- only darkness and shadow that would wish to consume you. However, if you are intent upon being among us, then by all means, do so at your own peril -- I care not for what fate befalls you and honestly, do not think you worthy of the shadow's service. Disregard my warnings if you must, but while you do so, do take the time to speak with the other adept minions of the shadow. They present most pressing arguments and will often give you the opportunity to learn from them the ways of their specific art. How marvelous it would be -- oh the irony indeed, that a child of the light would learn the ways of their craft from those whom they claim to detest! Aaaah. . . how you fuel us, and how we marvel at it.'</font>
<p><b>You give Sorcerer Dogan : </b><a href=http://phobos/eq/item.php?id=1225>Carmine Turban</a>
<br><b>Sorcerer Dogan says </b>'Thank you, [Your Name].'
<br><b>Sorcerer Dogan gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Sorcerer Dogan says </b>'I don't need this.'
<p><b>You give Sorcerer Dogan : </b><a href=http://phobos/eq/item.php?id=1226>Carmine Robe</a>
<br><b>Sorcerer Dogan says </b>'Thank you, [Your Name].'
<br><b>Sorcerer Dogan gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Sorcerer Dogan says </b>'I don't need this.'
<p><b>You give Sorcerer Dogan : </b><a href=http://phobos/eq/item.php?id=1227>Carmine Sleeves</a>
<br><b>Sorcerer Dogan says </b>'Thank you, [Your Name].'
<br><b>Sorcerer Dogan gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Sorcerer Dogan says </b>'I don't need this.'
<p><b>You give Sorcerer Dogan : </b><a href=http://phobos/eq/item.php?id=1228>Carmine Trinket</a>
<br><b>Sorcerer Dogan says </b>'Thank you, [Your Name].'
<br><b>Sorcerer Dogan gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Sorcerer Dogan says </b>'I don't need this.'
<p><b>You give Sorcerer Dogan : </b><a href=http://phobos/eq/item.php?id=1229>Carmine Gloves</a>
<br><b>Sorcerer Dogan says </b>'Thank you, [Your Name].'
<br><b>Sorcerer Dogan gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Sorcerer Dogan says </b>'I don't need this.'
<p><b>You give Sorcerer Dogan : </b><a href=http://phobos/eq/item.php?id=1230>Carmine Pants</a>
<br><b>Sorcerer Dogan says </b>'Thank you, [Your Name].'
<br><b>Sorcerer Dogan gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Sorcerer Dogan says </b>'I don't need this.'
<p><b>You give Sorcerer Dogan : </b><a href=http://phobos/eq/item.php?id=1231>Carmine Boots</a>
<br><b>Sorcerer Dogan says </b>'Thank you, [Your Name].'
<br><b>Sorcerer Dogan gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Sorcerer Dogan says </b>'I don't need this.'
<br><b>Sorcerer Dogan says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>