<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1225>Carmine Turban</a><li><a href=http://phobos/eq/item.php?id=1226>Carmine Robe</a><li><a href=http://phobos/eq/item.php?id=1227>Carmine Sleeves</a><li><a href=http://phobos/eq/item.php?id=1228>Carmine Trinket</a><li><a href=http://phobos/eq/item.php?id=1229>Carmine Gloves</a><li><a href=http://phobos/eq/item.php?id=1230>Carmine Pants</a><li><a href=http://phobos/eq/item.php?id=1231>Carmine Boots</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Sorcerer Farin </b>gives a deep, respectful nod of his head toward [Your Name]. 'Welcome, [Your Name]. I am Sorcerer Farin, ancient wizard of Erudin and head sorcerer of Selia. In light of your arrival, those who walk the path of light and hold the virtues of honor and justice high in their spirits. I offer my aid to any that would be so obliged as to accept it. In my former years, I was one of few guild masters in the newfound city of Erudin and what knowledge I have of that past is at your disposal.'</font>
<p><b>You give Sorcerer Farin : </b><a href=http://phobos/eq/item.php?id=1225>Carmine Turban</a>
<br><b>Sorcerer Farin says </b>'Thank you, [Your Name].'
<br><b>Sorcerer Farin gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Sorcerer Farin : </b><a href=http://phobos/eq/item.php?id=1226>Carmine Robe</a>
<br><b>Sorcerer Farin says </b>'Thank you, [Your Name].'
<br><b>Sorcerer Farin gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Sorcerer Farin : </b><a href=http://phobos/eq/item.php?id=1227>Carmine Sleeves</a>
<br><b>Sorcerer Farin says </b>'Thank you, [Your Name].'
<br><b>Sorcerer Farin gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Sorcerer Farin : </b><a href=http://phobos/eq/item.php?id=1228>Carmine Trinket</a>
<br><b>Sorcerer Farin says </b>'Thank you, [Your Name].'
<br><b>Sorcerer Farin gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Sorcerer Farin : </b><a href=http://phobos/eq/item.php?id=1229>Carmine Gloves</a>
<br><b>Sorcerer Farin says </b>'Thank you, [Your Name].'
<br><b>Sorcerer Farin gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Sorcerer Farin : </b><a href=http://phobos/eq/item.php?id=1230>Carmine Pants</a>
<br><b>Sorcerer Farin says </b>'Thank you, [Your Name].'
<br><b>Sorcerer Farin gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Sorcerer Farin : </b><a href=http://phobos/eq/item.php?id=1231>Carmine Boots</a>
<br><b>Sorcerer Farin says </b>'Thank you, [Your Name].'
<br><b>Sorcerer Farin gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Sorcerer Farin says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>