<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1225>Carmine Turban</a><li><a href=http://phobos/eq/item.php?id=1226>Carmine Robe</a><li><a href=http://phobos/eq/item.php?id=1227>Carmine Sleeves</a><li><a href=http://phobos/eq/item.php?id=1228>Carmine Trinket</a><li><a href=http://phobos/eq/item.php?id=1229>Carmine Gloves</a><li><a href=http://phobos/eq/item.php?id=1230>Carmine Pants</a><li><a href=http://phobos/eq/item.php?id=1231>Carmine Boots</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Sorcerer Kerynth </b>gives a gentle smile and polite bow of respect to [Your Name]. 'Greetings and welcome to the district of Tanaan, traveler. This place of neutrality is quite content to have you among us, learning from us what we humbly can teach you. Many adepts who were adventurers not too different from yourself have stepped forward and offered their memories as present lessons to those willing to learn of them. I myself was a master of the elements in my time, though I do not make this declaration as one that craves due respect for the title. Rather, I hope that you may perhaps be of the same path and if you need tutoring in the way of skills, then I would be more than pleased to oblige your needs.'</font>
<p><b>You give Sorcerer Kerynth : </b><a href=http://phobos/eq/item.php?id=1225>Carmine Turban</a>
<br><b>Sorcerer Kerynth says </b>'Thank you, [Your Name].'
<br><b>Sorcerer Kerynth gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Sorcerer Kerynth : </b><a href=http://phobos/eq/item.php?id=1226>Carmine Robe</a>
<br><b>Sorcerer Kerynth says </b>'Thank you, [Your Name].'
<br><b>Sorcerer Kerynth gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Sorcerer Kerynth : </b><a href=http://phobos/eq/item.php?id=1227>Carmine Sleeves</a>
<br><b>Sorcerer Kerynth says </b>'Thank you, [Your Name].'
<br><b>Sorcerer Kerynth gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Sorcerer Kerynth : </b><a href=http://phobos/eq/item.php?id=1228>Carmine Trinket</a>
<br><b>Sorcerer Kerynth says </b>'Thank you, [Your Name].'
<br><b>Sorcerer Kerynth gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Sorcerer Kerynth : </b><a href=http://phobos/eq/item.php?id=1229>Carmine Gloves</a>
<br><b>Sorcerer Kerynth says </b>'Thank you, [Your Name].'
<br><b>Sorcerer Kerynth gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Sorcerer Kerynth : </b><a href=http://phobos/eq/item.php?id=1230>Carmine Pants</a>
<br><b>Sorcerer Kerynth says </b>'Thank you, [Your Name].'
<br><b>Sorcerer Kerynth gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Sorcerer Kerynth : </b><a href=http://phobos/eq/item.php?id=1231>Carmine Boots</a>
<br><b>Sorcerer Kerynth says </b>'Thank you, [Your Name].'
<br><b>Sorcerer Kerynth gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Sorcerer Kerynth says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>