<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=22519>Sarnak Blood</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15958>Note from Tarerd</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Tarerd Gahar says </b>'I'm sorry, I have neither the time nor the patience to chat right now.'
<p><b>You say, </b>'pool'
<br><b>Tarerd Gahar says </b>'Oh Tatlan and Wicas sent you did they? I'll tell you what I told them, nothing is free. If you want to know about the pools then I need something [from you] first.'
<p><b>You say, </b>'from me'
<br><b>Tarerd Gahar says </b>'I'm sure it'll be easy for an adventurer as you. I am working on a potion, and I cannot currently travel to gather my last component. If you could bring me the blood of a Sarnak I'd be willing to share what I know.'
<p><b>You give Tarerd Gahar : </b><a href=http://phobos/eq/item.php?id=22519>Sarnak Blood</a>
<br><b>Tarerd Gahar says </b>'Ahh this is exactly what I was looking for. All the information I've gathered from these pools has come from Myrist. Thiran will give you the book I used as a reference. Give him this note so he knows I sent you.'
<br><b>Tarerd Gahar gives you : </b><a href=http://phobos/eq/item.php?id=15958>Note from Tarerd</a>
<br><b>Tarerd Gahar says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>