<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=16258>Hope Stone</a><li><a href=http://phobos/eq/item.php?id=28791>Advanced Combat Manual</a><li><a href=http://phobos/eq/item.php?id=28797>Advanced Magic Manual</a><li><a href=http://phobos/eq/item.php?id=28794>Advanced Stealth Manual</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28798>Secrets of the Planes</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Tenada Jeried says </b>'I am afraid I have little that I can talk about right now.  If you like you may speak to my [instructor] he can probably tell you about our work.'
<p><b>You say, </b>'who is your instructor?'
<br><b>Tenada Jeried says </b>'My instructor is Sage Balic; you will be able to find him upstairs.  Ask him about his research. I'm sure he would love to tell you about his work.'
<p><b>You give Tenada Jeried : </b><a href=http://phobos/eq/item.php?id=16258>Hope Stone</a>, <a href=http://phobos/eq/item.php?id=28791>Advanced Combat Manual</a>, <a href=http://phobos/eq/item.php?id=28797>Advanced Magic Manual</a>, <a href=http://phobos/eq/item.php?id=28794>Advanced Stealth Manual</a>
<br><b>Tenada Jeried says </b>'Take this [Your Name], and may it serve you well.'
<br><b>Tenada Jeried gives you : </b><a href=http://phobos/eq/item.php?id=28798>Secrets of the Planes</a>
<br><b>Tenada Jeried says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>