<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=15960>The Reflecting Pools of Tanaan</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=9321>Fine Cut, Diamond Inlaid Mask</a></ul></td><td><hr><b>When Tratlan Jowyr spawns </b>
<p><b>You say, </b>'Hail'
<br><font color=green><b>Tratlan Jowyr </b>looks deeply into the pool in front of him, 'Well darn it! I still can't see anything in this blasted [pool], can you Wicas?</font>
<p><b>You say, </b>'pool'
<br><font color=green><b>Tratlan Jowyr </b>glances up at you like he just noticed your presence, 'This pool. There is supposed to be strong [magic] in it.'</font>
<p><b>You say, </b>'magic'
<br><b>Tratlan Jowyr says </b>'Scrying magic. These pools can supposedly glance into all of the knowledge past, present, and future.'
<p><b>You give Tratlan Jowyr : </b><a href=http://phobos/eq/item.php?id=15960>The Reflecting Pools of Tanaan</a>
<br><font color=green><b>Tratlan Jowyr </b>leafs quickly through the book. 'Thank you, it will take quite some time to go through all the information here. Here is a little something for your troubles.'</font>
<br><b>Tratlan Jowyr gives you : </b><a href=http://phobos/eq/item.php?id=9321>Fine Cut, Diamond Inlaid Mask</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Tratlan Jowyr says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>