<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=15978>Merchant's Crate of Supplies</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17177>Empty Supplies Crate</a></ul></td><td><hr><b>When Trep Thilcan spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Trep Thilcan says </b>'Hi! You wouldn't be able to do a favor for a poor gnome would you?'
<p><b>You say, </b>'favor'
<br><b>Trep Thilcan says </b>'Well I am trying to setup a shop here, it is such a choice location! I am afraid if I leave though that nasty Halfling over there may steal my spot! She has been watching me keenly all day. I know she is just waiting for me to walk away. If you would go purchase some supplies for me from various locations around the world I would be able to reward you for your time spent. If you are ready to begin?'
<p><b>You say, </b>'begin'
<br><b>Trep Thilcan says </b>'Great! Here is a special crate. It needs to be filled with: A purification tablet from Freeport, A keg of beer from Qeynos, A ball of twine from Shadeweaver, A bundle of weapons from Firiona , An armor assortment from Thurgadin, and a case of meat from the Bazaar.  That should give me quite a stock of items to sell to travelers out here.'
<br><b>Trep Thilcan gives you : </b><a href=http://phobos/eq/item.php?id=17177>Empty Supplies Crate</a>
<p><b>You give Trep Thilcan : </b><a href=http://phobos/eq/item.php?id=15978>Merchant's Crate of Supplies</a>
<br><b>Trep Thilcan says </b>'Fantastic! You got me everything I need to set up shop. Here is some money for your troubles. I hoped you learned something as well. I am sorry I have nothing more to give you except this advice, if you combine: A clockwork carapace, A metal rod, Gnomish bolts, Firewater, and Grease ..in a Toolbox you should get something nice!'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 60pp
<br><b>Trep Thilcan says </b>'I don't need this.'
<br><b>Trep Thilcan says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>