<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>Vicar Qadar says </b>'Hello [Your Name], I can buff you with [Temperance], [Pure Blood] and my friend over there has 'chanter buffs.'
<br><font color=green><b>Vicar Qadar </b>waves at Nomaad</font>
<p><b>You say, </b>'hail'
<br><b>Vicar Qadar says </b>'Hello [Your Name], I can buff you with [Temperance], [Pure Blood] and my friend over there has 'chanter buffs.'
<br><font color=green><b>Vicar Qadar </b>waves at Nomaad</font>
<p><b>You say, </b>'Conviction'
<br><font color=brown><b>Vicar Qadar casts a spell on you : </b><a href=http://phobos/eq/spell.php?id=></a>.</font>
<br><b>Vicar Qadar says </b>'Casting Conviction, Good Hunting.'
<p><b>You say, </b>'Temperance'
<br><font color=brown><b>Vicar Qadar casts a spell : </b><a href=http://phobos/eq/spell.php?id=3692>Temperance</a>.</font>
<br><b>Vicar Qadar says </b>'Casting Temperance, Good hunting!'
<p><b>You say, </b>'Virtue'
<br><font color=brown><b>Vicar Qadar casts a spell on you : </b><a href=http://phobos/eq/spell.php?id=></a>.</font>
<br><b>Vicar Qadar says </b>'Casting Virtue, Good hunting!'
<p><b>You say, </b>'Pure Blood'
<br><font color=brown><b>Vicar Qadar casts a spell on you : </b><a href=http://phobos/eq/spell.php?id=></a>.</font>
<br><b>Vicar Qadar says </b>'Casting Pure Blood, Be Well!'
</td></tr></table>