<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4861>Imbrued Platemail Helm</a><li><a href=http://phobos/eq/item.php?id=4862>Imbrued Platemail Breastplate</a><li><a href=http://phobos/eq/item.php?id=4863>Imbrued Platemail Vambraces</a><li><a href=http://phobos/eq/item.php?id=4864>Imbrued Platemail Bracer</a><li><a href=http://phobos/eq/item.php?id=4865>Imbrued Platemail Gauntlets</a><li><a href=http://phobos/eq/item.php?id=4866>Imbrued Platemail Greaves</a><li><a href=http://phobos/eq/item.php?id=4867>Imbrued Platemail Boots</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Virtuoso Legilwan </b>gives a gentle, though formal nod of his head in warm greetings. 'Welcome, [Your Name], to the district of Tanaan. We have the utmost faith that this humble place will accommodate your every need most generously. The merchants in scattered throughout our region are quite useful to any tradesmen or adventurer seeking to restock on supplies and the devises of teleportation found in this district should be more than suitable for one of your ilk. If you have come to Tanaan seeking guidance in the ways of mentorship and skills, then know only success in your search for we are more than prepared to accommodate the needs of almost any adventurer. The bards of Norrath who seek guidance without the ravings of a philosophical, political, or religious zealot will find myself to be a most formidable suitor to their needs.'</font>
<p><b>You give Virtuoso Legilwan : </b><a href=http://phobos/eq/item.php?id=4861>Imbrued Platemail Helm</a>
<br><b>Virtuoso Legilwan says </b>'Thank you, [Your Name].'
<br><b>Virtuoso Legilwan gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Virtuoso Legilwan says </b>'I don't need this.'
<p><b>You give Virtuoso Legilwan : </b><a href=http://phobos/eq/item.php?id=4862>Imbrued Platemail Breastplate</a>
<br><b>Virtuoso Legilwan says </b>'Thank you, [Your Name].'
<br><b>Virtuoso Legilwan gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Virtuoso Legilwan says </b>'I don't need this.'
<p><b>You give Virtuoso Legilwan : </b><a href=http://phobos/eq/item.php?id=4863>Imbrued Platemail Vambraces</a>
<br><b>Virtuoso Legilwan says </b>'Thank you, [Your Name].'
<br><b>Virtuoso Legilwan gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Virtuoso Legilwan says </b>'I don't need this.'
<p><b>You give Virtuoso Legilwan : </b><a href=http://phobos/eq/item.php?id=4864>Imbrued Platemail Bracer</a>
<br><b>Virtuoso Legilwan says </b>'Thank you, [Your Name].'
<br><b>Virtuoso Legilwan gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Virtuoso Legilwan says </b>'I don't need this.'
<p><b>You give Virtuoso Legilwan : </b><a href=http://phobos/eq/item.php?id=4865>Imbrued Platemail Gauntlets</a>
<br><b>Virtuoso Legilwan says </b>'Thank you, [Your Name].'
<br><b>Virtuoso Legilwan gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Virtuoso Legilwan says </b>'I don't need this.'
<p><b>You give Virtuoso Legilwan : </b><a href=http://phobos/eq/item.php?id=4866>Imbrued Platemail Greaves</a>
<br><b>Virtuoso Legilwan says </b>'Thank you, [Your Name].'
<br><b>Virtuoso Legilwan gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Virtuoso Legilwan says </b>'I don't need this.'
<p><b>You give Virtuoso Legilwan : </b><a href=http://phobos/eq/item.php?id=4867>Imbrued Platemail Boots</a>
<br><b>Virtuoso Legilwan says </b>'Thank you, [Your Name].'
<br><b>Virtuoso Legilwan gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Virtuoso Legilwan says </b>'I don't need this.'
<br><b>Virtuoso Legilwan says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>