<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4861>Imbrued Platemail Helm</a><li><a href=http://phobos/eq/item.php?id=4862>Imbrued Platemail Breastplate</a><li><a href=http://phobos/eq/item.php?id=4863>Imbrued Platemail Vambraces</a><li><a href=http://phobos/eq/item.php?id=4864>Imbrued Platemail Bracer</a><li><a href=http://phobos/eq/item.php?id=4865>Imbrued Platemail Gauntlets</a><li><a href=http://phobos/eq/item.php?id=4866>Imbrued Platemail Greaves</a><li><a href=http://phobos/eq/item.php?id=4867>Imbrued Platemail Boots</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a></ul></td><td><p><b>You give Virtuoso Ciadus : </b><a href=http://phobos/eq/item.php?id=4861>Imbrued Platemail Helm</a>
<br><b>Virtuoso Ciadus says </b>'Thank you, [Your Name].'
<br><b>Virtuoso Ciadus gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Virtuoso Ciadus says </b>'I don't need this.'
<p><b>You give Virtuoso Ciadus : </b><a href=http://phobos/eq/item.php?id=4862>Imbrued Platemail Breastplate</a>
<br><b>Virtuoso Ciadus says </b>'Thank you, [Your Name].'
<br><b>Virtuoso Ciadus gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Virtuoso Ciadus says </b>'I don't need this.'
<p><b>You give Virtuoso Ciadus : </b><a href=http://phobos/eq/item.php?id=4863>Imbrued Platemail Vambraces</a>
<br><b>Virtuoso Ciadus says </b>'Thank you, [Your Name].'
<br><b>Virtuoso Ciadus gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Virtuoso Ciadus says </b>'I don't need this.'
<p><b>You give Virtuoso Ciadus : </b><a href=http://phobos/eq/item.php?id=4864>Imbrued Platemail Bracer</a>
<br><b>Virtuoso Ciadus says </b>'Thank you, [Your Name].'
<br><b>Virtuoso Ciadus gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Virtuoso Ciadus says </b>'I don't need this.'
<p><b>You give Virtuoso Ciadus : </b><a href=http://phobos/eq/item.php?id=4865>Imbrued Platemail Gauntlets</a>
<br><b>Virtuoso Ciadus says </b>'Thank you, [Your Name].'
<br><b>Virtuoso Ciadus gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Virtuoso Ciadus says </b>'I don't need this.'
<p><b>You give Virtuoso Ciadus : </b><a href=http://phobos/eq/item.php?id=4866>Imbrued Platemail Greaves</a>
<br><b>Virtuoso Ciadus says </b>'Thank you, [Your Name].'
<br><b>Virtuoso Ciadus gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Virtuoso Ciadus says </b>'I don't need this.'
<p><b>You give Virtuoso Ciadus : </b><a href=http://phobos/eq/item.php?id=4867>Imbrued Platemail Boots</a>
<br><b>Virtuoso Ciadus says </b>'Thank you, [Your Name].'
<br><b>Virtuoso Ciadus gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Virtuoso Ciadus says </b>'I don't need this.'
<br><b>Virtuoso Ciadus says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>