<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When Vuli Ironstove spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Vuli Ironstove says </b>'Welcome. traveler! The Ironstoves pride ourselves upon our goods. for no other baker in the whole of the cosmos can hold a candle to our quality. Please. search my inventory and if you do not find that which you are searching for. then search my brethren's stock. I guarantee that among the five of us. you will find the exact ingredient you seek.'
</td></tr></table>