<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4911>Indicolite Helm</a><li><a href=http://phobos/eq/item.php?id=4912>Indicolite Breastplate</a><li><a href=http://phobos/eq/item.php?id=4913>Indicolite Vambraces</a><li><a href=http://phobos/eq/item.php?id=4914>Indicolite Bracer</a><li><a href=http://phobos/eq/item.php?id=4915>Indicolite Gauntlets</a><li><a href=http://phobos/eq/item.php?id=4916>Indicolite Greaves</a><li><a href=http://phobos/eq/item.php?id=4917>Indicolite Boots</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Warlord Korehan </b>stands tall and in a stiff, well-trained mode, salutes [Your Name]. 'Welcome to the district of Selia. 'ere, ye will find that we all be children of light -- that virtues such as valor and justice are 'eld in the utmost respect and fervent reverence. Dinnae be fooled by our appearance, friend, fer we may differ in religions, but our focus be paralleled. If ye be a young warrior searchin' fer a mentor in the skills of the blade, then ye certaintly 'ave come t'the right man. If ye be of another art, then dinnae be discouraged, fer Selia 'olds many adepts and ye shall find one to suit ye in our midst.'</font>
<p><b>You give Warlord Korehan : </b><a href=http://phobos/eq/item.php?id=4911>Indicolite Helm</a>
<br><b>Warlord Korehan says </b>'Thank you, [Your Name].'
<br><b>Warlord Korehan gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Warlord Korehan says </b>'I don't need this.'
<p><b>You give Warlord Korehan : </b><a href=http://phobos/eq/item.php?id=4912>Indicolite Breastplate</a>
<br><b>Warlord Korehan says </b>'Thank you, [Your Name].'
<br><b>Warlord Korehan gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Warlord Korehan says </b>'I don't need this.'
<p><b>You give Warlord Korehan : </b><a href=http://phobos/eq/item.php?id=4913>Indicolite Vambraces</a>
<br><b>Warlord Korehan says </b>'Thank you, [Your Name].'
<br><b>Warlord Korehan gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Warlord Korehan says </b>'I don't need this.'
<p><b>You give Warlord Korehan : </b><a href=http://phobos/eq/item.php?id=4914>Indicolite Bracer</a>
<br><b>Warlord Korehan says </b>'Thank you, [Your Name].'
<br><b>Warlord Korehan gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Warlord Korehan says </b>'I don't need this.'
<p><b>You give Warlord Korehan : </b><a href=http://phobos/eq/item.php?id=4915>Indicolite Gauntlets</a>
<br><b>Warlord Korehan says </b>'Thank you, [Your Name].'
<br><b>Warlord Korehan gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Warlord Korehan says </b>'I don't need this.'
<p><b>You give Warlord Korehan : </b><a href=http://phobos/eq/item.php?id=4916>Indicolite Greaves</a>
<br><b>Warlord Korehan says </b>'Thank you, [Your Name].'
<br><b>Warlord Korehan gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Warlord Korehan says </b>'I don't need this.'
<p><b>You give Warlord Korehan : </b><a href=http://phobos/eq/item.php?id=4917>Indicolite Boots</a>
<br><b>Warlord Korehan says </b>'Thank you, [Your Name].'
<br><b>Warlord Korehan gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Warlord Korehan says </b>'I don't need this.'
<br><b>Warlord Korehan says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>