<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4911>Indicolite Helm</a><li><a href=http://phobos/eq/item.php?id=4912>Indicolite Breastplate</a><li><a href=http://phobos/eq/item.php?id=4913>Indicolite Vambraces</a><li><a href=http://phobos/eq/item.php?id=4914>Indicolite Bracer</a><li><a href=http://phobos/eq/item.php?id=4915>Indicolite Gauntlets</a><li><a href=http://phobos/eq/item.php?id=4916>Indicolite Greaves</a><li><a href=http://phobos/eq/item.php?id=4917>Indicolite Boots</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Warlord Welorf </b>gathers a deep breath, his body seeming unnaturally stiff within the large suit of iron. His cold, steely eyes glance over you once before addressing you in a low, baritone voice. 'You stand before Welorf, Warlord of the North and former chief of the Steel Warrior's clan. Should you be a warrior, the knowledge of my blade is at your reach and perhaps in time, and with some training, a proper warrior can borne of the weak creature I see before me.'</font>
<p><b>You give Warlord Welorf : </b><a href=http://phobos/eq/item.php?id=4911>Indicolite Helm</a>
<br><b>Warlord Welorf says </b>'Thank you, [Your Name].'
<br><b>Warlord Welorf gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Warlord Welorf says </b>'I don't need this.'
<p><b>You give Warlord Welorf : </b><a href=http://phobos/eq/item.php?id=4912>Indicolite Breastplate</a>
<br><b>Warlord Welorf says </b>'Thank you, [Your Name].'
<br><b>Warlord Welorf gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Warlord Welorf says </b>'I don't need this.'
<p><b>You give Warlord Welorf : </b><a href=http://phobos/eq/item.php?id=4913>Indicolite Vambraces</a>
<br><b>Warlord Welorf says </b>'Thank you, [Your Name].'
<br><b>Warlord Welorf gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Warlord Welorf says </b>'I don't need this.'
<p><b>You give Warlord Welorf : </b><a href=http://phobos/eq/item.php?id=4914>Indicolite Bracer</a>
<br><b>Warlord Welorf says </b>'Thank you, [Your Name].'
<br><b>Warlord Welorf gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Warlord Welorf says </b>'I don't need this.'
<p><b>You give Warlord Welorf : </b><a href=http://phobos/eq/item.php?id=4915>Indicolite Gauntlets</a>
<br><b>Warlord Welorf says </b>'Thank you, [Your Name].'
<br><b>Warlord Welorf gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Warlord Welorf says </b>'I don't need this.'
<p><b>You give Warlord Welorf : </b><a href=http://phobos/eq/item.php?id=4916>Indicolite Greaves</a>
<br><b>Warlord Welorf says </b>'Thank you, [Your Name].'
<br><b>Warlord Welorf gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Warlord Welorf says </b>'I don't need this.'
<p><b>You give Warlord Welorf : </b><a href=http://phobos/eq/item.php?id=4917>Indicolite Boots</a>
<br><b>Warlord Welorf says </b>'Thank you, [Your Name].'
<br><b>Warlord Welorf gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Warlord Welorf says </b>'I don't need this.'
<br><b>Warlord Welorf says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>