<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4911>Indicolite Helm</a><li><a href=http://phobos/eq/item.php?id=4912>Indicolite Breastplate</a><li><a href=http://phobos/eq/item.php?id=4913>Indicolite Vambraces</a><li><a href=http://phobos/eq/item.php?id=4914>Indicolite Bracer</a><li><a href=http://phobos/eq/item.php?id=4915>Indicolite Gauntlets</a><li><a href=http://phobos/eq/item.php?id=4916>Indicolite Greaves</a><li><a href=http://phobos/eq/item.php?id=4917>Indicolite Boots</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a><li><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Warlord Gligoth </b>glares coldly, his mouth twisted in a gruesome sneer of disgust. 'Kartis is place of shadow, not gud for light crawlers. But yu here, yu want something from shadow? Yes, yu want shadow to teach yu - yu want shadow to feed yu secrets, but yu will only fuel shadow's power in learning from it. If yu still want to stay in Kartis, then yu will only give power to shadow that yu say yu hate. I will teach yu, light crawler, if yu still tink yu can outsmart shadow's soldiers. I'll make that puny stick-thing yu light crawlers call weapons into fierce tools of war and no matter who dey kill, yu will kill in the shadow's name.'</font>
<p><b>You give Warlord Gligoth : </b><a href=http://phobos/eq/item.php?id=4911>Indicolite Helm</a>
<br><b>Warlord Gligoth says </b>'Thank you, [Your Name].'
<br><b>Warlord Gligoth gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Warlord Gligoth says </b>'I don't need this.'
<p><b>You give Warlord Gligoth : </b><a href=http://phobos/eq/item.php?id=4912>Indicolite Breastplate</a>
<br><b>Warlord Gligoth says </b>'Thank you, [Your Name].'
<br><b>Warlord Gligoth gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Warlord Gligoth says </b>'I don't need this.'
<p><b>You give Warlord Gligoth : </b><a href=http://phobos/eq/item.php?id=4913>Indicolite Vambraces</a>
<br><b>Warlord Gligoth says </b>'Thank you, [Your Name].'
<br><b>Warlord Gligoth gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Warlord Gligoth says </b>'I don't need this.'
<p><b>You give Warlord Gligoth : </b><a href=http://phobos/eq/item.php?id=4914>Indicolite Bracer</a>
<br><b>Warlord Gligoth says </b>'Thank you, [Your Name].'
<br><b>Warlord Gligoth gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Warlord Gligoth says </b>'I don't need this.'
<p><b>You give Warlord Gligoth : </b><a href=http://phobos/eq/item.php?id=4915>Indicolite Gauntlets</a>
<br><b>Warlord Gligoth says </b>'Thank you, [Your Name].'
<br><b>Warlord Gligoth gives you : </b><a href=http://phobos/eq/item.php?id=15981>Raw Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Warlord Gligoth says </b>'I don't need this.'
<p><b>You give Warlord Gligoth : </b><a href=http://phobos/eq/item.php?id=4916>Indicolite Greaves</a>
<br><b>Warlord Gligoth says </b>'Thank you, [Your Name].'
<br><b>Warlord Gligoth gives you : </b><a href=http://phobos/eq/item.php?id=10037>Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Warlord Gligoth says </b>'I don't need this.'
<p><b>You give Warlord Gligoth : </b><a href=http://phobos/eq/item.php?id=4917>Indicolite Boots</a>
<br><b>Warlord Gligoth says </b>'Thank you, [Your Name].'
<br><b>Warlord Gligoth gives you : </b><a href=http://phobos/eq/item.php?id=22503>Blue Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Warlord Gligoth says </b>'I don't need this.'
<br><b>Warlord Gligoth says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>