<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'tarerd'
<br><b>Wicas Adaolath says </b>'Tarerd is the one who told us about these pools. He wanted us to kill some sort of lizards for him, but we have neither the time nor energy for such adventures. Perhaps you can get some information about the pools from him.'
<br><b>Wicas Adaolath says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>