<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28092>New Sewing Needles</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28745>Planar Traveler's Manual</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Willamina says </b>'Hello and good morning. [Your Name].  It's such a lovely day to sit and enjoy the beautiful surroundings. is it not?  I do hope you find what you are looking for here. Not all of us have been so successful in our individual [quests].'
<p><b>You say, </b>'quests'
<br><b>Willamina says </b>'The city is full of curious people all searching for something. Many have struggled for a long time to find their reward. Some are not even aware of what is it they are looking for, but will know it when they see it. Would you care to [help] me out? It will only take a moment.'
<p><b>You say, </b>'help'
<br><b>Willamina says </b>'How wonderful! To pass the time I enjoy sitting under the trees and sewing together luscious fabrics. But now it seems my old sewing needles have all broke or gone dull, and I require a new supply. Bolcen Tendag has promised to purchase and deliver some for me, but he has not yet arrived and I worry about him. If you could locate him and ask him about the needles I would appreciate it.'
<p><b>You give Willamina : </b><a href=http://phobos/eq/item.php?id=28092>New Sewing Needles</a>
<br><font color=green><b>Willamina </b>takes the needles and smiles. 'Thank you so much, kind stranger. I can't tell you how much you have really helped by doing this for me. It's funny, you know. The entire city seems to be in a happier mood today. I can't quite put my finger on it, but everyone seems to have uplifted spirits. Oh well, thank you again. I have something you may find to be of use to you, if you would be interested. Remember, knowledge is the key to life.'</font>
<br><b>Willamina gives you : </b><a href=http://phobos/eq/item.php?id=28745>Planar Traveler's Manual</a>
<br><b>Willamina says </b>'I don't need this.'
<br><b>Willamina says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>