<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28788>Beginner Combat Manual</a><li><a href=http://phobos/eq/item.php?id=29145>Junk Beast Power Source</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28790>Intermediate Combat Manual</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Xasri Virek says </b>'I see by the beginner manual you carry that you are on the right track. Let us continue your lessons, shall we? Bring me the power source of the junk beast.  It resides in the Plane of Innovation.  Return this along with your Beginner Combat Manual.'
<p><b>You say, </b>'Hail'
<br><b>Xasri Virek says </b>'I see by the beginner manual you carry that you are on the right track. Let us continue your lessons, shall we? Bring me the power source of the junk beast.  It resides in the Plane of Innovation.  Return this along with your Beginner Combat Manual.'
<p><b>You give Xasri Virek : </b><a href=http://phobos/eq/item.php?id=28788>Beginner Combat Manual</a>, <a href=http://phobos/eq/item.php?id=29145>Junk Beast Power Source</a>
<br><b>Xasri Virek says </b>'Very impressive, [Your Name]. This proves you have clearly graduated to the next phase of training we have to offer. Keep this book by your side and speak to Gwiraba Gelrid when you are ready for your next lesson.'
<br><b>Xasri Virek gives you : </b><a href=http://phobos/eq/item.php?id=28790>Intermediate Combat Manual</a>
<br><b>Xasri Virek says </b>'I don't need this.'
<br><b>Xasri Virek says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>