<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1681>Engraved Ring</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=342>True Spirit</a></ul></td><td><p><b>You give #Neh-Ashiir : </b><a href=http://phobos/eq/item.php?id=1681>Engraved Ring</a>
<br><b>#Neh-Ashiir says </b>'Nothing is left to hide now. You shall have the truth. But truth is not won easily and if you cannot defeat me, you have not the ability to see that vengeance is served. Brace yourself!'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=342>True Spirit</a> has gotten better.</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=90181>#Neh`Ashiir_</a></b> spawns.</font>
<br><b>#Neh-Ashiir disappears.</b>
</td></tr></table>