<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When 90187 spawns </b>
<br><b>90187 says </b>'Young one, you cannot fathom how long it has been since I breathed air and felt flesh on my bones. I told you I would show you a weapon that would make you the most powerful of your kind. I said nothing of giving it to you. Feast your eyes on Innoruuk's Curse, mortal! Thank you for your service.'
<hr><b>When 90187 is killed </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=74089>Marl_Kastane</a></b> spawns (1.4,28.1,7).</font>
</td></tr></table>