<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=14384>Lhranc's Token</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=14383>Innoruuk's Curse</a></ul></td><td><p><b>You give Marl Kastane : </b><a href=http://phobos/eq/item.php?id=14384>Lhranc's Token</a>
<br><b>Marl Kastane says </b>'Very good, I will go deliver this right away.'
<br><b>Marl Kastane gives you : </b><a href=http://phobos/eq/item.php?id=14383>Innoruuk's Curse</a>
<br><b>Marl Kastane disappears.</b>
</td></tr></table>