<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10633>Dull Ruby</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10620>Enchanted Ruby</a></ul></td><td><p><b>You give Wraith of Jaxion : </b><a href=http://phobos/eq/item.php?id=10633>Dull Ruby</a>
<br><b>Wraith of Jaxion gives you : </b><a href=http://phobos/eq/item.php?id=10620>Enchanted Ruby</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>