<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=14519>Bark Potion</a><li><a href=http://phobos/eq/item.php?id=14512>Spring Crystal</a><li><a href=http://phobos/eq/item.php?id=14511>Harvest Crystal</a></ul></td><td><p><b>You say, </b>'Where is Bregun Dorey'
<br><b>Reothe says </b>'Bregun Dorey... I have not heard that name in many years. I will never forget it. He was very unique, always running around with an odd metal hat on. He swore that it would keep out the mind probing magics of the Question. I know where he was last seen, and I will tell you if you help by getting us some [supplies].'
<p><b>You say, </b>'what supplies'
<br><b>Reothe says </b>'Get me two Bark Potions, a Spring Crystal, and a Harvest Crystal. I will tell you where I last saw him headed. If you buy them in Sanctus Seru do not tell them you are giving aid to the Recuso or you shall be prosecuted as well.'
<p><b>You give Reothe : </b><a href=http://phobos/eq/item.php?id=14519>Bark Potion</a> x2, <a href=http://phobos/eq/item.php?id=14512>Spring Crystal</a>, <a href=http://phobos/eq/item.php?id=14511>Harvest Crystal</a>
<br><b>Reothe says </b>'This is great! We can treat our injured and have something to eat for weeks. I can vaguely recall Bregun heading towards the Lair of the Netherbians. You might ask a guard there if they have seen him.'
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>