<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28054>Shimmering Pearl</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17175>Zordak's Box of Bindings</a><li><a href=http://phobos/eq/item.php?id=28059>Swirling Pearl</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Zordak Ragefire </b>stares at you with unblinking eyes. A wide grin crosses Zordak's face and flames flicker in the depths of his eyes.</font>
<br><b>Zordak Ragefire says </b>'Welcome to the new fortress of the Plasmatic Priesthood! It's a shame about Lord Nagafen's untimely death, really it is! Such a powerful and noble creature should not perish at the hands of mortals.'
<p><b>You give Zordak Ragefire : </b><a href=http://phobos/eq/item.php?id=28054>Shimmering Pearl</a>
<br><font color=green><b>Zordak Ragefire </b>is engulfed by a shimmering blue light! An inhuman expression of rage crosses his face and flames leap in his eyes as he begins to vanish in the shimmering light! 'The Triumvirate may have succeeded in sending be back to my cursed homeland for the time being! I swear to you I shall return from Skyfire and destroy all of the Triumvirate Missionaries in flames!'</font>
<br><b>Zordak Ragefire gives you : </b><a href=http://phobos/eq/item.php?id=17175>Zordak's Box of Bindings</a>
<br><b>Zordak Ragefire gives you : </b><a href=http://phobos/eq/item.php?id=28059>Swirling Pearl</a>
<br><b>Zordak Ragefire disappears.</b>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>