<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28058>Head of Stanos</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2475>Guise of the Coercer</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=98>Fallen of Bloody Kithicor</a></ul></td><td><p><b>You say, </b>'Stanos'
<br><b>General V-ghera says </b>'Stanos? Stanos!! That dog, I WILL see him dead for what he cost me. Outcast I am, stripped of my position, my god has forsaken me, blaming ME for the loss of some tome. And you, [Your Name], you have aided him. For that, you will die first. Please, struggle and beg, I do so enjoy watching my victims squirm, and I have little joy left in my life now. If you want my favor, perhaps if you came bearing Stanos' head I would be more forgiving. But I doubt it.'
<p><b>You give General V-ghera : </b><a href=http://phobos/eq/item.php?id=28058>Head of Stanos</a>
<br><b>General V-ghera says </b>'Life is indeed sweet! Thank you, [Your Name], you have done me a great service this day. Take this, Stanos was kind enough to return it to me, and I have no use for it now. Know that you have the blessing of Innoruuk for this deed! But of course, I leave it to you to leave here alive. A leader has to feed his minions, you know.'
<br><b>General V-ghera gives you : </b><a href=http://phobos/eq/item.php?id=2475>Guise of the Coercer</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=98>Fallen of Bloody Kithicor</a> has gotten better.</font>
<br><b>General V-ghera disappears.</b>
<br><b>General V-ghera says </b>'The only object in this wretched world that I even desire is the bruised and bloodied head of that scoundrel, Stanos! Take this back!'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>