<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12321>Broken Bow Part B</a><li><a href=http://phobos/eq/item.php?id=12320>Broken Bow Part A</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=3190>Ivy Etched Gauntlets</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=182>Kithicor Residents</a><li><a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a><li><a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=347>Unkempt Druids</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Leaf Falldim says </b>'Greetings. [Your Name]!  Respect the woods and all its inhabitants or face the wrath of the rangers.  Do not end up like [Maldyn Greenburn].'
<p><b>You say, </b>'maldyn greenburn'
<br><b>Leaf Falldim says </b>'Maldyn was once one of us.  He was the finest of archers.  Everyone aspired to be like him.  He soon was tempted to hunt.  The animals of these woods found themselves nothing more than moving targets for Maldyn's training.  We held a trial and exiled him to parts unknown.  He would take with him Morin's [Bow of Kithicor].  I was asked to find a worthy ranger to [retrieve the bow].'
<p><b>You say, </b>'bow of kithicor'
<br><b>Leaf Falldim says </b>'The Bow of Kithicor was carved from an ancient tree. It has great powers which were but a portion of the tree's mana. I seek a brave ranger to [retrieve the bow].'
<p><b>You say, </b>'retrieve the bow'
<br><b>Leaf Falldim says </b>'Search the lands of the Unkempt Druids in the Rathe Mountains.  I have heard of his arrows being found inside its territories and  of his death wish to hunt down its leader.  Retrieve the bow and return it to me and I shall give you the ivy etched gauntlets.'
<p><b>You give Leaf Falldim : </b><a href=http://phobos/eq/item.php?id=12321>Broken Bow Part B</a>, <a href=http://phobos/eq/item.php?id=12320>Broken Bow Part A</a>
<br><b>Leaf Falldim gives you : </b><a href=http://phobos/eq/item.php?id=3190>Ivy Etched Gauntlets</a>
<br><b>Leaf Falldim says </b>'Very good, you have brought justice to these lands.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=182>Kithicor Residents</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=347>Unkempt Druids</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>