<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=16548>A strategic map of Kithicor</a><li><a href=http://phobos/eq/item.php?id=5405>Ebony Bladed Sword</a><li><a href=http://phobos/eq/item.php?id=20638>Sealed Ghoul Boss' Log Book</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=5422>Short Sword of Morin</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Morin Shadowbane says </b>'Hail, [Your Name]. I am the leader of this beleagured troop of rangers. Even though the once fair Kithicor slowly succumbs to the [darkness] at hand, we shall not abandon the woods without a fight.'
<p><b>You say, </b>'darkness'
<br><b>Morin Shadowbane says </b>'The denizens of these woods are slowly being overrun by dark fiends and shadowed men. As valiantly as we have fought, our numbers dwindle. We know very little about our aggressors, but if we [acquire some information] or perhaps [fine weapons], then we may yet have a chance to retake the woods once more.'
<p><b>You say, </b>'acquire some information'
<br><b>Morin Shadowbane says </b>'Your tracking skills are invaluable to our cause, brave [Your Name]. Our scouts have reported of a Ghoul Messenger. They have spotted him traveling between Kithicor and an undead camp in the Plains of Karana. They have attempted to track the monster and obtain any Strategic Domumentation he may be carrying. Perhaps you can succeed where others have failed. Perhaps you can earn my personal short sword.'
<p><b>You say, </b>'fine weapons'
<br><b>Morin Shadowbane says </b>'My soldiers are valiant, but poorly equipped. I have heard of a magical weapon of great power, some call it the Ebony Blade. Amongst the Froglocks there can be found a Minotaur who wields this sword of might. If you are a ranger and could provide me with this sword then I would gladly exchange it with my own meager weapon. If you prefer, you may attempt to [acquire some information] for us instead.'
<p><b>You say, </b>'another service'
<br><b>Morin Shadowbane says </b>'Very well then, your help will bring us closer to solving the mystery of Kithicor! Find Bryn Fynndel in Lesser Faydark and tell him Morin sent you. His band of elven warriors are observing the activities of the Crushbone Orcs and Mistmoore dark elves, perhaps you can help them shed some light on our plight.'
<p><b>You give Morin Shadowbane : </b><a href=http://phobos/eq/item.php?id=16548>A strategic map of Kithicor</a>
<br><b>Morin Shadowbane says </b>'Excellent work, [Your Name]!! It is obvious that you are a highly skilled tracker and warrior. Accept this reward, my personal sword which has served me well in countless battles.'
<br><b>Morin Shadowbane gives you : </b><a href=http://phobos/eq/item.php?id=5422>Short Sword of Morin</a>
<p><b>You give Morin Shadowbane : </b><a href=http://phobos/eq/item.php?id=5405>Ebony Bladed Sword</a>
<br><b>Morin Shadowbane says </b>'Excellent work, [Your Name]!! It is obvious that you are a highly skilled tracker and warrior. Accept this reward, my personal sword which has served me well in countless battles.'
<br><b>Morin Shadowbane gives you : </b><a href=http://phobos/eq/item.php?id=5422>Short Sword of Morin</a>
<p><b>You give Morin Shadowbane : </b><a href=http://phobos/eq/item.php?id=20638>Sealed Ghoul Boss' Log Book</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>