<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4766>Assorted Tailoring Supplies</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a><li><a href=http://phobos/eq/faction.php?id=152>House of Fordel</a><li><a href=http://phobos/eq/faction.php?id=153>House of Midst</a><li><a href=http://phobos/eq/faction.php?id=154>House of Stout</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Gearo says </b>'Hello there friend. My name is Gearo and as you can see I'm a Gnome, so what can I do for ya?'
<p><b>You say, </b>'take the gems'
<p><b>You give Gearo : </b><a href=http://phobos/eq/item.php?id=4766>Assorted Tailoring Supplies</a>
<br><b>Gearo says </b>'Ah you were sent from Steaon I see. So what's that tall drink of water up too? He must be busy at the store if he has you delivering his supplies for him. Well enough about all that. If he has trusted you to bring his supplies here I suppose I can give you these gems I picked up for him. Will you [take the gems] to him?'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=152>House of Fordel</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=153>House of Midst</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=154>House of Stout</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<br><b>Gearo says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>