<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10953>Large Shipment of High Quality Ore</a><li><a href=http://phobos/eq/item.php?id=10952>Small Shipment of High Quality Ore</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17814>Empty Ore Crate</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=152>House of Fordel</a><li><a href=http://phobos/eq/faction.php?id=153>House of Midst</a><li><a href=http://phobos/eq/faction.php?id=154>House of Stout</a><li><a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a></ul></td><td><hr><b>When Gliblixl Rocktok spawns </b>
<p><b>You say, </b>'hail'
<br><b>Gliblixl Rocktok says </b>'Hail [Your Name]! I sell the finest quality ore imported from the mines of Norrath! It's difficult to keep enough ore available with the demands of the local smiths however and could use some [assistance] in restocking my supplies.'
<p><b>You say, </b>'assistance'
<br><b>Gliblixl Rocktok says </b>'Hooray! Fill this crate with either four small bricks of unrefined ore or four large Bricks of unrefined ore from Norrath and I will pay you for your assistance in keeping me in business.'
<br><b>Gliblixl Rocktok gives you : </b><a href=http://phobos/eq/item.php?id=17814>Empty Ore Crate</a>
<p><b>You give Gliblixl Rocktok : </b><a href=http://phobos/eq/item.php?id=10953>Large Shipment of High Quality Ore</a>
<br><b>Gliblixl Rocktok says </b>'Thank you [Your Name]! I will prepare the ore for sale and be open for business again momentarily. Here is your payment for your services.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=152>House of Fordel</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=153>House of Midst</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=154>House of Stout</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a> has gotten better.</font>
<br><b>You receive </b> 44pp
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=151057>Gliblixl_Rocktok</a></b> spawns.</font>
<br><b>Gliblixl Rocktok disappears.</b>
<p><b>You give Gliblixl Rocktok : </b><a href=http://phobos/eq/item.php?id=10952>Small Shipment of High Quality Ore</a>
<br><b>Gliblixl Rocktok says </b>'Thank you [Your Name]! I will prepare the ore for sale and be open for business again momentarily. Here is your payment for your services.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=152>House of Fordel</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=153>House of Midst</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=154>House of Stout</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a> has gotten better.</font>
<br><b>You receive </b> 14pp
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=151057>Gliblixl_Rocktok</a></b> spawns.</font>
<br><b>Gliblixl Rocktok disappears.</b>
</td></tr></table>