<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=17900>Grandmaster's Satchel</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17138>Grandmaster's Carry-All</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Jolum says </b>'Hail! Nice to see ya, friend. I've got a fine selection of spankin' good spells, perhaps you'd be interested? Or maybe you'd like to learn how to [upgrade] your Grandmaster Trade items? Still yet, maybe you would like to know how to create a [Grandmaster's Medicine Bag]?'
<p><b>You say, </b>'upgrade'
<br><b>Jolum says </b>'What Grandmaster Trade item would you like to know how to upgrade? I can tell you how to upgrade your [Grandmaster Baker's Spoon], [Grandmaster Brewer's Corker], [Grandmaster Fletcher's Knife], [Grandmaster Jeweler's Eyeglass], [Grandmaster Potter's Sculpter], [Grandmaster Smith's Hammer], [Grandmaster Tailor's Needle], or your [Grandmaster Tinker's Spanner]. While you can't have more than one of the new items, they will summon a [bag] for you. Very useful for carrying heavy items about and such.'
<p><b>You say, </b>'bag'
<br><b>Jolum says </b>'Its a very sturdy bag, but I'm afraid that it's only temporary. If you'd like to get a more permanent bag, just hand me your summoned one and I'll trade it out you.'
<p><b>You give Jolum : </b><a href=http://phobos/eq/item.php?id=17900>Grandmaster's Satchel</a>
<br><b>Jolum says </b>'Here's a more permanent bag.'
<br><b>Jolum gives you : </b><a href=http://phobos/eq/item.php?id=17138>Grandmaster's Carry-All</a>
<br><b>Jolum says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>