<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=26055>Tattered Newsletter</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=26056>Sateals Economy Report</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a><li><a href=http://phobos/eq/faction.php?id=152>House of Fordel</a><li><a href=http://phobos/eq/faction.php?id=153>House of Midst</a><li><a href=http://phobos/eq/faction.php?id=154>House of Stout</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Sateal Deirosap says </b>'Hello there traveler. I have many wares for sale so please take a look at what I have. If you think all my goods are junk and wish to buy from someone else though I'll understand.'
<p><b>You give Sateal Deirosap : </b><a href=http://phobos/eq/item.php?id=26055>Tattered Newsletter</a>
<br><b>Sateal Deirosap says </b>'Ah great, I have been meaning to go and pick one of these up from the Trade Commissioner but I have been very busy with my work. I'm sure Henry has been waiting for my sales report so here it is. Please return it to him for me if you could and thanks again!'
<br><font color=green><b>Sateal Deirosap </b>gives you a Sales Report.</font>
<br><b>Sateal Deirosap gives you : </b><a href=http://phobos/eq/item.php?id=26056>Sateals Economy Report</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=152>House of Fordel</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=153>House of Midst</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=154>House of Stout</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Sateal Deirosap says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>