<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18833>A Sealed Letter</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17917>Peacekeeper Staff</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=103>Followers of Korucust</a><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Emil Parsini says </b>'Good to meet you. [Your Name].  Please look around.  I have much to offer.  I am a master woodworker.  It runs in the Parsini family.'
<p><b>You give Emil Parsini : </b><a href=http://phobos/eq/item.php?id=18833>A Sealed Letter</a>
<br><b>Emil Parsini says </b>'I have been waiting for someone to come and retrieve this staff.  Here you are.  You will have to combine it with treant resin and an Odus pearl.  You can find Odus pearls in the water in the harbor. As for the resin. I can make it if you can find me some treant shards.  Maybe another woodworker or cobbler in Qeynos has some.'
<br><b>Emil Parsini gives you : </b><a href=http://phobos/eq/item.php?id=17917>Peacekeeper Staff</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=103>Followers of Korucust</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
</td></tr></table>