<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17051>Soulcase</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Knarthenne Skurl says </b>'Ah, you do not possess the heart of an innocent. Be gone with you!'
<p><b>You say, </b>'heart of an innocent'
<br><b>Knarthenne Skurl says </b>'What's that? Heart of the Innocent, you say?! Ages, it has been, since I was last asked that. The Heart of the Innocent is an item of great power. Few are they who have ever commanded the dark magic of such an object. It is the bound soul of a pure mortal, rare indeed. Take this hollow gem, and combine with it the heart of one who is pure. If your hand is steady and your mind is clear, you shall have what you seek.'
<br><b>Knarthenne Skurl gives you : </b><a href=http://phobos/eq/item.php?id=17051>Soulcase</a>
</td></tr></table>