<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=6069>Packaged Research Notes</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1573>Ring of the Messenger</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Lanivon Baxer says </b>'Greetings, [Your Name]. Safe travels to you.'
<p><b>You give Lanivon Baxer : </b><a href=http://phobos/eq/item.php?id=6069>Packaged Research Notes</a>
<br><b>Lanivon Baxer says </b>'Excellent work! Thank you for delivering this to me. I will get it to the High Council as soon as possible. Take this Ring of the Messenger as an insignia of your service to the city.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Lanivon Baxer gives you : </b><a href=http://phobos/eq/item.php?id=1573>Ring of the Messenger</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>