<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10179>Maid Issis Fang</a><li><a href=http://phobos/eq/item.php?id=10178>Butler Syncalls Fang</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=5408>Electrum-Bladed Wakizashi</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>an avenging caitiff </b>an avenging caitiff glares at you with fangs bared as he draws an electrum-bladed wakizashi.</font>
<p><b>You say, </b>'electrum-bladed wakizashi'
<br><b>an avenging caitiff says </b>'HA! As if a mortal such as yourself is worthy of such a weapon. Leave me to my mission - my purpose in life - the slaying of those who brought me into this existence, then exiled me from this place.'
<p><b>You say, </b>'mother'
<br><b>an avenging caitiff says </b>'My mother was named Issis. She is, to my knowledge, employed as Lord Mistmoores maid.'
<p><b>You say, </b>'father'
<br><b>an avenging caitiff says </b>'Syncall is my fathers name. He serves as Lord Mistmoores butler.'
<p><b>You give an avenging caitiff : </b><a href=http://phobos/eq/item.php?id=10179>Maid Issis Fang</a>, <a href=http://phobos/eq/item.php?id=10178>Butler Syncalls Fang</a>
<br><b>an avenging caitiff gives you : </b><a href=http://phobos/eq/item.php?id=5408>Electrum-Bladed Wakizashi</a>
<br><b>an avenging caitiff says </b>'Mother? Father? May you find peace at last. I shall avenge your suffering! I will grow stronger and set free the souls of the others.'
<br><font color=yellow>You gain experience!!</font>
<br><b>an avenging caitiff says </b>'I have no need of these items, [Your Name].'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>