<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=21972>Symbol of the Brotherhood</a><li><a href=http://phobos/eq/item.php?id=21973>Brownie Torso</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Eirod Haerod says </b>'Hello [Your Name], you are definitely a newcomer to my castle. What brings you before me today? I have some [urgent matters] to attend too.'
<p><b>You say, </b>'urgent matters'
<br><b>Eirod Haerod says </b>'Well you see, I am in charge of all [documents] here for Castle Mistmoore. I have a very important job and I would like to think that I do it well.'
<p><b>You say, </b>'documents'
<br><b>Eirod Haerod says </b>'Many documents of war and other not so pleasant matters. I was wondering if you have anything important to say or are you just going to stand here and ask me questions all day. I am waiting for a delivery [from the Indigo Brotherhood].'
<p><b>You say, </b>'from the Indigo Brotherhood'
<br><b>Eirod Haerod says </b>'I am afraid I don't believe you, anyone sent by the brotherhood would most certainly bear the appropriate symbol. Leave my presence now before I get upset. I will not ask you again.'
<p><b>You say, </b>'missing'
<br><b>Eirod Haerod says </b>'I am afraid I don't believe you, anyone sent by the brotherhood would most certainly bear the appropriate symbol. Leave my presence now before I get upset. I will not ask you again.'
<p><b>You say, </b>'war scripts'
<br><b>Eirod Haerod says </b>'I am afraid I don't believe you, anyone sent by the brotherhood would most certainly bear the appropriate symbol. Leave my presence now before I get upset. I will not ask you again.'
<p><b>You give Eirod Haerod : </b><a href=http://phobos/eq/item.php?id=21972>Symbol of the Brotherhood</a>
<br><b>Eirod Haerod says </b>'I see you must be trusted by the brotherhood to get this far. Well I would imagine that you are here to deliver [Gerod's] documents are you not? I have heard rumors of him also being [missing], I certainly hope those rumors were unfounded.'
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<p><b>You give Eirod Haerod : </b><a href=http://phobos/eq/item.php?id=21973>Brownie Torso</a> x2
<br><b>Eirod Haerod says </b>'I don't need this.'
<br><b>Eirod Haerod says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>