<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=14362>A Flower</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=14364>A Scepter</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=320>Temple of Solusek Ro</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=291>Shadowed Men</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Ssynthi says </b>' I am Ssynthi, [Warder of Ro]. Would you do a simple [service] for me?'
<p><b>You say, </b>'warder of ro'
<br><b>Ssynthi says </b>'I have renounced my ties to the Shadowed Men and become a follower of the one True Flame, Solusek Ro. I have hopes that one day my brethren will see the errors of their ways and cease their mindless war.'
<p><b>You say, </b>'service'
<br><b>Ssynthi says </b>'The body of my true love lies within this tomb. I see a token to remember her by the flower which lies atop her coffin. I would get it myself, but the tomb is warded against my kind. Since I can not enter, I ask you to fetch it for me. '
<p><b>You give Ssynthi : </b><a href=http://phobos/eq/item.php?id=14362>A Flower</a>
<br><b>Ssynthi says </b>'Thank you. Since you have done me a service with no thought of reward, I offer you this small token of my favor.'
<br><b>Ssynthi gives you : </b><a href=http://phobos/eq/item.php?id=14364>A Scepter</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=320>Temple of Solusek Ro</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=291>Shadowed Men</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>