<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=55252>Brain-Scorched Goblin Head</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=55240>Enchanted Lava Spider Blood</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=341>Tribe Vrodak</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=120>Goblins of Fire Peak</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>#Hunter Gitog </b>growls as you approach. 'Do not attack. I wish to speak with you.' Gitog leans forward and sniffs the air. 'Yes you are powerful. [Help] me, and I will help you.'</font>
<p><b>You say, </b>'help'
<br><font color=green><b>#Hunter Gitog </b>'s lips curl into a snarl. 'I do not normally associate with outsiders, but we have a problem and you seem strong enough to assist us. Our hunting grounds have recently been overtaken by a dangerous group of [fire goblins]. These are no ordinary fire goblins however.'</font>
<p><b>You say, </b>'fire goblins'
<br><b>#Hunter Gitog says </b>'They were once members of the Taklasinai fire goblin tribe that lair further within the caverns. However they fed upon the flesh of the spiders that live in the caves. The spider flesh is poisonous. It burns the brain causing madness and rage. These fire goblins are out of control. They attack any who venture near them. They have recently attacked several members of our tribe in our hunting grounds. If you [assist] us in stopping them, you will be rewarded.'
<p><b>You say, </b>'assist'
<br><b>#Hunter Gitog says </b>'I will reward you for every four brain-scorched goblin heads you bring to me.'
<p><b>You give #Hunter Gitog : </b><a href=http://phobos/eq/item.php?id=55252>Brain-Scorched Goblin Head</a> x4
<br><b>#Hunter Gitog says </b>'These will be no more threat.  Take this, [Your Name].'
<br><font color=yellow>You gain experience!!</font>
<br><b>#Hunter Gitog gives you : </b><a href=http://phobos/eq/item.php?id=55240>Enchanted Lava Spider Blood</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=341>Tribe Vrodak</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=120>Goblins of Fire Peak</a> has gotten worse.</font>
<br><b>#Hunter Gitog says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>