<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=55252>Brain-Scorched Goblin Head</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=55240>Enchanted Lava Spider Blood</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=120>Goblins of Fire Peak</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=341>Tribe Vrodak</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>#Kiliki says </b>'Bring me the heads of brain scorched goblins and I will reward you, [Your Name].'
<p><b>You give #Kiliki : </b><a href=http://phobos/eq/item.php?id=55252>Brain-Scorched Goblin Head</a> x4
<br><b>#Kiliki says </b>'These will be no more threat.  Take this, [Your Name].'
<br><font color=yellow>You gain experience!!</font>
<br><b>#Kiliki gives you : </b><a href=http://phobos/eq/item.php?id=55240>Enchanted Lava Spider Blood</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=120>Goblins of Fire Peak</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=341>Tribe Vrodak</a> has gotten worse.</font>
<br><b>#Kiliki says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>