<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'greenmist'
<br><b>a spectral crusader says </b>'Mighty was the mist which covered the land. Mighty is the blade wielded by a crusader.'
<p><b>You say, </b>'golin'
<br><font color=green><b>a spectral crusader </b>swipes his hand toward his own head in a chopping motion. 'Stuck between crypt and dust.'</font>
<p><b>You say, </b>'visceral dagger'
<br><b>a spectral crusader says </b>'Shattered!! Three within the crypt. A master must go. To the [grand forge] they must go. Three become one with the spirit hammer.'
<p><b>You say, </b>'grand forge'
<br><font color=green><b>a spectral crusader </b>points to the ground. 'Beyond the doors lies a forge unlike any other.'</font>
</td></tr></table>