<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=3889>Mirror of Self-loathing</a><li><a href=http://phobos/eq/item.php?id=3896>Cracked Mirror of Self-Loathing</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=3896>Cracked Mirror of Self-Loathing</a></ul></td><td><p><b>You give a tormented tradesman : </b><a href=http://phobos/eq/item.php?id=3889>Mirror of Self-loathing</a>
<br><font color=green><b>a tormented tradesman </b>The undead entity looks in the mirror and appears to be stunned by the memory of his former self. He drops the mirror, which causes it to crack slightly. You immediately grab it and place it back in your bag. The spirit looks at you and begins to transform. Ethereal strands of muscle, blood, and flesh come together and the Haggle Baron Dalnir appears.</font>
<br><b>a tormented tradesman gives you : </b><a href=http://phobos/eq/item.php?id=3896>Cracked Mirror of Self-Loathing</a>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=DALNIR></a></b> spawns.</font>
<br><b>a tormented tradesman disappears.</b>
<p><b>You give a tormented tradesman : </b><a href=http://phobos/eq/item.php?id=3896>Cracked Mirror of Self-Loathing</a>
<br><font color=green><b>a tormented tradesman </b>The undead entity looks in the mirror and appears to be stunned by the memory of his former self. He drops the mirror, which causes it to crack slightly. You immediately grab it and place it back in your bag. The spirit looks at you and begins to transform. Ethereal strands of muscle, blood, and flesh come together and the Haggle Baron Dalnir appears.</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=DALNIR></a></b> spawns.</font>
<br><b>a tormented tradesman disappears.</b>
<p><i>This npc will return you any extra items you gave him.</i>
<br><font color=green><b>a tormented tradesman </b>looks at the items you gave him, puzzles over them for a second, and lets them drop from his grasp. He appears to not want them.</font>
</td></tr></table>