<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=14319>Golem Sprocket</a></ul></td><td><p><b>You give a broken golem : </b><a href=http://phobos/eq/item.php?id=14319>Golem Sprocket</a>
<br><b>a broken golem says </b>'Error! Malfunction! Destroy!'
<br><b>a broken golem says </b>'A  like you always bring out the worst in me.'
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=72106>an_enraged_golem</a></b> spawns.</font>
<br><b>a broken golem disappears.</b>
</td></tr></table>