<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=29010>Mark of Atonement</a><li><a href=http://phobos/eq/item.php?id=11050>Fiery Avenger</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10099>Fiery Defender</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Irak Altil </b>turns its head upon its dried, cracked spine to look at you with a rictus grin. After staring through you it continues to walk on.</font>
<p><b>You say, </b>'what are you mumbling about'
<br><font color=green><b>Irak Altil </b>turns its rotted eyesockets towards you. 'Fallen light, upon this ground I fell. Left to rot, cast out. My holy arms stripped and my soul cast out of the halls. Twisted, failed, disgraced.'</font>
<p><b>You say, </b>'disgraced'
<br><b>Irak Altil says </b>'Disgrace upon my soul for failing in my duties. Disgrace of my brethren.'
<p><b>You say, </b>'duties'
<br><font color=green><b>Irak Altil </b>breathes his words from his skeletal mouth as if wind through a valley. 'Sword, shield, breastplate. Twisted to Innoruuks foul will. Must be retrieved and cleansed else my soul is to wander for all time.'</font>
<p><b>You say, </b>'sword'
<br><b>Irak Altil says </b>'Hands of a twisted brother no longer living.'
<p><b>You say, </b>'shield'
<br><b>Irak Altil says </b>'Earthly children of the god of hate. Keeping stand over his dark brothers and sisters.'
<p><b>You say, </b>'breastplate'
<br><font color=green><b>Irak Altil </b>lets loose an unearthly howl as it gleams with sickly light. 'Upon she who lured me from my post. In that place where hatred festers. Painful corruption.'</font>
<p><b>You say, </b>'cleansed'
<br><b>Irak Altil says </b>'The sword must be dipped in water pure. Light of clean spirit to cleanse the shield. A gem of clarity unlike any other for the breastplate. All must be cleansed and returned to the temple for my soul to be freed. Only the temple can cleanse, only they can touch the artifacts. Take the sets of two to the temple. When they are all three cleansed separately take them to him who will grant me atonement.'
<p><b>You give Irak Altil : </b><a href=http://phobos/eq/item.php?id=29010>Mark of Atonement</a>, <a href=http://phobos/eq/item.php?id=11050>Fiery Avenger</a>
<br><font color=green><b>Irak Altil </b>screams so loudly it echoes across the valley as the mark and flames of your holy sword touch his rotted bones. As his body twists he quiets and then speaks. 'Your selflessness has made it possible to redeem my honor. With the cleansing of my corruption your own soul has been strengthened. Your power comes from your devotion to your god and with this you have been rewarded. Remember always your purity, devotion, and why you have sacrificed. I must go now to sacrifice myself upon the spear of pain.'</font>
<br><b>Irak Altil gives you : </b><a href=http://phobos/eq/item.php?id=10099>Fiery Defender</a>
</td></tr></table>