<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13268>Complete Bug Collection</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18011>Want List</a><li><a href=http://phobos/eq/item.php?id=17922>Bug Collection Box</a><li><a href=http://phobos/eq/item.php?id=16875>Stalking Probe</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=77>DeepPockets</a><li><a href=http://phobos/eq/faction.php?id=133>Guardians of the Vale</a><li><a href=http://phobos/eq/faction.php?id=208>Mayor Gubbin</a><li><a href=http://phobos/eq/faction.php?id=218>Merchants of Rivervale</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=48>Coalition of Tradefolk Underground</a></ul></td><td><hr><b>When Blixkin Entropop spawns </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=33065>Ember</a></b> spawns (,-10,).</font>
<p><b>You say, </b>'hail'
<br><b>Blixkin Entropop says </b>'BUGS! BUGS! I love them!.. Do you like to [collect bugs]?'
<p><b>You say, </b>'collect'
<br><b>Blixkin Entropop says </b>'Really? Great! Well since you are a fellow collector.. i'll tell you what.. If you collect this list of bugs for me, i'll give you something great!'
<br><b>Blixkin Entropop gives you : </b><a href=http://phobos/eq/item.php?id=18011>Want List</a>
<br><b>Blixkin Entropop gives you : </b><a href=http://phobos/eq/item.php?id=17922>Bug Collection Box</a>
<p><b>You give Blixkin Entropop : </b><a href=http://phobos/eq/item.php?id=13268>Complete Bug Collection</a>
<br><b>Blixkin Entropop says </b>'Thank you so much! You have done me a great service! Here is your reward'
<br><font color=green><b>Blixkin Entropop </b>digs around in his belt-pouch</font>
<br><font color=green><b>Blixkin Entropop </b>You have successfully completed the task!</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Blixkin Entropop gives you : </b><a href=http://phobos/eq/item.php?id=16875>Stalking Probe</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=77>DeepPockets</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=133>Guardians of the Vale</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=208>Mayor Gubbin</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=218>Merchants of Rivervale</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=48>Coalition of Tradefolk Underground</a> has gotten worse.</font>
</td></tr></table>