<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=16165>Sack of Turnips</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=133>Guardians of the Vale</a><li><a href=http://phobos/eq/faction.php?id=208>Mayor Gubbin</a><li><a href=http://phobos/eq/faction.php?id=316>Storm Reapers</a><li><a href=http://phobos/eq/faction.php?id=218>Merchants of Rivervale</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=88>Dreadguard Outer</a></ul></td><td><p><b>You give Deputy Eigon : </b><a href=http://phobos/eq/item.php?id=16165>Sack of Turnips</a>
<br><b>Deputy Eigon says </b>'Daleen sent you? She is so sweet. If she wasn't married.. ehem.. Thanks.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=133>Guardians of the Vale</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=208>Mayor Gubbin</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=316>Storm Reapers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=218>Merchants of Rivervale</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=88>Dreadguard Outer</a> has gotten worse.</font>
<br><b>You receive </b> 1gp
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>