<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13916>Deathfist Slashed Belt</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13024>Tagglefoot Tingle Drink</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=133>Guardians of the Vale</a><li><a href=http://phobos/eq/faction.php?id=208>Mayor Gubbin</a><li><a href=http://phobos/eq/faction.php?id=316>Storm Reapers</a><li><a href=http://phobos/eq/faction.php?id=218>Merchants of Rivervale</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=88>Dreadguard Outer</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Deputy Budo says </b>'Hail, [Your Name]. I am Deputy Budo Bullnose, the squad leader of the Great Wall Patrol. Be very careful in the lands beyond the wall. They are filled with dangerous beasts, as well as [Clan Runnyeye].'
<p><b>You say, </b>'clan Runnyeye'
<br><b>Deputy Budo says </b>'Beyond this wall lies Runnyeye, the lair of the goblins of Clan Runnyeye. They have been a nuisance to Rivervale for quite some time. If you wish to join the fight, go to Rivervale and ask Sheriff Roglio about Clan Runnyeye.'
<p><b>You say, </b>'I am reporting for duty'
<br><b>Deputy Budo says </b>'Stand tall then, Deputy [Your Name]. Your orders are to keep the creatures from venturing into the community of Rivervale and to kill many goblins. Check the goblin bodies, if you should find unbroken warrior beads on them, take them to Sheriff Roglio Bruth and should you be lucky enough to find a bizarre grappling device, you are to take it to Marshal Ghobber Truppack immediately! One more thing - should you defeat any orcs in battle, bring me their leather belts and I shall reward you for the great victory. May the power of Underfoot be with you!'
<p><b>You give Deputy Budo : </b><a href=http://phobos/eq/item.php?id=13916>Deathfist Slashed Belt</a>
<br><b>Deputy Budo says </b>'Grand work. Deputy [Your Name]! You will become a full-fledged deputy in no time. You should check in with Marshal Ghobber from time to time to see if you have earned your squad ring. Just go up to him and ask. 'Am I one with the Wall?' He will know. but you must first show your bravery in many battles against the goblins.'
<br><b>You receive </b> 9gp
<br><b>Deputy Budo gives you : </b><a href=http://phobos/eq/item.php?id=13024>Tagglefoot Tingle Drink</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=133>Guardians of the Vale</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=208>Mayor Gubbin</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=316>Storm Reapers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=218>Merchants of Rivervale</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=88>Dreadguard Outer</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>