<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18013>A Note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13240>Deputy Tagil's Payment</a></ul></td><td><p><b>You give Deputy Tagil : </b><a href=http://phobos/eq/item.php?id=18013>A Note</a>
<br><b>Deputy Tagil says </b>'What's this?  Oh dear.  I am very sorry.  Please take this to Uner with my apologies.'
<br><b>Deputy Tagil gives you : </b><a href=http://phobos/eq/item.php?id=13240>Deputy Tagil's Payment</a>
</td></tr></table>