<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20532>Torch of Misty</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20533>Torch of Ro</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Fajio Knejo says </b>'Greetings, [Your Name].  I hope you are having a fine day.'
<p><b>You give Fajio Knejo : </b><a href=http://phobos/eq/item.php?id=20532>Torch of Misty</a>
<br><b>Fajio Knejo says </b>'Run onward, my friend, to the far off Desert of Ro and give this torch to Andad Filla.'
<br><b>Fajio Knejo gives you : </b><a href=http://phobos/eq/item.php?id=20533>Torch of Ro</a>
<br><b>Fajio Knejo says </b>'I have no need of this, [Your Name].'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>