<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Roha Jumthief </b>smiles at you broadly. It is my pleasure to bid you greeting from the Council of New Tanaan. I have been granted the task of working as this region's gatekeeper to Shadowrest. Until recently, the Keeper held tightly onto all things that we lost. Thanks to the council, this is no longer true. The Keeper may grant you access to your lost corpses if you ask him. When you are [ready], I will transport you.</font>
<p><b>You say, </b>'ready'
<br><b>Roha Jumthief says </b>'Why would I send you there?! You have no bodies available. Begone!'
<p><b>You say, </b>'ready'
<br><b>Roha Jumthief says </b>'Why would I send you there?! You have no bodies available. Begone!'
</td></tr></table>