<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18753>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13584>Stained Red Robe*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Camia V-Retta says </b>'Hail.'
<p><b>You give Camia V-Retta : </b><a href=http://phobos/eq/item.php?id=18753>A tattered note</a>
<br><b>Camia V-Retta says </b>'Thanks.'
<br><b>Camia V-Retta gives you : </b><a href=http://phobos/eq/item.php?id=13584>Stained Red Robe*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>