<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13071>Rat Whiskers</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=87>Dreadguard Inner</a><li><a href=http://phobos/eq/faction.php?id=88>Dreadguard Outer</a><li><a href=http://phobos/eq/faction.php?id=155>Indigo Brotherhood</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=260>Primordial Malice</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Exterminator Damasi says </b>'Greetings, traveller. How would you like to make some money? I was brought in to kill some of these rodents that have been infesting the city but there are simply way too many of them. If you can kill some of the rodents around here and bring me four rat whiskers, perhaps I could find some spare coin for you.'
<p><b>You give Exterminator Damasi : </b><a href=http://phobos/eq/item.php?id=13071>Rat Whiskers</a> x4
<br><b>Exterminator Damasi says </b>'Well there are still many rodents around but I will honor my deal. Here are your coins. Now I must get back to work.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=87>Dreadguard Inner</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=88>Dreadguard Outer</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=155>Indigo Brotherhood</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=260>Primordial Malice</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 1gp 1sp 1cp
</td></tr></table>