<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18755>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13582>Ruined Red Robe*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Gath N-Mare says </b>'Hail.'
<p><b>You give Gath N-Mare : </b><a href=http://phobos/eq/item.php?id=18755>A tattered note</a>
<br><b>Gath N-Mare says </b>'Thanks.'
<br><b>Gath N-Mare gives you : </b><a href=http://phobos/eq/item.php?id=13582>Ruined Red Robe*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>