<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=31753>Request Form</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19559>Tattered Glove Pattern</a><li><a href=http://phobos/eq/item.php?id=19561>Tattered Boot Pattern</a><li><a href=http://phobos/eq/item.php?id=19558>Tattered Wristband Pattern</a><li><a href=http://phobos/eq/item.php?id=19555>Tattered Cap Pattern</a><li><a href=http://phobos/eq/item.php?id=19560>Tattered Pant Pattern</a><li><a href=http://phobos/eq/item.php?id=19557>Tattered Sleeve Pattern</a><li><a href=http://phobos/eq/item.php?id=19556>Tattered Tunic Pattern</a><li><a href=http://phobos/eq/item.php?id=17124>Mail Assembly Kit</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Issva H-Rugla says </b>'If you're looking for chit chat you can bugger off. I'm here to sell supplies not company.'
<p><b>You say, </b>'gauntlets'
<br><b>Issva H-Rugla says </b>'To craft Orc Slayer Gauntlets you require two [silk thread], a cracked pyre beetle carapace, and two orc finger bones. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Glove Pattern.'
<br><b>Issva H-Rugla gives you : </b><a href=http://phobos/eq/item.php?id=19559>Tattered Glove Pattern</a>
<p><b>You say, </b>'boots'
<br><b>Issva H-Rugla says </b>'To craft Orc Slayer Boots you require two [silk thread], two cracked pyre beetle carapaces, and two orc foot bones. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Boot Pattern.'
<br><b>Issva H-Rugla gives you : </b><a href=http://phobos/eq/item.php?id=19561>Tattered Boot Pattern</a>
<p><b>You say, </b>'bracer'
<br><b>Issva H-Rugla says </b>'To craft an Orc Slayer Bracer you require a [silk thread], a cracked pyre beetle carapace, and an orc ulna bone. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Bracer Pattern.'
<br><b>Issva H-Rugla gives you : </b><a href=http://phobos/eq/item.php?id=19558>Tattered Wristband Pattern</a>
<p><b>You say, </b>'helm'
<br><b>Issva H-Rugla says </b>'To craft an Orc Slayer Helm you require two [silk thread], a cracked pyre beetle carapace, and an orc skull. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Cap Pattern.'
<br><b>Issva H-Rugla gives you : </b><a href=http://phobos/eq/item.php?id=19555>Tattered Cap Pattern</a>
<p><b>You say, </b>'greaves'
<br><b>Issva H-Rugla says </b>'To craft Orc Slayer Greaves you require three [silk thread], a pyre beetle carapace, two orc tibia, and an orc pelvis bone. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Leggings Pattern.'
<br><b>Issva H-Rugla gives you : </b><a href=http://phobos/eq/item.php?id=19560>Tattered Pant Pattern</a>
<p><b>You say, </b>'vambraces'
<br><b>Issva H-Rugla says </b>'To craft Ord Slayer Vambraces you require two [silk thread], a pyre beetle carapace, and two orc humerus bones. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Sleeves Pattern.'
<br><b>Issva H-Rugla gives you : </b><a href=http://phobos/eq/item.php?id=19557>Tattered Sleeve Pattern</a>
<p><b>You say, </b>'breastplate'
<br><b>Issva H-Rugla says </b>'To craft an Orc Slayer Breastplate you require four [silk thread], a pristine pyre beetle carapace, an orc sternum, and an orc ribcage. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Tunic Pattern.'
<br><b>Issva H-Rugla gives you : </b><a href=http://phobos/eq/item.php?id=19556>Tattered Tunic Pattern</a>
<p><b>You give Issva H-Rugla : </b><a href=http://phobos/eq/item.php?id=31753>Request Form</a>
<br><b>Issva H-Rugla says </b>'So you are one of Jarrex's new recruits. You are to assist in the construction of the armor you will don as a new Warrior of the Indigo Brotherhood. I have assembled a kit that is used in the crafting of Orc Slayer Mail. You must travel beyond Neriak into the Nektulos Forest for the [materials] that compose the armor.'
<br><b>Issva H-Rugla gives you : </b><a href=http://phobos/eq/item.php?id=17124>Mail Assembly Kit</a>
<br><b>Issva H-Rugla says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>