<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13791>Orc Scalp</a><li><a href=http://phobos/eq/item.php?id=19565>Orc Clavicle</a><li><a href=http://phobos/eq/item.php?id=19564>Orc Fibula</a><li><a href=http://phobos/eq/item.php?id=19562>Young Kodiak Femur</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Jarrex N-Ryt says </b>'What have we here? A new weakling that wishes to reap some sort of self-value and renown through service to the Indigo Brotherhood perhaps? Well speak up whelp!! Have you come to [destroy the enemies of Neriak] or are you a coward better suited to mop the filth from the back rooms of the Maidens Fancy.'
<p><b>You say, </b>'destroy the enemies of Neriak'
<br><b>Jarrex N-Ryt says </b>'Begone fool, you are no member of the Indigo Brotherhood!'
<p><b>You say, </b>'further instruction'
<br><b>Jarrex N-Ryt says </b>'Ah, you are eager to advance further within the Indigo Brotherhood. Although it is my duty to aid your training, do not allow your arrogance to blind you to your lowly position amongst the Kings most loyal subjects. Your next task is to assist the construction of a [weapon] and [shield] worthy of being wielded by a Warrior of the Indigo Brotherhood.'
<p><b>You say, </b>'weapon'
<br><b>Jarrex N-Ryt says </b>'Beyond the mouth of Neriak lies the Nektulos Forest. There the Deathfist Clan of Orcs has set up camps in an attempt to invade and claim the Nektulos Forest. Slay these invaders and bring to me an Orc Templar Scalp, an Orc Fibula bone, and an Orc Clavicle bone.'
<p><b>You say, </b>'shield'
<br><b>Jarrex N-Ryt says </b>'Young Kodiak Bears often wander into the Nektulos Forest from the Commonlands searching for food. You do not appear to have the strength to arm wrestle a pixie. If you prove me wrong by slaying Young Kodiaks and bringing me four Young Kodiak Femurs I will guide you in the construction of a shield worthy of a warrior of the Indigo Brotherhood.'
<p><b>You give Jarrex N-Ryt : </b><a href=http://phobos/eq/item.php?id=13791>Orc Scalp</a>, <a href=http://phobos/eq/item.php?id=19565>Orc Clavicle</a>, <a href=http://phobos/eq/item.php?id=19564>Orc Fibula</a>
<br><b>Jarrex N-Ryt says </b>'I don't need this.'
<p><b>You give Jarrex N-Ryt : </b><a href=http://phobos/eq/item.php?id=19562>Young Kodiak Femur</a> x4
<br><b>Jarrex N-Ryt says </b>'I don't need this.'
<br><b>Jarrex N-Ryt says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>