<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18754>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13583>Torn Red Robe*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Jayna D-Bious says </b>'Hail.'
<p><b>You give Jayna D-Bious : </b><a href=http://phobos/eq/item.php?id=18754>A tattered note</a>
<br><b>Jayna D-Bious says </b>'Thanks.'
<br><b>Jayna D-Bious gives you : </b><a href=http://phobos/eq/item.php?id=13583>Torn Red Robe*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>