<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19584>Request Parchment</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19561>Tattered Boot Pattern</a><li><a href=http://phobos/eq/item.php?id=19558>Tattered Wristband Pattern</a><li><a href=http://phobos/eq/item.php?id=19555>Tattered Cap Pattern</a><li><a href=http://phobos/eq/item.php?id=19559>Tattered Glove Pattern</a><li><a href=http://phobos/eq/item.php?id=19560>Tattered Pant Pattern</a><li><a href=http://phobos/eq/item.php?id=19557>Tattered Sleeve Pattern</a><li><a href=http://phobos/eq/item.php?id=19556>Tattered Tunic Pattern</a><li><a href=http://phobos/eq/item.php?id=17124>Mail Assembly Kit</a></ul></td><td><p><b>You say, </b>'boots'
<br><b>Krivn S-Tai says </b>'To craft Bone Mail Boots you require two [silk thread], two ruined wolf pelts, and two calcified foot bones. Once you have the necessary components combine them in your Bone Mail Kit with this Tattered Boot Pattern.'
<br><b>Krivn S-Tai gives you : </b><a href=http://phobos/eq/item.php?id=19561>Tattered Boot Pattern</a>
<p><b>You say, </b>'bracer'
<br><b>Krivn S-Tai says </b>'To craft a Bone Mail Bracer you require a [silk thread], a ruined wolf pelt, and a calcified ulna bone. Once you have the necessary components combine them in your Bone Mail Kit with this Tattered Bracer Pattern.'
<br><b>Krivn S-Tai gives you : </b><a href=http://phobos/eq/item.php?id=19558>Tattered Wristband Pattern</a>
<p><b>You say, </b>'coif'
<br><b>Krivn S-Tai says </b>'To craft a Bone Mail Coif you require two [silk thread], a ruined wolf pelt, and a calcified skull. Once you have the necessary components combine them in your Bone Mail Kit with this Tattered Cap Pattern.'
<br><b>Krivn S-Tai gives you : </b><a href=http://phobos/eq/item.php?id=19555>Tattered Cap Pattern</a>
<p><b>You say, </b>'gloves'
<br><b>Krivn S-Tai says </b>'To craft Bone Mail Gloves you require two [silk thread], a ruined wolf pelt, and two calcified finger bones. Once you have the necessary components combine them in your Bone Mail Kit with this Tattered Glove Pattern.'
<br><b>Krivn S-Tai gives you : </b><a href=http://phobos/eq/item.php?id=19559>Tattered Glove Pattern</a>
<p><b>You say, </b>'leggings'
<br><b>Krivn S-Tai says </b>'To craft Bone Mail Leggings you require three [silk thread], a low quality wolf pelt, two calcified tibia, and a calcified pelvis. Once you have the necessary components combine them in your Bone Mail Kit with this Tattered Leggings Pattern.'
<br><b>Krivn S-Tai gives you : </b><a href=http://phobos/eq/item.php?id=19560>Tattered Pant Pattern</a>
<p><b>You say, </b>'sleeves'
<br><b>Krivn S-Tai says </b>'To craft Bone Mail Sleeves you require two [silk thread], a low quality wolf pelt, and two calcified humerus bones. Once you have the necessary components combine them in your Bone Mail Kit with this Tattered Sleeves Pattern.'
<br><b>Krivn S-Tai gives you : </b><a href=http://phobos/eq/item.php?id=19557>Tattered Sleeve Pattern</a>
<p><b>You say, </b>'tunic'
<br><b>Krivn S-Tai says </b>'To craft a Bone Mail Tunic you require four [silk thread], a medium quality wolf skin, a calcified sternum, and a calcified ribcage. Once you have the necessary components combine them in your Bone Mail Kit with this Tattered Tunic Pattern.'
<br><b>Krivn S-Tai gives you : </b><a href=http://phobos/eq/item.php?id=19556>Tattered Tunic Pattern</a>
<p><b>You give Krivn S-Tai : </b><a href=http://phobos/eq/item.php?id=19584>Request Parchment</a>
<br><b>Krivn S-Tai says </b>'So you are one of Ulraz's new recruits. You are to assist in the construction of the armor you will don as a new Shadowknight of the Lodge of the Dead. I have assembled a kit that is used in the crafting of Bone Mail. You must travel beyond Neriak into the Nektulos Forest for the [materials] that compose the armor.'
<br><b>Krivn S-Tai gives you : </b><a href=http://phobos/eq/item.php?id=17124>Mail Assembly Kit</a>
</td></tr></table>