<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13886>Goblin Supply Pouch</a><li><a href=http://phobos/eq/item.php?id=12259>Leatherfoot Raider Skullcap</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17972>Featherweight Pouch</a><li><a href=http://phobos/eq/item.php?id=12257>Footman's Voulge</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=155>Indigo Brotherhood</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=92>Emerald Warriors</a><li><a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a><li><a href=http://phobos/eq/faction.php?id=260>Primordial Malice</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Narex T-Vem says </b>'Welcome to the Cauldron of Hate. If you are a young warrior, you have come to the right place. There are many [duties] to be performed. If you are a veteran of the blade, we welcome your return to service. Perhaps you return with a [Leatherfoot] skullcap?'
<p><b>You say, </b>'duties'
<br><b>Narex T-Vem says </b>'I am so glad you asked. There is one matter of importance with which you may be able to assist. It seems an Erudite has made camp in Lavastorm. He is powerful and we do not expect you to slay him. Your mission is to cut off his supply line. I hope you will [accept the mission].'
<p><b>You say, </b>'accept the mission'
<br><b>Narex T-Vem says </b>'Go to the Lavastorm Mountain Range. It is a dangerous place, but the one you seek must leave by the direction you entered. He is a goblin. Apparently the Erudite is employing their strength. The fire goblin runner shall be an easy kill for you. At least, he should be. Return his runner pouch to me.'
<p><b>You say, </b>'leatherfoot'
<br><b>Narex T-Vem says </b>'Go!! Return when you have done more to serve the Indigo Brotherhood of Neriak. Fewer Leatherfoot Raiders in Nektulos and a few Leatherfoot skullcaps in the palms of Master Narex shall prove your true warrior nature and loyalty to our house.'
<p><b>You say, </b>'collect the bounty'
<br><b>Narex T-Vem says </b>'So you wish to collect the bounty on Leatherfoot Raiders? Then go into Nektulos and hunt them down. I shall pay a reward for no fewer than four Leatherfoot Raider skullcaps.'
<p><b>You give Narex T-Vem : </b><a href=http://phobos/eq/item.php?id=13886>Goblin Supply Pouch</a>
<br><b>Narex T-Vem says </b>'Fine work. I trust the denizens of Lavastorm were not unkind. Please take this featherweight pouch as a reward. May it keep you fleet of foot.'
<br><b>Narex T-Vem gives you : </b><a href=http://phobos/eq/item.php?id=17972>Featherweight Pouch</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=155>Indigo Brotherhood</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=92>Emerald Warriors</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=260>Primordial Malice</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Narex T-Vem : </b><a href=http://phobos/eq/item.php?id=12259>Leatherfoot Raider Skullcap</a> x4
<br><b>Narex T-Vem says </b>'Yes, you have done well.  Take this, and slay more!'
<br><b>Narex T-Vem gives you : </b><a href=http://phobos/eq/item.php?id=12257>Footman's Voulge</a>
<br><b>You receive </b> 4gp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=155>Indigo Brotherhood</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=92>Emerald Warriors</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=260>Primordial Malice</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Narex T-Vem says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>