<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18200>A Note</a><li><a href=http://phobos/eq/item.php?id=13846>Dark Elf Decapitated Head</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18201>A Note</a><li><a href=http://phobos/eq/item.php?id=18202>Book of Turmoil</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=87>Dreadguard Inner</a><li><a href=http://phobos/eq/faction.php?id=88>Dreadguard Outer</a><li><a href=http://phobos/eq/faction.php?id=69>Dark Bargainers</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Rysva To-Biath says </b>'Hello.  Let me know if I can get you a drink.'
<p><b>You give Rysva To-Biath : </b><a href=http://phobos/eq/item.php?id=18200>A Note</a>
<br><b>Rysva To-Biath says </b>'Take this note and be gone with you.'
<br><b>Rysva To-Biath gives you : </b><a href=http://phobos/eq/item.php?id=18201>A Note</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=87>Dreadguard Inner</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=88>Dreadguard Outer</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=69>Dark Bargainers</a> has gotten better.</font>
<p><b>You give Rysva To-Biath : </b><a href=http://phobos/eq/item.php?id=13846>Dark Elf Decapitated Head</a>
<br><b>Rysva To-Biath says </b>'Take this book and be gone with you.'
<br><b>Rysva To-Biath gives you : </b><a href=http://phobos/eq/item.php?id=18202>Book of Turmoil</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=87>Dreadguard Inner</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=88>Dreadguard Outer</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=69>Dark Bargainers</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Rysva To-Biath says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>