<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18751>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13580>Old Training Tunic*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Seloxia Punox says </b>'You may speak if you are a member of this house of warriors. Let it be of something important. Do not waste my time. Or wait. Perhaps you are a young warrior. If you are I have a [little test] for you.'
<p><b>You give Seloxia Punox : </b><a href=http://phobos/eq/item.php?id=18751>A tattered note</a>
<br><b>Seloxia Punox says </b>'Welcome to the Indigo Brotherhood. Hmmm. you're a bit scrawny. but we'll work with it. Here's your guild tunic. Defend Neriak and all her allies. For the time being this list includes our [new friends].Go see Yegek. one of our trainers. Hopefully he can mould you into something resembling a warrior.'
<br><b>Seloxia Punox gives you : </b><a href=http://phobos/eq/item.php?id=13580>Old Training Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>