<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13885>Orc Pawn Pick</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13021>Neriak Nectar</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=155>Indigo Brotherhood</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=92>Emerald Warriors</a><li><a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Trizam N-Tan says </b>'And who do you think you are? To step into the Cauldron of Hate one should have the black soul of a warrior. For one to speak with Trizam he should have good reason. Perhaps you return with tales of [deathfist] agendas. If so, then you're a year too late.'
<p><b>You say, </b>'deathfist'
<br><b>Trizam N-Tan says </b>'Have you been spending day and night at the Malden's Fancy?!! The Deathfist Orcs in the Commonlands are up to something. As the inept humans in Freeport hunt down the warrior orcs, the pawns run about on some secret mission. I have been appointed by King Nathox to attend to this matter and hire young warriors who wish to [collect] pawn kills.'
<p><b>You say, </b>'collect'
<br><b>Trizam N-Tan says </b>'Yes, You will. You need not know the reason why. I command you by order of King Naythox Thex to venture forth to the Commonlands and slay all the orc pawns you see. Return with four pawn picks and maybe I shall even reward you. Leave at once or you shall find yourself hanging from the Hooks of Innoruuk!'
<p><b>You give Trizam N-Tan : </b><a href=http://phobos/eq/item.php?id=13885>Orc Pawn Pick</a> x4
<br><b>Trizam N-Tan says </b>'As instructed, I shaw reward your good deed. But I choose to reward you with provisions from the pantries of Neriak. They shall keep you strong.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=155>Indigo Brotherhood</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=92>Emerald Warriors</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Trizam N-Tan gives you : </b><a href=http://phobos/eq/item.php?id=13021>Neriak Nectar</a>
<br><b>Trizam N-Tan says </b>'I have no need for this item [Your Name], you can have it back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>