<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When #Diabo Xi Xin spawns </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158088>Akhevan_Warder</a></b> spawns (2.1,1874.4,3.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158088>Akhevan_Warder</a></b> spawns (2.3,1767.3,67.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158088>Akhevan_Warder</a></b> spawns (1.9,1837,63.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158088>Akhevan_Warder</a></b> spawns (-64.3,1736.6,63.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158088>Akhevan_Warder</a></b> spawns (64.3,1736.6,63.1).</font>
<hr><b>When #Diabo Xi Xin is killed </b>
<br><b>#Diabo Xi Xin disappears.</b>
<br><b>#Diabo Xi Xin disappears.</b>
<br><b>#Diabo Xi Xin disappears.</b>
<br><b>#Diabo Xi Xin disappears.</b>
<br><b>#Diabo Xi Xin disappears.</b>
</td></tr></table>