<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When #Diabo Xi Xin Thall spawns </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158089>Akhevan_Warder</a></b> spawns (23.6,1596.9,63.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158089>Akhevan_Warder</a></b> spawns (-23.6,1596.9,63.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158089>Akhevan_Warder</a></b> spawns (23.6,1557.9,63.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158089>Akhevan_Warder</a></b> spawns (-23.6,1557.9,63.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158089>Akhevan_Warder</a></b> spawns (-17.4,1489.6,115.6).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158089>Akhevan_Warder</a></b> spawns (17.4,1489.3,115.6).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158089>Akhevan_Warder</a></b> spawns (2,1508.4,115.6).</font>
<hr><b>When #Diabo Xi Xin Thall is killed </b>
<br><b>#Diabo Xi Xin Thall disappears.</b>
<br><b>#Diabo Xi Xin Thall disappears.</b>
<br><b>#Diabo Xi Xin Thall disappears.</b>
<br><b>#Diabo Xi Xin Thall disappears.</b>
<br><b>#Diabo Xi Xin Thall disappears.</b>
<br><b>#Diabo Xi Xin Thall disappears.</b>
<br><b>#Diabo Xi Xin Thall disappears.</b>
</td></tr></table>