<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When #Kaas Thox Xi Ans Dyek spawns </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158087>Akhevan_Warder</a></b> spawns (256,626,6.25).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158087>Akhevan_Warder</a></b> spawns (-256,626,6.25).</font>
<hr><b>When #Kaas Thox Xi Ans Dyek is killed </b>
<br><b>#Kaas Thox Xi Ans Dyek disappears.</b>
<br><b>#Kaas Thox Xi Ans Dyek disappears.</b>
</td></tr></table>