<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When #Thall Xundraux Diabo spawns </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158091>Akhevan_Warder</a></b> spawns (0,880,126.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158091>Akhevan_Warder</a></b> spawns (0,941,126.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158091>Akhevan_Warder</a></b> spawns (0,755.7,126.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158091>Akhevan_Warder</a></b> spawns (45,740,126.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158091>Akhevan_Warder</a></b> spawns (-45,740,126.1).</font>
<hr><b>When #Thall Xundraux Diabo is killed </b>
<br><b>#Thall Xundraux Diabo disappears.</b>
<br><b>#Thall Xundraux Diabo disappears.</b>
<br><b>#Thall Xundraux Diabo disappears.</b>
<br><b>#Thall Xundraux Diabo disappears.</b>
<br><b>#Thall Xundraux Diabo disappears.</b>
</td></tr></table>