<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When #Thall Va Kelun spawns </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158090>Akhevan_Warder</a></b> spawns (-250.1,1736.1,115.6).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158090>Akhevan_Warder</a></b> spawns (250.1,1736.1,115.6).</font>
<hr><b>When #Thall Va Kelun is killed </b>
<br><b>#Thall Va Kelun disappears.</b>
<br><b>#Thall Va Kelun disappears.</b>
</td></tr></table>