<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When #Va Xi Aten Ha Ra spawns </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158094>Akhevan_Warder</a></b> spawns (0.2,368,128.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158094>Akhevan_Warder</a></b> spawns (0.2,498.9,128.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158094>Akhevan_Warder</a></b> spawns (0.2,593.4,128.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158094>Akhevan_Warder</a></b> spawns (-0.4,143,128.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158094>Akhevan_Warder</a></b> spawns (0.3,1153.7,236.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158094>Akhevan_Warder</a></b> spawns (0.3,1106,236.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158094>Akhevan_Warder</a></b> spawns (-26.6,1184.8,236.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158094>Akhevan_Warder</a></b> spawns (26.6,1184.8,236.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158094>Akhevan_Warder</a></b> spawns (0,1238.8,233.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158094>Akhevan_Warder</a></b> spawns (0,1348.9,233.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158094>Akhevan_Warder</a></b> spawns (-55,1380,233.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158094>Akhevan_Warder</a></b> spawns (55,1380,233.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158094>Akhevan_Warder</a></b> spawns (-85,1314.8,233.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=158094>Akhevan_Warder</a></b> spawns (85,1314.8,233.1).</font>
<hr><b>When #Va Xi Aten Ha Ra is killed </b>
<br><b>#Va Xi Aten Ha Ra disappears.</b>
<br><b>#Va Xi Aten Ha Ra disappears.</b>
<br><b>#Va Xi Aten Ha Ra disappears.</b>
<br><b>#Va Xi Aten Ha Ra disappears.</b>
<br><b>#Va Xi Aten Ha Ra disappears.</b>
<br><b>#Va Xi Aten Ha Ra disappears.</b>
<br><b>#Va Xi Aten Ha Ra disappears.</b>
<br><b>#Va Xi Aten Ha Ra disappears.</b>
<br><b>#Va Xi Aten Ha Ra disappears.</b>
<br><b>#Va Xi Aten Ha Ra disappears.</b>
<br><b>#Va Xi Aten Ha Ra disappears.</b>
<br><b>#Va Xi Aten Ha Ra disappears.</b>
<br><b>#Va Xi Aten Ha Ra disappears.</b>
<br><b>#Va Xi Aten Ha Ra disappears.</b>
</td></tr></table>