<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=67010>A Mug of Poisoned Ale</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=29863>Unadorned Ring</a></ul></td><td><p><b>You say, </b>'compromise'
<br><b>Brendar Mynden says </b>'A compromise? Zabaltin has fought me in every request asking for help protecting the delivery caravans! I will never work with him. Say what is that in your hand? The label looks like it is a bottle of my favorite ale. It's from Zabaltin you say? Maybe he really is trying to work things out. Well then let's open the bottle and have a drink!'
<p><b>You give Brendar Mynden : </b><a href=http://phobos/eq/item.php?id=67010>A Mug of Poisoned Ale</a>
<br><font color=green><b>Brendar Mynden </b>open the bottle and takes a large drink right from it. Immediately his eyes roll back into their sockets and he falls to the ground. You look around to make sure no one has seen and then take the ring from his finger.</font>
<br><b>Brendar Mynden disappears.</b>
<br><b>Brendar Mynden gives you : </b><a href=http://phobos/eq/item.php?id=29863>Unadorned Ring</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>