<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=6269>Tattered Letter</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=37>Citizens of Seru</a><li><a href=http://phobos/eq/faction.php?id=139>Hand of Seru</a><li><a href=http://phobos/eq/faction.php?id=142>Heart of Seru</a><li><a href=http://phobos/eq/faction.php?id=96>Eye of Seru</a><li><a href=http://phobos/eq/faction.php?id=298>Shoulders of Seru</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=168>Katta Castellum Citizens</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Centurion Jelin says </b>'Welcome to my home, my apologies for being untidy. I have been preoccupied with the thought of my brother lately. I love Seru and I love this town do not get me wrong, but it still makes me sad to see someone cast out. He was forced to submit to the Question when he was found to be supplying [Recuso] with food, water, and medical supplies. Because of the power of the question, they soon found this out, and now he has to live amongst the very people he was helping.'
<p><b>You say, </b>'Recuso'
<br><b>Centurion Jelin says </b>'Yes, they are a landless people, usually found to be in Marus Seru.'
<p><b>You give Centurion Jelin : </b><a href=http://phobos/eq/item.php?id=6269>Tattered Letter</a>
<br><font color=green><b>Centurion Jelin </b>looks at you puzzled and takes the letter and reads it. 'Oh I am so glad that he is alive! I am happy that you took the time to ease my worries about him. I shall let the people of this town know that you come with good intentions. For now i will rest for I have not slept in days.'</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=37>Citizens of Seru</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=139>Hand of Seru</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=142>Heart of Seru</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=96>Eye of Seru</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=298>Shoulders of Seru</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=168>Katta Castellum Citizens</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>