<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=3878>A Heavy Coin</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=3879>Official Seal of the Hand</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=139>Hand of Seru</a><li><a href=http://phobos/eq/faction.php?id=284>Seru</a><li><a href=http://phobos/eq/faction.php?id=138>Hand Legionnaries</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=96>Eye of Seru</a><li><a href=http://phobos/eq/faction.php?id=142>Heart of Seru</a><li><a href=http://phobos/eq/faction.php?id=350>Validus Custodus</a><li><a href=http://phobos/eq/faction.php?id=206>Magus Conlegium</a></ul></td><td><p><b>You give Consis Sinsolus : </b><a href=http://phobos/eq/item.php?id=3878>A Heavy Coin</a>
<br><font color=green><b>Consis Sinsolus </b>turns to look at you for a moment, but does not appear to notice that you made the swap.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=139>Hand of Seru</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=96>Eye of Seru</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=142>Heart of Seru</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=284>Seru</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=138>Hand Legionnaries</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=350>Validus Custodus</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=206>Magus Conlegium</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Consis Sinsolus gives you : </b><a href=http://phobos/eq/item.php?id=3879>Official Seal of the Hand</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>