<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=29865>Ethereal Drape</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=29890>Frayed Ethereal Drape</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Jylian Frostshade says </b>'Greetings, as you can see I am quite busy with my [research]. If you don't mind I need silence to concentrate.'
<p><b>You say, </b>'research'
<br><b>Jylian Frostshade says </b>'I am researching what went wrong in Mons Letalis. The spires constructed there should allow us passage back to Norrath freely. Upon completion of them something [went wrong].'
<p><b>You say, </b>'went wrong'
<br><b>Jylian Frostshade says </b>'Suddenly the spires were overwhelmed with eerie beings that seemed to have no essence to them. These spirits now plague the spires. Due to our lack of knowledge of these creatures we do not know how to deal with them. Fighting them seems useless because as soon as one is destroyed more would materialize. They seemed to feed off of death, especially ours. We must [find out more] about them.'
<p><b>You say, </b>'find out more'
<br><b>Jylian Frostshade says </b>'If you think you can help, I charge you with the task of gathering information. Seek out these creatures, and if you can manage to destroy them bring me their robes. I will study the garment to see if I can determine its origin. Now please, leave me be so that I can get to my research.'
<p><b>You give Jylian Frostshade : </b><a href=http://phobos/eq/item.php?id=29865>Ethereal Drape</a>
<br><font color=green><b>Jylian Frostshade </b>delicately removes one of the embroidered symbols from the fading robe. Jylian then begins to weave spells to the robe until it becomes fully materialized. 'These robes have unusual symbols all about them. I must study this symbol in greater deatail. Here you can have this robe, I have placed an enchantment on it to keep it from fading from this plane of existence any further. Your service to Seru is appreciated. Now go, I need silence to concentrate.'</font>
<br><b>Jylian Frostshade gives you : </b><a href=http://phobos/eq/item.php?id=29890>Frayed Ethereal Drape</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>