<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10692>Zelniak Meat</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=6514>Peran's Orders</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=37>Citizens of Seru</a><li><a href=http://phobos/eq/faction.php?id=139>Hand of Seru</a><li><a href=http://phobos/eq/faction.php?id=142>Heart of Seru</a><li><a href=http://phobos/eq/faction.php?id=96>Eye of Seru</a><li><a href=http://phobos/eq/faction.php?id=298>Shoulders of Seru</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=168>Katta Castellum Citizens</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Legionnaire Delaren says </b>'Well met [Your Name]. are you the new recruit that was sent to me to help exterminate the [Zelniaks] that attack our guards and caravans?'
<p><b>You say, </b>'zelniaks'
<br><b>Legionnaire Delaren says </b>'Weren't you briefed on this already? The zelniaks are highly aggresive scaled creatures with a large mane of fur that runs down the length of their back. They are a constant problem for the guards and caravans that used to travel in [dawnshroud].'
<p><b>You say, </b>'dawnshroud'
<br><b>Legionnaire Delaren says </b>'are you new here or something? The Dawnshroud Peaks are a range of mountains lush in vegetation and water. We used to utilize the area as a trade route to Shadow Haven. The caravans that would travel through were often attacked by roaming zelniaks. I thought you were the one that was sent to me to [help lower] the amount of zelniaks in the area. So the trade route could be reestablished.'
<p><b>You say, </b>'help lower'
<br><b>Legionnaire Delaren says </b>'How ambitious of you to help the mighty warriors of the Hand. If you choose to serve Seru bring me back four Zelniak Meat. I will reward you for your time in the field.'
<p><b>You say, </b>'peran'
<br><b>Legionnaire Delaren says </b>'Centurion Peran is new to the tanks. He gets things done I suppose it just takes him a long, long time. Since you did his job for him, take him these new orders. We will make a soldier out of him yet.'
<br><b>Legionnaire Delaren gives you : </b><a href=http://phobos/eq/item.php?id=6514>Peran's Orders</a>
<p><b>You give Legionnaire Delaren : </b><a href=http://phobos/eq/item.php?id=10692>Zelniak Meat</a> x4
<br><b>Legionnaire Delaren says </b>'Although your service to Seru is appreciated, I just recieved word that you were not the one that was sent to do this menial task. That lazy boy [Peran] was supposed to take the job.'
<br><b>You receive </b> 9pp 9gp 9sp 9cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=37>Citizens of Seru</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=139>Hand of Seru</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=142>Heart of Seru</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=96>Eye of Seru</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=298>Shoulders of Seru</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=168>Katta Castellum Citizens</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>