<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=6515>Cracked Amulet</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=6516>Nilibik's Yew Affixed Amulet</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Nilibik Driogo says </b>'Hello, you look like a battleworn traveller. Have you heard of the place where [grieg] resides?'
<p><b>You say, </b>'grieg'
<br><b>Nilibik Driogo says </b>'Aye, Grieg Veneficus. We do not know much about this madman, only where his [stronghold] is. One of my friends from the Eye was sent there to investigate it, but he has not returned. It has been quite some time and I am very worried about him.'
<p><b>You say, </b>'stronghold'
<br><b>Nilibik Driogo says </b>'Grieg's End is what it has become to be known as. Some reports have come back that this place is cursed with foul visages. Any entering will surely loose their minds. I.. I would go but you see I am desperately busy here in the city doing..uh..many important things! You look like you could help, will you [travel] to Grieg's End and look for my friend?'
<p><b>You say, </b>'travel'
<br><b>Nilibik Driogo says </b>'Good, I am glad you would prove yourself useful to Seru. Look for Bronus, you should beware if he has lost his sanity for he is almost as powerful as myself.'
<p><b>You give Nilibik Driogo : </b><a href=http://phobos/eq/item.php?id=6515>Cracked Amulet</a>
<br><font color=green><b>Nilibik Driogo </b>speaks a small incantation as he pulls a branch from a nearby tree and ties it around the amulet 'I shall mourn him dearly, he was a good friend. This was the amulet that I had given him before he left to explore Grieg's End. I want you to have this for helping to find his lost soul. Go in peace my friend.</font>
<br><b>Nilibik Driogo gives you : </b><a href=http://phobos/eq/item.php?id=6516>Nilibik's Yew Affixed Amulet</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>