<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=3880>A Vial of Thick Liquid</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=3882>An Empty Poison Vial</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=298>Shoulders of Seru</a><li><a href=http://phobos/eq/faction.php?id=284>Seru</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=96>Eye of Seru</a><li><a href=http://phobos/eq/faction.php?id=142>Heart of Seru</a><li><a href=http://phobos/eq/faction.php?id=168>Katta Castellum Citizens</a><li><a href=http://phobos/eq/faction.php?id=228>Nathyn Illuminious</a></ul></td><td><p><b>You give Ornis Tranum : </b><a href=http://phobos/eq/item.php?id=3880>A Vial of Thick Liquid</a>
<br><font color=green><b>Ornis Tranum </b>gasps suddenly then falls still.</font>
<br><b>Ornis Tranum gives you : </b><a href=http://phobos/eq/item.php?id=3882>An Empty Poison Vial</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=96>Eye of Seru</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=298>Shoulders of Seru</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=142>Heart of Seru</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=284>Seru</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=168>Katta Castellum Citizens</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=228>Nathyn Illuminious</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>