<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=14058>Aching Blood</a><li><a href=http://phobos/eq/item.php?id=29863>Unadorned Ring</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=67010>A Mug of Poisoned Ale</a><li><a href=http://phobos/eq/item.php?id=29864>Unadorned Ring</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=96>Eye of Seru</a><li><a href=http://phobos/eq/faction.php?id=139>Hand of Seru</a><li><a href=http://phobos/eq/faction.php?id=142>Heart of Seru</a><li><a href=http://phobos/eq/faction.php?id=284>Seru</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=141>Haven Smugglers</a><li><a href=http://phobos/eq/faction.php?id=350>Validus Custodus</a><li><a href=http://phobos/eq/faction.php?id=206>Magus Conlegium</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Zabaltin Draux says </b>'Enough with the chit chat. Are you or are you not a rogue?'
<p><b>You say, </b>'am a rogue'
<br><b>Zabaltin Draux says </b>'Good, I need you to serve Seru. There is a member of the Shoulder that is cutting the delivery of supplies to us and he must be stopped. He is a traitor to this city. He must be a sympathizer with the loyalists of Katta. What I need from you is poison. Go make me four vials of Aching Blood. We will see how he likes his wine with some of that in it!'
<p><b>You give Zabaltin Draux : </b><a href=http://phobos/eq/item.php?id=14058>Aching Blood</a> x4
<br><font color=green><b>Zabaltin Draux </b>takes the poison from you and pours it into a bottle of ale. 'Here, deliver this to Brendar Mynden! Tell him first that I wish to find compromise between our differences to throw him off guard. Then give him the ale to drink. So that I know you were successful bring me that gaudy ring he always wears. I sure do hate that ugly ring.'</font>
<br><b>Zabaltin Draux gives you : </b><a href=http://phobos/eq/item.php?id=67010>A Mug of Poisoned Ale</a>
<p><b>You give Zabaltin Draux : </b><a href=http://phobos/eq/item.php?id=29863>Unadorned Ring</a>
<br><b>Zabaltin Draux says </b>'Ha! His gaudy ring! You have done well young rogue. Perhaps you would be an asset to the Eye after all. You can have his nasty ring back, I am sure that it is worthless. Darn thing weighs as much as a Netherbian and is twice as ugly!'
<br><b>Zabaltin Draux gives you : </b><a href=http://phobos/eq/item.php?id=29864>Unadorned Ring</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=96>Eye of Seru</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=139>Hand of Seru</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=142>Heart of Seru</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=284>Seru</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=141>Haven Smugglers</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=350>Validus Custodus</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=206>Magus Conlegium</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>