<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=8365>Soul Essence of Aten Ha Ra</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=8364>Talisman of Vah Kerrath</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>remains of Vah Kerrath says </b>'Fleshy mortal, can you not see that I am cursed to live in eternal anguish? What is it that you seek from me?'
<p><b>You say, </b>'Where is Vex Thal'
<br><b>remains of Vah Kerrath says </b>'The city of shadow is sealed by powerful magic. Only one that wears the talisman of Akelha Ra can pass through the seals on the gate. I have not been beyond the gates but rumors of dark prophets that possess great power have been heard throughout the ages.'
<p><b>You say, </b>'What dark prophets'
<br><b>remains of Vah Kerrath says </b>'Only legends and rumors have circulated about the dark prophets in Vex Thal. I suspect that they are the reason for my eternally cursed state. If you could find someway to defeat the dark prophet leading those in Vex Thal and bring me back proof of the deed, I shall reward you with an ancient relic that I possess.'
<p><b>You give remains of Vah Kerrath : </b><a href=http://phobos/eq/item.php?id=8365>Soul Essence of Aten Ha Ra</a>
<br><b>remains of Vah Kerrath says </b>'[Your Name], you have done more than was ever expected. Take this and my blessing will be with you always.'
<br><font color=yellow>You gain experience!!</font>
<br><b>remains of Vah Kerrath gives you : </b><a href=http://phobos/eq/item.php?id=8364>Talisman of Vah Kerrath</a>
</td></tr></table>