<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28445>Spell: Draught of Thunder</a><li><a href=http://phobos/eq/item.php?id=9430>Lightning Sphere</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=59528>Spell: Draught of Lightning</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Hrelic Reista </b>glances over from his books for a moment. 'Greetings. Have you come to the realm of the tranquil to study as have? The chaotic energy of lightning has caught my interest of late. I've been trying to understand the magics that further refine my control of lightning and [thunder].</font>
<p><b>You say, </b>'thunder'
<br><b>Hrelic Reista says </b>'The sages of Knowledge have been able to create useful powers by translating some of the ancient scripts found in the planes. I've been doing further research into the Draught of Thunder spell. I believe I can refine the power of the thunder and lightning into a bolt of pure destructive energy. I hear rumors that the giants of Torden have acute control of thunder and lightning. If you bring me one of their lightning spheres and a copy of the Draught of Thunder scroll I may be able to weave them into a new spell.'
<p><b>You give Hrelic Reista : </b><a href=http://phobos/eq/item.php?id=28445>Spell: Draught of Thunder</a>, <a href=http://phobos/eq/item.php?id=9430>Lightning Sphere</a>
<br><b>Hrelic Reista says </b>'Thank you [Your Name]!  May this spell serve you well.'
<br><b>Hrelic Reista gives you : </b><a href=http://phobos/eq/item.php?id=59528>Spell: Draught of Lightning</a>
<br><b>Hrelic Reista says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>