<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>Miak the Searedsoul says </b>'Greetings mortal. Are you here about this [portal's destination]? I have been getting a lot of questions about it lately.'
<p><b>You say, </b>'hail'
<br><b>Miak the Searedsoul says </b>'Greetings mortal. Are you here about this [portal's destination]? I have been getting a lot of questions about it lately.'
<p><b>You say, </b>'portal's destination'
<br><b>Miak the Searedsoul says </b>'As I suspected. This portal leads to Doomfire, the Burning Lands, home to Fennin Ro, the Tyrant of Fire. Or rather, it used to. His son, [Solusek Ro], disapproved of the number of you mortals entering his father's plane, and so he sealed it. It's a shame really, I was starting to enjoy the sounds you mortals make when you fall into the lava.'
<p><b>You say, </b>'solusek ro'
<br><b>Miak the Searedsoul says </b>'So I've got another one eh? Alright, well if you really want to enter the relm of the flame, you're going to have to 'convince' the Burning Prince to remove his seal. He has been staying in his tower lately, so you will be able to find him there. Not that it matters. Nobody ever makes it to see him anyways.'
</td></tr></table>