<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Sarhya the Dawnbreeze says </b>'Well met. I am keeper of the Portal to the [Plane or Air].'
<p><b>You say, </b>'plane of air '
<br><b>Sarhya the Dawnbreeze says </b>'The Elemental Planes are not for idle exploration. Return to me when you have a reason to enter and I will consider opening the portal for you.'
<p><b>You say, </b>' plane of air '
<br><b>Sarhya the Dawnbreeze says </b>'The Elemental Planes are not for idle exploration. Return to me when you have a reason to enter and I will consider opening the portal for you.'
</td></tr></table>