<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18027>Letter to Behroe</a></ul></td><td><hr><b>When Aenia Ghenson spawns </b>
<p><b>You say, </b>'hail'
<br><b>Aenia Ghenson says </b>'Why, hello there!  I'm Aenia, daughter of Dranom.  It's such a bore just sitting around here all day and night.  My father is soooooo overprotective! He never lets me go out and have any fun at all.  And he's so mean to my poor [boyfriend]!'
<p><b>You say, </b>'boyfriend'
<br><b>Aenia Ghenson says </b>'My boyfriend's name is Behroe Dlexon.  He is so dreamy..  <sigh>..  But, I haven't been able to see him lately.  He works nights down at the docks, and with my father here all day, we just can't seem to get together.  Oh, how I wish I could speak with him..'
<p><b>You say, </b>'Oh beautiful thornless rose, growing in the briar patch. Oh glistening crimson rose, you would be such a catch. Oh beautiful thornless rose, your essence has no match. Oh glistening crimson rose, your love i must snatch.'
<br><b>Aenia Ghenson says </b>'Oh..   My Behroe is so sweet.  Oh, how I long to see him.  Please, oh please, kind Kajigger, can you do me but one favor? Here, quickly, before my father returns.  Take this letter to my love, Behroe.  I have no money to offer you, but as you are a friend of his, so are you a friend of mine, and I will not forget your good deeds, Kajigger.  Thank you and be safe.'
<br><b>Aenia Ghenson gives you : </b><a href=http://phobos/eq/item.php?id=18027>Letter to Behroe</a>
</td></tr></table>