<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18797>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=26025>Cowl of Mortality</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=10111></a><li><a href=http://phobos/eq/faction.php?id=2126></a><li><a href=http://phobos/eq/faction.php?id=10101></a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=10103></a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Astaed Wemor says </b>'Greetings. I am Astaed Wemor of the Paladins of the Temple of Life. We are the defenders of the all-giving Prime Healer.  Are you [here to pray] or are you [here to assist the temple]?'
<p><b>You say, </b>'here to pray'
<br><b>Astaed Wemor says </b>'Then pray long and silently, [Your Name].  Fill your soul with the breath of life.'
<p><b>You say, </b>'i am here to assist the temple'
<br><b>Astaed Wemor says </b>'Good.  There are a few in the congregation who require assistance.  Will you be [traveling afar] or are you [staying close to Qeynos]?'
<p><b>You say, </b>'i will be traveling Afar'
<br><b>Astaed Wemor says </b>'I do not dislike you, but I cannot fully trust one who has yet to prove his service to the Prime Healer.  Perhaps you can assist us in ridding the land of diseased animals.  Priestess Caulria will accept all pelts from rabid beasts.'
<p><b>You say, </b>'i will be staying close to qeynos'
<br><b>Astaed Wemor says </b>'I do not dislike you, but I cannot fully trust one who has yet to prove his service to the Prime Healer.  Perhaps you can assist us in ridding the land of diseased animals.  Priestess Caulria will accept all pelts from rabid beasts.'
<p><b>You give Astaed Wemor : </b><a href=http://phobos/eq/item.php?id=18797>A tattered note</a>
<br><b>Astaed Wemor says </b>'So you have helped Nerissa. That is good. Here, then, is a small reward. May you find it useful. Keep fighting the good fight!'
<br><b>Astaed Wemor gives you : </b><a href=http://phobos/eq/item.php?id=26025>Cowl of Mortality</a>
<br><b>You receive </b> 8gp 8sp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10111></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=2126></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10101></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10103></a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>