<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=26644>A Sealed Letter</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=6303>Combine Warhammer</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=2084></a><li><a href=http://phobos/eq/faction.php?id=2128></a><li><a href=http://phobos/eq/faction.php?id=2356></a><li><a href=http://phobos/eq/faction.php?id=2015></a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=10108></a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Brohan Ironforge says </b>'Please, leave me be alone. I have such sorrow in my heart.. I wish to be alone with my thoughts.'
<p><b>You say, </b>'sorrow'
<br><b>Brohan Ironforge says </b>'My daughter Tayla has left and I fear she will not return. If only I could find someone.. Hey, would you like to do a favor for an old man or are you too busy?'
<p><b>You say, </b>'Tayla'
<br><b>Brohan Ironforge says </b>'Tayla is my oldest and youngest daughter. Unlike the rest she is of a different mother. She is part elven. She appears to be physicaly younger than the rest, but she has spent more years as my daughter than all the others. Tayla is from my first marriage to Weleana.'
<p><b>You say, </b>'Where is Tayla'
<br><b>Brohan Ironforge says </b>'Tayla is my oldest and youngest daughter. Unlike the rest she is of a different mother. She is part elven. She appears to be physicaly younger than the rest, but she has spent more years as my daughter than all the others. Tayla is from my first marriage to Weleana.'
<br><b>Brohan Ironforge says </b>'My daughters have informed me that Tayla has runaway to live with the elves of Kelethin. Apparently life among the human citizens of Qeynos was not very kind to her. I wish her well, but I wish I knew she was safe.'
<p><b>You say, </b>'Hurrieta'
<br><b>Brohan Ironforge says </b>'Hurrieta is a good woman. She has a bit repulsed that I once was married to a wood elf. She got over that I believe. We had four children together. The children seem quite accepting of Tayla, even though she is a half elf.'
<p><b>You say, </b>'do you a favor'
<br><b>Brohan Ironforge says </b>'Good. Please find my daughter, Tayla Ironforge. Bring me proof that she is safe. She was last seen near Nektulos. I am a fine blacksmith and I shall give you a worthy gift if you do this for me.'
<p><b>You give Brohan Ironforge : </b><a href=http://phobos/eq/item.php?id=26644>A Sealed Letter</a>
<br><b>Brohan Ironforge says </b>'Oh! thank you! Now I know she is safe. My sweet Tayla. Here is your reward, as promised. A hero such as yourself deserves a weapon with which to uphold your noble values.'
<br><b>Brohan Ironforge gives you : </b><a href=http://phobos/eq/item.php?id=6303>Combine Warhammer</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=2084></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=2128></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=2356></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=2015></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10108></a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>