<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13324>Pestilence Scythe</a><li><a href=http://phobos/eq/item.php?id=13325>Decaying Heart</a><li><a href=http://phobos/eq/item.php?id=18710>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12238>Aegis of Life</a><li><a href=http://phobos/eq/item.php?id=13506>Faded Tunic*</a></ul></td><td><p><b>You say, </b>'What about Lord Grimrot'
<br><b>Camlend Serbold says </b>'You have heard of Lord Grimrot? He is a shadowknight working with the Bloodsabers. We have word he is trying to build an army of undead. Only a powerful knight can rid the lands of Grimrot. So, did you come here to [defend life]?'
<p><b>You say, </b>'defend life'
<br><b>Camlend Serbold says </b>'Then go to the Plains of Karana. Somewhere there, Lord Grimrot is hatching his little plan for the Bloodsabers. Bring me his evil scythe and his heart. It is said that upon his death, his soul will be absorbed into this weapon of darkness. Do this and be rewarded'
<p><b>You say, </b>'Hail'
<br><b>Camlend Serbold says </b>'I say, good to meet you, [Your Name] !  I am Camlend Serbold.  Some call me Serbold the Great.  I am the leader of the righteous order of paladins which serves the Temple of Life.  Together with the clerics of this temple, we defend the will of the great [Rodcet Nife] and smite all who dare to oppose us.'
<p><b>You say, </b>'Rodcet Nife'
<br><b>Camlend Serbold says </b>'Do you feel your heart beating within your chest?  It is Rodcet Nife, the Prime Healer, whose breath keeps it in perfect rhythm.  If you do not pray to His glory then I assure you, someday when your heart begins to slow, you shall be crying out loud to Rodcet Nife.'
<p><b>You give Camlend Serbold : </b><a href=http://phobos/eq/item.php?id=13325>Decaying Heart</a>, <a href=http://phobos/eq/item.php?id=13324>Pestilence Scythe</a>
<br><b>Camlend Serbold gives you : </b><a href=http://phobos/eq/item.php?id=12238>Aegis of Life</a>
<br><b>Camlend Serbold says </b>'Thank you for your service to the Knights of Thunder. Here is your reward.'
<p><b>You give Camlend Serbold : </b><a href=http://phobos/eq/item.php?id=13324>Pestilence Scythe</a>, <a href=http://phobos/eq/item.php?id=13325>Decaying Heart</a>
<br><b>Camlend Serbold gives you : </b><a href=http://phobos/eq/item.php?id=12238>Aegis of Life</a>
<br><b>Camlend Serbold says </b>'Thank you for your service to the Knights of Thunder. Here is your reward.'
<p><b>You give Camlend Serbold : </b><a href=http://phobos/eq/item.php?id=18710>A tattered note</a>
<br><b>Camlend Serbold says </b>'I do not know what these are for.'
<br><b>Camlend Serbold says </b>'Welcome to the Temple of Life. You have much to learn and we have much work to do. Pain, hurt, disease and death lurk everywhere, our job is seemingly endless, but none is more gratifying. Here is our guild tunic, represent us well. Suuspa Clanim shall help you to get started. Good health be with you.'
<br><b>Camlend Serbold gives you : </b><a href=http://phobos/eq/item.php?id=13506>Faded Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Camlend Serbold says </b>'I do not know what these are for.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>