<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=17600>A Tattered Leather Pouch</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13901>Crow's Special Brew</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=10108></a><li><a href=http://phobos/eq/faction.php?id=10102></a><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul></td><td><p><b>You give Crow : </b><a href=http://phobos/eq/item.php?id=17600>A Tattered Leather Pouch</a>
<br><b>Crow gives you : </b><a href=http://phobos/eq/item.php?id=13901>Crow's Special Brew</a>
<br><b>You receive </b> 6gp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10108></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10102></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
</td></tr></table>