<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=22610>An Enchanted Helm Mold</a><li><a href=http://phobos/eq/item.php?id=22611>An Enchanted Bracer Mold</a><li><a href=http://phobos/eq/item.php?id=22614>An Enchanted Greaves Mold</a><li><a href=http://phobos/eq/item.php?id=22613>An Enchanted Armguard Mold</a><li><a href=http://phobos/eq/item.php?id=22615>An Enchanted Gauntlet Mold</a><li><a href=http://phobos/eq/item.php?id=22616>An Enchanted Breastplate Mold</a><li><a href=http://phobos/eq/item.php?id=22612>An Enchanted Boot Mold</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Davloran Girionlis says </b>'Good day [Your Name]. I am Davloran Girionlis Holy Knight in service to the Prime Healer Rodcet Nife. I pride myself on being responsible for ridding my homeland of unimaginable evil during my fighting days. Nowadays I just like to train new Temple of Life paladin [recruits].'
<p><b>You say, </b>'recruits'
<br><b>Davloran Girionlis says </b>'We have a number of new recruits entering our guild hall every single day. For this reason I have developed a set of exercises that test the hunting and gathering skils of all young paladins. If you are a [Paladin of Rodcet] I might be able to present these tests to you as well.'
<p><b>You say, </b>'paladin of rodcet'
<br><b>Davloran Girionlis says </b>'Fantastic [Your Name]. let me explain to you how the exercises work. You will combine a number of magical items that you will gather from our city and in the training areas and combine them in a Lightbringers Assembly Kit. Certain items used in certain quantities will combine into a specific armor material. These materials can then be taken with the appropriate mold to a forge and be combined together to create a piece of Lightbringers Armor. I can present you with the material recipes along with the correct armor molds for each armor piece once you are [ready to begin your exercises].'
<p><b>You say, </b>'ready to begin your exercises'
<br><b>Davloran Girionlis says </b>'Very well [Your Name]. please take this Lightbringers Assembly Kit. When you are ready to gather the items for a specific armor piece you must only tell me what piece you [want] to craft. I can provide you with the recipes and armor molds for Lightbringers Platemail [Helms]. [Bracers]. [Armguards]. [Boots]. [Greaves]. [Gauntlets] and [Breastplates].'
<p><b>You say, </b>'helms'
<br><b>Davloran Girionlis says </b>'To create your helm material you will need to combine 2 Bricks of Crude Iron. 1 Whiskered Bat Backbone. 1 Chunk of Meat and 1 Ale in your assembly kit. Once you have created the proper material take it to a forge along with this mold to fashion your very own Helm of the Lightbringer.'
<br><b>Davloran Girionlis gives you : </b><a href=http://phobos/eq/item.php?id=22610>An Enchanted Helm Mold</a>
<br><b>Davloran Girionlis says </b>'To create your helm material you will need to combine 2 Bricks of Crude Iron. 1 Whiskered Bat Backbone. 1 Chunk of Meat and 1 Ale in your assembly kit. Once you have created the proper material take it to a forge along with this mold to fashion your very own Helm of the Lightbringer.'
<br><b>Davloran Girionlis gives you : </b><a href=http://phobos/eq/item.php?id=22610>An Enchanted Helm Mold</a>
<br><b>Davloran Girionlis says </b>'To create your helm material you will need to combine 2 Bricks of Crude Iron. 1 Whiskered Bat Backbone. 1 Chunk of Meat and 1 Ale in your assembly kit. Once you have created the proper material take it to a forge along with this mold to fashion your very own Helm of the Lightbringer.'
<br><b>Davloran Girionlis gives you : </b><a href=http://phobos/eq/item.php?id=22610>An Enchanted Helm Mold</a>
<p><b>You say, </b>'bracers'
<br><b>Davloran Girionlis says </b>'To create your bracer material you will need to combine 1 Bricks of Crude Iron. 1 Skeleton Tibia. 1 Gnoll Pup Scalp and 1 Ale in your assembly kit. Once you have created the proper material take it to a forge along with this mold to fashion your very own Bracer of the Lightbringer.'
<br><b>Davloran Girionlis gives you : </b><a href=http://phobos/eq/item.php?id=22611>An Enchanted Bracer Mold</a>
<br><b>Davloran Girionlis says </b>'To create your bracer material you will need to combine 1 Bricks of Crude Iron. 1 Skeleton Tibia. 1 Gnoll Pup Scalp and 1 Ale in your assembly kit. Once you have created the proper material take it to a forge along with this mold to fashion your very own Bracer of the Lightbringer.'
<br><b>Davloran Girionlis gives you : </b><a href=http://phobos/eq/item.php?id=22611>An Enchanted Bracer Mold</a>
<p><b>You say, </b>'greaves'
<br><b>Davloran Girionlis says </b>'To create your greaves material you will need to combine 4 Bricks of Crude Iron. 1 Lion Tail. 1 Ruined Cat Pelt. 1 Bottle and 1 Lightstone in your assembly kit. Once you have created the proper material take it to a forge along with this mold to fashion your very own Greaves of the Lightbringer.'
<br><b>Davloran Girionlis gives you : </b><a href=http://phobos/eq/item.php?id=22614>An Enchanted Greaves Mold</a>
<p><b>You say, </b>'armguards'
<br><b>Davloran Girionlis says </b>'To create your armguards material you will need to combine 2 Bricks of Crude Iron. 2 Fire Beetle Carapaces. 1 Gnoll Jawbone and 1 Raw Bamboo in your assembly kit. Once you have created the proper material take it to a forge along with this mold to fashion your very own Armguards of the Lightbringer.'
<br><b>Davloran Girionlis gives you : </b><a href=http://phobos/eq/item.php?id=22613>An Enchanted Armguard Mold</a>
<p><b>You say, </b>'gauntlets'
<br><b>Davloran Girionlis says </b>'To create your gauntlet material you will need to combine 3 Bricks of Crude Iron. 1 Black Wolf Tooth. 1 Mist Wolf Pelt. and 2 Spider Legs in your assembly kit. Once you have created the proper material take it to a forge along with this mold to fashion your very own Gauntlets of the Lightbringer.'
<br><b>Davloran Girionlis gives you : </b><a href=http://phobos/eq/item.php?id=22615>An Enchanted Gauntlet Mold</a>
<p><b>You say, </b>'breastplates'
<br><b>Davloran Girionlis says </b>'To create your breastplate material you will need to combine 5 Bricks of Crude Iron. 1 Rat Eyes. 1 Fire Beetle Eye. 1 Golden Bandit Tooth. 1 Medium Quality Bear Skin and 1 Severed Gnoll Foot in your assembly kit. Once you have created the proper material take it to a forge along with this mold to fashion your very own Breastplate of the Lightbringer. Please come back to see me after you have completed your breastplate. I have a [job] that I can only entrust to one of my finest knights in training.'
<br><b>Davloran Girionlis gives you : </b><a href=http://phobos/eq/item.php?id=22616>An Enchanted Breastplate Mold</a>
<p><b>You say, </b>'job'
<br><b>Davloran Girionlis says </b>'I have been working for quite some time at my blacksmithing skills in my spare time. My initial interest was to make armor for our new recruits. However. after I discovered these armor recipes there has been more of a need for weaponry rather then armor. I have began to construct weapons suitable for all those that pass the training exercises but I have run short on supplies. I need someone to [gather the necessary supplies] for me.'
<p><b>You say, </b>'gather necessary supplies'
<br><b>Davloran Girionlis says </b>'These are exactly what I needed! Its for sure that I have a lot to learn about Smithing but low and behold I was able to create this fine blade out of my remaining materials. Please carry it with you as a symbol of my gratitude. Rodcet smiles down upon you young [Your Name]. you have done well.'
<p><b>You say, </b>'I am ready to begin my exercises'
<br><b>Davloran Girionlis says </b>'Very well [Your Name]. please take this Lightbringers Assembly Kit. When you are ready to gather the items for a specific armor piece you must only tell me what piece you [want] to craft. I can provide you with the recipes and armor molds for Lightbringers Platemail [Helms]. [Bracers]. [Armguards]. [Boots]. [Greaves]. [Gauntlets] and [Breastplates].'
<p><b>You say, </b>'helm'
<br><b>Davloran Girionlis says </b>'To create your helm material you will need to combine 2 Bricks of Crude Iron. 1 Whiskered Bat Backbone. 1 Chunk of Meat and 1 Ale in your assembly kit. Once you have created the proper material take it to a forge along with this mold to fashion your very own Helm of the Lightbringer.'
<br><b>Davloran Girionlis gives you : </b><a href=http://phobos/eq/item.php?id=22610>An Enchanted Helm Mold</a>
<br><b>Davloran Girionlis says </b>'To create your helm material you will need to combine 2 Bricks of Crude Iron. 1 Whiskered Bat Backbone. 1 Chunk of Meat and 1 Ale in your assembly kit. Once you have created the proper material take it to a forge along with this mold to fashion your very own Helm of the Lightbringer.'
<br><b>Davloran Girionlis gives you : </b><a href=http://phobos/eq/item.php?id=22610>An Enchanted Helm Mold</a>
<p><b>You say, </b>'bracer'
<br><b>Davloran Girionlis says </b>'To create your bracer material you will need to combine 1 Bricks of Crude Iron. 1 Skeleton Tibia. 1 Gnoll Pup Scalp and 1 Ale in your assembly kit. Once you have created the proper material take it to a forge along with this mold to fashion your very own Bracer of the Lightbringer.'
<br><b>Davloran Girionlis gives you : </b><a href=http://phobos/eq/item.php?id=22611>An Enchanted Bracer Mold</a>
<p><b>You say, </b>'boots'
<br><b>Davloran Girionlis says </b>'To create your boot material you will need to combine 3 Bricks of Crude Iron. 1 Wisp Essence. 2 Rat Eyes in your assembly kit. Once you have created the proper material take it to a forge along with this mold to fashion your very own Boot of the Lightbringer.'
<br><b>Davloran Girionlis gives you : </b><a href=http://phobos/eq/item.php?id=22612>An Enchanted Boot Mold</a>
<p><b>You say, </b>'helm'
<br><b>Davloran Girionlis says </b>'To create your helm material you will need to combine 2 Bricks of Crude Iron. 1 Whiskered Bat Backbone. 1 Chunk of Meat and 1 Ale in your assembly kit. Once you have created the proper material take it to a forge along with this mold to fashion your very own Helm of the Lightbringer.'
<br><b>Davloran Girionlis gives you : </b><a href=http://phobos/eq/item.php?id=22610>An Enchanted Helm Mold</a>
<br><b>Davloran Girionlis says </b>'To create your helm material you will need to combine 2 Bricks of Crude Iron. 1 Whiskered Bat Backbone. 1 Chunk of Meat and 1 Ale in your assembly kit. Once you have created the proper material take it to a forge along with this mold to fashion your very own Helm of the Lightbringer.'
<br><b>Davloran Girionlis gives you : </b><a href=http://phobos/eq/item.php?id=22610>An Enchanted Helm Mold</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>