<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><font color=white>The npc waits 10 seconds...</font>
<br><b>Faldor Hendrys says </b>'What, [Your Name]?  Do I look like a merchant to you?  Just because all these merchants are in my library, it doesn't mean that I am one.  If you are interested in something other than spell scrolls, then, we can talk.'
</td></tr></table>