<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Guard Liben says </b>'Hello there. [Your Name].  Guard Liben at your service.  You can walk the streets of Qeynos and feel safe knowing that we guards are here to protect you.  Just be careful not to fall in with the [wrong crowd].'
<p><b>You say, </b>'wrong crowd'
<br><b>Guard Liben says </b>'Oh you know. the Circle.  The Circle of Unseen Hands is what they call themselves.  They are a bunch of thieves and murderers.  Just stay clear of them. if you know what's good for you.'
</td></tr></table>