<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13713>A Small Tattered Dress</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13188>Golden Locket</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=36>Citizens of Qeynos</a><li><a href=http://phobos/eq/faction.php?id=9>Antonius Bayle</a><li><a href=http://phobos/eq/faction.php?id=217>Merchants of Qeynos</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a><li><a href=http://phobos/eq/faction.php?id=33>Circle of Unseen Hands</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Guard Elron says </b>'Greetings. I am sorry but I can't concentrate on my post and talk to you at the same time. Especially when I should be out searching for [Lucie]..  Please excuse me.'
<p><b>You say, </b>'lucie'
<br><b>Guard Elron says </b>'Lucie is my only daughter. Her mother was killed by gnolls a little over a year ago, now Lucie is missing. Ton Firepride said he saw her playing in the south pond.  I have told her a million times to stay out of the aqueducts..  She never listens..  Now I spend every free moment searching for my little girl, if only I could find some clue to her fate. Well, I need to get back to work. Fare well, [Your Name].'
<p><b>You give Guard Elron : </b><a href=http://phobos/eq/item.php?id=13713>A Small Tattered Dress</a>
<br><b>Guard Elron says </b>'Oh gods.. no.. no.. I warned her about the aqueducts.. I warned her.. I coudn't watch her every minute of the day, could I? Oh Lucie.. Why didn't you listen to me? I'm sorry... Oh, here, take this - it belonged to her mother. She always said that in times of need, it gave her courage to go on. Thank you for your help, but I'd like to be alone now.'
<br><b>Guard Elron gives you : </b><a href=http://phobos/eq/item.php?id=13188>Golden Locket</a>
<br><b>You receive </b> 3sp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=36>Citizens of Qeynos</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=9>Antonius Bayle</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=33>Circle of Unseen Hands</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=217>Merchants of Qeynos</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>