<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Hurrieta Ironforge says </b>'What are you doing back here?! I cannot stand it when the children allow their friends to run rampant on our estate. Please leave!'
<p><b>You say, </b>'Tayla'
<br><b>Hurrieta Ironforge says </b>'Tayla! She is no Ironforge.'
<p><b>You say, </b>'Weleana'
<br><b>Hurrieta Ironforge says </b>'Waleana is a stain on Brohan's life. A horrid elf. She is gone now and Brohan has moved onto better things and more sanity.'
</td></tr></table>