<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Knargon Lanenda says </b>'Hey..  What's up? My name's Knargon Lanenda. I just came over here from [Freeport] a couple of months ago. I used to run a big business importing goods from [Faydwer]. If you've been to [Freeport]. I'm sure you've heard of me.'
<p><b>You say, </b>'freeport'
<br><b>Knargon Lanenda says </b>'It's a long way from here. . .which is a good thing for me.'
<p><b>You say, </b>'faydwer'
<br><b>Knargon Lanenda says </b>'It's a long way from here. . .which is a good thing for me.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>