<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13073>Bone Chips</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Lashun Novashine says </b>'Well met. [Your Name].  My name is Lashun Novashine and I am a humble priest of Rodcet Nife. the Prime Healer.  I wish to spread His word to every corner of Norrath.  My job gets more difficult each day with so many so willing to take lives rather than preserve them.'
<p><b>You give Lashun Novashine : </b><a href=http://phobos/eq/item.php?id=13073>Bone Chips</a> (x2)
<br><b>Lashun Novashine says </b>'Ah good. I see you seek healing.  But you must offer the remains of one more minion of Bertoxxulous before Rodcet will deem you worthy.'
<br><b>Lashun Novashine says </b>'Very well. young one.  May the light of the Prime Healer wash away your scars.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<p><b>You give Lashun Novashine : </b><a href=http://phobos/eq/item.php?id=13073>Bone Chips</a> (x4)
<br><b>Lashun Novashine says </b>'Ah good. I see you seek healing.  But you must offer the remains of one more minion of Bertoxxulous before Rodcet will deem you worthy.'
<br><b>Lashun Novashine says </b>'Very well. young one.  May the light of the Prime Healer wash away your scars.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
</td></tr></table>