<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=item1></a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13507>Torn Cloth Tunic*</a><li><a href=http://phobos/eq/item.php?id=10116>Black Headband</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>LuSun says </b>'Ah.. Greetings.. I am Lu'Sun, Guild Master of the Silent Fist Clan. Here, our goal is to train our body, mind, and soul to the peak of perfection.'
<p><b>You say, </b>'Tomer Instogle'
<br><b>LuSun says </b>'Tomer? I think Seta needs someone to go find him.. Go ask her.'
<p><b>You give LuSun : </b><a href=http://phobos/eq/item.php?id=18712>Note with Fist Insignia</a>
<br><b>LuSun says </b>'Greetings, and welcome to the Silent Fist Clan. Don our guild tunic, purge your mind and soul, and begin your lifelong devotion to the Clan. Brother Esrinap will introduce you to our lifestyle and begin your training. Be sound, allow your spirit to open up and guide you.'
<br><b>LuSun gives you : </b><a href=http://phobos/eq/item.php?id=13507>Torn Cloth Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
<hr><b>When LuSun is killed </b>
<br><b>LuSun gives you : </b><a href=http://phobos/eq/item.php?id=10116>Black Headband</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>