<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=24549>A Jester</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13836>Page 34 of a Book</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Moodoro Finharn says </b>'Greetings, fellow traveler! I gotta tell ya. I love this town. 

Especially Crow's. Although the crowd seems a bit shadier than other places of the sort.'
<p><b>You say, </b>'what testament of vanear'
<br><b>Moodoro Finharn says </b>'So you have heard that good old Moodoro has knowledge of the Testament 

of Vanear. I care little for that book. Of course I have it!! If you want it, I will sell it 

to you for two gold pieces.'
<p><b>You say, </b>'I want page 34'
<br><b>Moodoro Finharn says </b>'So, you know I have page 34. Pretty smart of me to tear the most 

important page out before someone else tried, eh? If you really want it, then sit down and 

deal in. Ante is 4 gold. I will give you one card. If it is a jester, then I will give you 

the page. Let's do it.'
<p><b>You give Moodoro Finharn : </b><a href=http://phobos/eq/item.php?id=24549>A Jester</a>
<br><b>Moodoro Finharn says </b>'Lucky you. We were hoping to really clean you out. Here you go. Take the 

page. Even together, the book is nothing more than fiction.'
<br><b>Moodoro Finharn gives you : </b><a href=http://phobos/eq/item.php?id=13836>Page 34 of a Book</a>
</td></tr></table>