<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13302>Monogrammed Cloth</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18797>A tattered note</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a><li><a href=http://phobos/eq/faction.php?id=10113></a><li><a href=http://phobos/eq/faction.php?id=10101></a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=10108></a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Nerissa Clothspinner says </b>'Good day to you! Be careful in the city of Qeynos. [Rumors] of corruption may be true. Believe me. I wish my [sister] were here to help.'
<p><b>You say, </b>'sister'
<br><b>Nerissa Clothspinner says </b>'My sister is in the Karanas. She is a warrior. Her name is Milea. I really need her. Would you please deliver a note to her? You look able-bodied enough for the job.'
<p><b>You say, </b>'deliver a note'
<p><b>You say, </b>'rumors'
<br><b>Nerissa Clothspinner says </b>'I have heard that a few of the Qeynos merchants and guards are not very happy with the current state of the city. Taxes are too high and many of the guards have been sent to the outlands. leaving Qeynos vulnerable to attack. I do not feel the same way. but I fear these few may become many. I [fear for my life].'
<p><b>You say, </b>'fear for your life'
<br><b>Nerissa Clothspinner says </b>'During a late night stroll by the pond in north Qeynos I spied a guard carrying a very large carpet on his shoulders. He approached the pond's edge and unrolled the carpet, the body of another guard rolled out and began to moan. The other guard grabbed for a long spear like weapon from his back. He drove the weapon into the man and pushed him into the pond, I screamed. He turned to me and I ran. I do not think he gave chase, too bad, he would not like to run into my [guardian] at home. I tolr my guardian and we both went to the pond and saw no body. He believes I was drinking too much wine. I do not drink. Now I fear for my life when I am in the streets of Qeynos.'
<p><b>You say, </b>'guardian'
<br><b>Nerissa Clothspinner says </b>'When my big sister left Qeynos for adventure, she left me in the hands of her old time friend Kane Bayle. Yes, the commander of the Qeynos Guards is my guardian. You would think I would be safe. Every time I tell him the rumors I hear he just ignores me. He is too busy I guess.'
<p><b>You give Nerissa Clothspinner : </b><a href=http://phobos/eq/item.php?id=13302>Monogrammed Cloth</a>
<br><b>Nerissa Clothspinner gives you : </b><a href=http://phobos/eq/item.php?id=18797>A tattered note</a>
<br><b>You receive </b> 20sp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10108></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10113></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10101></a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>