<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13910>Blessed Oil Flask</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Nomsoe Jusagta says </b>'Greetings and welcome to the Temple of Life! The healing of the world shall begin within. Let me know if you have seen a [new disciple of life]. I have a task which needs to be attended to.'
<p><b>You say, </b>'new disciple of life'
<br><b>Nomsoe Jusagta says </b>'It is good to meet a new follower of the Prime Healer. Remember that we must defend all life. Disease and poison are the enemies. Within Qeynos we work hand in hand with other guilds. I seek an acolyte to [deliver a flask].'
<p><b>You say, </b>'deliver a flask'
<br><b>Nomsoe Jusagta says </b>'Our allies, the Knights of Thunder, have requested that we aid their followers in the Plains of Karana. We have a few young acolytes working there now. Take this blessed oil to Brother Estle. Follow the path to the plains. He shall be waiting for you by a tree alongside the path.'
<br><b>Nomsoe Jusagta gives you : </b><a href=http://phobos/eq/item.php?id=13910>Blessed Oil Flask</a>
</td></tr></table>