<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'What do you want?!! Can't you see I am busy drinking here? You don't even look like you belonging here. You can have my seat when I am good and ready to leave, which won't be for a while yet. If I were you I would get lost before I got myself hurt.'
<p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'What do you want?!! Can't you see I am busy drinking here? You don't even look like you belonging here. You can have my seat when I am good and ready to leave, which won't be for a while yet. If I were you I would get lost before I got myself hurt.'
</td></tr></table>