<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=item1></a><li><a href=http://phobos/eq/item.php?id=13911>PrayerBeads</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13506>Faded Tunic*</a><li><a href=http://phobos/eq/item.php?id=18927>Temple Summons</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Priestess Jahnda says </b>'Welcome to the Temple of Life. where the will of Rodcet Nife, the Prime Healer, is carried out.  I am the High Priestess Jahnda.  If you require any training in our ways. please talk to any of our priests or any of the paladins of the Temple of Life.'
<p><b>You say, </b>'Brother Estle needs the blessed oil'
<br><b>Priestess Jahnda says </b>'I do not distribute the blessed oil of life. Please speak with Nomsoe Jusagta. Tell Nomsoe that Brother Estle needs the blessed oil.'
<p><b>You say, </b>'hayle mool'
<br><b>Priestess Jahnda says </b>'Brother Hayle Mool is one of our finest clerics. He could convert anyone to the ways of Rodcet Nife. Recently, he has been out in the [Plains of Karana] trying to befriend the [Splitpaw clan]. I pray he has not become their prisoner or even worse, their dinner.'
<p><b>You give Priestess Jahnda : </b><a href=http://phobos/eq/item.php?id=18714>A tattered note</a>
<br><b>Priestess Jahnda says </b>'Welcome to the Temple of Life. I am Jahnda. the High Priestess of the Clerics of Nife. Wear this tunic with pride and carry out the will of Nife. Please. see Tonmerk Plorsin or Nomsoe Jusagta. They will help get you started spreading the will of The Prime Healer.'
<br><b>Priestess Jahnda gives you : </b><a href=http://phobos/eq/item.php?id=13506>Faded Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Priestess Jahnda : </b><a href=http://phobos/eq/item.php?id=13911>PrayerBeads</a>
<br><b>Priestess Jahnda says </b>'Oh my word!! This is terrible news. This belongs to Hayle Mool. He has been captured by the Splitpaw Clan while in Karana. You must go to his aid. We cannot do so at this time. Here. Be sure to hand him this summons. I will need to speak with him.'
<br><b>Priestess Jahnda gives you : </b><a href=http://phobos/eq/item.php?id=18927>Temple Summons</a>
</td></tr></table>