<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13949>Diseased Wolf Pelt</a><li><a href=http://phobos/eq/item.php?id=13298>Putrid Bear Hide</a><li><a href=http://phobos/eq/item.php?id=13419>Vegetables</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15226>Spell: Endure Disease</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Priestess Caulria says </b>'Welcome to the holy Temple of Life.  Your presence shows an interest in our ways.  We are the followers of the [Prime Healer] and would gladly open our arms to any who [serve Rodcet Nife].  Do we not all owe our lives to the sustaining force of the Prime Healer?'
<p><b>You say, </b>'prime healer'
<br><b>Priestess Caulria says </b>'The Prime Healer is Rodcet Nife.  The one whose power flows through your body.  He is the air that you breathe.  To serve Him is to serve every living creature.  Do you wish to [serve the Prime Healer] or do you [need more time for contemplation]?'
<p><b>You say, </b>'serve the rodcet nife'
<br><b>Priestess Caulria says </b>'The Prime Healer is Rodcet Nife.  The one whose power flows through your body.  He is the air that you breathe.  To serve Him is to serve every living creature.  Do you wish to [serve the Prime Healer] or do you [need more time for contemplation]?'
<p><b>You say, </b>'serve the prime healer'
<br><b>Priestess Caulria says </b>'The Prime Healer is Rodcet Nife.  The one whose power flows through your body.  He is the air that you breathe.  To serve Him is to serve every living creature.  Do you wish to [serve the Prime Healer] or do you [need more time for contemplation]?'
<br><b>Priestess Caulria says </b>'The Temple of Life smiles upon you. friend..  but such a delicate matter can only be entrusted to our most loyal members.'
<p><b>You say, </b>'need more time for contemplation'
<br><b>Priestess Caulria says </b>'I understand.  Sometimes a person can be filled with the lies of so many other false deities that he cannot see the truth when it lies in front of him.'
<p><b>You give Priestess Caulria : </b><a href=http://phobos/eq/item.php?id=13949>Diseased Wolf Pelt</a>
<br><b>Priestess Caulria says </b>'I see you have rid our land of a beast tainted with the blood of Bertoxxulous.  The Prime Healer shall look favorably upon your soul.  Here is our thanks and just in case the beast may have bitten you...'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<p><b>You give Priestess Caulria : </b><a href=http://phobos/eq/item.php?id=13949>Diseased Wolf Pelt</a> (x3)
<br><b>Priestess Caulria says </b>'I see you have rid our land of a beast tainted with the blood of Bertoxxulous.  The Prime Healer shall look favorably upon your soul.  Here is our thanks and just in case the beast may have bitten you...'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<p><b>You give Priestess Caulria : </b><a href=http://phobos/eq/item.php?id=13298>Putrid Bear Hide</a>
<br><b>Priestess Caulria says </b>'Oh dear.  The disease has spread to the realm of the Treefolk.  It must have been difficult to kill such a large and rabid beast.  Here.  Take one of my personal scrolls as thanks for such a brave act of devotion.  I pray you can use it. If not. then perhaps one of your fellow adventurers can.'
<br><b>Priestess Caulria gives you : </b><a href=http://phobos/eq/item.php?id=15226>Spell: Endure Disease</a>
<br><b>You receive </b> 2pp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<p><b>You give Priestess Caulria : </b><a href=http://phobos/eq/item.php?id=13949>Diseased Wolf Pelt</a>, <a href=http://phobos/eq/item.php?id=13298>Putrid Bear Hide</a>
<br><b>Priestess Caulria says </b>'I see you have rid our land of a beast tainted with the blood of Bertoxxulous.  The Prime Healer shall look favorably upon your soul.  Here is our thanks and just in case the beast may have bitten you...'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<br><b>Priestess Caulria says </b>'Oh dear.  The disease has spread to the realm of the Treefolk.  It must have been difficult to kill such a large and rabid beast.  Here.  Take one of my personal scrolls as thanks for such a brave act of devotion.  I pray you can use it. If not. then perhaps one of your fellow adventurers can.'
<br><b>Priestess Caulria gives you : </b><a href=http://phobos/eq/item.php?id=15226>Spell: Endure Disease</a>
<br><b>You receive </b> 2pp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<br><b>Priestess Caulria says </b>'Oh dear.  The disease has spread to the realm of the Treefolk.  It must have been difficult to kill such a large and rabid beast.  Here.  Take one of my personal scrolls as thanks for such a brave act of devotion.  I pray you can use it. If not. then perhaps one of your fellow adventurers can.'
<br><b>Priestess Caulria gives you : </b><a href=http://phobos/eq/item.php?id=15226>Spell: Endure Disease</a>
<br><b>You receive </b> 2pp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<p><b>You give Priestess Caulria : </b><a href=http://phobos/eq/item.php?id=13419>Vegetables</a> (x2)
<br><b>Priestess Caulria says </b>'I see you have rid our land of a beast tainted with the blood of Bertoxxulous.  The Prime Healer shall look favorably upon your soul.  Here is our thanks and just in case the beast may have bitten you...'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<p><b>You give Priestess Caulria : </b><a href=http://phobos/eq/item.php?id=13949>Diseased Wolf Pelt</a>, <a href=http://phobos/eq/item.php?id=13298>Putrid Bear Hide</a> (x3)
<br><b>Priestess Caulria says </b>'I see you have rid our land of a beast tainted with the blood of Bertoxxulous.  The Prime Healer shall look favorably upon your soul.  Here is our thanks and just in case the beast may have bitten you...'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<br><b>Priestess Caulria says </b>'Oh dear.  The disease has spread to the realm of the Treefolk.  It must have been difficult to kill such a large and rabid beast.  Here.  Take one of my personal scrolls as thanks for such a brave act of devotion.  I pray you can use it. If not. then perhaps one of your fellow adventurers can.'
<br><b>Priestess Caulria gives you : </b><a href=http://phobos/eq/item.php?id=15226>Spell: Endure Disease</a>
<br><b>You receive </b> 1pp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
</td></tr></table>