<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Roesager Thusten says </b>'Hail. [Your Name]!  My name is Roesager Thusten. Paladin of Life.  I am a loyal servant of the Prime Healer and I seek to destroy all who wish to bring death and disease to the land of Norrath.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>