<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13717>Rat Head</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=10108></a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Sneed Galliway says </b>'Hello. [Your Name].  I am Sneed Galliway, merchant and citizen.  I run the only general store in all of Qeynos. serving the needs of the many adventurers who call Qeynos home.  If only one of them would take the time to help me with my er... [problem]...'
<p><b>You say, </b>'problem'
<br><b>Sneed Galliway says </b>'Shhh..  Keep it down.  It seems I have a little rodent problem in my store.  A mangy rat keeps digging into my crates of rations.  He looks as if he is diseased.  If you help me by killing this pest. I will make it worth your while.  Bring me his head as proof it is done.'
<p><b>You say, </b>'Ronn Castekin'
<br><b>Sneed Galliway says </b>'Ronn? I saw him a few days ago. He was with someone dressed in black I didn't recognize .. I think I saw them later that day, swimming in the north pond. They really should stay away from the aqueducts. They can be quite dangerous. Full of rats, ya know.'
<p><b>You give Sneed Galliway : </b><a href=http://phobos/eq/item.php?id=13717>Rat Head</a>
<br><b>Sneed Galliway says </b>'HA!  Good work!  I knew you were the person for the job.  A regular ratslayer you are.  Here is your reward as promised.  Be sure you keep this between us.'
<br><b>You receive </b> 6cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10108></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
</td></tr></table>