<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13301>Rat Shaped Ring</a><li><a href=http://phobos/eq/item.php?id=13908>Busted Prayer Beads</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=9>Antonius Bayle</a><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a><li><a href=http://phobos/eq/faction.php?id=257>Priests of Life</a><li><a href=http://phobos/eq/faction.php?id=183>Knights of Thunder</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=21>Bloodsabers</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Suuspa Clanim says </b>'Welcome to the Temple of Life, [Your Name].  It is here that you may pay tribute to the Prime Healer. Does not your heart beat with the sound of life? It is He who makes it so. Do not let the hand of Bertoxxulous and his [new disease] lay upon your soul or, like so many, you shall meet your fate at the end of my sword!'
<p><b>You say, </b>'new disease'
<br><b>Suuspa Clanim says </b>'The new disease I speak of is called the Bloodsabers. They are the loyal followers of Bertoxxulous and as such have been condemned by our temple. Do you wish to [join the fight]?'
<p><b>You say, </b>'join the fight'
<br><b>Suuspa Clanim says </b>'Then seek out those who worship the Plaguebringer. End their threat!! Each member has upon them the mark of the Bloodsabers, a rat-shaped ring. I shall reward all those who return such rings to me.'
<p><b>You say, </b>'Brother Trintle attacked Brother Estle'
<br><b>Suuspa Clanim says </b>'Impossible!! What madness do you speak of!!? If he did he must have had a reason. Maybe Trintle had been tainted by the words of Bertoxxulous..?'
<p><b>You give Suuspa Clanim : </b><a href=http://phobos/eq/item.php?id=13301>Rat Shaped Ring</a>
<br><b>Suuspa Clanim says </b>'Ah, one less of the Plaguebringer's followers to poison these lands. Take this as a reward for your service.'
<br><b>You receive </b> 1sp 10cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=9>Antonius Bayle</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=257>Priests of Life</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=183>Knights of Thunder</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=21>Bloodsabers</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Suuspa Clanim : </b><a href=http://phobos/eq/item.php?id=13908>Busted Prayer Beads</a>
<br><b>Suuspa Clanim says </b>'This is not good. Hmph. It appears they are shattered. For the first time one of our members has been swayed. I reward you for your deed. Also, if you have found anything upon Trintle, let me know.'
<br><b>You receive </b> 8cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=9>Antonius Bayle</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=257>Priests of Life</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=183>Knights of Thunder</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=21>Bloodsabers</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>