<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20459>Bag of Provisions</a></ul></td><td><p><b>You say, </b>'Hail'
<p><b>You say, </b>'dogs'
<p><b>You say, </b>'clan house'
<p><b>You say, </b>'Seta sent me to find you'
<p><b>You say, </b>'backpack'
<p><b>You say, </b>'lead you back to master seta'
<p><b>You say, </b>'Hail'
<p><b>You give Tomer Instogle : </b><a href=http://phobos/eq/item.php?id=20459>Bag of Provisions</a>
</td></tr></table>