<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=16581>Bog Juice</a><li><a href=http://phobos/eq/item.php?id=13009>Bandages</a><li><a href=http://phobos/eq/item.php?id=13067>Snake Fang</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Tonmerk Plorsin says </b>'Hello. child.  Welcome to the Temple of Life. Here. you may pay homage to the [Prime Healer]. [Rodcet Nife].  If you are in need of [healing] or require me to [cure disease] or [cure poison]. please inform me.  I am the resident healer of all Qeynos citizens.'
<p><b>You say, </b>'cure disease'
<br><b>Tonmerk Plorsin says </b>'Yes. we can do that.  First. you must fetch me some bandages and brew me some bog juice.  I.. err.. require the bog juice to.. to dampen the bandages.. Yes that's it!  To dampen the bandages.'
<p><b>You say, </b>'cure poison'
<br><b>Tonmerk Plorsin says </b>'To cast the poison from your body I require one snake fang.  The fang will contain a hint of poison which will help me focus my casting.'
<p><b>You say, </b>'prime healer'
<br><b>Tonmerk Plorsin says </b>'He is the sustaining force of all life.  It is in honor of Him that the Temple of Life was built.  Engineered with the help of the [Academy of Arcane Science].'
<p><b>You say, </b>'academy of arcane science'
<br><b>Tonmerk Plorsin says </b>'The Academy of Arcane Science is the greatest school of magic in Antonica.  It houses a wealth of resources and knowledge pertaining to any of the circles of magic.  It is also a marvel of magical engineering.  If you should ever visit Freeport. be sure to let me know.  I seek a faithful cleric to [pickup a reagent].'
<p><b>You say, </b>'pickup a reagent'
<br><b>Tonmerk Plorsin says </b>'Please deliver this potion to Serna Tasknon in The Academy of Arcane Science, she will know what it is that I require.'
<p><b>You say, </b>'rodcet nife'
<br><b>Tonmerk Plorsin says </b>'He is the sustaining force of all life.  It is in honor of Him that the Temple of Life was built.  Engineered with the help of the [Academy of Arcane Science].'
<p><b>You give Tonmerk Plorsin : </b><a href=http://phobos/eq/item.php?id=16581>Bog Juice</a>, <a href=http://phobos/eq/item.php?id=13009>Bandages</a>
<br><font color=brown><b>Tonmerk Plorsin casts a spell : </b><a href=http://phobos/eq/spell.php?id=96>Counteract Disease</a>.</font>
<p><b>You give Tonmerk Plorsin : </b><a href=http://phobos/eq/item.php?id=13067>Snake Fang</a>
<br><font color=brown><b>Tonmerk Plorsin casts a spell : </b><a href=http://phobos/eq/spell.php?id=95>Counteract Poison</a>.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>