<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13306>T.O.L. 2020</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15248>Spell: Ward Summoned</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Tyokan Mekase says </b>'Please look around. We have many items exclusively for the members of the Temple of Life. We also have [scroll strongboxes]. If you are unsure of what an item is, feel free to ask me.'
<p><b>You say, </b>'what scroll strongboxes'
<br><b>Tyokan Mekase says </b>'The scroll strongboxes are merely personal safes. Most of the members use them. I am afraid all are taken, but if you are here to remove a scroll, merely hand me your key and I shall get it for you. I handle all 20 numbered keys and [Whysia] handles all 30 and 40 numbered keys.'
<p><b>You give Tyokan Mekase : </b><a href=http://phobos/eq/item.php?id=13306>T.O.L. 2020</a>
<br><b>Tyokan Mekase says </b>'Oh, turning in your key, are you? Very well, defender of life. Here you are.'
<br><b>Tyokan Mekase gives you : </b><a href=http://phobos/eq/item.php?id=15248>Spell: Ward Summoned</a>
</td></tr></table>