<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Whysia Flock says </b>'Good evening, [Your Name]. Feel free to take your time browsing. The temple shop is open night and day for your convenience. Most clerics need access to their [scroll strongbox] at all times.'
<p><b>You say, </b>'scroll strongbox'
<br><b>Whysia Flock says </b>'The scroll strongboxes are kept here. They are used by the temple clerics to hold their valuable scrolls. I tend to the 30 and 40 numbered boxes and [Tyokan] deals with the 20s. Presently all are taken and the waiting list is quite long. If you are here to turn in your key, then please do so. I shall get your scroll for you.'
<p><b>You say, </b>'tyokan'
<br><b>Whysia Flock says </b>'Tyokan Mekase is the day merchant here at the temple shop. He usually arrives around eight in the morning or so.'
</td></tr></table>