<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=11486>Storm Giant Head</a><li><a href=http://phobos/eq/item.php?id=28749>Storm Giant Head</a><li><a href=http://phobos/eq/item.php?id=28781>Storm Giant Head</a><li><a href=http://phobos/eq/item.php?id=28782>Storm Giant Head</a><li><a href=http://phobos/eq/item.php?id=11488>Esoteric Meld</a><li><a href=http://phobos/eq/item.php?id=11487>Askr's Sealed Bag of Verity</a></ul></td><td><p><b>You say, </b>'Hail'
<p><b>You say, </b>'what problem'
<p><b>You say, </b>'continue'
<p><b>You say, </b>'It was me'
<p><b>You say, </b>'I am paying attention'
<p><b>You say, </b>'continue'
<p><b>You say, </b>'Bastion of Thunder'
<p><b>You give Askr the Lost : </b><a href=http://phobos/eq/item.php?id=11486>Storm Giant Head</a>, <a href=http://phobos/eq/item.php?id=28749>Storm Giant Head</a>, <a href=http://phobos/eq/item.php?id=28781>Storm Giant Head</a>, <a href=http://phobos/eq/item.php?id=28782>Storm Giant Head</a>
<p><b>You give Askr the Lost : </b><a href=http://phobos/eq/item.php?id=11488>Esoteric Meld</a>
<p><b>You give Askr the Lost : </b><a href=http://phobos/eq/item.php?id=11487>Askr's Sealed Bag of Verity</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>