<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18008>Words of Wealth</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17326>An Empty Pot of Gold</a></ul></td><td><p><b>You give Bob the Painter : </b><a href=http://phobos/eq/item.php?id=18008>Words of Wealth</a>
<br><b>Bob the Painter gives you : </b><a href=http://phobos/eq/item.php?id=17326>An Empty Pot of Gold</a>
<br><b>Bob the Painter says </b>'Ay!!! this is poifect! 'ere take this pot o' gold. It's empty at the moment. Go ask my brother Vinny about the pot and mebbe he'll have a clue how ta get it full agin.
'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Bob the Painter says </b>'I have no interest in this.'
</td></tr></table>