<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13106>Fishing Grubs</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17054>Deck of Spontaneous Generation</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Clukker The Crazy says </b>'Ha ha! Hello to you too! I have got this crazy deck that I'm willing to give to those [looking for a deck]. Ha ha! Oo!'
<p><b>You say, </b>'looking for a deck'
<br><b>Clukker The Crazy says </b>'You're looking for a DECK? Ha ha ha! Well, bring me a fishing grub, tee hee, and I'll give you a nifty deck'
<p><b>You give Clukker The Crazy : </b><a href=http://phobos/eq/item.php?id=13106>Fishing Grubs</a>
<br><font color=green><b>Clukker The Crazy </b>takes a bite out of the fishing grub that was handed to him. Clukker then says, 'Ha ha HA! Thanks for the tasty treat! Now here is your deck! Hee hee haw!'</font>
<br><b>Clukker The Crazy gives you : </b><a href=http://phobos/eq/item.php?id=17054>Deck of Spontaneous Generation</a>
</td></tr></table>