<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=9504>Funny Money</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=9506>A Blue Gift Box</a></ul></td><td><p><b>You give Peachy D-Vicci : </b><a href=http://phobos/eq/item.php?id=9504>Funny Money</a> x4
<br><b>Peachy D-Vicci gives you : </b><a href=http://phobos/eq/item.php?id=9506>A Blue Gift Box</a>
<br><font color=green><b>Peachy D-Vicci </b>reaches into her satchel and pulls out a small box.</font>
<br><b>Peachy D-Vicci says </b>'Here ya go! Enjoy it. Come back soon. Just a warning though, I cant give you a box that you already have. There isn't enough for everyone you know!'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Peachy D-Vicci says </b>'I have no interest in this.'
</td></tr></table>