<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=9510>A Library Card</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17325>Book of Mischief</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Posie the Librarian says </b>'SSH! do not disturb the library! It's  like you who have ruined your own books, you won't ruin mine!'
<p><b>You give Posie the Librarian : </b><a href=http://phobos/eq/item.php?id=9510>A Library Card</a>
<br><b>Posie the Librarian gives you : </b><a href=http://phobos/eq/item.php?id=17325>Book of Mischief</a>
<br><b>Posie the Librarian says </b>'Ahh, you brought your card. Let's see here. [Your Name] is it? Here's the only book we have stocked at the moment. It's missing the chapter on wealth but there's an excellent story about melting your clothing in a pot on page 11. It's a one of a kind story written completely in invisible ink. Enjoy!'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Posie the Librarian says </b>'I have no interest in this.'
</td></tr></table>