<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12143>H. K.  102</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18936>A Sealed Note</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Assistant Kiolna says </b>'Hello! I am Jaylin's new assistant, Kiolna. If you wish to hand in your keys, please give them to me and I will be happy to assist you! It is a pleasure doing business with you.'
<p><b>You give Assistant Kiolna : </b><a href=http://phobos/eq/item.php?id=12143>H. K.  102</a>
<br><b>Assistant Kiolna says </b>'I am sorry to see you check out. Here is all you had in your box. We hope to serve you again. Have a nice day!! Next!'
<br><b>Assistant Kiolna gives you : </b><a href=http://phobos/eq/item.php?id=18936>A Sealed Note</a>
<br><b>Assistant Kiolna says </b>'I have not use for this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>