<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Lislia Goldtune says </b>'Hail. [Your Name] - Are you [interested] in helping the League of Antonican Bards by delivering some [mail]?'
<p><b>You say, </b>'I am interested in delivering mail'
<br><b>Lislia Goldtune says </b>'I have messages that need to go to Freeport and to Qeynos.  Will you [deliver] mail to [Freeport] or [Qeynos] for me?'
</td></tr></table>