<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10086>A Glamour Stone</a><li><a href=http://phobos/eq/item.php?id=10790>Coin of Tash</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10087>Glowing Glamour Stone</a><li><a href=http://phobos/eq/item.php?id=2355>Gleaming Gloves</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Tarn Visilin says </b>'Hello.  I am Tarn Visilin.'
<p><b>You give Tarn Visilin : </b><a href=http://phobos/eq/item.php?id=10086>A Glamour Stone</a>
<br><b>Tarn Visilin says </b>'Here is your stone, fully enchanted.'
<br><b>Tarn Visilin gives you : </b><a href=http://phobos/eq/item.php?id=10087>Glowing Glamour Stone</a>
<p><b>You give Tarn Visilin : </b><a href=http://phobos/eq/item.php?id=10790>Coin of Tash</a>
<br><b>Tarn Visilin says </b>'I see that Sultin has sent you to me.  Very well, here are your gloves.'
<br><b>Tarn Visilin gives you : </b><a href=http://phobos/eq/item.php?id=2355>Gleaming Gloves</a>
<br><b>Tarn Visilin says </b>'I see that Sultin has sent you to me.  Very well, here are your gloves.'
<br><b>Tarn Visilin gives you : </b><a href=http://phobos/eq/item.php?id=2355>Gleaming Gloves</a>
</td></tr></table>