<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=27301>Priceless Velium Battlehammer</a><li><a href=http://phobos/eq/item.php?id=27321>Primal Velium Battlehammer</a><li><a href=http://phobos/eq/item.php?id=27300>Priceless Velium Warsword</a><li><a href=http://phobos/eq/item.php?id=27328>Primal Velium Warsword</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=5833>Priceless Velium Fist Wraps</a><li><a href=http://phobos/eq/item.php?id=27320>Primal Velium Fist Wraps</a><li><a href=http://phobos/eq/item.php?id=5834>Priceless Velium Knight's Sword</a><li><a href=http://phobos/eq/item.php?id=5835>Primal Velium Knight's Sword</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Garath the Trader says </b>'Hail to ya, Traveller, and well met! My Name's Garath, a warrior by trade, though I do dabble in some merchanting on the side. My exploring brought me here, and I saw some wonderous things. I ventured inside this ancient tomb with some friends, and oh! The horrors we encountered! I barely made it out alive, but I did manage to pick up some [weapons to trade].'
<p><b>You say, </b>'weapons'
<br><b>Garath the Trader says </b>'Interested in a trade, are ya? Well, let me tell ya.. I headed into this tomb in hopes of getting a sword I could use, maybe a warhammer.. Humm, yeah a hammer woulda been good also.. Anyhow, I was unlucky in finding those, but I did manage to get a couple weapons... Sadly, they're really more suited to a [Monk] or a [Knight], not really much use to a warrior like myself at all.'
<p><b>You say, </b>'monk'
<br><b>Garath the Trader says </b>'Ah, my eyes fail me lately.. Maybe the cold weather is getting to me? Well, in any case, I picked up some velium hand wraps inside the Tomb here, quite nice.. Yes indeed. I guess I would trade them to ya if you were to give me a warhammer for em. I gotta say, I'm not picky. I'd accept either a primal or a priceless warhammer, and give you these wraps in a straight trade. Heck, I'd take one of each and give you both these hand wraps.'
<p><b>You say, </b>'knight'
<br><b>Garath the Trader says </b>'Knight? Yeah, I don't make much distinction, paladin or shadow knight, they're all knights to me. Well, look here, I got two swords from inside the tomb, but I'll be damned if either of em was suited for a warrior. Clearly a knight's blade, what bad luck for me. I was hopin for a good warsword. That's why I'm standin out here ya know? I was hopin I could find someone who might swap me either a primal or priceless warsword, and take one of these knightly swords in trade.'
<p><b>You give Garath the Trader : </b><a href=http://phobos/eq/item.php?id=27301>Priceless Velium Battlehammer</a>
<br><b>Garath the Trader gives you : </b><a href=http://phobos/eq/item.php?id=5833>Priceless Velium Fist Wraps</a>
<br><b>Garath the Trader says </b>'Ah, excellent! Guess standin out here in the cold proved worthwhile for me after all. You take that weapon and enjoy it, I know I`ll be getting some use of this one. Safe travel to ya, friend!'
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Garath the Trader : </b><a href=http://phobos/eq/item.php?id=27321>Primal Velium Battlehammer</a>
<br><b>Garath the Trader gives you : </b><a href=http://phobos/eq/item.php?id=27320>Primal Velium Fist Wraps</a>
<br><b>Garath the Trader says </b>'Ah, excellent! Guess standin out here in the cold proved worthwhile for me after all. You take that weapon and enjoy it, I know I`ll be getting some use of this one. Safe travel to ya, friend!'
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Garath the Trader : </b><a href=http://phobos/eq/item.php?id=27300>Priceless Velium Warsword</a>
<br><b>Garath the Trader gives you : </b><a href=http://phobos/eq/item.php?id=5834>Priceless Velium Knight's Sword</a>
<br><b>Garath the Trader says </b>'Ah, excellent! Guess standin out here in the cold proved worthwhile for me after all. You take that weapon and enjoy it, I know I`ll be getting some use of this one. Safe travel to ya, friend!'
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Garath the Trader : </b><a href=http://phobos/eq/item.php?id=27328>Primal Velium Warsword</a>
<br><b>Garath the Trader gives you : </b><a href=http://phobos/eq/item.php?id=5835>Primal Velium Knight's Sword</a>
<br><b>Garath the Trader says </b>'Ah, excellent! Guess standin out here in the cold proved worthwhile for me after all. You take that weapon and enjoy it, I know I`ll be getting some use of this one. Safe travel to ya, friend!'
<br><font color=yellow>You gain experience!!</font>
<br><b>Garath the Trader says </b>'I have no use for this, [Your Name].'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>