<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=2700>Essence Blade</a><li><a href=http://phobos/eq/item.php?id=2698>Essence Lens</a><li><a href=http://phobos/eq/item.php?id=2699>Essence Mace</a><li><a href=http://phobos/eq/item.php?id=2748>Essence Pearl</a><li><a href=http://phobos/eq/item.php?id=2842>Essence Ring</a><li><a href=http://phobos/eq/item.php?id=27329>Prismatic Dragon Scale</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=27265>Sleeper's Key</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Nelef the Trader says </b>'Good day to you, friend! Tell me, have you [traversed the cold] and the muck to forge through the forsaken tomb of the sleeping dragon? Perhaps you've come across mighty beasts with [prismatic power] beyond imagination?!'
<p><b>You say, </b>'traversed the cold'
<br><b>Nelef the Trader says </b>'Aha! I knew you looked like a daring and intrepid adventurer! I've been looking for someone like yourself who has made it through that wretched place alive. I haven't had the privelege of coming across any that have had any [proof] they've been there though, so I'm a little skeptical when someone says they have been there, as you can rightly imagine.'
<p><b>You say, </b>'proof'
<br><b>Nelef the Trader says </b>'What proof? Well, let's see. . . Perhaps you can provide me with some kind of trinket that came from the prismatic dragon himself? I'd be most interested in a scale if you were able to get ahold of one.'
<p><b>You say, </b>'prismatic power'
<br><b>Nelef the Trader says </b>'Well, I have heard stories of a dragon who was after a prismatic scale and the key to enter the tomb as proof that the sleeping beast had been released. When he took them from the daring adventurers, he destroyed the key because he didn't want those people to return to the tomb. I have no idea why he did this, but if you were one of those unlucky few, please return to me the trinket he gave you and I'll return to you the key to regain entrance to that place.'
<p><b>You give Nelef the Trader : </b><a href=http://phobos/eq/item.php?id=2700>Essence Blade</a>
<br><font color=green><b>Nelef the Trader </b>beams 'Thank you, take this.'</font>
<br><b>Nelef the Trader gives you : </b><a href=http://phobos/eq/item.php?id=27265>Sleeper's Key</a>
<p><b>You give Nelef the Trader : </b><a href=http://phobos/eq/item.php?id=2698>Essence Lens</a>
<br><font color=green><b>Nelef the Trader </b>beams 'Thank you, take this.'</font>
<br><b>Nelef the Trader gives you : </b><a href=http://phobos/eq/item.php?id=27265>Sleeper's Key</a>
<p><b>You give Nelef the Trader : </b><a href=http://phobos/eq/item.php?id=2699>Essence Mace</a>
<br><font color=green><b>Nelef the Trader </b>beams 'Thank you, take this.'</font>
<br><b>Nelef the Trader gives you : </b><a href=http://phobos/eq/item.php?id=27265>Sleeper's Key</a>
<p><b>You give Nelef the Trader : </b><a href=http://phobos/eq/item.php?id=2748>Essence Pearl</a>
<br><font color=green><b>Nelef the Trader </b>beams 'Thank you, take this.'</font>
<br><b>Nelef the Trader gives you : </b><a href=http://phobos/eq/item.php?id=27265>Sleeper's Key</a>
<p><b>You give Nelef the Trader : </b><a href=http://phobos/eq/item.php?id=2842>Essence Ring</a>
<br><font color=green><b>Nelef the Trader </b>beams 'Thank you, take this.'</font>
<br><b>Nelef the Trader gives you : </b><a href=http://phobos/eq/item.php?id=27265>Sleeper's Key</a>
<p><b>You give Nelef the Trader : </b><a href=http://phobos/eq/item.php?id=27329>Prismatic Dragon Scale</a>
<br><font color=green><b>Nelef the Trader </b>beams 'Thank you, take this.'</font>
<br><b>Nelef the Trader gives you : </b><a href=http://phobos/eq/item.php?id=27265>Sleeper's Key</a>
<br><b>Nelef the Trader says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>