<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1553>Vial of Velium Vapors</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1560>Tanik's note</a></ul></td><td><hr><b>When Tanik Greskil spawns </b>
<p><b>You say, </b>'hail'
<br><b>Tanik Greskil says </b>'Outlander! Thank Brell you've found me! I am the last surviving member of my unit. Our mission was somehow compromised, the bloody Kromrif knew just where to find us... I can't imagine how they knew. I was barely able to escape with my life and wandered into a trap here. I am badly hurt and need your help.'
<p><b>You say, </b>'help'
<br><b>Tanik Greskil says </b>'Quickly, give me a vial of Velium Vapors so I can return home, I am in desperate need of some attention from our clerics.'
<p><b>You say, </b>'velium vapors'
<br><b>Tanik Greskil says </b>'Drat! Are you telling me you don't have one with you? Run back to Thurgadin at once and speak with Frundle, she can make you one. I will do what I can to stay alive. I may need to move about a bit to keep from being discovered. Hurry now outlander, you're my only hope.'
<hr><b>When Tanik Greskil is killed </b>
<p><b>You give Tanik Greskil : </b><a href=http://phobos/eq/item.php?id=1553>Vial of Velium Vapors</a>
<br><b>Tanik Greskil says </b>'Thank you, [Your Name]. I shall be eternally grateful to you. Should you ever require my assistance I pledge to you my aid. Please deliver this to Borannin, it is imperative that he deliver this to the Dain at once. Farewell for now outlander....'
<br><b>Tanik Greskil gives you : </b><a href=http://phobos/eq/item.php?id=1560>Tanik's note</a>
<br><b>Tanik Greskil disappears.</b>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>