<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=5018>Pick</a><li><a href=http://phobos/eq/item.php?id=13036>Dwarven Ale</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=6701>A Dusty Old Leg Bone</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Diggs Duggun says </b>'ail, dere! Ain'tcha a sight fer me sore eyes! I knows dat we're strangers an' all, but might I ask a [boon] of ye?'
<p><b>You say, </b>'boon'
<br><b>Diggs Duggun says </b>'Well, me pickaxe is blunted awfully bad and me ale supplies are dangerously low. If'n ye would be kind enough t' get me a new pick and a couple o' bottles o' dwarven ale, I would be f'rever in yer debt.'
<p><b>You give Diggs Duggun : </b><a href=http://phobos/eq/item.php?id=5018>Pick</a>, <a href=http://phobos/eq/item.php?id=13036>Dwarven Ale</a> x2
<br><font color=green><b>Diggs Duggun </b>drinks one of the ales, burps loudly, then says 'By Brell's Beard! Yer a lifesaver, ya are! 'ere, take dis bone I've found 'ere in dis maze. Looks human ta me and I'm thinkin that a proper burial is in order. Freeport's the closest place dat has one o Marr's temples. I'm thinkin dis was one o' his Holy Knights by da look o' da tattered tunic I found it wrapped in. I'm thinkin Valeron might be havin an interest in it if you show that to him.'</font>
<br><b>Diggs Duggun gives you : </b><a href=http://phobos/eq/item.php?id=6701>A Dusty Old Leg Bone</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>