<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=65574>Dragon Boneshard</a></ul></td><td><hr><b>When #Spirit of Garudon spawns </b>
<br><font color=grey><i>A global variable is unset at this point.</font></i>
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<p><b>You say, </b>'Hail'
<br><b>#Spirit of Garudon says </b>'Traveler, you must help me. I have been tortured in this city for generations. The mark of Kylong adorns the walls of the theater that houses my remains. These markings are preventing me from passing into the theater and rejoining with my body so that I may pass on in peace. If you can reclaim four samples and return them to me, it may be enough to draw power from. With this power I will pass into the theater and rejoin my body and rest in peace. You do this for me, the torture of eternal capture is more than I can bear.'
<p><b>You give #Spirit of Garudon : </b><a href=http://phobos/eq/item.php?id=65574>Dragon Boneshard</a> (x4)
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=109107>#Garudon</a></b> spawns (-120.265,-142.884,18.226).</font>
<br><font color=red><b>#Spirit of Garudon shouts </b>'As you place the remains of the dragon on the ground, a cold draft fills the air. Suddenly in a great vortex, the bones begin to rise up and move carried by the wind. They jut through the air and come down inside of the nearby theater. You hear the faint sound of bones clanking together, which is then followed by a massive moan. A sharp bolt of fear trickles up your spine as you feel anticipation fill the air.'</font>
<br><b>#Spirit of Garudon disappears.</b>
</td></tr></table>