<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=67053>Note to Stiggle</a></ul></td><td><p><b>You give #an Odd Looking Spider : </b><a href=http://phobos/eq/item.php?id=67053>Note to Stiggle</a>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=123150>#Stiggles_Cogswin</a></b> spawns.</font>
<br><b>#an Odd Looking Spider disappears.</b>
</td></tr></table>