<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=26033>Vaniki's Heart</a><li><a href=http://phobos/eq/item.php?id=26009>Zlandicar's Heart</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=26040>Neb's Warbone</a><li><a href=http://phobos/eq/item.php?id=28060>Jaled Dar's Tomb Key</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=244>Paebala</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=32>Chetari</a><li><a href=http://phobos/eq/faction.php?id=365>Zlandicar</a></ul></td><td><p><b>You say, </b>'hail'
<p><b>You say, </b>'chetari'
<br><b>Neb says </b>'Rika sa vi na Chetari aga val rak Zlandicar. The Chetari are an evil breed, shaped by Zlandicar. Asila sa vi ne Paebala ika so takina. They enslave the Paebala. Canti ri va ni makata ra Paebala. The Paebala revolted years ago. Mishi ro ka rilla vi ne graka sal ogoo mashan rina, villi rassa rassa ke! They are powerful in the ways of death, but they fear our goo friends, and our teeth are sharp! Rika re rika so malti fe isha kora, Chetari fa rish na
Paebala. But the Chetari will not rest until we are all dead or slaves. Villi rassa rassa ke, korta ne riki sa vena. Our teeth are sharp, but we can not win. Wilta fa unala kisha Zlandicar maka re, villa rasssa, moa Chetari isa rolak. Zlandicar has the sharpest teeth, and the Chetari do his bidding.'
<p><b>You give Neb : </b><a href=http://phobos/eq/item.php?id=26033>Vaniki's Heart</a>, <a href=http://phobos/eq/item.php?id=26009>Zlandicar's Heart</a>
<br><b>Neb says </b>'Ika Paebala ma ri skasha, Neb`ri mi re skashi! The Paebala
are joyful, Neb is joyful! Misu na tona Vaniki esa Zlandicar, no re Paebala soka mora Chetari, ika tu. With the death of Vaniki and Zlandicar, the Paebala can conquer the Chetari, and rule! Mika na so kaka rika, ug boro Neb`ri, ek val Vaniki ushta. Take this, it is Neb's fighting bone, and here, this key I took from Vaniki.'
<br><b>Neb gives you : </b><a href=http://phobos/eq/item.php?id=26040>Neb's Warbone</a>
<br><b>Neb gives you : </b><a href=http://phobos/eq/item.php?id=28060>Jaled Dar's Tomb Key</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=244>Paebala</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=32>Chetari</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=365>Zlandicar</a> has gotten worse.</font>
<p><b>You give Neb : </b>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>