<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=26010>Neb's head</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Zlandicar says </b>'Hrmm, who have we here?  A fleshling that managed to work past my guards...apparently, then, you have your wits about yourself.  In that case, perhaps you might be useful.  I need you to kill a ratman named Neb, because I cannot find him and he resides in an area too small for me to reach.  He and his clan of Paebala rats are of great annoyance to me, and need to be eradicated so that I may focus on greater tasks at hand.'
<p><b>You say, </b>'who is neb'
<br><b>Zlandicar says </b>'Neb is an enemy of my clan of Chetari ratmen, and a thorn in my side.  Slaughter him and bring me his head, and I will give you the key to Jaled-Dar's Tomb.'
<p><b>You give Zlandicar : </b><a href=http://phobos/eq/item.php?id=26010>Neb's head</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>