<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18069>Venril the Chief</a><li><a href=http://phobos/eq/item.php?id=18068>Before Green</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12889>Large Tassel Bookmark</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>tortured librarian says </b>'Bring to me that which was taken.'
<p><b>You give tortured librarian : </b><a href=http://phobos/eq/item.php?id=18069>Venril the Chief</a>, <a href=http://phobos/eq/item.php?id=18068>Before Green</a>
<br><font color=green><b>tortured librarian </b>fades out of existence. The air smells of death. Something has appeared in your hand.</font>
<br><b>tortured librarian disappears.</b>
<br><b>tortured librarian gives you : </b><a href=http://phobos/eq/item.php?id=12889>Large Tassel Bookmark</a>
<br><b>tortured librarian says </b>'All must be returned!'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>tortured librarian says </b>'All must be returned!'
</td></tr></table>