<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1683>Celestial Fists</a><li><a href=http://phobos/eq/item.php?id=1684>Charred Scale</a><li><a href=http://phobos/eq/item.php?id=1688>Demon Fangs</a><li><a href=http://phobos/eq/item.php?id=1689>Book of Celestial Fists</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1689>Book of Celestial Fists</a><li><a href=http://phobos/eq/item.php?id=1684>Charred Scale</a><li><a href=http://phobos/eq/item.php?id=10652>Celestial Fists</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>#Kaiaren says </b>''
<p><b>You say, </b>'lheao'
<br><b>#Kaiaren says </b>'Hmmm, never heard of him. Well, it doesnt matter, the book is here now. Curse that idiot for writing it in the first place. Not even sure why I let him stick around. If you ever see that clown monk Aradiel, kick him in the shins for me! At any rate, I suppose you would like to find the Fists and have a nice [chat] with them, eh? Their master owes me much. I would reward you well if you were to bring me proof of their masters defeat.'
<p><b>You say, </b>'chat'
<br><b>#Kaiaren says </b>'Yes, I suppose you would. All young children looking for fame and glory will eventually learn the poison of ambition. But how will you find them? They are able to meld with their elements seamlessly and they certainly have no interest in fooling with the likes of you. No, you will need to get their attention. Fortunately, I know how to get their [attention].'
<p><b>You say, </b>'attention'
<br><b>#Kaiaren says </b>'My guess is that the weakest of the Fists will be the easiest to draw out. He is egotistical and arrogant. How he became to master the Discipline of Fire, I do not know. He will most likely be in another form, one of his element. When you find the one you believe to be the Fist, you must challenge him. If you use his true name, Eejag, in your formal challenge, he will respond. A flame can burn intensely but it cannot last for long. Know this when you battle him.'
<br><b>#Kaiaren gives you : </b><a href=http://phobos/eq/item.php?id=1689>Book of Celestial Fists</a>
<p><b>You give #Kaiaren : </b><a href=http://phobos/eq/item.php?id=1683>Celestial Fists</a>
<br><b>#Kaiaren says </b>'Now, then. Where did you find this, monk? This is not just some light reading to be borrowed from the town library. Who gave this to you?'
<br><b>#Kaiaren says </b>'I have no need for this item [Your Name], you can have it back.'
<p><b>You give #Kaiaren : </b><a href=http://phobos/eq/item.php?id=1684>Charred Scale</a>
<br><b>#Kaiaren says </b>'Ahhh, impressive indeed! Now that you have broken the chain of the Fists, the others may come toppling down if you persevere. The Fist of Air is now the weakest, then Earth, and finally Water before the master of them all, Vorash. You must defeat them in order, proving the demise of the last to draw out the one you are after. The task before you is to take this scale and show it to the Fist of Air wherever he may be. Good luck, [Your Name].'
<br><b>#Kaiaren gives you : </b><a href=http://phobos/eq/item.php?id=1684>Charred Scale</a>
<br><b>#Kaiaren says </b>'I have no need for this item [Your Name], you can have it back.'
<p><b>You give #Kaiaren : </b><a href=http://phobos/eq/item.php?id=1688>Demon Fangs</a>, <a href=http://phobos/eq/item.php?id=1689>Book of Celestial Fists</a>
<br><font color=green><b>#Kaiaren </b>bows his head and breathes a long sigh as if relieved of a great weight. He then looks up at you.</font>
<br><b>#Kaiaren says </b>'I honestly did not believe you could have defeated Vorash. Even though he sought nothing by war and bloodshed, it is a life nonetheless and we must mourn him. I will sew these fangs into magical fist wraps and they shall be yours. Remember Xenevorash. A purpose can be found for every situation and individual. To achieve perfection is to perceive this truth.'
<br><b>#Kaiaren gives you : </b><a href=http://phobos/eq/item.php?id=10652>Celestial Fists</a>
<br><b>#Kaiaren says </b>'I have no need for this item [Your Name], you can have it back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>