<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12962>An Ornate Bottle</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12965>bottle of swirling smoke</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>a human skeleton says </b>'Save my.. Soul.. Find.. Wizard.. Desp..'
<p><b>You give a human skeleton : </b><a href=http://phobos/eq/item.php?id=12962>An Ornate Bottle</a>
<br><b>a human skeleton gives you : </b><a href=http://phobos/eq/item.php?id=12965>bottle of swirling smoke</a>
<br><b>a human skeleton disappears.</b>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>