<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1683>Celestial Fists</a><li><a href=http://phobos/eq/item.php?id=1684>Charred Scale</a><li><a href=http://phobos/eq/item.php?id=1688>Demon Fangs</a><li><a href=http://phobos/eq/item.php?id=1689>Book of Celestial Fists</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1683>Celestial Fists</a><li><a href=http://phobos/eq/item.php?id=1684>Charred Scale</a><li><a href=http://phobos/eq/item.php?id=10652>Celestial Fists</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Kaiaren says </b>'AHHH! Get it away from me. Go away. ..Leave me alone.'
<p><b>You say, </b>'celestial fists'
<br><b>Kaiaren says </b>'Eh? Whats that? Bah! That was destroyed long ago. Dont waste my time with fairy taAAAAAGGHH GET IT AWAY!!! HELP!!! Theyre all over MEHEHEHEEEEEee!!'
<hr><b>When Kaiaren is killed </b>
<br><b>Kaiaren says </b>'Not bad.. Now lets see if you can find my trueform if you do we discuss this further.'
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=95183>#Kaiaren</a></b> spawns (306,2470,-339).</font>
<p><b>You give Kaiaren : </b><a href=http://phobos/eq/item.php?id=1683>Celestial Fists</a>
<br><font color=green><b>Kaiaren </b>eyes open wide and he attacks you!</font>
<br><b>Kaiaren gives you : </b><a href=http://phobos/eq/item.php?id=1683>Celestial Fists</a>
<p><b>You give Kaiaren : </b><a href=http://phobos/eq/item.php?id=1684>Charred Scale</a>
<br><b>Kaiaren says </b>'Ahhh, impressive indeed! Now that you have broken the chain of the Fists, the others may come toppling down if you persevere. The Fist of Air is now the weakest, then Earth, and finally Water before the master of them all, Vorash. You must defeat them in order, proving the demise of the last to draw out the one you are after. The task before you is to take this scale and show it to the Fist of Air wherever he may be. Good luck, [Your Name].'
<br><b>Kaiaren gives you : </b><a href=http://phobos/eq/item.php?id=1684>Charred Scale</a>
<p><b>You give Kaiaren : </b><a href=http://phobos/eq/item.php?id=1688>Demon Fangs</a>, <a href=http://phobos/eq/item.php?id=1689>Book of Celestial Fists</a>
<br><font color=green><b>Kaiaren </b>bows his head and breathes a long sigh as if relieved of a great weight. He then looks up at you.</font>
<br><b>Kaiaren says </b>'I honestly did not believe you could have defeated Vorash. Even though he sought nothing by war and bloodshed, it is a life nonetheless and we must mourn him. I will sew these fangs into magical fist wraps and they shall be yours. Remember Xenevorash. A purpose can be found for every situation and individual. To achieve perfection is to perceive this truth.'
<br><b>Kaiaren gives you : </b><a href=http://phobos/eq/item.php?id=10652>Celestial Fists</a>
<br><b>Kaiaren says </b>'I have no need for this item [Your Name], you can have it back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>