<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=29062>Giant Warrior Helmet</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=30219>Coldain Velium Rapier</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=49>Coldain</a><li><a href=http://phobos/eq/faction.php?id=67>Dain Frostreaver IV</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=179>King Tormax</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Chamberlain Krystorf says </b>'Greetings and welcome to Thurgadin, [Your Name]. I am Chamberlain Krystorf and it is my duty to assist the Dain in the management of Icewell Keep and the Royal Court. One could say that Seneschal Aldikar is the Sword of the Dain while I am the Shield, protecting all of his interests and those of the kingdom.'
<p><b>You give Chamberlain Krystorf : </b><a href=http://phobos/eq/item.php?id=29062>Giant Warrior Helmet</a> x4
<br><b>Chamberlain Krystorf says </b>'Well done, [Your Name], the Dain is pleased with your efforts. With a few more brave allies like you, we'll soon be tearing down the halls of Kael Drakkel.'
<br><b>Chamberlain Krystorf gives you : </b><a href=http://phobos/eq/item.php?id=30219>Coldain Velium Rapier</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=49>Coldain</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=67>Dain Frostreaver IV</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=179>King Tormax</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 20pp
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>