<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=9270>Head of Elishia Blackguard</a><li><a href=http://phobos/eq/item.php?id=9271>Head of Reynold Blackguard</a><li><a href=http://phobos/eq/item.php?id=9273>Head of Vaurien Sticklebush</a><li><a href=http://phobos/eq/item.php?id=9272>Head of Zed Sticklebush</a><li><a href=http://phobos/eq/item.php?id=8264>Gnoll Canine</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a><li><a href=http://phobos/eq/faction.php?id=315>Storm Guardians</a></ul></td><td><p><b>You give Not Found : </b><a href=http://phobos/eq/item.php?id=9272>Head of Zed Sticklebush</a>, <a href=http://phobos/eq/item.php?id=9270>Head of Elishia Blackguard</a>, <a href=http://phobos/eq/item.php?id=9273>Head of Vaurien Sticklebush</a>, <a href=http://phobos/eq/item.php?id=9271>Head of Reynold Blackguard</a>
<p><b>You give Not Found : </b><a href=http://phobos/eq/item.php?id=8264>Gnoll Canine</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=315>Storm Guardians</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<p><b>You give Not Found : </b><a href=http://phobos/eq/item.php?id=8264>Gnoll Canine</a> (x3)
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=315>Storm Guardians</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
</td></tr></table>