<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13700>Gnoll Paw</a><li><a href=http://phobos/eq/item.php?id=13231>Bottom of Broken Staff</a><li><a href=http://phobos/eq/item.php?id=13232>Top of Broken Staff</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a><li><a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=279>Sabertooths of Blackburrow</a></ul></td><td><hr><b>When Corun Finisc spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Corun Finisc says </b>'Hello.  My name is Corun Finisc and I am one of the Jaggedpine Treefolk.  It is our divine responsibility to watch over and protect Surefall Glade and its [inhabitants] from those who seek to [destroy] them.'
<p><b>You say, </b>'what inhabitants'
<br><b>Corun Finisc says </b>'The bears of Surefall Glade are our brothers.  We are all children of [Tunare].  We would gladly die in their defense.'
<p><b>You say, </b>'what tunare'
<br><b>Corun Finisc says </b>'Tunare is the Mother of All.  It is though Her will that we protect this land and its many creatures.'
<p><b>You say, </b>'who seek to destroy the inhabitants'
<br><b>Corun Finisc says </b>'The bears of Surefall Glade are our brothers.  We are all children of [Tunare].  We would gladly die in their defense.'
<br><b>Corun Finisc says </b>'Poachers in seach of bear skins and [gnolls] who attack us unprovoked. We are doing all we can to stop them. May [Tunare] give me the strength needed to smite them dead with my [crook].'
<p><b>You say, </b>'destroy'
<br><b>Corun Finisc says </b>'Poachers in seach of bear skins and [gnolls] who attack us unprovoked. We are doing all we can to stop them. May [Tunare] give me the strength needed to smite them dead with my [crook].'
<p><b>You say, </b>'gnolls'
<br><b>Corun Finisc says </b>'The Sabertooths are a vicious band of gnolls who live in Blackburrow, to the east of Surefall Glade. They constantly attack us when we only seek to share this land with them. They also send many patrols out into the Qeynos Hills to the south. We have even seen a Sabertooth skulking about in the caves behind Grizzly Falls. There is a [reward] for his hide.'
<p><b>You say, </b>'reward'
<br><b>Corun Finisc says </b>'Yes. We are offering a small reward for slaying the skulking gnoll in the bear caves. Bring me his paw to claim your bounty. The Jaggedpine Treefolk remember well those who aid their cause.'
<p><b>You say, </b>'crook'
<br><b>Corun Finisc says </b>'My crook? The Jaggedpine crook is an enchanted weapon of the Jaggedpine Treefolk. The [Sabertooths] take great pleasure in destroying the crooks of any Treefolk they manage to slay. If you were to recover the pieces of a broken crook, I would gladly mend it for you.'
<p><b>You say, </b>'sabertooths'
<br><b>Corun Finisc says </b>'The gnolls of Blackburrow are called Sabertooths. They have been seen in force on a regular basis. They are surely up to something.'
<p><b>You give Corun Finisc : </b><a href=http://phobos/eq/item.php?id=13700>Gnoll Paw</a>
<br><b>Corun Finisc says </b>'Thank you for tracking down the filthy little poacher.  Take this as your reward.'
<br><b>You receive </b> 9pp 6gp 6sp 9cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=279>Sabertooths of Blackburrow</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Corun Finisc : </b><a href=http://phobos/eq/item.php?id=13231>Bottom of Broken Staff</a>, <a href=http://phobos/eq/item.php?id=13232>Top of Broken Staff</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>