<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Frenway Marthank says </b>'Greetings. stranger. Please excuse my melancholy state.  I have had some bad news that has brought me great sorrow.'
<p><b>You say, </b>'what bad news'
<br><b>Frenway Marthank says </b>'My youngest son was devoured by a grizzly bear while playing near the caves. It was an unfortunate accident. The great bear was just protecting its territory. Now. could you please just leave me be? <sniff>'
</td></tr></table>