<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18911>A Tattered Cloth Note</a><li><a href=http://phobos/eq/item.php?id=12141>Black Wood Chip</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13945>Flask of Nitrates</a><li><a href=http://phobos/eq/item.php?id=18912>A Tattered Cloth Note</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a><li><a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a><li><a href=http://phobos/eq/faction.php?id=267>QRG Protected Animals</a><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=347>Unkempt Druids</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Gerael Woodone says </b>'It is good to meet you, [Your Name]. You, my friend, are an adventurer. The rugged look of you testifies to that. Let me know if you plan to adventure in the Plains of Karana. I have need of a person such as yourself to [deliver a flask]'
<p><b>You say, </b>'deliver a flask'
<br><b>Gerael Woodone says </b>'That is splendid! I thought I would have to take the long journey to the western Plains of Karana myself. Here you are, my friend. Take this flask of nitrates to a woman named Linaya Sowlin. It will help her crops grow stronger. You will find her farm alongside the road to Highpass Hold. She should pay you well for the delivery. Farewell.'
<br><b>Gerael Woodone gives you : </b><a href=http://phobos/eq/item.php?id=13945>Flask of Nitrates</a>
<p><b>You say, </b>'Jale Phlintoes'
<br><b>Gerael Woodone says </b>'Jale Phlintoes was trained in the ways of the Jaggedpine Treefolk since his birth. He was only eight when his parents were killed by poachers. Young Jale would have had his throat slit also if he were not off fishing at the lake. Unfortunate. The now orphaned Jale was brought up by us druids. After many conflicts with our council, he ran off to start his own sect somewhere in the nearby lands. For his terrorist activities his head now brings a high price.'
<p><b>You say, </b>'Unkempt Druids'
<br><b>Gerael Woodone says </b>'The Unkempt Druids are a radical splinter group of druids. Their beliefs have been contorted by the mad druid [Jale Phlintoes]. It is he who engineers and coordinates the druids' transgressions. From setting lumbermills aflame to murdering any man who dares to wear a bearhide. They must be stopped!! Citizens must learn to understand Tunare's will, not fear it.'
<p><b>You give Gerael Woodone : </b><a href=http://phobos/eq/item.php?id=18911>A Tattered Cloth Note</a>
<br><b>Gerael Woodone says </b>'Oh my!! Our Qeynos Ambassador, Gash, is in danger. Please take the note over to Captain Tillin of the Qeynos Guard then find Gash and inform him [they are trying to kill him]. Go!!'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=267>QRG Protected Animals</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=347>Unkempt Druids</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><b>You receive </b> 2gp 6sp 8cp
<br><b>Gerael Woodone gives you : </b><a href=http://phobos/eq/item.php?id=18912>A Tattered Cloth Note</a>
<p><b>You give Gerael Woodone : </b><a href=http://phobos/eq/item.php?id=12141>Black Wood Chip</a>
<br><b>Gerael Woodone says </b>'So the Unkempt Druids are alive and well.  We shall keep a watchful eye out as should you.  Take this for your bravery and defense of the Jaggedpine.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=267>QRG Protected Animals</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=347>Unkempt Druids</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><b>You receive </b> 4gp 1sp 7cp
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>