<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13813>Gnoll Head</a><li><a href=http://phobos/eq/item.php?id=13825>Poacher's Head</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=8803>Rough Elm Recurve Bow</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a><li><a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=279>Sabertooths of Blackburrow</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Gillarian Naelev says </b>'Welcome, friend. Welcome to Surefall Glade. I need not remind you about [poaching], I hope'
<p><b>You say, </b>'poaching'
<br><b>Gillarian Naelev says </b>'Poaching is illegal. We here are the Protectors of the Pine, rangers sworn to protect our land and all its inhabitants. This includes the wildlife. We spend a lot of time hunting poachers. If you want to [join the hunt], just let me know.'
<p><b>You say, </b>'join the hunt'
<br><b>Gillarian Naelev says </b>'Very good, friend. Be on the lookout for poachers in Surefall Glade or Qeynos Hills, especially in the nearby caves. The poachers are not always human. Often times we find ourselves a Blackburrow gnoll or two. Bring me back their heads. Let's see how they look mounted above the mantle! Be on your way, then.'
<p><b>You give Gillarian Naelev : </b><a href=http://phobos/eq/item.php?id=13813>Gnoll Head</a>
<br><b>Gillarian Naelev says </b>'Good job, [Your Name].'
<br><b>Gillarian Naelev gives you : </b><a href=http://phobos/eq/item.php?id=8803>Rough Elm Recurve Bow</a>
<br><b>You receive </b> 2sp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=279>Sabertooths of Blackburrow</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Gillarian Naelev : </b><a href=http://phobos/eq/item.php?id=13825>Poacher's Head</a>
<br><b>Gillarian Naelev says </b>'Good job, [Your Name].'
<br><b>You receive </b> 2sp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=279>Sabertooths of Blackburrow</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>