<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18709>A tattered note</a><li><a href=http://phobos/eq/item.php?id=13913>Barbarian Head</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13509>Mud Stained Tunic*</a><li><a href=http://phobos/eq/item.php?id=17804>Tailored Quiver</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a><li><a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=279>Sabertooths of Blackburrow</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Hager Sureshot says </b>'Greetings, [Your Name].  Feel free to rest here in Surefall Glade.  Just be sure you do no hunting whilst here.  If so, then you shall pay the punishment of death.  I trust you [will abide by the laws]?'
<p><b>You say, </b>'will abide by the laws'
<br><b>Hager Sureshot says </b>'That is wise.  Your health, for now, is assured.  A plague of hunters has infested our land heavily in recent weeks.  The word is out that [Mammoth] still lives.  Hunters have flocked here in search of a trophy or profit and glory.  Instead, they find the deadly accuracy of my arrows.'
<p><b>You say, </b>'Mammoth'
<br><b>Hager Sureshot says </b>'Mammoth is the great bear of the caves.  [Tunare] has blessed our home with Mammoth's presence.  It is said that when the great bear dies, so too shall the Jaggedpine.  He would be quite a trophy to some hunter.  And quite profitable to a poacher. Even the infamous [Talym Shoontar] has tried his hand at the hunt.'
<p><b>You say, </b>'Tunare'
<br><b>Hager Sureshot says </b>'Tunare is the Mother of All.  It is through Her will that we protect this land and its many creatures.'
<p><b>You say, </b>'Talym Shoontar'
<br><b>Hager Sureshot says </b>'Talym Shoontar is a poacher.  He has eluded us for quite some time.  He has organized parties of poachers to plague our forest as well as others.  He hails from Halas, but I have heard he now calls the Plains of Karana home.  I have placed a bounty upon his head.  Do you [wish to collect the bounty]?'
<p><b>You say, </b>'wish to collect the bounty'
<br><b>Hager Sureshot says </b>'That's the spirit!!  Spoken like a true Protector of the Pine!  Last I heard, Talym Shoontar was hunting in the Plains of Karana.  He has also been spotted running to and from Qeynos.  No doubt he is selling hides to some merchant.  End his life of hunting.  Bring me his head to collect the bounty.'
<p><b>You give Hager Sureshot : </b><a href=http://phobos/eq/item.php?id=18709>A tattered note</a>
<br><b>Hager Sureshot says </b>'Welcome, we are the Protectors of the Pine. Wear this tunic of our guild, and help us defend our great and beautiful woods. Go to Larsk Juton, he will help train you and teach you the power of the woods.'
<br><b>Hager Sureshot gives you : </b><a href=http://phobos/eq/item.php?id=13509>Mud Stained Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=279>Sabertooths of Blackburrow</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<p><b>You give Hager Sureshot : </b><a href=http://phobos/eq/item.php?id=13913>Barbarian Head</a>
<br><b>Hager Sureshot says </b>'His days of hunting are over. In the name of the Protectors of the Pine, I offer you this reward. If you are unable to make use of it, you may sell it. I suggest you hold onto it. If you are a ranger it will come in handy.'
<br><b>Hager Sureshot gives you : </b><a href=http://phobos/eq/item.php?id=17804>Tailored Quiver</a>
<br><b>You receive </b> 4pp 8gp 11sp
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=279>Sabertooths of Blackburrow</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>