<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13309>Gnoll Head</a><li><a href=http://phobos/eq/item.php?id=17970>Blackburrow Cask</a><li><a href=http://phobos/eq/item.php?id=18800>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2140>Raw-hide Tunic</a><li><a href=http://phobos/eq/item.php?id=2915>Cloak of Jaggedpine</a><li><a href=http://phobos/eq/item.php?id=18800>A tattered note</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a><li><a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=279>Sabertooths of Blackburrow</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Larsk Juton says </b>'Hail, Adventurer! I hope you are enjoying your time in Surefall Glade. You must be careful when leaving the Jaggedpine. There have been many report of [Sabertooths] attacking travelers.'
<p><b>You say, </b>'Sabertooths'
<br><b>Larsk Juton says </b>'The gnolls of Blackburrow are called Sabertooths. They have been seen in force on a regular basis. They are surely up to something. We have even heard rumors of a [pact] between Qeynos merchants and the dogs.'
<p><b>You say, </b>'pact'
<br><b>Larsk Juton says </b>'Sources have come forward to tell of a pact between a merchant of Qeynos and the Sabertooths. It all has to do with blades and brew. We hear that a meeting will occur soon, somewhere in the Qeynos Hills at night. Do not fear, we shall find a brave ranger to [halt this meeting].'
<p><b>You say, </b>'halt this meeting'
<br><b>Larsk Juton says </b>'Very good of you. Stop this meeting by killing the gnoll in Qeynos Hills. We hear that he shall be there in the late evening, and that his name is Furgoot or Furgy, something like that. Find him and kill him. I want his head. And if you should find any evidence of who the merchant is, be sure to hand it over to me.'
<p><b>You say, </b>'assist in the extermination of the gnoll brewers'
<br><b>Larsk Juton says </b>'Within the bowels of Blackburrow, our scouts have reported seeing the gnoll brewers.  You will go and brave the lair of the dogs and slay these brewers in order to cease the flow of Blackburrow Stout.  During your mission, should you find any Blackburrow casks, you must return them to me.  When you have recovered three of these casks, I shall award you the [Cloak of Jaggedpine].'
<p><b>You say, </b>'Cloak of Jaggedpine'
<br><b>Larsk Juton says </b>'The Cloak of Jaggedpine was made for those loyal to the ways of the forest.  It is enchanted to increase one's dexterity.  It is awarded to those who have aided in our cause to rid the land of those vile dogs called the Sabertooths.  Should you earn one, be sure to hold onto it - you never know when we may alter the enchantments placed upon the cloak.'
<p><b>You give Larsk Juton : </b><a href=http://phobos/eq/item.php?id=13309>Gnoll Head</a>
<br><b>Larsk Juton says </b>'So, I see you rid the hills of the beast. Good work! I have a reward for you. I hope it will be usefull. I am afraid this gnoll's death will not halt the alliance between the two. I shall require your services to [assist in the extermination of the gnoll brewers].'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=279>Sabertooths of Blackburrow</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><b>You receive </b> 3pp 3gp 5sp 2cp
<br><b>Larsk Juton gives you : </b><a href=http://phobos/eq/item.php?id=2140>Raw-hide Tunic</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Larsk Juton : </b><a href=http://phobos/eq/item.php?id=17970>Blackburrow Cask</a> x3
<br><b>Larsk Juton says </b>'Excellent!  Ridding the area of those foul beasts will certainly slow down whatever it is they are planning.  Here is the Cloak of Jaggedpine.  You should keep this, for you never know when we may decide to alter the enchantments on it.'
<br><b>Larsk Juton gives you : </b><a href=http://phobos/eq/item.php?id=2915>Cloak of Jaggedpine</a>
<br><b>You receive </b> 7pp 6gp 9sp 1cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=279>Sabertooths of Blackburrow</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Larsk Juton : </b><a href=http://phobos/eq/item.php?id=18800>A tattered note</a>
<br><b>Larsk Juton says </b>'Fine Work, [Your Name]. Hmmm. It seems this needs taking care of. Take this note to the Captain of the City Guard in Qeynos. His name is Captain Tillin. He will have to attend to this matter. Also.. Let me see the gnoll's head. I must know you killed him. Be safe, my friend. I am sure that whoever this McNeal is, he was simply a lackey. Whoever he works for is most likely going to be looking for you. Watch your back in Qeynos.'
<br><b>Larsk Juton gives you : </b><a href=http://phobos/eq/item.php?id=18800>A tattered note</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>