<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12140>Regurgitonic</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18809>Bayle List II</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=267>QRG Protected Animals</a><li><a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a><li><a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=166>Karana Bandits</a></ul></td><td><p><b>You give Mammoth : </b><a href=http://phobos/eq/item.php?id=12140>Regurgitonic</a>
<br><b>Mammoth gives you : </b><a href=http://phobos/eq/item.php?id=18809>Bayle List II</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=267>QRG Protected Animals</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=166>Karana Bandits</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>