<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12774>Rose of Firiona</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20475>Wood Painting</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Merdan Fleetfoot says </b>'Yes Niera! Oh. Erm. Hi. I mean, uh. How are you?'
<p><b>You say, </b>'who is niera'
<br><font color=green><b>Merdan Fleetfoot </b>blushes. 'She is, uh.. I don't know. I haven't been able to speak with her. She has many suitors, and I'm just another poor ranger. I spend my days here pretending to fish, to carve bows, but really I'm just waiting to catch a glimpse of her. I thought about adventuring into the world to find some kind of token to give her, to show her how I feel, but I can't tear myself away from here.'</font>
<p><b>You give Merdan Fleetfoot : </b><a href=http://phobos/eq/item.php?id=12774>Rose of Firiona</a>
<br><font color=green><b>Merdan Fleetfoot </b>blinks and looks at the flower. 'This is perfect. Thank you! I'm going to go over to her now. Erm, well, maybe I'll wait a week to let the uh.. beauty of the flower.. uhm.. blossom. Yes, that sounds good. Here, you take this painting. I don't need it now. I made it myself, she wouldn't like it anyways.'</font>
<br><b>Merdan Fleetfoot gives you : </b><a href=http://phobos/eq/item.php?id=20475>Wood Painting</a>
<br><font color=green><b>Merdan Fleetfoot </b>will not take this item.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>