<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20476>Silver Chained Locket</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20456>Platinum Speckled Powder</a></ul></td><td><hr><b>When Niera Farbreeze spawns </b>
<p><b>You say, </b>'tune'
<br><b>Niera Farbreeze says </b>'Ohh. Just a little song my mother taught me when I was young. It speaks of the earth, the sky, and the sparkling stars above, always there.'
<p><b>You say, </b>'always there'
<br><b>Niera Farbreeze says </b>'Aye, always there. Like this small bag I wear around my neck. The last gift of my dying mother. It holds a fine dust, a dust she collected during her short life, that she believed brought her luck. It's speckled, flecked as the night sky is with stars.'
<p><b>You say, </b>'speckled flecked dust'
<br><b>Niera Farbreeze says </b>'I've had this little bit of dust, all I have of my mother, for many years now. It's the only reminder I have of her. She said it was special, magical, a warmth to help me through the nights. Even if my life were in the balance, I would have a hard time giving it up.'
<p><b>You give Niera Farbreeze : </b><a href=http://phobos/eq/item.php?id=20476>Silver Chained Locket</a>
<br><b>Niera Farbreeze says </b>'This, this is my mother's amulet. I cannot believe it. Please, take this powder you say you need. Perhaps it does have powers, I don't know, I don't care. Thank you, my eternal thanks for this.'
<br><b>Niera Farbreeze gives you : </b><a href=http://phobos/eq/item.php?id=20456>Platinum Speckled Powder</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>