<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18809>Bayle List II</a><li><a href=http://phobos/eq/item.php?id=18713>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13945>Flask of Nitrates</a><li><a href=http://phobos/eq/item.php?id=15222>Spell: Invigor</a><li><a href=http://phobos/eq/item.php?id=13510>Dried Grass Tunic*</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a><li><a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a><li><a href=http://phobos/eq/faction.php?id=267>QRG Protected Animals</a><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=347>Unkempt Druids</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Te-Anara says </b>'Welcome, friend. I hope your stay in Surefall Glade will enlighten your soul. While you are here we ask you to abide by the [laws of the Jaggedpine].'
<p><b>You say, </b>'laws of the jaggedpine'
<br><b>Te-Anara says </b>'We ask that you do not start campfires on our land. Do not litter our land with any items. Do not chop down our pines or tread upon any foliage. Please do not take more than a bellyful of fish. Do not harm any other wildlife and stay clear of [the great bear]!'
<p><b>You say, </b>'great bear'
<br><b>Te-Anara says </b>'The great bear I speak of is Mammoth. He has lived among us for over a century. Tunare has truly blessed us with his presence. As long as Mammoth lives, so too does Surefall Glade. We are currently worried. Corun has reported that there is something [wrong with Mammoth].'
<p><b>You say, </b>'wrong with Mammoth'
<br><b>Te-Anara says </b>'Mammoth is not eating. We believe something is lodged in his throat. We require a young druid to [fetch a special potion].'
<p><b>You say, </b>'fetch a special potion'
<br><b>Te-Anara says </b>'Go to the gnome city of Ak'Anon on the continent of Faydwer. With their great zoo, you will find a gnome named Kimble Nogflop. Give him this flask of nitrates and he shall hand you a special potion which will force Mammoth to cough up whatever may be stuck inside his throat. Be sure to show me what you find inside his throat upon your return.'
<br><b>Te-Anara gives you : </b><a href=http://phobos/eq/item.php?id=13945>Flask of Nitrates</a>
<p><b>You give Te-Anara : </b><a href=http://phobos/eq/item.php?id=18809>Bayle List II</a>
<br><b>Te-Anara says </b>'Oh my, this must belong to Antonius Bayle! I shall see that he receives it. You have done a great service to Qeynos and Surefall Glade. I rewards you with this. May it be of good use in your future deeds.'
<br><b>Te-Anara gives you : </b><a href=http://phobos/eq/item.php?id=15222>Spell: Invigor</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=267>QRG Protected Animals</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=347>Unkempt Druids</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Te-Anara : </b><a href=http://phobos/eq/item.php?id=18713>A tattered note</a>
<br><b>Te-Anara says </b>'Well met, friend of the forest. You will find power and enlightenment among these woods. Here, wear this tunic and represent the Jaggedpine with pride. Gerael Woodone will help train you and teach you the duties of Jaggedpine Treefolk. The forests, being the soul and heart of Norrath, depend on you and your actions from this day forth.'
<br><b>Te-Anara gives you : </b><a href=http://phobos/eq/item.php?id=13510>Dried Grass Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>