<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13864>Wooden Statue</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18012>Claim Check</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a><li><a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a><li><a href=http://phobos/eq/faction.php?id=267>QRG Protected Animals</a><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=347>Unkempt Druids</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Vesteri Nomanoi says </b>'Hail, Kajigger. I am Vesteri Namanoi. I provide training to the Jaggedpine Treefolk and their allies. If you are not busy, I would like to ask a small [favor] of you.'
<p><b>You say, </b>'favor'
<br><b>Vesteri Nomanoi says </b>'I need you to take this claim check to Qeynos for me. Nesiff Talaherd is a woodcarver who owns a shop in South Qeynos. I am having him carve a small statue of Tunare for Te'Anara. With my training schedule, I can not make the journey to Qeynos. Please give this claim check to Nesiff and bring the statue to me. It is a surprise, so please do not say anything to Te'Anara about it.'
<br><b>Vesteri Nomanoi gives you : </b><a href=http://phobos/eq/item.php?id=18012>Claim Check</a>
<p><b>You give Vesteri Nomanoi : </b><a href=http://phobos/eq/item.php?id=13864>Wooden Statue</a>
<br><b>Vesteri Nomanoi says </b>'Oh thank you so much! Here. Take this reward for your time. I will also tell Te'Anara of you.'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 2sp 10cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=267>QRG Protected Animals</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=347>Unkempt Druids</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>