<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=56004>Ancient Compass</a><li><a href=http://phobos/eq/item.php?id=56005>Mystical Spyglass</a><li><a href=http://phobos/eq/item.php?id=56006>Map of Norrath's Oceans</a><li><a href=http://phobos/eq/item.php?id=56007>Krasnok's Private Reserve</a></ul></td><td><hr><b>When Attendant Mi-Ta spawns </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=228120>#door_exit</a></b> spawns (-47.1,-1061,-285.8).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=228119>#door_enter</a></b> spawns (-290.5,-1363,73.5).</font>
<p><b>You say, </b>'Hail'
<br><b>Attendant Mi-Ta says </b>'Thieves! Thieves aboard the ship! Return what you have stolen and I promise, your death will be swift.'
<p><b>You say, </b>'What have I stolen'
<br><b>Attendant Mi-Ta says </b>'Do not try my patience dryfoot, the Captain and his hands will soon return. If he finds his things missing there will be death, he has been in foul spirits since losing the Stone. Your death if you are found with them. You did steal them? Admit it!'
<p><b>You say, </b>'I did not steal'
<br><font color=green><b>Attendant Mi-Ta </b>gets a suspicious look in his eyes</font>
<br><b>Attendant Mi-Ta says </b>'Ok, I will be honest. I lost the Captain's trinkets. If you help me find them before his return, I am sure I can track something down that will not be missed. I have access to the treasure room, and there is much there in the way of spoils.'
<p><b>You say, </b>'I will help you'
<br><b>Attendant Mi-Ta says </b>'Excellent! It is not much, I was below deck with his compass, spyglass, ocean map, and a bottle of his favorite spirits. I would be in your debt should you find them for me.'
<p><b>You give Attendant Mi-Ta : </b><a href=http://phobos/eq/item.php?id=56004>Ancient Compass</a>, <a href=http://phobos/eq/item.php?id=56005>Mystical Spyglass</a>, <a href=http://phobos/eq/item.php?id=56006>Map of Norrath's Oceans</a>, <a href=http://phobos/eq/item.php?id=56007>Krasnok's Private Reserve</a>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=228121>#Captain_Krasnok</a></b> spawns (-46,-1281,-285.8).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=228122>Fist_of_Krasnok</a></b> spawns (-120,-1281,-285.8).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=228122>Fist_of_Krasnok</a></b> spawns (118,-1281,-285.8).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=228122>Fist_of_Krasnok</a></b> spawns (-120,-1090,-285.8).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=228122>Fist_of_Krasnok</a></b> spawns (124,-1090,-285.8).</font>
<br><b>Attendant Mi-Ta disappears.</b>
</td></tr></table>