<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>#Translocator Gethia says </b>'Hello there, [Your Name]. There seem to be some strange problems with the boats in this area. The Academy of Arcane Sciences has sent a small team of us to investigate them. If you need to [travel to the Timorous Deep] in the meantime, I can transport you to my companion there.'
<p><b>You say, </b>'timorous deep'
<br><b>#Translocator Gethia says </b>'Off you go!'
<br><font color=white><b>The Player moves to zone 96 at -3260.1,-4544.56,19.47</b></font>
</td></tr></table>