<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12880>Frontier Ore</a><li><a href=http://phobos/eq/item.php?id=6552>Gem of Nimbleness</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Dapper Blackhammer says </b>'Hello, [Your Name]. What brings you to this neck of the mountains? Do you have any work for me?'
<p><b>You say, </b>'i have work for you'
<br><b>Dapper Blackhammer says </b>'Very good. Very good. What I require, if it is the whistler ya seek, is 500 platinum and the two components necessary. Once I have all three, I will then commence ta doin that right away fer ya.'
<p><b>You give Dapper Blackhammer : </b><a href=http://phobos/eq/item.php?id=12880>Frontier Ore</a>, <a href=http://phobos/eq/item.php?id=6552>Gem of Nimbleness</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>