<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=item1></a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=5029>Bronze Bastard Sword</a></ul></td><td><p><b>You give Guard Haldin : </b><a href=http://phobos/eq/item.php?id=18905>A Worn Rune</a>
<br><b>Guard Haldin says </b>'The slaves...thank you! Here, this will help you slaughter those foul orcs!'
<br><font color=yellow>You gain experience!!</font>
<br><b>Guard Haldin gives you : </b><a href=http://phobos/eq/item.php?id=5029>Bronze Bastard Sword</a>
</td></tr></table>