<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18169>Note from Arantir</a><li><a href=http://phobos/eq/item.php?id=14349>Green Oil</a><li><a href=http://phobos/eq/item.php?id=14333>Mistletoe Powder</a><li><a href=http://phobos/eq/item.php?id=14332>Cazic's Skin</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=342>True Spirit</a></ul></td><td><p><b>You say, </b>'hail'
<p><b>You say, </b>'what oil'
<p><b>You give Kandin Firepot : </b><a href=http://phobos/eq/item.php?id=18169>Note from Arantir</a>
<br><b>Kandin Firepot says </b>'Brother! I have one of those. He's great, but he's dead. His name was Gabstik and he was a really powerful wizard. I still have one of his greatest possesions! You look like you could use it. I've added another thing to my shopping list. I require a dry brittle skin that I can mold or a rare oil found in the planes that I can soak the fuse in. Get me one of these things and I'll trade it for my bother's stick.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=342>True Spirit</a> has gotten better.</font>
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<p><b>You give Kandin Firepot : </b><a href=http://phobos/eq/item.php?id=14349>Green Oil</a>
<p><b>You give Kandin Firepot : </b><a href=http://phobos/eq/item.php?id=14333>Mistletoe Powder</a>, <a href=http://phobos/eq/item.php?id=14332>Cazic's Skin</a>
<p><b>You give Kandin Firepot : </b><a href=http://phobos/eq/item.php?id=14332>Cazic's Skin</a>
</td></tr></table>