<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20530>Alluring Horn</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20378>Note to Forpar Fizfla</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Vedico Windwisper says </b>'Hello, [Your Name]. Have you seen the port master? I am here to complain about the shoddy service.'
<p><b>You say, </b>'shoddy service'
<br><b>Vedico Windwisper says </b>'I was sailing from Freeport on one of the boats when a giant cyclops attacked the boat! No one lifted a finger as he stole the horn I was playing and ran off. Someone here has to answer for the loss of my horn.'
<p><b>You say, </b>'giant cyclops'
<br><b>Vedico Windwisper says </b>'He was a huge cyclops! He came rushing up out of the water and stared at me with his big eye and said, 'Me like horn me take and play pretty music!' before he snatched my horn and disappeared back under the waves.'
<p><b>You give Vedico Windwisper : </b><a href=http://phobos/eq/item.php?id=20530>Alluring Horn</a>
<br><b>Vedico Windwisper says </b>'Where did you find this? I thought the cyclops took it. I am in your debt, [Your Name]. This horn has always been special to me.'
<br><font color=green><b>Vedico Windwisper </b>reaches into her pack and pulls out a note. 'Do you think you could deliver this to my gnome friend Forpar? I have not spoken to him in a while and unfortunatly I will be unable to make the trip to visit him. If you are looking to have an instrument made he is the man to ask.'</font>
<br><b>Vedico Windwisper gives you : </b><a href=http://phobos/eq/item.php?id=20378>Note to Forpar Fizfla</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>