<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28036>Power of Fire</a><li><a href=http://phobos/eq/item.php?id=28037>Power of Wind</a><li><a href=http://phobos/eq/item.php?id=28038>Power of Earth</a><li><a href=http://phobos/eq/item.php?id=28039>Power of Water</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28031>Power of the Elements</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Walnan says </b>'Hallo, [Your Name]! I am Walnan, elementalist, summoner, wanderer, and sometimes teacher. Might you be a elementalist in search of the truth?'
<p><b>You say, </b>'i am in search of the truth'
<br><b>Walnan says </b>'The truth is something not all people can handle or understand. If the truth of the elements is what you seek then the Power of the Elements shall reveal all. Have you come to learn of Magi'kot?'
<p><b>You say, </b>'i have come to learn'
<br><b>Walnan says </b>'Magi'kot was the most powerful elementalist of his age. He may have been the most powerful mortal mage of all time, such was his mastery. He wished to obtain infinite knowledge and wisdom in order to further expand the arcane art of Summoning. Do you know what became of Magi'kot?'
<p><b>You say, </b>'no'
<br><b>Walnan says </b>'Only a few elementalists and followers outside our circle know what truly happened to Magi'kot. Even now, many are fearful to speak of his name. If you truly wish to continue, here is what you must do. Gather the Power of the Earth, warded by a fae creature. Then seek the Power of Fire, held by an elemental. Next you will need the Power of Wind, held by a twirling and prancing wanderer who has been corrupted. Finally, the Power of Water, held by a ravenous beast who is the minion of a fallen Sarnak. Bring them all to me, and I shall give you the Power of the Elements.'
<p><b>You give Walnan : </b><a href=http://phobos/eq/item.php?id=28036>Power of Fire</a>, <a href=http://phobos/eq/item.php?id=28037>Power of Wind</a>, <a href=http://phobos/eq/item.php?id=28038>Power of Earth</a>, <a href=http://phobos/eq/item.php?id=28039>Power of Water</a>
<br><b>Walnan says </b>'The arcane art of Summoning is derived from the power of the elements which surround us. Continue your journey across the Ocean of Tears. In a dark fortress, you should find Akksstaf lurking about. Be wary, but tell him that you seek Magi'kot. Hurry now [Your Name], you do not wish to miss the ship!'
<br><b>Walnan gives you : </b><a href=http://phobos/eq/item.php?id=28031>Power of the Elements</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Walnan says </b>'I do not need these.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>