<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When #A Custodian of Marr spawns </b>
<br><b>#A Custodian of Marr says </b>'Fools!'
<hr><b>When #A Custodian of Marr is killed </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211091>a_gnome_villager</a></b> spawns (1324,651,-115).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211094>a_troll_villager</a></b> spawns (1412,564,-115).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211093>a_high_elf_villager</a></b> spawns (1415,651,-115).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211090>an_erudite_villager</a></b> spawns (1324,564,-115).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211091>a_gnome_villager</a></b> spawns (1331,1338,-115).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211090>an_erudite_villager</a></b> spawns (1332,1253,-115).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211091>a_gnome_villager</a></b> spawns (1417,1251,-115).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211090>an_erudite_villager</a></b> spawns (1417,1341,-115).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211091>a_gnome_villager</a></b> spawns (2015,1341,-115).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211095>a_wood_elf_villager</a></b> spawns (1923,1342,-115).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211093>a_high_elf_villager</a></b> spawns (1922,1251,-115).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211092>a_dwarf_villager</a></b> spawns (2016,1249,-115).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211096>Mirezvakla_Ry`Ten</a></b> spawns (1493,612,-115).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211097>Herot_Terkins</a></b> spawns (1250,609,-115).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211098>Ruark_Barr</a></b> spawns (1372,679,-115).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211099>Shott_Tarbs</a></b> spawns (1376,1395,-115).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211100>Trann_Berk</a></b> spawns (1273,1293,-115).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211101>Thullias_Rhidron</a></b> spawns (1471,1293,-115).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211102>Zullkata_Reeps</a></b> spawns (1969,1405,-115).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211103>Yarezka_Tri`Lok</a></b> spawns (2071,1296,-115).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211104>Fligg_Sterp</a></b> spawns (1968,1175,-115).</font>
</td></tr></table>