<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When A Custodian of Marr  spawns </b>
<br><b>A Custodian of Marr  says </b>'Fools!'
<hr><b>When A Custodian of Marr  is killed </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211077>#a_norrathian_maiden</a></b> spawns (-1725,-2468,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211077>#a_norrathian_maiden</a></b> spawns (-1719,-2485,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211077>#a_norrathian_maiden</a></b> spawns (-1739,-2485,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211078>#a_norrathian_maiden_</a></b> spawns (-1725,-3190,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211078>#a_norrathian_maiden_</a></b> spawns (-1740,-3172,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211078>#a_norrathian_maiden_</a></b> spawns (-1705,-3172,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211079>#_a_norrathian_maiden</a></b> spawns (-1097,-3172,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211079>#_a_norrathian_maiden</a></b> spawns (-1130,-3201,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211079>#_a_norrathian_maiden</a></b> spawns (-1129,-3151,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211080>a_crazed_norrathian</a></b> spawns (-1600,-2400,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211080>a_crazed_norrathian</a></b> spawns (-1870,-2400,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211080>a_crazed_norrathian</a></b> spawns (-1872,-2582,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211080>a_crazed_norrathian</a></b> spawns (-1727,-2588,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211080>a_crazed_norrathian</a></b> spawns (-1600,-2588,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211082>#_a_crazed_norrathian</a></b> spawns (-1841,-3318,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211082>#_a_crazed_norrathian</a></b> spawns (-1725,-3319,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211082>#_a_crazed_norrathian</a></b> spawns (-1621,-3299,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211082>#_a_crazed_norrathian</a></b> spawns (-1636,-3034,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211082>#_a_crazed_norrathian</a></b> spawns (-1816,-3034,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211083>a_crazed_norrathian_</a></b> spawns (-1027,-3293,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211083>a_crazed_norrathian_</a></b> spawns (-1035,-3027,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211083>a_crazed_norrathian_</a></b> spawns (-1229,-3035,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211083>a_crazed_norrathian_</a></b> spawns (-1229,-3303,-113).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211083>a_crazed_norrathian_</a></b> spawns (-1028,-3168,-113).</font>
</td></tr></table>