<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Alekson Garn says </b>'Weakling! How dare you approach me.  Access to Lord Marrs temple is reserved only for the honorable!  You will never be [ready]...'
<p><b>You say, </b>'ready'
<br><b>Alekson Garn says </b>'Be warned, [Your Name], if you believe you are ready, you will fail, even if you can kill Lord Marrs servants!'
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=211076>A_Custodian_of_Marr_</a></b> spawns (,-50,).</font>
</td></tr></table>