<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=69344>Neb's Note</a><li><a href=http://phobos/eq/item.php?id=69388>Shield of Dark Hues</a><li><a href=http://phobos/eq/item.php?id=69387>Dark Cloak of the Whelp</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=69387>Dark Cloak of the Whelp</a><li><a href=http://phobos/eq/item.php?id=69388>Shield of Dark Hues</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Nexona says </b>'Well, what have we here? How dare you enter my lair! I do not take kindly to your kind disturbing me. Are you here for the same reason all other adventurers are? To plunder and destroy the serenity of a place such as this for money and power? You are an affront to us and the Ring of Scale. You don't even look fit enough to eat, but perhaps I could make some use of you. I could have you [assist] me and the Ring of Scale in something we have been planning for a while now.'
<p><b>You say, </b>'assist'
<p><b>You give Nexona : </b><a href=http://phobos/eq/item.php?id=69344>Neb's Note</a>
<br><b>Nexona says </b>'If I understand this writing correctly, you have delivered. I am pleased, but I still do not trust you. However, in fairness, I shall reward you for your effort. If this reward is unsatisfactory, return it and I will find something more applicable. Now leave my lair before my hate overwhelms me!'
<br><font color=yellow>You gain experience!!</font>
<br><b>Nexona says </b>'I have no need for these items, you can have them back'
<p><b>You give Nexona : </b><a href=http://phobos/eq/item.php?id=69388>Shield of Dark Hues</a>
<br><b>Nexona says </b>'How utterly obtuse and arrogant. How about this one then?'
<br><b>Nexona gives you : </b><a href=http://phobos/eq/item.php?id=69387>Dark Cloak of the Whelp</a>
<br><b>Nexona says </b>'I have no need for these items, you can have them back'
<p><b>You give Nexona : </b><a href=http://phobos/eq/item.php?id=69387>Dark Cloak of the Whelp</a>
<br><b>Nexona says </b>'How utterly obtuse and arrogant. How about this one then?'
<br><b>Nexona gives you : </b><a href=http://phobos/eq/item.php?id=69388>Shield of Dark Hues</a>
<br><b>Nexona says </b>'I have no need for these items, you can have them back'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Nexona says </b>'I have no need for these items, you can have them back'
</td></tr></table>