<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=69324>Silverwing's Lexicon</a><li><a href=http://phobos/eq/item.php?id=69381>Earring of the Brood</a><li><a href=http://phobos/eq/item.php?id=69382>Ring of the Silver Dragon</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=69347>Silverwing's List</a><li><a href=http://phobos/eq/item.php?id=69323>Silverwing's Lexicon</a><li><a href=http://phobos/eq/item.php?id=69382>Ring of the Silver Dragon</a><li><a href=http://phobos/eq/item.php?id=69381>Earring of the Brood</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Silverwing says </b>'So, young one, you have come to seek an audience with me. What do you want? Hurry up and speak carefully. I'm not known for my patience or trust of your kind. Perhaps you can [assist] me by collecting a few items, then I may learn to be more trusting.'
<p><b>You say, </b>'I will assist you'
<br><b>Silverwing says </b>'Very well. One of my scouts has been attempting to acquire the locations of powerful, yet inscribable words for me, but has not returned as soon as I'd like. I've grown impatient -- as you might guess. These words contain great magic, I'm sure of it, and when incanted correctly, create a fabled spell of extraordinary power. I had obtained some, but more are missing. Here is my lexicon and a list of found words so far. Go quickly and acquire all eight of the words I need and the spell scroll.'
<br><b>Silverwing gives you : </b><a href=http://phobos/eq/item.php?id=69347>Silverwing's List</a>
<br><b>Silverwing gives you : </b><a href=http://phobos/eq/item.php?id=69323>Silverwing's Lexicon</a>
<p><b>You give Silverwing : </b><a href=http://phobos/eq/item.php?id=69324>Silverwing's Lexicon</a>
<br><b>Silverwing says </b>'I'm somewhat impressed, stranger. You cannot imagine the power this spell may unleash. Take this reward and leave me. If the reward I have given you is not pleasing, hand it back and I will give you a different one. Make haste and leave me be, for I will need to recite this spell in private.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Silverwing says </b>'I have no need for these items, you can have them back'
<p><b>You give Silverwing : </b><a href=http://phobos/eq/item.php?id=69381>Earring of the Brood</a>
<br><b>Silverwing says </b>'How utterly obtuse and arrogant. How about this one then?'
<br><b>Silverwing gives you : </b><a href=http://phobos/eq/item.php?id=69382>Ring of the Silver Dragon</a>
<br><b>Silverwing says </b>'I have no need for these items, you can have them back'
<p><b>You give Silverwing : </b><a href=http://phobos/eq/item.php?id=69382>Ring of the Silver Dragon</a>
<br><b>Silverwing says </b>'How utterly obtuse and arrogant. How about this one then?'
<br><b>Silverwing gives you : </b><a href=http://phobos/eq/item.php?id=69381>Earring of the Brood</a>
<br><b>Silverwing says </b>'I have no need for these items, you can have them back'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Silverwing says </b>'I have no need for these items, you can have them back'
</td></tr></table>