<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=69335>Lendiniara's Trinket</a><li><a href=http://phobos/eq/item.php?id=69385>Necklace of the Melodic Dragon</a><li><a href=http://phobos/eq/item.php?id=69386>Flame-Tempered Girdle</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=69333>Note from Xygoz</a><li><a href=http://phobos/eq/item.php?id=69385>Necklace of the Melodic Dragon</a><li><a href=http://phobos/eq/item.php?id=69386>Flame-Tempered Girdle</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Xygoz  says </b>'Well, I must say it is refreshing to find a new being in my lair after so many years. I have lived a long and fruitful life, yet I yearn for the past and a time when some of us were still whelps, where we learned everything we knew from our masters. My mentor was of the first brood, an ancient dragon, older than any of the other dragons save Veeshan herself. She was and still is a very powerful dragon and I yearn to speak with her. Her name is Lendiniara the Keeper and was the best teacher any dragon could ever have. How would you like to connect me with her great mind? You could perhaps [deliver] a message for me, since I cannot travel these days.'
<p><b>You say, </b>'deliver'
<br><b>Xygoz  says </b>'This is indeed a fortunate day for me. Take this letter to Lendiniara for me. It is no ordinary letter. My message is scribed with a magic only she can see. She will be proud I have used a magic she taught to me to greet her again. Thank you for the assistance mortal.'
<br><b>Xygoz  gives you : </b><a href=http://phobos/eq/item.php?id=69333>Note from Xygoz</a>
<p><b>You give Xygoz  : </b><a href=http://phobos/eq/item.php?id=69335>Lendiniara's Trinket</a>
<br><b>Xygoz  says </b>'Is this trinket truly meant for me? Lendiniara was not one for giving gifts. Oh, how I miss her. I must thank you again. Once again I'm brimming with pride because of my mentor. Here is your reward. If it doesn't suit you, please give it back and I will find something that does. Farewell.'
<br><b>Xygoz  gives you : </b><a href=http://phobos/eq/item.php?id=69385>Necklace of the Melodic Dragon</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Xygoz  : </b><a href=http://phobos/eq/item.php?id=69385>Necklace of the Melodic Dragon</a>
<br><b>Xygoz  says </b>'How utterly obtuse and arrogant. How about this one then?'
<br><b>Xygoz  gives you : </b><a href=http://phobos/eq/item.php?id=69386>Flame-Tempered Girdle</a>
<p><b>You give Xygoz  : </b><a href=http://phobos/eq/item.php?id=69386>Flame-Tempered Girdle</a>
<br><b>Xygoz  says </b>'How utterly obtuse and arrogant. How about this one then?'
<br><b>Xygoz  gives you : </b><a href=http://phobos/eq/item.php?id=69385>Necklace of the Melodic Dragon</a>
</td></tr></table>