<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=5243>Mammoth Calf Hide</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=5234>Black Wolf Mail</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=275>Rogues of the White Rose</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Cappi McTarnigal says </b>'Hail there, [Your Name]! If you are not a [member of the White Rose], then it be best that you stay on the lower level. This here floor is for honest ...ermm respectable rogues only.'
<p><b>You say, </b>'i am a member of the white rose'
<br><b>Cappi McTarnigal says </b>'I hope that you are indeed respectable and loyal to Halas and the Rogues of the White Rose. To do otherwise would bring the wrath of the Six Hammers down on you. But enough with talk! Our caravan to the frigid north leaves in less than two days. and we are short on mammoth calf hides. Return four of them and you will be given items that show your loyalty to our Clan.'
<p><b>You give Cappi McTarnigal : </b><a href=http://phobos/eq/item.php?id=5243>Mammoth Calf Hide</a> (x4)
<br><b>Cappi McTarnigal says </b>'You returned? We believed the gnoll pups got you. The caravan has already left, and these do me little good now. But, as I said before, one must remain respectable. Here is what I promised.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Cappi McTarnigal gives you : </b><a href=http://phobos/eq/item.php?id=5234>Black Wolf Mail</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=275>Rogues of the White Rose</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>