<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13761>Polar Bear Skin</a><li><a href=http://phobos/eq/item.php?id=12223>Wrath Orc Wristbands</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2125>Large Tattered Skullcap</a><li><a href=http://phobos/eq/item.php?id=2171>Large Raw-hide Leggings</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a><li><a href=http://phobos/eq/faction.php?id=361>Wolves of the North</a><li><a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=275>Rogues of the White Rose</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Cindl says </b>'Welcome to my humble shop. I offer fine items fashioned from the skins of the beasts of Everfrost. Leather is my specialty and I can always use [extra hides].'
<p><b>You say, </b>'extra hides'
<br><b>Cindl says </b>'I will offer any hunter some used Tattered Armor for every Polar Bear Skin. I am sure that even you can wrestle the skins from the back of a polar bear cub.'
<p><b>You say, </b>'second job'
<br><b>Cindl says </b>'I have seen the warriors bringing in items called Wrath Orc Wristbands. Apparently they find them upon the lifeless bodies of the snow orc troopers. They are made from a skin I have yet to find. I will gladly reward you with either a Rawhide Tunic or Leggings or even perhaps Leather Gloves. All I ask for are Two Wrath Orc Wristbands.'
<p><b>You give Cindl : </b><a href=http://phobos/eq/item.php?id=13761>Polar Bear Skin</a>
<br><b>Cindl says </b>'This is much appreciated.  Please accept this used armor in return and also a gold piece for yer troubles.  You have done well! I may have a [second job] fer ye, if ye like?'
<br><b>Cindl gives you : </b><a href=http://phobos/eq/item.php?id=2125>Large Tattered Skullcap</a>
<br><b>You receive </b> 1gp
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=361>Wolves of the North</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=275>Rogues of the White Rose</a> has gotten worse.</font>
<p><b>You give Cindl : </b><a href=http://phobos/eq/item.php?id=12223>Wrath Orc Wristbands</a> x2
<br><b>Cindl says </b>'Fine work hunter!  As your reward please accept this item which I have fashioned for you.'
<br><b>Cindl gives you : </b><a href=http://phobos/eq/item.php?id=2171>Large Raw-hide Leggings</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=361>Wolves of the North</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=275>Rogues of the White Rose</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Cindl says </b>'This is not what I asked for!'
</td></tr></table>