<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13245>Empty Bottle of Elixir</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13241>Full Bottle of Elixir</a><li><a href=http://phobos/eq/item.php?id=2012>Leather Boots</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a><li><a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a><li><a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a><li><a href=http://phobos/eq/faction.php?id=361>Wolves of the North</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Dargon McPherson says </b>'Hail, mighty [Your Name]! I assume ye must be a [warrior o' the Wolves]. Why else would ye approach a trainer such as meself, then?'
<p><b>You say, </b>'warrior o'
<br><b>Dargon McPherson says </b>'Aye, 'tis as I thought. I'm glad t' see we've warriors such as yerself amongst the Wolves o' the North. Lately, Kylan's been allowing too many scrawny warriors in, methinks. Nor have they fared well in Everfrost. Many frreeze to death, ye know... Will ye assist me and [deliver an elixir to young warriors] in Everfrost?'
<p><b>You say, </b>'deliver an elixir to young warriors'
<br><b>Dargon McPherson says </b>'Ach, 'tis good o' ye! Take this bottle of elixir to Everfrost Peaks. Find Talin O'Donal. He'll take the first sip and then instruct ye on who else ye need to find. Do that, and I'll give ye a fine reward when ye return the empty elixir bottle. Good luck, then. Don't die.'
<br><b>Dargon McPherson gives you : </b><a href=http://phobos/eq/item.php?id=13241>Full Bottle of Elixir</a>
<p><b>You give Dargon McPherson : </b><a href=http://phobos/eq/item.php?id=13245>Empty Bottle of Elixir</a>
<br><b>Dargon McPherson says </b>'Ye've proven yerself to be a cut above the rest and aided yer fellow warriors, no matter how worthless they were. Ye may take this. It was found in the snow by one of our foraging parties. I hope it can be of use to a warrior like yerself.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Dargon McPherson gives you : </b><a href=http://phobos/eq/item.php?id=2012>Leather Boots</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=361>Wolves of the North</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>