<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=14331>Ro's Breath</a><li><a href=http://phobos/eq/item.php?id=14335>Arantir's Ring</a><li><a href=http://phobos/eq/item.php?id=18168>Note to Arantir</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Dargon says </b>'Hello there, [Your Name].  Can I interest you in any components to help you in your research?'
<p><b>You give Dargon : </b><a href=http://phobos/eq/item.php?id=14331>Ro's Breath</a>
<br><b>Dargon says </b>'So, I've been discovered! You must know Camin - he is one of the only people who could have recognized my work. I have worked very hard to mask my presence here.'
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=29089>Arantir_Karondor</a></b> spawns.</font>
<br><b>Dargon disappears.</b>
<p><b>You give Dargon : </b><a href=http://phobos/eq/item.php?id=14335>Arantir's Ring</a>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=29089>Arantir_Karondor</a></b> spawns.</font>
<p><b>You give Dargon : </b><a href=http://phobos/eq/item.php?id=18168>Note to Arantir</a>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=29089>Arantir_Karondor</a></b> spawns.</font>
</td></tr></table>