<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20708>Jar of Honey</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12220>Everburn Candle</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Dok says </b>'Fine day to ye, [Your Name].  Welcome to me shop.  If ye're searchin' fer a [cigar], ye won't be findin' any, more's th' pity.'
<p><b>You say, </b>'what cigar'
<br><b>Dok says </b>'I was hoping to perfect me creation I was callin' the 'cigar.' but I'm afraid I just couldn't get it right.  To keep from settin' meself on fire, I switched me talents to makin' candles.  I could use help from a person such as yerself.  Ye could [collect the wax] fer me - the candle-makin's.'
<p><b>You say, </b>'i will collect the wax'
<br><b>Dok says </b>'Grreatt!!  Take this wax jarr.  Head to any place ye can find the wee ones they call bixies. I'm afraid ye're going to hafta bash 'em and search to find out if they're carrying any honeycombs.  If they are, then ye can fill the jar with them and combine them, then return the full honeycomb jar to me. I'll be givin' ye a special candle if ye can do that fer me.'
<p><b>You say, </b>'i am going to collect the wax'
<br><b>Dok says </b>'Grreatt!!  Take this wax jarr.  Head to any place ye can find the wee ones they call bixies. I'm afraid ye're going to hafta bash 'em and search to find out if they're carrying any honeycombs.  If they are, then ye can fill the jar with them and combine them, then return the full honeycomb jar to me. I'll be givin' ye a special candle if ye can do that fer me.'
<p><b>You say, </b>'i could collect the wax'
<br><b>Dok says </b>'Grreatt!!  Take this wax jarr.  Head to any place ye can find the wee ones they call bixies. I'm afraid ye're going to hafta bash 'em and search to find out if they're carrying any honeycombs.  If they are, then ye can fill the jar with them and combine them, then return the full honeycomb jar to me. I'll be givin' ye a special candle if ye can do that fer me.'
<p><b>You say, </b>'murderer'
<br><b>Dok says </b>'Aye. I've heard some things about the murderer. I investigated the crime but I could nah find a thing to help solve it. Ye might be able to get some more information from the leader of Clan McMannus. They are a clan that lives on the outskirts of Qeynos Hills in the Western portion of the Karana plains. They are a fishing clan, so they will be near the ocean. Ask their leader about the [murderer].'
<p><b>You say, </b>'sweaty clothing'
<br><b>Dok says </b>'Ah yes. I had forgotten about the sweaty shirt. I did not think it was useful so I sold it to [Tundra Jack].'
<p><b>You say, </b>'tundra jack'
<br><b>Dok says </b>'Tundra Jack is a man who wanders the Everfrost plains with his large polar bear named Iceberg. He has dedicated himself to ridding the land of Ice Giants.'
<p><b>You give Dok : </b><a href=http://phobos/eq/item.php?id=20708>Jar of Honey</a>
<br><b>Dok says </b>'Well done! Here, I made you an Everburn Candle in return.'
<br><b>Dok gives you : </b><a href=http://phobos/eq/item.php?id=12220>Everburn Candle</a>
<br><b>You receive </b> 2pp
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>