<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=item1></a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13513>Torn White Tunic*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Dun McDowell says </b>'Hail.'
<p><b>You give Dun McDowell : </b><a href=http://phobos/eq/item.php?id=18762>A tattered note</a>
<br><b>Dun McDowell says </b>'Ah.. ye wish to be a member o' the White Rose, then. eh? Well, let's train ye fer a bit. and see if ye've got what it takes.'
<br><b>Dun McDowell gives you : </b><a href=http://phobos/eq/item.php?id=13513>Torn White Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>