<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18847>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13574>Soiled Gray Tunic*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Field Priest Keven says </b>'Hail.'
<p><b>You give Field Priest Keven : </b><a href=http://phobos/eq/item.php?id=18847>A tattered note</a>
<br><b>Field Priest Keven says </b>'Thanks.'
<br><b>Field Priest Keven gives you : </b><a href=http://phobos/eq/item.php?id=13574>Soiled Gray Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>