<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Kevan McPherson says </b>'Well met. [Your Name]! I'm Kevan McPherson. the best darn smith in the north. Have ye come to purchase my finely crafted weapons or are ye wanting me ta teach ya the secrets of Northman smithing?'
<p><b>You say, </b>'what northman kite shields'
<br><b>Kevan McPherson says </b>'To smith a Northman kite shield ye'll need a kite shield mold. a smithy hammer. a flask of water and a medium quality folded sheet metal. Remember ye'll have ta smith the metal sheet in a regular forge and finish the shield in our special Northman forge.'
</td></tr></table>