<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12223>Wrath Orc Wristbands</a><li><a href=http://phobos/eq/item.php?id=13898>Bag of Ice Necklaces</a><li><a href=http://phobos/eq/item.php?id=13915>Gnoll Fang</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17944>Empty Bag</a><li><a href=http://phobos/eq/item.php?id=7322>Seax</a><li><a href=http://phobos/eq/item.php?id=13005>Iron Ration</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=361>Wolves of the North</a><li><a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a><li><a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a><li><a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Lysbith McNaff says </b>'Hail! Ye've come to [serve Halas]. have ye not? We're the Wolves o' the North and it is our task to defend our city from harm.'
<p><b>You say, </b>'serve halas'
<br><b>Lysbith McNaff says </b>'Halas is surrounded by barren arctic tundra. We've many foes. Among them are the [orc troopers]. [ice goblins] and the ever-present polar bears.'
<p><b>You say, </b>'what orc troopers'
<br><b>Lysbith McNaff says </b>'So. Ye think yerself strong enough to battle the snow orc troopers?  I pray to the Tribunal that ye are.  If ye can return to me four wrath orc wristbands  from the troopers' bodies. I'll reward ye with the [Seax].'
<p><b>You say, </b>'what ice goblins'
<br><b>Lysbith McNaff says </b>'The ice goblins have plagued our community fer some time now.  At times. they even manage to get inside our walls. Fer the most part. they prey on travelers who pass through Everfrost Peaks. Since they're a weak race. we employ our youngest warriors to [protect the pass].'
<p><b>You say, </b>'what seax'
<br><b>Lysbith McNaff says </b>'The Seax is a Northman warrior's piercing weapon.  Dinnae confuse this with the [Langseax].  The local rogues have also learned to master the Seax.  I'll only offer it to those who battle the [orc troopers].'
<p><b>You say, </b>'gnoll bounty'
<br><b>Lysbith McNaff says </b>'I've placed a bounty on the gnolls o'Blackburrow.  Their whelps have invaded our land and we must carry the fight into their dens.  Join the fight and return three gnoll fangs as proof of yer victory in Blackburrow.  Do so, and earn the respect o' the Wolves o' the North.'
<p><b>You say, </b>'protect the pass'
<br><b>Lysbith McNaff says </b>'Then travel to the Everfrost Peaks and take this pack with you.  I want you to return this pack to me when it is filled with the beaded ice necklaces of the Ice Goblins.  When it is filled, combine the items and return it to me and I shall decide if you deserve a reward for your deed.'
<br><b>Lysbith McNaff gives you : </b><a href=http://phobos/eq/item.php?id=17944>Empty Bag</a>
<p><b>You give Lysbith McNaff : </b><a href=http://phobos/eq/item.php?id=12223>Wrath Orc Wristbands</a> x4
<br><b>Lysbith McNaff says </b>'Well done! You've proved yerself worthy o' this!'
<br><b>Lysbith McNaff gives you : </b><a href=http://phobos/eq/item.php?id=7322>Seax</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=361>Wolves of the North</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<p><b>You give Lysbith McNaff : </b><a href=http://phobos/eq/item.php?id=13898>Bag of Ice Necklaces</a>
<br><b>Lysbith McNaff says </b>'Ye've done well, me young  .  We've gathered these to add to yer provisions.  While in the Everfrost Peaks, be on the watch fer any gnolls ye may find.  I declare there to be a [gnoll bounty].'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 4gp
<br><b>Lysbith McNaff gives you : </b><a href=http://phobos/eq/item.php?id=13005>Iron Ration</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=361>Wolves of the North</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<p><b>You give Lysbith McNaff : </b><a href=http://phobos/eq/item.php?id=13915>Gnoll Fang</a> x3
<br><b>Lysbith McNaff says </b>'Fine work, fine work!  The gnoll threat must be extinguished before it can ever fully grow.  Ye've done yer part to aid our cause.  Please allow me to repay ye with a few provisions and a wee bit o' coin.  Then, continue with yer good deeds.'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 5gp
<br><b>Lysbith McNaff gives you : </b><a href=http://phobos/eq/item.php?id=13005>Iron Ration</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=361>Wolves of the North</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>