<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18151>A Bardic Letter (Qeynos)</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Marton Stringsinger says </b>'Hail. [Your Name] - Are you [interested] in helping the League of Antonican Bards by delivering some [mail]?'
<p><b>You say, </b>'mail'
<br><b>Marton Stringsinger says </b>'The League of Antonican Bards has a courier system made up of travelers and adventurers.  We pay good gold to anyone who will take messages from bards such as myself to one of our more central offices.  Are you [interested]?'
<p><b>You say, </b>'interested'
<br><b>Marton Stringsinger says </b>'I have messages that need to go to - well. right now I have one that needs to go to Qeynos.  Will you [deliver mail to Qeynos] for me?'
<p><b>You say, </b>'deliver mail to qeynos'
<br><b>Marton Stringsinger says </b>'The League of Antonican Bards has a courier system made up of travelers and adventurers.  We pay good gold to anyone who will take messages from bards such as myself to one of our more central offices.  Are you [interested]?'
<br><b>Marton Stringsinger says </b>'Take this letter to Tralyn Marsinger in Qeynos.  You can find him at the bard guild hall.  I am sure he will compensate you for your troubles.'
<br><b>Marton Stringsinger gives you : </b><a href=http://phobos/eq/item.php?id=18151>A Bardic Letter (Qeynos)</a>
</td></tr></table>