<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18847>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13574>Soiled Gray Tunic*</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a><li><a href=http://phobos/eq/faction.php?id=10108></a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'Greetings to you brother. Did [Keven] send you?'
<p><b>You say, </b>'keven sent me'
<br><b>Not Found says </b>'Very well. then let us begin. We are at home in the wilderness and thus it is important that we learn all we can about our surroundings. Now is the time of your learning. You are to venture out. hunt and learn about Everfrost. Return to me with a White Wolf Skin as proof of your successful hunt. We will then continue your training.'
<p><b>You give Not Found : </b><a href=http://phobos/eq/item.php?id=18847>A tattered note</a>
<br><b>Not Found gives you : </b><a href=http://phobos/eq/item.php?id=13574>Soiled Gray Tunic*</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10108></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
</td></tr></table>