<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13249>Barbarian Femur</a><li><a href=http://phobos/eq/item.php?id=13248>Barbarian Jaw</a><li><a href=http://phobos/eq/item.php?id=13247>Barbarian Skull</a><li><a href=http://phobos/eq/item.php?id=13233>Barbarian Rib</a><li><a href=http://phobos/eq/item.php?id=10556>A Barbarian Head</a><li><a href=http://phobos/eq/item.php?id=13913>Barbarian Head</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=5367>Langseax</a><li><a href=http://phobos/eq/item.php?id=5368>Langseax of the Wolves</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Renth McLanis says </b>'Hail, [Your Name]! Have ye come to train?  I train all warriors. All Wolves o' the North must be strong warriors and swift as well. Are ye a young wolf, then? If so, maybe ye can [assist Renth] with his wee problem, eh?'
<p><b>You say, </b>'i can assist renth'
<br><b>Renth McLanis says </b>'I was ordered by Kylan O'Danos to personally escort a young warrior sent to fetch the remains of his cousin, Ivan McMannus. I forgot and spent me greater time testing out the fine spirits. Now I must find the courier and the remains. Will ye [search fer the courier]?'
<p><b>You say, </b>'i will assist renth'
<br><b>Renth McLanis says </b>'I was ordered by Kylan O'Danos to personally escort a young warrior sent to fetch the remains of his cousin, Ivan McMannus. I forgot and spent me greater time testing out the fine spirits. Now I must find the courier and the remains. Will ye [search fer the courier]?'
<p><b>You say, </b>'i will search fer the courier'
<br><b>Renth McLanis says </b>'Thank ye, [Your Name]! Go to Everfrost Peaks and seek out Arnis McLish. Ask him where Megan, the courier, is. Once ye find Megan, would ye ask her where Ivan's remains are? Please go, at once!'
<p><b>You say, </b>'what dangerous matter'
<br><b>Renth McLanis says </b>'It seems there be a murderer in these parts. Someone needs to find this person and put a stop to them. Why don't ye go and talk to Dok in his cigar shop. He might know something about the [murderer]. Once you solve the murder, return the proof to me.'
<p><b>You give Renth McLanis : </b><a href=http://phobos/eq/item.php?id=13248>Barbarian Jaw</a>, <a href=http://phobos/eq/item.php?id=13233>Barbarian Rib</a>, <a href=http://phobos/eq/item.php?id=13249>Barbarian Femur</a>, <a href=http://phobos/eq/item.php?id=13247>Barbarian Skull</a>
<br><b>Renth McLanis says </b>'Thank ye, [Your Name]! I knew ye could do it. It is a sad thing, but at least now he can rest in peace. Here is something for your efforts. If ye are interested, there is a [dangerous matter] that needs to be looked into.'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 5cp
<p><b>You give Renth McLanis : </b><a href=http://phobos/eq/item.php?id=10556>A Barbarian Head</a>
<br><b>Renth McLanis says </b>'Nice work [Your Name]! Basil has always been an outcast of sorts. I'm glad to see you were able to stop him. Here is a Langseax for your efforts.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Renth McLanis gives you : </b><a href=http://phobos/eq/item.php?id=5367>Langseax</a>
<p><b>You give Renth McLanis : </b><a href=http://phobos/eq/item.php?id=13913>Barbarian Head</a>
<br><b>Renth McLanis says </b>'Nice work [Your Name]! Paglan has always been an outcast of sorts. I'm glad to see you were able to stop him. Here is a Langseax of the Wolves for your efforts.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Renth McLanis gives you : </b><a href=http://phobos/eq/item.php?id=5368>Langseax of the Wolves</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>