<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Shamus Felligan says </b>'Greetin's! Justice speaks through us. We're the followers o' the Tribunal. We act as judge. jury and executioner fer all misled Northmen. Sometimes we must also execute our swift justice upon evil races. such as th' [ice goblins].'
<p><b>You say, </b>'what ice goblins'
<br><b>Shamus Felligan says </b>'The ice goblins are a weak race. They pose no threat to our community. but lately we've heard rumors of ice goblins as can cast spells. They're said to be as weak as the goblin warriors. so I seek to employ the talents of our young shamans to [hunt the goblin casters].'
<p><b>You say, </b>'i will hunt the goblin casters'
<br><b>Shamus Felligan says </b>'Aye. ye'll serve justice.  I must find the source o' their recent spellcasting ability.  I hear reports o' glowing necklaces upon these wicked beasts' necks. Get me one o' these casters' necklaces. Return them in any condition at all. Go! Justice awaits yer return.'
</td></tr></table>