<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12221>Lion Delight</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Teria O-Danos says </b>'Good day to ye! Ye look a wee bit hungrry.  I sell many fine foods. Please have a look. Might I suggest the [lion roast]? It is a wee bit expensive, but well worth it.'
<p><b>You say, </b>'what lion roast'
<br><b>Teria O-Danos says </b>'The lion roast is quite good. Tis me specialty. Ah marinate the lion meat in mammoth fat fer two days before roasting it. Lion meat isn't common around here.  I'll purchase what I can from strangers but I rely mostly on shipments from the Plains o' Karana.  I'm presently searching fer someone to [pick up me lion meat shipment].'
<p><b>You say, </b>'i will pick you up lion meat shipment'
<br><b>Teria O-Danos says </b>'It'd be grand o' ye to pick up me lion meat shipment. Ye must travel to the Plains o' Karana. Search fer a Northman fishing village. It should be Clan McMannus. Speak with the chieftain, Einhorst. Tell him ye're there to [pick up the lion meat shipment for Halas]. When ye return, I'll pay ye at least three gold.  I look forward to yer return.'
<p><b>You say, </b>'i will pick me up lion meat shipment'
<br><b>Teria O-Danos says </b>'It'd be grand o' ye to pick up me lion meat shipment. Ye must travel to the Plains o' Karana. Search fer a Northman fishing village. It should be Clan McMannus. Speak with the chieftain, Einhorst. Tell him ye're there to [pick up the lion meat shipment for Halas]. When ye return, I'll pay ye at least three gold.  I look forward to yer return.'
<p><b>You give Teria O-Danos : </b><a href=http://phobos/eq/item.php?id=12221>Lion Delight</a>
<br><b>Teria O-Danos says </b>'Thank ye for picking up this shipment. Here is your payment.'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 3gp
</td></tr></table>