<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18136>Delius Thyme's Diary Pg. 74</a><li><a href=http://phobos/eq/item.php?id=18137>Delius Thyme's Diary Pg. 75</a><li><a href=http://phobos/eq/item.php?id=18138>Delius Thyme's Diary Pg. 76</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18139>Garsen's Brewing List</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Thadres Thyme says </b>'Hello. [Your Name]!  It's hard to believe just how cold it gets here!  It really has been wearing me down. Especially after the [journey] from Qeynos.'
<p><b>You say, </b>'what journey'
<br><b>Thadres Thyme says </b>'I have been traveling the face of Norrath to unravel the mystery of why my beloved [brother] attacked a group of traveling bards.  He didn't survive the fight.  It's been so long. I can't really remember what he looked like!  I miss him so much...  Now all I have are his [diary] and some brewing recipes he sold before his death.'
<p><b>You say, </b>'what diary'
<br><b>Thadres Thyme says </b>'The diary?  It's one of the two connections I still have to my brother.  Sadly. [pages] are missing from it.  I've been looking for them.'
<p><b>You say, </b>'what pages'
<br><b>Thadres Thyme says </b>'I believe the pages contain the events that drove my brother to insanity.  I have been searching for the remaining three missing pages.  There is some hope; I found a couple of pages over in Everfrost Mountains.'
<p><b>You give Thadres Thyme : </b><a href=http://phobos/eq/item.php?id=18138>Delius Thyme's Diary Pg. 76</a>, <a href=http://phobos/eq/item.php?id=18136>Delius Thyme's Diary Pg. 74</a>, <a href=http://phobos/eq/item.php?id=18137>Delius Thyme's Diary Pg. 75</a>
<br><b>Thadres Thyme says </b>'Oh my! Thank ye! These really mean a lot to me. Here is what I promised you'
<br><b>Thadres Thyme gives you : </b><a href=http://phobos/eq/item.php?id=18139>Garsen's Brewing List</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>