<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13966>Jar of Fungus</a><li><a href=http://phobos/eq/item.php?id=13445>Mammoth Steaks</a><li><a href=http://phobos/eq/item.php?id=13967>Wooly Fungus</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17946>Empty Jar</a><li><a href=http://phobos/eq/item.php?id=15075>Spell: Sicken</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a><li><a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=33>Circle of Unseen Hands</a><li><a href=http://phobos/eq/faction.php?id=47>Coalition of Trade Folk</a><li><a href=http://phobos/eq/faction.php?id=90>Ebon Mask</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Waltor Felligan says </b>'Hello, me friend! I'm the resident healer o' Halas. Please inform me when ye've a need fer me talents to [bind wounds], [cure disease] or [cure poison]. Might I add, if ye're a young shaman o' Halas, ye can also [assist in gathering fungus].'
<p><b>You say, </b>'cure disease'
<br><b>Waltor Felligan says </b>'Two small quantities o' wooly fungus are needed before we can cure yer malady.'
<p><b>You say, </b>'bind wounds'
<br><b>Waltor Felligan says </b>'Before I bind yer wounds, ye must pay tribute to the Tribunal in the amount of ten gold coins.'
<p><b>You say, </b>'cure poison'
<br><b>Waltor Felligan says </b>'I'll be needing mammoth steaks to feed the unfortunate.  Then we'll drain the poison from yer veins.'
<p><b>You say, </b>'assist in gathering fungus'
<br><b>Waltor Felligan says </b>'As the wooly spiderlings get ready to molt, they'll carry wooly fungus. Oftentimes, one can find wooly fungus growing on their bellies. I use this in me healing practices. I'll reward ye if ye can fill this jar full o' the valuable fungus. Don't forget to combine them before ye return it to me. And have yerself some rations handy, or ye may find yerself snacking on this tasteless food source.'
<br><b>Waltor Felligan gives you : </b><a href=http://phobos/eq/item.php?id=17946>Empty Jar</a>
<p><b>You give Waltor Felligan : </b><a href=http://phobos/eq/item.php?id=13966>Jar of Fungus</a>
<br><b>Waltor Felligan gives you : </b><a href=http://phobos/eq/item.php?id=15075>Spell: Sicken</a>
<br><b>Waltor Felligan says </b>'Aye! Ye've filled the jar. I'll see to it that Holana locks this away. Tis difficult to obtain and we can only spare the talents of our young shamans. Allow me to give ye a reward. Thank ye kindly fer yer service.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=33>Circle of Unseen Hands</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=47>Coalition of Trade Folk</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=90>Ebon Mask</a> has gotten worse.</font>
<br><b>You receive </b> 4gp
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Waltor Felligan : </b><a href=http://phobos/eq/item.php?id=13445>Mammoth Steaks</a>
<br><font color=brown><b>Waltor Felligan casts a spell : </b><a href=http://phobos/eq/spell.php?id=203>Cure Poison</a>.</font>
<br><b>Waltor Felligan says </b>'Aye! I will draw the poison from your veins!'
<p><b>You give Waltor Felligan : </b><a href=http://phobos/eq/item.php?id=13967>Wooly Fungus</a> x2
<br><font color=brown><b>Waltor Felligan casts a spell : </b><a href=http://phobos/eq/spell.php?id=213>Cure Disease</a>.</font>
<br><b>Waltor Felligan says </b>'Ah! Now I can cure yer malady.'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Waltor Felligan says </b>'Why do ye give me these items?'
</td></tr></table>