<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1330>Patched Gnoll Fur Bundle</a><li><a href=http://phobos/eq/item.php?id=7041>Burning Rapier</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=24097>Sluggish Sketch</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=275>Rogues of the White Rose</a></ul></td><td><p><b>You say, </b>'gnoll fur'
<br><b>Ysanna MacGibbon says </b>'You should not be asking where or what a gnoll is, but asking how I make use of that patch fur I find on their corpse. It is quite simple, take four pieces of gnoll fur and sew them together. Take the result and sew four of them together. And again with that product. In the end you will have a bundle of tailored gnoll fur. You can either return it to me or keep it for yourself.'
<p><b>You say, </b>'dark assassin'
<br><b>Ysanna MacGibbon says </b>'That poor lad! I saw him in the tundra being chased by that big bear of Tundra Jack. I never liked that bear of his since the day he ate my poor dog Thunderpaw. Anyways i say Iceberg chasing the assassin and grabbed my trusty ahlspiess and threw it, aiming right for his big head. Can you believe I missed?? I hit his side instead. Iceberg ripped my ahlspiess out and ripped it into pieces and then went whining of to Tundra Jack. Serves that bear right! He ate my dog!'
<p><b>You say, </b>'ahlspiess'
<br><b>Ysanna MacGibbon says </b>'Ahhhh my beloved shrieking ahlspiess, it was nice i was able to help a fellow assassin out but i really do miss it. The dark assassin gave me a sketch of paper he said was very valueable but it still pains me to be without my favourite throwing weapon. If you go get me another I would gladly part with this sketch.'
<p><b>You give Ysanna MacGibbon : </b><a href=http://phobos/eq/item.php?id=1330>Patched Gnoll Fur Bundle</a>
<br><b>Ysanna MacGibbon says </b>'You have done well. Here is a small reward for your effort.'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 1pp 2gp 2sp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=275>Rogues of the White Rose</a> has gotten better.</font>
<p><b>You give Ysanna MacGibbon : </b><a href=http://phobos/eq/item.php?id=7041>Burning Rapier</a>
<br><font color=green><b>Ysanna MacGibbon </b>beams 'Thank you, take this.'</font>
<br><b>Ysanna MacGibbon gives you : </b><a href=http://phobos/eq/item.php?id=24097>Sluggish Sketch</a>
<br><b>Ysanna MacGibbon says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>