<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=25107>Mechanical Net</a><li><a href=http://phobos/eq/item.php?id=25109>Excellent Siren Scales</a><li><a href=http://phobos/eq/item.php?id=25108>Idol of Solusek Ro</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=25108>Idol of Solusek Ro</a><li><a href=http://phobos/eq/item.php?id=25110>Giant Siren Scale Cloak</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>an outcast siren says </b>'Leave me alone, beast! Or I will cut your belly open and feed your entrails to the sharks.'
<p><b>You give an outcast siren : </b><a href=http://phobos/eq/item.php?id=25107>Mechanical Net</a>
<br><b>an outcast siren says </b>'So you are the servant of Wenglawks here to retrieve his cloak.
I will need more scales to make the cloak in his size. I have already slaughtered a good thirty sirens and the cloak is nearly complete. Go forth and slaughter my kind and bring me three excellent scales and this idol. Let this idol be your protection from the wrath of E'ci. I will continue my work on the cloak.'
<br><font color=yellow>You gain experience!!</font>
<br><b>an outcast siren gives you : </b><a href=http://phobos/eq/item.php?id=25108>Idol of Solusek Ro</a>
<p><b>You give an outcast siren : </b><a href=http://phobos/eq/item.php?id=25109>Excellent Siren Scales</a> x3, <a href=http://phobos/eq/item.php?id=25108>Idol of Solusek Ro</a>
<br><b>an outcast siren says </b>'You are an excellent hunter. Tell me, did you enjoy the screams of the sirens as they perished? I find the sound so wonderful.'
<br><font color=green><b>an outcast siren </b>hands you a gigantic cloak made of slick siren scales.</font>
<br><b>an outcast siren says </b>'I was done making the cloak already. I just wanted to watch you slay the weak. I thank you for bringing more suffering into the world.'
<br><b>an outcast siren gives you : </b><a href=http://phobos/eq/item.php?id=25110>Giant Siren Scale Cloak</a>
</td></tr></table>