<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>Bloogy Shellcracker says </b>'Hello, strange one. I am Bloogy Shellcracker, the preparer of meals for my people. I am not familiar with the culinary tastes of your kind but you are welcome to purchase some of my supplies. I will also barter for ingredients to some of my exotic dishes.'
<p><b>You say, </b>'ingredients'
<br><b>Bloogy Shellcracker says </b>'The rarest treat I can prepare for my people is saucy salted seadragon steak. I wish to barter for some water dragon or sea dragon meat, saltwater seaweed, and fish eggs. The rest of the ingredients are collected locally by our collectors.'
<p><b>You say, </b>'flags'
<br><b>Bloogy Shellcracker says </b>'0 0 0'
</td></tr></table>