<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=22815>Section of Lodizal's Shell</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=22816>Lodizal Shell Shield</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=241>Othmir</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=345>Ulthork</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Bungre Crawcrusher says </b>'What manner of creature are you, strange one? I can see that you are not native to any nearby territories. Your thin flesh and lack of hair would mean certain death when the ice queen breathes upon these seas.'
<p><b>You say, </b>'lodizal'
<br><b>Bungre Crawcrusher says </b>'Lodizal is a giant carnivorous sea turtle that roams the iceclad ocean preying primarily on the Snowfang gnolls. The Snowfang gnolls are not trusted by we Othmir as they survive on the skins and meat of walrus and otter but Lodizal is a threat to all coastal dwellers. Should Lodizal ever be slain I would be willing to craft a shield from his shell and adorn it with Othmir runes. I would charge ten thousand gold for the service.'
<p><b>You give Bungre Crawcrusher : </b><a href=http://phobos/eq/item.php?id=22815>Section of Lodizal's Shell</a>
<br><font color=green><b>Bungre Crawcrusher </b>skillfully crafts the section of Lodizal's shell into the shape of a shield. He then attaches sturdy cured walrus hide leather straps to the inner side of the shield and inscribes intricate glowing runes on the shield's face. When he is finished, he hands you the shield and claps loudly.</font>
<br><b>Bungre Crawcrusher gives you : </b><a href=http://phobos/eq/item.php?id=22816>Lodizal Shell Shield</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=241>Othmir</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=345>Ulthork</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>