<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>Cedrick says </b>'So you wish to challenge me, eh? Why else would you be here bearing the Sign of Acceptance. It is your own funeral though. If you still wish to [prove your worth] and ascend to the next level I am ready.'
<p><b>You say, </b>'i will prove my worth'
<br><b>Cedrick says </b>'I didnt know slime could speak common.. go back to the sewer before I lose my temper.'
<hr><b>When Cedrick is killed </b>
<br><b>Cedrick says </b>'You have proven to be successful. Go now and continue your journey.'
</td></tr></table>