<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=24874>Ulthork Tusks</a><li><a href=http://phobos/eq/item.php?id=30068>Bulthar Trunk</a><li><a href=http://phobos/eq/item.php?id=30067>Bulthar Trunk</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10049>Fire Emerald Ring</a><li><a href=http://phobos/eq/item.php?id=22817>Runed Othmir Spear</a><li><a href=http://phobos/eq/item.php?id=10050>Sapphire Necklace</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=241>Othmir</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=345>Ulthork</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Chief Kalan </b>nods respectfully.</font>
<br><b>Chief Kalan says </b>'Welcome to Siren Bay strange one. These beaches belong to my people, the Othmir. You are welcome in our villages as long as you do not cause trouble and are willing to either assist the shellfish collectors provide nourishment or aid the warriors defending the beaches.'
<p><b>You say, </b>'aid the warriors'
<br><b>Chief Kalan says </b>'There are many creatures that would prey on my people if it were not for the dedication of our warriors. The Bulthar and Ulthork often invade our territory and prey on our shellfish collectors. They are wasteful creatures and take more than they could possibly eat from the sacred seas.'
<p><b>You say, </b>'bulthar'
<br><b>Chief Kalan says </b>'The Bulthar are sea elephant people. They are strong brutes with the intelligence of a clam. There is no reasoning with the savages since they seem to only understand their territorial instincts. There is a small herd of them that has taken up residence on the rocky beach beneath the lonely tower and have already injured many of our shellfish collectors. I will reward you for the trunks of every two brutes that you slay.'
<p><b>You say, </b>'ulthork'
<br><b>Chief Kalan says </b>'The Ulthork are walrus people. They are just as territorial and brutish as the Bulthar but are slightly more intelligent. They seem to be jealous of my people's prosperity and occasionally lead raiding parties onto our beaches. Our craftsman use the tusks of the slain Ulthork to carve ivory totems of praise to the ocean lord. I will gladly barter for no less than four pairs of Ulthork tusks.'
<p><b>You give Chief Kalan : </b><a href=http://phobos/eq/item.php?id=24874>Ulthork Tusks</a> x4
<br><b>Chief Kalan says </b>'Many thanks to you, strange one. Our craftsman will be pleased. They have been in need of a new bundle of ivory.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=241>Othmir</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=345>Ulthork</a> has gotten worse.</font>
<br><b>Chief Kalan gives you : </b><a href=http://phobos/eq/item.php?id=10049>Fire Emerald Ring</a>
<p><b>You give Chief Kalan : </b><a href=http://phobos/eq/item.php?id=30068>Bulthar Trunk</a>
<br><b>Chief Kalan says </b>'Such wasteful creatures the Bulthar are. It is a shame they are not intelligent enough to realize the harm they do to the very oceans that sustain them.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=241>Othmir</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=345>Ulthork</a> has gotten worse.</font>
<br><b>Chief Kalan gives you : </b><a href=http://phobos/eq/item.php?id=22817>Runed Othmir Spear</a>
<p><b>You give Chief Kalan : </b><a href=http://phobos/eq/item.php?id=30067>Bulthar Trunk</a> x2
<br><b>Chief Kalan says </b>'Such wasteful creatures the Bulthar are. It is a shame they are not intelligent enough to realize the harm they do to the very oceans that sustain them.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=241>Othmir</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=345>Ulthork</a> has gotten worse.</font>
<br><b>Chief Kalan gives you : </b><a href=http://phobos/eq/item.php?id=10050>Sapphire Necklace</a>
<br><b>Chief Kalan says </b>'I have no need of these, strange one.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>