<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1665>Tiny Gem</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>a lesser spirit says </b>'Did you take this person's life, shaman?'
<p><b>You say, </b>'yes'
<br><b>a lesser spirit says </b>'Why have you taken this person's life, [Your Name]? Did he threaten your life? Did you dislike him? Or was his death a profit to you in some way?'
<p><b>You say, </b>'threatened my life'
<br><b>a lesser spirit says </b>'I see. It brings me sadness to see another die, but his heart was black and a great nothingness. His body will become the grass now. Thank you for what you have done, shaman.'
<p><b>You say, </b>'what are you'
<br><b>a lesser spirit says </b>'What, or who, I am isn't as important as what, or who, WE are. Do you wish to know more, shaman?'
<p><b>You say, </b>'know more'
<br><b>a lesser spirit says </b>'That is good, [Your Name]. Take this gem. It is a part of us like the clouds to the sky and is a wonderful gift from the grandfather. Take this gem to where the humans gather to spoil the land and water. Some call it a port. There you will find one of us, a shaman like yourself. Give him the gem and perhaps he will tell you more of the spirits.'
<br><b>a lesser spirit gives you : </b><a href=http://phobos/eq/item.php?id=1665>Tiny Gem</a>
<br><b>a lesser spirit disappears.</b>
</td></tr></table>