<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Berserker-s Image </b>You feel the spirits rage being released...</font>
<br><b>Berserker-s Image says </b>'. . . [return]'
<p><b>You say, </b>'return'
<br><font color=white><b>The Player moves to zone 78 at 3603,2088,-155</b></font>
<br><b>Berserker-s Image disappears.</b>
</td></tr></table>