<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=60195>A Sealed Note for Mardic</a></ul></td><td><p><b>You say, </b>'Hail'
<p><b>You say, </b>'Hail'
<p><b>You give Mardic Crimsonsteel : </b><a href=http://phobos/eq/item.php?id=60195>A Sealed Note for Mardic</a>
<br><font color=white><b>The Player moves to zone 78 at 1065,525,176</b></font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>