<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12650>Scorpion Pincer</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a><li><a href=http://phobos/eq/faction.php?id=30>Cabilis Residents</a><li><a href=http://phobos/eq/faction.php?id=282>Scaled Mystics</a><li><a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a><li><a href=http://phobos/eq/faction.php?id=317>Swift Tails</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Warlord Zyzz says </b>'There is little time for talk. There are plenty of [tiny invaders]. Do your part and exterminate as many as you can. All of Cabilis shall look favorably upon you in the long run.'
<p><b>You say, </b>'tiny invaders'
<br><b>Warlord Zyzz says </b>'The small scorpions have been turning up everywhere!! One can hardly sleep when thinking of the little monsters. Please crush as many as you can for the greater good. I will even pay a bounty for every four Scorpion Pincers you return.'
<p><b>You give Warlord Zyzz : </b><a href=http://phobos/eq/item.php?id=12650>Scorpion Pincer</a> x4
<br><b>Warlord Zyzz says </b>'Magnificent!! The more pincers I get the lesser scorpions there are. Here. Take the bounty.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=30>Cabilis Residents</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=282>Scaled Mystics</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=317>Swift Tails</a> has gotten better.</font>
<br><b>You receive </b> 2sp 4cp
<br><font color=yellow>You gain experience!!</font>
<br><b>Warlord Zyzz says </b>'I have no need for this item [Your Name], you can have it back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>