<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18801>A Tattered Note</a><li><a href=http://phobos/eq/item.php?id=26644>A Sealed Letter</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13302>Monogrammed Cloth</a><li><a href=http://phobos/eq/item.php?id=5231>Black Wolf Crown</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=10103></a><li><a href=http://phobos/eq/faction.php?id=10101></a><li><a href=http://phobos/eq/faction.php?id=10112></a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=10102></a><li><a href=http://phobos/eq/faction.php?id=10111></a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Milea Clothspinner says </b>'Hail, fellow adventurer. Are you from Qeynos?'
<p><b>You give Milea Clothspinner : </b><a href=http://phobos/eq/item.php?id=18801>A Tattered Note</a>
<br><b>Milea Clothspinner says </b>'My sister is in danger. She is all the family I have left. I shall be on my way soon. Please take her my handkerchief, so she knows you have contacted me. Thank you. I am thankful Nerissa ran into you. I just wonder why she did not tell Kane about her suspicions.'
<br><b>Milea Clothspinner gives you : </b><a href=http://phobos/eq/item.php?id=13302>Monogrammed Cloth</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10103></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10101></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10102></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10111></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10112></a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Milea Clothspinner : </b><a href=http://phobos/eq/item.php?id=26644>A Sealed Letter</a>
<br><b>Milea Clothspinner says </b>'Oh great!! I thought I saw that last of Plagus, or as all the women in the Steel Warriors called him, The Plague. Please do not tell him where I am. It must have been a long journey for you. Here. A little something for your wasted trip. I found it on the ground. Have fun going back to Freeport.'
<br><b>Milea Clothspinner gives you : </b><a href=http://phobos/eq/item.php?id=5231>Black Wolf Crown</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10103></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10101></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10102></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10111></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10112></a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<hr><b>When Milea Clothspinner is killed </b>
<br><b>Milea Clothspinner gives you : </b><a href=http://phobos/eq/item.php?id=13302>Monogrammed Cloth</a>
</td></tr></table>