<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20451>Frayed Braided Grass Amulet</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20451>Frayed Braided Grass Amulet</a></ul></td><td><p><b>You give Nuien : </b><a href=http://phobos/eq/item.php?id=20451>Frayed Braided Grass Amulet</a>
<br><b>Nuien says </b>'So be it. Do as you have done before and find the next. Teloa is the last.'
<br><b>Nuien gives you : </b><a href=http://phobos/eq/item.php?id=20451>Frayed Braided Grass Amulet</a>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=15170>Teloa</a></b> spawns (-3840,-2854,126.5).</font>
<br><font color=green><b>Nuien </b>will not take this item.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>