<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20450>Braided Grass Amulet</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20451>Frayed Braided Grass Amulet</a></ul></td><td><p><b>You give Sionae : </b><a href=http://phobos/eq/item.php?id=20450>Braided Grass Amulet</a>
<br><b>Sionae says </b>'I see that the time has come. Take the amulet and give it to the third of our kin, Nuien. I will meet you at the gathering.'
<br><b>Sionae gives you : </b><a href=http://phobos/eq/item.php?id=20451>Frayed Braided Grass Amulet</a>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=15167>Nuien</a></b> spawns (-3657,300,3).</font>
<br><font color=green><b>Sionae </b>will not take this item.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>