<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Sir Morgan says </b>'Hail. traveler!  Might I escort you through to Highpass?  The path ahead is filled with giants and many other hungry beasts. I assure you. you will be safe with me.  I must admit. I am quite experienced in the ways of the warrior.  Do you [wish an escort] or will you [travel alone]?'
<p><b>You say, </b>'wish an escort'
<br><b>Sir Morgan says </b>'I shall be honored to escort you to Highpass, but you shall have to wait for a spell. I make trips every few hours. I also would be grateful to any who wish to donate gold coins to the upkeep of my armor. The rains in the plains cause much rusting.'
<p><b>You say, </b>'travel alone'
<br><b>Sir Morgan says </b>'Then, good luck to you! May your faith protect you. Or at the very least, guide you to a grand afterlife.'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Sir Morgan says </b>'Thank you [Your Name], but I do not need this, you can have it back.'
</td></tr></table>