<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>#Translocator Narrik says </b>'Hello there. There seems to be some strange problems with the boats in this area. The Academy of Arcane Sciences has sent a small team of us to investigate them. If you need to [travel to Freeport] or [travel to Butcherblock] in the meantime, I can transport you to my companion there.'
<p><b>You say, </b>'travel to freeport'
<br><font color=brown><b>#Translocator Narrik casts a spell : </b><a href=http://phobos/eq/spell.php?id=2283>Portal to Freeport</a>.</font>
<p><b>You say, </b>'travel to butcherblock'
<br><font color=brown><b>#Translocator Narrik casts a spell : </b><a href=http://phobos/eq/spell.php?id=2281>Portal to Butcher</a>.</font>
</td></tr></table>