<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=16889>Rebreather</a><li><a href=http://phobos/eq/item.php?id=20665>Block of Permafrost</a><li><a href=http://phobos/eq/item.php?id=20664>Keg of Vox Tail Ale</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20667>Ancient Sword Blade</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Denken Strongpick says </b>'Hello, [Your Name]. I am Denken Strongpick. I wish I could get off this rock, silly clan honor. My boss broke our rebreathers and we can not go back to the mainland before wegather some [goblin relics].'
<p><b>You say, </b>'goblin relics'
<br><b>Denken Strongpick says </b>'There are supposedly goblin ruins around here somewhere. Fendlemend thinks we will find paydirt underwater. We did find [one thing].'
<p><b>You say, </b>'one thing'
<br><b>Denken Strongpick says </b>' We found a very fine sword blade. Denken pulls open his pack and shows you a razor sharp sword covered with runes. I can't figure out what type of metal it is and I sure can't figure out what technique was used to forge it. Perhaps you would like to take it off my hands and [buy] it?'
<p><b>You say, </b>'buy'
<br><b>Denken Strongpick says </b>'Out here, money is fairly useless to me. You see, I can't leave Fendlemend out here alone. I signed on with a very detailed contract. I could sure [use] a few things from the mainland though.'
<p><b>You say, </b>'use'
<br><b>Denken Strongpick says </b>'I would be willing to part with this very fine blade for a keg of Vox tail ale, a block of permafrost to keep it cool and two new rebreathers to get this operation back underway.'
<p><b>You give Denken Strongpick : </b><a href=http://phobos/eq/item.php?id=16889>Rebreather</a> x2, <a href=http://phobos/eq/item.php?id=20665>Block of Permafrost</a>, <a href=http://phobos/eq/item.php?id=20664>Keg of Vox Tail Ale</a>
<br><b>Denken Strongpick gives you : </b><a href=http://phobos/eq/item.php?id=20667>Ancient Sword Blade</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Denken Strongpick says </b>'Excellent! Here is your sword. I feel like I'm at home already!'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>