<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Fendlemend Figlefop </b>sighs and looks up at you.</font>
<br><b>Fendlemend Figlefop says </b>'What a horrible expedition!'
<br><b>Fendlemend Figlefop says </b>'No goblin relics, not even some goblin dishes! My rebreather is broken and the only thing we [found] was not even from the goblinempires!'
<p><b>You say, </b>'found'
<br><font color=green><b>Fendlemend Figlefop </b>huffs for a moment, looking quite upset.</font>
<br><b>Fendlemend Figlefop says </b>'I found a [silly sword blade]. It is useless to me. The only thing I study is goblins, and this thing is definitely not goblin insign.'
<p><b>You say, </b>'silly sword blade'
<br><b>Fendlemend Figlefop says </b>'You will have to ask Denken about the blade. I gave it to him to get it out of my way.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>