<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=0></a><li><a href=http://phobos/eq/item.php?id=48127>Initiate's Sash of the Celestial Order</a><li><a href=http://phobos/eq/item.php?id=48129>Polished Symbol of Focus</a><li><a href=http://phobos/eq/item.php?id=48130>Polished Symbol of Tranquility</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Kaiaren says </b>'Hello [Your Name], I have been [expecting] you.'
<p><b>You say, </b>'expecting'
<br><b>Kaiaren says </b>'There is still much that needs to be done and I lack the strength still to continue it myself. If you choose to you can first begin by completing a [simple task] for me.'
<p><b>You say, </b>'simple task'
<br><b>Kaiaren says </b>'I need you to gather some rare [delicacies] and bring them back to me. This meal has been passed down the Order for ages. This meal is said to grant strength back to the feeble. It is the only way possible for us to combat this [menace].'
<p><b>You say, </b>'delicacies'
<br><b>Kaiaren says </b>'I will need you to gather some [sunless nectar] and some meat from an [ancient creature].'
<p><b>You say, </b>'sunless nectar'
<br><b>Kaiaren says </b>'The sunless nectar comes from the darkest parts of Norrath. Once you find it you must combine it with some spices and a pie tin to make a Sugar and Spice Nectar Pie. Please return soon after you have both items.'
<p><b>You say, </b>'ancient creature'
<br><b>Kaiaren says </b>'The creature you seek has been living for as long as any can remember. It can be found surrounded by water. You will need to take its meat and combine it with grilling sauce, a loaf of bread, and some cheese to make an Aged Meat and Cheese Sandwich. Please return soon after you have both items.'
<p><b>You say, </b>'menace'
<br><b>Kaiaren says </b>'What menace? For sure Vortix has mentioned to you his dreams? His dreams provide a rare gift of foresight into what lies ahead. There is a dark threat that looms over the Orders head like a vice. It wants nothing more than to destroy all that know of its existence.'
<p><b>You say, </b>'choose'
<br><b>Kaiaren says </b>'As I thought you would; you will find them as you did the others, in their natural essence. You will find the Disciple of Focus in the hills and mountains training diligently. The Disciple of Tranquility you shall find in a clearing where many do not travel without knowing valor and courage. It is there that you will be able to find your calmness. Please return to me when you have gained their respect as well as their symbols. I will also require your sash.'
<p><b>You say, </b>'final task'
<br><b>Kaiaren says </b>'Yes, you must combat an enlightened one. It is our way that balance must be kept. Without good, evil cannot exist. We are but a small part in the cycle of true immortality. If you are [ready to begin] I will battle you. Please do not worry, if you defeat me, my being will continue to exist within you as that is the way of our Order. If you fall however, it was meant to be.'
<p><b>You say, </b>'ready to begin'
<br><b>Kaiaren says </b>'Stand fast and ready to prove your worth now [Your Name]!'
<hr><b>When Kaiaren is killed </b>
<br><b>Kaiaren says </b>'You have done very well.. You must now travel to the heart of the discord-filled lands and obtain a Globe of Discordant Energy. It is only after the menace has been stopped can we begin to live anew. If you succeed, return to Vortix and hand him the globe. He will know what to do. Hurry for time is of the essence!'
<p><b>You give Kaiaren : </b><a href=http://phobos/eq/item.php?id=0></a>, <a href=http://phobos/eq/item.php?id=0></a>
<br><b>Kaiaren says </b>'Ah, thank you. These will help me greatly but I am afraid I will still lack the strength needed to combat this evil. You will have to go in my place until at least I have had a little longer to rest and train. If you [choose] to continue, there are two more Disciples that you must face in order to reach the point of transcendence.'
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Kaiaren : </b><a href=http://phobos/eq/item.php?id=48127>Initiate's Sash of the Celestial Order</a>, <a href=http://phobos/eq/item.php?id=48129>Polished Symbol of Focus</a>, <a href=http://phobos/eq/item.php?id=48130>Polished Symbol of Tranquility</a>
<br><b>Kaiaren says </b>'I see you are ready to assume the [final task] before facing the dark foe that will forever change our way of life here.'
</td></tr></table>