<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18302>Book of Scale</a><li><a href=http://phobos/eq/item.php?id=18202>Book of Turmoil</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19072>Miragul's Phylactery</a><li><a href=http://phobos/eq/item.php?id=10071>Glowing Torch</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=236>Oracle of Karnon</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=237>Oracle of Marud</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Oracle of K-Arnon says </b>'Greetings, [Your Name], I am the Oracle of K'Aron. Do you quest for [knowledge] yourself, or do you offer that which I [seek].'
<p><b>You say, </b>'knowledge'
<br><b>Oracle of K-Arnon says </b>'I have lived long and have insight into many matters, yet I despise charity. To learn from me, you must first bring me that which I [seek].'
<p><b>You say, </b>'seek'
<br><b>Oracle of K-Arnon says </b>'I seek knowledge, which is superior to all things. And no knowledge is greater than that which is contained within the [Tome of Ages].'
<p><b>You say, </b>'tome of ages'
<br><b>Oracle of K-Arnon says </b>'The Tome of Ages has been compiled over the millennia by the Scribes of [Dal]. It was divided into seven distinct [books] by the scribes to keep the knowledge from one such as me. That said, with aid, I shall unite these books and the Tome of Ages shall be mine.'
<p><b>You say, </b>'dal'
<br><b>Oracle of K-Arnon says </b>'They were elves once, but now are Teir'Dal, and as evil as they are wise. Many tomes have they written, but none greater than the Tome of Ages.'
<p><b>You say, </b>'books'
<br><b>Oracle of K-Arnon says </b>'The seven books that make up the Tome of Ages are those of [Enlightenment], [Scale], [Turmoil], [Monuments], [Elders], [Blood], and the [Lost].'
<p><b>You say, </b>'enlightenment'
<br><b>Oracle of K-Arnon says </b>'I do not seek the Book of Enlightenment at this time, but I might have need of it in the future.'
<p><b>You say, </b>'scale'
<br><b>Oracle of K-Arnon says </b>'Ah, the Book of Scale.. It would be wondrous indeed if you could recover the Book of Scale for me. If you do manage to procure the Book of Scale, I will gladly part with an artifact of my own that may be of interest to you.'
<p><b>You say, </b>'turmoil'
<br><b>Oracle of K-Arnon says </b>'Ah, yes! The Book of Turmoil. I seek this book, and should you find it and return it to me, I will reward you with secret knowledge.'
<p><b>You say, </b>'monuments'
<br><b>Oracle of K-Arnon says </b>'I do not seek the Book of Monuments at this time, but I might have need of it in the future.'
<p><b>You say, </b>'elders'
<br><b>Oracle of K-Arnon says </b>'I do not seek the Book of Elders at this time, but I might have need of it in the future.'
<p><b>You say, </b>'blood'
<br><b>Oracle of K-Arnon says </b>'I do not seek the Book of Blood at this time, but I might have need of it in the future.'
<p><b>You say, </b>'lost'
<br><b>Oracle of K-Arnon says </b>'I do not seek the Lost Book at this time, but I might have need of it in the future.'
<p><b>You give Oracle of K-Arnon : </b><a href=http://phobos/eq/item.php?id=18302>Book of Scale</a>
<br><b>Oracle of K-Arnon gives you : </b><a href=http://phobos/eq/item.php?id=19072>Miragul's Phylactery</a>
<p><b>You give Oracle of K-Arnon : </b><a href=http://phobos/eq/item.php?id=18202>Book of Turmoil</a>
<br><b>Oracle of K-Arnon says </b>'Thank thee for this tome. Be sure to check back with me later, as I might have another task for thee.'
<br><b>Oracle of K-Arnon gives you : </b><a href=http://phobos/eq/item.php?id=10071>Glowing Torch</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=236>Oracle of Karnon</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=237>Oracle of Marud</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Oracle of K-Arnon says </b>'I have no need for this item, [Your Name]. You can have it back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>