<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Emylie Steelclaws says </b>'Shalom friend. My mate Kalaaro is the primary blacksmith of our village. I mostly create his tools. do touch ups and refurbishes. and maintain the [kejek forge].'
<p><b>You say, </b>'what kejek forge?'
<br><b>Emylie Steelclaws says </b>'Our forge has received the blessings of the Titan Spirits to burn with a supernatural flame! This flame has many beneficial properties but most importantly it can aid in freeing the spirits that have been imprisoned in materials by evil sorcerers.'
</td></tr></table>