<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20043>Idol of Cazic Thule</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2099>Soulfiend Lance</a></ul></td><td><hr><b>When Ghost Of Ridossan spawns </b>
<br><b>Ghost Of Ridossan says </b>'Thank you, [Your Name]. I am not long for this world. Before I leave, I would like to reward the one who helped me have my revenge. Please, hand me the token of my God, of Cazic-Thule, and I shall pass you the spear I once used. You've earned it.'
<p><b>You give Ghost Of Ridossan : </b><a href=http://phobos/eq/item.php?id=20043>Idol of Cazic Thule</a>
<br><font color=green><b>Ghost Of Ridossan </b>takes the idol into his spectral hand and shoves the lance into your arms. After letting go of the lance, the ghost immediately begins to fade away. Before it is gone completely, it looks into your eyes and says, 'Suffer.'</font>
<br><b>Ghost Of Ridossan gives you : </b><a href=http://phobos/eq/item.php?id=2099>Soulfiend Lance</a>
<br><b>Ghost Of Ridossan disappears.</b>
</td></tr></table>