<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=6967>Heretics Head</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=6952>Wakizashi of the Frozen Skies</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Jali Kaliio says </b>'Greetings outsider. I trust you have [peaceful intentions] while visiting our village?'
<p><b>You say, </b>'peaceful intentions'
<br><b>Jali Kaliio says </b>'That is good to hear. Those filthy kobolds have caused enough trouble. We do not need more enemies.'
<br><font color=green><b>Jali Kaliio </b>Jali turns around and glances at another Kejekan. This one seems somewhat ill. Her fur is coming out in patches and strange sores cover her body.</font>
<br><b>Jali Kaliio says </b>'That is my wife, Yuio. She has come down with a sickness, no doubt caused by those accursed kobolds.'
<br><font color=green><b>Jali Kaliio </b>Anger wracks Jali's face as he speaks.</font>
<p><b>You say, </b>'I would ask you for [help] but you are a stranger and owe us nothing. Of course if you did assist me, I would be forever greatful.'
<br><b>Jali Kaliio says </b>'Oh thank you! You are most kind. I fear that there is not much time left for my dear Yuio. Please speak to [Khonza Ayssla]. She is most wise and perhaps can find some cure for this affliction.'
<br><b>Jali Kaliio says </b>'Oh thank you! You are most kind. I fear that there is not much time left for my dear Yuio. Please speak to [Khonza Ayssla]. She is most wise and perhaps can find some cure for this affliction.'
<p><b>You say, </b>'help'
<br><b>Jali Kaliio says </b>'Oh thank you! You are most kind. I fear that there is not much time left for my dear Yuio. Please speak to [Khonza Ayssla]. She is most wise and perhaps can find some cure for this affliction.'
<p><b>You say, </b>'khonza ayssla'
<br><b>Jali Kaliio says </b>'Khonza Ayssla is the village's High Shaman. She teaches the ancient ways of Okanjo and is most wise. If she cannot assist you I do not know who can. I would go myself but I am too worried to leave my dear wife behind. When you find Khonza, tell her that Jali sent you. Please hurry, friend!'
<p><b>You give Jali Kaliio : </b><a href=http://phobos/eq/item.php?id=6967>Heretics Head</a>
<br><b>Jali Kaliio says </b>'Khonza Ayssla gave this to you? We must try it at once then.'
<br><font color=green><b>Jali Kaliio </b>Jali opens the vial and gently tilts back Yuio's head. He pours the liquid into her mouth and waits. Miraculously, Yuios fur begins to take on a healthy sheen and the sores begin to disappear! Yuio falls into Jali's arms then goes slack, passing out.</font>
<br><b>Jali Kaliio says </b>'She needs much rest. I cannot begin to thank you enough for helping us. Please accept this as a reward. It is not much but it should be of some use. You are indeed a friend of ours and if you ever need shelter from the wilds, please visit us again.'
<br><b>Jali Kaliio gives you : </b><a href=http://phobos/eq/item.php?id=6952>Wakizashi of the Frozen Skies</a>
</td></tr></table>