<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19992>Chocolate Marr Cherries</a><li><a href=http://phobos/eq/item.php?id=2088>Tiny Pouch of Bone Dice</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20115>Pouch of Kejek Catnip</a><li><a href=http://phobos/eq/item.php?id=20116>Ball of Burlap Yarn</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=172>Kejek Village</a><li><a href=http://phobos/eq/faction.php?id=274>Riptide Goblins</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Miranda says </b>'I'm not supposed to talk to strangers but if my parents let you in here I guess it's ok. Do you like [candy]? I could give you some [candy] to play a game with me but my [dice] are gone now.'
<p><b>You say, </b>'candy'
<br><b>Miranda says </b>'Khonza Ayssla went away one time and came back with chocolate covered cherries and pixie powder cinnesticks for my sister and I. I like the chocolates the best.'
<p><b>You say, </b>'dice'
<br><b>Miranda says </b>'I had my dice in a little bag and lost it outside the walls of the village. I think the kobolds must have found it.'
<p><b>You give Miranda : </b><a href=http://phobos/eq/item.php?id=19992>Chocolate Marr Cherries</a>
<br><font color=green><b>Miranda </b>claps her hands with excitement.</font>
<br><b>Miranda says </b>'Chocolate cherries!! My favorite!! Here try some of this!!'
<br><font color=yellow>You gain experience!!</font>
<br><b>Miranda gives you : </b><a href=http://phobos/eq/item.php?id=20115>Pouch of Kejek Catnip</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=172>Kejek Village</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=274>Riptide Goblins</a> has gotten better.</font>
<p><b>You give Miranda : </b><a href=http://phobos/eq/item.php?id=2088>Tiny Pouch of Bone Dice</a>
<br><b>Miranda gives you : </b><a href=http://phobos/eq/item.php?id=20116>Ball of Burlap Yarn</a>
<br><b>Miranda says </b>'You found my dice!!! Thank you!!'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=172>Kejek Village</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=274>Riptide Goblins</a> has gotten better.</font>
</td></tr></table>