<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=6969>Satchel of Heretic Heads</a><li><a href=http://phobos/eq/item.php?id=6968>Kobold Head</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17883>Burlap Satchel</a><li><a href=http://phobos/eq/item.php?id=6953>Swiftclaw Sash</a><li><a href=http://phobos/eq/item.php?id=6984>Titan Blessed Bokken</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Shazda Kaekwon says </b>'Shalom, [Your Name]! I welcome you to our humble village in these [trying times].'
<p><b>You say, </b>'trying times'
<br><b>Shazda Kaekwon says </b>'There are many threats currently facing this village. The kobolds of Clan Kolbok are becoming bolder in pushing the boundaries of the territory in which they usually hunt. A few of the kobolds now hunt recklessly, killing for pleasure instead of sustenance. [Rognarog] the Infuriated is the most murderous of such kobolds. Then there are the [heretics] that have been invading both Clan Kolbok and Kejek territories alike, practicing their dark sorceries as a show of devotion to their faceless god.'
<p><b>You say, </b>'heretics'
<br><b>Shazda Kaekwon says </b>'The heretics have not only corrupted their own spirits but they defile the spirits of the dead with their evil sorceries. Fill this satchel with the heads of invading heretics and I shall reward you for your allegiance to Kejek.'
<br><b>Shazda Kaekwon gives you : </b><a href=http://phobos/eq/item.php?id=17883>Burlap Satchel</a>
<p><b>You say, </b>'rognarog'
<br><b>Shazda Kaekwon says </b>'Rognarog the Infuriated was once a mighty warrior for Clan Kolbok until his devotion to the kobold god Rolfron Zek devoured his spirit and drove him mad with anguish. Now he wanders the mountains and valleys of Stonebrunt shedding the blood of whatever creatures cross his path. Should you face Rognarog and release him from this life I will reward you for his severed head.'
<p><b>You give Shazda Kaekwon : </b><a href=http://phobos/eq/item.php?id=6969>Satchel of Heretic Heads</a>
<br><b>Shazda Kaekwon says </b>'Less heretics to defile the lands and spirits. You have the gratitude of Kejek for your assistance in repelling the heretic threat.'
<br><b>Shazda Kaekwon gives you : </b><a href=http://phobos/eq/item.php?id=6953>Swiftclaw Sash</a>
<p><b>You give Shazda Kaekwon : </b><a href=http://phobos/eq/item.php?id=6968>Kobold Head</a>
<br><b>Shazda Kaekwon says </b>'Thank you [Your Name]. Let's hope that sends out a strong message to the hertics. Please, take this as a reward.'
<br><b>Shazda Kaekwon gives you : </b><a href=http://phobos/eq/item.php?id=6984>Titan Blessed Bokken</a>
</td></tr></table>