<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1687>Eye of Kaiaren</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Astral Projection </b>ignores you.</font>
<p><b>You give Astral Projection : </b><a href=http://phobos/eq/item.php?id=1687>Eye of Kaiaren</a>
<br><b>Astral Projection disappears.</b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=85211>Vorash</a></b> spawns.</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=85223>Deep</a></b> spawns.</font>
</td></tr></table>