<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12451>Catfish Croak Sandwich</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12448>Foobscale Coif</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Klok Foob says </b>'Buy, buy, buy. Go ahead, make a purchase. I am not here to talk. Go to Cabilis for talk. Come to Foob for armor. Now hurry and.. Ooh.. Foob is starvings. Foob wish he had his [munch break favorite].'
<p><b>You say, </b>'munch break favorite'
<br><font color=green><b>Klok Foob </b>rubs his tummy. 'Oh!! Catfish croak sandwich is my favorite, it is. Can only eats on my break. I haves one and one is what the Haggle Baron says to Foob. Only thing is Foob gets way tired from standing. Foob needs some broodling to [fetch the catfish croak sandwich] for him.'</font>
<p><b>You say, </b>'fetch.*sandwich'
<br><b>Klok Foob says </b>'What?!! You dus gets Foob his sandwich for his munch break!! You be a good tail. Gets me two sandwiches, one fer break and one fer work, then me pay you something for the troubles. But it be no trouble. Foob is sure you know [how to make sandwich].'
<p><b>You say, </b>'how.*sandwich'
<br><font color=green><b>Klok Foob </b>chortles loudly in disbelief. 'How you not know? It da best food. You gots to get a sewer catfish which swims in da Cabilis, and find lizard who have thin sliced froglok. Then all you need is shrub lettuce and honey mush bread. All dis in da oven makes a good sandwich.'</font>
<p><b>You give Klok Foob : </b><a href=http://phobos/eq/item.php?id=12451>Catfish Croak Sandwich</a> x2
<br><b>Klok Foob says </b>'Me thanks you very much!! Now me stop da tummy grumbles. You have this. And you takes dis. Foob make special, not sold yet, you test it. It is not toughest, but it take a little bashing just like you. It is called Foobscale!!'
<br><b>Klok Foob gives you : </b><a href=http://phobos/eq/item.php?id=12448>Foobscale Coif</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>