<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=60189>Throwing Axe of the Spirit</a><li><a href=http://phobos/eq/item.php?id=60192>Bloodbeast Tooth</a><li><a href=http://phobos/eq/item.php?id=60190>Medal of Blood</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=60191>Bore Axes of the Spirit</a><li><a href=http://phobos/eq/item.php?id=60193>McArik-Crafted Bandage</a><li><a href=http://phobos/eq/item.php?id=60194>Medal of Mirages</a></ul></td><td><p><b>You say, </b>'defeat'
<p><b>You say, </b>'need more axes'
<p><b>You say, </b>'ready for this challenge'
<p><b>You give Lingering Axefall : </b><a href=http://phobos/eq/item.php?id=60189>Throwing Axe of the Spirit</a>
<br><b>Lingering Axefall says </b>'Ah, yes. The signature axe of my good friend, McArik. Here to test your control, hm? I hope you have better luck than I did. As you can see, I didn't fare so well against the enemy I was sent to [defeat]. Here, take these. I fashioned them for you from McArik's throwing axe. You will need them.'
<br><b>Lingering Axefall gives you : </b><a href=http://phobos/eq/item.php?id=60191>Bore Axes of the Spirit</a>
<br><b>Lingering Axefall gives you : </b><a href=http://phobos/eq/item.php?id=60191>Bore Axes of the Spirit</a>
<br><b>Lingering Axefall gives you : </b><a href=http://phobos/eq/item.php?id=60191>Bore Axes of the Spirit</a>
<p><b>You give Lingering Axefall : </b><a href=http://phobos/eq/item.php?id=60192>Bloodbeast Tooth</a>, <a href=http://phobos/eq/item.php?id=60190>Medal of Blood</a>
<br><b>Lingering Axefall says </b>'Aye, ye have done well, [Your Name]. However, that was a simple task and I'm sure ye had much help with it. Now ye must go alone. Ye may want to take some bandages with ye and be sure yer skill with them is top-notch. Ye'll likely need 'em. Here, take some o'mine. Ye may find 'em to be most useful. Do ye believe ye're [ready for this challenge]'
<br><b>Lingering Axefall gives you : </b><a href=http://phobos/eq/item.php?id=60193>McArik-Crafted Bandage</a>
<br><b>Lingering Axefall gives you : </b><a href=http://phobos/eq/item.php?id=60194>Medal of Mirages</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>