<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=62097>Mark of Imprisonment</a><li><a href=http://phobos/eq/item.php?id=62096>Blade of the Depredator</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=62204>Aged Earring of Aptitude</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Pagik Tsissun says </b>'The feeling of freedom is good indeed, greetings wanderer. Having escaped the clutches of the drogan goblins I desire for them to know the true meaning of fear. Will you help teach them the meaning of [fear]?'
<p><b>You say, </b>'fear'
<br><b>Pagik Tsissun says </b>'Very well head to the Temple of Droga and seek out the so called goblin bone depredators. Slaughter them until you have three Blades of the Depredator and bring those back. Also seek out the Jailor Maufan and bring back the Mark of Imprisonment. Do this and I shall reward you well.'
<p><b>You give Pagik Tsissun : </b><a href=http://phobos/eq/item.php?id=62097>Mark of Imprisonment</a>, <a href=http://phobos/eq/item.php?id=62096>Blade of the Depredator</a> x3
<br><b>Pagik Tsissun gives you : </b><a href=http://phobos/eq/item.php?id=62204>Aged Earring of Aptitude</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>