<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=65506>Steel Ch'Ror</a><li><a href=http://phobos/eq/item.php?id=65507>Steel Mak'Stor</a><li><a href=http://phobos/eq/item.php?id=65508>Steel So'Shar</a><li><a href=http://phobos/eq/item.php?id=65509>Steel Ta'Nak</a><li><a href=http://phobos/eq/item.php?id=65510>Steel Ga'Nak</a><li><a href=http://phobos/eq/item.php?id=65511>Steel Re'Stek</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=318>Syrik Iceblood</a><li><a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a><li><a href=http://phobos/eq/faction.php?id=30>Cabilis Residents</a><li><a href=http://phobos/eq/faction.php?id=282>Scaled Mystics</a><li><a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a><li><a href=http://phobos/eq/faction.php?id=317>Swift Tails</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Syrik Iceblood says </b>'Oh, hello. You caught me while I was in thought. Currently I am researching the methodology used in smithing weapons during the age of [Veksar]. If you wish to help, let me know. I will take any [help] available, be it friend or foe to the legions of Cabilis.'
<p><b>You say, </b>'help'
<br><b>Syrik Iceblood says </b>'We can tell from the weapons that we have taken back from the Bloodgill goblins, that their smithing process must have been very unique for them to remain so sharp after four thousand years of use. Cabilis would like to study the weapons and learn this technique so we can better outfit our troopers. If you will bring me four of the same weapon I will spread your name through our city, and one day you may be able to walk the streets. I am looking for Steel Ch'Ror, Mak'Stor, So'Shar, Ta'Nak, Ga'Nak, and Re'Stek. Until then I will reward you with whatever coin I can get from turning them in for you.'
<p><b>You say, </b>'veksar'
<br><b>Syrik Iceblood says </b>'Veksar was an opulent resort enjoyed by privileged nobles and generals of the empire. It was built near a small freshwater spring with legendary restorative properties, this small outpost was considered one of the finest treasures of the realm. Highly-ranked Iksar from the empire came here to cure their illness and extend their lives with the mystical [waters]. This town was originally created by the Kylong tribe of Iksar, but was assimilated into the ranks of Venril Sathir when he united the five tribes. Many [legendary Iksar] lived there.'
<p><b>You say, </b>'legendary iksar'
<br><b>Syrik Iceblood says </b>'When the Kunzar armies marched upon the Kylong, the three greatest Kylong mystics shattered the medallion of Kylong, a holy relic of their tribe, and fled their mountain homes in order to prevent the Kunzar from reassembling it. These three Kylong were [Verix Kylox], [Dakon Sythrax], and [Sirk Vemat]. As they fled from their tribe they knew that the chances to form the medallion together would be less if the Kylong split up. Verix attempted to hide in the hills of the Dreadlands. Dakon headed north to the Field of Bone. Sirk Vemat headed to the Burning Woods to hide in the forest.'
<p><b>You say, </b>'verix kylox'
<br><b>Syrik Iceblood says </b>'Venril Sathir found Verix Kylox the shaman while he was combining the lands for undead. Venril was angered by his lack of devotion. For his punishment he was sacrificed, but resurrected to become a part of Venril's undead army.'
<p><b>You say, </b>'dakon sythrax'
<br><b>Syrik Iceblood says </b>'Dakon Sythrax the necromancer fled to the Field of Bone. It was here that he raised a small troop of skeletons to build an underwater dungeon where he could hide his treasures. He hid the amulet and some of his more powerful tomes here. One of which was a great [book of necromancy]. The possessor of the book could have full control over an army of undead. He left the skeletons to do his work and returned to surrender to the Kunzar's forces. He was sent to Veksar to work through his days studying the effects of the spring.'
<p><b>You say, </b>'book of necromancy'
<br><b>Syrik Iceblood says </b>'Xalgoz later discovered the cove and he took the medallion back to the five towers of Teraaz, which is now referred to as Kaesora. He left all of the tomes because he did not find them of particular interest. Decades after the war between the dragons and Iksar, a troll that fell from a passing ship found Sythrax's small cove. The skeletons milled around in disarray. After finding the book and reading what of it he could he found that the skeletons would do his bidding. I have heard rumors that Sythrax was able to assume the form of a great lich to live through the decades. His hatred for being trapped, and for being forced to work for Venril has built over the ages. He only wants to escape this place so he can retrieve his medallion and books that he believes to be in the Field of Bone.'
<p><b>You say, </b>'sirk vemat'
<br><b>Syrik Iceblood says </b>'The Sarnak captured Sirk Vemat the warrior. They took him to Chardok where they forced him to work in mining out caves that would be used as their city. He still carried the medallion of the Kylong. He knew that in death they would find it on his body so he decided to hide it. He dug a hole as deep into the mountain as he could and placed it in the hole and covered it over. I have heard tales that a slaving rat by the name of Niblek would find the necklace. Niblek's love for shiny things meant that he would keep it with him, but would offer it as trade to anyone that had his favorite type of gems.'
<p><b>You say, </b>'waters'
<br><b>Syrik Iceblood says </b>'Veksar was guarded from the constant attack of dragons and the skulking bands of goblins living in the nearby hills. For years the city thrived with all sorts of visitors. Soldiers harmed by the war were sent there to mend their wounds. High-ranking officials came here to relax and escape the tedium of war. Even Iksar commoners came here desperate to cure whatever ailed them. Since the war with the dragons was always escalating, a massive dome was built overhead to keep the attacks of the dragons away. In spite of efforts, the [dragons] found a way to attack.'
<p><b>You say, </b>'dragons'
<br><b>Syrik Iceblood says </b>'Trakanon sent many dragons here to scout out why this town was so popular. After learning about the Iksar being healed, he know that he had to take action on the city. He formed a plan to first cripple the cities walls so that their own dome would trap them, and then flood the water of the healing spring. This would not only trap them, but also dilute the waters, preventing any further healing from taking place. [Garudon] would lead in the direct attack of the town.'
<p><b>You say, </b>'garudon'
<br><b>Syrik Iceblood says </b>'During the formation of Trakanon's ranks he did not garner the support he desired. One of the first dragons to come to his side was Garudon. He quickly grew to be Trakanon's most trusted ally, and aided in drawing support from the dragon ranks. Because of his high ranking position Garudon would lead the [fight] against Veksar.'
<p><b>You say, </b>'fight'
<br><b>Syrik Iceblood says </b>'The Dragons clawed at the supporting pillars of the dome. The town began to shake and the dome began to fall. The Dragons fled from the pillars, but one was trapped. Garudon was caught in a snare set up by the town's defense. Crumbling to the ground the dome sealed their fate. Garudon fought with the Iksar from under the dome with no hope of escaping. The Dragons then called upon the waters to flow, and flood the valley. The spring was flooded, its magical properties lost forever. The soldiers finally brought down Garudon. With his last breath he let out a flame that scorched much of the dome and then fell from the air, crashing through the ceiling of the theater that was built to entertain the Iksar on the mend. Most of his [bones] still remain there, while others were ground up in necromantic ceremonies.'
<p><b>You say, </b>'bones'
<br><b>Syrik Iceblood says </b>'Scout reports tell of his bones laying scattered across the floor of the theater. Because a constant surge of necromancy was needed to keep the citizens of Veksar animated it could not be stopped. They would have to find a way to prevent the magic from flowing into the theater and reanimating Garudon himself. The mystic words painted onto the wall of the theater seem to point to the fact that the flow of necromancy into the theater is stifled. This is all the lore of the town of Veksar that I can recall.'
<p><b>You give Syrik Iceblood : </b><a href=http://phobos/eq/item.php?id=65506>Steel Ch'Ror</a> x4
<br><b>Syrik Iceblood says </b>'Excellent work, [Your Name]. We will study the architecture of these weapons to better the legions of Cabilis. Soon your name will be known among the Iksar.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=318>Syrik Iceblood</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=30>Cabilis Residents</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=282>Scaled Mystics</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=317>Swift Tails</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 12pp 12gp 6sp
<p><b>You give Syrik Iceblood : </b><a href=http://phobos/eq/item.php?id=65507>Steel Mak'Stor</a> x4
<br><b>Syrik Iceblood says </b>'Excellent work, [Your Name]. We will study the architecture of these weapons to better the legions of Cabilis. Soon your name will be known among the Iksar.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=318>Syrik Iceblood</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=30>Cabilis Residents</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=282>Scaled Mystics</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=317>Swift Tails</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 12pp 12gp 6sp
<p><b>You give Syrik Iceblood : </b><a href=http://phobos/eq/item.php?id=65508>Steel So'Shar</a> x4
<br><b>Syrik Iceblood says </b>'Excellent work, [Your Name]. We will study the architecture of these weapons to better the legions of Cabilis. Soon your name will be known among the Iksar.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=318>Syrik Iceblood</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=30>Cabilis Residents</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=282>Scaled Mystics</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=317>Swift Tails</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 12pp 12gp 6sp
<p><b>You give Syrik Iceblood : </b><a href=http://phobos/eq/item.php?id=65509>Steel Ta'Nak</a> x4
<br><b>Syrik Iceblood says </b>'Excellent work, [Your Name]. We will study the architecture of these weapons to better the legions of Cabilis. Soon your name will be known among the Iksar.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=318>Syrik Iceblood</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=30>Cabilis Residents</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=282>Scaled Mystics</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=317>Swift Tails</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 12pp 12gp 6sp
<p><b>You give Syrik Iceblood : </b><a href=http://phobos/eq/item.php?id=65510>Steel Ga'Nak</a> x4
<br><b>Syrik Iceblood says </b>'Excellent work, [Your Name]. We will study the architecture of these weapons to better the legions of Cabilis. Soon your name will be known among the Iksar.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=318>Syrik Iceblood</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=30>Cabilis Residents</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=282>Scaled Mystics</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=317>Swift Tails</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 12pp 12gp 6sp
<p><b>You give Syrik Iceblood : </b><a href=http://phobos/eq/item.php?id=65511>Steel Re'Stek</a> x4
<br><b>Syrik Iceblood says </b>'Excellent work, [Your Name]. We will study the architecture of these weapons to better the legions of Cabilis. Soon your name will be known among the Iksar.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=318>Syrik Iceblood</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=30>Cabilis Residents</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=282>Scaled Mystics</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=317>Swift Tails</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 12pp 12gp 6sp
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>