<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=8004>Explorer Survival Knife</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a><li><a href=http://phobos/eq/faction.php?id=30>Cabilis Residents</a><li><a href=http://phobos/eq/faction.php?id=282>Scaled Mystics</a><li><a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a><li><a href=http://phobos/eq/faction.php?id=317>Swift Tails</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Trooper Vaurk says </b>'Have you been sent by the War Baron to [assist]? The explorers from Firiona Vie draw closer.'
<p><b>You say, </b>'assist'
<br><b>Trooper Vaurk says </b>'That is good, I will stay here to halt any advances. Head out near the lake and destroy the trespassers on our land! Bring me four of their knives that they carry for survival. Prove your allegiance to the Legion of Cabilis.'
<p><b>You give Trooper Vaurk : </b><a href=http://phobos/eq/item.php?id=8004>Explorer Survival Knife</a> x4
<br><b>Trooper Vaurk says </b>'Great work, the Legion of Cabilis will not soon forget your dedication. The trespassers shall all be dealt with.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=30>Cabilis Residents</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=282>Scaled Mystics</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=317>Swift Tails</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Trooper Vaurk says </b>'I have no need for this item [Your Name], you can have it back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>