<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When Vorash spawns </b>
<p><b>You say, </b>'hail'
<br><font color=green><b>Vorash </b>ignores you.</font>
<hr><b>When Vorash is killed </b>
<br><b>Vorash says </b>'Foolish mortal! you think you have defeated me? Now, witness the true power of Rallos Zek!'
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=85208>Xenevorash</a></b> spawns (-807,-542,79.12).</font>
</td></tr></table>