<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=2485>Torgiran Shackle Key</a></ul></td><td><hr><b>When a resistance miner is killed </b>
<br><font color=green><b>a resistance miner </b>'s corpse falls back, its legs jerking spastically.</font>
<p><b>You give a resistance miner : </b><a href=http://phobos/eq/item.php?id=2485>Torgiran Shackle Key</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>a resistance miner disappears.</b>
<p><b>You give a resistance miner : </b><a href=http://phobos/eq/item.php?id=2485>Torgiran Shackle Key</a> x2
<br><font color=yellow>You gain experience!!</font>
<br><b>a resistance miner disappears.</b>
<p><b>You give a resistance miner : </b><a href=http://phobos/eq/item.php?id=2485>Torgiran Shackle Key</a> x3
<br><font color=yellow>You gain experience!!</font>
<br><b>a resistance miner disappears.</b>
<p><b>You give a resistance miner : </b><a href=http://phobos/eq/item.php?id=2485>Torgiran Shackle Key</a> x4
<br><font color=yellow>You gain experience!!</font>
<br><b>a resistance miner disappears.</b>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>