<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4747>Bag of Rations</a><li><a href=http://phobos/eq/item.php?id=4755>A Bundle of Mining Picks</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=154>House of Stout</a><li><a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a></ul></td><td><hr><b>When Daesorak Steelknuckle spawns </b>
<p><b>You say, </b>'hail'
<br><b>Daesorak Steelknuckle says </b>'Lo there stranger what ya doin in ere? You know how dangerous it can be down ere! I be lucky I got some of da finest miners werkin for me. I sure do hope we get those supplies soon.'
<p><b>You say, </b>'retrieve the mining picks'
<p><b>You say, </b>'return a letter'
<p><b>You give Daesorak Steelknuckle : </b><a href=http://phobos/eq/item.php?id=4747>Bag of Rations</a>
<br><b>Daesorak Steelknuckle says </b>'Ah these must be from ol Coggo! Ye see I had sent out a few men to gather some new picks an such for the mining operation ere but they haven't returned yet. I'm really in need of some picks that are being held in Katta by a friend of mine. Will you [retrieve the mining picks] for me?'
<p><b>You give Daesorak Steelknuckle : </b><a href=http://phobos/eq/item.php?id=4755>A Bundle of Mining Picks</a>
<br><b>Daesorak Steelknuckle says </b>'Ye did it, [Your Name]! Ye hear dat boys! Dis outlander ere jess delivered us our new minin picks! You have no idea how much these supplies will aid our operation! As a final task would you be able to [return a letter] to me wife back home?'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=154>House of Stout</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>