<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When 215447 is killed </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=215446>a_sporadic_stormrider</a></b> spawns (,15,).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=215446>a_sporadic_stormrider</a></b> spawns (,-15,).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=215446>a_sporadic_stormrider</a></b> spawns.</font>
</td></tr></table>