<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1665>Tiny Gem</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=342>True Spirit</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Bondl Felligan </b>burps loudly in your face and says, 'Bah! Leave me be, fool! You have nothin' I want and I certainly have nothin' you want.</font>
<p><b>You say, </b>'you can buy booze'
<br><font color=green><b>Bondl Felligan </b>suddenly becomes completely sober and says, 'Very well, shaman, please come with me.'</font>
<p><b>You give Bondl Felligan : </b><a href=http://phobos/eq/item.php?id=1665>Tiny Gem</a>
<br><b>Bondl Felligan says </b>'WOW, thanks! This must be worth a fortune! I could drink for a month after sellin' this to one of them fool merchants. I'm going to see how much I can get for it right now!'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=342>True Spirit</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=8117>a_greater_spirit</a></b> spawns (66,62,32.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=8118>a_greater_spirit_</a></b> spawns (103,67,32.1).</font>
<br><b>Bondl Felligan says </b>'What!? You don't approve of me buyin' some drinks with this gem? Who the heck are you to offer me a gift and order me what to do with it? Is this some kinda conditional kindness? Well? Are you gonna let me buy some booze with this or not?'
</td></tr></table>