<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18747>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13571>Colorfully Patched Tunic*</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=322>The Dead</a><li><a href=http://phobos/eq/faction.php?id=316>Storm Reapers</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=165>Karana</a><li><a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a></ul></td><td><p><b>You give Caskin Marsheart : </b><a href=http://phobos/eq/item.php?id=18747>A tattered note</a>
<br><b>Caskin Marsheart says </b>'Welcome to the guild. here's your guild tunic. Now. let's get to work.'
<br><b>Caskin Marsheart gives you : </b><a href=http://phobos/eq/item.php?id=13571>Colorfully Patched Tunic*</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=322>The Dead</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=165>Karana</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=316>Storm Reapers</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>