<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13872>Sack of Piranha</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=322>The Dead</a><li><a href=http://phobos/eq/faction.php?id=Not_Found></a><li><a href=http://phobos/eq/faction.php?id=10103></a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=304>Soldiers of Tunare</a><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul></td><td><p><b>You give Celsar Vestagon : </b><a href=http://phobos/eq/item.php?id=13872>Sack of Piranha</a>
<br><b>You receive </b> 14cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=322>The Dead</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=304>Soldiers of Tunare</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10103></a> has gotten better.</font>
</td></tr></table>