<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18158>A Bardic Letter (Freeport)</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=316>Storm Reapers</a><li><a href=http://phobos/eq/faction.php?id=322>The Dead</a><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a><li><a href=http://phobos/eq/faction.php?id=165>Karana</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Felisity Starbright says </b>'Hail. [Your Name] - If you are interested in helping the League of Antonican Bards by delivering some mail. you should talk to Ton Twostring.'
<p><b>You give Felisity Starbright : </b><a href=http://phobos/eq/item.php?id=18158>A Bardic Letter (Freeport)</a>
<br><b>You receive </b> 12gp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=316>Storm Reapers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=322>The Dead</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=149>Highpass Guards</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=165>Karana</a> has gotten worse.</font>
</td></tr></table>