<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>Guard Willa says </b>'Please, let me go. I shall leave the [Freeport Militia]. I did not know they were such a vile group.'
<p><b>You say, </b>'What about the Freeport Militia'
<br><b>Guard Willa says </b>'I thought they were nothing more than the local militia. Little did I know they were so vile. Now I am stuck [here] and I ask for your forgiveness.'
<p><b>You say, </b>'Why are you here'
<br><b>Guard Willa says </b>'I came here to escape the militia and ask [Merko to forgive] me.'
<p><b>You say, </b>'Why ask Merko to forgive you'
<br><b>Guard Willa says </b>'I had a small encounter with his wife, my aunt. She was quite red after that altercation. I guess I upset her in a great way, somehow. Could you please go ask Merko to forgive [Willia]. I shall wait here for his answer.'
<hr><b>When Guard Willa is killed </b>
<br><b>Guard Willa says </b>'Your name shall be added to the most wanted list of the Freeport Militia!!'
</td></tr></table>