<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18737>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13554>Faded Purple Tunic*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Gygus Remnara says </b>'The Temple of Marr welcomes you. I am Gygus Remnara. High Sentinel for the Sentries of Passion. We are the order of paladins within the Priests of Marr and whose charge it is to protect the holy Temple of Marr.'
<p><b>You give Gygus Remnara : </b><a href=http://phobos/eq/item.php?id=18737>A tattered note</a>
<br><b>Gygus Remnara says </b>'Thanks.'
<br><b>Gygus Remnara gives you : </b><a href=http://phobos/eq/item.php?id=13554>Faded Purple Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>