<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Jemoz Lerkarson says </b>'Bless you. my friend!  We always welcome new converts into our Hall of Truth.  The righteous army of the twin deities must assemble.  The battle draws near.  The blessings of the Truthbringer are passed to all who are [devoted to truth].'
<p><b>You say, </b>'i am devoted to truth'
<br><b>Jemoz Lerkarson says </b>'Work on the ways of valor before we discuss such things. You are on the righteous path of the Truthbringer. but there is more work to do.'
</td></tr></table>