<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18818>A tattered flier</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18817>A Sealed Letter</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Kalatrina Plossen says </b>'Hail!  Welcome to the Hall of Truth.  We. the Knights of Truth. are all the hope this city has of loosening the grip of Lucan D'lere and his militia.  I seek a young knight to [serve the will of the Truthbringer].'
<p><b>You say, </b>'what serve the will of the truthbringer'
<br><b>Kalatrina Plossen says </b>'Shame on you.  To set foot into the Hall of Truth and not know for whom it was built.  Still. it is never too late to see the light.  Mithaniel Marr is our deity.  He is the Truthbringer.  By living our lives in valor and crushing all those who suppress His beliefs. We serve Him.'
<p><b>You say, </b>'I serve the will of the Truthbringer'
<br><b>Kalatrina Plossen says </b>'Stand tall then, knight! We have need of your services. We have sent a man to infiltrate the militia. We fear he may soon be found out. Take him this note of warning. Say the words, 'Truth is good,' and you shall find him. Be careful, young knight. The militia does not take prisoners.'
<br><b>Kalatrina Plossen gives you : </b><a href=http://phobos/eq/item.php?id=18817>A Sealed Letter</a>
<p><b>You say, </b>'Zimel's Blades was condemned'
<br><b>Kalatrina Plossen says </b>'Why would Lucan visit a condemned building? He must be searching for something. When I last visited the local forge, I heard rumors of Lucan searching for a sword named Soulfire. If this is true, you must find it first! No more power should go his way. Seek this sword out!'
<p><b>You give Kalatrina Plossen : </b><a href=http://phobos/eq/item.php?id=18818>A tattered flier</a>
<br><b>Kalatrina Plossen says </b>'Zimel's Blades?! Hmmmmm. It doesn't ring a bell and the remainder of the writing is too hard to make out. It kind of looks like a list of prices. You know, down at the Office of the People they might be able to tell us if this place exists. Go speak with Rashinda. She knows all about Freeport. If [Zimel's Blades] existed, you must report back to me what happened to it.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<br><b>Kalatrina Plossen says </b>'I have no use for this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>