<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=14018>A Spider Venom Sac</a><li><a href=http://phobos/eq/item.php?id=12144>Token of Bravery</a><li><a href=http://phobos/eq/item.php?id=13865>Token of Generosity</a><li><a href=http://phobos/eq/item.php?id=13866>Token of Truth</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18896>A note</a><li><a href=http://phobos/eq/item.php?id=12144>Token of Bravery</a><li><a href=http://phobos/eq/item.php?id=18828>Testimony</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Merko Quetalis says </b>'Hail. good citizen!  You have entered the Hall of Truth.  What is it you seek?  Many citizens come to request aid in dealing with the local rogues or the oppression of our sworn enemies. the Freeport Militia.  A few valiant ones have been [summoned to the Hall of Truth].'
<p><b>You say, </b>'i have been summoned to the hall of truth'
<br><b>Merko Quetalis says </b>'You have been summoned? You do not have the look of nobility. You must be a [squire]. There are many squires who have been summoned to our Hall. Not all pass the [Test of Truth].'
<p><b>You say, </b>'I am a squire'
<br><b>Merko Quetalis says </b>'Then I welcome you, Squire . Being a squire is the first step to becoming a true knight of the Hall of Truth. Remember always to protect and serve the meek. I have a [small task] which suits a squire perfectly.'
<p><b>You say, </b>'What small task'
<br><b>Merko Quetalis says </b>'Venture to the Commonlands and seek out our noble friend Altunic Jartin. He lives and works out of his home. Hand him this note.'
<br><b>Merko Quetalis gives you : </b><a href=http://phobos/eq/item.php?id=18896>A note</a>
<p><b>You say, </b>'earned the Token of Generosity'
<br><b>Merko Quetalis says </b>'Go to the deserts of North Ro. Seek out the desert tarantulas. Stand and face this dreaded creature. If you are lucky, you will find a venom sac. This is what I require. When you return, hand it to me.'
<p><b>You say, </b>'what test of truth'
<br><b>Merko Quetalis says </b>'Only when a squire is ready, may he tempt his fate. All he need do is hand the tokens of bravery and generosity to me. If the squire survives his ordeal, then he or she shall enter the order of the Knights of Truth. The squire will be given the Testimony of Truth and become a respected knight.'
<p><b>You say, </b>'Who is Willia'
<br><b>Merko Quetalis says </b>'She is my niece. Lucan ordered her to kill my wife.. She did. She now belongs to the Freeport Militia. As part of the militia, she must die!! Let no militia member stand in the way of nobility.'
<p><b>You give Merko Quetalis : </b><a href=http://phobos/eq/item.php?id=14018>A Spider Venom Sac</a>
<br><b>Merko Quetalis says </b>'You have earned the token of bravery. Now you must ask yourself if you are ready to face true fear. You will have but one chance. If you feel you are powerful enough to easily slay that desert tarantula, then hand me both tokens earned and you shall face the Test of Truth.'
<br><b>Merko Quetalis gives you : </b><a href=http://phobos/eq/item.php?id=12144>Token of Bravery</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<p><b>You give Merko Quetalis : </b><a href=http://phobos/eq/item.php?id=12144>Token of Bravery</a>, <a href=http://phobos/eq/item.php?id=13865>Token of Generosity</a>
<br><b>Merko Quetalis says </b>'Go to the open sewer across the way. Inside you shall find your opponent. Victory shall bring your final token. Return it to me. Remember our ways and remember our foes. Send them to their judgement in the afterlife. Be swift with your thoughts. May Marr be with you.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<p><b>You give Merko Quetalis : </b><a href=http://phobos/eq/item.php?id=13866>Token of Truth</a>
<br><b>Merko Quetalis says </b>'You have performed well. You have shown your allegiance to truth and cast aside the Freeport Militia. The militia will surely despise you from now on. This is how they treat the Knights of Truth. Beware. The followers of Marr stand alone in this city.'
<br><b>Merko Quetalis gives you : </b><a href=http://phobos/eq/item.php?id=18828>Testimony</a>
<br><b>You receive </b> 6gp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>