<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Palious Jarten says </b>'It is good to see you. [Your Name]!! Do not forget that the clerics of Mithaniel Marr are here to help those who pay tribute to Him. Should you require me to [cure disease]. just mention it.'
<p><b>You say, </b>'what cure disease'
<br><b>Palious Jarten says </b>'If you require me to cure disease. it will cost you 10 gold coins.'
</td></tr></table>