<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Rashinda Elore says </b>'Hello. I am Rashinda Elore. The city Landholder Manager. If you have business to discuss. please direct it to my two clerks downstairs. Good day.'
<p><b>You say, </b>'What do you know of Zimel's Blades'
<br><b>Rashinda Elore says </b>'Ariska Zimel was a human blacksmith, a master when it came to making swords, I hear. He kept to himself a lot. He disappeared about one year ago. A lot of people were disappointed when we had to condemn Zimel's Blades. All the merchandise was handed over to Groflah Steadirt. Mostly charred junk.'
<p><b>You say, </b>'Who is Groflah Steadirt'
<br><b>Rashinda Elore says </b>'Groflah Steadirt is the dwarven owner of Groflah's Forge which is right near here. He was Ariska Zimel's best friend. They were apparently avid travelers before settling down here in Freeport. I guess it was during their travels that they picked up the fine arts of the forge. You should talk to Groflah about Zimel. He can tell you more than I can.'
<p><b>You say, </b>'Why was Zimel's Blades condemned'
<br><b>Rashinda Elore says </b>'About a week after Ariska Zimel's disappearance, strange noises were heard from his shop. Loud booms and rumbling as though the earth itself were exploding. When the militia got to the shop, they said the shop was badly burned by an exploding boiler. They had us condemn the building due to its unsafe structure'
</td></tr></table>