<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18474>Scroll of the Burning Dead</a><li><a href=http://phobos/eq/item.php?id=31492>Ghostly Bridle</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=31496>Bridle of Sir Ariam</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a><li><a href=http://phobos/eq/faction.php?id=258>Priests of Marr</a><li><a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=86>Dismal Rage</a><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a></ul></td><td><p><b>You say, </b>'befallen'
<br><b>Sir Artanis says </b>'You did well to ride swiftly with this news. I must take this directly to Valeron Dushire. If you learn more about this plot that would unleash this monster upon Norrath or wish to someday soon aid the Knights of Truth in putting down this evil, then return to speak to me again at a later time.'
<p><b>You give Sir Artanis : </b><a href=http://phobos/eq/item.php?id=18474>Scroll of the Burning Dead</a>
<br><b>Sir Artanis says </b>'By Marr, what is this? .. Burning Dead .. .. Marnek! By my blade this must be stopped! Where did you find this?'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=86>Dismal Rage</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=258>Priests of Marr</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 6sp 10cp
<p><b>You give Sir Artanis : </b><a href=http://phobos/eq/item.php?id=31492>Ghostly Bridle</a>
<br><b>Sir Artanis says </b>'It was a fine and valiant steed to serve its master beyond the grave, but it looks to be near its end. But I have a fine eye for horses, and I dare say it will serve you one more time.'
<br><b>Sir Artanis gives you : </b><a href=http://phobos/eq/item.php?id=31496>Bridle of Sir Ariam</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=86>Dismal Rage</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=258>Priests of Marr</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>