<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18735>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13556>White and Blue Tunic*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Tholius Quey says </b>'Welcome [Your Name] . This is the Temple of Marr and you must be another seeker of Passion and Valor. That is good. Become one with us and help us to defeat the [fallen knight]. It is he who has caused the demise of this city.'
<p><b>You say, </b>'knight'
<br><b>Tholius Quey says </b>'The fallen knight I speak of is none other than Sir Lucan D'Lere. The self proclaimed ruler of this city. He is no ruler and he never was no true Knight of Truth. If it were not for the [Crusade of Tears] this city would still be united in valour.'
<p><b>You say, </b>'crusade'
<br><b>Tholius Quey says </b>'In the year of thirty one hundred fifty. the Knights of Truth were called upon by the twin gods Erollisi and Mithaniel Marr. They instructed us to go forth across the Ocean of Tears and across the lands of Faydwer and purge the lands of the undead. It was during this crusade Freeport was left in the care of Sir Lucan D'Lere. How unfortunate.'
<p><b>You give Tholius Quey : </b><a href=http://phobos/eq/item.php?id=18735>A tattered note</a>
<br><b>Tholius Quey says </b>'Thanks.'
<br><b>Tholius Quey gives you : </b><a href=http://phobos/eq/item.php?id=13556>White and Blue Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>