<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=31493>Arrialla's Expended Token</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=31495>Arrialla's Token</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=8>Anti-mage</a><li><a href=http://phobos/eq/faction.php?id=43>Clerics of Tunare</a><li><a href=http://phobos/eq/faction.php?id=178>King Tearis Thex</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Arrias Arcanum says </b>'I am sorry, young one, but I am too burdened by my own troubles to help you now. Please seek another of the faith to ease your soul.'
<p><b>You say, </b>'troubles'
<br><b>Arrias Arcanum says </b>'My son Ariam, a paladin of this fair city, has been missing for many years. Now, after remaining hopeful for so long, I have given up and it has broken my heart and soul. If I could but hear news to know of his fate, then I could find comfort again. Until then, I am no good to others. I am sorry.'
<p><b>You give Arrias Arcanum : </b><a href=http://phobos/eq/item.php?id=31493>Arrialla's Expended Token</a>
<br><b>Arrias Arcanum says </b>'This! This is the gift my daughter gave Ariam to aid his cause. This too is the piece of my soul that was missing. Your news of his fate is troubling, yet his heroism even beyond this life is cause for celebration. Here, keep this token. My heart is mended and I have no need of it. Once such as yourself who will continue to fight for the things in which
my son believes ought to bear this. I am sure my daughter would agree.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=8>Anti-mage</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=43>Clerics of Tunare</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=178>King Tearis Thex</a> has gotten better.</font>
<br><b>Arrias Arcanum gives you : </b><a href=http://phobos/eq/item.php?id=31495>Arrialla's Token</a>
</td></tr></table>