<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=14334>Arantir's Ring</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=14335>Arantir's Ring</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=342>True Spirit</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Challice says </b>'You!  Remove yourself from my presence!  Do you not know to whom you speak?  My husband is a very powerful noble and if you do not do as I say. he will have your head!'
<p><b>You give Challice : </b><a href=http://phobos/eq/item.php?id=14334>Arantir's Ring</a>
<br><b>Challice says </b>'Oh yes? Arantir? What a fool he was! the man gave me everything, but for all his intelligence, he could never understand why I was truly with him. It was for his power; he could do anything. But when he mysteriously lost it, he became just another toy. I never loved him. Return this ring to him. He will understand that I have no desire to see him again.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=342>True Spirit</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Challice gives you : </b><a href=http://phobos/eq/item.php?id=14335>Arantir's Ring</a>
</td></tr></table>