<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=29002>Tainted Darksteel Shield</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=29005>Gleaming Crested Shield</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Elia the Pure says </b>'Hail to you, friend. If you require assistance, please ask, if not I must return to my tasks.'
<p><b>You say, </b>'tasks'
<br><b>Elia the Pure says </b>'It is here that the light shines brightest in our fair city. Here I sit, transcribing scrolls of luminescence. Spells to light the dark, to blind the evil with purity, or to heal those in pain. I find it so much easier to work with such spells if I am in the light itself.'
<p><b>You say, </b>'purity'
<br><b>Elia the Pure says </b>'Cleansing and such. Often our temple will cleanse evil. If you have need of such a thing, I can help. Merely let me examine the item.'
<p><b>You give Elia the Pure : </b><a href=http://phobos/eq/item.php?id=29002>Tainted Darksteel Shield</a>
<br><font color=green><b>Elia the Pure </b>squints and turns her head. 'By the gods, such a twisted aura this has! To see it hurts my eyes. I will help you if for no other reason than to remove such a twisted thing from existence.' She unrolls a scroll from her pack and softly chants over the dark metal shield. She hands it back to you with an exhausted smile on her face. 'Your heart seems pure. If I was able to help at all, I am honored. May the light shine warmly upon you.'</font>
<br><b>Elia the Pure gives you : </b><a href=http://phobos/eq/item.php?id=29005>Gleaming Crested Shield</a>
</td></tr></table>