<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13071>Rat Whiskers</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=212>Merchants of Felwithe</a><li><a href=http://phobos/eq/faction.php?id=8>Anti-mage</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Exterminator Valern says </b>'Hello. Nice day, isn't it? It would be nicer if I didnt have to spend it killing these disgusting rodents that have infested town. Hey, I have an idea! How about you go kill some of them for me and collect four of their whiskers? I will reward you, of course.'
<p><b>You give Exterminator Valern : </b><a href=http://phobos/eq/item.php?id=13071>Rat Whiskers</a> x4
<br><b>Exterminator Valern says </b>'Here are you coins as promised. Have a nice day. I wish I could.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=212>Merchants of Felwithe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=8>Anti-mage</a> has gotten better.</font>
<br><b>You receive </b> 1gp 1sp 1cp
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>