<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13225>Illegible Scroll</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13004>Large Lantern</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>General Jyleel says </b>'Stand at attention!!  I am General Jyleel. of the Koada'Vie. defenders of Felwithe.  Do you [follow Tunare]. the Mother of All. or do you still [seek your enlightenment]?'
<p><b>You say, </b>'.*follow Tunare.*'
<br><b>General Jyleel says </b>'No.  You have yet to prove yourself a truly faithful defender of the Clerics of Tunare.  I await your return when you complete your service to the temple.'
<br><b>General Jyleel says </b>'Then you are wise indeed.  Would you like to [assist the defenders] in our conflicts or have you other business to attend to?'
<p><b>You say, </b>'.*seek your enlightenment.*'
<br><b>General Jyleel says </b>'Then seek it within these walls.  We welcome all fine upstanding Koada'Dal.'
<p><b>You say, </b>'i would like to assist the defenders'
<br><b>General Jyleel says </b>'Seek out the Crushbone orcs of the Faydarks.  We must have their oracle scrolls.  They are illegible to you. but we will study them here in Felwithe.  Only the orc oracles will carry them. so be very careful.  There is also the problem with the [Crushbone runners].'
<p><b>You say, </b>'what crushbone runners'
<br><b>General Jyleel says </b>'The Crushbone orcs are sending messages across the Ocean of Tears to Antonica.  Why. we do not know.  The runner is usually spotted on the open pathways of Butcherblock. running toward the docks.  Find him. kill him. and return his note pouch.'
<p><b>You say, </b>'i seek my enlightenment'
<br><b>General Jyleel says </b>'Then seek it within these walls.  We welcome all fine upstanding Koada'Dal.'
<p><b>You say, </b>'i still seek my enlightenment'
<br><b>General Jyleel says </b>'Then seek it within these walls.  We welcome all fine upstanding Koada'Dal.'
<p><b>You say, </b>'what assist the defenders'
<br><b>General Jyleel says </b>'Seek out the Crushbone orcs of the Faydarks.  We must have their oracle scrolls.  They are illegible to you. but we will study them here in Felwithe.  Only the orc oracles will carry them. so be very careful.  There is also the problem with the [Crushbone runners].'
<p><b>You give General Jyleel : </b><a href=http://phobos/eq/item.php?id=13225>Illegible Scroll</a>
<br><b>General Jyleel says </b>'Very fine work. A pity you are not Koada'Vie. Here is a small reward for you. Anytime you come upon an oracle. remember to return its scroll to me. Go and find your fate on the field of battle.'
<br><b>General Jyleel gives you : </b><a href=http://phobos/eq/item.php?id=13004>Large Lantern</a>
<br><b>You receive </b> 2sp 1cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>