<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Lieutenant Rosaed says </b>'What are you doing up here?  This area is for the Koada'Vie only!  If you are not a [defender of Felwithe]. leave at once!!'
<p><b>You say, </b>'what defender of felwithe'
<br><b>Lieutenant Rosaed says </b>'All paladins who have been charged with the defense of Felwithe are called Defenders.'
<p><b>You say, </b>'i am a defender of felwithe'
<br><b>Lieutenant Rosaed says </b>'Hmmph!!  You are a little short to be a guard.  Let us get to work then.  There is much to do.  I have news of a [frightening development] of late.'
<p><b>You say, </b>'what frightening development'
<br><b>Lieutenant Rosaed says </b>'Felwithe weeps!! Our beautiful flower. Princess Lenya Thex. has been reported missing! Lord Tynkale says he is looking into the matter. but I fear he is taking far too long.  I have heard that a man named Tolon Nurbyte has been seen in the city lately.  He looks like a shady one.  I would seek him out for answers to her disappearance.'
</td></tr></table>