<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20458>Grocery List</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20459>Bag of Provisions</a></ul></td><td><p><b>You give Merchant Nora : </b><a href=http://phobos/eq/item.php?id=20458>Grocery List</a>
<br><b>Merchant Nora says </b>'You hardly look like the type of errand runner Farios usually sends out to fetch his groceries but here they are. I hope he chokes on them. Oh, and tell him he still owes me five gold for his last order!'
<br><b>Merchant Nora gives you : </b><a href=http://phobos/eq/item.php?id=20459>Bag of Provisions</a>
<br><font color=green><b>Merchant Nora </b>will not take this item.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>