<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20288>Centurion Relgle's Head</a><li><a href=http://phobos/eq/item.php?id=20289>Head of an Ebon Mask Spy</a><li><a href=http://phobos/eq/item.php?id=20299>Sharp Felwithe Defenders Sword</a><li><a href=http://phobos/eq/item.php?id=20271>Pristine Forest Drakeling Scales</a><li><a href=http://phobos/eq/item.php?id=20274>Arborean Amber</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20295>Dull Felwithe Defenders Sword</a><li><a href=http://phobos/eq/item.php?id=20329>Felwithe Defenders Falchion</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=43>Clerics of Tunare</a><li><a href=http://phobos/eq/faction.php?id=178>King Tearis Thex</a><li><a href=http://phobos/eq/faction.php?id=8>Anti-mage</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Seria Woodwind says </b>'Hail friend. I am Seria Woodwind of the Royal Order of the Koada'Vie, the defenders of Felwithe. I assist young Koada'Dal that are called into Tunare's service as a paladin in learning the ways of the Koada'Vie so that one day they too may bear that noble title.'
<p><b>You say, </b>'wish to become a member'
<p><b>You say, </b>'enemies'
<p><b>You say, </b>'suit of armor'
<p><b>You say, </b>'felwithe defender gauntlets'
<p><b>You say, </b>'felwithe defender boots'
<p><b>You say, </b>'felwithe defender bracer'
<p><b>You say, </b>'felwithe defender helm'
<p><b>You say, </b>'felwithe defender greaves'
<p><b>You say, </b>'felwithe defender vambraces'
<p><b>You say, </b>'felwithe defender breastplate'
<p><b>You say, </b>'further instruction'
<p><b>You say, </b>'Hail'
<br><b>Seria Woodwind says </b>'Hail friend. I am Seria Woodwind of the Royal Order of the Koada'Vie, the defenders of Felwithe. I assist young Koada'Dal that are called into Tunare's service as a paladin in learning the ways of the Koada'Vie so that one day they too may bear that noble title.'
<p><b>You give Seria Woodwind : </b><a href=http://phobos/eq/item.php?id=20288>Centurion Relgle's Head</a>, <a href=http://phobos/eq/item.php?id=20289>Head of an Ebon Mask Spy</a>
<br><b>Seria Woodwind says </b>'Good work [Your Name].  King Tearis Thex and the Royal Order of the Koada'Vie shall be pleased.  Take the Dull Felwithe Defenders Sword to a forge and sharpen it with a sharpening stone.  It may take you several attempts if you are unfamiliar with the process.  Once that is accomplished bring me the Sharp Felwithe Defenders Sword, a Pristine Forest Drakeling Scale, and an Arborean Amber and I will put the finishing touches on the weapon.'
<br><b>Seria Woodwind gives you : </b><a href=http://phobos/eq/item.php?id=20295>Dull Felwithe Defenders Sword</a>
<p><b>You give Seria Woodwind : </b><a href=http://phobos/eq/item.php?id=20299>Sharp Felwithe Defenders Sword</a>, <a href=http://phobos/eq/item.php?id=20271>Pristine Forest Drakeling Scales</a>, <a href=http://phobos/eq/item.php?id=20274>Arborean Amber</a>
<br><font color=green><b>Seria Woodwind </b>fashions a grip from the pristine forest drakeling scales, fastens the arborean amber to the pommel of the hilt and polishes the blade of the sword with a luminescent substance.</font>
<br><b>Seria Woodwind says </b>'Here is your new weapon young defender. May it serve you well in your service to the Koada'Vie.'
<br><b>Seria Woodwind gives you : </b><a href=http://phobos/eq/item.php?id=20329>Felwithe Defenders Falchion</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=43>Clerics of Tunare</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=178>King Tearis Thex</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=8>Anti-mage</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>