<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Tolkar Parlone says </b>'Hail. good adventurer!  I am afraid that my services are not available at the moment.  I am too worried about my [daughter].'
<p><b>You say, </b>'who is your daughter'
<br><b>Tolkar Parlone says </b>'My daughter's name is Lenara.  I have not seen her in several months. and I fear the worst.  She went off adventuring. even though I told her how dangerous it was.'
</td></tr></table>