<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18781>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13591>Used Gold Training Tunic*</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Tynkale says </b>'Hail noble, [Your Name]!  Can you be of [service to the Clerics of Tunare] or are you not from our order?'
<p><b>You say, </b>'.*will.*service to the clerics of Tunare*.'
<br><b>Tynkale says </b>'When you have furthered your service to the Paladins of Tunare. we shall make conversation.'
<p><b>You say, </b>'i can be service to the clerics of tunare'
<br><b>Tynkale says </b>'That is good. Prove yourself, then.  Are you [new to Felwithe] or have I been conversing with a [veteran of the good fight]?'
<p><b>You say, </b>'i am new to felwithe'
<br><b>Tynkale says </b>'Then stand at attention when I speak.  I want you to venture to Kelethin and seek out Tandan Nybright.  He is an old member of ours.  He had some hardships and he fell from Tunare's grace, yet he is still a member of our family.  He will be the one who reeks of elven wine.  Greet him by name.  We are worried for him.'
<p><b>You say, </b>'i am a veteran of the good fight'
<br><b>Tynkale says </b>'I command you to venture to Innothule and seek a beast called Jojongua, a name penned by the trolls.  It is said to be ten feet tall and nothing but fury.  Some say it resembles a kobold, but how can that be?  You bring this beast's hide to me and then I will believe you to be a veteran.  Beware!  Innothule is a very dangerous place even for a noble veteran.'
<p><b>You give Tynkale : </b><a href=http://phobos/eq/item.php?id=18781>A tattered note</a>
<br><b>Tynkale says </b>'Greetings. young paladin!  I am Master Tynkale of the Clerics of Tunare.  Here. we shall teach and train you in the skills needed to defeat our evil and diseased enemies.  Take this, our guild tunic - it will help protect you.  Wear it with pride, for you are now one of us.'
<br><b>Tynkale gives you : </b><a href=http://phobos/eq/item.php?id=13591>Used Gold Training Tunic*</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>