<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13073>Bone Chips</a><li><a href=http://phobos/eq/item.php?id=18780>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15014>Spell: Strike</a><li><a href=http://phobos/eq/item.php?id=13590>Faded Gold Training Tunic*</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=43>Clerics of Tunare</a><li><a href=http://phobos/eq/faction.php?id=178>King Tearis Thex</a><li><a href=http://phobos/eq/faction.php?id=8>Anti-mage</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Yeolarn Bronzeleaf says </b>'Hail. [Your Name] !  We of Tunare are charged with protecting the Great Mother from the forces of Innoruuk.  Even now. the evil minions of this foul deity are despoiling our great forest.  Will you help us [protect the Mother]?'
<p><b>You say, </b>'protect'
<br><b>Yeolarn Bronzeleaf says </b>'Just outside the gates of Felwithe. the forces of Innoruuk gather in the guise of decaying skeletons.  Bring me four sets of bone chips as proof of your vigilance.  I assure you. your faith shall not go unrewarded.'
<p><b>You give Yeolarn Bronzeleaf : </b><a href=http://phobos/eq/item.php?id=13073>Bone Chips</a> x4
<br><b>Yeolarn Bronzeleaf says </b>'Praise Tunare! I knew you would be victorious.  I reward you with this spell. and pray that it will help you in your fight against the unholy forces of Innoruk. When you are ready you will make a fine [Initiate of Tunare].'
<br><b>Yeolarn Bronzeleaf gives you : </b><a href=http://phobos/eq/item.php?id=15014>Spell: Strike</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=43>Clerics of Tunare</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=178>King Tearis Thex</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=8>Anti-mage</a> has gotten better.</font>
<p><b>You give Yeolarn Bronzeleaf : </b><a href=http://phobos/eq/item.php?id=18780>A tattered note</a>
<br><b>Yeolarn Bronzeleaf says </b>'Welcome. friend. to the Clerics of Tunare.  I am Yeolarn Bronzeleaf. head of the guild and devout follower of Tunare.  Here is your guild tunic - it will help to protect you against this world's evils.'
<br><b>Yeolarn Bronzeleaf gives you : </b><a href=http://phobos/eq/item.php?id=13590>Faded Gold Training Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>