<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12317>The Idol</a><li><a href=http://phobos/eq/item.php?id=10133>Red Sash of Order</a><li><a href=http://phobos/eq/item.php?id=12315>Rare Robe Pattern</a><li><a href=http://phobos/eq/item.php?id=12256>Robe of the Lost Circle</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12315>Rare Robe Pattern</a><li><a href=http://phobos/eq/item.php?id=10133>Red Sash of Order</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Brother Zephyl says </b>'Greetings. I am one with the [Lost Circle]. You have found me. What is it you desire?'
<p><b>You say, </b>'what lost circle'
<br><b>Brother Zephyl says </b>'The [monks of the Whistling Fist] are called the Lost Circle by others. We are an ancient league of monks. Long forgotten and few yet remain. Within this realm there are only two, [Brother Qwinn] and I. We seek the items stolen from us. I seek the [idol of Zan Fi].'
<p><b>You say, </b>'I am an interested monk'
<br><b>Brother Zephyl says </b>'Then venture to the lands of evil. The swamps of the trolls and ogres. There, seek out a monk called Raster. He has the idol. You will return here and wait for my reappearance. When we meet again, you shall hand me the idol and a red sash earned from the Ashen Order. Do so and you shall be closer to joining the brotherhood.'
<p><b>You say, </b>'what idol of zan fi'
<br><b>Brother Zephyl says </b>'The idol of Zan Fi is a totem that is sacred to our brotherhood. I cannot share its secrets, but I can offer to you a reward for its return. Are you an [interested monk]?'
<p><b>You say, </b>'brother qwinn'
<br><b>Brother Zephyl says </b>'Brother Qwinn is searching for one who can return the [Code of the Whistling Fist]. I believe he is in the vicinity of the Plains of Karana.'
<p><b>You say, </b>'what code of the whistling fists'
<br><b>Brother Zephyl says </b>'The tome called the Code of the Whistling Fist has been stolen from [Brother Qwinn]. It contains many secrets pertaining to our brotherhood. Thankfully, it is magically locked and only a Zan Fi master could unlock it. Still, Qwinn must see its safe return.'
<p><b>You say, </b>'return the sash'
<br><b>Brother Zephyl says </b>'Very well. Give to me that which you have been rewarded or the robe, if you have a tailored one.'
<p><b>You give Brother Zephyl : </b><a href=http://phobos/eq/item.php?id=12317>The Idol</a>, <a href=http://phobos/eq/item.php?id=10133>Red Sash of Order</a>
<br><b>Brother Zephyl says </b>'We had an agreement. The proof of a skilled monk, the red sash, and the idol of Zan Fi.'
<br><b>Brother Zephyl says </b>'We thank you for the return of the idol of Zan Fi. Take this rare robe pattern. You shall find it useful should you aid [Brother Qwinn] in his quest. His item, the rare robe pattern, a swatch of shadow silk and a scroll containing Jonathan's Whistling Warsong. Into a sewing kit they will be going. And into the brotherhood will you. I hope you do not wish me to [return the sash].'
<br><b>Brother Zephyl gives you : </b><a href=http://phobos/eq/item.php?id=12315>Rare Robe Pattern</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Brother Zephyl : </b><a href=http://phobos/eq/item.php?id=12315>Rare Robe Pattern</a>
<br><b>Brother Zephyl gives you : </b><a href=http://phobos/eq/item.php?id=10133>Red Sash of Order</a>
<p><b>You give Brother Zephyl : </b><a href=http://phobos/eq/item.php?id=12256>Robe of the Lost Circle</a>
<br><b>Brother Zephyl gives you : </b><a href=http://phobos/eq/item.php?id=10133>Red Sash of Order</a>
</td></tr></table>