<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10085>A Shining Stone</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10086>A Glamour Stone</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Cynthia says </b>'Hello. I am Cynthia.'
<p><b>You give Cynthia : </b><a href=http://phobos/eq/item.php?id=10085>A Shining Stone</a>
<br><b>Cynthia says </b>'I've done what I can to enchant your stone, but you will need to find Tarn Visilin in Highpass Keep to finish the enchantments.  Don't forget to pay him the same fee you gave me, or he may decide to keep the stone for himself!'
<br><b>Cynthia gives you : </b><a href=http://phobos/eq/item.php?id=10086>A Glamour Stone</a>
</td></tr></table>