<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Darfumpel Zirubbel says </b>'Hail. [Your Name].  I am Darfumpel. master jeweler and proprietor of this shop.  How might I assist you today?  Perhaps you need a stone [cut] or some jewelry [repaired]?'
<p><b>You say, </b>'what cut'
<br><b>Darfumpel Zirubbel says </b>'Yes. I use a new gemcutting technique I designed myself.  It will bring out the beauty of any gem.  However. as arrogant as this may sound. I do not cut just any ordinary stone.  They must be rare or of extraordinary quality.  Have you an exceptional stone that requires faceting?  If so. what type of gem is it?'
<p><b>You say, </b>'what repaired'
<br><b>Darfumpel Zirubbel says </b>'Although more mundane a task. I do have a shop to keep up and so I repair jewelry for a nominal fee.'
</td></tr></table>