<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12311>Deepwater Goblin Net</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12301>Mold of Ro Bracer</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a><li><a href=http://phobos/eq/faction.php?id=103>Followers of Korucust</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=302>Skytalons</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>David says </b>'I. the keeper of the [Bracers of Ro].  welcome you.  Come and rest within our camp.  You have nothing to fear while such righteous might is gathered.'
<p><b>You say, </b>'what bracers of ro'
<br><b>David says </b>'When you can swim the waters of Rathe and return two goblin nets from the elusive goblin net masters. then you will be rewarded the bracer mold.'
<br><b>David says </b>'We. the Deepwater Knights. know of your vile ways. You had best leave while you can.'
<p><b>You give David : </b><a href=http://phobos/eq/item.php?id=12311>Deepwater Goblin Net</a> (x2)
<br><b>David says </b>'Two Deepwater goblin nets are required.'
<br><b>David says </b>'You have done well. Take the mold for the bracer.  Go forth to speak with Thomas of [Lord Searfire].  Then all components shall be known.'
<br><b>David gives you : </b><a href=http://phobos/eq/item.php?id=12301>Mold of Ro Bracer</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=103>Followers of Korucust</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=302>Skytalons</a> has gotten worse.</font>
</td></tr></table>