<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12313>A Nightfall Giant's Head</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Elisabeth says </b>'Very good to meet you. [Your Name].  I am the keeper of the [Greaves of Ro].  Please feel free to rest and recuperate here.  We shall see that you are safe from the evils of the Rathe Mountains.'
<p><b>You say, </b>'greaves of ro'
<br><b>Elisabeth says </b>'Go to the countryside of Freeport.  There, you shall seek out any nightfall giants .  They have terrorized the countryside for too long.  They have protection from common weapons.  Rely on magic.  I failed in tracking them down.  You shall succeed and when return any single head to me. you shall be awarded the mold for the greaves.'
<p><b>You give Elisabeth : </b><a href=http://phobos/eq/item.php?id=12313>A Nightfall Giant's Head</a>
<br><b>Elisabeth says </b>'You have done well.  These giants shall soon be purged from the Commonlands and the inns will be filled once again.  Here is the mold for the Ro Greaves.  For the final component, go and ask Thomas of [Lord Searfire].'
</td></tr></table>