<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13253>Spiderling Eye</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=264>Protectors of Gukta</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Exterminator Galub says </b>'Welcome to Gukta. I am afraid I do not have much time to talk, my friend. Recently, the jungle hatchling population has gotten way out of control around here. I was brought in to try to curb their numbers but there are too many! Perhaps you could be of assistance to me. If you have time, kill some of the hatchlings and bring me four of their eyes. I will reward you of course.'
<p><b>You give Exterminator Galub : </b><a href=http://phobos/eq/item.php?id=13253>Spiderling Eye</a> x4
<br><b>Exterminator Galub says </b>'Thank you for your help! But I must go, as you can see there are still many spiders for me to exterminate!'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=264>Protectors of Gukta</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 1gp 1sp 1cp
</td></tr></table>