<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12268>Ring of the Ancients</a><li><a href=http://phobos/eq/item.php?id=7100>Shadowed Rapier</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2300>Journeyman's Boots</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Hasten Bootstrutter says </b>'Stopped I have done. Greet you I will. What business do we have? Hmm? Speak up!!'
<p><b>You say, </b>'Journeyman Boots'
<br><b>Hasten Bootstrutter says </b>'Journeyman Boots are what you seek? Ha!! I have those upon my feet and disinigrate will they if my life is taken. Extra pair have I and [rare trade] can we make.'
<p><b>You say, </b>'Rare Trade'
<br><b>Hasten Bootstrutter says </b>'I call for three things and Journeyman Boots are yours. I call for a [Shadowed Rapier], call for the [Ring of the Ancients] and call for Gold.. 3250 Gold Coins!! This the trade that I call.'
<p><b>You say, </b>'Shadowed Rapier'
<br><b>Hasten Bootstrutter says </b>'Shadowed Men, foes to all, have appeared. Many lands do they walk. Invisible are they, but items they wield can be seen. Seek them out and return to me a Shadowed Rapier. Return it with haste before 'poof' goes the rapier!! No time to camp have you.'
<p><b>You say, </b>'Ring of the Ancients'
<br><b>Hasten Bootstrutter says </b>'Ancient cyclopes do march the land.  Long have they lived and crafted the rings of the ancients.  I must have one and you shall go and fetch one for me.  Seek the lands of the oldest cyclops clans.  Seek the plains. seek the island in tears and search the dunes for there is one who is last.  His clan was blown from the sands.'
<p><b>You give Hasten Bootstrutter : </b><a href=http://phobos/eq/item.php?id=7100>Shadowed Rapier</a>, <a href=http://phobos/eq/item.php?id=12268>Ring of the Ancients</a>
<br><b>Hasten Bootstrutter says </b>'The time to trade has come!! I am now rich and you are now fast. Take the Journeyman Boots and run like the wind.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Hasten Bootstrutter gives you : </b><a href=http://phobos/eq/item.php?id=2300>Journeyman's Boots</a>
</td></tr></table>