<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=14707>Platinum Diamond Wedding Ring</a><li><a href=http://phobos/eq/item.php?id=14703>Black Sapphire Platinum Necklace</a><li><a href=http://phobos/eq/item.php?id=9240>White Dragon Hide</a><li><a href=http://phobos/eq/item.php?id=11622>Red Dragon Scales</a><li><a href=http://phobos/eq/item.php?id=14402>Vial of Swirling Smoke</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=11603>White Dragonscale Cloak</a><li><a href=http://phobos/eq/item.php?id=11623>Red Dragonscale Armor</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Karam Dragonforge says </b>'Welcome. I have a number of platemail items, if you are interested. I am also a master [smith] of exotic materials such as dragon scales.'
<p><b>You say, </b>'smith'
<br><b>Karam Dragonforge says </b>'Dragon scales make terrific armor. I can make a [white dragonscale cloak] and [red dragonscale armor]. I have not seen any other colored dragon variants around. But if you see any, be sure to let me know. I would be interested in what can be made from their scales.'
<p><b>You say, </b>'white dragonscale cloak'
<br><b>Karam Dragonforge says </b>'Hrmmm. A white dragonscale cloak eh? Hrmmm. Well, I will make you a deal. You can save me some footwork and I will craft your cloak. I want to propose to my [fiancee] but I have neither a [wedding ring] nor a [present] for her. So, return with a white dragon hide, a wedding ring, and a present for my fiancee, and I will fashion your cloak for you.'
<p><b>You say, </b>'fiancee'
<br><b>Karam Dragonforge says </b>'My fiancee...AHHHH.... The love of my life. My purpose for existing. She is a real woman. Long, golden blonde hair with a similarly colored full beard. A stout broad she is, kind and warm at heart. She knows every nook of my essence. But do not let that fool you. She is as strong as many dwarven men. Between you and me, she has even beaten me once or twice arm-wrestling over who gets the last ale and who has to go to the market.'
<p><b>You say, </b>'wedding ring'
<br><b>Karam Dragonforge says </b>'Only the best will do. I will not propose to her with anything less than a platinum and diamond wedding ring.'
<p><b>You say, </b>'present'
<br><b>Karam Dragonforge says </b>'Well, she is quite fond of jewelry. And a black sapphire platinum necklace would complement her eyes and beard so exquisitely.'
<p><b>You say, </b>'red dragonscale armor'
<br><b>Karam Dragonforge says </b>'So you have a red dragon scale, eh? Well, I am wanting very much to return to my fiancee and propose to her. If you could aid me in quickly returning to her with a bit of spare change, we could have a deal. Heck, for the armor, a vial of swirling smoke and 1000 platinum coins is a bargain!'
<p><b>You give Karam Dragonforge : </b><a href=http://phobos/eq/item.php?id=14707>Platinum Diamond Wedding Ring</a>, <a href=http://phobos/eq/item.php?id=14703>Black Sapphire Platinum Necklace</a>, <a href=http://phobos/eq/item.php?id=9240>White Dragon Hide</a>
<br><b>Karam Dragonforge says </b>'My fiancee will be so excited! An exquisite ring for the wedding and a gorgeous necklace as my wedding gift to her. Well, as promised, here is your white dragonscale cloak.'
<br><b>Karam Dragonforge gives you : </b><a href=http://phobos/eq/item.php?id=11603>White Dragonscale Cloak</a>
<p><b>You give Karam Dragonforge : </b><a href=http://phobos/eq/item.php?id=11622>Red Dragon Scales</a>, <a href=http://phobos/eq/item.php?id=14402>Vial of Swirling Smoke</a>
<br><b>Karam Dragonforge says </b>'Wonderful! Now I can get back to my fiance instantly! Isn't Love grand? As for your Red Dragonscale Armor, it is all done. Farewell!'
<br><b>Karam Dragonforge gives you : </b><a href=http://phobos/eq/item.php?id=11623>Red Dragonscale Armor</a>
<br><b>Karam Dragonforge says </b>'I do not need this, friend.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>