<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13899>Lianna's Flute</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19010>Icon of the Reverent</a></ul></td><td><p><b>You say, </b>'Regis'
<br><b>Lianna Ferasa says </b>'Regis was my one true love, but he was [killed] and his soul enslaved by Zahal the Vile.'
<p><b>You say, </b>'killed'
<br><b>Lianna Ferasa says </b>'He was killed in the northern tree line to the east in North Karana. If you kill Zahal, Regis' body will rise from the place where he died. If my flute is on the body, please bring it to me.'
<p><b>You give Lianna Ferasa : </b><a href=http://phobos/eq/item.php?id=13899>Lianna's Flute</a>
<br><b>Lianna Ferasa says </b>'Thank you for setting his spirit free.  Keep his memory alive with this.'
<br><b>Lianna Ferasa gives you : </b><a href=http://phobos/eq/item.php?id=19010>Icon of the Reverent</a>
</td></tr></table>