<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12206>Kilij Plans</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12304>Mold of Ro Boots</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=44>Clerics of Underfoot</a><li><a href=http://phobos/eq/faction.php?id=169>Kazon Stormhammer</a><li><a href=http://phobos/eq/faction.php?id=219>Miners Guild 249</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Nicholas says </b>'Greetings, friend.  I am the keeper of the [Boots of Ro].  Please rest here with us in our camp of righteousness.  No harm can come to you while we paladins keep watch.'
<p><b>You say, </b>'boots of ro'
<br><b>Nicholas says </b>'If you desire the mold needed for smithing the Boots of Ro, then first, you shall prove your power.  I have long sought an ancient holy weapon called the brazen brass kilij.  I have heard rumors of detailed plans on how to make it, coming from Faydwer.  Seek out the kilij plans.  Bring them to me and you shall have the mold.'
<p><b>You give Nicholas : </b><a href=http://phobos/eq/item.php?id=12206>Kilij Plans</a>
<br><b>Nicholas says </b>'Ahh!!  The kilij!!  The legend was true.  As for you..  the mold for the Boots of Ro.  Go and speak with Thomas for the final component.  Ask him of [Lord Searfire].  Brell be with you.'
<br><b>Nicholas gives you : </b><a href=http://phobos/eq/item.php?id=12304>Mold of Ro Boots</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=44>Clerics of Underfoot</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=169>Kazon Stormhammer</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=219>Miners Guild 249</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Nicholas says </b>'I do not need this, friend.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>