<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12312>A Locket</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12302>Mold of Ro Gauntlets</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a><li><a href=http://phobos/eq/faction.php?id=322>The Dead</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Sentry Joanna says </b>'Love and passion to you. my friend.  Seek you the [Gauntlets of Ro]?  If not. then I offer you the safety of this camp.'
<p><b>You say, </b>'what gauntlets of ro'
<br><b>Sentry Joanna says </b>'I will give you the mold. but first you will complete a task in the name of Erollisi Marr.  My fellow Sentry. Alechin. was bitten by a wolf while he journeyed to Qeynos.  He now turns into a werewolf at night. forced to kill innocent travelers.  Go toward Qeynos.  Release him from life and his curse and return his locket to me.'
<br><b>Sentry Joanna says </b>'Erollisi would not approve of our alliance. not yet at least.  Go to Freeport and serve the Temple of Marr.  When you can ask Gygus Remnara if you are an [honored member] and have him answer yes. then we can join forces.'
<p><b>You give Sentry Joanna : </b><a href=http://phobos/eq/item.php?id=12312>A Locket</a>
<br><b>Sentry Joanna says </b>'Thank you my friend.  It is good to see him free at last.  I shall miss him.  Here now is the mold of gauntlets as promised. Go and speak with Thomas for information about [Lord Searfire].'
<br><b>Sentry Joanna gives you : </b><a href=http://phobos/eq/item.php?id=12302>Mold of Ro Gauntlets</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=322>The Dead</a> has gotten better.</font>
</td></tr></table>