<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12308>Cyclops skull</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12298>Mold of Ro Helm</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=183>Knights of Thunder</a><li><a href=http://phobos/eq/faction.php?id=257>Priests of Life</a><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=21>Bloodsabers</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Thomas says </b>'Welcome to our camp.  We are paladins gathered from many lands. We have been called to this land by our deities.  Ours is a crusade of righteousness.  Have you happened upon us by chance or do you [seek the sacred molds]?'
<p><b>You say, </b>'helm of ro'
<br><b>Thomas says </b>'To receive the mold of the Helm of Ro you must first demonstrate your strength.  Go to the plains of thunder.  There you shall hunt down the most vile creatures I have ever encountered.  Seek the undead cyclopes.  I have spied them in the most dangerous portions of my realm. Fetch me two of their skulls.'
<p><b>You say, </b>'seek the sacred molds'
<br><b>Thomas says </b>'Many of us carry the sacred molds of the holy paladin armor.  We will release it only to those who have proven themselves to each of our deities.  If you seek it, speak up!! Tell us which part you seek.  I carry the secret of the [Helm of Ro].  The others carry those of vambraces, breastplates, bracers, gauntlets, greaves and boots of Ro.'
<p><b>You say, </b>'Lord Searfire'
<br><b>Thomas says </b>'Lord Searfire is a great forge master.  He was called forth to the land of fire lakes.  It is said that he now toils in the name of Solusek Ro within a hidden temple of that land.  He and he alone knows how to obtain [ronium], a needed component for forging the sacred Armor of Ro.'
<p><b>You say, </b>'ronium'
<br><b>Thomas says </b>'It is an alloy created from two rare metals.  Only [Lord Searfire] knows the formula.'
<p><b>You give Thomas : </b><a href=http://phobos/eq/item.php?id=12308>Cyclops skull</a> x2
<br><b>Thomas says </b>'You have proven yourself to Karana.  I grant you the mold of the Ro Helm.  May the winds of Karana blow in your favor.  Now you must seek out [Lord Searfire] and  ask him for [ronium] to complete the second and only other component needed to be fashioned by a master blacksmith.'
<br><b>Thomas gives you : </b><a href=http://phobos/eq/item.php?id=12298>Mold of Ro Helm</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=183>Knights of Thunder</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=21>Bloodsabers</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=257>Priests of Life</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<p><b>You give Thomas : </b><a href=http://phobos/eq/item.php?id=12308>Cyclops skull</a>
<br><b>Thomas says </b>'I called for two cyclops skulls.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>