<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When #Aramin the Spider Guardian is killed </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=205154>An_Arachnae_Maleveler</a></b> spawns.</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=205154>An_Arachnae_Maleveler</a></b> spawns.</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=205154>An_Arachnae_Maleveler</a></b> spawns.</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=205154>An_Arachnae_Maleveler</a></b> spawns.</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=205154>An_Arachnae_Maleveler</a></b> spawns.</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=205154>An_Arachnae_Maleveler</a></b> spawns.</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=205154>An_Arachnae_Maleveler</a></b> spawns.</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=205154>An_Arachnae_Maleveler</a></b> spawns.</font>
</td></tr></table>