<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Giwin Mirakon says </b>'How did you get in here? Hrmm no matter, you will be helping me now for I am a [great warrior] of Rallos Zek and I know you wish not to provoke my fury!'
<p><b>You say, </b>'great warrior'
<br><b>Giwin Mirakon says </b>'Yeah, you heard me! You know that I must be important if Rallos himself has plucked me from battlefield to complete this [task]. Even though I serve my lord, I am desperate to return to my place on the eternal battlefield.'
<p><b>You say, </b>'task'
<br><b>Giwin Mirakon says </b>'Ya, you see Rallos sent me here to contract the machines to work on a mana powered piece of machinery that could test all on the eternal battlefield. This weapon of ultimate destruction is taking quite a long time to be completed. You know.. If you were to go [test the machine] and it were to fail against you I could be on my way back to tell Rallos that it was defeated by mere mortals. Help me to get back to the battlefield and out of this rusted out junkheap.'
<p><b>You say, </b>'test the machine'
<br><b>Giwin Mirakon says </b>'Haha! I knew I sensed the warring spirit within you. Go through over there. Ignore those steam powered soldiers and their talk of perimeters. Go into the main construction area. You will know you are there when you see power carriers taking energy to power up the machine. If you can stop the energy carriers from releasing their energy the machine will activate to see what has happened. I shall come to check on you and take a full report when you have destroyed it it. Long live Rallos!'
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<p><b>You say, </b>'Hail'
<br><b>Giwin Mirakon says </b>'How did you get in here? Hrmm no matter, you will be helping me now for I am a [great warrior] of Rallos Zek and I know you wish not to provoke my fury!'
<hr><b>When Giwin Mirakon is killed </b>
</td></tr></table>