<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1686>Trunt's Head</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1686>Trunt's Head</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Deep </b>ignores you.</font>
<p><b>You give Deep : </b><a href=http://phobos/eq/item.php?id=1686>Trunt's Head</a>
<br><font color=green><b>Deep </b>slowly opens her eyes and looks up at you. She stares at you a long while and then closes her eyes and lowers her head again.</font>
<br><b>Deep says </b>'Very well, [Your Name], if you wish death so greatly, we will be happy to oblige. My master projects part of himself in the wilder lands known as the Overthere. He has granted you an audience. Find him and show him the head of our earth brother. At that point, we will discuss how we will end your life.'
<br><b>Deep gives you : </b><a href=http://phobos/eq/item.php?id=1686>Trunt's Head</a>
<br><b>Deep disappears.</b>
</td></tr></table>