<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>Emkel Kabae says </b>'I am Emkel Kabae, first apprentice to Kazen. If you have a symbol, tell me its name.'
<p><b>You say, </b>'symbol of the serpent'
<br><b>Emkel Kabae says </b>'There are more reagents to be gathered. The time draws near for our master's ascension. Travel to the lands of Kunark and seek out Ssessthrass. He is a very wise Iksar herbalist helping me in my endeavor to please Master Kazen. Be careful not to insult his speech, or you may end up dead before you serve your purpose to the master. Be sure to show him the symbol as proof or he may consider you dinner.'
<br><font color=green><b>Emkel Kabae </b>will not accept this item.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>