<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20534>Torch of Rathe</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20379>Proof of Speed</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Misty Tekcihta </b>smiles and taps her foot.</font>
<p><b>You give Misty Tekcihta : </b><a href=http://phobos/eq/item.php?id=20534>Torch of Rathe</a>
<br><font color=green><b>Misty Tekcihta </b>hands you a small ring.</font>
<br><b>Misty Tekcihta gives you : </b><a href=http://phobos/eq/item.php?id=20379>Proof of Speed</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>