<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28046>Damaged Goblin Crown</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28047>Ornate Sea Shell</a></ul></td><td><hr><b>When Natasha Whitewater spawns </b>
<br><font color=red><b>Natasha Whitewater shouts </b>'The Triumvirate of Water has decreed your fate, Shmendrik Lavawalker!! I am here to deliver said fate!!'</font>
<p><b>You say, </b>'hail'
<br><b>Natasha Whitewater says </b>'The Riptide goblins must have their crown returned to them. If you would be so kind as to give me the crown I will make sure that it reaches them. Hopefully they are capable enough to repair the damage that has been done to it.'
<p><b>You give Natasha Whitewater : </b><a href=http://phobos/eq/item.php?id=28046>Damaged Goblin Crown</a>
<br><b>Natasha Whitewater says </b>'I will have this crown returned to the Riptide Goblins immediately! Should you ever come across an Erudite named Omat Vastsea, give him this sea shell. The waters of Norrath shimmer with awareness of your deeds here today!'
<br><b>Natasha Whitewater gives you : </b><a href=http://phobos/eq/item.php?id=28047>Ornate Sea Shell</a>
<br><b>Natasha Whitewater disappears.</b>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>