<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Rondel says </b>'Hello. stranger.  Are you an adventurer?'
<p><b>You say, </b>'i am an adventurer'
<br><b>Rondel says </b>'I wish I could go off and explore the world like you.  I will spend my days as a fisherman here. I am sure.  Nothing ever happens around here though.  Well. except for the other day..'
<p><b>You say, </b>'what other day'
<br><b>Rondel says </b>'I was spearfishing near the aviak construction and something amazing happened.  I was in the middle of spearing a fish when something at the bottom of the lake began to glow red.  I could swear I heard the sounds of a dragon. I did not stick around to find out what it was.'
</td></tr></table>