<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28003>Words of Magi`kot</a><li><a href=http://phobos/eq/item.php?id=28004>Words of Mastery</a><li><a href=http://phobos/eq/item.php?id=28031>Power of the Elements</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28035>Token of Mastery</a><li><a href=http://phobos/eq/item.php?id=18958>Power of the Orb</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Rykas says </b>''Greetings, [Your Name]. I am Rykas, chronicler of knowledge. I have journeyed all throughout the lands of Norrath, and I have learned many tales of adventure from people I have encountered during my travels. I have learned of legends known and unknown to most mortals. Are you in search of knowledge?'
<p><b>You say, </b>'knowledge'
<br><b>Rykas says </b>'A small task is needed if you wish to learn more. Do you wish to learn the tale of Magi'kot?'
<p><b>You say, </b>'Magi'kot'
<br><b>Rykas says </b>'If you seek to learn the tale of Trilith Magi'kot, your journey shall begin in the Commonlands. Search for Jahsohn Aksot and give him this token. He will share some of the knowledge I have bestowed upon him, and point you further down your path to Mastery. Bring me the Words of Mastery, Power of the Elements, and the Words of Magi'kot....Then you shall learn more about the power of the orb.'
<br><b>Rykas gives you : </b><a href=http://phobos/eq/item.php?id=28035>Token of Mastery</a>
<p><b>You give Rykas : </b><a href=http://phobos/eq/item.php?id=28003>Words of Magi`kot</a>, <a href=http://phobos/eq/item.php?id=28004>Words of Mastery</a>, <a href=http://phobos/eq/item.php?id=28031>Power of the Elements</a>
<br><b>Rykas says </b>'I see that you have completed the quest I laid before you. That speaks well of your dedication, yet you do not realize your journey has just begun. Study this tome.'
<br><b>Rykas gives you : </b><a href=http://phobos/eq/item.php?id=18958>Power of the Orb</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Rykas says </b>'I do not need these.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>