<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19001>Ingot of the Reliant</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Turgan says </b>'Hail!  What brings you here?'
<p><b>You say, </b>'icon of the reliant'
<br><b>Turgan says </b>'Where did you hear... I don't know what you are talking about.  Begone!  Back to Kithicor with you!'
<p><b>You give Turgan : </b><a href=http://phobos/eq/item.php?id=19001>Ingot of the Reliant</a>
<br><b>Turgan says </b>'I am that Turgan, but I am no longer worth of this title.  Take this in hopes that you become a better steward than I was.'
</td></tr></table>