<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=2344>Confession Document</a></ul></td><td><p><b>You say, </b>'Bloodsaber'
<br><b>#Donally Stultz says </b>'Of course I'm a Bloodsaber, you fool! I've just returned from the Plains of Karana where I was reveling in the glory of the Plaguebringer. Now then, since I see that this foolish investigator is with you, I suppose you want me to sign a confession document or something like that? Well, let's have it then!'
<p><b>You give #Donally Stultz : </b><a href=http://phobos/eq/item.php?id=2344>Confession Document</a>
<br><font color=green><b>#Donally Stultz </b>crumples the document into a ball, throws it to the ground and spits in your face, yelling, 'You are a fool if you really believe I would sign such a thing. Prepare to die!'</font>
<hr><b>When #Donally Stultz is killed </b>
<br><b>#Donally Stultz says </b>'You...can not...defeat us all...'
</td></tr></table>