<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When #Gash Flockwalker spawns </b>
<p><b>You say, </b>'Hail'
<br><b>#Gash Flockwalker says </b>'Good day to you. Your city of stone walls is quite magnificent. Still, the glory of Surefall Glade puts this city to shame.'
<p><b>You say, </b>'an assassin has been sent to kill you'
<br><b>#Gash Flockwalker says </b>'What!!?  Must be an Unkempt Druid Assassin nearby!!  Find him and slay him.  I am sure he stands to make a FORTUNE!  I believe the assassin may be carrying some sort of [black wood chip].'
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=1179>Raffel_Minnmorn</a></b> spawns (222,-100,2.3).</font>
<p><b>You say, </b>'black wood chip'
<br><b>#Gash Flockwalker says </b>'That is the mark of an Unkempt Druid.  Long ago there was a tree in Norrath we called the Great Tunarbos.  Legend says it spawned all the woodlands of Norrath.  Many centuries ago, long before the Combine Era, the Great Tunarbos was burned to the ground by unknown means.  The ancient rangers kept what little of the great tree they could find.  To make it short, all Unkempt Druids now carry burned wood chips to represent the great tree.  They are not real.  Take any black wood chips to Gerael Woodone in Surefall Glade.'
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=1138>Gash_Flockwalker</a></b> spawns (368.88,-86.88,3.4).</font>
<br><b>#Gash Flockwalker disappears.</b>
</td></tr></table>