<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>#Translocator Sedina says </b>'Hello there. There seem to be some strange problems with the boats in this area. The Academy of Arcane Sciences has sent a small team of us to investigate them. If you need to [travel to] Erud's [Crossing] in the meantime, I can transport you to my companion there.'
<p><b>You say, </b>'travel to crossing'
<br><font color=brown><b>#Translocator Sedina casts a spell : </b><a href=http://phobos/eq/spell.php?id=2289>Portal to Erud's Crossing</a>.</font>
</td></tr></table>