<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=2344>Confession Document</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2394>Willie's Confession</a></ul></td><td><p><b>You say, </b>'Bloodsabers'
<br><b>#Willie Garrote says </b>'A Bloodsaber? Of course I'm not, don't be ridiculous!'
<p><b>You give #Willie Garrote : </b><a href=http://phobos/eq/item.php?id=2344>Confession Document</a>
<br><b>#Willie Garrote gives you : </b><a href=http://phobos/eq/item.php?id=2394>Willie's Confession</a>
</td></tr></table>