<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18289>Investigator's Briefing</a><li><a href=http://phobos/eq/item.php?id=2369>Riley's Confession</a><li><a href=http://phobos/eq/item.php?id=2394>Willie's Confession</a><li><a href=http://phobos/eq/item.php?id=2279>Head of Donally Stultz</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2344>Confession Document</a><li><a href=http://phobos/eq/item.php?id=2386>Investigator's Badge</a></ul></td><td><p><b>You say, </b>'first suspect'
<br><b>an investigator says </b>'The first suspect was last seen near the shop called Fireprides.'
<p><b>You say, </b>'Follow me'
<br><b>an investigator says </b>'Right, let's get going.''
<p><b>You say, </b>'Give me a confession document'
<br><b>an investigator says </b>'Here you are.''
<br><b>an investigator gives you : </b><a href=http://phobos/eq/item.php?id=2344>Confession Document</a>
<p><b>You say, </b>'second suspect'
<br><b>an investigator says </b>'The second suspect was sighted below the Grounds of Fate.'
<p><b>You say, </b>'third suspect'
<br><b>an investigator says </b>'The last suspect has been known to hang around that low life known as Raz the Rat.'
<p><b>You give an investigator : </b><a href=http://phobos/eq/item.php?id=18289>Investigator's Briefing</a>
<br><b>an investigator says </b>'Very well, let's get to work. I assume you have read the briefing and committed it to memory. This is how you will be tested. I shall play the part of student and you shall play the master who directs me. I promise I won't make it easy on you either, we want only the best. We'll see how you do and then I'll decide if you are worthy to wear the badge or not.'
<p><b>You give an investigator : </b><a href=http://phobos/eq/item.php?id=2279>Head of Donally Stultz</a>, <a href=http://phobos/eq/item.php?id=2394>Willie's Confession</a>, <a href=http://phobos/eq/item.php?id=2369>Riley's Confession</a>
<br><b>an investigator says </b>'You have done our city a great service and helped to bring several criminals to justice this day! Wear this Investigator's Badge with pride! Speak again with Vegalys Keldrane, he may have information about [advancing further] in rank.'
<br><b>an investigator gives you : </b><a href=http://phobos/eq/item.php?id=2386>Investigator's Badge</a>
</td></tr></table>