<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18027>Letter to Behroe</a><li><a href=http://phobos/eq/item.php?id=18021>Jusean's Report Request</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18026>The Thornless Rose</a><li><a href=http://phobos/eq/item.php?id=18023>Behroe's Report</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=192>League of Antonican Bards</a><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=273>Ring of Scale</a><li><a href=http://phobos/eq/faction.php?id=207>Mayong Mistmoore</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Behroe Dlexon says </b>'Ah, greetings, [Your Name]!  How are you this evening?  Hopefully, you are faring much better than I..  I'm stuck on the night watch here, and never get to see my lovely [Aenia].  Ah..  she is so sweet..  I wrote her this beautiful [ballad], but I fear she may never hear it.'
<p><b>You say, </b>'aenia'
<br><b>Behroe Dlexon says </b>'Aenia lives in North Qeynos in a little blue house near the Temple of Life with her overprotective father.  Last time he caught me there, he nearly killed me!'
<p><b>You say, </b>'ballad'
<br><b>Behroe Dlexon says </b>'I wrote this little song for my dearest Aenia, but I can't sing it to her because I'm stuck here on watch duty.  You have a nice voice, [Your Name], maybe you could go and sing my song to her for me, huh?  Just make sure you don't sing to Aenia when her father's around, 'cause like I said, he's already tried to kill me for seeing her.'
<br><b>Behroe Dlexon gives you : </b><a href=http://phobos/eq/item.php?id=18026>The Thornless Rose</a>
<p><b>You give Behroe Dlexon : </b><a href=http://phobos/eq/item.php?id=18027>Letter to Behroe</a>
<br><b>Behroe Dlexon says </b>'Ah, thank you, kind [Your Name].  You've made two foolish lovebirds very happy.  Please, take this..  Though it is not much, it will help keep you warm on those chilly Karana nights.  It is very good to have a friend such as yourself, and I will one day repay you for your kindness and generosity.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=192>League of Antonican Bards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=273>Ring of Scale</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=207>Mayong Mistmoore</a> has gotten worse.</font>
<p><b>You give Behroe Dlexon : </b><a href=http://phobos/eq/item.php?id=18021>Jusean's Report Request</a>
<br><font color=green><b>Behroe Dlexon </b>yawns and says, 'Oh, report time already again?  Yeah, here ya go, [Your Name].  Be careful around here at night, I've been seeing some rough looking characters lurking about.'</font>
<br><b>Behroe Dlexon gives you : </b><a href=http://phobos/eq/item.php?id=18023>Behroe's Report</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=192>League of Antonican Bards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=273>Ring of Scale</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=207>Mayong Mistmoore</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>