<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18717>A tattered note</a><li><a href=http://phobos/eq/item.php?id=20374>Ripped Qeynos Bards Guild Flyer</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13502>Brown Tunic*</a><li><a href=http://phobos/eq/item.php?id=20373>Letter of Introduction</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Belious Naliedin says </b>'Welcome, my name is Belious Naliedin of the League of Antonican Bards. A few years ago, I had finally saved up the money, and I bought this place. I settled in, and have been [working] here ever since.'
<p><b>You say, </b>'working'
<br><b>Belious Naliedin says </b>'Ah, this is my shop. I am a musician, well known for my ability both in tuning, and [building instruments.]'
<p><b>You say, </b>'building'
<br><b>Belious Naliedin says </b>'Young bards are often not the wealthiest people in Norrath, and oftentimes, they have nothing to accompany their beautiful voices when they sing. If young bards are able to locate, and bring to me the [various parts] to assemble a lute with, I provide the labor for free.'
<p><b>You say, </b>'parts'
<br><b>Belious Naliedin says </b>'If you are able to find an unfinished lute body, an unfinished lute neck, a box of lute strings, and a set of fine lute tuners I will be able to craft for you one of the best sounding lutes that you have ever heard in your young life, and it will be yours, free of charge. It has long been my desire to help out any young men and women who wish to explore the bardic arts.'
<p><b>You say, </b>'i seek a famous bard'
<br><b>Belious Naliedin says </b>'A famous bard, you say? Why you must be seeking none other than the great Baenar Swiftsong! He is not here as you can see. Mayhap you seek an audience with him? He is a busy man and has not the time to speak with everyone who wishes to preoccupy his time with useless prattle! You are many and he is but one! Leave him be, I beg of you, to continue his songwriting in peace.'
<p><b>You say, </b>'i seek an audience with him'
<br><b>Belious Naliedin says </b>'Ah! In order to gain an audience with him, you must have a letter of introduction from me, otherwise he will not give you the time of day.'
<br><font color=green><b>Belious Naliedin </b>laughs briefly.</font>
<p><b>You say, </b>'give me a letter of introduction'
<br><font color=green><b>Belious Naliedin </b>looks around.</font>
<br><b>Belious Naliedin says </b>'Well, you want a letter of introduction, eh? I think that fifty shiny platinum pieces sounds like a good introduction to me, my friend.'
<p><b>You give Belious Naliedin : </b><a href=http://phobos/eq/item.php?id=18717>A tattered note</a>
<br><b>Belious Naliedin says </b>'Good day friend, and welcome to the Wind Spirit's Song. Thank you for joining our cause. Go speak with Jusean Evanesque; I'm sure you'll fit in well.'
<br><b>Belious Naliedin gives you : </b><a href=http://phobos/eq/item.php?id=13502>Brown Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Belious Naliedin : </b><a href=http://phobos/eq/item.php?id=20374>Ripped Qeynos Bards Guild Flyer</a>
<br><b>Belious Naliedin says </b>'A famous bard, you say? Why you must be seeking none other than the great Baenar Swiftsong! He is not here as you can see. Mayhap you seek an audience with him? He is a busy man and has not the time to speak with everyone who wishes to preoccupy his time with useless prattle! You are many and he is but one! Leave him be, I beg of you, to continue his songwriting in peace.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Belious Naliedin says </b>'Ah! Here is that letter of introduction I was looking for! Baenar likes to frequent a serene fountain in the southern Karanas. He finds the peace there accommodating to his work. He may even sing a tale for you if the mood strikes him.'
<br><b>Belious Naliedin gives you : </b><a href=http://phobos/eq/item.php?id=20373>Letter of Introduction</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>