<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Brin Stolunger says </b>'What?  What?!!  Are we a [young steel warrior]..  Or another [spectator] for the Arena?'
<p><b>You say, </b>'i am a young steel warrior'
<br><b>Brin Stolunger says </b>'The Steel Warriors have no cause to dislike you, but you have yet to truly prove your worth to this guild.'
<p><b>You say, </b>'i am a spectator'
<br><b>Brin Stolunger says </b>'As I thought!!  You shall be better off upon the ramparts of the arena.  It would be dreadful to see a fine citizen injured in the arena.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>