<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13114>Lisera Lute</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Cassius Messus says </b>'Hail!  What do think of [Lisera]?  She aint' much to look at, but soon she will be singing again.'
<p><b>You say, </b>'who is lisera'
<br><b>Cassius Messus says </b>'Lisera is my lute.  She sounds horrible.  I need to get her tuned by a master tuner, but the League's Master Tuner is in the Plains of Karana for a while.  If only..  hey!!  You look like a fellow bard...  You [interested in the job]?'
<p><b>You say, </b>'i am interested in the job'
<br><b>Cassius Messus says </b>'Great!!  Here.  Take Lisera to Vhalen Nostrolo.  He is in the plains near the well, composing.  He must tune it for me.  Be very careful! Lisera is all I've got.  If you complete this task and return with good news. I shall be glad to pass along an extra songsheet for a tune entitled 'Hymn of Restoration.''
<br><b>Cassius Messus gives you : </b><a href=http://phobos/eq/item.php?id=13114>Lisera Lute</a>
</td></tr></table>