<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12100>Bandit Sash</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=4206>Splinted Bronze Cloak</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=183>Knights of Thunder</a><li><a href=http://phobos/eq/faction.php?id=257>Priests of Life</a><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=21>Bloodsabers</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Chesgard Sydwen says </b>'May Karana guide your strengths.  Are you a [citizen of Qeynos] or a visitor?'
<p><b>You say, </b>'citizen of Qeynos'
<br><b>Chesgard Sydwen says </b>'Then I would urge you to attend daily services in the Temple of Thunder.  You are a [member of Thunder] are you not?  Or maybe I am mistaken and you are just [lost].'
<p><b>You say, </b>'lost'
<br><b>Chesgard Sydwen says </b>'Then study and spread the words of Karana the Rainkeeper.  May all the storms in your heart be controlled by the Rainkeeper.  You are young to the world just as [Cheslin] is.'
<p><b>You say, </b>'member of Thunder'
<br><b>Chesgard Sydwen says </b>'Well, friend, the Temple of Thunder has recognized and appreciates your past deeds for us.  But this matter is of vital importance to us and we need more proof of your devotion to our cause.'
<p><b>You say, </b>'karana bandit'
<br><b>Chesgard Sydwen says </b>'In the Plains of Karana can be found the [Karana Bandits].  They plague our followers and dare to use the name of the Rainkeeper as title.  For this, Karana commands their deaths.  I have a bounty for every returned Bandit Sash, collectible by members only.  For clerics, Gehna has a bounty on Binder Spectacles.'
<p><b>You say, </b>'Cheslin'
<br><b>Chesgard Sydwen says </b>'My son, Cheslin, is currently in training to be a Qeynos Guard.  I fear it was not his calling.  He is not quite in our realm of reality.  He spent too many years of playing games of warriors and dragons.  He will be doing his first patrols in Qeynos Hills this week.  If you are near there, I would appreciate it if you would watch and see him safely through his first patrols.  Tell him I sent you.'
<p><b>You give Chesgard Sydwen : </b><a href=http://phobos/eq/item.php?id=12100>Bandit Sash</a>
<br><b>Chesgard Sydwen says </b>'Good work  .  The Karana Bandits have been plaguing the Rainkeepers flock for some time.  Take this as a small reward for your devotion.  Continue the fight against the Karana Bandits.  Ahh... I wish [Cheslin] was equally as skilled.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Chesgard Sydwen gives you : </b><a href=http://phobos/eq/item.php?id=4206>Splinted Bronze Cloak</a>
<br><b>You receive </b> 1gp 12sp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=183>Knights of Thunder</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=21>Bloodsabers</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=257>Priests of Life</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>