<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13713>A Small Tattered Dress</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10018>Hematite</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=36>Citizens of Qeynos</a><li><a href=http://phobos/eq/faction.php?id=9>Antonius Bayle</a><li><a href=http://phobos/eq/faction.php?id=217>Merchants of Qeynos</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a><li><a href=http://phobos/eq/faction.php?id=33>Circle of Unseen Hands</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Endric says </b>'Hail, [Your Name]. My name is Endric and my task is to clean the [aqueducts] of Qeynos, although I don't relish the job.'
<p><b>You say, </b>'what aqueducts'
<br><b>Endric says </b>'Aye, the aqueducts are a horrible place. I have heard rumors of horrible [beasts] who live under the city in the water and just the other day, a child playing in the water just up and disappeared!'
<p><b>You say, </b>'what beasts'
<br><b>Endric says </b>'I know nothing of what or where they may be, just rumors, friend. However, should you foolishly choose to enter the waters to brave the possibilities and return with some evidence of the [child's] fate, I would be most appreciative.'
<p><b>You say, </b>'what child'
<br><b>Endric says </b>'The daughter of one of our own guardsmen is missing. He has offered me a reward for any information about her disappearance. So, if you find out anything, let me know and I will cut you in on the reward.'
<p><b>You give Endric : </b><a href=http://phobos/eq/item.php?id=13713>A Small Tattered Dress</a>
<br><b>Endric says </b>'Yes,  I do believe this was the child's dress. Here, take this as your share of the reward. Her father will be heartbroken..'
<br><b>Endric gives you : </b><a href=http://phobos/eq/item.php?id=10018>Hematite</a>
<br><b>You receive </b> 4sp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=36>Citizens of Qeynos</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=9>Antonius Bayle</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=33>Circle of Unseen Hands</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=217>Merchants of Qeynos</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>