<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Eve Marsinger says </b>'Hail, [Your Name] - Are you [interested] in helping the League of Antonican Bards by delivering some [mail]?'
<p><b>You say, </b>'i am interested'
<br><b>Eve Marsinger says </b>'I have messages that need to go to - well, right now I have one that needs to go to Highpass.  Will you [deliver] mail to [Highpass] for me?'
<p><b>You say, </b>'i want to deliver to highpass'
<br><b>Eve Marsinger says </b>'Take this pouch to Lislia Goldtune in Highpass.  You can find her at the entrance to HighKeep.  I am sure she will compensate you for your troubles.'
<p><b>You say, </b>'what mail'
<br><b>Eve Marsinger says </b>'The League of Antonican Bards has a courier system made up of travelers, adventurers and [agents].  We pay good gold to anyone who will take messages from bards such as myself to one of our more distant offices.  Are you [interested]?'
</td></tr></table>