<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13071>Rat Whiskers</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a><li><a href=http://phobos/eq/faction.php?id=9>Antonius Bayle</a><li><a href=http://phobos/eq/faction.php?id=217>Merchants of Qeynos</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a><li><a href=http://phobos/eq/faction.php?id=33>Circle of Unseen Hands</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Exterminator Rasmon says </b>'Hello, [Your Name]. Have you seen these pesky rodents? They are everywhere, and I simply cannot stand them! If you are willing to do a little cleaning up of the pests here, I will reward you for every four rat whiskers you bring me.'
<p><b>You give Exterminator Rasmon : </b><a href=http://phobos/eq/item.php?id=13071>Rat Whiskers</a> x4
<br><b>Exterminator Rasmon says </b>'I am very impressed, [Your Name]! A few more cleaners like yourself and we could have a rodent-free Qeynos in no time!'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=9>Antonius Bayle</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=217>Merchants of Qeynos</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=33>Circle of Unseen Hands</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 1gp 1sp 1cp
</td></tr></table>