<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13702>Wooden Fishing Tackle</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13129>Hurrieta's Tunic</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a><li><a href=http://phobos/eq/faction.php?id=9>Antonius Bayle</a><li><a href=http://phobos/eq/faction.php?id=217>Merchants of Qeynos</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a><li><a href=http://phobos/eq/faction.php?id=33>Circle of Unseen Hands</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Faren says </b>'Oh.. Hiya, I'm just out here fishing, since I can't find a job. I hope this [bait] I just bought catches me a big ol' fish.'
<p><b>You say, </b>'what bait'
<br><b>Faren says </b>'I use Captain Rohand's Secret Recipe Super Magic Catch-A-Lot brand bait. I bought my pole from Sneed's up by the north pond.'
<p><b>You say, </b>'tacklebox'
<br><b>Faren says </b>'Oh. That mean [dwarf], Trumpy, just knocked my tacklebox into the water. Could you please get it for me? I can't swim.'
<p><b>You say, </b>'fishboy'
<br><b>Faren says </b>'Hey! My [tacklebox]! You rotten dwarf!'
<p><b>You say, </b>'dwarf'
<br><b>Faren says </b>'Yes, that Trumpy is a dwarf, and a mean one too. I think he got kicked out of Kaladim and came here. Avoid him if you can.'
<p><b>You give Faren : </b><a href=http://phobos/eq/item.php?id=13702>Wooden Fishing Tackle</a>
<br><b>Faren says </b>'Thank you so much!  If you want some free advice, steer clear of those [Irontoes]! They are nothing but trouble. Here, It's not much but I must thank you somehow.'
<br><b>Faren gives you : </b><a href=http://phobos/eq/item.php?id=13129>Hurrieta's Tunic</a>
<br><b>You receive </b> 9cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=9>Antonius Bayle</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=33>Circle of Unseen Hands</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=217>Merchants of Qeynos</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>