<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18718>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13508>Blue Training Robe*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Gahlith Wrannstad says </b>'Hello.'
<p><b>You give Gahlith Wrannstad : </b><a href=http://phobos/eq/item.php?id=18718>A tattered note</a>
<br><b>Gahlith Wrannstad says </b>'Greetings, I am Gahlith, Master of the Wizard's Order of the Hall of Sorcery. Here, we have devoted our lives and souls to the study of the arcane. My apprentice Kazlo Naedra shall tutor you and teach you the foundations and fundamentals of sorcery.'
<br><b>Gahlith Wrannstad gives you : </b><a href=http://phobos/eq/item.php?id=13508>Blue Training Robe*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>