<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12101>A Spectacle</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12103>A Full Chalice</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a><li><a href=http://phobos/eq/faction.php?id=183>Knights of Thunder</a><li><a href=http://phobos/eq/faction.php?id=257>Priests of Life</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=21>Bloodsabers</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Gehna Solbenya says </b>'Greetings and blessings to you, [Your Name]. Karana offers you his protection and guidance. All who accept the offer shall find safe haven within our Temple of Thunder, If you are a cleric of Karana, you must have a [desire to serve Karana]'s flock.'
<p><b>You say, </b>'desire to serve karana'
<br><b>Gehna Solbenya says </b>'If you are a young acolyte, you may [deliver blessings to the flock] and if you are a skilled cleric, we need you to [hunt bandit binders].'
<p><b>You say, </b>'deliver blessings to the flock'
<br><b>Gehna Solbenya says </b>'Then go to the Plains of Karana. It is there that the blessings are needed. Ask every resident of the plains if they are followers of Karana. If they are, then ask them if they [require Karana's blessings]. Let them drink from this temple chalice. Return the empty chalice to me and you shall never go thirsty again.'
<br><b>Gehna Solbenya gives you : </b><a href=http://phobos/eq/item.php?id=12103>A Full Chalice</a>
<p><b>You say, </b>'hunt bandit binders'
<br><b>Gehna Solbenya says </b>'Go to the Plains of Karana and seek out the Karana Bandits. Among them can be found their bandit binders. They are healers of sorts. Which evil deity granted them this power is unknown to us. Each carries a binder spectacle. I shall reward clerics for  every two returned spectacles.  Perhaps a new power may even be bestowed.'
<p><b>You give Gehna Solbenya : </b><a href=http://phobos/eq/item.php?id=12101>A Spectacle</a>
<br><b>Gehna Solbenya says </b>'The bounty will not be paid until two spectacles are received.'
<p><b>You give Gehna Solbenya : </b><a href=http://phobos/eq/item.php?id=12101>A Spectacle</a> x2
<br><b>Gehna Solbenya says </b>'Excellent work. These foul men have no right to be proficient in the ways of healing. Here then is your bounty. Use it in your continued war against the Karana bandits.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=183>Knights of Thunder</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=257>Priests of Life</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=21>Bloodsabers</a> has gotten worse.</font>
<br><b>You receive </b> 5pp 5gp
</td></tr></table>