<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Ginleen Harltop says </b>'Hail!  Keep all combat to the center of the ring. So says [Ebon Strongbear].'
<p><b>You say, </b>'who is ebon strongbear'
<br><b>Ginleen Harltop says </b>'Ebon Strongbear is the current champion of the Steel Warriors. As champion, he rules over the Steel Warriors.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>