<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Grahan Rothkar says </b>'Hail, [Your Name]! What business do you have in the pens of the Qeynos Arena? Have you a report of the [escaped catman]?'
<p><b>You say, </b>'what escaped catman'
<br><b>Grahan Rothkar says </b>'We had a catman imprisoned here for use in future gladiator battles. He escaped. In the process, he bit off my assistant's hand which held the key to pen number seven. I now seek to hire a warrior to [retrieve key seven].'
<p><b>You say, </b>'i want to retrieve key seven'
<br><b>Grahan Rothkar says </b>'The Steel Warriors have no cause to dislike you, but you have yet to truly prove your worth to this guild.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>