<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Hansl Bigroon says </b>'Greetings, [Your Name]!  Are you a [citizen of Qeynos] or are you a [traveler of sorts]?'
<p><b>You say, </b>'i am a citizen of qeynos'
<br><b>Hansl Bigroon says </b>'Then you are aware of how few ships come and go to the continent of Erudin. The port authority is even planning to tax all passage aboard the ships. You will be happy to know that a few other engineers and I are designing a [titanic bridge].'
<p><b>You say, </b>'what titanic bridge'
<br><b>Hansl Bigroon says </b>'My grand plan has always been to erect a bridge which would span the distance between Qeynos and Odus. It would bypass the city of Erudin. Antonius Bayle would take full control of the bridge and its adjacent territories. This has had some opposition in Erudin, but for the most part, they just believe it is impossible to build such a bridge.'
</td></tr></table>