<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Joffrey Clay says </b>'Greetings, friend. My name is Joffrey. I'm trying to learn to play the [flute].  I'm also working on a new song I learned while I was visiting [Kelethin].'
<p><b>You say, </b>'what kelethin'
<br><b>Joffrey Clay says </b>'I just got back from a trip to Faydwer. I was over there studying the lore of Tunare, in the beautiful elven city of Kelethin. I highly recommend visiting there as soon as you get a chance.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>