<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=59023>A faded songbook</a><li><a href=http://phobos/eq/item.php?id=59042>A stained parchment</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=59024>A transcribed songbook</a><li><a href=http://phobos/eq/item.php?id=59001>Song: Aria of Innocence</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=192>League of Antonican Bards</a><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=273>Ring of Scale</a><li><a href=http://phobos/eq/faction.php?id=207>Mayong Mistmoore</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Jusean Evanesque </b>peers intently through several pages of the book, mumbling quietly under his breath as he does. His gaze falls on one page in particular as his eyes begin to widen as they pass over each line. He begins scribbling frantically across the pages in between the lines.</font>
<br><b>Jusean Evanesque says </b>'Take this, who ever wrote it was obviously a student of my father. The style is unmistakable. I've written some notes up for you so it should be easier to read. Take this back to Kardin and he'll teach it to you.'
<p><b>You say, </b>'Who is your father'
<br><b>Jusean Evanesque says </b>'My father Heltin disappeared while on a voyage aboard the Sea King. A group of troll pirates attacked and boarded the ship. Ginleen Harltop and the steel warriors traveling with them managed to fight them off, but took many casualties. My father was one of the bodies that was not accounted for. They found his song book floating in the water near the boat. The red water soaked through it's pages told more of the story then I ever care to know.'
<p><b>You give Jusean Evanesque : </b><a href=http://phobos/eq/item.php?id=59023>A faded songbook</a>
<br><b>Jusean Evanesque says </b>'What an interesting find. I think I may be able to transcribe this for you. Yes... Yes. here you are! If you can locate Kardin Nillic he should be able to teach you this song.'
<br><b>Jusean Evanesque gives you : </b><a href=http://phobos/eq/item.php?id=59024>A transcribed songbook</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=192>League of Antonican Bards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=273>Ring of Scale</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=207>Mayong Mistmoore</a> has gotten worse.</font>
<p><b>You give Jusean Evanesque : </b><a href=http://phobos/eq/item.php?id=59042>A stained parchment</a>
<br><b>Jusean Evanesque says </b>'My father gave you this just before he died?! So he's been alive all these years in the mines of Brokenskull Rock. What a bitter end for such a talented minstrel. I will transcribe this song for you Katarin, but you must promise to use it to help those like my father, trapped in an unnatural insanity. I pray that you will not fall to the same fate.'
<br><b>Jusean Evanesque gives you : </b><a href=http://phobos/eq/item.php?id=59001>Song: Aria of Innocence</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=192>League of Antonican Bards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=273>Ring of Scale</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=207>Mayong Mistmoore</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>