<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Kazlo Naedra says </b>'Hail, [Your Name]..  I'm Kazlo Naedra of the Order of Three.  We always seem to be running out of [supplies] around here, which is, of course, very distracting to our studies.'
<p><b>You say, </b>'what supplies'
<br><b>Kazlo Naedra says </b>'The Order of Three has been monitoring your recent activities, and we are appalled by you and your actions! Now, begone!'
</td></tr></table>