<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18719>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13508>Blue Training Robe*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Kinloc Flamepaw says </b>'Hello.'
<p><b>You give Kinloc Flamepaw : </b><a href=http://phobos/eq/item.php?id=18719>A tattered note</a>
<br><b>Kinloc Flamepaw says </b>'Welcome to the Order of Three. I am Kinloc, Guild Master of the Magicians. This tunic of the Order is for you, wear it with honour. Study hard and master your skills, and you will become an important part of our Order. Yestura shall help introduce you to the ways of magic.'
<br><b>Kinloc Flamepaw gives you : </b><a href=http://phobos/eq/item.php?id=13508>Blue Training Robe*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>