<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10070>Moonstone</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13107>Black Burrow Stout</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a><li><a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>McNeal Jocub says </b>'Good ta see ya! Now start showin' these poodlewalkers how a real fish drinks!'
<p><b>You say, </b>'what are you running low on'
<br><b>McNeal Jocub says </b>'This is going to sound crazy, but my main supplier of [Blackburrow Stout] is one of the brewers themselves. I have run too low on the fine brew and need someone to [pick up my shipment].'
<p><b>You say, </b>'what blackburrow stout'
<br><b>McNeal Jocub says </b>'Keep it down!! So you've heard of Blackburrow Stout? We sell it here in Fish's Backroom. If the Qeynos Guards knew, well.. it wouldn't be such a good thing. The stout is illegal, It's made by the gnolls. It is one of the finest brews you will ever taste. If you want any.. slide me a [moonstone].'
<p><b>You say, </b>'what moonstone'
<br><b>McNeal Jocub says </b>'Looking for moonstones, are we? The only way I know of getting a moonstone is to hunt gnolls for Captain Tillin of the Qeynos Guards.'
<p><b>You give McNeal Jocub : </b><a href=http://phobos/eq/item.php?id=10070>Moonstone</a>
<br><b>McNeal Jocub says </b>'Here you go then. Don't go tellin' no Guards where that came from,  I would hate to rid myself of a good paying customer.'
<br><b>McNeal Jocub gives you : </b><a href=http://phobos/eq/item.php?id=13107>Black Burrow Stout</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<p><b>You give McNeal Jocub : </b><a href=http://phobos/eq/item.php?id=10070>Moonstone</a> (x4)
<br><b>McNeal Jocub says </b>'Here you go then. Don't go tellin' no Guards where that came from, I would hate to rid myself of a good paying customer.'
<br><b>McNeal Jocub gives you : </b><a href=http://phobos/eq/item.php?id=13107>Black Burrow Stout</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<p><b>You give McNeal Jocub : </b><a href=http://phobos/eq/item.php?id=10070>Moonstone</a> (x3)
<br><b>McNeal Jocub says </b>'Here you go then. Don't go tellin' no Guards where that came from, I would hate to rid myself of a good paying customer.'
<br><b>McNeal Jocub gives you : </b><a href=http://phobos/eq/item.php?id=13107>Black Burrow Stout</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
</td></tr></table>