<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18720>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13508>Blue Training Robe*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Mespha Tevalian says </b>'Hello.'
<p><b>You give Mespha Tevalian : </b><a href=http://phobos/eq/item.php?id=18720>A tattered note</a>
<br><b>Mespha Tevalian says </b>'Greetings [Your Name]. Welcome to the Hall of Sorcery. You have much to learn. Wear this tunic and represent us well. See my apprentice, Unsar Koldhagon, he will get you started and help you with your studies.'
<br><b>Mespha Tevalian gives you : </b><a href=http://phobos/eq/item.php?id=13508>Blue Training Robe*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>