<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18012>Claim Check</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13864>Wooden Statue</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=218>Merchants of Rivervale</a><li><a href=http://phobos/eq/faction.php?id=9>Antonius Bayle</a><li><a href=http://phobos/eq/faction.php?id=47>Coalition of Trade Folk</a><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=33>Circle of Unseen Hands</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Nesiff Tallaherd says </b>'Greetings, [Your Name]!  Nesiff Tallaherd, owner and operator of Nesiff's Wooden Weapons, at your service.  I am the finest woodworker in all of Qeynos.  Even the Qeynos Guard uses my arrows, thanks to [Guard Weleth].'
<p><b>You say, </b>'guard weleth'
<br><b>Nesiff Tallaherd says </b>'Guard Weleth is like a son to me.  He is responsible for purchasing supplies for the Qeynos Guard.  He buys arrows from me.  He is usually stationed near the North Gate.'
<p><b>You give Nesiff Tallaherd : </b><a href=http://phobos/eq/item.php?id=18012>Claim Check</a>
<br><b>Nesiff Tallaherd says </b>'Oh.  Vesteri sent you?  Here you go.  I hope Te'Anara likes it.'
<br><b>Nesiff Tallaherd gives you : </b><a href=http://phobos/eq/item.php?id=13864>Wooden Statue</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=218>Merchants of Rivervale</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=33>Circle of Unseen Hands</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=9>Antonius Bayle</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=47>Coalition of Trade Folk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>