<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18715>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13505>Old Gray Tunic*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Renic Losaren says </b>'Welcome, [Your Name] .  Please feel at ease here in the Temple of Thunder.  We, the Knights of Thunder, are here to guide and serve.'
<p><b>You give Renic Losaren : </b><a href=http://phobos/eq/item.php?id=18715>A tattered note</a>
<br><b>Renic Losaren says </b>'Thanks.'
<br><b>Renic Losaren gives you : </b><a href=http://phobos/eq/item.php?id=13505>Old Gray Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>