<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18710>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13505>Old Gray Tunic*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Runethar Hamest says </b>'Welcome to the Temple of Thunder. We are home to paladins and clerics who follow the ways of Karana. Do you [need guidance] or are you [already a follower of Karana]?'
<p><b>You give Runethar Hamest : </b><a href=http://phobos/eq/item.php?id=18710>A tattered note</a>
<br><b>Runethar Hamest says </b>'Thanks.'
<br><b>Runethar Hamest gives you : </b><a href=http://phobos/eq/item.php?id=13505>Old Gray Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>