<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Tabure Ahendle says </b>'What have we here?  Perhaps a future Ebon Strongbear?  A [member of the Steel Warriors]?  If the way of the warrior is not to your liking, might I suggest joining the League of Antonican Bards?  The only damage you might take there is a sore throat! HAHAHA!'
<p><b>You say, </b>'i am a member of the steel warriors'
<br><b>Tabure Ahendle says </b>'The Steel Warriors have no cause to dislike you, but you have yet to truly prove your worth to this guild.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>