<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13129>Hurrieta's Tunic</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13134>Hurrieta's Bloody Dress</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a><li><a href=http://phobos/eq/faction.php?id=33>Circle of Unseen Hands</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a><li><a href=http://phobos/eq/faction.php?id=9>Antonius Bayle</a><li><a href=http://phobos/eq/faction.php?id=217>Merchants of Qeynos</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Ton Firepride says </b>'Greetings, adventurer!  A mighty warrior such as yourself deserves only the finest in armor and we here at Firepride's were trained by the finest dwarven smiths.  We shall be branching out and crafting [other items] soon, also.'
<p><b>You say, </b>'other items'
<br><b>Ton Firepride says </b>'Ah, such interest! We have yet to finalise our inventory before we branch out - check back with us later.'
<p><b>You give Ton Firepride : </b><a href=http://phobos/eq/item.php?id=13129>Hurrieta's Tunic</a>
<br><b>Ton Firepride says </b>'Ha! This is great. Here's your money, murderer! Hope the guards don't find you. Now get lost! Take the tunic. Maybe Garuc will reward you for such a vile deed. I sure don't want to keep it around here.'
<br><b>Ton Firepride gives you : </b><a href=http://phobos/eq/item.php?id=13134>Hurrieta's Bloody Dress</a>
<br><b>You receive </b> 1sp 5cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=9>Antonius Bayle</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=33>Circle of Unseen Hands</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=217>Merchants of Qeynos</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>