<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18150>A Bardic Letter (Qeynos)</a><li><a href=http://phobos/eq/item.php?id=18151>A Bardic Letter (Qeynos)</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=192>League of Antonican Bards</a><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=273>Ring of Scale</a><li><a href=http://phobos/eq/faction.php?id=207>Mayong Mistmoore</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Tralyn Marsinger says </b>'Hail, [Your Name] - If you are interested in helping the League of Antonican Bards by delivering some mail then you should talk to my wife, Eve.'
<p><b>You give Tralyn Marsinger : </b><a href=http://phobos/eq/item.php?id=18150>A Bardic Letter (Qeynos)</a>, <a href=http://phobos/eq/item.php?id=18151>A Bardic Letter (Qeynos)</a>
<br><b>Tralyn Marsinger says </b>'Incoming mail - very good!  Please take this gold for your troubles.'
<br><b>You receive </b> 3gp
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=192>League of Antonican Bards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=273>Ring of Scale</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=207>Mayong Mistmoore</a> has gotten worse.</font>
<br><b>Tralyn Marsinger says </b>'Incoming mail - very good!  Please take this gold for your troubles.'
<br><b>You receive </b> 3gp
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=192>League of Antonican Bards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=273>Ring of Scale</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=207>Mayong Mistmoore</a> has gotten worse.</font>
</td></tr></table>