<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13033>Honey Mead</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=10108></a><li><a href=http://phobos/eq/faction.php?id=10102></a><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a><li><a href=http://phobos/eq/faction.php?id=10101></a></ul></td><td><hr><b>When Trumpy Irontoe spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Trumpy Irontoe says </b>'Heh?  What's yer name?  [Your Name]?  Never heard of ya.  Now quit breathin' on me and buy us some [drinks]!'
<p><b>You say, </b>'what drinks'
<br><b>Trumpy Irontoe says </b>'<BURP!>  Yeah.  Gimme a..  <BURP!> er..  honey mead.'
<p><b>You say, </b>'Who is Skippy'
<br><b>Trumpy Irontoe says </b>'Skippy? You mean that fish farmer? Heh heh heh. What a moron. And his brother [Beren] has the nerve to actually threaten ME!?.. Burp.. Bah. Remind me to tell [Kane] about that steaming pile of gnoll dung.'
<p><b>You say, </b>'Who is Beren'
<br><b>Trumpy Irontoe says </b>'Don't even mention that weakling's name. He.. burp.. Keeps threatening me. ME! Trumpy IRONTOE!!! Peh! That useless son of a goblin had better wise up and realize that in this burg if you ain't with [Kane], you are against him. And if you are against him.. burp.. you ain't nothing but a corpse.'
<p><b>You say, </b>'Who is kane'
<br><b>Trumpy Irontoe says </b>'Ah.. burp.. that piece of cr.. eh? Oh its you.. Kane runs this burg.. or at least he will.. if [Sragg] can get his act together.'
<p><b>You say, </b>'Sragg'
<br><b>Trumpy Irontoe says </b>'Where did you hear that name?!? Not from me! I didn't say nothing about Sragg or those Bloodsabers or their dang temple in the sewers! Get away from me ya hobgoblins! I don't wants no trouble!'
<p><b>You give Trumpy Irontoe : </b><a href=http://phobos/eq/item.php?id=13033>Honey Mead</a> (x4)
<br><b>Trumpy Irontoe says </b>'Beh!  Thanks, Skippy.  Why don't ya buy yourself one?  And..  <GULP>.. <BURP!>.. get me another!'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10108></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10102></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10101></a> has gotten worse.</font>
</td></tr></table>