<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Wolten Grafe says </b>'Hail, noble [Your Name]. Remember to spread the words of Karana throughout the faraway lands on which you shall tread. We of the Temple of Thunder are looking for new members - good people who [wish to join our cause]. Let the call go out!'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>