<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Yakem Oreslinger says </b>'Greetings friend [Your Name]! I am a provider of the highest quality steel ore known to Norrath! This ore is in such demand that I often run low and find it difficult to restock my supplies. If you're [looking for a job] I will gladly pay you for some of your time.'
<p><b>You say, </b>'i am looking for a job'
<br><b>Yakem Oreslinger says </b>'I need you to take this crate and fill it with either Small Bricks of Unrefined Ore or Large Bricks of Unrefined Ore then return it to me so that I may refine it and sell it. The unrefined ore that I require is often mined by the goblins in the ruins of Permafrost Keep.'
</td></tr></table>