<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>a grol baku seer says </b>'Gobu gobu. bakula erila [shamu eku]?'
<br><b>a grol baku seer says </b>'Weeee Weeee! Shamiku! Weeee!'
<br><b>a grol baku seer says </b>'Gobu gobu. bakula erila [shamu eku]?'
<p><b>You say, </b>'what shamu eku?'
<br><b>a grol baku seer says </b>'Weeee Weeee! Shamiku! Weeee!'
</td></tr></table>