<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1685>Breath of Gwan</a></ul></td><td><hr><b>When a sleeping ogre spawns </b>
<p><b>You say, </b>'hail'
<br><font color=green><b>a sleeping ogre </b>yawns, and utters some gibberish, then falls back asleep.</font>
<p><b>You give a sleeping ogre : </b><a href=http://phobos/eq/item.php?id=1685>Breath of Gwan</a>
<br><b>a sleeping ogre says </b>'Your path of wanton destruction ends here, [Your Name]. Gwan and Eejag were impatient and hot-headed. You will not defeat me, for I have the patience and perseverance of stone, unlike the children you have beaten before me.'
<br><b>a sleeping ogre disappears.</b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=107161>Trunt</a></b> spawns.</font>
</td></tr></table>