<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=6349>Ajrah Leaf</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1120>Erudehide Tunic</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Allix says </b>'Rrraaarrr! Hello furless. You come to study from [mighty warrior] yes?'
<p><b>You say, </b>'mighty warrior'
<br><b>Allix says </b>'Errr. Well, Allix not yet mighty warrior but soon yes. Allix just come of age and soon will enter training to become mighty Pasdar. Errr. Allix little nervous. Allix missing [one thing] to become mighty Pasdar.'
<p><b>You say, </b>'one thing'
<br><b>Allix says </b>'Well, Allix not have to have but is good. Is leaf. Ajrah leaf. Powerful magic in the leaf. Pasdar hold's next to body, keep's body strong and mind clear. Not have to have but Pasdar without Ajrah Leaf is poor Pasdar. Someday Allix travel to the mighty plain's of East Karana and get one from tree's.'
<p><b>You give Allix : </b><a href=http://phobos/eq/item.php?id=6349>Ajrah Leaf</a>
<br><b>Allix says </b>'Ajrah! Raaarrr! Ajrah Leaf! Allix destined to be mighty saiar now! Allix unsure how to thank you. Here, take this. Is my most treasured tunic.'
<br><b>Allix gives you : </b><a href=http://phobos/eq/item.php?id=1120>Erudehide Tunic</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>