<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Errrak Thickshank says </b>'What?  What do you want. furless?  My tseq. Graalf. lies sick and you waste time with talk when you [cannot help].'
<p><b>You say, </b>'why cannot i help'
<br><b>Errrak Thickshank says </b>'The shamans. they have said I need [talismans] to ward the sickness from Graalf.'
<p><b>You say, </b>'what talismans'
<br><b>Errrak Thickshank says </b>'Errr?  You wish to help?  We will see.  I need a tiger's skin. from a tigerrr not of ourrr village. for its brave spirit. an aviaks charm. and a giant snake fang for the poison that can be made into an antidote.  If you truly intend to help. then good speed and hurry!'
</td></tr></table>