<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Feren says </b>'Rarr.  Me is Feren.  Me is fisher.  That means Feren catches [fish].'
<p><b>You say, </b>'what fish'
<br><b>Feren says </b>'All kinds of fish.  Tasty fish.  All day Feren catches the fishes so all Kerran can eat.  I do for good of all Kerran.  Rrrrr.  One thing bother Feren always though.  Is bad fish.  [Razortooth].'
<p><b>You say, </b>'what razortooth'
<br><b>Feren says </b>'Rrrrrr!  Razortooth mean fish.  Razortooth eat fish off Feren's line.  Razortooth gnaw Feren's boat.  Razortooth smart and dangerous.  Feren never able to catch Razortooth.  This haunt Feren for months.  If you was able to catch Razortooth. Feren be forever grateful. Maybe even give you possessions.'
</td></tr></table>