<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12360>Tunare's Finest</a><li><a href=http://phobos/eq/item.php?id=14914>Thunderhoof Mushroom</a><li><a href=http://phobos/eq/item.php?id=14915>Tea Leaves</a><li><a href=http://phobos/eq/item.php?id=17969>Hand Made Backpack</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17032>Rough Leather Sack</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Feskr Drinkmaker says </b>'Erh?  If you not be here to help Feskr with his [problem] then Feskr want you to leave.'
<p><b>You say, </b>'what problem'
<br><b>Feskr Drinkmaker says </b>'You wish to help?  Orrderrr of supplies I rrequest not arrive; ship sink.  Now Feskr needs supplies.  Feskr need bottle of Tunare's Finest. thunderhoof mushroom. tea leaf. and handmade backpack.  Rrrr. strange items but Feskr need to sell.  You bring. Feskr give you nice bag.'
<p><b>You give Feskr Drinkmaker : </b><a href=http://phobos/eq/item.php?id=12360>Tunare's Finest</a>, <a href=http://phobos/eq/item.php?id=14914>Thunderhoof Mushroom</a>, <a href=http://phobos/eq/item.php?id=14915>Tea Leaves</a>, <a href=http://phobos/eq/item.php?id=17969>Hand Made Backpack</a>
<br><b>Feskr Drinkmaker says </b>'Ahhh. This will help. Many Kerrans will like these. Here. Take this old bag. I have too many. Maybe it help you.'
<br><b>Feskr Drinkmaker gives you : </b><a href=http://phobos/eq/item.php?id=17032>Rough Leather Sack</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>