<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12319>Emissary Head</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10343>Kejaar Totem</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Shazda Asad says </b>'Rrrr..I am  Asad. Shazda of the Kerran [Sejah]. It is my duty to ensure the safety of what lands have not been taken from us by the Erudites. and to train my soldiers in the fighting styles of our heritage.'
<p><b>You say, </b>'what sejah'
<br><b>Shazda Asad says </b>'The soldiers of our sejah are all trained from the time they are weaned from their matriarchs. If you wish to be honored by the sejah you must prove to us your loyalty and devotion to the defense of our lands. In Toxxulia Forest there are Erudite emissaries who constantly attempt to encroach upon our territory. Bring me the head of one such emissary.'
<p><b>You give Shazda Asad : </b><a href=http://phobos/eq/item.php?id=12319>Emissary Head</a>
<br><b>Shazda Asad says </b>'Excellent work, young ayyar! You have proven your willingness to dispose of the enemies of our tribe, now you must face one of their most murderous sentries! Bring me the head of Sentinel Creot and I shall induct you into our sejah!'
<br><b>You receive </b> 6sp
<br><b>Shazda Asad gives you : </b><a href=http://phobos/eq/item.php?id=10343>Kejaar Totem</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>