<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Wislen Mamluk says </b>'Why you bother Wislen?  Wislen trying to get fishies.  Leave Wislen alone to get [fish]. please.'
<p><b>You say, </b>'what fish'
<br><b>Wislen Mamluk says </b>'Fish.  Wislen fish.  Wislen is mamluk. not just fisher.  Mamluk is warrior but they also helps provide for all Kerran.  This is hadi place in life.  We happy doing this.  Please. let Wislen fish now.'
</td></tr></table>