<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Bonlarg says </b>'Shadowknight master me be!!  [Your Name] prove to me that [Your Name] be worthy to be one with Greenblood and me give [Your Name] black shadow tunic.  You [want black shadow tunic]?'
<p><b>You say, </b>'i want black shadow tunic'
<br><b>Bonlarg says </b>'Help Greenbloods you will. Give lizard tails to Grevak.  Den maybe we trust.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>