<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10628>Large Muddy Sandals</a><li><a href=http://phobos/eq/item.php?id=10630>Gift to Bozlum</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10629>Scribbled Parchment</a><li><a href=http://phobos/eq/item.php?id=10609>Snow Blossoms</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Bozlum Blossom </b>heaves a great sigh.</font>
<p><b>You say, </b>'wrong'
<br><b>Bozlum Blossom says </b>'Boz like to grow perty flowers in her garden. But garden no more.'
<p><b>You say, </b>'garden'
<br><b>Bozlum Blossom says </b>'Boz not know what happen. Only see der biggins footprints in it. Me perty sure my puppy not smash garden. He has tiny feets. Right, puppy?'
<p><b>You give Bozlum Blossom : </b><a href=http://phobos/eq/item.php?id=10628>Large Muddy Sandals</a>
<br><font color=green><b>Bozlum Blossom </b>writes something down on a piece of parchment.</font>
<br><b>Bozlum Blossom says </b>'You go tell dat Brokk dat he owe me big for smushing garden. Make him read dis.'
<br><b>Bozlum Blossom gives you : </b><a href=http://phobos/eq/item.php?id=10629>Scribbled Parchment</a>
<p><b>You give Bozlum Blossom : </b><a href=http://phobos/eq/item.php?id=10630>Gift to Bozlum</a>
<br><b>Bozlum Blossom says </b>''Oh, dat silly Brokk. He sent me too many of these perty flowers. Me not know where put them all. Here, you take some cause you help Bozlum. Me like you. Flowers make you smell perty, too.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Bozlum Blossom gives you : </b><a href=http://phobos/eq/item.php?id=10609>Snow Blossoms</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>