<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10629>Scribbled Parchment</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10630>Gift to Bozlum</a></ul></td><td><p><b>You give Brokk Boxtripper : </b><a href=http://phobos/eq/item.php?id=10629>Scribbled Parchment</a>
<br><b>Brokk Boxtripper says </b>'Brokk sorry, me no smush Bozlum's perty garden on purpose. Me felt bad and me too shy to go tell Boz Brokk sorry. Umm....go give her these perty flowers. Dem smell good and maybe make Bozlum feel better.'
<br><b>Brokk Boxtripper gives you : </b><a href=http://phobos/eq/item.php?id=10630>Gift to Bozlum</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>