<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13384>Preserved Leg</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Chef Dooga says </b>'Welcome you. [Your Name].  You look all skin 'n bones.  Eat you must do.  Chef Dooga can fix up goodies for you.  Try [HEHE meat].'
<p><b>You say, </b>'what HEHE meat'
<br><b>Chef Dooga says </b>'It is a secret ground meat made with high elf. human and Erudite Flesh.  Mmmm.  It good stuff.  Dooga make it and [the Gobbler] make it.  If you find any of those meats in the swamps bring to me and I pay you.'
<p><b>You say, </b>'what the gobbler'
<br><b>Chef Dooga says </b>'You no hear of the Gobbler!!  Him great butcher.  Have all kinds of meat.  Him am low on froglok legs. Dooga supply him.  Dooga need someone to [deliver froglok legs].'
<p><b>You say, </b>'who is the gobbler'
<br><b>Chef Dooga says </b>'You no hear of the Gobbler!!  Him great butcher.  Have all kinds of meat.  Him am low on froglok legs. Dooga supply him.  Dooga need someone to [deliver froglok legs].'
<p><b>You say, </b>'i deliver froglok legs'
<br><b>Chef Dooga says </b>'You think so!!  That be good thing.  Make the Gobbler happy.  Maybe he give you something good.  Maybe not.  You take this.  Deliver meat.'
<br><b>Chef Dooga gives you : </b><a href=http://phobos/eq/item.php?id=13384>Preserved Leg</a>
<p><b>You say, </b>'i want to deliver froglok legs'
<br><b>Chef Dooga says </b>'You think so!!  That be good thing.  Make the Gobbler happy.  Maybe he give you something good.  Maybe not.  You take this.  Deliver meat.'
<br><b>Chef Dooga gives you : </b><a href=http://phobos/eq/item.php?id=13384>Preserved Leg</a>
</td></tr></table>