<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13740>Ogre Head</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Clurg says </b>'Hello. friend. Have a drink. I have some [unique drinks]. Try one. And remember. You get rowdy. the [Bouncers] crush you.'
<p><b>You say, </b>'what bouncers'
<br><b>Clurg says </b>'The Bouncers were organized by me. As I traveled to many of the world's taverns I encountered great enforcers called bouncers. It was their duty to keep order amongst chaos. When I returned and rose to greatness after the creation of the [Flaming Clurg]. I organized the Oggok Bouncers to keep order amongst the [rival guilds].'
<p><b>You say, </b>'what flaming clurg'
<br><b>Clurg says </b>'The Flaming Clurg was my greatest creation. It brought me great respect in Oggok. Unfortunately. I have heard tales of an [imposter drink].'
<p><b>You say, </b>'what imposter drink'
<br><b>Clurg says </b>'Bah! Dat damned Pungla! She be imitatin me drinks! I want som'on to [deal] with dat damned witch! If som'on wud jus bring me her head, I wud pay em!'
<br><b>Clurg says </b>'Find ways to help all in Oggok. Then we will have conversation.'
<p><b>You say, </b>'what rival guilds'
<br><b>Clurg says </b>'Oggok has been the battleground for the feud between the Greenblood knights and shamans and the Craknek warriors. It is fueled by the superior intellect of the Greenbloods. Few remember that I. Clurg. was once dim. but now I speak with great words.'
<p><b>You give Clurg : </b><a href=http://phobos/eq/item.php?id=13740>Ogre Head</a>
<br><b>Clurg says </b>'Ahahaha! Dat witch sur did get wat was commin ta her!'
<br><b>You receive </b> 5pp
</td></tr></table>