<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19195>Armadillo Husk</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=232>Oggok Guards</a><li><a href=http://phobos/eq/faction.php?id=233>Oggok Residents</a><li><a href=http://phobos/eq/faction.php?id=46>Clurg</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Exterminator Glurg says </b>'Hello dere. Do you see all dese darn critters running around here? Dere are little armadillos everywhere! We need to git rid of dem. If you bring me four of dere husks, I pay you money. Too many for me to smash alone.'
<p><b>You give Exterminator Glurg : </b><a href=http://phobos/eq/item.php?id=19195>Armadillo Husk</a> x4
<br><b>Exterminator Glurg says </b>'You smashed dem gud. Take dese coins!'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=232>Oggok Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=233>Oggok Residents</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=46>Clurg</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 1gp 1sp 1cp
</td></tr></table>