<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13354>Lizard Tail</a><li><a href=http://phobos/eq/item.php?id=13367>Mystic Doll</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13453>Pickled Lizard</a><li><a href=http://phobos/eq/item.php?id=5025>Rusty Two Handed Battle Axe</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=46>Clurg</a><li><a href=http://phobos/eq/faction.php?id=128>Green Blood Knights</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=292>Shadowknights of Night Keep</a><li><a href=http://phobos/eq/faction.php?id=314>Storm Guard</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Grevak says </b>'Need new members we do not. Powerful enough are we with Grevak. Still. peons needed. Are you a [new peon] or are you an [outsider]? Speak up!! Fool!! No time Grevak has!!'
<p><b>You say, </b>'i am a new peon'
<br><b>Grevak says </b>'So you think you can be greater than Grevak!! Touch you not and still I can smash you. I am a Greenblood shadowknight!! Peon are you. Peons go to swamps and slay lizardmen. You return with four lizardmen tails and a reward is yours. You return with two lizardman shaman dolls and a great reward is yours.'
<p><b>You say, </b>'i am an outsider'
<br><b>Grevak says </b>'Go away or soon your pain will find you.'
<p><b>You give Grevak : </b><a href=http://phobos/eq/item.php?id=13354>Lizard Tail</a> x4
<br><b>Grevak says </b>'Grevak rewards peon with reward instead of smashing you.  Bring me more, peon!'
<br><b>Grevak gives you : </b><a href=http://phobos/eq/item.php?id=13453>Pickled Lizard</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=46>Clurg</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=128>Green Blood Knights</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=292>Shadowknights of Night Keep</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=314>Storm Guard</a> has gotten worse.</font>
<p><b>You give Grevak : </b><a href=http://phobos/eq/item.php?id=13367>Mystic Doll</a> x2
<br><b>Grevak says </b>'Grevak rewards you. Grevak now afraid of nothing! Ha ha! Mighty mighty!'
<br><b>Grevak gives you : </b><a href=http://phobos/eq/item.php?id=5025>Rusty Two Handed Battle Axe</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=128>Green Blood Knights</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=292>Shadowknights of Night Keep</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>