<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=55206>Skull of Hermina</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=51377>Assembly Kit of War</a><li><a href=http://phobos/eq/item.php?id=51363>Helm Mold of War</a><li><a href=http://phobos/eq/item.php?id=51365>Bracer Mold of War</a><li><a href=http://phobos/eq/item.php?id=51364>Armplate Mold of War</a><li><a href=http://phobos/eq/item.php?id=51367>Boot Mold of War</a><li><a href=http://phobos/eq/item.php?id=51368>Legplate Mold of War</a><li><a href=http://phobos/eq/item.php?id=51366>Gauntlet Mold of War</a><li><a href=http://phobos/eq/item.php?id=51369>Breastplate Mold of War</a><li><a href=http://phobos/eq/item.php?id=55207>Gronk's Sword</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Gronk says </b>'Hi dere, yuz be talking to Gronk, mez know lotz bout da krafting of arnor dat protekts our yung warriors. If yuz a [warrior] come lookeeng to make sum armorz, yuz find da right Ogre.'
<p><b>You say, </b>'warrior'
<br><b>Gronk says </b>'Mez tink dat yuz were. Letz begin yur traineeng. One of da furst tingz dat yuz needz to do is gather da itemz dat will be uzed in da krafteeng of da [armor] and den yuz can kraft dem in dis majikal assembly kit.'
<br><b>Gronk gives you : </b><a href=http://phobos/eq/item.php?id=51377>Assembly Kit of War</a>
<p><b>You say, </b>'armor'
<br><b>Gronk says </b>'Da itemz you will needz to gather will be all ober da Feerrott. Dese itemz will be hard for yuz to gather, dey come from some of da meanest tings in da Feerrott. Once yuz are redy to begin, tell mez da piece dat yuz wantz to kraft and mez will give yuz da recipez dat yuz will need when making da armor. I have recipez for [Helms], [Bracers], [Sleeves], [Boots], [Legplates], [Gloves] and [Breastplate].'
<p><b>You say, </b>'helm'
<br><b>Gronk says </b>'A gud smert warrior wud not be widout his helm, oderwize yuz wud not be a smert warrior! Da recipe to kraft a helm... mez gotz it somewhere... Oh yes! To kraft da helm, yuz needz to gather a white lizard scale, one chunk of dark colored fungus, and a bone chip. Combine dese items in yur assembly kit to get da helm material. Once yuz got da material, den yuz need to use dis mold and smelt da material into da shape of a helm.'
<br><b>Gronk gives you : </b><a href=http://phobos/eq/item.php?id=51363>Helm Mold of War</a>
<p><b>You say, </b>'bracer'
<br><b>Gronk says </b>'Da bracer is da only ting dat you have sumtimz to cover yur wristz. Da wristz is bery impotent in da battle strat-a-geez dat we use in da Feerrott. If yuz want to kraft a bracer, yuz need to gather a white lizard scale, one black spider silk, and a fire beetle leg. Combine dese items in yur assembly kit to get da bracer material. Once yuz got da material, den yuz need to use dis mold and smelt da material into a bracer.'
<br><b>Gronk gives you : </b><a href=http://phobos/eq/item.php?id=51365>Bracer Mold of War</a>
<p><b>You say, </b>'sleeves'
<br><b>Gronk says </b>'Sleevez is often hard to come by if yuz an ogre, since wez have such large armz. Dunt worry mez can teech yuz how to make some sleevez yurself, and dey will protekt yur arms gud. Furst ting, yuz need to gather a white lizard scale, one chunk of multi-colored fungus, and a piece of froglok tadpole flesh. Combine dese items in yur assembly kit to get da sleeve material. Once yuz got da material, den yuz need to use dis mold and smelt da material into a set of armplatez.'
<br><b>Gronk gives you : </b><a href=http://phobos/eq/item.php?id=51364>Armplate Mold of War</a>
<p><b>You say, </b>'boots'
<br><b>Gronk says </b>'A gud warrior goes nowhere widout his boots! If a warrior dusnt have boots, den he not be able to travel bery far widout getting hurtz feetz. To kraft sum bootz, yuz need to gather a white lizard scale, one short lizard tail, and a tuft of giant bat fur. Combine dese items in yur assembly kit to get da boot material. Once yuz got da material, den yuz need to use dis mold and smelt da material into a set of bootz.'
<br><b>Gronk gives you : </b><a href=http://phobos/eq/item.php?id=51367>Boot Mold of War</a>
<p><b>You say, </b>'legplates'
<br><b>Gronk says </b>'Legplatez is prollee da most impotent armer dat yuz can get. Most of da emenies dat yuz will fight will go for da legz, widout legz, yuz become a bery easy target. Da legplates is a gud piece to have. If yuz want to kraft a legplates, yuz need to gather a white lizard scale, one brown lizard scale, and two pieces of pristine spider silk. Once yuz have dem items, yuz need to craft dem togeder in yur majikal kit to get da legplate material. When yuz got da material, yuz need to take it to da forge wit dis mold and smelt it into a gud set of legplatez.'
<br><b>Gronk gives you : </b><a href=http://phobos/eq/item.php?id=51368>Legplate Mold of War</a>
<p><b>You say, </b>'gloves'
<br><b>Gronk says </b>'A lotz can be sed about da glovez, but yuz look like a smert Ogre, I shudnt need to tell yuz about dem all. If yuz want to kraft a gloves, yuz need to gather a white lizard scale, one spiderling silk, one green lizard talon, and one black lizard talon. Once yuz have dem items, yuz need to craft dem togeder in yur majikal kit to get da glove material. When yuz got da material, yuz need to take it to da forge wit dis mold and smelt it into a gud set of glovez.'
<br><b>Gronk gives you : </b><a href=http://phobos/eq/item.php?id=51366>Gauntlet Mold of War</a>
<p><b>You say, </b>'breastplate'
<br><b>Gronk says </b>'A gud strong warrior wud not be widout his brestplate, oderwize yuz wud not be a strong warrior for long! Da recipe to kraft kraft a brestplate... Oh yes! Yuz need to gather a white lizard scale, two orange lizard scales, and one chunk of light colored fungus. Combine dese items in yur assembly kit to get da brestplate material. Once yuz got da material, den yuz need to use dis mold and smelt da material into da shape of a brestplate. After yuz maka da brestplate, mebbe me gives ya anuder [job].'
<br><b>Gronk gives you : </b><a href=http://phobos/eq/item.php?id=51369>Breastplate Mold of War</a>
<p><b>You say, </b>'job'
<br><b>Gronk says </b>'Gronk used to have girlfriend. Her name was Hermina. One day we iz sittin by da river on da big bridge. Hermina made Gronk's favorut treat, candeed lizard man brainz for da lunch. Hermina went into da water for da swim and never came back. Me looked fer her but never found her again. Gronk think dat da gaterz ate her. Huh? Me crying?! Gronk not cry! Gronk be strong! Mebbe you [help find] what happen to her?'
<p><b>You say, </b>'help find'
<br><b>Gronk says </b>'If you find anyting about her, I give you reward.'
<p><b>You give Gronk : </b><a href=http://phobos/eq/item.php?id=55206>Skull of Hermina</a>
<br><b>Gronk says </b>'What be dis??! No, my preshus Hermina!!! Why dis have to happen? Huh? No, Gronk not crying!!!! Take dis weapon for da help and leave Gronk for now.'
<br><b>Gronk gives you : </b><a href=http://phobos/eq/item.php?id=55207>Gronk's Sword</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>