<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18787>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13525>Mud Stained Skin Tunic*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Guntrik says </b>'Mmmph!!  Who you?  Oh. you [Your Name].  You supposed to be promising Craknek.  Me need you.  There bad things in swamp.  You want [help Crakneks] or you [want Guntrik bash your face]!!?'
<p><b>You say, </b>'what help crakneks'
<br><b>Guntrik says </b>'Crakneks warriors!!  They be far back.  Through last caves.  They smash and bash.  They no like Greenbloods.  Bouncers keep thems from bashing.'
<p><b>You say, </b>'i want gruntrik to bash my face'
<br><b>Guntrik says </b>'OK!! Me bash!!  You hurt!!'
<br><b>Guntrik says </b>'Me strongest. You weak. Craknek best alwayss.'
<p><b>You give Guntrik : </b><a href=http://phobos/eq/item.php?id=18787>A tattered note</a>
<br><b>Guntrik says </b>'Ahh..  good..  good..  here. take..  now you Craknek! You bash good. Bash lizards. Bash froggies. Bash mushrooms. Remember. you no help Greenbloods. Crakneks stronger than Greenbloods.'
<br><b>Guntrik gives you : </b><a href=http://phobos/eq/item.php?id=13525>Mud Stained Skin Tunic*</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>