<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Horgus says </b>'What!!? You [Craknek] or you [pest]?'
<p><b>You say, </b>'i am craknek'
<br><b>Horgus says </b>'Good. Me not bash you.  You help Horgus and Crakneks.  Go smash lizards.  Bring four tails.  Greenbloods think they get all lizard tails.  We take first.  Taste good.  You bring four tails.  Me give you tings.  Me gives armur.  Now go!!'
<p><b>You say, </b>'i am pest'
<br><b>Horgus says </b>'Bah!! You go join Greenbloods. You weak.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>