<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Kogna says </b>'You be tinking you be [real tuff Craknek]?'
<p><b>You say, </b>'i am a real tuff craknek'
<br><b>Kogna says </b>'Me not tinking so. but maybe me wrongs.. no.. me neber wrongs.  You no tuff. only liddle Craknek is you.  You tink you be tuff Craknek. you bringed me four lizard meats.  Me like lizard meats.  You no tuff.  You bringed me lizard meats.  I make you tuffer Craknek.  Me bestest Craknek.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>