<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20523>Dismembered Thumb</a><li><a href=http://phobos/eq/item.php?id=1717>Sealed Letter</a><li><a href=http://phobos/eq/item.php?id=13227>Black Heart</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=16547>A Stein</a><li><a href=http://phobos/eq/item.php?id=13355>A Crude Stein</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Lork says </b>'You [Your Name].  We hear of you.  We need help.  You [help Crakneks] or you [help self]?'
<p><b>You say, </b>'i want to help crakneks'
<br><b>Lork says </b>'Ha!!  We hear of great adventurer.  You?!!  Me no think so.  You prove self to Crakneks before you help us.  Go to Innoth.. Innotu.. Innooth.. Arghh!!  You go to outside Oggok.  Find fat alligator bit Lork brother in two.  Bring brother. Nork. body back.  Then me know you strong.'
<p><b>You say, </b>'i want to help self'
<br><b>Lork says </b>'You help self to leave Oggok before me bash you.  We no need cowards.'
<p><b>You give Lork : </b><a href=http://phobos/eq/item.php?id=20523>Dismembered Thumb</a>
<br><b>Lork says </b>'Ay danks. Take dis to Uglan.'
<br><b>Lork gives you : </b><a href=http://phobos/eq/item.php?id=16547>A Stein</a>
<p><b>You give Lork : </b><a href=http://phobos/eq/item.php?id=1717>Sealed Letter</a>
<br><b>Lork says </b>'Arg! Dem damned Orcs and Dark Elves! To da hells with dem! I be wantin revenge! Bring me da hearts of da dark elf ammbassador's K'ryn who can be locat'd in da shamen tun'ls, and D'vinn who can be located in da crushbone with da orc emperor.'
<p><b>You give Lork : </b><a href=http://phobos/eq/item.php?id=13227>Black Heart</a>
<br><b>Lork says </b>'Ahahaha! Da basterds! Here be a reward for ye!'
<br><b>Lork gives you : </b><a href=http://phobos/eq/item.php?id=13355>A Crude Stein</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>