<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=55210>Jungle Spider Poison Sac</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=51380>Assembly Kit of Darkness</a><li><a href=http://phobos/eq/item.php?id=51370>Helm Mold of Darkness</a><li><a href=http://phobos/eq/item.php?id=51372>Bracer Mold of Darkness</a><li><a href=http://phobos/eq/item.php?id=51371>Armplate Mold of Darkness</a><li><a href=http://phobos/eq/item.php?id=51374>Boot Mold of Darkness</a><li><a href=http://phobos/eq/item.php?id=51375>Legplate Mold of Darkness</a><li><a href=http://phobos/eq/item.php?id=51373>Gauntlet Mold of Darkness</a><li><a href=http://phobos/eq/item.php?id=51376>Breastplate Mold of Darkness</a><li><a href=http://phobos/eq/item.php?id=55211>Mooglan's Sword of Darkness</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Mooglan says </b>'Yuz come lookeeng to make sum armorz? Yuz come to da right place, if'n yuz be a shadowknight. Is you a [shadowknight]?'
<p><b>You say, </b>'shadowknight'
<br><b>Mooglan says </b>'Mez tink dat yuz were. Letz begin yur traineeng. Da furst ting dat yuz needz to do is gather da itemz dat will be uzed in da krafteeng of da [armor] and den yuz can kraft dem in dis majikal assembly kit.'
<br><b>Mooglan gives you : </b><a href=http://phobos/eq/item.php?id=51380>Assembly Kit of Darkness</a>
<p><b>You say, </b>'armor'
<br><b>Mooglan says </b>'Da itemz you will needz to gather will be all ober da Feerrott. Dese itemz will be hard for yuz to gather, dey come from some of da meanest tings in da Feerrott. Once yuz are redy to begin, tell mez da piece dat yuz wantz to kraft and mez will give yuz da recipez dat yuz will need when making da armor. I have recipez for [Helm], [Bracers], [Sleeves], [Boots], [Legplates], [Gloves] and [Breastplate].  Once yuz done wit da armorz, mez hab a job fer yuz, if I can [trust] yuz.'
<p><b>You say, </b>'helm'
<br><b>Mooglan says </b>'Da helm iz da most impotent piece to get, since it protekt da smertest part of da body. To kraft da helm, yuz needz to gather a pristine lizard scale, one chunk of light colored fungus, and two spider legs, and kraft dem into dis here majikal assembly kit to get yur helm material. Den yuz take dat material and dis mold to a forge and smelt dem together into a gud helm.'
<br><b>Mooglan gives you : </b><a href=http://phobos/eq/item.php?id=51370>Helm Mold of Darkness</a>
<p><b>You say, </b>'bracer'
<br><b>Mooglan says </b>'Da bracer is a gud piece to have. If yuz want to kraft a bracer, yuz need to gather a pristine lizard scale, two bone chips, and a pristine spider silk, and kraft dem into dis here majikal assembly kit to get yur bracer material. Den yuz take dat material and dis mold to a forge and smelt dem together into a gud bracer.'
<br><b>Mooglan gives you : </b><a href=http://phobos/eq/item.php?id=51372>Bracer Mold of Darkness</a>
<p><b>You say, </b>'sleeves'
<br><b>Mooglan says </b>'Da sleeves is also a importent piece or armer, one dat will serve yuz well if yuz decide to make some. If yuz want to kraft a sleeves, yuz need to gather a pristine lizard scale, one long lizard tail, and a chunk of dark colored fungus, and kraft dem into dis here majikal assembly kit to get yur armplate material. Den yuz take dat material and dis mold to a forge and smelt dem together into a gud set of sleeves.'
<br><b>Mooglan gives you : </b><a href=http://phobos/eq/item.php?id=51371>Armplate Mold of Darkness</a>
<p><b>You say, </b>'boots'
<br><b>Mooglan says </b>'Da boots is a gud piece to have, dey is gud for trompin around in da Feerrott and even gud for skweeshing da big bugs dat lives out dere. If yuz want to kraft a boots, yuz need to gather a pristine lizard scale, two spiderling silks, and a giant bat wing, and kraft dem into dis here majikal assembly kit to get yur boot material. Den yuz take dat material and dis mold to a forge and smelt dem together into a gud set of boots.'
<br><b>Mooglan gives you : </b><a href=http://phobos/eq/item.php?id=51374>Boot Mold of Darkness</a>
<p><b>You say, </b>'legplates'
<br><b>Mooglan says </b>'Wez Ogre have big legz, which make big targets for da enemies, so itz a gud ting to protekt dem as best you can. To kraft some legplates, yuz need to gather two pristine lizard scales, one black spider silk, and one chunk of multi-colored fungus, and kraft dem into dis here majikal assembly kit to get yur legplate material. Den yuz take dat material and dis mold to a forge and smelt dem together into some gud legplates.'
<br><b>Mooglan gives you : </b><a href=http://phobos/eq/item.php?id=51375>Legplate Mold of Darkness</a>
<p><b>You say, </b>'gloves'
<br><b>Mooglan says </b>'We also have big handz, which makes dem very easy to get hurt in da battles, so it also be a good idea to protekt dem too. If yuz want to kraft a gloves, yuz need to gather a pristine lizard scale, one black lizard scale, and one spiderling silk, and kraft dem into dis here majikal assembly kit to get yur gloves material. Den yuz take dat material and dis mold to a forge and smelt dem together into a some gud gloves.'
<br><b>Mooglan gives you : </b><a href=http://phobos/eq/item.php?id=51373>Gauntlet Mold of Darkness</a>
<p><b>You say, </b>'breastplate'
<br><b>Mooglan says </b>'Da brestplate is a gud piece to have, it protektz yuz from all da beatingz dat you get if you fight in da Feerrott. If yuz want to kraft a brestplate, yuz need to gather two pristine lizard scales, one black lizard scale, and four black spider silks, and kraft dem into dat there majikal assembly kit to get yur brestplate material. Den yuz take dat material and dis mold to a forge and smelt dem together into a gud breastplate.'
<br><b>Mooglan gives you : </b><a href=http://phobos/eq/item.php?id=51376>Breastplate Mold of Darkness</a>
<p><b>You say, </b>'trust'
<br><b>Mooglan says </b>'Sumbudy make Mooglan angry. No one make me angry and live. You go into da jungle and find me four jungle spider venom sacs. Me want to make da poison to kill dis person! Dis be secret. You not tell anybody! If you do dis for me, I give you a reward. Now go!'
<p><b>You give Mooglan : </b><a href=http://phobos/eq/item.php?id=55210>Jungle Spider Poison Sac</a> x4
<br><b>Mooglan says </b>'Dis be good. You do a great evil work on dis day. Take dis weapon.'
<br><b>Mooglan gives you : </b><a href=http://phobos/eq/item.php?id=55211>Mooglan's Sword of Darkness</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Mooglan says </b>'I not needz dis.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>