<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=55208>Lizardman Mystic Scale</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=51378>Assembly Kit of Protection</a><li><a href=http://phobos/eq/item.php?id=51349>Helm Mold of Protection</a><li><a href=http://phobos/eq/item.php?id=51351>Bracer Mold of Protection</a><li><a href=http://phobos/eq/item.php?id=51350>Armplate Mold of Protection</a><li><a href=http://phobos/eq/item.php?id=51353>Boot Mold of Protection</a><li><a href=http://phobos/eq/item.php?id=51354>Legplate Mold of Protection</a><li><a href=http://phobos/eq/item.php?id=51352>Gauntlet Mold of Protection</a><li><a href=http://phobos/eq/item.php?id=51355>Breastplate Mold of Protection</a><li><a href=http://phobos/eq/item.php?id=55209>Murak's Staff of Protection</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Murak says </b>'Yuz be a shaman, yes? Gud, mez have many tings to teach yuz, yuz have lots of training still. Da first ting we haz to work on is teeching yuz to make some armor. If yuz a [shaman], mez can teech you da ways of our class.'
<p><b>You say, </b>'shaman'
<br><b>Murak says </b>'Mez tink dat yuz were. Letz begin yur traineeng. Da furst ting dat yuz needz to do is gather da itemz dat will be uzed in da krafteeng of da [armor] and den yuz can kraft dem in dis majikal assembly kit.'
<br><b>Murak gives you : </b><a href=http://phobos/eq/item.php?id=51378>Assembly Kit of Protection</a>
<p><b>You say, </b>'armor'
<br><b>Murak says </b>'Da itemz you will needz to gather will be all ober da Feerrott. Dese itemz will be hard for yuz to gather, dey come from some of da meanest tings in da Feerrott. Once yuz are redy to begin, tell mez da piece dat yuz wantz to kraft and mez will give yuz da recipez dat yuz will need when making da armor. I have recipez for [Helms], [Bracers], [Sleeves], [Boots], [Legplates], [Gloves] and [Breastplate].'
<p><b>You say, </b>'helm'
<br><b>Murak says </b>'Oh! Yuz be a smert ogre, dat yuz are! Protektshun for dat hed of yurz be bery impotent! If yuz want to kraft da helm, yuz needz to gather an orange lizard scale, one chunk of dark colored fungus, and one short lizard tail. Once yuz have dem items, yuz need to craft dem togeder in yur majikal kit to get da helm material. When yuz got da material, yuz need to take it to da forge wit dis mold and smelt it into a gud helm.'
<br><b>Murak gives you : </b><a href=http://phobos/eq/item.php?id=51349>Helm Mold of Protection</a>
<p><b>You say, </b>'bracer'
<br><b>Murak says </b>'Da bracer is a gud piece to have. If yuz want to kraft a bracer, yuz need to gather an orange lizard scale, a fire beetle leg, two metal bits, and a flask of water. Once yuz have dem items, yuz need to craft dem togeder in yur majikal kit to get da bracer material. When yuz got da material, yuz need to take it to da forge wit dis mold and smelt it into a gud bracer.'
<br><b>Murak gives you : </b><a href=http://phobos/eq/item.php?id=51351>Bracer Mold of Protection</a>
<p><b>You say, </b>'sleeves'
<br><b>Murak says </b>'Da sleeves is a gud piece to have, speshully if yuz fight tings dat are taller den da knee. If yuz want to kraft a sleeves, yuz need to gather an orange lizard scale, one long lizard tail and a black lizard talon. Once yuz have dem items, yuz need to craft dem togeder in yur majikal kit to get da armplate material. When yuz got da material, yuz need to take it to da forge wit dis mold and smelt it into a gud set of armplatez.'
<br><b>Murak gives you : </b><a href=http://phobos/eq/item.php?id=51350>Armplate Mold of Protection</a>
<p><b>You say, </b>'boots'
<br><b>Murak says </b>'Da boots is a gud piece to have. If yuz want to kraft a boots, yuz need to gather an orange lizard scale, one green lizard scale, and wun giant bat fur. Once yuz have dem items, yuz need to craft dem togeder in yur majikal kit to get da boot material. When yuz got da material, yuz need to take it to da forge wit dis mold and smelt it into a gud set of bootz.'
<br><b>Murak gives you : </b><a href=http://phobos/eq/item.php?id=51353>Boot Mold of Protection</a>
<p><b>You say, </b>'legplates'
<br><b>Murak says </b>'Legplatez is prollee da most impotent armer dat yuz can get. Most of da emenies dat yuz will fight will go for da legz, widout legz, yuz become a bery easy target. Da legplates is a gud piece to have. If yuz want to kraft a legplates, yuz need to gather two orange lizard scales, one black spider silk, and one pristine spider silk. Once yuz have dem items, yuz need to craft dem togeder in yur majikal kit to get da legplate material. When yuz got da material, yuz need to take it to da forge wit dis mold and smelt it into a gud set of legplatez.'
<br><b>Murak gives you : </b><a href=http://phobos/eq/item.php?id=51354>Legplate Mold of Protection</a>
<p><b>You say, </b>'gloves'
<br><b>Murak says </b>'Fingerz must be protekted at all timez, if yuz looze a finger, yuz kant weild weaponz as gud anymore, and dat wud not be a good ting. If yuz want to kraft a gloves, yuz need to gather an orange lizard scale, one brown lizard talon, and one green lizard talon. Once yuz have dem items, yuz need to craft dem togeder in yur majikal kit to get da glove material. When yuz got da material, yuz need to take it to da forge wit dis mold and smelt it into a gud pair of glovez.'
<br><b>Murak gives you : </b><a href=http://phobos/eq/item.php?id=51352>Gauntlet Mold of Protection</a>
<p><b>You say, </b>'breastplate'
<br><b>Murak says </b>'Da breastplate is da most protektive armer yuz can get, but iz also da most impotent one if yuz plan on fighting in da army. If yuz want to kraft a tunic, yuz need to gather two orange lizard scales, one yellow lizard scale, and three pristine spider silks. Once yuz have dem items, yuz need to craft dem togeder in yur majikal kit to get da brestplate material. When yuz got da material, yuz need to take it to da forge wit dis mold and smelt it into a gud brestplate. After yuz make da breastplate mebbe me give you anuder [job].'
<br><b>Murak gives you : </b><a href=http://phobos/eq/item.php?id=51355>Breastplate Mold of Protection</a>
<p><b>You say, </b>'job'
<br><b>Murak says </b>'I been making necklace for ceremony. Me needs four more tings to finish it. If yuz could find four lizardman mystic scales, I give you a reward.'
<p><b>You give Murak : </b><a href=http://phobos/eq/item.php?id=55208>Lizardman Mystic Scale</a> x4
<br><b>Murak says </b>'Dese gud and shiny. Here be your reward. Gud luck.'
<br><b>Murak gives you : </b><a href=http://phobos/eq/item.php?id=55209>Murak's Staff of Protection</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>