<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'Hi [Your Name]. Did [Bordag send you]?'
<p><b>You say, </b>'bordag sent me'
<br><b>Not Found says </b>'So you want learn about how to fight like bear and to crush enemy with bare hand? That good. Best way to start is just go out and do it. Biggest enemy around here lizard men. You go practice. Fight against lizard men. Bring me their tasty meat. You bring four.'
</td></tr></table>