<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=66187>Basilisk Tongue</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=55398>Strongbear Chain Assembly Kit</a><li><a href=http://phobos/eq/item.php?id=55394>Strongbear Boot Mold</a><li><a href=http://phobos/eq/item.php?id=55392>Strongbear Bracer Mold</a><li><a href=http://phobos/eq/item.php?id=55391>Strongbear Coif Mold</a><li><a href=http://phobos/eq/item.php?id=55396>Strongbear Gloves Mold</a><li><a href=http://phobos/eq/item.php?id=55393>Strongbear Gorget Mold</a><li><a href=http://phobos/eq/item.php?id=55395>Strongbear Leggings Mold</a><li><a href=http://phobos/eq/item.php?id=55397>Strongbear Tunic Mold</a><li><a href=http://phobos/eq/item.php?id=55399>Axe of the Strongbear</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Ogomok says </b>'Who you be? You fight with anger in your veins? You think you strong [berserker]?'
<p><b>You say, </b>'berserker'
<br><b>Ogomok says </b>'You weak! Me teach you to be strong! Wot you think about that? Me teach you to make starting [armor].'
<p><b>You say, </b>'armor'
<br><b>Ogomok says </b>'Dis be armor only for strong berserker ogres. Me not sure if you are good enough, but we soon find out. If you pass, you get armor. If you fail, you die. Take dis kit. You put stuff in there and combine it to make Strongbear Armor. Wot you want to craft first? I can teach how to make [boots], [bracer], [coif], [gloves], [gorget], [leggings], and [tunic]. Tunic be hardest to make.'
<br><b>Ogomok gives you : </b><a href=http://phobos/eq/item.php?id=55398>Strongbear Chain Assembly Kit</a>
<p><b>You say, </b>'boots'
<br><b>Ogomok says </b>'To make da Strongbear Boots, youz need to find one small piece of ore, one yellow lizard scale, one low quality bear skin, and one black spider silk. Mebba youz can find da animal partz out in Feerrott. For da ore, mebbe you can find somewhere here in da city. Once you have all of da itemz, combine dem in your assembly kit and take da Strongbear Boots Material to a forge with dis mold to make your new boots.'
<br><b>Ogomok gives you : </b><a href=http://phobos/eq/item.php?id=55394>Strongbear Boot Mold</a>
<p><b>You say, </b>'bracer'
<br><b>Ogomok says </b>'To make a Strongbear Bracer, youz need to get one small piece of ore, two bone chips, and one yellow lizard scale. Mebba youz can find da animal partz out in Feerrott. For da ore, mebbe you can find somewhere here in da city. Once you have all of da itemz, combine dem in your assembly kit and take da Strongbear Bracer Material to a forge, with dis mold to make your new bracer.'
<br><b>Ogomok gives you : </b><a href=http://phobos/eq/item.php?id=55392>Strongbear Bracer Mold</a>
<p><b>You say, </b>'coif'
<br><b>Ogomok says </b>'To make Strongbear Coif, youz need to get one small piece of ore, one pristine lizard talon, one dark colored fungus, and one yellow lizard scale. Mebba youz can find da animal partz out in Feerrott. For da ore, mebbe you can find somewhere here in da city. Once you have all of day itemz, combine dem in your assembly kit and take da Strongbear Coif Material to a forge, with dis mold to make your new coif.'
<br><b>Ogomok gives you : </b><a href=http://phobos/eq/item.php?id=55391>Strongbear Coif Mold</a>
<p><b>You say, </b>'gloves'
<br><b>Ogomok says </b>'To make Strongbear Gloves, youz need to get one small piece of ore, two pristine lizard talons, one bone chips, and one yellow lizard scale. Mebba youz can find da animal partz out in Feerrott. For da ore, mebbe you can find somewhere here in da city. Once you have all of da itemz, combine dem in your assembly kit and take da Strongbear Gloves Material to a forge, with dis mold to make your new gloves.'
<br><b>Ogomok gives you : </b><a href=http://phobos/eq/item.php?id=55396>Strongbear Gloves Mold</a>
<p><b>You say, </b>'gorget'
<br><b>Ogomok says </b>'To make Strongbear Gorget, youz need to get one small piece of ore, one pristine lizard talon, one long lizard tail, and one yellow lizard scale. Mebba youz can find da animal partz out in Feerrott. For da ore, mebbe you can find somewhere here in da city. Once you have all of da itemz, combine dem in your assembly kit and take da Strongbear Gorget Material to a forge, with dis mold to make your new gorget.'
<br><b>Ogomok gives you : </b><a href=http://phobos/eq/item.php?id=55393>Strongbear Gorget Mold</a>
<p><b>You say, </b>'leggings'
<br><b>Ogomok says </b>'To make da Strongbear Leggings, youz need to get one small piece of ore, one yellow lizard scale, one pristine lizard talon, and one low quality bear skin. Mebba youz can find da animal partz out in Feerrott. For da ore, mebbe you can find somewhere here in da city. Once you have all of da itemz, combine dem in your assembly kit and take da Strongbear Leggings Material to a forge, with dis mold to make your new leggings.'
<br><b>Ogomok gives you : </b><a href=http://phobos/eq/item.php?id=55395>Strongbear Leggings Mold</a>
<p><b>You say, </b>'tunic'
<br><b>Ogomok says </b>'You tink you can do dis? It be da most diffa...Diffikclt...Hardest piece to make. If youz tink you ready, youz need ta get one thick grizzly bear skin, two small pieces of ore, two yellow lizard scales, and one bone chips. Mebba youz can find da animal partz out in Feerrott. For da ore, mebbe you can find somewhere here in da city. Once you have all of da itemz, combine dem in your assembly kit and take da Strongbear Tunic Material to a forge, with dis mold to make your new tunic. When you done wit dat, come back ere and mebbe me have anuder [ting] for you to do. Wot you think about that?'
<br><b>Ogomok gives you : </b><a href=http://phobos/eq/item.php?id=55397>Strongbear Tunic Mold</a>
<p><b>You say, </b>'ting'
<br><b>Ogomok says </b>'You say you filled with da rage? Me have da rage too. My rage start when my luv, Hooly Bubblegut got killed by nasty basilisks in da Rathe Mountains! Me want revenge!!!'
<br><font color=green><b>Ogomok </b>'s face turns bright red.</font>
<br><b>Ogomok says </b>'You go to doze mountains and kill basilisks. Me want four basilisk tongues. You bring me dem, and me give you reword.'
<p><b>You give Ogomok : </b><a href=http://phobos/eq/item.php?id=66187>Basilisk Tongue</a> x4
<br><b>Ogomok says </b>'You good! You help me much. Me give you dis! Me heart still hurt for Hooly be me rage comfortz me.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Ogomok gives you : </b><a href=http://phobos/eq/item.php?id=55399>Axe of the Strongbear</a>
</td></tr></table>