<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=item1></a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13527>Green Stained Skin Tunic*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Soonog says </b>'You [Greenblood]?'
<p><b>You give Soonog : </b><a href=http://phobos/eq/item.php?id=18789>A tattered note</a>
<br><b>Soonog says </b>'Soonog own you now.. fight for Soonog.. Soonog make you power.. Soonog army rule all!'
<br><b>Soonog gives you : </b><a href=http://phobos/eq/item.php?id=13527>Green Stained Skin Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>