<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13187>Froglok Tadpole Flesh</a><li><a href=http://phobos/eq/item.php?id=14199>Allize Volew Medicine Bag</a><li><a href=http://phobos/eq/item.php?id=13367>Mystic Doll</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15093>Spell: Burst of Flame</a><li><a href=http://phobos/eq/item.php?id=1444>Initiate Symbol of Rallos Zek</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=295>Shamen of War</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Zulort says </b>'Um, you.  Hi..  You Shaman of War now, right?  You gotta learns war and war spells.  We fights all and makes the Warlord likes us.  You [gonna help] or me gonna feed you fat stoopid boddie to doggies.'
<p><b>You say, </b>'help'
<br><b>Zulort says </b>'Good.  Warlord need many boddie.. I means Shamans of War.. to kill and gets killed.. no, ummm.. kill and smoosh for Him and makes Him happy.  You goes show me you can smoosh tings good.  Gets me four froglok tadpole fleshies for me to munchings on and me be happy.. um, He, the Warlord be so berry happy.  Helping our tuff friends de Greenbloods but be watching for dem scummy Crakneks, dumb ogres dey is.  No good, no our friends.  Go now. Me.. er.. he waiting and hungry.'
<p><b>You say, </b>'bedder shaman'
<br><b>Zulort says </b>'Yoo want to be bedda shaman? Them lizards in de Feerrott tink de bedda den us and bodder us wit der majiks like fleas on a dog. Kill dem and bring me, um, one of dem bags dey wear around dem necks and, um, three of dem dolls dey hold.'
<p><b>You give Zulort : </b><a href=http://phobos/eq/item.php?id=13187>Froglok Tadpole Flesh</a> x4
<br><b>Zulort says </b>'Oh, me.. um.. Warlord BERRY happy.  Berry like dese.  Gimme.  Uh, why is you still here?  Take dis and gets more kills.  You learning good, come sees me. I teaches you bout stuff.  Make you [bedder shaman].  Go.  He and me watching.'
<br><b>Zulort gives you : </b><a href=http://phobos/eq/item.php?id=15093>Spell: Burst of Flame</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=295>Shamen of War</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Zulort : </b><a href=http://phobos/eq/item.php?id=14199>Allize Volew Medicine Bag</a>, <a href=http://phobos/eq/item.php?id=13367>Mystic Doll</a> x3
<br><b>Zulort says </b>'Dis good stuff! Me and Warlord happy! Wear dis symbol and he make yoo strong with majik!'
<br><b>Zulort gives you : </b><a href=http://phobos/eq/item.php?id=1444>Initiate Symbol of Rallos Zek</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=295>Shamen of War</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Zulort says </b>'Me not need dis.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>