<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13753>Low Quality Wolf Skin</a><li><a href=http://phobos/eq/item.php?id=13754>Medium Quality Wolf Skin</a><li><a href=http://phobos/eq/item.php?id=13755>High Quality Wolf Skin</a></ul></td><td><hr><b>When Baobob Miller spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Baobob Miller says </b>'Hello, there. My name is Baobob Miller. My [sister] and I are the best tanners in all of Norath. Wolves are my specialty. A nice wolf skin [garmet] would be the perfect accessory to your 

stylish ensemble.'
<p><b>You say, </b>'what sister'
<br><b>Baobob Miller says </b>'My little sister Chanda is the second best tanner around!. Seriously though, she is a very skilled artisan and people travel far and wide to acquire one of her fine bear skin cloaks. I 

am proud of her. She doesn't really like to meet new people, but if you tell her [Baobob sent you], I am sure she can help get you into some nice bear skin boots.'
<p><b>You say, </b>'what garment'
<br><b>Baobob Miller says </b>'I make the finest wolf skin [boots],[cloaks] and [belts] in all of Antonica.'
<p><b>You say, </b>'what boot'
<br><b>Baobob Miller says </b>'If you can bring me a wolf skin of medium quality and pay me a fee of say.. hmmmm.. for you.. 15 gold pieces, I think I can make you a pair of boots that will make all of Qeynos envy 

you.'
<p><b>You say, </b>'what cloak'
<br><b>Baobob Miller says </b>'Yes! One of my wold skin cloaks would go very well with your.. eeerr.. style.. Ahem! Let's see.. I think I can get you into one for 21 gold pieces, but, you have to provide the skin, and 

I make my cloaks with only the highest quality wolf skins.'
<p><b>You say, </b>'what belt'
<br><b>Baobob Miller says </b>'Belts are far more forgiving than cloaks or boots. A lesser quality pelt and 5 gold pieces would get you a nice wolf-hide belt.'
<p><b>You give Baobob Miller : </b><a href=http://phobos/eq/item.php?id=13753>Low Quality Wolf Skin</a>
<p><b>You give Baobob Miller : </b><a href=http://phobos/eq/item.php?id=13754>Medium Quality Wolf Skin</a>
<p><b>You give Baobob Miller : </b><a href=http://phobos/eq/item.php?id=13755>High Quality Wolf Skin</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>