<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13750>Low Quality Bear Skin</a><li><a href=http://phobos/eq/item.php?id=13751>Medium Quality Bear Skin</a><li><a href=http://phobos/eq/item.php?id=13752>High Quality Bear Skin</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Chanda Miller says </b>'Um.. I do not know you. Please um.. leave me be.'
<p><b>You say, </b>'baobob sent me'
<br><b>Chanda Miller says </b>'Oh.. Hello. My name is Chanda. [Your Name] is your name? That's a nice name. My [brother] sent you to talk to me? You must want some bear.. um.. [clothes].'
<p><b>You say, </b>'what brother'
<br><b>Chanda Miller says </b>'umm.. My brother.. Um.. I mean my BROTHER.. He is the finest tanner there is. His name is Baobob and I love him very much.'
<p><b>You say, </b>'what clothes'
<br><b>Chanda Miller says </b>'I um.. know how to make.. umm.. [cloaks] and [boots]. Oh yes! and belts! I love to make bear skin belts! Um.. I really like [belts]. My [brother] says I have to start charging more gold 

for my stuff though..'
<p><b>You say, </b>'what cloak'
<br><b>Chanda Miller says </b>'I.. um.. can make.. um.. a good cloak for you. You have to get me a bear skin of high quality and my brother says I should not make them unless you also give me 21 gold pieces. I used to 

give them away but [Baobob] got mad at me so I don't do that anymore.'
<p><b>You say, </b>'what boot'
<br><b>Chanda Miller says </b>'I know how to make boots. Um.. I don't like them as much as belts. They are harder to make. You have to get me a medium quality bear skin and give me 15 gold pieces if you want some bear 

boots. They are really good, though. At least that is what Baobob tells me.'
<p><b>You say, </b>'what belt'
<br><b>Chanda Miller says </b>'Oh, yes, I like making belts! They are easy! All I need is a bear skin and 5 gold pieces. The bear skin doesn't have to be that great but don't bring me a ruined one. The gold was my 

brother's idea.. sorry.'
<p><b>You give Chanda Miller : </b><a href=http://phobos/eq/item.php?id=13750>Low Quality Bear Skin</a>
<p><b>You give Chanda Miller : </b><a href=http://phobos/eq/item.php?id=13751>Medium Quality Bear Skin</a>
<p><b>You give Chanda Miller : </b><a href=http://phobos/eq/item.php?id=13752>High Quality Bear Skin</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>