<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>Gnasher Furgutt says </b>'Who are you? Did McNeal send you? If not, you would do yourself good to leave Gnasher alone. I have friends in high places.'
<hr><b>When Gnasher Furgutt is killed </b>
<br><b>Gnasher Furgutt says </b>'Uuungghh!! You fool. Gnasher have human friends. They not be happy.. Bash you!!'
</td></tr></table>