<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18921>Message to Konem</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18922>Grathin's Invoice</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=300>Silent Fist Clan</a><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a><li><a href=http://phobos/eq/faction.php?id=12>Ashen Order</a></ul></td><td><p><b>You give Konem Matse : </b><a href=http://phobos/eq/item.php?id=18921>Message to Konem</a>
<br><b>Konem Matse says </b>'Oh I see.. Phin's always after me about something.  I mean, it's not my fault the order hasn't come in yet.  Hey, since I'm so busy right now, why don't you be a friend and take this back to Phin for me, huh?'
<br><b>Konem Matse gives you : </b><a href=http://phobos/eq/item.php?id=18922>Grathin's Invoice</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=300>Silent Fist Clan</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=12>Ashen Order</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>