<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18823>Note to Neclo</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15288>Spell: Minor Shielding</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Neclo Rheslar says </b>'Ah..   Hello. citizen..  Watch your step. there have been many vicious beasts about today.'
<p><b>You give Neclo Rheslar : </b><a href=http://phobos/eq/item.php?id=18823>Note to Neclo</a>
<br><b>Neclo Rheslar says </b>'Ah..  Hello friend..  So. I see Daenor sent you..  Uh huh. ok..  Here's something that will be very useful for you.  Practice this well. friend..  It will help protect you in this harsh world.'
<br><b>Neclo Rheslar gives you : </b><a href=http://phobos/eq/item.php?id=15288>Spell: Minor Shielding</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
</td></tr></table>