<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'Well. it seems that you have something of importance that you wish to speak to me about?  No?  Then perhaps you can do something [for me].'
<p><b>You say, </b>'what do you want me to do for you'
<br><b>Not Found says </b>'Well I need some information.  It appears that some gnolls are planning an [invasion] of Surefall.  I believe there are some gnoll couriers that are running information.  If you could bring me their marching orders. invasion plans. area maps. and their encryption key.  Your best chance to catch a courier is probably inside Blackburrow.'
<p><b>You say, </b>'what invasion'
<br><b>Not Found says </b>'Apparently they've heard of our plans to reopen the entrance to Jaggedpine inside Surefall.  It seems they believe the think they have a chance to stop us.  While most of us have little concern about a gnoll invasion force the information you provide would be of great assistance.'
<p><b>You say, </b>'what can i do for you'
<br><b>Not Found says </b>'Well I need some information.  It appears that some gnolls are planning an [invasion] of Surefall.  I believe there are some gnoll couriers that are running information.  If you could bring me their marching orders. invasion plans. area maps. and their encryption key.  Your best chance to catch a courier is probably inside Blackburrow.'
</td></tr></table>