<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13072>Rat Ears</a><li><a href=http://phobos/eq/item.php?id=13719>Grilled Rat Ears</a><li><a href=http://phobos/eq/item.php?id=13050>Giant Rat Ear</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13719>Grilled Rat Ears</a><li><a href=http://phobos/eq/item.php?id=13076>Fish Scales</a><li><a href=http://phobos/eq/item.php?id=18103>Rat Ear Pie</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=11>Arcane Scientists</a><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a><li><a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Rephas says </b>'Aagggh..  Get away from here..  Go, run..  Far away..  Or I shall call [Karana's] wrath upon you!'
<p><b>You say, </b>'karana\'s'
<p><b>You give Rephas : </b><a href=http://phobos/eq/item.php?id=13072>Rat Ears</a>
<br><b>Rephas says </b>'Ahh yes..  These are a little small, but still some good eating, if you know how to cook 'em of course..   Here ya go, enjoy and may Karana keep your fields lush and green.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=11>Arcane Scientists</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a> has gotten worse.</font>
<br><b>Rephas gives you : </b><a href=http://phobos/eq/item.php?id=13719>Grilled Rat Ears</a>
<p><b>You give Rephas : </b><a href=http://phobos/eq/item.php?id=13719>Grilled Rat Ears</a>
<br><b>Rephas says </b>'Wha?..   Ah, I guess it's a bit of an acquired taste..  Oh well, your loss..  Here, take this..  They ain't no ears, but it's the least I could do..   And if ya find any more rat ears, good ol' Rephas here will be glad to take 'em off your hands for ya!'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=11>Arcane Scientists</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a> has gotten worse.</font>
<br><b>Rephas gives you : </b><a href=http://phobos/eq/item.php?id=13076>Fish Scales</a>
<p><b>You give Rephas : </b><a href=http://phobos/eq/item.php?id=13050>Giant Rat Ear</a> x4
<br><b>Rephas says </b>'Wow!..  How big was the dang varmint that these come off of?!  Bigger'n a ol' grizzly, I bet!  You've earned this, my friend!  It's my own secret recipe for rat ear pie..  sure is tasty, easy to make, and keeps your belly full while you're running about in the hills and such.  Take care, and may Karana keep your path clear and our lakes full.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=11>Arcane Scientists</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a> has gotten worse.</font>
<br><b>Rephas gives you : </b><a href=http://phobos/eq/item.php?id=18103>Rat Ear Pie</a>
<p><b>You give Rephas : </b><a href=http://phobos/eq/item.php?id=13050>Giant Rat Ear</a>
<br><b>Rephas says </b>'Hey..  wow..  Now THESE are some good, meaty ears..  These will make one great rat ear pie..  Tell ya what, kid..  bring me a few more o' these beauties, and I'll give you my secret recipe for cooking 'em.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=11>Arcane Scientists</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a> has gotten worse.</font>
</td></tr></table>