<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=15931>Marching Orders</a><li><a href=http://phobos/eq/item.php?id=15932>Invasion Plans</a><li><a href=http://phobos/eq/item.php?id=15933>Area Maps of Qeynos Hills</a><li><a href=http://phobos/eq/item.php?id=15934>Encryption Key</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15935>Club of Gnoll Bashing</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Rilca Leafrunner says </b>'Well, it seems that you have something of importance that you wish to speak to me about? No? Then perhaps you can do something [for me].'
<p><b>You say, </b>'for you'
<br><b>Rilca Leafrunner says </b>'Well I need some information. It appears that some gnolls are planning an [invasion] of Surefall. I believe there are some gnoll couriers that are running information. If you could bring me their marching orders, invasion plans, area maps, and their encryption key. Your best chance to catch a courier is probably inside Blackburrow.'
<p><b>You say, </b>'invasion'
<br><b>Rilca Leafrunner says </b>'Apparently they've heard of our plans to reopen the entrance to Jaggedpine inside Surefall. It seems they believe the think they have a chance to stop us. While most of us have little concern about a gnoll invasion force the information you provide would be of great assistance.'
<p><b>You give Rilca Leafrunner : </b><a href=http://phobos/eq/item.php?id=15931>Marching Orders</a>, <a href=http://phobos/eq/item.php?id=15932>Invasion Plans</a>, <a href=http://phobos/eq/item.php?id=15933>Area Maps of Qeynos Hills</a>, <a href=http://phobos/eq/item.php?id=15934>Encryption Key</a>
<br><font color=green><b>Rilca Leafrunner </b>takes a look at the documents you handed her and smiles.</font>
<br><b>Rilca Leafrunner says </b>'This is exactly what we needed. We'll be better prepared if the gnolls are foolish enough to actually attack. I hope you are willing to assist us in the defense of Surefall. Should you choose to aid us, this club will serve you well.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Rilca Leafrunner gives you : </b><a href=http://phobos/eq/item.php?id=15935>Club of Gnoll Bashing</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>