<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13303>Guard Bracelet</a><li><a href=http://phobos/eq/item.php?id=13304>Guard Bracelet</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=9002>Round Shield</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a><li><a href=http://phobos/eq/faction.php?id=9>Antonius Bayle</a><li><a href=http://phobos/eq/faction.php?id=217>Merchants of Qeynos</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a><li><a href=http://phobos/eq/faction.php?id=33>Circle of Unseen Hands</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Capt Linarius says </b>'Hail, traveler! You are free to rest within this keep or within any of my towers along the roads to Qeynos. My guards shall keep watch over you. While you tread upon the roads, be warned that there are [local dangers] as well as rumors of [corrupt guards].'
<p><b>You say, </b>'corrupt guards'
<br><b>Capt Linarius says </b>'I have heard rumors of dissension among my guards. I will reward any fine resident for the death of these traitorous guards. If you find you must kill one, bring his guard bracelet back to me. I cannot allow such men among my guards. Be sure they are corrupt, or I shall have your head as well.'
<p><b>You say, </b>'local dangers'
<br><b>Capt Linarius says </b>'My guards report daily to me of dangers in the plains. Lately, they've been telling me of rumors of [Lord Grimrot].'
<p><b>You say, </b>'Lord Grimrot'
<br><b>Capt Linarius says </b>'My guards have heard rumors of this Lord Grimrot. It is said that he is a powerful shadowknight who is raising an army of undead. Such things should be reported to the Temle of Life. Journey to Qeynos and speak with Camlend Serbold. Tell him of Lord Grimrot.'
<p><b>You give Capt Linarius : </b><a href=http://phobos/eq/item.php?id=13303>Guard Bracelet</a>
<br><b>Capt Linarius says </b>'What a pity. Such a promising soldier. I thank you for ridding us of this corruption and offer you this as a reward. It is nothing more than junk which littered the roadways of the Plains of Karana. I hope you can find a use for it.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Capt Linarius gives you : </b><a href=http://phobos/eq/item.php?id=9002>Round Shield</a>
<br><b>You receive </b> 8gp 19cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=9>Antonius Bayle</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=33>Circle of Unseen Hands</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=217>Merchants of Qeynos</a> has gotten better.</font>
<p><b>You give Capt Linarius : </b><a href=http://phobos/eq/item.php?id=13304>Guard Bracelet</a>
<br><b>Capt Linarius says </b>'You fool!!! You have slain a loyal defender of the guard!  Prepare to DIE!!!'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Capt Linarius says </b>'I do not need this...'
</td></tr></table>