<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=16500>Silver Bar</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18178>Fixxin Followigs Silvery Blades</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=167>Karana Residents</a><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a><li><a href=http://phobos/eq/faction.php?id=257>Priests of Life</a><li><a href=http://phobos/eq/faction.php?id=183>Knights of Thunder</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Fixxin Followig says </b>'Hail, [Your Name]! Fixxin is my moniker. Nice ta see ya. I am a member of the [Fangbreakers] and we are hunting [werewolves]. We run into lots of other [creepies] out here as well.'
<p><b>You say, </b>'fangbreakers'
<br><b>Fixxin Followig says </b>'Fangbreakers? You have not heard of us? We are the best [werewolf] hunters there are!'
<p><b>You say, </b>'werewolves'
<br><b>Fixxin Followig says </b>'Those blasted fiends hide among normal folk during the day, but at night their bloodlust is set free on an innocent populace. Some claim there is a cure for their condition but the only one we know of is an [enchanted blade] through the bellies of the beasts.'
<p><b>You say, </b>'enchanted blade'
<br><b>Fixxin Followig says </b>'Interested in an enchanted blade? You wouldn't be planning on hunting the moon beasts without a strong, well-oiled party to back you up, now, would you? Well, in any case, I'll gladly lend you a copy of my book, Fixxin Followigs Silvery Blades, if you will fetch me a bar of silver. My supply is running low and our weapons are in need of repair after the deaths of so many lycanthropes.'
<p><b>You say, </b>'creepies'
<br><b>Fixxin Followig says </b>'Besides the occasional werewolf, we also tend to run across many griffons and hill giants out this way. Those giants can be bruisers but against a trained team such as we, they don't stand a chance. Especially with my enchantments protecting us.'
<p><b>You give Fixxin Followig : </b><a href=http://phobos/eq/item.php?id=16500>Silver Bar</a>
<br><font color=green><b>Fixxin Followig </b>thanks [Your Name] heartily. 'Here is the book as promised. I wish you luck with your enchanted weapons. May they slay many lycanthropes before they go dull.'</font>
<br><b>Fixxin Followig gives you : </b><a href=http://phobos/eq/item.php?id=18178>Fixxin Followigs Silvery Blades</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=167>Karana Residents</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=257>Priests of Life</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=183>Knights of Thunder</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>