<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Guard Shilster says </b>'Hey. hey! I have some Blackburrow Stout for sale. Just hand over five gold and I'll give you a bottle of it. Don't get caught though because it is considered [contraband]. [Antonius] don't like it being smuggled and all that but what does he know. anyway?'
<p><b>You say, </b>'contraband'
<br><b>Guard Shilster says </b>'Well it's brewed by gnolls, ya know. Don't know exactly why it's considered contraband but I think it's because they use the money they get from selling the stout to buy arms. I dunno. I buy low and sell high. Blackburrow Stout is good for you though! It does wonders for me! Now buy some already before someone hears us talking.'
<p><b>You say, </b>'Antonius'
<br><b>Guard Shilster says </b>'That man is as clueless as a froglok tad swimming in a keg of dwarven ale! He has no idea what is going on around him. He won't be around for much longer I wager.'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Guard Shilster says </b>'Thanks, but I do not need this...'
</td></tr></table>