<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10300>Lightstone</a><li><a href=http://phobos/eq/item.php?id=10400>Greater Lightstone</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18176>Runes and Research Volume II</a><li><a href=http://phobos/eq/item.php?id=17504>Concordance of Research</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Mrysila says </b>'I am Mrysila. custodian of the [Concordance of Research].'
<p><b>You say, </b>'Concordance of Research'
<br><b>Mrysila says </b>'The 'Concordance of Research' is an aid to those who follow the path of academia. It, and its sister books, 'Runes and Research,' volumes I and II, help those who are [interested] in researching spells.'
<p><b>You say, </b>'interested'
<br><b>Mrysila says </b>'I have several copies of each book. If you want a copy of 'Runes and Research', volume I or II, bring me a lightstone and I will give you whichever book I have more of at the moment. Bring me a greater lightstone, and I will give you a copy of the 'Concordance of Research.'
<p><b>You give Mrysila : </b><a href=http://phobos/eq/item.php?id=10300>Lightstone</a>
<br><b>Mrysila says </b>'A lightstone? Thank you very much. Here is a copy of 'Runes and Research'.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Mrysila gives you : </b><a href=http://phobos/eq/item.php?id=18176>Runes and Research Volume II</a>
<p><b>You give Mrysila : </b><a href=http://phobos/eq/item.php?id=10400>Greater Lightstone</a>
<br><b>Mrysila says </b>'A greater lightstone? Thank you very much. Here is a 'Concordance of Research' for you.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Mrysila gives you : </b><a href=http://phobos/eq/item.php?id=17504>Concordance of Research</a>
<br><b>Mrysila says </b>'[Your Name], I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>