<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20483>Refined Mithril Blade</a><li><a href=http://phobos/eq/item.php?id=20484>Shattered Emerald of Corruption</a><li><a href=http://phobos/eq/item.php?id=20699>Cleansed Spirit of Kunark</a><li><a href=http://phobos/eq/item.php?id=20697>Cleansed Spirit of Faydwer</a><li><a href=http://phobos/eq/item.php?id=20698>Cleansed Spirit of Antonica</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20488>Earthcaller</a><li><a href=http://phobos/eq/item.php?id=20490>Nature Walkers Scimitar</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Xanuusus says </b>'Greetings, small one! I am Xanuusus of the Stormreapers. You are welcome to rest beneath my mighty branches.'
<p><b>You give Xanuusus : </b><a href=http://phobos/eq/item.php?id=20483>Refined Mithril Blade</a>, <a href=http://phobos/eq/item.php?id=20484>Shattered Emerald of Corruption</a>
<br><font color=green><b>Xanuusus </b>waves his hands over the gem of corruption and a wave of warm energy passes through the area. With care for such a huge creature, he melds the gem into the sword and seems to glow all over as he channels energy into the weapon. 'Thus is the link of hate broken between Innoruuk and the spirit of earth. Through your will has balance returned. Your deeds, your work for the good of all, will be remembered by anyone who walks beneath the canopy of a forest or roams the plains. Continue your vigil over nature's balance.'</font>
<br><b>Xanuusus gives you : </b><a href=http://phobos/eq/item.php?id=20488>Earthcaller</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=green><b>Xanuusus </b>will not accept this item.</font>
<p><b>You give Xanuusus : </b><a href=http://phobos/eq/item.php?id=20699>Cleansed Spirit of Kunark</a>, <a href=http://phobos/eq/item.php?id=20697>Cleansed Spirit of Faydwer</a>, <a href=http://phobos/eq/item.php?id=20698>Cleansed Spirit of Antonica</a>
<br><b>Xanuusus gives you : </b><a href=http://phobos/eq/item.php?id=20490>Nature Walkers Scimitar</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=green><b>Xanuusus </b>will not accept this item.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>