<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10035>Ruby</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10081>Midnight Mallet</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=22>Broken Skull Clan</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=292>Shadowknights of Night Keep</a><li><a href=http://phobos/eq/faction.php?id=66>Da Bashers</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Lynuga says </b>'Hrrump?! Who you? [Your Name]? What you want with Lynuga? Me am out [collecting]. Leave me be!'
<p><b>You say, </b>'collecting'
<br><b>Lynuga says </b>'I collect all sort's of thing's. Gem's be my favorite. Me really like rubies. If you have ruby, give to me! Why you want to know? You want to steal my collection?!? I squish you if you do!!'
<p><b>You give Lynuga : </b><a href=http://phobos/eq/item.php?id=10035>Ruby</a>
<br><b>Lynuga says </b>'Mmm. Ruby!! Me thank's you! Here take this, me got it off dead someone who try take my collection. Me think's this valuable thing..'
<br><b>Lynuga gives you : </b><a href=http://phobos/eq/item.php?id=10081>Midnight Mallet</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=22>Broken Skull Clan</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=292>Shadowknights of Night Keep</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=66>Da Bashers</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Lynuga says </b>'I have no need for this item [Your Name], you can have it back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>