<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12108>Orc Hatchet</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=5048>Tarnished Bastard Sword</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=10404></a><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Dill Fireshine says </b>'Welcome to the treetops and the home of Faydark's Champions. We are the skilled rangers of the Faydarks. You are safe in Kelethin. but watch yourself upon the forest floor. I hear the [blue meanies] have been on the rise.'
<p><b>You say, </b>'Who are blue meanies'
<br><b>Dill Fireshine says </b>'That is a little name I have given the Crushbone orcs. It appears they have increased their numbers. The Emerald Warriors are charged with our defense against them. We rangers are to seek out the [orc saboteurs].'
<p><b>You say, </b>'Who are orc saboteurs'
<br><b>Dill Fireshine says </b>'As others move to battle the orc armies. we have word that the orc pawns have been sent into the woods to damage the great trees which support Kelethin. We shall employ the talents of our young rangers to halt their efforts. I currently seek those who will [hunt the orc pawns].'
<p><b>You say, </b>'I will hunt the orc pawns'
<br><b>Dill Fireshine says </b>'Go to the forest floor and seek out the orc pawns. Within their ranks can sometimes be found orc hatchetmen. They carry orc hatchets which you must return and I shall reward you for every two orc hatchets and perhaps offer you a weapon in return. should we have any to spare at the time.'
<p><b>You give Dill Fireshine : </b><a href=http://phobos/eq/item.php?id=12108>Orc Hatchet</a> (x2)
<br><b>Dill Fireshine says </b>'Fantastic work!! Your actions shall earn you the respect of all Fier'Dal!  Take this as a small bounty for your deed.  We have heard of [Crushbone allies] who wish our demise.'
<br><b>Dill Fireshine gives you : </b><a href=http://phobos/eq/item.php?id=5048>Tarnished Bastard Sword</a>
<br><b>You receive </b> 12cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10404></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>