<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12109>Pouch of Pixie Dust</a><li><a href=http://phobos/eq/item.php?id=16390>Crumpled Piece of Paper</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17957>Empty Pouch</a><li><a href=http://phobos/eq/item.php?id=24098>Remiss Sketch</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=283>Scouts of Tunare</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Expin says </b>'How are you, my friend?  You must be a [new scout of Kelethin].  I would hope so.  We dearly need more recruits.  Most of the Fier'Dal choose the path of the ranger.'
<p><b>You say, </b>'new scout of Kelethin'
<br><b>Expin says </b>'Good.  I have an easy, but very important, task for you.  We require all young members to cleanse these woods of the troublesome pixie tricksters.  Take this pouch, fill it, and when it is combined, return it to me.  I just may have some used armor lying around for you.'
<br><b>Expin gives you : </b><a href=http://phobos/eq/item.php?id=17957>Empty Pouch</a>
<p><b>You say, </b>'dark assassin'
<br><font color=green><b>Expin </b>squints at you and says, 'So you have heard about him as well? I had heard of him through the rogue grapevine, so I was wary when the home guard spoke of the arrival of a dark stranger. I was approaching him from behind and some loud ranger clompipng about in the bushes must of spooked him, for off he ran. As he was running I took the liberty to swipe a piece of paper protruding from his pocket.'</font>
<br><font color=green><b>Expin </b>mumbles to himself, 'Now where did I put that note?'</font>
<p><b>You give Expin : </b><a href=http://phobos/eq/item.php?id=12109>Pouch of Pixie Dust</a>
<br><b>Expin says </b>'Good work. scout!!  You have earned this reward.  It is all we have at the time.  I am certain you are satisfied.  If not, then do not let me hear of it.'
<br><b>You receive </b> 2sp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=283>Scouts of Tunare</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Expin : </b><a href=http://phobos/eq/item.php?id=16390>Crumpled Piece of Paper</a>
<br><b>Expin says </b>'Ahhh! You found it! Here let me make you a copy and put this in a secure spot so I don't lose it again.'
<br><b>Expin gives you : </b><a href=http://phobos/eq/item.php?id=24098>Remiss Sketch</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Expin says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>