<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20472>Worn Note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20446>Faelin`s Ring</a></ul></td><td><hr><b>When Faelin Bloodbriar spawns </b>
<p><b>You give Faelin Bloodbriar : </b><a href=http://phobos/eq/item.php?id=20472>Worn Note</a>
<br><font color=green><b>Faelin Bloodbriar </b>reads the note carefully and growls to herself. 'Bad news, eh? Take this ring. There is one elf, dark elf even, whom we must go to in order to gather insight into Innoruuk's plans. Giz X'Tin, he goes by most commonly. Kithicor seems to be his favorite haunt and most likely you will find him there. Don't ask how I know him. Just take the ring as my sign to him and he will speak to you. We don't need to speak again, so don't seek me out. Just go to Telin. I must leave to investigate these events.'</font>
<br><b>Faelin Bloodbriar gives you : </b><a href=http://phobos/eq/item.php?id=20446>Faelin`s Ring</a>
<br><b>Faelin Bloodbriar disappears.</b>
<br><font color=green><b>Faelin Bloodbriar </b>does not accept the item.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>