<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=67702>Sealed Note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12184>Useless Token</a><li><a href=http://phobos/eq/item.php?id=24420>Tunarean Scout Cape</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=283>Scouts of Tunare</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Geeda says </b>'Are not the woods of the Faydarks a lovely sight? Tunare has truly blessed us. It is unfortunate that the orcs of [Crushbone Citadel] have chosen to invade our lands.'
<p><b>You say, </b>'crushbone citadel'
<br><b>Geeda says </b>'Within the Greater Faydarks can be found the entrance to Crushbone Citadel, home of the orcs. They have increased their raids on our lands. We do not know why. The High Elder of Kelethin has instructed us to keep tabs on the orcs' movements. Hmmm.. How would you like to [assist the scouts]?'
<p><b>You say, </b>'will assist the scouts'
<br><b>Geeda says </b>'We trust this operation to high standing rogues of the Scouts of Tunare. Easy it may be, but the reward is a scout cape. The scout cape is meant for Scouts of Tunare only. Have you [contributed to the Scouts' cause]?'
<p><b>You say, </b>'i have contributed to the scouts' cause'
<br><b>Geeda says </b>'So we have heard. Here, then. Take this coin. Venture into Crushbone and find our scout, Kelynn. He is posing as a slave to gain information. He tries to work very close to an opening in a cave near the moats. Find this point and wait for him to appear. Give him the coin and he shall give you the information you are to return to me.'
<br><b>Geeda gives you : </b><a href=http://phobos/eq/item.php?id=12184>Useless Token</a>
<p><b>You give Geeda : </b><a href=http://phobos/eq/item.php?id=67702>Sealed Note</a>
<br><b>Geeda says </b>'Fine work. We are very grateful. Take this Scout Cape. May you use it to serve Kelethin.'
<br><b>Geeda gives you : </b><a href=http://phobos/eq/item.php?id=24420>Tunarean Scout Cape</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=283>Scouts of Tunare</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>