<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=5013>Rusty Short Sword</a><li><a href=http://phobos/eq/item.php?id=5016>Rusty Broad Sword</a><li><a href=http://phobos/eq/item.php?id=5019>Rusty Long Sword</a><li><a href=http://phobos/eq/item.php?id=5022>Rusty Bastard Sword</a><li><a href=http://phobos/eq/item.php?id=18786>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=5047>Tarnished Scimitar</a><li><a href=http://phobos/eq/item.php?id=13537>Green and Tan Tunic*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Heartwood Master says </b>'Welcome! We are the Soldiers of Tunare, the sworn protectors of Faydark. Through the magic of Tunare we care for the land and with blade, staff and spell we protect the Faydark against those who would destroy and despoil it. We are always grateful for any assistance to our cause. Perhaps you could help me with some simple [errands].'
<p><b>You say, </b>'errands'
<br><b>Heartwood Master says </b>'As druids of the Mother of All, we may only use the scimitar and blunt weapons, all other blades are forbidden. Prove your devotion by bringing me a rusty [short sword], [long sword], [broad sword] and [bastard sword]. I will destroy them and reward you for your faith. They will be reforged into weapons blessed by Tunare to assist the Soldiers in their defence of the Heartwood.'
<p><b>You give Heartwood Master : </b><a href=http://phobos/eq/item.php?id=5019>Rusty Long Sword</a>, <a href=http://phobos/eq/item.php?id=5016>Rusty Broad Sword</a>, <a href=http://phobos/eq/item.php?id=5022>Rusty Bastard Sword</a>, <a href=http://phobos/eq/item.php?id=5013>Rusty Short Sword</a>
<br><b>Heartwood Master says </b>'You have done well, child! Take this as a blessing from Tunare for doing her will.'
<br><b>Heartwood Master gives you : </b><a href=http://phobos/eq/item.php?id=5047>Tarnished Scimitar</a>
<br><b>You receive </b>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Heartwood Master : </b><a href=http://phobos/eq/item.php?id=18786>A tattered note</a>
<br><b>Heartwood Master says </b>'Welcome! We are the Soldiers of Tunare, the sworn protectors of Faydark. I thank you for joining our cause, we can always use the help. Here, put on this tunic, and let's get started.. you have much to learn. '
<br><b>Heartwood Master gives you : </b><a href=http://phobos/eq/item.php?id=13537>Green and Tan Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>