<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12112>Pack of Materials</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=8091>Treant Bow Staff</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Maesyn Trueshot says </b>'Welcome to Kelethin. [Your Name]!  I am Maesyn Trueshot. commander of Faydark's Champions.  We are the finest marksmen in all of Norrath.  With our trusty [Trueshot longbows] we can miss no target regardless of the distance or the conditions.'
<br><b>Maesyn Trueshot says </b>'Faydark's Champions cannot call you foe. but you have yet to earn our trust.'
<p><b>You say, </b>'What trueshot longbows'
<br><b>Maesyn Trueshot says </b>'The Trueshot Longbow was created by my famed father. Eldin Trueshot. It is quite accurate and takes a ranger's skill to wield. We use our new recruits to [gather materials] needed by my father.  We shall soon begin to release the formula to good elves so all may fletch such a bow.'
<br><b>Maesyn Trueshot says </b>'Faydark's Champions cannot call you foe. but you have yet to earn our trust.'
<p><b>You say, </b>'I will gather materials'
<br><b>Maesyn Trueshot says </b>'Faydark's Champions cannot call you foe. but you have yet to earn our trust.'
<p><b>You say, </b>'correct components'
<br><b>Maesyn Trueshot says </b>'Faydark's Champions cannot call you foe. but you have yet to earn our trust.'
<br><b>Maesyn Trueshot says </b>'Now that I have crafted the Treant Bow Staff, you shall need one Planing Tool, one Treant Bow Staff, one Micro Servo and one spool of Dwarven Wire. These items will be used with your Fletching Kit as all other bows. Be forewarned, only a Master Fletcher can create such a bow and even a master fails from time to time. Good Luck.'
<p><b>You say, </b>'next incarnation'
<br><b>Maesyn Trueshot says </b>'Faydark's Champions cannot call you foe. but you have yet to earn our trust.'
<br><b>Maesyn Trueshot says </b>'The Trueshot Longbow was once enchanted by the Koada'Dal enchanters.  Once it was enchanted now it is no more.  I am sure if you were ask the Koada'Dal [where the enchanted bows] are you will get an answer.'
<p><b>You give Maesyn Trueshot : </b><a href=http://phobos/eq/item.php?id=12112>Pack of Materials</a>
<br><b>Maesyn Trueshot says </b>'I shall see that my father gets the materials. I hope this can be of use to you. It will serve as your starting point toward fletching a Trueshot longbow. It is unfortunate that we are unable to enchant the bow to its [next incarnation], but it is still a fine weapon. You do know the [correct components] needed for fletching such a bow, do you not?'
<br><b>You receive </b> 6sp
<br><b>Maesyn Trueshot gives you : </b><a href=http://phobos/eq/item.php?id=8091>Treant Bow Staff</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>