<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18904>A Faded Wedding Cloth</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2004>Leather Tunic</a></ul></td><td><p><b>You give Merchant Iludarae : </b><a href=http://phobos/eq/item.php?id=18904>A Faded Wedding Cloth</a>
<br><b>Merchant Iludarae says </b>'The slaves...thank you! Here, this will help defend you against those vile orcs.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Merchant Iludarae gives you : </b><a href=http://phobos/eq/item.php?id=2004>Leather Tunic</a>
</td></tr></table>