<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18903>A Tattered Cloth Note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2004>Leather Tunic</a></ul></td><td><p><b>You give Merchant Nildar : </b><a href=http://phobos/eq/item.php?id=18903>A Tattered Cloth Note</a>
<br><b>Merchant Nildar says </b>'My brother still lives? Thank you for this news. Please, take this with my deepest thanks.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Merchant Nildar gives you : </b><a href=http://phobos/eq/item.php?id=2004>Leather Tunic</a>
</td></tr></table>