<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Ran Sunfire says </b>'Hail. [Your Name]! I trust you are not afraid of heights. Kelethin is a grand city. but it is also a safe haven from predators and evil beings. About the only thing to fear are the [pixie tricksters].'
<p><b>You say, </b>'who are pixie tricksters'
<br><b>Ran Sunfire says </b>'An irritating lot of fairy folk. They have been starting fires in our great forest. They may just burn our grand community down. We will have to [exterminate the pixies]. It is unfortunate. but it is for the good of the entire forest.'
<p><b>You say, </b>'I exterminate the pixies'
<br><b>Ran Sunfire says </b>'Faydark's Champions cannot call you foe. but you have yet to earn our trust.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>