<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13073>Bone Chips</a><li><a href=http://phobos/eq/item.php?id=13782>Ruined Wolf Pelt</a><li><a href=http://phobos/eq/item.php?id=13253>Spiderling Eye</a><li><a href=http://phobos/eq/item.php?id=13069>Bat Fur</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=7024>Tarnished Spear</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=92>Emerald Warriors</a><li><a href=http://phobos/eq/faction.php?id=174>Kelethin Merchants</a><li><a href=http://phobos/eq/faction.php?id=212>Merchants of Felwithe</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=155>Indigo Brotherhood</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Regren says </b>'Welcome, warrior! Show the Emerald Warriors your mettle and bring me a ruined wolf pelt, some bat fur, some bone chips, and a spiderling eye from the depths of Greater Faydark. If you succeed, my admiration and a reward will be yours. To battle!'
<p><b>You give Regren : </b><a href=http://phobos/eq/item.php?id=13073>Bone Chips</a>, <a href=http://phobos/eq/item.php?id=13782>Ruined Wolf Pelt</a>, <a href=http://phobos/eq/item.php?id=13253>Spiderling Eye</a>, <a href=http://phobos/eq/item.php?id=13069>Bat Fur</a>
<br><b>Regren says </b>'Fine work! You are on your way to becoming an adequate combatant.'
<br><b>Regren gives you : </b><a href=http://phobos/eq/item.php?id=7024>Tarnished Spear</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=92>Emerald Warriors</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=155>Indigo Brotherhood</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=174>Kelethin Merchants</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=212>Merchants of Felwithe</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>