<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Sindl Talonstrike says </b>'Greetings.  Is not Kelethin the most glorious city you have seen?  A part of the forest itself. it is.  The forest is our life force.  It shelters us and we feed from its vegetation.  The [Soldiers of Tunare] have [harvesters] upon the grounds at all times.  We have our hunters.'
<p><b>You say, </b>'what soldiers of tunare'
<br><b>Sindl Talonstrike says </b>'The Soldiers of Tunare are lovers of the forest.  They are druids who protect and nurture the forest.  The forest is the genesis of their mana.  The soldiers are comprised of Fier'Dal and Koada'Dal.  Imagine that!  A Koada'Dal not afraid to get dirt under his nails!!'
<p><b>You say, </b>'what harvesters'
<br><b>Sindl Talonstrike says </b>'Just as our young warriors are employed as hunters to supply all the meat for Kelethin. the druids have their young scour the grounds of the forest for all the vegetation we need to survive.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>