<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18783>A tattered note</a><li><a href=http://phobos/eq/item.php?id=9894>Severed Orc Foot</a><li><a href=http://phobos/eq/item.php?id=13099>Spiderling Silk</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13534>Faded Brown Tunic*</a><li><a href=http://phobos/eq/item.php?id=13000>Hand Drum</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Sylia Windlehands says </b>'Salutations! The Song Weavers are always glad to add a new voice to the choir.  In addition to your voice. will you also [fetch spiderling silk]?  We need some to replace our worn lute strings.  Carry out this task in high tempo and we will show our gratitude.'
<p><b>You say, </b>'how fetch spiderling silk?'
<br><b>Sylia Windlehands says </b>'Very spirited of you!!  Gather four spiderling silk and return them to me.  Good hunting. my friend!!'
<br><b>Sylia Windlehands says </b>'Very spirited of you!!  Gather four spiderling silk and return them to me.  Good hunting. my friend!!'
<p><b>You say, </b>'where fetch spiderling silk?'
<br><b>Sylia Windlehands says </b>'Very spirited of you!!  Gather four spiderling silk and return them to me.  Good hunting. my friend!!'
<br><b>Sylia Windlehands says </b>'Very spirited of you!!  Gather four spiderling silk and return them to me.  Good hunting. my friend!!'
<p><b>You say, </b>'fetch spiderling silk?'
<br><b>Sylia Windlehands says </b>'Very spirited of you!!  Gather four spiderling silk and return them to me.  Good hunting. my friend!!'
<p><b>You give Sylia Windlehands : </b><a href=http://phobos/eq/item.php?id=18783>A tattered note</a>
<br><b>Sylia Windlehands says </b>'Greetings. friend. I am Sylia.  I see that you wish to join our humble guild.  Good.  Here is a gift for you - your guild tunic.  Let's get started with your training. shall we?'
<br><b>Sylia Windlehands gives you : </b><a href=http://phobos/eq/item.php?id=13534>Faded Brown Tunic*</a>
<p><b>You give Sylia Windlehands : </b><a href=http://phobos/eq/item.php?id=13099>Spiderling Silk</a> (x3), <a href=http://phobos/eq/item.php?id=9894>Severed Orc Foot</a> (x2)
<br><b>Sylia Windlehands says </b>'Well done! Do you have the rest?'
<br><b>Sylia Windlehands says </b>'Splendid job!  Now if you can just keep a tune. you'll be a fine bard.'
<br><b>Sylia Windlehands gives you : </b><a href=http://phobos/eq/item.php?id=13000>Hand Drum</a>
<br><b>You receive </b> 1gp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>