<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17365>Assassins Mail Assembly Kit</a><li><a href=http://phobos/eq/item.php?id=22671>An Enchanted Coif Pattern</a><li><a href=http://phobos/eq/item.php?id=22672>An Enchanted Bracer Pattern</a><li><a href=http://phobos/eq/item.php?id=22673>An Enchanted Sleeves Pattern</a><li><a href=http://phobos/eq/item.php?id=22674>An Enchanted Boots Pattern</a><li><a href=http://phobos/eq/item.php?id=22675>An Enchanted Legplates Pattern</a><li><a href=http://phobos/eq/item.php?id=22676>An Enchanted Gauntlets Pattern</a><li><a href=http://phobos/eq/item.php?id=22677>An Enchanted Tunic Pattern</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Tilania Shadowwalker says </b>'Greetings to you [Your Name]. I welcome you to the Scouts of Tunare training halls. I have seen many scouts pass through my halls with unimaginable abilities and daggers guided by Tunare herself. I cannot say for certain what the future has in store for you. But I can say that wherever your adventures may take you it is always wise to have the proper [training].'
<p><b>You say, </b>'what training'
<br><b>Tilania Shadowwalker says </b>'The training that I speak of is only intended for rogues of Tunare that wish to develop skills that will mold them into the most deadly assassins in all of the lands. If you are a [rogue of Tunare] then I will be happy to explain the training exercises to you. However. if you are not a rogue I suggest you seek training from another house.'
<p><b>You say, </b>'i am a rogue of tunare'
<br><b>Tilania Shadowwalker says </b>'Excellent [Your Name]. let us get started then. Your training will test your fighting and gathering skills respectively. because of the items you will be required to gather all over the Faydark for [magical armor materials].'
<p><b>You say, </b>'what magical armor materials'
<br><b>Tilania Shadowwalker says </b>'First things first. here is your Assassins Mail Assembly Kit. Inside this kit you will combine different magical items. which in certain quantities in your mail kit can create armor materials for specific pieces of Tunarean Scouts Armor. Once you have completed a specific armor material you can then place it in a forge with the applicable pattern to create your piece of armor.[continue]'
<br><b>Tilania Shadowwalker gives you : </b><a href=http://phobos/eq/item.php?id=17365>Assassins Mail Assembly Kit</a>
<p><b>You say, </b>'continue'
<br><b>Tilania Shadowwalker says </b>'Simply tell me what armor piece you [want] to craft and I can provide you with the material recipes and armor patterns for [Coifs][Bracers][Sleeves][Boots][Legplates][Gauntlets] and [Tunics].'
<br><b>Tilania Shadowwalker gives you : </b><a href=http://phobos/eq/item.php?id=17365>Assassins Mail Assembly Kit</a>
<p><b>You say, </b>'i want to craft coifs'
<br><b>Tilania Shadowwalker says </b>'To create your coif material you will need to combine 2 Bricks of Crude Bronze. 1 Pixie Wing . 1 Ruined Wolf Pelt and 1 Bottle in your assembly kit. Once you have created the proper material take it to a forge along with this mold to fashion your very own Coif of the Tunarean Scout.'
<br><b>Tilania Shadowwalker gives you : </b><a href=http://phobos/eq/item.php?id=22671>An Enchanted Coif Pattern</a>
<p><b>You say, </b>'i want to craft bracers'
<br><b>Tilania Shadowwalker says </b>'To create your bracer material you will need to combine 1 Brick of Crude Bronze. 2 Wasp Wings. 1 Faerie Wing and 1 Cask in your assembly kit. Once you have created the proper material take it to a forge along with this mold to fashion your very own Bracer of the Tunarean Scout.'
<br><b>Tilania Shadowwalker gives you : </b><a href=http://phobos/eq/item.php?id=22672>An Enchanted Bracer Pattern</a>
<p><b>You say, </b>'i want to craft sleeves'
<br><b>Tilania Shadowwalker says </b>'To create your sleeves material you will need to combine 2 Bricks of Crude Bronze. 1 Fairy Dust and 1 Royal Jelly and 1 Elven Wine in your assembly kit. Once you have created the proper material take it to a forge along with this mold to fashion your very own Sleeves of the Tunarean Scout.'
<br><b>Tilania Shadowwalker gives you : </b><a href=http://phobos/eq/item.php?id=22673>An Enchanted Sleeves Pattern</a>
<p><b>You say, </b>'i want to craft boots'
<br><b>Tilania Shadowwalker says </b>'To create your boots material you will need to combine 3 Bricks of Crude Bronze. 1 Basilisk Hatchling Hide. 1 Orc Hatchet and 1 Bottle of Milk in your assembly kit. Once you have created the proper material take it to a forge along with this mold to fashion your very own Boots of the Tunarean Scout.'
<br><b>Tilania Shadowwalker gives you : </b><a href=http://phobos/eq/item.php?id=22674>An Enchanted Boots Pattern</a>
<p><b>You say, </b>'i want to craft legplates'
<br><b>Tilania Shadowwalker says </b>'To create your legplates material you will need to combine 4 Bricks of Crude Bronze. 2 Orc Eyes. 1 Orc Scalp and 1 Raw Bamboo in your assembly kit. Once you have created the proper material take it to a forge along with this mold to fashion your very own Legplates of the Tunarean Scout.'
<br><b>Tilania Shadowwalker gives you : </b><a href=http://phobos/eq/item.php?id=22675>An Enchanted Legplates Pattern</a>
<p><b>You say, </b>'i want to craft gauntlets'
<br><b>Tilania Shadowwalker says </b>'To create your gauntlets material you will need to combine 3 Bricks of Crude Bronze. 1 Orc Head. 1 Orc Skull . and 2 Bat Wings in your assembly kit. Once you have created the proper material take it to a forge along with this mold to fashion your very own Gauntlets of the Tunarean Scout.'
<br><b>Tilania Shadowwalker gives you : </b><a href=http://phobos/eq/item.php?id=22676>An Enchanted Gauntlets Pattern</a>
<p><b>You say, </b>'i want to craft tunics'
<br><b>Tilania Shadowwalker says </b>'To create your tunic material you will need to combine 5 Bricks of Crude Bronze. 1 Coyote Skull. 1 Orc Ribcage. 1 Pristine Forest Drakeling Scale. 1 Crushbone Shoulderpads and 1 Golden Bandit Tooth in your assembly kit. Once you have created the proper material take it to a forge along with this mold to fashion your very own Tunic of the Tunarean Scout. Please return to me after you have completed your tunic. for I have one final [favor] to ask of you.'
<br><b>Tilania Shadowwalker gives you : </b><a href=http://phobos/eq/item.php?id=22677>An Enchanted Tunic Pattern</a>
<p><b>You say, </b>'what favor'
<br><b>Tilania Shadowwalker says </b>'I have recently been trying my hand at weaponcrafting and I can say that it is going quite well. Before I can practice my skills however I need some [specific items] that will enable me to begin crafting daggers for our young scouts like yourself that have completed the training exercises.'
<p><b>You say, </b>'what specific items'
<br><b>Tilania Shadowwalker says </b>'In order to craft some more daggers I am in need of 1 Preserved Orc Hide and 2 Rotting Orc Teeth. You can most likely find these items on the vile orcs that inhabit the Faydark and Clan Crushbone of course. Bring me these items and I will reward you with a training dagger of the finest quality.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>