<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=54019>Encrypted Scout Note</a><li><a href=http://phobos/eq/item.php?id=7007>Rusty Dagger</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=54022>Scout's Mask</a><li><a href=http://phobos/eq/item.php?id=7021>Tarnished Dagger</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Tylfon says </b>'So. you think you have what it takes to be a Scout of Tunare? Come back with 2 [gold] and 2 [rusty dagger]s and I'll make it worth your while.'
<p><b>You give Tylfon : </b><a href=http://phobos/eq/item.php?id=54019>Encrypted Scout Note</a>
<br><font color=green><b>Tylfon </b>scans the note and sizes you up with a look.</font>
<br><b>Tylfon says </b>'Very well then, I thank you for assisting us. You have shown great bravery in aiding in this mission. Keep this as a symbol of our friendship.'
<br><b>Tylfon gives you : </b><a href=http://phobos/eq/item.php?id=54022>Scout's Mask</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Tylfon : </b><a href=http://phobos/eq/item.php?id=7007>Rusty Dagger</a>
<br><b>Tylfon says </b>'Well, well. I didn't think you could do it. Here's your cut and don't be surprised that it's not much because it's your first lesson. Remember. the smaller the operation. the bigger the share, and the richest rogues have the tightest lips.'
<br><b>Tylfon gives you : </b><a href=http://phobos/eq/item.php?id=7021>Tarnished Dagger</a>
<br><b>You receive </b> 5sp
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>