<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10262>Vial of Infectious Disease</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10263>Empty Infectious Vial</a></ul></td><td><p><b>You give a female rat : </b><a href=http://phobos/eq/item.php?id=10262>Vial of Infectious Disease</a>
<br><b>a female rat gives you : </b><a href=http://phobos/eq/item.php?id=10263>Empty Infectious Vial</a>
<br><font color=green><b>a female rat </b>injests the virulent substance and becomes ill.</font>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>