<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>Arias2 says </b>'Hail [Your Name]! I represent the people of Gloomingdeep, and was sent here to recruit [help].'
<p><b>You say, </b>'help'
<br><b>Arias2 says </b>'A slave revolt has broken out in the mines, we need you to help them as they escape.'
<br><b>Arias2 says </b>'If you [agree], I will take you with me, as I am about to leave for Gloomingdeep .'
<p><b>You say, </b>'agree'
<br><b>Arias2 says </b>'Good, Let's help the revolt!.'
<br><font color=white><b>The Player moves to zone 189 at -61.7,-123,17.4</b></font>
</td></tr></table>