<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19720>Spire Stone</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Nexus Scion says </b>'Hello [Your Name]. I do not have much time to chat. I must concentrate on the portal that is due to open soon. If you wish to [journey to Luclin], tell me so.'
<p><b>You say, </b>'journey to Luclin'
<br><b>Nexus Scion says </b>'Take this, [Your Name].  You must stay  inside the circle of the Spires, and keep this shard on your person.  Should you need another, simply ask me.  I do not think we will run out of shards any time soon!  If you do NOT wish to travel to Luclin, destroy that which I gave you, or step well away from the Spires lest you be caught up in the portal. It will open soon.'
<br><b>Nexus Scion gives you : </b><a href=http://phobos/eq/item.php?id=19720>Spire Stone</a>
</td></tr></table>