<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>Venenzi Oberzendi says </b>'What is it you want! Can't you see I am gathering reagents for my [master]? If I don't get them for him quickly he might punish me.'
<p><b>You say, </b>'master'
<br><b>Venenzi Oberzendi says </b>'You do not know of my teacher? The great Kazen Fecae! I am one of his illustrious apprentices! If you fancy yourself a necromancer, travel to Lake Rathetear and tell Kazen you wish to study the dark arts.'
<p><b>You say, </b>'reagents'
<br><b>Venenzi Oberzendi says </b>'My master is working on some great project. He's always busy studying an old text he found and murmuring something about following in the footsteps of Miragul.'
<p><b>You say, </b>'task'
<br><font color=green><b>Venenzi Oberzendi </b>looks down at her robes and back at you. 'There is an certain dark elf magician who has decided to wear the same fashion as I have on several occasions. I do not wish to attend another social gathering in Neriak and look exactly the same as another woman. Slay her and bring me her robe, and I will give you my hard earned reagents.'</font>
<p><b>Venenzi Oberzendi checks to see if you have <a href=http://phobos/eq/item.php?id=20643>Twisted Symbol of the Apprentice</a></b><br>
<br><font color=green><b>Venenzi Oberzendi </b>will not accept this item.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>