<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13260>Giant Wasp Venom Sac</a><li><a href=http://phobos/eq/item.php?id=18955>A Sealed Note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12366>never stop chopping</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Conium Darkblade says </b>'You seek Cinium Darkblade, do you? Find me you have. Often I am here. To test my [Wasp Poison], yes. Less Aqua Gobs there now are. Ha!! A true rogue am I with no leader or guild. Just the wind and shadows and much treasure to be had.'
<p><b>You say, </b>'wasp poison'
<br><b>Conium Darkblade says </b>'Giant Wasp Venom made from the Giant Wasp Venom Sacs. An interest in poison we share? Need the insect venom you do. It comes not cheap.
My time is precious, my talent supreme.. 30 Gold is my price and also provide me with three Giant Wasp Venom Sacs.'
<p><b>You say, </b>'the one who once owned it'
<br><b>Conium Darkblade says </b>'The human who gave me the axe remains nameless. We were separated during the battle. If he ever got out of there with all his gold, I do not know. The only clue I know of is the axe itself. The words 'Top of the World' were once printed on its handle.'
<p><b>You say, </b>'top of the world'
<br><b>Conium Darkblade says </b>'High in the pass you can find Top of the World. It sits near the highest bridge. It is one of the newest additions to our community. It specializes in imported items for adventuring.'
<p><b>You give Conium Darkblade : </b><a href=http://phobos/eq/item.php?id=13260>Giant Wasp Venom Sac</a> (x3)
<p><b>You give Conium Darkblade : </b><a href=http://phobos/eq/item.php?id=18955>A Sealed Note</a>
<br><b>Conium Darkblade says </b>'So Lon has sworn allegiance to a temple. What a fool, but he is a skilled fool. My word is my bond and if he asks for the gem, then so be it. Unfortunately I traded it for a much-needed axe. It was in the middle of a dungeon and... well, that is a long story. If you want to get the gem, take this axe back to the [one who once owned it].'
<br><b>Conium Darkblade gives you : </b><a href=http://phobos/eq/item.php?id=12366>never stop chopping</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>