<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=60199>Note for Treanik</a><li><a href=http://phobos/eq/item.php?id=60200>Treanik's Tarnished Axe</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=60201>A Bone Trinket</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Treanik Ireblade says </b>'You not berserker, so you go away. Me no talk to you!'
<p><b>You say, </b>'Hail'
<br><b>Treanik Ireblade says </b>'You not berserker, so you go away. Me no talk to you!'
<p><b>You say, </b>'Hail'
<br><b>Treanik Ireblade says </b>'You not berserker, so you go away. Me no talk to you!'
<p><b>You say, </b>'beast fights'
<p><b>You say, </b>'sense of strategy'
<br><b>Treanik Ireblade says </b>'It do have sense of stragegy. It a creature dat has got smartz wit da magic too. Da way it mixes its abilities is good stuffs. You gots to try to catch it when it eats. It usually comes out when it dark out. And when you kill it, can you get my axe back? Me lost it to dat beast. Plus me needs proof you killed it so me can give you sumtin to give to McArik.'
<p><b>You give Treanik Ireblade : </b><a href=http://phobos/eq/item.php?id=60199>Note for Treanik</a>
<br><b>Treanik Ireblade says </b>'Me hopes you can hold your breath, [Your Name]. Me make sure to stock up before makin' dat long swim. Pesky goblins all over. Treanik must tell dat dere is much more dan pests here to taunt da likes of us. Dere be a beast down dere dat me not killed yet. Me much younger dan you, but me learn how dat [beast fights] -- it smarter dan da average creature, you know. Don't be fooled.'
<p><b>You give Treanik Ireblade : </b><a href=http://phobos/eq/item.php?id=60200>Treanik's Tarnished Axe</a>
<br><b>Treanik Ireblade says </b>'My axe! Me so happy! You are big force to be rekoned with, [Your Name]. Me wasn't sure... but now, look at you, like spiroc fluffing feathers. McArik be so pleased! Take dis amulet me made. I know not much, but me swore to McArik that anyone who passes dis test would get a trinket from me.'
<br><b>Treanik Ireblade gives you : </b><a href=http://phobos/eq/item.php?id=60201>A Bone Trinket</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>