<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13134>Hurrieta's Bloody Dress</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2108>Patchwork Sleeves</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=21>Bloodsabers</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a><li><a href=http://phobos/eq/faction.php?id=257>Priests of Life</a><li><a href=http://phobos/eq/faction.php?id=183>Knights of Thunder</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Garuc Anehm says </b>'Welcome to the Shrine of Bertoxxulous! You appear to be [new to the shrine]. I do not remember seeing you around.'
<p><b>You say, </b>'i am new to the shrine.'
<br><b>Garuc Anehm says </b>'New blood to spread Bertoxxulous' disease? We presently need the help of a [young shadowknight]. There are certain deeds which must be carried out.'
<p><b>You say, </b>'i am a young shadowknight.'
<br><b>Garuc Anehm says </b>'Then let your supreme task be the extermination of the Priests of Life. Know that they threaten the will of our Lord Bertoxxulous. For every fallen paladin and cleric of the Temple of Life. you shall rise within our ranks.  So... do you [loathe paladins]?'
<p><b>You say, </b>'i loathe paladins.'
<br><b>Garuc Anehm says </b>'As do we all. The paladins of Qeynos come from either the Hall of Thunder or the Temple of Life. We have put a bounty upon their heads. Destroy these knights and return either the Order of Thunder or the prayer beads of these inferior men. There has even been a report from [Commander Kane].'
<p><b>You say, </b>'commander kane?'
<br><b>Garuc Anehm says </b>'Kane Bayle is the Commander of the Qeynos Guard. He has found it advantageous to befriend the Bloodsabers. We share a [common goal]. He assists us in many ways. He has some new information to reveal.  Go and tell him you are a Bloodsaber. Do not speak with him while he is on duty!!'
<p><b>You say, </b>'common goal?'
<br><b>Garuc Anehm says </b>'Kane Bayle and the leaders of this shrine all wish to overthrow the rule of Antonius Bayle. He, for power, and we for the glory of Bertoxxulous. From this city, our diseased lord shall appear and tread across the land spitting death from his mouth and deforming the land. His glory shall be eternal!'
<p><b>You give Garuc Anehm : </b><a href=http://phobos/eq/item.php?id=13134>Hurrieta's Bloody Dress</a>
<br><b>Garuc Anehm says </b>'Excellent work. You have done us a favour as well; meddlesome Ironprides. Take this reward.'
<br><b>Garuc Anehm gives you : </b><a href=http://phobos/eq/item.php?id=2108>Patchwork Sleeves</a>
<br><b>You receive </b> 9sp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=257>Priests of Life</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=183>Knights of Thunder</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=21>Bloodsabers</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>