<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Kurne Rextula says </b>'Welcome to the new order of life. the life of service to our diseased Lord. Bertoxxulous.  Did you encounter any of my [pets] on the way here?  I hope not.'
<p><b>You say, </b>'what pets?'
<br><b>Kurne Rextula says </b>'My pets are the skeleton guardians of these catacombs.  Some have been behaving erratically since the arrival of [Drosco].'
<p><b>You say, </b>'who is drosco?'
<br><b>Kurne Rextula says </b>'Drosco used to be a loyal member of our shrine. until we learned the truth.  The truth was that he was a mole from the Knights of Thunder.  It appears they are assisting the Temple of Life in their pursuit of our eradication.  Drosco was apprehended and boiled alive.  I turned his boiled body into a zombie to march these halls.  Now he must be stopped.  He has begun to [compromise the shrine's location].'
<p><b>You say, </b>'how will he compromise the shrine'
<br><b>Kurne Rextula says </b>'The problem is. he was strong in Karana's faith.  And as sometimes is the case. there is a resonance from his deity.  This causes him to wander in and out of our hidden shrine and I believe it also interferes with my control of the other pets.  Please find him and destroy him.  Bring me back the note I placed upon his body.  Go!!'
</td></tr></table>