<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28014>Stanos' Pouch</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Malka Rale says </b>'Whew! I thought you were one of Hanns' goons. These sewers are a mess, you never know what is going to turn up next. I really wish I could get out of here.'
<p><b>You say, </b>'i will help'
<br><b>Malka Rale says </b>'Ok! I am trusting you. Take this pouch to Vilnius in West Karana. Last word I had from him, he was hanging out near one of the bandit camps. Be careful, since he does not know you. Just give him the puch, and tell him I was..delayed. While you are doing that, I will be thinking of a way to get out of this slimehole. With any luck, the Circle will learn the puch is out of Qeynos, and will assume I got away. That means they won't be looking for me here.'
<br><b>Malka Rale gives you : </b><a href=http://phobos/eq/item.php?id=28014>Stanos' Pouch</a>
</td></tr></table>