<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10626>Empty Ink Vial</a></ul></td><td><p><b>You say, </b>'ink of the dark'
<br><b>Reania Jukle says </b>'Ink of the Dark, you say? That isn't an everyday item, you know. In fact, I can't remember the last time someone requested it. I have given up keeping any here with me. You are going to need to find your own supply now. Sorry.'
<p><b>You say, </b>'where can i find the ink'
<br><b>Reania Jukle says </b>'The ink is the blood of a dark scribe. Tempt him and give him this vial. He should cooperate.'
<br><b>Reania Jukle gives you : </b><a href=http://phobos/eq/item.php?id=10626>Empty Ink Vial</a>
</td></tr></table>