<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20207>Note to Torin Krentar</a><li><a href=http://phobos/eq/item.php?id=20199>Refined Bloodsaber Mace</a><li><a href=http://phobos/eq/item.php?id=19946>Giant King Snake Skin</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19633>Crude Gauntlets Mold</a><li><a href=http://phobos/eq/item.php?id=19634>Crude Boot Mold</a><li><a href=http://phobos/eq/item.php?id=19632>Crude Bracer Mold</a><li><a href=http://phobos/eq/item.php?id=19631>Crude Helm Mold</a><li><a href=http://phobos/eq/item.php?id=19636>Crude Greaves Mold</a><li><a href=http://phobos/eq/item.php?id=19635>Crude Vambrace Mold</a><li><a href=http://phobos/eq/item.php?id=19637>Crude Breastplate Mold</a><li><a href=http://phobos/eq/item.php?id=17124>Mail Assembly Kit</a><li><a href=http://phobos/eq/item.php?id=20261>Pestilence Priest Mace</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Torin Krentar says </b>'The dead are watching you young one, yet you are safe under their otherworldly gaze. Is there something I can do for you?'
<p><b>You say, </b>'gauntlet'
<br><b>Torin Krentar says </b>'To assemble pestilence priest gauntlets you will need to obtain two bricks of crude iron and smelt them in a forge with a Water Flask and this crude Gauntlet Mold. Once that is done combine the Crude Iron Gauntlets with a Large King Snake Skin and two Gnoll Finger Bones in the Mail Assembly Kit.'
<br><b>Torin Krentar gives you : </b><a href=http://phobos/eq/item.php?id=19633>Crude Gauntlets Mold</a>
<p><b>You say, </b>'boot'
<br><b>Torin Krentar says </b>'To assemble pestilence priest boots you will need to obtain two bricks of crude iron and smelt them in a forge with a Water Flask and this crude Boot Mold. Once that is done combine the Crude Iron Boots with two Large King Snake Skins, and two Gnoll Foot Bones in the Mail Assembly Kit.'
<br><b>Torin Krentar gives you : </b><a href=http://phobos/eq/item.php?id=19634>Crude Boot Mold</a>
<p><b>You say, </b>'bracer'
<br><b>Torin Krentar says </b>'To assemble a pestilence priest bracer you will need to obtain a brick of crude iron and smelt it in a forge with a Water Flask and this Crude Bracer Mold. Once that is done, combine the Crude Iron Bracer with a Large King Snake Skin and a Gnoll Ulna Bone in the Mail Assembly Kit.'
<br><b>Torin Krentar gives you : </b><a href=http://phobos/eq/item.php?id=19632>Crude Bracer Mold</a>
<p><b>You say, </b>'helm'
<br><b>Torin Krentar says </b>'To assemble a pestilence priest helm you will need to obtain two bricks of crude iron and smelt them in a forge with a Water Flask and this Crude Helm Mold. Once that is done combine the Crude Iron Helm with a Large King Snake Skin and a Gnoll Skull in the Mail Assembly Kit.'
<br><b>Torin Krentar gives you : </b><a href=http://phobos/eq/item.php?id=19631>Crude Helm Mold</a>
<p><b>You say, </b>'greaves'
<br><b>Torin Krentar says </b>'To assemble pestilence priest greaves you will need to obtain two bricks of crude iron and smelt them in a forge with a Water Flask and this Crude Greaves Mold. Once that is done combine the Crude Iron Greaves with two Giant King Snake Skins and two Gnoll Tibia in the Mail Assembly Kit.'
<br><b>Torin Krentar gives you : </b><a href=http://phobos/eq/item.php?id=19636>Crude Greaves Mold</a>
<p><b>You say, </b>'vambrace'
<br><b>Torin Krentar says </b>'To assemble pestilence priest vambraces you will need to obtain two bricks of crude iron and smelt them in a forge with a Water Flask and this Crude Vambrace Mold. Once that is done combine the Crude Iron Vambraces with a Giant King Snake Skin and two Gnoll Humerus Bones in the Mail Assembly Kit.'
<br><b>Torin Krentar gives you : </b><a href=http://phobos/eq/item.php?id=19635>Crude Vambrace Mold</a>
<p><b>You say, </b>'breastplate'
<br><b>Torin Krentar says </b>'To assemble a pestilence priest breastplate you will need to obtain four bricks of crude iron and smelt them in a forge with a Water Flask and this Crude Breastplate Mold. Once that is done combine the Crude Iron Breastplate with a Giant King Snake Skin, a Gnoll Sternum, and a Gnoll Ribcage in the Mail Assembly Kit.'
<br><b>Torin Krentar gives you : </b><a href=http://phobos/eq/item.php?id=19637>Crude Breastplate Mold</a>
<p><b>You give Torin Krentar : </b><a href=http://phobos/eq/item.php?id=20207>Note to Torin Krentar</a>
<br><b>Torin Krentar says </b>'Well met young disciple of Bertoxxulous. Perhaps one day you shall serve the Plague Lord in his realm, but for now you will serve the Bloodsabers, his mortal agents on Norrath. The armor you seek must be assembled using this Mail Assembly Kit. The materials necessary to construct the armor vary depending on the piece being crafted. Do you wish to craft [Gauntlets] of the Pestilence Priests, [Boots] of the Pestilence Priests, a [Bracer] of the Pestilence Priests, a [Helm] of the Pestilence Priests, [Greaves] of the Pestilence Priests, [Vambraces] of the Pestilence Priests, or a [Breastplate] of the Pestilence Priests?'
<br><b>Torin Krentar gives you : </b><a href=http://phobos/eq/item.php?id=17124>Mail Assembly Kit</a>
<p><b>You give Torin Krentar : </b><a href=http://phobos/eq/item.php?id=20199>Refined Bloodsaber Mace</a>, <a href=http://phobos/eq/item.php?id=19946>Giant King Snake Skin</a>
<br><b>Torin Krentar says </b>'Well done, [Your Name]. Now go, spread the gifts of the Plague Lord upon the world.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Torin Krentar gives you : </b><a href=http://phobos/eq/item.php?id=20261>Pestilence Priest Mace</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>