<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>A Wandering Spirit says </b>'groans in extreme anguish. '[Help] me.''
<p><b>You say, </b>'what help'
<br><b>A Wandering Spirit says </b>'My resting grounds have been desecrated. I now lie awake unable to rest with my fellow brethren. My soul is bound to this area for all of eternity. Until my [belongings] are brought back I cannot rest.'
<p><b>You say, </b>'what belongings'
<br><b>A Wandering Spirit says </b>'Many different things were taken. but I'm mainly concerned with my [amulet] and my family's crescent symbol. Bring these articles back into my possession and I'll return back to my state of rest.'
<p><b>You say, </b>'what amulet'
<br><b>A Wandering Spirit says </b>'The amulet was given to me after passing the Trials many many generations ago. It is a part of every soldier who has passed the trials. it is a part of my very being.'
</td></tr></table>