<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=25796>A piece of the crystalline globe</a><li><a href=http://phobos/eq/item.php?id=25797>A piece of the crystalline globe</a><li><a href=http://phobos/eq/item.php?id=25798>A piece of the crystalline globe</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=25596>A Crystalline Globe</a></ul></td><td><p><b>You say, </b>'hail'
<p><b>You say, </b>'busy'
<p><b>You say, </b>'help'
<p><b>You say, </b>'mission'
<p><b>You say, </b>'war'
<p><b>You say, </b>'willing'
<p><b>You say, </b>'hail'
<p><b>You give Captain Ryglot Cupperhide : </b><a href=http://phobos/eq/item.php?id=25796>A piece of the crystalline globe</a>, <a href=http://phobos/eq/item.php?id=25797>A piece of the crystalline globe</a>, <a href=http://phobos/eq/item.php?id=25798>A piece of the crystalline globe</a>
<br><b>Captain Ryglot Cupperhide says </b>'Confident you are.  We all have agreed that since you are so willing to help, we will give you this Crystaline Globe.  It is said to open the lair of Aerin`Dar.  Good luck, [Your Name].'
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<br><b>Captain Ryglot Cupperhide gives you : </b><a href=http://phobos/eq/item.php?id=25596>A Crystalline Globe</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>