<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Katizm Banum says </b>'Hail [Your Name]. You can just call me Banum. Just [exploring] are you?'
<p><b>You say, </b>'i am exploring'
<br><b>Katizm Banum says </b>'Be careful out there. I have heard of the glass playing tricks on people's eyes.'
<p><b>You say, </b>'what exploring'
<br><b>Katizm Banum says </b>'Be careful out there. I have heard of the glass playing tricks on people's eyes.'
</td></tr></table>