<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=25598>A Razorfiend's Heart</a><li><a href=http://phobos/eq/item.php?id=25597>A Crystalline Spider's Heart</a><li><a href=http://phobos/eq/item.php?id=25599>A Planarian Larvae's Heart</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Paralin Notion says </b>'You're either [brave], or you're [stupid]'
<p><b>You say, </b>'brave'
<br><b>Paralin Notion says </b>'That you are.  Perhaps you'd be interested in helping our [company]'
<p><b>You say, </b>'company'
<br><b>Paralin Notion says </b>'We're a part of the Battalion of Marr. We're soldiers from Che Virtuson. We were dispatched to this part of the Plane of Valor to eliminate an age old target. Unfortunately, due to some recent events our mission has been placed on hold and our [squad] has been asked to remain behind.'
<p><b>You say, </b>'squad'
<br><b>Paralin Notion says </b>'We are a part of Ducee Tapferson. Our squad is known for our bravery. We were successful in capturing this [razorfiend] earlier today. You've shown some bravery as well my friend and that is the reason I request your [assistance].'
<p><b>You say, </b>'razorfiend'
<br><b>Paralin Notion says </b>'These vile beasts live in the caves west of here.'
<p><b>You say, </b>'assistance'
<br><b>Paralin Notion says </b>'Man of us here are anxious to leave.  May wish to regroup with the rest of our company.  Others wish to go back to the Halls to complete the [Trials]'
<p><b>You say, </b>'trials'
<br><b>Paralin Notion says </b>'The Trials are overseen by the Heroes of Marr. It's these Trials that allow us to rise in rank. Only those who have passed the trials are able to enter the Temple of Marr. Now if you wish to aid us I must ask you to do a few [things].'
<p><b>You say, </b>'things'
<br><b>Paralin Notion says </b>'You must find the Master Sergeant and tell him that you are here to [aid the cause].'
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<p><b>You say, </b>'hail'
<br><b>Paralin Notion says </b>'You're either [brave], or you're [stupid]'
<p><b>You say, </b>'prove'
<p><b>You say, </b>'hail'
<br><b>Paralin Notion says </b>'You're either [brave], or you're [stupid]'
<p><b>You give Paralin Notion : </b><a href=http://phobos/eq/item.php?id=25598>A Razorfiend's Heart</a>, <a href=http://phobos/eq/item.php?id=25597>A Crystalline Spider's Heart</a>, <a href=http://phobos/eq/item.php?id=25599>A Planarian Larvae's Heart</a>
<br><b>Paralin Notion says </b>'Very good my friend. You've definitely proven yourself. Find the Master Sergeant. He should be able to help you this time.'
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>