<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Sergeant Lusahn Matthers says </b>'Greetings [Your Name].  I have a little time to chat. we are not due in the [field] for a while.  What may I help you with?'
<p><b>You say, </b>'what field'
<br><b>Sergeant Lusahn Matthers says </b>'The Glassy Wastelands.  We work hard to keep the [plight] back from the rest of the Forest. but I fear that is a losing battle.'
<p><b>You say, </b>'what plight'
<br><b>Sergeant Lusahn Matthers says </b>'I am afraid that I am not at liberty to go into depth. even with the little that we know.  What I can tell you is that the Wasteland is dangerous; the glass manages to hide terrors that few men outside these walls could bear to speak of. much less see.  If you choose to journey know that we will offer you little protection.'
</td></tr></table>