<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>#AriasORG says </b>'Thank you for helping our rebellion. If you wish to [escape] at any time simply let me know.'
<p><b>You say, </b>'escape'
<br><b>#AriasORG says </b>'Here I'll show you how to get out. But remember once you leave you can't get back in, or you jepordize our whole operation.'
<br><font color=grey><i>A global variable is unset at this point.</font></i>
<br><font color=white><b>The Player moves to zone 202 at 337.91,335.6,-126.5</b></font>
</td></tr></table>