<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=56001>Cracked Finger Bone</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>#AriasLoY says </b>'Thank you for helping our rebellion. If you wish to [escape] at any time simply let me know.'
<br><font color=green><b>#AriasLoY </b>sighs...</font>
<br><b>#AriasLoY says </b>'Or perhaps you have become bored with the same adventures and prefer something [different].'
<p><b>You say, </b>'escape'
<br><b>#AriasLoY says </b>'Here, I'll show you how to get out. But remember, once you leave you can't get back in, or you jepordize our whole operation.'
<br><b>#AriasLoY says </b>'Are you [sure] you want to leave?'
<p><b>You say, </b>'different'
<br><b>#AriasLoY says </b>'Aye, different; a world of [pirates] and [treasure] ... '
<p><b>You say, </b>'pirates'
<br><b>#AriasLoY says </b>'There are many evil pirates there, nasty place to be. I could [send] you there, with proper [status], although you'd never be able to return here'
<p><b>You say, </b>'treasure'
<br><b>#AriasLoY says </b>'Many riches those pirates carry, you could attain an impressive [status] if you weren't killed first'
<p><b>You say, </b>'status'
<br><b>#AriasLoY says </b>'I can give you a compatible starting-level, with a few extra spells, once you ge there.'
<p><b>You say, </b>'prove'
<br><b>#AriasLoY says </b>'Bring me a part of Krenshin's bones, and I'll know you have mastered these mines, send you on your way...'
<p><b>You say, </b>'sure'
<br><b>#AriasLoY says </b>'Good luck!'
<br><font color=grey><i>A global variable is unset at this point.</font></i>
<br><font color=white><b>The Player moves to zone 202 at 337.91,335.6,-126.5</b></font>
<p><b>You say, </b>'send'
<br><b>#AriasLoY says </b>'I can send you, but I worry you might not survive, due to lack of skills. You'd have to [prove] yourself to me first'
<p><b>You say, </b>'send'
<br><b>#AriasLoY says </b>'I can send you, but I worry you might not survive, due to lack of skills. You'd have to [prove] yourself to me first'
<p><b>You give #AriasLoY : </b><a href=http://phobos/eq/item.php?id=56001>Cracked Finger Bone</a>
<br><font color=grey><i>A global variable is unset at this point.</font></i>
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<br><b>#AriasLoY says </b>'You have done well! I can now [send] you to The Gulf of Gunthak at your request'
</td></tr></table>