<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=59955>Gloomingdeep Mushrooms</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=59765>Shimmering Vial of Vigor</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>189016 says </b>'Maps are a wonderful thing you know. Any time you find yourself lost you can hit BACKSPACE to view your map , try it.'
<br><b>189016 says </b>'Come back later if you have time to [help].'
<p><b>You say, </b>'help'
<br><b>189016 says </b>'Greetings [Your Name]. I've been trying to find some Gloomingdeep mushrooms for some potions I'm making, but I can't seem to find any. If you happen upon some I can make you a potion if you bring one to me.'
<p><b>You give 189016 : </b><a href=http://phobos/eq/item.php?id=59955>Gloomingdeep Mushrooms</a>
<br><b>189016 says </b>'Excellent, Thank you, [Your Name]. Now I can finish my potions. Here take this sample I made earlier.'
<br><b>189016 gives you : </b><a href=http://phobos/eq/item.php?id=59765>Shimmering Vial of Vigor</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>