<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=item1></a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=7021>Tarnished Dagger</a><li><a href=http://phobos/eq/item.php?id=6030>Tarnished Mace</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>189034 says </b>'Weapons are one of your main forms of combat. And a faster weapon can make the battle go in your favor. While helping out here , I found enough stones to sharpen weapons. If youd like I can sharpen your's , simply hand it to me.'
<p><b>You give 189034 : </b><a href=http://phobos/eq/item.php?id=9997>Dagger*</a>
<br><b>189034 gives you : </b><a href=http://phobos/eq/item.php?id=7021>Tarnished Dagger</a>
<p><b>You give 189034 : </b><a href=http://phobos/eq/item.php?id=9999>Club*</a>
<br><b>189034 gives you : </b><a href=http://phobos/eq/item.php?id=6030>Tarnished Mace</a>
</td></tr></table>