<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=54603>Flutterwing's Unhatched Sibling</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Flutterwing says </b>'Hello there [Your Name]. Please don't hurt me, I may be the last of my lineage since the [theft]'
<p><b>You say, </b>'theft'
<br><font color=green><b>Flutterwing </b>saddens and lets out a sigh.</font>
<br><b>Flutterwing says </b>'My unhatched sibling was stolen from our nest by a nasty kobold. I'm afraid the worst might have happened. Would you please search for the [egg] during your journeys in the mines?'
<p><b>You say, </b>'egg'
<br><b>Flutterwing says </b>'Well of course an egg . How do you think us dragons are born? If you would return this egg to me or what is left, I will reward you.'
<p><b>You give Flutterwing : </b><a href=http://phobos/eq/item.php?id=54603>Flutterwing's Unhatched Sibling</a>
<br><font color=green><b>Flutterwing </b>beams with glee.</font>
<br><b>Flutterwing says </b>'Oh [Your Name] how can I ever repay such kindness. I will not be alone in this dreadful place after all. Please accept this small token.'
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>