<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13090>Clump of Dough</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13087>Bottle of Milk</a><li><a href=http://phobos/eq/item.php?id=13193>Cup of Flour</a><li><a href=http://phobos/eq/item.php?id=13088>Snake Egg</a><li><a href=http://phobos/eq/item.php?id=3395>Fang Shaped Stone Earring</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Frizznik Hailstorm says </b>'Hello there [Your Name]. The name's Frizznik and I'm in charge of making food for the revolt. Most of what I make starts with the basics. I don't have the time to make the basic items and the final products. Let me know if you are interested in [assisting] me with making dough.'
<p><b>You say, </b>'assisting'
<br><font color=green><b>Frizznik Hailstorm </b>eyes you up and down.</font>
<br><b>Frizznik Hailstorm says </b>'Make sure you buy a mixing bowl and come see me when you are [ready].'
<p><b>You say, </b>'ready'
<br><b>Frizznik Hailstorm says </b>'Good enough. Now, combine these ingredients in your mixing bowl and return to me all the clumps of dough you can. If you give me four clumps of dough, I'll reward your assistance.'
<br><b>Frizznik Hailstorm gives you : </b><a href=http://phobos/eq/item.php?id=13087>Bottle of Milk</a>
<br><b>Frizznik Hailstorm gives you : </b><a href=http://phobos/eq/item.php?id=13193>Cup of Flour</a>
<br><b>Frizznik Hailstorm gives you : </b><a href=http://phobos/eq/item.php?id=13088>Snake Egg</a>
<p><b>You give Frizznik Hailstorm : </b><a href=http://phobos/eq/item.php?id=13090>Clump of Dough</a> (x4)
<br><b>Frizznik Hailstorm says </b>'I appreciate your assitance in getting everyone fed. Please take this as a small token of my eternal appreciation.'
<br><b>Frizznik Hailstorm gives you : </b><a href=http://phobos/eq/item.php?id=3395>Fang Shaped Stone Earring</a>
</td></tr></table>