<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=14018>A Spider Venom Sac</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=77780>Distillate of Celestial Healing II</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Guard Maddoc says </b>'Queen Gloomfang spawns dozens of eggs every day. She must be stopped before the Kobolds can train and raise any more spiderlings. Venture into the spider tunnels and kill Queen Gloomfang. She lairs on a ledge high above the other spiders. You will recognize her perch by the thick stench of poison and decay. Once you destroy her, I can use an extract from her chitin to brew you a protective potion.'
<p><b>You give Guard Maddoc : </b><a href=http://phobos/eq/item.php?id=14018>A Spider Venom Sac</a>
<br><b>Guard Maddoc gives you : </b><a href=http://phobos/eq/item.php?id=77780>Distillate of Celestial Healing II</a>
<br><b>Guard Maddoc gives you : </b><a href=http://phobos/eq/item.php?id=77780>Distillate of Celestial Healing II</a>
<br><b>Guard Maddoc gives you : </b><a href=http://phobos/eq/item.php?id=77780>Distillate of Celestial Healing II</a>
<br><b>Guard Maddoc gives you : </b><a href=http://phobos/eq/item.php?id=77780>Distillate of Celestial Healing II</a>
<br><b>Guard Maddoc gives you : </b><a href=http://phobos/eq/item.php?id=77780>Distillate of Celestial Healing II</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>