<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=54604>Gloomingdeep Violet</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Guard Rahtiz says </b>'The Gloomingdeep spider tamer is able to brew anti-venom from a rare flower that grows in gloomingdeep. If we had this flower,we may be able to use it to save the lives of our comardes.'
<p><b>You give Guard Rahtiz : </b><a href=http://phobos/eq/item.php?id=54604>Gloomingdeep Violet</a>
<br><b>Guard Rahtiz says </b>'Well done [Your Name]! We shall start brewing right away.'
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>