<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=59968>Poxan's Sword</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=59969>Kobold Leather Mask</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Poxan  </b>sighs heavily as he peers into the murky water.</font>
<br><b>Poxan  says </b>'This is terrible, I've dropped my sword into the water and I can't swim! I don't suppose you could get it back for me [Your Name]? I can't very well fight kobolds without a sword.'
<br><b>Poxan  says </b>'While you're at it, you can brush up on your swimming skills here. Simply jump into the lake and use your direction keys to swim back and forth. You can also up PAGEUP to swim up and PAGEDOWN to swim down. Give it a try.'
<p><b>You give Poxan  : </b><a href=http://phobos/eq/item.php?id=59968>Poxan's Sword</a>
<br><b>Poxan  says </b>'Excellent, Thank you, . Now I can fight along side the revolt against the kobolds. Here take this. I found it in the tunnels earlier. You might need it.'
<br><b>Poxan  gives you : </b><a href=http://phobos/eq/item.php?id=59969>Kobold Leather Mask</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>