<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Rashere Al-Ayahd says </b>'Did you know that when you die your soul can be recalled to your last bind spot? Well it can , and that is exactly my purpose on this world. I can [bind] your soul so that after death you will be brought to life again in this spot.'
<p><b>You say, </b>'bind'
<br><font color=brown><b>Rashere Al-Ayahd casts a spell : </b><a href=http://phobos/eq/spell.php?id=35>Bind Affinity</a>.</font>
</td></tr></table>