<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>Rytan says </b>'Hello. There are many things one can do with spells and you should take the time to learn them. If you wish I can [bless] you with the power of the gods using one such spell.'
<p><b>You say, </b>'bless'
<br><b>Rytan says </b>'Very well ......... there you have been blessed.'
<br><font color=brown><b>Rytan casts a spell : </b><a href=http://phobos/eq/spell.php?id=5150>Gloomingdeep Guard</a>.</font>
</td></tr></table>