<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1908>Jualicn's Token</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1895>Rune of Bleve</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a><li><a href=http://phobos/eq/faction.php?id=362>Yelinak</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Derasinal says </b>'It is not often that I see strangers in these dangerous lands. Perhaps you are the chosen that Jualicn speaks of that will aid us in our battle against the foul giants. I do not believe you would be here if you were not in need of my sacred rune.'
<p><b>You give Derasinal : </b><a href=http://phobos/eq/item.php?id=1908>Jualicn's Token</a>
<br><b>Derasinal says </b>'I have given you the Rune of Bleve, to assist you in your research for the once lost magic against the Kromzek. I hope that you can make good use of it, for it is very sacred to me. May Veeshan guide your path!'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=362>Yelinak</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Derasinal gives you : </b><a href=http://phobos/eq/item.php?id=1895>Rune of Bleve</a>
<br><b>Derasinal says </b>'I have no need for this item [Your Name], you can have it back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>