<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1908>Jualicn's Token</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1896>Rune of Concentration</a><li><a href=http://phobos/eq/item.php?id=1908>Jualicn's Token</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a><li><a href=http://phobos/eq/faction.php?id=362>Yelinak</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Draazak says </b>'Greetings, [Your Name]. It cannot be that you would present yourself before me without reason. What brings you to these lands on this day? Please be quick for I have many ancient runes I must study.'
<p><b>You give Draazak : </b><a href=http://phobos/eq/item.php?id=1908>Jualicn's Token</a>
<br><b>Draazak says </b>'[Your Name], whom Relinar found to be necessary for the success of the magic against those foul giants. I present this Rune of Concentration to you with faith that you are trusted amongst us or you would not have been sent to me. Make haste so that no time is wasted in extracting revenge for their past transgressions.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=362>Yelinak</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Draazak gives you : </b><a href=http://phobos/eq/item.php?id=1896>Rune of Concentration</a>
<br><b>Draazak gives you : </b><a href=http://phobos/eq/item.php?id=1908>Jualicn's Token</a>
<br><b>Draazak says </b>'I have no need for this item, [Your Name], you can have it back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>