<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1908>Jualicn's Token</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1893>Rune of Eradication</a><li><a href=http://phobos/eq/item.php?id=1908>Jualicn's Token</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a><li><a href=http://phobos/eq/faction.php?id=362>Yelinak</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Entariz says </b>'Greetings, [Your Name]. I have heard that one is amongst us in the lands which will aid us in our cause. If you are the one that seeks my ancient rune for your studies please make sure it is not used in vain. I do not talk to many that pass through here and I feel in my heart that it is you that shall help us.'
<p><b>You give Entariz : </b><a href=http://phobos/eq/item.php?id=1908>Jualicn's Token</a>
<br><b>Entariz says </b>'Ah of course, [Your Name]. You will need a Rune of Eradication for your lexicon. We are counting on your loyalty. Remember that you will need to bring the teachings of Relinar to Lawyla for further instructions, as she requires them to pass on the magic to those worthy of it. I bid you farewell, [Your Name].'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=362>Yelinak</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Entariz gives you : </b><a href=http://phobos/eq/item.php?id=1893>Rune of Eradication</a>
<br><b>Entariz gives you : </b><a href=http://phobos/eq/item.php?id=1908>Jualicn's Token</a>
<br><b>Entariz says </b>'I have no need for this item [Your Name], you can have it back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>