<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=27260>Frakadar's Talisman</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=27261>Shroud of the Dar Brood</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a><li><a href=http://phobos/eq/faction.php?id=362>Yelinak</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Harla Dar says </b>'I do not have time for you now, Gaulven. My son is lost, and you can not help me.'
<p><b>You say, </b>'son'
<br><b>Harla Dar says </b>'Have you seen him? I must find him, he has been gone far to long! If you have harmed him, I will slay you and all of your
race! Tell me where he is!'
<p><b>You give Harla Dar : </b><a href=http://phobos/eq/item.php?id=27260>Frakadar's Talisman</a>
<br><b>Harla Dar says </b>'This...this is not what I had hoped for. My whelp is lost, but I take some comfort in knowing that you helped destroy his killer. Zlandicar has been a blight upon our race since the beginning. Here is your reward, as I promised. It will protect you in more ways than are obvious. Leave me now, it is time to mourn.'
<br><b>Harla Dar gives you : </b><a href=http://phobos/eq/item.php?id=27261>Shroud of the Dar Brood</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=362>Yelinak</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>