<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1908>Jualicn's Token</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1894>Rune of Revenge</a><li><a href=http://phobos/eq/item.php?id=1908>Jualicn's Token</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a><li><a href=http://phobos/eq/faction.php?id=362>Yelinak</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Ionat says </b>'Hello [Your Name]. It is good to see that you have traveled so far to be in my presence. I do believe that you are the one chosen to aid us in our fight against the giants. If you are then I am sure that you will need my rune for your research.'
<p><b>You give Ionat : </b><a href=http://phobos/eq/item.php?id=1908>Jualicn's Token</a>
<br><b>Ionat says </b>'Take this Rune of Revenge, [Your Name]. You will need it to extract retribution in remembrance of our dear Hsagra. I thank you for your contributions to our cause. It is good to have you amongst our ranks.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=362>Yelinak</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Ionat gives you : </b><a href=http://phobos/eq/item.php?id=1894>Rune of Revenge</a>
<br><b>Ionat gives you : </b><a href=http://phobos/eq/item.php?id=1908>Jualicn's Token</a>
<br><b>Ionat says </b>'I have no need for this item [Your Name], you can have it back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>