<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=24069>Full Crate of Fusible Ore</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18290>Fusibility Study: Part 1</a><li><a href=http://phobos/eq/item.php?id=18293>Fusibility Study: Part 2</a><li><a href=http://phobos/eq/item.php?id=18294>Fusibility Study: Part 3</a><li><a href=http://phobos/eq/item.php?id=17408>Empty Fusible Ore Crate</a><li><a href=http://phobos/eq/item.php?id=24070>Strength of the Elements</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Makil Rargon says </b>'Greetings. I am Makil Rargon, an esteemed assistant to the great wizard [Al'Kabor]. What can I help you with?'
<p><b>You say, </b>'al'kabor'
<br><b>Makil Rargon says </b>'Al'Kabor is the most powerful wizard on all of Norrath. He is currently back to his Combine Empire research. Being his most trusted assistant, he assigned me to follow up on his fusibility [research] findings. Do you have any information to offer?'
<p><b>You say, </b>'research'
<br><b>Makil Rargon says </b>'Ah. Yes, his fusibility research. Al'Kabor has been studying the melting point of minerals. Here, take this journal. It explains what fusibility is. Over the last few years, he has conducted several tests on [fusible ores].'
<br><b>Makil Rargon gives you : </b><a href=http://phobos/eq/item.php?id=18290>Fusibility Study: Part 1</a>
<p><b>You say, </b>'fusible ores'
<br><b>Makil Rargon says </b>'An ore is considered fusible if it can be melted. Now, this book explains the most unique forms of fusible ore that the master has conducted [experiments] on.'
<br><b>Makil Rargon gives you : </b><a href=http://phobos/eq/item.php?id=18293>Fusibility Study: Part 2</a>
<p><b>You say, </b>'experiments'
<br><b>Makil Rargon says </b>'So far his research has been quite successful. This journal explains what he has been able to accomplish. He has managed to create several magical items including an artifactual scepter of great power. While only he can grant permission to a worthy wizard to possess the artifact, if you are willing to help me complete a [fusibility test], I can offer you another item of great strength against the elements.'
<br><b>Makil Rargon gives you : </b><a href=http://phobos/eq/item.php?id=18294>Fusibility Study: Part 3</a>
<p><b>You say, </b>'fusibility test'
<br><b>Makil Rargon says </b>'Very well then . . . Fill this Empty Fusible Ore Crate up with four different fusible ores then seal it. Bring me back the Full Crate of Fusible Ore and I will use the compound to create a magical item that was developed by Master Al'Kabor.'
<br><b>Makil Rargon gives you : </b><a href=http://phobos/eq/item.php?id=17408>Empty Fusible Ore Crate</a>
<p><b>You give Makil Rargon : </b><a href=http://phobos/eq/item.php?id=24069>Full Crate of Fusible Ore</a>
<br><b>Makil Rargon says </b>'Well done, [Your Name]. Here is your reward.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Makil Rargon gives you : </b><a href=http://phobos/eq/item.php?id=24070>Strength of the Elements</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>