<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=25106>Bekerak's New Spear</a><li><a href=http://phobos/eq/item.php?id=25191>Giant Shard Wurm Tooth</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=25130>Giant Icewurm Talisman</a></ul></td><td><p><b>You give Bekerak Coldbones : </b><a href=http://phobos/eq/item.php?id=25106>Bekerak's New Spear</a>
<br><b>Bekerak Coldbones says </b>'Well, well, I see Wenglawks finally got around to sending me my new spear. I hope it's not as shoddy as the last one. Your payment? Bahaha, did Wenglawks not tell you? Payment was to be a giant icewurm tooth carved into an amulet. Come now, little one. I will find an ice wurm for us to slay together. 
Then you can pull one of its teeth out for me and I will fashion the talisman for that greedy merchant.'
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=118164>#an_angry_shardwurm</a></b> spawns (-3011,-2776,255.5).</font>
<p><b>You give Bekerak Coldbones : </b><a href=http://phobos/eq/item.php?id=25191>Giant Shard Wurm Tooth</a>
<br><font color=green><b>Bekerak Coldbones </b>pulls out a large knife and begins to carve at the tooth.
After a few minutes he pulls out a length of rope and fashions it into a very large necklace. 'Here is his payment. Tell him the spear is fine, and that I might reconsider his last offer to me. He will know what I mean.'</font>
<br><b>Bekerak Coldbones gives you : </b><a href=http://phobos/eq/item.php?id=25130>Giant Icewurm Talisman</a>
</td></tr></table>