<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=30045>Third part of an Iceclad Map</a></ul></td><td><hr><b>When bloody gnome captive spawns </b>
<p><b>You say, </b>'hail'
<br><b>bloody gnome captive says </b>'Uh, hi. Hey, that was great work and all. I couldn't believe that. Knowing that bear, I was sure my time was up. I'm heading back to Ak'Anon. I've had enough of pirates, mountains, snow, and bears ten times my size. If you want a map to get back you can have it.'
<p><b>You say, </b>'map'
<br><b>bloody gnome captive gives you : </b><a href=http://phobos/eq/item.php?id=30045>Third part of an Iceclad Map</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>bloody gnome captive disappears.</b>
</td></tr></table>