<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=30264>Yakman Parts</a></ul></td><td><p><b>You give Bloodmaw : </b><a href=http://phobos/eq/item.php?id=30264>Yakman Parts</a> (x4)
<br><font color=yellow>You gain experience!!</font>
<br><b>Bloodmaw disappears.</b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=118026>bloody_gnome_captive</a></b> spawns (-5931,3172,-107.2).</font>
</td></tr></table>