<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1861>An old worn Talisman</a><li><a href=http://phobos/eq/item.php?id=1862>Head of the Taskmaster</a></ul></td><td><p><b>You say, </b>'hail'
<p><b>You say, </b>'glanitar'
<p><b>You say, </b>'disappear'
<p><b>You say, </b>'rolandal'
<p><b>You give Kardakor : </b><a href=http://phobos/eq/item.php?id=1861>An old worn Talisman</a>, <a href=http://phobos/eq/item.php?id=1862>Head of the Taskmaster</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>