<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=30262>Shardwurm Claw</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=30263>Coldain Velium-Pick</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Relik says </b>'Huh? What are ya needin'? Speak up! I ain't got all day. Are you here to help out or just eat up valuable time chatting?'
<p><b>You say, </b>'here to help'
<br><b>Relik says </b>'Ah, good. That's what I wanted to hear. We be needin' help with supplies. I been needin' pickheads for a while now but the minin' guild hasn't had the stock ta send 'em. We're gonna need ta improvise. I've seen the gashes left in rock after a shardwurm crawled over it and I think that be the thing we need. If ya can bring me four shardwurm claws, maybe I can rig 'em up into enough picks to keep us runnin' on time with our crystal mining.'
<p><b>You give Relik : </b><a href=http://phobos/eq/item.php?id=30262>Shardwurm Claw</a> x4
<br><b>Relik says </b>'Oh, yeah. That's strong, very strong. With these, we can make our shipment for this month. I gotta be thankin' ya properly. This be one of our best tools. Here, ya can swing a pick with us anytime, [Your Name].'
<br><b>Relik gives you : </b><a href=http://phobos/eq/item.php?id=30263>Coldain Velium-Pick</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>