<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1675>Marr's Promise</a><li><a href=http://phobos/eq/item.php?id=1676>Woe</a><li><a href=http://phobos/eq/item.php?id=1677>Envy</a><li><a href=http://phobos/eq/item.php?id=1669>Obsidian Pebble</a><li><a href=http://phobos/eq/item.php?id=1670>Marble Pebble</a><li><a href=http://phobos/eq/item.php?id=1667>A Small Gem</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1679>Shield of Falsehood</a><li><a href=http://phobos/eq/item.php?id=1668>Sparkling Gem</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=342>True Spirit</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>a wandering spirit </b>stops and flashes brightly for a moment. It seems to be regarding you with interest.</font>
<br><font color=white>The npc waits 30 seconds...</font>
<p><b>You say, </b>'Shield of Falsehood'
<br><b>a wandering spirit says </b>'Yes, I have taken Marr's Promise along with Woe and Envy and fashioned them together to create the Shield of Falsehood. Wield this in defense of possession and the weakness that comes with hoarding treasure instead of using it to accomplish your goals. May it serve you well, .'
<br><b>a wandering spirit gives you : </b><a href=http://phobos/eq/item.php?id=1679>Shield of Falsehood</a>
<p><b>You say, </b>'last path'
<br><b>a wandering spirit says </b>'You have trusted us along the paths we have set before you. You have been known to be patient and await the right moment. And now, you have learned the wisdom to act in our best interest. However, one last path awaits, to determine if you have the ability to act out what must be done. There are many troubles about the world we try to rub out but none is more serious than the curse on what the wasichu call the Emerald Jungle. Go there and find one of our spirits. Show them the gem you have been given and follow the path they set you on.'
<br><b>a wandering spirit gives you : </b><a href=http://phobos/eq/item.php?id=1668>Sparkling Gem</a>
<p><b>You give a wandering spirit : </b><a href=http://phobos/eq/item.php?id=1677>Envy</a>, <a href=http://phobos/eq/item.php?id=1676>Woe</a>, <a href=http://phobos/eq/item.php?id=1675>Marr's Promise</a>
<br><font color=green><b>a wandering spirit </b>nods somberly and takes the items. After a moment, he says, 'It is unfortunate that it came to this, but nothing else was to be done. Both paragons had lost sight of their virtures to protect the items given to them. The mere protection of these material belongings was not as important to Mithaniel Marr or Bertoxulous as it was that they act with righteousness in their minds and purpose in their hearts. You saw this and acted accordingly. For that, we will reward you with the three treasures made into one to ward off the falsehood of possession, the [Shield of Falsehood]. You have walked the path and now, as your final test, we must set you along one [last path].</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=342>True Spirit</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give a wandering spirit : </b><a href=http://phobos/eq/item.php?id=1669>Obsidian Pebble</a>, <a href=http://phobos/eq/item.php?id=1670>Marble Pebble</a>
<br><b>a wandering spirit says </b>'This is a sad day. You have failed and strayed from the path set before you. Please try to live as close to the spirits as you are able, though this is the closest you will ever get.'
<br><b>a wandering spirit disappears.</b>
<p><b>You give a wandering spirit : </b><a href=http://phobos/eq/item.php?id=1667>A Small Gem</a>
<br><b>a wandering spirit says </b>'Oh, it is you, shaman! Good! You must hurry before it's too late. Go now to the Mountains they call Rathe and find them! They need your help quickly! They will know you when they see you and instruct you on how you can help, but you must hurry!'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=342>True Spirit</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give a wandering spirit : </b><a href=http://phobos/eq/item.php?id=1669>Obsidian Pebble</a>
<br><b>a wandering spirit says </b>'This is a sad day. You have failed and strayed from the path set before you. Please try to live as close to the spirits as you are able, though this is the closest you will ever get.'
<br><b>a wandering spirit disappears.</b>
<p><b>You give a wandering spirit : </b><a href=http://phobos/eq/item.php?id=1670>Marble Pebble</a>
<br><b>a wandering spirit says </b>'This is a sad day. You have failed and strayed from the path set before you. Please try to live as close to the spirits as you are able, though this is the closest you will ever get.'
<br><b>a wandering spirit disappears.</b>
</td></tr></table>