<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13910>Blessed Oil Flask</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13911>PrayerBeads</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=257>Priests of Life</a><li><a href=http://phobos/eq/faction.php?id=183>Knights of Thunder</a><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a><li><a href=http://phobos/eq/faction.php?id=9>Antonius Bayle</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=21>Bloodsabers</a></ul></td><td><p><b>You say, </b>'Hail, $mname'
<p><b>You say, </b>'what prime healer'
<br><b>Brother Estle says </b>'Rodcet Nife is the Prime Healer. His way is the path of healing and life. There can be no true life until your soul is healed by healing others. This will take you into the eternal when your time comes.'
<p><b>You say, </b>'what mass'
<br><b>Brother Estle says </b>'Mass is not being held out here as yet. I am waiting for the [blessed oil] from the Temple of Life. You may attend services there.'
<p><b>You say, </b>'what blessed oil'
<br><b>Brother Estle says </b>'The blessed oil is necessary during services. It is blessed by High Priestess Jahnda at the [Temple of Life]. If you are going in that direction, please stop at the temple and remind High Priestess Jahnda that brother Estle is waiting for his blessed oil.'
<p><b>You say, </b>'what temple of life'
<br><b>Brother Estle says </b>'The Temple of Life is the center of worship for the followers of Rodcet Nife. It is located in North Qeynos and is one of the greatest temples ever created. Be sure to visit and attend services.'
<p><b>You give Brother Estle : </b><a href=http://phobos/eq/item.php?id=13910>Blessed Oil Flask</a>
<br><b>Brother Estle says </b>'Thank you. Now I may cleanse the bodies of the new converts and help them enter into a new life. I also have this. It was given to me by a dying gnoll of all things. They belong to Brother Hayle. The gnoll's last words were 'Free him.' Make sure High Priestess Jahnda gets this. Be swift!'
<br><b>Brother Estle gives you : </b><a href=http://phobos/eq/item.php?id=13911>PrayerBeads</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=257>Priests of Life</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=183>Knights of Thunder</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=21>Bloodsabers</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=9>Antonius Bayle</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 1sp
</td></tr></table>