<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13063>A Piece of Parchment</a><li><a href=http://phobos/eq/item.php?id=13051>A Quill</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12100>Bandit Sash</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Chrislin Baker </b>slowly lifts her head.</font>
<br><b>Chrislin Baker says </b>'Have you brought any writing materials for me? The last few supplies I had were stolen.'
<p><b>You say, </b>'writing materials'
<br><b>Chrislin Baker says </b>'A passing illusionist gave me some enchanted writing materials. He said they would help inspire me to capture my mind's images on paper. If you would just be so kind as to bring me plain old paper and a quill from Qeynos, I can get back to writing.'
<p><b>You say, </b>'paper'
<br><b>Chrislin Baker says </b>'I don't know who might be selling those these days. Just ask around. I am sure someone will know.'
<p><b>You give Chrislin Baker : </b><a href=http://phobos/eq/item.php?id=13063>A Piece of Parchment</a>, <a href=http://phobos/eq/item.php?id=13051>A Quill</a>
<br><font color=green><b>Chrislin Baker </b>gives you a hug. 'Thank you so much. I did some cleaning after you left and found this behind a barrel. It may have been left behind by the person who took my materials. You can have it.'</font>
<br><b>Chrislin Baker gives you : </b><a href=http://phobos/eq/item.php?id=12100>Bandit Sash</a>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=12172>Thrackin_Griften</a></b> spawns (878,-11570,14).</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>