<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12169>Gnoll Paw</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Coron Finisc says </b>'Hello [Your Name] have you seen any [Sabertooth Gnolls] around?'
<p><b>You say, </b>'sabertooth gnolls'
<br><b>Coron Finisc says </b>'Sabertooth Gnoll are viscious gnolls of Blackburrow who attack us constantly and send patrols out into Qeynos Hills,A gnoll has even been seen in the bear caves on occasion!'
<br><b>Coron Finisc says </b>'There is a [reward] offered if you can bring me his hide'
<p><b>You say, </b>'reward'
<br><b>Coron Finisc says </b>'Yes. We are offering a small reward for slaying the stalking gnoll in the bear caves. Bring us his Paw to claim your bounty. The Jaggedpine Treefolk remember well those who aid their cause.'
<p><b>You give Coron Finisc : </b><a href=http://phobos/eq/item.php?id=12169>Gnoll Paw</a>
<br><b>Coron Finisc says </b>'The Jagged Pine Tree Folk will never forget your actions!'
<br><b>You receive </b> 10gp 5sp 5cp
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a> has gotten better.</font>
</td></tr></table>