<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When Draze Slashyn spawns </b>
<br><font color=white><b>The NPC moves to -7756,-3726,1.</b></font>
<br><font color=red><b>Draze Slashyn shouts </b>'Come out of that house, Linaya Sowlin!! I am waiting! It is time for you to die!'</font>
<hr><b>When Draze Slashyn is killed </b>
<br><b>Draze Slashyn says </b>'Your act of murder will not go unnoticed by the Unkempt Druids or nature itself!!'
</td></tr></table>