<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Einhorst McMannus says </b>'Greetings, [Your Name]. Welcome to the fishing village of Clan McMannus. We sell what we can here.  Have a look around but, please do not buy too much. We must save most of our stock for delivery to our home.'
<p><b>You say, </b>'pick up the lion meat shipment for Halas'
<br><b>Einhorst McMannus says </b>'Aye, good. Talk to Misla, she will get you the [Lion Roast].'
</td></tr></table>