<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=14017>A Snake Venom Sac</a><li><a href=http://phobos/eq/item.php?id=13901>Crow's Special Brew</a></ul></td><td><p><b>You say, </b>'Hail, $mname'
<p><b>You say, </b>'what poison'
<br><font color=green><b>Gindlin Toxfodder </b>grins</font>
<br><b>Gindlin Toxfodder says </b>'So your here about poison eh? I can make it for ya. Get me a snakes venom sac and the Special Brew made by Crow in Crow's Bar in Qeynos, and of course, a fee of 20 gold.'
<p><b>You give Gindlin Toxfodder : </b><a href=http://phobos/eq/item.php?id=13901>Crow's Special Brew</a>, <a href=http://phobos/eq/item.php?id=14017>A Snake Venom Sac</a>
</td></tr></table>