<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13990>Sack of Hay</a></ul></td><td><p><b>You say, </b>'Hail, $mname'
<p><b>You say, </b>'what grains do you grow'
<br><b>Hetina Miller says </b>'We grow all sorts of grains here, but there is a difference between crops and grains. Crops can be anything that is harvested for sell. While a grain is a specific type of crop. I have just gotten done baggin up the grain from our latest crop. The bags are laying out in the field. However, I am exausted from all this work, I would be willing to pay if you would drag these bags in for me. Will you help me drag the grain in?'
<p><b>You say, </b>'no'
<br><font color=green><b>Hetina Miller </b>sighs.</font>
<br><b>Hetina Miller says </b>'Well, I'll just be getting back to work.'
<p><b>You say, </b>'yes'
<br><b>Hetina Miller says </b>'Thank you! Just go out to the fields and collect the grain bags. Hand me one bag at a time, they are quite heavy, and watch out the the scarecrows as well, they can get a bit mean at times.'
<p><b>You give Hetina Miller : </b><a href=http://phobos/eq/item.php?id=13990>Sack of Hay</a>
<br><b>Hetina Miller says </b>'Thank you for helping me with this task. It has saved me a lot of time and strength.'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 1gp 5sp 5cp
</td></tr></table>