<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20379>Proof of Speed</a><li><a href=http://phobos/eq/item.php?id=20366>Mahlin's Mystical Bongos</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20532>Torch of Misty</a><li><a href=http://phobos/eq/item.php?id=20376>Maestro's Symphony Page 24 Top</a><li><a href=http://phobos/eq/item.php?id=20383>Maestro's Symphony Page 24 Bottom</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Konia Swiftfoot says </b>'Hello there, [Your Name].  I am hosting a relay running contest.  Would you like to participate?'
<p><b>You say, </b>'i would like to participate'
<br><b>Konia Swiftfoot says </b>'Great!  The prize will be this silly old music sheet.  Let me know when you are ready and I will pass you the torch and tell you where the next stop is.'
<p><b>You say, </b>'ready'
<br><b>Konia Swiftfoot says </b>'Here you go.  Run with this torch as fast as you can to the Misty Thicket and hand this torch off to Fajio Knejo.  He will tell you where to go from there.  Hurry!  You do not have much time!'
<br><b>Konia Swiftfoot gives you : </b><a href=http://phobos/eq/item.php?id=20532>Torch of Misty</a>
<p><b>You give Konia Swiftfoot : </b><a href=http://phobos/eq/item.php?id=20379>Proof of Speed</a>
<br><b>Konia Swiftfoot says </b>'Excellent!  You are quite a runner.  Here is half of the sheet music.  I decided to keep the other half because it has this wonderful signature.  I think it might be quite valuable.  It is probably worth as much as an instrument the great Mahlin used.'
<br><b>Konia Swiftfoot gives you : </b><a href=http://phobos/eq/item.php?id=20376>Maestro's Symphony Page 24 Top</a>
<p><b>You give Konia Swiftfoot : </b><a href=http://phobos/eq/item.php?id=20366>Mahlin's Mystical Bongos</a>
<br><b>Konia Swiftfoot says </b>'Mahlin's bongos!  Here, take the other half of the sheet music.  I can't really make out what the signature was, anyway.'
<br><b>Konia Swiftfoot gives you : </b><a href=http://phobos/eq/item.php?id=20383>Maestro's Symphony Page 24 Bottom</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>