<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13945>Flask of Nitrates</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a><li><a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a><li><a href=http://phobos/eq/faction.php?id=267>QRG Protected Animals</a><li><a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=347>Unkempt Druids</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Linaya Sowlin says </b>'Greetings!  It is always nice to meet another traveler.  The roads of the Plains of Karana are heavily trodden, but sparsely patrolled.  Be careful of bandits and especially of giants.  I have seen a few since my [move from the Jaggedpine].'
<p><b>You say, </b>'note'
<br><b>Linaya Sowlin says </b>'The note spoke of the [Unkempt Druids]. I did not get a chance to read it all, only a glimpse. Perhaps the man still has the note. Too bad. I am sure Gerael Woodone of the druids of Surefall Glade should look at it.'
<p><b>You say, </b>'Unkempt Druids'
<br><b>Linaya Sowlin says </b>'The Unkempt Druids are a crazed group of druids and rangers. I learned of them when I was in the Jaggedpine. They are a secret group and aim to keep it that way. They would kill anyone who learned of their whereabouts.'
<p><b>You say, </b>'move from the Jaggedpine'
<br><b>Linaya Sowlin says </b>'I inherited this farmhouse from my late uncle so I left the Jaggedpine to live here.  The Jaggedpine is a beautiful forest but I believe my skills as a druid may come in handy as a farmer.'
<p><b>You give Linaya Sowlin : </b><a href=http://phobos/eq/item.php?id=13945>Flask of Nitrates</a>
<br><b>Linaya Sowlin says </b>'Oh thank Tunare you showed up when you did. I was at a nearby merchant house when a fellow dropped a [note] and I picked it up and read it. It talked of the [Unkempt Druids] and before I could read on, the man swiped it from my hands. I ran for dear life, for surely he would kill me for reading the note. I think I lost him in the woods but I am not sure. Please stay with me a while to be sure.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=265>Protectors of Pine</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=159>Jaggedpine Treefolk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=267>QRG Protected Animals</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=347>Unkempt Druids</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=135>Guards of Qeynos</a> has gotten better.</font>
<br><b>You receive </b> 1pp 9gp 5sp
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=12181>Draze_Slashyn</a></b> spawns (-3400,-8000,23).</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>