<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12221>Lion Delight</a></ul></td><td><p><b>You say, </b>'lion roast'
<br><b>Misla McMannus says </b>'Hello there. You are here to deliver the lion roast to Halas? Very well, here is the lion roast.'
<br><b>Misla McMannus gives you : </b><a href=http://phobos/eq/item.php?id=12221>Lion Delight</a>
</td></tr></table>