<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>Mystik says </b>'I see you bear the Sign of Acceptance. So you believe you are strong enough to accomplish all that is asked of you? If you stand true during this [test] you will find all you seek.'
<p><b>You say, </b>'i am ready for the test'
<br><b>Mystik says </b>'In this test you will have to face me and prove that you have the heart to succeed. I hope you have brought strong allies to accompany you for you shall need them. We shall begin as soon as you are [ready to start].'
<p><b>You say, </b>'i am ready to start'
<br><b>Mystik says </b>'I didnt know slime could speak common.. go back to the sewer before I lose my temper.'
<hr><b>When Mystik is killed </b>
<br><b>Mystik says </b>'You have proven to be successful. Go now and continue your journey.'
</td></tr></table>