<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2416>Note to Kanthuk</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Ryshon Hunsti says </b>'Hello, [Your Name]. What brings you to the Karanas? Do you seek [enlightenment]?'
<p><b>You say, </b>'enlightenment'
<br><b>Ryshon Hunsti says </b>'Ahh, i could see by the look in your eyes that you are looking for something more than just enlightenment. Perhaps you are looking for a [sword] crafted by a noble man.'
<p><b>You say, </b>'sword'
<br><b>Ryshon Hunsti says </b>'It is not just a sword friend. It is much more than that. This sword carries with it special [power], something unlike anything else within this realm.'
<p><b>You say, </b>'power'
<br><b>Ryshon Hunsti says </b>'It is an instrument fashioned together by a noble man. It is said to be blessed by the gods themselves. Only a man who comes from nobility may wield it. Do you seek the [sword of nobility]?'
<p><b>You say, </b>'sword of nobility'
<br><b>Ryshon Hunsti says </b>'It is not just a sword friend. It is much more than that. This sword carries with it special [power], something unlike anything else within this realm.'
<br><b>Ryshon Hunsti says </b>'I see.  Then take this note to Kanthuk Ogrebane. I've been told he can be found fishing not far from the dwarven city.'
<br><b>Ryshon Hunsti gives you : </b><a href=http://phobos/eq/item.php?id=2416>Note to Kanthuk</a>
</td></tr></table>