<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Ulrich McMannus says </b>'Welcome to the village of McMannus. We sell many goods. Feel free to look around - just keep your hands to yourself. Good day.'
<p><b>You say, </b>'murderer'
<br><b>Ulrich McMannus says </b>'Aye. I have heard 'bout the murderer. Clan McMannus has the best hunting dogs in the land. The one over there named Frostbite is one of the best. If you have a piece of sweaty clothing, he can track the person no matter how far away they are.'
</td></tr></table>