<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18010>Torn Parchment</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Yiz Pon says </b>'Hello. I was in paw, and I stole a skull, but then I gave it to an assassin to leave me alone. He did not leave me alone. I am on the run, and I would appriciate it if you would please give this note to my brother Hyrill in Freeport.'
<br><b>Yiz Pon gives you : </b><a href=http://phobos/eq/item.php?id=18010>Torn Parchment</a>
</td></tr></table>