<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=15959>Goblins and Their Religions</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15960>The Reflecting Pools of Tanaan</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Jeren Manri says </b>'Shhh, be quiet! The goblins may hear you.'
<p><b>You give Jeren Manri : </b><a href=http://phobos/eq/item.php?id=15959>Goblins and Their Religions</a>
<br><font color=green><b>Jeren Manri </b>Oh! Thank you, I assume this means that Thiran sent you. I ran off with the incorrect book without thinking to check. Would you be kind enough to return this to him?</font>
<br><b>Jeren Manri gives you : </b><a href=http://phobos/eq/item.php?id=15960>The Reflecting Pools of Tanaan</a>
<br><b>Jeren Manri says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>