<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>#Translocator Tradil says </b>'Hello there. There seems to be some strange problems with the boats in this area. The Academy of Arcane Sciences has sent a small team of us to investigate them. If you need to [travel to Timorous] in the meantime, I can transport you to my companion there.'
<p><b>You say, </b>'travel to timorous'
<br><font color=white><b>The Player moves to zone 96 at -3260.1,-4544.56,19.47</b></font>
</td></tr></table>