<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Wygrish </b>As you approach Wygrish you can see him meditating with a small ripped book in his grasp. As you pass him by he raises his eyes and stares at you before going back into meditation.</font>
<br><b>Wygrish says </b>'I see you wear the Celestial Mark! I know why you are here and you cant have it back! I will fight you with all that I am to prevent losing the diary!'
</td></tr></table>