<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=6475>Drogan Warlord's Insignia</a><li><a href=http://phobos/eq/item.php?id=6471>Forged Note to Courier</a></ul></td><td><p><b>You say, </b>'hail'
<p><b>You say, </b>'I am your contact'
<p><b>You give a shady goblin : </b><a href=http://phobos/eq/item.php?id=6475>Drogan Warlord's Insignia</a>, <a href=http://phobos/eq/item.php?id=6471>Forged Note to Courier</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>