<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12492>Misscribed Lifetap</a><li><a href=http://phobos/eq/item.php?id=12493>Misscribed Gate</a><li><a href=http://phobos/eq/item.php?id=12494>Scroll in a Bottle</a><li><a href=http://phobos/eq/item.php?id=6026>Shovel</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12496>Chalp Diagram</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a><li><a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>an Iksar knight </b>wipes the sweat from his forehead and spits some flarefire seeds on the ground near your feet. 'Whew!! Good to be back and safe at the Cabilis Gate. The troopers will protect us.'</font>
<p><b>You say, </b>'chalp diagram'
<br><font color=green><b>an Iksar knight </b>spits out some flarefire seeds. 'Great!! Sent to retrieve the Chalp diagram. I will give them to you, but I want you to do me a little favor first. I want you to [retrieve some spells] I lost. They are incorrectly scribed and useless, but I yearn for their return nonetheless.'</font>
<p><b>You say, </b>'retrieve some spells'
<br><font color=green><b>an Iksar knight </b>spits flarefire seeds on you. 'Oops!! Sorry. Yeah!! You go to Chalp and get two incorrectly scribed spells which they grabbed from me. The third one, I threw in a river crossing by Chalp. It was in a bottle and probably drifted way down the river. Bring me all three and also a shovel and I will make it worth your while.'</font>
<p><b>You say, </b>'flarefire seeds'
<br><font color=green><b>an Iksar knight </b>spits some flarefire seeds on your face. 'What? Interested in flarefire seeds? There you go. Ha!!'</font>
<p><b>You give an Iksar knight : </b><a href=http://phobos/eq/item.php?id=6026>Shovel</a>, <a href=http://phobos/eq/item.php?id=12493>Misscribed Gate</a>, <a href=http://phobos/eq/item.php?id=12494>Scroll in a Bottle</a>, <a href=http://phobos/eq/item.php?id=12492>Misscribed Lifetap</a>
<br><font color=green><b>an Iksar knight </b>accidently swallows a mouthful of flarefire seeds. 'ACCCKK!!  I can't believe you did it!! Here is the Chalp diagram.'</font>
<br><b>an Iksar knight gives you : </b><a href=http://phobos/eq/item.php?id=12496>Chalp Diagram</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<br><b>an Iksar knight disappears.</b>
<p><i>This npc will return you any extra items you gave him.</i>
<br><font color=green><b>an Iksar knight </b>spits flarefire seeds on your chest. 'Listen up!! I asked for the misscribed spells; Fear, Lifetap and Gate, and also, a shovel.'</font>
</td></tr></table>