<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=60210>Medal of Mastery</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=60210>Medal of Mastery</a></ul></td><td><p><b>You say, </b>'Hail'
<p><b>You say, </b>'Hail'
<hr><b>When Lurking Hopeful is killed </b>
<p><b>You give Lurking Hopeful : </b><a href=http://phobos/eq/item.php?id=60210>Medal of Mastery</a>
<br><b>Lurking Hopeful says </b>'Ah, me also got one of dose medal tings. Me guess you here for da same reason me is -- to finish da final berserker trial. Me been waiting for someone to come by here. Me need to figure out how to do dis challenge. Me tried once and didn't have a chance. Me ran. Dat goblin is mad. Hey, if you give me 1000 platinum, me save you some time and show you where da crazy goblin is. Me hate to ask for money, but me needs to hire help for dis.'
<br><b>Lurking Hopeful gives you : </b><a href=http://phobos/eq/item.php?id=60210>Medal of Mastery</a>
<p><b>You give Lurking Hopeful : </b>
</td></tr></table>