<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=6353>Burnished Wooden Stave</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19958>Piece of a medallion</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Ssolet Dnaas says </b>'Greetingss, [Your Name].  Unlesss you bring closssure to my ssearch, leave me while I contemplate thingss.'
<p><b>You say, </b>'search'
<br><b>Ssolet Dnaas says </b>'My sssearch. I have been ssent out by my massster to find an item. A burnished wooden sstaff. I know not why and I do not quessstion. I know not where thiss item is found. I musst have one though. Ssssss. If you can find one for me I will give you a trinket.'
<p><b>You give Ssolet Dnaas : </b><a href=http://phobos/eq/item.php?id=6353>Burnished Wooden Stave</a>
<br><b>Ssolet Dnaas says </b>'Sssss. Thisss is what I need. You have my thanksss. Please, take thiss. I know not what it iss for but maybe you will find a ussse for it.'
<br><b>Ssolet Dnaas gives you : </b><a href=http://phobos/eq/item.php?id=19958>Piece of a medallion</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>