<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>10155 says </b>'Hello there. There seem to be some strange problems with the boats in this area. The Academy of Arcane Sciences has sent a small team of us to investigate them. If you need to travel to the [Ocean of Tears] in the meantime, I can transport you to my companion there.'
<p><b>You say, </b>'Ocean of Tears'
<br><b>10155 says </b>'On your way'
<br><font color=white><b>The Player moves to zone 69 at -9000,459,14</b></font>
</td></tr></table>