<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13036>Dwarven Ale</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Beur Tenlah says </b>'Heya. [Your Name]!  I've been on watch duty all night.  Kinda makes a man thirsty. ya know?  Why don't you be a good little scamp and run up to the bar and get me a [dwarven ale]?  That sure would hit the spot right about now.'
<p><b>You say, </b>'dwarven ale'
<br><b>Beur Tenlah says </b>'Ahhh..  Dwarven ale is the best.  You gotta hand it to those stinky little dirt diggers. they know how to make a good brew.  Now if they could just learn to shower. huh. Harkin? Ha ha ha!'
<p><b>You give Beur Tenlah : </b><a href=http://phobos/eq/item.php?id=13036>Dwarven Ale</a>
<br><b>Beur Tenlah says </b>'Well, well, well.. It's about time. Whatta ya got, boots fulla stones? Or maybe yer just part turtle? Bah, anyways, thanks for the ale. Maybe I'll buy you one sometime, eh? Bwahaha!'
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>