<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18857>A tattered note</a><li><a href=http://phobos/eq/item.php?id=19932>Tarsa Yovar's Head</a><li><a href=http://phobos/eq/item.php?id=19852>Giant Rattlesnake Skin</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=26644>A Sealed Letter</a><li><a href=http://phobos/eq/item.php?id=13561>Faded Crimson Tunic*</a><li><a href=http://phobos/eq/item.php?id=55623>Dull Axe*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Brutol Rhaksen says </b>'Oh. hello down there. puny one. I'm Brutol Rhaksen. Commmander of warriors who [serve] the Dismal Rage. and that's really all you need to know..for now.'
<p><b>You say, </b>'serve'
<br><b>Brutol Rhaksen says </b>'You must become strong to survive amongst the ranks of the Dismal Rage. Take this note to Rolfic Gohar and he will help you get a suit of armor to protect your scrawny hide from the weapons of our enemies. Once you have been properly outfitted return to me and will give you your [next orders].'
<br><b>Brutol Rhaksen gives you : </b><a href=http://phobos/eq/item.php?id=26644>A Sealed Letter</a>
<p><b>You say, </b>'next orders'
<br><b>Brutol Rhaksen says </b>'Ready to make yourself useful [Your Name] ? Beneath West Freeport are sewer tunnels leading to North Freeport being used by the Knights of Truth and the Sentries and Passion that have gained too much notoriety with the Freeport Militia and the Dismal Rage to pass safely through the eastern and western quarters of Freeport. We believe a sympathizer of the Sentries of Passion. Tarsa Yovar. is hiding somewhere in the western tunnel system. The sympathizer is a Steel Warrior faithful to Erollisi and although she is only a minor nuisance must be dealt with. Find her and bring me her head.'
<p><b>You give Brutol Rhaksen : </b><a href=http://phobos/eq/item.php?id=18857>A tattered note</a>
<br><b>Brutol Rhaksen says </b>'Welcome to warriors guild of East Freeport. Take this to help you on your journeys.'
<br><b>Brutol Rhaksen gives you : </b><a href=http://phobos/eq/item.php?id=13561>Faded Crimson Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Brutol Rhaksen : </b><a href=http://phobos/eq/item.php?id=19932>Tarsa Yovar's Head</a>
<br><b>Brutol Rhaksen says </b>'Take this and get it sharpened. Bring it back to me with a Giant Rattlesnake Skin and you will have proven yourself able to wield a Dismal Rage Battle Axe, to help teach the way of Innoruuk!'
<br><b>Brutol Rhaksen gives you : </b><a href=http://phobos/eq/item.php?id=55623>Dull Axe*</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Brutol Rhaksen : </b><a href=http://phobos/eq/item.php?id=19932>Tarsa Yovar's Head</a>, <a href=http://phobos/eq/item.php?id=19852>Giant Rattlesnake Skin</a>
<br><b>Brutol Rhaksen says </b>'Take this and get it sharpened. Bring it back to me with a Giant Rattlesnake Skin and you will have proven yourself able to wield a Dismal Rage Battle Axe, to help teach the way of Innoruuk!'
<br><b>Brutol Rhaksen gives you : </b><a href=http://phobos/eq/item.php?id=55623>Dull Axe*</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>