<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=17710>Cartography Binder</a><li><a href=http://phobos/eq/item.php?id=63003>A Coordinate Label</a><li><a href=http://phobos/eq/item.php?id=63001>A Compass Notation</a><li><a href=http://phobos/eq/item.php?id=63002>A Map Legend</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17710>Cartography Binder</a><li><a href=http://phobos/eq/item.php?id=63048>Skyfall Seeker</a></ul></td><td><hr><b>When Cartographer Piri spawns </b>
<hr><b>When Cartographer Piri spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Cartographer Piri says </b>'Hail, traveler! Would you have a moment? I'm in need of some [assistance].'
<p><b>You say, </b>'assistance'
<br><b>Cartographer Piri says </b>'Thank you! I'll make it worth your while. I recently discovered the remains of an odd little map that may detail the distant Gulf of Gunthak. The map itself, however, is in a horrible state... a suspiciously horrible state if you ask me. Much of it is [missing].'
<p><b>You say, </b>'missing'
<br><b>Cartographer Piri says </b>'The pirates of Broken Skull Rock have purposefully destroyed any accurate maps to protect the secrecy of their base. Three key parts are damaged. The compass notation, the legend and the coordinate label are all gone. Take this Cartography Binder. Use it to [collect] the fragments.'
<p><b>You say, </b>'collect'
<br><b>Cartographer Piri says </b>'No doubt the pirates will have some of the fragments. Search Broken Skull Rock, paying careful attention to Gunthak and Dulak Harbor. An accurate map must be made. It is the first step in breaking the pirates' hold on the region. Good luck. The three pieces needed are A Coordinate Label, A Compass Notation, and A Map Legend.'
<br><b>Cartographer Piri gives you : </b><a href=http://phobos/eq/item.php?id=17710>Cartography Binder</a>
<p><b>You give Cartographer Piri : </b><a href=http://phobos/eq/item.php?id=63003>A Coordinate Label</a>, <a href=http://phobos/eq/item.php?id=63001>A Compass Notation</a>, <a href=http://phobos/eq/item.php?id=17710>Cartography Binder</a>, <a href=http://phobos/eq/item.php?id=63002>A Map Legend</a>
<br><b>Cartographer Piri says </b>'Incredible! With a little work, I will be able to create a finished map of the Gulf of Gunthak. No longer will the pirates be able to keep their lair a secret. Thank you! Please take this as a reward for your efforts.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Cartographer Piri gives you : </b><a href=http://phobos/eq/item.php?id=63048>Skyfall Seeker</a>
<hr><b>When Cartographer Piri is killed </b>
<hr><b>When Cartographer Piri is killed </b>
</td></tr></table>