<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18745>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13568>Brown Faded Tunic*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Elisi Nasin says </b>'Listen. this is a pretty busy [operation] I run here.  I certainly don't have any spare time to sit around and chit-chat with you all day. got it?'
<p><b>You say, </b>'operation'
<br><b>Elisi Nasin says </b>'Look. [Your Name] . I don't have time for this.  Let's just say importing exotic goods is our main interest. along with a few other profitable ventures.  Now quit pestering me. or you'll force me to sic Grenny here on ya.'
<p><b>You give Elisi Nasin : </b><a href=http://phobos/eq/item.php?id=18745>A tattered note</a>
<br><b>Elisi Nasin says </b>'Welcome to the Coalition of Tradesfolk underground. We like to keep a low profile around here and not draw any unneeded attention to our operations. you following me? I hope so. for your sake. Anyways. Nestral T'Gaza is in charge with helping out our newest members. Go see her as soon as you get a chance.'
<br><b>Elisi Nasin gives you : </b><a href=http://phobos/eq/item.php?id=13568>Brown Faded Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>