<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13122>Erud's Tonic</a><li><a href=http://phobos/eq/item.php?id=13383>Koalindl Fish</a><li><a href=http://phobos/eq/item.php?id=13952>Honey Jum</a><li><a href=http://phobos/eq/item.php?id=13340>Kiola Nut</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13379>Barkeep Compendium</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=48>Coalition of Tradefolk Underground</a><li><a href=http://phobos/eq/faction.php?id=47>Coalition of Trade Folk</a><li><a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a><li><a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Gregor Nasin says </b>'Sit down and name your poison!  I know we are lacking in originality. but I intend to create some [exotic drinks].'
<p><b>You say, </b>'exotic drinks'
<br><b>Gregor Nasin says </b>'Interested in exotic drinks. are we?  I am attempting to create some of these drinks I read about in this book I found. It was called the [Barkeep's Compendium].  I will first need to get my hands on a few [exotic ingredients].'
<p><b>You say, </b>'Barkeep's Compendium'
<br><b>Gregor Nasin says </b>'I found the book amongst some garbage littering the ground in Freeport East.  It appears to have been created by an ogre named [Clurg].  I am sure he wants it returned. but I will never part with it.  That is... unlessI get a few [exotic ingredients] I need to experiment with.'
<p><b>You say, </b>'exotic ingredients'
<br><b>Gregor Nasin says </b>'I desire a [kiola nut]. [Erud's Tonic]. [honey jum] and a [Koalindl fish].  If I could get those. I would no longer need to hold on to the [Barkeep's Compendium].  Whoever returned the ingredients to me could have it!!'
<p><b>You say, </b>'kiola nut'
<br><b>Gregor Nasin says </b>'The kiola nut usually grows only in humid territories.  I hear there are some such lands between Qeynos and Erudin.  Some also have been found on the islands of the Ocean of Tears.'
<p><b>You say, </b>'Erud's Tonic'
<br><b>Gregor Nasin says </b>'Now that is an ingredient that is hard to obtain.  Found only in the city of Erudin. it is a crime for anyone to attempt to smuggle it out of the city.  If caught. a horrid death is assured. though I hear there is a frequent customer of the taverns of Qeynos who has a way to obtain the forbidden liquid.'
<p><b>You say, </b>'honey jum'
<br><b>Gregor Nasin says </b>'Honey jum can be found in the halfling community of Rivervale.  I hear it is used in many of their potions.  I am sure it can be purchased somewhere in Rivervale.  If it is not on the shelf it is surely known by the shopkeeper.'
<p><b>You say, </b>'koalindl fish'
<br><b>Gregor Nasin says </b>'Some rare drinks call for ground up fish. I intend to use the Koalindl fish of Qeynos.  It is said to be magical in nature.  The problem with obtaining them is that you must get them from Jahnda's Pool near the Temple of Life and I hear that the members protect these fish with great ferocity.'
<p><b>You say, </b>'Clurg'
<br><b>Gregor Nasin says </b>'I do not know. Ask an ogre. Maybe they have heard of him.'
<p><b>You give Gregor Nasin : </b><a href=http://phobos/eq/item.php?id=13952>Honey Jum</a>, <a href=http://phobos/eq/item.php?id=13122>Erud's Tonic</a>, <a href=http://phobos/eq/item.php?id=13383>Koalindl Fish</a>, <a href=http://phobos/eq/item.php?id=13340>Kiola Nut</a>
<br><b>Gregor Nasin says </b>'Now I have every ingredient mentioned in the Barkeep Compendium. Here. You take it. <..click!.> Whoops!! I just closed it. It's magically sealed, I never closed it before. It's useless to you. I have no need for it any longer. Maybe you can return it to [Clurg] for some type of reward.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Gregor Nasin gives you : </b><a href=http://phobos/eq/item.php?id=13379>Barkeep Compendium</a>
<br><b>You receive </b> 2pp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=48>Coalition of Tradefolk Underground</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=47>Coalition of Trade Folk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
</td></tr></table>