<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13159>Broken Heirloom Necklace</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18925>Letter to Falia</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=369>Coalition of TradeFolk III</a><li><a href=http://phobos/eq/faction.php?id=47>Coalition of Trade Folk</a><li><a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a><li><a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Gren Frikniller says </b>'Aya. howdy there. [Your Name].  The name's Gren Frikniller.  'Niller the Killer' The only person who can give me a run for my money is my [sister].'
<p><b>You say, </b>'sister'
<br><b>Gren Frikniller says </b>'The one and only Falia Frikniller. By a good little grunt and take this letter to her will ya.'
<br><b>Gren Frikniller gives you : </b><a href=http://phobos/eq/item.php?id=18925>Letter to Falia</a>
<p><b>You say, </b>'rivervale'
<br><b>Gren Frikniller says </b>'Rivervale?  Well. it's far from here. thank Fizzlethorpe.  They got more wanted posters with my face on 'em than they got trees there.  I mean. 'tweren't my fault either.  Just a friendly game of cards. and this little weasel catches me with an extra ace up my sleeve.  Can you believe this kid calls ol' Grenny here a cheater. right in front of the whole bar?!!  So. you know. I gave him a quick cut. ear to ear. with me dagger...  just to shut him up. you know.  Suddenly. I'm a murderer?  For simply defending myself?! Go figure!'
<p><b>You say, </b>'elisi'
<br><b>Gren Frikniller says </b>'Elisi runs the show around here.  She's usually a pretty busy lady.  Dang smart. too.  And it's my sworn duty to protect her at any cost. even with my very own life.'
<p><b>You give Gren Frikniller : </b><a href=http://phobos/eq/item.php?id=13159>Broken Heirloom Necklace</a>
<br><b>Gren Frikniller says </b>'To you this heirloom isn't worth anything. But you have no idea what this is worth to me. Thanks [Your Name].'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=369>Coalition of TradeFolk III</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=47>Coalition of Trade Folk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
</td></tr></table>