<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19934>Raenna Griff's Head</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19845>Note to Quan Nektogo</a><li><a href=http://phobos/eq/item.php?id=19923>Dull Dismal Long Sword</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=86>Dismal Rage</a><li><a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a></ul></td><td><hr><b>When Gunex Eklar spawns </b>
<hr><b>When Gunex Eklar spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Gunex Eklar says </b>'Begone lest you seek instruction. I am very busy. I teach those who [follow the path of rage] as a Shadowknight. the leaders of the Dismal Rage.'
<p><b>You say, </b>'follow the path of rage'
<br><b>Gunex Eklar says </b>'As the leaders of the Dismal Rage we Shadowknights forefront of our struggles. We use the spiritual guidance of our Clerics. the Dark Arts of our Necromancers. and the tactics of our Warriors to advance the causes and secure the needs of our followers. If you aspire to be of importance to your colleagues you must first obtain a suit of armor to defend you from the aggressions of our enemies. Take this note to Quan Nektogo here in the eastern quarter of Freeport. He will aid you in the construction of your armor. When you are properly outfitted return to me and I will present you with an [important task].'
<br><b>Gunex Eklar gives you : </b><a href=http://phobos/eq/item.php?id=19845>Note to Quan Nektogo</a>
<p><b>You say, </b>'important task'
<br><b>Gunex Eklar says </b>'It has come to our attention that a paladin of the Sentries of Passion. Raenna Griff. has been aiding sympathizers and wanted members of the Sentries of Passion and the Knights of Truth in the sewer tunnels beneath the western quarter of Freeport. The incompetent Freeport Militia has yet to capture these wanted followers of the Mar twins. We will wait for their capture no longer. Seek this Raenna Griff individual and slay her. I want her head presented to me this very night!'
<hr><b>When Gunex Eklar is killed </b>
<hr><b>When Gunex Eklar is killed </b>
<p><b>You give Gunex Eklar : </b><a href=http://phobos/eq/item.php?id=19934>Raenna Griff's Head</a>
<br><b>Gunex Eklar says </b>'It took you long enough. I wonder if the Militia will be able to identify the body minus its head. Take this Dull Dismal Long Sword and sharpen it in a forge with a sharpening stone. It may take you several attempts if you are unfamiliar with the process. Once that is accomplished deliver the Sharpened Dismal Long Sword and a Giant Rattlesnake Skin to Quan Nektogo. He will make the final preparations on your weapon.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Gunex Eklar gives you : </b><a href=http://phobos/eq/item.php?id=19923>Dull Dismal Long Sword</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=86>Dismal Rage</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>