<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18016>Note to Harkin</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18015>Note to Janam</a><li><a href=http://phobos/eq/item.php?id=1054>Used Merchants Gloves</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=48>Coalition of Tradefolk Underground</a><li><a href=http://phobos/eq/faction.php?id=47>Coalition of Trade Folk</a><li><a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a><li><a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Harkin Duskfoot says </b>'HA! Greetings there. [Your Name]!  How are ya this fine day?  Me?  I'm doing all right.  Guard duty down here always reminds me of home.'
<p><b>You say, </b>'message'
<br><b>Harkin Duskfoot says </b>''Ok, [Your Name] , I need you to take this message to Janam in West Freeport. He is usually hanging out in front of the Theater of the Tranquil with that good-for-nothing Rebby. Anyway, give this note to Janam and bring his reply back to me.'
<br><b>Harkin Duskfoot gives you : </b><a href=http://phobos/eq/item.php?id=18015>Note to Janam</a>
<p><b>You give Harkin Duskfoot : </b><a href=http://phobos/eq/item.php?id=18016>Note to Harkin</a>
<br><b>Harkin Duskfoot says </b>'Ah, good work, [Your Name] . And quick too, I'll makes sure that Elisi hears of your loyal work. Here... take this for your efforts.. it's not much, but it's all I have on me right now.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Harkin Duskfoot gives you : </b><a href=http://phobos/eq/item.php?id=1054>Used Merchants Gloves</a>
<br><b>You receive </b> 6cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=48>Coalition of Tradefolk Underground</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=47>Coalition of Trade Folk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>