<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18855>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13564>Dirty Torn Robe*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Heneva Jexsped says </b>'Yes. yes. yes.  Hail to you. too. [Your Name] .  Now. quit bugging me!'
<p><b>You give Heneva Jexsped : </b><a href=http://phobos/eq/item.php?id=18855>A tattered note</a>
<br><b>Heneva Jexsped says </b>'Take this to help you on your journeys.'
<br><b>Heneva Jexsped gives you : </b><a href=http://phobos/eq/item.php?id=13564>Dirty Torn Robe*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>