<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=0000></a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=0000></a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=0></a></ul></td><td><hr><b>When Ikthar Fireheart spawns </b>
<hr><b>When Ikthar Fireheart spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Ikthar Fireheart says </b>'You look like the type who needs a suit of sturdy plate mail! I've got plenty of steel plate in stock but if you're looking for field plate we've been out of the [necessary ores] for quite some time.'
<p><b>You say, </b>'necessary ores'
<br><b>Ikthar Fireheart says </b>'Field plate is stronger than steel or fine steel plate and offers more protection to certain areas of the body. Unfortunately. it can only be crafted with high quality ores from those goblin infested mines. If you are planning on getting some ore I can instruct you in the [techniques of crafting field plate].'
<p><b>You say, </b>'techniques of crafting field plate'
<br><b>Ikthar Fireheart says </b>'Field plate may only be crafted in the special Freeport forge located in West Freeport. All pieces will require the appropriate plate mold. sea temper. a smithy hammer. leather backing. and chain jointing. Different amounts of ore will be needed for the various pieces of armor and the ore must be worked into [folded sheets].'
<p><b>You say, </b>'folded sheets'
<br><b>Ikthar Fireheart says </b>'Folded sheets of high quality ore can be crafted only in the special Freeport forge or Qeynos Royal Forge in the same fashion that regular folded sheets are fashioned in a standard forge. Field plate visors. collars. and bracers require only one folded sheet of high quality ore. Helms. pauldrons. girdles. vambraces. gauntlets. and boots require two folded sheets of high quality ore. Breastplates. greaves. and cloaks require three folded sheets of high quality ore.'
<p><b>You give Ikthar Fireheart : </b><a href=http://phobos/eq/item.php?id=0></a>
<br><b>Ikthar Fireheart says </b>'Thanks'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b>
<br><b>Ikthar Fireheart gives you : </b><a href=http://phobos/eq/item.php?id=0000></a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=0></a> has gotten better.</font>
<hr><b>When Ikthar Fireheart is killed </b>
<hr><b>When Ikthar Fireheart is killed </b>
</td></tr></table>