<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=0000></a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=0000></a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=0></a></ul></td><td><hr><b>When Imxil Tbrow spawns </b>
<hr><b>When Imxil Tbrow spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Imxil Tbrow says </b>'There are No greater circles of magic than those of the Teir'Dal.'
<p><b>You give Imxil Tbrow : </b><a href=http://phobos/eq/item.php?id=0></a>
<br><b>Imxil Tbrow says </b>'Thanks'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b>
<br><b>Imxil Tbrow gives you : </b><a href=http://phobos/eq/item.php?id=0000></a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=0></a> has gotten better.</font>
<hr><b>When Imxil Tbrow is killed </b>
<hr><b>When Imxil Tbrow is killed </b>
</td></tr></table>