<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=0000></a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=0000></a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=0></a></ul></td><td><hr><b>When Innkeep Paggie spawns </b>
<hr><b>When Innkeep Paggie spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Innkeep Paggie says </b>'Hello there [Your Name] ! You'll be happy to see that I am fully stocked with all my usual goods. Have a look around'
<p><b>You give Innkeep Paggie : </b><a href=http://phobos/eq/item.php?id=0></a>
<br><b>Innkeep Paggie says </b>'Thanks'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b>
<br><b>Innkeep Paggie gives you : </b><a href=http://phobos/eq/item.php?id=0000></a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=0></a> has gotten better.</font>
<hr><b>When Innkeep Paggie is killed </b>
<hr><b>When Innkeep Paggie is killed </b>
</td></tr></table>