<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=0000></a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=0000></a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=0></a></ul></td><td><hr><b>When Innkeep Rastle spawns </b>
<hr><b>When Innkeep Rastle spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Innkeep Rastle says </b>'Hail [Your Name]. Business is going well these days. I have a full stock of baked goods and other items for sale. Have a look around!'
<p><b>You give Innkeep Rastle : </b><a href=http://phobos/eq/item.php?id=0></a>
<br><b>Innkeep Rastle says </b>'Thanks'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b>
<br><b>Innkeep Rastle gives you : </b><a href=http://phobos/eq/item.php?id=0000></a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=0></a> has gotten better.</font>
<hr><b>When Innkeep Rastle is killed </b>
<hr><b>When Innkeep Rastle is killed </b>
</td></tr></table>