<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=55002>Bundle of Mail</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=55003>Note to Guard Bribbely</a><li><a href=http://phobos/eq/item.php?id=55027>Seawind Necklace</a></ul></td><td><hr><b>When Jasmine Yiur spawns </b>
<hr><b>When Jasmine Yiur spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Jasmine Yiur says </b>'Oh, hello. Sorry,'
<br><font color=green><b>Jasmine Yiur </b>lowers her head.</font>
<br><b>Jasmine Yiur says </b>'I am not really in best form today. I am in a bit of a [big predicament].'
<p><b>You say, </b>'big predicament'
<br><b>Jasmine Yiur says </b>'I work for the League of Antonican Bards. As you may or may not know, we are sometimes tasked with the delivery of mail to various cities around Norrath. A shipment of mail was to be delivered from here to Qeynos. It was supposed to arrive several days ago but I have received word that it never arrived. I have recently been informed by the guards that the ship was stolen before it could leave port. The guards reported seeing a large number of trolls board the ship and sail away with it in the dead of the night. The League and myself would be most appreciative of such a brave adventurer's [help].'
<p><b>You say, </b>'help'
<br><font color=green><b>Jasmine Yiur </b>gives you a warm smile.</font>
<br><b>Jasmine Yiur says </b>''That is the first time I have smiled in days, this mess has me so worried. Not only are we missing the mail but now an entire ship. Please take this note to Guard Bribbely. He is probably still near the docks investigating this matter.'
<br><b>Jasmine Yiur gives you : </b><a href=http://phobos/eq/item.php?id=55003>Note to Guard Bribbely</a>
<p><b>You give Jasmine Yiur : </b><a href=http://phobos/eq/item.php?id=55002>Bundle of Mail</a>
<br><b>Jasmine Yiur says </b>'I am so happy to see that you have returned, and with the mail! You are truly a hero. I will make certain that the other members of the League hear about you. You didn't find the missing ship you say? Guard Bribbely will not be pleased, but you did all that you could. Please take this for payment of your brave deeds. May we meet again.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Jasmine Yiur gives you : </b><a href=http://phobos/eq/item.php?id=55027>Seawind Necklace</a>
<hr><b>When Jasmine Yiur is killed </b>
<hr><b>When Jasmine Yiur is killed </b>
</td></tr></table>