<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19844>Note to Jerra Renlock</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17124>Mail Assembly Kit</a></ul></td><td><hr><b>When Jerra Renlock spawns </b>
<hr><b>When Jerra Renlock spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Jerra Renlock says </b>'Yes? What is it you want from me? I have nothing that you would be interested in. Not even money to pay the ridiculous taxes imposed by the Freeport Militia.'
<p><b>You say, </b>'dismal priest boots'
<br><b>Jerra Renlock says </b>''To assemble Dismal priest Mail Boots you will need to obtain two bricks of crude iron and smelt them in a forge with a Water Flask and this crude Boot Mold. Once that is done combine the Crude Iron Boots with two Ruined Coyote Pelts, and two Large Fire Beetle Tarsi in the Mail Assembly Kit.'
<p><b>You say, </b>'dismal priest bracer'
<br><b>Jerra Renlock says </b>'To assemble a Dismal priest Mail Bracer you will need to obtain a brick of crude iron and smelt it in a forge with a Water Flask and this Crude Bracer Mold. Once that is done, combine the Crude Iron Bracer with a Ruined Coyote Pelt and a Sand Scarab Hatchling Sternite in the Mail Assembly Kit.'
<p><b>You say, </b>'dismal priest breastplate'
<br><b>Jerra Renlock says </b>'To assemble a Dismal priest Breastplate you will need to obtain four bricks of crude iron and smelt them in a forge with a Water Flask and this Crude Breastplate Mold. Once that is done combine the Crude Iron Breastplate with a Coyote Pelt, a Giant Fire Beetle Carapace, and two Giant Fire Beetle Tergites in the Mail Assembly Kit.'
<p><b>You say, </b>'dismal priest gauntlets'
<br><b>Jerra Renlock says </b>'To assemble Dismal priest Gauntlets you will need to obtain two bricks of crude iron and smelt them in a forge with a Water Flask and this crude Gauntlet Mold. Once that is done combine the Crude Iron Gauntlets with a Ruined Coyote Pelt and two Sand Scarab Hatchling Tarsi in the Mail Assembly Kit.'
<p><b>You say, </b>'dismal priest greaves'
<br><b>Jerra Renlock says </b>'To assemble Dismal priest Greaves you will need to obtain two bricks of crude iron and smelt them in a forge with a Water Flask and this Crude Greaves Mold. Once that is done combine the Crude Iron Greaves with two Low Quality Coyote Pelts and two Large Fire Beetle Sternites in the Mail Assembly Kit.'
<p><b>You say, </b>'dismal priest helm'
<br><b>Jerra Renlock says </b>'To assemble a Dismal priest Helm you will need to obtain two bricks of crude iron and smelt them in a forge with a Water Flask and this Crude Helm Mold. Once that is done combine the Crude Iron Helm with a Ruined Coyote Pelt and two Sand Scarab Hatchling Eyes in the Mail Assembly Kit.'
<p><b>You say, </b>'dismal priest vambraces'
<br><b>Jerra Renlock says </b>'To assemble Dismal priest Vambraces you will need to obtain two bricks of crude iron and smelt them in a forge with a Water Flask and this Crude Vambrace Mold. Once that is done combine the Crude Iron Vambraces with a Low Quality Coyote Pelt and two Large Fire Beetle Patella in the Mail Assembly Kit.'
<p><b>You give Jerra Renlock : </b><a href=http://phobos/eq/item.php?id=19844>Note to Jerra Renlock</a>
<br><b>Jerra Renlock says </b>'Ah, so Zhem wants me to assist you with some armor. You will surely need it if you are an associate of the likes of him. This Mail Assembly Kit will be needed for you to construct your armor. The materials required depend on the armor section you plan to construct. Do you plan to construct a [dismal priest helm], a [dismal priest bracer], [dismal priest gauntlets], [dismal priest boots], [dismal priest vambraces], [dismal priest greaves], or a [dismal priest breastplate].'
<br><b>Jerra Renlock gives you : </b><a href=http://phobos/eq/item.php?id=17124>Mail Assembly Kit</a>
<hr><b>When Jerra Renlock is killed </b>
<hr><b>When Jerra Renlock is killed </b>
</td></tr></table>