<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=0000></a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=0000></a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=0></a></ul></td><td><hr><b>When Jyle Windshot spawns </b>
<hr><b>When Jyle Windshot spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Jyle Windshot says </b>'Greetings. friend!!  Nice to meet you.  I see you enjoy barging into other people's rooms.  No problem.  I enjoy the company.  What are you looking for?'
<p><b>You give Jyle Windshot : </b><a href=http://phobos/eq/item.php?id=0></a>
<br><b>Jyle Windshot says </b>'Thanks'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b>
<br><b>Jyle Windshot gives you : </b><a href=http://phobos/eq/item.php?id=0000></a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=0></a> has gotten better.</font>
<hr><b>When Jyle Windshot is killed </b>
<hr><b>When Jyle Windshot is killed </b>
</td></tr></table>