<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20674>Tiny Lute</a><li><a href=http://phobos/eq/item.php?id=20684>Tenal's note to Kargek</a><li><a href=http://phobos/eq/item.php?id=20679>Spiroc Wingblade</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18083>Redblade's Legacy</a><li><a href=http://phobos/eq/item.php?id=17859>Red Scabbard</a></ul></td><td><p><b>You say, </b>'Hail'
<p><b>You say, </b>'Wenden'
<p><b>You say, </b>'red sword Scabbard'
<p><b>You say, </b>'favor'
<p><b>You give Kargek Redblade : </b><a href=http://phobos/eq/item.php?id=20674>Tiny Lute</a>
<br><b>Kargek Redblade says </b>'Thank you for delivering the note to my Associate. Take this book - It will tell you A little of the history of the old scabbard. If you would like to own the scabbard, seek out my younger brother Tenal and give him the book.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Kargek Redblade gives you : </b><a href=http://phobos/eq/item.php?id=18083>Redblade's Legacy</a>
<p><b>You give Kargek Redblade : </b><a href=http://phobos/eq/item.php?id=20684>Tenal's note to Kargek</a>, <a href=http://phobos/eq/item.php?id=20679>Spiroc Wingblade</a>
<br><b>Kargek Redblade says </b>'What is this? A note from my brother? Thank you for the gift as well.'
<br><font color=green><b>Kargek Redblade </b>reads the note and hands you the red scabbard. Your mind is filled with the sound of battle and a voice. 'Place the ancient sword blade, ancient blade, finely crafted dragon head hilt, and the jeweled dragon head hilt into the scabbard to receive your rewards. If you think you are worthy, place your rewards into the scabbard and see what havoc you can unleash on the world.'</font>
<br><font color=green><b>Kargek Redblade </b>addresses you as you turn to leave. 'One more thing. Gartrog over there has told me of a great discovery. Seems there are all sorts of stones being found in the recently discovered lost dungeons scattered around Antonica.  The Wayfarer's Brotherhood has found a way to make items even more powerful by using the stones with existing items.'</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Kargek Redblade gives you : </b><a href=http://phobos/eq/item.php?id=17859>Red Scabbard</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>