<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18856>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13565>Old Stained Robe*</a></ul></td><td><hr><b>When Konious Eranon spawns </b>
<hr><b>When Konious Eranon spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Konious Eranon says </b>'Greetings!  I am the mighty Konious Eranon, Master Enchanter, devoted follower of Innoruuk, and loyal assistant to the all-powerful Nexvok.'
<p><b>You give Konious Eranon : </b><a href=http://phobos/eq/item.php?id=18856>A tattered note</a>
<br><b>Konious Eranon says </b>'Take this [Your Name], to help you in your journeys.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Konious Eranon gives you : </b><a href=http://phobos/eq/item.php?id=13565>Old Stained Robe*</a>
<hr><b>When Konious Eranon is killed </b>
<hr><b>When Konious Eranon is killed </b>
</td></tr></table>