<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13818>Boat Beacon</a><li><a href=http://phobos/eq/item.php?id=13814>L.S. Pouch</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12146>Ak'Anon's Portrait</a><li><a href=http://phobos/eq/item.php?id=9216></a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=361>Wolves of the North</a><li><a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a><li><a href=http://phobos/eq/faction.php?id=143>Heretics</a><li><a href=http://phobos/eq/faction.php?id=147>High Guard of Erudin</a><li><a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a><li><a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=275>Rogues of the White Rose</a></ul></td><td><hr><b>When Lenka Stoutheart spawns </b>
<hr><b>When Lenka Stoutheart spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Lenka Stoutheart says </b>'If I catch the little thief who took my pouch, may the Wolves of the North have no mercy on em!!'
<p><b>You give Lenka Stoutheart : </b><a href=http://phobos/eq/item.php?id=13818>Boat Beacon</a>
<br><b>Lenka Stoutheart says </b>'Oh!! You must work for that Erudite named Palatos. I guess he won't have to spend anymore money drinking in Freeport. Here. Here is the portrait I kept until he could get me a new boat beacon.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Lenka Stoutheart gives you : </b><a href=http://phobos/eq/item.php?id=12146>Ak'Anon's Portrait</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=361>Wolves of the North</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=143>Heretics</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=147>High Guard of Erudin</a> has gotten better.</font>
<p><b>You give Lenka Stoutheart : </b><a href=http://phobos/eq/item.php?id=13814>L.S. Pouch</a>
<br><b>Lenka Stoutheart says </b>'You found my pouch! Thanks kid. Let me buy you A drink and this is for the good work. Hmmmm. It looks as though they took my voucher. Darn it! Hey... It looks like they were using my bag to hold items they were stealing. Here you go. You can have it. It looks like junk. '
<br><font color=yellow>You gain experience!!</font>
<br><b>Lenka Stoutheart gives you : </b><a href=http://phobos/eq/item.php?id=9216></a>
<br><b>You receive </b> 2sp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=361>Wolves of the North</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=275>Rogues of the White Rose</a> has gotten worse.</font>
<hr><b>When Lenka Stoutheart is killed </b>
<hr><b>When Lenka Stoutheart is killed </b>
</td></tr></table>