<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=0000></a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=0000></a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=0></a></ul></td><td><hr><b>When Nesin Tapper spawns </b>
<hr><b>When Nesin Tapper spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Nesin Tapper says </b>'I am not here for you to make fancy with!! Just order something!'
<p><b>You give Nesin Tapper : </b><a href=http://phobos/eq/item.php?id=0></a>
<br><b>Nesin Tapper says </b>'Thanks'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b>
<br><b>Nesin Tapper gives you : </b><a href=http://phobos/eq/item.php?id=0000></a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=0></a> has gotten better.</font>
<hr><b>When Nesin Tapper is killed </b>
<hr><b>When Nesin Tapper is killed </b>
</td></tr></table>