<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13158>Rebby's Rat Whiskers</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18923>Message to Rebby</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=48>Coalition of Tradefolk Underground</a><li><a href=http://phobos/eq/faction.php?id=47>Coalition of Trade Folk</a><li><a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a><li><a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Nestral TGaza says </b>'It's been so busy around here lately. Barely time to eat and sleep, much have my fun. Oh well, keeps me employed. But and I really could use someone to [ help ] me out around here.'
<p><b>You say, </b>'help'
<br><b>Nestral TGaza says </b>'Yea and if you can help me out with A few things that'd be great. Geez and where do we Start? I need someone to run over to [ Janam and Rebbys ]? Can you do that for me?'
<p><b>You say, </b>'Janam and Rebbys'
<br><b>Nestral TGaza says </b>'Janam and Rebby are A couple of merchants working the area around the Theater of the Tranquil and the Ashen Order, in West Freeport. It's part of my job to keep tabs on those two rascals. I need someone to take this note to Rebby for me. Don't worry, your efforts won't go unnoticed [Your Name].'
<br><b>Nestral TGaza gives you : </b><a href=http://phobos/eq/item.php?id=18923>Message to Rebby</a>
<p><b>You give Nestral TGaza : </b><a href=http://phobos/eq/item.php?id=13158>Rebby's Rat Whiskers</a>
<br><b>Nestral TGaza says </b>'Thank you [Your Name], You have done well.'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 1cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=48>Coalition of Tradefolk Underground</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=47>Coalition of Trade Folk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=31>Carson McCabe</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=53>Corrupt Qeynos Guards</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>