<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12270>A Sealed Letter</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=14598>Sonic Wolf Shaped Cookie</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=86>Dismal Rage</a><li><a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Netuk Phenzon says </b>'Welcome [Your Name]. Let us fill your heart with hate. May you carry that hate unto your fellow citizens. Innoruuk has need of your services. We have A [ mission ] for you. '
<p><b>You say, </b>'mission'
<br><b>Netuk Phenzon says </b>'There is a man called Groflah Steadirt. He runs A weapons shop here in Freeport. Our sources tell us he was given A piece of parchment taken from one of our allies. Who that is is none of your business. We only require you to recover the parchment, which he No doubt has on him. End his life and return the note to me. Do not let me see your miserable face again until you have the parchment. '
<p><b>You give Netuk Phenzon : </b><a href=http://phobos/eq/item.php?id=12270>A Sealed Letter</a>
<br><b>Netuk Phenzon says </b>'This isn't much, but let it show you the gratitude the Dismal Rage has for your deeds.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Netuk Phenzon gives you : </b><a href=http://phobos/eq/item.php?id=14598>Sonic Wolf Shaped Cookie</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=86>Dismal Rage</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>