<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18854>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13562>Dark Stained Robe*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Nexvok Thirod says </b>'I am Nexvok, master wizard of the Dismal Rage.  My associates Heneva and Konious and I provide our services to master Zarn on a regular basis.  People of our talent are in high demand. and Pietro pays well, so we are, of course, very loyal.'
<p><b>You give Nexvok Thirod : </b><a href=http://phobos/eq/item.php?id=18854>A tattered note</a>
<br><b>Nexvok Thirod says </b>'Thanks'
<br><font color=yellow>You gain experience!!</font>
<br><b>Nexvok Thirod gives you : </b><a href=http://phobos/eq/item.php?id=13562>Dark Stained Robe*</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>