<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13922>Snapped Pole</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a><li><a href=http://phobos/eq/faction.php?id=48>Coalition of Tradefolk Underground</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a><li><a href=http://phobos/eq/faction.php?id=258>Priests of Marr</a></ul></td><td><hr><b>When Olunea Miltin spawns </b>
<hr><b>When Olunea Miltin spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Olunea Miltin says </b>'Hello. It is good to meet you. Try not to scare the fish away. This is A good spot I supply fish to the Grub N' Grog. The patrons there love me!'
<p><b>You give Olunea Miltin : </b><a href=http://phobos/eq/item.php?id=13922>Snapped Pole</a>
<br><b>Olunea Miltin says </b>'Great! Thank you stranger. The rogues must have broken it. At least I could repair it. It would be seasons before I could afford another pole.'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 8cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=48>Coalition of Tradefolk Underground</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=258>Priests of Marr</a> has gotten worse.</font>
<hr><b>When Olunea Miltin is killed </b>
<hr><b>When Olunea Miltin is killed </b>
</td></tr></table>