<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=item1></a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13558>Patched Violet Robe*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Opal Darkbriar says </b>'Hello.'
<p><b>You give Opal Darkbriar : </b><a href=http://phobos/eq/item.php?id=18739>A tattered note</a>
<br><b>Opal Darkbriar says </b>'Thanks.'
<br><b>Opal Darkbriar gives you : </b><a href=http://phobos/eq/item.php?id=13558>Patched Violet Robe*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>