<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13817>Capt. Orlin's Spiced Ale</a><li><a href=http://phobos/eq/item.php?id=13818>Boat Beacon</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12145>Beacon Mount</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=56>Craftkeepers</a><li><a href=http://phobos/eq/faction.php?id=145>High Council of Erudin</a><li><a href=http://phobos/eq/faction.php?id=147>High Guard of Erudin</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=143>Heretics</a></ul></td><td><hr><b>When Palatos Kynarn spawns </b>
<hr><b>When Palatos Kynarn spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Palatos Kynarn says </b>'What do you want?  Can't you see that I wish to be alone?!  I have no need nor desire to speak with anyone.  I have a minor dilemma to ponder and the only person I wish to speak with is the [captain].'
<p><b>You say, </b>'captain'
<br><b>Palatos Kynarn says </b>'If you have to ask that. you should not be in this fine establishment.'
<p><b>You say, </b>'Danaria sent me'
<br><b>Palatos Kynarn says </b>'If you are working for Danaria, you have been misguided. You will go back to her empty handed. Now leave. The [captain] and I have some business to discuss.'
<p><b>You give Palatos Kynarn : </b><a href=http://phobos/eq/item.php?id=13817>Capt. Orlin's Spiced Ale</a> (x4)
<br><b>Palatos Kynarn says </b>'Ahh.. I.. Need help.. You.. take this.. Go build.. boat beacon. Ask gnomes about.. boat beacon. They know how.. Then bring back.. Unnnhh!! Prexus help me!! I will never drink again.'
<br><font color=green><b>Palatos Kynarn </b>In his drunkedness, Palatos advises you to seek out Svinal Wyspin, a Gnome merchant in North Freeport.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Palatos Kynarn gives you : </b><a href=http://phobos/eq/item.php?id=12145>Beacon Mount</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=56>Craftkeepers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=145>High Council of Erudin</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=147>High Guard of Erudin</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=143>Heretics</a> has gotten worse.</font>
<p><b>You give Palatos Kynarn : </b><a href=http://phobos/eq/item.php?id=13818>Boat Beacon</a>
<br><b>Palatos Kynarn says </b>'Thanks.. That saved me a lot of money. Now I can spend more time with the captain before I give this back to Lenka Stoutheart. Here is a little so...mething.'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 1pp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=56>Craftkeepers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=145>High Council of Erudin</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=147>High Guard of Erudin</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=143>Heretics</a> has gotten worse.</font>
<hr><b>When Palatos Kynarn is killed </b>
<hr><b>When Palatos Kynarn is killed </b>
</td></tr></table>