<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18743>A tattered note</a><li><a href=http://phobos/eq/item.php?id=18961>Translated Parchment</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13561>Faded Crimson Tunic*</a><li><a href=http://phobos/eq/item.php?id=12153>Rage War Maul</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a><li><a href=http://phobos/eq/faction.php?id=86>Dismal Rage</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Pietro Zarn says </b>'Who are you that you dare to speak with the great Pietro Zarn!! I see nothing more than a whelp in front of me. Innoruuk himself speaks with me. And now you expect me to waste words on you, a common. Begone [Your Name] . You have nothing to peak my interest, only my rage.'
<p><b>You give Pietro Zarn : </b><a href=http://phobos/eq/item.php?id=18743>A tattered note</a>
<br><b>Pietro Zarn says </b>'A new member to carry the rage of Innoruuk into the city and beyond. How wonderful. I must admit that you do not appear to carry the rage within. Hopefully you shall color the battlefields with the blood of many knights from the Hall of Truth. Here. Wear this tunic with pride. Ha ha ha!! We shall see young one. We shall see.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Pietro Zarn gives you : </b><a href=http://phobos/eq/item.php?id=13561>Faded Crimson Tunic*</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=86>Dismal Rage</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten worse.</font>
<p><b>You give Pietro Zarn : </b><a href=http://phobos/eq/item.php?id=18961>Translated Parchment</a>
<br><b>Pietro Zarn says </b>'I will deal with this [Your Name]. Take this and know that you are welcomed by the Dismal Rage.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Pietro Zarn gives you : </b><a href=http://phobos/eq/item.php?id=12153>Rage War Maul</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>