<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19928>Sharpened Dismal Long Sword</a><li><a href=http://phobos/eq/item.php?id=19852>Giant Rattlesnake Skin</a><li><a href=http://phobos/eq/item.php?id=26644>A Sealed Letter</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19940>Dismal Rage Long Sword</a><li><a href=http://phobos/eq/item.php?id=17124>Mail Assembly Kit</a></ul></td><td><hr><b>When Quan Nektogo spawns </b>
<hr><b>When Quan Nektogo spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Quan Nektogo says </b>'Sorry friend. I have nothing to sell at the moment. These taxes imposed by the Freeport Militia and the Coalition of Tradefolk take a heavy toll on us poor folk.'
<p><b>You say, </b>'forge'
<br><b>Quan Nektogo says </b>'You can find them all over freeport. Inside and out of many of the buildings where Weapons and armor are sold.'
<p><b>You say, </b>'dismal knight boots'
<br><b>Quan Nektogo says </b>'To assemble Dismal Knight Boots you will need to obtain two bricks of crude iron and smelt them in a [forge] with a Water Flask and this crude Boot Mold. Once that is done combine the Crude Iron Boots with two Ruined Cat Pelts, and two Large Leaf Scarab Tarsi in the Mail Assembly Kit.'
<p><b>You say, </b>'dismal knight bracer'
<br><b>Quan Nektogo says </b>'To assemble a Dismal Knight Bracer you will need to obtain a brick of crude iron and smelt it in a [forge] with a Water Flask and this Crude Bracer Mold. Once that is done, combine the Crude Iron Bracer with a Ruined Cat Pelt and a Leaf Scarab Sternite in the Mail Assembly Kit.'
<p><b>You say, </b>'dismal knight breastplate'
<br><b>Quan Nektogo says </b>'To assemble a Dismal Knight Breastplate you will need to obtain four bricks of crude iron and smelt them in a [forge] with a Water Flask and this Crude Breastplate Mold. Once that is done combine the Crude Iron Breastplate with a Medium Quality Cat Pelt, a Giant Leaf Scarab Carapace, and two Giant Leaf Scarab Tergites in the Mail Assembly Kit.'
<p><b>You say, </b>'dismal knight gauntlets'
<br><b>Quan Nektogo says </b>'To assemble Dismal Knight Gauntlets you will need to obtain two bricks of crude iron and smelt them in a [forge] with a Water Flask and this crude Gauntlet Mold. Once that is done combine the Crude Iron Gauntlets with a Ruined Cat Pelt and two Leaf Scarab Tarsi in the Mail Assembly Kit.'
<p><b>You say, </b>'dismal knight greaves'
<br><b>Quan Nektogo says </b>'To assemble Dismal Knight Greaves you will need to obtain two bricks of crude iron and smelt them in a [forge] with a Water Flask and this Crude Greaves Mold. Once that is done combine the Crude Iron Greaves with two Low Quality Cat Pelts and two Large Leaf Scarab Sternites in the Mail Assembly Kit.'
<p><b>You say, </b>'dismal knight helm'
<br><b>Quan Nektogo says </b>'To assemble a Dismal Knight Helm you will need to obtain two bricks of crude iron and smelt them in a [forge] with a Water Flask and this Crude Helm Mold. Once that is done combine the Crude Iron Helm with a Ruined Cat Pelt and two Large Leaf Scarab Eyes in the Mail Assembly Kit.'
<p><b>You say, </b>'dismal knight vambraces'
<br><b>Quan Nektogo says </b>'To assemble Dismal Knight Vambraces you will need to obtain two bricks of crude iron and smelt them in a [forge] with a Water Flask and this Crude Vambrace Mold. Once that is done combine the Crude Iron Vambraces with a Low Quality Cat Pelt and two Large Leaf Scarab Patella in the Mail Assembly Kit.'
<p><b>You give Quan Nektogo : </b><a href=http://phobos/eq/item.php?id=19928>Sharpened Dismal Long Sword</a>, <a href=http://phobos/eq/item.php?id=19852>Giant Rattlesnake Skin</a>
<br><font color=green><b>Quan Nektogo </b> fashions a grip out of the giant rattlesnake skin and polishes the blade of the sword with a strange glowing substance.</font>
<br><b>Quan Nektogo says </b>'May your new sword see the deaths of many enemies!'
<br><font color=yellow>You gain experience!!</font>
<br><b>Quan Nektogo gives you : </b><a href=http://phobos/eq/item.php?id=19940>Dismal Rage Long Sword</a>
<p><b>You give Quan Nektogo : </b><a href=http://phobos/eq/item.php?id=26644>A Sealed Letter</a>
<br><b>Quan Nektogo says </b>'Sorry buddy I didn't realize you were one of us. I've got no problem helping out an associate of Gunex. You'll need this Mail Assembly Kit to construct your new armor. The materials required depend on the section of armor you're planning on crafting. Do you plan on crafting a [dismal knight helm], a [dismal knight bracer], [dismal knight gauntlets], [dismal knight boots], [dismal knight vambraces], [dismal knight greaves], or a [dismal knight breastplate].'
<br><b>Quan Nektogo gives you : </b><a href=http://phobos/eq/item.php?id=17124>Mail Assembly Kit</a>
<hr><b>When Quan Nektogo is killed </b>
<hr><b>When Quan Nektogo is killed </b>
</td></tr></table>