<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=26644>A Sealed Letter</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17124>Mail Assembly Kit</a></ul></td><td><hr><b>When Rolfic Gohar spawns </b>
<hr><b>When Rolfic Gohar spawns </b>
<p><b>You say, </b>'hail'
<br><b>Rolfic Gohar says </b>'I am but a poor peddler of trinkets living amongst the rats and beggars of these slums. Perhaps you will purchase some of my wares and help a struggling merchant?'
<p><b>You say, </b>'forge'
<br><b>Rolfic Gohar says </b>'You can find forges all over freeport.'
<p><b>You say, </b>'dismal warrior breastplate'
<br><b>Rolfic Gohar says </b>''To assemble a Dismal Warrior Breastplate you will need to obtain four bricks of crude iron and smelt them in a [forge] with a Water Flask and this Crude Breastplate Mold. Once that is done combine the Crude Iron Breastplate with a Coyote Pelt, a Dune Tarantula Thorax, and a Dune Tarantula Abdomen in the Mail Assembly Kit.'
<p><b>You say, </b>'dismal warrior helm'
<br><b>Rolfic Gohar says </b>'To assemble a Dismal Warrior Helm you will need to obtain two bricks of crude iron and smelt them in a [forge] with a Water Flask and this Crude Helm Mold. Once that is done combine the Crude Iron Helm with a Ruined Coyote Pelt and two Desert Tarantula Eyes in the Mail Assembly Kit.'
<p><b>You say, </b>'dismal warrior bracer'
<br><b>Rolfic Gohar says </b>'To assemble a Dismal Warrior Mail Bracer you will need to obtain a brick of crude iron and smelt it in a [forge] with a Water Flask and this Crude Bracer Mold. Once that is done, combine the Crude Iron Bracer with a Ruined Coyote Pelt and a Dune Spiderling Tibia in the Mail Assembly Kit.'
<p><b>You say, </b>'dismal warrior gauntlets'
<br><b>Rolfic Gohar says </b>'To assemble Dismal Warrior Gauntlets you will need to obtain two bricks of crude iron and smelt them in a [forge] with a Water Flask and this crude Gauntlet Mold. Once that is done combine the Crude Iron Gauntlets with a Ruined Coyote Pelt and two Dune Spiderling Tarsi in the Mail Assembly Kit.'
<p><b>You say, </b>'dismal warrior boots'
<br><b>Rolfic Gohar says </b>'To assemble Dismal Warrior Mail Boots you will need to obtain two bricks of crude iron and smelt them in a [forge] with a Water Flask and this crude Boot Mold. Once that is done combine the Crude Iron Boots with two Ruined Coyote Pelts, and two Dune Spiderling Hairs in the Mail Assembly Kit.'
<p><b>You say, </b>'dismal warrior vambraces'
<br><b>Rolfic Gohar says </b>'To assemble Dismal Warrior Vambraces you will need to obtain two bricks of crude iron and smelt them in a [forge] with a Water Flask and this Crude Vambrace Mold. Once that is done combine the Crude Iron Vambraces with a Low Quality Coyote Pelt and two Desert Tarantula Patella in the Mail Assembly Kit.'
<p><b>You say, </b>'dismal warrior greaves'
<br><b>Rolfic Gohar says </b>'To assemble Dismal Warrior Greaves you will need to obtain two bricks of crude iron and smelt them in a [forge] with a Water Flask and this Crude Greaves Mold. Once that is done combine the Crude Iron Greaves with two Low Quality Coyote Pelts and two Desert Tarantula Femurs in the Mail Assembly Kit.'
<p><b>You give Rolfic Gohar : </b><a href=http://phobos/eq/item.php?id=26644>A Sealed Letter</a>
<br><b>Rolfic Gohar says </b>'I see now we have similar interests. I will help you get outfitted in an affordable suit of armor to help you in your endeavors. You will need this Mail Assembly Kit to aid you in the construction of the armor. The materials required depend on the armor section you desire to craft. Do you plan to construct a [dismal warrior helm], a [dismal warrior bracer], [dismal warrior gauntlets], [dismal warrior boots], [dismal warrior vambraces], [dismal warrior greaves], or a [dismal warrior breastplate].'
<br><b>Rolfic Gohar gives you : </b><a href=http://phobos/eq/item.php?id=17124>Mail Assembly Kit</a>
<hr><b>When Rolfic Gohar is killed </b>
<hr><b>When Rolfic Gohar is killed </b>
</td></tr></table>