<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18474>Scroll of the Burning Dead</a><li><a href=http://phobos/eq/item.php?id=31492>Ghostly Bridle</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=31496>Bridle of Sir Ariam</a></ul></td><td><p><b>You say, </b>'befallen'
<br><b>Sir Artanis says </b>'You did well to ride swiftly with this news. I must take this directly to Valeron Dushire. If you learn more about this plot that would unleash this monster upon Norrath or wish to someday soon aid the Knights of Truth in putting down this evil, then return to speak to me again at a later time.'
<p><b>You give Sir Artanis : </b><a href=http://phobos/eq/item.php?id=18474>Scroll of the Burning Dead</a>
<br><b>Sir Artanis says </b>'By Marr, what is this? .. Burning Dead .. .. Marnek! By my blade this must be stopped! Where did you find this?'
<p><b>You give Sir Artanis : </b><a href=http://phobos/eq/item.php?id=31492>Ghostly Bridle</a>
<br><b>Sir Artanis says </b>'It was a fine and valiant steed to serve its master beyond the grave, but it looks to be near its end. But I have a fine eye for horses, and I dare say it will serve you one more time.'
<br><b>Sir Artanis gives you : </b><a href=http://phobos/eq/item.php?id=31496>Bridle of Sir Ariam</a>
</td></tr></table>