<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=0000></a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=0000></a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=0></a></ul></td><td><hr><b>When Talym Shoontar spawns </b>
<hr><b>When Talym Shoontar spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Talym Shoontar says </b>'Hello [Your Name], I hope your hunt is going well.'
<p><b>You give Talym Shoontar : </b><a href=http://phobos/eq/item.php?id=0></a>
<br><b>Talym Shoontar says </b>'Thanks'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b>
<br><b>Talym Shoontar gives you : </b><a href=http://phobos/eq/item.php?id=0000></a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=0></a> has gotten better.</font>
<hr><b>When Talym Shoontar is killed </b>
<hr><b>When Talym Shoontar is killed </b>
</td></tr></table>