<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13885>Orc Pawn Pick</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=></a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=47>Coalition of Trade Folk</a><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a><li><a href=http://phobos/eq/faction.php?id=217>Merchants of Qeynos</a><li><a href=http://phobos/eq/faction.php?id=48>Coalition of Tradefolk Underground</a></ul></td><td><hr><b>When Tohsan Hallard spawns </b>
<hr><b>When Tohsan Hallard spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Tohsan Hallard says </b>'Greetings and welcome to Hallard's!  You will find many aged weapons begging you to shine them up and make them great once more.  We will gladly pay you top dollar for any rusty weapons you may have found littering the Commonlands.  I have a [special offer] for those who have obtained orc pawn picks.'
<p><b>You say, </b>'what special offer'
<br><b>Tohsan Hallard says </b>'I will pay some silver pieces for every four orc pawn picks returned to me.  I shall also throw in a ticket to the Highpass Hold lottery.  It could be a winner!!'
<p><b>You give Tohsan Hallard : </b><a href=http://phobos/eq/item.php?id=13885>Orc Pawn Pick</a> (x4)
<br><b>Tohsan Hallard says </b>'As I promised, some silver and of course, the Highpass lottery ticket. Oh yes, I forgot to mention the ticket was for last season's lottery. Ha Ha!! You now own a losing Highpass lottery ticket, lucky you! Ha!!'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 3sp
<br><b>Tohsan Hallard gives you : </b><a href=http://phobos/eq/item.php?id=></a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=47>Coalition of Trade Folk</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=217>Merchants of Qeynos</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=48>Coalition of Tradefolk Underground</a> has gotten better.</font>
<hr><b>When Tohsan Hallard is killed </b>
<hr><b>When Tohsan Hallard is killed </b>
</td></tr></table>