<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19931>Bundle of Hardwood Staves</a><li><a href=http://phobos/eq/item.php?id=19929>Crate of Pick Axe Heads</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12270>A Sealed Letter</a><li><a href=http://phobos/eq/item.php?id=13903>Bent Playing Card</a><li><a href=http://phobos/eq/item.php?id=19919>Faceted Blue Gem</a><li><a href=http://phobos/eq/item.php?id=19920>Dull Coalition Dirk</a></ul></td><td><hr><b>When Tovan Tenlah spawns </b>
<hr><b>When Tovan Tenlah spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Tovan Tenlah says </b>'I suppose you're one of Nestrals new employees, eh? Well if that's the case I can help get you outfitted with some [gear] necessary for people in this [line of work].'
<p><b>You say, </b>'gear'
<br><b>Tovan Tenlah says </b>'The first thing you need is a suit of sturdy traders clothing. Take this note to Verona Rankin and she'll help you with a suit tailored to your needs. Once you have been outfitted in your traders clothing return to me and I will inform you of your [next task].'
<br><b>Tovan Tenlah gives you : </b><a href=http://phobos/eq/item.php?id=12270>A Sealed Letter</a>
<p><b>You say, </b>'next task'
<br><b>Tovan Tenlah says </b>'Ready to get to work are you? Listen carefully. Outside Freeports South gate you will find one of our employees, Rigg Nostra, who is acting as an intermediary between the Coalition of Tradefolk and some recently acquired business associates. Give him this card so he knows I've sent you and he will give you further instructions. Do not mention any of our names in public. The Freeport Militia would likely impose high taxes on the Coalition if they found out about the goods being exchanged to us by our new associates.'
<br><b>Tovan Tenlah gives you : </b><a href=http://phobos/eq/item.php?id=13903>Bent Playing Card</a>
<hr><b>When Tovan Tenlah is killed </b>
<hr><b>When Tovan Tenlah is killed </b>
<p><b>You give Tovan Tenlah : </b><a href=http://phobos/eq/item.php?id=19931>Bundle of Hardwood Staves</a>, <a href=http://phobos/eq/item.php?id=19929>Crate of Pick Axe Heads</a>
<br><b>Tovan Tenlah says </b>'Sharpen this dagger and take it with this gem and a rattlesnake skin to Verona Rankin.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Tovan Tenlah gives you : </b><a href=http://phobos/eq/item.php?id=19919>Faceted Blue Gem</a>
<br><b>Tovan Tenlah gives you : </b><a href=http://phobos/eq/item.php?id=19920>Dull Coalition Dirk</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>