<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13829>Drom's Champagne</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12196>Bunker Cell #1</a></ul></td><td><p><b>You say, </b>'Lucan'
<br><b>Tykar Renlin says </b>'That man is no just ruler. He has jailed me and my friend Zimel for merely begging.'
<p><b>You say, </b>'Hail'
<br><b>Tykar Renlin says </b>'Do you have any spare coppers for a thirsty soul?'
<p><b>You say, </b>'What can you tell me of Zimel'
<br><b>Tykar Renlin says </b>'What?! You know my friend Zimel?! I would like to speak of him, but my mouth is so parched. Maybe a fine grog would loosen my lips. I am uncertain which flavor shall do the trick.'
<p><b>You give Tykar Renlin : </b><a href=http://phobos/eq/item.php?id=13829>Drom's Champagne</a> x4
<br><b>Tykar Renlin says </b>'Oooh!! That is the taste. My lips are almost loose. Maybe another will do the trick.'
<br><b>Tykar Renlin says </b>'Oooh!! That is the taste. My lips are almost loose. Maybe another will do the trick.'
<br><b>Tykar Renlin says </b>'Oooh!! That is the taste. My lips are almost loose. Maybe another will do the trick.'
<br><b>Tykar Renlin says </b>'Ahh!! That was good. Now where were we?. Oh yes. My friend Zimel is a fellow beggar. He was locked up in the arena. They were going to let him go when the Freeport Militia came for him. Ha!! He is crazy as a troll now. I took this blanket from his cell before I was released. I no longer need it and my guilt has reached its peak. I do not want crazy old Zimel to freeze. Perhaps you can return it to him.'
<br><b>Tykar Renlin gives you : </b><a href=http://phobos/eq/item.php?id=12196>Bunker Cell #1</a>
</td></tr></table>