<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18744>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13561>Faded Crimson Tunic*</a></ul></td><td><hr><b>When Venox Tarkog spawns </b>
<hr><b>When Venox Tarkog spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Venox Tarkog says </b>'Welcome to the shrine of the Dismal Rage.  May [Innoruuk] guide your every move in life.  Here. we will teach you to release your rage unto the world.  My priests are at your disposal.'
<p><b>You say, </b>'Innoruuk'
<br><b>Venox Tarkog says </b>'You do not even know the name of the Prince of Hate!  That is a crime in here.  Our god Innoruuk speaks with Pietro Zarn himself.  It was Innoruuk who told him to create the Dismal Rage.  You should speak with our family.  Perhaps someone will help you better understand our beliefs.'
<p><b>You give Venox Tarkog : </b><a href=http://phobos/eq/item.php?id=18744>A tattered note</a>
<br><b>Venox Tarkog says </b>'Take this to help you on your journeys #name.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Venox Tarkog gives you : </b><a href=http://phobos/eq/item.php?id=13561>Faded Crimson Tunic*</a>
<hr><b>When Venox Tarkog is killed </b>
<hr><b>When Venox Tarkog is killed </b>
</td></tr></table>