<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Vesagar Nekio says </b>'Welcome into our church of rage.  I am Vesagar Nekio. servant of Innoruuk.  If you should need me to [cure poison]. [cure disease]. or if you [require healing]. just let me know.'
<br><b>Vesagar Nekio says </b>'Blasphemer!!  You are no ally of the Dismal Rage.  Run while you still have legs!!'
<p><b>You say, </b>'cure poison'
<br><b>Vesagar Nekio says </b>'Ally of the Dismal Rage,  Be free of poison!!'
<br><font color=brown><b>Vesagar Nekio casts a spell : </b><a href=http://phobos/eq/spell.php?id=203>Cure Poison</a>.</font>
<p><b>You say, </b>'cure disease'
<br><b>Vesagar Nekio says </b>'Ally of the Dismal Rage,  Be free of disease!!'
<br><font color=brown><b>Vesagar Nekio casts a spell : </b><a href=http://phobos/eq/spell.php?id=213>Cure Disease</a>.</font>
<p><b>You say, </b>'require healing'
<br><b>Vesagar Nekio says </b>'Ally of the Dismal Rage,  Be healed of all your wounds!!'
<br><font color=brown><b>Vesagar Nekio casts a spell : </b><a href=http://phobos/eq/spell.php?id=13>Complete Healing</a>.</font>
</td></tr></table>