<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20668>Unjeweled Dragon Head Hilt</a><li><a href=http://phobos/eq/item.php?id=10037>Diamond</a><li><a href=http://phobos/eq/item.php?id=10036>Black Sapphire</a><li><a href=http://phobos/eq/item.php?id=10053>Jacinth</a><li><a href=http://phobos/eq/item.php?id=20669>Severely Damaged Dragon Head Hilt</a><li><a href=http://phobos/eq/item.php?id=20666>Rejesiam Ore</a><li><a href=http://phobos/eq/item.php?id=20677>Ball of Everliving Golem</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20671>Jeweled Dragon Head Hilt</a><li><a href=http://phobos/eq/item.php?id=20672>Finely Crafted Dragon Head Hilt</a><li><a href=http://phobos/eq/item.php?id=20669>Severely Damaged Dragon Head Hilt</a></ul></td><td><p><b>You say, </b>'Hail'
<p><b>You say, </b>'hilt'
<p><b>You say, </b>'repaired'
<p><b>You say, </b>'unjeweled dragon head hilt'
<p><b>You say, </b>'Severely Damaged Dragon Head Hilt'
<p><b>You say, </b>'golem'
<p><b>You say, </b>'rejesiam'
<p><b>You give Wenden Blackhammer : </b><a href=http://phobos/eq/item.php?id=20668>Unjeweled Dragon Head Hilt</a>, <a href=http://phobos/eq/item.php?id=10037>Diamond</a>, <a href=http://phobos/eq/item.php?id=10036>Black Sapphire</a>, <a href=http://phobos/eq/item.php?id=10053>Jacinth</a>
<br><font color=green><b>Wenden Blackhammer </b>begins to fiddle with the hilt, gently pressing the gems into place. It seems to take forever as you watch in silence. Wenden slowly places the last gem in place and gently bends the settings to hold the gems before he hands it back to you. 'That's a very impressive looking hilt there. The material it is made out of seems strangely familiar,' Wenden says as he turns back to his forge and his other work.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Wenden Blackhammer gives you : </b><a href=http://phobos/eq/item.php?id=20671>Jeweled Dragon Head Hilt</a>
<p><b>You give Wenden Blackhammer : </b><a href=http://phobos/eq/item.php?id=20669>Severely Damaged Dragon Head Hilt</a>, <a href=http://phobos/eq/item.php?id=20666>Rejesiam Ore</a>, <a href=http://phobos/eq/item.php?id=20677>Ball of Everliving Golem</a>
<br><font color=green><b>Wenden Blackhammer </b>works his magic with his forge as you have never seen done quite like this. The bending and shaping to repair the hilt is only something a master of his art could even fathom to try. Once the hilt has been cooled in a near by bucket of ice cold water, he checks it for balance and resonance before handing it to you.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Wenden Blackhammer gives you : </b><a href=http://phobos/eq/item.php?id=20672>Finely Crafted Dragon Head Hilt</a>
<p><b>You give Wenden Blackhammer : </b><a href=http://phobos/eq/item.php?id=20669>Severely Damaged Dragon Head Hilt</a>
<br><b>Wenden Blackhammer says </b>''Where in the world did you drag that up?!' He peers closely at the severely damaged dragon head hilt. 'This metal is the same material that some mages use to make powerful golems and this other metal looks like rejesiam ore. If you can find some of those materials, I can fix this hilt up easily.''
<br><b>Wenden Blackhammer gives you : </b><a href=http://phobos/eq/item.php?id=20669>Severely Damaged Dragon Head Hilt</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>