<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13099>Spiderling Silk</a><li><a href=http://phobos/eq/item.php?id=13927>Cyclops Eye</a><li><a href=http://phobos/eq/item.php?id=10307>Fire Beetle Eye</a><li><a href=http://phobos/eq/item.php?id=13073>Bone Chips</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=73575>Radiant Sodalite of Pure Efficiency</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=86>Dismal Rage</a><li><a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Xelha Nevagon says </b>'A new recruit to our cause.  Just what I have been waiting for!  How would you like to serve the great Xelha Nevagon?  I need an apprentice necromancer to [assist the great Xelha].'
<p><b>You say, </b>'assist the great xelha'
<br><b>Xelha Nevagon says </b>'Fantastic.  Stick with me and you shall ascend in our ranks quickly.  I am in need of some components for new spells.  Will you collect them for me?  I shall need four each of the following - fire beetle eyes. bone chips and spiderling silk.  Fetch these items for me at once. Well..? Did not you hear the great Xelha? Begone!'
<p><b>You give Xelha Nevagon : </b><a href=http://phobos/eq/item.php?id=13099>Spiderling Silk</a> (x4)
<br><b>Xelha Nevagon says </b>'Let's see here. One.. two.. three.. and.. four. Great!! Just enough for my needs. You are serving Xelha well. I give you Xelha's Sparkler. It is not much, but neither are you. You know what I really need is a cyclops eye. That would be worthy of a great reward.'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 4sp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=86>Dismal Rage</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten worse.</font>
<p><b>You give Xelha Nevagon : </b><a href=http://phobos/eq/item.php?id=13927>Cyclops Eye</a>
<br><b>Xelha Nevagon says </b>'A cyclops eye!! You are stronger than I believed. You will rise in the ranks of the Dismal Rage quickly with acts such as this!! I am most appreciative! Here, take this. It was lying around my shelves, just gettingg all dusty. I hope you can use it. And watch yourself in your journeys, the aura of your faith in Innoruuk surrounds you like a shroud. Our enemies will surely see you for what you are.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Xelha Nevagon gives you : </b><a href=http://phobos/eq/item.php?id=73575>Radiant Sodalite of Pure Efficiency</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=86>Dismal Rage</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten worse.</font>
<p><b>You give Xelha Nevagon : </b><a href=http://phobos/eq/item.php?id=10307>Fire Beetle Eye</a> (x4)
<br><b>Xelha Nevagon says </b>'Let's see here. One.. two.. three.. and.. four. Great!! Just enough for my needs. You are serving Xelha well. I give you Xelha's Sparkler. It is not much, but neither are you. You know what I really need is a cyclops eye. That would be worthy of a great reward.'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 1sp 8cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=86>Dismal Rage</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten worse.</font>
<p><b>You give Xelha Nevagon : </b><a href=http://phobos/eq/item.php?id=13073>Bone Chips</a> (x4)
<br><b>Xelha Nevagon says </b>'Let's see here. One.. two.. three.. and.. four. Great!! Just enough for my needs. You are serving Xelha well. I give you Xelha's Sparkler. It is not much, but neither are you. You know what I really need is a cyclops eye. That would be worthy of a great reward.'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 4cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=86>Dismal Rage</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=235>Opal Dark Briar</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten worse.</font>
</td></tr></table>