<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13121>Innoruuk's Kiss of Death</a><li><a href=http://phobos/eq/item.php?id=22298>King Card</a><li><a href=http://phobos/eq/item.php?id=22295>Joker Card</a><li><a href=http://phobos/eq/item.php?id=22299>Knight Card</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=4111>Black Steel Greaves</a><li><a href=http://phobos/eq/item.php?id=13279>A Telescope Lens</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Zenita DRin says </b>'Greetings! I would love to chat with you. but I just remembered something.. I do not waste time with whelps.'
<p><b>You say, </b>'lens'
<br><b>Zenita DRin says </b>'If you want the lens then either you will have to [fight] or play a [card game] of chance.'
<p><b>You say, </b>'card game'
<br><b>Zenita DRin says </b>'You bring me a bottle of Innoruuk's Kiss of Death and you can draw a random card from my deck. If you get a King, you can have the lens.'
<p><b>You say, </b>'fight'
<br><b>Zenita DRin says </b>'This should be a joke! But... DIE!!!'
<p><b>You give Zenita DRin : </b><a href=http://phobos/eq/item.php?id=13121>Innoruuk's Kiss of Death</a>
<br><b>Zenita DRin says </b>'Let see what card you pulled.'
<br><b>Zenita DRin gives you : </b><a href=http://phobos/eq/item.php?id=4111>Black Steel Greaves</a>
<p><b>You give Zenita DRin : </b><a href=http://phobos/eq/item.php?id=22298>King Card</a>
<br><b>Zenita DRin says </b>'As much as I hate to admit it, you won! Take this and be gone before take it back the easy way!'
<br><font color=yellow>You gain experience!!</font>
<br><b>Zenita DRin gives you : </b><a href=http://phobos/eq/item.php?id=13279>A Telescope Lens</a>
<p><b>You give Zenita DRin : </b><a href=http://phobos/eq/item.php?id=22295>Joker Card</a>
<br><b>Zenita DRin says </b>'I see you have drawn the card that best represnts a  such as yourself. You lose!'
<p><b>You give Zenita DRin : </b><a href=http://phobos/eq/item.php?id=22299>Knight Card</a>
<br><b>Zenita DRin says </b>'Bad luck must be one of your strong suits. You should have been a begger because you sure aren't a very good . You lose!'
</td></tr></table>