<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Beno Targnarle says </b>'Step forth. young [Your Name]!  I heard that you have come of age!  The spirit of adventure has entered your body.  That is good.  Go and speak with the others.  They shall help you.  I am afraid I have no time to spend conversing.  There is much I have to [ponder].'
<p><b>You say, </b>'what ponder'
<br><b>Beno Targnarle says </b>'Must you know everyone's business?  Hmm..  Maybe you can be of assistance.  You see. I have been instructed by Furtog to tend to a matter of extreme urgency. which is keeping me from clearing the mines of rats.  Will you assist and [exterminate the rats]?'
<p><b>You say, </b>'i want to exterminate the rats'
<br><b>Beno Targnarle says </b>'Very good!  I shall reward you for every four giant rat pelts returned to me.  And be on the lookout for a [metal rat]!'
<p><b>You say, </b>'what metal rat'
<br><b>Beno Targnarle says </b>'I cannot tell you how many reports I have heard of metal rats in Kaladim.  I first thought it was a vision obtained from having too many Tumpy Tonics. but Furtog himself is said to have seen them.  If you ever catch sight of the little metal beast. give chase!!  Return its metal carcass to me and I shall reward you.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>