<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=2396>Enraged Goblin Beads</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2429>A Note To Taldrik</a><li><a href=http://phobos/eq/item.php?id=1430>Initiate Symbol of Brell Serilis</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=44>Clerics of Underfoot</a><li><a href=http://phobos/eq/faction.php?id=169>Kazon Stormhammer</a><li><a href=http://phobos/eq/faction.php?id=219>Miners Guild 249</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Bronlor Lightblade says </b>'Allo dere [Your Name], how does ye fare today? Are ye a [priest] of the great Brell Serilis? If ye are not I mean nothing against yar but I am on a mission to administer guidance to a holy priest of milord Brell Serilis.'
<p><b>You say, </b>'priest'
<br><b>Bronlor Lightblade says </b>'Well now were talkin [Your Name]. I think if ye have been doing well in your training then ye will be ready to assist me in with the problem we been havin with those dern good fer nothin [green rascals].'
<p><b>You say, </b>'green rascals'
<br><b>Bronlor Lightblade says </b>'Well of course I be talkin bout dose goblins that have tried to storm our front gates fer some time. I reckon dey are up to no good sense I hear dey just be a few from a well trained horde of goblin invaders that are planning an attack me thinks. Will ye [help] us in finding and slaying these goblins?'
<p><b>You say, </b>'help'
<br><b>Bronlor Lightblade says </b>'Dats great to here [Your Name]! To prove to me that you have found and slain these beasts bring four sets of the beads that dey carry around their necks. I dont know much about dem but Id reckon dey have set up camp close by here. The night watch that haulted the first attack by these goblins described the fighting style to be of the highest goblin caliber. I hope this helps, good luck to ye.'
<p><b>You say, </b>'task'
<br><b>Bronlor Lightblade says </b>'Ah ye are ready fer yer task are ya [Your Name]. I must say dat I am quite impressed with the excellent job dat ya did taking care of those strong goblins. Ok well ye came for yer task so here it tis. I need to get this note to me friend Taldrik, however he has told me that he was heading to the Oasis that is finest in norrath for sum relaxin time. Although I would love to go myself but Im afraid I hab many duties to uphold here. Will you [deliver] my note to Taldrik?'
<p><b>You say, </b>'deliver'
<br><b>Bronlor Lightblade says </b>'Fantastic [Your Name]! I knew that ye would be able to help me. Please take this note to Taldrik, whereber he may be and be sure to give him his favorite [drinks] or he may be very grumpy.'
<br><b>Bronlor Lightblade gives you : </b><a href=http://phobos/eq/item.php?id=2429>A Note To Taldrik</a>
<p><b>You say, </b>'drinks'
<br><b>Bronlor Lightblade says </b>'Oh yes of course. Taldriks favorites if I can remembur correctly be Elven wine, Freeport stout, and of course Dwarven ale! Bring these drinks to him with your note and after ye tell him you are sent from muh to continue your training im shure he will warm up to ye fer sure.'
<p><b>You give Bronlor Lightblade : </b><a href=http://phobos/eq/item.php?id=2396>Enraged Goblin Beads</a> x4
<br><b>Bronlor Lightblade says </b>'I knew I was able to trust ye to help me rid the land of these nasty goblins! The Bloodforge Brigade salutes ye [Your Name]. Ye will be well known in our city for being the young one that helped rid our mountains of these goblins. Please take this as a symbol of your devotion to your faith and your God and return to me when ye are ready for yer next [task].'
<br><b>Bronlor Lightblade gives you : </b><a href=http://phobos/eq/item.php?id=1430>Initiate Symbol of Brell Serilis</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=44>Clerics of Underfoot</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=169>Kazon Stormhammer</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=219>Miners Guild 249</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>