<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Byzar Bloodforge says </b>'State your business!!  I have no time for chitchat.  Well..  speak up. toad!!  What?!!..  Have you come here to [return goblin beads]?'
<p><b>You say, </b>'what return goblin beads'
<br><b>Byzar Bloodforge says </b>'The Bloodforge Brigade is the elite force of the Stormguard. They took the place of the Irontoe Brigade. They are led by Byzar Bloodforge.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>