<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13318>Crushbone Belt</a><li><a href=http://phobos/eq/item.php?id=13319>Crushbone Shoulderpads</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2124>Small Patchwork Boots</a><li><a href=http://phobos/eq/item.php?id=2113>Small Tattered Skullcap</a><li><a href=http://phobos/eq/item.php?id=2120>Small Patchwork Sleeves</a><li><a href=http://phobos/eq/item.php?id=10017>Turquoise</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=314>Storm Guard</a><li><a href=http://phobos/eq/faction.php?id=169>Kazon Stormhammer</a><li><a href=http://phobos/eq/faction.php?id=219>Miners Guild 249</a><li><a href=http://phobos/eq/faction.php?id=215>Merchants of Kaladim</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=57>Craknek Warriors</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Canloe Nusback says </b>'Step forward and speak up. young [Your Name]! Kaladim can always use another warrior. Are you [ready to serve Kaladim] or has a yellow streak appeared down your back?'
<p><b>You say, </b>'i am ready to serve kaladim'
<br><b>Canloe Nusback says </b>'Then serve you shall. Let your training begin on the battlefields of Faydwer. Seek out and destroy all [Crushbone orcs]. Return their belts to me.  I shall also reward you for every two orc legionnaire shoulder pads  returned.  A warrior great enough to slay one legionnaire shall surely have no problem with another.  Go. and let the cleansing of Faydwer begin.'
<p><b>You say, </b>'what crushbone orcs'
<br><b>Canloe Nusback says </b>'The army of the Crushbone orcs is deadly indeed. They are great military strategists. It was a legion of them that brought down the great [Trondle Ogrebane]. Speak with Furtog Ogrebane about the Crushbones. He has need of warriors such as you.'
<p><b>You say, </b>'who is crushbone orcs'
<br><b>Canloe Nusback says </b>'The army of the Crushbone orcs is deadly indeed. They are great military strategists. It was a legion of them that brought down the great [Trondle Ogrebane]. Speak with Furtog Ogrebane about the Crushbones. He has need of warriors such as you.'
<p><b>You say, </b>'who is trondle ogrebane'
<br><b>Canloe Nusback says </b>'Trondle Ogrebane is the legendary dwarven warrior who single-handedly exterminated the ogre clan called the [Mudtoes]. He was recently killed in battle. It took an entire legion of Crushbone orcs to bring him down. Furtog is still fuming about that.'
<p><b>You say, </b>'what mudtoes'
<br><b>Canloe Nusback says </b>'The Mudtoes were a small clan of ogres. They lived somewhere in the Butcherblock Mountains. They had an insatiable appetite for dwarves. They were finally destroyed by the hand of Trondle Ogrebane.'
<p><b>You give Canloe Nusback : </b><a href=http://phobos/eq/item.php?id=13318>Crushbone Belt</a>
<br><b>Canloe Nusback says </b>'Good work. warrior! Now continue with your training. Only on the battlefield can one become a great warrior.'
<br><b>Canloe Nusback gives you : </b><a href=http://phobos/eq/item.php?id=2124>Small Patchwork Boots</a>
<br><b>You receive </b> 8sp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=314>Storm Guard</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=169>Kazon Stormhammer</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=219>Miners Guild 249</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=215>Merchants of Kaladim</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=57>Craknek Warriors</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Canloe Nusback : </b><a href=http://phobos/eq/item.php?id=13318>Crushbone Belt</a> (x4)
<br><b>Canloe Nusback says </b>'Good work. warrior! Now continue with your training. Only on the battlefield can one become a great warrior.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Canloe Nusback gives you : </b><a href=http://phobos/eq/item.php?id=2113>Small Tattered Skullcap</a>
<br><b>You receive </b> 12sp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=314>Storm Guard</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=169>Kazon Stormhammer</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=219>Miners Guild 249</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=215>Merchants of Kaladim</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=57>Craknek Warriors</a> has gotten worse.</font>
<p><b>You give Canloe Nusback : </b><a href=http://phobos/eq/item.php?id=13318>Crushbone Belt</a> (x2)
<br><b>Canloe Nusback says </b>'Good work. warrior! Now continue with your training. Only on the battlefield can one become a great warrior.'
<br><b>Canloe Nusback gives you : </b><a href=http://phobos/eq/item.php?id=2120>Small Patchwork Sleeves</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 6sp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=314>Storm Guard</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=169>Kazon Stormhammer</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=219>Miners Guild 249</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=215>Merchants of Kaladim</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=57>Craknek Warriors</a> has gotten worse.</font>
<p><b>You give Canloe Nusback : </b><a href=http://phobos/eq/item.php?id=13318>Crushbone Belt</a> (x3)
<br><b>Canloe Nusback says </b>'Good work. warrior! Now continue with your training. Only on the battlefield can one become a great warrior.'
<br><b>Canloe Nusback gives you : </b><a href=http://phobos/eq/item.php?id=2120>Small Patchwork Sleeves</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 16sp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=314>Storm Guard</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=169>Kazon Stormhammer</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=219>Miners Guild 249</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=215>Merchants of Kaladim</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=57>Craknek Warriors</a> has gotten worse.</font>
<p><b>You give Canloe Nusback : </b><a href=http://phobos/eq/item.php?id=13319>Crushbone Shoulderpads</a> (x2)
<br><b>Canloe Nusback says </b>'Aha!! You have downed a Crushbone legionnaire!! You have shown yourself to be a strong warrior. Take this. This is more becoming of a great warrior such as yourself. Let no creature stand in the way of the Stormguard!'
<br><b>Canloe Nusback gives you : </b><a href=http://phobos/eq/item.php?id=10017>Turquoise</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 4gp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=314>Storm Guard</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=169>Kazon Stormhammer</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=219>Miners Guild 249</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=215>Merchants of Kaladim</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=57>Craknek Warriors</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>