<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18766>Recruitment Letter</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13515>Dirt Stained Tunic*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Furtog Ogrebane says </b>'Hail. mighty [Your Name]! Welcome to Stormguard Hall. I am Captain Furtog Ogrebane. only surviving descendant of the legendary Trondle Ogrebane. slayer of the [Mudtoes]. If you wish to serve the grand city of Kaladim. I urge you to speak with any of the trainers. Good day.'
<p><b>You say, </b>'what mudtoes'
<br><b>Furtog Ogrebane says </b>'The Mudtoes were a small but mighty clan of ogres. My great father [Trondle] destroyed them. I have heard disturbing rumors of one Mudtoe surviving. Would you mind [searching for the Mudtoes] or have you other duties to perform?'
<p><b>You say, </b>'who is trondle'
<br><b>Furtog Ogrebane says </b>'Trondle was my great father and slayer of the Mudtoes. He was killed by those vile Crushbone orcs. If you truly wish to help Kaladim remain safe. speak with trainer Canloe Nusback. Say that you are ready to serve Kaladim.'
<p><b>You say, </b>'what searching for mudtoes'
<br><b>Furtog Ogrebane says </b>'The Mudtoes were a small but mighty clan of ogres. My great father [Trondle] destroyed them. I have heard disturbing rumors of one Mudtoe surviving. Would you mind [searching for the Mudtoes] or have you other duties to perform?'
<p><b>You say, </b>'i am searching for the mudtoes'
<br><b>Furtog Ogrebane says </b>'I have heard persistent rumors of two Mudtoe ogres who survived the slaughter.  Go to the port of Butcherblock.  Those dock hands must have heard of the name [Mudtoe].  Bring me the remaining heads of the Mudtoes!!  I want all the Mudtoes dead!!  Do not return until you have them both!!'
<p><b>You say, </b>'who is mudtoe'
<br><b>Furtog Ogrebane says </b>'The Mudtoes were a small but mighty clan of ogres. My great father [Trondle] destroyed them. I have heard disturbing rumors of one Mudtoe surviving. Would you mind [searching for the Mudtoes] or have you other duties to perform?'
<p><b>You give Furtog Ogrebane : </b><a href=http://phobos/eq/item.php?id=18766>Recruitment Letter</a>
<br><b>Furtog Ogrebane gives you : </b><a href=http://phobos/eq/item.php?id=13515>Dirt Stained Tunic*</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>