<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Hogunk Ventille says </b>'Hail. and welcome to Stormguard Hall. home to all great warriors! Are you also a [warrior of the Stormguard] or do you [follow another guild]?'
<p><b>You say, </b>'i am a warrior of the stormguard'
<br><b>Hogunk Ventille says </b>'As I thought. You do not appear to be one who relies on wits rather than brawn. no offense. I have word that a Stormguard on duty has deserted his post at one of the guardposts in the Butcherblocks. I want you to go and seek him out. He is Guard Bundin. Return his Stormguard axe to me. along with his head. There shall be no cowards in the Stormguard!!'
<p><b>You say, </b>'i follow another guild'
<br><b>Hogunk Ventille says </b>'Then go to your guild. This is the hall of the dwarven warriors - not a place for common folk to lounge around.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>