<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18906>A Small Wood Carving</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=23359>Targ Shield</a></ul></td><td><p><b>You give Kalameky Darkfoam : </b><a href=http://phobos/eq/item.php?id=18906>A Small Wood Carving</a>
<br><b>Kalameky Darkfoam says </b>'The slaves...thank you! Here, this will help defend you against those vile orcs.'
<br><b>Kalameky Darkfoam gives you : </b><a href=http://phobos/eq/item.php?id=23359>Targ Shield</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>