<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18161>A Bardic Letter (Kelethin)</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Kilam Oresinger says </b>'Hail. [Your Name] - Are you [interested] in helping the League of Antonican Bards by delivering some [mail]?'
<p><b>You say, </b>'what mail'
<br><b>Kilam Oresinger says </b>'The League of Antonican Bards has a courier system made up of travelers and adventurers.  We pay good gold to anyone who will take messages from bards such as myself to one of our more central offices.  Are you [interested]?'
<p><b>You say, </b>'i am interested'
<br><b>Kilam Oresinger says </b>'I have messages that need to go to - well. right now I have one that needs to go to Kelethin.  Will you [deliver] mail to [Kelethin] for me?'
<p><b>You say, </b>'I will deliver to Kelethin'
<br><b>Kilam Oresinger says </b>'Take this letter to Jakum Webdancer in Kelethin.  You can find him at the bard guild hall.  I am sure he will compensate you for your troubles.'
<br><b>Kilam Oresinger gives you : </b><a href=http://phobos/eq/item.php?id=18161>A Bardic Letter (Kelethin)</a>
</td></tr></table>