<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18700>Tome of Order and Discord</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18700>Tome of Order and Discord</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Priest of Discord says </b>'Greetings. [Your Name] .  Are you a child of Order?  If you have come seeking the path of Discord. I require only that you give me your [Tome of Order and Discord] and I shall show you the way.  Only then will you be freed from Order's confining restraints.'
<p><b>You say, </b>'tome'
<br><b>Priest of Discord says </b>'The Tome of Order and Discord was penned by the seventh member of the Tribunal and has become the key to a life of Discord. in spite of the author's pitiful warnings.  Do you not have one. child of Order?  Would you like to [read] it?'
<p><b>You say, </b>'read'
<br><b>Priest of Discord says </b>'Very well.  Here you go.  Simply return it to me to be released from the chains of Order. Your PvP has been disabled.'
<br><b>Priest of Discord gives you : </b><a href=http://phobos/eq/item.php?id=18700>Tome of Order and Discord</a>
<p><b>You give Priest of Discord : </b><a href=http://phobos/eq/item.php?id=18700>Tome of Order and Discord</a>
<br><b>Priest of Discord says </b>'I see you wish to join us in Discord! Welcome! By turning your back on the protection of Order you are now open to many more opportunities for glory and power. Remember that you can now be harmed by those who have also heard the call of Discord.'
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>