<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13340>Kiola Nut</a><li><a href=http://phobos/eq/item.php?id=13006>Water Flask</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12114>Tumpy Tonic</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Tumpy Irontoe says </b>'Welcome to Irontoe's! The finest watering hole this side of Oggok! If you're looking for anything special and it ain't behind the bar, just ask. Maybe I can make it.'
<p><b>You say, </b>'tumpy tonic'
<br><b>Tumpy Irontoe says </b>'So you want a Tumpy Tonic? I can make you one. All I need is a flask of water and a kiola nut. The kiola nut can be bought in the Ocean of Tears island chain.'
<p><b>You give Tumpy Irontoe : </b><a href=http://phobos/eq/item.php?id=13006>Water Flask</a>, <a href=http://phobos/eq/item.php?id=13340>Kiola Nut</a>
<br><b>Tumpy Irontoe says </b>'Here you go. One Tumpy Tonic. Don't drink that too fast now.'
<br><b>Tumpy Irontoe gives you : </b><a href=http://phobos/eq/item.php?id=12114>Tumpy Tonic</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>