<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13849>Scarab Carapace</a><li><a href=http://phobos/eq/item.php?id=13133>Pristine Giant Scarab Carapace</a><li><a href=http://phobos/eq/item.php?id=13132>Cracked Giant Scarab Carapace</a><li><a href=http://phobos/eq/item.php?id=13848>Scarab Legs</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2175>Small Scarab Helm</a><li><a href=http://phobos/eq/item.php?id=2176>Small Scarab Breastplate</a><li><a href=http://phobos/eq/item.php?id=2177>Small Scarab Boots</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Vacto Molunel says </b>'Well met. [Your Name]!  I am Vacto Molunel.  If you are seeking to outfit yourself with the finest weapons in all of Kaladim. I am the one to see.  I also posses a [rare talent] you might find useful.'
<p><b>You say, </b>'what rare talent'
<br><b>Vacto Molunel says </b>'Piqued your interest. did I?  Well. you see. I am one of the few dwarves who possess the knowledge and talent to craft a unique type of armor entirely out of scarab carapaces.  While my specialty is making [scarab helms]. I have also been convinced to make [scarab breastplates] and [scarab boots] from time to time.  All of the pieces I craft are to dwarven proportions. but I have had some gnomish and halfling customers as well.  They come from all over for my armor.'
<p><b>You say, </b>'what scarab helms'
<br><b>Vacto Molunel says </b>'Interested in a scarab helm. are you?  Well. because my talent is so unique and my time is so valuable. I am afraid I could only make you a helm if you were to provide me with the two scarab carapaces necessary to accommodate a head such as yours.  I will also need a payment of 5 gold pieces.  The Butcherblocks are crawling with worker scarabs that have just the right size carapaces for our needs.'
<p><b>You say, </b>'what scarab breastplates'
<br><b>Vacto Molunel says </b>'Ah..  A  scarab breastplate.. hmm.  Well. if you want to convince me to go though the trouble of crafting one of those. not only will you have to pay my fee of 23 gold pieces. you must provide me with a pristine giant scarab carapace.  I refuse to make a breastplate with cracked carapaces.'
<p><b>You say, </b>'what boots'
<br><b>Vacto Molunel says </b>'Ah..  Scarab Boots.. hmm.  Well. if you want to convince me to go though the trouble of crafting a pair of those. not only will you have to pay my fee of 17 gold pieces. you must provide me with a cracked giant scarab shell and 2 scarab legs.'
<p><b>You give Vacto Molunel : </b><a href=http://phobos/eq/item.php?id=13849>Scarab Carapace</a> x2
<br><b>Vacto Molunel gives you : </b><a href=http://phobos/eq/item.php?id=2175>Small Scarab Helm</a>
<br><b>Vacto Molunel says </b>'Here is your Scarab Helm!'
<p><b>You give Vacto Molunel : </b><a href=http://phobos/eq/item.php?id=13133>Pristine Giant Scarab Carapace</a>
<br><b>Vacto Molunel gives you : </b><a href=http://phobos/eq/item.php?id=2176>Small Scarab Breastplate</a>
<br><b>Vacto Molunel says </b>'Here is your Scarab breastplate!'
<p><b>You give Vacto Molunel : </b><a href=http://phobos/eq/item.php?id=13132>Cracked Giant Scarab Carapace</a>, <a href=http://phobos/eq/item.php?id=13848>Scarab Legs</a> x2
<br><b>Vacto Molunel gives you : </b><a href=http://phobos/eq/item.php?id=2177>Small Scarab Boots</a>
<br><b>Vacto Molunel says </b>'Here is your Scarab boots!'
</td></tr></table>