<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When #air event spawns </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223087>An_Air_Phoenix_Noble</a></b> spawns (1364,67,494.8).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223087>An_Air_Phoenix_Noble</a></b> spawns (1347,67,494.8).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223087>An_Air_Phoenix_Noble</a></b> spawns (1364,62,494.8).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223087>An_Air_Phoenix_Noble</a></b> spawns (1347,62,494.8).</font>
</td></tr></table>