<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When #earth event spawns </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223106>a_pile_of_living_rubble</a></b> spawns (1644.5,70.3,493.7).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223106>a_pile_of_living_rubble</a></b> spawns (1654.5,70.3,493.7).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223106>a_pile_of_living_rubble</a></b> spawns (1634.5,70.3,493.7).</font>
</td></tr></table>