<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When #fire event spawns </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223088>#a_flame_mephit</a></b> spawns (573,68,504).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223088>#a_flame_mephit</a></b> spawns (563,68,504).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223088>#a_flame_mephit</a></b> spawns (583,68,504).</font>
</td></tr></table>