<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When #main trigger spawns </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223169>#earth_trigger</a></b> spawns (1632.4,13.5,492.3).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223178>#earth_counter</a></b> spawns (1632.4,13.5,492.3).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223170>#air_trigger</a></b> spawns (1350,10.1,492.6).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223179>#air_counter</a></b> spawns (1350,10.1,492.6).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223171>#undead_trigger</a></b> spawns (1107,18,492.2).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223180>#undead_counter</a></b> spawns (1107,18,492.2).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223172>#water_trigger</a></b> spawns (857,11.5,492.5).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223181>#water_counter</a></b> spawns (857,11.5,492.5).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223173>#fire_trigger</a></b> spawns (574.2,13.2,492.3).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223182>#fire_counter</a></b> spawns (574.2,13.2,492.3).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223211>#start_trial</a></b> spawns (1737,-140,547).</font>
</td></tr></table>