<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When #undead event spawns </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223121>an_undead_guardian</a></b> spawns (1109.7,65.2,494.8).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223121>an_undead_guardian</a></b> spawns (1119.7,65.2,494.8).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223122>an_undead_guardian</a></b> spawns (1099.7,65.2,494.8).</font>
</td></tr></table>