<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When #water event spawns </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223104>Anar_of_Water</a></b> spawns (867,68,495).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223192>a_regrua_defender</a></b> spawns (877,68,495).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223192>a_regrua_defender</a></b> spawns (857,68,495).</font>
</td></tr></table>