<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When a pile of living rubble is killed </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223147>a_rock_shaped_assassin</a></b> spawns.</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223147>a_rock_shaped_assassin</a></b> spawns.</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223147>a_rock_shaped_assassin</a></b> spawns.</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223147>a_rock_shaped_assassin</a></b> spawns.</font>
</td></tr></table>