<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When phase3 trigger spawns </b>
<br><font color=red><b>phase3 trigger shouts </b>'Phase 3 has started. You have 75 minutes.'</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223209>#firewater_door</a></b> spawns (709,458,495).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223208>#undead2_door</a></b> spawns (1101,458,495).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223210>#earthair_door</a></b> spawns (1502,458,495).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223010>A_Needletusk_Warboar</a></b> spawns (1010,1280,359.38).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223011>Deathbringer_Rianit</a></b> spawns (1030,1280,359.38).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223012>Sinrunal_Gorgedreal</a></b> spawns (1250,1260,359.38).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223013>Herlsoakian</a></b> spawns (1270,1260,359.38).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223014>Xerskel_Gerodnsal</a></b> spawns (1210,1280,359.38).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223015>Dersool_Fal`Giersnaol</a></b> spawns (1190,1280,359.38).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223016>Xeroan_Xi`Geruonask</a></b> spawns (970,1260,359.38).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223017>Kraksmaal_Fir`Dethsalsin</a></b> spawns (950,1260,359.38).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223018>Dreamwarp</a></b> spawns (1070,1300,359.38).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223019>Champion_of_Torment</a></b> spawns (1090,1300,359.38).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223020>Dark_Knight_of_Terris</a></b> spawns (1130,1300,359.38).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223021>Undead_Squad_Leader</a></b> spawns (1150,1300,359.38).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223022>A_Deadly_Warboar</a></b> spawns (1330,1230,359.38).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223023>Deathbringer_Skullsmash</a></b> spawns (1310,1230,359.38).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223155>A_Ferocious_Warboar</a></b> spawns (1135,1250,359.5).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223156>Deathbringer_Blackheart</a></b> spawns (1085,1250,359.5).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223006>A_Dark_Guardian_of_the_Warlord</a></b> spawns (1035,1150,358.5).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223006>A_Dark_Guardian_of_the_Warlord</a></b> spawns (1085,1150,357.6).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223005>A_Pig_of_War</a></b> spawns (1135,1150,358.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223005>A_Pig_of_War</a></b> spawns (1185,1150,359.2).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223005>A_Pig_of_War</a></b> spawns (1035,1200,358.1).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223006>A_Dark_Guardian_of_the_Warlord</a></b> spawns (1085,1200,357.6).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223005>A_Pig_of_War</a></b> spawns (1135,1200,357.6).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223005>A_Pig_of_War</a></b> spawns (1185,1200,358.7).</font>
</td></tr></table>