<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When phase4 trigger spawns </b>
<br><font color=red><b>phase4 trigger shouts </b>'Phase 4 has started. You have 90 minutes.'</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223075>Terris_Thule</a></b> spawns (307,-310,365).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223076>Saryrn</a></b> spawns (-316,-320,358).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223077>Tallon_Zek</a></b> spawns (-84,405,358).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223078>Vallon_Zek</a></b> spawns (75,405,358).</font>
</td></tr></table>