<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When phase2 trigger spawns </b>
<br><font color=red><b>phase2 trigger shouts </b>'Phase 2 not yet implemented. Skipping to phase 3...'</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223154>phase3_trigger</a></b> spawns (1737,-140,547).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223160>#earth_door</a></b> spawns (1645,80,495).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223203>#earth_retdoor</a></b> spawns (1645,98,495).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223161>#air_door</a></b> spawns (1355,80,495).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223204>#air_retdoor</a></b> spawns (1355,98,495).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223162>#undead_door</a></b> spawns (1109,80,495).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223205>#undead_retdoor</a></b> spawns (1109,98,495).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223202>#water_door</a></b> spawns (868,80,495).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223207>#water_retdoor</a></b> spawns (868,98,495).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223201>#fire_door</a></b> spawns (574,80,495).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=223206>#fire_retdoor</a></b> spawns (574,98,495).</font>
<br><b>phase2 trigger disappears.</b>
</td></tr></table>