<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When #a skeletal foreman spawns </b>
<br><b>#a skeletal foreman says </b>'Dig! Dig faster, you fools! Our masters say this ghost is all that stands in the way of the great one's return. Uncover his hiding place so that the forces of the Burning Dead might destroy him and recover its legacy!'
<hr><b>When #a skeletal foreman is killed </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=36091>#Sir_Ariam_Arcanum</a></b> spawns (-339.8,-43.5,-10.9).</font>
</td></tr></table>