<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=31492>Ghostly Bridle</a><li><a href=http://phobos/eq/item.php?id=18474>Scroll of the Burning Dead</a><li><a href=http://phobos/eq/item.php?id=31493>Arrialla's Expended Token</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>#Sir Ariam Arcanum says </b>'My thanks for destroying these minions of Befallen's masters.This accursed place rends my soul trying to twist me to its purposes. My time here is short, so i must get this [task] done quikly.'
<p><b>You say, </b>'task'
<br><b>#Sir Ariam Arcanum says </b>'I have this parchment that must be delivered to either the Knights of Truth in Freeport or to the Queen of Neriak. The contents of the note concern them both and I am desperate to have this matter addressed so ask that you take it to which ever of the cities will accept your presence. Will you take the note to the [Knights of Truth] or to [The Dead]?'
<p><b>You say, </b>'truth'
<br><b>#Sir Ariam Arcanum says </b>'It must be delivered to Sir Artanis in the city of Freeport. It details a terrible plan of the masters of this place to restore life to a foul necromancer named Marnek. The Burning Dead must not be allowed to achieve this goal. So that you may ride swiftly with news of this nefarious scheme, take this as well, the bridle to the noble steed that was entombed alive with me here. He has strength enough for one final ride.'
<br><b>#Sir Ariam Arcanum gives you : </b><a href=http://phobos/eq/item.php?id=31492>Ghostly Bridle</a>
<br><b>#Sir Ariam Arcanum gives you : </b><a href=http://phobos/eq/item.php?id=18474>Scroll of the Burning Dead</a>
<br><b>#Sir Ariam Arcanum disappears.</b>
<p><b>You say, </b>'dead'
<br><b>#Sir Ariam Arcanum says </b>'Then take this parchment to the Queens assistant, the necromancer Xon, enemy of my enemy. I have no love for her, but Queen Thex's interests too are at risk. This details a terrible plan of the masters of this place to restore life to a foul necromancer named Marnek. The Burning Dead must not be allowed to achieve this goal. So that you may ride swiftly with news of this nefarious scheme, take this as well, the bridle to the noble steed that was entombed alive with me here.'
<br><b>#Sir Ariam Arcanum gives you : </b><a href=http://phobos/eq/item.php?id=31492>Ghostly Bridle</a>
<br><b>#Sir Ariam Arcanum gives you : </b><a href=http://phobos/eq/item.php?id=18474>Scroll of the Burning Dead</a>
<br><b>#Sir Ariam Arcanum disappears.</b>
<p><b>You say, </b>'who or what'
<br><b>#Sir Ariam Arcanum says </b>'I am Sir Ariam Arcanum, a paladin of Tunare. There is no time for my own story, which is of little account. But if you wish to know more of me, and wish also to do me a personal favor then you could seek out my family in Felwithe, provided you are welcome there. Will you travel to Felwithe?'
<p><b>You say, </b>'travel to felwithe'
<br><b>#Sir Ariam Arcanum says </b>'Then deliver this to my family. I have my sisters token to thank for my survival in this form. Something in the magic of this persisted even as I truly wasted away buried alive near here.'
<br><b>#Sir Ariam Arcanum gives you : </b><a href=http://phobos/eq/item.php?id=31493>Arrialla's Expended Token</a>
</td></tr></table>