<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1671>Icon of the High Scale</a></ul></td><td><p><b>You give #High Scale Kirn  : </b><a href=http://phobos/eq/item.php?id=1671>Icon of the High Scale</a>
<br><font color=green><b>#High Scale Kirn  </b>looks down at the icon in his hands for a long moment before speaking. 'Why did you bring me this? Are you here to accuse me of the queen's death?' High Scale Kirn chuckles venomously and continues, 'I am High Scale and beyond your petty laws. However, I wish the truth to be known. On my hand is a ring. If you can take it from me, show it to the queen and she will remember. However, I will not give up the ring easily. Defend yourself!</font>
<br><font color=yellow>You gain experience!!</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=39083>#High_Scale_Kirn</a></b> spawns.</font>
<br><b>#High Scale Kirn  disappears.</b>
</td></tr></table>