<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=14373>Cell Key</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=342>True Spirit</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Caradon says </b>'Please help me get out of here! My companion, Kyrenna, and I are trapped in this hellish place!'
<p><b>You say, </b>'Who is Kyrenna'
<br><b>Caradon says </b>'I was with Kyrenna when she attempted to revive the corpse of Glohnor the Valiant. Like fools, we rushed into a trap. Now we sit here and await our deaths.'
<p><b>You say, </b>'Where is Kyrenna'
<br><b>Caradon says </b>'She is close by. For a price, I shall tell you. Bring me the key to my freedom and I will betray her, who sentenced me to this fate.'
<p><b>You give Caradon : </b><a href=http://phobos/eq/item.php?id=14373>Cell Key</a>
<br><b>Caradon says </b>'Kyrenna! We are free!'
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=39155>Kyrenna</a></b> spawns (426.6,-195.8,-213.9).</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=342>True Spirit</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>