<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10604>Jeb's Seal</a><li><a href=http://phobos/eq/item.php?id=10638>A Sack For Polzin</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10604>Jeb's Seal</a><li><a href=http://phobos/eq/item.php?id=17861>An Enchanters Sack</a><li><a href=http://phobos/eq/item.php?id=10613>4th Piece of Staff</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=342>True Spirit</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Polzin Mrid says </b>'Yes, young one?'
<p><b>You say, </b>'i am ready for the test of the phantasm'
<br><b>Polzin Mrid says </b>'It will be simple, go collect these items and return them to me. Head of a serpent, essence of a ghost, essence of a vampire, and sands of the mystics. Do so and you will receive the last of the pieces. Be sure to combine them in a sack first. Just ask and I will provide you with one.'
<p><b>You say, </b>'head of a serpent'
<br><b>Polzin Mrid says </b>'Serpent is probably not an accurate term for what you must return to me. It is actaully the reminants of a spirit. The spirit is one which was erradicated long long ago by the Iksar. I believe they were called the Shissar. You may need to travel to the Iksar city to learn more about these creatures.'
<p><b>You say, </b>'essence of a ghost'
<br><b>Polzin Mrid says </b>'You don't have to look far to find roaming spirits. One in particular though has more meaning then the other sorry souls trapped here. You see, Kindle was a dear friend of mine. I came in search of him when he stopped writing. Well...look at me now. I fear that I have succumbed to the same fate as poor Kindle.'
<p><b>You say, </b>'essence of a vampire'
<br><b>Polzin Mrid says </b>'The essence of a vampire is just that. Only the most powerful of these creatures will possess what you need.'
<p><b>You say, </b>'sands of the mystic'
<br><b>Polzin Mrid says </b>'They are sands that were imbued with the magical might of the mystics. Mystics use a ritual involving their own blood to create a powerful bond with the sand. One will need to search the shores.'
<p><b>You give Polzin Mrid : </b><a href=http://phobos/eq/item.php?id=10604>Jeb's Seal</a>
<br><b>Polzin Mrid says </b>'Jeb has spoken with you already, excellent. Tell me are you ready for the test of the phantasm?'
<br><b>Polzin Mrid gives you : </b><a href=http://phobos/eq/item.php?id=10604>Jeb's Seal</a>
<br><b>Polzin Mrid gives you : </b><a href=http://phobos/eq/item.php?id=17861>An Enchanters Sack</a>
<p><b>You give Polzin Mrid : </b><a href=http://phobos/eq/item.php?id=10638>A Sack For Polzin</a>
<br><b>Polzin Mrid says </b>'You have done well, take this last piece and return them to Jeb. He will be able to complete the final crafting.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=342>True Spirit</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Polzin Mrid gives you : </b><a href=http://phobos/eq/item.php?id=10613>4th Piece of Staff</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>