<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When #Qezzin Adan spawns </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=200042>Elite_Knight_of_Decay</a></b> spawns (,10,).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=200042>Elite_Knight_of_Decay</a></b> spawns (5,10,).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=200042>Elite_Knight_of_Decay</a></b> spawns (-10,10,).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=200042>Elite_Knight_of_Decay</a></b> spawns (,-10,).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=200043>Elite_Priest_of_Decay</a></b> spawns.</font>
<hr><b>When #Qezzin Adan is killed </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=200053>#Meedo_Adan</a></b> spawns (-280,0,-244).</font>
</td></tr></table>