<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When #Xhut Adan spawns </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=200042>Elite_Knight_of_Decay</a></b> spawns (,10,).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=200042>Elite_Knight_of_Decay</a></b> spawns (10,10,).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=200042>Elite_Knight_of_Decay</a></b> spawns (,-10,).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=200042>Elite_Knight_of_Decay</a></b> spawns (-10,-10,).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=200043>Elite_Priest_of_Decay</a></b> spawns.</font>
<hr><b>When #Xhut Adan is killed </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=200045>#Feig_Adan</a></b> spawns (0,-200,-274).</font>
</td></tr></table>