<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When Bishop Toluwon spawns </b>
<hr><b>When Bishop Toluwon is killed </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=200034>Vindor_Mawnil</a></b> spawns (325,325,-71.5).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=200033>Raex_Pwodill</a></b> spawns (325,290,-71.5).</font>
</td></tr></table>