<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18770>Recruitment Summons</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13520>Torn and Ripped Tunic*</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=303>Snowfang Gnolls</a><li><a href=http://phobos/eq/faction.php?id=373>Harbingers Clan</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Baxok Curhunter says </b>'Hail, [Your Name]. I invite you to serve the mighty state of Ak'Anon by becoming a Gemchopper. We gnomes are not known for our warrior skills, but those few who endure and survive to become elite amongst our warriors soon find that the technology of the gnomes has found its way into our halls. You must be a [new recruit] or [an outsider], perhaps?'
<p><b>You say, </b>'i am a new recruit'
<br><b>Baxok Curhunter says </b>'Well, good to make your acquaintance, [Your Name]. Maybe someday you shall be a great Watchman. Until then, I have a task for you. Will you [serve the Crown] or has a yellow streak appeared upon your back?'
<p><b>You say, </b>'i will serve the crown'
<br><b>Baxok Curhunter says </b>'You are too inexperienced. Leave that business to someone more worldly.'
<p><b>You say, </b>'i am an outsider'
<br><b>Baxok Curhunter says </b>'I should have guessed as much. You look the part.'
<p><b>You give Baxok Curhunter : </b><a href=http://phobos/eq/item.php?id=18770>Recruitment Summons</a>
<br><b>Baxok Curhunter gives you : </b><a href=http://phobos/eq/item.php?id=13520>Torn and Ripped Tunic*</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=303>Snowfang Gnolls</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=373>Harbingers Clan</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>