<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10604>Jeb's Seal</a><li><a href=http://phobos/eq/item.php?id=10636>A Sack For Mizzle</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10604>Jeb's Seal</a><li><a href=http://phobos/eq/item.php?id=17861>An Enchanters Sack</a><li><a href=http://phobos/eq/item.php?id=10611>2nd Piece of Staff</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=342>True Spirit</a></ul></td><td><p><b>You say, </b>'are you mizzle'
<br><b>Clockwork VIIX says </b>'Oh hello! I'm Mizzle, that I am. I bet you want to be given true clarity, don't you?'
<p><b>You say, </b>'i am ready to collect'
<br><b>Clockwork VIIX says </b>'Then bring me a spoon, the one key, the lost scroll, and the book Charm and Sacrifice. I will then reward you with what you seek.'
<p><b>You say, </b>'spoon'
<br><b>Clockwork VIIX says </b>'Its a giant sized tool I will use to stir my magical pot. The spoon will help finish the ritual of crafting.'
<p><b>You say, </b>'one key'
<br><b>Clockwork VIIX says </b>'It is a key I lost long ago when I was travelling with a companion. We were traveling in the new lands flying over some large crevices when the key dropped out of my pocket.'
<p><b>You say, </b>'lost scroll'
<br><b>Clockwork VIIX says </b>'The lost scroll contains the magical incantation I need to help you out. It was penned ages ago by the Elves. It was lost along with its protector during one of the raids on the Outpost in Firiona. I fear it may be lost for good.'
<p><b>You say, </b>'book of charm and sacrifice'
<br><b>Clockwork VIIX says </b>'Oh, that is a book of good reading. If you want to take the time to read it. I haven't had much free time to read it, but now that you are getting supplies for me, I can take a break.'
<p><b>You give Clockwork VIIX : </b><a href=http://phobos/eq/item.php?id=10604>Jeb's Seal</a>
<br><b>Clockwork VIIX says </b>'It is time then, are you ready to get the required components?'
<br><b>Clockwork VIIX gives you : </b><a href=http://phobos/eq/item.php?id=10604>Jeb's Seal</a>
<br><b>Clockwork VIIX gives you : </b><a href=http://phobos/eq/item.php?id=17861>An Enchanters Sack</a>
<p><b>You give Clockwork VIIX : </b><a href=http://phobos/eq/item.php?id=10636>A Sack For Mizzle</a>
<br><b>Clockwork VIIX says </b>'Oh excellent, you have done what is required. Here take this part, and seek the third master, you are well on your way.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=342>True Spirit</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Clockwork VIIX gives you : </b><a href=http://phobos/eq/item.php?id=10611>2nd Piece of Staff</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>