<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18771>Stained Letter</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13524>Dark Gold Felt Robe*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Eonis Mournunder says </b>'Hail.'
<p><b>You give Eonis Mournunder : </b><a href=http://phobos/eq/item.php?id=18771>Stained Letter</a>
<br><b>Eonis Mournunder says </b>'Thanks.'
<br><b>Eonis Mournunder gives you : </b><a href=http://phobos/eq/item.php?id=13524>Dark Gold Felt Robe*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>