<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10967>Clockwork Rat Leg Section</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=176>King Ak'Anon</a><li><a href=http://phobos/eq/faction.php?id=91>Eldritch Collective</a><li><a href=http://phobos/eq/faction.php?id=115>Gem Choppers</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=71>Dark Reflection</a><li><a href=http://phobos/eq/faction.php?id=209>Meldrath</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Exterminator VII says </b>'Greetings, citizen. Welcome to Akanon. *whirr whirr* Mission *Terminate Vermin* initiated. Bring four clockwork rat leg sections from defective cleaners for reward. All defective models must be eradicated *bzzzt whirr*.'
<p><b>You give Exterminator VII : </b><a href=http://phobos/eq/item.php?id=10967>Clockwork Rat Leg Section</a> x4
<br><b>Exterminator VII says </b>'Four Clockwork Rat Leg Sections recieved *bzzzt* processing reward. Reward mode initiated. Coins given. Mission *Terminate Vermin* reset one second *bzzt whirr*.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=176>King Ak'Anon</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=91>Eldritch Collective</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=115>Gem Choppers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=71>Dark Reflection</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=209>Meldrath</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 1gp 1sp 1cp
</td></tr></table>