<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Jarah Reskan says </b>'Greetings. child. Welcome to Gemchopper Hall. I trust that you are a [warrior]. or perhaps you are lost..?'
<p><b>You say, </b>'I am a warrior'
<br><b>Jarah Reskan says </b>'That is good news! We gnomes are not known for our love of battle so it is always good to bring new blood into our ranks. We shall prove our worth as warriors to all other races. For now. there is much to do in Ak'Anon. There are [rogue clockworks] and the [cargo clockwork].'
<p><b>You say, </b>'what rogue clockworks?'
<br><b>Jarah Reskan says </b>'The clockworks are the responsibility of Manik Compolten. Speak with him - I am sure he is here somewhere.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>