<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18773>Registration Letter</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13522>Dirty Gold Felt Robe*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Juline Urncaller says </b>'Hail.'
<p><b>You give Juline Urncaller : </b><a href=http://phobos/eq/item.php?id=18773>Registration Letter</a>
<br><b>Juline Urncaller says </b>'Thanks.'
<br><b>Juline Urncaller gives you : </b><a href=http://phobos/eq/item.php?id=13522>Dirty Gold Felt Robe*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>