<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18705>Old Folded Letter</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13518>Tin Patched Tunic*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Kaxon Frennor says </b>'Hail.'
<p><b>You give Kaxon Frennor : </b><a href=http://phobos/eq/item.php?id=18705>Old Folded Letter</a>
<br><b>Kaxon Frennor says </b>'Thanks.'
<br><b>Kaxon Frennor gives you : </b><a href=http://phobos/eq/item.php?id=13518>Tin Patched Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>