<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13945>Flask of Nitrates</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12140>Regurgitonic</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=115>Gem Choppers</a><li><a href=http://phobos/eq/faction.php?id=210>Merchants of Ak'Anon</a><li><a href=http://phobos/eq/faction.php?id=176>King Ak'Anon</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=71>Dark Reflection</a><li><a href=http://phobos/eq/faction.php?id=37>Citizens of Seru</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Kimble Nogflop says </b>'Greetings!  I am the keeper of this zoo.  I advise you to stay on the upper tiers to observe the animals.'
<p><b>You say, </b>'regurgitonic'
<br><b>Kimble Nogflop says </b>'I formulate the Regurgitonic myself. My animals kept eating the occasional spectator here and there. Femurs and ribs kept getting stuck inside, not to mention a few platinum pieces. Sometimes my batch would come out wrong and the animals would go berserk!! I hope I got the formula right this time.'
<p><b>You give Kimble Nogflop : </b><a href=http://phobos/eq/item.php?id=13945>Flask of Nitrates</a>
<br><b>Kimble Nogflop says </b>'The flask of nitrates I sent for!! As was the deal, here is my [Regurgitonic]. Give it to whoever may need it and they will surely cough up whatever may be inside them with no harm to them whatsoever.'
<br><b>Kimble Nogflop gives you : </b><a href=http://phobos/eq/item.php?id=12140>Regurgitonic</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=115>Gem Choppers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=210>Merchants of Ak'Anon</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=176>King Ak'Anon</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=71>Dark Reflection</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=37>Citizens of Seru</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>