<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13077>Minotaur Horn</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Larkon Theardor says </b>'Greetings! Welcome to the Library of Mechanimagica. You must be a [current member of the Library] or has my [mind begun to slip]?'
<p><b>You say, </b>'Your mind has begun to slip'
<br><b>Larkon Theardor says </b>''What!!? That was but a joke. I try to make you feel comfortable with a little levity and you proclaim my mind has gone the way of Meldrath's. Well.. enough frivolity. You will do your part to help in the menial tasks of the Collective. Do you want the [clean tasks] or the [dirty tasks]?'
<p><b>You say, </b>'I want clean tasks'
<br><b>Larkon Theardor says </b>'Clean.. Dirty.. It matters not. You have upset me with your rude remarks. You will go to the Steamfont Mountains. There you will find Fodin and tell him I have sent you. He will have a nice tidy task for you. A bath!! Be on your way!'
<p><b>You say, </b>'I want dirty tasks'
<br><b>Larkon Theardor says </b>'Clean.. Dirty.. It matters not. You have upset me with your rude remarks. You will go to the Steamfont Mountains. There you will find Fodin and tell him I have sent you. He will have a nice tidy task for you. A bath!! Be on your way!'
<p><b>You say, </b>'I am a current member of the Library'
<br><b>Larkon Theardor says </b>'Good. The last thing a member of the Eldritch Collective needs is to lose his mind. Look what happened to Meldrath. Enough chitchat. I am Larkon and it is not my job to teach you. It is my job to direct you to service. We require items and such to complete our studies. We need someone of moderate skill to [gather minotaur horns] and [collect basilisk tongues].'
<p><b>You say, </b>'I will gather minotaur horns'
<br><b>Larkon Theardor says </b>'We magicians require the horns of minotaurs.  We crush them down and use the powder in many of our tests. Go and fetch two minotaur horns.  Do not return empty-handed. I await your return as does your reward.'
<p><b>You say, </b>'I will collect basilisk tongues'
<br><b>Larkon Theardor says </b>'Very good of you.  Go beyond the land of the gnomes and seek out basilisks.  Return four of their tongues to me and I shall share the knowledge of the magicians of the Eldritch Collective.'
<p><b>You give Larkon Theardor : </b><a href=http://phobos/eq/item.php?id=13077>Minotaur Horn</a>
<br><b>Larkon Theardor says </b>'Fine work. You have earned the respect of the Library. Here is a small token of our appreciation. We shall have this ground down as soon as we find someone to go to Kaladim.'
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>