<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=9470>Bundle of Poisons</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=24096>Dip Resist Sketch</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Lobal Postugger says </b>'Hello. I am the guild master.'
<p><b>You say, </b>'dark assassin'
<br><b>Lobal Postugger says </b>'You have heard of him? I had a nice conversation with him. Sharing some secrets of gnomish spirits if yah know what i mean! In return he gave me a sketch that looks quite interesting. Of course I am stuck in this place waiting youngsters to teach when I would rather be out with you making poisons. Perhaps you are willing to make a trade with me for the sketch?'
<p><b>You say, </b>'make a trade'
<br><b>Lobal Postugger says </b>'Fantastic! If you combine Rage of Incapacitation, Wasted Flesh and Dreams of Drusella within a coffin bottle you can make me a nice bundle of poisons to play with. Then I will have no need for the sketch.'
<p><b>You give Lobal Postugger : </b><a href=http://phobos/eq/item.php?id=9470>Bundle of Poisons</a>
<br><font color=green><b>Lobal Postugger </b>laughs. 'Here, take this then!'</font>
<br><b>Lobal Postugger gives you : </b><a href=http://phobos/eq/item.php?id=24096>Dip Resist Sketch</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>