<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Lyra Lyrestringer says </b>'Hail [Your Name].  Are you [interested] in helping the League of Antonican Bards by delivering some [mail]?'
<p><b>You say, </b>'I am interested in delivering some mail'
<br><b>Lyra Lyrestringer says </b>'I have messages that need to go to well. right now I have one that needs to go to Kelethin.  Will you [deliver] mail to [Kelethin] for me?'
<p><b>You say, </b>'I will deliver mail to kelethin'
<br><b>Lyra Lyrestringer says </b>'Take this letter to Jakum Webdancer in Kelethin.  You can find him at the bard guild hall.  I am sure he will compensate you for your troubles.'
</td></tr></table>