<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13844>Shiny Card</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Manik Compolten says </b>'Greetings, young one. I am Manik Compolten, High Watchman. Are you a [new warrior] or an [experienced fighter]?'
<p><b>You say, </b>'i am a new warrior'
<br><b>Manik Compolten says </b>'It is always good to see new blood amongst the Gemchoppers. I have a small task for you. Take this keycard. I will give you only one at a time. Use each to obtain blackboxes for the C series clockworks. I am sure you are familiar with the clockworks. When you are done, bring them all to me. Let me know if you need another keycard.'
<br><b>Manik Compolten gives you : </b><a href=http://phobos/eq/item.php?id=13844>Shiny Card</a>
<p><b>You say, </b>'i am an experienced fighter'
<br><b>Manik Compolten says </b>'Good.  I require your talents to destroy rogue clockworks.  After we sent the clockworks to destroy the Asylum of the Mad we found some of the clockworks went haywire and never returned.  We must destroy them, not for the safety of the people, but to keep our technology from falling into the hands of any other nation. Go to the Steamfont Mountains and return their rogue blackboxes to me.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>