<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1360>Shining Metallic Robes</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10600>Mechanical Pen</a></ul></td><td><p><b>You say, </b>'mechanical pen'
<br><b>Rilgor Plegnog says </b>'Why do you want one of those contraptions. You will spend more time repairing it then you will writing with it. But if you insist on getting one, you are going to have to do a small favor.'
<br><font color=green><b>Rilgor Plegnog </b>tugs at your robe and grins evilly. 'Mighty nice outfit you have there. Sure beats these drab robes us three are wearing. Hmm...my favorite color is purple, in fact a shiny metallic purple would do nicely. How bad did you want that pen?'</font>
<p><b>You give Rilgor Plegnog : </b><a href=http://phobos/eq/item.php?id=1360>Shining Metallic Robes</a>
<br><b>Rilgor Plegnog says </b>'Very nice!! It is perfect! Here take this pen. Have fun with it.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Rilgor Plegnog gives you : </b><a href=http://phobos/eq/item.php?id=10600>Mechanical Pen</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>