<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13198>Scrap Metal</a><li><a href=http://phobos/eq/item.php?id=9426>Bundle of Super Conductive Wires</a><li><a href=http://phobos/eq/item.php?id=28618>Gold tipped boar horn</a><li><a href=http://phobos/eq/item.php?id=29906>Shard of Pure Energy</a><li><a href=http://phobos/eq/item.php?id=28165>Silicorrosive Grease</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15980>Note to Fimli</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=115>Gem Choppers</a><li><a href=http://phobos/eq/faction.php?id=176>King Ak'Anon</a><li><a href=http://phobos/eq/faction.php?id=210>Merchants of Ak'Anon</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=71>Dark Reflection</a><li><a href=http://phobos/eq/faction.php?id=39>Clan Grikbar</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Sanfyrd Featherhead says </b>'Greetings! I am the operator of this scrapyard. If you have any scrap metal. I would be glad to purchase it from you in loads of four.  The Gemchoppers no longer allow me to accept blackbox fragments and micro servos.'
<p><b>You give Sanfyrd Featherhead : </b><a href=http://phobos/eq/item.php?id=13198>Scrap Metal</a> (x4)
<br><b>Sanfyrd Featherhead says </b>'Excellent work. You were born to be a warrior. Here is a little bonus for the good job.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=115>Gem Choppers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=176>King Ak'Anon</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=210>Merchants of Ak'Anon</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=71>Dark Reflection</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=39>Clan Grikbar</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 7gp
<p><b>You give Sanfyrd Featherhead : </b><a href=http://phobos/eq/item.php?id=9426>Bundle of Super Conductive Wires</a>, <a href=http://phobos/eq/item.php?id=28618>Gold tipped boar horn</a>, <a href=http://phobos/eq/item.php?id=29906>Shard of Pure Energy</a>, <a href=http://phobos/eq/item.php?id=28165>Silicorrosive Grease</a>
<br><b>Sanfyrd Featherhead says </b>'I've been waiting for those.  Thank you, please take this!'
<br><b>Sanfyrd Featherhead gives you : </b><a href=http://phobos/eq/item.php?id=15980>Note to Fimli</a>
</td></tr></table>