<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13333>Iron Pellet</a><li><a href=http://phobos/eq/item.php?id=13387>Tergon's Spellbook</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1717>Sealed Letter</a><li><a href=http://phobos/eq/item.php?id=15058>Spell: Elementalkin: Earth</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=91>Eldritch Collective</a><li><a href=http://phobos/eq/faction.php?id=115>Gem Choppers</a><li><a href=http://phobos/eq/faction.php?id=176>King Ak'Anon</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=71>Dark Reflection</a><li><a href=http://phobos/eq/faction.php?id=322>The Dead</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Tergon Brenclog says </b>'Eh!!? What do I see before me? A young upstart? Some child pretending to be a great mind? If you wish to test your mettle then you will assist Tergon. Will you [Help Tergon] or are you far [too superior] to deal with such things?'
<p><b>You say, </b>'I will help tergon'
<br><b>Tergon Brenclog says </b>'No!! You will help yourself. Your task shall find your skills tested. Succeed and knowledge is yours. Fail and death shall embrace you. Go to the Steamfont Mountains and seek out a troll named Bugglegupp. As a youngster I once tried to attack the beast with a device of mine. It sent an Iron Pellet deep into the beasts head. Kill Bugglegupp and return the Iron Pellet. I hope the Pellet does not get lost in the battle.'
<p><b>You say, </b>'I am too superior'
<br><b>Tergon Brenclog says </b>'Well excuse me!! your majesty. Please forgive my arrogance. Now get out of here, before you stink this place up with that rotting grape you call a brain!'
<p><b>You say, </b>'What further tasks'
<br><b>Tergon Brenclog says </b>'Not all experience is gained upon the battlefield. We magicians must heighten our minds to become formidable opponents. I see much promise in you, Vaslin . I will require you to [travel abroad] toward Freeport.'
<p><b>You say, </b>'I will travel abroad'
<br><b>Tergon Brenclog says </b>'You will go to Freeport and seek out the Academy of Arcane Science. There you shall find my brother Retlon. He has scribed some new spells in my [personal spellbook]. Hand him this note as proof of your alliance. He works closely with Master Dooly Jonkers.'
<br><b>Tergon Brenclog gives you : </b><a href=http://phobos/eq/item.php?id=1717>Sealed Letter</a>
<p><b>You say, </b>'What Defector'
<br><b>Tergon Brenclog says </b>'It seems a gnome magician by the name of Toko Binlittle has gone and left the guild. He joined forces with the [Pirates of Gunthak]. Find him. He must be destroyed. Our secrets cannot be known. Return his spellbook to me and I shall give you the [Elemental Grimoire].'
<p><b>You say, </b>'What pirates of gunthak'
<br><b>Tergon Brenclog says </b>'From what I know, the Pirates of Gunthak are from the southern Gulf of Gunthak. It seems as though a small band of them has been operating within the Ocean of Tears, leagues from their own territory.'
<p><b>You say, </b>'what elemental grimoire'
<br><b>Tergon Brenclog says </b>'The Elemental Grimoire contains the knowledge which will advance your techniques in research. With it you shall learn to research spells and scribe them for your own spellbook.'
<p><b>You give Tergon Brenclog : </b><a href=http://phobos/eq/item.php?id=13333>Iron Pellet</a>
<br><b>Tergon Brenclog says </b>'So, you have survived. There is no doubt in my mind that you achieved this solely with your own powers. Only a dim one requires the assistance of others. Take this. May it help you in your pursuit of greatness. [Further tasks] may bring you to that point.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=91>Eldritch Collective</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=71>Dark Reflection</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=322>The Dead</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=115>Gem Choppers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=176>King Ak'Anon</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Tergon Brenclog : </b><a href=http://phobos/eq/item.php?id=13387>Tergon's Spellbook</a>
<br><b>Tergon Brenclog says </b>'Thank you [Your Name]. I had no doubt you would fulfill my will and return my spellbook.. here is your reward for such effort.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=91>Eldritch Collective</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=71>Dark Reflection</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=322>The Dead</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=115>Gem Choppers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=176>King Ak'Anon</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Tergon Brenclog gives you : </b><a href=http://phobos/eq/item.php?id=15058>Spell: Elementalkin: Earth</a>
</td></tr></table>