<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10994>Winex's Staff</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17125>Curing Kit</a><li><a href=http://phobos/eq/item.php?id=19561>Tattered Boot Pattern</a><li><a href=http://phobos/eq/item.php?id=19555>Tattered Cap Pattern</a><li><a href=http://phobos/eq/item.php?id=19559>Tattered Glove Pattern</a><li><a href=http://phobos/eq/item.php?id=19560>Tattered Pant Pattern</a><li><a href=http://phobos/eq/item.php?id=19556>Tattered Tunic Pattern</a><li><a href=http://phobos/eq/item.php?id=19557>Tattered Sleeve Pattern</a><li><a href=http://phobos/eq/item.php?id=19558>Tattered Wristband Pattern</a><li><a href=http://phobos/eq/item.php?id=11081>Staff of Dark Reflections</a></ul></td><td><p><b>You say, </b>'silk thread'
<br><b>Tilkzog Mournunder says </b>'To create silk thread, combine 2 spiderling silk inside a tailoring kit.'
<p><b>You say, </b>'Hail, Tilkzog Mournunder'
<br><b>Tilkzog Mournunder says </b>'Hail [Your Name]. I am Tilkzog Mournunder, Necromancer of the Dark Reflection. It is my duty here to assist not only the young necromancers of the Dark Reflection but also those wizards, magicians, and enchanters that have been called into the service of the Plague Bringer. I will aid you in obtaining an outfit of [durable clothing] suitable for a young sorcerer of the Dark Reflection. Once you have been adequately outfitted for venturing beyond our homeland in service of the Plague Bringer return to me and I will assist you in obtaining a [staff of dark reflections].'
<p><b>You say, </b>'staff of dark reflections'
<br><b>Tilkzog Mournunder says </b>'The Dark Reflection has many enemies even within our home of Ak'Anon and the surrounding Steamfont Mountains. Many fear and oppose the beliefs that grant us our vision and powers. A wizard of the Eldrich Collective by the name of Winex Kloktik has been aiding members of the Deep Muses hunt and slay those loyal to Bertoxxulous and the Dark Reflection. Seek Winex Kloktik and eliminate her. When you have completed this task bring me Winex's Staff.'
<p><b>You say, </b>'durable clothing'
<br><b>Tilkzog Mournunder says </b>'The sorcerous servants of Bertoxxulous, the Plague Bringer, are privileged with the sight of the Dark Reflection. This gift enlightens us to the powers of disease, decay, death, and destruction. Forces that are misunderstood and feared by the majority of Norrath, including our fellow gnomes of Ak'Anon. These forces are the catalyst of change, cleansing Norrath of the old and weak, and we are the agents of this catalyst. However, before you will be of much use to the Dark Reflection you must gather the [components] necessary for the outfit that will protect and aid you in your duties.'
<p><b>You say, </b>'components'
<br><b>Tilkzog Mournunder says </b>'You will need this Curing Kit and varying components depending on the piece of clothing you wish to fabricate. Do you desire to craft a [plague sorcerer cap], [plague sorcerer wristband], [plague sorcerer gloves], [plague sorcerer boots], [plague sorcerer sleeves], [plague sorcerer pantaloons], or [plague sorcerer robe]?'
<br><b>Tilkzog Mournunder gives you : </b><a href=http://phobos/eq/item.php?id=17125>Curing Kit</a>
<p><b>You say, </b>'plague sorcerer boots'
<br><b>Tilkzog Mournunder says </b>'To craft Plague Sorcerer Boots you require two [silk thread], two ebon drakeling bile, and two large rat pelts. Once you have the necessary components combine them in your Curing Kit with this Tattered Boot Pattern.'
<br><b>Tilkzog Mournunder gives you : </b><a href=http://phobos/eq/item.php?id=19561>Tattered Boot Pattern</a>
<p><b>You say, </b>'plague sorcerer cap'
<br><b>Tilkzog Mournunder says </b>'To craft a Plague Sorcerer Cap you will require two [silk thread], ebon drakeling bile, and a grikbar kobold scalp. Once you have the necessary components combine them in your Curing Kit with this Tattered Cap Pattern.'
<br><b>Tilkzog Mournunder gives you : </b><a href=http://phobos/eq/item.php?id=19555>Tattered Cap Pattern</a>
<p><b>You say, </b>'plague sorcerer gloves'
<br><b>Tilkzog Mournunder says </b>'To craft Plague Sorcerer Gloves you require two [silk thread], ebon drakeling bile, and two yellow recluse silks. Once you have the necessary components combine them in your Curing Kit with this Tattered Glove Pattern.'
<br><b>Tilkzog Mournunder gives you : </b><a href=http://phobos/eq/item.php?id=19559>Tattered Glove Pattern</a>
<p><b>You say, </b>'plague sorcerer pantaloons'
<br><b>Tilkzog Mournunder says </b>'To craft Plague Sorcerer Pantaloons you require two [silk thread], young ebon drake bile, and four yellow recluse silks. Once you have the necessary components combine them in your Curing Kit with this Tattered Pant Pattern.'
<br><b>Tilkzog Mournunder gives you : </b><a href=http://phobos/eq/item.php?id=19560>Tattered Pant Pattern</a>
<p><b>You say, </b>'plague sorcerer robe'
<br><b>Tilkzog Mournunder says </b>'To craft a Plague Sorcerer Robe you will require three [silk thread], ebon drake bile, a giant rat pelt, and two yellow recluse silks. Once you have the necessary components combine them in your Curing Kit with this Tattered Tunic Pattern.'
<br><b>Tilkzog Mournunder gives you : </b><a href=http://phobos/eq/item.php?id=19556>Tattered Tunic Pattern</a>
<p><b>You say, </b>'plague sorcerer sleeves'
<br><b>Tilkzog Mournunder says </b>'To craft Plague Sorcerer Sleeves you require two [silk thread], young ebon drake bile, and three yellow recluse silks. Once you have the necessary components combine them in your Curing Kit with this Tattered Sleeves Pattern.'
<br><b>Tilkzog Mournunder gives you : </b><a href=http://phobos/eq/item.php?id=19557>Tattered Sleeve Pattern</a>
<p><b>You say, </b>'plague sorcerer wristband'
<br><b>Tilkzog Mournunder says </b>'To craft a Plague Sorcerer Wristband you require a [silk thread], ebon drakeling bile, and a large rat pelt. Once you have the necessary components combine them in your Curing Kit with this Tattered Wristband Pattern.'
<br><b>Tilkzog Mournunder gives you : </b><a href=http://phobos/eq/item.php?id=19558>Tattered Wristband Pattern</a>
<p><b>You give Tilkzog Mournunder : </b><a href=http://phobos/eq/item.php?id=10994>Winex's Staff</a>
<br><b>Tilkzog Mournunder says </b>'You have done well to bring Winex's staff to me, [Your Name]. Here is your reward for dealing with that meddlesome fool.'
<br><b>Tilkzog Mournunder gives you : </b><a href=http://phobos/eq/item.php?id=11081>Staff of Dark Reflections</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>