<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18774>Registration Letter</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18868>A List</a><li><a href=http://phobos/eq/item.php?id=13523>Soot Stained Gold Robe*</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=91>Eldritch Collective</a><li><a href=http://phobos/eq/faction.php?id=115>Gem Choppers</a><li><a href=http://phobos/eq/faction.php?id=176>King Ak'Anon</a><li><a href=http://phobos/eq/faction.php?id=210>Merchants of Ak'Anon</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Tobon Starpyre says </b>'It is good to see the young show an interest in the ways of magic. Its circles can be used in tandem with our unique ways of tinkering. Have you [joined the Eldritch Collective] or are you [merely curious]?'
<p><b>You say, </b>'I am merely curious'
<br><b>Tobon Starpyre says </b>'Please look around. We have much knowledge within these halls. May you soon find your place among our members. Good day.'
<p><b>You say, </b>'I have joined the Eldritch Collective'
<br><b>Tobon Starpyre says </b>'Very good. Would you like to [go on a little mission] or are you busy studying?'
<p><b>You say, </b>'I will go on a little mission'
<br><b>Tobon Starpyre says </b>'Fabulous! Here is a list of the observers outside of Ak'Anon. Go and ask each for a [spare telescope lens]. Each should give you one. We have need of them.  I await your return as does your reward, either Fire Bolt or Fingers of Fire.  Meant for a skilled wizard of the eighth trial.'
<br><b>Tobon Starpyre gives you : </b><a href=http://phobos/eq/item.php?id=18868>A List</a>
<p><b>You say, </b>'who is yendar'
<br><b>Tobon Starpyre says </b>'Oh, he is my older brother. Used to be the leader of the Eldritch Collective. Then he founded the Observers, a pretty good piece of work. Went off his rocker a long while back, though. Became obsessed with Innoruuk and the Teir'Dal. Stays away for days at a time, nobody knows where he has been. Mother still worries about him, asked me to keep an eye on him. But he is a grown gnome, and with his mastery of the art, has little to fear in this world or others. But if you are seeking him, I would look outside Ak'Anon, in the Steamfonts. That is where he makes his home these days.'
<p><b>You give Tobon Starpyre : </b><a href=http://phobos/eq/item.php?id=18774>Registration Letter</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Tobon Starpyre gives you : </b><a href=http://phobos/eq/item.php?id=13523>Soot Stained Gold Robe*</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=91>Eldritch Collective</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=115>Gem Choppers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=176>King Ak'Anon</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=210>Merchants of Ak'Anon</a> has gotten better.</font>
</td></tr></table>