<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18702>Old Folded Letter</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13524>Dark Gold Felt Robe*</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=71>Dark Reflection</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Vaenor Husga says </b>'Hail.'
<p><b>You give Vaenor Husga : </b><a href=http://phobos/eq/item.php?id=18702>Old Folded Letter</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=71>Dark Reflection</a> has gotten better.</font>
<br><b>Vaenor Husga says </b>'Thank you. Here is your Robe. Wear it proudly.'
<br><b>Vaenor Husga gives you : </b><a href=http://phobos/eq/item.php?id=13524>Dark Gold Felt Robe*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>