<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=67054>Note to Tani</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>#Tani Cogswin says </b>'Please leave me be if they catch me talking to you I will be punished again.'
<p><b>You say, </b>'Who is Historian Selrin'
<br><b>#Tani Cogswin says </b>'Historian Selrin is the lorekeeper of Chardok. He spends most of his time in the library but I hear he and the Prince often talk for hours on end. Please you must get that paper back from him and return it to my brother. Don't worry about me, your timely intrusion has provided an opportunity for my escape.'
<p><b>You give #Tani Cogswin : </b><a href=http://phobos/eq/item.php?id=67054>Note to Tani</a>
<br><b>#Tani Cogswin says </b>'Oh thank Brell I thought I would never be found. My borther Pellillo is right we were wrong to take the paper and I realized that shortly after, but when I started the journey back I was captured by a band of Sarnaks and brought here. When they found the paper, the Queen demanded that it be researched and so she gave it to [Historian Selrin].'
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=103217>#Historian_Silren_Di`zok</a></b> spawns (-559.92,1291.27,-159.75).</font>
</td></tr></table>