<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=16972>Mt. Death Mineral Salts</a><li><a href=http://phobos/eq/item.php?id=22135>Green Goblin Skin</a><li><a href=http://phobos/eq/item.php?id=6476>Head of Skargus</a><li><a href=http://phobos/eq/item.php?id=5728>Di'zok Signet of Service</a><li><a href=http://phobos/eq/item.php?id=5727>Regal Band of Bathezid</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=5727>Regal Band of Bathezid</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=23>Brood of Di`Zok</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=384>Mountain Death Clan</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Herald Telcha says </b>'Hail to you, lesser being! It is good to see you seeking the enlightenment and satisfaction that can only come from serving the Sarnak! Experience for yourself the joy of fealty to our Lord the Overking Bathezid Di'zok! I am Telcha, lesser apprentice sub-herald in training to the Court of Di'zok and I stand ready to welcome those who would serve our noble Overking. Are you here to [aid] us?'
<p><b>You say, </b>'aid'
<br><b>Herald Telcha says </b>'Ah, so good of you to strive to improve yourself! So often members of your pathetic lesser races plod along in ignorance, unaware of the most Noble empire of the Di'zok. Enough though of the chit-chat, as I'm sure you are most eager to make yourself useful! Before you may enter our worthy city and be looked upon as a valuable servant, you must prove your worth to our [cause].'
<p><b>You say, </b>'cause'
<br><b>Herald Telcha says </b>'The first task I shall set you is the slaying of goblins! Ooh, how very heroic you must feel to finally have a worthy goal guiding your previously menial existance! Yes, go forth from here and journey to Droga, stronghold of our enemies. Slay the warriors and menials of the Mountain Death Clan, bring havoc to their homes. Return to me with proof of your deeds, to raise in your standing with the Dizok. Bring me [tokens] of many dead goblins, and one day you shall walk among us.'
<p><b>You say, </b>'token'
<br><b>Herald Telcha says </b>'As proof of your deeds I shall require either 2 Mountain Death mineral salts, or a patch of green goblin skin. Bring me many of these, as you bring destruction on the goblin city, and I shall speak to my superiors of your efforts on our behalf. Do enough for our cause, and I shall reward you directly. Return to me later and remind me that you serve the Sarnak, and I may have a ring for you if you are worthy.'
<p><b>You say, </b>'serve the sarnak'
<br><b>Herald Telcha says </b>'What to do, what to do.. You've served the Di'zok well, young one but you are not yet experienced enough to wear the Signet of the Di'zok. Come back when you've seen a bit more of the world, and the ring shall be yours.'
<p><b>You give Herald Telcha : </b><a href=http://phobos/eq/item.php?id=16972>Mt. Death Mineral Salts</a> x2
<br><b>Herald Telcha says </b>'Ah, most excellent! You are sure to be more highly valued as our servant once I speak to my masters of this! Mountain Death Mineral Salts, they shall grace the Overkings table this very night! Be off, minion! Fetch us some more salts to prove your value!'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=23>Brood of Di`Zok</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=384>Mountain Death Clan</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Herald Telcha : </b><a href=http://phobos/eq/item.php?id=22135>Green Goblin Skin</a>
<br><b>Herald Telcha says </b>'Green Goblin Skin! You have indeed been busy! I shall speak to my masters of this, continue your good work and return to me with more skins.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=23>Brood of Di`Zok</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=384>Mountain Death Clan</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Herald Telcha : </b><a href=http://phobos/eq/item.php?id=6476>Head of Skargus</a>, <a href=http://phobos/eq/item.php?id=5728>Di'zok Signet of Service</a>
<br><b>Herald Telcha says </b>'Ah hah! You are notworthy indeed amongst the servants of the Sarnak! Perhaps I should have you killed, before your deeds outdo mine.. Hmm..'
<br><b>Herald Telcha says </b>'Guards! Guards! Haha, do not panic menial being, in fact I am most impressed with your service. Here is the ring I promised you in exchange for your efforts.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=23>Brood of Di`Zok</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=384>Mountain Death Clan</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Herald Telcha gives you : </b><a href=http://phobos/eq/item.php?id=5727>Regal Band of Bathezid</a>
<br><font color=grey><i>A global variable is unset at this point.</font></i>
<p><b>You give Herald Telcha : </b><a href=http://phobos/eq/item.php?id=5727>Regal Band of Bathezid</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>