<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10036>Black Sapphire</a><li><a href=http://phobos/eq/item.php?id=10035>Ruby</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19964>Piece of a medallion</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Niblek says </b>'I Niblek. You want something from Niblek?  Niblek find treasures in walls. Niblek like to trade treasures.'
<p><b>You say, </b>'treasures'
<br><b>Niblek says </b>'Niblek find piece of old jewelry! It very old, probably has much power!'
<p><b>You say, </b>'want'
<br><b>Niblek says </b>'Niblek likes shiny tings very much! You bring Niblek two shiny tings! Niblek has seen black sapphire and ruby! Niblek likes them very much!'
<p><b>You give Niblek : </b><a href=http://phobos/eq/item.php?id=10035>Ruby</a>, <a href=http://phobos/eq/item.php?id=10036>Black Sapphire</a>
<br><b>Niblek says </b>'I much happy now!! I want shiny tings for long time! I give you ugly broken necklace now!'
<br><b>Niblek gives you : </b><a href=http://phobos/eq/item.php?id=19964>Piece of a medallion</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>