<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=6477>Spirit Wracked Urn</a><li><a href=http://phobos/eq/item.php?id=6478>Undead Dragon Sinew</a><li><a href=http://phobos/eq/item.php?id=5727>Regal Band of Bathezid</a></ul></td><td><p><b>You say, </b>'hail'
<p><b>You say, </b>'service'
<p><b>You say, </b>'additional components'
<p><b>You give Queen Velazul Di`zok : </b><a href=http://phobos/eq/item.php?id=6477>Spirit Wracked Urn</a>, <a href=http://phobos/eq/item.php?id=6478>Undead Dragon Sinew</a>, <a href=http://phobos/eq/item.php?id=5727>Regal Band of Bathezid</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>