<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=30269>Sceptre of the Coldain Ancients</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=30270>Gem of Persuasion</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Erdarf Restil says </b>'Huh? Dont you know better than to interrupt a Coldain enjoying his ale? I may be a user of priestly magic but that doesnt mean I cant bash your head in.'
<p><b>You say, </b>'priestly magic'
<br><b>Erdarf Restil says </b>'Aye. An old one not much taken with idle chit chat.'
<p><b>You say, </b>'old one'
<br><b>Erdarf Restil says </b>'Very old, very wise, and on and on. You must have some point to bothering me. Im not a merchant and I dont contract myself out for work. I've performed works for the Dain. There isn't much I haven't done..'
<p><b>You say, </b>'have you done'
<br><font color=green><b>Erdarf Restil </b>chuckles at you. 'If you want to impress me, and let me make certain you understand I doubt you can, then you can do what I never was able. For years I adventured and attempted to venture to the bottom of the Crystal Caverns in search of ancient artifacts from my people. Do that, show me that you have, and I will be impressed.'</font>
<p><b>You give Erdarf Restil : </b><a href=http://phobos/eq/item.php?id=30269>Sceptre of the Coldain Ancients</a>
<br><font color=green><b>Erdarf Restil </b>smirks at you. 'Hrm, you again eh? Did you come back to bother me with more...Wait a minute, let me see that. This is... This must be, yes it is. This is one of the ancient coldain priests sceptres of channeling. This is too good to be true. Haha! Oh, what I can do with this. Here, take this gem from the sceptre. If ancient lore proves right it will allow you to persuade beasts of many kinds.' He grins at you strangely and then leaves.</font>
<br><b>Erdarf Restil gives you : </b><a href=http://phobos/eq/item.php?id=30270>Gem of Persuasion</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>