<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17513>Velium Purifier</a></ul></td><td><p><b>You say, </b>'velium vapors'
<br><b>Frundle Frenkler says </b>'Ahh, you come seeking my family recipe? After all you've done for our people it's the least I can do. First you must fashion a velium vial, then combine the vial with two small pieces of velium in this jar. That's all there is to it. Please keep the recipe a secret.'
<br><b>Frundle Frenkler gives you : </b><a href=http://phobos/eq/item.php?id=17513>Velium Purifier</a>
<p><b>You say, </b>'velium vial'
<br><b>Frundle Frenkler says </b>'I'm no potter mind you, but if I remember correctly it's a small brick of velium, three crystalline silks, and two glass shards. Then you'll have to finish up by firing it in a kiln with a high quality firing sheet.'
</td></tr></table>