<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1418>Thoridain's Napkin</a><li><a href=http://phobos/eq/item.php?id=1428>Snow Griffin Souffle</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1422>Seal of Thoridain</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=49>Coldain</a><li><a href=http://phobos/eq/faction.php?id=67>Dain Frostreaver IV</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=188>Kromrif</a><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a></ul></td><td><hr><b>When Grand Historian Thoridain spawns </b>
<p><b>You say, </b>'hail'
<p><b>You say, </b>'Oh Brell, Thank you for protecting me and seeing me through my trials. Forgive me for the things I think and say and do that displease you. Please reveal to me your will and bless me with the patience and obedience to do that which you desire. Amen.'
<p><b>You give Grand Historian Thoridain : </b><a href=http://phobos/eq/item.php?id=1418>Thoridain's Napkin</a>, <a href=http://phobos/eq/item.php?id=1428>Snow Griffin Souffle</a>
<br><b>Grand Historian Thoridain says </b>'My compliments, [Your Name], what a wonderful dish! Please accept my personal Seal as a token of my appreciation. May it give you power over your adversaries.'
<br><b>Grand Historian Thoridain gives you : </b><a href=http://phobos/eq/item.php?id=1422>Seal of Thoridain</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=49>Coldain</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=67>Dain Frostreaver IV</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten worse.</font>
<p><b>You give Grand Historian Thoridain : </b><a href=http://phobos/eq/item.php?id=1428>Snow Griffin Souffle</a>
<br><b>Grand Historian Thoridain says </b>'My compliments, [Your Name], what a wonderful dish!'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=49>Coldain</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=67>Dain Frostreaver IV</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>