<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1856>Etched Rune</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17514>Fish oil extractor</a><li><a href=http://phobos/eq/item.php?id=1856>Etched Rune</a></ul></td><td><p><b>You say, </b>'cutlass fish oil'
<br><b>Grimthor Brewbeard says </b>'Grab a pole and fish the waters in Iceclad until you catch yourself three Iceclad Cutlass fish. Place them in this oil extractor and you'll have whatcha need.'
<br><b>Grimthor Brewbeard gives you : </b><a href=http://phobos/eq/item.php?id=17514>Fish oil extractor</a>
<p><b>You say, </b>'liquid velium'
<br><b>Grimthor Brewbeard says </b>'Collect a small piece of velium and a bottle of rubbing alcohol and brew them together in a barrel. It aint easy, but it should prove to be a minor task for the likes of you.'
<p><b>You give Grimthor Brewbeard : </b><a href=http://phobos/eq/item.php?id=1856>Etched Rune</a>
<br><b>Grimthor Brewbeard says </b>'That looks about right. You're moving along well outlander. Next you'll be needin to brew up a sacred ink to fill the grooves in your rune. Take Iceclad Cutlass fish oil, liquid velium, and some Royal Kromrif blood, brew them in the barrel here then take the product and the rune and combine them in a fletching kit. Show Talem Tucker the resulting item if yer successful.'
<br><b>Grimthor Brewbeard gives you : </b><a href=http://phobos/eq/item.php?id=1856>Etched Rune</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>