<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1415>Leif's Napkin</a><li><a href=http://phobos/eq/item.php?id=1425>Tundrabear Sandwich</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1419>Used Napkin</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=49>Coldain</a><li><a href=http://phobos/eq/faction.php?id=67>Dain Frostreaver IV</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=188>Kromrif</a><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a></ul></td><td><p><b>You give Guard Leif : </b><a href=http://phobos/eq/item.php?id=1415>Leif's Napkin</a>, <a href=http://phobos/eq/item.php?id=1425>Tundrabear Sandwich</a>
<br><b>Guard Leif says </b>'Well I'll be derned. An outlander that can make a good Bearmeat 'n Bread! Thank ye, [Your Name].'
<br><b>Guard Leif gives you : </b><a href=http://phobos/eq/item.php?id=1419>Used Napkin</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=49>Coldain</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=67>Dain Frostreaver IV</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten worse.</font>
<p><b>You give Guard Leif : </b><a href=http://phobos/eq/item.php?id=1425>Tundrabear Sandwich</a>
<br><b>Guard Leif says </b>'Well I'll be derned. An outlander that can make a good Bearmeat 'n Bread! Thank ye, [Your Name].'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=49>Coldain</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=67>Dain Frostreaver IV</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>