<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=8893>Etching Tools</a></ul></td><td><p><b>You say, </b>'I need a set of Etching Tools'
<br><b>Meg Tucter says </b>'Oh, really? There are not many that work in faceting gems. I am surprised to see your interest. You can have this old set of mine. There is no need to return the tools, Talem recently made me a new sturdy set. Brell bless him.'
<br><b>Meg Tucter gives you : </b><a href=http://phobos/eq/item.php?id=8893>Etching Tools</a>
</td></tr></table>