<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1420>Borannin's Seal</a><li><a href=http://phobos/eq/item.php?id=1419>Used Napkin</a><li><a href=http://phobos/eq/item.php?id=1423>Dirty Pot</a><li><a href=http://phobos/eq/item.php?id=1424>Used Pie Tin</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1415>Leif's Napkin</a><li><a href=http://phobos/eq/item.php?id=1416>Trita's Napkin</a><li><a href=http://phobos/eq/item.php?id=1417>Brita's Napkin</a><li><a href=http://phobos/eq/item.php?id=1418>Thoridain's Napkin</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=49>Coldain</a><li><a href=http://phobos/eq/faction.php?id=67>Dain Frostreaver IV</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=188>Kromrif</a><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Mordin Frostcleaver says </b>'Ah, allo there, and welcome to me shop, [Your Name]. Ye'll have to excuse the mess but I've been havin a bloody good time here lately. . . HAR HAR, ye get it? Anyways, thanks to you offlanders I now have a selection of some exotic meats never afore seen here on Velious.  I've been amazed at the demand for some of 'em.  I can't seem to keep shark meat in stock any more.  I wonder if eatin' raw fish is catching on?  In addition to supplyin' the freshest meat in Thurgadin I also offer tasks to would-be hunters in the wastes.'
<p><b>You say, </b>'tasks'
<br><b>Mordin Frostcleaver says </b>'Sorry, [Your Name], but I've got no tasks to offer ye this week.  If ye be seriously lookin fer sumthin ta do ask ole Borannin 'bout duties fer the crown..'
<p><b>You say, </b>'tundrabear sandwich'
<br><b>Mordin Frostcleaver says </b>'Dat's easy, ye just take a slab o' dat Tundra Kodiak meat and a jug o' sauce, put it in da oven, den combine the product with a loaf o' bread in a mixin' bowl an' there ye be.'
<p><b>You say, </b>'snow bunny stew'
<br><b>Mordin Frostcleaver says </b>'Simple enuff, getcherself two hunksa Bunny meat and a jug o' sauces. Stir 'em in a mixin bowl, then put spices and two flasks o' water with it and cook it in a pot. Mmmm, zesty!'
<p><b>You say, </b>'ulthork meat pie'
<br><b>Mordin Frostcleaver says </b>'Hmm, lemme look that one up. Been a while since I made one. Here we are, two Ulthork meats, a vinegar and a spices in a mixin' bowl. Put yer meat mix, a clump o' dough, an' a pie tin in da oven an' yer good ta go.'
<p><b>You say, </b>'snow griffin souffle'
<br><b>Mordin Frostcleaver says </b>'This one's a bit tricky, ya toss four snow griffin eggs and a pack of spices in de oven. Ye must bake it just right or it's all gunna be wasted. When yer done bring it to Thoridain and if ye did it right he'll give ye his special seal. Just show Borannin that seal and yer shawl and he'll know that yer finished in the kitchen.'
<p><b>You give Mordin Frostcleaver : </b><a href=http://phobos/eq/item.php?id=1420>Borannin's Seal</a>
<br><b>Mordin Frostcleaver says </b>'Hullo, [Your Name], I see you've signed on for a bit of food service eh? Well, we can always use an extra pair o' hands here dat's fer sure. First things first, warsh yer grubby mitts an' cook up dinner fer good ol' Leif. Should'n be too tough fer ye, he has simple enough taste. Make him a Tundrabear sandwich an' lemme know when he's been fed. Don'tcha ferget ta give him this with his meal.'
<br><b>Mordin Frostcleaver gives you : </b><a href=http://phobos/eq/item.php?id=1415>Leif's Napkin</a>
<p><b>You give Mordin Frostcleaver : </b><a href=http://phobos/eq/item.php?id=1419>Used Napkin</a>
<br><b>Mordin Frostcleaver says </b>'Well don, outlander! We'll make a chef of you before we're through. Next you'll need to whip up some Snow Bunny stew fer Missus Coldheart. Again, give her this napkin with her meal an' lemme know when she's been served.'
<br><b>Mordin Frostcleaver gives you : </b><a href=http://phobos/eq/item.php?id=1416>Trita's Napkin</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=49>Coldain</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=67>Dain Frostreaver IV</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten worse.</font>
<p><b>You give Mordin Frostcleaver : </b><a href=http://phobos/eq/item.php?id=1423>Dirty Pot</a>
<br><b>Mordin Frostcleaver says </b>'Now yer cookin! Letsee here... Guard Leif, check... Trita Coldheart, check... Ahh yes, next we need an Ulthork meat pie fer Brita. She's a doll, smart too, but she can be testy when she's hungry so get movin'!'
<br><b>Mordin Frostcleaver gives you : </b><a href=http://phobos/eq/item.php?id=1417>Brita's Napkin</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=49>Coldain</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=67>Dain Frostreaver IV</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten worse.</font>
<p><b>You give Mordin Frostcleaver : </b><a href=http://phobos/eq/item.php?id=1424>Used Pie Tin</a>
<br><b>Mordin Frostcleaver says </b>'More dirty dishes, eh? Well outlander, only one more meal to serve and I'll be done with ye. Make a snow griffin souffle fer the Grand Historian himself. It's his favorite.'
<br><b>Mordin Frostcleaver gives you : </b><a href=http://phobos/eq/item.php?id=1418>Thoridain's Napkin</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=49>Coldain</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=67>Dain Frostreaver IV</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>