<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1179>Silk Coldain Prayer Shawl</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17879>Glowing Bile Soaker</a><li><a href=http://phobos/eq/item.php?id=1179>Silk Coldain Prayer Shawl</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Rexx Frostweaver says </b>'Hmmm, ye be one o them offlanders, don't ye? I've heard some strange tales o yer kind so don't be tryin' any funny business with me. I know the value of a platinum piece and I'll not get cheated by yer foreign coin.'
<p><b>You say, </b>'prayer shawl'
<br><b>Rexx Frostweaver says </b>'Gather five strands of crystalline silk thread and combine them in a sewing kit to make a crystalline silk fiber. Take this container and combine a glowing shardwurm bile with three of the fibers to form a piece of glowing crystalline silk. Five pieces of glowing crystalline silk sewn to your fur-lined shawl will yield a beautiful silk shawl. Become a master in the art of tailoring before risking all you've worked for and be sure to let me inspect your work when it's complete.'
<br><b>Rexx Frostweaver gives you : </b><a href=http://phobos/eq/item.php?id=17879>Glowing Bile Soaker</a>
<p><b>You say, </b>'am i worthy'
<br><b>Rexx Frostweaver says </b>'To ensure your worthiness you must continue to refine your prayer shawl. Speak with my wife Betti regarding the embroidered shawl and listen carefully to her words. Hurry now, there seems to be a sense of urgency about.'
<p><b>You give Rexx Frostweaver : </b><a href=http://phobos/eq/item.php?id=1179>Silk Coldain Prayer Shawl</a>
<br><b>Rexx Frostweaver says </b>'Splendid, [Your Name], this is beautiful workmanship! As the Grand Historian may have mentioned, our esteemed Dain Frostreaver the fourth is making some important plans with his council. These plans will doubtlessly include you if the Dain deems you worthy.'
<br><b>Rexx Frostweaver gives you : </b><a href=http://phobos/eq/item.php?id=1179>Silk Coldain Prayer Shawl</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>