<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1416>Trita's Napkin</a><li><a href=http://phobos/eq/item.php?id=1426>Frost Bunny Stew</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1423>Dirty Pot</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=49>Coldain</a><li><a href=http://phobos/eq/faction.php?id=67>Dain Frostreaver IV</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=188>Kromrif</a><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a></ul></td><td><p><b>You give Trita Coldheart : </b><a href=http://phobos/eq/item.php?id=1416>Trita's Napkin</a>, <a href=http://phobos/eq/item.php?id=1426>Frost Bunny Stew</a>
<br><b>Trita Coldheart says </b>'Why thank you, [Your Name], I haven't tasted snow bunny stew this good in quite some time. Be a dear and take this back to Mordin for me.'
<br><b>Trita Coldheart gives you : </b><a href=http://phobos/eq/item.php?id=1423>Dirty Pot</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=49>Coldain</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=67>Dain Frostreaver IV</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten worse.</font>
<p><b>You give Trita Coldheart : </b><a href=http://phobos/eq/item.php?id=1426>Frost Bunny Stew</a>
<br><b>Trita Coldheart says </b>'Thanks for the Snow Bunny Stew, [Your Name].'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=49>Coldain</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=67>Dain Frostreaver IV</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>