<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1725>Velium Delivery Note</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Ungdin says </b>'Uuuuhhh, how goes it, ? Oh, I'm doin' jest fine down here, just hanging around... Mining! Yes mining for our fearless leader, the Dain. Yessiree... sssoooooo...'
<p><b>You give Ungdin : </b><a href=http://phobos/eq/item.php?id=1725>Velium Delivery Note</a>
<br><font color=green><b>Ungdin </b>Hmmm, not sure why you're giving me all this. <cough> 50 pieces <cough> of platinum <cough> Whew, wow, I may be coming down with <cough> and the note <cough> something.</font>
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>