<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>a captured erudite </b>bats her eye lashes seductively.</font>
<br><b>a captured erudite says </b>'I would be immensely pleased if someone would free me from these shackles.'
<p><b>You give a captured erudite : </b>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>