<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2049>rolled up strip of cloth</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Aderius Rhenar says </b>'Hail. [Your Name]. I am Aderius Rhenar. priest of Quellious and assistant to Lady Laraena. I have been fortunate to be imprisoned here with these Kejekan cat men. they are a very wise people. Are you planning on returning to Erudin soon my friend?'
<p><b>You say, </b>'I am planning to return to erudin'
<br><b>Aderius Rhenar says </b>'I have managed to prepare a message on this scrap of cloth for the priestess Laraena. It is a matter of great importance to the High Council of Erudin. Please deliver this message to her promptly. I must stay here for a while longer and converse further with my Kejekan friends.'
<br><b>Aderius Rhenar gives you : </b><a href=http://phobos/eq/item.php?id=2049>rolled up strip of cloth</a>
</td></tr></table>