<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>an erudite prisoner </b>angrily rattles his shackles.</font>
<br><b>an erudite prisoner says </b>'Damned Kobolds!! Some day I will return and these filthy warrens will be littered with their dog faced corpses! You wouldn't happen to have a key for these shackles would you?'
<p><b>You give an erudite prisoner : </b>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>