<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=30861>Saurek Hopper Scales</a><li><a href=http://phobos/eq/item.php?id=30862>Saurek Darkclaw Scales</a><li><a href=http://phobos/eq/item.php?id=30863>Saurek Shredder Scales</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=30870>Hunting Leather Boots</a><li><a href=http://phobos/eq/item.php?id=30867>Hunting Leather Bracer</a><li><a href=http://phobos/eq/item.php?id=30866>Hunting Leather Sleeves</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=132>Guardians of Shar Vahl</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Captain Tarief says </b>'Well met, have you [come to aid] us in hunting the hoppers of the thicket?'
<p><b>You say, </b>'come to aid'
<br><b>Captain Tarief says </b>'If you are preparing to hunt, then there are a few things you should know. Some of the hoppers have unique abilities. Knowledge of these abilities can mean the difference between life and death. I will tell you a little bit about them if you [wish to listen].'
<p><b>You say, </b>'wish to listen'
<br><b>Captain Tarief says </b>'A wise choice, it is good to learn all that you can of the prey before initiating the hunt. Such a tactic is vital when you set out for larger game. Learn of your prey's strengths and weaknesses and you shall have the upper hand. Saureks may all seem similar to one another at first glance, but this is not the case. Such a mistake has left many Taruun dead. I have learned that the darkclaw saureks have venom dripping from their claws. There are a few other [unique qualities] to the saureks as well.'
<p><b>You say, </b>'unique qualities'
<br><b>Captain Tarief says </b>'Each of the saureks have their own unique set of scales. I am able to tell which saurek my trainees have managed to hunt successfully by the scale they return to me. Feel free to join in our lesson or the hunt. I hope that you will benefit from my advice. Hunt well, [Your Name].'
<p><b>You give Captain Tarief : </b><a href=http://phobos/eq/item.php?id=30861>Saurek Hopper Scales</a> x3
<br><b>Captain Tarief gives you : </b><a href=http://phobos/eq/item.php?id=30870>Hunting Leather Boots</a>
<br><b>Captain Tarief says </b>'Excellent work, [Your Name]. Please take this as a reward.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=132>Guardians of Shar Vahl</a> has gotten better.</font>
<p><b>You give Captain Tarief : </b><a href=http://phobos/eq/item.php?id=30862>Saurek Darkclaw Scales</a> x3
<br><b>Captain Tarief gives you : </b><a href=http://phobos/eq/item.php?id=30867>Hunting Leather Bracer</a>
<br><b>Captain Tarief says </b>'Excellent work, [Your Name]. Please take this as a reward.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=132>Guardians of Shar Vahl</a> has gotten better.</font>
<p><b>You give Captain Tarief : </b><a href=http://phobos/eq/item.php?id=30863>Saurek Shredder Scales</a> x3
<br><b>Captain Tarief gives you : </b><a href=http://phobos/eq/item.php?id=30866>Hunting Leather Sleeves</a>
<br><b>Captain Tarief says </b>'Excellent work, [Your Name]. Please take this as a reward.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=132>Guardians of Shar Vahl</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>