<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=30616>Bloody Shak Dratha Heart</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13009>Bandages</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Captain Koldar says </b>'Stand back hunter! Not all of my men are properly trained in the use of their spears. You may find yourself losing an eye if you get too close. Now then, I assume you have [come to help.] Is that correct?'
<p><b>You say, </b>'come to help'
<br><b>Captain Koldar says </b>'Then why are you standing around! Can't you see the invading forces of the Shak Dratha approach our town? Destroy them and bring me four of their bloody hearts as proof of your deed. Snap to it!'
<p><b>You give Captain Koldar : </b><a href=http://phobos/eq/item.php?id=30616>Bloody Shak Dratha Heart</a> x4
<br><b>Captain Koldar says </b>'Well done, hunter.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Captain Koldar gives you : </b><a href=http://phobos/eq/item.php?id=13009>Bandages</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>