<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Captain Alim says </b>'Have you come for training young one?  The way of the Beastlord teaches many things about the forces of nature.  The [forces] in the thicket are very interesting.'
<p><b>You say, </b>'what forces?'
<br><b>Captain Alim says </b>'Yes, the force that compels a creature to adjust to their surroundings in particular.  The Saruek have seem to adapted to their environment very well.  I am studying the effects of their claws.   It seems the different [variety] of Saruek have special enhancements.'
<p><b>You say, </b>'what variety?'
<br><b>Captain Alim says </b>'Well, for example the Firefall Saruek can attack with claws that burn the flesh, the Deathmaw attack with poisonous claws. the shredder Saruek are especially skilled in fending off the Tegi that threaten them, and lastly there is a more uncommon Claw Beast that is very strong but does not appear that often.  I believe I could take their claws and affix them to a weapon to [enhance] it.'
<p><b>You say, </b>'how can you enhance it?'
<br><b>Captain Alim says </b>'If you would like to test this theory go hunt these Saurek.  Bring me three claws each for Deathmaw, Firefall, and Shredder.  Due to the reported size of the Claw Beast I only need his talons.  Along with these claws bring me a wooden practice flail to fasten the claws to.  Go now I have many trainees waiting to be taught.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>