<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4758>Zimloro Ingredient List</a></ul></td><td><hr><b>When Elefan spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Elefan says </b>'Hello, [Your Name]. It's a pleasure to meet you as I do not see many visitors while I am working in the field gathering research.'
<p><b>You say, </b>'research'
<p><b>You say, </b>'take the antidote ingredients'
<p><b>You give Elefan : </b><a href=http://phobos/eq/item.php?id=4758>Zimloro Ingredient List</a>
<br><b>Elefan says </b>'Ah I see you are sent from master Zimloro eh, [Your Name]. This note reads that he needs some specific items at once. Perhaps he could find some use out of all of this research I have recently collected.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>