<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=30618>A Stinking Pile of Refuse</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17890>Scavengers Satchel</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Faer Shahar says </b>'Greetings friend, please mind your [garbage]. They attract the hoppers who can be a danger to our young ones.'
<p><b>You say, </b>'what garbage?'
<br><b>Faer Shahar says </b>'Careless travelers from Shadow Haven leave their rubbish along our roads. They attract vermin and can smell just horrid. I try my best to keep the road clean, but it seems that I cannot keep up with the filth.'
<p><b>You give Faer Shahar : </b><a href=http://phobos/eq/item.php?id=30618>A Stinking Pile of Refuse</a> (x4)
<br><b>Faer Shahar says </b>'Thank you friend, you have done an excellent service for our city. Take this and may it help you on your endeavors.'
<br><b>Faer Shahar gives you : </b><a href=http://phobos/eq/item.php?id=17890>Scavengers Satchel</a>
<br><b>You receive </b> 7cp
</td></tr></table>