<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=31289>Loda Kai Remains</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=7498>Talisman of the Flame</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=132>Guardians of Shar Vahl</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Hymnist Omiyad says </b>'Greetings young one, have a seat by the fire.  You will notice the dance being preformed.  This is much more than just a dance though.  It is a ritual that we preform to [purge] the evil spirits that are plaguing the thicket.'
<p><b>You say, </b>'purge'
<br><b>Hymnist Omiyad says </b>'Lately there has been a surge in the number of Lodi Kai threatening our trade routes.  This ritual is preformed around a fire that burns from their [remains].  Setting their remains in the fire will free their tie with this world and shall ward off their numbers.'
<p><b>You say, </b>'remains'
<br><font color=green><b>Hymnist Omiyad </b>glances toward the fire.</font>
<br><b>Hymnist Omiyad says </b>'I see the fire is dying down some. Should you come across the remains of the Loda Kai bring them to me to keep the ritual fire burning. Bring plenty though, four if you can.'
<p><b>You give Hymnist Omiyad : </b><a href=http://phobos/eq/item.php?id=31289>Loda Kai Remains</a> x4
<br><font color=green><b>Hymnist Omiyad </b>takes the remains and throws them into the fire, flames blaze immediatey with a sicky hue.</font>
<br><b>Hymnist Omiyad says </b>'You have preformed a great service by helping destroy some of the wretched Lodi Kai. Take this small talisman, it is worn by the dancers here. Take it with you and feel free to do a dance whenever you like, haha!'
<br><b>Hymnist Omiyad gives you : </b><a href=http://phobos/eq/item.php?id=7498>Talisman of the Flame</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=132>Guardians of Shar Vahl</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Hymnist Omiyad says </b>'I don't need these items, [Your Name]. You can have them back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>