<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=30619>Payala Fruit</a><li><a href=http://phobos/eq/item.php?id=30625>Sweet Payala Nectar</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=30625>Sweet Payala Nectar</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul></td><td><p><b>You say, </b>'what is Payala?'
<br><b>Saren Kaja says </b>'Payala has the sweetest nectar in all the lands. You can find them throughout the thicket beneath the blue leafed Payala tree. Try some. I have many Payala goodies for sale. I always say, 'the quickest way to someones heart is a freshly baked Payala tart!'''
<p><b>You give Saren Kaja : </b><a href=http://phobos/eq/item.php?id=30619>Payala Fruit</a> (x4)
<br><b>Saren Kaja says </b>'Oh thank you ever so much! You are truly as sweet as the gift you bring.'
<br><b>Saren Kaja gives you : </b><a href=http://phobos/eq/item.php?id=30625>Sweet Payala Nectar</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<p><b>You give Saren Kaja : </b><a href=http://phobos/eq/item.php?id=30619>Payala Fruit</a> (x3), <a href=http://phobos/eq/item.php?id=30625>Sweet Payala Nectar</a> (x2)
<br><b>Saren Kaja says </b>'Oh thank you ever so much! You are truly as sweet as the gift you bring.'
<br><b>Saren Kaja gives you : </b><a href=http://phobos/eq/item.php?id=30625>Sweet Payala Nectar</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
</td></tr></table>