<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Sentry Har Kalaf says </b>'Tread cautiously here. The road to the [paludal] caverns is a dangerous journey these days.'
<p><b>You say, </b>'what paludal?'
<br><b>Sentry Har Kalaf says </b>'The paludal caverns lie to the north, just beyond that copse of blue payala trees. Be careful if you decide to head that way, there are many [dangers] on the road to the north.'
<p><b>You say, </b>'what dangers?'
<br><b>Sentry Har Kalaf says </b>'The spirits have been restless in the northern region. The shak dratha have also been attacking travelers and merchants alike. I hear there is some good hunting within the Paludal caverns, however. The journey may be worth your while.'
</td></tr></table>