<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=30872>A Darkened Jawbone</a><li><a href=http://phobos/eq/item.php?id=30873>A Sharp Toothed Jawbone</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=30879>Rebirth Leather Gloves</a><li><a href=http://phobos/eq/item.php?id=30877>Rebirth Leather Sleeves</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=132>Guardians of Shar Vahl</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Spiritist Karina says </b>'Welcome, friend. Come dance by our warm fire or have a seat and [learn] a little bit about the ways of the spiritist.'
<p><b>You say, </b>'learn'
<br><b>Spiritist Karina says </b>'We are those in tune with the spirits that surround us. Ancestral spirits with knowledge of the ancients dance around us by this very fire. They guide is through the darkness. Protect us from pain. But a terrible [curse] has befallen the spirits of this thicket, and so it is my duty to train these young Dar Khura in order to aid in the battle that lies ahead.'
<p><b>You say, </b>'curse'
<br><b>Spiritist Karina says </b>'The spirits are corrupted by foul magic. The souls of our ancestors have been twisted into an abomination known as [shades]. The corpses of long passed friends and relatives walk through the night seeking to destroy the living. We must destroy the corrupted remains of their old bodies and allow the spirits to roam free once more. Will you help us [release the souls] of our kindred spirits?'
<p><b>You say, </b>'shades'
<br><b>Spiritist Karina says </b>'The shades are a deeper form of corruption of the spirit. I can sense great anguish in the spirits that have been twisted into such a creation. Their horror burns my heart so deeply that I cannot bear it. I would not normally ask another to place themselves in danger, but it is important that the souls are released from these shadowed prisons of torture and darkness. Please help us [release the souls] of our ancestral spirits.'
<p><b>You say, </b>'release the souls'
<br><b>Spiritist Karina says </b>'I am relieved that you have accepted this dangerous task. I can feel the strength of the spirit within you. There are many kindred spirits aiding us in this battle. If you are in tune with the spiritual realm, you will find that your rituals of magic will result in aid from our spiritual allies. Return to me with the [darkened jawbones] of the lesser shades so that I may release the spirit once more.'
<p><b>You say, </b>'darkened jawbones'
<br><b>Spiritist Karina says </b>'The jawbones will aid me in tuning to the essence of the corrupted spirits. When you return to me with them, you are enabling me to place the lost soul to rest. I am able to release four of these spirits at one time in much the same way I am training these four young trainees. It is best to bring me four of them at one time if you are able.'
<br><b>Spiritist Karina says </b>'Always pay attention to your surroundings. There are many opponents that will ambush you while you are out in the field. It is wise to take companions with you when venturing far.'
<p><b>You say, </b>'loda kai'
<br><b>Spiritist Karina says </b>'Loda Kai left Shar Vahl many years ago. He had set off for the distant city of Katta Castellum just north of the tenebrous mountains. We have not seen him since, but the brigands wear his family emblem. [Kedra Kai] has banished himself from our city in shame.'
<p><b>You say, </b>'kendra kai'
<br><b>Spiritist Karina says </b>'He stands vigil at the 
crossroads of the trading routes. Kedra has sworn to destroy the brigands and his brother before returning to Shar Vahl. There are many skeletal brigands within the thicket. If you are able to acquire their rotting jawbones, please bring them to me. I will try to learn what I can from the magic within them.'
<p><b>You give Spiritist Karina : </b><a href=http://phobos/eq/item.php?id=30872>A Darkened Jawbone</a> x4
<br><b>Spiritist Karina says </b>'I can see that you have a brave heart. You have rescued many of the fallen spirits with little regard to your own welfare. Such selfless acts should not go unrewarded. Please take these gloves and wear them with pride. It is a symbol of [rebirth].'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=132>Guardians of Shar Vahl</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Spiritist Karina gives you : </b><a href=http://phobos/eq/item.php?id=30879>Rebirth Leather Gloves</a>
<p><b>You give Spiritist Karina : </b><a href=http://phobos/eq/item.php?id=30873>A Sharp Toothed Jawbone</a> x4
<br><b>Spiritist Karina says </b>'Thank you for bringing these to me [Your Name].'
<br><font color=green><b>Spiritist Karina </b>Karina closes her eyes and meditates over the jawbones for a moment.</font>
<br><b>Spiritist Karina says </b>'I can sense the mark of the [Loda Kai] within these jawbones. This is a horror, for Loda Kai was once a member of my people. I do not know how he came about these strange magical forces but it can not be good news. Please wear these sleeves for protection. This new discovery worries me 
deeply.'
<br><b>Spiritist Karina gives you : </b><a href=http://phobos/eq/item.php?id=30877>Rebirth Leather Sleeves</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=132>Guardians of Shar Vahl</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Spiritist Karina says </b>'I don't want these items, [Your Name]. You can have them back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>