<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=30601>A Needle Thin Claw</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=30617>A Claw Needle</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Tiamon Aroo says </b>'Those wretched vermin swarm to our city and trade routes in search of the refuse left by careless travelers who pass through these parts. They are just about useless and their stench brings bile to my throat. I would have set out to poison the whole lot of them if it was not for their unique [claws].'
<p><b>You say, </b>'claws'
<br><b>Tiamon Aroo says </b>'The claws of the hoppers act as a [spirit anchor]. They are specialized in tearing into the fiber of the shadow beings that roam the thicket. I find these claws useful in binding the silk fashioned by the [shadeweavers].'
<p><b>You say, </b>'shadeweavers'
<br><b>Tiamon Aroo says </b>'The shadeweavers hunt the beings of shadow found within the thicket. From them they fashion their shadow armor they call Xakra. We have tried to use this strong and lightweight armor in the past, but the shadows just disperse. I have found that sewing this armor onto a suitable [spirit anchor] will keep it from dispersing.'
<p><b>You say, </b>'spirit anchor'
<br><b>Tiamon Aroo says </b>'A spirit can only materialize within our realm by binding themselves to an object that is a spirit anchor. Some bones and stones have such properties. A spirit anchor can also do the most damage to the material form of such spirits when used as a weapon. I use the claws of the hoppers as a sewing needle of sorts to [bind the silk] made by the [shadeweavers]. A standard sewing needle would only pass through the substance of the silk. The hopper claws can pierce through their ethereal fabric effectively.'
<p><b>You say, </b>'bind the silk'
<br><b>Tiamon Aroo says </b>'A spirit must be bound to material from our own realm. Stones such as those used to build cities can be great anchors for spirits. The more ritual and culture that a stone is exposed to, the stronger it becomes as an anchor. You can use the claws of a hopper to sew the shadeweavers silk onto a suitable anchor. If you bring me four of these claws, I can fashion one of them into a needle for you.'
<p><b>You give Tiamon Aroo : </b><a href=http://phobos/eq/item.php?id=30601>A Needle Thin Claw</a> x4
<br><b>Tiamon Aroo says </b>'Well done! You have brought me plenty of claws. I have enough now to make a needle for you. May it serve you well.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Tiamon Aroo gives you : </b><a href=http://phobos/eq/item.php?id=30617>A Claw Needle</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>