<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Trainee Paelin says </b>'It is an honor to meet a fellow hunter. I am training to learn how to hunt down the [saurek] that roam the thicket. It is our duty as taruun to provide food for our kin. I plan on claiming captain Tarief's [reward].'
<p><b>You say, </b>'what saurek?'
<br><b>Trainee Paelin says </b>'The Saurek hoppers are far more aggressive than the needle clawed hoppers. We must hunt them down and kill them lest they attack our families and traders that wander through these thickets. They have many uses to us as well. Their meat gives us food to eat, and their hides make strong protective armor.'
<p><b>You say, </b>'what reward?'
<br><b>Trainee Paelin says </b>'Captain Tarief has offered to reward those that slay four of the saurek hoppers. You must return four of their scales to him as proof of your deeds to claim the reward. I hope to bring honor to my family by returning home with such a trophy.'
</td></tr></table>