<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12157>Aviak Chick Talon</a><li><a href=http://phobos/eq/item.php?id=12158>Aviak Talon</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2118>Small Patchwork Cloak</a><li><a href=http://phobos/eq/item.php?id=2120>Small Patchwork Sleeves</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=44>Clerics of Underfoot</a><li><a href=http://phobos/eq/faction.php?id=169>Kazon Stormhammer</a><li><a href=http://phobos/eq/faction.php?id=219>Miners Guild 249</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Bumle Reminjar says </b>'Welcome, [Your Name].  The Cathedral of Underfoot welcomes all good persons.  May you find peace from the dangers of Butcherblock within these walls.  The paladins of this holy place are very much aware of the evils outside Kaladim.  The threat of goblins and [birdmen] has increased.'
<p><b>You say, </b>'what birdmen'
<br><b>Bumle Reminjar says </b>'The birdmen I speak of are the aviak krags.  These vile creatures have desecrated our land.  They have dared to perch upon our great statue.  The king has instructed all noble paladins in this order to [destroy the krag chicks].'
<p><b>You say, </b>'i want to destroy the krag chicks'
<br><b>Bumle Reminjar says </b>'Yes.  You are known to have aided our cause.  You shall continue by returning any aviak chick talons to me.  I will reward you for the return of no fewer than four at a time.  Go, and serve the will of the king!'
<p><b>You give Bumle Reminjar : </b><a href=http://phobos/eq/item.php?id=12157>Aviak Chick Talon</a> x4
<br><b>Bumle Reminjar says </b>'Well done, [Your Name]! Thanks for the Aviak Chick Talons.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=44>Clerics of Underfoot</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=169>Kazon Stormhammer</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=219>Miners Guild 249</a> has gotten better.</font>
<br><b>Bumle Reminjar gives you : </b><a href=http://phobos/eq/item.php?id=2118>Small Patchwork Cloak</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Bumle Reminjar says </b>'You have proven yourself worthy, [Your Name]. Now, the real threat from the birdmen are the more fully-grown aviaks. Return no less than four talons from these creatures and I shall reward you!'
<p><b>You give Bumle Reminjar : </b><a href=http://phobos/eq/item.php?id=12157>Aviak Chick Talon</a> x4
<br><b>Bumle Reminjar says </b>'Well done, [Your Name]! Thanks for the Aviak Chick Talons.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=44>Clerics of Underfoot</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=169>Kazon Stormhammer</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=219>Miners Guild 249</a> has gotten better.</font>
<br><b>Bumle Reminjar gives you : </b><a href=http://phobos/eq/item.php?id=2120>Small Patchwork Sleeves</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Bumle Reminjar says </b>'You have proven yourself worthy, [Your Name]. Now, the real threat from the birdmen are the more fully-grown aviaks. Return no less than four talons from these creatures and I shall reward you!'
<p><b>You give Bumle Reminjar : </b><a href=http://phobos/eq/item.php?id=12158>Aviak Talon</a> x4
<br><b>Bumle Reminjar says </b>'Ahh! you are truly brave, [Your Name]!'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=44>Clerics of Underfoot</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=169>Kazon Stormhammer</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=219>Miners Guild 249</a> has gotten better.</font>
<br><b>You receive </b> 2pp 5gp 4sp
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>