<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Diggins says </b>'How is life treating you, bud?  What are you doing around the mines?  Either you are a [member of 628] or you are lost.  If you are lost, I can't help you.  I ain't no guide.'
<p><b>You say, </b>'i am a member of 628'
<br><b>Diggins says </b>'Don't take this personally,  but I can't quite trust you with such matters.  Maybe a few less Butcherblock bandits would prove your worth.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>