<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13071>Rat Whiskers</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=314>Storm Guard</a><li><a href=http://phobos/eq/faction.php?id=169>Kazon Stormhammer</a><li><a href=http://phobos/eq/faction.php?id=219>Miners Guild 249</a><li><a href=http://phobos/eq/faction.php?id=215>Merchants of Kaladim</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=57>Craknek Warriors</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Exterminator Vin says </b>'Hello, I be Vin the Exterminator. I am here to get rid of these darn rodents that are plaguing our town. If ya would like to make a small bit of coin, perhaps you could help me. Hunt down some rodents and bring me four of their whiskers.  If yer not too busy, that is.'
<p><b>You give Exterminator Vin : </b><a href=http://phobos/eq/item.php?id=13071>Rat Whiskers</a> x4
<br><b>Exterminator Vin says </b>'Ah ya have returned. Nice work. You might consider a career in vermin extermination yourself!'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=314>Storm Guard</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=169>Kazon Stormhammer</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=219>Miners Guild 249</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=215>Merchants of Kaladim</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=57>Craknek Warriors</a> has gotten worse.</font>
<br><b>You receive </b> 1gp 1sp 1cp
</td></tr></table>