<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>Founy Jestands says </b>'Hello. I am the guildmaster.'
<p><b>You say, </b>'note'
<br><font color=green><b>Founy Jestands </b>fingers his belt pouch.</font>
<br><b>Founy Jestands says </b>'I don't know what you're talking about, if you know what I mean. You should leave now, if you know what's good for you. Don't make me sic the crew on you.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>