<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=55470>Scalded Rat Skin</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=55492>Stonewrath Chain Assembly Kit</a><li><a href=http://phobos/eq/item.php?id=55488>Stonewrath Boot Mold</a><li><a href=http://phobos/eq/item.php?id=55486>Stonewrath Bracer Mold</a><li><a href=http://phobos/eq/item.php?id=55485>Stonewrath Coif Mold</a><li><a href=http://phobos/eq/item.php?id=55490>Stonewrath Gloves Mold</a><li><a href=http://phobos/eq/item.php?id=55487>Stonewrath Gorget Mold</a><li><a href=http://phobos/eq/item.php?id=55489>Stonewrath Leggings Mold</a><li><a href=http://phobos/eq/item.php?id=55491>Stonewrath Tunic Mold</a><li><a href=http://phobos/eq/item.php?id=55493>Stonewrath Axe</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Goriba Thurgorson </b>scratches her beard.</font>
<br><b>Goriba Thurgorson says </b>'What do we have here? A young [berserker] perhaps seeking fame and glory?'
<p><b>You say, </b>'berserker'
<br><b>Goriba Thurgorson says </b>'To be honest, I do not think that fame and glory will become yours so soon, but I can instruct you on how to make a helpful set of armor if you are [interested].'
<p><b>You say, </b>'interested'
<br><b>Goriba Thurgorson says </b>'Take this assembly kit. With this kit, you will be able to combine the various components necessary to make your armor. I can instruct you on how to make [boots], [bracer], [coif], [gloves], [gorget], [leggings], or a [tunic]. I suggest you wait to make the tunic last, as it is the most difficult item to construct.'
<br><b>Goriba Thurgorson gives you : </b><a href=http://phobos/eq/item.php?id=55492>Stonewrath Chain Assembly Kit</a>
<p><b>You say, </b>'boots'
<br><b>Goriba Thurgorson says </b>'To make Stonewrath boots, you must obtain two small pieces of ore, one aviak eye, and one pristine skunk claws. You should able to find the animal parts in the Butcherblock Mountains and the ore somewhere here in town. Once you have combined these items in your assembly kit, take the Stonewrath Boots Material to a forge along with this mold to create your new boots.'
<br><b>Goriba Thurgorson gives you : </b><a href=http://phobos/eq/item.php?id=55488>Stonewrath Boot Mold</a>
<p><b>You say, </b>'bracer'
<br><b>Goriba Thurgorson says </b>'To make a Stonewrath Bracer, you must obtain one small piece of ore, one bat wing, and two bone chips. You should be able to find the animal parts in the Butcherblock Mountains and the ore somewhere here in town. Once you have combined these items in you assembly kit, take the Stonewrath Bracer Material to a forge along with this mold to create your new bracer.'
<br><b>Goriba Thurgorson gives you : </b><a href=http://phobos/eq/item.php?id=55486>Stonewrath Bracer Mold</a>
<p><b>You say, </b>'coif'
<br><b>Goriba Thurgorson says </b>'To make a Stonewrath Coif, you must obtain two small pieces of ore, one goblin brain, one bone chips, and one giant bat wing. You should be able to find the animal parts in the Butcherblock Mountains and the ore somewhere here in town. Once you have combined these items in your assembly kit, take the Stonewrath Coif Material to a forge along with this mold to create your new coif.'
<br><b>Goriba Thurgorson gives you : </b><a href=http://phobos/eq/item.php?id=55485>Stonewrath Coif Mold</a>
<p><b>You say, </b>'gloves'
<br><b>Goriba Thurgorson says </b>'To make Stonewrath Gloves, you must obtain one small piece of ore, one aviak eye, and two bone chips. You should be able to find the animal parts in the Butcherblock Mountains and the ore somewhere here in town. Once you have combined these items in your assembly kit, take the Stonewrath Gloves Material to a forge along with this mold to create your new gloves.'
<br><b>Goriba Thurgorson gives you : </b><a href=http://phobos/eq/item.php?id=55490>Stonewrath Gloves Mold</a>
<p><b>You say, </b>'gorget'
<br><b>Goriba Thurgorson says </b>'To make a Stonewrath Gorget, you must obtain one small piece of ore, one bat wing, two bone chips, and one skunk tail. You should be able to find the animal parts in the Butcherblock Mountains and the ore somewhere here in town. Once you have combined these items in your assembly kit, take the Stonewrath Gorget Material to a forge along with this mold to create your new gorget.'
<br><b>Goriba Thurgorson gives you : </b><a href=http://phobos/eq/item.php?id=55487>Stonewrath Gorget Mold</a>
<p><b>You say, </b>'leggings'
<br><b>Goriba Thurgorson says </b>'To make Stonewrath Leggings, you must obtain two small pieces of ore, one RunnyEye warbeads, and one spiderling silk. You should be able to find the animal parts in the Butcherblock Mountains and the ore somewhere here in town. Once you have combined these items in your assembly kit, take the Stonewrath Leggings Material to a forge along with this mold to create your new leggings.'
<br><b>Goriba Thurgorson gives you : </b><a href=http://phobos/eq/item.php?id=55489>Stonewrath Leggings Mold</a>
<p><b>You say, </b>'tunic'
<br><b>Goriba Thurgorson says </b>'To make a Stonewrath Tunic, you must obtain two small pieces of ore, two goblin brains, one giant bat fur, and one snake fang. You should be able to find the animal parts in the Butcherblock Mountains and the ore somewhere here in town. Once you have combined these items in your assembly kit, take the Stonewrath Tunic Material to a forge along with this mold to create your new tunic. Once you have made your tunic, return to me and I may have another [task] for you to complete.'
<br><b>Goriba Thurgorson gives you : </b><a href=http://phobos/eq/item.php?id=55491>Stonewrath Tunic Mold</a>
<p><b>You say, </b>'task'
<br><b>Goriba Thurgorson says </b>'Venture to the nearby Dagnor's Cauldron and find four scalded rat skins. Once you have these items, return to me and I will reward you.'
<p><b>You give Goriba Thurgorson : </b><a href=http://phobos/eq/item.php?id=55470>Scalded Rat Skin</a> x4
<br><b>Goriba Thurgorson says </b>'I see you have embraced the rage burning from within and have accomplished your task. Take this axe as a reward.'
<br><b>Goriba Thurgorson gives you : </b><a href=http://phobos/eq/item.php?id=55493>Stonewrath Axe</a>
</td></tr></table>