<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13073>Bone Chips</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2116>Small Patchwork Tunic</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=10803></a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Gunlok Jure says </b>'Hail, [Your Name]!  Bow before the greatness of the Clerics of Underfoot!  It is good to be a paladin in such an order as ours - to fight the good fight and defend Kaladim from the evil and undead.  If you be a paladin, then I pray you find the [courage] to battle the undead.'
<p><b>You say, </b>'courage'
<br><b>Gunlok Jure says </b>'Yes!!  To battle the undead is our greatest call.  There has been a rise in the number of dwarven skeletons seen in the Butcherblocks.  If you are a true member of this order. I shall reward you for the return of four bone chips.  We shall defend our land from evil!'
<p><b>You give Gunlok Jure : </b><a href=http://phobos/eq/item.php?id=13073>Bone Chips</a> x4
<br><b>Gunlok Jure says </b>'You have done well.  We thank you for your deed with this humble reward.  The power behind the raising of our dead shall soon be found.  You will earn more respect with more bone chips.  I only wish you could assist in the return of the [remains] of Cromil.'
<br><b>Gunlok Jure gives you : </b><a href=http://phobos/eq/item.php?id=2116>Small Patchwork Tunic</a>
<br><b>You receive </b> 10sp 7cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=10803></a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>