<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=29007>cold plate of beef and bread</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=29006>Pure Crystal</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Jark </b>strikes the wall with his pick. A clacking sound echoes through the cave. 'Har har. There's something all right.'</font>
<p><b>You say, </b>'something'
<br><b>Jark says </b>'Huh? Oh, I struck me some silver. Ain't gonna make me rich but it'll sure pay for me minin' costs. Speakin of, that wife o' mine was supposed ta bring me food already. Hey, you, wanna go get me my dinner? I ain't got nothing ta pay ya with but I sure would appreciate it.'
<p><b>You say, </b>'dinner'
<br><b>Jark says </b>'Har, I know you were a good sort. Nella has it. She's out there somewhere in the lower areas. She likes to visit the temple, so maybe she's there. Just tell 'er Jark sent ya and she'll prolly have everythin' ready fer me.'
<p><b>You give Jark : </b><a href=http://phobos/eq/item.php?id=29007>cold plate of beef and bread</a>
<br><b>Jark says </b>'Har, har! No time fer eatin' now! While you were gone I struck me a rich vein. Lookie here! Ya ever seen a gem so pure? It's tiny but clear as glass. Ya take it, [Your Name]. Ya showed me some kindness, least I can do. Besides, still a share here for me.'
<br><b>Jark gives you : </b><a href=http://phobos/eq/item.php?id=29006>Pure Crystal</a>
</td></tr></table>