<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Jeet says </b>'What business do you have here?!!  This here is the mine and that means if you ain't a [member of Miner's Guild 628], you'd best be moving on!!'
<p><b>You say, </b>'i am a member of miner'
<br><b>Jeet says </b>'Don't take this personally,  but I can't quite trust you with such matters.  Maybe a few less Butcherblock bandits would prove your worth.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>