<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10952>Small Shipment of High Quality Ore</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'Hail, [Your Name]. The Mining Journal has all the news fit fer dwarven eyes to feast upon.'
<p><b>You say, </b>'what run an errand'
<p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'Hail, [Your Name]. The Mining Journal has all the news fit fer dwarven eyes to feast upon.'
<p><b>You give Not Found : </b><a href=http://phobos/eq/item.php?id=10952>Small Shipment of High Quality Ore</a>
<br><b>You receive </b> 14pp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
</td></tr></table>