<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Nultal Malfoot says </b>'May the power of Underfoot be with you.  Welcome.  I am here to serve the will of the king as should you.  If you [need healing]. then speak.  Or perhaps you are here to [return skunk glands]?'
<p><b>You say, </b>'i need healing'
<br><b>Nultal Malfoot says </b>'Before the power of Underfoot can attempt to bind your wounds you must pay tribute.  Three gold coins!!'
<p><b>You say, </b>'i want to return skunk glands'
<br><b>Nultal Malfoot says </b>'I have made an offer to all clerics of this cathedral.  I shall reward one cleric scroll from our scribes for the return of four skunk scent glands.  This offer is best left to our clerics.'
</td></tr></table>