<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18765>Dirt Covered Letter</a><li><a href=http://phobos/eq/item.php?id=12106>Fairy Dust</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13514>Dusty Tunic*</a><li><a href=http://phobos/eq/item.php?id=12282>Soil of Underfoot</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=44>Clerics of Underfoot</a><li><a href=http://phobos/eq/faction.php?id=169>Kazon Stormhammer</a><li><a href=http://phobos/eq/faction.php?id=219>Miners Guild 249</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Priestess Ghalea says </b>'Welcome to the Church of Underfoot.  Please open your soul to the greatness of Brell Serilis.  May he guide you in all your future endeavors. And may your soles long for the [Soil of Underfoot].'
<p><b>You say, </b>'soil of underfoot'
<br><b>Priestess Ghalea says </b>'I can trust you with the soil of Underfoot, but first you must obtain four portions of fairy dust.  Return them to me and I shall mix it and pray over it. Then I shall give you a pouch of soil of Underfoot.'
<p><b>You give Priestess Ghalea : </b><a href=http://phobos/eq/item.php?id=18765>Dirt Covered Letter</a>
<br><b>Priestess Ghalea says </b>'Welcome to the Underfoot Cathedral. I am High Priestess Ghalea. Here is your guild tunic. Now. let's get you started helping us spread the will of Brell.'
<br><b>Priestess Ghalea gives you : </b><a href=http://phobos/eq/item.php?id=13514>Dusty Tunic*</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=44>Clerics of Underfoot</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=169>Kazon Stormhammer</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=219>Miners Guild 249</a> has gotten better.</font>
<p><b>You give Priestess Ghalea : </b><a href=http://phobos/eq/item.php?id=12106>Fairy Dust</a> x4
<br><b>Priestess Ghalea says </b>'May the mighty power of Brell saturate this soil with his divinity.  Here you are, my noble friend.  You may have a pouch of the soil of Underfoot.'
<br><b>Priestess Ghalea gives you : </b><a href=http://phobos/eq/item.php?id=12282>Soil of Underfoot</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=44>Clerics of Underfoot</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=169>Kazon Stormhammer</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=219>Miners Guild 249</a> has gotten better.</font>
<br><b>Priestess Ghalea says </b>'I do not need this, friend.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>