<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12114>Tumpy Tonic</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12111>Dwarven Wire</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Trantor Everhot says </b>'Yes, yes!! I am a very busy man. I've got blueprints to work on, [dwarven wire] to perfect and formulae to calculate. In between those tasks, I have to find time to head down to Irontoe's and down a few Tumpy Tonics.'
<p><b>You say, </b>'what dwarven wire'
<br><b>Trantor Everhot says </b>'Oh!! Interested in my dwarven wire, are you? Many are. I have no problem letting you use a spool, but I have to warn you that I have not perfected the strength of it yet. I will make you a trade. A couple of [Tumpy Tonics] for a spool.'
<p><b>You say, </b>'what tumpy tonics'
<br><b>Trantor Everhot says </b>'Aaah!! I love Tumpy Tonics. They were created by Tumpy Irontoe. He was once a member of the famed Irontoe Brigade. Since they disbanded and left for parts unknown he decided to stay in Kaladim and open Irontoe's, the finest well in Faydwer.'
<p><b>You give Trantor Everhot : </b><a href=http://phobos/eq/item.php?id=12114>Tumpy Tonic</a>
<br><b>Trantor Everhot says </b>'Hey!! Only one?!!'
<p><b>You give Trantor Everhot : </b><a href=http://phobos/eq/item.php?id=12114>Tumpy Tonic</a> (x2)
<br><b>Trantor Everhot says </b>''Aaah!! I love Tumpy Tonics. They were created by Tumpy Irontoe. He was once a member of the famed Irontoe Brigade. Since they disbanded and left for parts unknown he decided to stay in Kaladim and open Irontoe's, the finest well in Faydwer.'
<br><b>Trantor Everhot gives you : </b><a href=http://phobos/eq/item.php?id=12111>Dwarven Wire</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>