<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20533>Torch of Ro</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20534>Torch of Rathe</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Andad Filla says </b>'Hello traveler, please do not bother me right now; I am waiting for someone.'
<p><b>You give Andad Filla : </b><a href=http://phobos/eq/item.php?id=20533>Torch of Ro</a>
<br><b>Andad Filla says </b>'You still have a ways to go! Seek out Misty Tekcihta near the arena at Lake Rathe. Run like the wind!'
<br><b>Andad Filla gives you : </b><a href=http://phobos/eq/item.php?id=20534>Torch of Rathe</a>
</td></tr></table>