<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12348>Gem of Stamina</a><li><a href=http://phobos/eq/item.php?id=12349>A Sparkling Sapphire</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=7041>Burning Rapier</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=442>Temple Of Sol Ro</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=291>Shadowed Men</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Ortallius says </b>'Welcome to the lands of Ro.  Stand and fight with me.  We shall fight to reclaim the desert in the name of Solusek Ro.  Death to all [dervish cutthroats]!!'
<p><b>You give Ortallius : </b><a href=http://phobos/eq/item.php?id=12348>Gem of Stamina</a>, <a href=http://phobos/eq/item.php?id=12349>A Sparkling Sapphire</a>
<br><b>Ortallius says </b>'You serve the Burning Prince as I do. The Redeemed has instructed me to give you this reward upon completion of your test. Practice your arts and prepare yourself. Evil approaches our realm. Long live Ro!!'
<br><b>Ortallius gives you : </b><a href=http://phobos/eq/item.php?id=7041>Burning Rapier</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=442>Temple Of Sol Ro</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=291>Shadowed Men</a> has gotten worse.</font>
<br><b>You receive </b> 4pp
<br><b>Ortallius says </b>'I was instructed to wait for two gems.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>