<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Adept Delf says </b>'Should you decide to leave the House Fordel. make sure you stock up on plenty of these basic but important items to aid you in your journey.'
<br><b>Adept Delf says </b>'Due to the problems we have had lately with dishonorable visitors to the Haven we require all newcomers to see Daloran and Mistala for some simple tasks to prove that your intentions are good. I hope to see you soon.'
</td></tr></table>