<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Akeral says </b>'Hello [Your Name]. our shop specializes in literature for different types of trade skills. If you have some information that you would like to share. please let me know.'
<br><b>Akeral says </b>'Due to the problems we have had lately with dishonorable visitors to the Haven we require all newcomers to see Daloran and Mistala for some simple tasks to prove that your intentions are good. I hope to see you soon.'
</td></tr></table>