<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4756>Letter to Aliane</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=154>House of Stout</a><li><a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Aliane Steelknuckle says </b>'Hello, [Your Name]. I'm waiting to hear from my husband. He's been working on assignment for the Patriarch.'
<p><b>You give Aliane Steelknuckle : </b><a href=http://phobos/eq/item.php?id=4756>Letter to Aliane</a>
<br><b>Aliane Steelknuckle says </b>'Oh my sweet Daosorak, such a hard worker he is. It brings a smile upon my face to know that his mining operation is going well and that he will be home soon. I thank you for bringing me this letter from him.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=154>House of Stout</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>