<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Alorob Bolrodo says </b>'You seem like a nice enough stranger but I am afraid all newcomers must see the Patriarch first before we are able to offer our great deals to them.'
<br><b>Alorob Bolrodo says </b>'Hello there [Your Name]! I sell all of the finest vegetables that are grown here in the Haven.'
</td></tr></table>