<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Bailes says </b>'Ho there. [Your Name]. Thinking about picking up a trusty weapon to aid you in the treacherous depths of the Paludal Caverns?  Then you're in luck 'cause I have a few for sale right here!'
<br><b>Bailes says </b>'Due to the problems we have had lately with dishonorable visitors to the Haven we require all newcomers to see Daloran and Mistala for some simple tasks to prove that your intentions are good. I hope to see you soon.'
</td></tr></table>