<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Barkeep Veronica says </b>'Greetings my friend. we have many drinks available here at the Knights Table. If I do not have the specific drink for your taste please let me know and I will try my best to make it for you.'
<br><b>Barkeep Veronica says </b>'Due to the problems we have had lately with dishonorable visitors to the Haven we require all newcomers to see Daloran and Mistala for some simple tasks to prove that your intentions are good. I hope to see you soon.'
</td></tr></table>