<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4770>Book of Ancient Scribings</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=4769>Seal of Beriol</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=153>House of Midst</a><li><a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Beriol Talorakoir says </b>'Hail, [Your Name]. And good day to you. What brings you to my quarters today? Do you wish to learn more about the [magic] that we study in our hallowed section of the Shadowhaven?'
<p><b>You say, </b>'magic'
<br><b>Beriol Talorakoir says </b>'It's always a pleasure to meet someone that shows interest in the magic we practice here. Our magic studies consist mostly of teleportation and the arts of elemental mastery. I'm Actually conducting a study now, but I' missing a few [books].'
<p><b>You say, </b>'books'
<br><b>Beriol Talorakoir says </b>'Well, I have an old student that is now serving as an advisor to one of the most respected residents of Katta Castelleum. He has some specific books that i need to further my research, but i cannot take the time to travel so far away from my home to retrieve them. I seek out one who will [bring my research] to me from Dersino.'
<p><b>You say, </b>'bring your research'
<br><b>Beriol Talorakoir says </b>'You are exactly the one I am looking for. After presenting this seal to Dersino, inform him that you wish to take the research and I am sure that he will know i have sent you. I loook forward to seeing you soon.'
<br><b>Beriol Talorakoir gives you : </b><a href=http://phobos/eq/item.php?id=4769>Seal of Beriol</a>
<p><b>You give Beriol Talorakoir : </b><a href=http://phobos/eq/item.php?id=4770>Book of Ancient Scribings</a>
<br><b>Beriol Talorakoir says </b>'This is exactly the research book that I was in need of. I am very thankful for you getting these for me. Should you ever feel up to it again in the future Dersino always is getting new books in that could be very helpful in my studies. Again, I thank you and wish you the best of luck.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=153>House of Midst</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>