<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=4747>Bag of Rations</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Coglixar Xorlopodil says </b>'Hello there, [Your Name]. It's nice to meet you. Are you just passing through our fine city or do you have dealings you need to address to me personally? Also, if ye know anyone that will want to assist with some deliveries to our mining contingent in the Paludal caverns let me know.'
<p><b>You say, </b>'assist'
<br><b>Coglixar Xorlopodil says </b>'That is great to hear, [Your Name]. I have a task for you to complete for me first and if you are able to complete it I may have other things for you in the future. I have heard word that some of our dwarf workers in the [mining operation] are in need of some food.'
<p><b>You say, </b>'mining operation'
<br><b>Coglixar Xorlopodil says </b>'In the Paludal caverns our workers are starting to get very low on rations and are working with very old and tarnished mining utensils. I need you to deliver these rations to Daesorak first and then see what supplies he thinks they need. He is the one overseeing the operation and will be able to tell you what supplies he needs and what quanity is necessary.'
<br><b>Coglixar Xorlopodil gives you : </b><a href=http://phobos/eq/item.php?id=4747>Bag of Rations</a>
</td></tr></table>