<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4762>Gemmed Sword Hilt</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=4762>Gemmed Sword Hilt</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Daloran Glimmerblade says </b>'Greetings, [Your Name], I am Lord Daloran Glimmerblade. I reside over the Fordel section of the Haven with my dear Mistala. I have not ever seen you around these parts so I would imagine you are a [newcomer] to our great city.'
<p><b>You say, </b>'newcomer'
<br><b>Daloran Glimmerblade says </b>'Excellent, [Your Name]. It's nice to have you here as a guest. I am very proud of all that we have accomplished here and invite you to make yourself at home when you are with us. If you wish to further [prove your allegiance] to the House of Fordel I may have some tasks for you to complete.'
<p><b>You say, </b>'prove my allegiance'
<br><b>Daloran Glimmerblade says </b>'Ah that is excellent to hear, [Your Name]. I believe I have a task that I could entrust you with. I have numerous Gemmed sword hilts that I have yet to attach to a blade. They have all been glowing for quite some time with an [unknown force]. All of my residing magicians and enchanters have been unable to decifer the magics that surround these hilts.'
<p><b>You say, </b>'unknown force'
<br><b>Daloran Glimmerblade says </b>'I wish that I was able to discover this myself. Unfortunately, not one person in my quarter possesses such identification powers. However, I do have a [friend] in Katta Castellum that specializes in discovering such magical origins.'
<p><b>You say, </b>'friend'
<br><b>Daloran Glimmerblade says </b>'Yaeorat is who I speak of, he is a very trusted and old friend of mine that is a very powerful and skillfull enchanter. Will you bring to him the [Gemmed sword hilt]? I feel that if anyone will be able to identify this it will be Yaeorat.'
<p><b>You say, </b>'gemmed sword hilt'
<br><b>Daloran Glimmerblade says </b>'That is great to hear, [Your Name], here is the hilt. Please go see Yaeorat at once and bring me news about the magic that surrounds this sword hilt good or bad.'
<br><b>Daloran Glimmerblade gives you : </b><a href=http://phobos/eq/item.php?id=4762>Gemmed Sword Hilt</a>
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<p><b>You give Daloran Glimmerblade : </b><a href=http://phobos/eq/item.php?id=4762>Gemmed Sword Hilt</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>