<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Darian Shallowsong says </b>'Hello [Your Name]. it seems that you have caught me relaxing a bit on my off time at the tavern here. No matter. though if you are a bard in need of assistance. just let me know and we will get right to work.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>