<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Eiles says </b>'If you're planning on travelling through the Paludal Caverns. make sure you pick up a torch. [Your Name]. Those caverns are quite confusing and you don't want to find yourself lost in the dark.'
<br><b>Eiles says </b>'Due to the problems we have had lately with dishonorable visitors to the Haven we require all newcomers to see Daloran and Mistala for some simple tasks to prove that your intentions are good. I hope to see you soon.'
</td></tr></table>