<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Ferusal says </b>'Nice to meet you stranger. I have various books on the skill of tailoring.  Feel free to take a look if you are interested.'
<br><b>Ferusal says </b>'Due to the problems we have had lately with dishonorable visitors to the Haven we require all newcomers to see Daloran and Mistala for some simple tasks to prove that your intentions are good. I hope to see you soon.'
</td></tr></table>