<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Garon Battlehand says </b>'Hello there. [Your Name]. I am responsible for all of the newly recruited Defenders of the Haven. I make sure that our soldiers are trained well and ready for any conflict that may present itself. All of those that pass though my training exercises are sure to be the best of the best.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>