<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Gelson says </b>'Greetings. friend. If you ever consider trying to pick up tailoring. I have a lot of information that you might find interesting- take a look.'
<br><b>Gelson says </b>'Due to the problems we have had lately with dishonorable visitors to the Haven we require all newcomers to see Daloran and Mistala for some simple tasks to prove that your intentions are good. I hope to see you soon.'
</td></tr></table>