<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=4757>Hardams Box of Goods</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Hardam Stonegrinder says </b>'In need of some ores or other mining supplies? Well step right up. I got everything ye could possibly need! Also I'll have more supplies coming in as soon as I can get some dern time to deliver my [payment] to the commissioner.'
<p><b>You say, </b>'what payment='
<br><b>Hardam Stonegrinder says </b>'Well ya see mate I have a representative of me great mining business here that is currently in the bazaar. however I got some new things I need him to sell but I can't leave me shop! I just need to get these new [items] to him so that he can sell them.'
<br><b>Hardam Stonegrinder says </b>'Well ya see mate I have a representative of me great mining business here that is currently in the bazaar. however I got some new things I need him to sell but I can't leave me shop! I just need to get these new [items] to him so that he can sell them.'
<p><b>You say, </b>'what items?'
<br><b>Hardam Stonegrinder says </b>'Well da usual items ya know. I gets a lot of different goods in here every day and it is important that I move em out as fast as possible when they worth more ya knows? If ye lewkin for a [task] I've heard about ye around town and ye seem to be a trustworthy person.'
<p><b>You say, </b>'what task?'
<br><b>Hardam Stonegrinder says </b>'I'm simply lookin for someone to take me box of [goods] here to my friend in the bazaar. his name is Faeroi and he will know what to do with them.'
<p><b>You say, </b>'I will take the goods'
<br><b>Hardam Stonegrinder says </b>'I thank ya for your willingness to help. [Your Name]. Here is the box of the different things I need taken to Faeroi. When I spoke to him before he left for the bazaar this morning he told me that the helm that I had been having customized was ready. I have enclosed a note for him to give that to you to return to me. I look forward to seeing you soon.'
<br><b>Hardam Stonegrinder gives you : </b><a href=http://phobos/eq/item.php?id=4757>Hardams Box of Goods</a>
<p><b>You say, </b>'what payment'
<br><b>Hardam Stonegrinder says </b>'Well ya see mate I have a representative of me great mining business here that is currently in the bazaar. however I got some new things I need him to sell but I can't leave me shop! I just need to get these new [items] to him so that he can sell them.'
<p><b>You say, </b>'i will take the box of goods'
<br><b>Hardam Stonegrinder says </b>'I thank ya for your willingness to help. [Your Name]. Here is the box of the different things I need taken to Faeroi. When I spoke to him before he left for the bazaar this morning he told me that the helm that I had been having customized was ready. I have enclosed a note for him to give that to you to return to me. I look forward to seeing you soon.'
<br><b>Hardam Stonegrinder gives you : </b><a href=http://phobos/eq/item.php?id=4757>Hardams Box of Goods</a>
<p><b>You say, </b>'i can take the box of goods'
<br><b>Hardam Stonegrinder says </b>'I thank ya for your willingness to help. [Your Name]. Here is the box of the different things I need taken to Faeroi. When I spoke to him before he left for the bazaar this morning he told me that the helm that I had been having customized was ready. I have enclosed a note for him to give that to you to return to me. I look forward to seeing you soon.'
<br><b>Hardam Stonegrinder gives you : </b><a href=http://phobos/eq/item.php?id=4757>Hardams Box of Goods</a>
</td></tr></table>