<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Kelly Blackhand says </b>'Due to the problems we have had lately with dishonorable visitors to the Haven we require all newcomers to see Daloran and Mistala for some simple tasks to prove that your intentions are good. I hope to see you soon.'
<br><b>Kelly Blackhand says </b>'Hello. and welcome to our shop! If there is something you should need for any of your smithing needs. you've come to the right place!'
</td></tr></table>