<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Lander Furthers says </b>'Greetings [Your Name]. if you are an aspiring brewer. I have just the tools for the trade. Take a look!'
<br><b>Lander Furthers says </b>'Due to the problems we have had lately with dishonorable visitors to the Haven we require all newcomers to see Daloran and Mistala for some simple tasks to prove that your intentions are good. I hope to see you soon.'
</td></tr></table>