<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Meribeth says </b>'Need some padding to cushion those blows. [Your Name]? I have some armor that I just got in that may be to your liking. Have a look!'
<br><b>Meribeth says </b>'Due to the problems we have had lately with dishonorable visitors to the Haven we require all newcomers to see Daloran and Mistala for some simple tasks to prove that your intentions are good. I hope to see you soon.'
</td></tr></table>