<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Narsam says </b>'Hello [Your Name]. and welcome to our general store. I sell some of the finest weapons that used to be only crafted for the Fordel soldiers. however now you can have one for your very own. For a price. of course.'
<br><b>Narsam says </b>'Due to the problems we have had lately with dishonorable visitors to the Haven we require all newcomers to see Daloran and Mistala for some simple tasks to prove that your intentions are good. I hope to see you soon.'
</td></tr></table>