<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Nicoela says </b>'Welcome [Your Name]! If you need to use anything I have in my shop. such as the mixing bowl here or the loom. please make yourself at home.'
<br><b>Nicoela says </b>'Due to the problems we have had lately with dishonorable visitors to the Haven we require all newcomers to see Daloran and Mistala for some simple tasks to prove that your intentions are good. I hope to see you soon.'
</td></tr></table>