<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4768>A Pulsating Rock</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=153>House of Midst</a><li><a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Palomidiar Allakhaji says </b>'Good day to you adventurer. Is there something I can assist you with? I have been quite busy as of late with the study of this [mysterious glowing rock] I was presented with and I do not have much time for small talk.'
<p><b>You say, </b>'mysterious glowing rock'
<br><b>Palomidiar Allakhaji says </b>'Well, if you look closely, I have it right here. It has been glowing since I first received it. But since it was delivered to me it has lost a lot of it's aura. I feel I will need another sample soon, it seems to lose its [energy] as time goes on.'
<p><b>You say, </b>'energy'
<br><b>Palomidiar Allakhaji says </b>'This I do not know and I am trying to discover. However, as I said before, this rock is slowly losing its energy it seems. I will need another [sample rock] soon.'
<p><b>You say, </b>'sample rock'
<br><b>Palomidiar Allakhaji says </b>'I believe these rocks are from the Paludal Caverns, if my sources were correct. Beetles that crawl over and feed off the rock structures there might explain the glowing, if they are the origins of these mysterious rocks. To further my studies I will need another pulsating rock. Will you [retrieve this rock] for me?'
<p><b>You say, </b>'retrieve this rock'
<br><b>Palomidiar Allakhaji says </b>'Fantastic, [Your Name]. Please return to me at once with a pulsating rock. We will conclude our dealings at that time.'
<p><b>You give Palomidiar Allakhaji : </b><a href=http://phobos/eq/item.php?id=4768>A Pulsating Rock</a>
<br><b>Palomidiar Allakhaji says </b>'This is it, this is what I am looking for to continue my studies. It is generating the same if not more energy then the rock before it! Excellent work, [Your Name]. You have my sincere thanks. Should you collect further samples in the future please bring them to me directly.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=153>House of Midst</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>