<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Priestess Farinthorn says </b>'Hi there. [Your Name]! I am Priestess Farinthorn. loyal paladin of House Fordel. It's nice to see visitors to our somewhat quiet town- all the excitement has the economy booming like never before!'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>