<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Robert Blackhand says </b>'Due to the problems we have had lately with dishonorable visitors to the Haven we require all newcomers to see Daloran and Mistala for some simple tasks to prove that your intentions are good. I hope to see you soon.'
<br><b>Robert Blackhand says </b>'Hello [Your Name] and welcome to Blackhands. Please let me know if there is anything I can help you with.'
</td></tr></table>