<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Rusty Blackhand says </b>'Due to the problems we have had lately with dishonorable visitors to the Haven we require all newcomers to see Daloran and Mistala for some simple tasks to prove that your intentions are good. I hope to see you soon.'
<br><b>Rusty Blackhand says </b>'Welcome to our smithing shop [Your Name]. please have a look and let me know if there is a certain mold or tin that you seek. I might have it laying around here somewhere. you never know.'
</td></tr></table>