<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Sneathe says </b>'It's nice to see a friendly face in Shadowhaven. Please take a look at what I have and let me know if there is anything you would like.'
<br><b>Sneathe says </b>'Due to the problems we have had lately with dishonorable visitors to the Haven we require all newcomers to see Daloran and Mistala for some simple tasks to prove that your intentions are good. I hope to see you soon.'
</td></tr></table>