<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4767>Bag of Assorted Gems</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=4766>Assorted Tailoring Supplies</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a><li><a href=http://phobos/eq/faction.php?id=152>House of Fordel</a><li><a href=http://phobos/eq/faction.php?id=153>House of Midst</a><li><a href=http://phobos/eq/faction.php?id=154>House of Stout</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Steaon Alarenier says </b>''Hail [Your Name]. You will have to excuse me because I am quite busy with my work and trying to sort out my [deliveries]. However, please help yourself to anything in my store that may be to your liking.'
<p><b>You say, </b>'deliveries'
<br><b>Steaon Alarenier says </b>'You see, I have to make more and more deliveries everyday, what with my business growing so much. I find it difficult to make time to go pick up the different skins and pelts I need for my trade. It's tough when you need some good help but can't afford to pay them. Sorry to bother you with my banter, perhaps I will find someone on the [way to the bazaar].'
<p><b>You say, </b>'trip to the bazaar'
<br><b>Steaon Alarenier says </b>''All right! Great to hear that [Your Name]. Here are the supplies I need delivered to my partner Gearo in the Bazaar. Please take them to him and return with whatever he has picked up for me. I look forward to seeing you soon, and thank you.'
<br><b>Steaon Alarenier gives you : </b><a href=http://phobos/eq/item.php?id=4766>Assorted Tailoring Supplies</a>
<p><b>You give Steaon Alarenier : </b><a href=http://phobos/eq/item.php?id=4767>Bag of Assorted Gems</a>
<br><b>Steaon Alarenier says </b>'Hey again [Your Name]. It's nice to see you back so soon, thank you for bringing my supplies to that crazy Gnome and bringing back my gems that he got for me. You are always welcome in my shop, good luck to you!'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=152>House of Fordel</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=153>House of Midst</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=154>House of Stout</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Steaon Alarenier says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>