<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Tabard Redhand says </b>'Greetings [Your Name]. If you are in need of some shoes for the big and tall then have a look around. I am sure to have something that will catch your eye.'
<br><b>Tabard Redhand says </b>'Due to the problems we have had lately with dishonorable visitors to the Haven we require all newcomers to see Daloran and Mistala for some simple tasks to prove that your intentions are good. I hope to see you soon.'
</td></tr></table>