<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Talor says </b>'Hello [Your Name] and welcome to our tavern. If you are looking for Verte he might be on a delivery. but I'm sure he will be right back.'
<br><b>Talor says </b>'Due to the problems we have had lately with dishonorable visitors to the Haven we require all newcomers to see Daloran and Mistala for some simple tasks to prove that your intentions are good. I hope to see you soon.'
</td></tr></table>