<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=26056>Sateals Economy Report</a><li><a href=http://phobos/eq/item.php?id=26058>Thars Sales Report</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=26055>Tattered Newsletter</a><li><a href=http://phobos/eq/item.php?id=26057>Book of Sales Secrets</a><li><a href=http://phobos/eq/item.php?id=26054>Amulet of the Haven</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a><li><a href=http://phobos/eq/faction.php?id=152>House of Fordel</a><li><a href=http://phobos/eq/faction.php?id=153>House of Midst</a><li><a href=http://phobos/eq/faction.php?id=154>House of Stout</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Trade Commissioner Henry says </b>'Hello there, traveler. I don't believe that I have seen you around these parts before- then again, I could have and simply forgotten since there have been so many new faces around here. However, if you are a newcomer to Shadowhaven, please make sure that you [register for trading] in the Haven. Registering with the Traders of the Haven will legitimize you in the eyes of local merchants and customers.'
<p><b>You say, </b>'register for trading'
<br><b>Trade Commissioner Henry says </b>'It's great that you are interested [Your Name], you will surely be glad you did. I have some simple deliveries that I need completed if you wish to be a registered trader in Shadowhaven.'
<p><b>You say, </b>'deliveries'
<br><b>Trade Commissioner Henry says </b>'The deliveries are simple enough, I just need you to bring some letters to some merchants of the Haven that are currently working in other locations. Will you [deliver these letters]?'
<p><b>You say, </b>'deliver these letters'
<br><b>Trade Commissioner Henry says </b>'I surely do appreciate the help, [Your Name]- clearly you understand the value of solid relations with the locals. First, I will need you to take this newsletter to Sateal. He is currently on assignment in the Bazaar and has been out of the loop on the happenings of Shadowhaven because of his heavy workload. Bring this to him and then return to me with his sales report. I look forward to seeing you soon.'
<br><b>Trade Commissioner Henry gives you : </b><a href=http://phobos/eq/item.php?id=26055>Tattered Newsletter</a>
<p><b>You give Trade Commissioner Henry : </b><a href=http://phobos/eq/item.php?id=26056>Sateals Economy Report</a>
<br><b>Trade Commissioner Henry says </b>'Great to see you back so soon [Your Name], you looked like a dependable person from the start. The next thing I need you to do is a bit more dangerous, but by the looks of you I doubt it will be a problem. Go to the Shadowhaven outpost in Fungusgrove and give Thar this book. Thar is a great merchant but I have seen his sales steadily declining, so I figured this book full of selling tips will help him regain his confidence and help him produce the kinds of numbers I know he is capable of. If his economy report is ready please, bring that back to me when you return.'
<br><font color=green><b>Trade Commissioner Henry </b>gives you a Book of Sales Secrets.</font>
<br><b>Trade Commissioner Henry gives you : </b><a href=http://phobos/eq/item.php?id=26057>Book of Sales Secrets</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=152>House of Fordel</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=153>House of Midst</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=154>House of Stout</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Trade Commissioner Henry : </b><a href=http://phobos/eq/item.php?id=26058>Thars Sales Report</a>
<br><b>Trade Commissioner Henry says </b>'Excellent work [Your Name], I knew that you were someone that I could trust to get the job done. The trader's union of Shadowhaven will hear of your solid work ethic. Perhaps a courier job is in your future, I couldn't have expected anyone to make these deliveries as fast as you did! Please take this amulet as a symbol of your dedication to Shadowhaven's booming economy. While wearing this you are sure to get all the greatest deals from the merchants of the Haven both here and in the bazaar. It was a pleasure meeting, you and thanks for all of your help.'
<br><b>Trade Commissioner Henry gives you : </b><a href=http://phobos/eq/item.php?id=26054>Amulet of the Haven</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=152>House of Fordel</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=153>House of Midst</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=154>House of Stout</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Trade Commissioner Henry says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>