<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Verte says </b>'Hey there [Your Name]. We carry many Shadowhaven exclusive brews here in our tavern. Pull up a barstool and enjoy an ale or two.'
<br><b>Verte says </b>'Due to the problems we have had lately with dishonorable visitors to the Haven we require all newcomers to see Daloran and Mistala for some simple tasks to prove that your intentions are good. I hope to see you soon.'
</td></tr></table>