<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Volan says </b>'Hi there and welcome to our shop. If it's some nice chainmail that you seek I have just the goods for you. I sell only the finest Fordel chainmail crafted by some of the best blacksmiths in the land.'
<br><b>Volan says </b>'Due to the problems we have had lately with dishonorable visitors to the Haven we require all newcomers to see Daloran and Mistala for some simple tasks to prove that your intentions are good. I hope to see you soon.'
</td></tr></table>