<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Wawker says </b>'Greetings [Your Name]. my partner and I run this little shop dedicated to bringing you only the finest armor. Have a look'
<br><b>Wawker says </b>'Due to the problems we have had lately with dishonorable visitors to the Haven we require all newcomers to see Daloran and Mistala for some simple tasks to prove that your intentions are good. I hope to see you soon.'
</td></tr></table>