<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4759>Antidote Ingredients</a><li><a href=http://phobos/eq/item.php?id=4765>Antidote Supplies</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=4758>Zimloro Ingredient List</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=154>House of Stout</a><li><a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Zimloro Jalobottle says </b>'Oi there, [Your Name]. If you are lookin for a potion or an antidote I got just what the doctor ordered. Step right up! I also have many other special potions but sadly I do not have the correct [components] for them.'
<p><b>You say, </b>'components'
<br><b>Zimloro Jalobottle says </b>'Well you see I can make some very magnificent potions. Unfortunately, I am in need of a few [ingredients] that I lost in a lab accident a few days back.'
<p><b>You say, </b>'ingredients'
<br><b>Zimloro Jalobottle says </b>'You sure seem interested in my work there, [Your Name]. So interested that I think you would be willing to go fetch the components I require for my studies for me! Am I correct? Will you [retrieve these components] for me?'
<p><b>You say, </b>'retrieve these components'
<br><b>Zimloro Jalobottle says </b>'Well you see I can make some very magnificent potions. Unfortunately, I am in need of a few [ingredients] that I lost in a lab accident a few days back.'
<br><b>Zimloro Jalobottle says </b>'Fantastic, [Your Name]! Elefan, my apprentice, is currently studying under my wing. He had been collecting samples in Shadeweaver lately and he probably has the items that I need. If you could go and speak with him and present him with this ingredient list, hopefully he will have what I need. Please bring the components back to me as soon as possible!'
<br><b>Zimloro Jalobottle gives you : </b><a href=http://phobos/eq/item.php?id=4758>Zimloro Ingredient List</a>
<p><b>You give Zimloro Jalobottle : </b><a href=http://phobos/eq/item.php?id=4759>Antidote Ingredients</a>
<br><b>Zimloro Jalobottle says </b>'You did it, [Your Name]! Finally I can finish these potions that I have been working on for such a long time. I will surely tell all of my friends of your willingness to help me!'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=154>House of Stout</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a> has gotten better.</font>
<p><b>You give Zimloro Jalobottle : </b><a href=http://phobos/eq/item.php?id=4765>Antidote Supplies</a>
<br><b>Zimloro Jalobottle says </b>'Ah, of course, the antidote supplies I have been waiting for from Daksins. I hope he is ok, we all told him it was not wise to go out to the cursed mountains alone. I thank you for bringing me these supplies because Daksins was unable too. There have been many reports lately of people receiving the disease carried by the beasts you encountered. Should you come across these extracts in the future bring them to me if you like. Thank you again, your actions will not go unnoticed.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=154>House of Stout</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>