<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13990>Sack of Hay</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=14320>Sack of Cursed Hay</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=18>Beta Neutral</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>#Roror says </b>'Do you [know fear]?'
<p><b>You say, </b>'i know fear'
<br><b>#Roror says </b>'That's great!'
<p><b>You say, </b>'I know no fear'
<p><b>You say, </b>'bless my hay'
<br><b>#Roror says </b>'I require 66 gold coin and the hay in order to bless it.'
<p><b>You say, </b>'curse my hay'
<br><b>#Roror says </b>'I require 66 gold coin and the hay in order to curse it.'
<p><b>You give #Roror : </b><a href=http://phobos/eq/item.php?id=13990>Sack of Hay</a>
<br><b>#Roror gives you : </b><a href=http://phobos/eq/item.php?id=14320>Sack of Cursed Hay</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=18>Beta Neutral</a> has gotten better.</font>
<p><b>You give #Roror : </b><a href=http://phobos/eq/item.php?id=13990>Sack of Hay</a>
<br><b>#Roror gives you : </b><a href=http://phobos/eq/item.php?id=14320>Sack of Cursed Hay</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=18>Beta Neutral</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>