<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=8720>Phobonomicon of Thul Tae Ew</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=8732>Medallion of the Arcane Scientists</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Aqaar Aluram says </b>'Hail traveler. may I assist you with something. or are you just [passing through]?'
<p><b>You say, </b>'passing through'
<br><b>Aqaar Aluram says </b>'Very well friend. please take care when passing beyond the river to the east.  Several researchers and their mercenary escort passed through our camp en route to the temple.  That was last week and they have yet to return.  We are holding off on our expedition until we can [learn more] about what happened to them.'
<p><b>You say, </b>'learn more'
<br><b>Aqaar Aluram says </b>'We are not sure exactly what happened to them. They were researching an ancient ritual performed by the lizards. It is rumored to summon the very dead to walk again. Should you dare to venture inside the temple, should you discover anything about this I would greatly appreciate it.'
<p><b>You give Aqaar Aluram : </b><a href=http://phobos/eq/item.php?id=8720>Phobonomicon of Thul Tae Ew</a>
<br><b>Aqaar Aluram gives you : </b><a href=http://phobos/eq/item.php?id=8732>Medallion of the Arcane Scientists</a>
<br><b>Aqaar Aluram says </b>'Thank You. This is most interesting. I must study it immediatly'
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>