<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20673>Wax Sealed Note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20674>Tiny Lute</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Oknoggin Stonesmacker says </b>'Yoo leave me 'lone!'
<p><b>You give Oknoggin Stonesmacker : </b><a href=http://phobos/eq/item.php?id=20673>Wax Sealed Note</a>
<br><font color=green><b>Oknoggin Stonesmacker </b>snatches the note from your hand and rips it open with his large hands.</font>
<br><b>Oknoggin Stonesmacker says </b>'You take dis to Kargek. He want!'
<br><font color=yellow>You gain experience!!</font>
<br><b>Oknoggin Stonesmacker gives you : </b><a href=http://phobos/eq/item.php?id=20674>Tiny Lute</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>