<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Linara Parlone says </b>'Please [help] me out of this horrid place! My family must be terribly worried!'
<p><b>You say, </b>'how how can I help you?'
<br><b>Linara Parlone says </b>'If you can find the [key] to my restraints. I should be able to escape.'
<p><b>You say, </b>'where is the key'
<br><b>Linara Parlone says </b>'Last I knew. Najena's priest had the key.  I fear he has left this place though.  I heard talk of traveling to some estate.  I know not where.  Oh dear. oh dear!  I shall never leave this place!'
</td></tr></table>