<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>#Translocator Ionie says </b>'Hello there. There seems to be some strange problems with the boats in this area. The Academy of Arcane Sciences has sent a small team of us to investigate them. If you need to [travel to Iceclad] in the meantime, I can transport you to my companion there.'
<p><b>You say, </b>'travel to iceclad'
<br><font color=brown><b>#Translocator Ionie casts a spell : </b><a href=http://phobos/eq/spell.php?id=2284>Portal to Iceclad</a>.</font>
</td></tr></table>