<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Magus Arindri says </b>'Greetings [Your Name]. As you may have guessed I have been sent here by the Wayfarers Brotherhood to assist those that dare subject themselves to our magic. I promise you I have trained long and hard to be up to the task.  I only rarely make the type of mistakes you may have heard about regarding these spells of travel. Come, let me know where you would like to go and I'll send you on your way.  I can send you to any of the Wayfarer camps in [Butcherblock], [Commonlands], [Everfrost], [North Ro], [South Ro], or [Nedaria's Landing].'
<p><b>You say, </b>'PoK'
<br><b>Magus Arindri says </b>'Off you go..'
<br><font color=white><b>The Player moves to zone 202 at -118,-193,-156</b></font>
<p><b>You say, </b>'Butcherblock'
<br><b>Magus Arindri says </b>'Off you go...'
<br><font color=white><b>The Player moves to zone 68 at -2489,-1107,0</b></font>
<p><b>You say, </b>'North Ro'
<br><b>Magus Arindri says </b>'Off you go...'
<br><font color=white><b>The Player moves to zone 34 at 901,2675,-25</b></font>
<p><b>You say, </b>'South Ro'
<br><b>Magus Arindri says </b>'Off you go...'
<br><font color=white><b>The Player moves to zone 35 at 1029.8,-1431.5,-23.8</b></font>
<p><b>You say, </b>'Everfrost'
<br><b>Magus Arindri says </b>'Off you go...'
<br><font color=white><b>The Player moves to zone 30 at -5050,1832,-60</b></font>
<p><b>You say, </b>'Commonlands'
<br><b>Magus Arindri says </b>'Off you go...'
<br><font color=white><b>The Player moves to zone 22 at -222,-1629,3.3</b></font>
<p><b>You say, </b>'Nedaria'
<br><b>Magus Arindri says </b>'Off you go...'
<br><font color=white><b>The Player moves to zone 182 at 1481.6,1047.8,83.6</b></font>
<p><b>You say, </b>'Abysmal Sea'
<br><b>Magus Arindri says </b>'Off you go...'
<br><font color=white><b>The Player moves to zone 279 at 37,-150,140</b></font>
<p><b>You say, </b>'Guild Lobby'
<br><b>Magus Arindri says </b>'Off you go...'
<br><font color=white><b>The Player moves to zone 344 at 0,575,6</b></font>
</td></tr></table>