<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=5728>Di'zok Signet of Service</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=5728>Di'zok Signet of Service</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>a goblin traitor says </b>'Serve the Sarnak do ya? You the one they say they send? I don't know that I believe ya, show a token. Humm show me ya ring if ya got it.'
<p><b>You say, </b>'plan'
<p><b>You say, </b>'evidence'
<p><b>You give a goblin traitor : </b><a href=http://phobos/eq/item.php?id=5728>Di'zok Signet of Service</a>
<br><font color=green><b>a goblin traitor </b>looks relieved when he sees your signet of service and eyes you with a bit more respect.</font>
<br><b>a goblin traitor says </b>'Good! They tell'd me to wait here for ya, can't say I like it but here I sits. It be good to be rid of Skargus though, so I be a happy one, oh yes. Want to know the [plan] then?'
<br><b>a goblin traitor gives you : </b><a href=http://phobos/eq/item.php?id=5728>Di'zok Signet of Service</a>
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>