<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20475>Wood Painting</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20476>Silver Chained Locket</a></ul></td><td><p><b>You give a human skeleton : </b><a href=http://phobos/eq/item.php?id=20475>Wood Painting</a>
<br><font color=green><b>a human skeleton </b>begins to crack and disintegrate, its body collapsing into a pile of dust that scatters into the winds. On the ground you notice a locket on a fine, thin chain which you pick up.</font>
<br><b>a human skeleton gives you : </b><a href=http://phobos/eq/item.php?id=20476>Silver Chained Locket</a>
<br><b>a human skeleton disappears.</b>
<br><font color=green><b>a human skeleton </b>will not take this item.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>