<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=6472>Traitor's note</a></ul></td><td><p><b>You say, </b>'proceed'
<p><b>You say, </b>'get the report'
<p><b>You give a sarnak spy : </b><a href=http://phobos/eq/item.php?id=6472>Traitor's note</a>
<br><font color=green><b>a sarnak spy </b>reads the note slowly, turning it around in his claws a few times before completing it. 'I see you spoke with that half-wit goblin! I hate hate hate it when he sends me a note, his penmanship is almost illegible. I hope he informed you of the situation, he's really not the most dependable agent of Di'zok, and sadly his note doesn't really make much sense. No matter though, are you ready to [proceed] in this mission?'</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>