<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12708>A Stone Key</a><li><a href=http://phobos/eq/item.php?id=12712>A Bone Key</a><li><a href=http://phobos/eq/item.php?id=12713>A Bone Necklace</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12714>A Coarse Iron Needle</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>an enslaved iksar </b>looks up at you. You can tell his spirit is broken. His scars speak of a severe beating.</font>
<p><b>You say, </b>'Vok Na Zov'
<br><b>an enslaved iksar says </b>'Forget them. I believe all six scrolls lie in the [Kaesora Library] and that is no safe place for any explorer. The scrolls are not readable by any livng person, but I came here in search of a machine which may be able to decipher them, the [Stupendous Contraption]. Should you return to Cabilis, see that the Arch Duke hears of the scrolls.'
<p><b>You say, </b>'kaesora library'
<br><b>an enslaved iksar says </b>'Oh!! You heard of the ancient library I discovered in Kaesora? I think the six scrolls of [Vok Na Zov] may lie there. I have not yet actually found the location of the library and it's very dangerous to lurk within the ruins of Kaesora. I would not venture there if I were you.'
<p><b>You say, </b>'stupendous contraption'
<br><b>an enslaved iksar says </b>'I have learned it was a machine tinkered by a legendary gnome. It has many uses. It lies in the slave pens of Droga. Perhaps it may be used to decipher the [Scrolls of Vok Na Zov]. I have leearned that it will not work without a [contraption needle]. Luckily I have found one in my journies.'
<p><b>You say, </b>'contraption needle'
<br><b>an enslaved iksar says </b>'The contraption needle is a piece of the machine, the [Stupendous Contraption]. It won't operate without it and if you want it, you're going to have to bring me the [pen keys].'
<p><b>You say, </b>'pen keys'
<br><b>an enslaved iksar says </b>'Pen keys!! I need the pen keys to get out of here! Find the ones who hold these keys. Bring me the key to pen number 1 and both keys to the pen gates. Do so and I shall give you the [contraption needle].'
<p><b>You give an enslaved iksar : </b><a href=http://phobos/eq/item.php?id=12708>A Stone Key</a>, <a href=http://phobos/eq/item.php?id=12712>A Bone Key</a>, <a href=http://phobos/eq/item.php?id=12713>A Bone Necklace</a>
<br><font color=green><b>an enslaved iksar </b>escapes with a flash, but before he goes, he speaks, 'At last!! The keys which shall bring me freedom! I thank you and here is the contraption needle. Good luck.'</font>
<br><b>an enslaved iksar gives you : </b><a href=http://phobos/eq/item.php?id=12714>A Coarse Iron Needle</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>an enslaved iksar disappears.</b>
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>an enslaved iksar says </b>'These are not the items I sent you for.'
</td></tr></table>