<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=62100>Hoodlum Symbol of Dust</a><li><a href=http://phobos/eq/item.php?id=62101>Heaprit's Heart</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=62206>Antique Ring of Truth</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Digmaster Duggert says </b>'I am certainly lucky to be alive this day hail and well met. The goblins in the Temple of Droga have been a constant thorn in my peoples side and we need to strike back at them. Will you help us strike back?'
<p><b>You say, </b>'strike back'
<br><b>Digmaster Duggert says </b>'I am glad you will help. Here is what I need for you to do for me. Find the goblin dust hoodlums within the depths of the Temple of Droga and bring back three Hoodlum Symbols of Dust they often have. Also seek out the famous thief, Dust Hoodlum Heaprit, and bring back his heart so I might use it in a ritual of protection. If you do this for me I will reward you well.'
<p><b>You give Digmaster Duggert : </b><a href=http://phobos/eq/item.php?id=62100>Hoodlum Symbol of Dust</a> x3, <a href=http://phobos/eq/item.php?id=62101>Heaprit's Heart</a>
<br><b>Digmaster Duggert says </b>'May the blessing of the earth be with you. Here take this, it may prove useful to you.'
<br><b>Digmaster Duggert gives you : </b><a href=http://phobos/eq/item.php?id=62206>Antique Ring of Truth</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Digmaster Duggert says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>