<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20678>Giant Sized Monocle</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20666>Rejesiam Ore</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Mentrax Mountainbone says </b>'What be it you want! Go away before I eat you for dinner!'
<p><b>You say, </b>'wenden sent me'
<br><b>Mentrax Mountainbone says </b>'Did he? Perhaps you would like to trade for some Rejesiam ore? Bring me the monocle from the patriarch that wanders around the Dreadlands. I've always wanted one of those.'
<p><b>You give Mentrax Mountainbone : </b><a href=http://phobos/eq/item.php?id=20678>Giant Sized Monocle</a>
<br><b>Mentrax Mountainbone says </b>'Eh, you actually found one! Thank you, [Your Name]. Here is a block of ore for you. Just don't let the other giants know.'
<br><b>Mentrax Mountainbone gives you : </b><a href=http://phobos/eq/item.php?id=20666>Rejesiam Ore</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>