<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Basher Nanrum says </b>'Peh! What am you wanted?! I am Basher Nanrum. You? [Your Name] ? Heh, you look for works? Hmm, me tinks you too weakling for [job] me need done. Hmm.. You might do, mebbe.'
<p><b>You say, </b>'job'
<br><b>Basher Nanrum says </b>'Me in charge of making torches for basher patrols. But Nanrum is much too mighty for such stupid job and Nanrum get idea. Dem fire bugses in da desert - dem eyes glowed. And dem don't burneded like torches. If [Your Name] getted Nanrum three fire beetle eyes me would giveded [Your Name] a shiny thingie dat you wanteded. Go ahed, [Your Name] , an' get me da eyes.'
<br><b>Basher Nanrum says </b>'Well dat be some of da eyeballses I askeded for. But I you needs ta give me three for da shiny.'
</td></tr></table>