<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13253>Spiderling Eye</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=131>Grobb Merchants</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Exterminator Filrog says </b>'Hey you dere! Look at all these spiders! Dey called me to come kill em, but there is too many!!! If you bring me four eyes from da little spiders, I reward you!'
<p><b>You give Exterminator Filrog : </b><a href=http://phobos/eq/item.php?id=13253>Spiderling Eye</a> x4
<br><b>Exterminator Filrog says </b>'You good at killing spiders. Mebbe me should find anuder job. Here take da coins.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=131>Grobb Merchants</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 1gp 1sp 1cp
</td></tr></table>