<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18846>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13576>Molding Tunic*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Gardunk says </b>'Hello.'
<p><b>You give Gardunk : </b><a href=http://phobos/eq/item.php?id=18846>A tattered note</a>
<br><b>Gardunk says </b>'Thanks.'
<br><b>Gardunk gives you : </b><a href=http://phobos/eq/item.php?id=13576>Molding Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>