<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Gargh says </b>'You [friend of Gardunk]? Meez friend of Gardunk.'
<p><b>You say, </b>'i am a friend of gardunk'
<br><b>Gargh says </b>'Dat good. He tell meez you was comin'. Meez learn you to fight like alligator. Dominate through fear. Dat is what we do. Strike fear into heart of enemies. You [ready to start]?'
<p><b>You say, </b>'i am ready to start'
<br><b>Gargh says </b>'Good. We start easy. Little froggies a good place. They our enemies. You go to da swamp and kill da tadpoles. Bring back to me four pieces of Froglok Tadpole Flesh. Strip da flesh from our enemies. Dat your first task.'
</td></tr></table>