<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18792>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13529>Muck Stained Tunic*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Hukulk says </b>'What you want!!  You make fun of [helm of Hukulk]?!!  Me smash you!!  Maybe you come learn ways of Hate and Fear!  You be dark power.  You be Pain. You [want join Nightkeep]?'
<p><b>You say, </b>'join'
<br><b>Hukulk says </b>'Good.  Hate and Pain.  Innoruuk teach power. I teach power.  Me make you power.  You do what me say.  You no mess up. I no kill you.  We no like dead creature we no own.  Go. kill dem.  Bring four bone chips.  I make you power.'
<p><b>You give Hukulk : </b><a href=http://phobos/eq/item.php?id=18792>A tattered note</a>
<br><b>Hukulk says </b>'Haaah!! Bow to Hukulk!! Hukulk make you feared.. make you powered! Dark power flow through you! Hate and Fear in your blood! Go to Vergad. He give you first lesson in pain.'
<br><b>Hukulk gives you : </b><a href=http://phobos/eq/item.php?id=13529>Muck Stained Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>