<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18791>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13530>Black and Green Tunic*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Kaglari says </b>'SNORT!  HHUUUUCCCKSSH..  Peh!  You speak at Kaglari. High Priestess of Dark Ones.  Children of Hate.  Spawn of Innoruuk.  [Your Name] . speak or be gone!  SNORT!  You [wish majik power]?'
<p><b>You say, </b>'power'
<br><b>Kaglari says </b>'GOOD!  <SNORT!!>  Innoruuk needs more childrens.  You show majik skill or I give you to Innoruuk.  You bring two froglok tadpole fleshes and two bone chips ..<SNORT>..  from old bones.  I teach you majik.  GO!  <SNORT!!>'
<p><b>You give Kaglari : </b><a href=http://phobos/eq/item.php?id=18791>A tattered note</a>
<br><b>Kaglari says </b>'Good.. Kaglari need you help.. Kaglari teach you majik now.'
<br><b>Kaglari gives you : </b><a href=http://phobos/eq/item.php?id=13530>Black and Green Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>