<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18790>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13528>Mud Covered Tunic*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Ranjor says </b>'Ya wanna be a member a Da Bashers. duz ya?  What making ya tink yooz is good nuff ta be one o' us?  Can ya proves ta me why I shouldn't oughtta just eat yer smelly hide?  I gonna tests ya. ya big. ugly peece o' meet.  Ya [willin ta test] or duz I just eats ya now?'
<p><b>You say, </b>'test'
<br><b>Ranjor says </b>'Stoopid meat.  I gonna eats ya anyways sumday.  Brings me a froglok meat and two dem li'l froglok tadpole fleshes.  Dey berry good.'
<p><b>You give Ranjor : </b><a href=http://phobos/eq/item.php?id=18790>A tattered note</a>
<br><b>Ranjor says </b>'Arhh.. Ranjor mighty warrior.. Ranjor teach you warrior.. you fight for Ranjor now.'
<br><b>Ranjor gives you : </b><a href=http://phobos/eq/item.php?id=13528>Mud Covered Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>