<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Savarixsa Zexus says </b>'Salutations. [Your Name]! I am here as a favor to my brother. High Priest Perrir. We seek loyal followers of Innoruuk to earn their place among the hierarchy of the Spires. Are you [devoted to Innoruuk]?'
<p><b>You say, </b>'i am devoted to innoruuk'
<br><b>Savarixsa Zexus says </b>'My brother requests your presence in Neriak at the Spires of Innoruuk. Take this note with you. [Your Name]. It will inform Perrir of who sent you.'
</td></tr></table>