<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12190>Huge Mushroom Head</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2308>Froglok Skin Mask</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=66>Da Bashers</a><li><a href=http://phobos/eq/faction.php?id=292>Shadowknights of Night Keep</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=22>Broken Skull Clan</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Treskar says </b>'You dare speak to Master Treskar!! You be [sent by Hukulk] or you be hurtin'!! Me have no time to waste with ugly one like you!!'
<p><b>You say, </b>'sent by hukulk'
<br><b>Treskar says </b>'Ha!! Hukulk accept puny troll now?!! Ha!! You join us and you join fight. Nightkeep enemy is [Your Name] enemy!! You help smash [other weak shadowknights].  Them weak.  We true power!!  You bash good and maybe you do [secret mission] for Treskar.'
<p><b>You say, </b>'other weak shadowknights'
<br><b>Treskar says </b>'Ha! Dem Ogre Greenbloods are weaklings. Dems your enemy. Frogloks are your enemy. Smash all Greenbloods! Smash all Frogloks!'
<p><b>You say, </b>'secret mission'
<br><b>Treskar says </b>'Nightkeep hear bashers see fungus man spore guardian at Innothule. Him protect young fungus man spores so they grow big, BIG an' attack trolls!! You go find spore guardian. Smash hi big red head!! Bring Treskar that huge mushroom head of his to prove he walk no more. You do this and me give you froglok skin mask.'
<p><b>You give Treskar : </b><a href=http://phobos/eq/item.php?id=12190>Huge Mushroom Head</a>
<br><b>Treskar says </b>'Ha! Dats one big dead head. You smashed him guud. Take dis mask, Shadowknight uv Nightkeep - I seez great tings for you.'
<br><b>Treskar gives you : </b><a href=http://phobos/eq/item.php?id=2308>Froglok Skin Mask</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=66>Da Bashers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=22>Broken Skull Clan</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=292>Shadowknights of Night Keep</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=22>Broken Skull Clan</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>