<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When 214105 spawns </b>
<p><b>You say, </b>'Hail'
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<br><font color=green><b>214105 </b>Maelin Starpyre's thoughts enter into your own. 'The singed parchment of Rallos lies in his dead hand. Bring it back to me I will translate them using the Cipher of Druzzil.'</font>
</td></tr></table>