<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>#Translocator Jempar says </b>'Hello there. There seem to be some strange problems with the boats in this area. The Academy of Arcane Sciences has sent a small team of us to investigate them. If you need to [travel to Erudin] or [travel to Qeynos] in the meantime, I can transport you to my companion there.'
<p><b>You say, </b>'travel to erudin'
<br><font color=brown><b>#Translocator Jempar casts a spell : </b><a href=http://phobos/eq/spell.php?id=2290>Portal to Erudin</a>.</font>
<p><b>You say, </b>'travel to qeynos'
<br><font color=brown><b>#Translocator Jempar casts a spell : </b><a href=http://phobos/eq/spell.php?id=2288>Portal to Qeynos</a>.</font>
</td></tr></table>