<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1680>A Broken Arrow</a></ul></td><td><hr><b>When Abe the Abandoned spawns </b>
<p><b>You say, </b>'hail'
<br><font color=green><b>Abe the Abandoned </b>turns his head slowly toward you but his eyes never come into focus. You can't tell if he's looking at you, behind you, or right in front of his own face. Then, suddenly, he shouts at the top of his lungs, 'HOOOOKAAAHEEEEYYYY! I AM [ABE]!</font>
<p><b>You say, </b>'Abe'
<br><b>Abe the Abandoned says </b>'Nothing is hidden. All is discernible if you only know where to look and you have the right [eyes]. Don't be angry with me if you can't get your eyes right to see what you're looking for. I'd lend you mine but I don't wear the same size.'
<p><b>You say, </b>'eyes'
<br><font color=green><b>Abe the Abandoned </b>begins to draw a picture in the mud with his finger although it doesn't seem to make any sense at all. He points to his picture and nods approvingly at you, saying, 'You see? The curtains fell and it was naught but a dream upon a landscape that we thought we knew. The dream of the [Combine] fulfilled when we finally trimmed our fingernails and looked into the mud. And now we are abandoned, in a world that none can see, no one has the eyes.</font>
<p><b>You say, </b>'combine'
<br><font color=green><b>Abe the Abandoned </b>shakes his head in amusement and says, 'Heheheh, yeah, you'd think so, wouldn't you? But I guess not.</font>
<p><b>You say, </b>'broken arrow'
<br><font color=green><b>Abe the Abandoned </b>'s eyes suddenly come into focus, looking deep into your own and says, 'There was a time when we cared for the world and trod with the spirits along the paths of the cosmos. We built many great things and worked to preserve what was. I came here to wait for an answer when we began to die off. We could not figure why this was and I was chosen to come here and commune with our friends. We carved an arrow, and everyone who was left shaved a sliver of wood from it. We let it drop to hallowed ground and our highest shaman stepped on it, breaking it. I've been waiting here for so long. So, so long, to give it to the spirits, and thank them.</font>
<p><b>You say, </b>'give them the arrow'
<br><font color=green><b>Abe the Abandoned </b>removes a quiver slung across his shoulder and solemnly hands it to you without a word.</font>
<br><b>Abe the Abandoned gives you : </b><a href=http://phobos/eq/item.php?id=1680>A Broken Arrow</a>
</td></tr></table>