<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When Froham the Forgotten spawns </b>
<p><b>You say, </b>'hail'
<br><font color=green><b>Froham the Forgotten </b>looks up at you and mumbles a brief greeting. He appears uncomfortable around others.</font>
<p><b>You say, </b>'who are you'
<br><font color=green><b>Froham the Forgotten </b>glances up at you, fiddling with his bony fingers and mumbles, 'Mmmm me name's Froham..I'm 'ere [waitin].</font>
<p><b>You say, </b>'waitin'
<br><b>Froham the Forgotten says </b>'Just waitin' . . . it'll [be ere soon], I s'pose.'
<p><b>You say, </b>'be here soon'
<br><font color=green><b>Froham the Forgotten </b>obviously has trouble communicating. He shifts uncomfortably and says, 'Well I'm not sure, but it's real important. I been 'ere fer a [long time], a real long time. So I'll keep waitin' til it comes.</font>
<p><b>You say, </b>'long time'
<br><b>Froham the Forgotten says </b>'Been 'ere since Erud sailed over with his friends. They let me catch a ride on their ship after I told them I needed to come 'ere to wait. He was a nice fella, real smart. Though I'm thinkin' he's dead by now. Maybe [Abe] knows fer sure. Abe's been here longer'n me, even.'
<p><b>You say, </b>'abe'
<br><b>Froham the Forgotten says </b>'Yeah, Abe's an old guy. Well, he's kinda beyond bein' old if ye know what I mean. Not all together either. His mind floats all over like the sea around us. But he's got enough sense to wait here like he's done fer, well, fer dang near ever. If ye see him, and he ain't much fer talkin' straight, ask him about [a broken arrow]. Not sure what it means to him but it seems to bring him around.'
</td></tr></table>