<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1666>Opaque Gem</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=342>True Spirit</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Ooglyn says </b>'Ooooh, it you, [Your Name]. Me's been waitin for you cuz our frenz say you comin an need da test. So's I gib you da test. Hmm, now where me put it? Ooglyn been waiting for sign for so long dat me forget where me put test. Keep your eyes out for sign while me look for test. Oh, hey, [Your Name], they gib you gem? I need dat gem, please, heheh.'
<p><b>You give Ooglyn : </b><a href=http://phobos/eq/item.php?id=1666>Opaque Gem</a>
<br><b>Ooglyn says </b>'Ahhh, tank you, now me can...OH LOOK!! DA SIGN!!!! Oh, sorry you missed it. The sign show you where to wait for da test. Follow me...I like you so I take you there. We goin for a swim, [Your Name]!'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=342>True Spirit</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Ooglyn says </b>'Ok shaman, let us be off.'
</td></tr></table>