<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When Srafen the Soaked spawns </b>
<p><b>You say, </b>'hail'
<br><b>Srafen the Soaked says </b>'Why hello there! Ahh, it's good to see a new face down [here]. So you've come to [wait] with [us] eh? That is splendid! It's been getting very boring lately.'
<p><b>You say, </b>'here'
<br><b>Srafen the Soaked says </b>'Oh! Well this is where [we wait]. It's not much for looks but if you're lucky, a pretty fish will swim by. Oh, and once Dillon said he saw one of those fish women, a mermaid, he called it! Although, I'm not so sure of his state of mind, hehehe. He's been waiting here much longer than I.'
<p><b>You say, </b>'\bus\b'
<p><b>You say, </b>'wait'
<br><b>Srafen the Soaked says </b>'We've been waiting quite some time, really. I have been here the least amount of time, but that doesn't help keep the boredom away, heheh. What are we waiting for, you ask? HehehHAahahah! What are we waiting for?? Heheheh, what a silly question! It's quite obvious if you take the time to think about it. Heh. Ummm.. I'm really not sure.'
<p><b>You say, </b>'else'
<br><b>Srafen the Soaked says </b>'Ahh, yes, there's also a really old guy I've only seen a couple times, name's Froham. Whew, he is really old, and not much of a talker. Mostly mumbles from time to time. Dillon says he's been here since Erud first took his people across the sea. Not sure who this Erud feller is but Froham isn't in the best of shape, so it must have been a LONG time ago. Froham did mention there's one other guy but we've never seen him. He apparently had something to do with the Combine Empire, no idea what that is though.'
<p><b>You say, </b>'not an illusion'
<br><b>Srafen the Soaked says </b>'Awww, well that's too bad. Although illusions and real people don't seem to be much different at times, so, please stay and keep Dillon and me company. We could use it, right Dillon?'
</td></tr></table>