<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When #A Sludge Lurker is killed </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=218042>A_Filth_Gorger</a></b> spawns (,15,).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=218042>A_Filth_Gorger</a></b> spawns (,-15,).</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=218042>A_Filth_Gorger</a></b> spawns.</font>
</td></tr></table>