<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19629>Letter to Bartle Barnick</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19555>Tattered Cap Pattern</a><li><a href=http://phobos/eq/item.php?id=19558>Tattered Wristband Pattern</a><li><a href=http://phobos/eq/item.php?id=19559>Tattered Glove Pattern</a><li><a href=http://phobos/eq/item.php?id=19561>Tattered Boot Pattern</a><li><a href=http://phobos/eq/item.php?id=19557>Tattered Sleeve Pattern</a><li><a href=http://phobos/eq/item.php?id=19560>Tattered Pant Pattern</a><li><a href=http://phobos/eq/item.php?id=19556>Tattered Tunic Pattern</a><li><a href=http://phobos/eq/item.php?id=17124>Mail Assembly Kit</a></ul></td><td><p><b>You say, </b>'moss toe cap'
<br><b>Bartle Barnick says </b>'To assemble a Moss Toe Cap you will require two [silk thread], a ruined mossy rat pelt, and a giant thicket rat skull. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Cap Pattern.'
<br><b>Bartle Barnick gives you : </b><a href=http://phobos/eq/item.php?id=19555>Tattered Cap Pattern</a>
<p><b>You say, </b>'moss toe bracer'
<br><b>Bartle Barnick says </b>'To assemble a Moss Toe Bracer you will require a [silk thread], a ruined mossy rat pelt, and a large wood spider tibia. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Wristband Pattern.'
<br><b>Bartle Barnick gives you : </b><a href=http://phobos/eq/item.php?id=19558>Tattered Wristband Pattern</a>
<p><b>You say, </b>'moss toe gloves'
<br><b>Bartle Barnick says </b>'To assemble Moss Toe Gloves you will require two [silk thread], a ruined mossy rat pelt, and two large wood spider tarsus. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Glove Pattern.'
<br><b>Bartle Barnick gives you : </b><a href=http://phobos/eq/item.php?id=19559>Tattered Glove Pattern</a>
<p><b>You say, </b>'moss toe boots'
<br><b>Bartle Barnick says </b>'To assemble Moss Toe Boots you will require two [silk thread], two ruined mossy rat pelts, and two giant wood spider hairs. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Boot Pattern.'
<br><b>Bartle Barnick gives you : </b><a href=http://phobos/eq/item.php?id=19561>Tattered Boot Pattern</a>
<p><b>You say, </b>'moss toe sleeves'
<br><b>Bartle Barnick says </b>'To assemble Moss Toe Sleeves you will require two [silk thread], a mossy rat pelt, and two giant wood spider patella. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Sleeves Pattern.'
<br><b>Bartle Barnick gives you : </b><a href=http://phobos/eq/item.php?id=19557>Tattered Sleeve Pattern</a>
<p><b>You say, </b>'moss toe leggings'
<br><b>Bartle Barnick says </b>'To assemble Moss Toe Leggings you will require three [silk thread], two mossy rat pelts, and two giant wood spider femurs. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Pants Pattern.'
<br><b>Bartle Barnick gives you : </b><a href=http://phobos/eq/item.php?id=19560>Tattered Pant Pattern</a>
<p><b>You say, </b>'moss toe tunic'
<br><b>Bartle Barnick says </b>'To assemble a Moss Toe Tunic you will require four [silk thread], an undamaged mossy rat pelt, and a giant wood spider thorax. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Tunic Pattern.'
<br><b>Bartle Barnick gives you : </b><a href=http://phobos/eq/item.php?id=19556>Tattered Tunic Pattern</a>
<p><b>You say, </b>'silk thread'
<br><b>Bartle Barnick says </b>'Silk Thread is sewn by a tailor using a [sewing kit] or a community [loom]. Two spiderling silks combined in the sewing kit or loom will create one silk thread.'
<p><b>You say, </b>'sewing kit'
<br><b>Bartle Barnick says </b>'Meeka Diggs in the center of Rivervale behind the Fools Gold Tavern may be able to provide you with a sewing kit. There is also a loom near where she peddles her goods.'
<p><b>You say, </b>'loom'
<br><b>Bartle Barnick says </b>'Meeka Diggs in the center of Rivervale behind the Fools Gold Tavern may be able to provide you with a sewing kit. There is also a loom near where she peddles her goods.'
<p><b>You give Bartle Barnick : </b><a href=http://phobos/eq/item.php?id=19629>Letter to Bartle Barnick</a>
<br><b>Bartle Barnick says </b>'It is good to see another of our young people choose the humble life of a druid of Karana. I have assembled patterns that will allow you to construct some protective leather garments to keep you comfortable in the wilds and help turn aside the weapons of the Storm Reapers enemies. The required components for the leather vary according to which piece of Moss Toe Leather your are planning on crafting. Do you wish to craft a [moss toe cap], a [moss toe bracer], [moss toe gloves], [moss toe boots], [moss toe sleeves], [moss toe leggings], or a [moss toe tunic]?'
<br><b>Bartle Barnick gives you : </b><a href=http://phobos/eq/item.php?id=17124>Mail Assembly Kit</a>
<br><b>Bartle Barnick says </b>'I have no need for this item [Your Name], you can have it back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>