<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18731>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13538>Faded Gold Felt Tunic*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Beek Guinders says </b>'Hay. ho, there, young  ! I'd love to yak it up with you but I'm a bit busy at the moment. trying to find some [help].'
<p><b>You give Beek Guinders : </b><a href=http://phobos/eq/item.php?id=18731>A tattered note</a>
<br><b>Beek Guinders says </b>'Aye. Welcome. my fur-footed friend. My name is Beek Guinders. and I am guild master here at the Chapel of Mischief. Here is our guild tunic. Wear it with pride, as it will set you apart from the crowd.'
<br><b>Beek Guinders gives you : </b><a href=http://phobos/eq/item.php?id=13538>Faded Gold Felt Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>