<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19627>Letter to Bipdo Hargin</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19555>Tattered Cap Pattern</a><li><a href=http://phobos/eq/item.php?id=19558>Tattered Wristband Pattern</a><li><a href=http://phobos/eq/item.php?id=19559>Tattered Glove Pattern</a><li><a href=http://phobos/eq/item.php?id=19561>Tattered Boot Pattern</a><li><a href=http://phobos/eq/item.php?id=19557>Tattered Sleeve Pattern</a><li><a href=http://phobos/eq/item.php?id=19560>Tattered Pant Pattern</a><li><a href=http://phobos/eq/item.php?id=19556>Tattered Tunic Pattern</a><li><a href=http://phobos/eq/item.php?id=17124>Mail Assembly Kit</a></ul></td><td><p><b>You say, </b>'what thorn mail coif'
<br><b>Bipdo Hargin says </b>'To assemble a Thorn Mail Coif you will require two [silk thread]. ruined thorn drakeling scales. and a giant thicket rat skull. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Coif Pattern.'
<br><b>Bipdo Hargin gives you : </b><a href=http://phobos/eq/item.php?id=19555>Tattered Cap Pattern</a>
<p><b>You say, </b>'what thorn mail bracer'
<br><b>Bipdo Hargin says </b>'To assemble a Thorn Mail Bracer you will require a [silk thread]. ruined thorn drakeling scales. and a large fruit bat wing. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Bracer Pattern.'
<br><b>Bipdo Hargin gives you : </b><a href=http://phobos/eq/item.php?id=19558>Tattered Wristband Pattern</a>
<p><b>You say, </b>'what thorn mail gloves'
<br><b>Bipdo Hargin says </b>'To assemble Thorn Mail Gloves you will require two [silk thread]. ruined thorn drakeling scales. and two large fruit bat furs. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Glove Pattern.'
<br><b>Bipdo Hargin gives you : </b><a href=http://phobos/eq/item.php?id=19559>Tattered Glove Pattern</a>
<p><b>You say, </b>'what thorn mail boots'
<br><b>Bipdo Hargin says </b>'To assemble Thorn Mail Boots you will require two [silk thread]. two ruined thorn drakeling scales. and two giant thicket rat pelts. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Boot Pattern.'
<br><b>Bipdo Hargin gives you : </b><a href=http://phobos/eq/item.php?id=19561>Tattered Boot Pattern</a>
<p><b>You say, </b>'what thorn mail sleeves'
<br><b>Bipdo Hargin says </b>'To assemble Thorn Mail Sleeves you will require two [silk thread]. thorn drakeling scales. and two giant fruit bat wings. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Sleeves Pattern.'
<br><b>Bipdo Hargin gives you : </b><a href=http://phobos/eq/item.php?id=19557>Tattered Sleeve Pattern</a>
<p><b>You say, </b>'what thorn mail leggings'
<br><b>Bipdo Hargin says </b>'To assemble Thorn Mail Leggings you will require three [silk thread]. two thorn drakeling scales. and two giant fruit bat furs. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Leggings Pattern.'
<br><b>Bipdo Hargin gives you : </b><a href=http://phobos/eq/item.php?id=19560>Tattered Pant Pattern</a>
<p><b>You say, </b>'what thorn mail tunic'
<br><b>Bipdo Hargin says </b>'To assemble a Thorn Mail Tunic you will require four [silk thread]. pristine thorn drakeling scales. a giant fruit bat rib cage. and a giant fruit bat fur. Once you have the necessary components combine them in your Mail Assembly Kit with this Tattered Tunic Pattern.'
<br><b>Bipdo Hargin gives you : </b><a href=http://phobos/eq/item.php?id=19556>Tattered Tunic Pattern</a>
<p><b>You give Bipdo Hargin : </b><a href=http://phobos/eq/item.php?id=19627>Letter to Bipdo Hargin</a>
<br><b>Bipdo Hargin says </b>'Pleased to meet you [Your Name]! You must be one of Megosh's new trainees. Megosh has asked me to help get you outfitted in a suit of armor to protect you from the vile weapons of Rivervales foes. I have assembled a kit for you that will allow you to construct the armor pieces once you have gathered the necessary components. The required components vary according to which piece of Thorn Mail armor you are planning on assembling. Do you wish to craft a [thorn mail coif], a [thorn mail bracer], [thorn mail gloves], [thorn mail boots], [thorn mail sleeves], [thorn mail leggings], or a [thorn mail tunic].'
<br><b>Bipdo Hargin gives you : </b><a href=http://phobos/eq/item.php?id=17124>Mail Assembly Kit</a>
</td></tr></table>