<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When Daleen Leafsway spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Daleen Leafsway says </b>'Greetings. [Your Name]!  Welcome to Tagglefoot's Farm.  We grow nothing but the finest vegetables in our field.  We even manage to harvest the mystical jumjum stalk in our fields.  Karana has blessed us indeed.'
<p><b>You say, </b>'starving'
<p><b>You say, </b>'turnips'
</td></tr></table>