<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13071>Rat Whiskers</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=133>Guardians of the Vale</a><li><a href=http://phobos/eq/faction.php?id=208>Mayor Gubbin</a><li><a href=http://phobos/eq/faction.php?id=316>Storm Reapers</a><li><a href=http://phobos/eq/faction.php?id=218>Merchants of Rivervale</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=88>Dreadguard Outer</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Exterminator Sutten says </b>'Hi there [Your Name] . Think you could help me out a bit? I was hired to get rid of all these pesky rodents running around town but there seems to be no end to them! They are ruining the jumjum field and worse yet, if I dont get rid of them all, my boss wont give me the muffins he promised me! Think you could hunt some of the rodents down and bring me back four rat whiskers? I would pay you of course!'
<p><b>You give Exterminator Sutten : </b><a href=http://phobos/eq/item.php?id=13071>Rat Whiskers</a> x4
<br><b>Exterminator Sutten says </b>'Nice work! Take these coins. Oh no, there are still more rodents! I better get to work. Farewell, friend!'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=133>Guardians of the Vale</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=208>Mayor Gubbin</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=316>Storm Reapers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=218>Merchants of Rivervale</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=88>Dreadguard Outer</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 1gp 1sp 1cp
</td></tr></table>