<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13936>Squad Ring</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13936>Squad Ring</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Hendi Mrubble says </b>'Why. hello there!!  Welcome to the Church of Mischief.  I am Hendi Mrubble. The 'R' is silent.  I am the resident healer of the church. so if you are in [need of healing]. or want me to [cure poison] or [cure disease]. let me know.  If you've got a touch of the crazy brain. I can't do a thing for you.'
<p><b>You say, </b>'I am need of healing'
<br><b>Hendi Mrubble says </b>'Hmmm.  I would love to help you with that. but you will have to make a donation to the temple.  The Guardians asked me to charge one of the Rivervale piranha teeth.'
<p><b>You say, </b>'i am in need of healing'
<br><b>Hendi Mrubble says </b>'Hmmm.  I would love to help you with that. but you will have to make a donation to the temple.  The Guardians asked me to charge one of the Rivervale piranha teeth.'
<p><b>You say, </b>'what cure disease'
<br><b>Hendi Mrubble says </b>'Eeww!! Careful. don't touch Hendi.  I figured there must have been something not quite right about you.  Well. now. before we can cast the disease from your body you will have to make a little donation of one gold for the service and eight gold to disinfect this place.  That would be 10 total!!  Let's see it.'
<p><b>You say, </b>'what cure poison'
<br><b>Hendi Mrubble says </b>'Cure poison. eh?  Before we do that. you must fetch me three bixie stingers.'
<p><b>You give Hendi Mrubble : </b><a href=http://phobos/eq/item.php?id=13936>Squad Ring</a>
<br><b>Hendi Mrubble gives you : </b><a href=http://phobos/eq/item.php?id=13936>Squad Ring</a>
</td></tr></table>