<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13411>Case of Jumjum Juice</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Ilscent Tagglefoot says </b>'Oh hello. [Your Name].  My name is Ilscent.   I am glad to see you. but I am in a bit of a [bind] right now.'
<p><b>You say, </b>'what bind'
<br><b>Ilscent Tagglefoot says </b>'Well. I promised an ally of ours that I would send him a case of Jumjum juice for all the help he has given us.  I had planned on taking it to him myself but I have too many chores to do here on the farm. Will you take the [jumjum juice] to him?'
<p><b>You say, </b>'I will take the the jumjum juice to him'
<br><b>Ilscent Tagglefoot says </b>'Oh. thank you so much!  His name is Xanuusus and he lives in the Plains of Karana. in the foothills along their northern edge. actually.  We are most grateful for your help.  Xanuusus normally rewards messengers well.'
<br><b>Ilscent Tagglefoot gives you : </b><a href=http://phobos/eq/item.php?id=13411>Case of Jumjum Juice</a>
</td></tr></table>