<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18431>Halfling Paladin Note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13541>Jumjum Sack Tunic*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Jano Jinglebelly says </b>'A pleasure to make your acquaintance [Your Name] . I am Kaya Cloudfoot. first Paladin of the Storm Reapers. I traveled long ago when I was just a wee sprout to the city of Qeynos far to the west. It was there I grew under the tutelage of the Knights of Thunder. a noble order of paladins loyal to Karana. the Storm Lord. I have returned now to Rivervale to teach interested young halflings the ways of a Knight of the Storm Reapers so that we may defend Karana's people and lands from the [evil forces] that would see it destroyed.'
<p><b>You give Jano Jinglebelly : </b><a href=http://phobos/eq/item.php?id=18431>Halfling Paladin Note</a>
<br><b>Jano Jinglebelly says </b>'Thanks.'
<br><b>Jano Jinglebelly gives you : </b><a href=http://phobos/eq/item.php?id=13541>Jumjum Sack Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>