<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19628>Letter to Jimji Bottletoe</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19631>Crude Helm Mold</a><li><a href=http://phobos/eq/item.php?id=19632>Crude Bracer Mold</a><li><a href=http://phobos/eq/item.php?id=19633>Crude Gauntlets Mold</a><li><a href=http://phobos/eq/item.php?id=19635>Crude Vambrace Mold</a><li><a href=http://phobos/eq/item.php?id=19636>Crude Greaves Mold</a><li><a href=http://phobos/eq/item.php?id=19637>Crude Breastplate Mold</a><li><a href=http://phobos/eq/item.php?id=19634>Crude Boot Mold</a><li><a href=http://phobos/eq/item.php?id=17124>Mail Assembly Kit</a></ul></td><td><p><b>You say, </b>'what bravefoot helm'
<br><b>Jimji Bottletoe says </b>'To assemble a Bravefoot Helm you will need to obtain two bricks of crude iron ore and smelt them in a [forge] with a Water Flask and this Crude Helm Mold. Once that is done combine the Crude Iron Helm with a Ruined Wolf Pelt and a Large Yellowjacket Tergite in the Mail Assembly Kit.'
<br><b>Jimji Bottletoe gives you : </b><a href=http://phobos/eq/item.php?id=19631>Crude Helm Mold</a>
<p><b>You say, </b>'what forge'
<br><b>Jimji Bottletoe says </b>'There is a forge at the Tagglefoots Farm near the vegetable stand and the main house of the farm.'
<p><b>You say, </b>'what bravefoot mail bracer'
<br><b>Jimji Bottletoe says </b>'To assemble a Bravefoot Mail Bracer you will need to obtain a brick of crude iron ore and smelt it in a [forge] with a Water Flask and this Crude Bracer Mold. Once that is done. combine the Crude Iron Bracer with a Ruined Wolf Pelt and a Large Yellowjacket Sternite in the Mail Assembly Kit.'
<br><b>Jimji Bottletoe gives you : </b><a href=http://phobos/eq/item.php?id=19632>Crude Bracer Mold</a>
<p><b>You say, </b>'what bravefoot  gauntlets'
<br><b>Jimji Bottletoe says </b>'To assemble Bravefoot Gauntlets you will need to obtain two bricks of crude iron ore and smelt them in a [forge] with a Water Flask and this crude Gauntlet Mold. Once that is done combine the Crude Iron Gauntlets with a Ruined Wolf Pelt and two Large Yellowjacket Tarsi in the Mail Assembly Kit.'
<br><b>Jimji Bottletoe gives you : </b><a href=http://phobos/eq/item.php?id=19633>Crude Gauntlets Mold</a>
<p><b>You say, </b>'what bravefoot  vambraces'
<br><b>Jimji Bottletoe says </b>'To assemble Bravefoot Vambraces you will need to obtain two bricks of crude iron ore and smelt them in a [forge] with a Water Flask and this Crude Vambrace Mold. Once that is done combine the Crude Iron Vambraces with a Low Quality Wolf Pelt and two Giant Yellowjacket Tergites in the Mail Assembly Kit.'
<br><b>Jimji Bottletoe gives you : </b><a href=http://phobos/eq/item.php?id=19635>Crude Vambrace Mold</a>
<p><b>You say, </b>'what bravefoot  greaves'
<br><b>Jimji Bottletoe says </b>'To assemble Bravefoot Greaves you will need to obtain two bricks of crude iron ore and smelt them in a [forge] with a Water Flask and this Crude Greaves Mold. Once that is done combine the Crude Iron Greaves with two Low Quality Wolf Pelts and two Giant Yellowjacket Sternites in the Mail Assembly Kit.'
<br><b>Jimji Bottletoe gives you : </b><a href=http://phobos/eq/item.php?id=19636>Crude Greaves Mold</a>
<p><b>You say, </b>'what bravefoot  breastplate'
<br><b>Jimji Bottletoe says </b>'To assemble a Bravefoot Breastplate you will need to obtain four bricks of crude iron ore and smelt them in a [forge] with a Water Flask and this Crude Breastplate Mold. Once that is done combine the Crude Iron Breastplate with a Medium Quality Wolf Pelt and a Giant Yellowjacket Thorax in the Mail Assembly Kit.'
<br><b>Jimji Bottletoe gives you : </b><a href=http://phobos/eq/item.php?id=19637>Crude Breastplate Mold</a>
<p><b>You say, </b>'what bravefoot mail boots'
<br><b>Jimji Bottletoe says </b>'To assemble Bravefoot Mail Boots you will need to obtain two bricks of crude iron ore and smelt them in a [forge] with a Water Flask and this crude Boot Mold. Once that is done combine the Crude Iron Boots with two Ruined Wolf Pelts. and two Giant Yellowjacket Tarsi in the Mail Assembly Kit.'
<br><b>Jimji Bottletoe gives you : </b><a href=http://phobos/eq/item.php?id=19634>Crude Boot Mold</a>
<p><b>You give Jimji Bottletoe : </b><a href=http://phobos/eq/item.php?id=19628>Letter to Jimji Bottletoe</a>
<br><b>Jimji Bottletoe says </b>'Pleased to meet you [Your Name]! You must be one of Kayas new trainees. Kaya has asked me to help get you outfitted in a suit of armor to protect you from the vile weapons of Rivervales foes. I have assembled a kit for you that will allow you to construct the armor pieces once you have gathered the necessary components. The required components vary according to which piece of Bravefoot Mail armor you are planning on assembling. Do you wish to craft a [bravefoot helm]. a [bravefoot mail bracer]. [bravefoot gauntlets]. [bravefoot mail boots]. [bravefoot vambraces]. [bravefoot greaves]. or a [bravefoot breastplate].'
<br><b>Jimji Bottletoe gives you : </b><a href=http://phobos/eq/item.php?id=17124>Mail Assembly Kit</a>
</td></tr></table>