<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Marshal Ghobber says </b>'Greetings!  Allow me to introduce myself.  I am Marshal Ghobber Truppack.  Marshal of the Great Wall Patrol.  Are you [new to the squad]?'
<p><b>You say, </b>'I am new to the squad'
<p><b>You say, </b>'I am new to the squad'
<p><b>You say, </b>'I am new to the squad'
<p><b>You say, </b>'Am I one with the wall'
<p><b>You say, </b>'Am I one with the wall'
<p><b>You say, </b>'what new threat'
<br><b>Marshal Ghobber says </b>'The new threat I refer to is the community of goblins which was found beyond the Great Wall of Serilis. They are called Clan Runnyeye. They have begun to sneak over the wall. The deputies have reported seeing them launch themselves up the wall in a matter of seconds using ornate grappling hooks. We have attempted to obtain one of these devices for further inspection, but we have yet to find one on any of the dead goblins. If you should ever find one, be sure to bring it to me immediately.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>