<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Marshal Lanena says </b>'Hello. [Your Name].  I am Lanena Wickystick. marshal of all Vale concerns.  If there are any troubles brewing in our fine town which concern the Guardians of the Vale. please inform me.  You must be a [new deputy] or are you an [outsider]?'
<p><b>You say, </b>'I am a new deputy'
<br><b>Marshal Lanena says </b>'You are in good standing with the Guardians of the Vale. Continue with your good work and then we may speak.'
<br><b>Marshal Lanena says </b>'It is good to see such fine stock in the ranks of the Guardians.  Being new. there is much to learn. in battle and in life itself.  If you are not presently obligated. we have need of you here in the hollow.  There seems to be a [small problem].'
<p><b>You say, </b>'I am an outsider'
<br><b>Marshal Lanena says </b>'Well. then!! You should not be in here.  This place is restricted to all outsiders.  You will leave at once!  Thank you and good day.'
<p><b>You say, </b>'what small problem'
<br><b>Marshal Lanena says </b>'For months. Fiddy Bobick has petitioned the marshals to assist him with a problem he has.  With the addition of new deputies such as yourself. we can now give him the assistance he requires.  Just go down to Bobick's shop near the lake.  Tell him I sent you.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>