<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Marshal Anrey says </b>'Do I look like your best friend?!!  Well I'm not. bixie buster!!  You will address an officer with the word 'Hail' like every other deputy.  Stand up straight. hunchback. or you'll be patrolling Rivervale till dawn!'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>