<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13971>Crate of Rotten Carrots</a><li><a href=http://phobos/eq/item.php?id=13972>Crate of Rotten Carrots</a><li><a href=http://phobos/eq/item.php?id=13974>Jumjum Stalk</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13971>Crate of Rotten Carrots</a><li><a href=http://phobos/eq/item.php?id=13957>Crate of Fine Carrots</a><li><a href=http://phobos/eq/item.php?id=13958>Crate of Carrots</a><li><a href=http://phobos/eq/item.php?id=10303>Earring of Fire Reflection</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Reebo Leafsway says </b>'Greetings and salutations. [Your Name]! My name is Reebo Leafsway. loyal Druid of [Karana].  I am in charge of helping young druids who wish to get started down the [trail to Karana's wisdom].  I also do my share of tending the [crops].'
<p><b>You say, </b>'Shakey'
<br><b>Reebo Leafsway says </b>'Shakey is our protector and friend. He is just getting old. Losing his [stuffing]. His [head] is getting very cracked and dry as well.'
<p><b>You say, </b>'stuffing'
<br><b>Reebo Leafsway says </b>'The hay he requires is difficult to obtain.  It must have been harvested from the Plains of Karana. then cursed by a high priest of the Faceless, [Cazic-Thule].  Finally, you must cast the hay and a flask of blessed Oil of Life into an armorer's forge.  Only then will the hay be ready.  We Stormreapers will reward you greatly if you could accomplish this task.  Remember, you must give the scarecrow stuffing to Shakey only after it has been properly prepared.'
<p><b>You say, </b>'who is karana'
<br><b>Reebo Leafsway says </b>'Karana is known as the Rainkeeper. It is through His will that our [crops] and our children grow big and healthy. He watches over us and protects us. calling down the fury of a tempest on those who wish harm upon His followers.'
<p><b>You say, </b>'crops'
<br><b>Reebo Leafsway says </b>'The crops we grow here are mostly carrots. lettuce and squash.  We also are the only place on all of Norrath where the soil can support the mystical Jumjum Stalk.'
<p><b>You say, </b>'head'
<br><b>Reebo Leafsway says </b>'The head of a scarecrow is difficult to replace.  We do not know what is needed and all of our attempts have failed.  Perhaps you could [research] this for us and bring back a new head for our old friend Shakey?'
<p><b>You say, </b>'research'
<br><b>Reebo Leafsway says </b>'We have heard of a great forbidden tome penned by an evil necromancer that holds the secrets of instilling life into scarecrows.  We have recovered pages from that book.  That is how we know about Shakey's hay.  But the pages detailing the creation of a scarecrow's head are missing.  We believe that the Erudites possess at least some of the pages and might know where the rest of them may be found.  Start your search in their city of Erudin.'
<p><b>You say, </b>'Nillipuss'
<br><b>Reebo Leafsway says </b>'Nillipuss is a brownie that lives in the area who often steals and destroys our JumJum Stalk. Will you teach him a [lesson]?'
<p><b>You say, </b>'lesson'
<br><b>Reebo Leafsway says </b>'Good. Bring me back some of the JumJum he has stolen and I will reward you for your trouble.'
<p><b>You say, </b>'trail to Karana'
<br><b>Reebo Leafsway says </b>'Good.  First you should learn that Karana's work is just that..  work.  Karana provides us with the tools but it is by the sweat of our brows that we prosper.  Common sense and hard work are two things that are highly prized by our people.  Time for you to sweat. young one.  Take this crate of carrots over to Blinza Toepopal in the Fool's Gold.  They need our finest carrots for Mayor Gubbin's stew.  When you return I will teach you a lesson of the Rainkeeper.'
<br><b>Reebo Leafsway gives you : </b><a href=http://phobos/eq/item.php?id=13971>Crate of Rotten Carrots</a>
<p><b>You give Reebo Leafsway : </b><a href=http://phobos/eq/item.php?id=13971>Crate of Rotten Carrots</a>
<br><b>Reebo Leafsway says </b>'Very good. Very good indeed. Karana does not need the blind obedience that so many deities require. Trust your instincts, they are more often right than not. Here, take this to Blinza. Hurry, she is expecting them. You may keep the donation she gives you in return.'
<br><b>Reebo Leafsway gives you : </b><a href=http://phobos/eq/item.php?id=13957>Crate of Fine Carrots</a>
<p><b>You give Reebo Leafsway : </b><a href=http://phobos/eq/item.php?id=13972>Crate of Rotten Carrots</a>
<br><b>Reebo Leafsway says </b>'These carrots are rotten.  They were rotten when I gave them to you.  Why would you waste time and energy on such a fool's errand?  Because I asked you to?  Many, even those you trust will ask you to do things which you should not.  Use the common sense that Karana has blessed you with to know which tasks can benefit our people and which could harm them.  Learn this lesson well.  You will need it if you plan to adventure beyond the vale.  Now take these fresh carrots to Blinza and apologize for your error.  You may keep the donation she gives you as payment.'
<br><b>Reebo Leafsway gives you : </b><a href=http://phobos/eq/item.php?id=13958>Crate of Carrots</a>
<p><b>You give Reebo Leafsway : </b><a href=http://phobos/eq/item.php?id=13974>Jumjum Stalk</a>
<br><b>Reebo Leafsway says </b>'Oh good!  I see you have taugh that nasty Nillipuss a thing or two!  Good.  But it seems to me that he has stolen more jumjum than this.  Perhaps he needs another lesson?'
<p><b>You give Reebo Leafsway : </b><a href=http://phobos/eq/item.php?id=13974>Jumjum Stalk</a> x2
<br><b>Reebo Leafsway says </b>'Oh good!  I see you have taught that nasty Nillipuss a thing or two!  Good.  But it seems to me that he has stolen more jumjum than this.  Perhaps he needs another lesson?'
<p><b>You give Reebo Leafsway : </b><a href=http://phobos/eq/item.php?id=13974>Jumjum Stalk</a> x3
<br><b>Reebo Leafsway says </b>'Oh good!  I see you have taught that nasty Nillipuss a thing or two!  Good.  But it seems to me that he has stolen more jumjum than this.  Perhaps he needs another lesson?'
<p><b>You give Reebo Leafsway : </b><a href=http://phobos/eq/item.php?id=13974>Jumjum Stalk</a> x4
<br><b>Reebo Leafsway says </b>'Excellent!!  You must have taught ol' Nillipuss a great deal!  But he never seems to learn..  Oh well.  The Stormreapers and all of Rivervale owe you a debt of gratitude.  Please accept this token of our appreciation.'
<br><b>You receive </b> 6gp 4sp
<br><b>Reebo Leafsway gives you : </b><a href=http://phobos/eq/item.php?id=10303>Earring of Fire Reflection</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>