<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Rueppy Kutpurse says </b>'Hello. [Your Name].  Rueppy's my name.  Why don't you buy us something to [drink] and we can talk?'
<p><b>You say, </b>'what drink'
<br><b>Rueppy Kutpurse says </b>'How about a short beer?  That sounds good.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>