<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=14321>Sack of Writhing Hay</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13980>Wee Harvester</a></ul></td><td><p><b>You say, </b>'hail'
<p><b>You give Shakey Scarecrow : </b><a href=http://phobos/eq/item.php?id=14321>Sack of Writhing Hay</a>
<br><b>Shakey Scarecrow gives you : </b><a href=http://phobos/eq/item.php?id=13980>Wee Harvester</a>
</td></tr></table>