<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13931>RunnyEye Warbeads</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13023>Bixie Berry Buns</a><li><a href=http://phobos/eq/item.php?id=13024>Tagglefoot Tingle Drink</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=133>Guardians of the Vale</a><li><a href=http://phobos/eq/faction.php?id=208>Mayor Gubbin</a><li><a href=http://phobos/eq/faction.php?id=316>Storm Reapers</a><li><a href=http://phobos/eq/faction.php?id=218>Merchants of Rivervale</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=88>Dreadguard Outer</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Sheriff Roglio says </b>'Hail, [Your Name]! Stand tall whenever you are speaking to the Sheriff of Rivervale. I command the warriors of this vale. You must be new to the ranks of the Guardians of the Vale, so be sure to report to your squad at once. We must protect our people. The [danger] has come closer to home. If you are not a deputy, then please leave these halls.'
<p><b>You say, </b>'What danger'
<br><b>Sheriff Roglio says </b>'What danger?!! You must be new to the community. The goblins of Clan Runnyeye have been scaling our wall somehow. You must join our forces in exterminating every one of those beasts. Your wages are earned with every four bloody goblin warbead necklaces you return to me. Now be off and fight the good fight.'
<p><b>You give Sheriff Roglio : </b><a href=http://phobos/eq/item.php?id=13931>RunnyEye Warbeads</a> x4
<br><b>Sheriff Roglio says </b>'Good work, Deputy [Your Name]! We shall soon rid our countryside of the goblin threat. Here are your wages. Eat well tonight!'
<br><b>Sheriff Roglio gives you : </b><a href=http://phobos/eq/item.php?id=13023>Bixie Berry Buns</a>
<br><b>Sheriff Roglio gives you : </b><a href=http://phobos/eq/item.php?id=13024>Tagglefoot Tingle Drink</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=133>Guardians of the Vale</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=208>Mayor Gubbin</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=316>Storm Reapers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=218>Merchants of Rivervale</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=88>Dreadguard Outer</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 8sp
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>