<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Soulbinder Hoggle Grubbytoe says </b>'Greetings . When a hero of our world is slain  their soul returns to the place it was last bound and the body is reincarnated. As a member of the Order of Eternity  it is my duty to [bind your soul] to this location if that is your wish.'
<p><b>You say, </b>'Bind my soul'
<br><b>Soulbinder Hoggle Grubbytoe says </b>'Binding your soul.  You will return here when you die.'
<br><font color=brown><b>Soulbinder Hoggle Grubbytoe casts a spell : </b><a href=http://phobos/eq/spell.php?id=2049>Bind Affinity</a>.</font>
</td></tr></table>