<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13240>Deputy Tagil's Payment</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18013>A Note</a><li><a href=http://phobos/eq/item.php?id=13083>Pine Needles</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=316>Storm Reapers</a><li><a href=http://phobos/eq/faction.php?id=208>Mayor Gubbin</a><li><a href=http://phobos/eq/faction.php?id=218>Merchants of Rivervale</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=347>Unkempt Druids</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Uner Gnarltrunk says </b>'Hello there, [Your Name]. Please watch where you are stepping when you're out in the field.  Nothing is more frustrating than having some fine jumjum ruined by our own careless feet. That reminds me, [Deputy Tagil] still owes us for that jumjum he stomped on the other day!'
<p><b>You say, </b>'who is Deputy Tagil'
<br><b>Uner Gnarltrunk says </b>'Deputy Tagil is a fine young halfling who serves the vale well. But the other day, chasing that dirty Nillipuss, he trampled some fresh Jumjum.  He promised to make amends but it must have slipped his mind.  Please take this note to him as a friendly reminder.'
<br><b>Uner Gnarltrunk gives you : </b><a href=http://phobos/eq/item.php?id=18013>A Note</a>
<p><b>You give Uner Gnarltrunk : </b><a href=http://phobos/eq/item.php?id=13240>Deputy Tagil's Payment</a>
<br><b>Uner Gnarltrunk says </b>'I knew that Deputy Tagil had simply forgotten. He really is a good young halfling. Here, take this as a small payment for your time.'
<br><b>Uner Gnarltrunk gives you : </b><a href=http://phobos/eq/item.php?id=13083>Pine Needles</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=316>Storm Reapers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=208>Mayor Gubbin</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=218>Merchants of Rivervale</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=347>Unkempt Druids</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>