<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12401>A Glowing Skull</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=59526>The Skull of Torture</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>a skeletal cook says </b>'Some cracked old bone's, two zombie flesh, and a salt minnow make up the rest. Throw inside a skull and mix, and I would have a delightful dish. But with no eye's I have no sight to make Kurn's delicious delight. And if I could I would not eat without a tongue behind my teeth.'
<p><b>You give a skeletal cook : </b><a href=http://phobos/eq/item.php?id=12401>A Glowing Skull</a>
<br><font color=green><b>a skeletal cook </b>The cook's bone's crack as he reaches out to take the skull from your hand's. A voice in your mind say's, Thank you. Now I can leave this dreadful place. Please take this as I no longer have any use for it. The cook places the skull back in your hand's before collapsing into a lifeless pile of bone's.</font>
<br><b>a skeletal cook gives you : </b><a href=http://phobos/eq/item.php?id=59526>The Skull of Torture</a>
<br><b>a skeletal cook says </b>'I have no need for this item, [Your Name]. You can have it back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>