<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10400>Greater Lightstone</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Khrix Fritchoff says </b>'Close the door and be gone fool !! You are going to give away my hiding spot!!'
<p><b>You say, </b>'powder of reanimation'
<br><b>Khrix Fritchoff says </b>'I can help you get the powder you ask of, if you would supply me with a greater lightstone so that I may see my way out of this place.'
<p><b>You give Khrix Fritchoff : </b><a href=http://phobos/eq/item.php?id=10400>Greater Lightstone</a>
<br><b>Khrix Fritchoff says </b>'At last I may leave this place!! Good luck destroying my abomination, you will surely need it against my most powerful yet uncontrolable creation!'
<br><font color=yellow>You gain experience!!</font>
<br><b>Khrix Fritchoff says </b>'SORRY, Khrixs Abomination is not in the DB right now!'
</td></tr></table>