<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20370>Mechanical Doll</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20374>Ripped Qeynos Bards Guild Flyer</a><li><a href=http://phobos/eq/item.php?id=20371>Note for Baenar</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Serra says </b>'H..h..hello? Can you help me? I lost [something] and I need it so I can go back home.'
<p><b>You say, </b>'something'
<br><b>Serra says </b>'I never got my doll for my birthday. Before he could bring it to me I was h..hurt by the bad man. I cannot leave without my doll. Will you please help me?'
<p><b>You say, </b>'doll'
<br><b>Serra says </b>'Oh goody! But... I cannot seem to remember his name. He gave me this note before I...'
<br><font color=green><b>Serra </b>begins to hand you a ripped note.</font>
<p><b>You say, </b>'note'
<br><b>Serra says </b>'I hope it will help you out. Please find him so I can leave this place.'
<br><b>Serra gives you : </b><a href=http://phobos/eq/item.php?id=20374>Ripped Qeynos Bards Guild Flyer</a>
<p><b>You give Serra : </b><a href=http://phobos/eq/item.php?id=20370>Mechanical Doll</a>
<br><b>Serra says </b>'Oh! You have the dolly! Thank you! Thank you! Thank you! I can go home now. Please give this to my father, Baenar. He will understand when he gets it.'
<br><font color=green><b>Serra </b>begins to fade away.</font>
<br><b>Serra says </b>'Bye bye!'
<br><b>Serra gives you : </b><a href=http://phobos/eq/item.php?id=20371>Note for Baenar</a>
<br><b>Serra disappears.</b>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>