<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>#Mavuin says </b>'I have been locked away, shamed for a reason that is not my own! Take [this information] to the Tribunal, I beg of you! It may be the only chance to prove that I am truly innocent!'
<p><b>You say, </b>'What information'
<br><b>#Mavuin says </b>'Oh, excuse me... The Tribunal is not a being who deals with parchment and quills, he will test you to allow me to [plea my case].  When you tell him of my request, be prepared, [Your Name].'
<p><b>You say, </b>'plea your case'
<br><b>#Mavuin says </b>'Thank you! Oh I wish you luck.'
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<p><b>You say, </b>'Hail'
<br><b>#Mavuin says </b>'I have been locked away, shamed for a reason that is not my own! Take [this information] to the Tribunal, I beg of you! It may be the only chance to prove that I am truly innocent!'
</td></tr></table>