<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=31842>Mark of Execution</a><li><a href=http://phobos/eq/item.php?id=31796>Mark of Flame</a><li><a href=http://phobos/eq/item.php?id=31960>Mark of Lashing</a><li><a href=http://phobos/eq/item.php?id=31845>Mark of Stone</a><li><a href=http://phobos/eq/item.php?id=31844>Mark of Torture</a></ul></td><td><p><b>You give 201435 : </b><a href=http://phobos/eq/item.php?id=31842>Mark of Execution</a>
<p><b>You give 201435 : </b><a href=http://phobos/eq/item.php?id=31796>Mark of Flame</a>
<p><b>You give 201435 : </b><a href=http://phobos/eq/item.php?id=31960>Mark of Lashing</a>
<p><b>You give 201435 : </b><a href=http://phobos/eq/item.php?id=31845>Mark of Stone</a>
<p><b>You give 201435 : </b><a href=http://phobos/eq/item.php?id=31844>Mark of Torture</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>