<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Agent of The Tribunal  says </b>'Do you wish to [return]?'
<p><b>You say, </b>'return'
<br><b>Agent of The Tribunal  says </b>'Very well.'
<br><font color=white><b>The Player moves to zone 201 at 456,825,9</b></font>
<p><b>You say, </b>'return'
<br><b>Agent of The Tribunal  says </b>'Very well.'
<br><font color=white><b>The Player moves to zone 201 at 456,825,9</b></font>
</td></tr></table>