<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13243>One Half of Elixir</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13244>One Quarter of Elixir</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a><li><a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a><li><a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a><li><a href=http://phobos/eq/faction.php?id=361>Wolves of the North</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Arnis McLish says </b>'My word!! I cannot believe how cold it is out here. I must keep running around just to keep warm.'
<p><b>You say, </b>'where is megan'
<br><b>Arnis McLish says </b>'I heard she got lost on the plains. You should go ask her dog, Snowflake, where she is. I hear she is somewhere around the pass to Halas.'
<p><b>You give Arnis McLish : </b><a href=http://phobos/eq/item.php?id=13243>One Half of Elixir</a>
<br><b>Arnis McLish says </b>'Mmmm.. Thank you stranger. I feel a lot warmer now. You should now go and find [Megan] O'Reilly.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=361>Wolves of the North</a> has gotten better.</font>
<br><b>Arnis McLish gives you : </b><a href=http://phobos/eq/item.php?id=13244>One Quarter of Elixir</a>
</td></tr></table>