<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13242>One Quarter of Elixir</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13243>One Half of Elixir</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a><li><a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a><li><a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a><li><a href=http://phobos/eq/faction.php?id=361>Wolves of the North</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Bryndin McMill says </b>'H-ha.. H-hai.. Hail!! It is v-v-very.. C-cold out here. You sh-sh-should light a c-c-campfire.'
<p><b>You give Bryndin McMill : </b><a href=http://phobos/eq/item.php?id=13242>One Quarter of Elixir</a>
<br><b>Bryndin McMill says </b>'Ahhh!! I feel warm all over. Thanks. You should go give Arnis McLish a drink of this elixir. Last time I saw him he was headed toward Blackburrow.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=361>Wolves of the North</a> has gotten better.</font>
<br><b>Bryndin McMill gives you : </b><a href=http://phobos/eq/item.php?id=13243>One Half of Elixir</a>
</td></tr></table>