<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12221>Lion Delight</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12226>Sweaty Shirt</a></ul></td><td><p><b>You give Iceberg : </b><a href=http://phobos/eq/item.php?id=12221>Lion Delight</a>
<br><b>Iceberg says </b>'Growlll'
<br><b>Iceberg gives you : </b><a href=http://phobos/eq/item.php?id=12226>Sweaty Shirt</a>
</td></tr></table>