<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13761>Polar Bear Skin</a><li><a href=http://phobos/eq/item.php?id=13714>Werewolf Pelt</a><li><a href=http://phobos/eq/item.php?id=13715>Werewolf Claws</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Karg Icebear says </b>'Hail, traveller! I am Karg of Clan Icebear, lone hunter of the Everfrost Peaks. Have you seen any polar bears about?'
<p><b>You say, </b>'yes'
<br><b>Karg Icebear says </b>'I hunt polar bears and furnish cloaks from their [pelts]. They keep you warm in this cold weather.'
<p><b>You say, </b>'pelt'
<br><b>Karg Icebear says </b>'Have you some polar bear pelts? You know I can furnish warm cloaks from them, and for you I will do it for the measly sum of 5 platinum pieces.'
<p><b>You say, </b>'werewolf'
<br><b>Karg Icebear says </b>'Werewolf?! I have not seen a werewolf in years. Have you slain one and collected its [skin] or [claws]?'
<p><b>You say, </b>'skin'
<br><b>Karg Icebear says </b>'You have managed to procure a werewolf skin?? Amazing! Well then, I will let you know that for a fee of 100 platinum, I can craft a hearty cloak for you if you leave the skin and the coin with me.'
<p><b>You say, </b>'claw'
<br><b>Karg Icebear says </b>'Oh, a werewolf claw? If you were to give me the claw and 75 platinum, I could craft excellent gauntlets.'
<p><b>You give Karg Icebear : </b><a href=http://phobos/eq/item.php?id=13761>Polar Bear Skin</a>
<p><b>You give Karg Icebear : </b><a href=http://phobos/eq/item.php?id=13714>Werewolf Pelt</a>
<p><b>You give Karg Icebear : </b><a href=http://phobos/eq/item.php?id=13715>Werewolf Claws</a>
</td></tr></table>