<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13244>One Quarter of Elixir</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13245>Empty Bottle of Elixir</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a><li><a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a><li><a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a><li><a href=http://phobos/eq/faction.php?id=361>Wolves of the North</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Megan OReilly says </b>'Brrrr.. It.. Is sooo.. c-cold!! I never.. sh-should've j-joined.. the.. the W-wolves of the N-north!!'
<p><b>You give Megan OReilly : </b><a href=http://phobos/eq/item.php?id=13244>One Quarter of Elixir</a>
<br><b>Megan OReilly says </b>'Oh thank you. Sorry, but the bottle is empty now. I hope you did't need any. Take the empty bottle back to Dargon. He may refill it for you.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=361>Wolves of the North</a> has gotten better.</font>
<br><b>Megan OReilly gives you : </b><a href=http://phobos/eq/item.php?id=13245>Empty Bottle of Elixir</a>
</td></tr></table>