<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=14360>Staff of the Wheel</a><li><a href=http://phobos/eq/item.php?id=14361>Star of Eyes</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17510>A glowing chest</a><li><a href=http://phobos/eq/item.php?id=18031>Tome of the Wheel</a><li><a href=http://phobos/eq/item.php?id=11880>Rune of Frost</a><li><a href=http://phobos/eq/item.php?id=11881>Rune of the Astral</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Sulgar says </b>'Greetings. I am searching for the [wheel of Tarton]. If you will assist me I will provide you with [runes] to create a powerful spell.'
<p><b>You say, </b>'runes'
<br><b>Sulgar says </b>'I have these runes, Rune of Frost and Rune of the Astral, which can be combined to produce a powerful spell that can call down destruction from the heavens. I will give them to you in exchange for the Staff of the Wheel and Star of Eyes'
<p><b>You say, </b>'case'
<br><b>Sulgar says </b>'You can use this case to reassemble the wheel. It has been infused with energy to combine the spokes. You will need to work quickly though or it will consume itself.'
<br><b>Sulgar gives you : </b><a href=http://phobos/eq/item.php?id=17510>A glowing chest</a>
<p><b>You say, </b>'wheel'
<br><b>Sulgar says </b>'The wheel was broken into several pieces and scattered throughout the world. This book will give you clues as to their whereabouts. Once you gather all the pieces, they can be reassembled in a special [case]'
<br><b>Sulgar gives you : </b><a href=http://phobos/eq/item.php?id=18031>Tome of the Wheel</a>
<p><b>You give Sulgar : </b><a href=http://phobos/eq/item.php?id=14360>Staff of the Wheel</a>, <a href=http://phobos/eq/item.php?id=14361>Star of Eyes</a>
<br><b>Sulgar says </b>'Wonderful, you have brought me the Wheel. Here is the reward I promised you.'
<br><b>Sulgar gives you : </b><a href=http://phobos/eq/item.php?id=11880>Rune of Frost</a>
<br><b>Sulgar gives you : </b><a href=http://phobos/eq/item.php?id=11881>Rune of the Astral</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Sulgar says </b>'I have no interest in these items.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>