<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13241>Full Bottle of Elixir</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13242>One Quarter of Elixir</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a><li><a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a><li><a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a><li><a href=http://phobos/eq/faction.php?id=361>Wolves of the North</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Talin O-Donal says </b>'Brrrrrr!! Grr.. Grreetings. It is freezing out here!!'
<p><b>You give Talin O-Donal : </b><a href=http://phobos/eq/item.php?id=13241>Full Bottle of Elixir</a>
<br><b>Talin O-Donal says </b>'Mmmm.. I feel much warmer. Thank you. You should now find Bryndin McMill. He could use a swig also. I saw him hanging around two other guards.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=213>Merchants of Halas</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=294>Shamen of Justice</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=361>Wolves of the North</a> has gotten better.</font>
<br><b>Talin O-Donal gives you : </b><a href=http://phobos/eq/item.php?id=13242>One Quarter of Elixir</a>
</td></tr></table>