<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10528>Shadowed Ball</a><li><a href=http://phobos/eq/item.php?id=10556>A Barbarian Head</a><li><a href=http://phobos/eq/item.php?id=1347>Warthread Kilt</a><li><a href=http://phobos/eq/item.php?id=18797>A tattered note</a><li><a href=http://phobos/eq/item.php?id=18798>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18797>A tattered note</a><li><a href=http://phobos/eq/item.php?id=18798>A tattered note</a><li><a href=http://phobos/eq/item.php?id=2365>Tishan's Kilt</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Trankia says </b>'Hmmph.'
<p><b>You say, </b>'avenge your brother'
<br><b>Trankia says </b>'My brother was part of a raiding party that adventured into the Caverns of Guk. Somewhere within he was betrayed and left for dead by the dastardly brother of Karg IceBear - Martar. I want you to find me what remains of my brothers body and bring it back to me. I am told that he died within a mine shaft.'
<p><b>You give Trankia : </b><a href=http://phobos/eq/item.php?id=10528>Shadowed Ball</a>
<br><b>Trankia says </b>'You must be another one from Vilissia. I will tell you what I tell all the others--you must help me [avenge] my [brother] before I will help you attain Tishan's Kilt.'
<br><b>Trankia gives you : </b><a href=http://phobos/eq/item.php?id=18797>A tattered note</a>
<p><b>You give Trankia : </b><a href=http://phobos/eq/item.php?id=10556>A Barbarian Head</a>
<br><b>Trankia says </b>'Oh Wulfthan, look what has become of you. I told you that you should not have trusted Martar.  [Your Name], as a final service, I want you to kill Martar IceBear for me. He is known to roam these parts. Bring me the Warthread Kilt that he wears and my two reminder notes, and I will give to you Tishan's Kilt. '
<br><b>Trankia gives you : </b><a href=http://phobos/eq/item.php?id=18798>A tattered note</a>
<p><b>You give Trankia : </b><a href=http://phobos/eq/item.php?id=18798>A tattered note</a>, <a href=http://phobos/eq/item.php?id=1347>Warthread Kilt</a>, <a href=http://phobos/eq/item.php?id=18797>A tattered note</a>
<br><b>Trankia says </b>'Thank you for avenging my brother's death, friend.  Here is your reward.'
<br><b>Trankia gives you : </b><a href=http://phobos/eq/item.php?id=2365>Tishan's Kilt</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>