<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Tundra Jack says </b>'Greetings .'
<p><b>You say, </b>'sweaty shirt'
<br><b>Tundra Jack says </b>'I would give it to you, but I'm afraid Iceberg here is using it as a collar now. I think you might be able to distract him with some [Lion Roast] if you give it to him.'
<p><b>You say, </b>'lion roast'
<br><b>Tundra Jack says </b>'Yes, that is Iceberg's favorite snack. I think Teria O'Danos in Halas gets a shipment every month. You might want to talk to her.'
</td></tr></table>