<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18205>Guild Summons</a><li><a href=http://phobos/eq/item.php?id=18051>Stupendous Tome</a><li><a href=http://phobos/eq/item.php?id=5126>Hero's Khukri</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=5120>Pawn's Khukri</a><li><a href=http://phobos/eq/item.php?id=5128>Lord of Pain's Khukri</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a><li><a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Arch Duke Xog says </b>'These are the sacred unholy grounds of the Crusaders of Greenmist and the Scaled Mystics.  If you do not belong to us, you must leave this temple at once or learn great suffering in the name of Cazic-Thule.'
<p><b>You say, </b>'greenmist'
<br><font color=green><b>Arch Duke Xog </b>appears surprised at your words. 'You know of Greenmist? The Unholy Khukri of Rile? We once had knowledge of this weapon, but when our great cities were destroyed in 1056 A.G., so, too, were all the great libraries. We lost all records. An explorer named [Argest] claimed to have found one library still intact. Pure babble.'</font>
<p><b>You say, </b>'argest'
<br><b>Arch Duke Xog says </b>'Once a Lord of Pain, Argest is now a great explorer. No lizard has seen more of Kunark than he. He returned one season ago to tell tales of an [ancient library]. He said that he believed that there he would find a tome which would reveal the location of the ancient crusader weapon, Greenmist.'
<p><b>You say, </b>'ancient library'
<br><b>Arch Duke Xog says </b>'There are many ancient libraries yet to be discovered. Our once great cities have been decimated, if not by our foes, then by nature itself. Within the outlands are many ruins which have yet to reveal themselves. We look forward to the discovery of these ruins by such explorers as Lord Argest the Great. If only we knew [where] he was...'
<p><b>You say, </b>'where'
<br><font color=green><b>Arch Duke Xog </b>becomes despondent at your question. 'Alas, our chance of locating Greenmist is lost as long as Argest remains missing. Reports have come in from the Legion's deep range patrols that he may be in the Frontier Mountain range. At least, that is where the patrol captain found Argest's walking staff. He might have been captured, killed or even digested!!'</font>
<p><b>You give Arch Duke Xog : </b><a href=http://phobos/eq/item.php?id=18205>Guild Summons</a>
<br><b>Arch Duke Xog says </b>'Welcome into our brotherhood. Know you that our way is the way of pain. Do as we say and you shall climb the rungs of knighthood. Listen well to the Lords of Pain within this temple and follow the words of the hierophants, for Cazic-Thule speaks to us through them. Take this khukri. It is the chosen weapon of the Crusaders and can deliver great pain unto our foes. Go now and learn our ways. Seek out Lord Gikzic.'
<br><b>Arch Duke Xog gives you : </b><a href=http://phobos/eq/item.php?id=5120>Pawn's Khukri</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<p><b>You give Arch Duke Xog : </b><a href=http://phobos/eq/item.php?id=18051>Stupendous Tome</a>, <a href=http://phobos/eq/item.php?id=5126>Hero's Khukri</a>
<br><b>Arch Duke Xog says </b>'A legible tome of the scrolls of Vok Na Zov! What a find this is!! May the unholy curses of Cazic flow through you. Please accept the weapon of a Lord of Pain. To abandon it is to abandon our ways and earn yourself the hatred of our order.'
<br><b>Arch Duke Xog gives you : </b><a href=http://phobos/eq/item.php?id=5128>Lord of Pain's Khukri</a>
<br><b>You receive </b> 4pp
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>