<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Drill Master Dal says </b>'Yes. yes!!  What do I have here?!!  Another [new recruit]?  If so. then speak up!  If not. then leave and do not waste my time nor risk your life.  I also seek a [legion soldier] if you be one.'
<p><b>You say, </b>'i am a new recruit'
<br><b>Drill Master Dal says </b>'Hiss..  Serve the Legion of Cabilis further and you may get what you seek.'
<br><b>Drill Master Dal says </b>'Yes.  You have the look of the Partisan.  I trust you have begun your blacksmith training.  If not. then do so.  Also. you should read all the books available to you in Fortress Talishan.  We are not dimwitted broodlings here.  You shall need the knowledge soon. That. or a coffin.  Ha!!  Here is your task. are you [ready for your task]?'
<p><b>You say, </b>'i am a legion soldier'
<br><b>Drill Master Dal says </b>'Hiss..  Serve the Legion of Cabilis further and you may get what you seek.'
<br><b>Drill Master Dal says </b>'Good news to my ears!!  I seek to prove to the War Baron that the infamous forsaken band of thieves who call themselves Marrtail's Marauders are operating within earshot of our city.  You must bring me proof that you encountered no fewer than four of these thieves.  Do so and I shall offer you an armor item unavailable to most.'
<p><b>You say, </b>'I am ready for my task'
<br><b>Drill Master Dal says </b>'Yes. yes!!  It does not matter.  You must be ready.  I will hand you the Partisan pack.  Into it you shall combine one giant blood sac of the giant leech;  scout beads from a goblin scout; one sabertooth kitten canine and finally. three bone shards from decaying skeletons.  Hopefully. you will survive your attempt to obtain these items.  Return the full Partisan pack and you shall be rewarded with a curscale shield.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>