<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Drill Master Kyg says </b>'Welcome. Welcome!!  Time to train.  Time to fight.  Time to serve the Iksar Empire.  You will need weapons.  I have the [footman pike] for all new recruits to earn.'
<p><b>You say, </b>'what footman pike?'
<br><b>Drill Master Kyg says </b>'A footman pike is what you need.  A footman pike is what you get. but earn it you will.  You must [slay many beasts] to prove to us that you are a true warrior.  Fail and you will be exiled to live with the Forsaken.'
<p><b>You say, </b>'I will slay many beasts'
<br><b>Drill Master Kyg says </b>'Yes.  You will slay or you will be slain.  Take this footman's pack and fill it you will.  Fill it with [weapons of our foes].  When all are combined. the full footman's pack shall be returned to me along with your militia pike.  Do this and earn your footman pike and then we may have a true mission for you.'
<p><b>You say, </b>'what weapons of our foes?'
<br><b>Drill Master Kyg says </b>'Yes.  You need to know the weapons required.  Fill the pack with javelins.  Froglok bounder and goblin hunter javelins.  Two of each.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>