<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18203>Guild Summons</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=5130>Partisan's Pike</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Drill Master Vygan says </b>'I am a Drill Master of the Legion of Cabilis.  I have no time for idle chitchat.  Be off if you were not summoned to this fortress!  Find that guild which was chosen for you as an egg.'
<p><b>You give Drill Master Vygan : </b><a href=http://phobos/eq/item.php?id=18203>Guild Summons</a>
<br><b>Drill Master Vygan says </b>'Thanks.'
<br><b>Drill Master Vygan gives you : </b><a href=http://phobos/eq/item.php?id=5130>Partisan's Pike</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>