<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18204>Guild Summons</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=4190>Shackle of Dust</a></ul></td><td><hr><b>When Grand Master Glox spawns </b>
<p><b>You say, </b>'hail'
<br><font color=green><b>Grand Master Glox </b>shows no reaction to your greeting.</font>
<p><b>You say, </b>'what trial of agility'
<br><b>Grand Master Glox says </b>'I knew you were not the whiff others claimed you to be, are you sure you are [ready] to be tested in agility?'
<p><b>You say, </b>'i am ready'
<br><b>Grand Master Glox says </b>'We shall spar then, I hope you are as prepared as you think you are.'
<br><font color=white><b>The Player moves to zone 106 at -190.9,1089.8,-25.2</b></font>
<p><b>You give Grand Master Glox : </b><a href=http://phobos/eq/item.php?id=18204>Guild Summons</a>
<br><font color=green><b>Grand Master Glox </b>breaks his meditation and quickly grabs your forearms. You feel the raw power in his heavily callused hands. Out of nowhere, his tail sweeps forward and places a shackle upon your wrist. He then points south towards Master Bain and returns to his meditation.</font>
<br><b>Grand Master Glox gives you : </b><a href=http://phobos/eq/item.php?id=4190>Shackle of Dust</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>