<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=30146>The Broken Glacier Souvenir Mug</a><li><a href=http://phobos/eq/item.php?id=12609>Cabilis Pale Ale</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12852>Foot of Candlestick</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Grype says </b>'I will give you the Foot if you get the stein from that Halfling rogue, all in black, from Firiona Vie.'
<p><b>You say, </b>'blue talon'
<br><font color=green><b>Grype </b>takes a swipe at you. 'We used to be the bruisers of the west side. We didn't take nothin' from no one!! Fist and mind was our motto. Now get lost before I introduce my fist to your face. Hmpf. Too late, I see.'</font>
<p><b>You give Grype : </b><a href=http://phobos/eq/item.php?id=30146>The Broken Glacier Souvenir Mug</a>
<br><b>Grype says </b>'Well, as promised, here's your Foot of the candlestick.'
<br><b>Grype gives you : </b><a href=http://phobos/eq/item.php?id=12852>Foot of Candlestick</a>
<p><b>You give Grype : </b><a href=http://phobos/eq/item.php?id=12609>Cabilis Pale Ale</a> x4
<br><font color=green><b>Grype </b>swallows the whole bottle in one gulp. 'Here, go buy yourself a brain. What?!! You expecting something? How about this.. <BUUURRRPPPP!!> Thanks for helping me get through my dry spell, croak!! Never mess with a Blue Talon!!</font>
<br><b>You receive </b> 1cp
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>