<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18272>Rites of Exoneration</a><li><a href=http://phobos/eq/item.php?id=24770>Filled Penance Bag</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18271>A Ragged Book</a><li><a href=http://phobos/eq/item.php?id=5140>Iron Cudgel of the Petitioner</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Hierophant Zand says </b>'Welcome to the Temple of Terror, young one. May the pain of the ancients guide you. Have you lost your Iron Cudgel of the Petitioner?'
<p><b>You say, </b>'no'
<br><b>Hierophant Zand says </b>'The Temple of Terror requires all young Scaled Mystics to wear the symbol of their station. Wear it with pride in these halls to display the rank you have attained. Go now, and serve The Faceless.'
<p><b>You say, </b>'yes'
<br><font color=green><b>Hierophant Zand </b>shakes his head and growls. 'That is not good, broodling... Not good at all. You will need to take this note and seek out the Toilmaster immediately. Read it on the way and hope that your incompetence can be overcome. The Crusaders of Greenmist have a pit meant for you, should this prove to be impossible.</font>
<br><b>Hierophant Zand gives you : </b><a href=http://phobos/eq/item.php?id=18271>A Ragged Book</a>
<p><b>You give Hierophant Zand : </b><a href=http://phobos/eq/item.php?id=18272>Rites of Exoneration</a>, <a href=http://phobos/eq/item.php?id=24770>Filled Penance Bag</a>
<br><font color=green><b>Hierophant Zand </b>takes the bag and tome from you and in return gives you the item that you have been thinking of all of this time.</font>
<br><b>Hierophant Zand says </b>'Lucky you. You have earned a second chance. Praise Cazic-Thule!'
<br><b>Hierophant Zand gives you : </b><a href=http://phobos/eq/item.php?id=5140>Iron Cudgel of the Petitioner</a>
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Hierophant Zand says </b>'This isn't what I asked for.'
</td></tr></table>