<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12403>Full Component Mortar</a><li><a href=http://phobos/eq/item.php?id=3895>A note to Oxyn</a><li><a href=http://phobos/eq/item.php?id=3886>Chunk of Tynnonium</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17020>Component Mortar</a><li><a href=http://phobos/eq/item.php?id=12406>Cursed Wafers</a><li><a href=http://phobos/eq/item.php?id=3892>Bottle of Liquid Deklium</a><li><a href=http://phobos/eq/item.php?id=3893>Note to Librarian Zimor</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=282>Scaled Mystics</a><li><a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a><li><a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Hierophant Oxyn says </b>'Greetings, and may the pain of the ancients guide you. You have come to us for guidance, have you not? We are the Hierophants of Cabilis and we guide the young Scaled Mystics. All petitioners shall speak with me of [temple tasks].'
<p><b>You say, </b>'temple tasks'
<br><b>Hierophant Oxyn says </b>'The Temple of Terror requires all young Scaled Mystics to [perform daily tasks]. The tasks are necessary to the upkeep of our order as well as that of our brothers, the Crusaders of Greenmist.'
<p><b>You say, </b>'perform daily tasks'
<br><b>Hierophant Oxyn says </b>'We require many components for various rituals. Take this component mortar and fill it with the following items -- foraged [mud crabs], two small mosquito wings and one portion of bone chips. You must then use the pestle and combine all the components. When you have a full component mortar, you may return to me and I shall pay you your wages, but most importantly, you shall prove your devotion to the Scaled Mystics.'
<br><b>Hierophant Oxyn gives you : </b><a href=http://phobos/eq/item.php?id=17020>Component Mortar</a>
<p><b>You say, </b>'mud crabs'
<br><b>Hierophant Oxyn says </b>'Mud crabs are tiny crustaceans which live along the mudcaked shores of the Lake of Ill Omen. You can forage for them and find a handful of them at a time.'
<p><b>You say, </b>'lost skulls'
<br><b>Hierophant Oxyn says </b>'You must have heard of the Trilac Brotherhood's disappearance. They are the skulls of three soon-to-be ancients. They were taken from this temple by a silent intruder. Crusaders are always on duty. I do not know how they got into our vault. Every petitioner is ordered to search for the three skulls and return them to me along with their petitioner cudgel and then they shall become clairvoyants.'
<p><b>You say, </b>'Iron Cudgel of the Clairvoyant'
<br><font color=green><b>Hierophant Oxyn </b>shakes his head and waves a finger in your face. 'If you are looking to be handed the Iron Cudgel of the Clairvoyant then you are sadly mistaken. Perhaps if you were to gather a few [lost skulls] for the temple we may find you worthy to wield one.</font>
<p><b>You say, </b>'liquid'
<br><b>Hierophant Oxyn says </b>'The bottle contains deklium in a liquid solution. The metal of prophecy has been determined to rest in a mass of living earth. Our scholars have written of a mass of ore that fell from the heavens. This ore was used in the creation of a blade of our father, Rile. We have been filled with visions of this blade. I have seen it in the hands of our Crusaders as they march towards the new age of Greenmist! Seek out the corrupted earth that guards the interlopers. We have an alchemist near there. He will be able to use the deklium to determine which golem contains the metal. Take care to go in force. I sense that there will be a battle.'
<p><b>You give Hierophant Oxyn : </b><a href=http://phobos/eq/item.php?id=12403>Full Component Mortar</a>
<br><b>Hierophant Oxyn says </b>'We appreciate your service. Take a few copper for your deed as well as some of our cursed waters. They will provide you with nourishment. As for future tasks, we are searching for a few [lost skulls] and I am sure you are searching for your [Iron Cudgel of the Clairvoyant]. I also hear that the furscales are in need of some broodlings to do some manual labor. Tell them Oxyn sent you.'
<br><b>Hierophant Oxyn gives you : </b><a href=http://phobos/eq/item.php?id=12406>Cursed Wafers</a>
<br><b>You receive </b> 3cp
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=282>Scaled Mystics</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<p><b>You give Hierophant Oxyn : </b><a href=http://phobos/eq/item.php?id=3895>A note to Oxyn</a>
<br><font color=green><b>Hierophant Oxyn </b>takes the note and begins to howl into the air! 'The visions are true! The new prophecy begins today, Crusader,' the mystic growls with pleasure. He quickly turns and takes a bottle of murky liquid from one of his potion bags and hands it to you. 'Take this and keep it safe. Our visions have told of this day. We have been able to learn of the metal of prophecy. This [liquid] will help us to locate its true resting place!</font>
<br><b>Hierophant Oxyn gives you : </b><a href=http://phobos/eq/item.php?id=3892>Bottle of Liquid Deklium</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<p><b>You give Hierophant Oxyn : </b><a href=http://phobos/eq/item.php?id=3886>Chunk of Tynnonium</a>
<br><font color=green><b>Hierophant Oxyn </b>holds the ore in his hands and begins to chant. His eyes go white as he raises the chunk of ore above his head. He lowers his arms and shakes his head for a moment. His eyes return to their normal state as they focus on you. The shaman hands you the ore and says, 'Seek out the creator of Rile's blade. He is still on this plane. I have felt his torment. Take this note to Librarian Zimor. He learned a great deal from the tome and can instruct you further.'</font>
<br><b>Hierophant Oxyn gives you : </b><a href=http://phobos/eq/item.php?id=3893>Note to Librarian Zimor</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Hierophant Oxyn says </b>'I don't need that.'
</td></tr></table>