<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12655>Full Curskin Bag</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17992>Empty Curskin Bag</a><li><a href=http://phobos/eq/item.php?id=4277>Curscale Sleeves</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=30>Cabilis Residents</a><li><a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Klok Mugruk says </b>'Welcome to my shop, sss. Only the finessst I have. I make for you jussst as I make for the emperor's harem. Many [bristle silk] garmentsss do they need. Ssss.. Lucky man, the emperor isss.'
<p><b>You say, </b>'bristle silk'
<br><b>Klok Mugruk says </b>'What is bristle silk?!! Huh? Where have you been living? Under the rocksss.. Nahh. I sssee. You are a broodling from the common ssstock. You could never afford bristle silk nor the affectionss of those who drape themselves with it. Still, commons have much ssservice to offer. Maybe you would like to earn some [curscale armor]. Hmm?'
<p><b>You say, </b>'curscale armor'
<br><b>Klok Mugruk says </b>'Curscale armor? I make thisss crude armor from the broodlings of the scaled wolves. I use the ssskins of the pupsss and cubs. Those ssskins are ssstill young and thin and are bessst for the young adventurers. I sssupply them to the Legion of Cabilisss, but for a [small service] I shall make them available to you.'
<p><b>You say, </b>'^small service$'
<p><b>You say, </b>'perform a small service'
<br><b>Klok Mugruk says </b>'Good. You take thisss pack and fill it all with scaled curskins. Only the pupsss and cubs of the scaled wolves shall do. They are not much for one sssuch as you. Combine all those ssskins and return the full curskin pack and I shall reward you with any available piece of curskin armor and a sssmall amount of coin. Mossst important is that you shall be proving your allegiance to all of Cabilisss.'
<br><b>Klok Mugruk gives you : </b><a href=http://phobos/eq/item.php?id=17992>Empty Curskin Bag</a>
<p><b>You give Klok Mugruk : </b><a href=http://phobos/eq/item.php?id=12655>Full Curskin Bag</a>
<br><b>Klok Mugruk says </b>'You are a good servant and a fine citizen. I have this piece of curscale armor available, but if it is not enough then perhaps I shall have another piece available if you were to [perform the small service] again.'
<br><b>Klok Mugruk gives you : </b><a href=http://phobos/eq/item.php?id=4277>Curscale Sleeves</a>
<br><b>You receive </b> 1gp 1sp 9cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=30>Cabilis Residents</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>