<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12450>Sharp Cutting Disk</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12445>Thin Sliced Froglok Meat</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Klok Ephmir </b>stares at you with a wicked smirk. 'So you share the Brood's love of frogloks, do you? Alive, they provide much trouble. Dead, they provide much delight. I have found many uses for the frogloks. From fine meat to fine mats. Be sure to ask if you do not see something you desire.'</font>
<p><b>You say, </b>'i need thinly sliced froglok'
<br><b>Klok Ephmir says </b>'I can provide thin sliced froglok meat, or rather, I used to. First I need to [sharpen the dull cutting disk].'
<p><b>You say, </b>'sharpen.*disk'
<br><b>Klok Ephmir says </b>'That would be good. If you are a blacksmith, I am sure you can find a sharpening stone and bring life back in my disk. If you sharpen this I shall gladly provide you with some thin sliced froglok.'
<p><b>You give Klok Ephmir : </b><a href=http://phobos/eq/item.php?id=12450>Sharp Cutting Disk</a>
<br><font color=green><b>Klok Ephmir </b>takes the disk and attaches it to an odd device powered by a foot pedal. He takes a froglok leg and begins to slice it as chunks of gristle flies into your face. When he is done he hands you some thin sliced froglok. 'There you are. Run along.'</font>
<br><b>Klok Ephmir gives you : </b><a href=http://phobos/eq/item.php?id=12445>Thin Sliced Froglok Meat</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>