<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>Klok Poklon says </b>'Greetings, thirsty traveler. Pull up a stool and lay yer copper down. Its time to drink and be merry. Just dont get too merry or I will have to call the trooers.'
<p><b>You say, </b>'what of talon southpaw'
<br><font color=green><b>Klok Poklon </b>feints with two quick left hooks!!</font>
<br><b>Klok Poklon says </b>'Talon Southpaw. He had the fastest hands in the empire. I remember he once beat another lizard in an arm wrestling match. The amazing thing was, while he was gripping the croaks left hand, he left hooked him without losing his hold!! Thats quick!! I hear one of his treasured hands is in the possession of a monk called Master Rinmark.'
</td></tr></table>