<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12496>Chalp Diagram</a><li><a href=http://phobos/eq/item.php?id=5123>Knight's Khukri</a><li><a href=http://phobos/eq/item.php?id=1729>Charasis Tome</a><li><a href=http://phobos/eq/item.php?id=1730>Charasis Tome Copy</a><li><a href=http://phobos/eq/item.php?id=5124>Zealot's Khukri</a><li><a href=http://phobos/eq/item.php?id=7324>The Visceral Dagger</a><li><a href=http://phobos/eq/item.php?id=5125>Crusader's Khukri</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=5124>Zealot's Khukri</a><li><a href=http://phobos/eq/item.php?id=5125>Crusader's Khukri</a><li><a href=http://phobos/eq/item.php?id=5126>Hero's Khukri</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a><li><a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Lord Qyzar </b>looks upon you with a sneer. 'What is the year of our birth and who was our Father?'</font>
<p><b>You say, </b>'the year is 371 AG and our father is Rile'
<br><b>Lord Qyzar says </b>'You are a student of our ways? I would hope so. I seek a knight in search of a way to prove his allegiance and a way to earn his [zealot khukri].'
<p><b>You say, </b>'zealot khukri'
<br><b>Lord Qyzar says </b>'In search of a zealot khukri? I have heard much of your deeds to aid us. I offer it to you in exchange for your service. I have dispatched a knight named Grizzle to seek out the Kromdul fortress called Chalp. He was to secretly map Chalp and return with a [Chalp diagram]. He has yet to return. Perhaps you can [rescue Grizzle].'
<p><b>You say, </b>'chalp diagram'
<br><font color=green><b>Lord Qyzar </b>grimaces in pure disgust. 'I have been awaiting the Chalp diagram from a knight named Grizzle, but alas, he has proven himself weak. He has been taken prisoner by one of the Kromdul of Chalp. If only there were another knight I could send to [rescue Grizzle] and return the Chalp diagram...'</font>
<p><b>You say, </b>'rescue grizzle'
<br><b>Lord Qyzar says </b>'If you can find the knight in Chalp and have him hand you the Chalp diagram, you shall become a zealot and wield a zealot khukri. All I need are the Chalp diagram and your knight khukri.'
<p><b>You say, </b>'matter of betrayal'
<br><b>Lord Qyzar says </b>'One of our agents, a hero by the name of Goxnok, has found evidence that the book entitled 'Charasis' has been taken from this temple and is to be delivered to an unknown foe in the Outlands. Go at once to the lower levels of the temple and greet Goxnok. Hurry, before he departs!'
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=106301>an_Iksar_crusader</a></b> spawns (1000,-113,-23.9).</font>
<p><b>You say, </b>'visceral dagger'
<br><b>Lord Qyzar says </b>'The visceral dagger was an ancient torturing weapon. I do not know much of it other than that it was forged by a member of the Brood of Kotiz, but that was ages ago. He is surely dust by now.'
<p><b>You give Lord Qyzar : </b><a href=http://phobos/eq/item.php?id=5123>Knight's Khukri</a>, <a href=http://phobos/eq/item.php?id=12496>Chalp Diagram</a>
<br><b>Lord Qyzar says </b>'At last!! The Chalp diagram. I shall see that the emperor gets this at once. You have proven yourself more than just a mere knight, you are a zealot. Being new to the temple we have need of you in a [matter of betrayal].'
<br><b>Lord Qyzar gives you : </b><a href=http://phobos/eq/item.php?id=5124>Zealot's Khukri</a>
<br><b>You receive </b> 1pp 6gp
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<p><b>You give Lord Qyzar : </b><a href=http://phobos/eq/item.php?id=1730>Charasis Tome Copy</a>, <a href=http://phobos/eq/item.php?id=5124>Zealot's Khukri</a>, <a href=http://phobos/eq/item.php?id=1729>Charasis Tome</a>
<br><b>Lord Qyzar says </b>'Congratulations! You are now a true crusader, but there is no time for celebration. We have lost two of our operatives. Crusaders Golin and Fodcod were dispatched to seek out an ancient artifact, the [visceral dagger]. Where they have gone, I do not know. They have been gone far too long. Find them and return the dagger to me with your crusader khukri and you shall be a hero.'
<br><b>Lord Qyzar gives you : </b><a href=http://phobos/eq/item.php?id=5125>Crusader's Khukri</a>
<br><b>You receive </b> 2pp
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<p><b>You give Lord Qyzar : </b><a href=http://phobos/eq/item.php?id=7324>The Visceral Dagger</a>, <a href=http://phobos/eq/item.php?id=5125>Crusader's Khukri</a>
<br><font color=green><b>Lord Qyzar </b>gazes in astonishment at the dagger. 'Ahhh!! You have brought the sacred visceral dagger back to the Temple of Terror. Let all be aware that the great [Your Name] has returned to Cabilis a hero!! You now wield the weapon of a hero. Hail, [Your Name], hero of the Crusaders of Greenmist.</font>
<br><b>Lord Qyzar gives you : </b><a href=http://phobos/eq/item.php?id=5126>Hero's Khukri</a>
<br><b>You receive </b> 3pp
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>