<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12401>A Glowing Skull</a><li><a href=http://phobos/eq/item.php?id=5122>Squire's Khukri</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=5123>Knight's Khukri</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a><li><a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Lord Korzin says </b>'What is it you seek? [Eternal suffering]?'
<p><b>You say, </b>'eternal suffering'
<br><b>Lord Korzin says </b>'Then follow the words of Cazic-Thule and may his blessed curses rain upon your soul as they shall on all of his faithful servants. Were you [sent] to me by Gikzic?'
<p><b>You say, </b>'sent'
<br><b>Lord Korzin says </b>'Then you must be the squire who found the ancient tome, 'The Origins of Pain'. I can use a talented crusader such as yourself. In my dreams, Cazic-Thule has spoken to me. He instructed me to seek out the 'Skull of Torture' which was last reported to be within the torture tower of the ancient Lord of Pain, Kurn. Will you [accept the calling]?'
<p><b>You say, </b>'accept the calling'
<br><b>Lord Korzin says </b>'As if you had a choice. Seek out the tower of Kurn and find the Skull of Torture. You should be able to easily recognize this skull as it glows with the power of Cazic Thule. Return it to me with your squire's khukri and I shall reward you with the knight's khukri. Go at once.'
<p><b>You give Lord Korzin : </b><a href=http://phobos/eq/item.php?id=12401>A Glowing Skull</a>, <a href=http://phobos/eq/item.php?id=5122>Squire's Khukri</a>
<br><b>Lord Korzin says </b>'Excellent work! You are no squire. You are now a knight of the crusaders. Your next step shall be zealot. And every zealot wields a magical khukri.'
<br><b>Lord Korzin gives you : </b><a href=http://phobos/eq/item.php?id=5123>Knight's Khukri</a>
<br><b>You receive </b> 15gp
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>