<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12381>Full Pack of Sarnak Heads</a><li><a href=http://phobos/eq/item.php?id=5120>Pawn's Khukri</a><li><a href=http://phobos/eq/item.php?id=12382>Magically Locked Tome</a><li><a href=http://phobos/eq/item.php?id=5121>Knave's Khukri</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17017>Sarnak Head Pack</a><li><a href=http://phobos/eq/item.php?id=18229>A Page of A Tome</a><li><a href=http://phobos/eq/item.php?id=5121>Knave's Khukri</a><li><a href=http://phobos/eq/item.php?id=5122>Squire's Khukri</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a><li><a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Lord Gikzic says </b>'You dare to intrude upon the presence of a Lord of Pain?!  Such foolish acts can only be those of a knight in training.  Are you a [knight in training]?'
<p><b>You say, </b>'knight in training'
<br><b>Lord Gikzic says </b>'If you are a pawn, then let us begin with a simple test.  Complete the test and you shall be rewarded with a new khukri.  Do you [wish to perform the test of a pawn]?'
<p><b>You say, </b>'test of a pawn'
<br><b>Lord Gikzic says </b>'You shall carry this pack.  Within it you shall combine 4 sarnak hatchling heads. When you have the full sarnak head pack then you shall return it to me along with your pawn's khukri and I shall reward you with the khukri of a knave. Beware, for the sarnak are our most hated foes and even their whelps are quite formidable fighters. Be sure to seek out Klok Mugruk. He may have some curscale armor available.'
<br><b>Lord Gikzic gives you : </b><a href=http://phobos/eq/item.php?id=17017>Sarnak Head Pack</a>
<p><b>You say, </b>'greater concern'
<br><b>Lord Gikzic says </b>'A tome has been taken from us. An expeditionary unit was returning to Cabilis when they were overtaken by a band of froglok raiders. The odds were greatly in their favor, but our forces would soon cut them down. Then, as abruptly as the battle began, it came to an end. The frogs retreated. The only item they took was an ancient tome entitled 'The Origins of Pain'. What the frogs want with it is unknown to us. Will you [retrieve the tome]?'
<p><b>You say, </b>'retrieve the tome'
<br><b>Lord Gikzic says </b>'The tome ripped open in battle. There were but ten pages. This is one of those pages. You must find the remainder and the tome binder. Place the pages within the binder and once you combine them, the binder shall magically lock. Do not look upon the pages, for the words would bring a great madness upon you. Your task is simply to seek out the froglok raiders and return the magically locked tome to me. Return it with a knave's khukri and I shall give you a more powerful weapon.'
<br><b>Lord Gikzic gives you : </b><a href=http://phobos/eq/item.php?id=18229>A Page of A Tome</a>
<p><b>You give Lord Gikzic : </b><a href=http://phobos/eq/item.php?id=5120>Pawn's Khukri</a>, <a href=http://phobos/eq/item.php?id=12381>Full Pack of Sarnak Heads</a>
<br><b>Lord Gikzic says </b>'You have learned to behead your opponents with great precision. Take the khukri of the knave. It shall prove most formidable in combat when wielded by a young crusader. You may now assist us with a [greater concern] than your training.'
<br><b>Lord Gikzic gives you : </b><a href=http://phobos/eq/item.php?id=5121>Knave's Khukri</a>
<br><b>You receive </b> 1gp
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<p><b>You give Lord Gikzic : </b><a href=http://phobos/eq/item.php?id=5121>Knave's Khukri</a>, <a href=http://phobos/eq/item.php?id=12382>Magically Locked Tome</a>
<br><b>Lord Gikzic says </b>'You have done as instructed. You are wise to hand this tome to me. It could bring you nothing more than insanity. As your reward, you shall have the squire's khukri. Soon you shall wield the knight's khukri, but that is for another Lord of Pain to decide.'
<br><b>Lord Gikzic gives you : </b><a href=http://phobos/eq/item.php?id=5122>Squire's Khukri</a>
<br><b>You receive </b> 3gp
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>