<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12427>Full First Rite Pack</a><li><a href=http://phobos/eq/item.php?id=4190>Shackle of Dust</a><li><a href=http://phobos/eq/item.php?id=4191>Shackle of Clay</a><li><a href=http://phobos/eq/item.php?id=12428>Iksar Bandit Mask</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17026>First Rite Pack</a><li><a href=http://phobos/eq/item.php?id=4191>Shackle of Clay</a><li><a href=http://phobos/eq/item.php?id=4192>Shackle of Stone</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Master Raska says </b>'Hmmph!! Expect to be a great master such as I? Maybe. You still appear to be a [whiff].'
<p><b>You say, </b>'what is a whiff'
<br><b>Master Raska says </b>'A whiff is the sound of a tail striking air. A whiff is you. Inexperienced. I can help you, if you [want to earn the second shackle].'
<p><b>You say, </b>'i want to earn the second shackle'
<br><b>Master Raska says </b>'Then you shall perform the first rite. Take this pack. To the Outlands you will go. You will fill and combine the pack with one of each of the following: goblin scout beads, a large scorpion pincer, a froglok skipper skipping stone, and a sabertooth cub canine. Bring these to me and you shall prove yourself a monk.'
<br><b>Master Raska gives you : </b><a href=http://phobos/eq/item.php?id=17026>First Rite Pack</a>
<p><b>You say, </b>'shackle of stone'
<br><b>Master Raska says </b>'Interested in the shackle of stone are we? They are made for monks who have earned their first two shackles and are ready to climb up to the next rung. A monk who feels he is ready to wear the shackle of stone must first [perform the task of cleansing].'
<p><b>You say, </b>'i will perform the task of cleansing'
<br><b>Master Raska says </b>'Go forth to the outer gates and seek out the Iksar bandits. They have refused to bow to the will of the empire and shall pay dearly for their traitorous ways. They often wear bandit masks. If you return with two bandit masks and the shackles of dust and clay then I shall reward you with the shackle of stone.'
<p><b>You give Master Raska : </b><a href=http://phobos/eq/item.php?id=12427>Full First Rite Pack</a>
<br><b>Master Raska says </b>'You have succeeded, young [Your Name]! You have proven yourself a skilled monk. You will now wear the shackle of clay. You will now be required to increase your intensity of training in hopes that you may soon be able to earn your [shackle of stone].'
<br><b>Master Raska gives you : </b><a href=http://phobos/eq/item.php?id=4191>Shackle of Clay</a>
<p><b>You give Master Raska : </b><a href=http://phobos/eq/item.php?id=4190>Shackle of Dust</a>, <a href=http://phobos/eq/item.php?id=4191>Shackle of Clay</a>, <a href=http://phobos/eq/item.php?id=12428>Iksar Bandit Mask</a> x2
<br><b>Master Raska says </b>'You have done supremely, [Your Name]. You have earned your shackle of stone. Mistress Niska will now help you on your way to earning the shackle of rock. May the elements guide you to the next rung.'
<br><b>Master Raska gives you : </b><a href=http://phobos/eq/item.php?id=4192>Shackle of Stone</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>