<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18272>Rites of Exoneration</a><li><a href=http://phobos/eq/item.php?id=24770>Filled Penance Bag</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18271>A Ragged Book</a><li><a href=http://phobos/eq/item.php?id=5120>Pawn's Khukri</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Squire Gristle says </b>'Hail Broodling! When you walk the halls of this tower, you should always display the status that you have earned within our ranks. It brings me pride to see the might of the brood displayed by one such as you while I reflect here in the tower. Do you have the tool of your caste with you at this time?'
<p><b>You say, </b>'yes'
<br><b>Squire Gristle says </b>'Ah... Yes... very good! Continue to work at this pace and the enemies of the Greenmist will fall beneath the blades of Cazic-Thule! Now move out... To Victory!'
<p><b>You say, </b>'no'
<br><font color=green><b>Squire Gristle </b>shakes his head and growls. 'That is not good, broodling... Not good at all. You will need to take this note and seek out the Toilmaster immediately. Read it on the way and hope that your incompetence can be overcome. We do have a pit for you, should this prove to be impossible.</font>
<br><b>Squire Gristle gives you : </b><a href=http://phobos/eq/item.php?id=18271>A Ragged Book</a>
<p><b>You give Squire Gristle : </b><a href=http://phobos/eq/item.php?id=18272>Rites of Exoneration</a>, <a href=http://phobos/eq/item.php?id=24770>Filled Penance Bag</a>
<br><font color=green><b>Squire Gristle </b>takes the bag and tome from you and in return gives you the item that you have been thinking of all of this time.</font>
<br><b>Squire Gristle says </b>'Lucky you. You have earned a second chance. Praise Cazic-Thule!'
<br><b>Squire Gristle gives you : </b><a href=http://phobos/eq/item.php?id=5120>Pawn's Khukri</a>
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Squire Gristle says </b>'This isn't what I asked for.'
</td></tr></table>