<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12660>Busted Froglok Slave Shackles</a><li><a href=http://phobos/eq/item.php?id=18271>A Ragged Book</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=24767>Hammer of Exoneration</a><li><a href=http://phobos/eq/item.php?id=17091>Penance Bag</a><li><a href=http://phobos/eq/item.php?id=12689>Pile of Granite Pebbles</a><li><a href=http://phobos/eq/item.php?id=18272>Rites of Exoneration</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a><li><a href=http://phobos/eq/faction.php?id=30>Cabilis Residents</a><li><a href=http://phobos/eq/faction.php?id=282>Scaled Mystics</a><li><a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a><li><a href=http://phobos/eq/faction.php?id=317>Swift Tails</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>The Toilmaster says </b>'Do not bother me unless you wish to join the chain gang. Now go away or I shall have my slaves chop you as they chop this granite!'
<p><b>You say, </b>'hammer of exoneration'
<br><font color=green><b>The Toilmaster </b>hands you a massive hammer and says, 'So, you can read. Good for you. Don't think that you're going to make an impression on me with that rubbish. Let's see if you can handle this hammer like you can that book, whelp.'</font>
<br><b>The Toilmaster gives you : </b><a href=http://phobos/eq/item.php?id=24767>Hammer of Exoneration</a>
<p><b>You say, </b>'bag'
<br><font color=green><b>The Toilmaster </b>turns his head to focus on you and hands you a dusty bag. He then returns to looking into the distance, just over your left shoulder.</font>
<br><b>The Toilmaster gives you : </b><a href=http://phobos/eq/item.php?id=17091>Penance Bag</a>
<p><b>You say, </b>'granite pebbles'
<br><b>The Toilmaster says </b>'Ah. Looking for granite pebbles, are we? You must be a Swifttail. I am tired of doing your caste's work when you give nothing in return. Tell you what, I have lost many slaves to escape. If you bash their heads in with your many skills and return at least two busted froglok shackles I will give you one pile of granite pebbles.'
<p><b>You give The Toilmaster : </b><a href=http://phobos/eq/item.php?id=12660>Busted Froglok Slave Shackles</a> (x2)
<br><b>The Toilmaster says </b>'A deal is a deal. Here is one pile of granite pebbles. I hope you need more because I know there are more escaped froglok slaves.'
<br><b>The Toilmaster gives you : </b><a href=http://phobos/eq/item.php?id=12689>Pile of Granite Pebbles</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=30>Cabilis Residents</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=282>Scaled Mystics</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=317>Swift Tails</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 12cp
<p><b>You give The Toilmaster : </b><a href=http://phobos/eq/item.php?id=18271>A Ragged Book</a>
<br><font color=green><b>The Toilmaster </b>looks at the tome and speaks to you, scowling, 'Very well Broodling, I have a task for you. I should make you work at the feet of my Froglok Slaves, crushing granite, but the lore of the Brood has a specific rite for this situation. Take this book and learn the will of Cazic-Thule. Read it and ask me any questions that you may have before you start your penance. It would be a shame for you to fail at this task as well... though I wouldn't mind destroying you.</font>
<br><b>The Toilmaster gives you : </b><a href=http://phobos/eq/item.php?id=18272>Rites of Exoneration</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>