<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12466>Loose Scale</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12468>Shestar's Unfinished Coif</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Trooper Shestar says </b>'My father was a great blacksmith.  He taught me how to make great items such as the [Shestar scaled coif].  Alas, smithing was not my rebirth, but rather the life of a warrior.'
<p><b>You say, </b>'shestar scaled coif?'
<br><b>Trooper Shestar says </b>'The Shestar Scaled Coif was a light coif my father would fashion out of loose scales from the scaled wolves.  I have some scales on me and if you bring me three loose scales I will have enough to create the coif for you, but I require you to also pay a fee of five gold.'
<p><b>You give Trooper Shestar : </b><a href=http://phobos/eq/item.php?id=12466>Loose Scale</a> x3
<br><font color=green><b>Trooper Shestar </b>quickly inserts the scales into a half finished coif and hands you the coif. 'I am afraid that is not enough and I cannot possibly complete the task while on duty. You must go and find an additional three Scaled Wolf Scales and take them, along with the Unfinished Coif, to the nearest forge and complete the smithing yourself. I hope you are a blacksmith.'</font>
<br><b>Trooper Shestar gives you : </b><a href=http://phobos/eq/item.php?id=12468>Shestar's Unfinished Coif</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>