<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12439>Froglok Tad Tongue</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a><li><a href=http://phobos/eq/faction.php?id=30>Cabilis Residents</a><li><a href=http://phobos/eq/faction.php?id=282>Scaled Mystics</a><li><a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a><li><a href=http://phobos/eq/faction.php?id=317>Swift Tails</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Captain Nedar says </b>'Come to serve the garrison? Good. I aim to offer a reward for the return of four froglok tad tongues. Best if we handle the pesky critters before they grow too big and too numerous.'
<p><b>You give Captain Nedar : </b><a href=http://phobos/eq/item.php?id=12439>Froglok Tad Tongue</a> x4
<br><b>Captain Nedar says </b>'Well done. It is good to serve the Warlord. Here is a small reward befitting such a small task.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=193>Legion of Cabilis</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=30>Cabilis Residents</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=282>Scaled Mystics</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=62>Crusaders of Greenmist</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=317>Swift Tails</a> has gotten better.</font>
<br><b>You receive </b> 6cp
<br><font color=yellow>You gain experience!!</font>
<br><b>Captain Nedar says </b>'I have no need for this item [Your Name], you can have it back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>