<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19030>Crate of Teir`Dal Provisions</a><li><a href=http://phobos/eq/item.php?id=19028>Missing Teir`Dal Crate</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19029>Receipt for Provisions Crate</a><li><a href=http://phobos/eq/item.php?id=12499>Voucher of Service to Naythox</a></ul></td><td><p><b>You say, </b>'missing shipment'
<br><b>Dragoon Szorn says </b>'Seek out Ennixy and tell her [hate be my guide]. She typically works from her homeland in the steamfont mountains.'
<p><b>You give Dragoon Szorn : </b><a href=http://phobos/eq/item.php?id=19030>Crate of Teir`Dal Provisions</a>
<br><b>Dragoon Szorn says </b>'Finally!! We have been in dire need of these supplies for quite some time, [Your Name]!  Here is the receipt for the shipment. The last shipment never made it here and there is an item of great importance stored in the lost crate. Before you return to Neriak, your services are needed to retrieve our [missing shipment]. I command your obedience as is my right as a dragoon of Naythox Thex's personal regime.'
<br><b>Dragoon Szorn gives you : </b><a href=http://phobos/eq/item.php?id=19029>Receipt for Provisions Crate</a>
<br><b>You receive </b> 1pp
<p><b>You give Dragoon Szorn : </b><a href=http://phobos/eq/item.php?id=19028>Missing Teir`Dal Crate</a>
<br><b>Dragoon Szorn says </b>'What is this!! The items of importance have been removed from the crate!! This is most unfortunate. However, you have done well in your service to the Teir'Dal Empire. Take this voucher of services rendered under the command of Naythox Thex back to Ithvol along with the head of that slain Fier'Dal, the receipt for the provisions, and your disciple symbol of Innoruuk.'
<br><b>Dragoon Szorn gives you : </b><a href=http://phobos/eq/item.php?id=12499>Voucher of Service to Naythox</a>
<br><b>You receive </b> 1pp
<br><b>Dragoon Szorn says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>