<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Who is the scalekeeper?'
<br><b>Grynnaf Einoom says </b>'Ahh...Ye be lookin' for Nortlav then. Nortlav is a strong fella. Ye dunna want to mess with the likes of him. He's known as a dragonslayer. I heard that he keeps the scales of the dragons he's slain. Yer not impressed eh? All the dragons he's killed have died by the blade of a [rusty weapon].'
<p><b>You say, </b>'What rusty weapon?'
<br><b>Grynnaf Einoom says </b>'Aye. I dunno know why he does what he does. But every dragon he's killed died by the likes of a rusty weapon. I dunno where he is now. but I heard he can be found in the depths of Norrath. surrounded by darkness.'
</td></tr></table>