<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Anario Dirkog says </b>'Hello there [Your Name]. Might you be interested in helping us make a [delivery].'
<p><b>You say, </b>'what delivery'
<br><b>Anario Dirkog says </b>'We have a barrel of brew that we must deliver to Ryann Desgrey. We've been meaning to deliver it. but haven't been able to. because Caelin's been feeling ill. But before you can deliver it I have to know that you're able to make the trek across these lands. Bring me back a Fungus Mushroom.''
</td></tr></table>