<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Atruelin Nobilis says </b>'Hello [Your Name]. What brings you here to [Dawnshroud]?'
<p><b>You say, </b>'I came to Dawnshroud to fight'
<br><b>Atruelin Nobilis says </b>'Dawnshroud is a crazy place. I suggest you travel with a good group here. it can get dangerous.''
<p><b>You say, </b>'what dawnshroud'
<br><b>Atruelin Nobilis says </b>'Dawnshroud is a crazy place. I suggest you travel with a good group here. it can get dangerous.''
</td></tr></table>