<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=30173>Gant's Remains</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=29897>Tribal Warblade</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Bryce McFadden says </b>'What are you doing here? Can't you see we're trying to get some rest. It's not easy trying to find [Gant's Remains].'
<p><b>You say, </b>'what gant'
<br><b>Bryce McFadden says </b>'We're looking for Gant's Remains. We've heard that they can be found somewhere in the caves not to far from here. Though. it's not easy getting into those caves. Those dawnhoppers are a vicious bunch. Maybe you'd like to help us. If you can find Gant's Remains bring it back to me and you'll get a handsome reward.'
<p><b>You give Bryce McFadden : </b><a href=http://phobos/eq/item.php?id=30173>Gant's Remains</a>
<br><b>Bryce McFadden says </b>'Thanks!'
<br><b>Bryce McFadden gives you : </b><a href=http://phobos/eq/item.php?id=29897>Tribal Warblade</a>
</td></tr></table>