<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=6514>Peran's Orders</a><li><a href=http://phobos/eq/item.php?id=2692>Vampyre Ashes</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=7499>Combine Gladius</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=284>Seru</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Centurion Peran says </b>'Hey there. Come to take a swim?'
<p><b>You say, </b>'mission'
<br><b>Centurion Peran says </b>'Well, since you are so inquisitive I will tell you. The orders say to go to Maidens Eye and investigate reports of Vampyres in the area. Vampyres! Are the kidding?! I am just a Centurion! I know, I will continue to keep this area secure while you go investigate. Bring me sufficient proof of their existence in the area. Four piles of vampyre ashes should cover it. Well, get going! This mission isnt going to finish itself.'
<p><b>You give Centurion Peran : </b><a href=http://phobos/eq/item.php?id=6514>Peran's Orders</a>
<br><b>Centurion Peran says </b>'Bah, why do I always get stuck with the hard jobs. Here I am, out here patrolling the area in all this danger! They send me to even more threatening conditions? The life of a soldier is a hard one I tell ya! Oh well, off to do these orders I suppose. A shame no one will help me I am sure there is fame and fortune in the [mission]. More for me I suppose.'
<p><b>You give Centurion Peran : </b><a href=http://phobos/eq/item.php?id=2692>Vampyre Ashes</a> x4
<br><b>Centurion Peran says </b>'Hah! I knew that we could do it! Oh, you can take my weapon for helping me out again. I will just tell the Hand it was lost in battle. I guess that I better take this evidence back to the Hand, right after one more lap!.'
<br><b>Centurion Peran gives you : </b><a href=http://phobos/eq/item.php?id=7499>Combine Gladius</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=284>Seru</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>