<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=32170>Hunter's Pike</a><li><a href=http://phobos/eq/item.php?id=32300>A Gem-Inlaid Spear</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=32170>Hunter's Pike</a><li><a href=http://phobos/eq/item.php?id=17073>Dragen's Box</a><li><a href=http://phobos/eq/item.php?id=32189>Dragen's Runed War Spear</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Dragen Faux says </b>'I've been told that you may be the wolf slayer. I don't know though. You look a little scrawny to be the one. I suggest you prove it and bring me the Wolf Slayer. Once I've seen it we shall speak again.'
<p><b>You give Dragen Faux : </b><a href=http://phobos/eq/item.php?id=32170>Hunter's Pike</a>
<br><b>Dragen Faux says </b>'I'm sorry to have doubted you before. Please forgive me. My mind is not what it used to be. Since you are the wolf slayer perhaps you can help us find something. We've been unable to find it. If you can combine the Centerstone along with the Wolf Slayer in this box and bring back what you have. I should be able to reward you once we are through here.'
<br><b>Dragen Faux gives you : </b><a href=http://phobos/eq/item.php?id=32170>Hunter's Pike</a>
<br><b>Dragen Faux gives you : </b><a href=http://phobos/eq/item.php?id=17073>Dragen's Box</a>
<p><b>You give Dragen Faux : </b><a href=http://phobos/eq/item.php?id=32300>A Gem-Inlaid Spear</a>
<br><b>Dragen Faux says </b>'I knew you'd come through. This is going to make someone really happy. Take this for your troubles.'
<br><b>Dragen Faux gives you : </b><a href=http://phobos/eq/item.php?id=32189>Dragen's Runed War Spear</a>
</td></tr></table>