<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Glenda Melonfus says </b>'Hello there [Your Name]. Did Kanthek send you to me?''
<p><b>You say, </b>'yes kanthek sent me'
<br><b>Glenda Melonfus says </b>'Ahh. so you're interested in the Galorians then? Good to hear. The Galorians seem to be at war with the [Dawnhoppers]. The Galorians are known as the Sambata Tribe. I heard that they once lived in the caves behind us. but that all changed when the Dawnhoppers grew in numbers.''
<p><b>You say, </b>'what dawnhoppers?'
<br><b>Glenda Melonfus says </b>'The Dawnhoppers are the rockhoppers who inhabited Dawnshroud. They are a cruel bunch of hoppers. I swear. if I didn't know any better I'd think that the hoppers were out to kill every last galorian they encountered. They don't like 'em very much.''
</td></tr></table>