<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=4760>A Notorized Letter</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=4761>Journal of Broansas</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=152>House of Fordel</a><li><a href=http://phobos/eq/faction.php?id=140>Haven Defenders</a><li><a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Lieutenant Broansas says </b>'Greetings Stranger, is there something I can help you with? I would love to chat with you but i'm afraid I have to stay focused on the [case] I am investigating.'
<p><b>You say, </b>'case'
<br><b>Lieutenant Broansas says </b>'Well, [Your Name]. I'm monitoring a possible smugglers ring down there ahead of us in the distance. That group down there sure has a large shipment of goods and I intend to find out why.'
<p><b>You give Lieutenant Broansas : </b><a href=http://phobos/eq/item.php?id=4760>A Notorized Letter</a>
<br><b>Lieutenant Broansas says </b>'You are sent from Lady Mistala I see? Ah of course she needs my reports. I trust you will return these documents to Mistala at once. Here you are, and thank you for your help. I shall have more reports soon.'
<br><b>Lieutenant Broansas gives you : </b><a href=http://phobos/eq/item.php?id=4761>Journal of Broansas</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=152>House of Fordel</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=140>Haven Defenders</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=338>Traders of the Haven</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>