<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=31479>Fungus Covered Mushroom</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Reiker Rikes says </b>'I be Reiker Rikes! The fastest gnome in the woods!'
<p><b>You give Reiker Rikes : </b><a href=http://phobos/eq/item.php?id=31479>Fungus Covered Mushroom</a>
<br><font color=green><b>Reiker Rikes </b>grins. 'These should go nicely in my stew.'</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>