<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Ryann Desgrey says </b>'What brings to our outpost [Your Name]? Did you run into [Anario] by any chance?''
<p><b>You say, </b>'yes, anario sent me'
<br><b>Ryann Desgrey says </b>'Anario was supposed to make a delivery some time ago. but he hasn't shown up yet.''
<p><b>You say, </b>'who is anario'
<br><b>Ryann Desgrey says </b>'Anario was supposed to make a delivery some time ago. but he hasn't shown up yet.''
</td></tr></table>