<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>Sedona Raines says </b>'Don't be bothered by that crazy gnome. He won't hurt you. He's just a little out of it today. I'm sure if he had some [mushrooms] it'd calm him down.'
<p><b>You say, </b>'mushrooms'
<br><b>Sedona Raines says </b>'Reiker and his brother are always looking for fungus covered shrooms. They love to mix it into their stew. I must admit, it is very tasty.'
</td></tr></table>