<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=31782>Note to Wils</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=31781>Note to Carre</a><li><a href=http://phobos/eq/item.php?id=32170>Hunter's Pike</a></ul></td><td><p><b>You say, </b>'forest ravagers'
<br><b>Wils Otton says </b>'I can't  believe Jon mentioned that to you. I'll deal with him myself. If you want to help us kill the forest ravagers then you must first find Carre Harger. Bring this note to him. He'll get you started.''
<br><b>Wils Otton gives you : </b><a href=http://phobos/eq/item.php?id=31781>Note to Carre</a>
<p><b>You give Wils Otton : </b><a href=http://phobos/eq/item.php?id=31782>Note to Wils</a>
<br><b>Wils Otton says </b>'We've been hunting those wolves for a long time now. They killed many of my men. I'm glad to see that they are gone. Take this Hunter's Pike and get some good use out of it.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Wils Otton gives you : </b><a href=http://phobos/eq/item.php?id=32170>Hunter's Pike</a>
</td></tr></table>