<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Starzin the Sweet One says </b>'A warm hello to you. [Your Name]! Please make yourself at home here in the serene locale of Sunset Home. Here you can forget about the [queue]. and enjoy the company of your fellow guides!'
<p><b>You say, </b>'What queue?'
<br><b>Starzin the Sweet One says </b>'Queue? What queue? We don't need no stinkin' QUEUE!' Starzin glances around and giggles gleefully. then whispers. 'Just don't tell anyone else!'
</td></tr></table>