<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=31445>First Half of Vin`Pekir's Tome</a><li><a href=http://phobos/eq/item.php?id=31446>Second Half of Vin`Pekir's Tome</a><li><a href=http://phobos/eq/item.php?id=31443>First Half of Al`Tarlkal's Tome</a><li><a href=http://phobos/eq/item.php?id=31444>Second Half of Al`Tarlkal's Tome</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1325>Wreath of Nature</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>a gleaming sphere of light says </b>'I greet thee, [Your Name]. You will have to pardon my demeanour; I am afraid that I am not in the best of spirits. Recently yet another brother was taken from us by an evil unknown through the dark art of mind rending.'
<p><b>You say, </b>'evil'
<br><b>a gleaming sphere of light says </b>'Somewhere there exists a group of outcast phantasmists that use their powers solely to harvest pure evil. These masters of the mind are of an origin that we have yet to uncover, for they exist only in one's thoughts, slowly turning one insane from the horrors that pound through their mind.'
<p><b>You say, </b>'outcast'
<br><b>a gleaming sphere of light says </b>'These outcasts were once believe to be part of our circle before turning to the way of evil and using the mindbending abilities that they possess to take over those whose knowledge would benefit them most.'
<p><b>You say, </b>'abilities'
<br><b>a gleaming sphere of light says </b>'What these beguilers are capable of is unknown, but what we do know is that as each day passes we are all at risk from an attack that could very well end us. But there is a chance that if we could find the ancient tomes of their weaknesses, this evil could be stopped.'
<p><b>You say, </b>'tomes'
<br><b>a gleaming sphere of light says </b>'Legend exists that there are two lost tomes that cover the darker sides of mind control. These tomes were last believed to be possessed by mortals much like yourself that stumbled upon them not knowing what they possessed because they could not understand the unknown code the books are scribed in.'
<p><b>You say, </b>'code'
<br><b>a gleaming sphere of light says </b>'To prevent those that could not control the powerful abilities that these tomes described how to perform, these tomes were scribed of ancient language that not many could decifer. In search of someone that could assist them, these heros fell in the city of giants.'
<p><b>You say, </b>'language'
<br><b>a gleaming sphere of light says </b>'As I told you before, these books are distinctly coded to only be understood by those that have the abilities to perform and contain these magics. If these tomes were recovered it is very possible that I could decode them and develop an immunity to the mind altering attacks that I feel are upon us.'
<p><b>You give a gleaming sphere of light : </b><a href=http://phobos/eq/item.php?id=31445>First Half of Vin`Pekir's Tome</a>, <a href=http://phobos/eq/item.php?id=31446>Second Half of Vin`Pekir's Tome</a>, <a href=http://phobos/eq/item.php?id=31443>First Half of Al`Tarlkal's Tome</a>, <a href=http://phobos/eq/item.php?id=31444>Second Half of Al`Tarlkal's Tome</a>
<br><b>a gleaming sphere of light says </b>'In my hands I hold the teachings of those who gave their lives to produce a defense against the evils of mind control. For what you have done for me I cannot thank you enough; please accept this magical item as a reminder of my gratitude.'
<br><b>a gleaming sphere of light gives you : </b><a href=http://phobos/eq/item.php?id=1325>Wreath of Nature</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>a gleaming sphere of light says </b>'I have no need of this, friend.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>