<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=31435>Tome of Elemental Understanding</a><li><a href=http://phobos/eq/item.php?id=31436>Tome of Elemental Cognizance</a><li><a href=http://phobos/eq/item.php?id=31437>Tome of Elemental Contemplation</a><li><a href=http://phobos/eq/item.php?id=31438>Tome of Elemental Thought</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1224>Chord of Vines</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>a mosscovered treant says </b>'I welcome thee, [Your Name]. Is there something I can assist you with? I am afraid my tireless searching for the incantations is going to be endless.'
<p><b>You say, </b>'searching'
<br><b>a mosscovered treant says </b>'For quite some time now I have been seeking the teachings and scribings of Conjurers and Summoners of great power. As I continue my personal quest towards enlightenment there is absolute knowledge that evades me to this day.'
<p><b>You say, </b>'knowledge'
<br><b>a mosscovered treant says </b>'There is believed to be a tome that contained only the most spectacular and powerful summoning. Many great magicians of time passed were believed to be contributors to this magical tome. During the meeting called by these select few something went terribly wrong.'
<p><b>You say, </b>'wrong'
<br><b>a mosscovered treant says </b>'Of those in attendance, there was one servant of Innoruuk whose intentions were to steal the research and knowledge of his peers and use it to benefit himself and his Dark god. This selfishness led to numerous Intellectual conflicts and the Arch-Magi decided to go their separate ways, only to perish so close to the answer for which they sought.'
<p><b>You say, </b>'answer'
<br><b>a mosscovered treant says </b>'As time progressed the Elementalists continued their studies and research only to soon discover that there was always something missing. As each of them decended upon the Skyshrine they continued to look, not knowing that what they were searching for was each other.'
<p><b>You say, </b>'i will look'
<br><b>a mosscovered treant says </b>'That is a kind gesture indeed my friend, but be warned the journey that lies ahead of you will not be easy. But I have faith that this tome will one day be assembled as it was always meant to be and never was. I have faith that the pages do still exist, waiting to be unearthed.'
<p><b>You say, </b>'journey'
<br><b>a mosscovered treant says </b>'Search the lands for the remains of these Arch-mages, [Your Name]. Only when I have these teachings and am able to once again construct this tome may I bring myself closer to my Enlightenment and Arcane Mastery.'
<p><b>You give a mosscovered treant : </b><a href=http://phobos/eq/item.php?id=31435>Tome of Elemental Understanding</a>, <a href=http://phobos/eq/item.php?id=31436>Tome of Elemental Cognizance</a>, <a href=http://phobos/eq/item.php?id=31437>Tome of Elemental Contemplation</a>, <a href=http://phobos/eq/item.php?id=31438>Tome of Elemental Thought</a>
<br><font color=green><b>a mosscovered treant </b>whispers, like wind through the tree tops, as it speaks hushed words to the tree.</font>
<br><b>a mosscovered treant gives you : </b><a href=http://phobos/eq/item.php?id=1224>Chord of Vines</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>a mosscovered treant says </b>'I have no need of this, friend.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>