<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=31427>Fleshless Skull</a><li><a href=http://phobos/eq/item.php?id=31430>Corrupted Fauns Skin</a><li><a href=http://phobos/eq/item.php?id=31429>Corrupted Panther Skin</a><li><a href=http://phobos/eq/item.php?id=31428>Corrupted Unicorns Skin</a><li><a href=http://phobos/eq/item.php?id=31432>Idol of Corruption</a><li><a href=http://phobos/eq/item.php?id=31434>Idol of Decay</a><li><a href=http://phobos/eq/item.php?id=31431>Idol of Disease</a><li><a href=http://phobos/eq/item.php?id=31433>Idol of Erosion</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1209>Natures Defender</a><li><a href=http://phobos/eq/item.php?id=1223>Symbol of Tunarian Worship</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Guardian of Takish says </b>'Well met, [Your Name]. It is indeed a wondrous day to be serving the lady Tunare. If you know of any templars or knights, send them to me.'
<p><b>You say, </b>'knight'
<br><b>Guardian of Takish says </b>'Fortune smile upon me this day. It seems that the great corrupter and the Prince of Hate have been spreading seeds of corruption within this continent. Will you assist us to stop them?'
<p><b>You say, </b>'assist'
<br><b>Guardian of Takish says </b>'Seek out the corrupter of life in the plane of hate and slay him. He has been reported performing dark rituals upon various wildlife within the Wakening Lands during the late hours of night. Return to me any evidence that you may find.'
<p><b>You say, </b>'templar'
<br><b>Guardian of Takish says </b>'I require your aid. It seems the agents of corruption have supplied the followers of the warbringer with four idols that will help defoliate the Wakening Lands. Will you aid me, noble Templar?'
<p><b>You say, </b>'aid'
<br><b>Guardian of Takish says </b>'Excellent. Gather the four idols that are held in Kael and return them to me. I will then properly dispose of these foul creations.'
<p><b>You give Guardian of Takish : </b><a href=http://phobos/eq/item.php?id=31427>Fleshless Skull</a>, <a href=http://phobos/eq/item.php?id=31430>Corrupted Fauns Skin</a>, <a href=http://phobos/eq/item.php?id=31429>Corrupted Panther Skin</a>, <a href=http://phobos/eq/item.php?id=31428>Corrupted Unicorns Skin</a>
<br><b>Guardian of Takish gives you : </b><a href=http://phobos/eq/item.php?id=1209>Natures Defender</a>
<br><b>Guardian of Takish says </b>'I have no need for this, friend.'
<p><b>You give Guardian of Takish : </b><a href=http://phobos/eq/item.php?id=31432>Idol of Corruption</a>, <a href=http://phobos/eq/item.php?id=31434>Idol of Decay</a>, <a href=http://phobos/eq/item.php?id=31431>Idol of Disease</a>, <a href=http://phobos/eq/item.php?id=31433>Idol of Erosion</a>
<br><b>Guardian of Takish gives you : </b><a href=http://phobos/eq/item.php?id=1223>Symbol of Tunarian Worship</a>
<br><b>Guardian of Takish says </b>'May Tunare's blessing be upon thee! Here, take this item and use it wisely.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Guardian of Takish says </b>'I have no need for this, friend.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>