<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=31424>Grenk's Head</a><li><a href=http://phobos/eq/item.php?id=31425>Delar's Head</a><li><a href=http://phobos/eq/item.php?id=31426>Bjek's Head</a><li><a href=http://phobos/eq/item.php?id=31423>Derakor's Head</a><li><a href=http://phobos/eq/item.php?id=31419>Frostgiant Overseers Head</a><li><a href=http://phobos/eq/item.php?id=31420>Kallis' Head</a><li><a href=http://phobos/eq/item.php?id=31421>A bloody protector of Zek's Head</a><li><a href=http://phobos/eq/item.php?id=31422>A smashed protector of Zek's Head</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1208>Gloves of Earthcrafting</a><li><a href=http://phobos/eq/item.php?id=1207>Helm of the Tracker</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Tunarean Earthmelder says </b>'Hail, my friend. Unfortunately I cannot talk right now. The giants must be dealt with.'
<p><b>You say, </b>'giants'
<br><b>Tunarean Earthmelder says </b>'The giants are continuing to put forth efforts to encroach the lands blessed by Tunare. We need an outrider or preserver to aid us in our continued fight.'
<p><b>You say, </b>'preserver'
<br><b>Tunarean Earthmelder says </b>'Noble preserver, you will be needed to combat the priests of the warbringer. Scouts have reported three priests wandering the Wakening Lands in search of a site to build a shrine to their god. Seek them out, kill them, and bring their heads and those of anyone else involved.'
<p><b>You say, </b>'outrider'
<br><b>Tunarean Earthmelder says </b>'We have need of you to disrupt the construction efforts of the giants in the Wakening Land. Find the frost giant overseer, kill him and any others that are responsible for the building and bring back their heads.'
<p><b>You give Tunarean Earthmelder : </b><a href=http://phobos/eq/item.php?id=31424>Grenk's Head</a>, <a href=http://phobos/eq/item.php?id=31425>Delar's Head</a>, <a href=http://phobos/eq/item.php?id=31426>Bjek's Head</a>, <a href=http://phobos/eq/item.php?id=31423>Derakor's Head</a>
<br><b>Tunarean Earthmelder gives you : </b><a href=http://phobos/eq/item.php?id=1208>Gloves of Earthcrafting</a>
<br><b>Tunarean Earthmelder says </b>'You have done well, [Your Name].  Here, take this item and use it well! Your efforts will not be forgotten.'
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Tunarean Earthmelder : </b><a href=http://phobos/eq/item.php?id=31419>Frostgiant Overseers Head</a>, <a href=http://phobos/eq/item.php?id=31420>Kallis' Head</a>, <a href=http://phobos/eq/item.php?id=31421>A bloody protector of Zek's Head</a>, <a href=http://phobos/eq/item.php?id=31422>A smashed protector of Zek's Head</a>
<br><b>Tunarean Earthmelder gives you : </b><a href=http://phobos/eq/item.php?id=1207>Helm of the Tracker</a>
<br><b>Tunarean Earthmelder says </b>'You have done well, [Your Name].  Here, take this item and use it well! Your efforts will not be forgotten.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Tunarean Earthmelder says </b>'I have no need of these, friend.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>