<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=22954>A Screaming Sphere</a></ul></td><td><hr><b>When Tylis Newleaf spawns </b>
<p><b>You say, </b>'Hail'
<p><b>You say, </b>'will assist you'
<p><b>You say, </b>'ready'
<p><b>You give Tylis Newleaf : </b><a href=http://phobos/eq/item.php?id=22954>A Screaming Sphere</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>