<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18896>A note</a><li><a href=http://phobos/eq/item.php?id=13867>A Human Head</a><li><a href=http://phobos/eq/item.php?id=1004>Cloth Shirt</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13865>Token of Generosity</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a><li><a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Altunic Jartin says </b>'Greetings, traveler! Have you need of provisions or perhaps other wares? I sell what I find upon the battlegrounds of the Commonlands.'
<p><b>You say, </b>'Where is your house'
<br><b>Altunic Jartin says </b>'Follow me.'
<br><font color=white><b>The NPC moves to 4791.06,-83.55,-51.47.</b></font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=22196>Squire_Narl</a></b> spawns (-105.49,4707.63,-51.47).</font>
<p><b>You give Altunic Jartin : </b><a href=http://phobos/eq/item.php?id=18896>A note</a>
<br><b>Altunic Jartin says </b>'You are the one they have sent? A squire?!! I hope you can help me. I gather items strewn upon the grounds of the Commonlands. I sell them at good prices. Lately, I have been terrorized by a human rogue named Narl. He will no doubt appear at my [house] soon. Bring his head to me.'
<p><b>You give Altunic Jartin : </b><a href=http://phobos/eq/item.php?id=13867>A Human Head</a>
<br><b>Altunic Jartin says </b>'You have performed a great service to me, but I fear others will attack me while I stroll the countryside. It would be very noble of you to fetch me a cloth shirt for protection from wicked creatures. It is not much, but it will help.'
<br><b>You receive </b> 7cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
<p><b>You give Altunic Jartin : </b><a href=http://phobos/eq/item.php?id=1004>Cloth Shirt</a>
<br><b>Altunic Jartin says </b>'Thank you. You are very noble for a squire. I can see you becoming a very valuable asset to the Hall of Truth. Take this token. Tell Merko that you have [earned the Token of Generosity].'
<br><b>Altunic Jartin gives you : </b><a href=http://phobos/eq/item.php?id=13865>Token of Generosity</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=105>Freeport Militia</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=311>Steel Warriors</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=184>Knights of Truth</a> has gotten better.</font>
</td></tr></table>