<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12351>A Tiny Key</a><li><a href=http://phobos/eq/item.php?id=12352>A Tiny Key</a><li><a href=http://phobos/eq/item.php?id=12350>Gem Case</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12349>A Sparkling Sapphire</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Bubar says </b>'Greetings, friend! I am Bubar, merchant from the burning sands. You must be thirsty or, perhaps, hungry. Please look over my goods.'
<p><b>You give Bubar : </b><a href=http://phobos/eq/item.php?id=12351>A Tiny Key</a>, <a href=http://phobos/eq/item.php?id=12352>A Tiny Key</a>, <a href=http://phobos/eq/item.php?id=12350>Gem Case</a>
<br><b>Bubar says </b>'Mmmph!!.. *Pop!!* Ouch, my thumb!! Here you are. You had a gem inside.'
<br><b>Bubar gives you : </b><a href=http://phobos/eq/item.php?id=12349>A Sparkling Sapphire</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Bubar says </b>'I need at least two of the case keys and the gem case.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>