<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10626>Empty Ink Vial</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10601>Ink of the Dark</a></ul></td><td><p><b>You give a ghoul scribe : </b><a href=http://phobos/eq/item.php?id=10626>Empty Ink Vial</a>
<br><b>a ghoul scribe says </b>'Crroooaak! Crrroooooaaakk!'
<br><b>a ghoul scribe gives you : </b><a href=http://phobos/eq/item.php?id=10601>Ink of the Dark</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>