<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12316>Code of Zan Fi</a><li><a href=http://phobos/eq/item.php?id=10114>Purple Headband</a><li><a href=http://phobos/eq/item.php?id=12314>Needle of the Void</a><li><a href=http://phobos/eq/item.php?id=12256>Robe of the Lost Circle</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12314>Needle of the Void</a><li><a href=http://phobos/eq/item.php?id=10114>Purple Headband</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>#Brother Qwinn says </b>'In the name of the [Brotherhood of the Lost Circle] I greet you.'
<p><b>You say, </b>'Brotherhood of the Lost Circle'
<br><b>#Brother Qwinn says </b>'The [Monks of the Whistling Fist] are called the Lost Circle by others. We are an ancient league of monks. Long forgotten and few remaining. Within this realm there are only two. I and [Brother Zephyl]. We seek the items stolen from us. I seek the [Code of Zan Fi].'
<p><b>You say, </b>'Monks of the Whistling Fist'
<br><b>#Brother Qwinn says </b>'The Monks of the Whistling fist were forged from the ways of the great master , Zan Fi. When the Combine Empire reigned supreme, a single bard grew to learn the ways of the monk. This bard was Zan Fi. The brotherhood was all but destroyed in the times that followed. Now only a few remain to carry on Zan Fi's legacy.'
<p><b>You say, </b>'What is the Code of Zan Fi'
<br><b>#Brother Qwinn says </b>'The tome called the Code of the Whistling Fist has been stolen from me. It contains many secrets pertaining to our brotherhood. Thankfully it is magically locked and only a Zan Fi master could unlock it. I quest for a monk to retrieve it. Would you be an [interested monk].'
<p><b>You say, </b>'I am an interested monk'
<br><b>#Brother Qwinn says </b>'Then venture into the depths beyond the great Solusek Mining Company. There, living among the Kobolds, will be Targin the Rock. Get the book from him and return here and wait for my reappearance. When we meet again you shall hand me the book and a Purple Headband earned from the Silent Fist Clan. Do so and you shall be closer to joining the brotherhood.'
<p><b>You say, </b>'Who is Brother Zephyl'
<br><b>#Brother Qwinn says </b>'Brother Zephyl is searching for one who can return the [Idol of Zan Fi]. I believe he is within the vicinity of the Rathe Mountains.'
<p><b>You say, </b>'What is Idol of Zan Fi'
<br><b>#Brother Qwinn says </b>'The Idol of Zan Fi is a sacred totem to our brotherhood. I cannot share it's secrets, but I can tell you that [Brother Zephyl] will offer to you a reward for it's return.'
<p><b>You say, </b>'return the headband'
<br><b>#Brother Qwinn says </b>'Then you will return that which was earned or the robe.'
<p><b>You give #Brother Qwinn : </b><a href=http://phobos/eq/item.php?id=12316>Code of Zan Fi</a>, <a href=http://phobos/eq/item.php?id=10114>Purple Headband</a>
<br><b>#Brother Qwinn says </b>'We had an agreement. The proof of a skilled monk, the purple Headband, and the Code of the Whistling Fist.'
<br><b>#Brother Qwinn says </b>'We thank you for the return of the Code of the Whistling Fist. Take this sewing needle. You shall find it useful should you aid [Brother Zephyl] in his quest. His item, the needle, a swatch of shadow silk and a scroll containing Jonathan's Whistling Warsong. Into a sewing kit they will be going. And into the brotherhood will you. I hope you do not wish me to [return the headband]..'
<br><b>#Brother Qwinn gives you : </b><a href=http://phobos/eq/item.php?id=12314>Needle of the Void</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give #Brother Qwinn : </b><a href=http://phobos/eq/item.php?id=12314>Needle of the Void</a>
<br><b>#Brother Qwinn gives you : </b><a href=http://phobos/eq/item.php?id=10114>Purple Headband</a>
<p><b>You give #Brother Qwinn : </b><a href=http://phobos/eq/item.php?id=12256>Robe of the Lost Circle</a>
<br><b>#Brother Qwinn gives you : </b><a href=http://phobos/eq/item.php?id=10114>Purple Headband</a>
</td></tr></table>