<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=2344>Confession Document</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2395>Theodore's Confession</a></ul></td><td><hr><b>When #Theodore Exanthem spawns </b>
<p><b>You say, </b>'Take us to the location'
<br><font color=green><b>#Theodore Exanthem </b>reels back, his eyes wide with shock. 'Ow,' he says nervously.</font>
<p><b>You give #Theodore Exanthem : </b><a href=http://phobos/eq/item.php?id=2344>Confession Document</a>
<br><b>#Theodore Exanthem gives you : </b><a href=http://phobos/eq/item.php?id=2395>Theodore's Confession</a>
</td></tr></table>