<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20373>Letter of Introduction</a><li><a href=http://phobos/eq/item.php?id=20371>Note for Baenar</a><li><a href=http://phobos/eq/item.php?id=20367>Maligar's Head</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20372>Solusek Mining Company Invoice</a><li><a href=http://phobos/eq/item.php?id=20368>Note to Maligar</a><li><a href=http://phobos/eq/item.php?id=20366>Mahlin's Mystical Bongos</a></ul></td><td><hr><b>When Baenar Swiftsong spawns </b>
<br><font color=grey><i>A global variable is unset at this point.</font></i>
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<p><b>You say, </b>'Hail'
<br><b>Baenar Swiftsong says </b>'Please, I am trying to work here. If you bother me I will write a horrible song about you and sing it from the mountain tops!'
<p><b>You say, </b>'request'
<br><b>Baenar Swiftsong says </b>'You have no request for me? How odd. Well, then. Perhaps a tale of [history] will do?'
<p><b>You say, </b>'tale of history'
<br><font color=green><b>Baenar Swiftsong </b>strums his lute and clears his throat.</font>
<br><b>Baenar Swiftsong says </b>'Here is a tale of the place of torment from which souls good and bad have come to call home upon this earthly [realm].'
<p><b>You say, </b>'realm'
<br><b>Baenar Swiftsong says </b>'The place I speak of is the Estate of Unrest. It is a place that the dead roam and the living detest. Garanel Rucksif was his name, a name that no longer came to be . A name that Quellious herself saw fit not to let anyone see, for a cleric loyal to her called the lands home. Open to all, the Fier'Dal, Koada'Dal and even the occasional [gnome].'
<p><b>You say, </b>'gnome'
<br><b>Baenar Swiftsong says </b>'A mansion built by the cleric with care, for he came to spread the word of Quellious to Faydwer. Garanel mad with rage, killed his wife and children three. From his dwarven homelands he now will flee. Upon this place of tranquility he stumbled upon. He tortured and killed the cleric and his kin by morning's dawn. Within the sacred chapel walls the bloodshed took place. Eyes wild with rage, madness and blood upon his [face].'
<p><b>You say, </b>'face'
<br><b>Baenar Swiftsong says </b>'Quellious, enraged by this act of violence and murder, decreed that this would continue no further! Garanel was struck down, his soul cursed forever more, to haunt the grounds of the defiled estate, guarding its bloody floor. Undead monsters, ghosts and [ghouls] slaughter all those who stray. They say his undead power grows within him to this day. This sad tale, my friends, is the Legend of Unrest.'
<p><b>You say, </b>'ghouls'
<br><b>Baenar Swiftsong says </b>'I've even heard of the ghosts of poor children haunting the estate. Have you ever [seen a child's ghost]?'
<p><b>You say, </b>'seen a child's ghost'
<br><b>Baenar Swiftsong says </b>'You have? Did it speak to you? What did it say? Only the essences of those unjustly wronged or the vilest of souls are bound to this realm and sometimes end up in that accursed place. Only that which binds them to this realm may set them free. Curse those who would harm an innocent child! I knew of one such unfortunate child. I was to bring her a [doll] for her birthday but she fell to a thieving cutthroat's sword!'
<br><font color=green><b>Baenar Swiftsong </b>eyes fill with tears.</font>
<br><b>Baenar Swiftsong says </b>'Pardon me, friends, she was like a daughter to me. I loved her as I would my own!'
<p><b>You say, </b>'doll'
<br><b>Baenar Swiftsong says </b>'What's that you say? You wish to have the doll I was to give her? Whatever for? Bah! Nevermind me. I rant like an old woman sometimes. I should let her memory go but I would stop my heart from beating before I forget that child. Here, take this invoice. I have no further use for it. Give it to Marfen Binkdirple.'
<br><b>Baenar Swiftsong gives you : </b><a href=http://phobos/eq/item.php?id=20372>Solusek Mining Company Invoice</a>
<p><b>You give Baenar Swiftsong : </b><a href=http://phobos/eq/item.php?id=20373>Letter of Introduction</a>
<br><b>Baenar Swiftsong says </b>'So, Belious Naliedin sent you, eh?' Baenar shakes his head. 'I hope your letter of introduction did not empty your purse. You have the audience you seek. What is your [request]? A song perhaps? To immortalize your heroic deeds in song? How about an epic battle with a gnoll pup? I'll make you famous.'
<p><b>You give Baenar Swiftsong : </b><a href=http://phobos/eq/item.php?id=20371>Note for Baenar</a>
<br><b>Baenar Swiftsong says </b>'A note from the child? How can that be! How could she know I was her father? Unless? Cyrah told her. Forgive me. Cyrah was the name of the woman to whom I was betrothed. Unfortunately her parents forbade her from marrying a lowly bard such as myself. Her father married her off to a young merchant in Qeynos named Maligar. She married him only out of respect to her father. Her heart was truly mine, at least, so she always said. When Serra was born, I visited them both often. She was like no other, so innocent and sweet. In those few years I watched her grow up to be more and more like her mother and I saw none of the father in her appearance. I do not like Maligar, but the least we can do is inform him of his child's death. I saw his caravan pass by not more than a day ago headed to Qeynos.'
<br><b>Baenar Swiftsong gives you : </b><a href=http://phobos/eq/item.php?id=20368>Note to Maligar</a>
<p><b>You give Baenar Swiftsong : </b><a href=http://phobos/eq/item.php?id=20367>Maligar's Head</a>
<br><b>Baenar Swiftsong says </b>'That vile dog! I knew there was something not right with him, the way he stared at everyone with contempt! Even his own wife! I curse him! I curse him to stay upon the realm and deny him what he most desires! This is too much! I cannot play or write this day. The sadness overwhelms me. In honor of Serra, the daughter that was denied to me in spirit, I vow never to play this instrument again! It was her favorite and she listened to me play for hours on end. Here take it! Take it out of my sight! Leave me be with my grief and my loss.'
<br><b>Baenar Swiftsong gives you : </b><a href=http://phobos/eq/item.php?id=20366>Mahlin's Mystical Bongos</a>
</td></tr></table>