<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20527>Chromodrac Gut</a><li><a href=http://phobos/eq/item.php?id=20528>Red Wurm Gut</a><li><a href=http://phobos/eq/item.php?id=20529>Onyx Drake Gut</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20377>Maestro's Symphony Page 25</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Kelkim Menkia </b>sighs as she looks over her lute.</font>
<br><b>Kelkim Menkia says </b>'My lute was mangled by those damnable gnolls. I have no idea how I'm going to get a new set of strings for it. They were so rare.'
<p><b>You say, </b>'rare strings'
<br><b>Kelkim Menkia says </b>'I only use the finest lute strings on my lute. My uncle got them for me from across the world. His name was Zendrik the Wurmslayer. As his name implies, he killed many wurms and drakes. The strings for my lute were all made from the guts of the wurms and drakes he slew.'
<p><b>You say, </b>'wurms and drakes'
<br><b>Kelkim Menkia says </b>'The strings were from a chromodrac, a red wurm, and a huge onyx drake. It always sounded so wonderful.'
<br><font color=green><b>Kelkim Menkia </b>sighs, looking off into the horizon.</font>
<br><font color=green><b>Kelkim Menkia </b>shakes her lute angrily</font>
<br><b>Kelkim Menkia says </b>'I'll kill all of you dirty gnolls!'
<p><b>You give Kelkim Menkia : </b><a href=http://phobos/eq/item.php?id=20527>Chromodrac Gut</a>, <a href=http://phobos/eq/item.php?id=20528>Red Wurm Gut</a>, <a href=http://phobos/eq/item.php?id=20529>Onyx Drake Gut</a>
<br><font color=green><b>Kelkim Menkia </b>snatches the gut strings from your hand and immediately begins to string her lute.</font>
<br><b>Kelkim Menkia says </b>'This is wonderful, I will be able to play my lute again soon! Take this old sheet of music I found - I don't think I will have much use for it. My new desire is to bash gnoll heads in with my lute. Safe travels to you, [Your Name].'
<br><b>Kelkim Menkia gives you : </b><a href=http://phobos/eq/item.php?id=20377>Maestro's Symphony Page 25</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>