<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Lord Grimrot says </b>'Welcome to my field of decay. Won't you be so kind as to attack me? I have need of more bodies to join my diseased legion. Try it. maybe you shall win and gain my trusty [Pestilence].'
<p><b>You say, </b>'what pestilence'
<br><b>Lord Grimrot says </b>'My beloved scythe. Upon my death. my soul shall live withn her.  Such is the pact.'
</td></tr></table>