<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13743>Goblin Fire Totem</a><li><a href=http://phobos/eq/item.php?id=10035>Ruby</a><li><a href=http://phobos/eq/item.php?id=13737>Aviak Charm</a><li><a href=http://phobos/eq/item.php?id=10032>Star Ruby</a><li><a href=http://phobos/eq/item.php?id=13744>Goblin Frost Totem</a><li><a href=http://phobos/eq/item.php?id=10034>Sapphire</a><li><a href=http://phobos/eq/item.php?id=13739>Griffon Eye</a><li><a href=http://phobos/eq/item.php?id=10033>Fire Emerald</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=4173>Crafted Helm</a><li><a href=http://phobos/eq/item.php?id=4178>Crafted Gauntlets</a><li><a href=http://phobos/eq/item.php?id=4180>Crafted Plate Boots</a><li><a href=http://phobos/eq/item.php?id=4176>Crafted Vambraces</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Shakrn Meadowgreen says </b>'Hail. I am Shakrn Meadowgreen, Warrior extraordinaire and Master Armorer of the Meadowgreen family. My brother and I craft [armor] for the bravest warriors in the land -- do you think you [qualify]?'
<p><b>You say, </b>'armor'
<br><b>Shakrn Meadowgreen says </b>'I smith [Helms], [Gauntlets], [Boots] and [Vambraces]. My brother Ulan smiths Bracers, Greaves, Pauldruns and Breastplates.'
<p><b>You say, </b>'qualify'
<br><b>Shakrn Meadowgreen says </b>'So you are a warrior of renown?  [Prove] it to me and I will smith you [armor] befitting your exalted station.'
<p><b>You say, </b>'prove'
<br><b>Shakrn Meadowgreen says </b>'You will prove yourself to me the old fashioned way, by killing things and bringing me back proof of your deed.  Bah.  What other way is there?'
<p><b>You say, </b>'helm'
<br><b>Shakrn Meadowgreen says </b>'One of my brethren spoke to me of the mystic properties of the Fire Totems carried by the Goblin High Shaman in Solusek's Eye. My mighty Centaur body will not fit down those twisty goblin passages, so I have not been able to acquire one on my own. As proof of your powers, I ask you to bring me a Fire Totem and one [Ruby] stone. Do so and I will reward you with a Crafted Helmet.'
<p><b>You say, </b>'gauntlets'
<br><b>Shakrn Meadowgreen says </b>'Crafted Gauntlets - the mark of a distinguished warrior. I have a personal grudge to settle with those twice-cursed Aviaks. They have been raiding our merchant convoys for the last few weeks, causing mischief to no end. Bring me an Aviak charm from a Avocet - I am sure that you will not need me to tell you how to get it. An Aviak Charm and two [Star Rubies], and I will reward you with Crafted Gauntlets.'
<p><b>You say, </b>'boots'
<br><b>Shakrn Meadowgreen says </b>'One of my brethren spoke to me of the mystic properties of the Frost Totems carried by the Goblin High Shamans in Permafrost Keep. I have been unable to fetch one for myself, as my Centaur's body will not fit through the tunnels of those sniveling wretches. Prove your might by gifting me a Frost Totem and two [Sapphire] stones. Do this and I will reward you with a pair of Crafted Boots.'
<p><b>You say, </b>'vambraces'
<br><b>Shakrn Meadowgreen says </b>'Come, Warrior, and speak to me of your strength. Bring me the Eye of a Griffon that I might eat it raw in the fashion of my ancestors. Do this for me - then gift me with two [Fire Emeralds], and for you I will make a Crafted Vambrace.'
<p><b>You say, </b>'ruby'
<br><b>Shakrn Meadowgreen says </b>'I need a ruby for a piece of jewelry my brother and I are creating.'
<p><b>You say, </b>'star rubies'
<br><b>Shakrn Meadowgreen says </b>'I need a star ruby for a piece of jewelry my brother and I are creating.'
<p><b>You say, </b>'fire emerald'
<br><b>Shakrn Meadowgreen says </b>'i need a fire emerald for a piece of jewelry my brother and I are creating.'
<p><b>You say, </b>'sapphire'
<br><b>Shakrn Meadowgreen says </b>'I need a sapphire for a piece of jewelry my brother and I are creating'
<p><b>You give Shakrn Meadowgreen : </b><a href=http://phobos/eq/item.php?id=13743>Goblin Fire Totem</a>, <a href=http://phobos/eq/item.php?id=10035>Ruby</a>
<br><b>Shakrn Meadowgreen says </b>'Excellent! Here is your reward, you have earned it!'
<br><font color=yellow>You gain experience!!</font>
<br><b>Shakrn Meadowgreen gives you : </b><a href=http://phobos/eq/item.php?id=4173>Crafted Helm</a>
<p><b>You give Shakrn Meadowgreen : </b><a href=http://phobos/eq/item.php?id=13737>Aviak Charm</a>, <a href=http://phobos/eq/item.php?id=10032>Star Ruby</a> x2
<br><b>Shakrn Meadowgreen says </b>'Excellent! Here is your reward, you have earned it!'
<br><font color=yellow>You gain experience!!</font>
<br><b>Shakrn Meadowgreen gives you : </b><a href=http://phobos/eq/item.php?id=4178>Crafted Gauntlets</a>
<p><b>You give Shakrn Meadowgreen : </b><a href=http://phobos/eq/item.php?id=13744>Goblin Frost Totem</a>, <a href=http://phobos/eq/item.php?id=10034>Sapphire</a> x2
<br><b>Shakrn Meadowgreen says </b>'Excellent! Here is your reward, you have earned it!'
<br><font color=yellow>You gain experience!!</font>
<br><b>Shakrn Meadowgreen gives you : </b><a href=http://phobos/eq/item.php?id=4180>Crafted Plate Boots</a>
<p><b>You give Shakrn Meadowgreen : </b><a href=http://phobos/eq/item.php?id=13739>Griffon Eye</a>, <a href=http://phobos/eq/item.php?id=10033>Fire Emerald</a> x2
<br><b>Shakrn Meadowgreen says </b>'Excellent! Here is your reward, you have earned it!'
<br><font color=yellow>You gain experience!!</font>
<br><b>Shakrn Meadowgreen gives you : </b><a href=http://phobos/eq/item.php?id=4176>Crafted Vambraces</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>