<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1866>Glanitar's Imbued Talisman</a></ul></td><td><p><b>You say, </b>'hail'
<p><b>You say, </b>'what.*worries'
<p><b>You say, </b>'what.*promise'
<p><b>You say, </b>'broken'
<p><b>You say, </b>'what.*training'
<p><b>You say, </b>'what.*patrol'
<p><b>You say, </b>'kardakor'
<p><b>You give #Ralgyn : </b><a href=http://phobos/eq/item.php?id=1866>Glanitar's Imbued Talisman</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>