<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>#Supreme Laochsmith Psorin says </b>'It is most unfortunate that you do not have scales to defend your fragile mortal shell, , I can only hope that the armor we in the Shrine can provide you with will extend your life another fraction of a century. In addition to that you also might want a [special helm] to cover up that scaleless face of yours. I understand that the Mother could not grace you with all our blessings, but at least we can try to make you look half-way decent.'
<p><b>You say, </b>'special helm'
<br><b>#Supreme Laochsmith Psorin says </b>'Using my obviously superior skills I can customize a plate helm from the Shrine to suit a  such as yourself. Give me your Blood Lord's Crown, Scaled Knight's Helm, Helm of Twilight, Akkirus' Crown of the Risen, Cowl of Mortality, Frostreaver's Velium Crown, Crown of the Kromzek Kings, or Crown of the Myrmidon and I shall make you a new helm that will better hide and protect your unscaled features.'
<p><b>You give #Supreme Laochsmith Psorin : </b>
<br><b>#Supreme Laochsmith Psorin says </b>'This item is not worthy of my talents.'
<p><b>You give #Supreme Laochsmith Psorin : </b>
<br><b>#Supreme Laochsmith Psorin says </b>'This item is not worthy of my talents.'
<p><b>You give #Supreme Laochsmith Psorin : </b>
<br><b>#Supreme Laochsmith Psorin says </b>'This item is not worthy of my talents.'
<p><b>You give #Supreme Laochsmith Psorin : </b>
<br><b>#Supreme Laochsmith Psorin says </b>'This item is not worthy of my talents.'
<p><b>You give #Supreme Laochsmith Psorin : </b>
<br><b>#Supreme Laochsmith Psorin says </b>'This item is not worthy of my talents.'
<p><b>You give #Supreme Laochsmith Psorin : </b>
<br><b>#Supreme Laochsmith Psorin says </b>'This item is not worthy of my talents.'
<p><b>You give #Supreme Laochsmith Psorin : </b>
<br><b>#Supreme Laochsmith Psorin says </b>'This item is not worthy of my talents.'
<p><b>You give #Supreme Laochsmith Psorin : </b>
<br><b>#Supreme Laochsmith Psorin says </b>'This item is not worthy of my talents.'
<br><b>#Supreme Laochsmith Psorin says </b>'This item is not worthy of my talents.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>