<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=29688>Scout Report</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=29683>Scout Tools</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a><li><a href=http://phobos/eq/faction.php?id=362>Yelinak</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Commander Leuz says </b>'Welcome to Skyshrine. I have noticed a great deal more of your people joining the ranks of the shrine, hoping to assist in pushing back the giants for good. I am here as the commander of the militia set forth by Lord Yelinak himself. With that in mind, it is my duty to assign certain tasks to those who are willing to show their support to the kin, and to the shrine.'
<p><b>You say, </b>'what.*task'
<br><b>Commander Leuz says </b>'Well, for instance, we have recently acquired information from one of our scouts in the wastelands to the west that there have been storm giants wandering the coastal area nearby. We have not heard from this scout in some time however, and we are beginning to worry about their status. Your task, should you choose to accept it, is to deliver some tools to the scout so that they can communicate back to us with their status, and the status of those giants.'
<p><b>You say, </b>'accept.*task'
<br><b>Commander Leuz says </b>'Good. Please take these tools with haste to the western wastelands and find the scout. Strength be with you, and with the kin.'
<br><b>Commander Leuz gives you : </b><a href=http://phobos/eq/item.php?id=29683>Scout Tools</a>
<p><b>You give Commander Leuz : </b><a href=http://phobos/eq/item.php?id=29688>Scout Report</a>
<br><b>Commander Leuz says </b>'Well this artifact will definitely need study. Thank you for this report. Perhaps after we have researched this object more we will have more for you to search for.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=362>Yelinak</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>