<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1908>Jualicn's Token</a><li><a href=http://phobos/eq/item.php?id=17061>Lexicon of Relinar</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Jualicn says </b>'Why hello there, [Your Name]. I do not see many that pass through these chambers unless they are trusted. What brings you before me today?'
<p><b>You say, </b>'Teachings of Relinar'
<br><b>Jualicn says </b>'In order to receive the teachings, you need to gather four runes from the [descendants of Relinar]. Each descendant of Relinar has one of the four runes. You will find them where they stand six abreast in the wasteland. However in order to know that you have my blessing you must present them with a [treasure] that they would know came from me.'
<p><b>You say, </b>'treasure'
<br><b>Jualicn says </b>'I do have an ancient token that I have carried with me for quite some time. It is very special to me, but if you have been sent here by Lawyla then you must be worthy, for she is quick to see through the lies that some believe will gain them admittance to our halls. Please take this and present it to each of the descendants so that they will know you are truthful when you say that you were sent by me'
<br><b>Jualicn gives you : </b><a href=http://phobos/eq/item.php?id=1908>Jualicn's Token</a>
<p><b>You say, </b>'descendants of Relinar'
<br><b>Jualicn says </b>'Another wizard joining our ranks? Excellent. Listen closely, [Your Name]. I will give you the Lexicon of Relinar, a great and well remembered sorcerer whose teachings are necessary in constructing a spell that is very powerful against the giants. I will give you his ancient lexicon which can harness his teachings if you can carry this large tome. You may need to rearrange your belongings. Are you [ready to receive the lexicon]?'
<p><b>You say, </b>'I am ready to receive the lexicon'
<br><b>Jualicn says </b>'Combine the four runes in this lexicon and you will then have the teachings of Relinar. After you have done this, you are required to speak again with Lawyla about the [problems] we are having [with Kromzek spies].'
<br><b>Jualicn gives you : </b><a href=http://phobos/eq/item.php?id=17061>Lexicon of Relinar</a>
</td></tr></table>