<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=29623>Eysa's Token</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=29067>Note to Tunare's Court</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a><li><a href=http://phobos/eq/faction.php?id=362>Yelinak</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Liason Dolvak says </b>'You have pervaded the inner core of the shrine, what brings your corporeal essence this far? Seek you to prove your worth to the lord and his kin?'
<p><b>You say, </b>'prove my worth'
<br><b>Liason Dolvak says </b>'So it shall be then that you will perform a task for the kin. As it happens, I was on a mission to speak with a [contact] of the shrine in the lands that do not sleep. This contact has vital information on the movements of the giants in that region and it is most important that we recover that information. Unfortunately, I have been called away on duty to further bolster our defenses and will not be able to meet with her.'
<p><b>You say, </b>'contact'
<br><b>Liason Dolvak says </b>'Her name is Eysa Florawhisper. She is a Countess from the Tunarean Court, of whom we are allied with in this fight against the giants. The court does not want the giants encroaching on the lands of Tunare, for they fear that the giants will cause great harm to the area, should they be allowed to control it. As you can see, this gives us a common enemy, which has forged an even stronger alliance between our two peoples. If you can deliver this report to her in my stead, she will give you the documents we need.'
<br><b>Liason Dolvak gives you : </b><a href=http://phobos/eq/item.php?id=29067>Note to Tunare's Court</a>
<p><b>You give Liason Dolvak : </b><a href=http://phobos/eq/item.php?id=29623>Eysa's Token</a>
<br><b>Liason Dolvak says </b>'Ah, excellent. You've returned with the papers we needed. There is some rather interesting information here that I'm sure the council will be glad to have in their possession, and it will allow for our further fortification against the giants. You have proven yourself to be an honorable ally and a friend to the shrine and we thank you for it. I cannot offer you much for this but in time, your actions may prove to be invaluable to the shrine and its kin.'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 7pp 5gp 3sp 2cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=362>Yelinak</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten worse.</font>
<br><b>Liason Dolvak disappears.</b>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>