<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=29062>Giant Warrior Helmet</a><li><a href=http://phobos/eq/item.php?id=29124>Storm Giant Toes</a><li><a href=http://phobos/eq/item.php?id=29125>Frost Giant Toes</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a><li><a href=http://phobos/eq/faction.php?id=362>Yelinak</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Lieutenant Milven says </b>'Hmm, the guards at the gate sent a  to assist with the [rampant problems]? They shall have to be replaced with functional sentries so this does not occur again, but that is another matter for later.'
<p><b>You say, </b>'rampant problems'
<br><b>Lieutenant Milven says </b>'I trust that what is said here will not be repeated to outsiders, yes? Good. For some time now, we've been fortifying our position in the shrine to fend off giant attacks as they come. Though there hasn't been a major engagement between the shrine and the giants for quite some time, there have been strafing runs done by them in an attempt to test us. If you're up for it, I have a [mission] I need someone new to the shrine to complete.'
<p><b>You say, </b>'mission'
<br><b>Lieutenant Milven says </b>'We've been looking for someone that isn't from the shrine to find some of the giants that have been on these strafing runs and have them eliminated. You're of the perfect ilk because they will not recognize you as a friend to the shrine. Once you pry their steel-plated helms from their cold, dead heads and bring them back to me, your worth will be proven and you may show promise as an ally to the shrine.'
<p><b>You say, </b>'assignment'
<br><b>Lieutenant Milven says </b>'While the helmets of the giants are a good way to prove your worth, it really strikes home to the giants when they see some of their best warriors dead without their toes. If you can bring me back either Storm Giant toes or Frost Giant toes, you will not only show us that you are a friend to the shrine, but also that the giants are not as indestructible as they would have you believe.'
<p><b>You give Lieutenant Milven : </b><a href=http://phobos/eq/item.php?id=29062>Giant Warrior Helmet</a>
<br><b>Lieutenant Milven says </b>'Well done, [Your Name]. You are proving to be worth the risk of sending a new recruit out on a mission such as this. If you feel this is the type of mission you're best suited for, feel free to slay more of these beasts and return their helmets to me. The fewer giants there are out there, the less chance they continue their random attacks against us. I also may have another [assignment] for you if you're interested.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=362>Yelinak</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Lieutenant Milven : </b><a href=http://phobos/eq/item.php?id=29124>Storm Giant Toes</a>
<br><font color=green><b>Lieutenant Milven </b>chuckles as he looks at the toes of the giants.</font>
<br><b>Lieutenant Milven says </b>'You have indeed proven yourself to me, and in doing so to the shrine. Keep it up and you'll be on your way to becoming a great ally to the shrine. We appreciate your efforts in this matter greatly, and if you choose to continue your endeavors in this matter, we won't hold it against you.'
<br><font color=green><b>Lieutenant Milven </b>gives you a sly grin before going back to his work.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=362>Yelinak</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten worse.</font>
<br><b>You receive </b> 4pp 14gp 10sp 14cp
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Lieutenant Milven : </b><a href=http://phobos/eq/item.php?id=29125>Frost Giant Toes</a>
<br><font color=green><b>Lieutenant Milven </b>chuckles as he looks at the toes of the giants.</font>
<br><b>Lieutenant Milven says </b>'You have indeed proven yourself to me, and in doing so to the shrine. Keep it up and you'll be on your way to becoming a great ally to the shrine. We appreciate your efforts in this matter greatly, and if you choose to continue your endeavors in this matter, we won't hold it against you.'
<br><font color=green><b>Lieutenant Milven </b>gives you a sly grin before going back to his work.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=362>Yelinak</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten worse.</font>
<br><b>You receive </b> 4pp 14gp 10sp 14cp
<br><font color=yellow>You gain experience!!</font>
<br><b>Lieutenant Milven says </b>'I have no need for this item, [Your Name]. You can have it back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>