<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=11655>Kromrif Bones</a><li><a href=http://phobos/eq/item.php?id=11654>Cured Brontotherium Hide</a><li><a href=http://phobos/eq/item.php?id=1834>Siren Hair</a><li><a href=http://phobos/eq/item.php?id=11657>Shellacked Brontotherium Femur</a><li><a href=http://phobos/eq/item.php?id=10036>Black Sapphire</a><li><a href=http://phobos/eq/item.php?id=11658>Shellacked Dragon Horn</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12552>Draconic Fellowship Drum</a><li><a href=http://phobos/eq/item.php?id=12553>Draconic Fellowship Lute</a><li><a href=http://phobos/eq/item.php?id=12554>Draconic Fellowship Horn</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Mercutius Del Torre says </b>'Good day, night, or whatever the time is. I am Mercutius Del Torre, minstrel of the Draconic Loyalist Fellowship. The great crystalline dragon goddess, Veeshan, has blessed my life with the opportunity to live among her children here in the Skyshrine. I have learned more of the dragons history, lore, and heritage than I ever could have dreamed of knowing back in my younger days in Qeynos. If you are privy to the musical arts and a friend of the dragons and kin I have developed a method of crafting [draconic instruments] and would craft some for you given I am provided with the necessary materials.'
<p><b>You say, </b>'draconic instruments'
<br><b>Mercutius Del Torre says </b>'I have a collection of instruments that I have crafted during my stay here in the Skyshrine from materials that can be found here on the continent of Velious. I presented my crafted instruments to the dragon scholars and they decorated them with runes in the ancient dragon script that enhances the magnificence of their sounds. I will craft either a [draconic drum], [draconic lute], or [draconic horn] if you bring me the materials in order to do so.'
<p><b>You say, </b>'draconic horn'
<br><b>Mercutius Del Torre says </b>'The horn must be crafted from the horn of a dragon, but you must not slay or participate in the slaying of a dragon to acquire this item.
The horn must be from a dragon of no prominent social status that died from natural causes. The old dragon horn must also be treated with a [special shellac] before it is returned to me. I will also require a black sapphire that will be cut into a mouthpiece for the horn. If you bring me those items I will craft the horn for you and have it inscribed with the dragon script runes.'
<p><b>You say, </b>'draconic drum'
<br><b>Mercutius Del Torre says </b>'The frame of the drum must be crafted from Kromrif Bones and the skin of the drum must be crafted from a [Cured Brontotherium Hide]. If you bring me those items I will craft the drum for you and have it inscribed with the dragon script runes.'
<p><b>You say, </b>'draconic lute'
<br><b>Mercutius Del Torre says </b>'The strings of the draconic lute must be crafted from Siren Hair and the body of the lute must be carved from a Brontotherium Femur treated with a [special shellac]. If you bring me those items I will craft the lute for you and have it inscribed with the dragon script runes.'
<p><b>You say, </b>'cured brontotherium hide'
<br><b>Mercutius Del Torre says </b>'First you must hunt down a brontotherium and skin its hide. Once you have the hide it needs to be cured with a [special tannin] in a tailoring kit.'
<p><b>You say, </b>'special tannin'
<br><b>Mercutius Del Torre says </b>'The tannin used to cure the brontotherium hide must be created by a brewer from a Flask of Water, an [Oily Goo Secretion], and one [Melted Glacier Whiskey].'
<p><b>You say, </b>'oily goo secretion'
<br><b>Mercutius Del Torre says </b>'In the caves of the Geonids in the Wakening Lands can be found Tar Goos. These Tar Goos secrete a sticky oily substance that makes an excellent preservative.'
<p><b>You say, </b>'melted glacier whiskey'
<br><b>Mercutius Del Torre says </b>'Melted Glacier Whiskey is a strong alcohol that can be purchased from the Coldain brewers of Thurgadin.'
<p><b>You say, </b>'special shellac'
<br><b>Mercutius Del Torre says </b>'The shellac used for the instruments must be created by a brewer from a Flask of Water, an [Oily Goo Secretion], and one [Kromrif Spit Vodka].
Once you have the shellac fire the old dragon horn or brontotherium femur in a kiln with the shellac.'
<p><b>You say, </b>'kromrif spit vodka'
<br><b>Mercutius Del Torre says </b>'Kromrif Spit Vodka is a strong alcohol that can be purchased from the Coldain brewers of Thurgadin.'
<p><b>You give Mercutius Del Torre : </b><a href=http://phobos/eq/item.php?id=11655>Kromrif Bones</a>, <a href=http://phobos/eq/item.php?id=11654>Cured Brontotherium Hide</a>
<br><b>Mercutius Del Torre says </b>'This will do nicely. Here take the drum I have already prepared and I will craft myself another drum from the materials you have collected.'
<br><b>Mercutius Del Torre gives you : </b><a href=http://phobos/eq/item.php?id=12552>Draconic Fellowship Drum</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten better.</font>
<p><b>You give Mercutius Del Torre : </b><a href=http://phobos/eq/item.php?id=1834>Siren Hair</a>, <a href=http://phobos/eq/item.php?id=11657>Shellacked Brontotherium Femur</a>
<br><b>Mercutius Del Torre says </b>'This will do nicely. Here take the lute I have already prepared and I will craft myself another lute from the materials you have collected.'
<br><b>Mercutius Del Torre gives you : </b><a href=http://phobos/eq/item.php?id=12553>Draconic Fellowship Lute</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten better.</font>
<p><b>You give Mercutius Del Torre : </b><a href=http://phobos/eq/item.php?id=10036>Black Sapphire</a>, <a href=http://phobos/eq/item.php?id=11658>Shellacked Dragon Horn</a>
<br><b>Mercutius Del Torre says </b>'This will do nicely. Here take the horn I have already prepared and I will craft myself another horn from the materials you have collected.'
<br><b>Mercutius Del Torre gives you : </b><a href=http://phobos/eq/item.php?id=12554>Draconic Fellowship Horn</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>