<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=29062>Giant Warrior Helmet</a><li><a href=http://phobos/eq/item.php?id=29624>Mercenary Assignments</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=332>The Tro Jeg Clan</a><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=336>Thrall of Kly</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'I've seen your kind dashing about.  Just watch your footing. you never know when you might slip and fall.'
<p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'I've seen your kind dashing about.  Just watch your footing. you never know when you might slip and fall.'
<p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'I've seen your kind dashing about.  Just watch your footing. you never know when you might slip and fall.'
<p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'I've seen your kind dashing about.  Just watch your footing. you never know when you might slip and fall.'
<p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'I've seen your kind dashing about.  Just watch your footing. you never know when you might slip and fall.'
<p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'I've seen your kind dashing about.  Just watch your footing. you never know when you might slip and fall.'
<p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'I've seen your kind dashing about.  Just watch your footing. you never know when you might slip and fall.'
<p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'I've seen your kind dashing about.  Just watch your footing. you never know when you might slip and fall.'
<p><b>You say, </b>'what special helm'
<p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'I've seen your kind dashing about.  Just watch your footing. you never know when you might slip and fall.'
<p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'I've seen your kind dashing about.  Just watch your footing. you never know when you might slip and fall.'
<p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'I've seen your kind dashing about.  Just watch your footing. you never know when you might slip and fall.'
<p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'I've seen your kind dashing about.  Just watch your footing. you never know when you might slip and fall.'
<p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'I've seen your kind dashing about.  Just watch your footing. you never know when you might slip and fall.'
<p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'I've seen your kind dashing about.  Just watch your footing. you never know when you might slip and fall.'
<p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'I've seen your kind dashing about.  Just watch your footing. you never know when you might slip and fall.'
<p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'I've seen your kind dashing about.  Just watch your footing. you never know when you might slip and fall.'
<p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'I've seen your kind dashing about.  Just watch your footing. you never know when you might slip and fall.'
<p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'I've seen your kind dashing about.  Just watch your footing. you never know when you might slip and fall.'
<p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'I've seen your kind dashing about.  Just watch your footing. you never know when you might slip and fall.'
<p><b>You give Not Found : </b><a href=http://phobos/eq/item.php?id=29062>Giant Warrior Helmet</a>
<br><b>Not Found says </b>'Very good. you are on your way to proving yourself'
<br><b>Not Found says </b>'Very good. you are on your way to proving yourself.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=332>The Tro Jeg Clan</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=336>Thrall of Kly</a> has gotten worse.</font>
<p><b>You give Not Found : </b><a href=http://phobos/eq/item.php?id=29062>Giant Warrior Helmet</a> (x4)
<br><b>Not Found says </b>'Very good. you are on your way to proving yourself'
<br><b>Not Found says </b>'Very good. you are on your way to proving yourself.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=332>The Tro Jeg Clan</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=336>Thrall of Kly</a> has gotten worse.</font>
<p><b>You give Not Found : </b><a href=http://phobos/eq/item.php?id=29624>Mercenary Assignments</a>
<br><b>Not Found says </b>'Ahhh yes! Well done Erudite. Here is your reward. Your status with our people grows with each interloper you eradicate.'
<br><b>You receive </b> 6gp 6sp 13cp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=332>The Tro Jeg Clan</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=336>Thrall of Kly</a> has gotten worse.</font>
<p><b>You give Not Found : </b><a href=http://phobos/eq/item.php?id=29062>Giant Warrior Helmet</a> (x2)
<br><b>Not Found says </b>'Very good. you are on your way to proving yourself.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=332>The Tro Jeg Clan</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=336>Thrall of Kly</a> has gotten worse.</font>
<p><b>You give Not Found : </b><a href=http://phobos/eq/item.php?id=29062>Giant Warrior Helmet</a> (x3)
<br><b>Not Found says </b>'Very good. you are on your way to proving yourself.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=332>The Tro Jeg Clan</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=336>Thrall of Kly</a> has gotten worse.</font>
</td></tr></table>