<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=29064>A shipment of Velium Ore</a><li><a href=http://phobos/eq/item.php?id=29065>A Spy Report</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1725>Velium Delivery Note</a><li><a href=http://phobos/eq/item.php?id=1727>Bracer of Hammerfal</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=362>Yelinak</a><li><a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Sentry Kale says </b>'Another , in the great shrine? Perhaps the times have gotten worse than we had expected -- I wonder if I will need to reactivate my [sentinel] for further use in my stead.'
<p><b>You say, </b>'i wish to become a friend of the kin'
<p><b>You say, </b>'hail'
<br><b>Sentry Kale says </b>'Another , in the great shrine? Perhaps the times have gotten worse than we had expected -- I wonder if I will need to reactivate my [sentinel] for further use in my stead.'
<p><b>You say, </b>'sentinel'
<br><b>Sentry Kale says </b>'It was not too long ago that I was merely a chunk of walking velium in the eyes of most who traveled through the shrine. However that golem was in fact one of my sentinels used to keep my identity secluded, and took on the tasks that I gave it. However, there has been a problem recently with our supplies, and I have had to take it offline until further notice.'
<p><b>You say, </b>'problem'
<br><b>Sentry Kale says </b>'As you may have noticed, there are a great deal of golems and gargoyles within the shrine that consist of velium. These are our guards and they serve us well, however with extended use of these creatures comes extensive repair needed. It is because of this necessity to keep our sentries and lookouts working well that we require a great deal of velium ore stocked and ready for use. Unfortunately, our supplies have been running thin and we are in need of a new shipment of ore.'
<p><b>You say, </b>'supplies'
<br><b>Sentry Kale says </b>'I may have been wrong in my initial thoughts about your race, Halfling. You may just prove to be worth my time. Take this note now and find Ungdin. Please hurry and remember to keep this information to yourself.'
<br><b>Sentry Kale gives you : </b><a href=http://phobos/eq/item.php?id=1725>Velium Delivery Note</a>
<p><b>You say, </b>'i am interested'
<p><b>You say, </b>'source'
<p><b>You say, </b>'i am capable'
<p><b>You give Sentry Kale : </b><a href=http://phobos/eq/item.php?id=29064>A shipment of Velium Ore</a>
<br><b>Sentry Kale says </b>'You've returned, and with the shipment of ore intact! It was wise to send you out on that mission, [Your Name], and I'm glad you did not fail. If you're looking for more assignments to do, I may have something that is just right for you. If you're interested in it, just let me know and we'll talk.'
<br><b>Sentry Kale gives you : </b><a href=http://phobos/eq/item.php?id=1727>Bracer of Hammerfal</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 10pp 10gp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=362>Yelinak</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten worse.</font>
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<p><b>You give Sentry Kale : </b><a href=http://phobos/eq/item.php?id=29065>A Spy Report</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>