<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=28601>Message to Herald</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28600>Message to Wenglawks</a><li><a href=http://phobos/eq/item.php?id=28602>Shrine Key</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Ziglark Whisperwing says </b>'Welcome to the greatness that is Skyshrine, [Your Name]. I am Herald to our great leader, Lord Yelinak. It is my position to make sure that all is running in an orderly and functional matter in the mighty shrine before you. I handle the guard assignments as well as granting [access] to pass through the shrine. If you'd like to find out about either of these, please just ask.'
<p><b>You say, </b>'access'
<br><b>Ziglark Whisperwing says </b>'You may have seen the large monument in a pond out in the commune area on your journey to see me. This is not just a monument to our great Lord Yelinak, but also a portal to the cold recesses of the Cobalt Scar. Access is, however, only granted to those who are [worthy] to be called allies of the shrine.'
<p><b>You say, </b>'worthy'
<br><b>Ziglark Whisperwing says </b>'Perhaps, then again you only say that so you might gain access and plunder through the riches beyond the portal. We shall see. If you truly wish to prove yourself, you will need to entertain a bit of a [challenge].'
<p><b>You say, </b>'challenge'
<br><b>Ziglark Whisperwing says </b>'We of the kin have a contact within the giant regime, named Wenglawks Kkeak. He has information on the movements of the storm giants through the arctic homelands of Velious. We have been in contact with him for quite some time, however, as of late, our couriers have been lost on their way to met him. As you can imagine, this worries us and makes it rather difficult to keep abreast of the movements of the giants. What we needs is someone to find Wenglawks and [deliver] the payment to him, so that we can gather further information on their movements.'
<p><b>You say, </b>'deliver'
<br><b>Ziglark Whisperwing says </b>'As much I figured you would say that. You must take this request for the information and give it to him, along with 200 platinum pieces. Only then will he part with the information. Once you have it, bring it back to me and your worth to the shrine will be proven.'
<br><b>Ziglark Whisperwing gives you : </b><a href=http://phobos/eq/item.php?id=28600>Message to Wenglawks</a>
<p><b>You give Ziglark Whisperwing : </b><a href=http://phobos/eq/item.php?id=28601>Message to Herald</a>
<br><b>Ziglark Whisperwing says </b>'I appear to have mistaken your declaration of worth as a phony attempt at bravado, and do apologize. You have truly proven yourself worthy of the shrine, and in short order as well. For your troubles, and as a token of your worth to the shrine, I grant you this key to traverse into the lands of the Cobalt Scar. Praise be with you and good journeys always, [Your Name].'
<br><font color=yellow>You gain experience!!</font>
<br><b>Ziglark Whisperwing gives you : </b><a href=http://phobos/eq/item.php?id=28602>Shrine Key</a>
<br><b>Ziglark Whisperwing says </b>'I have no need for this item [Your Name], you can have it back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>