<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=55007>A note of safe passage</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>#Jordin Sretin says </b>'Welcome to the Port of Erudin. What can I help you with today?'
<p><b>You say, </b>'Glory'
<br><font color=green><b>#Jordin Sretin </b>shuffles through some paperwork that is strewn messily before him. 'The Light's Glory, let's see. Yes it is a merchant ship headed from Freeport to Erudin. Yes it should have been here a week ago. Seems we have had a couple ships disappear as of late. Rumors tell of increased pirate activity. Seems none of the local guards wants to get involved in investigating this. Any assistance you could provide would be most appreciated. I suggest that you travel to Erud's Crossing and talk to a Kerran named Nifta. He lives near the dock on the isle and has a great wealth of knowledge of the sea and ships that pass through the crossing. Ask him if he has seen The Light's Glory.'</font>
<p><b>You say, </b>'safe passage'
<br><b>#Jordin Sretin says </b>'How unfortunate.  I don't like Trolls much, but I feel I must help.  Take this and give it to him.'
<br><b>#Jordin Sretin gives you : </b><a href=http://phobos/eq/item.php?id=55007>A note of safe passage</a>
</td></tr></table>