<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=31828>Venomous Spikefish Poison Sac</a><li><a href=http://phobos/eq/item.php?id=22570>Necromancer Blood</a><li><a href=http://phobos/eq/item.php?id=6949>Ancient Venom Sack</a><li><a href=http://phobos/eq/item.php?id=6950>Ancient Snake Fang</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=22571>Thick Caustic Liquid</a></ul></td><td><p><b>You say, </b>'Hail, Collier'
<br><b>Collier says </b>'Make it a habit of walking into peoples rooms now do ya? Well seeing as I'm here on business I may have a [proposition] for you.'
<p><b>You say, </b>'What is the proposition'
<br><b>Collier says </b>'I'm in the employment of an alchemist that desires some rare venom from this region of Norrath. I will reward you with a special weapon treatment if you can return to me with a venomous spikefish poison sac, an ancient poison sac, an ancient snake fang, and the blood of a necromancer.'
<p><b>You say, </b>'What special weapon treatment'
<br><b>Collier says </b>'My employer has uncovered the secrets of the Bloodclaw and can reproduce the weapon treatment used in the forging of the legendary Stiletto of the Bloodclaw.'
<p><b>You give Collier : </b><a href=http://phobos/eq/item.php?id=31828>Venomous Spikefish Poison Sac</a>, <a href=http://phobos/eq/item.php?id=22570>Necromancer Blood</a>, <a href=http://phobos/eq/item.php?id=6949>Ancient Venom Sack</a>, <a href=http://phobos/eq/item.php?id=6950>Ancient Snake Fang</a>
<br><b>Collier says </b>'There is the weapon treatment I promised you. Use it in a forge with either a Long Sword or a Scimitar. Choose which weapon you prefer carefully as there is only enough of the substance for a single treatment.'
<br><b>Collier gives you : </b><a href=http://phobos/eq/item.php?id=22571>Thick Caustic Liquid</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>