<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18726>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13546>Faded Silver Tunic*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Depnar Bulrious says </b>'Hail. [Your Name] ! I am the master of the paladins among the Peacekeepers. Have you [joined] the harmony of the Peacekeepers] or are you merely a visitor?'
<p><b>You say, </b>'joined'
<br><b>Depnar Bulrious says </b>'Then go and speak with the other Peacekeepers. Do your part to promote the words of Quellious.'
<p><b>You give Depnar Bulrious : </b><a href=http://phobos/eq/item.php?id=18726>A tattered note</a>
<br><b>Depnar Bulrious says </b>'Welcome to the Temple of Divine Light. I am Master Bulrious. Here. we study and spread the will of Quellious. Here is your guild tunic. Go find Jras Solsier. he will get you started with your first lesson.'
<br><b>Depnar Bulrious gives you : </b><a href=http://phobos/eq/item.php?id=13546>Faded Silver Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>