<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Dleria Mausrel says </b>'Hail! You appear to be a [new priest]. <smiles> Ah. I so enjoy the presence of youth within Deepwater Temple. I am sure Prexus is smiling upon us as we speak.'
<p><b>You say, </b>'i am a new priest'
<br><b>Dleria Mausrel says </b>'As I suspected. I shall assist you with your training and you shall assist the temple with your service. A young priest can help out by asking to [convert fishermen in Qeynos] or maybe even something truly great such as requesting to [protect the depths].'
<p><b>You say, </b>'i want to protect the depths'
<br><b>Dleria Mausrel says </b>'We have heard of zombies inhabiting the depths of Erud's Crossing. Go and seek them out. Destroy them. This evil should not exist within the realm of the Ocean Lord. Take this bag. Fill it with their rotting flesh. combine it and return it to me. May Prexus guide you.'
</td></tr></table>