<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18724>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13544>Old Blue Tunic*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Gans Paust says </b>'Hello.'
<p><b>You give Gans Paust : </b><a href=http://phobos/eq/item.php?id=18724>A tattered note</a>
<br><b>Gans Paust says </b>'Yes. welcome friend! Here is your guild tunic. You'll make a fine addition to the Deepwater Knights. Go see Dleria. she will get you started in your studies.'
<br><b>Gans Paust gives you : </b><a href=http://phobos/eq/item.php?id=13544>Old Blue Tunic*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>