<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13881>A Nicked Coin</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=79>Deepwater Knights</a><li><a href=http://phobos/eq/faction.php?id=145>High Council of Erudin</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=143>Heretics</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Laoni Reista says </b>'Very good to make your acquaintance. [Your Name]. If you are a [new knight]. then let it be known. for I am seeking young knights of Deepwater.'
<p><b>You say, </b>'i am a new knight'
<br><b>Laoni Reista says </b>'You do seem a bit young. We shall have to test your mettle. Within this temple. you shall learn to swim as fast as the swordfish and attack with the bravery and skill of the shark. Are you willing to [assist with the cleansing of the ocean]?'
<p><b>You say, </b>'i will assist with the cleansing of the ocean'
<br><b>Laoni Reista says </b>'Go to the waters near the harbor. We have heard of Qeynos' rogue guild attempting to smuggle our valuable Vasty Deep water from Odus by way of swimmers. We require proof of their involvement. It is said they often carry special coins. Return one of these coins to me.'
<p><b>You give Laoni Reista : </b><a href=http://phobos/eq/item.php?id=13881>A Nicked Coin</a>
<br><b>Laoni Reista says </b>'Good work. You have shown these rogues who are the better swimmers. Now we have proof of their involvement. You are a fine addition to the temple. Take this small reward. Go, and serve Prexus.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=79>Deepwater Knights</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=145>High Council of Erudin</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=143>Heretics</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>