<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18723>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13989>Peacekeeper Token</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Leraena Shelyrak says </b>'Welcome. my child.  I am Leraena Shelyrak. overseer of the Temple of Divine Light. Inside this temple. you may find the path to inner peace.  Introduce yourself to each of the priests and priestesses of the temple as well as the paladins. Together we shall put an end to such disruptive influences as the [kobold shamans].'
<p><b>You say, </b>'kobold shaman'
<br><b>Leraena Shelyrak says </b>'The primitive kobold race has begun to show signs of healing ability.  No doubt this was granted by some evil deity.  Since they are of little power compared to a much more superior race such as ours. we only require the talents of young priests to [slay the kobold shaman].'
<p><b>You say, </b>'slay'
<br><b>Leraena Shelyrak says </b>'You are so young...  Go to Toxxulia and find these kobold shamans.  Cut off their paws and return them to me.  I require three paws as proof of your worth to our temple.'
<p><b>You say, </b>'i need a guild coin'
<br><b>Leraena Shelyrak says </b>'Yes, of course. Here it is. Remember that it is not a form of currency.'
<br><b>Leraena Shelyrak gives you : </b><a href=http://phobos/eq/item.php?id=13989>Peacekeeper Token</a>
<p><b>You give Leraena Shelyrak : </b><a href=http://phobos/eq/item.php?id=18723>A tattered note</a>
</td></tr></table>