<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13882>A Box of Bones</a><li><a href=http://phobos/eq/item.php?id=13816>Peacekeeper Staff</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18833>A Sealed Letter</a><li><a href=http://phobos/eq/item.php?id=17941>Box For Bones</a><li><a href=http://phobos/eq/item.php?id=15209>Spell: Spook the Dead</a><li><a href=http://phobos/eq/item.php?id=6016>Rusty Morning Star</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=247>Peace Keepers</a><li><a href=http://phobos/eq/faction.php?id=145>High Council of Erudin</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=143>Heretics</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Lumi Stergnon says </b>'Peace and tranquility be with you. [Your Name].  Are you a [new acolyte of peace] or are you [here to pay homage] to the child of tranquility?'
<p><b>You say, </b>'new acolyte of peace'
<br><b>Lumi Stergnon says </b>'Then you shall learn the ways of Quellious and learn to do as you are told by higher ranking members. It is time for you to do the lesser duties of a young priest. Which will it be? [Retrieve the Peacekeeper staffs] or [battle the undead]?'
<p><b>You say, </b>'I will retrieve the Peacekeeper staffs'
<br><b>Lumi Stergnon says </b>'Then take this note to the woodworker in Toxxulia Forest. His name is Emil Parsini. He shall have the staff to be returned to the temple.'
<br><b>Lumi Stergnon gives you : </b><a href=http://phobos/eq/item.php?id=18833>A Sealed Letter</a>
<p><b>You say, </b>'I will battle the undead'
<br><b>Lumi Stergnon says </b>'Then you shall venture to Toxxulia Forest. There has been an increase in skeleton sightings lately. I do not know their origin, but I believe that your efforts will reduce their numbers! Take this box. Return it to me when you have filled it with the bones of these undead creatures and combined it. May Quellious' light guide you.'
<br><b>Lumi Stergnon gives you : </b><a href=http://phobos/eq/item.php?id=17941>Box For Bones</a>
<p><b>You say, </b>'important missions'
<br><b>Lumi Stergnon says </b>'We have need of skilled priests. We have learned that a High Guard battle staff has been stolen. We require a priest to [track down the staff].'
<p><b>You say, </b>'here to pay homage'
<br><b>Lumi Stergnon says </b>'You have not done much to upset the Peacekeepers of this temple, but we must ask you to prove yourself to us before we may discuss things such as this.'
<br><b>Lumi Stergnon says </b>'Then respect our temple and keep your prayers silent.'
<p><b>You give Lumi Stergnon : </b><a href=http://phobos/eq/item.php?id=13882>A Box of Bones</a>
<br><b>Lumi Stergnon says </b>'This is fabulous work, my friend! You have served your people well. Take this as a gift. I hope it can be of use to you. We need proof of these skeletons' origins. Continue the eradication of the undead and find out who creates them. Once you know, bring their head to me.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=247>Peace Keepers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=145>High Council of Erudin</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=143>Heretics</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 3gp 12sp
<br><b>Lumi Stergnon gives you : </b><a href=http://phobos/eq/item.php?id=15209>Spell: Spook the Dead</a>
<p><b>You give Lumi Stergnon : </b><a href=http://phobos/eq/item.php?id=13816>Peacekeeper Staff</a>
<br><b>Lumi Stergnon says </b>'You have done well, neophyte.Let me add the touch of harmony to finish the job.. Here, then. Take these supplies. I am sure you'll need them. Soon you may be able to assist us in [important missions].'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=247>Peace Keepers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=145>High Council of Erudin</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=143>Heretics</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 11sp 12cp
<br><b>Lumi Stergnon gives you : </b><a href=http://phobos/eq/item.php?id=6016>Rusty Morning Star</a>
<br><b>Lumi Stergnon says </b>'You're contribution is interesting in your choice of it, but you may have it back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>