<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13118>Erud's Tonic</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13122>Erud's Tonic</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a><li><a href=http://phobos/eq/faction.php?id=103>Followers of Korucust</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=302>Skytalons</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Nolusia Finharn says </b>'Good evening. Are not the stars beautiful? Somewhere out there. I imagine there is another world and another person staring right back at me. If you have business with me. please save it for the morning in the palace.'
<p><b>You give Nolusia Finharn : </b><a href=http://phobos/eq/item.php?id=13118>Erud's Tonic</a>
<br><b>Nolusia Finharn gives you : </b><a href=http://phobos/eq/item.php?id=13122>Erud's Tonic</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=103>Followers of Korucust</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=302>Skytalons</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
</td></tr></table>