<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=6339>Blessed Silver Wand</a><li><a href=http://phobos/eq/item.php?id=10792>Gleaming Coin of Tash</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=6340>Glowing Silver Wand</a><li><a href=http://phobos/eq/item.php?id=10793>Radiant Coin of Tash</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=211>Merchants of Erudin</a><li><a href=http://phobos/eq/faction.php?id=145>High Council of Erudin</a><li><a href=http://phobos/eq/faction.php?id=147>High Guard of Erudin</a><li><a href=http://phobos/eq/faction.php?id=442>Temple Of Sol Ro</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=291>Shadowed Men</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Raine Beteria says </b>'Welcome. I am Raine Beteria.'
<p><b>You give Raine Beteria : </b><a href=http://phobos/eq/item.php?id=6339>Blessed Silver Wand</a>
<br><b>Raine Beteria says </b>'Here is your wand back - I assure you it is now fully enchanted.'
<br><b>Raine Beteria gives you : </b><a href=http://phobos/eq/item.php?id=6340>Glowing Silver Wand</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=211>Merchants of Erudin</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=145>High Council of Erudin</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=147>High Guard of Erudin</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Raine Beteria : </b><a href=http://phobos/eq/item.php?id=10792>Gleaming Coin of Tash</a>
<br><b>Raine Beteria says </b>'Thank you very much. I have always wanted one of these! Hehehe? Just kidding. I see that you have enchanted this coin. I have placed the final enchantment on it - take it back to Romar.'
<br><b>Raine Beteria gives you : </b><a href=http://phobos/eq/item.php?id=10793>Radiant Coin of Tash</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=442>Temple Of Sol Ro</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=291>Shadowed Men</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>