<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Rarnan Lapice says </b>'It is good to meet you. [Your Name].  To enter the Temple of Divine Light is to invite Quellious into your body and soul.  Tranquility is our way and. as such. we do all we can to uphold it.  Are you a [cleric of Quellious]. or am I mistaken?'
<p><b>You say, </b>'i am a cleric of the quellious'
<br><b>Rarnan Lapice says </b>'You have not done much to upset the Peacekeepers of this temple. but we must ask you to prove yourself to us before we may discuss things such as this.'
</td></tr></table>