<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=29001>Tainted Darksteel Breastplate</a><li><a href=http://phobos/eq/item.php?id=29006>Pure Crystal</a><li><a href=http://phobos/eq/item.php?id=29000>Tainted Darksteel Sword</a><li><a href=http://phobos/eq/item.php?id=29009>bucket of pure water</a><li><a href=http://phobos/eq/item.php?id=29003>Gleaming Crested Sword</a><li><a href=http://phobos/eq/item.php?id=29004>Gleaming Crested Breastplate</a><li><a href=http://phobos/eq/item.php?id=29005>Gleaming Crested Shield</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=29004>Gleaming Crested Breastplate</a><li><a href=http://phobos/eq/item.php?id=29003>Gleaming Crested Sword</a><li><a href=http://phobos/eq/item.php?id=29010>Mark of Atonement</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Reklon Gnallen says </b>'Hail to you, friend.  Seek you knowledge or atonement in this temple of peace?'
<p><b>You say, </b>'i seek knowledge'
<br><b>Reklon Gnallen says </b>'Many are the things I could speak to you of.  Have you any specific interest?'
<p><b>You say, </b>'i seek atonement'
<br><b>Reklon Gnallen says </b>'Yes.  Many are those who enter these halls seeking the forgiveness, the atonement of a god.  By turning their spirit against whatever wrong they have committed they may be able to receive redemption in the eyes of their diety.  Many seek such a thing, but few truly have the strength of spirit to attain it.'
<p><b>You say, </b>'temple of peace'
<br><b>Reklon Gnallen says </b>'Dedicated to the god of peace, Quellious, is this temple. It is here that her clerics and paladins pray and receive inspiration.'
<p><b>You say, </b>'paladins'
<br><b>Reklon Gnallen says </b>'As the clerics are the warm hand of healing, the paladins are the stalwart shield of protection, and in times of grave need the sharp sword of justice. To our post must we always remain vigilant, else dishonor might befall us.'
<p><b>You say, </b>'remain vigilant'
<br><b>Reklon Gnallen says </b>'To a paladin the upholding of his duty, or honor to his temple is foremost. To fail in his duty to stand at his assigned post in time of need is a great disgrace. Few are the paladins who have done so, and their spirits have been outcast from the god of peace.'
<p><b>You say, </b>'outcast'
<br><b>Reklon Gnallen says </b>'Harsh though it seems, a true paladin must always remain vigilant and dedicated to his cause. If he does not then he might find himself fallen from grace.'
<p><b>You say, </b>'fallen from grace'
<br><b>Reklon Gnallen says </b>'here are a few who have done so. Only a few that come to mind. Such stories are useful to remember as reminders of our beliefs.'
<p><b>You say, </b>'stories'
<br><b>Reklon Gnallen says </b>'One is the story of the paladin who fell due to his weakness in the duty of his guard post. He let himself be seduced by a peasant woman'
<p><b>You say, </b>'peasant woman'
<br><b>Reklon Gnallen says </b>'Many hundreds of years ago did this story begin. There was a paladin, whose name is lost to all but our oldest leaders, who was among the greatest examples of honor. It was his post to guard the chambers to our most important halls. His fall was a creature in the guise of a poor peasant woman.'
<p><b>You say, </b>'sacrifice'
<br><b>Reklon Gnallen says </b>'Only this crest and the sacrifice of something that symbolizes your strength and purity will release his spirit into the cleansing flames of our lady Quellious. Go now.'
<p><b>You give Reklon Gnallen : </b><a href=http://phobos/eq/item.php?id=29006>Pure Crystal</a>, <a href=http://phobos/eq/item.php?id=29001>Tainted Darksteel Breastplate</a>
<br><font color=green><b>Reklon Gnallen </b>presses the gem of purity against the breastplate. Its dark gleam softens and then glows bright once again. 'Compassion is strong in you. Few so called heroes would sacrifice their time for such a menial task as you performed. Continue your work. Hold this ancient breastplate until you have completed your task.</font>
<br><b>Reklon Gnallen gives you : </b><a href=http://phobos/eq/item.php?id=29004>Gleaming Crested Breastplate</a>
<p><b>You give Reklon Gnallen : </b><a href=http://phobos/eq/item.php?id=29009>bucket of pure water</a>, <a href=http://phobos/eq/item.php?id=29000>Tainted Darksteel Sword</a>
<br><font color=green><b>Reklon Gnallen </b>washes the sword's blade in the water of purity. Its dark surface begins to shine, as true as the day it was forged. 'Such a sacrifice is rare among the poor. Truly, the woman must have loved her brother. Remember the lesson you have learned from her. Keep the sword until your work is done.'</font>
<br><b>Reklon Gnallen gives you : </b><a href=http://phobos/eq/item.php?id=29003>Gleaming Crested Sword</a>
<p><b>You give Reklon Gnallen : </b><a href=http://phobos/eq/item.php?id=29003>Gleaming Crested Sword</a>, <a href=http://phobos/eq/item.php?id=29005>Gleaming Crested Shield</a>, <a href=http://phobos/eq/item.php?id=29004>Gleaming Crested Breastplate</a>
<br><b>Reklon Gnallen says </b>'I never thought our order would see these artifacts again. With the return of these relics we can now put at ease a scar upon the history of our order. This cleansing will atone for his failure. Your soul must be pure to have given so freely of yourself. Go now, take this crested token of our order. If you wish to free his soul you must undertake another sacrifice.'
<br><b>Reklon Gnallen gives you : </b><a href=http://phobos/eq/item.php?id=29010>Mark of Atonement</a>
</td></tr></table>