<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13121>Innoruuk's Kiss of Death</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13118>Erud's Tonic</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Sinnkin Highbrow says </b>'Why. hello there fellow scholar!  Don't you just love books?  I am quite a bookworm myself.  I could read forever!  I am currently working my way through the 'T's.'
<p><b>You give Sinnkin Highbrow : </b><a href=http://phobos/eq/item.php?id=13121>Innoruuk's Kiss of Death</a>
<br><b>Sinnkin Highbrow gives you : </b><a href=http://phobos/eq/item.php?id=13118>Erud's Tonic</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten better.</font>
</td></tr></table>