<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10600>Mechanical Pen</a><li><a href=http://phobos/eq/item.php?id=10601>Ink of the Dark</a><li><a href=http://phobos/eq/item.php?id=10602>White Paper</a><li><a href=http://phobos/eq/item.php?id=54008>A Dimly Glowing Ring</a><li><a href=http://phobos/eq/item.php?id=54007>Note to Stofo</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10603>Copy of Notes</a><li><a href=http://phobos/eq/item.php?id=59016>Spell: Scryer's Trespass</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=342>True Spirit</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Stofo Olan says </b>'Good day, I have discovered something truly wonderful! If I only had the materials required so I can copy my notes and send them to my teacher.'
<p><b>You say, </b>'discover'
<br><b>Stofo Olan says </b>'I was researching a new spell, and discovered new information concerning the history of the Serpent.'
<p><b>You say, </b>'materials'
<br><b>Stofo Olan says </b>'The materials I need are a mechanical pen, ink of the dark, and white paper. Bring me those and I will give you a copy of this information.'
<p><b>You say, </b>'teacher'
<br><b>Stofo Olan says </b>'My teacher is Jeb Lumsed. He was last seen in the regions of the newly discovered lands of Kunark. If you wish to find him that is where you must seek him out.'
<p><b>You say, </b>'ink of the dark'
<br><b>Stofo Olan says </b>'Dark illusions, thievery, and the plague of the living will guide you. These are the only hints I can provide. Safe travels and may you be protected from all maladies.'
<p><b>You say, </b>'mechanical pen'
<br><b>Stofo Olan says </b>'The answer you seek is in your question. If you are unable to figure it out, then perhaps you are not ready to travel along this path.'
<p><b>You say, </b>'white paper'
<br><b>Stofo Olan says </b>'It may seem like ordinary paper at first. However, this paper was enchanted by a friend of mine. This paper was given to a lass in the Karanas to help with her writings. The paper will guide her hands and draw forth the thoughts in her mind. I no longer have any and I have not had contact with my friend in some time. Search them out.'
<p><b>You give Stofo Olan : </b><a href=http://phobos/eq/item.php?id=10600>Mechanical Pen</a>, <a href=http://phobos/eq/item.php?id=10601>Ink of the Dark</a>, <a href=http://phobos/eq/item.php?id=10602>White Paper</a>
<br><b>Stofo Olan says </b>'Yes, that is what I wanted. Here, take these notes. My teacher will be very interested if he is shown what I have found.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=342>True Spirit</a> has gotten better.</font>
<br><b>Stofo Olan gives you : </b><a href=http://phobos/eq/item.php?id=10603>Copy of Notes</a>
<p><b>You give Stofo Olan : </b><a href=http://phobos/eq/item.php?id=54008>A Dimly Glowing Ring</a>, <a href=http://phobos/eq/item.php?id=54007>Note to Stofo</a>
<br><font color=green><b>Stofo Olan </b>scans the note quickly and gasps. Hardly glancing at you, he begins examining the ring, tearing through notes and books scattered about his dark room. As he pores over a scroll of parchment covered in strange texts his eyes light up, 'Yes, yes this is it! Ofala really found something quite remarkable in this one! Watch my friend.' The slim Erudite slips the ring onto his finger and the gem begins to throb, Stofo seems to draw the power into himself for a moment then carefully places the ring back onto his desk. He closes his eyes a moment then turns to you, the darkness in his eyes almost lends fear for a moment before he smiles. 'Thank you my friend, this stone is very dangerous, but I believe that I have accessed the powers within me through it. Take these words and use them well, perhaps the power shall work for you as well, and please tell my dear sister hello.'</font>
<br><b>Stofo Olan gives you : </b><a href=http://phobos/eq/item.php?id=59016>Spell: Scryer's Trespass</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Stofo Olan says </b>'This is not what I wanted.'
</td></tr></table>