<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1761>Kobold Molar</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Tiam Khonsir says </b>'Greetings. [Your Name]. Are you a follower of our order, the Deepwater Knights. servants of the Ocean Lord, Prexus?'
<p><b>You say, </b>'yes'
<br><b>Tiam Khonsir says </b>'That is good. [Your Name]. Our followers are few but our faith is strong. With the efforts of those few, our destiny may be reached in time. We must walk with perseverence and devotion, much like the tides that, over time, can destroy a mighty stone cliff. Have you [come to serve our Lord], [Your Name]?'
<p><b>You say, </b>'i have come to serve our lord'
<br><b>Tiam Khonsir says </b>'Then I shall send you on a quest to prove your devotion. No doubt you have seen the vermin kobolds scuttling about the land as fleas upon a mangy dog. The kobolds have a lair on our continent from which they launch their wantonly destructive raids. You are to enter that lair and destroy as many of these dogs as you can. For each molar you bring me. you will receive praise. admiration. and perhaps some coin.'
<p><b>You say, </b>'quest of greater importance'
<br><b>Tiam Khonsir says </b>'Very well then, [Your Name], you may be able to help us. Go to Breya and tell her I sent you. She will brief you.'
<p><b>You give Tiam Khonsir : </b><a href=http://phobos/eq/item.php?id=1761>Kobold Molar</a>
<p><b>You give Tiam Khonsir : </b><a href=http://phobos/eq/item.php?id=1761>Kobold Molar</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>