<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13884>Fishy Cat Tail</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13053>Brass Ring</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=247>Peace Keepers</a><li><a href=http://phobos/eq/faction.php?id=145>High Council of Erudin</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=143>Heretics</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Vynon Estaliun says </b>'I welcome you to the temple of the Peacekeepers. The ways of peace and tranquility are ours to uphold. May you find a place among us. We have much work to do. If you are a paladin of this temple. you must [desire to face fear].'
<p><b>You say, </b>'i desire to face fear'
<br><b>Vynon Estaliun says </b>'Very well. You shall face it. In Toxxulia Forest. you shall seek out Kerra Ridge. Once found. you will bring me the tail of a catfisher. Somehow. you shall find a way. They are weak. but they only work near the opposite side of the bridge. along the water's edge.'
<p><b>You give Vynon Estaliun : </b><a href=http://phobos/eq/item.php?id=13884>Fishy Cat Tail</a>
<br><b>Vynon Estaliun says </b>'Good work. I knew you could do it. Take this as reward.'
<br><b>Vynon Estaliun gives you : </b><a href=http://phobos/eq/item.php?id=13053>Brass Ring</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=247>Peace Keepers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=145>High Council of Erudin</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=143>Heretics</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>