<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13876>Bag of Shark Remains</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17938>Empty Shark Bag</a><li><a href=http://phobos/eq/item.php?id=17939>Empty Bag</a><li><a href=http://phobos/eq/item.php?id=12194>Barnacle Breastplate</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=79>Deepwater Knights</a><li><a href=http://phobos/eq/faction.php?id=145>High Council of Erudin</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=143>Heretics</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Weligon Steelherder says </b>'Hail. [Your Name]! This is the Deepwater Temple. Here you shall find the wisdom and courage of Prexus. the Ocean Lord. I am glad to see you have an interest. Forgive me if I cut our conversation short. but I have many [Deepwater tasks] to complete.'
<p><b>You say, </b>'what deepwater tasks'
<br><b>Weligon Steelherder says </b>'We here at the Deepwater Temple must tend to the [Peacekeeper battlestaff] and the [Deepwater harpoon] as well as other duties such as [ocean protection]. There is always something we must do.'
<p><b>You say, </b>'what deepwater harpoon'
<br><b>Weligon Steelherder says </b>'We do not award the Deepwater harpoon to just any paladin.  Nobility is all well and good. but you must still prove yourself.  We have heard rumors of a very distressing matter.  Perhaps it is your calling.  Are you ready to [prove allegiance to Erudin] and earn the Deepwater harpoon?'
<p><b>You say, </b>'i am ready to prove allegiance to erudin'
<br><b>Weligon Steelherder says </b>'There is no reason to dislike you. but we of the Deepwater Knights must see more done for our cause before we truly accept you.'
<p><b>You say, </b>'what peacekeeper battlestaff'
<br><b>Weligon Steelherder says </b>'Every sentinel in Erudin carries a High Guard battlestaff.  The creation of these weapons is the duty of the Deepwater Temple and the Temple of Divine Light.  Our portion of the task is to send young members to [collect the Pearls of Odus].  These are imbedded into the staff and used to store mystical power.'
<p><b>You say, </b>'i want to collect the pearls of odus'
<br><b>Weligon Steelherder says </b>'Then venture to the harbor of Erudin. There. you shall dive into the shark-infested water and search for the Pearls of Odus. They lie upon the grounds of our waters.  Fill the bag I have given you. combine it. and return it to me.  Good luck.'
<p><b>You say, </b>'ocean protection'
<br><b>Weligon Steelherder says </b>'In the name of Prexus. we are sworn to protect all ocean creatures.  We have heard reports of a shark carrying a deadly malady.  We believe she is pregnant.  If she delivers her young to the ocean. it will endanger all other creatures.  We need to find a young paladin to [hunt the diseased shark].'
<p><b>You say, </b>'hunt the diseased shark'
<br><b>Weligon Steelherder says </b>'Ah. yes!  Take this bag with you.  When you have collected the remains of the diseased shark and no fewer than three of her young in it. combine them in it and return it to me.  Then. you shall get your reward.'
<br><b>Weligon Steelherder gives you : </b><a href=http://phobos/eq/item.php?id=17938>Empty Shark Bag</a>
<p><b>You say, </b>'i will hunt the diseased shark'
<br><b>Weligon Steelherder says </b>'Ah. yes!  Take this bag with you.  When you have collected the remains of the diseased shark and no fewer than three of her young in it. combine them in it and return it to me.  Then. you shall get your reward.'
<br><b>Weligon Steelherder gives you : </b><a href=http://phobos/eq/item.php?id=17938>Empty Shark Bag</a>
<br><b>Weligon Steelherder says </b>'There is no reason to dislike you. but we of the Deepwater Knights must see more done for our cause before we truly accept you.'
<p><b>You say, </b>'i will collect the pearls of odus'
<br><b>Weligon Steelherder says </b>'Then venture to the harbor of Erudin. There. you shall dive into the shark-infested water and search for the Pearls of Odus. They lie upon the grounds of our waters.  Fill the bag I have given you. combine it. and return it to me.  Good luck.'
<br><b>Weligon Steelherder gives you : </b><a href=http://phobos/eq/item.php?id=17939>Empty Bag</a>
<p><b>You give Weligon Steelherder : </b><a href=http://phobos/eq/item.php?id=13876>Bag of Shark Remains</a>
<br><b>Weligon Steelherder says </b>'Very good, my dear young follower of Prexus. You will learn that swimming is a strong skill among the Deepwater Knights. Keep this up and you may wield a Deepwater harpoon soon enough. For now, you shall wear this barnacle breastplate. It is strong enough to aid a young knight in his quest for perfection.'
<br><b>Weligon Steelherder gives you : </b><a href=http://phobos/eq/item.php?id=12194>Barnacle Breastplate</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=79>Deepwater Knights</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=145>High Council of Erudin</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=143>Heretics</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>