<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1684>Charred Scale</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>a presence </b>ignores you.</font>
<p><b>You give a presence : </b><a href=http://phobos/eq/item.php?id=1684>Charred Scale</a>
<br><b>a presence says </b>'Hahaha! That dolt Eejag fell to the likes of you? Im not surprised. So, I guess this means you are here to challenge me. Normally, I wouldnt waste my time, but since you have defeated my younger brother, I suppose Im obligated.'
<br><b>a presence disappears.</b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=71069>Gwan</a></b> spawns.</font>
</td></tr></table>