<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>a thunder spirit princess says </b>'Greetings, travelers, welcome to the Plane of Sky! We are thunder spirits - this first island is our home. You are welcome to stay here as long as you like. If you wish to go to other islands you may purchase keys from the Key Master.'
<p><b>You say, </b>'gkzzallk'
<br><b>a thunder spirit princess says </b>'Gkzzallk lives far above here. We often take him tea because he's so nice to us fairies! He likes to chat with the others who live here and can often be found in the temple up above. If you give me a bit of money, I can go make sure he is home.'
<hr><b>When a thunder spirit princess is killed </b>
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=71058>Sirran_the_Lunatic</a></b> spawns.</font>
</td></tr></table>