<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20933>Ochre Tessera</a><li><a href=http://phobos/eq/item.php?id=20807>Silver Hoop</a><li><a href=http://phobos/eq/item.php?id=20806>Sky Emerald</a><li><a href=http://phobos/eq/item.php?id=20808>Dark Wood</a><li><a href=http://phobos/eq/item.php?id=20939>Gold Disc</a><li><a href=http://phobos/eq/item.php?id=20809>Small Shield</a><li><a href=http://phobos/eq/item.php?id=20946>Adumbrate Globe</a><li><a href=http://phobos/eq/item.php?id=20829>Glowing Diamond</a><li><a href=http://phobos/eq/item.php?id=20811>Shiny Pauldrons</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=14563>Truewind Earring</a><li><a href=http://phobos/eq/item.php?id=27716>Aegis of the Wind</a><li><a href=http://phobos/eq/item.php?id=27717>Pauldrons of Piety</a></ul></td><td><hr><b>When Alan Harten spawns </b>
<p><b>You say, </b>'hail'
<br><b>Alan Harten says </b>'Greetings faithful. Your faith shall be tested this day.  Shall you take the test of courage, skill, or protection?'
<p><b>You say, </b>'courage'
<br><b>Alan Harten says </b>'You have come seeking the knowledge and treasures that I posses. I will impart such things to you, if you do a service to your god. It matters not who that god may be, but the service and the faith you must exemplify. Bring to me an Ochre Tessera, a Sky Emerald, and a Silver Hoop.'
<p><b>You say, </b>'skill'
<br><b>Alan Harten says </b>'The test of skill it will be. Bring to me, a Gold Disc, a Dark Wood, and a Small Shield. You shall be rewarded upon your return.'
<p><b>You say, </b>'protection'
<br><b>Alan Harten says </b>'So, you must be a great protector to have ventured this far. Bring for me an Adumbrate Globe, a Glowing Diamond, and some Shiny Pauldrons for your reward.'
<p><b>You give Alan Harten : </b><a href=http://phobos/eq/item.php?id=20933>Ochre Tessera</a>, <a href=http://phobos/eq/item.php?id=20807>Silver Hoop</a>, <a href=http://phobos/eq/item.php?id=20806>Sky Emerald</a>
<br><b>Alan Harten gives you : </b><a href=http://phobos/eq/item.php?id=14563>Truewind Earring</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Alan Harten says </b>'Wonderful! Take this as your reward!'
<br><b>Alan Harten disappears.</b>
<p><b>You give Alan Harten : </b><a href=http://phobos/eq/item.php?id=20808>Dark Wood</a>, <a href=http://phobos/eq/item.php?id=20939>Gold Disc</a>, <a href=http://phobos/eq/item.php?id=20809>Small Shield</a>
<br><b>Alan Harten gives you : </b><a href=http://phobos/eq/item.php?id=27716>Aegis of the Wind</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Alan Harten says </b>'Wonderful! Take this as your reward!'
<br><b>Alan Harten disappears.</b>
<p><b>You give Alan Harten : </b><a href=http://phobos/eq/item.php?id=20946>Adumbrate Globe</a>, <a href=http://phobos/eq/item.php?id=20829>Glowing Diamond</a>, <a href=http://phobos/eq/item.php?id=20811>Shiny Pauldrons</a>
<br><b>Alan Harten gives you : </b><a href=http://phobos/eq/item.php?id=27717>Pauldrons of Piety</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Alan Harten says </b>'Wonderful! Take this as your reward!'
<br><b>Alan Harten disappears.</b>
<br><b>Alan Harten says </b>'What am I supposed to do with these?'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>