<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20947>Phosphoric Globe</a><li><a href=http://phobos/eq/item.php?id=20824>Shimmering Diamond</a><li><a href=http://phobos/eq/item.php?id=20825>Crude Wooden Flute</a><li><a href=http://phobos/eq/item.php?id=20940>Platinum Disc</a><li><a href=http://phobos/eq/item.php?id=20822>Music Box</a><li><a href=http://phobos/eq/item.php?id=20823>Light Woolen Mantle</a><li><a href=http://phobos/eq/item.php?id=20933>Ochre Tessera</a><li><a href=http://phobos/eq/item.php?id=20820>Songbird Statuette</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=27722>Ervaj's Flute of Flight</a><li><a href=http://phobos/eq/item.php?id=27721>Mantle of the Songweaver</a><li><a href=http://phobos/eq/item.php?id=27720>Mask of Song</a></ul></td><td><hr><b>When Denise Songweaver spawns </b>
<p><b>You say, </b>'hail'
<br><b>Denise Songweaver says </b>'Hi there [Your Name]! I give three sections of the test of songs, Denise does the rest. Do you wish to take the test of pitch, voice, or tone?'
<p><b>You say, </b>'pitch'
<br><b>Denise Songweaver says </b>'The pitch that we sing and play has a great affect on those that listen.  Keep this in mind Gendal, and you shall always be welcome in taverns and inns.  Now if you return to me Phosphoric Globe, a Shimmering Diamond, and crude wooden flute I will give to you Ervaj's Flute of Flight.'
<p><b>You say, </b>'voice'
<br><b>Denise Songweaver says </b>'The sweet sound rising forth from our throats are what makes us truly great.  Go forth and give voice to your songs, and return to me a platinum disc, a music box, and a light woolen mantle. If you do this I shall give you the Songweaver's Mantle. Good luck!'
<p><b>You say, </b>'tone'
<br><b>Denise Songweaver says </b>'Tone is important to all singers. Prove to me that you can keep your tone even and pure by bringing me an Ochre Tessera, a songbird statuette, and a light woolen cloak. If you do this I will give you the Mask of the Songbird.'
<p><b>You give Denise Songweaver : </b><a href=http://phobos/eq/item.php?id=20947>Phosphoric Globe</a>, <a href=http://phobos/eq/item.php?id=20824>Shimmering Diamond</a>, <a href=http://phobos/eq/item.php?id=20825>Crude Wooden Flute</a>
<br><b>Denise Songweaver gives you : </b><a href=http://phobos/eq/item.php?id=27722>Ervaj's Flute of Flight</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Denise Songweaver says </b>'Excellent! Take this as your reward.'
<br><b>Denise Songweaver disappears.</b>
<p><b>You give Denise Songweaver : </b><a href=http://phobos/eq/item.php?id=20940>Platinum Disc</a>, <a href=http://phobos/eq/item.php?id=20822>Music Box</a>, <a href=http://phobos/eq/item.php?id=20823>Light Woolen Mantle</a>
<br><b>Denise Songweaver gives you : </b><a href=http://phobos/eq/item.php?id=27721>Mantle of the Songweaver</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Denise Songweaver says </b>'Excellent! Take this as your reward.'
<br><b>Denise Songweaver disappears.</b>
<p><b>You give Denise Songweaver : </b><a href=http://phobos/eq/item.php?id=20933>Ochre Tessera</a>, <a href=http://phobos/eq/item.php?id=20823>Light Woolen Mantle</a>, <a href=http://phobos/eq/item.php?id=20820>Songbird Statuette</a>
<br><b>Denise Songweaver gives you : </b><a href=http://phobos/eq/item.php?id=27720>Mask of Song</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Denise Songweaver says </b>'Excellent! Take this as your reward.'
<br><b>Denise Songweaver disappears.</b>
<br><b>Denise Songweaver says </b>'What am I supposed to do with these?'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>