<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20813>Silvered Spiroc Necklace</a><li><a href=http://phobos/eq/item.php?id=20812>Spiroc Healing Totem</a><li><a href=http://phobos/eq/item.php?id=20954>Spiroc Statuette</a><li><a href=http://phobos/eq/item.php?id=20815>Djinni Aura</a><li><a href=http://phobos/eq/item.php?id=20816>Efreeti Mace</a><li><a href=http://phobos/eq/item.php?id=20814>Glowing Sapphire</a><li><a href=http://phobos/eq/item.php?id=20817>Efreeti Standard</a><li><a href=http://phobos/eq/item.php?id=20968>Manna Nectar</a><li><a href=http://phobos/eq/item.php?id=20819>Mithril Bands</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=14562>Necklace of Resolution</a></ul></td><td><hr><b>When Deric Lennox spawns </b>
<p><b>You say, </b>'hail'
<br><b>Deric Lennox says </b>'Greetings there lad. Come seekin glory then have ya? Alrighty

then, glorious ye shall be. Take me tests here, and I will show ya the light

there. Take ye the Test of Resolution, of Theurgy, or the Weak?'
<p><b>You say, </b>'resolution'
<br><b>Deric Lennox says </b>'The test of resolution be an easy one. Trust me there! Just

needin bring me a Spiroc Stattuete, a Spiroc Healing Totem, and a Silvered

Spiroc Necklace. Ne'r liked those birdies anyway.'
<p><b>You say, </b>'theurgy'
<br><b>Deric Lennox says </b>'The test of Theurgy. Ne'r understood it meself. It calls fer

you ta bring me an Efreeti Mace, a Saffron Spiroc Feather, a Glowing

Sapphire, and a Djinni Aura.'
<p><b>You say, </b>'weak'
<br><b>Deric Lennox says </b>'Aye, the weak. I laugh at 'em. Right after I put 'em in their

places. Aye. Bring me there lad, a Efreeti Standard, a Manna Nectar, and a

Shimmering Topaz. Yup, that'll do it.'
<p><b>You give Deric Lennox : </b><a href=http://phobos/eq/item.php?id=20813>Silvered Spiroc Necklace</a>, <a href=http://phobos/eq/item.php?id=20812>Spiroc Healing Totem</a>, <a href=http://phobos/eq/item.php?id=20954>Spiroc Statuette</a>
<br><b>Deric Lennox gives you : </b><a href=http://phobos/eq/item.php?id=14562>Necklace of Resolution</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Deric Lennox says </b>'Good on ya!'
<br><b>Deric Lennox disappears.</b>
<p><b>You give Deric Lennox : </b><a href=http://phobos/eq/item.php?id=20815>Djinni Aura</a>, <a href=http://phobos/eq/item.php?id=20816>Efreeti Mace</a>, <a href=http://phobos/eq/item.php?id=20814>Glowing Sapphire</a>
<br><b>Deric Lennox says </b>'What am I supposed to do with these?'
<p><b>You give Deric Lennox : </b><a href=http://phobos/eq/item.php?id=20817>Efreeti Standard</a>, <a href=http://phobos/eq/item.php?id=20968>Manna Nectar</a>, <a href=http://phobos/eq/item.php?id=20819>Mithril Bands</a>
<br><b>Deric Lennox says </b>'What am I supposed to do with these?'
<br><b>Deric Lennox says </b>'What am I supposed to do with these?'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>