<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20943>Diaphanous Globe</a><li><a href=http://phobos/eq/item.php?id=20869>Ivory Sky Diamond</a><li><a href=http://phobos/eq/item.php?id=20868>Silvery Girdle</a></ul></td><td><hr><b>When Dirkog Steelhand spawns </b>
<p><b>You say, </b>'hail'
<br><b>Dirkog Steelhand says </b>'Leave me be, ye orc kissin' son o' Innoruuk!'
<p><b>You say, </b>'I am not a son of Innoruuk'
<br><b>Dirkog Steelhand says </b>'Eh? Ye say that ye ain't one o' the cursed dark elf dogs? Well then, laddie, are ye ready to get started or are ye here fer somethin' else??'
<p><b>You say, </b>'holy swords'
<br><b>Dirkog Steelhand says </b>'Eh, lad? What was that? Ye wish to hear o' holy swords? Well, lad, I ain't the one ye be needin' t' talk to!'
<p><b>You say, </b>'who do I need to talk to'
<br><b>Dirkog Steelhand says </b>'A follower o' the water god he be, an' one o' the most powerful holy knights e'er to walk Norrath. His name be Inte Akera, an' he kin tell ye what ye be wantin' t' know.'
<p><b>You say, </b>'where is inte akera'
<br><b>Dirkog Steelhand says </b>'Ah, I see ye wish t' speak with him! Why didn't ye say that earlier, laddie? It would've saved ye some trouble! If ye wish to speak with him, ye must donate some spare change t' me ale.. er, t' me holy crusade fund! Well, lad, what d' ye say?'
<p><b>You say, </b>'donate'
<br><b>Dirkog Steelhand says </b>'Eh? Oh, 500 platinum will be plenty, laddie!'
<p><b>You say, </b>'ready to get started'
<br><b>Dirkog Steelhand says </b>'Well then! You best go out an get me a silvery girdle, a diaphanous globe, an a ivory sky diamond! Come on back with them and you'll get a nice belt.'
<p><b>You give Dirkog Steelhand : </b><a href=http://phobos/eq/item.php?id=20943>Diaphanous Globe</a>, <a href=http://phobos/eq/item.php?id=20869>Ivory Sky Diamond</a>, <a href=http://phobos/eq/item.php?id=20868>Silvery Girdle</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Dirkog Steelhand says </b>'There ya go laddie!'
<br><b>Dirkog Steelhand disappears.</b>
<br><b>Dirkog Steelhand says </b>'What am I supposed to do with these?'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>