<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>Drakis Bloodcaster says </b>'Greetings, . Are you ready to begin?'
<p><b>You say, </b>'ready to begin'
<br><b>Drakis Bloodcaster says </b>'Who would you like to be tested by? Jzil or Dugaas?'
<p><b>You say, </b>'jzil'
<br><b>Drakis Bloodcaster says </b>'Very well.'
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=71074>Jzil_GSix</a></b> spawns (1305,654.9,-762.2).</font>
<br><b>Drakis Bloodcaster disappears.</b>
<p><b>You say, </b>'Dugaas'
</td></tr></table>