<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20953>Imp Statuette</a><li><a href=http://phobos/eq/item.php?id=20786>Obsidian Amulet</a><li><a href=http://phobos/eq/item.php?id=20787>Pulsating Ruby</a><li><a href=http://phobos/eq/item.php?id=20790>Gorgon Head</a><li><a href=http://phobos/eq/item.php?id=20967>Aged Nectar</a><li><a href=http://phobos/eq/item.php?id=20791>Glowing Black Pearl</a><li><a href=http://phobos/eq/item.php?id=20960>White Spiroc Feather</a><li><a href=http://phobos/eq/item.php?id=20788>Nebulous Ruby</a><li><a href=http://phobos/eq/item.php?id=20789>Ring of Veeshan</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=14560>Sphinx Heart Amulet</a><li><a href=http://phobos/eq/item.php?id=27713>Band of Wailing Winds</a></ul></td><td><hr><b>When Duggas Helpyre spawns </b>
<p><b>You say, </b>'hail'
<br><b>Duggas Helpyre says </b>'So, you dare be seen in my precense. Truly a brave fool you
are. You come seeking fame and glory here do you? Well fool, perhaps you will
get what you seek. Shall you take the test of the Heart, the Hands, or the
Finger?'
<p><b>You say, </b>'heart'
<br><b>Duggas Helpyre says </b>'So the heart it be. Bring me, foolish one, an Imp Statuette,
an Obsidian Amulet, and a Pulsating Ruby. Perhaps then, you shall find your
reward.'
<p><b>You say, </b>'hands'
<br><b>Duggas Helpyre says </b>'The test of the Hands it shall be. Bring me a Gorgon's Head,
some Aged Nectar, a Glowing Black Pearl, and an Efreeti's Great Staff. When
you return, I shall reward you for your deeds, assuming you live through the
experience. Hahaha!'
<p><b>You say, </b>'finger'
<br><b>Duggas Helpyre says </b>'The finger. Needed for nearly every casting you shall ever
hope to produce, it truly is the most powerful creation. Should you bring me
a White Spiroc Feather, a Nebulous Ring, and the Ring of Veeshan, I shall
reward you with power that you can just now begin to comprehend.'
<p><b>You give Duggas Helpyre : </b><a href=http://phobos/eq/item.php?id=20953>Imp Statuette</a>, <a href=http://phobos/eq/item.php?id=20786>Obsidian Amulet</a>, <a href=http://phobos/eq/item.php?id=20787>Pulsating Ruby</a>
<br><b>Duggas Helpyre gives you : </b><a href=http://phobos/eq/item.php?id=14560>Sphinx Heart Amulet</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Duggas Helpyre says </b>'Haha! So you lived! Take this and be gone!'
<br><b>Duggas Helpyre disappears.</b>
<p><b>You give Duggas Helpyre : </b><a href=http://phobos/eq/item.php?id=20790>Gorgon Head</a>, <a href=http://phobos/eq/item.php?id=20967>Aged Nectar</a>, <a href=http://phobos/eq/item.php?id=20791>Glowing Black Pearl</a>
<br><b>Duggas Helpyre says </b>'What? What are these for? Go Away!'
<p><b>You give Duggas Helpyre : </b><a href=http://phobos/eq/item.php?id=20960>White Spiroc Feather</a>, <a href=http://phobos/eq/item.php?id=20788>Nebulous Ruby</a>, <a href=http://phobos/eq/item.php?id=20789>Ring of Veeshan</a>
<br><b>Duggas Helpyre gives you : </b><a href=http://phobos/eq/item.php?id=27713>Band of Wailing Winds</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Duggas Helpyre says </b>'Haha! So you lived! Take this and be gone!'
<br><b>Duggas Helpyre disappears.</b>
<br><b>Duggas Helpyre says </b>'What? What are these for? Go Away!'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>