<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Enchanter Jolas says </b>'Greetings, [Your Name].  Have you come here to test your powers of enchantment?'
<p><b>You say, </b>'enchantment'
<br><b>Enchanter Jolas says </b>'I am most honored to be able to help you. Please choose from one of my instructors. Lelulean or Enderbite.'
<p><b>You say, </b>'Enderbite'
<p><b>You say, </b>'lelulean'
</td></tr></table>