<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20931>Crimson Tessera</a><li><a href=http://phobos/eq/item.php?id=20754>Ethereal Sapphire</a><li><a href=http://phobos/eq/item.php?id=20755>Feathered Cape</a><li><a href=http://phobos/eq/item.php?id=20937>Iron Disc</a><li><a href=http://phobos/eq/item.php?id=20756>Gem of Empowerment</a><li><a href=http://phobos/eq/item.php?id=20757>Ceramic Mask</a><li><a href=http://phobos/eq/item.php?id=20944>Hyaline Globe</a><li><a href=http://phobos/eq/item.php?id=20758>Ivory Pendant</a><li><a href=http://phobos/eq/item.php?id=20759>Golden Coffer</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1274>Bracelet of Clarification</a><li><a href=http://phobos/eq/item.php?id=2707>Mask of Empowerment</a><li><a href=http://phobos/eq/item.php?id=14557>Gold White Pendant</a></ul></td><td><hr><b>When Frederic Calermin spawns </b>
<p><b>You say, </b>'hail'
<br><b>Frederic Calermin says </b>'Great, let us waste no more time! I offer to you three challenges. Clarification, Empowerment, and Shielding. Please choose one of these.'
<p><b>You say, </b>'clarification'
<br><b>Frederic Calermin says </b>'Clarification it is. Proceed upward through the sky and return to me a Crimson Tessera, an Ethereal Sapphire, and Feathered Cape.  This will prove your abilities to me and I will reward you with the Bracelet of Clarification.'
<p><b>You say, </b>'empowerment'
<br><b>Frederic Calermin says </b>'Empowerment it is. Proceed upward through the sky and return to me an Iron Disc, a Gem of Empowerment, and a Ceramic Mask. This will prove your abilities to me and I will reward you with the Mask of Empowerment.'
<p><b>You say, </b>'shielding'
<br><b>Frederic Calermin says </b>'Shielding it is. Proceed upward through the sky and return to me a Hyaline Globe, an Ivory Pendant, and a Golden Coffer. This will prove your abilities to me and I will reward you with an Gold White Pendant.'
<p><b>You give Frederic Calermin : </b><a href=http://phobos/eq/item.php?id=20931>Crimson Tessera</a>, <a href=http://phobos/eq/item.php?id=20754>Ethereal Sapphire</a>, <a href=http://phobos/eq/item.php?id=20755>Feathered Cape</a>
<br><b>Frederic Calermin gives you : </b><a href=http://phobos/eq/item.php?id=1274>Bracelet of Clarification</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Frederic Calermin says </b>'Take this as your reward.'
<br><b>Frederic Calermin disappears.</b>
<p><b>You give Frederic Calermin : </b><a href=http://phobos/eq/item.php?id=20937>Iron Disc</a>, <a href=http://phobos/eq/item.php?id=20756>Gem of Empowerment</a>, <a href=http://phobos/eq/item.php?id=20757>Ceramic Mask</a>
<br><b>Frederic Calermin gives you : </b><a href=http://phobos/eq/item.php?id=2707>Mask of Empowerment</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Frederic Calermin says </b>'Take this as your reward.'
<br><b>Frederic Calermin disappears.</b>
<p><b>You give Frederic Calermin : </b><a href=http://phobos/eq/item.php?id=20944>Hyaline Globe</a>, <a href=http://phobos/eq/item.php?id=20758>Ivory Pendant</a>, <a href=http://phobos/eq/item.php?id=20759>Golden Coffer</a>
<br><b>Frederic Calermin gives you : </b><a href=http://phobos/eq/item.php?id=14557>Gold White Pendant</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Frederic Calermin says </b>'Take this as your reward.'
<br><b>Frederic Calermin disappears.</b>
<br><b>Frederic Calermin says </b>'What am I supposed to do with these?'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>