<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20955>Djinni Statuette</a><li><a href=http://phobos/eq/item.php?id=20856>Spiroc Thunder Totem</a><li><a href=http://phobos/eq/item.php?id=20857>White Gold Earring</a><li><a href=http://phobos/eq/item.php?id=20859>Bitter Honey</a><li><a href=http://phobos/eq/item.php?id=20860>Circlet of Brambles</a><li><a href=http://phobos/eq/item.php?id=20858>Efreeti Long Sword</a><li><a href=http://phobos/eq/item.php?id=20861>Efreeti War Bow</a><li><a href=http://phobos/eq/item.php?id=20969>Thickened Nectar</a><li><a href=http://phobos/eq/item.php?id=20862>Sphinx Tallow</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=14568>Thunderforged Earring</a></ul></td><td><hr><b>When Gordon Treecaller spawns </b>
<p><b>You say, </b>'hail'
<br><b>Gordon Treecaller says </b>'Hello [Your Name], I can only hope that my disturbance was necessary. Ahh, you seem to be decently adept with a blade. Would you like to be tested in the element of thunder, the blade, or the art of ranged attack?'
<p><b>You say, </b>'element of thunder'
<br><b>Gordon Treecaller says </b>'One of my greatest allies indeed. Thunder can be very powerful if used properly. Bring me a djinni statuette, a spiroc thunder totem, and a white gold earring. Then you will know the true power of nature.'
<p><b>You say, </b>'blade'
<br><b>Gordon Treecaller says </b>'Very good choice, my blade is my best friend and yours will be as well if you can complete this task. Retrieve an efreeti long sword, an emerald spiroc feather, some bitter honey, and a circlet of thorns. Be careful with the honey, if it is tainted the blade will not come to life.'
<p><b>You say, </b>'art of ranged attack'
<br><b>Gordon Treecaller says </b>'Many of the fools on Norrath don’t realize how powerful a good bow can be. Many dread wolves have met their fate from my bow and you can have the same power if you can bring me back these items. Efreeti war bow, thickened nectar, a sphinx tallow, and a shimmering pearl.'
<p><b>You give Gordon Treecaller : </b><a href=http://phobos/eq/item.php?id=20955>Djinni Statuette</a>, <a href=http://phobos/eq/item.php?id=20856>Spiroc Thunder Totem</a>, <a href=http://phobos/eq/item.php?id=20857>White Gold Earring</a>
<br><b>Gordon Treecaller gives you : </b><a href=http://phobos/eq/item.php?id=14568>Thunderforged Earring</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Gordon Treecaller says </b>'Take this as your reward.'
<br><b>Gordon Treecaller disappears.</b>
<p><b>You give Gordon Treecaller : </b><a href=http://phobos/eq/item.php?id=20859>Bitter Honey</a>, <a href=http://phobos/eq/item.php?id=20860>Circlet of Brambles</a>, <a href=http://phobos/eq/item.php?id=20858>Efreeti Long Sword</a>
<br><b>Gordon Treecaller says </b>'What am I supposed to do with these?'
<p><b>You give Gordon Treecaller : </b><a href=http://phobos/eq/item.php?id=20861>Efreeti War Bow</a>, <a href=http://phobos/eq/item.php?id=20969>Thickened Nectar</a>, <a href=http://phobos/eq/item.php?id=20862>Sphinx Tallow</a>
<br><b>Gordon Treecaller says </b>'What am I supposed to do with these?'
<br><b>Gordon Treecaller says </b>'What am I supposed to do with these?'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>