<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>Gorgalosk says </b>'Greetings, [Your Name]. This is my domain and I hope you have a peaceful stay. That is, unless the [lunatic sent you].'
<p><b>You say, </b>'lunatic sent me'
<br><b>Gorgalosk says </b>'Oh, I see. I suppose you [want these cursed markers] that lunatic made me hold?'
<p><b>You say, </b>'cursed markers'
<br><b>Gorgalosk says </b>'I am afraid that I can not just give them away. The lunatic had them cursed. They make me do [strange things]'
<p><b>You say, </b>'strange things'
<br><b>Gorgalosk says </b>'Like ATTACK you!'
<hr><b>When Gorgalosk is killed </b>
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=71058>Sirran_the_Lunatic</a></b> spawns.</font>
</td></tr></table>