<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Gragrot says </b>'Hail!  So you think you are a mighty Knight of Shadows?  We must test these skills.  Are you ready to begin the test?  Or do you think you have already proof of your deeds?'
<p><b>You say, </b>'i am ready to begin the test'
<br><b>Gragrot says </b>'Great, let us waste no more time!  I offer to you three challenges,  Bash, smash, or slash?  What do you wish to be tested in?'
</td></tr></table>