<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When Gwan spawns </b>
<br><b>Gwan says </b>'Im ready when you are, [Your Name]. Tell me when you are [prepared].'
<p><b>You say, </b>'hail'
<br><font color=green><b>Gwan </b>ignores you.</font>
<p><b>You say, </b>'prepared'
<hr><b>When Gwan is killed </b>
<br><font color=green><b>Gwan </b>lets out one last, frustrated breath and gasps.</font>
<br><b>Gwan says </b>'Trunt! Prepare yourself!'
</td></tr></table>