<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Holwin says </b>'Peace to you, [Your Name].  I see that you have come far along the path of tranquility and enlightenment.  Do you wish to test yourself further, and perhaps complete the path you started on so long ago?'
<p><b>You say, </b>'tranquility and enlightenment'
<p><b>You say, </b>'wu'
<p><b>You say, </b>'ton po'
</td></tr></table>