<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=5504>SoulFire</a><li><a href=http://phobos/eq/item.php?id=5403>Ghoulbane</a><li><a href=http://phobos/eq/item.php?id=18033>Inte's First Blessing</a><li><a href=http://phobos/eq/item.php?id=18034>Inte's Second Blessing</a><li><a href=http://phobos/eq/item.php?id=19073>Miragul's Head</a><li><a href=http://phobos/eq/item.php?id=1254>Miragul's Robe</a></ul></td><td><hr><b>When Inte Akera spawns </b>
<p><b>You say, </b>'hail'
<br><b>Inte Akera says </b>'Greetings, [Your Name]. I am Inte Akera. I have retired to the Plane of Sky after a long life toiling on Norrath's soil. Have you retreated here as well, or are you merely visiting?'
<p><b>You say, </b>'toil'
<br><b>Inte Akera says </b>'Long ago, before I came to this plane, I fought in the name of Prexus against all the evils that plagued Norrath. In that time, I have done everything one can do. I have fought for the causes of good. I gained the esteem of kings and lords. The sword I hold is but one example of the treasures I have sought and won. I have accomplished all that I can, have all that I desire. My toil is done and now I sit among the clouds in peace, occasionally blessing those who seek it and are found worthy.'
<p><b>You say, </b>'blessing'
<br><b>Inte Akera says </b>'Many come seeking my blessings. No matter how minor the blessing they ask, all must prove that they embody the qualities of a paladin before I bless them.'
<p><b>You say, </b>'prove myself'
<br><b>Inte Akera says </b>'I believe the two most important qualities of a paladin are nobility and sacrifice. Hand me an item of yours that proves you understand what nobility and sacrifice are. Be warned however, if I do not think as you do, I will simply accept the item as a gift, and give you no blessing.'
<p><b>You say, </b>'nobility'
<br><b>Inte Akera says </b>'Ah nobility. A true measure of a paladin. If you are wondering what to bring me, then perhaps you should look within yourself. Look into your soul for a great, burning fire of nobility and you will know.'
<p><b>You say, </b>'sacrifice'
<br><b>Inte Akera says </b>'Sacrifice is a virtue all paladins should strive for. The sacrifice of something dear to you will show your devotion. Perhaps something you use to smite the unholy undead.'
<p><b>You say, </b>'accomplish'
<br><b>Inte Akera says </b>'I accomplished many great deeds; far too many to name. I saved kings and kingdoms; I helped the weak and destitue; I accomplished all I sought to do, save one at which I failed.'
<p><b>You say, </b>'failed'
<br><b>Inte Akera says </b>'No.. I was unable to kill my most hated foe, Miragul. The head of this wretched, foul necromancer is forever out of the reach of justice. It would be worth restoring him to his former state for the chance to take his head as a trophy.'
<p><b>You say, </b>'miragul'
<br><b>Inte Akera says </b>'You think you can succeed where I cannot? Perhaps you can noble one.. Bring me the head of Miragul, his robe and hand me back the two blessings I gave you, and in return I shall bequeath to you this sword I carry. Good luck my friend.'
<p><b>You give Inte Akera : </b><a href=http://phobos/eq/item.php?id=5504>SoulFire</a>
<br><b>Inte Akera says </b>'What am I supposed to do with these?'
<p><b>You give Inte Akera : </b><a href=http://phobos/eq/item.php?id=5403>Ghoulbane</a>
<br><b>Inte Akera says </b>'What am I supposed to do with these?'
<p><b>You give Inte Akera : </b><a href=http://phobos/eq/item.php?id=18033>Inte's First Blessing</a>, <a href=http://phobos/eq/item.php?id=18034>Inte's Second Blessing</a>, <a href=http://phobos/eq/item.php?id=19073>Miragul's Head</a>, <a href=http://phobos/eq/item.php?id=1254>Miragul's Robe</a>
<br><b>Inte Akera says </b>'What am I supposed to do with these?'
<br><b>Inte Akera says </b>'What am I supposed to do with these?'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>