<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20932>Verdant Tessera</a><li><a href=http://phobos/eq/item.php?id=20780>Ebon Shard</a><li><a href=http://phobos/eq/item.php?id=20781>Griffon's Beak</a><li><a href=http://phobos/eq/item.php?id=20938>Silver Disc</a><li><a href=http://phobos/eq/item.php?id=20782>Spiroc Feathers</a><li><a href=http://phobos/eq/item.php?id=20783>Black Silk Cape</a><li><a href=http://phobos/eq/item.php?id=20945>Rugous Globe</a><li><a href=http://phobos/eq/item.php?id=20784>Djinni Blood</a><li><a href=http://phobos/eq/item.php?id=20785>Fine Cloth Raiment</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=27712>Bloody Griffon-Hide Wrist Guard</a><li><a href=http://phobos/eq/item.php?id=1278>Cloak of Spiroc Feathers</a><li><a href=http://phobos/eq/item.php?id=1279>Bloodsoaked Raiment</a></ul></td><td><hr><b>When Jzil GSix spawns </b>
<p><b>You say, </b>'hail'
<br><b>Jzil GSix says </b>'Ah, so you have come to be tested. Many fine things can be your reward. There are three tests which I can administer. Shall you take the test of flight, power, or mind? '
<p><b>You say, </b>'flight'
<br><b>Jzil GSix says </b>'So, you wish the test of flight? So be it. You must return to me a Verdant Tessera, and Ebon Shard, and a Griffons Beak to reap your rewards. May the darkness guide your steps.'
<p><b>You say, </b>'test of power'
<br><b>Jzil GSix says </b>'The test of power it is. Prove yourself worthy of power and bring me a silver disc, spiroc feathers, and a black silk cape. Only then will you know true power.'
<p><b>You say, </b>'mind'
<br><b>Jzil GSix says </b>'So, the test of mind it shall be. You must return to me, from this place of air and mist, a Rogous Globe, some Djinni Blood, and some Fine Cloth Raiments. Then, and only then, you shall have the reward that you deserve!'
<p><b>You give Jzil GSix : </b><a href=http://phobos/eq/item.php?id=20932>Verdant Tessera</a>, <a href=http://phobos/eq/item.php?id=20780>Ebon Shard</a>, <a href=http://phobos/eq/item.php?id=20781>Griffon's Beak</a>
<br><b>Jzil GSix gives you : </b><a href=http://phobos/eq/item.php?id=27712>Bloody Griffon-Hide Wrist Guard</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Jzil GSix says </b>'Very good. Now take this and leave me.'
<br><b>Jzil GSix disappears.</b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=71053>Drakis_Bloodcaster</a></b> spawns.</font>
<p><b>You give Jzil GSix : </b><a href=http://phobos/eq/item.php?id=20938>Silver Disc</a>, <a href=http://phobos/eq/item.php?id=20782>Spiroc Feathers</a>, <a href=http://phobos/eq/item.php?id=20783>Black Silk Cape</a>
<br><b>Jzil GSix gives you : </b><a href=http://phobos/eq/item.php?id=1278>Cloak of Spiroc Feathers</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Jzil GSix says </b>'Very good. Now take this and leave me.'
<br><b>Jzil GSix disappears.</b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=71053>Drakis_Bloodcaster</a></b> spawns.</font>
<p><b>You give Jzil GSix : </b><a href=http://phobos/eq/item.php?id=20945>Rugous Globe</a>, <a href=http://phobos/eq/item.php?id=20784>Djinni Blood</a>, <a href=http://phobos/eq/item.php?id=20785>Fine Cloth Raiment</a>
<br><b>Jzil GSix gives you : </b><a href=http://phobos/eq/item.php?id=1279>Bloodsoaked Raiment</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Jzil GSix says </b>'Very good. Now take this and leave me.'
<br><b>Jzil GSix disappears.</b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=71053>Drakis_Bloodcaster</a></b> spawns.</font>
<br><b>Jzil GSix says </b>'Fool! I do not need these!'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>