<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20928>Ivory Tessera</a><li><a href=http://phobos/eq/item.php?id=20984>Gem of Invigoration</a><li><a href=http://phobos/eq/item.php?id=20985>Inlaid Choker</a><li><a href=http://phobos/eq/item.php?id=20989>Spiroc Sky Totem</a><li><a href=http://phobos/eq/item.php?id=20942>Pearlescent Globe</a><li><a href=http://phobos/eq/item.php?id=20988>Black Griffon Feather</a><li><a href=http://phobos/eq/item.php?id=20956>Mottled Spiroc Feather</a><li><a href=http://phobos/eq/item.php?id=20992>Cracked Leather Belt</a><li><a href=http://phobos/eq/item.php?id=20993>Sphinxian Circlet</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=14552>Wispy Choker of Vigor</a><li><a href=http://phobos/eq/item.php?id=2703>Griffon Wing Spauldors</a><li><a href=http://phobos/eq/item.php?id=11676>Renard's Belt of Quickness</a></ul></td><td><hr><b>When Kendrick spawns </b>
<p><b>You say, </b>'hail'
<br><b>Kendrick says </b>'Great, let us waste no more time! Do you wish to begin your 	test of Thievery, Silence, or Trickery?'
<p><b>You say, </b>'thievery'
<br><b>Kendrick says </b>'Thievery is absolute. Travel beyond and bring forth an Ivory Tessera, a gem of invigoration, and an inlaid choker to complete the test of thievery and earn the wispy choker of vigor!'
<p><b>You say, </b>'silence'
<br><b>Kendrick says </b>'Silence makes us deadly. Proceed upward and bring to me a spiroc sky totem, a pearlescent globe, and a black griffon feather. Griffon Wing Spauldors shall be yours if you complete this.'
<p><b>You say, </b>'trickery'
<br><b>Kendrick says </b>'Trickery, ahh how Fizzlethorpe blesses us! Adventure and return a mottled spiroc feather, a cracked leather belt, and a sphinxian circlet to complete the test of trickery and earn Renards Belt of Quickness.'
<p><b>You give Kendrick : </b><a href=http://phobos/eq/item.php?id=20928>Ivory Tessera</a>, <a href=http://phobos/eq/item.php?id=20984>Gem of Invigoration</a>, <a href=http://phobos/eq/item.php?id=20985>Inlaid Choker</a>
<br><b>Kendrick gives you : </b><a href=http://phobos/eq/item.php?id=14552>Wispy Choker of Vigor</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Kendrick says </b>'Excellent! Fizzlethorpe blesses you with this gift.'
<br><b>Kendrick disappears.</b>
<p><b>You give Kendrick : </b><a href=http://phobos/eq/item.php?id=20989>Spiroc Sky Totem</a>, <a href=http://phobos/eq/item.php?id=20942>Pearlescent Globe</a>, <a href=http://phobos/eq/item.php?id=20988>Black Griffon Feather</a>
<br><b>Kendrick gives you : </b><a href=http://phobos/eq/item.php?id=2703>Griffon Wing Spauldors</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Kendrick says </b>'Excellent! Fizzlethorpe blesses you with this gift.'
<br><b>Kendrick disappears.</b>
<p><b>You give Kendrick : </b><a href=http://phobos/eq/item.php?id=20956>Mottled Spiroc Feather</a>, <a href=http://phobos/eq/item.php?id=20992>Cracked Leather Belt</a>, <a href=http://phobos/eq/item.php?id=20993>Sphinxian Circlet</a>
<br><b>Kendrick gives you : </b><a href=http://phobos/eq/item.php?id=11676>Renard's Belt of Quickness</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Kendrick says </b>'Excellent! Fizzlethorpe blesses you with this gift.'
<br><b>Kendrick disappears.</b>
<br><b>Kendrick says </b>'What am I supposed to do with these?'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>