<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20764>Crown of Elemental Mastery</a><li><a href=http://phobos/eq/item.php?id=28043>Elemental Binder</a><li><a href=http://phobos/eq/item.php?id=2463>Pegasus Feather Cloak</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=28033>Element of Wind</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Kihun Solstin says </b>'So, you have made it this far. I am Kihun Solstin, the Master of Wind. I control the unfettered Element like none other. As you should have learned, Air is the most potent of Elements. It fuels Fire, Water is comprised of it, and Earth cannot restrain it. Knowing this, do you seek the Element of Wind?'
<p><b>You say, </b>'i seek the element of wind'
<br><b>Kihun Solstin says </b>'I will test you then. In this wondrous plane of Sky, find the Crown of Elemental Mastery. Then, search the world below for an Elemental Binder and a cloak fashioned from the feathers of a Pegusus. Return them to me and I shall give you the Element of Wind.'
<p><b>You say, </b>'see the master'
<br><b>Kihun Solstin says </b>'Very well.'
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=71040>#Master_of_Elements</a></b> spawns (1346.3,604.5,-766).</font>
<p><b>You give Kihun Solstin : </b><a href=http://phobos/eq/item.php?id=20764>Crown of Elemental Mastery</a>, <a href=http://phobos/eq/item.php?id=28043>Elemental Binder</a>, <a href=http://phobos/eq/item.php?id=2463>Pegasus Feather Cloak</a>
<br><b>Kihun Solstin says </b>'If you have obtained the other, lesser Elements, go speak with The Master of Elements, who is now waiting for you. I wish you luck. If you have not completed all the tasks set for you, let me know, and I shall let you see the Master.'
<br><b>Kihun Solstin gives you : </b><a href=http://phobos/eq/item.php?id=28033>Element of Wind</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=71040>#Master_of_Elements</a></b> spawns (1346.3,604.5,-766).</font>
<br><b>Kihun Solstin says </b>'I have no need for this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>