<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Medicine Man Veetra says </b>'Good day to you, [Your Name]. Are you a shaman of [much experience]?'
<p><b>You say, </b>'much experience'
<br><b>Medicine Man Veetra says </b>'Then welcome to the tests of the medicine man. I have two tomes, each tells of a shaman of great accomplishment. They are Gina MacStargan and Ooga. Simply tell me the name of the shaman you want to be tested by.'
<p><b>You say, </b>'Gina MacStargan'
<p><b>You say, </b>'Ooga'
</td></tr></table>