<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Overseer of Air says </b>'So you have awakened me!! It seems my brother was not much of a challenge. Before we get on to business, there are some matters that must be addressed. But enough talk, let's address these matters first.'
<p><b>You say, </b>'matters'
<br><b>Overseer of Air says </b>'The matter at hand is where you are to go after this. I believe that crazy halfling will be showing up. But if by chance he oversleeps, there is some information you should have.'
<p><b>You say, </b>'information'
<br><b>Overseer of Air says </b>'You have come to my home. This is also home to the soul carriers and essence harvesters. On the mortal plane, they are still natural enemies, but have learned to live together and are now peaceful creatures here in the Plane of Sky. Be forewarned that as you proceed about your tour, each gate you must reach and pass through will become substantially harder.'
<hr><b>When Overseer of Air is killed </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=71060>the_Hand_of_Veeshan</a></b> spawns (-270.1,-1462.2,1250.9).</font>
</td></tr></table>