<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20963>Honeyed Nectar</a><li><a href=http://phobos/eq/item.php?id=20994>Bixie Stinger</a><li><a href=http://phobos/eq/item.php?id=20995>Lightning Rod</a><li><a href=http://phobos/eq/item.php?id=20949>Pegasus Statuette</a><li><a href=http://phobos/eq/item.php?id=20990>Prismatic Sphere</a><li><a href=http://phobos/eq/item.php?id=20935>Bronze Disc</a><li><a href=http://phobos/eq/item.php?id=20987>Jester's Mask</a></ul></td><td><hr><b>When Rayne spawns </b>
<p><b>You say, </b>'hail'
<br><b>Rayne says </b>'Great, let us waste no more time! Do you wish to begin your

test of Deception, Stealth, or Cunning?'
<p><b>You say, </b>'deception'
<br><b>Rayne says </b>'Deception it is. Proceed upward through the sky and return to

me the honeyed nectar, a bixie stinger, a lightning rod, and a bloodsky

sapphire for the test of deception and earn Ebonsting, caller of

lightning.'
<p><b>You say, </b>'stealth'
<br><b>Rayne says </b>'Stealth is a must. Travel among the residents of the sky and

bring to me a Pegasus Statuette, a Prismatic Sphere, and a Fine Wool Cloak. 

In return, The Scintillating Bracer of Protection shall be yours.'
<p><b>You say, </b>'cunning'
<br><b>Rayne says </b>'Cunning, the true source of all rogue power. Plan and succeed

above us and return to me a bronze disc, a jester's mask, and some red face

paint to compelte the test of cunning. The transparent mask shall be yours if

you do so.'
<p><b>You give Rayne : </b><a href=http://phobos/eq/item.php?id=20963>Honeyed Nectar</a>, <a href=http://phobos/eq/item.php?id=20994>Bixie Stinger</a>, <a href=http://phobos/eq/item.php?id=20995>Lightning Rod</a>
<br><b>Rayne says </b>'What am I supposed to do with these?'
<p><b>You give Rayne : </b><a href=http://phobos/eq/item.php?id=20949>Pegasus Statuette</a>, <a href=http://phobos/eq/item.php?id=20990>Prismatic Sphere</a>
<br><b>Rayne says </b>'What am I supposed to do with these?'
<p><b>You give Rayne : </b><a href=http://phobos/eq/item.php?id=20935>Bronze Disc</a>, <a href=http://phobos/eq/item.php?id=20987>Jester's Mask</a>
<br><b>Rayne says </b>'What am I supposed to do with these?'
<br><b>Rayne says </b>'What am I supposed to do with these?'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>