<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20934>Auburn Tessera</a><li><a href=http://phobos/eq/item.php?id=20850>Griffon Talon</a><li><a href=http://phobos/eq/item.php?id=20849>Ysgaril Root</a><li><a href=http://phobos/eq/item.php?id=20853>Fine Velvet Cloak</a><li><a href=http://phobos/eq/item.php?id=20852>Harpy Tongue</a><li><a href=http://phobos/eq/item.php?id=20854>Dragon-hide Mantle</a><li><a href=http://phobos/eq/item.php?id=20948>Gridelin Globe</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2715>Spiroc Healer's Cloak</a></ul></td><td><hr><b>When Relinin Skyrunner spawns </b>
<p><b>You say, </b>'hail'
<br><b>Relinin Skyrunner says </b>'Greetings [Your Name]. I can only assume my reasons for being

summoned is that you wish to take the tests. Would you like to be tested in

the body, in defense, or in the element of earth?'
<p><b>You say, </b>'body'
<br><b>Relinin Skyrunner says </b>'Very well. You must scour this plane and bring back to me

these components: an auburn tessera, a ysgaril root, and a griffon talon.

Make haste, and good luck.'
<p><b>You say, </b>'defense'
<br><b>Relinin Skyrunner says </b>'Defense it is. You must prove yourself worthy enough for the

Spiroc spirits to guard you. Bring back to me a mithril disc, a harpy tongue,

and a fine velvet cloak. Good luck to you [Your Name].'
<p><b>You say, </b>'element of earth'
<br><b>Relinin Skyrunner says </b>'Elemental earth you say? When honed, the elements can be

among our best allies. Retrieve a gridelin globe, a dragon hide mantle, and a

spiroc earth totem. Only with these items can you master the element of

earth.'
<p><b>You give Relinin Skyrunner : </b><a href=http://phobos/eq/item.php?id=20934>Auburn Tessera</a>, <a href=http://phobos/eq/item.php?id=20850>Griffon Talon</a>, <a href=http://phobos/eq/item.php?id=20849>Ysgaril Root</a>
<br><b>Relinin Skyrunner gives you : </b><a href=http://phobos/eq/item.php?id=2715>Spiroc Healer's Cloak</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Relinin Skyrunner says </b>'Good work, ranger.'
<br><b>Relinin Skyrunner disappears.</b>
<p><b>You give Relinin Skyrunner : </b><a href=http://phobos/eq/item.php?id=20853>Fine Velvet Cloak</a>, <a href=http://phobos/eq/item.php?id=20852>Harpy Tongue</a>
<br><b>Relinin Skyrunner says </b>'What am I supposed to do with these?'
<p><b>You give Relinin Skyrunner : </b><a href=http://phobos/eq/item.php?id=20854>Dragon-hide Mantle</a>, <a href=http://phobos/eq/item.php?id=20948>Gridelin Globe</a>
<br><b>Relinin Skyrunner says </b>'What am I supposed to do with these?'
<br><b>Relinin Skyrunner says </b>'What am I supposed to do with these?'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>