<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20952>Harpy Statuette</a><li><a href=http://phobos/eq/item.php?id=20760>Finely Woven Cloth Amice</a><li><a href=http://phobos/eq/item.php?id=20761>Large Diamond</a><li><a href=http://phobos/eq/item.php?id=20959>Carmine Spiroc Feather</a><li><a href=http://phobos/eq/item.php?id=20762>Blood Sky Amethyst</a><li><a href=http://phobos/eq/item.php?id=20763>Golden Efreeti Ring</a><li><a href=http://phobos/eq/item.php?id=20966>Sweet Nectar</a><li><a href=http://phobos/eq/item.php?id=20764>Crown of Elemental Mastery</a><li><a href=http://phobos/eq/item.php?id=20766>Large Opal</a><li><a href=http://phobos/eq/item.php?id=20765>Djinni Stave</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=11687>Duennan Shielding Ring</a><li><a href=http://phobos/eq/item.php?id=11568>Staff of Elemental Mastery: Air</a></ul></td><td><hr><b>When Roanis Elindar spawns </b>
<p><b>You say, </b>'hail'
<br><b>Roanis Elindar says </b>'Great, let us waste no more time! I offer to you three challenges. Summoning, Interpretation, and Displacement.  Please choose one of these.'
<p><b>You say, </b>'summoning'
<br><b>Roanis Elindar says </b>'Summoning it is. Proceed upward through the sky and return to me a Harpy Statuette, a Finely Woven Cloth Amice, and a Large Diamond. This will prove your abilities to me and I will reward you with a Drake Hide Amice.'
<p><b>You say, </b>'interpretation'
<br><b>Roanis Elindar says </b>'Interpretation it is. Proceed upward through the sky and return to me a Carmine Spiroc Feather, a Blood Sky Amethyst, and a Golden Efreeti Ring. This will prove your abilities to me and I will reward you with the Duennan Shielding Ring.'
<p><b>You say, </b>'displacement'
<br><b>Roanis Elindar says </b>'Displacement it is. Proceed upward through the sky and return to me some Sweet Nectar, the Crown of Elemental Mastery, a Large Opal, and Djinni's Stave. This will prove your abilities to me and I will reward you with the Staff of Elemental Mastery.'
<p><b>You give Roanis Elindar : </b><a href=http://phobos/eq/item.php?id=20952>Harpy Statuette</a>, <a href=http://phobos/eq/item.php?id=20760>Finely Woven Cloth Amice</a>, <a href=http://phobos/eq/item.php?id=20761>Large Diamond</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Roanis Elindar says </b>''
<br><b>Roanis Elindar disappears.</b>
<p><b>You give Roanis Elindar : </b><a href=http://phobos/eq/item.php?id=20959>Carmine Spiroc Feather</a>, <a href=http://phobos/eq/item.php?id=20762>Blood Sky Amethyst</a>, <a href=http://phobos/eq/item.php?id=20763>Golden Efreeti Ring</a>
<br><b>Roanis Elindar gives you : </b><a href=http://phobos/eq/item.php?id=11687>Duennan Shielding Ring</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Roanis Elindar says </b>''
<br><b>Roanis Elindar disappears.</b>
<p><b>You give Roanis Elindar : </b><a href=http://phobos/eq/item.php?id=20966>Sweet Nectar</a>, <a href=http://phobos/eq/item.php?id=20764>Crown of Elemental Mastery</a>, <a href=http://phobos/eq/item.php?id=20766>Large Opal</a>, <a href=http://phobos/eq/item.php?id=20765>Djinni Stave</a>
<br><b>Roanis Elindar gives you : </b><a href=http://phobos/eq/item.php?id=11568>Staff of Elemental Mastery: Air</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Roanis Elindar says </b>''
<br><b>Roanis Elindar disappears.</b>
<br><b>Roanis Elindar says </b>'What am I supposed to do with these?'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>