<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Sarkis Ebonblade says </b>'Greetings. [Your Name].  Have you come here to test your dark powers of skill and spell casting?'
<p><b>You say, </b>'dark powers of skill'
<br><b>Sarkis Ebonblade says </b>'You will be tested by either Gragrot or Tynicon.  Choose one!'
<p><b>You say, </b>'Gragrot'
<p><b>You say, </b>'Tynicon'
</td></tr></table>