<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Strandar Pinemist says </b>'Greetings, young one. Are you a [child of the trees]?'
<p><b>You say, </b>'what child of the trees'
<br><b>Strandar Pinemist says </b>'Then you are welcome in my presence. I shall call forth some loyal children if you but speak the name. Will or Fenalla will serve you well.'
<p><b>You say, </b>'Will'
<p><b>You say, </b>'Fenalla'
</td></tr></table>