<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Thalik Silenthand says </b>'Greetings, [Your Name].  Do you believe you are a great rogue?'
<p><b>You say, </b>'great rogue'
<br><b>Thalik Silenthand says </b>'I will not take your word for it!  You must prove your greatness to one of my apprentices.  Do you wish to be tested by Rayne or by Kendrick?'
<p><b>You say, </b>'Rayne'
<p><b>You say, </b>'Kendrick'
</td></tr></table>