<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20793>Finely Woven Gold Mesh</a><li><a href=http://phobos/eq/item.php?id=20794>Silken Strands</a><li><a href=http://phobos/eq/item.php?id=20932>Verdant Tessera</a><li><a href=http://phobos/eq/item.php?id=20796>Cracked Leather Eyepatch</a><li><a href=http://phobos/eq/item.php?id=20939>Gold Disc</a><li><a href=http://phobos/eq/item.php?id=20946>Adumbrate Globe</a><li><a href=http://phobos/eq/item.php?id=20798>Dove Slippers</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1282>Mystical Back Straps</a></ul></td><td><hr><b>When Ton Po spawns </b>
<p><b>You say, </b>'hail'
<br><b>Ton Po says </b>'So, I have been called upon to test you, and test you I
shall. I will give you the option of choosing your test though enlightened
one. Shall you take the test of Strength, Sight, or Speed?'
<p><b>You say, </b>'strength'
<br><b>Ton Po says </b>'So be it, the test of Strenth you shall have. Bring to me a
Verdant Tessera, some Finely Woven Gold Mesh,  and some Silken Strands. The
task will not be easy, but it should serve as an adequate test of Strengh,
for one of your abilities.'
<p><b>You say, </b>'sight'
<br><b>Ton Po says </b>'The test of sight is both a test of body and mind. The mind
will allow you to see beyond that which is usually, invisible. Bring me a
Gold Disc, a Tiny Ruby, and a Cracked Leather Eyepatch and I will assist you
in seeing what should not be seen.'
<p><b>You say, </b>'speed'
<br><b>Ton Po says </b>'The test of speed. Every Monk must be swift if he is to best
his opponent. Speed in both mind and body is essential in many facets of
life. Return to me an Adumbrate Globe, a Shimmering Opal,  and some Dove
Slippers and I shall aid your speed of mind.'
<p><b>You give Ton Po : </b><a href=http://phobos/eq/item.php?id=20793>Finely Woven Gold Mesh</a>, <a href=http://phobos/eq/item.php?id=20794>Silken Strands</a>, <a href=http://phobos/eq/item.php?id=20932>Verdant Tessera</a>
<br><b>Ton Po gives you : </b><a href=http://phobos/eq/item.php?id=1282>Mystical Back Straps</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Ton Po says </b>'You have done well, [Your Name].'
<br><b>Ton Po disappears.</b>
<p><b>You give Ton Po : </b><a href=http://phobos/eq/item.php?id=20796>Cracked Leather Eyepatch</a>, <a href=http://phobos/eq/item.php?id=20939>Gold Disc</a>
<br><b>Ton Po says </b>'What am I supposed to do with these?'
<p><b>You give Ton Po : </b><a href=http://phobos/eq/item.php?id=20946>Adumbrate Globe</a>, <a href=http://phobos/eq/item.php?id=20798>Dove Slippers</a>
<br><b>Ton Po says </b>'What am I supposed to do with these?'
<br><b>Ton Po says </b>'What am I supposed to do with these?'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>