<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Torgon Blademaster says </b>'Greetings, [Your Name]. Are you a true warrior?'
<p><b>You say, </b>'i am a true warrior'
<br><b>Torgon Blademaster says </b>'Then you shall be tested as one.  Choose.  Do you wish to be tested by Falorn or Ogog?'
<p><b>You say, </b>'Falorn'
<p><b>You say, </b>'Ogog'
</td></tr></table>