<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20930>Azure Tessera</a><li><a href=http://phobos/eq/item.php?id=20728>Black Face Paint</a><li><a href=http://phobos/eq/item.php?id=20729>Worn Leather Mask</a><li><a href=http://phobos/eq/item.php?id=20936>Copper Disc</a><li><a href=http://phobos/eq/item.php?id=20731>Mantle of Woven Grass</a><li><a href=http://phobos/eq/item.php?id=20730>Nature Walker's Sky Emerald</a><li><a href=http://phobos/eq/item.php?id=20943>Diaphanous Globe</a><li><a href=http://phobos/eq/item.php?id=20732>Hardened Clay</a><li><a href=http://phobos/eq/item.php?id=20733>Spiroc Battle Staff</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=2706>Drake-Hide Mask</a><li><a href=http://phobos/eq/item.php?id=2705>Nature Walker's Mantle</a><li><a href=http://phobos/eq/item.php?id=6411>Shillelagh</a></ul></td><td><hr><b>When Will Treewalker spawns </b>
<p><b>You say, </b>'hail'
<br><b>Will Treewalker says </b>'The tests of old are difficult and dangerous, but the rewards for perseverance are great. I hold rewards for three tests. The test of the Wolf, test of the Bear and the test of the Tree.'
<p><b>You say, </b>'wolf'
<br><b>Will Treewalker says </b>'So you wish the test of The Wolf do you? Go forth unto the islands and find an Azure Tessera, Black Face Paint and finally a Worn Leather Mask. Bring them back to me, but not until you have all three and you shall be rewarded.'
<p><b>You say, </b>'bear'
<br><b>Will Treewalker says </b>'Ah, the test of The Bear It Is. Find In this plane a Copper Disc, a Sky Emerald and a Mantle of Woven Grass. Bring all three at one time to me for your reward.'
<p><b>You say, </b>'tree'
<br><b>Will Treewalker says </b>'The test of The Tree Is said to be a test of Nature and only those stout of limb and bark will succeed. Bring to me a Diaphanous Globe, some Hardened Clay and a Spiroc Battle Staff. Hand them all to me at once and the Reward will be yours.'
<p><b>You give Will Treewalker : </b><a href=http://phobos/eq/item.php?id=20930>Azure Tessera</a>, <a href=http://phobos/eq/item.php?id=20728>Black Face Paint</a>, <a href=http://phobos/eq/item.php?id=20729>Worn Leather Mask</a>
<br><b>Will Treewalker gives you : </b><a href=http://phobos/eq/item.php?id=2706>Drake-Hide Mask</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Will Treewalker says </b>'Good work.'
<br><b>Will Treewalker disappears.</b>
<p><b>You give Will Treewalker : </b><a href=http://phobos/eq/item.php?id=20936>Copper Disc</a>, <a href=http://phobos/eq/item.php?id=20731>Mantle of Woven Grass</a>, <a href=http://phobos/eq/item.php?id=20730>Nature Walker's Sky Emerald</a>
<br><b>Will Treewalker gives you : </b><a href=http://phobos/eq/item.php?id=2705>Nature Walker's Mantle</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Will Treewalker says </b>'Good work.'
<br><b>Will Treewalker disappears.</b>
<p><b>You give Will Treewalker : </b><a href=http://phobos/eq/item.php?id=20943>Diaphanous Globe</a>, <a href=http://phobos/eq/item.php?id=20732>Hardened Clay</a>, <a href=http://phobos/eq/item.php?id=20733>Spiroc Battle Staff</a>
<br><b>Will Treewalker gives you : </b><a href=http://phobos/eq/item.php?id=6411>Shillelagh</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Will Treewalker says </b>'Good work.'
<br><b>Will Treewalker disappears.</b>
<br><b>Will Treewalker says </b>'What am I supposed to do with these?'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>