<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Wizard Schrock says </b>'Greetings, [Your Name].  Do you believe that you are a great wizard?'
<p><b>You say, </b>'i am a great wizard'
<br><b>Wizard Schrock says </b>'I will not take your word for it!  You must prove your greatness to my apprentices.  Do you wish to be tested by Neasin or by Abec?'
<p><b>You say, </b>'Neasin'
<p><b>You say, </b>'Abec'
</td></tr></table>