<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20800>Silken Wrap</a><li><a href=http://phobos/eq/item.php?id=20954>Spiroc Statuette</a><li><a href=http://phobos/eq/item.php?id=20799>Spiroc Talon</a><li><a href=http://phobos/eq/item.php?id=20803>Brass Knuckles</a><li><a href=http://phobos/eq/item.php?id=20801>Ethereal Amethyst</a><li><a href=http://phobos/eq/item.php?id=20802>Nebulous Sapphire</a><li><a href=http://phobos/eq/item.php?id=20967>Aged Nectar</a><li><a href=http://phobos/eq/item.php?id=20804>Decree of Quellious</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1283>Ton Po's Shoulder Wraps</a></ul></td><td><hr><b>When Wu the Enlightened spawns </b>
<p><b>You say, </b>'hail'
<br><b>Wu the Enlightened says </b>'Greetings Warrior of mind and body. To prove your worth to

me, you must complete a test. Which test do you wish to take? I will permit

you to take the test of Tears, Fists, or Tranquility.'
<p><b>You say, </b>'tears'
<br><b>Wu the Enlightened says </b>'The test of tears involves knowing when to release, and when

to provide a shoulder for another. Bring me a Spiroc Statuette, a Spiroc

Talon, and a Silken Wrap. I will teach you the way.'
<p><b>You say, </b>'fists'
<br><b>Wu the Enlightened says </b>'A monk must know when to use his or her fists, and when to

use ones mind. You must decide in this endevour, which you shall use. Return

to me, once you have found them, a pair of Brass Knuckles, a White Spiroc

Feather, an Emerald Amethyst, and a Nebulous Sapphire.'
<p><b>You say, </b>'tranquility'
<br><b>Wu the Enlightened says </b>'Ah, the test of tranquility. Only the tranquil monk can

achieve enlightenment. Are you such an individual? Time shall tell. Retrieve

these items for me. Bring an Aged Nectar, a Writ of Quellious, and a Glowing

Diamond and we shall asses your ability.'
<p><b>You give Wu the Enlightened : </b><a href=http://phobos/eq/item.php?id=20800>Silken Wrap</a>, <a href=http://phobos/eq/item.php?id=20954>Spiroc Statuette</a>, <a href=http://phobos/eq/item.php?id=20799>Spiroc Talon</a>
<br><b>Wu the Enlightened gives you : </b><a href=http://phobos/eq/item.php?id=1283>Ton Po's Shoulder Wraps</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Wu the Enlightened says </b>'You have moved closer to enlightenment.'
<br><b>Wu the Enlightened disappears.</b>
<p><b>You give Wu the Enlightened : </b><a href=http://phobos/eq/item.php?id=20803>Brass Knuckles</a>, <a href=http://phobos/eq/item.php?id=20801>Ethereal Amethyst</a>, <a href=http://phobos/eq/item.php?id=20802>Nebulous Sapphire</a>
<br><b>Wu the Enlightened says </b>'These will not bring you enlightenment.'
<p><b>You give Wu the Enlightened : </b><a href=http://phobos/eq/item.php?id=20967>Aged Nectar</a>, <a href=http://phobos/eq/item.php?id=20804>Decree of Quellious</a>
<br><b>Wu the Enlightened says </b>'These will not bring you enlightenment.'
<br><b>Wu the Enlightened says </b>'These will not bring you enlightenment.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>