<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20376>Maestro's Symphony Page 24 Top</a><li><a href=http://phobos/eq/item.php?id=20383>Maestro's Symphony Page 24 Bottom</a><li><a href=http://phobos/eq/item.php?id=20377>Maestro's Symphony Page 25</a><li><a href=http://phobos/eq/item.php?id=20538>Mystical Lute</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20542>Singing Short Sword</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Baldric Slezaf says </b>'Hello, [Your Name]. Don't you think this would be a wonderful place to perform a [symphony]?'
<p><b>You say, </b>'symphony'
<br><b>Baldric Slezaf says </b>'It has been my dream for years to perform a symphony that would be remembered for ages to come. I have run into a few [minor snags], however.'
<p><b>You say, </b>'minor snags'
<br><b>Baldric Slezaf says </b>'Several years ago I bought sheets of the most beautiful sounding music from a traveling merchant. He did not know the author of the work as it was simply signed 'the Maestro'. The melody I played from them was wondrous and invoked feelings in me I have never felt before. However, as I reached the middle of the music, I discovered it was [missing two pages]!'
<p><b>You say, </b>'missing two pages'
<br><b>Baldric Slezaf says </b>'The pages that were missing were pages 24 and 25. I have been searching the world for a spot to hold my symphony and I have finally found it. Without the music and a new [lute] crafted by the famous instrument maker Forpar Fizfla, I do not think I can pull it off.'
<p><b>You say, </b>'lute'
<br><b>Baldric Slezaf says </b>'Forpar Fizfla is an eccentric instrument maker from Ak'Anon. He makes enchanted instruments that enhance the sound of the [music]. If I am to perform the concert of all concerts, I must have one of his instruments. I went to Ak'Anon, seeking to purchase an instrument from him but he wouldn't even speak to me.'
<p><b>You say, </b>'music'
<br><b>Baldric Slezaf says </b>'It makes me sad to know that the pages of this music may be spread across the world or destroyed. If you find and bring me the two missing sheets as well as a new lute, I would be happy to [repay] you in some way.'
<p><b>You say, </b>'repay'
<br><font color=green><b>Baldric Slezaf </b>pulls a fantastic looking sword from its scabbard and says</font>
<br><b>Baldric Slezaf says </b>'I might be willing to part with this wonderful sword if I were able to perform this symphony. You would also gain recognition at the opening of the symphony.' Baldric sheathes his sword and begins to hum a haunting melody.'
<p><b>You give Baldric Slezaf : </b><a href=http://phobos/eq/item.php?id=20376>Maestro's Symphony Page 24 Top</a>, <a href=http://phobos/eq/item.php?id=20383>Maestro's Symphony Page 24 Bottom</a>, <a href=http://phobos/eq/item.php?id=20377>Maestro's Symphony Page 25</a>, <a href=http://phobos/eq/item.php?id=20538>Mystical Lute</a>
<br><font color=green><b>Baldric Slezaf </b>looks shocked as you hand him the pages and the mystical lute. 'I will put on a symphony the likes of which the gods have never seen. Thank you so much, [Your Name]. Please take this sword as a token of my gratitude.</font>
<br><b>Baldric Slezaf gives you : </b><a href=http://phobos/eq/item.php?id=20542>Singing Short Sword</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>