<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12979>A Metal Pipe</a><li><a href=http://phobos/eq/item.php?id=12980>A Metal Pipe</a><li><a href=http://phobos/eq/item.php?id=12256>Robe of the Lost Circle</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12970>Robe of the Whistling Fists</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Brother Balatin </b>Brother Balatin turns to you. A transparent human face materalizes upon the skull. As he speaks the smell of rotted rat corpses rushes into your face. You must fight the urge to vomit.</font>
<br><b>Brother Balatin says </b>'What discipline do you follow?'
<p><b>You say, </b>'lost circle'
<br><b>Brother Balatin says </b>'Then we are one. The rebirth of our circle shall start with you. I have waited decades for your arrival. You should seek the living brothers within Tunaria. When you have earned your garb then you will be ready for the [true drape].'
<p><b>You say, </b>'true drape'
<br><b>Brother Balatin says </b>'Seek the broken flute of our master. Taken from us by the Iksar twins of Vistrei. To me they will come and to me your robe and you will come the dawning of the new brotherhood.'
<p><b>You give Brother Balatin : </b><a href=http://phobos/eq/item.php?id=12979>A Metal Pipe</a>, <a href=http://phobos/eq/item.php?id=12980>A Metal Pipe</a>, <a href=http://phobos/eq/item.php?id=12256>Robe of the Lost Circle</a>
<br><font color=green><b>Brother Balatin </b>holds his arms out and a fine robe materializes before your eyes. You grab it just in time to see the skeleton fade from existence.</font>
<br><b>Brother Balatin gives you : </b><a href=http://phobos/eq/item.php?id=12970>Robe of the Whistling Fists</a>
<br><b>Brother Balatin says </b>'I have no need for this item [Your Name], you can have it back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>