<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10073>Dufrenite</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=12946>Dread Diamond</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>gem cutter skeleton </b>appears to be busy cutting a green gem; upon your greeting, it jumps, fleshless hands slipping carelessly and breaking the gem into powder.</font>
<p><b>You say, </b>'green gem'
<br><b>gem cutter skeleton says </b>'The greenest of gems I seek! Jade too brittle, emerald too hard, but [dufrenite]! Ahh, now there is a gem amongst gems.'
<p><b>You say, </b>'dufrenite'
<br><b>gem cutter skeleton says </b>'Yes, dufrenite! Find me a dufrenite to replace the one you made me break. Now go!'
<p><b>You give gem cutter skeleton : </b><a href=http://phobos/eq/item.php?id=10073>Dufrenite</a>
<br><font color=green><b>gem cutter skeleton </b>eyes sparkle as you hand it the gem.</font>
<br><b>gem cutter skeleton says </b>'Yes! Yes! This is the greenest of gems!'
<br><b>gem cutter skeleton gives you : </b><a href=http://phobos/eq/item.php?id=12946>Dread Diamond</a>
<br><b>gem cutter skeleton says </b>'Worth more to you crushed, that is! Find a spectral pestle, and crush it to dust!'
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>gem cutter skeleton says </b>'Ha! Worthless to me, this is! I return it!'
</td></tr></table>