<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=item1></a><li><a href=http://phobos/eq/item.php?id=7880>Mark of Patience</a><li><a href=http://phobos/eq/item.php?id=7879>Mark of Agility</a><li><a href=http://phobos/eq/item.php?id=5192>Mark of Peace</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=4199>Shackle of Tynnonium</a></ul></td><td><p><b>You say, </b>'Hail'
<br><font color=green><b>Veltar </b> 's body has scars all about it, looking as though beaten with whips. One wrist bares a unique looking bracer, the other is bare.</font>
<br><b>Veltar says </b>'Leave me be! I did not come up here because I wanted company.'
<p><b>You say, </b>'Tell me about the tynnonium shackle'
<br><b>Veltar says </b>'So it is the one that has freed me before! You seek the ways of Tynn I see. You must be on the true path of the monk to accomplish what is needed. The path will test the [three virtues] most important to becoming a true vessel for Cazic Thule's power.'
<p><b>You say, </b>'three virtues'
<br><b>Veltar says </b>'The three virtues are [patience], [agility], and [peace of mind]. Patience is important in knowing in when to strike your opponent, too soon and you may crushed, too late and your opportunity may pass. Agility is very important in showing your ability to avoid blows sent your way, and then returning what was sent to you. Without striking quickly you are no monk at all. Peace of mind will allow you to concentrate on the situation you are in. With it you can control your actions and make decisive strikes at critical times. Without peace of mind you may attack out of rage and will surely fall for your mind is clouded. You must complete these three [trials] to earn the shackle of the Grandmaster.'
<p><b>You say, </b>'patience'
<br><b>Veltar says </b>'Patience shall be tested by the one whom has the greatest patience. Seek Master Rinmark, and ask him of this trial.'
<p><b>You say, </b>'agility'
<br><b>Veltar says </b>'To show agility you must be tested by the most swift of us. Grandmaster Glox will provide your test for this. Ask him of the trial of agility.'
<p><b>You say, </b>'peace of mind'
<br><b>Veltar says </b>'To show peace of mind you must decipher a tome found in the library of Kaesora. An undead tome keeper will wait for you to come, ask him of the trial of peace of mind. The tome will tell you what you shall seek. Do with the tome the same as you would with the item you seek. Show you have clarity of mind in solving this.'
<p><b>You give Veltar : </b><a href=http://phobos/eq/item.php?id=7880>Mark of Patience</a>, <a href=http://phobos/eq/item.php?id=7879>Mark of Agility</a>, <a href=http://phobos/eq/item.php?id=5192>Mark of Peace</a>
<br><b>Veltar gives you : </b><a href=http://phobos/eq/item.php?id=4199>Shackle of Tynnonium</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Veltar : </b><a href=http://phobos/eq/item.php?id=7880>Mark of Patience</a>, <a href=http://phobos/eq/item.php?id=7879>Mark of Agility</a>, <a href=http://phobos/eq/item.php?id=5192>Mark of Peace</a>
<br><b>Veltar gives you : </b><a href=http://phobos/eq/item.php?id=4199>Shackle of Tynnonium</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>