<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10632>Dull Sapphire</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10619>Enchanted Sapphire</a></ul></td><td><p><b>You give Felia Goldenwing : </b><a href=http://phobos/eq/item.php?id=10632>Dull Sapphire</a>
<br><b>Felia Goldenwing gives you : </b><a href=http://phobos/eq/item.php?id=10619>Enchanted Sapphire</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>