<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=60333>Joshel's Bandana</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>#Translocator Kurione says </b>'Hello there. There seems to be some strange problems with the boats in this area. The Academy of Arcane Sciences has sent a small team of us to investigate them. If you need to [travel to North Ro] in the meantime, I can transport you to my companion there. We also just recently discovered that Joshel has been stranded over in the middle of the ocean since the problems with the boats started. If you'd be willing to go see if he's ok, I may be able to [teleport you near there]. Keep in mind though that it will be a one way trip. There is no one on the island able to send you back.'
<p><b>You say, </b>'teleport near there'
<br><font color=white><b>The Player moves to zone 110 at -20266.8,3985.5,0</b></font>
<p><b>You say, </b>'travel to north ro'
<br><font color=brown><b>#Translocator Kurione casts a spell : </b><a href=http://phobos/eq/spell.php?id=2282>Portal to Ro</a>.</font>
<p><b>You give #Translocator Kurione : </b><a href=http://phobos/eq/item.php?id=60333>Joshel's Bandana</a>
<br><b>#Translocator Kurione says </b>'Whew, it's good that you were able to find him, and doing so well. Thanks very much for checking on him for me. I would have done so myself, but with the problems with the boats, I just haven't had the time. Thanks again.'
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>