<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=30042>Chapter P</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18962>Pirate Grammar Manual</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Ami </b>flips through a few pages of a small book, reading intently before answering you.</font>
<br><b>Ami says </b>'Ye scurvy dog. I'll strike yer colors 'fore ya can put me on a gibbet. Take that, ya crimp!'
<br><font color=green><b>Ami </b>flips through a few more pages then smiles at you.</font>
<br><b>Ami says </b>'Arrrr!'
<p><b>You say, </b>'ye scurvy dog'
<br><b>Ami says </b>'Hey, that's pretty good. You did it without a book too. Nice to meet you. I'm the bosun here.'
<p><b>You say, </b>'a bosun'
<br><b>Ami says </b>'Yup. I think it means I'm in charge of the flag cause that's what the Cap'n told me to take care of. I'm the one who made our symbol, so I get to protect it. I even got my own copy of the grammar manual so I can practice my pirate speech.'
<p><b>You say, </b>'grammar manual'
<br><font color=green><b>Ami </b>nods and shows you the book for a moment.</font>
<br><b>Ami says </b>'We don't have many of them and usually we share. My book is missing a chapter, though.'
<p><b>You say, </b>'chapter'
<br><font color=green><b>Ami </b>nods.</font>
<br><b>Ami says </b>'A mate of mine borrowed the P Chapter to draw a map on but then he went and got himself lost. I've memorized the rest of the book but that chapter. Oh, well, I guess I can get by with what I have. Walk the mizenmast and batten down the boom!'
<br><font color=green><b>Ami </b>looks at you proudly.</font>
<br><b>Ami says </b>'Good, eh? I'm one of the best pirates we have.'
<p><b>You give Ami : </b><a href=http://phobos/eq/item.php?id=30042>Chapter P</a>
<br><b>Ami says </b>'Oh! I've been needing this!' She reads over the pages intently. 'Uh. Pirate - A sea robber.' She scratches her head. 'I totally forgot we were supposed to be robbing people. Put down yer weapons and hand over yer platinum and gold ya port side bilge suckers! Heh. This is great. Thank you, [Your Name].'
<br><font color=green><b>Ami </b>grins and goes back to reading.</font>
<br><b>Ami gives you : </b><a href=http://phobos/eq/item.php?id=18962>Pirate Grammar Manual</a>
</td></tr></table>