<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=30042>Chapter P</a></ul></td><td><hr><b>When an agitated snowfang spawns </b>
<p><b>You say, </b>'hail'
<br><font color=green><b>an agitated snowfang </b>shivers and growls to itself.</font>
<br><b>an agitated snowfang says </b>'Much thanks must I give, [Your Name]. Furless one still wants magic thing, after all the troubles? Say quickly. Much pain from attack. Must go, shaman help.'
<p><b>You say, </b>'magic thing'
<br><b>an agitated snowfang gives you : </b><a href=http://phobos/eq/item.php?id=30042>Chapter P</a>
<br><b>an agitated snowfang disappears.</b>
</td></tr></table>