<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=30055>Skin of the Garou</a><li><a href=http://phobos/eq/item.php?id=30032>Bloody Cougar Bone</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=30056>Garou Bone Club</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=303>Snowfang Gnolls</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Balix Misteyes says </b>'Outlander, hail. Share the fire. I have little but if you are in need then take what I have. If you need nothing then take nothing. Balix my name is. Shaman to the tribe of Snowfangs.'
<p><b>You say, </b>'shaman'
<br><b>Balix Misteyes says </b>'Yes, shaman. I listen to the land to tell my tribe what the winds and waters will bring. Good or bad. Little good and much bad these days. That is why I sit here listening.'
<p><b>You say, </b>'listening'
<br><b>Balix Misteyes says </b>'I am on spirit quest. No food do I take. All day I listen only. I wait until the land tells me how to help my tribe. Maybe nothing will happen but I cannot fail to try. Hard is this. Many dangerous creatures are near but none come close so far.'
<p><b>You say, </b>'dangerous creatures'
<br><font color=green><b>Balix Misteyes </b>growls under his breath.</font>
<br><b>Balix Misteyes says </b>'Most dangerous is the Garou. Evil spirit of the land. It was made from long dead wolf spirits when the tower spread its dark magics through the islands. It preys on the Snowfang. We have tried to hunt it but always it is too strong.'
<p><b>You say, </b>'garou'
<br><b>Balix Misteyes says </b>'If you want to try, you can hunt Garou. If you kill, spread its soul to the air for cleansing, then all is good. Its skin is powerful from the magics that made it. With a cougar's bone, fresh with the spirit of earth, I can make you powerful talisman in thanks for your service to Snowfangs.'
<p><b>You give Balix Misteyes : </b><a href=http://phobos/eq/item.php?id=30055>Skin of the Garou</a>, <a href=http://phobos/eq/item.php?id=30032>Bloody Cougar Bone</a>
<br><font color=green><b>Balix Misteyes </b>pulls its lips back as it scratches and cuts the skin, working it around the bloody puma bone.</font>
<br><b>Balix Misteyes says </b>'Good for hitting or for talisman. Powerful thing to hold. All Snowfang thank you. Now, all of us are safer.'
<br><b>Balix Misteyes gives you : </b><a href=http://phobos/eq/item.php?id=30056>Garou Bone Club</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=303>Snowfang Gnolls</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>