<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=30047>Completed Map of Iceclad</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=30008>Eyepatch of Plunder</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Captain Nalot </b>squints at you through one eye, the other covered by a metallic eyepatch.</font>
<br><b>Captain Nalot says </b>'Garrr. What `ave we here? Another beller yellied land blubber, eh? By the looks of ye someones mudder didn't know when ta throw a bad fish back. HAR HAR!'
<p><b>You say, </b>'bad fish'
<br><b>Captain Nalot says </b>'That means I'm callin ya ugly as a piece o' whale blubber but twice as bad smellin, ya son of a water treadin . Yer about as smart as the slime we use ta patch our boat hull, aren't ya?'
<p><b>You say, </b>'boat'
<br><b>Captain Nalot says </b>''Arrrr. So we ain't got a boat right now. What's that got ta do with anythin'? Just cause we ain't got a boat, or a way to sail the waters, or even know how ta sail, don't mean we aren't crusty and dangerous. Just watch yerself cause we're mean.'
<p><b>You say, </b>'mean'
<br><b>Captain Nalot says </b>'Thats right! We're mean, nasty, devious 'n cruel. We'll knock ya down, bite yer knees, and steal yer money. Arrr. We won't always say please and thank you either! Just remember that and don't be tryin' anyhin' funny.'
<p><b>You say, </b>'funny'
<br><b>Captain Nalot says </b>'Uh, I dunno what funny stuff. No one's ever asked that one. You know, just be nice ta everyone I guess. Think ya can do that?'
<p><b>You say, </b>'map'
<br><b>Captain Nalot says </b>'The map? What map? Oh wait, that thing I made ol' what's-his-name do ta get los... uh adventure. Uh, sure. If yer wantin' we've got a job for ya. If ya do it ya get ta be a real member o' me crew.'
<p><b>You say, </b>'real member of your crew'
<br><b>Captain Nalot says </b>'That means ya get ta take orders from me and ya get ta use fancy words like bilge hoistin' land blubbing beller yellied, and more. Anyways, we needed a map so me lads would stop gettin' lost, but the lad I sent out ain't come back with it. I even sent out a search party but I ain't heard from them either. If ya find 'im get the map and get back 'ere.'
<p><b>You give Captain Nalot : </b><a href=http://phobos/eq/item.php?id=30047>Completed Map of Iceclad</a>
<br><font color=green><b>Captain Nalot </b>squints and then knocks hard on the metal half of his face to get his eye back in adjustment. 'Arrr. This is perfect. Har! Now we can be plannin' our pillagin' and plunderin' all proper like. Good work, [Your Name]!'</font>
<br><font color=green><b>Captain Nalot </b>slaps you on the back and accidentally drops his eyepatch. Being a proper pirate now you conveniently forget to mention it to him.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Captain Nalot gives you : </b><a href=http://phobos/eq/item.php?id=30008>Eyepatch of Plunder</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>