<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Errgriz says </b>'Errrr.  You come for master. learning like me?'
<p><b>You say, </b>'what learning'
<br><b>Errgriz says </b>'I am learning ways of skinning and tailoring.  None left but the master so I must learn to help.  For now I only clean the furs.'
<p><b>You say, </b>'i come for learning'
<br><b>Errgriz says </b>'I am learning ways of skinning and tailoring.  None left but the master so I must learn to help.  For now I only clean the furs.'
</td></tr></table>