<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=6310>Runed Totem Staff</a><li><a href=http://phobos/eq/item.php?id=30050>Whale Bone</a><li><a href=http://phobos/eq/item.php?id=30049>Tinkered Rope</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=30052>Rune Shafted Harpoon</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=303>Snowfang Gnolls</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=345>Ulthork</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Grizlin Bloodfang says </b>'Lo outlander. Grizlin weaponsmaker for tribe. Make mighty blade from bone. Very important now.. need make many spear for hunter. Not make spear, then hunter not bring meat. Now my friend Keref sad, his pack gone north and Keref alone. Want to find way to help Keref but must make weapon for tribe. Maybe you go find what Keref need to make happy?'
<p><b>You say, </b>'harpoon'
<br><b>Grizlin Bloodfang says </b>'Ahh, Harpoon hard to make. Grizlin need many thing to make true harpoon. Will need strong staff, strong bone, strong rope.'
<p><b>You say, </b>'strong staff'
<br><b>Grizlin Bloodfang says </b>'Good staff always properly carved with totem and rune. Strong and mighty, very good for harpoon making. Not make in many moons here. All wood kept for fire. Perhaps find among outland gnoll tribe where wood is plentiful'
<p><b>You say, </b>'bone'
<br><b>Grizlin Bloodfang says </b>'Mightiest bone come from whale. Very strong, very powerful. Yes, bone of mighty whale make very strong blade. Good for harpoon.'
<p><b>You say, </b>'strong rope'
<br><b>Grizlin Bloodfang says </b>'Not know where find strong rope. For mighty harpoon, need very strong bone or harpoon break rope too much. Maybe furless ones with steel canoe have mighty rope.'
<p><b>You give Grizlin Bloodfang : </b><a href=http://phobos/eq/item.php?id=6310>Runed Totem Staff</a>, <a href=http://phobos/eq/item.php?id=30050>Whale Bone</a>, <a href=http://phobos/eq/item.php?id=30049>Tinkered Rope</a>
<br><b>Grizlin Bloodfang says </b>'Yes, these good.'
<br><font color=green><b>Grizlin Bloodfang </b>forges the items into a finely crafted harpoon. Grizlin holds the weapon up and inspects it for a moment.</font>
<br><b>Grizlin Bloodfang says </b>'Yes, this fine weapon. This hero weapon! Groumshak have harpoon much like this. May it bring much food for your pack, furless one.'
<br><font color=green><b>Grizlin Bloodfang </b>hands you the harpoon with a nod of his head.</font>
<br><b>Grizlin Bloodfang gives you : </b><a href=http://phobos/eq/item.php?id=30052>Rune Shafted Harpoon</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=303>Snowfang Gnolls</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=345>Ulthork</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>