<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=60333>Joshel's Bandana</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Joshel the Large says </b>'That's right. Large, cause that's what I be. If'n ya don't like it, or even if ya do, ya best get to the dock on the other side o' this island. Ya never know when [Icebreaker] is gonna stop by again and yet not wantin' ta miss it.'
<p><b>You say, </b>'icebreaker'
<br><b>Joshel the Large says </b>'What about it? Wait. How did you get here? There weren't no raft come to this island. Come to think o' it, I don't think I've heard hide nor hair o' the Icebreaker for a while. Well, drat. I wonder if anyone's been looking for me. Here, have this bandana to let whoever know that I'm alright. Thanks for checking up on me, but I'll be ok here for a while longer.'
<br><b>Joshel the Large gives you : </b><a href=http://phobos/eq/item.php?id=60333>Joshel's Bandana</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>