<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=30052>Rune Shafted Harpoon</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=30051>Icy Totem of Protection</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=303>Snowfang Gnolls</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=345>Ulthork</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Keref Spiritspear says </b>'Bark! Lo furless one. My people are Snowfang. Once mighty tribe, now snowfang home lost to vengeful winter.'
<p><b>You say, </b>'vengeful winter'
<br><b>Keref Spiritspear says </b>'Our tribe once many strong, then vengeful winter come. Tribe grow lost in storm of ice. Many moon, no food, no water, no home. Many snowfang die, many snowfang leave to find new home.'
<p><b>You say, </b>'new home'
<br><b>Keref Spiritspear says </b>'Many go north, not see again. Many family go, Keref family go. Aroooooooo. Someday Keref become brave, like mighty hero Groumshak. Keref go find pack to north.'
<p><b>You say, </b>'Groumshak'
<br><b>Keref Spiritspear says </b>'Groumshak mighty snowfang hero. Groumshak make battle with furless one fifty paws high. When Groumshak return to tribe, vengeful winter fall. If you bring Keref mighty harpoon like Groumshak, then Keref become hero like Groumshak. Will give totem of great protection for thanks.'
<p><b>You give Keref Spiritspear : </b><a href=http://phobos/eq/item.php?id=30052>Rune Shafted Harpoon</a>
<br><font color=green><b>Keref Spiritspear </b>gasps in astonishment.</font>
<br><b>Keref Spiritspear says </b>'This true hero weapon. This just like harpoon of mighty Groumshak! Now I can find family! Many thanks, friend to Snowfang. Take this for thanks. It protect from danger.'
<br><font color=green><b>Keref Spiritspear </b>hands you an intricately carved ice totem. A feeling of safety washes over you as he places it in your hand.</font>
<br><b>Keref Spiritspear gives you : </b><a href=http://phobos/eq/item.php?id=30051>Icy Totem of Protection</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=303>Snowfang Gnolls</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=345>Ulthork</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>