<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18962>Pirate Grammar Manual</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=30041>Ice Forged Shackles</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Nilham the Chef says </b>'Ahoy, [Your Name]. Welcome ta the brig. I didn't get ta the 'B' section of my piratisms manual so I'm not sure what a brig is but I'm guessin' it means 'really small place without enough food or water.' So, ya here ta stay or just visitin'?'
<p><b>You give Nilham the Chef : </b><a href=http://phobos/eq/item.php?id=18962>Pirate Grammar Manual</a>
<br><font color=green><b>Nilham the Chef </b>looks at you with a gleam in his eye.</font>
<br><b>Nilham the Chef says </b>'Wow. Ya actually got one. Thanks, mate! Here, you can have my cuffs. I'm tired of 'em and they're startin' ta chafe.'
<br><b>Nilham the Chef says </b>'B - Bilgewater. Barnacle brained blunderhead. Blast yer ballast...'
<br><font color=green><b>Nilham the Chef </b>happily reads through the book.</font>
<br><b>Nilham the Chef gives you : </b><a href=http://phobos/eq/item.php?id=30041>Ice Forged Shackles</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Nilham the Chef says </b>'Yar, what am I ta do with these, [Your Name]? Take 'em back and leave me be.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>