<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=30048>Frost Giant Scout Beard</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=30049>Tinkered Rope</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=251>Pirates of Iceclad</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Ritap says </b>'Avast you! Ya best be shoving off if ye knows whats good for you. We be pirate raiders and ya best not be messing with the likes of us!'
<p><b>You say, </b>'tinkered rope'
<br><b>Ritap says </b>'Batten down yer yapper! Ahl be doin the talking here. We be needin the rope to tie ye down fer ransom. Now fetch me the beard of a frost giant scout so's I can make some more rope to tie ye up with.'
<p><b>You give Ritap : </b><a href=http://phobos/eq/item.php?id=30048>Frost Giant Scout Beard</a>
<br><b>Ritap says </b>'Arg! By blubberbeards nostril! Ye'v done it!''
<br><font color=green><b>Ritap </b>He braids the beard together into a sturdy rope.</font>
<br><b>Ritap says </b>'Now take this here rope and tie yerself up! Come lets go tell the cap'n we've captured us some prisoners!'
<br><b>Ritap gives you : </b><a href=http://phobos/eq/item.php?id=30049>Tinkered Rope</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=251>Pirates of Iceclad</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>