<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=25104>Coldain Toolset</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=20474>Receipt</a></ul></td><td><p><b>You give Sojan the Sleess.pl : </b><a href=http://phobos/eq/item.php?id=25104>Coldain Toolset</a>
<br><b>Sojan the Sleess.pl says </b>'Uhhh, thank you... Now I can uhh... work on fixing some things around...'
<br><font color=green><b>Sojan the Sleess.pl </b>seems to nod off for a moment as he drops a small note on the ground.</font>
<br><b>Sojan the Sleess.pl gives you : </b><a href=http://phobos/eq/item.php?id=20474>Receipt</a>
</td></tr></table>