<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12292>Decayed Left Gauntlet</a><li><a href=http://phobos/eq/item.php?id=12291>Decayed Right Gauntlet</a><li><a href=http://phobos/eq/item.php?id=16507>Enchanted Platinum Bar</a><li><a href=http://phobos/eq/item.php?id=12294>Decayed Left Legplate</a><li><a href=http://phobos/eq/item.php?id=12293>Decayed Right Legplate</a><li><a href=http://phobos/eq/item.php?id=12297>Melatite</a><li><a href=http://phobos/eq/item.php?id=12296>Decayed Left Boot</a><li><a href=http://phobos/eq/item.php?id=12295>Decayed Right Boot</a><li><a href=http://phobos/eq/item.php?id=12106>Fairy Dust</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=3144>Darkforge Gauntlets</a><li><a href=http://phobos/eq/item.php?id=3145>Darkforge Greaves</a><li><a href=http://phobos/eq/item.php?id=3146>Darkforge Boots</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>an undead knight says </b>'Away from this place of torment!  Make haste and flee before you, too, share my [gruesome fate]!!'
<p><b>You say, </b>'gruesome fate'
<br><b>an undead knight says </b>'I was once a proud shadowknight, but failed I did in my master's quest.  I was sent into a lizard fortress deep in the swamplands.  I was to seek out an ancient item for my master.  I failed and was captured. The lizards stripped me of my [darkforge armor] and planned to boil me alive.  Before they could do so, I escaped.  Upon my return to my master's lair I found myself in a [worse predicament].'
<p><b>You say, </b>'worse predicament'
<br><b>an undead knight says </b>'I was torn apart by my master and my bones were given as toys to my master's associates!!  I am now only half Grandyf the Vile.  My hands, feet and legs were sent here and assembled with spare bones of other unfortunates.  Since this is the case, I can only [create darkforge armor] in the form of boots, greaves and gauntlets.'
<p><b>You say, </b>'create darkforge armor'
<br><b>an undead knight says </b>'I and I alone have the power to create darkforge armor!!  It was crafted for me so naturally it is to be worn by shadowknights only.  My armor was taken by the lizardman crusaders.  Unfortunately for them, it lost all power and cannot be worn.  I would be glad to see it put to good use. Do you [seek the darkforge armor]?'
<p><b>You say, </b>'seek the darkforge armor'
<br><b>an undead knight says </b>'Darkforge gauntlets require both of my decayed gauntlets and one enchanted platinum bar.  For the darkforge greaves, I will need both decayed legplates and two pieces of melatite from the Solusek Mining Company.  For the boots, I need both my decayed boots and two parts of fairy dust.'
<p><b>You give an undead knight : </b><a href=http://phobos/eq/item.php?id=16507>Enchanted Platinum Bar</a>, <a href=http://phobos/eq/item.php?id=12292>Decayed Left Gauntlet</a>, <a href=http://phobos/eq/item.php?id=12291>Decayed Right Gauntlet</a>
<br><b>an undead knight says </b>'Well done, [Your Name], here is your reward.'
<br><b>an undead knight gives you : </b><a href=http://phobos/eq/item.php?id=3144>Darkforge Gauntlets</a>
<p><b>You give an undead knight : </b><a href=http://phobos/eq/item.php?id=12297>Melatite</a> (x2), <a href=http://phobos/eq/item.php?id=12293>Decayed Right Legplate</a>, <a href=http://phobos/eq/item.php?id=12294>Decayed Left Legplate</a>
<br><b>an undead knight says </b>'Well done, [Your Name], here is your reward.'
<br><b>an undead knight gives you : </b><a href=http://phobos/eq/item.php?id=3145>Darkforge Greaves</a>
<p><b>You give an undead knight : </b><a href=http://phobos/eq/item.php?id=12296>Decayed Left Boot</a>, <a href=http://phobos/eq/item.php?id=12106>Fairy Dust</a> (x2), <a href=http://phobos/eq/item.php?id=12295>Decayed Right Boot</a>
<br><b>an undead knight says </b>'Well done, [Your Name], here is your reward.'
<br><b>an undead knight gives you : </b><a href=http://phobos/eq/item.php?id=3146>Darkforge Boots</a>
<br><b>an undead knight says </b>'I don't need this.'
<br><b>You receive </b> 10000pp 10000gp 10000sp 10000cp
</td></tr></table>