<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10032>Star Ruby</a><li><a href=http://phobos/eq/item.php?id=10000>Lambent Stone</a><li><a href=http://phobos/eq/item.php?id=16507>Enchanted Platinum Bar</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10117>Lambent Star Ruby</a><li><a href=http://phobos/eq/item.php?id=19047>Galvanized Platinum Bar</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=320>Temple of Solusek Ro</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=291>Shadowed Men</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Genni says </b>'I am Genni of the temple of Solusek Ro.  I serve as custodian of the [lambent stones].'
<p><b>You say, </b>'lambent stones'
<br><b>Genni says </b>'Lambent stones are receptacles of power.  Alone they are not useful, but when combined with other gemstones they can be used for making magic items.  I know of [star ruby] lambent, [ruby] lambent, [sapphire] lambent and [fire opal] lambent.'
<p><b>You say, </b>'ruby'
<br><b>Genni says </b>'My Sister Vilissia holds the secrets to making ruby lambent stones.  Though she will not speak of it, if you give her two rubies and a lambent stone, she will make you ruby lambent.'
<p><b>You say, </b>'star'
<p><b>You say, </b>'sapphire'
<br><b>Genni says </b>'My Brother Gardern holds the secret to making sapphire lambent stones.  Though he will not speak of it, if you give him two sapphires and a lambent stone, he will make you sapphire lambent.'
<p><b>You say, </b>'fire opal'
<br><b>Genni says </b>'My Brother Ostorm holds the secret to making fire opal lambent stones.  Though he will not speak of it, if you give him two fire opals and a lambent stone, he will make you fire opal lambent.  If you are interested, I can [sell] you a [fire opal].'
<p><b>You say, </b>'sell'
<br><b>Genni says </b>'I will sell you a fire opal for 550 golden coins.  Remember, gold!  The metal of fire for a gem of fire.'
<p><b>You give Genni : </b><a href=http://phobos/eq/item.php?id=10032>Star Ruby</a> (x2), <a href=http://phobos/eq/item.php?id=10000>Lambent Stone</a>
<br><b>Genni says </b>'Here is your prize - a lambent star ruby.'
<br><b>Genni gives you : </b><a href=http://phobos/eq/item.php?id=10117>Lambent Star Ruby</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=320>Temple of Solusek Ro</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=291>Shadowed Men</a> has gotten worse.</font>
<p><b>You give Genni : </b><a href=http://phobos/eq/item.php?id=16507>Enchanted Platinum Bar</a>
<br><b>Genni says </b>'I see that Gavel has sent you to me.  Very well, I have galvanized your platinum bar - take it.'
<br><b>Genni gives you : </b><a href=http://phobos/eq/item.php?id=19047>Galvanized Platinum Bar</a>
</td></tr></table>