<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18955>A Sealed Note</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Lon the Redeemed says </b>'Welcome. friend. I am one of the redeemed. I once walked the path of evil and woe. My talents were those of the House of V'ree of Neriak. I now serve the Burning Prince. Are you a [rogue in need of redemption] also?'
<p><b>You say, </b>'i am a rogue in need of redemption'
<br><b>Lon the Redeemed says </b>'Then so be it. Ro commands you to aid the saved one. Ortallius of the hot sands. He is in need of two gems: the gem of stamina, also known as the gem of passion, and the gem of righteousness. I once owned these gems in my former life. They rest with my old friend, [Conium Darkblade]. Take this note to him and he shall give you the gems which you will then take to Ortallius.  Be off.'
<br><b>Lon the Redeemed gives you : </b><a href=http://phobos/eq/item.php?id=18955>A Sealed Note</a>
<p><b>You say, </b>'conium darkblade'
<br><b>Lon the Redeemed says </b>'When evil ruled my life, I hid in the shadows with a fellow thief. This dwarf's name was Conium Darkblade. He was a genius when it came to poisons. I believe he now taints this world with his evil toxins. No doubt he hides near his homeland.'
</td></tr></table>