<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17977>Sol Cauldron</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Lord Searfire says </b>'Greetings!  May the glory of Solusek Ro burn in your veins.  I am the forge master of this temple.  Called to service by the Burning Prince.  Should you ever need my service and find me gone. have no fear. I shall return.  I must occasionally venture to other realms in service of the temple.  I shall always return. this is my eternal home.'
<p><b>You say, </b>'ronium'
<br><b>Lord Searfire says </b>'You seek ronium.  It is a fine blend of metals.  I alone hold the secret of its formula.  I, and I alone, can offer it to those who serve this temple.  Do you wish a [bar of the alloy]?'
<p><b>You say, </b>'bar of the alloy'
<br><b>Lord Searfire says </b>'Take this Sol Cauldron.  Within it shall be combined elements of this world.  You will add to it, melatite, two bars of enchanted platinum, Mistmoore granite, the sands of Ro and soil of Underfoot.  If you be a master blacksmith, the elements shall combine to make the enchanted metal I have named 'ronium.''
<br><b>Lord Searfire gives you : </b><a href=http://phobos/eq/item.php?id=17977>Sol Cauldron</a>
</td></tr></table>