<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10035>Ruby</a><li><a href=http://phobos/eq/item.php?id=10031>Fire Opal</a><li><a href=http://phobos/eq/item.php?id=10000>Lambent Stone</a><li><a href=http://phobos/eq/item.php?id=16507>Enchanted Platinum Bar</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10128>Lambent Fire Opal</a><li><a href=http://phobos/eq/item.php?id=19049>Magnetized Platinum Bar</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=320>Temple of Solusek Ro</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=291>Shadowed Men</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Ostorm says </b>'I am Ostorm of the Temple of Solusek Ro, guardian of the sacred crystal of Kintaz.  Be wary and keep your distance, lest the proximity of the crystal [steal] your [memories].'
<p><b>You say, </b>'steal my memories'
<br><b>Ostorm says </b>'It is the nature of the crystal of Kintaz to steal the memories of those around it. Only I am safe, and then only because of the strong wardings placed on me by Solusek Ro himself. Are you interested in [losing] any [memories]?'
<p><b>You say, </b>'losing my memories'
<br><b>Ostorm says </b>'Recently, I have been experimenting with the crystal, and have found that those exposed to ruby light filtered through it tend to lose the memories of their most specialized arcane skills. Are you sure you want to [lose advanced memory] of specialization?'
<p><b>You say, </b>'lose advanced memory'
<br><b>Ostorm says </b>'Be warned that once exposed to the crystal, I can not reverse the effects. If you desire exposure, fetch me a ruby.'
<p><b>You say, </b>'fifty gold'
<br><b>Ostorm says </b>'You do not remember?  You promised me fifty gold coins for allowing you to be exposed to the sacred crystal of Kintaz.'
<p><b>You give Ostorm : </b><a href=http://phobos/eq/item.php?id=10035>Ruby</a>
<br><b>Ostorm says </b>'..hear me? Ah, you seem to be coming out of your stupor. I think you have been exposed to the crystal long enough. By the time you leave the temple, your memories should have faded. Do you have the [fifty gold] coins that you owe me?'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=320>Temple of Solusek Ro</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=291>Shadowed Men</a> has gotten worse.</font>
<br><font color=green><b>Ostorm </b>Your specialize skills have all been set to 49.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Ostorm : </b><a href=http://phobos/eq/item.php?id=10000>Lambent Stone</a>, <a href=http://phobos/eq/item.php?id=10031>Fire Opal</a> (x2)
<br><b>Ostorm says </b>'Ahh, Genni must have sent you to me.  Very well, here is your Lambent Fire Opal.'
<br><b>Ostorm gives you : </b><a href=http://phobos/eq/item.php?id=10128>Lambent Fire Opal</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=320>Temple of Solusek Ro</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=291>Shadowed Men</a> has gotten worse.</font>
<p><b>You give Ostorm : </b><a href=http://phobos/eq/item.php?id=16507>Enchanted Platinum Bar</a>
<br><b>Ostorm says </b>'I see that Gavel has sent you to me.  Very well, I have magnetized your platinum bar - take it.'
<br><b>Ostorm gives you : </b><a href=http://phobos/eq/item.php?id=19049>Magnetized Platinum Bar</a>
</td></tr></table>