<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10000>Lambent Stone</a><li><a href=http://phobos/eq/item.php?id=10793>Radiant Coin of Tash</a><li><a href=http://phobos/eq/item.php?id=10790>Coin of Tash</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17511>A coin pouch</a><li><a href=http://phobos/eq/item.php?id=6048>Darkwood Staff</a><li><a href=http://phobos/eq/item.php?id=15678>Spell: Tashania</a><li><a href=http://phobos/eq/item.php?id=10790>Coin of Tash</a><li><a href=http://phobos/eq/item.php?id=18032>Tome of Tesh</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=320>Temple of Solusek Ro</a><li><a href=http://phobos/eq/faction.php?id=442>Temple Of Sol Ro</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=291>Shadowed Men</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Romar Sunto says </b>'I am Romar Sunto, servant of Solusek Ro. I am searching for the [Coin] of the mighty enchanter [Tash] - if you are interested in helping me acquire it, I will [reward] you with a powerful spell. I am also dispenser of [Darkwood Staves] - sometimes also called the Staff of Ro.'
<p><b>You say, </b>'darkwood staves'
<br><b>Romar Sunto says </b>'Bring me a Lambent Stone from a Hill Gant, a Sand Giant or a Griffon and I will give you a Darkwood Staff.'
<p><b>You say, </b>'tash'
<br><b>Romar Sunto says </b>'Tash was a mighty enchanter and a master jewelcrafter.'
<p><b>You say, </b>'coin pouch'
<br><b>Romar Sunto says </b>'I will gladly lend you this coin pouch - put all 10 antique silver coins into it and combine them into the Coin of Tash.'
<br><b>Romar Sunto gives you : </b><a href=http://phobos/eq/item.php?id=17511>A coin pouch</a>
<p><b>You say, </b>'coin'
<br><b>Romar Sunto says </b>'Tash had a collection of ten antique silver coins that were left in different cities around the world. If you were to collect all 10 coins, I would give you a [coin pouch] that would let you combine them into the master Coin of Tash. If you are interested I will sell you a copy of the Tome of Tash, detailing where the coins were reportedly left, for a mere 50 gold.'
<p><b>You give Romar Sunto : </b><a href=http://phobos/eq/item.php?id=10000>Lambent Stone</a>
<br><b>Romar Sunto says </b>'Very well, [Your Name].  Here is your staff.'
<br><b>Romar Sunto gives you : </b><a href=http://phobos/eq/item.php?id=6048>Darkwood Staff</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=320>Temple of Solusek Ro</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=291>Shadowed Men</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Romar Sunto : </b><a href=http://phobos/eq/item.php?id=10793>Radiant Coin of Tash</a>
<br><b>Romar Sunto says </b>'The Coin of Tash - fully enchanted! I am in your debt. Here is the scroll of Tashania that was promised to you.'
<br><b>Romar Sunto gives you : </b><a href=http://phobos/eq/item.php?id=15678>Spell: Tashania</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=442>Temple Of Sol Ro</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=291>Shadowed Men</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Romar Sunto : </b><a href=http://phobos/eq/item.php?id=10790>Coin of Tash</a>
<br><b>Romar Sunto says </b>'The Coin of Tash. It is of no use to me like this. You must take the coin to Tarn Visilin in High Keep to get it enchanted.'
<br><b>Romar Sunto gives you : </b><a href=http://phobos/eq/item.php?id=10790>Coin of Tash</a>
<br><b>Romar Sunto gives you : </b><a href=http://phobos/eq/item.php?id=18032>Tome of Tesh</a>
</td></tr></table>