<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=14340>Magically Sealed Bag</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18088>Note to Camin</a><li><a href=http://phobos/eq/item.php?id=14341>Staff of the Four</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Solomen says </b>'Ah, I see you have found my study.  This is where I study and scribe the history of magic in Norrath.'
<p><b>You say, </b>'what history'
<br><b>Solomen says </b>'I have worked to chronicle everything from the beginnings of magic to what we consider the modern day of magic.  Solusek Ro has been very generous to those who wield magic in Norrath.  But throughout history there is one thing I have noticed - too much power corrupts the soul.  I have seen and documented that the strongest wizards and those closest to Solusek Ro become corrupted by their power.'
<p><b>You say, </b>'what wizards'
<br><b>Solomen says </b>'Unfortunately, I don't have time to speak of such things right now.  But I could use your help since you are here.  I have here an envelope that I need delivered to one Camin.  You can find him near the wizard tower in the city of Erudin.  He is a sage like myself whose knowledge rivals my own.  Do you [agree] to undertake my task?'
<p><b>You say, </b>'i agree'
<br><b>Solomen says </b>'Here you are, then.  Good luck on your journey.'
<br><b>Solomen gives you : </b><a href=http://phobos/eq/item.php?id=18088>Note to Camin</a>
<p><b>You give Solomen : </b><a href=http://phobos/eq/item.php?id=14340>Magically Sealed Bag</a>
<br><b>Solomen says </b>'You actually did it! I never would have thought that anyone could have truly followed this path. This is a tribute to your intelligence and patience. Here, take this staff and know that you have made Solusek Ro and all the wizards of the world proud this day.'
<br><b>Solomen gives you : </b><a href=http://phobos/eq/item.php?id=14341>Staff of the Four</a>
<br><b>Solomen says </b>'I don't need this.'
<br><b>You receive </b> 10000pp 10000gp 10000sp 10000cp
</td></tr></table>