<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10538>A fungus eye</a><li><a href=http://phobos/eq/item.php?id=10031>Fire Opal</a><li><a href=http://phobos/eq/item.php?id=7331>A shadowed knife</a><li><a href=http://phobos/eq/item.php?id=5103>Shadowed Scythe</a><li><a href=http://phobos/eq/item.php?id=10536>Book of Darkness</a><li><a href=http://phobos/eq/item.php?id=10537>Book of Frost</a><li><a href=http://phobos/eq/item.php?id=10529>Shadowed Book</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=5316>Harvester</a><li><a href=http://phobos/eq/item.php?id=10527>Words of Darkness</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Vurgo says </b>'Welcome! I am Vurgo, follower of Solusek Ro and holder of the [harvester] and the [Words of Darkness].'
<p><b>You say, </b>'what harvester'
<br><b>Vurgo says </b>'I can forge you one, but you will need to bring me the correct [scythe components].'
<p><b>You say, </b>'what scythe components'
<br><b>Vurgo says </b>'The first thing I need is a shadowed scythe from our mortal enemies, the shadowed men.'
<p><b>You say, </b>'what words of darkness'
<br><b>Vurgo says </b>'I can scribe for you the Words of Darkness, but you will need to bring me the correct [word components].'
<p><b>You say, </b>'what word components'
<br><b>Vurgo says </b>'The first thing that I need is a shadowed book from our mortal enemies, the shadowed men.'
<p><b>You give Vurgo : </b><a href=http://phobos/eq/item.php?id=5103>Shadowed Scythe</a>, <a href=http://phobos/eq/item.php?id=10538>A fungus eye</a>, <a href=http://phobos/eq/item.php?id=7331>A shadowed knife</a>, <a href=http://phobos/eq/item.php?id=10031>Fire Opal</a>
<br><b>Vurgo gives you : </b><a href=http://phobos/eq/item.php?id=5316>Harvester</a>
<p><b>You give Vurgo : </b><a href=http://phobos/eq/item.php?id=10529>Shadowed Book</a>, <a href=http://phobos/eq/item.php?id=10537>Book of Frost</a>, <a href=http://phobos/eq/item.php?id=10536>Book of Darkness</a>
<br><b>Vurgo gives you : </b><a href=http://phobos/eq/item.php?id=10527>Words of Darkness</a>
<br><b>Vurgo says </b>'I don't need this.'
<br><b>You receive </b> 10000pp 10000gp 10000sp 10000cp
</td></tr></table>