<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=2318>Firewalker Boots</a><li><a href=http://phobos/eq/item.php?id=10119>Lambent Sapphire</a><li><a href=http://phobos/eq/item.php?id=10561>Rune of the One Eye</a><li><a href=http://phobos/eq/item.php?id=2319>Black Silk Gloves</a><li><a href=http://phobos/eq/item.php?id=10118>Lambent Ruby</a><li><a href=http://phobos/eq/item.php?id=4114>Shin Gauntlets</a><li><a href=http://phobos/eq/item.php?id=4115>Icy Greaves</a><li><a href=http://phobos/eq/item.php?id=10128>Lambent Fire Opal</a><li><a href=http://phobos/eq/item.php?id=4116>Shin Greaves</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=4159>Lambent Boots</a><li><a href=http://phobos/eq/item.php?id=4157>Lambent Gauntlets</a><li><a href=http://phobos/eq/item.php?id=4158>Lambent Greaves</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Walthin Fireweaver says </b>'Greetings, [Your Name]. I am Walthin Fireweaver of the Temple of Solusek Ro. I am the protector of an ancient armor invented by long dead bards of the temple. This armor will help any bard in their journey across Norrath. Are you a bard that would desire to own some of this armor?'
<p><b>You say, </b>'no'
<br><b>Walthin Fireweaver says </b>'Very well.'
<p><b>You say, </b>'yes'
<br><b>Walthin Fireweaver says </b>'Very well. I craft a type of bardic armor that I invented called Lambent Armor. I can craft for you [boots], [gauntlets], and [greaves]. My friend Cryssia Stardreamer will craft for you the other pieces. I require a special kind of lambent stone for each of my armor pieces.  Find my friends Orstorm, Genni, Gardern, and Vilissia within the temple and they will help you create them.'
<p><b>You say, </b>'boots'
<br><b>Walthin Fireweaver says </b>'Alright, I will require some items. Go and get me some Firewalker Boots, a Lambent Sapphire, and the middle piece of the Rune of the One Eye. Return to me with these items and I will craft your boots.'
<p><b>You say, </b>'gauntlets'
<br><b>Walthin Fireweaver says </b>'Alright, I need you to retrieve for me some Black Silk Gloves, a Lambent Ruby, and Shin Gauntlets. Return to me with these and I will craft your gauntlets.'
<p><b>You say, </b>'i want to craft greaves'
<br><b>Walthin Fireweaver says </b>'Very well, return to me with these items and I will craft them. A set of Icy Greaves, a Lambent Fire Opal, and Shin Greaves.'
<p><b>You give Walthin Fireweaver : </b><a href=http://phobos/eq/item.php?id=2318>Firewalker Boots</a>, <a href=http://phobos/eq/item.php?id=10119>Lambent Sapphire</a>, <a href=http://phobos/eq/item.php?id=10561>Rune of the One Eye</a>
<br><b>Walthin Fireweaver says </b>'Excellent. Here are your Lambent Boots.'
<br><b>Walthin Fireweaver gives you : </b><a href=http://phobos/eq/item.php?id=4159>Lambent Boots</a>
<p><b>You give Walthin Fireweaver : </b><a href=http://phobos/eq/item.php?id=2319>Black Silk Gloves</a>, <a href=http://phobos/eq/item.php?id=10118>Lambent Ruby</a>, <a href=http://phobos/eq/item.php?id=4114>Shin Gauntlets</a>
<br><b>Walthin Fireweaver says </b>'Excellent. Here are your Lambent Gauntlets.'
<br><b>Walthin Fireweaver gives you : </b><a href=http://phobos/eq/item.php?id=4157>Lambent Gauntlets</a>
<p><b>You give Walthin Fireweaver : </b><a href=http://phobos/eq/item.php?id=4115>Icy Greaves</a>, <a href=http://phobos/eq/item.php?id=10128>Lambent Fire Opal</a>, <a href=http://phobos/eq/item.php?id=4116>Shin Greaves</a>
<br><b>Walthin Fireweaver says </b>'Excellent. Here are your Lambent Greaves.'
<br><b>Walthin Fireweaver gives you : </b><a href=http://phobos/eq/item.php?id=4158>Lambent Greaves</a>
</td></tr></table>