<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13989>Peacekeeper Token</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13939>Clear Water</a></ul></td><td><p><b>You say, </b>'Hail, Agryn Moonfield'
<br><b>Agryn Moonfield says </b>'Welcome to the Bank of Erudin. I am Agryn, the bank manager. How may I be of service to you?'
<p><b>You say, </b>'I need Vasty Deep Water.'
<br><b>Agryn Moonfield says </b>'You must have been sent by one of the guilds. All you need to do is give me your guild coin and I shall exchange it for the Vasty Deep water.'
<p><b>You give Agryn Moonfield : </b><a href=http://phobos/eq/item.php?id=13989>Peacekeeper Token</a>
<br><b>Agryn Moonfield gives you : </b><a href=http://phobos/eq/item.php?id=13939>Clear Water</a>
<br><b>Agryn Moonfield says </b>'Ah!! A Peacekeeper. I have some Vasty Deep water sitting out already. Here you are. Do not let it fall into the wrong hands.'
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>