<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18727>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13550>Old Used Robe*</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Ghanlin Skyphire says </b>'Hello.'
<p><b>You give Ghanlin Skyphire : </b><a href=http://phobos/eq/item.php?id=18727>A tattered note</a>
<br><b>Ghanlin Skyphire says </b>'Greetings. I am Ghanlin Skyphire, Master Wizard of the Crimson Hands. All of us here have devoted our lives to the studies of the arcane and mystical. Let's get you started. Here's your training robe.  Now, go find Raskena. She'll help train you and give you your first lesson.'
<br><b>Ghanlin Skyphire gives you : </b><a href=http://phobos/eq/item.php?id=13550>Old Used Robe*</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>