<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Josper Kenshed says </b>'Come forward and speak.  What is it you seek within these walls?  Let it be the knowledge of wizardry. for that is what we are.  Only a [servant of wizardry] should be within these walls.'
<p><b>You say, </b>'i am a servant of wizardry'
<br><b>Josper Kenshed says </b>'A servant. you say?  If you be a young apprentice. perhaps you might assist me? I could use you to [collect components].  If you believe yourself to be beyond such things. you may wish to assist me with a [special matter].'
<p><b>You say, </b>'what collect components'
<br><b>Josper Kenshed says </b>'The Crimson Hands have no quarrel with you. but we cannot truly trust you as yet.'
<p><b>You say, </b>'what special matter'
<br><b>Josper Kenshed says </b>'The Crimson Hands have no quarrel with you. but we cannot truly trust you as yet.'
</td></tr></table>