<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18729>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13549>Old Patched Robe*</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=56>Craftkeepers</a><li><a href=http://phobos/eq/faction.php?id=145>High Council of Erudin</a><li><a href=http://phobos/eq/faction.php?id=147>High Guard of Erudin</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=143>Heretics</a></ul></td><td><hr><b>When Lanken Rjarn spawns </b>
<p><b>You say, </b>'Hail'
<br><b>Lanken Rjarn says </b>'I do not have time to speak with thee. I have a problem on my hands. Feel free to speak with any of my trainers.'
<p><b>You say, </b>'problem'
<br><b>Lanken Rjarn says </b>'My problems are of no concern of yours. but if you must know it deals with Nolusia's brother. I can tell you no more. Leave me be.'
<p><b>You give Lanken Rjarn : </b><a href=http://phobos/eq/item.php?id=18729>A tattered note</a>
<br><b>Lanken Rjarn says </b>'Welcome to the Craft Keepers! You have much to learn. and I'm sure you are anxious to get started. Here's your training robe. Go see Nolusia. she'll give you your first lesson.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Lanken Rjarn gives you : </b><a href=http://phobos/eq/item.php?id=13549>Old Patched Robe*</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=56>Craftkeepers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=145>High Council of Erudin</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=143>Heretics</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=147>High Guard of Erudin</a> has gotten better.</font>
</td></tr></table>