<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13128>Bones</a><li><a href=http://phobos/eq/item.php?id=18728>A tattered note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13548>Old Torn Robe*</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=112>Gate Callers</a><li><a href=http://phobos/eq/faction.php?id=147>High Guard of Erudin</a><li><a href=http://phobos/eq/faction.php?id=145>High Council of Erudin</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=143>Heretics</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Markus Jaevins says </b>'Greetings, young one! It is always good to see a new face here in the Palace of Erudin, the perfect city-state, free from [crime].'
<p><b>You say, </b>'crime'
<br><b>Markus Jaevins says </b>'Oh, yes. We here in Erudin have no crime. Actually, it is a very low crime rate. Most of those crimes are committed by the defective brains of [heretics] or inferior, non-Erudite races.'
<p><b>You say, </b>'heretics'
<br><b>Markus Jaevins says </b>'The heretics are our sworn enemies. Their ancient origins are our own, however, they are the mad Erudites who chose the dark side of magic called necromancy. We, the magicians, caught one snooping in the palace just last week. He is now our [prisoner].'
<p><b>You say, </b>'prisoner'
<br><b>Markus Jaevins says </b>'The infidel was memorizing our spells to take to the rest of the heretic scum. He will finally be [purged] today. Could you please go to the cells here in the palace and ask Jail Master Lius to give you the heretic's remains?'
<p><b>You say, </b>'purged'
<br><b>Markus Jaevins says </b>'To be purged is to take all the evil from ones body and set your soul free. Through magical means, the Erudite Cleansers pull the accused's organs out through the mouth. When all is done, you can be assured the body is cleansed of all evil.'
<p><b>You say, </b>'the heretic has escaped'
<br><b>Markus Jaevins says </b>'Escaped!! This is not good. The sentinels will not find him in time. You must find him. When you find him, release his soul and rid his body of evil any way you can. Bring me proof and all will be well.'
<p><b>You give Markus Jaevins : </b><a href=http://phobos/eq/item.php?id=13128>Bones</a>
<br><b>Markus Jaevins says </b>'Welcome. young one! I see you show interest in the circle of magic. Nowhere upon Norrath will you find a greater school than this - the Gatecallers. You shall wear this robe as a sign that you have begun the training of this circle. Remember. the power of the Gatecaller is the power of summoning. Go find Vasile. he will help teach you the basics of summoning. Good luck, friend!'
<br><b>Markus Jaevins gives you : </b><a href=http://phobos/eq/item.php?id=13548>Old Torn Robe*</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give Markus Jaevins : </b><a href=http://phobos/eq/item.php?id=18728>A tattered note</a>
<br><b>Markus Jaevins says </b>'This is fine work, young one. You keep this up and you shall be knighted before long.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=112>Gate Callers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=147>High Guard of Erudin</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=145>High Council of Erudin</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=143>Heretics</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>