<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'My sincerest apologies young adventurer but I do not believe you are yet ready for the tasks I have at hand.'
<p><b>You say, </b>'Hail'
<br><b>Not Found says </b>'My sincerest apologies young adventurer but I do not believe you are yet ready for the tasks I have at hand.'
</td></tr></table>