<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10307>Fire Beetle Eye</a><li><a href=http://phobos/eq/item.php?id=13250>Fire Beetle Leg</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=15288>Spell: Minor Shielding</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Raskena Djor says </b>'Greetings. What brings you to Raskena? Did Ghanlin send you?'
<p><b>You say, </b>'ghanlin'
<br><b>Raskena Djor says </b>'Then let us begin your first task. I require some components for an experiment I have been meaning to conduct. If you could [gather] them for me, I will make sure that you are rewarded.'
<p><b>You say, </b>'gather'
<br><b>Raskena Djor says </b>'In Toxxulia Forest you should be able to find some fire beetles. I require two fire beetle legs and two fire beetle eyes. Once you have collected them, bring them to me for your reward.'
<p><b>You give Raskena Djor : </b><a href=http://phobos/eq/item.php?id=10307>Fire Beetle Eye</a> x2, <a href=http://phobos/eq/item.php?id=13250>Fire Beetle Leg</a> x2
<br><b>Raskena Djor gives you : </b><a href=http://phobos/eq/item.php?id=15288>Spell: Minor Shielding</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Raskena Djor says </b>'You have passed your first task. Nice work. Take this spell as your payment.'
<p><i>This npc will return you any extra items you gave him.</i>
<br><b>Raskena Djor says </b>'What am I supposed to do with these, [Your Name]?'
</td></tr></table>