<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=13126>Vasty Deep Ale</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=115>Gem Choppers</a><li><a href=http://phobos/eq/faction.php?id=210>Merchants of Ak'Anon</a><li><a href=http://phobos/eq/faction.php?id=176>King Ak'Anon</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=71>Dark Reflection</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Shondo Billin says </b>'Oh, Brell!! Help me get out of here. I did nothing wrong!! I did not know you could not take that [tonic] out of the city.'
<p><b>You say, </b>'tonic'
<br><b>Shondo Billin says </b>'Oh, why did I have to try and help that Erudite in Qeynos? He was sick and vomiting and needed something called Erud's Tonic!! Now just because I wanted to help, I am going to be vomiting up my insides!! Oh, Brell!!! GET ME OUT OF HERE!!'
<p><b>You say, </b>'where is the heretic'
<br><b>Shondo Billin says </b>'Why are you asking me about the heretic?! I am going to die! DO YOU HEAR ME?!! Oh, I need a drink. Please... honor a dying man's last request, a bottle of Vasty Deep Ale. If you get me that, I will tell you what I know of the heretic.'
<p><b>You give Shondo Billin : </b><a href=http://phobos/eq/item.php?id=13126>Vasty Deep Ale</a>
<br><b>Shondo Billin says </b>'Gulp.. Gulp.. Aaahhh!!! That hits the spot. All I can tell you is that the heretic's name was E'lial B'rook. He mumbled something about a rendezvous and he would be floating down a river, smooth sailing back to something called Paineel. That's all I know.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=115>Gem Choppers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=210>Merchants of Ak'Anon</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=176>King Ak'Anon</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=71>Dark Reflection</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>