<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Toresian Fhabel says </b>'Welcome. my friend! We are the Craftkeepers. We study the circle of magic called enchantment. What circle do you [study]?'
<p><b>You say, </b>'i study enchantment'
<br><b>Toresian Fhabel says </b>'Then I welcome you into our circle. It is good to see new blood. I have a favor to ask of you. Do you [wish to assist Toresian] or do you not have the time?'
<p><b>You say, </b>'i wish to assist Toresian'
<br><b>Toresian Fhabel says </b>'You are most welcome to the circle of the Craftkeepers. but I require more service before we can discuss such things.'
</td></tr></table>