<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>Warden Lius says </b>'Hail, citizen! This is no place for you. Make sure you keep it that way. We do not need any more [hollow men].'
<p><b>You say, </b>'hollow men'
<br><b>Warden Lius says </b>'There is only one sentence in Erudin, death!! And death by purging is the most common. The insides of the criminal are literally pulled out chunk by chunk through the mouth. Then the hollow man is set adrift to float the seas of Erud's Crossing, his body cleansed of all anarchy.'
<p><b>You say, </b>'give me the heretic's remains'
<br><b>Warden Lius says </b>'I am afraid the heretic prisoner has escaped. There was a skirmish on the palace grounds so I went to assist. When I returned to my post he was gone! I don't know how... he was locked away in the first cell, across from that no-good, thieving gnome, and it is impossible to break the lock with or without magic. We will find him soon. Tell Guildmaster Markus he has escaped.'
</td></tr></table>