<table border=0 width=100%><tr valign=top><td nowrap></td><td><hr><b>When Agnarr the Storm Lord spawns </b>
<hr><b>When Agnarr the Storm Lord is killed </b>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=202367>A_Planar_Projection</a></b> spawns.</font>
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=209108>Karana</a></b> spawns (-1754,-469,2351.2).</font>
</td></tr></table>