<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10170>Evil Eye Lens</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=10171>Staff of the Observers</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=176>King Ak'Anon</a><li><a href=http://phobos/eq/faction.php?id=91>Eldritch Collective</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Brona Frugrin says </b>'Well met, [Your Name]!  What brings you out this way?  Are you interested in becoming an observer?  No, you look like the adventuring type.  The wilds of the Steamfont Mountains is as far as my body goes.  But through my [duties] as an observer, my mind travels the cosmos.'
<p><b>You say, </b>'duties'
<br><b>Brona Frugrin says </b>'Well, I am quite an accomplished enchanter but most of my time now is spent crafting the magical lenses that enable us to see beyond the ceiling of Norrath and into other realms and dimensions.  Say, in your travels have you encountered any [evil eyes]?'
<p><b>You say, </b>'evil eyes'
<br><b>Brona Frugrin says </b>'Evil eyes are dangerous creatures of great magical power.  You will know one if you see one.  I believe that with the lens from an evil eye and some expert tinkering, I could create a device that will enable me to observe the gods themselves in their native planes.  If you were to bring me one of these lenses, the Eldritch Collective would reward you greatly.'
<p><b>You give Brona Frugrin : </b><a href=http://phobos/eq/item.php?id=10170>Evil Eye Lens</a>
<br><b>Brona Frugrin says </b>'This lens is perfect, [Your Name]!  Please, take this staff in return for your services.'
<br><b>Brona Frugrin gives you : </b><a href=http://phobos/eq/item.php?id=10171>Staff of the Observers</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=176>King Ak'Anon</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=91>Eldritch Collective</a> has gotten better.</font>
</td></tr></table>