<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Ennixy Frennor says </b>'Unless you have something to tell me about yourself that I could possibly be interested in, be gone!'
<p><b>You say, </b>'hate be my guide'
<br><b>Ennixy Frennor says </b>'Very well.  I know what you seek.  Find Crusader Swiftmoon and slay him!'
<br><font color=white><b><a href=http://phobos/eq/npc.php?id=56150>Crusader_Swiftmoon</a></b> spawns (1385,-836,-110).</font>
<br><b>Ennixy Frennor says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>