<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=63008>Sealed Ore Samples</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17711>Sealed Sack</a><li><a href=http://phobos/eq/item.php?id=63049>Encased Mnemonic Vapor</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Metallurgist Mirakzin says </b>'Quickly! I need your [help]!'
<p><b>You say, </b>'help'
<br><b>Metallurgist Mirakzin says </b>'I just received a sample of a new ore mined by the pirates of Broken Skull Rock. Unfortunately, it is not pure enough to conduct the needed experiments. I need several Pristine Ore Samples from within the mines. Are you willing to help me in return for a [favor]?'
<p><b>You say, </b>'favor'
<br><b>Metallurgist Mirakzin says </b>'Bah! Don't worry. You'll be rewarded well. Take this Sealed Sack and get three samples. Make sure to combine them. I wouldn't want the samples to oxidize like the last ones.'
<br><b>Metallurgist Mirakzin gives you : </b><a href=http://phobos/eq/item.php?id=17711>Sealed Sack</a>
<p><b>You give Metallurgist Mirakzin : </b><a href=http://phobos/eq/item.php?id=63008>Sealed Ore Samples</a>
<br><b>Metallurgist Mirakzin says </b>'Hmm. It LOOKS like the samples survived. I will, however, have to test them. But you've done well I suppose. Here. Take this as payment.'
<br><b>Metallurgist Mirakzin gives you : </b><a href=http://phobos/eq/item.php?id=63049>Encased Mnemonic Vapor</a>
</td></tr></table>