<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'hail'
<br><b>Yendar Starpyre says </b>'Hail, traveler! I sense you did not simply chance upon my isolation here, but are instead seeking me for something.'
<p><b>You say, </b>'translate'
<br><b>Yendar Starpyre says </b>'Oh, if it is written in Eder Teir'Dal, most likely I can translate it. I will be happy to try, in any case. Let me see it, please.'
<p><b>You say, </b>'what key'
<br><b>Yendar Starpyre says </b>'In the Plane of Hate, where dwell Innoruuk and his minions, there is a tome. This tome is called the Book of Souls.'
<p><b>You say, </b>'book of souls'
<br><b>Yendar Starpyre says </b>'The Book of Souls chronicles all the lives Innoruuk has tainted over the years. It is in the care of the Maestro of Rancor. I can use this tome as a basis for my translation, if you return it and the note to me. An experienced practitioner in the art of non-detection should be able to snatch it from its resting place, don't you think, ?''
<br><font color=green><b>Yendar Starpyre </b>will not accept this item.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>