<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20021>Shackle Key 21</a><li><a href=http://phobos/eq/item.php?id=10351>Brass Earring</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18902>A Torn Drawing</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=170>Keepers of the Art</a><li><a href=http://phobos/eq/faction.php?id=178>King Tearis Thex</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>58014 says </b>'Slavedrivers are just lackeys for the [taskmaster]. He is the real orc in charge.'
<p><b>You say, </b>'taskmaster'
<br><b>58014 says </b>'The taskmaster?? He is that large orc who runs around with that [bronze earring] in his ear.'
<p><b>You say, </b>'what bronze earring'
<br><b>58014 says </b>'Yeah, a bronze earring; He wears it like a newly crowned king. If I ever had that earring I know I would stand a chance at escape.'
<p><b>You give 58014 : </b><a href=http://phobos/eq/item.php?id=20021>Shackle Key 21</a>
<br><b>58014 says </b>'Good work!! I shall be on my way. Farewell my friend!!'
<br><b>You receive </b> 2pp 2gp 2sp
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=170>Keepers of the Art</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=178>King Tearis Thex</a> has gotten better.</font>
<br><b>58014 disappears.</b>
<p><b>You give 58014 : </b><a href=http://phobos/eq/item.php?id=10351>Brass Earring</a>
<br><b>58014 says </b>'You killed the taskmaster?!  Absolutely amazing! The orcs will be fighting among themselves for power now and I can disappear in the commotion. Thanks, friend! Take this for your deeds!'
<br><b>58014 gives you : </b><a href=http://phobos/eq/item.php?id=18902>A Torn Drawing</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>58014 disappears.</b>
<br><b>58014 says </b>'Please!! I need a key with a number 21!!'
</td></tr></table>