<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20016>Shackle Key 16</a><li><a href=http://phobos/eq/item.php?id=10351>Brass Earring</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=18905>A Worn Rune</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=169>Kazon Stormhammer</a><li><a href=http://phobos/eq/faction.php?id=314>Storm Guard</a><li><a href=http://phobos/eq/faction.php?id=220>Miners Guild 628</a><li><a href=http://phobos/eq/faction.php?id=215>Merchants of Kaladim</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>58051 says </b>'Slavedrivers are just lackeys for the [taskmaster]. He is the real orc in charge.'
<p><b>You say, </b>'taskmaster'
<br><b>58051 says </b>'The taskmaster?? He is that large orc who runs around with that [bronze earring] in his ear.'
<p><b>You say, </b>'bronze earring'
<br><b>58051 says </b>'Yeah, a bronze earring; He wears it like a newly crowned king. If I ever had that earring I know I would stand a chance at escape.'
<p><b>You give 58051 : </b><a href=http://phobos/eq/item.php?id=20016>Shackle Key 16</a>
<br><b>58051 says </b>'Good work!! I shall be on my way. Farewell my friend!!'
<br><b>You receive </b> 3gp 5sp
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=169>Kazon Stormhammer</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=314>Storm Guard</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=220>Miners Guild 628</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=215>Merchants of Kaladim</a> has gotten better.</font>
<br><b>58051 disappears.</b>
<p><b>You give 58051 : </b><a href=http://phobos/eq/item.php?id=10351>Brass Earring</a>
<br><b>58051 says </b>'You killed the taskmaster?!  Absolutely amazing! The orcs will be fighting among themselves for power now and I can disappear in the commotion. Thanks, friend! Take this for your deeds!'
<br><b>58051 gives you : </b><a href=http://phobos/eq/item.php?id=18905>A Worn Rune</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>58051 disappears.</b>
<br><b>58051 says </b>'No, no!! I do not need this!! Get me key number 16!!'
</td></tr></table>