<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=10351>Brass Earring</a><li><a href=http://phobos/eq/item.php?id=9307>Shiny Brass Shield</a><li><a href=http://phobos/eq/item.php?id=3301>Dwarven Ringmail Tunic</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13850>Unfinished Blade Mold</a><li><a href=http://phobos/eq/item.php?id=13851>Unfinished Sledge Mold</a><li><a href=http://phobos/eq/item.php?id=6315>Dwarven Mace</a></ul></td><td><p><b>You say, </b>'what ringmail'
<br><b>a dwarven smith says </b>'The king was the last person I heard of who was wearing what sounded like my ringmail. Return it to me and I will reward you with a fine weapon I forged myself.'
<p><b>You give a dwarven smith : </b><a href=http://phobos/eq/item.php?id=10351>Brass Earring</a>
<br><b>a dwarven smith says </b>'Outstanding! If you can kill the taskmaster, you might prove useful in recovering the items the orcs took from me when they caught me out in the Faydarks. Interested in helping me out?'
<br><b>a dwarven smith gives you : </b><a href=http://phobos/eq/item.php?id=13850>Unfinished Blade Mold</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give a dwarven smith : </b><a href=http://phobos/eq/item.php?id=9307>Shiny Brass Shield</a>
<br><b>a dwarven smith says </b>''MY SHIELD!! Excellent, laddie! Next item on the list is my ringmail. Once I have my [ringmail], I am out of here for good. I will finally be able to leave!'
<br><b>a dwarven smith gives you : </b><a href=http://phobos/eq/item.php?id=13851>Unfinished Sledge Mold</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give a dwarven smith : </b><a href=http://phobos/eq/item.php?id=3301>Dwarven Ringmail Tunic</a>
<br><b>a dwarven smith says </b>'AHA!! My ringmail!! My, you ARE a resourceful one! Here is your reward as promised. It is exquisite, if I do say so myself. You might also wish to tell the priest in the cell over there that the king is dead. I am sure he will be pleased to hear that and might even be able to help you further. Farewell! It's time for me to make my escape!'
<br><b>a dwarven smith gives you : </b><a href=http://phobos/eq/item.php?id=6315>Dwarven Mace</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>a dwarven smith disappears.</b>
</td></tr></table>