<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=2301>Bracers of Battle</a><li><a href=http://phobos/eq/item.php?id=6315>Dwarven Mace</a><li><a href=http://phobos/eq/item.php?id=1900>Prayer Cloth of Tunare</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1900>Prayer Cloth of Tunare</a><li><a href=http://phobos/eq/item.php?id=6305>Screaming Mace</a></ul></td><td><p><b>You say, </b>'the king is dead'
<br><b>an elven priest says </b>'Dead you say? My goodness! Did you manage to slay the warlord too? If you provide me with proof of his death, I can enchant the mace the dwarf gave you as payment. But, I will require the proof first!'
<p><b>You give an elven priest : </b><a href=http://phobos/eq/item.php?id=2301>Bracers of Battle</a>
<br><b>an elven priest says </b>'Erollisi be praised! You slew the orc lord! Well, here is a token of my appreciation! Should you wish to have that mace enchanted, just hand me the mace and my token and I shall uphold my end of the bargain!'
<br><b>an elven priest gives you : </b><a href=http://phobos/eq/item.php?id=1900>Prayer Cloth of Tunare</a>
<br><font color=yellow>You gain experience!!</font>
<p><b>You give an elven priest : </b><a href=http://phobos/eq/item.php?id=6315>Dwarven Mace</a>, <a href=http://phobos/eq/item.php?id=1900>Prayer Cloth of Tunare</a>
<br><b>an elven priest says </b>'Have you the other item I require?'
<br><b>an elven priest says </b>'Have you the other item I require?'
<br><b>an elven priest gives you : </b><a href=http://phobos/eq/item.php?id=6305>Screaming Mace</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>