<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=12184>Useless Token</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=67702>Sealed Note</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Kelynn says </b>'What are you doing here?!!  Get out before you find yourself mining for these wretched beasts!'
<p><b>You give Kelynn : </b><a href=http://phobos/eq/item.php?id=12184>Useless Token</a>
<br><b>Kelynn says </b>'You were sent by Geeda!! Here. Take the information. Maybe next you shall earn your [Scout Blade] from Laren. Quickly!! Leave at once!!'
<br><b>Kelynn gives you : </b><a href=http://phobos/eq/item.php?id=67702>Sealed Note</a>
</td></tr></table>