<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=20015>Shackle Key 15</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=176>King Ak'Anon</a><li><a href=http://phobos/eq/faction.php?id=91>Eldritch Collective</a><li><a href=http://phobos/eq/faction.php?id=115>Gem Choppers</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=322>The Dead</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Retlon Brenclog says </b>'Oh my word!! A rescuer!! Hurry! Get me out of these chains!! Go find the orc who has the keys!'
<p><b>You give Retlon Brenclog : </b><a href=http://phobos/eq/item.php?id=20015>Shackle Key 15</a>
<br><b>Retlon Brenclog says </b>'Good work!! I shall be on my way. Farewell my friend!!'
<br><b>You receive </b> 2gp 3sp
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=176>King Ak'Anon</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=91>Eldritch Collective</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=115>Gem Choppers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=322>The Dead</a> has gotten worse.</font>
<br><b>Retlon Brenclog disappears.</b>
<br><b>Retlon Brenclog says </b>'No, no!! I do not need this!! Get me key number 15!!'
</td></tr></table>