<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=29147>Globe of Dancing Flame</a></ul></td><td><hr><b>When 202368 spawns </b>
<p><b>You say, </b>'Hail'
<br><font color=grey><i>That step of the quest sets a global variable.</font></i>
<br><b>202368 gives you : </b><a href=http://phobos/eq/item.php?id=29147>Globe of Dancing Flame</a>
</td></tr></table>