<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Captain Necin says </b>'Hello, [Your Name]. I'm looking for an accomplished soldier to help me carry out a very dangerous mission. If you know of one please have them report to me at once.'
<p><b>You say, </b>'i am a soldier'
<br><b>Captain Necin says </b>'Very well, acquire a chest of valor and fill it with the medals you receive from scouts Husma, Danarin, and Derin. Give me the resulting soldier's chest and I will reveal the details of my mission.'
<p><b>You say, </b>'i am an accomplished soldier'
<br><b>Captain Necin says </b>'Very well, acquire a chest of valor and fill it with the medals you receive from scouts Husman, Danarin, and Derin. Give me the resulting soldier's chest and I will reveal the details of my mission.'
<p><b>You say, </b>'what accomplished soldier'
<br><b>Captain Necin says </b>'Very well, acquire a chest of valor and fill it with the medals you receive from scouts Husman, Danarin, and Derin. Give me the resulting soldier's chest and I will reveal the details of my mission.'
</td></tr></table>