<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=63145>Shard Filled Staff</a><li><a href=http://phobos/eq/item.php?id=63135>Loaded Sample Chest</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=63160>Compartmented Staff</a><li><a href=http://phobos/eq/item.php?id=63157>Prospector`s Sample Chest</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=348>VahShir Crusaders</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Prospector Keykis says </b>'Oh, hello! Are you busy at the moment...I need a [quick favor].'
<p><b>You say, </b>'quick favor'
<br><b>Prospector Keykis says </b>'With your prowess, this task shouldn't be too difficult. A bit time consuming maybe, but worth the effort. I need ore samples from deep within the mountain .. from Acrylia Caverns itself. Now, I'm looking for a specific form of the ore .. pristine shards. The Grimlings of the caverns apparently use these as money so you'll no doubt have an easier time finding the shards on ...ahem...them. But you have to be [careful].'
<p><b>You say, </b>'careful'
<br><b>Prospector Keykis says </b>'Well, no one outside the caverns has actually ever seen a pristine shard. And I'd like to keep it that way. Take this staff and put the samples in it. It has secret compartments in it that should hold the eight shards I'm after. Return it to me and I'll make it well worth your while.'
<br><b>Prospector Keykis gives you : </b><a href=http://phobos/eq/item.php?id=63160>Compartmented Staff</a>
<p><b>You say, </b>'wealth of possibilities'
<br><b>Prospector Keykis says </b>'Yes. I'm sure you already know the value of the ore. With the war against the Grimlings going so well, I've been sent to sample the purity of the remaining ore. Unfortunately, I'm not a warrior and it's almost impossible to retrieve the [samples] I need.'
<p><b>You say, </b>'samples'
<br><b>Prospector Keykis says </b>'I need a range of samples from within the mine. Six should be enough. Actually ... would you mind getting the samples for me? Please? Here's a chest for you to carry them in.'
<br><b>Prospector Keykis gives you : </b><a href=http://phobos/eq/item.php?id=63157>Prospector`s Sample Chest</a>
<p><b>You give Prospector Keykis : </b><a href=http://phobos/eq/item.php?id=63145>Shard Filled Staff</a>
<br><b>Prospector Keykis says </b>'Yes...exactly whay I was after. On the down side, such a pure source of Acrylia will no doubt fuel this war further. But, on the up side, there's a lot of profit to be made. Thank you, [Your Name]. Here, this should give you a taste of the wealth of possibilities. Ha!'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 750pp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=348>VahShir Crusaders</a> has gotten better.</font>
<p><b>You give Prospector Keykis : </b><a href=http://phobos/eq/item.php?id=63135>Loaded Sample Chest</a>
<br><b>Prospector Keykis says </b>'So... perfect! Thank you'
<br><font color=yellow>You gain experience!!</font>
<br><b>You receive </b> 300pp
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=348>VahShir Crusaders</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>