<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Scout Derrin says </b>'Greetings [Your Name], what brings you to the battlegrounds? Looking to raid a grimling camp perhaps?'
<p><b>You say, </b>'i am looking to raid a grimling camp'
<br><b>Scout Derrin says </b>'I can lead a dozen men of my strength on a raid against a well fortified grimling encampment. It's a risky mission, but one that has the potential to yield substantial rewards. If you have the manpower and the courage, give me a glowing acrylia sphere and we'll get started.'
<br><b>Scout Derrin says </b>'I can lead a dozen men of my strength on a raid against a well fortified grimling encampment. It's a risky mission, but one that has the potential to yield substantial rewards. If you have the manpower and the courage, give me a glowing acrylia sphere and we'll get started.'
<p><b>You say, </b>'i am looking to raid'
<br><b>Scout Derrin says </b>'I can lead a dozen men of my strength on a raid against a well fortified grimling encampment. It's a risky mission, but one that has the potential to yield substantial rewards. If you have the manpower and the courage, give me a glowing acrylia sphere and we'll get started.'
</td></tr></table>