<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=24872>Block of Living Granite</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=24877>A Gigantic Kromzek Pick</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a><li><a href=http://phobos/eq/faction.php?id=188>Kromrif</a><li><a href=http://phobos/eq/faction.php?id=179>King Tormax</a><li><a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>#a storm giant architect says </b>'Hmmm, I didn't know refuse could speak. Are you here to annoy me or are you planning on making yourself useful, if the latter is even possible?'
<p><b>You say, </b>'make myself useful'
<br><b>#a storm giant architect says </b>'A feeble creature like yourself is near worthless. If you must insist on serving the mighty Kromzek then go to the caverns of the geonids and bring me four blocks of living granite so that I may perform some tests on its value as a resource in the expansion of Kael.'
<p><b>You give #a storm giant architect : </b><a href=http://phobos/eq/item.php?id=24872>Block of Living Granite</a> x4
<br><b>#a storm giant architect says </b>'So you proved to be of value after all, take this for your work. Don't let it go to your head.'
<br><font color=yellow>You gain experience!!</font>
<br><b>#a storm giant architect gives you : </b><a href=http://phobos/eq/item.php?id=24877>A Gigantic Kromzek Pick</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=179>King Tormax</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>