<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=24873>Kromzek Foreman Helm</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=24868>Crest of the Faerie Dragons</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=344>Tunarean Court</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>#Lord Gossimerwind </b>blinks at you a few times then speaks in a strangely musical, draconic voice. 'You vish to azzizt ze count of ze Tunarean Faerie Dragons?</font>
<p><b>You say, </b>'assist'
<br><b>#Lord Gossimerwind says </b>'I vish to ztop ze Kromzek Foreman from continuing ta deztroy thiz land. Iv you vish to azzizt you can zlay ze Foreman and bring me hiz helm az proof.'
<p><b>You give #Lord Gossimerwind : </b><a href=http://phobos/eq/item.php?id=24873>Kromzek Foreman Helm</a>
<br><b>#Lord Gossimerwind says </b>'Good, ze Foreman iz dead and now we will be left in peazz.  Take diz az a zign of my friendship.'
<br><b>#Lord Gossimerwind gives you : </b><a href=http://phobos/eq/item.php?id=24868>Crest of the Faerie Dragons</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=344>Tunarean Court</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>#Lord Gossimerwind says </b>'I have no use for this, [Your Name].'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>