<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=24876>drixie remains</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=24867>Crest of the Drixie</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=344>Tunarean Court</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>#Lord Prismwing </b>flutters his wings rapidly, sending shimmering dust through the air around you. Although he speaks in high pitched chirps you somehow understand his meaning. Hello [Your Name], I am the Count of the Tunarean Drixies. Are you a friend of the Tunarean Court?</font>
<p><b>You say, </b>'friend'
<br><b>#Lord Prismwing says </b>'I am in need of some help. One of my heralds was sent to deliver a message to the Othmir in the Cobalt Scar some time ago and has not returned. I fear for his safety. If your travels should lead you in that direction please attempt to find news of my missing herald.'
<p><b>You give #Lord Prismwing : </b><a href=http://phobos/eq/item.php?id=24876>drixie remains</a>
<br><b>#Lord Prismwing says </b>'Thank you for your assistance, [Your Name], though I am greatly saddened by the death of my herald.  Truly you are a friend of the Tunarean Court.  Take this crest as a token of my gratitude.'
<br><b>#Lord Prismwing gives you : </b><a href=http://phobos/eq/item.php?id=24867>Crest of the Drixie</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=344>Tunarean Court</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>#Lord Prismwing says </b>'I have no use for this, [Your Name].'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>