<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=30221>Kromzek Surveyor Scope</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=24866>Crest of the Sifaye</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=344>Tunarean Court</a></ul></td><td><p><b>You say, </b>'hail'
<br><font color=green><b>Countess Silveana </b>curtsies politely.</font>
<br><b>Countess Silveana says </b>'Welcome to our home! I am the Countess Silveana of the Tunarean Court.'
<p><b>You say, </b>'court'
<br><b>Countess Silveana says </b>'The Tunarean Court consists of several of Tunare's most blessed creatures. We Sifaye help defend the wakening land from the invading giants to the east and watch for threats from the dragons to the west.'
<p><b>You say, </b>'giants'
<br><b>Countess Silveana says </b>'There is a giant with a strange metal stick that has been the largest threat as of late. He wanders further into our lands than the other with the stick to his eye and squashes my Sifaye when he finds them. If you eliminate him for us I would like to see that stick he carries.'
<p><b>You give Countess Silveana : </b><a href=http://phobos/eq/item.php?id=30221>Kromzek Surveyor Scope</a>
<br><font color=green><b>Countess Silveana </b>claps boisterously.</font>
<br><b>Countess Silveana says </b>'My people are in your debt for putting an end to that monster's murderous squashings! Here is the crest of the Sifaye.'
<br><b>Countess Silveana gives you : </b><a href=http://phobos/eq/item.php?id=24866>Crest of the Sifaye</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=344>Tunarean Court</a> has gotten better.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Countess Silveana says </b>'I have no use for this, [Your Name].'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>