<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=29067>Note to Tunare's Court</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=29623>Eysa's Token</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=344>Tunarean Court</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Eysa Florawhisper says </b>'A pleasure to meet you. I am Countess Eysa Florawhisper of the Tunarean Court. Are you a friend of the court?'
<p><b>You give Eysa Florawhisper : </b><a href=http://phobos/eq/item.php?id=29067>Note to Tunare's Court</a>
<br><font color=green><b>Eysa Florawhisper </b>looks over the report you have given her. She glances up at you with a suspicious eye, as though she doesn't fully trust you. 'I was supposed to meet with Dolvak on this matter, as he is the liason between the shrine and the court. Instead he sent you with this report? I guess I have no choice but to trust you are a friend of the shrine, as the seal bears its mark on this parchment. These papers show the Tunarean Court's progress with the giants so far. Do you have any idea why this report is so important?'</font>
<br><b>Eysa Florawhisper gives you : </b><a href=http://phobos/eq/item.php?id=29623>Eysa's Token</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=344>Tunarean Court</a> has gotten better.</font>
<br><b>Eysa Florawhisper disappears.</b>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>