<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1861>An old worn Talisman</a><li><a href=http://phobos/eq/item.php?id=1864>Teachings of Gkrean</a><li><a href=http://phobos/eq/item.php?id=1865>Head of Staff Sergeant Drioc</a><li><a href=http://phobos/eq/item.php?id=1863>A chipped fang</a></ul></td><td><p><b>You say, </b>'hail'
<p><b>You say, </b>'kardakor.*sent.*me'
<p><b>You say, </b>'talisman.*identif'
<p><b>You say, </b>'rare.*treasures'
<p><b>You give Rolandal : </b><a href=http://phobos/eq/item.php?id=1861>An old worn Talisman</a>, <a href=http://phobos/eq/item.php?id=1864>Teachings of Gkrean</a>, <a href=http://phobos/eq/item.php?id=1865>Head of Staff Sergeant Drioc</a>, <a href=http://phobos/eq/item.php?id=1863>A chipped fang</a>
<p><b>You give Rolandal : </b><a href=http://phobos/eq/item.php?id=1861>An old worn Talisman</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>