<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=30220>Kromrif Laborer Pick</a><li><a href=http://phobos/eq/item.php?id=30222>Kromzek Architect Blueprints</a><li><a href=http://phobos/eq/item.php?id=22855>Pile of Rubble</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=17865>Empty Crest Case</a><li><a href=http://phobos/eq/item.php?id=24860>Bag of Crushed Herbs</a><li><a href=http://phobos/eq/item.php?id=17862>Empty Sulfur Collection Bag</a><li><a href=http://phobos/eq/item.php?id=24865>Crest of the Fauns</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=344>Tunarean Court</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Shamus Aghllsews says </b>'Welcome to my fiefdom, wayward . I am Duke Shamus Aghllsews of the Tunarean Court. Only those who pledge friendship or membership to the Court are allowed sanctuary in the Wakening Lands.'
<p><b>You say, </b>'pledge friendship'
<br><b>Shamus Aghllsews says </b>'You must first prove your intentions to the Tunarean Court. I will permit you to participate in an oath of friendship only after you bring me four picks used by the Kromrif Laborers that are attempting to build into our lands.'
<p><b>You give Shamus Aghllsews : </b><a href=http://phobos/eq/item.php?id=30220>Kromrif Laborer Pick</a> x4
<br><font color=green><b>Shamus Aghllsews </b>grips your hand in his own and recites an oath in an ancient tongue. 'Should you ever seek membership in this court you are required to receive the support of its counts, countesses, barons, and baronesses. Should they deem you worthy you may present their crests to me and with my approval become a citizen of our kingdom. The Kromrif and Kromzek are persistent in their efforts to expand Kael into the forest of Tunare, they are a threat to all houses of the Tunarean Court. A Kromzek architect occasionally visits the building sites. I desire to acquire his blueprints for the expansion of Kael.'</font>
<br><b>Shamus Aghllsews gives you : </b><a href=http://phobos/eq/item.php?id=17865>Empty Crest Case</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=344>Tunarean Court</a> has gotten better.</font>
<p><b>You give Shamus Aghllsews : </b><a href=http://phobos/eq/item.php?id=30222>Kromzek Architect Blueprints</a>
<br><b>Shamus Aghllsews says </b>'You have my gratitude, [Your Name]. With these blueprints we can better prepare the forests defenses against the giant invaders. I have yet another favor to ask of you as well. Fill this empty bag with crystallized sulfur. When mixed with the crushed herbs in the other bag it will create an explosion strong enough to destroy stone. Take the two full bags into Kael Drakkel and plant it into a crate of the kromzeks building supplies.'
<br><b>Shamus Aghllsews gives you : </b><a href=http://phobos/eq/item.php?id=24860>Bag of Crushed Herbs</a>
<br><b>Shamus Aghllsews gives you : </b><a href=http://phobos/eq/item.php?id=17862>Empty Sulfur Collection Bag</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=344>Tunarean Court</a> has gotten better.</font>
<p><b>You give Shamus Aghllsews : </b><a href=http://phobos/eq/item.php?id=22855>Pile of Rubble</a>
<br><b>Shamus Aghllsews says </b>'You have proven yourself to the Fauns of the Tunarean Court. The destruction of the Kromzeks building supplies will slow their progress for some time.'
<br><b>Shamus Aghllsews gives you : </b><a href=http://phobos/eq/item.php?id=24865>Crest of the Fauns</a>
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=344>Tunarean Court</a> has gotten better.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>