<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1724>Field Supplies</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=188>Kromrif</a><li><a href=http://phobos/eq/faction.php?id=189>Kromzek</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a></ul></td><td><p><b>You give Teir-Dal Mercenary : </b><a href=http://phobos/eq/item.php?id=1724>Field Supplies</a>
<br><b>Teir-Dal Mercenary says </b>'Ahh, thank you, [Your Name]. I've been waiting for these supplies for ages.'
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=42>Claws of Veeshan</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=188>Kromrif</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=189>Kromzek</a> has gotten better.</font>
<br><b>You receive </b> 1pp 2gp 5sp 5cp
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>