<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=19840>Smuggled Goods</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=19841>Note to Jarin</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=141>Haven Smugglers</a><li><a href=http://phobos/eq/faction.php?id=191>Lake Recondite Bandits</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=152>House of Fordel</a><li><a href=http://phobos/eq/faction.php?id=153>House of Midst</a><li><a href=http://phobos/eq/faction.php?id=154>House of Stout</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Duke Norfin says </b>'Hello, [Your Name]. My guards seem to find you harmless enough, but I have yet to determine if you are trustworthy. We are always on the lookout for additional hands to assist in our work. Perhaps you are... sympathetic to our situation.'
<p><b>You say, </b>'situation'
<br><b>Duke Norfin says </b>'Those blasted Houses in Shadow Haven. They think they have the right to own all trade going through the Haven. Well it's about time they learn that trade will continue with or without their consent. I know a few people on the Trade Commission who understand the way things really work and they don't care who does the trading as long as they get their cut.'
<p><b>You say, </b>'work'
<br><b>Duke Norfin says </b>'Excellent! We like to keep changing who we use for deliveries. Keeps those dumb Defenders guessing and reduces the chances of goods not reaching their destination.'
<p><b>You say, </b>'destination'
<br><b>Duke Norfin says </b>'I have an important shipment coming from Katta Castellum that's late. The courier who was picking up the shipment should still be there. I'd like for you to go over there and see what the hold up is. Take this note and show it to Jarin Lorean so he knows you're on official business. Report back to me with news. Better yet, return with the shipment if you can.'
<br><b>Duke Norfin gives you : </b><a href=http://phobos/eq/item.php?id=19841>Note to Jarin</a>
<p><b>You give Duke Norfin : </b><a href=http://phobos/eq/item.php?id=19840>Smuggled Goods</a>
<br><b>Duke Norfin says </b>'Excellent work. I'm glad you were able to collect this shipment. The buyers were getting anxious to have it delivered. Come back later and I may have another job for you.'
<br><font color=yellow>You gain experience!!</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=141>Haven Smugglers</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=191>Lake Recondite Bandits</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=152>House of Fordel</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=153>House of Midst</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=154>House of Stout</a> has gotten worse.</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>