<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Master Yurian says </b>'You have a lot of nerve wandering in here.  We'll be watching you carefully.  Try anything and it will be the last thing you ever try.'
<br><b>Master Yurian says </b>'I may be a Magician of small stature. but that belies my not so small power.  If you are worthy I may be able to teach you.'
</td></tr></table>