<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Master Celerik says </b>'You have a lot of nerve wandering in here.  We'll be watching you carefully.  Try anything and it will be the last thing you ever try.'
<br><b>Master Celerik says </b>'I can teach those that follow the Wizardly arts.  If you are not such a one than stop wasting my time.'
</td></tr></table>