<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=9969>Aglthin's Fishing Pole</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=9968>A Smelly Sealed Bag</a><li><a href=http://phobos/eq/item.php?id=13697>Staff of the Abattoir Initiate</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=143>Heretics</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=113>Gate Keepers</a><li><a href=http://phobos/eq/faction.php?id=79>Deepwater Knights</a><li><a href=http://phobos/eq/faction.php?id=56>Craftkeepers</a><li><a href=http://phobos/eq/faction.php?id=60>Crimson Hands</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Antus Shelbra says </b>'Greetings. [Your Name]. You have come to me searching for tasks and tasks I have.  Would you judge yourself an [experienced heretic] or one who has [much to learn]?'
<p><b>You say, </b>'i have much to learn'
<br><b>Antus Shelbra says </b>'Very well. [Your Name].  I do have a task for you.  There is an old and frail Erudite male who now lives in Toxxulia named Aglthin Dasmore.  He has left the ways of Cazic-Thule and no longer practices our craft.  He has been stripped of his power and wealth. so he spends his time fishing by the river.  Our great Lord of Fear has decreed that his life is forfeit.  Slay him. and bring me proof of the deed.'
<p><b>You say, </b>'i am an experienced heretic'
<br><b>Antus Shelbra says </b>'Ah.  Excellent.  I have just the task for you. [Your Name].  In Kerra Ridge. there is a particular cat named Kirran Mirrah that we have been using to gather information about. well. certain aspects of cat society.  He is no longer providing information for us and we have something for him that may encourage him to assist again. Ha!  Hand him this sealed bag for us.  It may just change his point of view. Hahaha!'
<br><b>Antus Shelbra gives you : </b><a href=http://phobos/eq/item.php?id=9968>A Smelly Sealed Bag</a>
<p><b>You give Antus Shelbra : </b><a href=http://phobos/eq/item.php?id=9969>Aglthin's Fishing Pole</a>
<br><b>Antus Shelbra says </b>'Yes, this will do.'
<br><b>Antus Shelbra gives you : </b><a href=http://phobos/eq/item.php?id=13697>Staff of the Abattoir Initiate</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=143>Heretics</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=113>Gate Keepers</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=79>Deepwater Knights</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=56>Craftkeepers</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=60>Crimson Hands</a> has gotten worse.</font>
</td></tr></table>