<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1528>Azzar's Dreadful Hat</a><li><a href=http://phobos/eq/item.php?id=19076>Bear Paw's Pelt</a><li><a href=http://phobos/eq/item.php?id=12096>Gold Thread</a><li><a href=http://phobos/eq/item.php?id=22502>Imbued Amber</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1530>Black Lace Sash</a><li><a href=http://phobos/eq/item.php?id=1529>Dreadful Cap</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=143>Heretics</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=56>Craftkeepers</a><li><a href=http://phobos/eq/faction.php?id=60>Crimson Hands</a><li><a href=http://phobos/eq/faction.php?id=79>Deepwater Knights</a><li><a href=http://phobos/eq/faction.php?id=112>Gate Callers</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Azzar Habbib says </b>'I'm not in any mood for conversation. My favorite hat was torn right from my head by a gigantic bat the other night and I am quite upset.'
<p><b>You say, </b>'what other tasks?'
<br><b>Azzar Habbib says </b>'I will sew you your own personal dreadful cap if you bring me the necessary components. I will need the pelt of a feared beast, some gold thread, and an imbued amber.'
<p><b>You say, </b>'what hat'
<br><b>Azzar Habbib says </b>'It is a marvelous cap sewn from the finest textiles and imbued with the divine power of our lord of fear. Cazic Thule!'
<p><b>You give Azzar Habbib : </b><a href=http://phobos/eq/item.php?id=1528>Azzar's Dreadful Hat</a>
<br><font color=green><b>Azzar Habbib </b>gasps in astonishment</font>
<br><b>Azzar Habbib says </b>'You...you..found my hat!! This is the most I can repay you but perhaps I can reward you further for some [other tasks]?'
<br><b>Azzar Habbib gives you : </b><a href=http://phobos/eq/item.php?id=1530>Black Lace Sash</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=143>Heretics</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=56>Craftkeepers</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=60>Crimson Hands</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=79>Deepwater Knights</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=112>Gate Callers</a> has gotten worse.</font>
<p><b>You give Azzar Habbib : </b><a href=http://phobos/eq/item.php?id=19076>Bear Paw's Pelt</a>, <a href=http://phobos/eq/item.php?id=12096>Gold Thread</a>, <a href=http://phobos/eq/item.php?id=22502>Imbued Amber</a>
<br><b>Azzar Habbib says </b>'Well done [Your Name], here is your new hat wear it with pride'
<br><b>Azzar Habbib gives you : </b><a href=http://phobos/eq/item.php?id=1529>Dreadful Cap</a>
</td></tr></table>