<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18018>Dark Truth Guild Note</a><li><a href=http://phobos/eq/item.php?id=13069>Bat Fur</a><li><a href=http://phobos/eq/item.php?id=13068>Bat Wing</a><li><a href=http://phobos/eq/item.php?id=13067>Snake Fang</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13551>Dirt Soiled Robe*</a><li><a href=http://phobos/eq/item.php?id=15338>Spell: Cavorting Bones</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=302>Skytalons</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=Not_Found></a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Coriante Verisue says </b>'Greetings, young one! There are many tasks to be performed aside from your studies to truly harness the powers passed down to us by our ancestor [Miragul]. The most basic of these tasks is the gathering of bat wings and snake fangs from the yard outside our city. I will reward you for every two bat wings and two snake fangs you bring to me.'
<p><b>You say, </b>'what miragul'
<br><b>Coriante Verisue says </b>'You do not know of Miragul?!! You have more to learn of the heritage of the Dark Truth than at first I thought. Miragul was the first High Man to unlock the secrets of necromancy and is the founder of our city as well as the creator of the treacherous Hole.'
<p><b>You say, </b>'who is miragul'
<br><b>Coriante Verisue says </b>'You do not know of Miragul?!! You have more to learn of the heritage of the Dark Truth than at first I thought. Miragul was the first High Man to unlock the secrets of necromancy and is the founder of our city as well as the creator of the treacherous Hole.'
<p><b>You say, </b>'what about miragul?'
<br><b>Coriante Verisue says </b>'You do not know of Miragul?!! You have more to learn of the heritage of the Dark Truth than at first I thought. Miragul was the first High Man to unlock the secrets of necromancy and is the founder of our city as well as the creator of the treacherous Hole.'
<p><b>You say, </b>'tell me about miraguls'
<br><b>Coriante Verisue says </b>'You do not know of Miragul?!! You have more to learn of the heritage of the Dark Truth than at first I thought. Miragul was the first High Man to unlock the secrets of necromancy and is the founder of our city as well as the creator of the treacherous Hole.'
<br><b>Coriante Verisue says </b>'You do not know of Miragul?!! You have more to learn of the heritage of the Dark Truth than at first I thought. Miragul was the first High Man to unlock the secrets of necromancy and is the founder of our city as well as the creator of the treacherous Hole.'
<p><b>You say, </b>'tell me about miragul'
<br><b>Coriante Verisue says </b>'You do not know of Miragul?!! You have more to learn of the heritage of the Dark Truth than at first I thought. Miragul was the first High Man to unlock the secrets of necromancy and is the founder of our city as well as the creator of the treacherous Hole.'
<p><b>You give Coriante Verisue : </b><a href=http://phobos/eq/item.php?id=18018>Dark Truth Guild Note</a>
<br><b>Coriante Verisue says </b>'You are welcomed into the fold.  Now go out, and prove yourself, young one.  You have much to learn about the Dark Truth.'
<br><b>Coriante Verisue gives you : </b><a href=http://phobos/eq/item.php?id=13551>Dirt Soiled Robe*</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=302>Skytalons</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<br><b>Coriante Verisue says </b>'You must gather all four of the required items in order to receive your reward. I expect more reliability from you in the future.'
<p><b>You give Coriante Verisue : </b><a href=http://phobos/eq/item.php?id=13068>Bat Wing</a>, <a href=http://phobos/eq/item.php?id=13067>Snake Fang</a> (x2), <a href=http://phobos/eq/item.php?id=13069>Bat Fur</a> (x4)
<br><b>Coriante Verisue says </b>'Very good, young acolyte. Maintain your diligence in your duties and you will quickly learn the secrets of the Dark Truth.'
<br><b>Coriante Verisue gives you : </b><a href=http://phobos/eq/item.php?id=15338>Spell: Cavorting Bones</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=302>Skytalons</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=Not_Found></a> has gotten worse.</font>
<br><b>Coriante Verisue says </b>'You must gather all four of the required items in order to receive your reward. I expect more reliability from you in the future.'
</td></tr></table>