<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=14041>A Rolled Up Note</a><li><a href=http://phobos/eq/item.php?id=12998>Rolled up Note</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Davorre Bloodthorn says </b>'Greetings.  Perhaps within that husk you call a body there is some worth?  Are you [experienced] in your craft, young one, or are you a [neonate]?'
<p><b>You say, </b>'i am neonate'
<br><b>Davorre Bloodthorn says </b>'Well then, child. I may still have a task for you.  Will you [make use of your pathetic cowardice], then, eh?'
<p><b>You say, </b>'i want to make use of my pathetic cowardice'
<br><b>Davorre Bloodthorn says </b>'I see.  This will not be the first time for you, I am sure.  Take this list to Auhrik Siet'ka.  His writing has become illegible in his old age, but he shall clarify what it is he needs you to do.  Do as he says, child, and perhaps you will prove yourself a bit more worthy than the rotting flesh he will most likely have you return to him.'
<br><b>Davorre Bloodthorn gives you : </b><a href=http://phobos/eq/item.php?id=14041>A Rolled Up Note</a>
<p><b>You say, </b>'i will make use of my pathetic cowardice'
<br><b>Davorre Bloodthorn says </b>'I see.  This will not be the first time for you, I am sure.  Take this list to Auhrik Siet'ka.  His writing has become illegible in his old age, but he shall clarify what it is he needs you to do.  Do as he says, child, and perhaps you will prove yourself a bit more worthy than the rotting flesh he will most likely have you return to him.'
<br><b>Davorre Bloodthorn gives you : </b><a href=http://phobos/eq/item.php?id=14041>A Rolled Up Note</a>
<p><b>You say, </b>'i am experienced'
<br><b>Davorre Bloodthorn says </b>'Ahhhh, a youth doth approach me with such confidence!  That is to be commended in and of itself.  Ordinarily, I would turn you away without a second glance, but perhaps you can be of some use.  Tell me, child, are you [willing to assist] me in a small, yet important, task?'
<p><b>You say, </b>'i am willing to assist'
<br><b>Davorre Bloodthorn says </b>'Good, child.  Deliver this note to Veisha Fathomwalker.  You shall find her patrolling the outer regions of Toxxulia Forest.  I trust that you will keep your eyes to yourself in this matter.  Now go, and please travel within the veil of night, so you will not be seen by those whose minds are still clouded with delusions of Erudin's grandeur.'
<br><b>Davorre Bloodthorn gives you : </b><a href=http://phobos/eq/item.php?id=12998>Rolled up Note</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>