<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Dzan Amo says </b>'Welcome to the Tabernacle of Terror. Perhaps you can control your fear long enough to be of [service] to us.'
<p><b>You say, </b>'what service'
<br><b>Dzan Amo says </b>'I need some things fetched from the creatures just outside our city for some ritual experimentation. Bring me two tufts of bat fur and two fire beetle legs and I will school you in the ways of terror.'
</td></tr></table>