<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Evus Doracmal says </b>'Good day. [Your Name]!  Have you visited Taria already? Taria does indeed make some of the finest statuettes in all the land.  I fear. though. that she has lost her faith.  She used to make idols depicting our Lord of Fear.  Now she dabbles in the creation of [other idols]!'
<p><b>You say, </b>'what other idols'
<br><b>Evus Doracmal says </b>'Well. just the other day. she was commissioned to create a representation of Tunare for Iva down at the Bakery.  I've always known that Iva was a bit odd. but that is just downright strange!'
</td></tr></table>