<table border=0 width=100%><tr valign=top><td nowrap><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=6378>Bone Crafted Key</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Guard Lecknar says </b>'Uggg.  You needz [keyz]?  Rrrrrrr.'
<p><b>You say, </b>'keyz'
<br><b>Guard Lecknar says </b>'Uggggg.  Take dis keyz.'
<br><b>Guard Lecknar gives you : </b><a href=http://phobos/eq/item.php?id=6378>Bone Crafted Key</a>
</td></tr></table>