<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1774>Envelope with dust sample</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1775>Heretic's Report</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Keletha Nightweaver says </b>'Hello. [Your Name].  Interested in the art of research?  I have several tomes which may aid you in such a pursuit.'
<p><b>You give Keletha Nightweaver : </b><a href=http://phobos/eq/item.php?id=1774>Envelope with dust sample</a>
<br><font color=green><b>Keletha Nightweaver </b>takes the note, dumps the dust into her hand and examines it for a moment. She looks up and chuckles</font>
<br><b>Keletha Nightweaver says </b>'It's amuzing how one of our Royal Guards cannot identify this substance. Do you feel how it's slightly cooler than other metals? It's called Permafrost Iron, also known as Cold Iron to laymen. Miragul wrote of it's properties in his memoirs. There are much better metals at our disposal now, so it's use is rare except in more primitive cultures. Here is my report.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Keletha Nightweaver gives you : </b><a href=http://phobos/eq/item.php?id=1775>Heretic's Report</a>
<br><b>Keletha Nightweaver says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>