<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=item1></a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13573>Blood Splattered Tunic</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Mandaril Dark Knife says </b>'Desist in your prattle.  If you want idle chitchat. talk to someone else.'
<p><b>You give Mandaril Dark Knife : </b><a href=http://phobos/eq/item.php?id=18017>Fell Blade Guild Note</a>
<br><b>Mandaril Dark Knife says </b>'You are welcomed into the fold. Now go out. and prove yourself. young one. You have much to learn about the Dark Truth.'
<br><b>Mandaril Dark Knife gives you : </b><a href=http://phobos/eq/item.php?id=13573>Blood Splattered Tunic</a>
<br><font color=yellow>You gain experience!!</font>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>