<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Miadera Shadowfyre says </b>'Ahhhahahaha! The terror that lays over this city like a blanket tingles my bones with vigor. I seek a fellow apostle of Cazic-Thule to assist me in the [summoning of Terror].'
<p><b>You say, </b>'what summoning of terror'
<br><b>Miadera Shadowfyre says </b>'Ahhhahahaha! The terror that lays over this city like a blanket tingles my bones with vigor. I seek a fellow apostle of Cazic-Thule to assist me in the [summoning of Terror].'
<p><b>You say, </b>'i want to assist you in the summoning of terror'
<br><b>Miadera Shadowfyre says </b>'Ahhhahahaha! The terror that lays over this city like a blanket tingles my bones with vigor. I seek a fellow apostle of Cazic-Thule to assist me in the [summoning of Terror].'
<p><b>You say, </b>'i want to assist you in the summoning of fright'
<br><b>Miadera Shadowfyre says </b>'Ahhhahahaha! The terror that lays over this city like a blanket tingles my bones with vigor. I seek a fellow apostle of Cazic-Thule to assist me in the [summoning of Terror].'
</td></tr></table>