<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=7107>Rotting Femur</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=7106>Noclin's Femur</a></ul><b>Factions raised :</b><ul><li><a href=http://phobos/eq/faction.php?id=143>Heretics</a></ul><b>Factions lowered :</b><ul><li><a href=http://phobos/eq/faction.php?id=79>Deepwater Knights</a><li><a href=http://phobos/eq/faction.php?id=112>Gate Callers</a><li><a href=http://phobos/eq/faction.php?id=56>Craftkeepers</a><li><a href=http://phobos/eq/faction.php?id=60>Crimson Hands</a></ul></td><td><p><b>You say, </b>'hail'
<br><b>Noclin Saah says </b>'Hail to yourself fool. Leave me be. I have [matters of importance] to ponder.'
<p><b>You say, </b>'matters of importance'
<br><b>Noclin Saah says </b>'If you are so greatly interested in my affairs then so be it. I have lost my skeleten servant. He now wanders the yard, taking his pain out on the new apprentices of our guild. I cannot return to my guild without ridding the yard of that menace for my mistake will cost me dearly if it is brought to the attention of my masters. Hrm. Perhaps you could destroy my pet for me and bring me proof of his removal. If you do I may even grace you with a [reward].'
<p><b>You say, </b>'reward'
<br><b>Noclin Saah says </b>'Speak not of reward when you have not even finished this simple task! Now leave me be.'
<p><b>You give Noclin Saah : </b><a href=http://phobos/eq/item.php?id=7107>Rotting Femur</a>
<br><b>Noclin Saah says </b>'Ah! You found him and obviously removed his presence from the yard. You have my thanks, small as it is for such a menial task. Here. Keep this worthless bit of bone for your labors.'
<br><b>Noclin Saah gives you : </b><a href=http://phobos/eq/item.php?id=7106>Noclin's Femur</a>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=143>Heretics</a> has gotten better.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=79>Deepwater Knights</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=112>Gate Callers</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=56>Craftkeepers</a> has gotten worse.</font>
<br><font color=red>Your faction with <a href=http://phobos/eq/faction.php?id=60>Crimson Hands</a> has gotten worse.</font>
<br><font color=yellow>You gain experience!!</font>
<br><b>Noclin Saah says </b>'I have no need for this item [Your Name], you can have it back.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>