<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Pardas Nalue says </b>'Oh. hello there. [Your Name]!  I have been absolutely slaving all day to choose a new [advertisement] for my wonderful store here.  Care to hear what I have?'
<p><b>You say, </b>'what advertisement?'
<br><b>Pardas Nalue says </b>'Excellent!  Here goes.  Come to Pardas Nalue's Sinfully Handsome Tailor!  You can get everything you need to be just as good looking as Pardas.  Well. almost everything!  So. do you like it?'
<p><b>You say, </b>'Yes, I like it'
<br><b>Pardas Nalue says </b>'I just knew you would!  Come on folks. let's watch the money just come pouring in!  Isn't this absolutely fabulous?!'
<p><b>You say, </b>'yes, its absolutely fabulous'
<br><b>Pardas Nalue says </b>'I just knew you would!  Come on folks. let's watch the money just come pouring in!  Isn't this absolutely fabulous?!'
</td></tr></table>