<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1773>Large Empty Crate</a><li><a href=http://phobos/eq/item.php?id=1775>Heretic's Report</a><li><a href=http://phobos/eq/item.php?id=1776>Crate full of Ore</a><li><a href=http://phobos/eq/item.php?id=1777>Courier's Head</a><li><a href=http://phobos/eq/item.php?id=18174>Sealed Letter</a><li><a href=http://phobos/eq/item.php?id=1778>Supplier's Head</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=1774>Envelope with dust sample</a><li><a href=http://phobos/eq/item.php?id=1764>Leggings of Ridossan</a></ul></td><td><p><b>You say, </b>'audience'
<br><b>Royal Guard Sheltuin says </b>'The Overlord is not seeing anyone at this time. however. I may have work for you. You seem to have some experience with the kobold annoyance in the region. Are you [interested]. [Your Name]?'
<p><b>You say, </b>'i am interested'
<br><b>Royal Guard Sheltuin says </b>'Then I shall give you a task. I assume you are aware of the kobold lair nearby. Many of our adventurous knights and priests crusade to destroy those pests so seeing many Erudites frequent the area is normal. However. it is not normal to see someone carry large crates into the lair and return empty handed. This person's movements also show he is attempting to remain unseen.....the [fool].'
<p><b>You say, </b>'what fool'
<br><b>Royal Guard Sheltuin says </b>'Whoever it is. obviously is not an Erudite. even though he appears to be. Only an outsider would take us to be such idiots as to fall for their pitiful attempt at disguise. Or perhaps....well. never mind that. I want you to enter the kobold lair and find these crates. Return one to me and we'll decide what to do from there.'
<p><b>You give Royal Guard Sheltuin : </b><a href=http://phobos/eq/item.php?id=1773>Large Empty Crate</a>
<br><b>Royal Guard Sheltuin says </b>'Hmmm. Very odd. The dust in the crate implies some sort of stone was transported in it. Perhaps our brothers of the Arcane will be able to find out where this dust came from and what it?s used for. Take this dust sample and note to Keletha Nightweaver. She will examine the dust and send you back with a report. Make haste.'
<br><b>Royal Guard Sheltuin gives you : </b><a href=http://phobos/eq/item.php?id=1774>Envelope with dust sample</a>
<br><font color=yellow>You gain experience!!</font>
<br><b>Royal Guard Sheltuin says </b>'I don't need this.'
<p><b>You give Royal Guard Sheltuin : </b><a href=http://phobos/eq/item.php?id=1775>Heretic's Report</a>
<br><font color=green><b>Royal Guard Sheltuin </b>'s eyes redden with intense anger after reading the report. When he speaks, his voice is suprisingly calm and measured.</font>
<br><b>Royal Guard Sheltuin says </b>''Listen close . When you leave this building, you will find the courier who is bringing the ore. You will kill him, and collect his head and a box of the ore. You will then find the supplier, and collect his head and any other information you find on him. Bring me these four things and you will be rewarded. Do not fail.'
<br><font color=yellow>You gain experience!!</font>
<br><b>Royal Guard Sheltuin says </b>'I don't need this.'
<p><b>You give Royal Guard Sheltuin : </b><a href=http://phobos/eq/item.php?id=1776>Crate full of Ore</a>, <a href=http://phobos/eq/item.php?id=1777>Courier's Head</a>, <a href=http://phobos/eq/item.php?id=18174>Sealed Letter</a>, <a href=http://phobos/eq/item.php?id=1778>Supplier's Head</a>
<br><b>Royal Guard Sheltuin says </b>''Honestly [Your Name], I thought you would not return. Such strength and intelligence in a Knight of Fear I have not seen for quite some time. Wear this in pride of the ancient Ridossan. Perhaps when you are ready, i will give you a more [important task]. This conspiracy must be stopped.''
<br><font color=yellow>You gain experience!!</font>
<br><b>Royal Guard Sheltuin gives you : </b><a href=http://phobos/eq/item.php?id=1764>Leggings of Ridossan</a>
<br><b>Royal Guard Sheltuin says </b>'I don't need this.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>