<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=1761>Kobold Molar</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Royal Guard Lilkus says </b>'You tread upon sacred ground, . None may go further unless they [have business with the Overlord], or, if you're looking to gain favor with the heretics and need a little coin, I have a [job] for you.'
<p><b>You say, </b>'business'
<br><b>Royal Guard Lilkus says </b>'The Overlord only sees those he calls forward. If you have a summons from him, I will escort you and announce your arrival. If not, then forget whatever business you may have had here. If you wish an audience, then go speak to Sheltian below. He may be able to help you.....if you help him.'
<p><b>You say, </b>'job'
<br><b>Royal Guard Lilkus says </b>'There are many campaigns we administer from within our city, Paineel. Some of these campaigns are threatened or hindered by annoyances. One of these annoyances are the kobolds that live in the filth of a cave not far from here. Find that lair and kill as many of these beasts as you can. For every kobold molar you return, you shall be rewarded.'
<p><b>You give Royal Guard Lilkus : </b><a href=http://phobos/eq/item.php?id=1761>Kobold Molar</a>
<p><b>You give Royal Guard Lilkus : </b><a href=http://phobos/eq/item.php?id=1761>Kobold Molar</a>
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>