<table border=0 width=100%><tr valign=top><td nowrap><b>Quest items:</b><ul><li><a href=http://phobos/eq/item.php?id=18019>Harbingers of Fear Guild Note</a></ul><b>Rewards :</b><ul><li><a href=http://phobos/eq/item.php?id=13573>Blood Splattered Tunic</a></ul></td><td><p><b>You say, </b>'Hail'
<br><b>Sern Adolia says </b>'I hope you have a good reason for disturbing my contemplations. Perhaps you [seek the knowledge] of those who meditate within this Temple of Fear?'
<p><b>You say, </b>'assist'
<br><b>Sern Adolia says </b>'In order to summon the avatar of Fright. I require some special components for the ritual. Fetch me the flesh of a zombie. the dust used in the process of mummification. [charred bone chips]. and a [vial of Tunare's Breath].'
<p><b>You say, </b>'chips'
<br><b>Sern Adolia says </b>'Some time ago a necromancer by the name of Obretl was sent to slay Rathmana Allin and his abomination of an adopted son. Ortallius. Obretl failed in his task and now haunts a small ruin in the desert of Ro cursed by Solusek to wallow in his failure in the form of a burning skeleton. Slay Obretl to free him from his pathetic existence and gather his charred remains.'
<p><b>You say, </b>'vial'
<br><b>Sern Adolia says </b>'Tunare's Breath is a life-giving potion created by the Fier'Dal Soldiers of Tunare. Seek out the druid Kalayia who is known to wander the Faydarks in search of reagents for potions. Procure from her a vial of Tunare's Breath. Shed her blood if need be.'
<p><b>You give Sern Adolia : </b><a href=http://phobos/eq/item.php?id=18019>Harbingers of Fear Guild Note</a>
<br><b>Sern Adolia says </b>'You are welcomed into the fold. Now go out. and prove yourself. young one. You have much to learn about the Dark Truth.'
<br><b>Sern Adolia gives you : </b><a href=http://phobos/eq/item.php?id=13573>Blood Splattered Tunic</a>
<br><font color=yellow>You gain experience!!</font>
</td></tr></table>