<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Shevra Kollintar says </b>'Unless you intend to [make yourself useful]. do not bother me.  I await the return of our Lord. Cazic-Thule.  He comes. and I shall be the first to greet Him.  I will train you. if need be. for He looks upon those who aid Him kindly.  If you are not here for training. return to your meditations or bother someone else.'
<p><b>You say, </b>'i want to make myself useful'
<br><b>Shevra Kollintar says </b>'One of our spies has reported a sighting of Malik Zaren. a courier of [the High Council].  He was seen resting at an inn called 'Golden Roosters' in High Pass Hold and is en route to Erudin Palace. He may be carrying a message containing information of great value to us.  Hunt him down and return to me with the letter he carries. I will reward you for this task.'
<p><b>You say, </b>'what high council'
<br><b>Shevra Kollintar says </b>'The High Council is the governing board of Erudin. our sworn enemies.  Beware of these types. they will not look upon you warmly.'
<p><b>You say, </b>'I intend to make myself useful'
<br><b>Shevra Kollintar says </b>'One of our spies has reported a sighting of Malik Zaren. a courier of [the High Council].  He was seen resting at an inn called 'Golden Roosters' in High Pass Hold and is en route to Erudin Palace. He may be carrying a message containing information of great value to us.  Hunt him down and return to me with the letter he carries. I will reward you for this task.'
<p><b>You say, </b>'i wish to make myself usefull'
<br><b>Shevra Kollintar says </b>'One of our spies has reported a sighting of Malik Zaren. a courier of [the High Council].  He was seen resting at an inn called 'Golden Roosters' in High Pass Hold and is en route to Erudin Palace. He may be carrying a message containing information of great value to us.  Hunt him down and return to me with the letter he carries. I will reward you for this task.'
<p><i>This npc will return you any extra items you gave him.</i>
</td></tr></table>