<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Taria Clayspinner says </b>'Hello. [Your Name].  I make the finest statuettes in all the land.  Each one depicts a power on Norrath.  I have some of the most realistic and lifelike statues.  I only take [special orders] as they are rather time-consuming to make.'
<p><b>You say, </b>'what special orders'
<br><b>Taria Clayspinner says </b>'Well. if you must know. many priests and devout worshipers of Cazic-Thule purchase my statues and pray over them.  I have made many other statuettes of the gods just to practice. on the off chance that a worshiper of another faith might care to order one from me.'
</td></tr></table>