<table border=0 width=100%><tr valign=top><td nowrap></td><td><p><b>You say, </b>'Hail'
<br><b>Yvonne Ani says </b>'Welcome to my shop. [Your Name].  Feel free to purchase whatever you need.  I am sure that I can fill those needs. as [the Seekers of the Dark Truth] generally keep me stocked and on my toes.'
<p><b>You say, </b>'who are the seekers of the dark truth'
<br><b>Yvonne Ani says </b>'Ah. so you wish to know about the Seekers? They are the guild of necromancers here in Paineel.  They are by far the most knowledgeable in the dark arts of all the known world.  They purchase a good many [herbs] from me.'
<p><b>You say, </b>'what herbs'
<br><b>Yvonne Ani says </b>'The herbs the necromancers use typically have properties useful for the preservation of dead flesh.  Who knows what they use them for?'
</td></tr></table>